#include "..\headers\define.h"
//---------------------

#define NAME                            SCRIPT_HCBoss
#define TOWN_REP_VAR                    GVAR_TOWN_REP_HERMOSILLO  // привязка к репутации (-1, если не нужно)

#define NUM_TEAM                        TEAM_HERMO_FORT       // группа, к которой принадлежит персонаж (-1 если нужно оставить Team, заданный в редакторе)
#define NUM_AI                          AI_HERMO_GENERAL      // AI персонажа (-1 если нужно оставить AI, заданный в редакторе)
#define KILL_SLAVA                      (SLAVA_KILL_BAD*5)    // слава за убийство этого персонажа (SLAVA_KILL_GOOD, SLAVA_KILL_BAD, SLAVA_KILL_NEITRAL, SLAVA_KILL_CHILD)
#define KILL_TOWN_REP                   REP_KILL_CRITICAL     // репутация за убийство этого персонажа (REP_KILL_GOOD, REP_KILL_NEITRAL, REP_KILL_BAD, REP_KILL_CHILD, REP_KILL_CRITICAL)
#define KILL_FRAC_REP                   FRAC_NON              // принадлежность определенной фракции (-1, если не нужно)

#define FLAG_STEAL                      100 // Нижний порог навыка для кражи (для торговцев 200, для животных 300)
#define FLAG_ALCOHOL                    1  // Примет ли алкоголь от ГГ: 0 - принимает, 1 - не принимает
#define FLAG_FOOD                       1  // Примет ли пищу от ГГ: 0 - принимает, 1 - не принимает

//---------------------

procedure start;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure critter_p_proc;
procedure use_obj_on_p_proc;
procedure use_skill_on_p_proc;
procedure pickup_p_proc;
procedure combat_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure talk_p_proc;

procedure Node998;
procedure Node999;
procedure NodeStartDialog;
procedure NodeFstDialog;
procedure NodeFstDialog2;
procedure NodeFstDialog3;
procedure NodeFstDialog4;
procedure NodeSndDialog;

procedure NodeFstDialog2E;
procedure NodeFstDialog3E;
procedure NodeFstDialog4E;

//---------------------

//#define LVAR_Flag_A                     (6) // is responsible for ...

//---------------------

// modified to use Espanol_Trait, but still honor original game intention - cambragol

procedure start begin
end

procedure map_enter_p_proc begin
   if (is_loading_game == false) then begin
       set_start_home
   end
end

procedure timed_event_p_proc begin
   // Timer number 1 is reserved for character movement around the location
   // Timer number 2 is reserved for pop-up dialogue
   if (fixed_param == 1) then begin
       timer_move_to_home
   end
   if (fixed_param == 2) then begin
       //timer_float_reply(110,119)
   end
   if (fixed_param == 3) then begin
       dude_teleport_map(0,0,MAP_HERMO_RANCHO,1);
   end
end

procedure critter_p_proc begin
   set_critter_options(0,0) //attack condition (0 personal feud, 1 clan feud, 2 always), turn to GG
end

procedure use_skill_on_p_proc begin
   skillUseSteal
   skillUseFAid
end

procedure pickup_p_proc begin
   pickupProcCritter
end

procedure use_obj_on_p_proc begin
   UsedItemToCrit_Proc
end

procedure combat_p_proc begin
   effectAttak(0,0,2,2,2) //poisoning min, radiation min, leg injury %, arm injury %, eye injury %
end

procedure damage_p_proc begin
   set_damage_dude
end

procedure destroy_p_proc begin
   set_global_var(GVAR_HERMO_STATUS_BOSS,-1);
   if (source_obj == dude_obj) then begin
   set_global_var(GVAR_HERMO_DUDE_ALARM,2);
   end
   kill_critter_opt
end

procedure talk_p_proc begin
   if town_rep_is_hated then begin
      if DudeTraitHas(TRAIT_espanol) then begin
         floater(self_obj,103,COLOR_MSG_RED);
      end
      else begin
         floater(self_obj,102,COLOR_MSG_RED);
      end
   end
   else begin
   setReaction(0) // Attitude towards the main character (1 - positive character, -1 negative, 0 neutral)
   dialog_proc(0,0,NodeStartDialog,-1,-1)
   end
end

procedure Node998 begin
   set_global_var(GVAR_HERMO_DUDE_ALARM,2);
   set_REP(-100)
   setNodeCombat;
end

procedure Node999 begin
end

procedure NodeStartDialog begin
   if (bitDialog(bit_1) == 0) then begin
   call NodeFstDialog;
   end
   else begin
   call NodeSndDialog;
   end
   //!!! If the dialogue is successful, set - set_global_var(GVAR_HERMO_DUDE_ALARM,1);
end

//--- FIRST DIALOGUE

procedure NodeFstDialog begin
   bitDialogExp(bit_1,100)
   if DudeTraitHas(TRAIT_espanol) then begin
      Reply(300)
      NAnswerSkill(306,4,NodeFstDialog3E,SKILL_CONVERSANT,100,302,NodeFstDialog2E)
      BAnswer(301,1,Node998)
   end
   else begin
      Reply(200)
      NAnswerSkill(206,4,NodeFstDialog3,SKILL_CONVERSANT,100,202,NodeFstDialog2)
      BAnswer(201,0,Node998)
   end
end

procedure NodeFstDialog2 begin
   zReply(203)
   BAnswer(204,0,Node998)
   NAnswer(205,0,Node998)
end

procedure NodeFstDialog3 begin
   zReply(207)
   NAnswer(208,0,NodeFstDialog4)
   BAnswer(209,0,Node998)
end

procedure NodeFstDialog4 begin
   bitDialogExp(bit_2,250)
   rm_timer_event(self_obj);
   add_timer_event(self_obj, 2, 3);
   call Node999;
end

//--- REPEAT DIALOGUE

procedure NodeSndDialog begin
   if DudeTraitHas(TRAIT_espanol) then begin
      zReply(310)
      BAnswer(312,0,Node998)
      BAnswer(311,0,Node998)
   end
   else begin
      zReply(210)
      BAnswer(212,0,Node998)
      BAnswer(211,0,Node998)
   end
end

// Espanol nodes

procedure NodeFstDialog2E begin
   Reply(303)
   BAnswer(304,1,Node998)
   NAnswer(305,1,Node998)
end

procedure NodeFstDialog3E begin
   zReply(307)
   NAnswer(308,1,NodeFstDialog4E)
   BAnswer(309,1,Node998)
end

procedure NodeFstDialog4E begin
   bitDialogExp(bit_2,250)
   rm_timer_event(self_obj);
   add_timer_event(self_obj, 2, 3);
   call Node999;
end
