#include "..\headers\define.h"
#include "..\headers\dayglow.h"
#define NAME                    SCRIPT_YSEnd

procedure start;
procedure map_enter_p_proc;
procedure description_p_proc;
procedure timed_event_p_proc;
procedure use_p_proc;
procedure use_skill_on_p_proc;
procedure use_obj_on_p_proc;
procedure talk_p_proc;
procedure Node999;
procedure NodeDialog;
procedure NodeDialog2;
procedure NodeDialog3;

variable itemRemoveCheck;



procedure start begin
end

procedure map_enter_p_proc begin
   if (is_loading_game == false) then begin
       set_obj_visibility(self_obj, 0);
       if (gvar_bit(GVAR_DAYGLOW_STATUS_CARAVAN, bit_20) == 0) then begin
       set_obj_visibility(self_obj, 1);
       end
       if (getQuest(GVAR_GAME_DLC_1) != qStart) then begin
       set_obj_visibility(self_obj, 1);
       end
   end
end

procedure description_p_proc begin
   script_overrides;
   if ((map_var(MVAR_DIEGOSTART_FAIL) != 0) and (cur_map_index == MAP_DAYGLOW_TIJUANA)) then begin
   display_mstr(101);
   end
   else begin
   display_mstr(100);
   end
end

#define removeQstItems(pid)         if (item_amnt(dude_obj,pid)>0) then begin \
                                    item_remove(dude_obj,pid,1) \
                                    itemRemoveCheck += 1; \
                                    end \

procedure timed_event_p_proc begin
   if (fixed_param == 1) then begin
       if (cur_map_index == MAP_DAYGLOW_START_POINT) then begin
       setQuest(GVAR_DAYGLOW_VISITED, qStart);
       dude_teleport_map(1,1,MAP_DAYGLOW_TIJUANA,(2*24)+random(1,23)); // время пути синхронизировать с SCRIPT_YCStart
       end
       else begin
       setQuest(GVAR_GAME_DLC_1, qEnd);
       setQuest(GVAR_DAYGLOW_VISITED, qEnd);

       itemRemoveCheck := 0;
       removeQstItems(PID_RELICT_DAYGLOW)

       removeQstItems(PID_Q_DAYGLOW_GUITAR)
       removeQstItems(PID_Q_DAYGLOW_GHOULBODY)
       removeQstItems(PID_Q_DAYGLOW_BORDERBADGE_A)
       removeQstItems(PID_Q_DAYGLOW_BORDERBADGE_B)
       removeQstItems(PID_Q_DAYGLOW_DUM_PLAN)

       removeQstItems(PID_Q_DAYGLOW_HOLO_GUSTAVO)
       removeQstItems(PID_Q_DAYGLOW_TRAIL_DETALS_A)
       removeQstItems(PID_Q_DAYGLOW_TRAIL_DETALS_B)
       removeQstItems(PID_Q_DAYGLOW_PATRUL_CODES)
       removeQstItems(PID_Q_DAYGLOW_HOLOMODUL)
       removeQstItems(PID_Q_DAYGLOW_BOOK_SANDIEGO)
       removeQstItems(PID_Q_DAYGLOW_BIOGEL)
       removeQstItems(PID_Q_DAYGLOW_CHIP)
       removeQstItems(PID_Q_DAYGLOW_CODE_CORONADO)
       removeQstItems(PID_Q_DAYGLOW_CODE_HANDY)
       removeQstItems(PID_Q_DAYGLOW_FILM)
       removeQstItems(PID_Q_DAYGLOW_FOODPROCESSOR)
       removeQstItems(PID_Q_DAYGLOW_ROCKET)
       removeQstItems(PID_Q_DAYGLOW_GAUBI_DETALS)

       removeQstItems(PID_Q_DAYGLOW_CARAVAN_1)
       removeQstItems(PID_Q_DAYGLOW_CARAVAN_2)
       removeQstItems(PID_Q_DAYGLOW_CARAVAN_3)
       removeQstItems(PID_Q_DAYGLOW_CARAVAN_4)
       removeQstItems(PID_Q_DAYGLOW_CARAVAN_5)

       if (itemRemoveCheck>0) then begin
       display_msg(mstr(102)+itemRemoveCheck+mstr(103));
       end
       itemRemoveCheck := 0;

       mark_area_known(MARK_TYPE_TOWN, AREA_DAYGLOW, MARK_STATE_INVISIBLE);
       dude_teleport_map(1,1,MAP_DAYGLOW_START_POINT,(2*24)+random(1,23)); // время пути синхронизировать с SCRIPT_YCStart
       end
   end
end

procedure use_p_proc begin
   script_overrides;
   call talk_p_proc;
end

procedure use_skill_on_p_proc begin
   script_overrides;
   call use_p_proc;
end

procedure use_obj_on_p_proc begin
   stopUseCarGaz
end

procedure talk_p_proc begin
   dialog_proc_obj(NodeDialog)
end

procedure Node999 begin
end

procedure NodeDialog begin
   if (cur_map_index == MAP_DAYGLOW_START_POINT) then begin
      Reply(110)
      NAnswer(118,1,NodeDialog2)
      NAnswer(119,1,Node999)
   end
   else begin
      Reply(110)
      if (map_var(MVAR_DIEGOSTART_FAIL) == 0) then begin
      NAnswer(111,1,NodeDialog2)
      end
      else begin
      NAnswer(112,1,NodeDialog2)
      end
      NAnswer(113,1,Node999)
   end
end

procedure NodeDialog2 begin
   Reply(114)
   NAnswer(115,1,NodeDialog3)
   NAnswer(116,1,Node999)
end

procedure NodeDialog3 begin
   if (who_carry_amount(dude_obj) <= 100) then begin
   partyRemoveAll // !!! тщательно проверить
   add_timer_event(self_obj, 2, 1);
   call Node999;
   end
   else begin
   display_mstr(117);
   end
end
