{100}{}{You see a merchant.}
{101}{}{You see a fishmonger... or maybe a bartender.}
{102}{}{Hide behind the counter. I don't think these demons are gonna find us here.}

{200}{}{What do you need, stranger?}
{1200}{}{What do you need, lady?}
{201}{}{I don't need anything right now. Later.}
{202}{}{I need a beer maybe...}
{203}{}{Is that all? Enjoy.}
{204}{}{Bye.}
{205}{}{Thanks again for the Geiger counter.}
{206}{}{After the fire on the platform, fishing here is gradually picking up. Appreciate it, amigo.}
{1206}{}{After the fire on the platform, fishing here is gradually picking up. Appreciate it, amiga.}

{210}{}{Where can I buy fuel cell batteries for a boat?}
{211}{}{None of the fishermen are gonna sell their reserves - they don't have enough themselves. The closest place we get batteries for the boats and generator is Puerto Penasco. Try your luck there.}
{212}{}{Thanks.}
{213}{}{Hey, if you're heading that way, can you do me a favor?}
{214}{}{Depends. What do you need?}
{215}{}{I've been asking the Puerto Knights for a new Geiger counter. They hoard tech like gold. By the time they send a new meter, we might be glowing in the dark. If you bring me one, I'll trade it for a battery or pay in clean caps.}
{216}{}{I'll keep that in mind.}
{217}{}{You're in luck. I've got a counter I don't need.}
{218}{}{I have a Geiger counter for you.}
{219}{}{Where can I buy fuel cell batteries for my bike?}
{220}{}{Finally! Let me check it... hmm... seems good. What do you want in return? Caps or the battery you needed?}
{221}{}{Fuel Cell Battery.}
{222}{}{Caps.}
{223}{}{Take it for free. Consider it a gift for making the world a cleaner place.}
{224}{}{Here. Fully charged.}
{225}{}{Just what I needed.}
{226}{}{Here are the caps, }
{227}{}{ pieces.}
{228}{}{Great.}
{229}{}{Oh, thank you, amigo!}
{1229}{}{Oh, thank you, amiga!}
{230}{}{You're welcome.}

{240}{}{Gilberto says you've been to Inferno?}
{241}{}{Yeah, it's a hellhole. Charred ruins and... human bones everywhere.}
{242}{}{Wow, can you tell me more? I'm going there on a mission.}
{243}{}{Sounds terrifying. Maybe don't tell me more.}
{244}{}{You really want to know? I don't like talking about it, but I'll make an exception for you.}
{245}{}{What dangers await there?}
{246}{}{You really want to know? I don't like talking about it. So, are you gonna order something or not?}
{247}{}{Here are 20 caps for tea. I want to hear your story.}
{248}{}{I don't have any caps right now. Maybe another time.}
{249}{}{I was scavenging for useful things. The ruins aren't picked clean like Phoenix, so they're full of relics. But getting them out is risky - radiation and collapses. Half the time I was crawling through underground passages. You can hide from radiation there for a while.}
{250}{}{Go on.}
{251}{}{But the worst thing is the demons. The 'Reavers'.}
{252}{}{Demons? Reavers?}
{253}{}{They're like ghouls, remnants of those who somehow didn't die in the nuclear blasts. Walking dead, lost their minds and humanity. Thankfully, they rarely leave the core ruins.}
{254}{}{You must have been through hell.}
{255}{}{Many scavengers have died from those demons or radiation. Be careful - stock up on meds and a good gun if you're still going.}
{256}{}{Thanks for the advice.}
{257}{}{I'm not scared by that.}
{258}{}{Judging by your look, you already know the risks.}
{259}{}{Caught me. Okay, let's change the subject.}

{260}{}{What do you know about the treasure Ruiz is after?}
{261}{}{Don't mess with Ruiz. He's a sly and dangerous man. That treasure is probably a hoax. No one knows if it even exists.}
{262}{}{Have you tried to find it?}
{263}{}{I've got one piece of the map. Ruiz won't give up his part. No clue where the other pieces are.}
{264}{}{Can you sell me your piece?}
{265}{}{Maybe. The chance of finding the treasure is slim, but I'll sell it for a good price. Let's say }
{266}{}{ caps.}
{267}{}{Deal. Here's the caps.}
{268}{}{How much? No thanks. Keep your piece of paper.}
{269}{}{No, that won't cut it. Come back with more caps. I want to profit from others' greed too.}
{270}{}{Uh, okay. I'll be back with the caps...}
{271}{}{(counts the caps excitedly) Looks like I've used up all my luck today! Here's my piece of the map. Good luck finding the treasure. You'll need it.}
{272}{}{Bye.}

{280}{}{Hey, you know what happened to Johnny?}
{281}{}{Yeah, rumors spread fast. It's terrible. Didn't think anyone here would resort to violence.}
{282}{}{Who do you think did it?}
{283}{}{No idea. Johnny was liked by everyone. Only Ruiz was cold with him. But Ruiz hates everyone. And that clown... his uncle Tin-Tan. Johnny avoided him, which is odd since he was excited about his uncle's arrival from Phoenix. After that, Johnny changed.}
{284}{}{Is he really from Phoenix?}
{285}{}{Yeah. His papers are legit, all from Sonora Express. No branch here, so we send and receive through Casa Nueva when dealing with Phoenix.}
{286}{}{Casa Nueva or Phoenix? Thanks.}
{287}{}{Hey, you didn't buy anything!}
{1287}{}{Hey, you didn't buy anything!}
{288}{}{You'll manage.}
{289}{}{Sorry, here's 5 caps for tea.}
