{110}{}{This body needs a closer look.}
{111}{}{This is difficult to do during combat.}

{200}{}{You see the body of a teenager. It's been here for quite some time now.}
{201}{}{Poor guy. What could have happened to you?}
{202}{}{You're out of luck, kid.}
{203}{}{It appears this teenager died from strangulation. There are dark rope marks on his neck, and a stream of bowel movements that leaked from his pants. There are signs of a struggle on the sand.}
{204}{}{Apparently someone killed him. The fishermen should be told about this.}
{205}{}{Leave the body alone.}
