{100}{}{You see the security computer.}
{101}{}{You see a computer with access to the security system.}

#Dialogue
{200}{}{Access to security system has been granted. Enter command:}
{201}{}{End session}
{202}{}{Back}
{203}{}{Next}
{204}{}{Return to main menu}
{205}{}{Cancel}

{210}{}{Deactivate security turrets.}
{211}{}{Disabling the turrets threatens the safety of the oil platform. Are you sure you want to disable the security turrets?}
{212}{}{Yes. Disable those damn turrets!}
{213}{}{Done. Security turrets are deactivated.}
{214}{}{Activate security turrets.}
{215}{}{Done. Security turrets are activated.}

{220}{}{Add new identity to database.}
{221}{}{Please complete the clearance form.}
{222}{}{Name: }
{223}{}{. Age: }
{224}{}{. Place of birth: Villa, Arizona. Clearance: full.}
{225}{}{Done. A new user has been added to the database.}
