{100}{}{You see the creature from the Black Lagoon.}
{101}{}{A terrible-looking creature crawls out of the ruins of the lighthouse!}
{102}{}{Ooooh!}

{200}{}{Oooh!}
{201}{}{Ahhh, monster! Die! Die!}
{202}{}{Stop! I'm just like you. I don't want to kill you. You understand me?}
{203}{}{Huh?}
{204}{}{Nope, nope. It'll be best if you just die, creature!}
{205}{}{Listen, you need to get out of here.}
{206}{}{Uh-huh?}
{207}{}{The fishermen are looking for you. And if they find you, they'll kill you. Understand?}
{208}{}{Ry? Keeel? Arr! Food! My food!}
{209}{}{Yes, yes. I understand you're hungry. But these are their fish. And they are ready to kill for them. Get out of here, otherwise you'll die!}
{210}{}{You don't seem to understand. Let's see how you understand the language... of violence!}
{211}{}{Then you leave me no choice. You'll have to be killed.}
{212}{}{(Looks around in a panic and then quickly runs away)}
{213}{}{Come on, you hideous freak, go back to the hell you came from.}
