{100}{}{You see a tribal hunter.}
{101}{}{You see one of the tribe's men. He is wearing very light clothes.}
{102}{}{Thank you, friend of our tribe. It is good that there are strangers you can trust.}
{103}{}{Thank you for your help in oasis. It seems somewhere in you there is still a hothouse of goodness.}

#Before receiving the quest
{200}{}{Greetings, stranger. Our camp is open for you, but I doubt that you will be of use to us.}
{1200}{}{Greetings, stranger. Our camp is open for you, but I doubt that you will be of use to us.}
{201}{}{Why?}
{202}{}{Because of missionaries and brahmin thieves, we have lost trust in outsiders.}
{203}{}{I understand that. Believe me, I don't wish you harm and I don't want problems with you.}
{204}{}{We have long forgotten how to believe words. Yet I am glad to hear it.}
{205}{}{I hope you and I can find some understanding.}
{206}{}{I haven't done anything yet and you're already harassing me!}
{1206}{}{I haven't done anything yet and you're already harassing me!}
{207}{}{Not wise. You should not test our good will for too long.}
{208}{}{I don't care. I'm just passing through.}
{209}{}{Sorry, that's not what I meant.}

{220}{}{What do you want, stranger?}
{221}{}{What do you want, man from the Villa?}
{222}{}{Good to see you, friend.}
{223}{}{I don't need anything. Bye.}

{230}{}{What are you doing here?}
{231}{}{Elders gather us into pueblo to prepare to drive back outsiders. I think it is foolish.}
{232}{}{Why?}
{233}{}{Few hunters now watch desert around us. I return from one watering hole. There I see many huge desert scorpions. They stop herders from using water.}
{234}{}{Whoa, that's bad... And nothing can be done?}
{235}{}{Have you talked to anyone about this?}
{236}{}{I want to gather warriors to get rid of monsters. But leader forbade warriors to leave pueblo unless great need arises.}
{237}{}{I think the scorpions will eventually leave on their own. It's my time too. Bye.}
{238}{}{This doesn't sound good. Maybe I can help you.}
{239}{}{Can you handle crowd of scorpions alone? This will be hot battle.}
{240}{}{You know, I can't even handle one scorpion. You'll have to deal with them without me.}
{241}{}{I'll figure it out. Show me the way to this watering hole.}

{250}{}{I destroyed all the radscorpions at the watering hole.}
{1250}{}{I destroyed all the radscorpions at the watering hole.}
{251}{}{Thank Divine Brahmin! You have brought help to our brahmin herders, for whom oasis was important waystop. Thank you, friend of our tribe.}
{252}{}{You're welcome.}
