{100}{}{You see a guard in front of you.}
{101}{}{You see a man of Mexican appearance.}
{102}{}{Muchas gracias, senor.}
{1102}{}{Muchas gracias, senora.}
{103}{}{The guard breaks into a smile. It doesn't look like he's very concerned with his job at the moment.}

{104}{}{«Thank you very much, sir.»}
{1104}{}{«Thank you very much, ma'am.»}

{110}{}{Vete, escoria!}
{111}{}{No puedes entrar.}
{112}{}{No toques la puerta.}

{120}{}{«Get out, scum!»}
{121}{}{«You can't go in.»}
{122}{}{«Don't touch that door.»}
{123}{}{«You can't go there.»}
