{100}{}{You see a highwayman.}
{101}{}{You see a rugged man in worn road armor.}
{102}{}{Move along, stranger.}

{200}{}{Hey, you! What do you think you're doing here?}
{201}{}{I thought this land was free for the taking. What's the issue?}
{202}{}{Well, there is an issue. You're on *our* turf, poking around *our* warehouse.}
{203}{}{How was I supposed to know? Maybe put up a sign next time.}
{204}{}{What, got road dust in your eyes? Can't you read? Oh wait, are you messing with me? You're in for a rough ride, pal.}

{210}{}{Mind your own business.}
{211}{}{No, this is MY warehouse and MY business.}
{212}{}{Really? Maybe I should've put up a sign on the door.}
{213}{}{Tough break, friend.}
{214}{}{You're a loose end. Can't have you spreading stories.}
{215}{}{That sounds pretty grim...}
{216}{}{You need a reality check. And maybe a bath while you're at it.}

{220}{}{Looks like we're from the same clan. No need for us to fight, brother.}
{221}{}{Blue Shield brother! You from the base? Been a while since I was there. What's new?}
{222}{}{Things are good. The clan's safe, and we've secured our independence.}
{223}{}{Yeah, I heard. Might swing by sometime. Safe travels, brother. May the dust cover your tracks.}
{1223}{}{Yeah, I heard. Might swing by sometime. Safe travels, sister. May the dust cover your tracks.}
{224}{}{Safe travels to you too.}

{230}{}{I'm just a scavenger. Please, don't hurt me.}
{231}{}{So you're a local, huh? Must be new around here. Everyone knows to steer clear of our territory. Now get out. If I see you again, you're dead.}
{232}{}{Alright, as you say...}
{233}{}{I'm just looking around. What's the harm in that?}
{234}{}{The harm is that we don't like trespassers. This is our turf. Gotta take you out to keep things quiet.}
{235}{}{Your turf? Yeah, right...}
