{100}{}{You see a robot administrator.}

{200}{}{Welcome to the world of Wild West adventure!}
{201}{}{Welcome to Legend City!}
{202}{}{Welcome to Arizona's largest amusement park!}
{203}{}{Wow, that sounds great.}
{204}{}{Don't get in my way, bucket of bolts.}

{210}{}{How can I help you, sir?}
{1210}{}{How can I help you, ma'am?}
{211}{}{Nothing else.}
{212}{}{That's all I wanted to know. Now let me have my fun.}

{220}{}{What is this place?}
{221}{}{You are in Legend City - the largest amusement park in all of Arizona!}
{222}{}{Tell me what there is to do here?}
{223}{}{Amusement rides, virtual play area, shooting range, cafeteria - what interests you?}
{224}{}{Perhaps it would be better if I just looked around on my own. For free.}
{225}{}{But what is this place?}
{226}{}{I'm interested in the rides.}
{227}{}{I regret to inform you, sir, that the attractions are presently closed due to technical issues. Our sincerest apologies for any inconvenience caused.}
{1227}{}{My apologies, ma'am, but the attractions are currently closed due to technical issues. We apologize for any inconvenience this may cause.}
{228}{}{Can I shoot at the shooting range?}
{229}{}{I'm sorry, sir, but the shooting range is currently out of ammunition.}
{1229}{}{I'm sorry, ma'am, but the shooting range is currently out of ammunition.}
{230}{}{Is the cafeteria open?}
{231}{}{We apologize, sir, but the cafe is temporarily closed.}
{1231}{}{We apologize, ma'am, but the cafe is temporarily closed.}
{232}{}{Does anything work here?}
{233}{}{You can try virtual games in our new gaming room. Enjoy your Wild West adventure, sir!}
{1233}{}{You can try virtual games in our new gaming room. Enjoy your Wild West adventure, ma'am!}
{234}{}{Okay, let's see these virtual games.}
{235}{}{Then step aside, little piece of iron, I'm gonna win big!}
{236}{}{Is the cafeteria even open?}
