{100}{}{You see the curator.}
{101}{}{You see a man clad in a robe of striking color. As he surveys the convoy, he appears to tower above the entire world.}
{102}{}{This man doesn't want to talk to you.}

{200}{}{A peaceful traveler in these parts? Quite a surprise. But we don't need any companions. Stay away from us and our slaves. Is that clear? Now, be on your way.}
{201}{}{Can I ask a question?}
{202}{}{Why don't the Followers of Fire share information?}
{203}{}{I'm not leaving here without answers.}
{204}{}{I see. I'm leaving.}

{205}{}{It's a pity your mind is as miniscule as an atom in a nuclear womb. We'll have to split you until nothing remains!}
{206}{}{What are you talking about...?}
{207}{}{If you are truly a Brother of Fire, then you should know: if you are not initiated into the most important matters, you are not worthy.}
{208}{}{So, can I ask a question?}
{209}{}{You seem smart, what's the harm in a little conversation?}

{210}{}{Just one.}
{211}{}{What are you transporting?}
{212}{}{An ancient artifact. Too important to discuss with the uninitiated.}
{213}{}{Who are you?}
{214}{}{Of all questions, you choose the most meaningless. These are my mercenaries, and these my slaves, and I am the leader of this convoy.}
{215}{}{Isn't that robe hot in the middle of the desert?}
{216}{}{(smirking) No. The synthetic fiber and capillary fluid compressor make it perfect for the desert.}
{217}{}{I need to get to the nearest town. Can you tell me the way?}
{218}{}{Hm? (raises an eyebrow mysteriously)}
{219}{}{Is that all? I was hoping for more...}
{220}{}{Uh, thanks.}
{221}{}{(points to the town of Flagstaff on your map)}
{222}{}{(points to the city of Phoenix on your map)}
{223}{}{(points to the city of Two-Sun on your map)}
{224}{}{Your questions are over. Leave, if you value your miserable life.}
{225}{}{I'm dying of thirst! Can you give me a sip of water?}
{226}{}{Saving a worthless life isn't part of my plans. Yet, even a fleeting act of mercy has its place in the grand design of rebuilding the world. Take a sip of this pure water, and let it remind you of the Followers of Fire's mission. Tell everyone you encounter that we dream of bringing water to all... to all who are worthy.}
{227}{}{I'm not going to waste my time with people demanding to talk but not willing to listen. Leave now!}
