{100}{}{You see a cyborg.}
{101}{}{You see a crazed Tinsmith whose mind has been overtaken by technology.}

{110}{}{System malfunction... What a headache!}
{111}{}{Error! Stop those numbers! I can't take it anymore!}
{112}{}{Why? Why? Why?}
{113}{}{It's all numbers... all data!}
{114}{}{Directive: Eliminate target.}
{115}{}{I am a machine. I am a machine. I am not a person...}
{116}{}{That voice in my head disrupts the program!}
{117}{}{I am just a variable in a vast algorithm. Do not interfere!}
{118}{}{You have corrupted my program!}
{119}{}{You must be deleted from the database!}
