{100}{}{You see Preacher Hiram, his robe worn and weathered.}
{101}{}{You see a man before you, his robe in tatters.}
{102}{}{What... what are you doing...}
{103}{}{...cough... hrrr...}
{104}{}{Heretic! The technology of the Ancients is not for casual wear. This armor belongs in our main temple in Phoenix.}

#First dialogue
{200}{}{Greetings, traveler. It took great courage to venture into this city.}
{1200}{}{Greetings, traveler. It took great courage to venture into this city.}
{201}{}{Why is that?}
{202}{}{Flagstaff stands as one of the last bastions of order in the wasteland. Here, strangers may find themselves consigned to forced labor or worse, fuel for the Holy Fire. But ultimately, it's your choices that dictate your fate.}
{203}{}{I see. I'd like to speak with you.}
{204}{}{Got it. Goodbye.}
{205}{}{Welcome, traveler. May the rays of the Holy Fire guide your path in this city. I trust you don't condemn our local customs?}
{206}{}{What do you mean by local customs?}
{207}{}{Greetings, traveler. How may I be of service to you?}
{208}{}{Well, I'm new here and could use some guidance.}
{209}{}{Hmm, not the most auspicious start to our encounter. Learn to embrace faith as it is. Words merely veil deeper truths.}

#Re-dialogue
{210}{}{How can I assist you?}
{211}{}{Goodbye.}
{212}{}{Who are you, and what is this place?}
{213}{}{This is the Great Church of the Holy Fire, and I am Hiram, its humble priest. Welcome to the radiant sanctuary of our faith.}
{214}{}{Why all the fancy language?}
{215}{}{Well... truth be told, I can scarcely remember a time when I spoke differently. The Teachings of the Holy Fire have transformed my entire existence.}

#About knowledge
{216}{}{Is your church of any use to Flagstaff?}
{217}{}{Certainly! Let me begin by explaining that Flagstaff was established because of our church... or rather, the main temple, located in Phoenix.}
{218}{}{So what?}
{219}{}{Uranium stands as one of the sacred resources bequeathed by our ancestors. We harness its radiant energy to glorify the Holy Fire...}
{220}{}{Go on.}
{221}{}{We impart literacy and pre-war knowledge to all who seek it. Additionally, as a humble servant of the Holy Fire, I am blessed with the gift of healing.}
{222}{}{I suspect there's a cost involved.}
{223}{}{Ah, a skeptic! Yet, I must concede, there is truth in your suspicion. To access the wisdom of the Old World, one must either pay in caps or become a member of our church. Not all are ready to embrace the knowledge of ages past.}
{224}{}{I see. Can I ask you about something else?}
{225}{}{That's enough. Goodbye.}
{226}{}{I'm interested in learning from you.}
{227}{}{Certainly. However, I cannot accept you as a brother in faith until I receive approval from the main temple. This means you'll need to make a payment. Can you read?}
{1227}{}{Certainly. However, I cannot accept you as a sister in faith until I receive approval from the main temple. This means you'll need to make a payment. Can you read?}
{228}{}{Yes.}
{229}{}{I can kind of... uh... sound it out.}
{230}{}{Then the secrets of the Holy Fire shall elude you! Let's start with the basics - literacy. A single lesson costs one hundred caps.}
{231}{}{Here's the caps. I seek enlightenment!}
{232}{}{Not now. I have some other questions first.}
{233}{}{That's a little much for me right now.}
{234}{}{Very well, today's lesson concludes here. With continued practice in reading and writing, you shall unlock the mysteries of pre-war knowledge. Remember who guided you on this sacred journey!}
{235}{}{Whew... my head hurts a little. I definitely need a breather.}
{236}{}{One mustn't entrust the mysteries of the Holy Fire to just anyone. This knowledge holds potential for both good and ill. Demonstrate your devotion to our faith through a substantial donation. Three hundred caps is the price.}
{237}{}{I think I've donated enough to your church already.}
{238}{}{Then I want to make a donation.}
{239}{}{Ah, indeed. Very well, I must honor my word. Beyond that door lies my sanctuary. Within lie ancient manuscripts. Treat them with reverence and care.}
{240}{}{Excellent, material for bedtime reading.}
{241}{}{Thanks, you're a real wasteland saint!}
{242}{}{Enough about the church; I've got the gist of it.}

#About faith
{245}{}{Tell me about your church.}
{246}{}{I could expound on this endlessly. The world was forged by the Holy Fire, which descended to earth a century ago. It cleansed the earth of those steeped in sin, sparing only select families to ensure humanity's survival.}
{247}{}{Go on.}
{248}{}{Now we, the descendants of these survivors, endeavor to construct a New World, free from the errors and vices of the past.}
{249}{}{Who's "we"?}
{250}{}{We refers to our church and its adherents, naturally. Regrettably, others have forsaken the lessons of antiquity. It falls upon us to guide them to enlightenment.}
{251}{}{I thought it was war, the Great War, that destroyed everything.}
{252}{}{War and the struggle for the material is the plight of many in our time. They have relinquished faith in the spirit, descending into the realm of mere materialism. The Great War merely veils the true nature of the Holy Fire. It was not atomic bombs that chastised humanity, but rather human folly and avarice. That is the crux of it.}
{253}{}{How far has your faith spread?}
{254}{}{Our primary temple resides in Phoenix, though its location is of lesser import. Numerous towns, settlements and tribes embrace faith in the Holy Fire, albeit under different names and interpretations of ancient events. Hence, our church proliferates effortlessly. Our doctrines resonate throughout Sonora.}
{255}{}{What do the settlers think of your church?}
{256}{}{The majority of settlers hold reverence for the Holy Fire, or at least feign as much. However, Faber's mercenaries are largely faithless, and skepticism pervades within the populace. Fear not; the Holy Fire shall eventually illumine their minds. My apprehension lies with those who strike out against its wisdom.}
{257}{}{}
{258}{}{I have a few more things to ask of you.}
{259}{}{Very well, goodbye.}

#Donation
{260}{}{I wish to donate to your church.}
{261}{}{Any contribution brings us closer to the essence of the Holy Fire. What do you offer?}
{262}{}{Uhmm, I don't have anything really. However, I do have a lot of questions.}
{263}{}{Nothing today. Goodbye.}
{264}{}{Only 10 caps.}
{265}{}{Here are 50 caps.}
{266}{}{A whole 100 caps.}
{267}{}{(swiftly conceals the caps within the folds of his robe) Thank you.}
{268}{}{(promptly transfers your caps into a leather pouch affixed to his belt) Truly, your magnanimity knows no bounds!}
{269}{}{(quickly pours your caps into a leather pouch hanging from his belt) May the Holy Fire be with you!}

#Treatment
{270}{}{I need healing.}
{271}{}{By the grace of the Holy Fire, what ails you?}
{272}{}{I've been wounded.}
{273}{}{I've been crippled.}
{274}{}{I've been exposed to radiation.}
{275}{}{I've been poisoned.}
{276}{}{Nothing too severe, thankfully.}
{277}{}{Of course, the church will help you, but wouldn't you like to reward it with a small donation? We're talking about }
{278}{}{ caps.}
{279}{}{Here are the caps.}
{280}{}{I don't have enough caps!}
{281}{}{Regrettably, without the necessary donation, I cannot extend my assistance.}
{282}{}{Damn...}
{283}{}{No need, I can recover on my own.}
{284}{}{Praise be to the Holy Fire for granting you additional time!}
{285}{}{Ah, that feels much better.}
{286}{}{}
{287}{}{Man, in a big bag! Oh oh!}
{288}{}{Are you referring to my robe? (shakes head) Oh, unfortunate child of Atom, I pity you. I wish I could aid you in reclaiming the Atoms of Consciousness you've lost, but alas, I am powerless in this matter. Depart now, Child of Radiation.}
{289}{}{Go outside? I like go outside.}

#Receiving a letter of recommendation
{290}{}{I would contribute significantly to the church if I had access to its senior leadership.}
{291}{}{That may be possible. I could draft a letter of recommendation in your name for the main temple. However, it appears you haven't fully embraced our faith yet.}
{1291}{}{That may be possible. I could draft a letter of recommendation in your name for the main temple. However, it appears you haven't fully embraced our faith yet.}
{292}{}{I see.}
{293}{}{I could arrange a letter of recommendation for you to present at the main temple in Phoenix. This could mark the beginning of your journey. But are you truly prepared for the trials ahead?}
{1293}{}{I could arrange a letter of recommendation for you to present at the main temple in Phoenix. This could mark the beginning of your journey. But are you truly prepared for the trials ahead?}
{294}{}{Absolutely!}
{295}{}{I need time to consider.}
{296}{}{Excellent. Here's the letter. Guard it with care until you reach the main temple. This will be your first test.}
{297}{}{I will carry this letter in the name of the Holy Fire! Or something like that.}
{298}{}{Given your reputation in Flagstaff, I question your suitability for the main temple.}
{299}{}{}

#Quest - beginning:
{300}{}{Are caps the only issue?}
{301}{}{While many harbor quiet disdain for our faith, some are less subtle.}
{302}{}{Is someone threatening the church?}
{303}{}{An unknown assailant perpetrates vile deeds under the cover of night -- drawing crosses on walls, setting fires, defiling doors with filth. Clearly, they seek to intimidate me, to coax me into fleeing the colony. But I have yet to confront this heretic face-to-face.}
{304}{}{Perhaps I can track them down. It would be interesting to find out what their problem is with you.}
{305}{}{I'd rather not get involved in 'religious' matters. Let's talk about something else.}
{306}{}{Your assistance would be greatly appreciated.}
{307}{}{Okay, I'm gonna go poke around a bit.}
{308}{}{I don't think there has to be any 'accident'.}

#Quest - detecting a saboteur:
{310}{}{Tell me about the nighttime disturbances.}
{311}{}{Have you uncovered anything new?}
{312}{}{Not yet, but I had another question.}
{313}{}{No, nothing new. I'll come back when I find something.}
{314}{}{I caught the vandal in the act. Turns out, he's a balding resident from a house to the south.}
{315}{}{Festus... A tragic victim of atomic fallout.}
{316}{}{Do you know him?}
{317}{}{He attended our sermons but failed to grasp the radiant truths of the Fire. When he sought entry, Festus was consumed by anger and pride. And I barred the church doors to him.}
{318}{}{What happened afterward?}
{319}{}{Festus's son became a source of discord. I pleaded to send the gifted youth for temple teachings, but Festus adamantly refused. Sadly, in Flagstaff, many fail to recognize the value of knowledge, relying instead on brute force.}
{320}{}{Go on...}
{321}{}{When the boy fell ill from radiation, I offered free treatment if Festus would reconsider and send his son to the temple. Yet Festus's animosity proved insurmountable. It appears he's exacting revenge now.}
{322}{}{What can be done?}
{323}{}{Halting Festus's threats and sending the child to the temple is a formidable challenge.}
{324}{}{Leaving us... no choice?}
{325}{}{I'll try to reason with him.}
{326}{}{I need time to think.}
{327}{}{When nuclear material turns hazardous, it's contained and kept from harm's way. Otherwise, it poses a danger to all.}
{328}{}{May the Holy Fire guide you.}
{329}{}{Yeah...}

#Quest - completion of the quest:
{330}{}{Let's talk about Festus.}
{331}{}{Go ahead.}
{332}{}{I have some other questions.}
{333}{}{I'll come back once I've dealt with his situation.}
{334}{}{I've persuaded Festus. He'll send his son to the temple and stop his vandalism.}
{335}{}{Praise the Power of the Atom! Festus will publicly repent, and his son has a bright future as a clerk and scientist in the Cathedral of Fire. Excellent work.}
{336}{}{Festus had... an accident. He's no longer a concern.}
{337}{}{May the Holy Fire consume his soul! Festus was beyond redemption, and his conversion would've only caused harm. However, his son now has a promising future within the Cathedral of Fire. Well done.}
{338}{}{How can I repay you for your efforts?}
{339}{}{No need for thanks. I do it for the faith.}
{340}{}{I need some medicine - RadAway and two stimpaks.}
{341}{}{Can I receive a 20% discount on treatment?}
{342}{}{I need caps to free my fellow villagers from prison.}
{343}{}{I have a grand ambition -- to journey to the main Cathedral of Fire and seek an audience with its leader.}
{344}{}{I'd like access to your library.}
{345}{}{[More]}
{346}{}{}
{347}{}{But how do we do this without angering the other colonists?}
{348}{}{Hmm. Festus is afflicted by radiation. Introducing something highly radioactive to him could hasten his soul's decomposition into atoms. I'm sure something like that could be found in a uranium mine.}
{349}{}{An accident? A lethal dose of radiation? I'm no expert in such matters.}

{350}{}{Thanks.}
{351}{}{May the Heavenly Flame protect you. Your generosity will be mentioned in the next sermon, elevating your reputation among the common folk.}
{352}{}{Well deserved. Take them.}
{353}{}{It is well deserved. You can count on this "discount" henceforth.}
{354}{}{I can only offer 100 caps due to meager parishioner donations. Nonetheless, it should be enough to get Faber's attention.}
{355}{}{Hmm. I can draft a letter of recommendation to the main Cathedral of Fire in Phoenix. However, your merit must be further demonstrated with a larger donation.}
{356}{}{This collection of invaluable pre-war knowledge must be handled with care. Treat it respectfully.}
{357}{}{Things have moved on. His son is cured.}
{358}{}{Is he truly cured? I thought this problem would never be resolved without me. Now, sadly, I've lost what little chance I had to sway the father.}
{359}{}{Consider this a lesson learned.}

#Treatment of Festus's son
{360}{}{Festus's son needs treatment.}
{361}{}{I'll gladly assist him, only if he agrees to attend the temple.}
{362}{}{Understood.}
{363}{}{With Festus out of the picture, it's time to honor the promise.}
{364}{}{Further delay won't bode well with the main Cathedral of Fire.}
{365}{}{Your 'principles'' could turn public opinion against you.}
{366}{}{Showing leniency could bolster the church's reputation.}
{367}{}{I'll commence treatment as soon as I'm ready.}
{368}{}{Sounds good.}
{369}{}{I must stand firm.}
{370}{}{That's what I thought...}
{371}{}{Why resort to such tactics?}
{372}{}{Changing the minds of adults is often futile. It's through children that faith's seeds must be sown. And eventually, the 'deal' will be forgotten, and only the debt of gratitude will remain.}
{373}{}{I see.}

#Dialogue adjustments after the events in the Phoenix Temple
{400}{}{Leave me alone... Oh, it's you. Never mind.}
{401}{}{Is someone bothering you?}
{402}{}{The colonists have grown intolerant of my faith since learning about the events in the south. Some want to drive me out of town. But I have nowhere else to go now.}
{403}{}{Seems like you're in a tough spot. I'll leave you be then.}
{404}{}{Greetings. I'm glad to see a fellow believer in our monastery. Welcome to radiant Flagstaff!}
{1404}{}{Greetings. I'm glad to see a fellow believer in our monastery. Welcome to radiant Flagstaff!}
{405}{}{How did you find out about my promotion?}
{406}{}{For our faith, distance is inconsequential. The messengers of the Renaissance have informed me of your rise.}
{407}{}{Ah, yes, the postal service...}
{408}{}{}
{409}{}{}
{410}{}{So how can I assist, brother?}
{1410}{}{So how can I assist, sister?}
{411}{}{Hold! What do you, brother in faith, know of the events in Phoenix?}
{1411}{}{Hold! What do you, sister in faith, know of the events in Phoenix?}
{412}{}{Same as you, I suppose.}
{413}{}{I blew up the Temple of Fire. It brought tragedy to the Villa, so I taste the same fate.}
{1413}{}{I blew up the Temple of Fire. It brought tragedy to the Villa, so I taste the same fate.}
{414}{}{Hmm. That's regrettable.}
{415}{}{Yeah. I'll be on my way then.}
{416}{}{So it's done. For... Vengence? What a barbaric motive! But if the church is gone, then I'll discard the preacher's robe and leave Flagstaff. Your actions grant me the chance for a fresh start. Perhaps it's not all bad.}
{417}{}{Fair enough.}
{418}{}{I've heard of your expulsion from the Brotherhood of Fire. I need to understand why.}
{419}{}{Do reasons matter to you? Stick 'em where the sun don't shine, cultist!}
{420}{}{I won't stand for the desecration of my faith! The Holy Fire is no myth. It was real a century ago! If even after my sermons you refuse to see the truth, then may you soon atomize into oblivion.}
{421}{}{Whatever.}
{422}{}{Your faith preaches the wrong ideas.}
{423}{}{Are you suggesting the Holy Fire never existed? That we shouldn't strive to restore the world to its former glory by rectifying its arrogant mistakes? What's your alternative? Languishing in the ruins and desolate wasteland? Then remain in your blissful ignorance.}
{424}{}{Whatever.}
{425}{}{I still believe in the Fire and seek enlightenment, brother.}
{426}{}{Your lies are an affront to faith. Leave Flagstaff until the Fire enlightens you to the truth.}
{427}{}{Whatever.}
{428}{}{Can I trust you... brother? Maybe you're not beyond redemption yet. Go forth. Prove your dedication to the faith through tangible actions. With or without the temple's sanction.}
{1428}{}{Can I trust you... sister? Maybe you're not beyond redemption yet. Go forth. Prove your dedication to the faith through tangible actions. With or without the temple's sanction.}
{429}{}{Alright.}
{430}{}{Your mere presence already aids the church. But we always welcome caps from any source.}
{431}{}{You mustn't allow just anyone to approach the mysteries of the Holy Fire. This knowledge can be wielded for both good and ill...}
{432}{}{Of course. And I've already demonstrated my devotion to the faith.}
{1432}{}{Of course. And I've already demonstrated my devotion to the faith.}
{433}{}{An odd question for a fellow believer. I am Hiram, the priest of this temple.}
{1433}{}{An odd question for a sister in faith. I am Hiram, the priest of this temple.}
{434}{}{Certainly. But can you read?}
