{100}{}{You see Roy Faber.}
{101}{}{You see the colony's warden. It's hard to withstand his heavy gaze.}
{102}{}{Your rule ends here, bastard.}
{103}{}{Your rule ends here.}

#First Dialogue
{200}{}{(looks you over, as if evaluating your worth) I haven't seen you before. Who the hell are you?}
{1200}{}{Pardon my ignorance, but a lady shouldn't be wandering in such places without an escort. I haven't seen you before. Where are you from?}
{201}{}{I won't introduce myself to a slaver.}
{202}{}{Hmph? It's been a while since someone dared talk back to me. All those who did, well, they're dead now. I'll give you a minute for your courage. I'm curious to hear you out.}
{203}{}{No need for a minute. You need to die now!}
{204}{}{Seriously?}
{205}{}{I'm looking for my people, the villagers from Villa. They say they're in your pen.}
{206}{}{(says with indifference) Yes, those filthy peasants are here.}
{207}{}{But why are you holding them captive?}
{208}{}{I was about to shoot you. But I remembered meeting a few ghouls in Phoenix. Are you one of them? Then what the hell are you doing here in Flagstaff?}
{1208}{}{I was about to shoot you. But I remembered meeting a few ghouls in Phoenix. Are you one of them? Then what the hell are you doing here in Flagstaff?}
{209}{}{I just want to talk.}

{210}{}{Well?}
{211}{}{Let me talk to my kin.}
{212}{}{I demand you release the villagers from Villa.}
{213}{}{Why do you need so many prisoners?}
{214}{}{Is there any work for me here?}
{215}{}{}
{216}{}{Let's go back a bit.}
{217}{}{Let's talk about something else.}
{218}{}{Let's change the subject.}
{219}{}{That's all, I'll be going.}

#Access to the Pen
{220}{}{Is that all? A minute of talking will cost you 100 caps.}
{221}{}{Here's the caps. Now can I enter the pen?}
{222}{}{Wait, I wanna ask you about something else first.}
{223}{}{I don't have that many caps. I'll be back when I have enough.}
{224}{}{No problem. My guards will let you in and out... if you behave.}
{225}{}{I'll try.}
{226}{}{I don't have that many caps. Just give us a minute!}
{227}{}{I named my price. Can't pay? Then get lost.}
{228}{}{Damn...}
{229}{}{You villagers have a remarkable herd instinct... Alright, go in. But misbehave, and you'll stay there forever.}

#Topic of Slaves
{230}{}{Here, in this penal colony, these useless dregs of the wasteland can provide some value, through their labor.}
{231}{}{What kind of labor are we talking about?}
{232}{}{Mining for uranium ore here, working caravans to the south, rebuilding Flagstaff, sometimes we get orders from Phoenix... Can't remember them all.}
{233}{}{So this isn't a slave town, but rather, a prison?}
{234}{}{Until recently, it was. Half the scum in our colony got caught by lawmen in the southern lands. Then they were brought here. Raiders, rapists, card debtors - we'll find uses for everyone.}
{235}{}{Call it what you want, but you're holding people against their will.}
{236}{}{Look around - Flagstaff thrives thanks to our prison. We're the only force that can bring order around here. Besides, just the mention of this colony scares people away from crime. Still don't like us? Then get the hell out.}
{237}{}{But the villagers from Villa aren't criminals.}
{238}{}{It so happened that we ran low on prisoners, and the quickest way to replenish our supply was to round up local savages. Villa fit the bill. Excellent material, hard to resist.}
{239}{}{The villagers of Villa are not savages, and don't deserve this.}
{240}{}{A savage like you has a narrow view of things. Do you know about the cities to the south? True civilization is reviving there. Like in the old days.}
{241}{}{So?}
{242}{}{Flagstaff supplies uranium, and our prisoners are the main workforce in this chain. Without us, there'd be no progress in the south. We're making history, and now your pathetic village can be part of it. You'll do something useful for the rest of the world.}
{243}{}{You don't seem like lawmen yourselves.}
{244}{}{You think there's a big difference? Lawmen live off criminals. They collect taxes from settlements in exchange for protection from raiders and other filth. We live off the criminals labor. (lifts a brass knuckle, inspecting it fondly) Power gives authority. How you wield it is up to you.}
{245}{}{Why do you need uranium ore?}
{246}{}{Ah, savages like you have forgotten the Old World. Several generations ago, people used uranium ore to generate energy. It powered old technology - from a regular light bulb to the most advanced electronics. In big cities, they still use the remnants of these technologies.}
{247}{}{Who's buying it?}
{248}{}{There are a few buyers in the south, the main one being the Church of the Holy Fire.}
{249}{}{There are a few buyers in the south. Most of our goods used to be bought by the Church of the Holy Fire. Now it's a bit trickier with clients.}

#Liberation
{250}{}{I don't see any reason to do that.}
{251}{}{I managed to solve your mine problems.}
{252}{}{Ah yes, I've been told. Hard to believe a peasant managed to solve long-standing problems. Okay, I keep my word. Go to the pen and make your kin happy. They're free.}
{1252}{}{Ah yes, I've been told. Hard to believe a peasant woman managed to solve long-standing problems. Okay, I keep my word. Go to the pen and make your kin happy. They're free.}
{253}{}{Good.}
{254}{}{Then let's find a reason.}
{255}{}{Alright, let's make a deal. There are a few problems that need solving. Do that, and I'll release your fellow peasants that remain in the pen.}
{256}{}{What do you need done?}
{257}{}{I need to get the mine running normally. Talk to the administrator; he'll fill you in.}
{258}{}{Alright, but I have a few questions first.}
{259}{}{Got it. I'll talk to him and come back when things are dealt with.}
{260}{}{What the hell are you talking about?! The mine is ruined, and it'll take months to clear it! Does that sound like solving problems? No. Now get the hell out!}
{261}{}{Aright...}
{262}{}{Remind me of our deal.}
{263}{}{Didn't you get it the first time? Go to the administrator at the mine. He'll tell you what to do.}
{264}{}{You'll see a reason in a week when the villagers infect the entire colony.}
{265}{}{What the hell are you talking about?}
{266}{}{About "wasteland disease," of course. Villa's residents are immune to it, but the colonists probably aren't. You've never heard of it?}
{267}{}{Shit... whole settlements in the south have died from some plague... Can you prove they've got it?}
{268}{}{When the disease shows up, you'll see for yourself. Decide if it's worth the risk.}
{269}{}{Damn it... Fine, I'll let your villagers go, but you better leave the colony right now!}
{270}{}{That's the right decision.}
{271}{}{Well... the villagers are sick. Can't you see?}
{272}{}{Keep fuckin' around, and you'll end up worse than your kin.}
{273}{}{Hey, take it easy...}

{274}{}{They say someone's been snooping around among my people. I don't like that. If I get one more report on you, you're going straight to the noose.}
{275}{}{This is a mistake! Your informants are lying!}
{276}{}{Uh... okay.}
{277}{}{Shut up! This colony runs on strict rules. Break one - you get punished. Break another - you get a noose around your neck. And I'm the one who makes the rules here.}

{278}{}{(yells) You rat bastard, do you even realize that a handful of filthy peasants are putting the whole of Flagstaff at risk! Years of hard work establishing and controlling an entire town, the hopes of the entire south for prosperity - all of it down the brahmin's ass. Come on, time to show me what you're fuckin' made of!}
{279}{}{Wait, hold on...}

#Quests
{280}{}{Maybe I could work off those caps?}
{281}{}{Perhaps. There's been a pesky problem that's been bugging me for a while.}
{282}{}{Tell me more.}
{283}{}{Several patrols have gone missing in the city ruins to the east. People say they heard gunfire. Find out what going on and eliminate the problem - I'll pay you 300 caps.}
{284}{}{Deal. I'll be back once I've sorted it out.}
{285}{}{I'll think about your offer.}
{286}{}{Alright, but if it involves killing anyone, I'm out.}
{287}{}{Why don't your mercenaries handle this?}
{288}{}{The ruins of the old city are too difficult and dangerous. I'd lose more people if I sent them in. But now I have you... What's wrong? Having second thoughts already?}
{289}{}{Then I have no other choice. You're dead!}
{290}{}{Ranger? Just another criminal playing hero. Well, good job. Here's your 300 caps.}
{291}{}{Just like that? A human life doesn't mean much to you.}
{292}{}{Great.}
{293}{}{Exactly. Including *your* pathetic, worthless life. So far, the surrounding savages only cared about their personal survival. Here, in my colony, people live for something *bigger*... Though, you wouldn't understand that, peasant.}
{294}{}{Yeah. See ya.}
{295}{}{Ranger? Just another criminal playing hero. Well, good job. Here's your 200 caps.}
{296}{}{Hey, we agreed on 300!}
{297}{}{Your memory's failing you. You won't get any more.}
{298}{}{Fine, whatever... Later.}
{299}{}{Any idea what it could be?}
{300}{}{Most likely, another big beast or a gang has holed up in the ruins. You'll find out for sure once you locate the missing patrols.}

{301}{}{One of your subordinates owes the bar 100 caps.}
{302}{}{I've heard something about that, but I'm not gonna intervene over such a tiny sum.}
{303}{}{Then I'll handle it.}
{304}{}{Hmm. Suit yourself. I'll tell my men not to touch you if it comes to a fight.}

{305}{}{I want my reward. There was a ranger saboteur in the east ruins, but he's dead now.}
{306}{}{There was a ranger saboteur in the ruins, but he's already left Flagstaff.}
{307}{}{Ranger? Unexpected, yet not a big surprise. I had a feeling we'd have trouble with those narrow-minded lawmen sooner or later.}
{308}{}{What about my payment?}
{309}{}{You didn't really eliminate the problem. But I'll give you 50 caps for the information.}
{310}{}{Hey, we agreed on 300!}
{311}{}{Better than nothing.}
{312}{}{Our deal involved *eliminating* the problem, not just delaying it. Take the caps and get lost before I change my mind.}
{313}{}{Mother...}
{314}{}{Fine, I'll leave.}
{315}{}{God damn... if you're fuckin' me around, it'll cost you your life. Get your peasant friends out of here before I change my mind.}
{316}{}{You made the right decision. I'll go release my kin from the pens.}
{317}{}{Hard to believe a peasant could solve all these problems. Even more perplexing is your diligence. Your people have been free for a while now.}
{1317}{}{Hard to believe a peasant woman could solve all these problems. Even more perplexing is your diligence. Your people have been free for a while now.}
{318}{}{In our village, people keep their word. If I promise to do a job, I do it. Adios, warden.}
{319}{}{Life in the village is boring. I just wanted some adventure. Bye, warden.}
{320}{}{I have other questions.}
{321}{}{You're just a sick bastard. Time to put an end to you!}
{322}{}{There might be something to your words. I need to think.}
{323}{}{Slavery remains slavery, no matter how you dress it up. You need to be stopped here and now.}
{324}{}{I didn't know about all this. Can you tell me more?}
{325}{}{Camp Winon has been overrun by savages.}
{326}{}{Damn savages! They're always in the way at the worst times. The hunting grounds are too important for the town. I'll have to send people to clear the camp.}
{327}{}{Great idea. I'll scout ahead and meet them there.}
{328}{}{Hold off on that. I might be able to handle it without your mercenaries' help.}

{330}{}{Who? Me? Uh...}
{331}{}{I don't need idiots here. Get lost.}
{332}{}{Lost... Ah! Yeah, I'm going home. Villa is my home, yeah.}
{333}{}{Wait... What are you saying? We recently got a batch of slaves from the Villa. Are you from there? No wonder they left you at home - even a shovel is too much for an idiot like you.}
{334}{}{What's a sho-vel?}
{335}{}{I think you're looking for your friends. They're here, in the pen. But if you want to see them, you'll have to do me a little favor. Understand?}
{336}{}{Oh! Yes! Friends!}
{337}{}{Yes, your friends... Listen to me, you blockhead. Go to the mine and go down. There's a big rat there. Kill the rat, and I'll take you to your friends. Got it?}
{338}{}{No, I want to see my friends now!}
{339}{}{Rat! Kill the rat! Kiiill!}
{340}{}{You won't see them until you kill the big rat in the mine. And don't piss me off any more.}
{341}{}{Ooh, angry man.}
{342}{}{Rat! Kill the rat! Kiiill!}
{343}{}{Mine... okay. Yes, no problems there.}

{344}{}{I'm an honored member of the Brotherhood of Steel. And I demand: release these innocent villagers, or the Brotherhood will bring its wrath down on you.}
{345}{}{Pff. Is everyone in your Brotherhood so pompous? Fine. But why the sudden change? You were the ones who demanded maintaining the labour supply by any means necessary.}
{346}{}{None of your business. That's what the command decided.}
{347}{}{Alright, I don't want trouble. I'll release the peasants.}
{348}{}{Excellent. Let's get the paperwork done.}
{349}{}{Make sure it doesn't happen again.}

{350}{}{Overseer Lash is beating the prisoners.}
{351}{}{I know. That's exactly why I value his firm hand. He won't hesitate to shoot to kill.}
{352}{}{Oh. Well, I guess reporting him for it won't achieve much.}
{353}{}{But he's not just beating them, he's injuring them. And for no serious reason.}
{354}{}{Whoa, slow down. What are you talking about?}
{355}{}{Lash forces the administrator to fake reports and write off injuries as accidents.}
{356}{}{I'm not liking the sound of this. I put Lash in charge of maintaining order, relying on his firmness. If he's really going overboard, I won't let it slide. Workers are too expensive to waste so carelessly.}
{357}{}{Maybe you should investigate and fire this menace?}
{358}{}{I don't need your opinion on what to do. But if you're telling the truth, replacing Lash won't be easy. I'll keep an eye out for a replacement, but I don't think I'll find one anytime soon... Here, take five caps for the information.}
{359}{}{Thank you, ...sir.}
{360}{}{[Leave silently]}
{361}{}{About Lash. I know a suitable replacement...}
{362}{}{...Alright. I'm not against getting rid of Lash. It'll be amusing to see one warden replace another. Though, I still don't get why you care.}
{363}{}{No reason.}
{364}{}{I just can't stand injustice.}
