{100}{}{You see a guard in front of you.}
{101}{}{You see a guard. He seems tired from a long trip.}

{110}{}{What should I do before the cargo ships?}
{111}{}{Want to play Caravan?}
{112}{}{Wake me up when the packing starts.}
{113}{}{This ore is really a real *hot* commodity in the south. Haha.}
{114}{}{Every trade trip could be your last.}
{115}{}{I don't know what I would do if there weren't a colony here.}
{116}{}{Talk to the chief, I'm just a caravan guard.}
{117}{}{We don't usually take tag alongs.}
{118}{}{Dust storms kept us in San Brahmin for a week.}
{119}{}{This trip is going to be tough.}
