{100}{}{You see a guard in front of you.}
{101}{}{You see an ordinary mercenary guarding the entrance to the colony.}
{102}{}{That would be right away.}
{103}{}{While this guard is distracted, you can sneak into the pen.}
{104}{}{Hrrr... Huh? Come on in...}
{105}{}{Stop, this is a restricted area. Entry only with the warden's permission.}
{106}{}{I warned you!}
{107}{}{This is a high-security area. Don't try to cause trouble.}

#Responses - good attitude
{110}{}{I'm watching you.}
{111}{}{Don't try to enter the pen without permission.}
{112}{}{What's behind that door? Try to get in and your dead.}
{113}{}{Enter only with the warden's permission.}
{114}{}{You can't go there.}

{120}{}{That's right, you have clearance.}
{121}{}{You can enter the pen.}
{122}{}{Go ahead, the door is open.}
{123}{}{Do you have clearance? Then go on in.}
