{100}{}{You see a prisoner in front of you.}
{101}{}{You see a prisoner from the colony. His appearance doesn't inspire confidence.}

#Dialogue
{200}{}{What do you want?}
{201}{}{Goodbye.}
{202}{}{What are you in for?}
{203}{}{(crooked grin) Murder.}
{204}{}{Just one?}
{205}{}{I've lost count. Highway 17 was littered with the bones of travelers my brothers and I robbed. Ah, those were the days.}
{206}{}{I doubt there were that many travelers.}
{207}{}{Alright, maybe I stretched the truth a bit. Hell, maybe I didn't kill anyone at all. But the roads have been rough these past few years. More folks are out there, but there ain't enough space for everyone. So they wander the highways, heading wherever they can.}
{208}{}{How did you end up here?}
{209}{}{We stole cattle from herders. Turned out the cattle were for influential people in Phoenix. They hired bounty hunters. Pinned our gang down in the old ruins. Real fighting machines, trained and equipped. I had to surrender. Now I regret choosing hard labor over execution.}
{210}{}{If we try a break out, will you help?}
{211}{}{Two against all the guards? You're crazy!}
{212}{}{Two against all the guards? Well, if you think about it, there's a chance, and if I die, so be it. Alright, I'm in. Can you get me a weapon?}
{213}{}{Got one. Hide it in your rags so no one sees.}

{214}{}{No can do. Okay, be ready to move.}
