{100}{}{You see Uncle Tom.}
{101}{}{You see a strong and serene colony resident. Judging by his appearance, he's been through a lot.}

{200}{}{Hello. I'm Tom. I live in this shack. So what brought you here?}
{201}{}{I'm new here. Just looking to meet people.}
{202}{}{Oh, real likely. You're trying to find your "uranium vein", ain't ya? Forget it. This city isn't what it once was on posters. If you wanna earn money, you'll have to work like hell.}
{203}{}{I'm not here to make money. I'm looking for my relatives.}
{204}{}{Well then, good luck. You'll need it.}
{205}{}{Can I ask you a couple of questions?}
{206}{}{Okay. Bye.}

{210}{}{What can I do you for?}
{211}{}{Nothing today. Goodbye.}

{220}{}{Who are you?}
{221}{}{They call me Uncle Tom.}
{222}{}{Is there anything else you want to tell me?}
{223}{}{No.}
{224}{}{Okay, forget it.}
{225}{}{Come on, tell me your story, I won't tell anyone.}
{226}{}{The thing is, I'd just rather not.}
{227}{}{Okay, forget it.}
{228}{}{Looks like you've been through hell, keeping your mouth shut like that.}  
{229}{}{Damn straight. I might be the only one who survived the labor camp and made it in this town. But the colonists still look down on me.}  
{230}{}{Why do they treat you like that?}
{231}{}{So, you're an ex-criminal?}
{232}{}{Got caught stealing mutfruit. I did my time in the camp and now I'm clean as a whistle, in the eyes of the world and myself.}  
{233}{}{Then why is your place such a mess?}  
{234}{}{You mean the writing on the walls? Local punks don't know how to blow off steam. They've made me their target. They know I'm not looking for trouble.}  
{235}{}{Thanks for being open, Tom.}  
{236}{}{If I were you, I'd rip their arms off. But hey, it's your call.}  
{1236}{}{If I were you, I'd rip their arms off. But hey, it's your call.}  

{240}{}{What are you doing in Flagstaff?}
{241}{}{I work odd jobs and spend my free time scavenging ruins for useful items. It's enough to get by.}
{242}{}{Got it.}
{243}{}{How long have you been living in this colony?}
{244}{}{Quite a few years, I think. I've lost track of time.}
{245}{}{I see.}
{246}{}{Roy Faber is dead. Shouldn't you be happy?}
{247}{}{Happy? I'm not sure... The colony taught me to obey and live by strict rules. It's harsh but effective. Faber's dictatorship brought order, but now others will fight for power. Who knows how it will end?}
{248}{}{That's something to consider.}
{249}{}{You're just a weakling, Tom. Take it.}
{250}{}{Do you know where I can get scraps or parts to repair the robot in the mine?}
{251}{}{I have some parts lying around here you can buy, but it's not much really.}
{252}{}{That's not enough, Tom. Where can I find more?}
{253}{}{Are you serious? You can't fix a complex machine with just this junk.}
{254}{}{Let me think. There are still unexplored areas in the old city, but they're dangerous. The easiest way is to get scrap metal from the scavengers in Garage City, west of here.}
{255}{}{Thanks.}
{256}{}{Got it.}

{260}{}{Did you hear about Mrs. Brandley's stuff going missing?}
{261}{}{Yeah, I heard about it. But I had nothin' to do with it.}
{262}{}{If you know who did, you should tell me.}
{263}{}{Listen, I don't want anyone getting hurt, okay? But that stuck-up lady had it coming.}
{264}{}{That explains a lot. Thanks.}
{265}{}{I'll pay you 10 caps if you tell me who did it.}
{266}{}{10 caps can loosen some lips. Do you have them?}
{267}{}{Not on me, but I'll bring them when I can. Bye.}
{268}{}{Here's 10 caps.}
{269}{}{Wait a minute, let me check outside... Yeah, it was the neighborhood kids. But remember, you didn't hear this from me. Take it easy on the kids.}
{270}{}{Thanks for your honesty, Uncle Tom. I promise no one'll get hurt.}
{271}{}{I'll deal with them as I like. And pray I don't turn you in as an accomplice of the young thieves.}
{1271}{}{I'll deal with them as I like. And pray I don't turn you in as an accomplice of the young thieves.}
{272}{}{Please, just tell me what you know. I want to help.}
{273}{}{Help? You just want to profit from someone else's misery. I won't be part of that.}
{274}{}{Your choice. Goodbye.}
{275}{}{Seems like you don't know anything. Goodbye, Uncle Tom.}
{276}{}{I promise I won't expose the thief. I just want to get her stuff back.}
{277}{}{Do you promise? (sigh) It was the neighborhood kids. I saw everything through the window. But remember, this conversation never happened.}
