{100}{}{You see a resident.}
{101}{}{You see one of the few residents of Garage City.}

{110}{}{Stay away from me.}
{111}{}{What do you want?}
{112}{}{Hello. How are you?}

{200}{}{Do you always break into other people's houses without invitation? It doesn't matter. I can't help you anyway.}
{201}{}{I just wanted to ask about the city.}
{202}{}{I don't need your help anyway.}
{210}{}{You again? Great. What is it this time?}
{211}{}{I want to ask about this city.}
{212}{}{Nothing.}
{213}{}{Why should I talk to you? I don't see the point in this. Just wasting breath on empty talk.}
{214}{}{I'll find a way to get you chatting.}
{215}{}{Okay, fine. Have it your way.}

{220}{}{Well, Garage City is a city of scavengers. Everyone here lives off the ruins, the 'mine' as most call it, which is controlled by Mr. Kogan's cartel.}
{221}{}{Thanks, that was a comprehensive answer.}
{222}{}{Scavengers?}
{223}{}{Just people who find old things and take them to the garage to be repaired.}
{224}{}{Who is this Kogan?}
{225}{}{He runs the scavenger cartel, and basically the entire city. You need to be respectful and careful in your choice of words with him.}
{226}{}{What kind of mine?}
{227}{}{It's just a ruins where old things are found. Go to the garage across the street and talk to Pete if you're interested.}
{228}{}{How do you like life here?}
{229}{}{It couldn't be worse. The cartel used to provide a good income, but not anymore. Even if you earn caps, there's nothing to spend them on since trade with other cities has almost stopped. If something doesn't change soon, the city won't last.}
{230}{}{It couldn't be worse. The cartel used to provide a good income, but not anymore. However, with the restoration of the Plant, things are looking up. I think the city still has a chance for a bright future.}
{231}{}{He used to run the scavenger cartel. But that's history now.}
