{100}{}{You see a scavenger.}
{101}{}{You see a man hardened by work and time.}
{102}{}{*Convulsively clutches chest*}
{103}{}{Arch...}
{104}{}{You've made a successful trade. Time to make Eugene happy with this news.}
{105}{}{You better not bother me.}

#First dialogue
{200}{}{What do you want, stranger?}
{1200}{}{What do you want, stranger?}
{201}{}{What's with the attitude?}
{202}{}{(spits as if by accident) We're not used to sissies here, sorry.}
{203}{}{Uh, alright...}
{204}{}{Why, looks like you've had a lot of practice. Bye wuss.}

#Re-dialogue
{210}{}{So what do you want?}
{211}{}{Nothing.}
{212}{}{Can you tell me about this settlement?}
{213}{}{I don't have time for an ass like you.}
{214}{}{Why is there a crossed-out star on your door?}
{215}{}{Rangers. These vile lovers of other people's goods want to take my most valuable thing - my son. I'm trying to shield him from this stupidity.}
{216}{}{Why do they need your son?}
{217}{}{They recruit the young and train them to become warriors and scouts. I didn't slave in these ruins just for my son to become a killer for someone else's cause. Let him scavenge like I did, and bring the benefits home, not to someone else.}
{218}{}{What's the situation with the Rangers?}
{219}{}{A gang of armed do-gooders trying to take over the entire area. They promise security and order in exchange for resources and recruits.}
{220}{}{What's the catch?}
{221}{}{Sounds reasonable.}
{222}{}{Life has taught us you can't trust people like that. They just hoard for themselves and share only the surplus. They're the same as raiders, just with prettier words.}
{223}{}{I see.}
{224}{}{Okay.}

#Quest
{250}{}{I'm here to take your son to the Rangers.}
{251}{}{Get out, Ranger bootlicker! You won't get shit here except a piece of crowbar between your eyes.}
{252}{}{So this is what you're teaching him - using a crowbar for harm rather than for good?}
{253}{}{I said get out!}
{254}{}{...He can do more with the Rangers. He can work on complex machinery rather than picking up dirty trash.}
{255}{}{*I* know what he needs!}
{256}{}{This city will die sooner or later, and Eugene will be left with nothing but rubbish.}
{257}{}{That might be true, but... So what? How do I know these Rangers really want what's best for Eugene? I don't believe them!}
{258}{}{Trust Eugene. Otherwise, watch him languish in this landfill. Do you really want this? At least with the Rangers he'll have some kind of future.}
{259}{}{Fine. You've got a real silver tongue mister... Take Eugene and take him to a 'better' place. But remember - if something happens to him, you'll answer for it with your head!}
{260}{}{You don't have to worry about anything. Eugene is in good hands.}
{261}{}{There's no convincing you.}
{262}{}{One more word, I swear, it'll be your fuckin' last!}
{263}{}{Listen to me - it'll be better for him.}

{270}{}{I can ransom Eugene. How much do you want for the contract?}
{271}{}{You'd never collect enough junk to trade for him in your entire life.}
{272}{}{Take a look at my proposal first...}
{273}{}{Then forget it.}
{274}{}{Hah! Get out of here.}
{275}{}{[Done]}
{276}{}{Finally this brat has done me some good. And what's that? A contract? I can't write! Whatever, I'll put a cross on it if that's what you want. Now take my son. But if anything happens to him, I'm gonna come for you! Clear?}
{277}{}{No problem.}
{278}{}{(scratching his unshaven cheek in thought)}
{279}{}{[More]}
