{100}{}{You see a girl in front of you.}
{101}{}{You see a half-naked girl.}

{110}{}{I didn't want to! They took off my clothes themselves!}

{200}{}{(sits sadly on the bed and slowly straightens her rags) So... thank you...}
{201}{}{How did you get involved with these guys?}
{202}{}{I don't know... I didn't think it would end like this...}
{203}{}{You're not very bright. That's clear.}
{204}{}{You'll be smarter in future, I think.}
{205}{}{Animal! Why did you have to kill them? They weren't as bad as you! Now everyone will avoid me!}
{206}{}{Isn't that better for you?}
{207}{}{No! How else am I supposed to make money in this dying city? I'm trapped here... It would be better if you hadn't come along... I wish this city didn't even exist! God...}
{208}{}{Um, you should calm down. Goodbye...}
{209}{}{Come to your senses, you fool. I did what I had to do.}
{1209}{}{Come to your senses, you fool. I did what I had to do.}
{210}{}{I didn't want this. But how else can I make money in this dying city? I'm trapped here... I wish this whole city didn't exist! God...}
{211}{}{Hmm... hmm... Oh, it's you... Hello.}
{212}{}{Hmm... hmm... Oh, it's you... Go away, I don't want to see you.}
{213}{}{Bye.}
