{100}{}{You see a prisoner of war.}
{101}{}{You see a man with signs of a recent beating.}
{102}{}{This is Pancho.}
{103}{}{And this is your house? A little old-fashioned, but peaceful. I like it here.}
{104}{}{You're doing well! I've only seen so many plants in Casa Nueva.}
{105}{}{Don't tell me we have to climb into some hole again.}
{106}{}{Phoenix... Although I grew up here, I somehow don't want to go back.}

{200}{}{Who are you? What do you want?}
{201}{}{It doesn't matter. Just sit and be quiet.}
{202}{}{Don't make noise, I'm not exactly "authorized" to be here. Why are they keeping you locked up?}
{203}{}{Is this some kind of trick to loosen my tongue? I already told you everything during the interrogation! I was hired by merchants to explore these lands. They hoped for new caravan routes. That's all. Leave me alone!}
{204}{}{Sounds a little lame. It's no wonder they think you're a spy.}
{205}{}{What else would I be doing in these barren lands? In the north, no one even has any idea there's a military fort here.}
{206}{}{I believe you. Do you want to escape? I could use a partner.}
{207}{}{Well, well. In your situation, lies won't help you. Stay here and don't make too much noise.}
{208}{}{I don't know if I can trust you, but I have nothing to lose. If I stay here, they'll hang me eventually. But without weapons and armor, I won't be much use. Do you know where their armory is?}
{209}{}{We'll figure it out as we go. Let's move.}

{210}{}{I already told you everything. Leave me alone!}
{211}{}{Your story isn't that convincing.}
{212}{}{It's okay, we're in this together. Do you want to escape?}
{213}{}{Sit here and stop making so much noise.}
{214}{}{It's too early to leave. Wait for my signal.}

{220}{}{Hey, where are we going?}
{221}{}{Don't make any noise. You'll find out soon.}
{222}{}{You'll have to wait here for me.}
{223}{}{I thought you weren't coming back. Are we movin' out?}
{224}{}{Yeah, it's time to go.}
{225}{}{No, it's not time yet.}
{226}{}{Show the way, amigo.}
{1226}{}{Show the way, amiga.}
{227}{}{Let's go.}
{228}{}{Okay. But don't forget about me.}
{229}{}{Don't go anywhere.}

{230}{}{You should hide your weapon.}
{231}{}{Sounds like a pretty bad idea. Okay, I'll put it away. Until the first occasion.}
{232}{}{You shouldn't show your hostility now.}
{233}{}{We'll have to take off this armor.}
{234}{}{Okay. It's really quite stuffy in there.}
{235}{}{That's good.}
{236}{}{Wait. Are you going to raise the alarm with the whole crowd? Well, no, I'd rather try to escape alone.}
{237}{}{Are you sure? It's your call.}
{238}{}{Okay, I'll leave the team somewhere safe and come back for you.}

{250}{}{What do you know about this place?}
{251}{}{I'm not familiar with these parts. But we shouldn't hang around here too long.}
{252}{}{Got it.}
{253}{}{Hermosillo is the skeletal remains of a very old city. No one lived here until Mexican troops set up their fort. Aside from crumbling ruins, military types, and a few stubborn civilians, there's nothing else worth mentioning.}
{254}{}{This is Phoenix, the largest city in this region. But don't get too comfortable; this place is a nest of vipers.}
{255}{}{You're in the slums of Phoenix. Not the best place to put down roots. Keep your weapon handy.}
{256}{}{Sewers? Uh... What exactly are we doing down here, anyway?}
{257}{}{I've been through this way a few times, but I've never been to the Tinsmiths' base. They don't like newcomers and consider them second-class citizens. However, if you're comfortable with technology, you'll probably get along with them.}
{258}{}{A small oasis on the trade route. Literally. The water pump still works here, so caravans readily stop for the night. There shouldn't be any problems with the locals if you don't meddle in their affairs.}
{259}{}{It's a peaceful but somewhat closed-off town. They mainly grow agave and corn... Listen, further west is Puerto Penasco. It would be nicer to go there right now. It doesn't take that long.}
{260}{}{I've never been to these parts. We've gone too far. Hey, I'm never gonna get to Puerto Penasco!}
{261}{}{The Cathedral of Fire is a local landmark. Although these people are devout, they also know how to handle a weapon.}
{262}{}{This place is creepy. It feels like someone is watching us...}
{263}{}{Are you kidding me? The Brotherhood base is gone!}
{264}{}{The Brotherhood of Steel runs the show here. Great guys, if you don't piss them off. Keep your gun in your holster and watch your language; they don't like cowboys and anyone giving lip.}
{265}{}{Some call this place the Devil's City. They say demons roam the streets here or something like that. Look, do we have to stick around here?}
{266}{}{So the monks hid this vault from the rest of the city years and years? Damn, what other secrets are they keeping?}

{300}{}{Tell me about yourself.}
{301}{}{Nothing much to tell. Call me Pancho if you like. I'm here on the orders of caravanners from the north. They needed guys to explore these southern lands. They hoped to find settlements suitable for trade here. But it looks like the idea is doomed to failure.}
{302}{}{Why were you locked up?}
{303}{}{The military didn't believe my explanations and decided I was a spy. In their minds, there are enemies all around.}
{304}{}{What are your plans now?}
{305}{}{First, we need to get out of Hermosillo, away from the garrison. And then we'll see.}
{306}{}{Then let's get out of here.}
{307}{}{Looks like you really can be trusted. Listen, I need to get to Puerto Penasco. It's an old port on the shores of the Sea of Cortez. I can't get there alone, maybe we can go together? I think there might be a job there for you too.}
{308}{}{What's at the port?}
{309}{}{My employers are there. I need to report on the work done... But I couldn't find out anything special. It would be good to collect more intel for them in Hermosillo.}
{310}{}{Sounds like a good deal. Great, I'm in.}
{311}{}{Good to hear, partner. You won't regret it.}
{312}{}{Then let's head to Puerto Penasco...}
{313}{}{I'll take you to the port, but if it's some kind of scam, you'll pay dearly.}
{314}{}{I'm telling you, this is just business. Don't worry, you'll get a cut of the pay too.}
{315}{}{Okay, let's head to Puerto Penasco...}
{316}{}{Sorry, but we're not on the same path.}
{317}{}{Okay, whatever you say. In that case, I suggest we get to the nearest populated area, and then we can part ways peacefully.}
{318}{}{Okay.}
{319}{}{Looks like we got away. What are you going to do now?}

{320}{}{Remind me where you need to go?}
{321}{}{Puerto Penasco is a port city on the Sea of Cortez.}
{322}{}{Then let's not waste time.}
{323}{}{I can't go there right now, sorry.}
{324}{}{I hate to disappoint you, but one of the ships in Puerto was blown up. That place is a smoking crater now.}
{325}{}{You must be joking. I'll believe it when I see it with my own eyes.}
{326}{}{Okay, then let's go to Puerto.}
{327}{}{Well, don't say I didn't warn you.}

{330}{}{What the... What happened here?}
{331}{}{So this is where you were supposed to meet your employer?}
{332}{}{Yes, but... What could destroy this entire port?}
{333}{}{It looks like the local "caravanners" were trading in something pretty lethal, doesn't it?}
{334}{}{Wait... okay... let me explain. I actually lied a little. It wasn't the caravan workers who hired me; it was the Brotherhood of Steel. And I wasn't scouting trade routes... but uh... rather, the military potential of the Mexican army. But what does it matter now? The Brotherhood's base has been destroyed!}
{335}{}{Looks like someone was left without their pay.}
{336}{}{Well, *we* were left without our caps. Shit, this trip turned out to be pointless.}
{337}{}{What are you gonna do now?}
{338}{}{I don't know. Without the Brotherhood, towns around these parts will decline... and without caps, there's no point in returning to Phoenix. I'll have to wander the wastelands in search of work.}
{339}{}{You know, we should stick together. I could use help on my... mission, and you could have a place at the Villa once everything settles down there.}
{340}{}{Do you think your kin will accept me? Well, it's worth a try. It must be great to have your own home and family. Let's go, partner. I've got your back.}
{341}{}{Come on, Pancho.}
{342}{}{You're right. You're completely screwed. I think we should go our separate ways from here.}
{343}{}{Are you going to leave me like this? After everything we've been through together?}
{344}{}{Yes. You've proven that you can't be trusted. Give me my stuff and go your own way.}
{345}{}{You know, I liked escaping from Hermosillo with you. I think there'll be a place for you at our Villa when everything settles down there.}

{350}{}{We're here. You'll have to wait a bit while I talk to my employer.}
{351}{}{Wait a minute, your employer is the Brotherhood of Steel? But you said that...}
{352}{}{Yeah, yeah, I lied about the caravan people. The Brotherhood of Steel is paying a lot of caps for scouting of the southern lands... Now wait here, it'll take a little time.}
{353}{}{[More]}
{354}{}{(Three hours later, Pancho comes out to you with a contrite look)}
{355}{}{How did the negotiations go?}
{356}{}{Those bastards don't want to pay! In their opinion, I didn't get any useful information. I had to talk about you and my rescue from captivity. And for some reason, they were interested in you. Go talk to Paladin Latham; he wants to see you. I'll rest here and wait for you.}
{357}{}{Damn. Okay, Pancho. See you in bit.}
{358}{}{Paladin Latham wanted to see you. Remember?}
{359}{}{Something's changed. Now we're not welcome here. I think we should get outta here before we get screwed.}
{360}{}{What's with the caps? Did you get paid?}
{361}{}{Yeah, but they said they don't want to work with you anymore. Sorry 'bout that.}
{362}{}{Bastards... Why did I go through so much? Looks like this trip was pointless.}
{363}{}{What are you going to do now, Pancho?}
{364}{}{I don't know. Since the contract with the Brotherhood is broken and I have no caps, I'll have to wander the wastelands in search of work.}
{365}{}{We'll talk about this later.}
{366}{}{No, I couldn't work things out with Latham.}
{367}{}{Pancho has left you temporarily.}
{368}{}{They didn't think our information about Hermosillo was of any use. We'll have to go back there and get better intel, if we want to get paid.}