{100}{}{You see a slot machine.}

{110}{}{This slot machine is out of order.}
{111}{}{Please insert coins to start playing.}
{112}{}{After a simple melody echoed through the hall, the slot machine came to life!}

{120}{}{Go through that stress again? The machine still has no prize coupons left.}
{121}{}{I've had enough of gambling.}
{122}{}{You're too weak to gamble right now.}
{123}{}{First thing is to heal.}
{124}{}{Due to its dilapidated state, the machine has response issues. With your limited skills, it's impossible to beat it.}
{125}{}{This will be very difficult.}

{130}{}{You beat the machine with }
{131}{}{ points.}
{132}{}{In total you earned }
{133}{}{ points out of 1000 possible.}
{134}{}{Yes!}
{135}{}{Yes!}
{136}{}{That's it!}
{137}{}{Ha!}
{138}{}{Get it!}
{139}{}{Who's the best here?}
{140}{}{You've lost. The machine gun has removed }
{141}{}{ points from your account.}
{142}{}{Hey!}
{143}{}{No!}
{144}{}{Damn!}
{145}{}{Damn tin!}
{146}{}{Damn it!}
{147}{}{Umm!}
{148}{}{Yes HOW is that possible?!}
{149}{}{This really pisses me off.}

{200}{}{Congratulations on your victory! You are our first winner! Take the prize coupon.}
{201}{}{I'll take the Super Strength coupon.}
{202}{}{I'll take the Ultra Perception coupon.}
{203}{}{I'll take the Extreme Endurance coupon.}
{204}{}{I'll take the Enhanced Charisma coupon.}
{205}{}{I'll take the Mega Intelligence coupon.}
{206}{}{I'll take the Hyper Agility coupon.}
{207}{}{I'll take the Multi-Luck coupon.}
{208}{}{I don't need this.}
