{110}{}{This jukebox is broken.}
{111}{}{The jukebox has been repaired and is ready to make those scary squeaky noises called music.}
{112}{}{The machine has been successfully repaired. Oh, how wonderful!}
{113}{}{The jukebox is completely out of order.}

{120}{}{*Boom boom*}
{121}{}{*Psh-sh-sh*}
{122}{}{*Padum-padum*}
{123}{}{*Shi-boom, shi-boom*}
{124}{}{*Sha-la-la*}
{125}{}{*Thrum-thump-thump*}
