{100}{}{You see a raider in front of you.}
{101}{}{You see your fellow raider.}
{102}{}{It was a good raid, wasn't it?}

#Response
{200}{}{It's time to attack. Are you still with us?}
{201}{}{Any suggestions before it gets started?}
{202}{}{Jackals are pretty weak, so we won't need any serious weapons. But they'll overwhelm us with numbers and swarm in packs in cramped corridors. It'd be nice to just toss a grenade in there or unload with a shotgun.}
{203}{}{Of course. Let's move.}
{204}{}{Let's go.}
{205}{}{What else?}
{206}{}{Beware of their poisoned blades and claws. And we need to get some light in here. There must be torches in these tunnels; it's worth finding them and lighting them.}
{207}{}{This is not a good time to chat. Keep moving.}
{208}{}{I didn't expect to see a ranger here. And still locked up. Looks like they're not as tough as everyone thinks they are.}
{209}{}{Do you think these were the last ones?}
{210}{}{Seems like it. These tunnels are cleared of filth. Now we just have to loot the corpses and head home.}
{211}{}{Okay.}
{212}{}{[More]}
