{100}{}{You see Miss Bates.}
{101}{}{You see a horribly disfigured woman.}
{102}{}{*Sobbing*}
{103}{}{My children will kill you and eat you.}

{200}{}{(In the darkness of the room, you see a woman on the bed; she is sobbing quietly, turned away from you).}
{201}{}{Hey, ma'am...}
{202}{}{Get out! Go away!}
{203}{}{Calm down, ma'am, I want to help you.}
{204}{}{Stop yelling, or those mutants will come running.}
{205}{}{No! Don't touch me! Aaah!}
{206}{}{Everything is fine. Those monsters are no longer a threat to you.}
{207}{}{Either you shut up, or I'll gag you. What's it going to be?}
{208}{}{(The woman stops screaming; in the silence, you notice terrible welts all over her body).}
{209}{}{Good God, you need a doctor. I'll help you get out of here.}
{210}{}{Follow me if you want to live.}
{211}{}{Why?}
{212}{}{What?}
{213}{}{Why would I go outside? This is my home. I won't leave.}
{214}{}{But... Then who are those monsters?}
{215}{}{Sherman, George, Edmond - they're good boys, you can be proud of them. My boys are golden.}
{216}{}{Are these cannibals and murderers your sons?}
{217}{}{Bitch, are you telling me these freaks are your kids?}
{218}{}{Ha, it's obvious you don't have children. They are my pride and joy. No one will break the Bates family. None of the strangers could.}
{219}{}{It's too late to boast about your family's achievements. Your degenerates are dead. All three of them.}
{220}{}{Killer! My boys just wanted to live. All the strangers tried to kill them. Just like you. Why are you so angry? (the woman turns her disfigured face sharply towards you) Since then, we haven't let anyone in. Outsiders bring death to us!}
{221}{}{I don't...}
{222}{}{This is so familiar...}
{223}{}{But that's okay. We are all one family. No one will break the Bates. There will be new ones. Someday. Ha! Ha ha! Ahaha! U-i-i-i...}
{224}{}{[Leave the mutant alone]}
{225}{}{You're just crazy.}
{226}{}{You've killed a lot of people. This needs to stop.}
{227}{}{You think I can't handle a few freaks?}
{228}{}{My sons will kill you! And any other stranger. Because we are family. No one can break the Bates. Ha! Ha ha! Ahaha! U-i-i-i...}
{229}{}{Actually, I understand you well. Strangers tried to break my village too. And that's why I'm not going to die just yet.}
{230}{}{Strangers tried to break my village too. I won't let you stop me. Your sons tried - and now they're dead.}
