{100}{}{You see a prisoner.}
{101}{}{You see a raider caught by justice.}
{102}{}{S-su-uka...}
{103}{}{*Cough cough*}
{104}{}{See you at the base. If we survive.}

{200}{}{(A half-naked raider sits on the floor in front of you; his body is covered in bruises) What do you want? I've already told you everything.}

{210}{}{What do you want?}
{211}{}{I'm the one asking questions here.}
{212}{}{Well, ask away. I still won't answer.}
{213}{}{Ben sent me. He wants to save you.}
{214}{}{So save me then, if you're worth anything. Or maybe Ben didn't really send you?}
{215}{}{Enjoy your stay.}
{216}{}{Are you just going to leave me like this?}

{220}{}{Why are they keeping you locked up?}
{221}{}{Because I'm dangerous, alright? The mayor needs to know something, but he's asking the wrong questions.}
{222}{}{What does the mayor want from you?}
{223}{}{All I know about is some Ben and his base. I have no idea what you're talking about.}
{224}{}{How did you get captured?}
{225}{}{I was spotted by some locals as I approached the city. They decided I was a highwayman and reported me to the mayor.}
{226}{}{Any ideas on how to get you out of here?}
{227}{}{Convince the mayor I'm innocent, give me a gun, and I'll just walk out of here.}
{228}{}{I've got bad news, buddy. Ben told me to finish you off if there's no other choice.}
{229}{}{(shows middle finger) Fuck you.}
{1229}{}{(shows middle finger) Fuck you.}
{230}{}{Now you definitely won't be able to get out of here.}
{231}{}{You're not helping yourself.}
{232}{}{We'll have to fight our way out. There's no other choice. Let's go.}
{233}{}{Great, let's bring some heat to this hole. But no heroics. I just need to get out of the city to safety.}
{234}{}{Let's go.}
{235}{}{Stay here while I scout outside.}

{250}{}{You're free. The mayor signed your release.}
{251}{}{Is it that simple? Listen, I need an escort, or the locals will tear me apart.}
{252}{}{Okay, let's go.}
{253}{}{I'll go alone. It'll be easier to cover my tracks.}
{254}{}{As you wish. By the way, Ben said if you talk, you'll be killed.}
{255}{}{(gulps) If it weren't for Ben and his thirst for revenge, I wouldn't be here. He sent me to find a weak spot in the city's defenses. But everyone here knows each other, so I got spotted easily. Now I have to return to Ben with nothing.}
{256}{}{Think he'll be angry?}
{257}{}{Yah. But if I don't return, he'll call me out as a traitor. That's even worse.}
{258}{}{You're screwed. Good luck.}
{259}{}{Maybe he'll understand your failure.}
{260}{}{We need to get out of town before they catch us.}
{261}{}{Right. Let's go.}
{262}{}{Looks like we're in the clear. I thought I'd have to ditch you and run. Are you really from Ben? I haven't seen you before.}
{263}{}{Yes, I'm new to his gang. That's why he sent me to find you.}
