{100}{}{You see Nestor.}
{101}{}{You see a tall blond man in a pristine robe. He delicately adjusts his glasses on his nose.}
{102}{}{Please put your weapons away. You won't need them here.}
{103}{}{Please leave your armor outside the clinic. We value cleanliness and order here.}

#First Meeting
{200}{}{Welcome, traveler. Hmm. I sense you have many questions and requests. Let me clarify something first: this is a clinic, where people are treated. And I am its manager, Nestor. So, are you sick? Injured? Or do you seek knowledge?}
{1200}{}{Welcome, traveler. Hmm. I sense you have many questions and requests. Let me clarify something first: this is a clinic, where people are treated. And I am its manager, Nestor. So, are you sick? Injured? Or do you seek knowledge?}
{201}{}{Well, I do have some questions actually.}

#Repeated Meeting
{210}{}{Alright. I'm listening.}
{211}{}{We've talked enough. I gotta go.}
{212}{}{Good to see you again.}
{213}{}{Why did you come back?}
{1213}{}{Why did you come back?}

#Medicine
{220}{}{I need healing.}
{221}{}{Strange. I don't see how I can help you. Many would envy your health.}
{222}{}{What a joy, Doctor! Somehow I feel better already.}
{223}{}{Oh, well... I can heal you. But, the treatment is very expensive. We'll have to spend at least }
{224}{}{ caps on your course. Can you offer that many in compensation?}
{225}{}{Yes. Exactly as many as needed.}
{226}{}{I don't have that many caps.}

{230}{}{Wait a minute, are you alright? You don't look well.}
{231}{}{Doctor, I'm hurting... I gotta shake this addiction!}
{1231}{}{Doctor, I'm hurting... I gotta shake this addiction!}
{232}{}{My heart aches to see you suffer. If you truly WANT to stop, I will do everything I can to help you.}
{233}{}{I do! What do you need to do this?}
{234}{}{Rehabilitation is an expensive and time-consuming process. I'm afraid the clinic cannot fully cover the costs at this time.}
{235}{}{Your clinic is just a way to shake people down for caps. I'm gone!}
{236}{}{I have nothing. I'll go ask someone who actually cares for help.}
{237}{}{I get it. I'll pay }
{238}{}{caps. Will that be enough?}
{239}{}{Hmm. It's not much, but what can we do - after all, you need to be saved.}
{240}{}{Before we start, I need to get some fresh air. I'll be back shortly.}
{241}{}{Here are the caps. When do we start?}
{242}{}{The sooner the better. First, you should take a bath...}
{243}{}{Take a bath? Wow!}
{244}{}{Acquired the Rehabilitation Perk.}
{245}{}{After a week of treatment and training, you have overcome your addiction and are stronger against future relapses.}

#Dialogue
{250}{}{You mentioned pre-war medicine and experiments?}
{251}{}{Oh yes. We have vaccinations against various diseases, a pre-war health enhancement procedure, and Vault-Tec equipment for specialized training used in bomb shelters. But none of us have tested out these procedures seriously yet.}
{252}{}{Sounds promising.}
{253}{}{The problem is the high cost. Such procedures are not essential and consume a lot of resources and time. Therefore, the clinic cannot provide these services at its own expense.}
{254}{}{How much does the health enhancement cost?}
{255}{}{Hmm. Let me calculate... It will cost }
{256}{}{ caps and require ten days of strict regimen. Expensive, but it buys you extra health.}
{257}{}{Uh, no. Thanks for the offer, Doc, but I don't have that many caps.}
{258}{}{I'm in, Doc. Here's the payment.}
{259}{}{Very good. First, let's conduct an examination...}
{260}{}{Hey, that tickles, doc!}
{261}{}{You have received a bonus to your hit points.}
{262}{}{After completing a course of treatment, you feel an unprecedented surge of strength!}
{263}{}{Can I take that health enhancement course again?}
{264}{}{It's possible. But the effect will be less noticeable. This time you'll need to spend more time and effort to achieve similar results.}
{265}{}{How much does it cost?}
{266}{}{It'll be }
{267}{}{ caps and will take two weeks.}
{268}{}{Ahh, that's just a little too much.}
{269}{}{Here's the caps. When do we start?}

### Quest to Clean Up Plantations

{300}{}{I need to talk to you about my friend Carlos.}
{301}{}{Of course. What happened to him?}
{302}{}{He's interested in old technology. Do you have any job vacancy for him?}
{303}{}{Intriguing offer. But where is he?}
{304}{}{He's currently in Two-Sun, awaiting your response.}
{305}{}{Two-Sun! So he's... a Tinsmith?}
{306}{}{No, no, he's from my village. The Tinsmiths accepted Carlos, appreciating his talents.}
{307}{}{You know, I'm not sure this is actually worth talking about. Sorry to bother you.}
{308}{}{Oh, interesting. You've got a good reputation. If you vouch for him, that's enough for me. Tell your friend we are ready to welcome him with open arms.}
{309}{}{Thanks!}
{310}{}{Oh, interesting. But I'm afraid we can't take chances with untested assistants right now.}
{311}{}{I understand. It's a pity my reputation isn't enough for you.}

{320}{}{I know about the infection that turns peasants into monsters.}
{321}{}{So you know...}
{322}{}{No need to roll your eyes and sigh heavily. It's your fault, isn't it?}
{323}{}{Yes, it's our mistake. And it's becoming harder to hide. But I ask for your understanding - we must avoid panic. It's already tough managing so many issues in the town.}
{324}{}{Why don't you declare a quarantine?}
{325}{}{That's unthinkable! People must tend the plantations, or they'll vanish into the sands. And if the population flees, looters will come and spread the infection further.}
{326}{}{Really?}
{327}{}{Besides, the risk of a general epidemic is still very low. All victims were near the laboratory where the leak occurred. Though insects are starting to spread it further.}
{328}{}{Is the risk really that low?}
{329}{}{I don't like the sound of insects spreading it.}
{330}{}{There's no point in panicking. We almost have a solution to the problem. We're just missing a few pieces of the puzzle.}
{331}{}{Hmm. I don't know whether to believe you.}
{332}{}{How did you even let this happen?}
{333}{}{We tried to solve the food problem by creating the most resilient, fruit-bearing flora. The infection is a side effect of experiments on plants and insects, which was hard to foresee.}
{334}{}{Hmm. I don't know whether to believe you.}
{335}{}{Are you going to correct your mistake?}
{336}{}{Of course. All our free time is spent doing calculations and experiments. But we still lack some data.}
{337}{}{I hope you can solve this problem. Otherwise, it could be really bad, for everyone.}
{338}{}{Wait. You won't create panic, will you? We need help, not more problems. We'll pay generously for your service.}
{339}{}{So what do you want from me?}
{340}{}{Is there anything I can do to help?}
{341}{}{We need help now more than ever. We'll pay generously for your service.}
{342}{}{What can I do for you?}
{343}{}{Our laboratory outside the town has become a breeding ground for infection. There are also laboratory documents and chemical reagents needed for our work to combat this there.}
{344}{}{Are you suggesting I go there?}
{345}{}{The laboratory is under quarantine, and residents are prohibited from approaching it. God knows what it's like now, but it's overgrown with vegetation. There are many insects and some infected may still be alive.}
{346}{}{But then I risk getting infected too, don't I?}
{347}{}{Yes. And that's the main problem. We'll give you an antidote for insect bites. But for airborne spores, you'll need a gas mask. We asked the Tinsmiths to make gas masks, but they have higher priority orders.}
{348}{}{Okay. I'll help you.}
{349}{}{Thanks. When you're ready, come to me. I'll get you to the laboratory without being noticed by the other residents.}
{350}{}{See you.}
{351}{}{You're like one of those mad scientists who created the nuclear bomb before the War. I'm not going to cooperate with you.}
{352}{}{I understand. You don't trust us and don't want to take risks. But now it doesn't matter who's to blame; it's more important to solve the problem. Think of the heroic service you'll render to the town. You will be remembered for generations. If you change your mind, come back.}
{353}{}{Bye.}
{354}{}{I can't figure out how to properly use this poison.}
{355}{}{Go to the agave plantations and dump it into the water tank. It will spread the insecticide via the irrigation pipes to all the infected crops.}#modified to make sense of in game actions - cambragol
{356}{}{Okay.}
{357}{}{Well, that's another matter.}

{360}{}{I'll help you. It's time to end this infection!}
{361}{}{Glad to hear that. We might not manage without you.}
{362}{}{I'm ready to go.}
{1362}{}{I'm ready to go.}
{363}{}{Wait. I need to grab a couple more things. I'll be back soon.}
{364}{}{Your task is to find laboratory documents and components for creating an insecticide that was being developed. The faster you can get in and out, the less likely you'll be affected by the infection. Here, take the antidote and a stimpak. Good luck.}
{365}{}{[Go to the laboratory]}
{366}{}{Here's the lab data and components.}
{367}{}{Finally! Now we're one step closer to victory. I need time to study and check the materials...}
{368}{}{Go ahead.}
{369}{}{...So this is the direction our colleague was taking? How did I not guess it right away! Yes, different specializations have an effect. I'm not good with insects, so I couldn't account for such symbiosis with fungal spores... Ah, Wang Chong, how I miss his boring maxims now.}
{370}{}{What are you going to do?}
{371}{}{First, I'll make an insecticide to stop the infection's spread. It won't take long; the reagents from the lab are well preserved. Please wait in the corridor for a couple of hours.}
{372}{}{Okay...}
{373}{}{Ready! It's a mixture of fungicide for fungal spores and insecticide for parasitic vectors. Add it to the water supply at the agave plantations while we deal with the cleanup at the greenhouses.}#added to make sense of ingame actions - cambragol
{374}{}{Okay.}
{375}{}{I dumped the poison into the water tank on the plantations. I didn't see any immediate effect though...}#modified to make sense of in game actions - cambragol
{1375}{}{I added the poison to the water supply on the plantations. I didn't see any immediate effect though...}#modified to make sense of in game actions - cambragol
{376}{}{It will take time of course. Well, performance must be in your genes. Your pest control work sets an example for the rest of the Followers. Someday we'll send a report to the Boneyard detailing this story.}
{377}{}{Sorry, four-eyes. But I was risking it for the promised caps, not for the sake of science.}
{1377}{}{Sorry, four-eyes. But I was risking it for the promised caps, not for the sake of science.}
{378}{}{All work must be paid. I asked the mayor for a bonus - 350 caps are due to you. Spend it wisely. And thanks again.}
{379}{}{I'm glad things worked out well.}

{380}{}{The lab's gone. Burned down in a fire.}
{381}{}{We saw the smoke. This is your doing, isn't it? (sigh) What a fool...}
{1381}{}{We saw the smoke. This is your doing, isn't it? (sigh) What a disaster...}
{382}{}{What's the problem? Isn't the source of the infection destroyed?}
{383}{}{There were other ways to destroy it! And now, all the scientific work that could have helped people in the future is gone!}
{384}{}{I didn't think of that.}
{1384}{}{I didn't think of that.}
{385}{}{It was the most effective way to halt the infection.}
{386}{}{Of course! Leave it to a wasteland wanderer to solve a scientific problem... My god. I need to calm down.}
{387}{}{?}
{388}{}{Sorry, your actions were commendable. Safety first, after all. But what if the infection appears somewhere else? Without the lab data, dealing with it will be a lot tougher. On the other hand, we now have plenty of time to prepare. So, in any case - thanks.}
{389}{}{The main thing is that the problem's solved. Good luck with your research, Nestor.}
{390}{}{Hey, hey! Am I gonna get paid? It wasn't that easy.}
{391}{}{Technically, you failed. I asked for documents and chemicals. But to be fair, I'll pay you 100 caps. It's enough.}
{1391}{}{Technically, you didn't complete your task. I asked for documents and chemicals. But to be fair, I'll pay you 100 caps. It's enough.}
{392}{}{It's better than nothing.}
{393}{}{You tricked me! That's the last time I help the Followers.}
{394}{}{Sorry it turned out this way. Goodbye.}
{395}{}{I came across these chemicals in the lab.}
{396}{}{These chemicals might be useful for making poison. Look around the lab carefully, there should also be detailed documentation and necessary equipment.}
{397}{}{Okay, I'll keep looking.}
{398}{}{Hmph, I thought the job was done...}

# Questions
{400}{}{Tell me about the Followers.}
{401}{}{There's myself. I run the clinic and chemical lab. And Teresa. She handles teaching and research.}
{402}{}{Also Diana recently joined us.}
{403}{}{Thanks, I had some other questions though.}
{404}{}{Who is the boss among you?}
{405}{}{We don't have bosses. Each Follower does their own thing, and together we form a board to resolve common issues. It's different from the rough, primitive relationships you're used to in the wasteland.}
{406}{}{How do you like Diana?}
{407}{}{We value every member, especially with such rich experience and motivation. And the data she gathered on her way here is priceless. I'm sure it'll be very useful.}
{408}{}{That's good.}
{409}{}{Unfortunately, she doesn't yet understand that in Casa Nueva, it's important to follow the rules and not go against the authorities. And yes, I know Diana survived thanks to you. Thank you.}
{410}{}{I see. Remind me who's who here?}
{411}{}{Why is Teresa so stubborn?}
{412}{}{Sorry about her. Working with children is tough, and almost no one has such experience these days. All she can do is read old books on child psychology and figure it out as she goes. And she also has to do research.}
{413}{}{Why do you need an assistant?}
{414}{}{I can't cope alone. I have a clinic and a chemical lab, though I'm not a chemistry specialist. Alexandra takes some pressure off me.}
{415}{}{Who was involved in the plantations?}
{416}{}{That man isn't with us. He sacrificed himself to science. Please, try not to ask about him to avoid hurting anyone's feelings.}
{417}{}{But there was another Follower, right?}
{418}{}{Wang Chong... He was unlucky. He spent most of his time in greenhouses. He didn't like talking to people, but he loved plants and science. Ultimately, that's what destroyed him when mutagenic spores took over his body. It's better not to ask about him, to avoid hurting anyone's feelings.}
{419}{}{Plantations are your thing too?}
{420}{}{Correct.}
{421}{}{Isn't it strange to grow plants in the desert?}
{422}{}{Believe me, we had our reasons for being here. This decision came from extensive preliminary research.}

{429}{}{What else do you need to know?}

{430}{}{Tell me about the clinic.}
{431}{}{Well, what can I say... We opened it primarily to serve soldiers from Puerto. This was part of our agreement with the military; otherwise, we wouldn't have been allowed here. Then local workers started coming for help.}
{432}{}{Okay. Can I ask you about something else?}
{433}{}{Where does all this equipment come from?}
{434}{}{The Tinsmiths made some to order. Some things were brought by caravans from different places.}
{435}{}{I see.}
{436}{}{I'm interested in your methods. In our Villa, it's hard to find anything other than herbs and mushrooms.}
{437}{}{I don't have any special prejudices against traditional medicine. It was useful in its time. But pre-war techniques are coming back. We've finally launched a vaccination system against wasteland disease. Isn't this a miracle?}
{438}{}{Where do you get your medicine?}
{439}{}{We make it ourselves, of course. For example, ethanol is easily produced from fire agave. And we sell or trade the resulting drugs for chemical raw materials.}

{440}{}{How do you like life here?}
{441}{}{Just wonderful. It's hard to find a better town these days.}
{442}{}{Good for you. I had some other questions...}
{443}{}{Even with all these regulations?}
{444}{}{What's confusing you about the regulations? They were in place before the War. The authorities had their reasons for restricting ordinary citizens, and those reasons need to be considered.}
{445}{}{Has a lack of will and totalitarianism ever made people truly happy?}
{446}{}{Has the average person ever been completely free? Such a scenario is only feasible in isolation, cut off from the world, and most likely, completely alone. So, the conclusion is simple: appreciate what we have.}
{447}{}{Hmm. It's worth thinking about.}
{448}{}{What can you tell me about your mayor?}
{449}{}{Alvaro has a heavy weight on his shoulders. He has to be responsible for the town only because there's no one else to do it. You shouldn't create problems for him.}
{450}{}{I didn't even think about it.}

{451}{}{Do you know anything about Vault 24? }
{452}{}{Certainly, it's in the ruins of San Diego. Our mission's founders came from there. But I've never been there myself because it's cursed by radiation, and will be for many generations to come.}
{453}{}{How did your founders live there then?}
{454}{}{Vaults were built to survive tough times after a nuclear attack. According to legend, the founders left the Vault to help the world be reborn. This sacrifice is appreciated by all Followers.}
{455}{}{I was there. The place is truly cursed. Everything useful has been scavenged long ago.}
{456}{}{Not surprising. I heard about the Great Exodus of ghouls south to the Glow. It looks like they found a suitable place for themselves. Let that radioactive land be lenient towards them.}
{457}{}{Yeah, something like that. Shall we talk about something else?}
{458}{}{I have a relic from that vault. Look, this is a copy of the overseer's diaries.}
{459}{}{Really? From Vault 24?! Please, let me see... Okay... Hmph... So the founders were forced to leave by the situation in the vault? How... common. The legend sounded more beautiful, more noble. Sadly, I now see they were just like everyone else. Thank you for this treasure of our past. I'll save it for our history.}
{460}{}{You're welcome. Shall we talk about something else?}
{461}{}{Shall we talk about something else?}
