{100}{}{You see Carlos.}
{101}{}{He looks like one of the Villa peasants, but something about him seems... different.}
{102}{}{Hello. I'm glad to see you.}
{103}{}{Don't talk to me. The whole town despises you.}

{200}{}{What a surprise! I'm glad to see you, }
{201}{}{.}
{202}{}{How did the Followers receive you?}
{203}{}{Very warmly. They are good people, unlike the Tinsmiths.}
{204}{}{Have you settled into Casa Nueva yet?}
{205}{}{There's plenty of work for me here. Plus, I signed an agreement for several years... Well, I marked it with a cross. Now I have a home and the means to survive. I won't starve, that's for sure.}
{206}{}{Cool. I'm glad everything worked out for you.}
{207}{}{You know, they gave me some first aid supplies, but I doubt I'll need them here. Here, there yours. You need them more than I do.}
{208}{}{Thanks, Carlos. Goodbye for now.}

{210}{}{Hello, }
{211}{}{. I'm glad to see you.}
{212}{}{You too. Goodbye, Carlos.}
