{100}{}{+}
{101}{}{-}

# Use with hands
{110}{}{Without power, this motorcycle won't go anywhere.}
{111}{}{Damn, I need to charge the power supply.}
{112}{}{The motorcycle won't start. The onboard computer is locked and requires an access key.}
{113}{}{Hmm, looks like we need a key here.}
{114}{}{This isn't the best time for a long ride.}
{115}{}{I have unfinished business.}
{116}{}{You stole this bike from highwaymen! They're probably not too happy about it.}
{117}{}{The motorcycle only seats two passengers.}

# Using items
{200}{}{Access granted. The motorcycle is now ready to ride.}
{201}{}{Not suitable.}
{202}{}{This vehicle uses a different power source.}
{203}{}{The motorcycle doesn't need oil yet.}
{204}{}{No parts need replacing on the motorcycle yet.}
{205}{}{The onboard computer doesn't need repairs yet.}
{206}{}{This skull will look great on the steering wheel, warning others not to mess with you.}
{207}{}{You can't do this unless you own the motorcycle.}
{208}{}{The steering wheel already has a skull decoration.}
{209}{}{You've repaired the broken headlight. Now it will light your way.}
{210}{}{All the lights on this motorcycle are working fine.}
{211}{}{This is more about the luggage container.}

# Using skills
{300}{}{Nothing to hack here.}
{301}{}{The onboard computer is already under your control.}
{302}{}{This is too difficult for you. Try to find the passkey.}
{303}{}{There's nothing to fix here.}
{304}{}{There's nothing to fix here. However, you haven't checked the trunk yet.}
{305}{}{You can't repair this motorcycle until you own it.}
