{100}{}{You see a slum dweller.}
{101}{}{You see a slum dweller. A sorry sight.}
{102}{}{You see a slum dweller. They pick at their ear.}
{103}{}{You see a slum dweller. They brush dirt out of their hair.}
{104}{}{You see a slum dweller. They lovingly straighten their filthy rags.}
{105}{}{You see a local resident. Their bald spots hint at the unhealthy conditions of the slums.}

{110}{}{I'm starving.}
{111}{}{If only I could catch a rat to fry for dinner.}
{112}{}{Hard to believe they once flushed *clean* water down the toilet.}
{113}{}{Empty talk just makes you hungrier.}
{114}{}{We need food.}
{115}{}{They say muties have been living in the sewers since the Great War.}
{116}{}{Another dead body was found on the next block.}
{117}{}{Don't gamble at the casino unless you want to end up a slave.}
{118}{}{The Fire Cult has eyes and ears everywhere.}
{119}{}{I wouldn't want to be one of those cultists.}
{120}{}{Hello.}
{121}{}{See you.}
{122}{}{I gotta go.}
{123}{}{Please don't cause any trouble.}
{124}{}{Do you ever take off that thing on your arm?}
{125}{}{What's a "TV"?}
{126}{}{Isn't a "mailbox" just a trash can?}
{127}{}{Sorry, I need to get back to doing nothing.}
{128}{}{This dirty water isn't even good for putting out fires.}
{129}{}{Is it true there's white, solid water in the mountains?}
{130}{}{The sky is always smoggy here.}
{131}{}{Haven't seen rain in years.}
{132}{}{The day's over and I'm still alive. That's luck.}
{133}{}{The scavengers have picked the ruins clean.}
