{100}{}{This is a slum dweller.}
{101}{}{You see a woman with a haunted look. She seems out of place here.}
{102}{}{Some bastard killed him!}
{103}{}{Huh? What? Do you have any food?}
{104}{}{Thanks for the food, sir.}
{1104}{}{Thanks for the food, senora.}

{200}{}{Hello. Can I help you with something?}
{201}{}{Probably not.}

{210}{}{Who are you?}
{211}{}{My name's Susie. My husband and I came from a small ranch out in the desert. Life there was too harsh, so we tried our luck in the big city.}
{212}{}{Bye, Susie.}

{220}{}{Why live in such a wretched place?}
{221}{}{We can't afford to live in the better areas. At least here, Vernon and his gang keep an eye on us.}
{222}{}{Who is Vernon?}
{223}{}{He's the community house manager. His office is down the corridor to the right.}
{224}{}{What's this gang about?}
{225}{}{They're a rough bunch. We steer clear of them. Their camp is in an old gym north of here.}
{226}{}{Got it. Bye.}
{227}{}{What was your name again?}
{228}{}{Who are you?}

{230}{}{What can you tell me about this area?}
{231}{}{It's the worst part of the city to live in.}
