{100}{}{You see a child of the slums.}
{101}{}{You see a child from the local slums. Life has taught them a lot.}

{110}{}{Hello.}
{111}{}{Do you have a gun?}
{112}{}{Dad promised to get a gun. Then I'll kill everyone who treated me badly.}
{113}{}{When I grow up, I'm gonna be a pimp.}
{114}{}{How are you?}
{115}{}{I don't know you.}
{116}{}{What do you want?}
{117}{}{Don't touch me.}
{118}{}{I'm not allowed to talk to strangers.}
{119}{}{Can you give me something?}
