{100}{}{You see a clothing merchant.}
{101}{}{You see a woman with a mohawk, dressed in a leather jacket. She knows modern fashion well.}

#Floating Lines
{110}{}{Throw away your rags, I have some decent clothes.}
{111}{}{You definitely need a change of image.}
{112}{}{I can sew up torn pockets.}
{113}{}{That jacket is splitting at the seams.}
{114}{}{Need shoes made from car tires?}
{115}{}{Fresh footwraps!}
{116}{}{This pajama will hide your many flaws.}
{117}{}{Clothes straight from pre-war warehouses.}
{118}{}{Felt hats and business suits are no longer in fashion.}
{119}{}{The fire worshippers know a thing or two about clothing.}

#First Dialogue
{200}{}{Hi. I have all kinds of casual clothes and a few items of workwear. Look around, don't be shy.}
{201}{}{Wow. This is better than the burlap my whole village wears.}
{202}{}{Whoa, these clothes must be a hundred years old. No wonder the locals look so creepy.}

{210}{}{So, did anything catch your eye?}
{211}{}{Not yet.}
{212}{}{Let's try this on...}

#Questions
{220}{}{Where do you get all these clothes?}
{221}{}{Half of the goods are handmade. The other half is brought by scavengers. Sometimes we find intact pre-war clothing warehouses, but nowadays not so much.}
{222}{}{Got it.}
{223}{}{Where do the Followers of Fire get their garments?}
{224}{}{Obviously, they make them themselves. And they aren't in a hurry to share this tech with ordinary mortals.}
{225}{}{So this was considered good clothing before the Great War?}
{226}{}{Apparently so. No one expected to walk around the ruins of Phoenix in it. Now people need different clothes - more practical, I guess.}
{227}{}{Uh-huh.}
{228}{}{I don't wanna wear old stuff like this...}
{229}{}{Hmm. I think our ancestors considered these suits to be pretty slick. Ah, old times... Alright, forget it.}

#Glasses
{230}{}{Is this all your merchandise?}
{231}{}{I can make something custom.}
{232}{}{Okay, I need something special to impress people then.}
{233}{}{I'll think about it.}
{234}{}{Okay... People these days aren't so impressed with clothes... But you're in luck. I have a pair of mirrored sunglasses in excellent condition. These are a rare find these days.}
{235}{}{You could definitely use that. Try covering your... uh... burns with these mirrored sunglasses. At least from a distance, you won't scare people.}
{236}{}{Yes, you definitely need it. I have some nice, stylish sunglasses. They're great for hiding your gaze, so no one will know where your looking or what your thinking.}
{237}{}{Put it aside for now, I'll think about it.}
{238}{}{Let's see what I can offer in return...}
{239}{}{Show me what you have.}

#Metal Armor
{240}{}{How about armor?}
{241}{}{That's not really my specialty. Ordinary townsfolk don't need armor, and few of them can even afford it. However, if someone needs it, I take orders with prepayment.}
{242}{}{I can put up 50 caps for something.}
{243}{}{Come on, you must have something in a secret stash for special clients.}
{244}{}{Listen, why do you need armor? Take a jacket instead; you're not going to war.}
{245}{}{Maybe so. Alright, forget it.}
{246}{}{Alright, forget it.}
{247}{}{Okay. But note - no returns. And no guarantees against bullets either.}
{248}{}{Just take my order. I'll take the risks.}
{249}{}{Thanks for the warning.}
{250}{}{Do you even know what 50 caps looks like?}
{251}{}{Wait, they were definitely here!}

#Follower's Robe
{260}{}{I need a Follower of Fire's robe.}
{261}{}{(looks around warily) Listen, I don't wanna know why your asking for that, but I don't want any trouble.}
{262}{}{I'll pay whatever you ask. And no one will know about our secret deal.}
{263}{}{Don't worry, our mutual friends sent me to you.}
{264}{}{Are you out of your mind? They'd kill me for selling one of their robes!}
{265}{}{You just lost a heap of caps. Congratulations.}
{266}{}{Sorry to bother you.}
{267}{}{Oh, that changes things. But I hope you know what you're doing.}
{268}{}{No problem. I'm just passing by.}
{269}{}{Alright, here's what I have. But don't ask again - it's too dangerous.}
{270}{}{Okay.}

#Vault Suit
{280}{}{Hey, is that the legendary vault suit? Where did you get it?}
{281}{}{Found it.}
{1281}{}{Found it.}
{282}{}{I inherited it from my ancestors.}
{283}{}{Lucky you. And of course, you don't know where to get more, right? Just know that these suits are a real find. If you find more, bring them to me, I'll pay *real* caps for them.}
{284}{}{Okay. But first, I want to look at your goods.}
{285}{}{I'm off to look for more right now.}
{286}{}{Here's a vault suit just like you wanted.}
{287}{}{Whoa! Finally, I can ditch this smelly jacket. Hey, don't forget the caps. And thank you.}
{288}{}{You're welcome.}
{289}{}{The caps are what matter. No thanks needed.}
{290}{}{What's the story with the vault suits?}
{291}{}{Well, it's an old legend. They say several vaults were built around Phoenix before the Great War. Some people survived the War there and then came out to rebuild the city. However, the stories aren't really clear.}
{292}{}{[Continue]}
{293}{}{Also, my parents had a vault suit. It's a special memory for me. Unfortunately, that suit has long since decayed.}
{294}{}{Interesting story.}
{295}{}{I have a vault suit for you.}
{296}{}{Another one? Wow, you sure do find the good stuff. Here's the caps.}
{297}{}{You're welcome.}
{298}{}{Great. But I need something else.}

#Attack on the Monks
{300}{}{What did you see during the attack on the Followers?}
{301}{}{Hey! Don't get me involved. I just sell clothes. And I didn't see anything.}
{302}{}{Then sorry, no more questions.}
{303}{}{Speak up, bitch, or I'll tear your miserable shop apart.}
{304}{}{What do you want? God... Okay, people in masks ran out of the alleys and started shooting at the monks. Then they just disappeared. They didn't touch anyone else. That's all I know!}
{305}{}{Thanks, now I don't have to tear your shop apart.}
{306}{}{I'll believe you. For now.}
{307}{}{Relax, you can trust me.}
{308}{}{Sure. But I really don't know anything about the attack. Leave me alone.}
{309}{}{I promise, you're not in danger.}
{310}{}{Sure... Either I displease the Followers, or their enemies.}
{311}{}{Well, anyway. Tell me how it happened.}
{312}{}{Alright... people in masks ran out of the alleys and started shooting at the monks. Then they just disappeared. They didn't touch anyone else. That's all I know.}
{313}{}{Hmm, interesting story. Thanks.}
{314}{}{I'll believe you. For now.}
{315}{}{The situation is becoming clearer.}
{316}{}{Things are coming into focus. Time to talk to Aaron about this.}
