{100}{}{You see a client.}
{101}{}{You see a client. He's already gone over his daily quota of alcohol and is beginning to get a bit too talkative.}

#Before drinking alcohol
{200}{}{(You see a smiling man with a grand mustache. His tanned skin and cowboy hat suggest a penchant for travel, and his sober gaze hints at an acute lack of alcohol in his system.)}
{201}{}{[Sit next to him at the counter]}
{202}{}{(turns toward you with a friendly grin) Hey partner, can you buy me a drink? That one-armed bandit took all my cash.}
{1202}{}{(turns around with a friendly grin) Hey, little lady, can you buy me a drink? That one-armed bandit took all my cash.}
{203}{}{Just buy you a drink, just like that? I'm not crazy mister.}
{1203}{}{Ask a lady for a drink? Have you no shame?}
{204}{}{Whatever you say, partner. But if you sit next to someone at a bar, be prepared to be asked for a drink.}
{1204}{}{Okay, lady. You win. Sorry for the old traveler's tactlessness. But that damn slot machine took my last caps. I can't buy you a drink either, beauty.}
{205}{}{Next time you might end up in a scrap, cowboy.}
{1205}{}{Everything is clear with you. Goodbye, loser.}
{206}{}{Sure, partner, I'll buy you a cup of 'get lost'...}
{207}{}{Sorry, no can do. Maybe next time.}
{208}{}{I understand.}
{209}{}{[Return to your important business]}
{210}{}{Alright, I'll get you a drink...}
{211}{}{Someone here must have balls of steel. By the way, my request still stands.}
{1211}{}{Someone here must have nerves of steel. By the way, my request still stands.}

#After drinking alcohol
# Quote from the movie "Prison Rock" 1957: "It's like angels are dancing on the tip of the tongue. It's a shame to even swallow this bourbon."
{220}{}{(takes a sip) Ahh, it's like angels dancing on the tip of your tongue. It's a shame to even swallow such alcohol. }
{221}{}{You talk like you have a lot of experience.}
{222}{}{Oh, these feet have trampled many miles around Phoenix and along the caravan routes. You interested?}
{223}{}{Actually, no, but go ahead.}
{224}{}{Definitely. Tell me about your travels.}
{225}{}{Thanks for the drink.}
{226}{}{Have fun, I need to get some fresh air.}
{227}{}{Enjoy it, buddy.}
{228}{}{Maybe just enjoy it in silence.}
{229}{}{Thanks. It's not often you meet someone willing to share with a stranger.}

#Story
{230}{}{I work for the caravans as a free mercenary. Sometimes I travel alone in search of... fortune. Everyone knows me as an excellent marksman and desert survivalist. So, I've always got work if I need it. But travel... It's becoming increasingly dangerous.}
{231}{}{What do you mean? Why the change?}
{232}{}{You mean they used to be safe?}
{233}{}{Dust storms have become more frequent. Some say it was much worse years ago. But now, during the bad season, entire settlements are swept away, and if you're caught in a storm in the open desert, your chances of survival are fifty-fifty at best. What can I say about giant tornadoes or clouds of poisonous glowing dust from the west? Apparently, nature doesn't want to give the world back to men.}
{234}{}{Yeah, nothing worse than a serious dust storm on the road.}
{235}{}{Ha, an experienced survivalist huh? Scared of the wind and sand?}

{236}{}{Dust storms? They ain't the worst thing you'll face on the road. You see them coming, you can skirt 'round. People, though? They're way worse. Out on the caravan routes, we'd find bodies - stripped by raiders of anything worth a damn, even the meat on their bones. Picked clean.}
{237}{}{I'd eat human too if it came to that. In the wasteland, food's food, right?}
{1237}{}{I'd do it too. In the wasteland, food's food, right?}
{238}{}{Really? I wouldn't. Human meat's more dangerous than leaves or bugs. But, I wouldn't judge if someone was starving.}
{239}{}{Why are you even talking about this?}
{240}{}{That's sick. Even if you were starving, what kind of animal does that?}
{241}{}{Plenty of savages out there, especially the highwaymen on Route 10. They act like they own the road. Pay a toll or die. Some don't even bother asking - they just take everything.}
{242}{}{Why are you bringing this up?}
{243}{}{You're exaggerating. The desert can't be that bad.}
{244}{}{Oh, there's 'civilized' places out there, sure. But they're few and far between. Most are closed to travelers, keeping their heads down, just trying to survive in the worst of conditions.}
{245}{}{Why are you bringing this up?}

{250}{}{(sighs, takes a sip after a pause) Well... there was this one time...}
{251}{}{Come on, buddy. Let's hear it. This is a bar, after all.}
{1251}{}{Tell me, oh great survivalist, what's weighing on your mind? We're in a bar, aren't we?}
{252}{}{Heh, thought we were wrapping up, but here we go.}
{253}{}{...We went down to Gila Bend to trade, but the place was abandoned. Had to turn back to Phoenix empty-handed. Ran out of supplies on the way, and... the desert didn't give us a break. No animals, no plants. Just heat and shifting sands, messing with our path.}
{254}{}{How'd you make it out?}
{255}{}{Ran into this guy from Phoenix, out searching for a new home. Unlike us, he still had food.}
{256}{}{So, what happened? You rob him?}
{257}{}{One of the guards... he snapped. Couldn't handle the hunger. Stabbed the poor guy 27 times before he finally stopped. We just... watched. Didn't lift a finger.}
{258}{}{Hey, you made it out. You can't control what someone else does.}
{259}{}{You think so? I'm not so sure. But you know what, I'm glad I picked you to talk to. Feeling a bit lighter now. Even though... I could've stopped him. And maybe... if I'd planned better, we wouldn't have been starving in the first place. This'll haunt me for a long time.}
{260}{}{In the wasteland, it's all about survival. Morals don't mean much out there. Just try to move on.}
{261}{}{After hearing that, I'd rather forget I ever met you. Get lost, bandit.}
{262}{}{How do you even know how many times he stabbed him?}
{263}{}{I was counting.}
{264}{}{You just stood there... No wonder you're drowning in this bar. I hope you never find peace.}
{265}{}{Yeah... you're right. But isn't that what bars are for? Talking about the things that tear you up inside?}
{266}{}{Forget it. I'll... go try my luck at roulette.}
{267}{}{Good riddance. Hope I never see you again.}

{268}{}{We stumbled upon an old motel. It didn't look completely abandoned. In fact, the restaurant doors were wide open, with a poster for... Nuka Cola calling out to us.}
{269}{}{Was anyone inside?}
{270}{}{There was water and food. We were starving and parched... everyone just dove in, drinking and eating like crazy. I tried to warn them, but the water turned out to be... poisoned... and the place was crawling with traps. I was the only one who made it out alive.}
{271}{}{Who would do something like that?}
{272}{}{Raiders? Cannibals? The souls of those who died during the Great War? I don't know. But there are... stories... rumors about that ghostly motel.}
{273}{}{You survived. You kept your cool even through that nightmare.}
{274}{}{Do you really think I should be proud of that? I guess I picked the right drinking buddy. I feel a bit better. Just wish I could've gotten my caravan mates out too.}
{275}{}{Yeah, it's a tough story. Hang in there, buddy.}
{276}{}{Well, I'm not sure I can just take your word for it. Sounds like quite the tall tale.}
{277}{}{Or maybe there was no motel? You being the only survivor... maybe it was all a trap you set yourself.}
{278}{}{You're not the first to suggest that. People whisper behind my back, saying I abandoned or even killed my friends. But that doesn't make sense. It's harder to survive out in the desert alone than with a group.}
{1278}{}{You're not the first to suggest that. People whisper behind my back, saying I abandoned or even killed my friends. But that doesn't make sense. It's harder to survive out in the desert alone than with a group.}


{280}{}{I can't shake that story about the ghost motel. Where exactly is it?}
{281}{}{You can imagine how rattled I was. That damn motel is out in the desert, swallowed by the sands. I can't even find it on a map - I just know it's... lurking... somewhere southwest of Phoenix.}
{282}{}{I just wanted to know how to steer clear of that nightmare. Take care.}
{283}{}{Would it help if I went looking for it?}
{284}{}{You can't bring the dead back, but you might save other travelers. Just be careful - it'd be a real shame to lose your soul in that... cursed place.}
{285}{}{It's not cursed. Come on.}
{286}{}{Can you remind me which direction that creepy motel was in?}
{287}{}{It's just out there somewhere in the desert. I couldn't pinpoint it on a map. All I know is it's southwest of Phoenix - three, maybe four days' journey.}
{288}{}{Right. Thanks.}
{289}{}{That creepy motel you mentioned? It was pure hell. I still get chills just thinking about it.}
{290}{}{Whoa! Did you actually find it?}
{291}{}{Yeah, I did. Turned out it was run by a twisted family of cannibal freaks. Clever bastards, but they're out of the game now. For good.}
{292}{}{That's a relief... I feel like a weight's been lifted off my soul. I'm really glad you avenged my friends - and probably a lot of other poor souls too. Thank you, partner. Here, take a bottle on me.}
{293}{}{Come on.}

