{100}{}{You see a dealer in front of you.}
{101}{}{You see a sharp-dressed man deftly shuffling cards.}
{102}{}{Uh, I'm afraid you can't hold the cards in THAT...}
{103}{}{Sorry, sir, I'm not allowed to serve you.}
{1103}{}{Sorry, ma'am, but I'm not allowed to serve you.}

#Acquaintance

{200}{}{(A neat man with a serious look deftly shuffles a deck of cards at a card table.) Are you playing nuclearjack?}
{201}{}{Not today.}
{202}{}{No, I don't know the rules.}
{203}{}{I'm in. But first, explain the rules.}
{204}{}{It's a variation of blackjack. You need to collect 21 points with as few cards as possible. Cards with nuclear bombs add a twist. Get 21 points, and you can "bomb" the deck. It requires more brains than roulette or slots. The stakes are higher if you're willing to risk it.}
{205}{}{I'm sure.}
{206}{}{Are you playing?}
{207}{}{Yes.}
{208}{}{No.}

#Betting

{210}{}{New game. Place your bets.}
{211}{}{ chips)}
{212}{}{I don't play.}
{213}{}{I'd love to join, but I don't have any chips.}
{1213}{}{I'd love to join, but I don't have any chips.}
{214}{}{My bet is 10 chips.}
{215}{}{My bet is 20 chips.}
{216}{}{My bet is 30 chips.}
{217}{}{My bet is 40 chips.}
{218}{}{Bets accepted. Dealing now.}
{219}{}{Let's begin.}

{220}{}{Remind me of the last score?}
{221}{}{The score is }
{222}{}{ to }
{223}{}{ in your favor.}
{224}{}{ in favor of the casino.}
{225}{}{Okay. Let's continue.}
{226}{}{My bet is 50 chips.}

{230}{}{(The dealer places two cards face down, then turns over one, showing a value of }
{231}{}{ points)}
{232}{}{Hit me.}
{233}{}{(You were dealt two cards with a value of }
{234}{}{ points)}
{235}{}{[More]}
{236}{}{(Your hand contains cards worth }
{237}{}{ points. The dealer's open card shows }
{238}{}{ points.) What's your move?}

{240}{}{I fold.}
{241}{}{The first player leaves the game. Half the bet is lost.}
{242}{}{Gentlemen, I take my leave.}
{243}{}{I double down.}
{244}{}{Double your bet. You can only increase the bet once per game.}
{245}{}{Double your bet.}
{246}{}{[Continue game]}
{247}{}{Pass.}
{248}{}{The first player passes the card. Continuing the deal...}
{249}{}{[Continue game]}
{250}{}{More.}
{251}{}{First player draws a card...}
{252}{}{[Continue game]}

{260}{}{Player 1, Nuclearjack! Would you like to play again?}
{261}{}{No, thanks.}
{262}{}{Oh yeah, I want to play again.}
{263}{}{Casino, Nuclearjack. Your bet is lost. Do you want to get even?}
{264}{}{Yeah, I just need to get even.}
{265}{}{No, I better not.}
{266}{}{Player 1, Lose. Your bet is lost. Do you want to get even?}
{267}{}{Casino: Loses. Do you want to continue?}
{268}{}{It's a draw. Players keep their bets. Do you want to continue?}
{269}{}{Card limit reached.}
