{100}{}{You see an old friend.}
{101}{}{You see one of the Followers of Fire.}

{200}{}{(You see your old acquaintance, who used to spy on the rangers; he seems depressed and weak-willed, his gaze dimmed, and his former bandit mannerisms a thing of the past.)}
{201}{}{Well, well, imagine meeting you here...}
{202}{}{(His cloudy eyes rise heavily, barely distinguishing you) You... I remember you. The Holy Fire must have brought us together that day. Thanks to you, I am here among the Followers. Thank you.}
{203}{}{Uh, sure. It's nice to be a part of someone's 'spiritual' growth.}
{204}{}{I never would have thought you'd make it here. Anyway.}

{210}{}{I have to pray. Please leave me.}
{211}{}{Bye.}

{220}{}{How did you make it out of Parker Dam?}
{221}{}{Don't ask me about such nonsense. I'm above it now.}
{222}{}{Then stay alone with your... prayers.}
{223}{}{What's it like to be an acolyte in the Church of the Holy Fire?}
{224}{}{Work and prayers. That's all we need. Until I'm ready for something more important. Only my mentor can determine this.}
{225}{}{Hmm, let me look at your pupils.}
{226}{}{What are you doing? Keep your hands to yourself, villager.}
{227}{}{Alright then... later.}
{228}{}{Looks like you're being drugged here, huh?}
{229}{}{Yeah... they give us pills with lunch to help us relax. Part of the initiation, you know? We're supposed to clear our minds of arrogance... at least, that's what my mentor says... Ugh, I think I need to find a toilet...}
{230}{}{Okee, dokee, better leave you to it.}
