{100}{}{You see Matthias.}
{101}{}{You see one of the Followers. He seems to be deep in thought.}
{102}{}{Go ahead, acolyte.}
{103}{}{This man quickly utters prayers for the salvation of all mankind.}
{104}{}{. . .}
{105}{}{Now the church will return to its original mission. You have my undying gratitude.}
{106}{}{So, the operation failed? But this is not the end. For the good of the entire city, Aaron and his Advisor must be killed.}
{107}{}{So, the operation failed? But this is not the end. For the good of the entire city, Aaron must be killed.}
{108}{}{So, the operation failed? But this is not the end. For the good of the entire city, the Advisor must be killed.}

{200}{}{How dare you disturb me while I'm praying? Go away.}
{201}{}{Uh...}

#Questions
{210}{}{Please do not disturb me while I'm praying.}
{211}{}{Whatever you say.}
{212}{}{Who are you?}
{213}{}{I'm Matthias. Now get out and close the door behind you.}
{214}{}{But...}
{215}{}{What are you doing here, Matthias?}
{216}{}{Talking to you, wasting my time. Get out.}
{217}{}{Wait...}
{218}{}{It didn't really look like you were praying.}
{219}{}{Urgh... If my meditation wasn't constantly being disturbed, I would be more focused.}
{220}{}{So, prayer or meditation? You seem confused.}
{221}{}{Hmm. Your persistence is like the persistence of a louse in an old cassock. What do you want?}
{222}{}{I want to talk.}
{223}{}{Nothing, nevermind.}

{230}{}{This is ridiculous. If you need answers, speak to the preachers in the hall on the first floor.}
{231}{}{I'll do just that. Goodbye.}
{232}{}{Certainly, Brother Matthias. I'm sorry to trouble you.}
{233}{}{Where should I go to find a mentor?}
{234}{}{Obviously you don't need one.}
{235}{}{Before asking such a question, think about whether you need one.}

#Rebel Quest
{250}{}{I come on behalf of Marcos.}
{1250}{}{I come on behalf of Marcos.}
{251}{}{Marcos... Who is this?}
{252}{}{What, didn't he contact you about me?}
{253}{}{Your uncertainty is like an atomic groan in the belly of a mushroom cloud. Leave and come back only when you have organized your thoughts.}
{254}{}{Uh, okay...}
{255}{}{Come on, you know who I'm talking about. The guy who lurks in the subway, and wants the same revenge as you.}
{256}{}{Yes, of course... Revenge... The base feeling of atomic beings eking out a miserable existence. Don't you dare compare me to him, an inhabitant of stinking sewers. My entire being is depressed just by the thought of what Aaron did to the Church of the Holy Fire.}
{257}{}{So you're against Aaron's policies?}
{258}{}{We don't care about your motives. The main thing is that we have the same goal.}
{259}{}{Previously, the church brought the light of pre-war wisdom to this broken world. We did not participate in any bloodshed, our banner was not a symbol of tyranny. But Aaron sold his soul to the devil. I can't stand it anymore.}
{260}{}{Okay. What can we do to fix it?}
{261}{}{Eliminating Aaron isn't the point. After all, the church is now much larger than it seems. We are connected with other forces in Arizona, our banner is setting entire communities on a new path. You can't just eliminate one person to stop the whole process.}
{262}{}{What are you proposing, Prior Matthias?}
{263}{}{We must destroy the entire church. This sounds crazy. But there is such a possibility. Beneath the cathedral there are underground levels where scientists have been creating a new weapon for several years. It is capable of destroying this entire cathedral.}
{264}{}{Wouldn't a weapon like that harm the rest of the city?}
{265}{}{The Church has already done enough damage to this fragile world. Don't worry, I assure you the city will remain intact.}
{266}{}{Why don't you do it?}
{267}{}{I'm not allowed to go down without a good reason after I tried it once already. But you have the advantage of surprise.}
{268}{}{Probably not the worst idea, but I'd like to survive.}
{269}{}{Find the fuses in the professor's office. Once they are activated, you'll have a few minutes to escape from the cathedral.}
{270}{}{Okay then. But how can I get there? It's a secured area, right?}
{271}{}{I will give you the key and Follower's robe. Introduce yourself to the guards as a newcomer who has been sent to report to the professor.}
{272}{}{Give me the key and the robe. I'm going straight to it.}
{273}{}{May the Holy Fire forgive us. Amen.}
{274}{}{Uh, whatever you say, Prior. Goodbye.}

{275}{}{Aaron and his Advisor are well protected, but if you act quickly and decisively, you'll be strong enough. We need to take them by surprise in different parts of the cathedral so that they cannot unite. I'm will make sure that the peaceful monks do not interfere with your attack.}
{276}{}{Great. I'll give the signal to attack. In the meantime, warn the monks.}
{277}{}{Is it possible to do this without bloodshed?}
{278}{}{Alas, Aaron and his allies will not give up without a fight. But there is another option. Under the cathedral there are underground levels where the Advisor has been working on a new weapon for several years. It is capable of destroying this entire cathedral.}
{279}{}{This is a little too much. We'll just take over the church. I'll give the signal to attack. In the meantime, warn the monks.}
{280}{}{This is a crazy plan. But that's why I like it.}
{281}{}{You are the last hope for peace. I'm will give you the key to the basement where the Advisor is located, and I'll give a signal to my like-minded people so that they do not disturb you. Take action.}
{282}{}{Great.}

# Aaron's Quest
{300}{}{I think we have something to discuss. This concerns recent attacks on monks.}
{301}{}{Obviously, your search has reached a dead end if you talk about it with random people you meet.}
{302}{}{To be honest, it has. Maybe you can give me some advice?}
{303}{}{Don't despair, but still, watch your back. It's not just the acolytes at risk - anyone who crosses our enemies can become a target.}
{304}{}{You're no help.}
{305}{}{Uh, thanks for the "advice."}

{310}{}{On the contrary. It is clear from the records in the library that *you* followed the acolytes' routine.}
{311}{}{Of course. As one of the cathedral's caretakers, I have access to this information. And if you don't want to be burned at the heretical stake, then I advise you to find something more significant before you begin accusing me. Now disappear.}
{312}{}{Not so fast. I also know that you sent encrypted messages through the radio.}
{313}{}{But...}
{314}{}{Actually, there *is* a clue. You sent encrypted radio messages. To whom and why?}
{315}{}{As the caretaker of the cathedral, I cannot allow outsiders to hear my communications. But where did YOU get access to the radio station? This is highly suspicious.}
{316}{}{You should be concerned about the library records now. You were clearly keeping an eye on the acolytes.}
{317}{}{It's not what you think...}
{318}{}{I can convince Aaron to conduct a full search of your belongings and contacts. What do you say to that?}
{319}{}{You're testing my patience, atomic worm. Get out.}
{320}{}{You're gonna come off worse in this.}
{321}{}{Ah, holy heavens! You've only recently come to this cathedral, and you're already digging deeper than the Vault-Tec prophets.}
{322}{}{Vault... What?}
{323}{}{So you admit that you leaked information to the enemies of the church?}
{324}{}{Don't disturb the peace of these quarters. If you need answers to your questions, I'll give them in a quieter place. Meet me in the confessional on the first floor. Don't worry, I haven't been able to run for a long time.}
{325}{}{Okay. But you better be there... no tricks.}
{326}{}{Of course, the walls have ears here.}

# Dialogue in the confessional
{330}{}{I have to say, I didn't expect a newcomer from the wasteland to be able to solve this case. Up until now, I had managed to hide my actions even from Aaron.}
{331}{}{So why is Aaron's 'loyal' servant helping his enemies?}
{332}{}{Under Aaron's leadership, the church has changed its beliefs. The stronghold of holiness and wisdom it once was, has become a receptacle for sin. I can't stand it anymore.}
{333}{}{Tell me the story.}
{334}{}{Ten years ago, we were a peaceful church, isolated from the people. We preserved pre-war relics and knowledge to pass them on to those who would be worthy to receive them.}
{335}{}{Apparently such people were found?}
{336}{}{New people came from the south, though they turned out to be less than worthy. They lured our priors to their side and, together with the help of the church, staged a revolution in the city. Aaron became the Lord of Phoenix, although before that he was only a mid-level cleric.}
{337}{}{And you're not happy with that?}
{338}{}{Our mission was to guard ancient knowledge. We should have been more careful about who we allowed near them. We made a terrible mistake, for which we will all end up in the Nuclear Hell.}
{339}{}{Who are the people who are attacking the acolytes?}
{340}{}{Who are the people you help?}
{341}{}{It's a long story... Since the time of the revolution, a group of rebels who call themselves the "Liberation Party" has been active in Phoenix. Until now, they tried to keep a low profile in order to gather strength in order to, eventually, overthrow Aaron. Although I do not agree with them on everything, we had an agreement to drive the church from the city.}
{342}{}{Now explain why I shouldn't upset your plans?}
{1342}{}{Now explain why I shouldn't upset your plans?}
{343}{}{But why are you, a prior of the Cathedral, helping its enemies?}
{344}{}{I don't care what motivates you. Just tell me, why shouldn' I just close this case right now?}
{345}{}{Sooner or later, Aaron will figure out the source of the leak. But it's not my life that worries me, but rather, the mission of the church.}
{346}{}{Trying to get me on your side?}
{347}{}{Yes. Now, I suggest you meet with the rebels and discuss everything face to face.}
{348}{}{This is stupid. I'm just gonna tell Aaron everything.}
{349}{}{Then you leave me no choice. May the Holy Fire forgive us...}
{350}{}{Uh...}
{351}{}{Okay, I'm in. It'll be interesting to hear the other side of this conflict.}
{1351}{}{Okay, I'm in. It'll be interesting to hear the other side of this conflict.}
{352}{}{So be it. Find the rebel headquarters under Union Station. You can only get there through the sewers. Tell them you're sent by me, and in the meantime I'll try to get a message to them. Good luck.}
{353}{}{See you, Prior Matthias.}
{354}{}{I've changed my mind. I'm just gonna tell Aaron everything.}
{1354}{}{I've changed my mind. I'm just gonna tell Aaron everything.}
{355}{}{Go ahead, acolyte.}
{356}{}{Okay.}
{357}{}{I need to know which of the Red Cardinals is leaking information about the gang to you.}
{358}{}{What an outrageous question! Even if I knew, I certainly wouldn't tell you.}
{359}{}{But you don't deny it, do you?}
{360}{}{We have spies all over the city. And we get information from them in many different ways. There's no surprise here.}
{361}{}{That's all I needed to know for now.}
{362}{}{I can trust you, right? Murphy's one of ours. He infiltrated the gang and climbed the ranks to steer those poor fools onto the right path.}
{363}{}{It's good that you warned me. Thanks.}
