{100}{}{You see a beggar.}
{101}{}{You see an ordinary street dweller.}
{102}{}{You witnessed a crime.}
{103}{}{Why am I standing here? We need to remove witnesses!}

{110}{}{Am I really a murderer?}
{111}{}{I didn't mean for this to happen!}
{112}{}{She made me do it.}
{113}{}{If she hadn't flashed those caps...}
{114}{}{Why the hell did I do that?}
{115}{}{I think I... I killed her.}
{116}{}{Oh God, I killed someone!}
{117}{}{It's done now. There's no going back.}
{118}{}{You won't tell anyone, right?}
{119}{}{Guess I'll have to get outta town...}
