{100}{}{You see a clerk.}
{101}{}{You see a middle-aged woman. Judging by her clothes, she is doing well.}
{102}{}{(she looks at your armor with a fascination that quickly turns into fear)}
{103}{}{We're closed. Come back during business hours.}

#Dialogue
{200}{}{Yes?}
{201}{}{Goodbye.}
{202}{}{I need to send a package to Flagstaff.}
{203}{}{I need to send a package to Two-Sun.}
{204}{}{Maybe we could just chat?}
{205}{}{I don't have time for small talk. Are you going to send a package or not?}
{206}{}{Maybe.}

#Sending a package
{210}{}{The shipping cost is }
{211}{}{ caps. You can use that box by the wall. After payment, we'll ensure your items reach their destination.}
{212}{}{Here's the payment, you can send the package.}
{213}{}{Not now.}
{214}{}{I already named the price. Do you want me to call security?}
{215}{}{}
{216}{}{It's just a misunderstanding. I'll be back.}
{217}{}{Please wait while I update our records. There. You can retrieve your package from any "Sonora Express" office.}
{218}{}{Alright.}
{220}{}{Can I, as a Follower of Fire, get a special price?}
{1220}{}{Can I, as a Follower of Fire, get a special price?}
{221}{}{Yes, of course. We have special agreements with the temple.}
{222}{}{That's good.}
{223}{}{Good that you dropped by. But don't expect a discount. I've got orders from above, so don't start complaining.}
{224}{}{I understand. No problem.}
{225}{}{What the hell do you think you're doing, bitch?}
{226}{}{No. I'm leaving this place. For good.}
{230}{}{Welcome. How can I help you?}
{231}{}{Excuse me, what is this place?}
{232}{}{This is a courier delivery service. Didn't the sign outside tell you anything?}
{233}{}{Such a service is a bit... unusual, considering the scorched wasteland around. What do you transport?}
{234}{}{We transport anything, even a dead flea, if it pays the right price. Are you just curious, or are you ready to place an order?}
{235}{}{Maybe. I want to know more.}
{236}{}{No, no, I was just attracted by the sign. Goodbye.}
{237}{}{I think you're being a little rude. With service like this, you won't catch me here again.}

{280}{}{I need to know, did any of your caravans escort a man named Tin-Tan?}
{281}{}{We keep a log. But I'm not digging through it for free.}
{282}{}{Alright. I'll pay 10 caps.}
{283}{}{Then it's not worth it. Goodbye.}
{284}{}{Alright. Who exactly are you looking for?}
{285}{}{German Henaro Cipriano Gomez Valdes-y-Castillo. He was en route to a settlement called El Faro Pier via Casa Nueva.}
{286}{}{According to our records, a man by that name did travel with one of our caravans. But it also notes that the caravan didn't reach its destination. It was robbed by highwaymen.}
{287}{}{I see. Thanks.}

# added by cambragol
{288}{}{Well, well... the Sonora Express.}

#Lost package from world map
{290}{}{I found this package during my travels.}
{291}{}{What's this?}
{292}{}{I think they're letters from a colony or some village. Whoever was delivering them must've been ambushed by highwaymen.}
{293}{}{Hmm, looks to be the case. Many people are waiting for news from the new colonies. But because of the highwaymen, we keep losing caravans. Well, I'll have to buy these letters from you for half the courier fee.}
{294}{}{Better than nothing.}
{295}{}{There. Thank you for the delivery.}
{296}{}{Take care.}
{297}{}{Keep the caps. It's enough that these letters reach their destination.}
{298}{}{First time I've seen someone refuse caps. You're an interesting person. But thanks for the delivery.}
{299}{}{Glad to help. Take care.}
{1299}{}{Glad to help. Take care.}

#Quest
{300}{}{I'm seeking honest work. Got any jobs available?}
{301}{}{We have enough staff.}
{302}{}{I see.}
{303}{}{However... there is one "delicate" job everyone refuses.}
{304}{}{I'm listening.}
{305}{}{In the eastern slums, our courier was attacked by gangsters and lost everything, including fresh letters. We need them found and returned. Are you up for it? It's risky, but the company will pay 50 caps for the return of the letters.}
{306}{}{Sounds like one of the local gangs. Finding them shouldn't be a big problem. I'm in.}
{307}{}{Very good. Payment upon return. Good luck.}
{308}{}{Yes, goodbye.}
{309}{}{Gangsters, slums... No, I'm not risking my neck for some caps.}
{310}{}{Of course, I understand. All the best.}
{311}{}{Yes, goodbye.}
{312}{}{Remind me, where were the letters stolen?}
{313}{}{The eastern slums, where the poor live. There's also that inhuman arena where they hold death matches.}
{314}{}{Thanks. One more question, please.}
{315}{}{Understood, goodbye.}
{316}{}{I came across some letters. Doesn't look like they made it to the recipients.}
{317}{}{Let me see... Ah, finally! These letters were considered lost after our courier was robbed in the slums. You've done us a great service.}
{318}{}{You're welcome. Is there any reward for finding them?}
{320}{}{Are these the letters you mentioned? A member of the Red Cardinal gang had them.}
{321}{}{Ah, finally! You've done us a great service. Let me see... Yes, these are the ones.}
{322}{}{And my caps?}
{323}{}{Of course, here's your 50 caps. You know what, I'll pay you another 25 caps for delivering one of these letters. It's addressed to someone named Steve, who lives in those dangerous slums. You seem to manage there without trouble, and we need *guaranteed* delivery.}
{324}{}{Sure, more caps won't hurt.}
{325}{}{It's always like this. Help once, and everyone flocks to you. Alright, hand it over.}
{326}{}{Let's sign a short contract. There... Excellent. Now head to the slums and deliver the letter with a receipt. Good luck.}
{327}{}{[Leave the office]}
{330}{}{The letter is delivered. Here's the recipient's receipt.}
{331}{}{Wonderful. Here are your hard-earned 25 caps. I hope I don't need to specify that we won't tolerate any deceit.}
{332}{}{Of course.}
{333}{}{Thanks for your help. It's been a pleasure working with you. Unfortunately, we won't have any new deliveries for a while.}
{334}{}{Goodbye.}
{335}{}{About that letter. There's no one left to receive it. The recipient's dead.}
{336}{}{What a shame. Well, that happens. The contract accounted for such a mishap. You'll get only half the fee. Here's your 12 caps.}
{337}{}{This is outrageous! I demand full payment!}
{338}{}{Read the contract. You signed it. And don't you start yelling here.}
{339}{}{Wha... How... Hmph.}
{340}{}{Well, that's fair. No complaints.}
{341}{}{[Leave the office with a sense of accomplishment]}
{342}{}{Remind me, where was I supposed to take this letter?}
{343}{}{(sighs in frustration) The letter is addressed to someone named Steve, who lives in the slums near the arena. I repeat: in the slums near the arena. Got it? Write it down so you don't forget.}
{344}{}{I hear you, woman.}
{345}{}{Thanks, now I got it.}
