{100}{}{You see a fighter in front of you.}
{101}{}{You see an arena fighter. Looks like he overdid it in training.}
{102}{}{You see an arena fighter. He looks cheerful.}
{103}{}{Thanks, Doc, that's much better.}

#Responses
{110}{}{*Groans*}
{111}{}{It hurts... so bad.}
{112}{}{Ugh...}
{113}{}{*Coughs hard*}
{114}{}{Ughh...}
{115}{}{That was brutal...}
{116}{}{I'm not stepping back in the ring again.}
{117}{}{Where's that damn dealer?}
{118}{}{I need a painkiller, quick.}
{119}{}{It's getting worse with every hour...}

{150}{}{That ring broke me.}
{151}{}{As you can see, I'm dying here.}
{152}{}{That last fight was a real killer.}
{153}{}{Pretty sure I got a concussion.}
{154}{}{I need a doctor... now.}
{155}{}{Got any painkillers?}
{156}{}{Damn dealer can't find a stimpak.}
{157}{}{These fights are hell.}
{158}{}{*Groans, clutching his head*}
{159}{}{Ugh... My head's killing me!}

#Random phrases for gratitude and recovery
{170}{}{Thanks for saving me.}
{171}{}{If it wasn't for you, I'd probably be dead.}
{172}{}{Where'd you learn first aid?}
{173}{}{Lucky you were around.}
{174}{}{A lot of people I know could've made it if you were there.}
{175}{}{You're not going into the ring, are you?}
{176}{}{Patch me up after my next fight, yeah?}
{177}{}{Another fight? Why not!}
{178}{}{Your help was just what I needed.}
{179}{}{I'll be back in the ring soon enough.}
