{100}{}{You see a fan.}
{101}{}{You see a man, indifferently waiting for the next fight.}
{102}{}{You see a wild-looking man. He screams furiously at the top of his lungs.}

#Response
{110}{}{Can't wait for the next fight.}
{111}{}{What'd you think of the last one?}
{112}{}{Iron Mike isn't training fighters anymore.}
{113}{}{Not a single good fight since Iron Mike left.}
{114}{}{Boring... When's the next bout?}
{115}{}{I'm betting all my caps on this fighter.}
{116}{}{You betting or fighting?}
{117}{}{This is my last bet. I can feel it.}
{118}{}{}
{119}{}{}

{150}{}{Hey there, champ.}
{151}{}{How's it going, champ?}
{152}{}{Is that really you?}
{153}{}{Oh my god, the champ's talking to me!}
{154}{}{Why'd you stop fighting?}
{155}{}{Punch me! I'll tell everyone I know.}
{156}{}{Hey, can I feel your biceps?}
{157}{}{Thanks to you, I'm sittin' pretty.}
{158}{}{}
{159}{}{}

{160}{}{Hey.}
{161}{}{Enjoying that victory high?}
{162}{}{Whoa, easy there!}
{163}{}{Cool fight, champ, but I bet on the other guy. Now I'm broke...}
{164}{}{Why'd you quit fighting?}
{165}{}{C'mon, try to hit me.}
{166}{}{Aren't those biceps a little too tight?}
{167}{}{You busted my bet. Now what? Help a guy out.}
{168}{}{}
{169}{}{}

#Random phrases outside of combat
{170}{}{When's the next fight?}
{171}{}{Boring.}
{172}{}{The ring is missing something.}
{173}{}{ }
{174}{}{ }
{175}{}{ }
{176}{}{ }
{177}{}{ }
{178}{}{ }
{179}{}{ }

#Random phrases during battle
{180}{}{I'm putting my caps on this fighter!}
{181}{}{Go! Go!}
{182}{}{Finish him off!}
{183}{}{I love you!}
{184}{}{Go right! Hit him on the right!}
{185}{}{Defend yourself!}
{186}{}{This fight's a snooze.}
{187}{}{I'll never forget this fight.}
{188}{}{This heat's killin' me.}
{189}{}{*Whistles*}
{190}{}{*Screams*}
{191}{}{Hit him! Come on, hit him!}
{192}{}{Let's go!}
{193}{}{Don't slow down now!}

{194}{}{!}
{195}{}{Go for it, }
{196}{}{You're the best, }
{197}{}{Finish him off, }
{198}{}{I've got my caps on you, }
{199}{}{Do it, }