{100}{}{You see Rico.}
{101}{}{You see a huge fellow with a dull expression, but an impressive presence.}

#Response
{110}{}{You listening or what?}
{111}{}{Nah, talk to the dwarf.}
{112}{}{Angelo's the boss around here.}
{113}{}{What do you want?}
{114}{}{Missed my target again.}
{115}{}{I'm hungry.}
{116}{}{Keep your hands where I can see 'em.}
{117}{}{You in trouble, huh?}
{118}{}{Sit down! I said SIT!}
{119}{}{Take a bite, go on!}
{120}{}{*Grunts*}
{121}{}{*Stretches hands out*}
{122}{}{You smell like a baby.}
{123}{}{Don't wait for me.}
{124}{}{Stop talking.}
{125}{}{Time for a nap.}
{126}{}{You need a trainer or somethin'?}
{127}{}{Uh-huh.}
{128}{}{Exit's that way.}
{129}{}{Back off.}
{130}{}{*Looks at you blankly*}
{131}{}{What do ya need?}

#Random phrases
{150}{}{(Enviously) That was one hell of a fight.}
{151}{}{You fight like a wild dog.}
{152}{}{Who taught you to fight like that?}
{153}{}{Don't hit me!}
{154}{}{You're ruthless.}
{155}{}{I'm not even close to your level.}
{156}{}{I ain't fighting you.}
{157}{}{You ain't human, you're a beast.}
{158}{}{I need a trainer.}
{159}{}{Finish me off.}
{160}{}{*Grunts*}
{161}{}{*Toothless grin*}
{162}{}{*Nods stupidly*}

#Emotional outbursts
{200}{}{*Cries like a baby*}
{201}{}{Ange-e-looo!}
{202}{}{Ange-elo! Ange-elo!}
{203}{}{*Whines*}
{204}{}{Oooohhh...}
{205}{}{*Moans*}
{206}{}{Don't look! Don't look at me!}
{207}{}{I'll kill you! I'll kill all of you!}
{208}{}{Bitches! All of you!}
{209}{}{Angelo was smart, I was dumb.}
{210}{}{Who saw this coming?!}
{211}{}{Show me who saw this coming!}
{212}{}{Who killed my Angelo?!}
{213}{}{*Takes a deep breath*}
