{100}{}{You see a small-time trader.}
{101}{}{You see a local merchant, mixing drinks for the arena spectators.}

{110}{}{That's it, my business is toast.}
{111}{}{Who's the idiot that tried to take out Angelo?}
{112}{}{Sorry, that item's gone.}
{113}{}{Arena's closed, and so is my shop.}
{114}{}{I'll be lucky to get outta here in one piece.}

{200}{}{Need a drink before the match? Prices are cheap.}
{201}{}{No drinks today.}
{202}{}{Well, well. Didn't expect a winner like you to stop by for a drink.}
{203}{}{Great fight, }
{204}{}{. Keep it up.}

{210}{}{Need a drink before the fight? Got it cheap.}
{211}{}{Catch you later.}
{212}{}{Can I place bets in the arena?}
{213}{}{Not sure when the next fight is. Ask around. Drink or no drink?}
{214}{}{No drinks today.}
{215}{}{I'll think about it.}
