{100}{}{You see a squatter.}
{101}{}{In front of you is a skinny man in dirty clothes.}
{102}{}{*Chomp chomp*}
{103}{}{It was the Cardinals! They sabotaged the power plant!}

#Dialogue
{200}{}{Oh, mama, don't scare me like that! People don't come around here often.}
{201}{}{Sorry, I didn't mean to. What are you doing here?}
{1201}{}{Sorry, I didn't mean to. What are you doing here?}
{202}{}{Idiot! I almost killed you. What the hell are you doing here?}
{203}{}{Catching rats. They're quick and sneaky, don't fall into traps easy. Sometimes you gotta wait for hours in ambush.}
{204}{}{Well, good luck with that. See you around.}
{205}{}{If you've been around here for a while, then maybe you saw someone go down into the sewers?}
{206}{}{Yeah. Maybe I did... What's in it for me if I tell you?}
{207}{}{I'll give you some food. Hold on, I'll grab something...}
{208}{}{You've already had enough food. Now start talking.}
{209}{}{Here's ten caps to buy food.}
{210}{}{Oh, much obliged.}
{211}{}{Now, start talking.}
{212}{}{Sorry, but my wallet's empty.}
{213}{}{I'll spare your life, you piece of trash.}
{214}{}{Get lost! Or I'll sic a pack of rats on you. Scram! Scram!}
{215}{}{Yeah, yeah.}
{216}{}{Looks like I'll have to dirty my hands after all. Come on! What did you see?}
{217}{}{I'll spare your life, you piece of trash.}
{218}{}{Mercy! Please! I'll tell you everything!}
{219}{}{Go on, start talking.}
{220}{}{It was the Cardinals. They came with a fire worshipper and a ghoul... Ralph's his name I think... The fire worshipper was telling them to blow up some pipes to trick the head honcho at the power plant. Complicated stuff, I didn't get it all.}
{221}{}{Good, you can live for now.}
{222}{}{Thanks, buddy. You've been a big help.}

{250}{}{Hey there. I've been seeing a lot of folks around here lately.}
{251}{}{Thanks for the food. Got any more?}
{252}{}{What are you doing here?}
{253}{}{Later.}
