{100}{}{You see a console.}
{101}{}{You see the prison block security console. Through it you can control force fields.}
{102}{}{The prison block's force fields have been disabled.}
{103}{}{Insufficient security clearance.}

{200}{}{Enter command:}
{201}{}{Disable camera 1's force field.}
{202}{}{Activate chamber 1 force field.}
{203}{}{Disable camera 2's force field.}
{204}{}{Activate chamber 2 force field.}
{205}{}{Disable camera 3's force field.}
{206}{}{Activate chamber 3's force field.}
{207}{}{Back}
{208}{}{End session}
