{100}{}{You see a child.}
{101}{}{You see a local kid. He smells like fish and dirt.}
{102}{}{Thanks, Mister! I'll need this.}
{1102}{}{Thanks, miss! I'll need this.}
{103}{}{Thanks, Mister. But I already have a pair of sandals.}
{1103}{}{Thank you, miss. But I already have a pair of sandals.}
{104}{}{That was very nice of you.}

{200}{}{I saw them! I'm telling you! It's true! Oh... But you're a... Aren't you an outsider?}
{201}{}{What did you see?}
{202}{}{Watch who you're calling an outsider, small fry.}
{203}{}{Monsters! They come out of the aqueduct at night - I swear, I saw it! Now I get why they don't let anyone go down there. There's gotta be a whole nest of 'em lurking in the dark!}
{204}{}{Hmm.}
{205}{}{You're clearly lying.}
{206}{}{I told you, I saw them! They're hairless and disgusting, making weird sounds through their piggy-noses. What if they come up here and attack us?}
{207}{}{Calm down, they're probably just pig rats. Nothing will happen unless you get close to them.}
{208}{}{They might. What's gonna be done about them?}
{209}{}{Uh... I'm not sure, really. But Garth probably has a plan - he always does. I even saw him go down into the aqueduct himself! Garth's not scared of anything. He'll keep us safe, no matter what comes our way!}
{210}{}{By the way, what were YOU doing at the aqueduct?}
{211}{}{Well... I was just walking, okay? But you're not supposed to go there, so they punished me - made me sort through the algae nets. Ugh, they were all slimy and nasty.}  
{212}{}{Found anything interesting?}
{213}{}{Not really... but, uh... need any ammo? I found some near the aqueduct. Probably dropped by one of the hunters. I could trade it to you for something useful.}  
{214}{}{I'll keep that in mind.}
{215}{}{No need, your bullets are probably damp.}
{216}{}{Judging by your bare feet, you could use anything.}

{220}{}{I saw them! I'm telling you! It's true!}
{221}{}{I believe you. Bye.}

{230}{}{Is that why you walk around barefoot?}
{231}{}{Yeah... When I saw those monsters, I just ran here right away. I ran so hard that I didn't notice I tore my sandals. Now I gotta find new ones...}
{232}{}{So did you find anything interesting while you were walking by the aqueduct?}
