{100}{}{You see Old Man Rufus.}
{101}{}{You see the overseer of the dam, a grizzled old man in worn overalls.}

#First Dialogue
{200}{}{(You observe a bald, unshaven man around 50 years old, his dirty overalls indicating the nature of his work.) Eh? Sorry, my hearing's not what it used to be. Spend as many years as I did around these roaring machines, and you'll end up hard of hearing too.}
{201}{}{I see.}
{202}{}{And who might you be? Don't recognize you, and I know everyone 'round here. Newbies ain't typically allowed near the plant, and the quartermaster handles the caravans. Which means...}
{203}{}{I'm here on business.}
{204}{}{Right, business it is. Just don't go sticking your nose where it don't belong.}
{205}{}{So, what's your role here, old-timer?}
{206}{}{Then I'll leave you to it.}

#Re-dialogue
{210}{}{Speak up! Why're you muttering?}
{211}{}{I said "goodbye".}
{212}{}{Let's go back a bit.}
{213}{}{Got another question.}

#Questions
{220}{}{And who might you be?}
{221}{}{They call me Rufus. I'm the dam's overseer. I keep this place running smooth.}
{222}{}{What's your rank, Rufus?}
{223}{}{Don't have one. I'm a worker, not some soldier.}
{224}{}{How long you been at this post, Rufus?}
{225}{}{Hmm, gotta think on it. 'Bout 30 years, I reckon. No one really counts the years 'round here.}
{226}{}{Why'd the Rangers set up shop at this dam?}
{227}{}{Oh, lotsa reasons: it's a fortress against baddies, shields from dust storms, plenty of water, and power for days. You could say it's history.}
{228}{}{I'm the dam's overseer. I keep this place running smooth.}
{229}{}{So, Rufus, what exactly's your job here?}
{230}{}{The aqueduct part of the power plant too?}
{232}{}{Nope, separate deal. Plant runs fine without it. Aqueduct's been outta commission for ages.}
{231}{}{What happened to it?}
{233}{}{Time's done its work. Pumps died long ago, beyond fixin'. Plus, river's runnin' low. Even if it worked, no one along the way needs that water no more.}
{234}{}{Impressive structure. Who built it?}
{235}{}{Folks in the past were clever. No one alive today could build this.}
{236}{}{Guess they were too clever for their own good, huh?}
{237}{}{Yeah... but they built a damn fine aqueduct to water the desert.}

#First quest
{250}{}{Sounds challenging.}
{251}{}{This ancient relic has seen its fair share! That control unit, for instance, just refuses to cooperate. And we can't find a replacement - all the gadgets here are one-of-a-kind.}
{252}{}{So, that control unit's on the fritz? Think I could tinker with it?}
{253}{}{No way! Fixing it takes more than just skill. But you're one of them's always on the move, ain't ya? If you come across any electronic parts in your travels, bring 'em back here. Maybe we can get it running with those.}
{254}{}{I'll keep an eye out.}
{255}{}{I might be able to scrounge up the parts you need.}
{256}{}{Sure thing. While you play hero, I'll see if I can get some work done up. No offense.}
{257}{}{Actually, I need more info on this.}
{258}{}{We'll catch up later then.}
{260}{}{About that busted control unit...}
{261}{}{Huh? What about it?}
{1261}{}{Huh? What about it?}
{262}{}{Eh, never mind. Just a thought.}
{263}{}{What's the deal with getting electronic parts?}
{264}{}{You think we ain't been scouring? Every patrol and trader knows. But 'round these parts, it's all countryside. Where do you find gadgets in places like this? Hauling 'em from the big cities ain't cheap or quick. They got their own folks to take care of.}
{265}{}{Why's that control unit so crucial?}
{266}{}{Look at that big contraption smack in the middle of the room. A screw inside it, dips into the Colorado river. The river spins it, and makes electricity... You know what "electricity" is, right?}
{267}{}{Sure, I do...}
{268}{}{The juice flows through the control unit to the transformers outside, then to the power lines. But right now, it's all kaput - just a mess of wires.}
{269}{}{Hmm. I had some more questions.}
{270}{}{I managed to get the control unit working.}
{271}{}{Huh? Just remember, Rangers ain't always good with jokes, especially when it comes to this dam.}
{272}{}{But it's humming along fine now. Take a look.}
{273}{}{Well, let's check it out... By the saints! Wha... it's actually working!}
{274}{}{It is. Good as new. But... uh... this isn't charity work, you know?}
{275}{}{Yeah... Of course. Here, take these micro fusion cells for your trouble. If you ain't got use for 'em, trade 'em in some nearby town for something handy.}
{276}{}{Yeah. It wasn't that hard to fix.}
{277}{}{Rangers don't forget their pals. Here, take these micro fusion cells for your help. If you ain't got use for 'em, trade 'em in some nearby town for something handy.}
{278}{}{[Continue]}
{279}{}{Thanks. Shame I won't have you around when I retire. If you don't mind, could you keep an eye on this ol' girl for a bit? I worry she needs some extra TLC. Wouldn't want her to breakdown again.}
{280}{}{Sure thing. I'll check back later... you keep the rest of this hunk of metal up and running.}
{281}{}{Easy now, old timer. Those wires might just surprise you with a jolt.}
{282}{}{}
{283}{}{Where can I get electronic parts?}
{284}{}{Closest place is Garage City. Sent a request there a while back, but no dice yet.}

#Second quest
{300}{}{So, how's the plant running since I fixed it?}
{301}{}{Like a charm! Won't be needing any repairs for a good while now. It's a shame you won't be able to take over when I retire, though.}
{302}{}{You're running this dam solo?}
{303}{}{(sighs) Sometimes I just listen to the hum of those hydraulic units. Their rusty whirring takes me back to days long gone.}
{304}{}{So... you need a replacement?}
{305}{}{Exactly, friend. This place needs a fresh caretaker - someone young, skilled with tech. Hard to come by these days.}
{1305}{}{Exactly, ma'am. This place needs a fresh caretaker - someone young, skilled with tech. Hard to come by these days.}
{306}{}{Anyone you have in mind?}
{307}{}{Well, aside from you, caravaners mentioned a lad from Garage City. Supposedly gifted, but wasting away his days. I'd like to train him up, but the locals there ain't too fond of us Rangers, see? Can't just snatch him up, gotta make him willing.}
{308}{}{Maybe I could convince him.}
{309}{}{Consider it done. I'll fetch the kid from that scrapyard.}
{310}{}{Guess you'll have to find someone else. Later, old timer.}
{311}{}{That's the spirit! That's what sets the new blood apart. Deal. Lookin' forward to meetin' him.}
{312}{}{Goodbye.}
{320}{}{Bad news - the kid from Garage City didn't make it.}
{321}{}{(shakes head) Shame about the lad, could've been a real asset to the Rangers down the line... Oh well, I'll have to make do with the locals, even if none of 'em are particularly keen on tech. Got no more tasks for you though. Thanks for your efforts.}
{322}{}{So, no reward for my troubles?}
{323}{}{Your efforts came up short, didn't they. Well, move along now, I've got work to do.}
{324}{}{So that's how it goes...}
{330}{}{This's the kid you were after.}
{331}{}{Well, hello there, son! Got a feeling you'll fit right in with the Rangers. First thing's first, though - you could use a good scrub...}
{332}{}{Ahem...}
{333}{}{...And you've done the Rangers a fine service by bringing him here. Pay a visit to the quartermaster, I told him to set aside a nice reward for you.}
{1333}{}{...And you've done the Rangers a fine service by bringing him here. Pay a visit to the quartermaster, I told him to set aside a nice reward for you.}
{334}{}{Excellent! Off to collect my reward, then.}
