{100}{}{You see Flick's guard.}
{101}{}{You see a tough, but not too bright, muscle.}

{110}{}{Go yap at Flick; he knows what's what.}  
{111}{}{Flick's smart - trades junk nobody wants for stuff we do.}  
{112}{}{Need somethin' useful? Flick's got you covered.}  
{113}{}{I'm here to keep an eye on Flick's stash, got it?}  
{114}{}{Lookin' for some firewater, eh?}  
{115}{}{When Flick screws up, I get real pissed.}  
{116}{}{No swipin' from the boss, got that?}  
{117}{}{Try n' steal from Flick, and I'll bust your hands good.}  
{118}{}{Don't think I ain't watchin' you.}  
{119}{}{Wanna find out what my spear feels like?}  
{120}{}{Boss says time to pack it up. Let's go.}  

