{100}{}{You see Jack.}
{101}{}{You see a ranger on duty, guarding the entrance to the dam.}
{102}{}{Hey, hey, get out of that damn tin can! I'm not kidding!}
{103}{}{We don't negotiate with cultists of any kind. Get lost!}

#Initial dialogue
{200}{}{(As you approach the guards, you notice their faces change as they raise their weapons.) Stop, no outsiders allowed here.}
{201}{}{What's in there?}
{202}{}{Over *there*, behind *that* door? That's the main headquarters of the rangers.}
{203}{}{Ah, that's what it is. Then I don't need to go there.}
{204}{}{Then don't loiter around here.}
{205}{}{Okay.}
{206}{}{Hold on, what business do you have at the base?}
{207}{}{None.}
{208}{}{I need to speak with your commander.}
{209}{}{Sure. Not every recruit gets to go down there. And certainly not you. Do you have a pass?}
{210}{}{You'll regret this.}
{211}{}{Fine, no problem.}
{212}{}{Listen, this is very important.}
{213}{}{If any ranger vouches for you, then you MIGHT get in. But for now, give me a good reason or get lost.}
{214}{}{Okay, you can go through. But remember, we'll be watching your every move. Go straight to the general and don't stray. Keep your weapon holstered.}
{215}{}{You didn't need to spell it out.}
{216}{}{Thank you, Ranger.}
{217}{}{I need to talk to your commander.}
{218}{}{Your quartermaster might be interested in my goods.}
{219}{}{You'll be the one regretting it if you keep causing trouble. Get lost.}

{220}{}{You shouldn't wear that rag around the base. You might get mistaken for a saboteur.}
{221}{}{Why?}
{222}{}{You know why. That's the robe of the Followers of Fire, and we don't like those guys. They impose their ways on others. Fuck those guys.}
{223}{}{Got it.}
{224}{}{Isn't this the kid Old Rufus was waiting for? Good job bringing him here. Let him be of use to the Wasteland. Skills like his don't belong in a junkyard.}
{1224}{}{Isn't this the kid Old Rufus was waiting for? Good job bringing him here. Let him be of use to the Wasteland. Skills like his don't belong in a junkyard.}
{225}{}{I did what I said I'd do. The rest is on you.}
{226}{}{I'm glad to see you're welcoming the kid.}
{227}{}{Hey, are you tired of living?! What the hell happened with Flick?}
{228}{}{Why, were you close with him?}
{229}{}{Us? Most folks on the base couldn't stand the guy. But that doesn't mean you go and kill one of the few merchants we've got! Look, I don't know what went down - command will sort it out. Just know, if you're to blame, the rangers won't be cutting you any slack.}  
{1229}{}{Us? Most folks on the base couldn't stand the guy. But that doesn't mean you go and kill one of the few merchants we've got! Look, I don't know what went down - command will sort it out. Just know, if you're to blame, the rangers won't be cutting you any slack.}

{230}{}{Commander Helford guaranteed me a pass.}
{231}{}{I've got a story from Kuyuk in Flagstaff that the general might be interested in.}
{232}{}{I was helping Oscar in San Brahmin.}
{1232}{}{I was helping Oscar in San Brahmin.}
{233}{}{I have information from a spy in Two-Sun.}
{234}{}{Your general should know about my connection with the rebels in Phoenix.}
{235}{}{I have very important information. It's about the Brotherhood of Steel.}
{236}{}{Hey, I'm just passing through.}
{237}{}{I have a holodisk with an important internal report from the Cathedral in Phoenix.}

#Repeat dialogue
{250}{}{Hi.}
{251}{}{Bye.}

{260}{}{I want to report a spy hiding in a shack on the old road...}
{261}{}{...Thanks for the tip. We'll send a squad to catch the bastard by surprise.}
{262}{}{}
{263}{}{Good luck with that.}

{270}{}{Is there a way to cross to the other side here?}
{271}{}{Only by the general's permission. Crossing the dam is forbidden for civilians. If you need to get to the other side, I suggest swimming.}
{272}{}{Where's the nearest crossing?}
{273}{}{Fifteen miles downstream, there's a ferry.}
{274}{}{So you've taken over the only bridge to the other side?}
{275}{}{Yeah. That's right. Any problems?}
{276}{}{Uh, no, none.}
{277}{}{Yes. It's unfair.}
{278}{}{Unfair? Then go cry to your momma you little baby.}
{279}{}{So that's how it is...}
{280}{}{Why won't you let this woman see the general?}
{281}{}{The general is too busy.}
{282}{}{Really? Seems to me he just doesn't want to be accountable for his soldiers' actions.}
{283}{}{Bullcrap. This woman was with a criminal and got what she deserved. If you're gonna help her, you'd better make tracks from the base before I lose my temper.}
{284}{}{Alright, let's drop it.}
