{100}{}{You see a handyman.}
{101}{}{You see an average wastelander.}

#First dialogue
{200}{}{(a young man in ragged attire stands before you, looking up wearily, clearly discontent) What do you want?}
{201}{}{You're not one of the Rangers?}
{202}{}{Hell no. I couldn't care less about those Rangers. But they're the ones keeping our settlement safe, I guess. In exchange, they put me to work.}
{203}{}{Alright. I'll leave you alone then.}

#Re-dialogue
{210}{}{Back again, huh?}
{211}{}{Later.}
{212}{}{Can't you refuse to work for them?}
{213}{}{Not really. If the Rangers get pissed, they'll cut off our supplies and leave us defenseless against raiders and mutants. So, we're stuck catering to their every demand. And trust me, that list is long.}
{214}{}{Tell me about your settlement.}
{215}{}{We're situated in Aqueduct, on the banks of the Colorado, scraping by on fish and whatever small game we can catch. Not much else to say.}
{216}{}{What's your take on the Rangers?}
{217}{}{When push comes to shove, they're our only shot at survival. But in between crises, they're just leeching off our community, taking a cut of our catch and making us work for their benefit.}
{218}{}{Know any way into their base?}
{219}{}{Not a clue. They're not exactly welcoming folks inside for a tour. You either gotta do the Rangers a big favor or have a damn good reason to get in there.}
