{100}{}{You see Raymond.}
{101}{}{You see the Brotherhood of Steel quartermaster. He scans the lists through a large eyepiece mounted on his forehead.}
{102}{}{Now is not the time to chat with the locals.}
{103}{}{?}
{104}{}{Damn it, I've told you a hundred times already - don't go into the warehouse wearing Power Armor! You're like a deathclaw in a pottery shop.}

#Floating lines
{110}{}{We've got to update the ammo inventory.}
{111}{}{Next time, I'll make sure *you* scrub this filth off yourself.}
{112}{}{The Brotherhood values my signature more than you know.}
{113}{}{This rust is really getting up my nose.}
{114}{}{Grenades? Way overrated, if you ask me.}
{115}{}{}
{116}{}{}
{117}{}{}
{118}{}{}
{119}{}{}

#Dialogue
{200}{}{Well, well, a new face on the ship. That's always interesting. Can I help you with something?}
{201}{}{Nothing today. Maybe another time.}
{202}{}{Maybe. Tell me, what is this place?}
{203}{}{This is the main ship's warehouse. And I'm its quartermaster. My name is Knight Raymond.}
{204}{}{It's an honor to meet you, Knight Raymond.}
{205}{}{I see.}
{206}{}{Oh, just a warehouse... I thought there would be something interesting here.}

{210}{}{So, how can I help?}
{211}{}{I'll come by later.}
{212}{}{Mind if I ask a few questions?}
{213}{}{About what?}
{214}{}{Just idle curiosity.}
{215}{}{How can I help you, brother?}
{1215}{}{How can I help you, sister?}

{220}{}{I found a medal for bravery. Do you know anything about stuff like that?}
{221}{}{Operation Anchorage, huh? Yeah, that was one of the biggest wins for the U.S. before the Great War. Our forces went toe-to-toe with the Reds in Alaska. But, in the end, it didn't save us from getting nuked into oblivion...}
{222}{}{It looks like this is more than just a story for you.}
{223}{}{The Brotherhood of Steel traces its roots back to military families, some of whom fought in that very battle. Power armor? Yeah, it made its debut during Operation Anchorage. Now, about that medal - you're not too attached to it, are you? I'd like to add it to our collection. What do you want in return?}
{224}{}{What kind of medal? Show me.}
{225}{}{I'll bring it later.}
{226}{}{350 caps.}
{227}{}{That's a deal. Here's the caps.}
{228}{}{Thanks.}
{229}{}{Take it for free. I'm just happy to help the Brotherhood of Steel.}
{230}{}{My brothers in arms will definitely appreciate this. Thank you. If you need any of my supplies, you can count on a small discount.}
{231}{}{That's pretty good. I'll keep it in mind.}
{232}{}{What I really need is an opportunity to hone my weapon skills. Tough battles lie ahead.}
{233}{}{Then shooting at our range with training weapons will help you. I'll arrange it.}
{234}{}{Just what I need...}
{235}{}{The Quartermaster has reduced the cost of his goods by 10%.}

{240}{}{Can you tell me about the Brotherhood?}
{241}{}{Talk to the scribes or the general himself about us. If they don't want to talk, then I shouldn't either.}
{242}{}{Alright. I guess I'll do that.}
{243}{}{Let's talk about something else then.}
{244}{}{Remind me what this place is?}
{245}{}{This is the main ship's warehouse. And I'm its quartermaster. My name is Knight Raymond.}
{246}{}{Thanks, I'll remember that now.}
{247}{}{What are these strange 10mm rounds? This is the first time I've seen these.}
{248}{}{That's our own creation. The bullet in them consists of a particularly strong nanostructured alloy and has an unusual penetrating shape. Just right against well-protected enemies. Even though such enemies are rare, it's better to have a spare clip with you.}
{249}{}{I see.}

{250}{}{Can I see what you have?}
{251}{}{Of course. All the best for you.}
{252}{}{Looking to trade? Sorry, the Brotherhood doesn't do bartering. We stick to dealing with trusted caravans. But if you've got something useful, I might be able to make an exception.}
{253}{}{Exception? How about a really good weapon?}
{254}{}{The commanders think handing out good weapons or explosives could bite us in the ass. So, for now, you'll have to settle for what's available - until you've earned a bit more trust.}
{255}{}{How is it usually earned?}
{256}{}{Through business, obviously.}
{257}{}{I see.}
{258}{}{Okay, maybe later though.}
{259}{}{About caravans. I could become a caravan master.}
{260}{}{Sure you could, but we need regular suppliers.}
{261}{}{No fooling you I guess...}
{262}{}{I've got trading partners all across Arizona. I could bring in some top-notch caravans to do business here.}
{263}{}{Is that so? Well, you managed to convince me. I'll add you to our list of suppliers.}
{264}{}{Thanks.}
{265}{}{It's okay. I have clearance from the general himself.}
{266}{}{Right. I remember that order. You can count on a full range of supplies.}
{267}{}{Thanks.}
{268}{}{Come on, Raymond. Everyone here knows I can be trusted.}
{269}{}{Hmm... Okay, I'll add you to our list of suppliers.}
{270}{}{Thanks.}
{271}{}{It's okay. I have clearance from the High Scribe.}
{272}{}{It's okay. I have clearance from the patrol commander.}
{273}{}{We just lost one of our squad there. Talk to the patrol leader at the ship's entrance about this.}
{274}{}{Okay.}
{275}{}{I happened to find this dog tag in the ruins of Inferno.}

{280}{}{I came across some Brotherhood dog tags. What should I do with them?}
{281}{}{Hmm... each tag represents a fallen brother. Sad fate. If you've got a dog tag, I'll buy it for 10 caps.}
{282}{}{Those caps could come in useful.}
{283}{}{Take it for free. I don't need to profit from someone else's tragedy.}
{284}{}{Thanks. Every tag is important to us.}
{285}{}{I understand. But I still have questions.}
{286}{}{You're welcome.}
{287}{}{General Dixon promised a reward for delivering a report to him.}

{288}{}{Yes, that's right. There's already an order out in your name. Your pay is 250 caps, as well as three stimpaks and two Rad-X. Receive and sign.}
{289}{}{Thanks.}

{290}{}{Do you have any magazines for my grenade launcher?}
{291}{}{Sure, I have a drum magazine for this model. Just one. I'll install it for }
{292}{}{ caps.}
{293}{}{Nice. That big drum will improve my chances out there. Do it. Here's the caps.}
{294}{}{Not yet.}

{300}{}{Seems like I'm supposed to be given some service equipment here.}
{301}{}{That's right. Welcome to the Brotherhood, new recruit.}
{302}{}{What am I entitled to?}
{303}{}{Your gear depends on your role and rank. Anything outside the standard issue, you'll need to buy or maybe sweet-talk someone into lending it for certain missions. But hey, my warehouse is open to you now, and you'll get way better prices than the average civilian. So, what are you looking for?}
{304}{}{Can we delay the release for a moment? I need to clarify something. Goodbye.}
{305}{}{Scribe's kit.}
{306}{}{Great. Here's your things: a laser pistol with extra micro fusion cells for it, a decoder, a Geiger counter. Receive and sign.}
{307}{}{Paladin Set.}
{308}{}{You like big guns, don't you? Young people often strive to become paladins. Here are your weapons: a light machine gun, a box of ammunition for it and combat armor. Receive and sign.}
{309}{}{Knight Set.}
{310}{}{Ah, so you and I are in the same rank, brother. Very good. Here's your equipment: an atomic cutter, a super sledgehammer and rubber boots. Receive and sign.}
{311}{}{Scout Kit.}
{312}{}{A smart choice, considering you're also from the wasteland... Oh, I'm sorry, I don't mean to offend you. Here's your equipment: rocket launcher with ammo, shock glove, stealth boy. Receive and sign.}
{313}{}{Thank you, Knight Raymond.}
{314}{}{That's all? Okay, that'll do too.}

{320}{}{Looks like this is where you need to turn in lost Power Armor?}
{321}{}{Oh, the one we've been waiting for? Is it here with you?}
{322}{}{It's, uh, nearby. Wait until I stomp onto the ship in it.}
{323}{}{Yes, here it is. I return it to you, the rightful owners.}
{324}{}{Ah, just look at that chrome gleam under the lamplight! There's nothing quite like old-world tech, and this war machine is a real beauty... Oh, and thanks for your help. The Brotherhood appreciates it.}
{325}{}{Unfortunately, it took a bit of a beating at the ruins of Inferno.}
{326}{}{I see. It's OK. The damage is quite repairable, although the recovery process may take a couple of weeks.}
{327}{}{What if I need this armor again?}
{328}{}{We're grateful you brought it back, but this armor belongs to the Brotherhood of Steel, and you don't have any rights to it. Now, the General might recognize your efforts and give you permission, so talk to him. Meanwhile, I've got to get started on repairs. Seriously, who the hell tore this piece off...}
{329}{}{Your order's already been sent. You'll get to exercise your right to wear Power Armor... once I finish fixing it. Damn it, who thought ripping this part off was a good idea...}
{330}{}{I'll check back in a couple of weeks.}
{331}{}{I just want to know if I can use it after I return it?}
{332}{}{What kind of question is that? This gear belongs to the Brotherhood of Steel. If you want to use it, you'll need permission - or better yet, become one of us. But for now, you need to return that armor to the warehouse. Come on, don't waste our time.}
{333}{}{Okay, here it is. I am handing it over to the rightful owners.}
{334}{}{Wait until I stomp onto the ship in it.}
{335}{}{So this is the one that was transported through the ruins of Inferno? Just great. Come on, crawl out of her, I can't wait to check it out.}
{336}{}{This'll take a while, can we talk for a sec?}
{337}{}{Oh, sure, I'll take it off right now.}

{340}{}{Have you finished repairing that Power Armor?}
{341}{}{No. It's not as easy as it seems.}
{342}{}{Okay.}
{343}{}{Oh yeah. Looks like new!}
{344}{}{Can I take it?}
{345}{}{I need this armor for important business.}
{346}{}{That's a dumb question. This is Brotherhood of Steel property. If you want to use it, you'll need permission - or better yet, join us.}
{347}{}{Okay...}
{348}{}{An order has already arrived in your name. You may exercise your sacred right to wear Power Armor.}
{349}{}{Thanks... Nice, it looks better than ever.}
