{100}{}{You see Cody.}
{101}{}{You see a bald child in baggy clothes. His calloused hands speak of a life full of labor.}
{102}{}{I'll do anything to make the world a better place.}

#First dialogue
{200}{}{(You see a bald child in baggy clothes. He studiously ignores you.)}
{201}{}{Hey, where are your parents, kid?}
{202}{}{(He looks around warily and mutters under his breath) I... I have no parents.}
{203}{}{How is that possible? You weren't made on a pottery wheel, were you?}
{204}{}{Sorry if I hurt your feelings. Just curious, how did you wind up here?}
{205}{}{[Do the same]}
{206}{}{My parents died during the war in Casa Grande. I was left alone on the streets. The Tinsmiths saved me from starvation. I've been here ever since.}
{207}{}{That's... very noble of them.}
{208}{}{Strangers shouldn't meddle in our affairs.}
{209}{}{Given the reputation of the Tinsmiths, this story sounds a little off. Don't you think?}
{210}{}{(He looks away angrily) How do you know what happened there? You're a stranger. You don't understand anything. Better leave.}
{211}{}{Okay, kid, whatever you say.}
{212}{}{If we were out in the wasteland, you wouldn't talk to me like that. You're lucky we're here.}

{220}{}{What's your name, kid?}
{221}{}{For now, my name is Cody, same as before. But when I'm initiated as a Tinsmith, I'll receive an ID, and the old name will be gone.}
{222}{}{I see.}
{223}{}{Are the Tinsmiths treating you well?}
{224}{}{Pretty good. They feed and clothe me, and give me work that isn't too hard. No one hurts anyone here. But if you break the rules or cause trouble, the punishment is severe.}
{225}{}{I see.}
{226}{}{Do you have any friends here?}
{227}{}{Of course. We're allowed to talk and even play. Though some games are banned because Hard says they interfere with brain function and distract us from important matters.}
{228}{}{I see.}

#Re-dialogue
{250}{}{Go away. I'm not allowed to talk to strangers.}
{251}{}{Consider me invisible.}
{252}{}{By the way, I can stop by Casa Grande if you'd like and ask some questions...}
{253}{}{No, don't do that! This is my home now, and the Tinsmiths treat me very well. You'll only cause trouble for me. Leave me alone! (He turns away in fear and walks off)}
{254}{}{Oh, sorry...}
{255}{}{Come on, kid, stop being a little scaredy-cat.}

{260}{}{I think you should know this. The Tinsmiths didn't save you. They accepted you as payment for repairing the water pump in Casa Grande.}
{261}{}{That's not true! You're a stranger, how can you know that?}
{1261}{}{That's not true! You're a stranger, how can you know that?}
{262}{}{I found your parents in Casa Grande.}
{1262}{}{I found your parents in Casa Grande.}
{263}{}{Are... are they alive? But... why did the others lie to me all this time?}
{264}{}{The Tinsmiths were probably trying to block memories that could prevent your assimilation into the 'Collective'.}
{265}{}{You know, sometimes adults lie. Well, for example, to use someone to get something they want.}
{266}{}{(Confused) So my parents sold me, and my new family kept me in a lie for years? I... I don't know what to think now.}
{267}{}{That's up to you, Cody.}
{268}{}{Thank you for opening my eyes. Now I need to think about all this carefully.}
{1268}{}{Thank you for opening my eyes. Now I need to think about all this carefully.}
{269}{}{Of course. I hope you come to the right conclusions. Goodbye, boy.}
{270}{}{What is it, the world collapsing before your eyes? Yep, the Tinsmiths turned out to be cunning and deceitful, didn't they?}
{271}{}{I'm not going to hate this place now. But from now on no one will fool me so easily.}
{272}{}{I like your way of thinking. Don't let the Tinsmiths turn you into a soulless cog in a big machine.}
{273}{}{Anyway, they gave you a better life than the slums of Casa Grande. Believe me, there's nothing good left in that hole.}
{274}{}{The Tinsmiths seem disliked... But if you, a stranger from the wasteland, see good in Two-Sun, then maybe I can believe this really is a good place.}
{275}{}{That's it. Make Two-Sun a model for the whole wasteland, boy.}
{276}{}{Listen, are you sure your parents are dead?}
{277}{}{Hard himself told me about it. I believe him.}
{278}{}{Looks like I'll have to have a talk with him...}
