{100}{}{You see a Tinsmith.}
{101}{}{You see a resident of Two-Sun. She looks more civilized than other residents.}
{102}{}{You have gained favor with the local population.}

# First dialogue
{200}{}{(you see a bald woman with an optical amplifier under her left eye) Another wasteland primitive with primitive notions of Progress. Our conversation is irrelevant. Move along.}
{201}{}{Yeah, whatever.}
{202}{}{I think you're missing out on a lot.}
{203}{}{My views on Progress might surprise you.}
{204}{}{My Brotherhood of Steel membership might change your mind.}
{205}{}{After all my efforts, I expected more trust.}

{206}{}{My data suggests otherwise.}
{207}{}{Oh well.}
{208}{}{(pause) No objection.}
{209}{}{Alright, let's find common ground.}

# Re-dialogue
{210}{}{State your inquiry.}
{211}{}{Probably nothing more. Goodbye.}
{212}{}{Just one more question.}

{213}{}{Why don't you want to talk to me?}
{214}{}{Outsiders with low development coefficients don't deserve our trust. An exception would be trade gains, especially in food products. Do you have any nutrients?}
{215}{}{I'll look through my bag and see if I have anything to eat.}
{216}{}{You won't get anything from me.}
{217}{}{My food gift deserves some answers.}

# Questions
{220}{}{Why do Tinsmiths buy slaves?}
{221}{}{To achieve Progress, we require labor. The absence of slaves would decelerate our advancements. Eventually, we aim to replace slaves with robots, but that demands time and resources, which are presently constrained.}
{222}{}{Tell me about 'Progress'.}
{223}{}{Attaining technological and societal perfection akin to pre-Great War standards. In this era, Progress is imperative for the continued existence of humanity as a species.}
{224}{}{I see. I have another question.}
{225}{}{}
{226}{}{Do you know anything about Villa's slaves?}
{227}{}{No. This should be discussed with Master Hard, our leader.}
{228}{}{And you agree with such inhumane practices?}
{229}{}{Ethical considerations are secondary. Progress requires sacrifices. The advancement of humanity outweighs the value of a few wasteland primitives.}

{230}{}{What do you do?}
{231}{}{I tend to the workers in the hangar. I prepare nutrients and maintain order in the residential complex.}
{232}{}{So Tinsmiths have families?}
{233}{}{Family... Many Tinsmiths once had families. Now, such bonds are irrelevant.}
{234}{}{Why?}
{235}{}{We take in children from the wastelands and program them to serve our collective. Personality is irrelevant. No need for family.}
{236}{}{Some Tinsmiths seem different from others.}
{237}{}{Our society is divided into levels. Each level has its own set of knowledge and technologies. Only senior members receive complex and expensive implant operations.}

{240}{}{Why are you so distrustful of strangers?}
{241}{}{Trust is immaterial. We possess superior development metrics compared to nearly all wasteland dwellers. In such a situation, outsiders are mainly useful as slaves, and occasionally as trading partners.}
{242}{}{But you still have outside connections.}
{243}{}{That is correct... Until recently, we were a closed community, restricting entry of outsiders.}
{244}{}{What's changed?}
{245}{}{Food shortages, mathematical projections of our future, and contact with a highly developed community. But I can't discuss this with strangers.}
{246}{}{Interesting.}
