{100}{}{You see a patient.}
{101}{}{You see a sick Tinsmith. He is suffering from post-operative complications.}
{102}{}{How could primitive medicine cure me? This is illogical!}
{104}{}{Why... haven't I... been digitized yet...}
{105}{}{My... biomatrix... is malfunctioning...}

{110}{}{Disassemble me for parts.}
{111}{}{Doctor, will I be deactivated?}
{112}{}{I only regret one thing -- that I didn't live to see my biomatrix digitized.}
{113}{}{It's time to sacrifice myself for Progress.}
{114}{}{There was a glitch in my biomatrix.}

{115}{}{Thanks for the fix, Doc.}
{116}{}{Facing deactivation, I rethought a lot of things.}
{117}{}{I need to recalculate my algorithms.}
{118}{}{I no longer consider Progress worth my sacrifice.}
{119}{}{My biomatrix is stable now.}
