{100}{}{You see Hard's computer.}
{101}{}{You see Master Hard's personal computer. It's in excellent condition.}

#Dialogue
{200}{}{Enter command:}
{201}{}{End session}
{202}{}{Back}

{210}{}{Reports on the supply of slaves}
{211}{}{(Tinsmiths seem to love numbers and accounting. Detailed statistics about slaves are collected here - their origins, employment, and causes of death. Half of the slaves were sent to the Forbidden Zone, their fate unknown.)}
{212}{}{Information about slaves originally from Villa}
{213}{}{(You discover information about two slaves. Carlos is working in the hangar, and your padre has been sent to the Forbidden Zone. You'll have to go there yourself to find him.)}
{214}{}{Information about slaves from Phoenix}
{215}{}{(The main source of slaves for Tinsmiths is the Church of the Holy Fire in Phoenix.)}
{216}{}{Trade reports}
{217}{}{(Tinsmiths actively trade with several settlements, exchanging technology and providing repair services. Main contracts: Church of the Holy Fire in Phoenix (slaves, clothing, food), colony in Flagstaff (slaves, uranium), Casa Nueva (food), Casa Grande (clean water).)}
{218}{}{Instructions from the headquarters}
{219}{}{(The leader of the Tinsmiths receives direct instructions from the Brotherhood of Steel in Puerto Penasco. The Brotherhood doesn't interfere in local affairs but regulates some production and foreign policy. Specifically, the Brotherhood obliges them to fulfill important requests from the Church of the Holy Fire in Phoenix. The latest contract was for parts for a nuclear bomb.)}

{220}{}{Cody's dossier}
{221}{}{(Cody was among the children that the Tinsmiths acquired from outer settlements and re-educated under their rules. The parents gave Cody as payment for repairing the water pump in Casa Grande. However, for better assimilation within the Collective, his official history was a bit "simplified".)}

{230}{}{Receiving a part from...Garage City?}
{231}{}{(It turns out the Tinsmiths received from the Followers of Fire the very same part you gave to the caravaners in Garage City. It was sent here for mass reproduction.)}
{232}{}{Dossier on Carlos}
{233}{}{(Oddly enough, despite all their isolation, the Tinsmiths appreciated and accepted Carlos for his talents and interest in technology.)}
{234}{}{Okay, well, let's tweak the dossier a little here... and here... This should knock Carlos's arrogance down a notch.}
{235}{}{(You've committed sabotage. The Tinsmiths are going to get suspicious of this newcomer from the Villa.)}
{236}{}{Great, this will force Carlos to leave Two-Sun.}
