{101}{}{You see a makeshift workbench.}
{102}{}{You crafted 20 flare rounds from old party fireworks.}
{110}{}{This workbench contains components for assembling micro fusion cells.}
{111}{}{All components are used up. There's nothing more to do here.}
{112}{}{You have assembled an 8-charge micro fusion cell.}
{113}{}{You have assembled a micro fusion cell with 16 charges.}
{114}{}{You have assembled a micro fusion cell with 20 charges.}
