{100}{}{You see Chris.}
{101}{}{You see one of the residents of the Villa. His look betrays a fair amount of anxiety.}

{200}{}{(looks away) Oh... I thought those raiders got you too. Glad to see someone made it.}
{201}{}{I gotta go.}
{202}{}{Tell me about the raid.}
{203}{}{Why didn't the raiders touch you?}
{204}{}{Those raiders came out of nowhere, surrounded us, and trapped everyone. Some folks hid in their homes, but they didn't stand a chance.}
{205}{}{They figured I wasn't worth it. Probably too scrawny for them, or something.}
{206}{}{Something doesn't add up, Chris.}
{207}{}{(looks away) I just... hid in the cellars... stayed there till it was over.}
{208}{}{And you watched as your people were dragged away? You coward!}
{209}{}{Chris, you're a real piece of work.}
{210}{}{Alright, well, can't say I blame you entirely.}
{211}{}{What was I supposed to do?! Walk into their arms?! I can't fight... I never could... I could only hide.}
{212}{}{What you should be worried about now, is how our people will deal with you when they return. I'll leave you for now.}
{213}{}{Yes, I know! But what could I do? I can't fight, had no weapon, and was alone against a dozen raiders! Easy for you to judge - you weren't here. Now I have to live with it...}
{214}{}{Do you really think so? Yeah, sure, you weren't here either... But that doesn't make it easier. I abandoned them. Now I have to live with that.}
{215}{}{Go on.}
{216}{}{It was the worst for those hiding in the town hall - it was a bloodbath in there.}
