{100}{}{You see a peasant.}
{101}{}{You see one of the residents of the Villa, inspecting the settlement with a cautious eye.}

{110}{}{Hey, has anyone seen Chris?}
{111}{}{If anyone has seen Chris, speak up now.}
{112}{}{If Chris doesn't come back on his own, he'll be in even deeper trouble.}
{113}{}{Hey, you! Know where Chris is hiding?}
{114}{}{That little coward's gotten away with too much.}
{115}{}{I knew Chris would crack under pressure.}

{200}{}{Hail to our savior! How are things going?}
{1200}{}{Hail to our savior! How are things going?}
{201}{}{Great. See you.}
{202}{}{Wait! I know it's a lot to ask, but we need your help again.}
{203}{}{Help with what?}
{204}{}{It's about your old friend Chris. Did you know he was hiding in the cellars during the raid? While we were out there fighting for our lives, that coward didn't even lift a finger!}
{205}{}{So he's on the run?}
{206}{}{Looks like it. He's probably hiding, just like last time. Find him and bring him back. He must answer to the village Council. It's important.}
{207}{}{I'm not interested. But if I see him, I'll let him know he's being looked for.}
{208}{}{I'll find him.}

{210}{}{Have you seen Chris? It'd be better if he returned and faced the Council.}
{211}{}{Haven't seen him yet.}
{212}{}{Where do you think he might be hiding?}
{213}{}{I don't think he'd flee into the wasteland - he doesn't have the guts, and there's nowhere to run. We checked the cellars, but he wasn't there. Someone must be hiding him, but who? Friends, neighbors, even his little brother won't confess.}
{214}{}{Well, he's gotta be somewhere.}

{220}{}{Chris is dead. His body's in the ruins where he was hiding.}
{221}{}{What a shame. It would have been better to see him punished. But at least it's a lesson to others. Thank you for your efforts; the community appreciates it.}
{222}{}{You're welcome.}
{223}{}{Thanks to you, Chris is back in Villa and will soon face punishment for his betrayal. The community is grateful for your efforts.}
{224}{}{You're welcome.}
{225}{}{By the way, we found some forbidden items on him. You decide what to do with it. We have no use for Old World tech. (hands you several old bullets of different calibers)}
{226}{}{Great, I'll... dispose of them.}
{227}{}{Guess there's no point in waiting for Chris anymore, right?}
{228}{}{Yeah. He left the valley and won't be coming back.}
{229}{}{Good. His presence was a threat to our community's order. The further away he is, the better.}
{230}{}{My job's done. Take care of yourselves.}
