{100}{}{You see the nanny.}
{101}{}{You see Anita, one of your many aunts. She looks very stressed.}
{102}{}{Get snippy with me again, and I'll give it right back!}
{103}{}{You have added a new task to your Pip-Boy.}
{104}{}{Get out of here, you...you... tin man! Don't touch the children!}

{200}{}{Good to see you.}
{201}{}{First the raiders, and now you.}
{202}{}{Nothing, goodbye.}
{203}{}{I see. Goodbye.}
{204}{}{}
{205}{}{}
{206}{}{? Oh, you weren't taken! Thank god! The raiders took half the village.}
{207}{}{Don't worry, I'm gonna get them back.}
{208}{}{I know. Bastards.}
{209}{}{I can see that. Do you have anything useful to say?}

{210}{}{Tell me about the raid.}
{211}{}{I don't want to think about that nightmare! Strangers stormed in, beat our husbands, smashed the doors and windows... I was too scared to even move! And the kids still haven't recovered.}
{212}{}{How are the kids?}
{213}{}{They're still in shock. I have to take care of the children, although I could use some support myself... It's terrible!}
{214}{}{Is there anything I can do to help?}
{215}{}{Yeah, I guess... Eden was so scared after losing his parents that he ran away and is now hiding somewhere. I can't leave the other children to look for him. Can you?}
{216}{}{Where should I start looking?}
{217}{}{He could be anywhere!}
{218}{}{Does he still have a favorite hiding place?}
{219}{}{Well, I remember he set up his "base" in the shacks on the plantations.}
{220}{}{I'll see what I can do.}
{221}{}{Tell me about Eden again.}
{222}{}{Eden was so scared after losing his parents that he ran away and is now hiding somewhere. I'm afraid he might get into even more trouble.}
{223}{}{Bad news - Eden is... dead.}
{224}{}{(nearly faints) Oh... Oh god... I guessed it was too late... it was all my fault... if only I had stopped him in time...}
{225}{}{We did what we could.}
{226}{}{As you can see, Eden is back.}
{227}{}{He might have died without your help! Now it's my turn to take care of him. (with tears in her eyes) Thank you so much!}
{228}{}{Come on, we're kin.}
{229}{}{I'd prefer something to eat, but I guess I'll have to settle for a "thank you."}
{1229}{}{I'd prefer something to eat, but I guess I'll have to settle for a "thank you."}
{230}{}{Ah, well... the raiders left us with nothing, really. But I do have something for you. This is what the children found; it looks like one of the raiders dropped it.}
{1230}{}{Ah, well... the raiders left us with nothing, really. But I do have something for you. This is what the children found; it looks like one of the raiders dropped it.}
{231}{}{Brass knuckles? Hmm, I might need these.}
{232}{}{It's good to have you... Oh yes, the children found this; it looks like one of the raiders dropped it. Take it, maybe it'll help you.}
{233}{}{They still have nightmares. I try to help them while the others are busy rebuilding the village. But sometimes, it would be nice to have some support. I don't know how we'll ever recover.}
