{110}{}{This well is as old as the Villa itself.}
{111}{}{You lowered a sturdy rope to the bottom of the well.}
{112}{}{You have already lowered a rope to the bottom of the well. A second one is not necessary.}
{113}{}{As you descend to the bottom of the well, you discover an ancient cache. Looks like someone hid some 'forbidden' items here.}
{114}{}{What a surprise.}
{115}{}{ }
{116}{}{No repairs needed.}
