{100}{}{You see Jeffrey.}
{101}{}{You see a ghoul in an old pair of pajamas, calmly sipping a cocktail.}
{102}{}{I can't stop you from being here. But stay out of my way.}
{103}{}{Smoothskins are such xenophobes. Am I right?}
{104}{}{Laws? I don't think you'd like living in a "lawful state".}

{200}{}{Hey, welcome, dead friend. Where you from?}
{201}{}{Thanks for the drink, buddy. Where you from?}
{1201}{}{Thanks for the drink, lady. Where you from?}
{202}{}{Welcome, buddy. Where you from?}
{1202}{}{Welcome, lady. Where you from?}
{203}{}{I'm from Arizona.}
{204}{}{Arizona! Didn't think there were ghouls there too. Seems like the plague got more than just us a hundred years ago.}
{205}{}{Us?}
{206}{}{Arizona! Didn't think there were people there either. Though calling us "people" is a bit of a stretch.}
{207}{}{Us?}
{208}{}{The ghouls of Necropolis. We survived the nukes in a local vault, but turned into ghouls. Died and went to heaven. That's my favorite joke.}
{209}{}{Then why are you here and not in Necropolis?}
{210}{}{You don't know the story? Oh, it happened a few years ago. Long story short, some crazed mutant was breeding more mutants, and the normals took up arms against ALL mutants. That forced us to migrate. And now we're here. It's not so bad.}
{211}{}{In other words, you just ran away from your problems?}
{212}{}{Think what you want. It's irrelevant now.}
{213}{}{That's sensible. Shows you don't want conflict with normal folks.}
{214}{}{Thanks for the kind words, buddy.}
{1214}{}{Thanks for the kind words, lady.}
{215}{}{Seems like you enjoy it here?}
{216}{}{In Necropolis, we'd be digging our own graves. Here, we live normal lives. Right now, I'm sipping a White Russian in a bar-what could be better?}
{217}{}{[Listen]}
{218}{}{By the way, I lived here before the War. Fond memories. A whole century has passed. I'm back, but my home is gone. What I miss most is the carpet. It really tied the room together.}
{219}{}{You should switch to a Black Russian. Might wake up the remains of your brain, which seem pretty rotten.}
{220}{}{I don't know what I did to offend you, smoothskin. But you need to change your attitude around here.}
{221}{}{Maybe. Goodbye.}
{222}{}{That's so sad. I can't imagine what it's like to live for a century among ruins.}
{223}{}{Then you haven't lost much in this life. Hope you enjoy it here.}
{1223}{}{Then you haven't lost much in this life. Hope you enjoy it here.}
{224}{}{Maybe. Bye.}
{225}{}{I don't know what I did to offend you, leatherface. You need to change your attitude around here.}

{230}{}{You know, these lands once belonged to Mexicans. Then the Americans came and took it. But the War erased the borders. Now this land belongs to mutants without race or nationality.}
{231}{}{That's just how it is, I guess.}

{250}{}{Write "Arizona" in the dust on the bar counter.}
{251}{}{Nec-cropolis?}
{252}{}{[Express disgust at the ghouls' cowardice]}
{253}{}{[Show approval]}
{254}{}{Why?}
{255}{}{[Twirl finger next to your head]}
{256}{}{[Pat on the shoulder]}
{257}{}{[Leave]}
{258}{}{Bye!}
