{100}{}{You see John D. Butler.}
{101}{}{You see a ghoul in a worn-out business suit.}
{102}{}{Are you heading to naval base? Private Gomer wants to go too!}

#Introduction
{200}{}{Hey there. Looks like we haven't met before. I'm John Butler, elected mayor of Dayglow. And who might you be?}
{201}{}{Nice to meet you, Butler. I'm }
{202}{}{, just another poor soul mutated by the wasteland.}
{203}{}{Don't try to cozy up to me, ghoul.}
{204}{}{(sigh) Never thought I'd see one mutant curse out another for being a mutant.}
{205}{}{The wasteland throws all kinds at you.}
{206}{}{I'm John Butler. I run this town... or what's left of it. And I welcome any smoothskin who behaves in my town.}
{207}{}{I have no intention of causing trouble here.}
{208}{}{Good. People and super mutants already drove us from our homes. You've probably heard the story. But that's no reason to hate everyone. I want to show people that ghouls are still, um, human too...}
{209}{}{Are you joking? I thought ghouls hated normies.}
{210}{}{We moved here because humans and super mutants drove us from our homes. But that's no reason to hate everyone. On the contrary, I want to prove to people that ghouls are, uh, human too...}
{211}{}{Wordplay isn't your strong suit, John.}
{212}{}{You're right. This soldier's got no humor. Old habits die hard, even after a hundred years. So, how can I help you?}
{213}{}{Nothing for now, thanks.}
{214}{}{That's very noble of you.}
{215}{}{To hell with us old folks. We've survived many wars and battles, our fate is in the past. What matters is what happens to your generation... So, how can I help you?}
{216}{}{Just wanted to say hello. But now I gotta go.}
{1216}{}{Just wanted to say hello. But now I gotta go.}

{220}{}{Well, well, if it isn't our old pal, Gomer. And he's brought a human? That's newsworthy! Like a snake making friends with a rabbit. I'm really happy for you.}
{1220}{}{Well, well, if it isn't our old pal, Gomer. And he's brought a human? That's newsworthy! Like a snake making friends with a rabbit. I'm really happy for you. Too bad we don't have a church to get you two married.}
{221}{}{Gomer is my bodyguard.}
{222}{}{I command Gomer. He can't even take a leak without my say-so.}

#Repeat Dialogue
{230}{}{Alright. How can I help you?}
{231}{}{Hello, smoothskin. Got a question?}
{1231}{}{Hello, smoothskin. Got a question?}
{232}{}{Hello, young wasteland mutant. How can I help you?}
{233}{}{Hey, John. Just passing through. See you.}
{234}{}{Shame we didn't chat longer. If you need anything - I'm always here...}
{235}{}{Goodbye.}
{236}{}{What do you need?}
{237}{}{Enough joking around. Time to get to business.}

{240}{}{Tell me, how did you all end up here?}
{241}{}{We lived up north in a city called Necropolis. Then came the super mutants - and after them, the normies. They fought each other and forgot all about us... but once the dust settled, the normies decided they didn't like ghouls either. So we set out to find a new home.}
{242}{}{What kind of city are you trying to build?}
{243}{}{Just a normal, functioning city. With trade and economy, hotels and casinos, roads and skyscrapers. And enough room for everyone - ghouls, humans, and mutants alike.}
{244}{}{Thanks for the info. I gotta go.}
{245}{}{Can I help with anything?}
{246}{}{Do you really want to help? If it weren't for these glazed eyes, I'd be in tears right now. Ask the corpses around here, I'm sure someone needs help.}
{247}{}{Will do. Goodbye.}
{248}{}{Can I help with anything else?}
{249}{}{Tell me about yourself.}
{250}{}{I've already told you. I'm John Butler. I'm the mayor of Dayglow... well, the future Dayglow.}
{251}{}{Does San Ysidro fall under your control?}
{252}{}{It's one of the districts of future Dayglow. There are several ghoul camps in the ruins. Old Town and San Ysidro are the largest. Each is managed by its own mayor.}

#Story Quests
{259}{}{I knew there was a reason we needed that radio station fixed. A caravan from the Far Go Traders just contacted us. They got ambushed on Route Five. Ghouls are too slow and weak. We just can't get there in time. Our only hope lies with you. Go help them out before its too late!}
{260}{}{I'm already on my way!}
{261}{}{As usual, you're of no use. Fine, I'll take care of it.}
{262}{}{The caravan is at the highway junction. Head straight north on the main road.}
{263}{}{Are the Far Go Traders still alive?}
{264}{}{I haven't had a chance to check on them. I'll be back when I know more.}
{265}{}{Mr. Rutger told me about your heroic deed. Saving the caravan helped us ghouls out a lot. We need goods from the north, and the Far Go Traders are the most reliable caravan company. So thank you }
{266}{}{.}
{267}{}{, you're pretty decent for a smoothskin.}
{268}{}{No problem.}
{269}{}{I can see by your eyes that your mission failed. Well, Rutger was the best caravaner. Without him and his company, trading with humans will be harder. But Gustavo will be pleased to hear this. He doesn't want to share Old World finds with smoothskins.}
{270}{}{That was the plan all along.}
{271}{}{It's a shame it ended that way. But I tried my best.}
{1271}{}{It's a shame it ended that way. But I tried my best.}
{272}{}{Now I need to think on my next course of action. I won't need anything from you for a while.}
{273}{}{Alright.}
{274}{}{}
{275}{}{}
{276}{}{}
{277}{}{}
{278}{}{}
{279}{}{}

#Story Quests
{300}{}{Gustavo asked me to give you this disk.}
{301}{}{Hand it over. Let's see what this old stiff is up to... Hmm. This is some real progress! Now Dayglow has power and radio communication. Just like in the good old days. What could be better?}
{302}{}{[Continue]}
{303}{}{Ah yes, Gustavo's at it again, demanding we cut ties with the smoothskins. The old geezer just doesn't get it. See, Gustavo wants to shut the city off from outsiders, but I think that's foolish. We need the goods and supplies from the Hub, and they need Dayglow's tech. Tell me you're not planning to indulge his nonsense, are you?}
{304}{}{No, I'm not.}
{305}{}{I don't care, as long as I get paid.}
{306}{}{Great. Then I have a couple of small and easy tasks for you.}
{307}{}{I'm listening.}
{308}{}{What if I am?}
{309}{}{That would be sad. And very foolish.}
{310}{}{Not convinced. I'm heading back to San Ysidro.}
{311}{}{Alright. You convinced me. What do you need done?}
{312}{}{That would be sad. And very foolish. Tell me, do you care who pays for the job? I need your services too.}
{313}{}{What do you need done?}

{320}{}{Right now, the scavengers are tearing apart the old aircraft factory, piece by piece. I don't mind that it's those smoothskins doing it, but they're working without Set's Seal and even forcing ghouls into labor. Most importantly, we need the electronics from that factory for the next caravan. Head over to the factory. Tell the scavengers I'll give them Set's Seal, but they gotta get all the chips, right away, and let those ghouls go. And not a word to Gustavo!}
{321}{}{What is "Set's Seal"?}
{322}{}{It's the right to scavenge for resources in San Diego and its surroundings. Naturally, in exchange for a share of the profits. A kind of tax. If the scavengers take all the resources for themselves, our city will be left with nothing.}
{323}{}{Got it. I'll try to talk to them.}
{324}{}{We need to discuss the situation with the scavengers at the Factory.}
{325}{}{So, did you talk with the scavengers?}
{326}{}{No, unfortunately.}
{327}{}{I just want to ask again, what is "Set's Seal"?}
{328}{}{Ah, now I understand.}
{329}{}{It turns out that all the scavengers at the factory are dead.}
{330}{}{All dead? Holy saints! What about the chips? Did you manage to collect them?}
{331}{}{Always glad to help.}
{332}{}{What's in it for me, for all my effort?}
{333}{}{We collected all the chips and sent them here.}
{334}{}{Excellent work.}
{335}{}{Here's your reward. But don't rush off to the bar. We've got a problem here.}
{336}{}{Thanks. What happened?}
{337}{}{No. Should I have?}
{338}{}{The chips were the main point! Since the scavengers didn't succeed, you're our last hope. Bring me those damn chips!}
{339}{}{Alright.}
{340}{}{Yes. Here they are.}
{341}{}{Only some of them.}
{342}{}{The chips were the main point! Since the scavengers didn't succeed, you're our last hope. I need you to collect the remaining chips.}
{343}{}{The factory is now under Gustavo's control. You won't be getting any chips.}
{344}{}{What?! Gustavo beat me to it? Well that's just... Damn it! But right now we have a bigger problem. We'll have to put this setback aside.}
{345}{}{What happened?}
{346}{}{Where is the aircraft factory located?}
{347}{}{Get to Highway 805. Find the Paradise Valley Hospital there. The Factory will be to the east.}
{348}{}{Got it.}
{349}{}{}

{350}{}{I've thought it through, and made a big decision! The contract Mr. Rutger had is from the Hub - a technology exchange, but only if Dayglow's ghouls secure the Coronado naval base. With control of that base, the contract - and all the riches that come with it - will be ours. This could be the key to rebuilding Dayglow from the ground up! The dream of Dayglow would be fulfilled!}
{351}{}{Take control of the naval base? What's the catch?}
{352}{}{It's inaccessible right now due to the base's still-active shore defenses. However, we managed to assemble a transponder from the scrap at the Plant. The final step is setting its ID so the military base accepts it as friendly. Perfect job for that San Ysidro radio station you restored. Here. Use these security codes with the radio station so the base accepts the transponders ID as friendly. Once that's done, head to the pier where a team will be waiting. Then we'll take that base! Oh, and don't tell Gustavo about this...}
{353}{}{[Leave]}

# added by cambragol
{354}{}{Where did you get the security codes?}
{355}{}{They were found in the Glow. It's another military base not too far from here. Excavations are currently underway there.}
