{100}{}{You see a crazed ghoul.}
{101}{}{You see one of the ghouls. He's muttering something unintelligible.}

{110}{}{I'm a man without a heart. No heart! You know why? Do you?}
{111}{}{A monster took root in there... ate it up, chewed it clean. Now it's gone.}
{112}{}{Ain't much time left.}
{113}{}{One last chance, that's all we got.}
{114}{}{Where's my skull-scraper?}
{115}{}{We've all lost somethin'. We're all lost.}
{116}{}{Sing somethin' for goodbye.}
{117}{}{I only want one thing... to see the light.}
{118}{}{Rest in peace, smoothskin.}
{119}{}{Welcome to hell, baby.}
{120}{}{*low muttering*}

