{100}{}{You see a ghoul.}
{101}{}{You see an ordinary ghoul.}

{102}{}{Oh, thanks, you're just in time.}
{103}{}{Hey, this food's cold! Oh well, can't be helped. Hand it over.}
{104}{}{Do you enjoy delivering food? Thanks.}
{105}{}{This is just what I wanted!}
{106}{}{Thanks. But I don't have any tips.}
{107}{}{(}
{108}{}{) of the clients have received their order.}
{109}{}{This client has already received their order.}

{110}{}{Whoa! A human - haven't seen one of you in a while!}
{111}{}{Smoothskins in Dayglow? Now I've seen everything!}
{112}{}{What are these normies even doing here?}
{113}{}{Just what we needed - more smoothskins hanging around.}
{114}{}{Even here, smoothskins gotta poke their noses in.}

{115}{}{This one... yeah, they seem alright.}
{116}{}{A human in Dayglow? They must be crazy.}
{117}{}{Normies sure messed up. They'll figure it out sooner or later.}
{118}{}{Maybe not all smoothskins are that bad... maybe.}
{119}{}{We just want to live our lives without smoothskins meddling.}

{120}{}{Smoothskins never leave us alone, do they?}
{121}{}{Guess my line yet?}
{122}{}{Dayglow's not so bad, y'know?}
{123}{}{Wish old Harold was still around - he headed up north.}
{124}{}{Hold still! I dropped my brains... haha, classic ghoul joke!}
{125}{}{I still get nostalgic about Necropolis sometimes.}
{126}{}{Necropolis is even deader now than before.}
{127}{}{Just thinking about Set still gives me the shivers.}
{128}{}{Where's my hair gone? Oh yeah, lost it back in '77 - ha!}
{129}{}{Sometimes I remember little pieces of my old life... strange, that.}

{130}{}{Everyone who could, headed off to Coronado Island.}
{131}{}{Haven't seen this much buzz among ghouls in ages!}
{132}{}{Whoever opened the way to Coronado for us - now that's a real hero.}
{133}{}{Coronado's ours now, baby!}
{134}{}{Time to live it up with all that sweet loot from Coronado!}

{135}{}{Had big plans for Coronado, I did...}
{136}{}{Coronado could've been our Klondike! A real gold rush - what a loss.}
{137}{}{Nothing left of Coronado Island now...}
{138}{}{An old bomb went off there. Wonder if it just happened or someone helped it along?}
{139}{}{Lucky me - I wasn't on the pier when it blew.}

{150}{}{Standing tall, boss! Just like you asked!}
{151}{}{Greetings, officer.}
{152}{}{I'm a law-abiding ghoul, I am.}
{153}{}{Nice to see some law around here... oh, wait, that's not even a real badge, huh?}
{154}{}{What, you got nearly a hundred years of service under your belt?}
{155}{}{Some folks used to mess with the law like that... led right into World War III.}
{156}{}{Wait... am I under arrest?}
