{100}{}{You see Mr. De Santi.}
{101}{}{You see a ghoul in a pre-war suit and fedora. A long scar runs across his face.}
{102}{}{This is Albert De Santi.}

{200}{}{You come to the right place, kid. Name's Albert De Santi. This here's my joint - La Pensione Hotel and Spa.}
{1200}{}{You come to the right place, sweetheart. Name's Albert De Santi. This here's my joint - La Pensione Hotel and Spa.}
{201}{}{[Continue]}
{202}{}{Here, you can forget about all the rough stuff out there. We got massages, old-school flicks, clean baths, rad-tanning, fancy rat dishes - anything you got a taste for, just let me know.}
{203}{}{Seriously? You opened a spa in the middle of these burned-out ruins? Who would come here?}
{204}{}{Take it easy, kid. A place like this? It's actually the safest spot... Well, 'cept for those lunatics across the street. They're puttin' up with other ghouls for now, but that ain't gonna last forever.}
{1204}{}{Take it easy, sweetheart. A place like this? It's actually the safest spot... Well, 'cept for those lunatics across the street. They're puttin' up with other ghouls for now, but that ain't gonna last forever.}
{205}{}{Alright. I'll keep that in mind.}

{210}{}{What's on your mind, kid?}
{1210}{}{What's on your mind, sweetheart?}
{211}{}{Nothing. See you around.}
{212}{}{See you around, Mr. De Santi.}
{213}{}{Catch you later, Mr. De Santi.}
{214}{}{Ah, nothin' like the smell of caps before bed. Alright, kid, you really earned half.}
{215}{}{(shakes the bag of caps) Ah! Love the sound of caps during lunch. Alright, kid, you really earned half.}

# Quests
{220}{}{Have you tried dealing with the crazies in the building next door?}
{221}{}{I'll throw in 100 hubbucks for every one of 'em you take out. You get it done, the caps are yours.}
{222}{}{Don't you feel bad for them? They're your... kin after all.}
{223}{}{Listen up, kid: in this business, there's only one rule - shoot first, shoot fast, shoot often. That's how you survive.}
{1223}{}{Listen, sweetheart, in this business, there's only one rule - shoot first, shoot fast, shoot often. That's how you survive.}
{224}{}{Deal. I was looking for a way to earn quick money. Consider it done.}
{225}{}{No. I'm not gonna do that.}
{226}{}{All the crazies have been taken care of.}
{227}{}{Here you go, kid. Easy money. Good thing you came by.}
{1227}{}{Here you go, sweetheart. Easy money. Good thing you came by.}
{228}{}{I like your business approach, mister. I can keep working for you, if there's more caps. Maybe there's someone else you need dealt with?}
{229}{}{Well... there is another little 'problem'. You know Derrick? He's dealin' right near the entrance, cuttin' into my profits. I don't like that. Do somethin' about him.}
{230}{}{Okay.}
{231}{}{Derrick won't cut into your profits anymore. 'Problem' is solved.}
{232}{}{Too bad! 'Course, we don't know who did it, right? (winks and hands you 100 caps) Guess I'll have to clean up the mess out front.}
{233}{}{[Leave]}
{234}{}{Derrick has reconsidered his future plans. He's willing to work for you.}
{235}{}{Nice work, kid. You earned a little extra for this. (winks and hands you 150 caps)}
{1235}{}{Nice work, sweetheart. You earned a little extra for this. (winks and hands you 150 caps)}
{236}{}{[Leave]}
{237}{}{Are you sure killing the crazies is a good idea?}
{238}{}{I get it.}
{239}{}{Remind me, why does Derrick bother you?}
{240}{}{He's dealin' right at the entrance, cuttin' into my profits. That ain't gonna fly. Do somethin' about him.}
{241}{}{Okay.}
{242}{}{Got any more work?}
{243}{}{Let's see... There's a rat who skipped out to Old Town without payin' what he owes.}
{244}{}{What's this guy's name?}
{245}{}{Name's Kurt. He's short 300 caps. Shake it outta him, and half is yours.}
{246}{}{Alright.}
{247}{}{Here are the caps Kurt owed - exactly 300 of them.}
{248}{}{Ah, nothin' like the smell of caps in the mornin'. Alright, kid, you earned your cut.}
{249}{}{Of course.}

{250}{}{It looks like everything is falling apart here. Need some repairs done?}
{251}{}{You got it, kid. Takin' care of this place alone? It's no picnic. Could use a bit of a tune-up, that's for sure.}
{252}{}{I could do it for a moderate fee.}
{253}{}{Sorry, but I can't help with that.}
{254}{}{Actually, I know someone better suited. Don't even need to pay him. He's sittin' in the pantry across the street - it's a 'Mr. Handy'. Just gotta get him up and runnin' and load a hotel manager program on him. I'll pay you 300 hubbucks if you pull it off.}
{255}{}{Alright, I'll do it.}
{256}{}{Then get to work, kid. Parts, you can probably scavenge anywhere, but that hotel manager program? Check Old Town.}
{1256}{}{Then get to work, honey. Parts, you can probably scavenge anywhere, but that hotel manager program? Check Old Town.}
{257}{}{Okay.}
{258}{}{I got the robot up and running. But where can I find a program for him?}
{259}{}{You'll need that hotel manager program. Best bet? Try Old Town.}
{260}{}{Your Mr. Handy is ready to go.}
{261}{}{Good work, kid. Here's your pay. And hey, I got more jobs if you're still interested.}
{1261}{}{Good work, honey. Here's your pay. And hey, I got more jobs if you're still interested.}
{262}{}{What are they?}
{263}{}{Got it.}
{264}{}{Not interested. I don't want to fix old tech.}
{265}{}{One of my clients wants an old cult flick - "Deep Throat." Whaddaya mean, you ain't heard of it? Ah, you're missin' out! A classic! Anyway, someone in San Ysidro's got a copy. Grab it for me, and we'll split the loot.}
{1265}{}{One of my clients wants an old cult flick - "Deep Throat." Whaddaya mean, you ain't heard of it? Ah, you're missin' out! A classic! Anyway, someone in San Ysidro's got a copy. Grab it for me, and we'll split the loot.}
{266}{}{Alright.}
{267}{}{Where did you say I can find that movie?}
{268}{}{One of the ghouls in San Ysidro has it. Don't know exactly who, though.}
{269}{}{Got it.}
{270}{}{Here's the movie you were looking for.}
{271}{}{Ah, love them old classics. But I wouldn't recommend watchin' it, kid - you're too young for this sorta thing. Just take the caps and fuhgeddaboudit.}
{1271}{}{Ah, love them old classics. But I wouldn't recommend watchin' it, honey - you're too young for this sorta thing. Just take the caps and fuhgeddaboudit.}
{272}{}{Okay.}
{273}{}{Got one more job for ya, but it ain't small potatoes. I'll pay good - 500 hubbucks - but listen, kid, I don't take failure lightly.}
{274}{}{Tell me what to do.}
{275}{}{Don't tak... Hold on, mister. That's enough. I'm getting a little tired of your attitude. I'm out.}
{276}{}{Somewhere on the way to San Ysidro, a courier bot with an important part got... misplaced. I need that part. Chop-chop, kid, move it.}
{1276}{}{Somewhere on the way to San Ysidro, a courier bot with an important part got... misplaced. I need that part. Get movin', honey.}
{277}{}{[Leave]}
{278}{}{Watch that mouth, kid. Alright, take a hike. Don't need ya around here no more.}
{1278}{}{Watch that mouth, honey. Alright, take a hike. Don't need ya around here no more.}
{279}{}{[Leave]}
{280}{}{Can you be more specific about where the courier robot is?}
{281}{}{Somewhere between here and San Ysidro. Highway's your best bet. That's all I know.}
{282}{}{Got it.}
{283}{}{Here's the part you were looking for.}
{284}{}{Nice work, kid! Ain't had a sharp one like you in the crew... uh, team. Here's your pay. But I think I'm outta jobs for ya. Take it easy now, kid.}
{1284}{}{Nice work! Knew I could count on ya, honey. Here's your pay. But I think I'm outta jobs for ya. Take it easy now, toots.}
{285}{}{Then I'll go cut loose I guess. Goodbye, partner.}
{1285}{}{Then I'll go cut loose I guess. Goodbye, partner.}
{286}{}{By the way, why is this part labeled as Ed's property?}
{287}{}{Don't ask unnecessary questions, kid. I'm payin' ya to get things done, not think.}
{1287}{}{Don't ask unnecessary questions, honey. I'm payin' ya to get things done, not think.}
{288}{}{[Leave]}
{289}{}{Hey, kid, you got things twisted? Heard ya handed that part over to San Ysidro. What's goin' on here?}
{1289}{}{Hey, honey, you got things twisted? Heard ya handed that part over to San Ysidro. What's goin' on here?}
{290}{}{Well, it isn't yours, right?}
{291}{}{Guess you're right. But that don't matter - you work FOR ME. Damn shame, kid. Ya really let me down. Get outta my sight, now!}
{1291}{}{Guess you're right. But that don't matter - you work FOR ME. Damn shame, honey. Ya really let me down. Get outta my sight, now!}
{292}{}{[Leave]}
{293}{}{Alright, let's get down to *real* business. There's a bunch of rogue scavengers nearby. They're diggin' through MY ruins without payin' up. They should be workin' for me, and if not, they can get off my turf! Go handle it.}
{294}{}{Will do.}
{295}{}{Nah, that isn't for me. I'm here to earn caps, not be some muscle for your shady deals.}
{296}{}{Disappointed, kid. Thought we were friends. And friends don't turn on each other. So here's a tip: watch your back.}
{297}{}{I'm done with this business with the scavengers.}
{298}{}{The 'problem' with the scavengers has been... resolved.}
{299}{}{Once again, you came through for me.}


# Services
{300}{}{I want to relax.}
{301}{}{Sorry, kid, but my services aren't suited for smoothskins.}
{1301}{}{Sorry, honey, but my services aren't suited for smoothskins.}
{302}{}{That's a shame.}
{303}{}{Not suitable at all? But my caps are just begging to be spent.}
{304}{}{Admit it, you just don't like smoothskins, do you?}
{305}{}{It's just business, kid. I can't have a client boiling alive. But since you're so sensitive, I could tell my ghoul friends that you're a smoothskin worth knowing - for a fee.}
{1305}{}{It's just business, honey. I can't have a client boiling alive. But since you're so sensitive, I could tell my ghoul friends that you're a smoothskin worth knowing - for a fee.}
{306}{}{No thanks. I'll earn my reputation the old-fashioned way.}
{307}{}{Deal.}
{308}{}{Waiting for the caps, kid. Reputation doesn't come cheap.}
{1308}{}{Waiting for the caps, honey. Reputation doesn't come cheap.}
{309}{}{I'm a little short right now.}
{310}{}{(quickly counts the caps) You've got my word - I'll make you a tale that'll impress every ghoul around.}
{311}{}{I'm counting on you.}
{312}{}{Just no tricks. I don't like that.}
{313}{}{ caps. Deal?}

{320}{}{For starters, I'd suggest a healing bath with my 'charming' attendant. And if you've got time and caps to spare, we offer a full hotel stay with movies, music, and therapeutic amenities. All services geared especially for mutants and ghouls!}
{321}{}{I like the sound of the bath for now. How much does it cost?}
{322}{}{ caps.}
{323}{}{Alright. Here's the caps.}
{324}{}{I'll think about it. How much does the 'full stay' package cost?}
{325}{}{Maybe another time.}
{326}{}{I'm interested in the second option.}
{327}{}{For }
{328}{}{ caps, we offer everything from uranium baths and massages to meditation and mushroom smoking. A ghoul picks up a lot of grime over the years.}
{329}{}{I like the sound of that. Here's the caps, I'm all yours.}
{330}{}{I don't have that much money. But a bath sounds good.}
{331}{}{For that much, I could arrange all this myself! Goodbye.}
{1331}{}{For that much, I could arrange all this myself! Goodbye.}
{332}{}{The therapeutic procedures have done you good. Your endurance has increased.}
{333}{}{The therapeutic procedures restored your health. Though you expected something more.}

{350}{}{Once again, you haven't let me down. Now, I've got one last task for you. There's a super mutant named Flowers. Right now, his aimless, lonely body's wandering Highway 805, searching for his 'purpose.' Bring him to me. Let him know I'll give him a place here if he's willing to work.}
{351}{}{Got it.}
{352}{}{I've got Flowers right here.}
{353}{}{He's here, kid! Perfect! Flowers'll be my hotel 'bouncer,' the ideal job for him. But... uh, I've got no more work for you. Here's your final payday, friend. Enjoy your retirement.}
{354}{}{[Leave]}
{355}{}{Flowers is dead.}
{356}{}{That's rotten news, kid. And I don't take kindly to rotten news. You've let me down. Get out. No more work for you.}
{357}{}{[Leave]}
{358}{}{Flowers didn't want to work for you. He joined the scavengers.}

