{100}{}{You see Frank.}
{101}{}{You see a ghoul in a business suit and hat, just like in the good old days.}
{102}{}{Thank you, friend. Without you, this story could have ended very badly.}
{103}{}{Don't touch me, smoothskin! I'm on edge right now.}
{104}{}{Sorry, I'm too flustered to talk right now.}

{110}{}{Jane, if we find him, I'll stop drinking. I promise.}
{111}{}{Prepare for the worst, Jane.}
{112}{}{This would have happened someday anyway.}
{113}{}{Don't cry. Or else I'll start crying too.}
