{100}{}{You see Gomer.}
{101}{}{You see a super mutant. He's wearing an army helmet and camouflage pants.}

{102}{}{Don't you touch Nightkin, normie!}
{103}{}{Gomer not forget this, normie!}
{104}{}{Brothers, Gomer with you!}
{105}{}{My friends? Ho-ho! You know whose side Gomer's on now!}
{106}{}{Don't mess with the Nightkin!}
{107}{}{Gomer will never forgive you for this!}
{108}{}{Brothers, Gomer here! Ready to fight!}
{109}{}{See my buddies? Don't make 'em mad.}

{110}{}{Master was right - all of you shoulda been part of Unity!}
{111}{}{Hello.}
{112}{}{[recruit to party]}
{113}{}{[remove from party]}
{114}{}{[holster weapon]}
{115}{}{Goodbye.}
{116}{}{Right! No need for fightin'. Gomer agrees.}
{117}{}{}
{118}{}{}
{119}{}{}

{150}{}{Dead folks live here. They no like strangers, but they won't hurt you.}
{151}{}{Biggest ghoul camp. Normies come here too.}
{152}{}{Heart of the ruins. Not many been here. Too dangerous.}
{153}{}{Gomer not go past outpost yet.}
{154}{}{See the island? Used to be a naval base. It's all busted now.}
{155}{}{}
{156}{}{If big beast show up, don't worry. Gomer protect you!}
{157}{}{Gomer can't do that. Gomer is too big.}
{158}{}{You treat ghouls bad. Gomer no stay with you no more.}
{159}{}{Gomer leave now. You fix reputation, and Gomer might come back.}

#First Dialogue
{200}{}{A human here with all the ghouls? That's... fishy!}
{201}{}{No, I... never mind. Just don't touch me, big guy. Agreed?}
{202}{}{Even a human tells Gomer what to do. Ghouls don't want Gomer around either. Nobody needs Gomer!}
{203}{}{Whoa-whoa, easy! I don't want you to get upset. I just thought ghouls don't get along with those like you.}
{204}{}{No... humans aren't welcome either. Gomer's old squad threw him out. Ghouls said they'd take care of Gomer if he was good, if he helped. Gomer tries hard. But still... they don't like Gomer.}
{205}{}{Who needs a mountain of green muscle like you?}
{206}{}{Gomer got kicked out of his squad. Ghouls said if Gomer helped here and behaved, they'd keep him around. Gomer tries real hard. But they still don't like Gomer.}
{207}{}{Sad. But understandable. }
{208}{}{What did you expect, you blockhead? You shouldn't have gotten expelled from your squad.}
{209}{}{Just a little more and Gomer will be respected. Ghouls will see how good Gomer is. Gomer will help them, even if they don't want him to.}
{210}{}{Great. I'm also helping the ghouls. Maybe we should join forces? You watch my back on the road, and I'll help you earn respect.}
{211}{}{I've got business here. What are *you* doing here? Are mutants welcome around here?}
{212}{}{Ghouls will never accept you. Forget about them and help me. I respect your muscles.}
{213}{}{That's very noble of you. Good luck. I gotta go now.}
{214}{}{Go, human. Gomer won't hurt you... unless you hurt the ghouls.}
{215}{}{Goodbye, Gomer.}
{216}{}{Maybe we should team up? I need your muscles out there. I'll help you regain respect.}
{217}{}{A mutant and human in same team? Ha-ha! Funny! But if Gomer is useful, he will be happy.}
{218}{}{That's right. Come with me. Together we'll make a great team.}
{219}{}{Great. I'll come back and get you when I need your help.}
{220}{}{What do you want, brother-mutant?}
{1220}{}{What do you want, sister?}
{221}{}{I don't need anything from you. Just don't touch me, big guy. Agreed?}
{222}{}{You don't trust Gomer either. Nobody does. Nobody needs Gomer!}
{223}{}{What are you doing here? How did you end up among the ghouls?}
{224}{}{That's the spirit! You know, we could help each other: you watch my back on the road, and I'll help you earn respect. Deal?}
{225}{}{If Gomer can be useful, Gomer will be happy.}
{226}{}{I need you. Come with me.}
{227}{}{Private Gomer will do his best!}
{228}{}{At ease, soldier.}
{229}{}{Private Gomer, you're  dismissed.}
{230}{}{Aww, too bad. Gomer wanted to help. But... don't forget Private Gomer.}
{231}{}{See you.}
{232}{}{Put away your weapon. It's not needed right now.}
{233}{}{Yes, putting away the weapon!}
{234}{}{Good boy.}

{240}{}{Awaiting orders... uh... boss.}
{241}{}{At ease, Gomer.}
{242}{}{Captain! Private Gomer ready to help! Gomer follow orders!}

{250}{}{Will you come with me to Sonora? I could use your back-up on the road.}
{251}{}{Go with humans? No way. Humans not want Gomer around.}
{252}{}{Alright, as you say.}
{253}{}{Your fellow super mutants are getting ready to attack these caravaners. Can you talk them out of it?}
{254}{}{No, no, they don't listen to Gomer. They kicked Gomer out. Don't respect Gomer. But... Gomer won't let his mutant friends get hurt!}
{255}{}{Got it.}

{260}{}{Tell me about yourself.}
{261}{}{Me? Gomer. Private Gomer. Why?}
{262}{}{Alright. Let's just forget it.}
{263}{}{Is Gomer a name or a nickname?}
{264}{}{It's... uh... Gomer forgot! Gomer's name from radio! From radio call-sign! Not real name. Gomer forgets what real name was. Nothing left from before the 'change'.}
{265}{}{You don't remember who you were before the... change?}
{266}{}{Yes. And Gomer doesn't want to remember. Humans weak, with their tiny problems. The Master tried to make humans better... but he didn't get to finish.}
{267}{}{You can tell me. The memories must torment you sometimes. You can't just erase an old life.}
{268}{}{You think that why Gomer so dumb? That why he talk to himself at night? Gomer doesn't like to remember... he was human, he... uh...}
{269}{}{[Comfort]}
{270}{}{[Mock]}
{271}{}{How did you end up in Dayglow?}
{272}{}{Came here with squad. Walked desert long time. Brotherhood chased us, killed Gomer's friends, drove us out into wasteland. We had no choice, had to leave.}
{273}{}{[Continue]}
{274}{}{On way, met ghouls. They told us 'bout Dayglow. They were running too, from the humans. Humans hate everyone.}
{275}{}{Why aren't you with your squad?}
{276}{}{There was big hunger. Gomer so hungry... he ate all food. Shameful! They threw Gomer out after that. Haven't seen them since.}
{277}{}{Do you know where your squad is now?}
{278}{}{Maybe in ruins. Gomer will know if he listens for them on radio.}
{279}{}{Now we know where your squad is. Do you want to meet your old friends?}
{280}{}{Gomer miss them... but they don't need Gomer.}
{281}{}{Don't worry about that. I'll take care of it. Let's go.}
{282}{}{Did you hear? Your captain is in trouble.}
{283}{}{Gomer MAD! Humans cause all this! They will pay!}
{284}{}{So you want to rescue the captain even though you were expelled from the squad?}
{285}{}{Gomer ready. Let's go, human! Forward!}
{286}{}{Alright. Let's go.}
{287}{}{Alright. If you don't want to, we won't deal with them.}
{288}{}{I have a radio, but due to high radiation, it won't work without a functioning radio station.}
{289}{}{I have a radio. Shall we try?}
{290}{}{No use. Radiation messes it up. We need strong antenna. Maybe ghouls got one?}
{291}{}{Hmph. So that's why the radio doesn't work... Alright, maybe we can find a relay.}
{292}{}{(Gomer adjusts the frequency and carefully listens to the communications. All the veins on his face bulge from concentration. Finally, he says: "They are in Balboa Park.")}
{293}{}{Good. Then we go to Balboa Park.}
{294}{}{There was a radio station in San Ysidro. Let's try to find them from there.}
{295}{}{There's a radio station here. Shall we try?}
{296}{}{No good. No work.}
{297}{}{Indeed. It doesn't work.}
{298}{}{Nothing! Need higher ground.}
{299}{}{Alright.}

{300}{}{This is it! Damn paladins holdin' captain here!}
{301}{}{What's your plan?}
{302}{}{Plan? Gomer no need plan! Gomer stronger than paladins! Gomer smash 'em! That the plan.}
{303}{}{Good plan. Reliable as clockwork. Go ahead, Gomer! Kick those bastards' butts!}
{304}{}{No, Gomer, you can't kill the paladins. It's too dangerous. We have to rescue the captain without violence. Do you understand?}
{305}{}{Grrr! Stupid humans! Gomer want fight! Gomer not hide like coward!}
{306}{}{Alright... if you think about it, your idea *is* the simplest and safest. Go ahead, Gomer! Kick those bastards' butts!}
{307}{}{No! We have little chance in an open fight. Let's scout first.}
{308}{}{If Gomer sees paladin, Gomer smash. You remember that, human.}
{309}{}{Alright. I'll keep that in mind.}
{310}{}{You know, it would be better if I scout first and you wait here. That's an order, Gomer.}
{311}{}{Gomer grateful to you for saving captain. Gomer couldn't do it alone. Thanks to you.}
{312}{}{A mutant saying "thank you"? That's something new!}
{313}{}{Don't thank me yet. We still need to meet up with your squad.}
{314}{}{Yes. Gomer must meet the squad again.}
{315}{}{Then let's head to the camp. Let's go.}
{316}{}{What about captain? Captain okay?}
{317}{}{Don't get upset, Gomer. The captain is dead. And so is your squad.}
{318}{}{DAMN BROTHERHOOD! Gomer HATE THEM! HATE THEM ALL!}
{319}{}{I think it's best to give you some time alone.}
{320}{}{Don't get upset, Gomer. The captain is dead.}
{321}{}{What do you plan to do now without your squad?}
{322}{}{Gomer work hard for ghouls. Ghouls need strong Gomer. Ghouls won't regret takin' him in. Gomer will be useful. Will make Gomer happy. Yes.}
{323}{}{I see. Well, I hope you'll stick with me a bit longer before I return to Sonora.}
{324}{}{The squad is ready to accept you again.}
{325}{}{Squad... forgive Gomer? Gomer happy! But he promised ghouls he'd help. Can Gomer be trusted if he breaks promise again? Tell Gomer, human - what best choice for Gomer?}
{326}{}{I think you should go with the squad. You'll probably be happier with your own kind, anyway. Besides, you don't owe the ghouls anything.}
{327}{}{You ought to stay with the ghouls and help them rebuild. They could really use your strength. And let's be real - your squad turned their backs on you once; they might do it again. Besides, who knows what kind of trouble they'll run into out there in the wastes.}
{328}{}{Gomer will make sure to never lose trust again! Squad will be proud to have Gomer back. Yes. Gomer will be useful and happy. That's all Gomer ever wanted.}
{329}{}{Glad that we sorted out your problem. I hope you'll stay with me a bit longer before your squad heads out of Dayglow.}

