{100}{}{You see Mr. MedBot.}
{101}{}{You see a Mr. MedBot series medical robot.}
{102}{}{Wee-oo! Wee-oo! Make way for the medics!}

{200}{}{I regret to inform you that I was unable to save these individuals. My deepest apologies.}
{201}{}{Sir, this area is unsafe for you. Please consider relocating.}
{202}{}{Sir, should you contract radiation sickness, my assistance may be limited.}
{203}{}{Sir, I am detecting heightened radiation levels. It would be prudent for you to leave this area.}
{204}{}{I am doing everything within my capacity. Unfortunately, these individuals cannot be revived.}
{205}{}{Apologies, sir, but I must focus on treating the injured here.}
{206}{}{There are numerous casualties - conditions resemble a recent conflict.}
{207}{}{Sir, may I ask if you are familiar with any of these patients?}
{208}{}{}
{209}{}{Oops, wrong door.}

{1200}{}{I regret to inform you that I was unable to save these individuals. My deepest apologies.}
{1201}{}{Ma'am, this area is unsafe for you. Please consider relocating.}
{1202}{}{Ma'am, should you contract radiation sickness, my assistance may be limited.}
{1203}{}{Ma'am, I am detecting heightened radiation levels. It would be prudent for you to leave this area.}
{1204}{}{I am doing everything within my capacity. Unfortunately, these individuals cannot be revived.}
{1205}{}{Apologies, ma'am, but I must focus on treating the injured here.}
{1206}{}{There are numerous casualties - conditions resemble a recent conflict.}
{1207}{}{Ma'am, may I ask if you are familiar with any of these patients?}
{1208}{}{}
{1209}{}{Oops, wrong door.}

{210}{}{I have a fracture. Help me, doc!}
{211}{}{This condition is quite serious. You require immediate medical attention. Please lie down, and I will do my utmost to help.}
{212}{}{[Follow MedBot's instructions]}
{213}{}{Your condition is stable. Kindly exercise caution in the future.}
{214}{}{Thanks.}
{215}{}{Can you uh, heal people?}
{216}{}{Certainly. I am programmed as a medical assistant robot. However, my current capabilities are limited due to a shortage of medical supplies. May I assist you in any way?}
{217}{}{No, not today.}
{218}{}{No way! I won't trust my life to some soulless machine.}
{219}{}{Private Gomer has a serious injury. Can you heal it?}
{220}{}{Private Gomer's condition is stable. No further treatment is necessary.}
{221}{}{Thanks.}

