{100}{}{You see Falik.}
{101}{}{You see an ordinary ghoul.}
{102}{}{You eavesdropped on the ghoul's confession.}
{103}{}{Don't disturb my prayer!}
{104}{}{Sorry for treating you so badly at first.}

{105}{}{Hey, don't eavesdrop!}
{106}{}{Excuse me, I'm in confession. Do your business quickly.}
{107}{}{You're interrupting my confession, little human!}
{108}{}{Are you eavesdropping?}

{110}{}{Father, you can keep a grave secret, right?}
{111}{}{Do you have a moment to hear my story?}
{112}{}{Listen, Father.}
{113}{}{My friend Zerah - he was a ghoul, like me. Now he's dead for good.}
{114}{}{Not exactly... because of me.}
{115}{}{But I did abandon him.}
{116}{}{It happened in that damn hospital.}
{117}{}{Zerah and I were scavenging when we ran into a pack of rogue scavengers.}
{118}{}{I still get chills, and I don't even have skin!}
{119}{}{They caught Zerah and killed him. And I... I ran and hid.}
{120}{}{Tell me, Father, will God forgive me?}

{200}{}{(Falik is praying fervently.)}
{201}{}{I uh, accidentally overheard your confession.}
{1201}{}{I uh, accidentally overheard your confession.}
{202}{}{[Leave him.]}
{203}{}{You smoothskin bastard! Don't you dare tell anyone!}
{204}{}{I'm not blaming you. I understand. You did what you had to.}
{205}{}{Oh, friend, please don't tell anyone!}
{206}{}{Really? Well, thank you. But Zerah's gone...}
{207}{}{Are you sure he's dead?}
{208}{}{Scum like you piss me off. How could you abandon your friend like that!}
{209}{}{It's easy for you to say! You weren't there! And you didn't even know Zerah. What's it to you?}
{210}{}{Are you sure he's dead?}
{211}{}{He must be... His body's probably still lying there in the hospital. But I don't have the guts to go back and give him a proper burial.}
{212}{}{I could do that. Not for free, of course.}
{213}{}{Okay, I'll look for his body. Your story moved me.}
{214}{}{I don't need your help! Just leave me alone.}
{215}{}{Alright, take it easy. Bye.}
{216}{}{At least see if he's really dead. I'd appreciate that.}
{217}{}{Don't worry about it. Bye.}

{220}{}{(Falik is still praying fervently.)}
{221}{}{[Leave him.]}
{222}{}{Zerah really is dead. His body is lying in the hospital.}
{223}{}{(pauses) Ah... I knew it. Shouldn't have let myself hope. But... at least now I know for sure.}
{224}{}{Life is a bitch. Goodbye.}
{225}{}{I'm very sorry.}
{226}{}{Zerah turned out to be alive. The scavengers captured and tortured him. But I managed to rescue him.}
{227}{}{HE'S ALIVE?! Oh my God, my prayers have been answered! You must have been sent to me by heaven.}
{228}{}{No, heaven has nothing to do with it.}
{229}{}{Believe that if you wish.}
{230}{}{Can I ask you for one more favor? Can you help me reconcile with him? Find him and tell him I want to ask for his forgiveness!}
{231}{}{}

