{100}{}{You see a Nightkin super mutant.}
{101}{}{You see a super mutant in combat gear.}
{102}{}{We Nightkin stay loyal to the Master. Even if Normies leave us alone.}

{200}{}{Hey, human, put down your weapon. We no hurt you if you no attack.}
{201}{}{Hey, friend, no worry. We no hurt you if you no attack.}
{202}{}{Why so friendly?}
{203}{}{Why should I trust you?}
{204}{}{We tired of war. We just want humans to stop hunting us!}
{205}{}{I see. Well, goodbye then.}
{206}{}{Don't stare, little human. I no like being stared at.}
{207}{}{As you say.}
{208}{}{}
{209}{}{}

{210}{}{Tell me, is it true you kicked Gomer out of your squad?}
{211}{}{Gomer? We no want to hear about him. Traitor! He no loyal to us. No excuse for that.}
{212}{}{He might redeem himself.}
{213}{}{No way. Gomer dumb. He not even good at carrying big gun. Too bad captain not here to yell at him again...}
{214}{}{What happened to the captain?}
{215}{}{Brotherhood soldiers catch him. Shame us. Now they hurt him at border place near San Ysidro.}
{216}{}{So why are you standing around here instead of rescuing him?}
{217}{}{It's a trap, stupid human! Brotherhood want catch us all. Captain said when he left: no save him.}
{218}{}{You know, if I were you, I'd be doing everything I could to get the captain back. Come on, Gomer, let's leave these losers.}
{1218}{}{You know, if I were you, I'd be doing everything I could to get the captain back. Come on, Gomer, let's leave these losers.}
{219}{}{I understand. Orders are orders. Come on, Gomer, we need to talk privately.}
{220}{}{You know, if I were you, I'd be doing everything I could to get the captain back. Adios, cowards.}
{1220}{}{You know, if I were you, I'd be doing everything I could to get the captain back. Adios, cowards.}
{221}{}{I understand. Orders are orders.}
{222}{}{Your captain is dead. I couldn't save him from the Brotherhood of Steel.}
{223}{}{We thought so.}
{224}{}{What are you going to do without the captain?}
{225}{}{Is that it? No angry speeches or guttural roars? Do you even know how to survive without the captain?}
{226}{}{Your captain is saved. No need for thanks.}
{227}{}{We didn't ask for help, but you help us anyway. You think humans and mutants can be friends? Impossible. But thanks. If Master not gone, you be good for Unity.}
{228}{}{What are you going to do now?}
{229}{}{Do you have any plans? Or are you going to just keep standing around in the middle of this park?}
{230}{}{We go east. Where they no know about us yet. Away from Brotherhood and other humans.}
{231}{}{What's stopping you from doing that now that the captain is with you?}
{232}{}{What's stopping you from doing that now that the captain no longer holds you back?}
{233}{}{Then I wish you luck on your journey.}
{234}{}{Right. No need to ruin the mood for normal people. I hope you won't bother anyone in the future.}
{235}{}{What about Gomer? Will you take him with you?}
{236}{}{If he want, he can come back to group.}
{237}{}{Alright. He hasn't been the greatest help here anyway.}

