{100}{}{You see Ralph.}
{101}{}{You see a familiar ghoul wearing worn-out pre-war work clothes.}
{102}{}{I wonder how things are going at the power station?}

{200}{}{Well, well! Looks like the Angel of Electromagnetism has brought us together again!}
{201}{}{Ralph? What are you doing here? Weren't you planning to leave for Texas?}
{202}{}{Well, for a while, I didn't want to leave Phoenix. There are some pretty fat rats in the local sewers. But then a wandering ghoul came to town and told me about Dayglow. It occurred to me that it's better to be close to my kind than to perish alone in the sands. What about you? What are you doing here?}
{203}{}{Looking for new adventures... I guess.}
{204}{}{Huh? I don't even know what to say. You're a strange person. Maybe something's not right at home for you? But it'll be tough for you to fit in here - radiation and traces of the Old World are everywhere. }
{205}{}{I know.}
{206}{}{Here, take this RadAway as thanks for your help at the power station. It might come in handy.}
{207}{}{Thanks, Ralph. See you.}
{208}{}{Did you mean - as an apology for what you did there? Alright, I'll take it. See you, Ralph.}
{209}{}{Good luck then. I'll tell the others how I came to my senses with your help. You probably want them to know, because it doesn't seem like you're well-liked around here.}
{210}{}{Thanks, Ralph. I appreciate it.}
{211}{}{It's nothing. I'm not worried about my reputation. Goodbye.}

{220}{}{I had some good times at the power plant. I wonder how things are going there now?}
{221}{}{I don't know. Bye.}
