{100}{}{You see a Mister Officer.}
{101}{}{This robot bears a heavily worn badge. It appears to represent some kind of authority here.}
{102}{}{Be vigilant, citizen. It's currently unsafe on the road.}

{110}{}{Halt! You are violating traffic regulations.}
{111}{}{Pedestrian presence on the highway is a breach of current legislation.}
{112}{}{It is prohibited to be on the highway outside of a vehicle.}
{113}{}{You are under arrest. Exit the roadway and lie face down.}
{114}{}{You are required to accompany me to the nearest police station.}
{115}{}{Surrender now. You cannot evade justice.}
{116}{}{I mean no harm. You have created this situation by your own actions.}
{117}{}{My programming mandates that I stop you.}
{118}{}{All complaints may be addressed with legal representation present.}
{119}{}{You will not be allowed to leave until your fine is paid.}
{120}{}{It is my duty to prevent any potential traffic accident caused by your actions.}

