{100}{}{You see Derrick.}
{101}{}{You spot a ghoul keeping a close eye on everyone who walks by in the streets.}
{102}{}{My business collapsed with De Santi's death.}
{103}{}{Okay! Okay! I'll work for him. Just don't touch my fragile delicate body!}
{104}{}{Derrick isn't looking for another fight.}

{200}{}{Hey, smooth face. Where're you heading?}
{201}{}{None of your business.}
{202}{}{Okay, whatever you say.}
{203}{}{Adios.}
{204}{}{Maybe to Old Town, or maybe to the place across the street, or maybe nowhere. Why do you ask?}
{205}{}{Why do you ask?}
{206}{}{I can give you a lift. Or, are you headed to La Pensione? Just a heads up, though - it's a place for ghouls only, so I wouldn't recommend it for smooth skins like you. Besides, there's not much to do there. But if you're looking for 'relaxation', I can offer you some great options at a low price. Come check it out; you won't regret it.}
{207}{}{Alright, let's see what you've got.}
{208}{}{I can give you a lift. Or, are you heading to La Pensione? It's just for ghouls, like you. But watch out - prices there are as high as my late wife's nagging! I can get you all kinds of 'relaxation' for a better price. Come on over; you won't regret it.}
{209}{}{Hmm, I'll keep that in mind.}
{210}{}{Hello, good-looking. Where're you heading?}
{211}{}{You'll come back for another dose.}
{212}{}{Sure. Bye.}
{213}{}{I doubt it very much.}
{214}{}{What do you mean by "I can give you a lift"?}

{220}{}{Ah, it's you again. What do you want this time?}
{221}{}{Oh, nothing special. Goodbye.}
{222}{}{Show me what you've got.}
{223}{}{"Where" isn't the question, it's "what". Let me see what you're selling.}

{230}{}{Well, Derrick, you've caught my attention. De Santi isn't happy that you're cutting into his profits.}
{231}{}{This is a free town. I wanna deal here, and I will.}
{232}{}{Aren't you afraid this street will become your grave?}
{233}{}{I get why people admire Wild West gunfighters. They faced off in real duels. But De Santi? He was just a small-time, back-stabbing thug in the Bakersfield outlaw scene, and that's where he's stayed. He doesn't intimidate me at all.}
{234}{}{Oh, alright. I don't want to get involved in this.}
{235}{}{You're talking too much, Derrick. I'll have to teach you a lesson.}
{236}{}{You'll regret this. Someday.}
{237}{}{I'll give you a choice - die, or work for De Santi. So, I'm waiting for your answer. One...}
{238}{}{Hey, hey, you're not really going to do the dirty work for some washed-up thug, are you?}
{239}{}{No, I'm not. I was just kidding. Bye, Derrick.}
{240}{}{I don't care, as long as he pays. And I'm wasting my time talking with you. Let's finish this.}
{241}{}{Two...}
{242}{}{Whoa, whoa, whoa, De Santi really ordered this? You're gonna kill me for him? Seriously? Damn it!}
{243}{}{Three!}
{244}{}{Okay! Okay! I'll work for him. Just don't touch my fragile delicate body!}
{245}{}{Too late, Derrick. You've annoyed me. I'll have to punish you.}
{246}{}{Great. I'm glad we came to this understanding. De Santi's your boss now.}

{250}{}{You said you "can give me a lift."}
{251}{}{Well, I haven't had a car for a long time. But I know the fastest and safest routes to anyplace in Dayglow. Where do you wanna go?}
{252}{}{[San Ysidro for }
{253}{}{[Bonita Dam for }
{254}{}{ hubbucks]}
{255}{}{I think I'll just walk.}
{256}{}{Short on caps, huh? Too bad.}
{257}{}{Yah, I guess I'll have to find my own way.}
{258}{}{Wait, there's something else I wanted to ask you.}
{259}{}{[Chula Vista for }

