{100}{}{You see Kurt.}
{101}{}{You see an ordinary ghoul.}
{102}{}{I don't have any caps! NONE! NOT A SINGLE ONE!}
{103}{}{OKAY! OKAY! Here's the caps. Just don't hit me anymore!}
{104}{}{OKAY! OKAY! Here's all my caps. I don't have any more!}
{105}{}{Kurt surrenders.}
{106}{}{Hey, what do you want from me?}
{107}{}{What a mess!}

{200}{}{I'm feeling great today! Haven't relaxed like this in a long time... Uhh, what do you want?}
{201}{}{Who are you?}
{202}{}{They call me Kurt. So what?}
{203}{}{I'm looking for you. I'm here for Mr. De Santi's debts.}
{204}{}{Mr. De Santi is really pissed, huh? Well, let him be mad at himself! I'm not paying for lousy service in a dump of a room. And anyway - one ghoul charging another ghoul? What a disgrace! Who does he think he is? Aren't we all supposed to be building a little ghoul paradise here? Isn't that right?}
{205}{}{Don't give me that. Fork over the caps!}
{206}{}{Mr. De Santi won't let it go.}
{207}{}{I'm not paying! If he wants money, he can get it from you!}
{208}{}{Okay, then I'll take the caps by force. Empty your pockets!}
{209}{}{Fine, I guess I'll have to pay instead of you.}
