{100}{}{You see Flowers.}
{101}{}{You see a massive super mutant.}
{102}{}{Want food!}
{103}{}{Welcome to... uh, forgot the name.}
{104}{}{Right. Ghouls and mutants should get along.}
{105}{}{Yum yum... Not enough!}
{106}{}{Now I'm full!}

{200}{}{You! Don't be afraid of me... Come closer... I won't eat you... Argh! Gotcha, silly little mouse! Oh, escaped...}
{201}{}{Hands off, big guy.}
{202}{}{I want food! Hey, do you have food? Hm-m, you look not bad to eat... But no! I can't eat you! Ghouls won't accept me then.}
{203}{}{So you're Flowers? Mr. De Santi is offering you a job. Take it, and you'll have plenty of food.}
{204}{}{Want food! Food first - then talk!}
{205}{}{Okay.}
{206}{}{Yum yum yum... Not enough!}
{207}{}{Want more? Then go work for De Santi.}
{208}{}{Go to De Santi. De Santi must be a good ghoul. I go now!}
{209}{}{I think you'll find your way. See you in Little Italy.}
