{102}{}{This emitter is de-energized.}
{103}{}{This emitter is now useless.}
{104}{}{This emitter is severely damaged.}
{105}{}{You managed to fix the malfunction. The emitter is ready for use again.}
{106}{}{The emitter is damaged!}
{107}{}{A powerful pulse travels through the ground and spreads out, damaging all electronics in its path.}
{108}{}{The emitter is damaged.}
{109}{}{The emitter is already charged.}
{110}{}{You have charged the emitter's battery.}
{111}{}{This emitter burned out under its own voltage after the last use.}
