{100}{}{This is the substation computer.}
{101}{}{This is the substation control computer.}
{102}{}{The computer won't turn on.}
{103}{}{There might be no power coming to it.}

{200}{}{System operational. Awaiting command input.}
{201}{}{Exit terminal.}
{202}{}{Check status of power station.}
{203}{}{Power station is unresponsive.}
{204}{}{Check status of substation.}
{205}{}{Substation is unresponsive.}
{206}{}{Return to main menu.}
{207}{}{Activate outdoor lighting at station.}
{208}{}{Outdoor lighting activated.}
{209}{}{Activate indoor lighting at station.}
{210}{}{Indoor lighting activated.}
{211}{}{Deactivate general alarm.}
{212}{}{General alarm deactivated.}
{213}{}{Disable combat readiness mode.}
{214}{}{Warning: Combat readiness mode disabled. Security robots set to passive mode.}
{215}{}{Deploy repair robots to restore monorail network.}
{216}{}{Power network restored.}

