{100}{}{This is the designated assembly point for the departure to Sonora.}
{101}{}{From here, you can return to the wastelands of Sonora.}

{110}{}{The assembly point is here.}
{111}{}{[Wait for the guide and return to the Sonoran wasteland.]}
{112}{}{[Return to the Sonoran wasteland alone.]}
{113}{}{[Stay in Dayglow. Sonora can wait.]}
{114}{}{Are you sure? You won't be able to come back.}
{115}{}{Yes, I want to return.}
{116}{}{No, I'm staying in Dayglow.}
{117}{}{You can carry no more than 100 pounds of cargo.}
{118}{}{[Go to Dayglow alone.]}
{119}{}{[Stay in the Sonoran wasteland.]}
