{100}{}{These doors cannot be locked.}
{101}{}{The monorail line is unpowered. It won't go anywhere.}
{102}{}{The monorail isn't moving for some reason. Something must be broken.}
{103}{}{After almost a hundred years, the monorail is running again!}
{104}{}{The monorail is operational.}

{110}{}{"Welcome to the San Diego Metropolitan Rapid Transit network. Please take a seat and wait for departure."}
{111}{}{[Leave the monorail]}
{112}{}{[Get off at San Ysidro Station]}
{113}{}{[Get off at Chula Vista Center Station]}
{114}{}{[Get off at Broadway Station]}
{115}{}{[Get off at Old Town Station]}
