{110}{}{This radio station is still operational.}
{111}{}{This radio station has recently stopped working.}
{112}{}{This equipment doesn't need repairs. But without an antenna, it's useless. Just leave it be for now.}
{113}{}{You extracted the amplifier and other parts needed in San Ysidro.}
{114}{}{The equipment of this radio station is in working condition. But for some reason, the signal isn't transmitting.}
{115}{}{Useless. This radio station has transmission issues.}
