{200}{}{The station is ready for operation. Load the working materials and select a processing program.}
{201}{}{Shut down the station.}
{202}{}{Back.}
{203}{}{This weapon should be put away.}

{210}{}{Required materials: }
{211}{}{, }
{212}{}{.}
{213}{}{Load materials and start the program.}
{214}{}{The program has completed. Take the item from the tray.}
{215}{}{Shut down the station.}
{216}{}{Return to the general list.}
{217}{}{Cancel and return to the general list.}
{218}{}{Not enough materials.}
{219}{}{Return to the last section.}
{220}{}{Received: }
{221}{}{, }
{222}{}{ pcs.}
{223}{}{Repair Section.}
{224}{}{Chemistry Section.}
{225}{}{Ammunition Section.}
{226}{}{}

{250}{}{Homemade bottle caps.}
{251}{}{Homemade anti-radiation drug.}
{252}{}{Homemade stimpak.}
{253}{}{Homemade antidote.}
{254}{}{Flamethrower fuel.}
{255}{}{Molotov cocktail.}
{256}{}{Pulse grenade.}

{260}{}{Recycle fireworks into flares.}
{261}{}{Upgrade regular flares to modified flares (2 for 1).}
{262}{}{Upgrade regular flares to reinforced flares (3 for 1).}
{263}{}{Upgrade modified flares to reinforced flares (2 for 1).}
{264}{}{Convert shotgun shell to bullet.}
{265}{}{Convert bullet to shotgun shell.}

{270}{}{Clean the dirt off the patrol badge.}
{271}{}{Replace the crystal in the laser pistol.}
{272}{}{Repair the monorail control module.}

