{110}{}{The vending machine only dispenses goods for money.}
{111}{}{This vending machine has already been unlocked.}
{112}{}{}
{113}{}{The lock is too complicated.}
{114}{}{Lockpicks are set. It will now be easier for you to pick this lock.}
{115}{}{The necessary number of lockpicks is already in the lock.}
{116}{}{The electronic decoder is not suitable for picking mechanical locks.}
{117}{}{You opened the container with goods. Time to see what's left inside.}
{118}{}{Now that the machine is open, this is pointless.}
{119}{}{You acquired: }
{120}{}{The vending machine is out of goods.}
{121}{}{ pcs.}
{122}{}{You are unable to bypass the vending machine's security mechanism.}
