{100}{}{You see an immigrant.}
{101}{}{You see a dirty, emaciated person.}

{110}{}{Por favor no nos ataquen!}
{111}{}{No queremos problemas!}
{112}{}{Estamos buscando un nuevo hogar.}
{113}{}{Ya llegamos?}
{114}{}{Quiero dormir.}
{115}{}{Eres un aventurero, no?}
{116}{}{Ya hemos tenido suficiente de estos tiranos y guerrilleros.}
{117}{}{Hay bandidos por todas partes.}
{118}{}{Dejanos en paz!}
{119}{}{No tenemos nada de valor.}

{210}{}{«You're not going to attack us, right?»}
{211}{}{«We just want to live in peace.»}
{212}{}{«We're looking for a new home, a fresh start.»}
{213}{}{«Are we there yet?»}
{214}{}{«I just want to sleep.»}
{215}{}{«You're on a quest, right?»}
{216}{}{«We've had enough of these gangs and warlords.»}
{217}{}{«The damn raiders are everywhere.»}
{218}{}{«Leave us be!»}
{219}{}{«We have nothing to steal.»}


{310}{}{You're not going to attack us, right?}
{311}{}{We just want to live in peace.}
{312}{}{We're looking for a new home, a fresh start.}
{313}{}{Are we there yet?}
{314}{}{I just want to sleep.}
{315}{}{You're on a quest, right?}
{316}{}{We've had enough of these gangs and warlords.}
{317}{}{The damn raiders are everywhere.}
{318}{}{Leave us be!}
{319}{}{We have nothing to steal.}
