{100}{}{You see a traveler.}
{101}{}{You see an overgrown man in a dirty, shabby jacket with a sawn-off shotgun on his belt. He looks warily in your direction.}

{200}{}{Don't come too close. My dog's quite protective. Where are you from?}
{201}{}{I'm from a village in Northern Arizona. And you?}
{202}{}{I'm from Southern California. Just traveling.}
{203}{}{Do you mind if I ask you a few questions?}
{204}{}{I see. Well, it's probably best if we go our seperate ways. Farewell, traveller.}

{210}{}{Got something on your mind? Alright, go ahead.}  
{211}{}{I guess it's time for me to go.}
{212}{}{Watch yourself out here. I've run into wild ghouls and big ol' rats more times than I'd like. Stay sharp, and good luck.}  
{213}{}{Bye.}

{220}{}{Where are you headed?}
{221}{}{Nowhere special. Just wandering, hoping to find a place untouched by war or human greed. And if there's none left... guess I'll have to make one myself.}  
{222}{}{What's the news from California?}
{223}{}{Things have been rough lately. The super mutant army's gone, the ghouls from Necropolis are drifting south, and new trade wars are kicking off in the Hub. Angel's Boneyard's getting too crowded, so folks are packing up, looking for someplace new to call home.}  
{224}{}{Why do you have a dog?}
{225}{}{It just started following me one day on the road. At first, I figured I'd cook it over the fire, but turns out having a dog's pretty useful when you're out traveling.}  
{226}{}{Interested in trading?}
{227}{}{Okay. Let's see what you have.}
{228}{}{Do you know of any nearby settlements?}
{229}{}{I heard the east is nothing but endless wasteland. Honestly, I'm surprised I ran into you at all. Though, I also heard the Ranger lands stretch up northeast. Folks even talk about them back in California.}  
{230}{}{Anything else?}
{231}{}{I've been warned about the ruins of Inferno too. Folks say it's a deadly place where an ordinary person doesn't stand a chance. If you're thinking of heading that way, you better think twice.}  
