{110}{}{Oh no, I've been dodging humans for 90 years. Your arrival ends my mission. I have no purpose left.}
{111}{}{I am Shybot. My directive is to "avoid humans." Successfully evading for 90 years.}

{120}{}{I am Shybot. My prime directive is to avoid all humans.}
{121}{}{Ninety years of successful evasion completed.}
{122}{}{Your presence signifies the end of my mission. Unacceptable.}
{123}{}{No one can know my mission has failed.}
{124}{}{I must erase all traces of you from my memory banks.}
{125}{}{I've successfully avoided humans for 90 years. But you disrupt my task.}
{126}{}{You are an obstacle to my primary directive.}
{127}{}{There's no point in hiding anymore.}
{128}{}{I'm weary of fleeing from humans.}
{129}{}{I want to approach you, but my protocols forbid it.}
