{110}{}{The machine dispenses drinks only for money. Unless, of course, you intend to pick its lock.}
{111}{}{This machine's lock has already been picked.}
{112}{}{}
{113}{}{The lock is too complicated.}
{114}{}{The lockpicks are installed. Now it will be easier for you to pick this lock.}
{115}{}{The lock already has the required number of lockpicks.}
{116}{}{The electronic decoder isn't suitable for picking mechanical locks.}
{117}{}{You've opened a container of drinks. Time to see what's left inside.}
{118}{}{Now that the machine is open, this makes no sense.}
{119}{}{You received a bottle of warm, stale Nuka Cola.}
{120}{}{The machine is out of Nuka Cola.}
{121}{}{}
{122}{}{You are unable to bypass the machine's security mechanism.}
