#include "..\headers\define.h"
#define NAME                            SCRIPT_ASFlag

procedure start;
procedure map_enter_p_proc;
procedure damage_p_proc;



procedure start begin
end

procedure map_enter_p_proc begin
   if (is_loading_game == false) then begin
       set_obj_visibility(self_obj, 1);
       if (getQuest(GVAR_PUERTO_QST_SANFELIPE_PIP) >= qEnd) then begin
       if (gvar_bit(GVAR_SANFELIPE_BITS,bit_4) != 0) then begin
       set_obj_visibility(self_obj, 0);
       end
       end
       if (getQuest(GVAR_SANFELIPE_QST_RUN) >= qEnd) then begin
       set_obj_visibility(self_obj, 1);
       end
   end
end

procedure damage_p_proc begin
   destroy_object(self_obj);
end
