#include "..\headers\define.h"
#include "..\headers\REPAIR.h"
#define NAME                    SCRIPT_ASNasos
#define SKILL_LIMIT                     60

procedure start;
procedure map_enter_p_proc;
procedure use_p_proc;
procedure use_skill_on_p_proc;
procedure use_obj_on_p_proc;
procedure repair_proc;



procedure start begin
end

procedure map_enter_p_proc begin
end

procedure use_p_proc begin
   script_overrides;
   RepairProcUsing(110,111)
end

procedure use_skill_on_p_proc begin
   RepairVarCheck
   RepairSkillRepair
end

procedure use_obj_on_p_proc begin
   stopUseCarGaz
   RepairUsedJunk(PID_TOOL_PARTS_MECHANICAL,20)
end

procedure repair_proc begin
   set_gvar_bit_on(GVAR_SANFELIPE_BITS, bit_5);
   gfade_out(ONE_GAME_SECOND);
   game_time_advance(ONE_GAME_HOUR);
   gfade_in(ONE_GAME_SECOND);
   obj_set_light_level(self_obj, 100, 1);
   RepairProcRepair(112,0,"FIXSTILL")
end
