#
# 
#
# Text labels and messages used by FISSION
#
#

#
# Preferences
#

#
# Message Box
#

{100}{}{Quitar la pantalla completa}
{101}{}{desactiva las preferencias}
{102}{}{adicionales. ¿Continuar?}
{103}{}{Reinicia para aplicar los}
{104}{}{cambios gráficos.}
{105}{}{Cambiar área de juego a original}

#
# Extended Titles
#

{124}{}{PANTALLA}
{125}{}{ESTIRAR PANTALLA}
{126}{}{CALIDAD}
{127}{}{ÁREA ACTIVA}
{128}{}{} #Leave blank
{129}{}{} #Leave blank

#
# Extended Label text
#

{225}{}{No}
{226}{}{Pantalla Completa}        
{227}{}{No}        
{228}{}{Pantalla Ancha} 
{229}{}{No}           
{230}{}{Estirar} 
{231}{}{No}
{232}{}{Relación Aspecto}
{233}{}{No}         
{234}{}{Alta Calidad}        
{235}{}{No}
{236}{}{Pixeles Cuadrados}
{237}{}{Original}      
{238}{}{Por Defecto}        
{239}{}{Grande}
{240}{}{Enorme}

#
# Fission About
#

{300}{}{F.I.S.S.I.O.N.}
{301}{}{Flexible e Isométrico Sistema de Simulación}
{302}{}{Interactiva de Origen Nuclear}

