################################################## #####
#
# Map level names -- AUTOMAP Names
#
################################################## #####

#---------------------------------------
#00: Desert Encounter 1, desert1.MAP
#---------------------------------------
{200}{}{Desierto}
{201}{}{}
{202}{}{}
#---------------------------------------
#01: Desert Encounter 2, desert2.MAP
#---------------------------------------
{203}{}{Yermo}
{204}{}{}
{205}{}{}
#---------------------------------------
#02: Desert Encounter 3, desert3.MAP
#---------------------------------------
{206}{}{Cactus}
{207}{}{}
{208}{}{}
#---------------------------------------
#03: Desert Encounter 4, desert4.MAP
#---------------------------------------
{209}{}{Campamento}
{210}{}{}
{211}{}{}
#---------------------------------------
#04: Road Encounter 1, ROAD1.MAP
#---------------------------------------
{212}{}{Interestatal}
{213}{}{}
{214}{}{}
#---------------------------------------
#05: Road Encounter 2, ROAD2.MAP
#---------------------------------------
{215}{}{Interestatal}
{216}{}{}
{217}{}{}
#---------------------------------------
#06: Road Encounter 3, ROAD3.MAP
#---------------------------------------
{218}{}{Carretera}
{219}{}{}
{220}{}{}
#---------------------------------------
#07: Road Encounter 4, ROAD4.MAP
#---------------------------------------
{221}{}{Ruta}
{222}{}{}
{223}{}{}
#---------------------------------------
#08: City Encounter 1, city1.MAP
#---------------------------------------
{224}{}{Ruinas}
{225}{}{}
{226}{}{}
#---------------------------------------
#09: City Encounter 2, city2.MAP
#---------------------------------------
{227}{}{Tiendas}
{228}{}{Alcantarilla}
{229}{}{}
#---------------------------------------
#10: City Encounter 3, city3.MAP
#---------------------------------------
{230}{}{Casa}
{231}{}{}
{232}{}{}
#---------------------------------------
#11: City Encounter 4, city4.MAP
#---------------------------------------
{233}{}{Campamento}
{234}{}{}
{235}{}{}
#---------------------------------------
#12: Mountain Encounter 1, MOUNT1.MAP
#---------------------------------------
{236}{}{Acantilado}
{237}{}{}
{238}{}{}
#---------------------------------------
#13: Mountain Encounter 2, MOUNT2.MAP
#---------------------------------------
{239}{}{Acantilado}
{240}{}{}
{241}{}{}
#---------------------------------------
#14: Mountain Encounter 3, MOUNT3.MAP
#---------------------------------------
{242}{}{Campamento}
{243}{}{}
{244}{}{}
#---------------------------------------
#15: Mountain Encounter 4, MOUNT4.MAP
#---------------------------------------
{245}{}{Acantilado}
{246}{}{Caverna}
{247}{}{}
#---------------------------------------
#16: Mountain Encounter 5, MOUNT5.MAP
#---------------------------------------
{248}{}{Acantilado}
{249}{}{Caverna}
{250}{}{}
#---------------------------------------
#17: Mountain Encounter 6, MOUNT6.MAP
#---------------------------------------
{251}{}{Acantilado}
{252}{}{Caverna}
{253}{}{}
#---------------------------------------
#18: Coast Encounter 1, COAST1.MAP
#---------------------------------------
{254}{}{Costa}
{255}{}{}
{256}{}{}
#---------------------------------------
#19: Coast Encounter 2, COAST2.MAP
#---------------------------------------
{257}{}{Costa}
{258}{}{}
{259}{}{}
#---------------------------------------
#20: Coast Encounter 3, COAST3.MAP
#---------------------------------------
{260}{}{Cabaña}
{261}{}{}
{262}{}{}
#---------------------------------------
#21: Villa1, artemple.MAP
#---------------------------------------
{263}{}{Residencial}
{264}{}{}
{265}{}{}
#---------------------------------------
#22: Villa2, VLPlaza.MAP
#---------------------------------------
{266}{}{Plaza}
{267}{}{Pozo}
{268}{}{Ayuntamiento}
#---------------------------------------
#23: Villa3, VLCave.MAP
#---------------------------------------
{269}{}{Sótano}
{270}{}{Sótano}
{271}{}{Sótano}
#---------------------------------------
#24: Villa4, VLGard.MAP
#---------------------------------------
{272}{}{Plantación}
{273}{}{}
{274}{}{}
#---------------------------------------
#25: FlagstaffCity, PoolCity.MAP
#---------------------------------------
{275}{}{Residencial}
{276}{}{Sótano}
{277}{}{}
#---------------------------------------
#26: FlagstaffSlave, PoolSlav.MAP
#---------------------------------------
{278}{}{Guarnición}
{279}{}{}
{280}{}{}
#---------------------------------------
#27: FlagstaffMine, PoolMine.MAP
#---------------------------------------
{281}{}{Administración}
{282}{}{}
{283}{}{}
#---------------------------------------
#28: FlagstaffGard, PoolGard.MAP
#---------------------------------------
{284}{}{Ruinas}
{285}{}{Escondite}
{286}{}{}
#---------------------------------------
#29: GarageSign, GCSign.MAP
#---------------------------------------
{287}{}{Entrada}
{288}{}{}
{289}{}{}
#---------------------------------------
#30: GarageHome, GCHome.MAP
#---------------------------------------
{290}{}{Cabañas}
{291}{}{}
{292}{}{}
#---------------------------------------
#31: GarageDsrt, GCDstr.MAP
#---------------------------------------
{293}{}{Fábrica}
{294}{}{Fábrica}
{295}{}{Fábrica}
#---------------------------------------
#32: SanBrahminSign, SBSign.MAP
#---------------------------------------
{296}{}{Campamento}
{297}{}{Alcantarilla}
{298}{}{}
#---------------------------------------
#33: SanBrahminCity, SBChurch.MAP
#---------------------------------------
{299}{}{Pueblo}
{300}{}{Sótano}
{301}{}{Santuario}
#---------------------------------------
#34: SanBrahminTabl, SBTabl.MAP
#---------------------------------------
{302}{}{Corrales}
{303}{}{}
{304}{}{}
#---------------------------------------
#35: TwoSunCity, TSCity.MAP
#---------------------------------------
{305}{}{Asentamiento}
{306}{}{}
{307}{}{}
#---------------------------------------
#36: TwoSunAngar, TSGarage.MAP
#---------------------------------------
{308}{}{Taller}
{309}{}{}
{310}{}{}
#---------------------------------------
#37: TwoSunDstr, TSDstr.MAP
#---------------------------------------
{311}{}{Ruinas}
{312}{}{Escondite}
{313}{}{Escondite}
#---------------------------------------
#38: TwoSunZAX, TSGrave.MAP
#---------------------------------------
{314}{}{Nivel 1}
{315}{}{Nivel 4}
{316}{}{Nivel 5}
#---------------------------------------
#39: Puerto1, PSSign.MAP
#---------------------------------------
{317}{}{Ruinas}
{318}{}{Segundo Piso}
{319}{}{Tercer Piso}
#---------------------------------------
#40: Puerto2, PSDocs.MAP
#---------------------------------------
{320}{}{Puerto}
{321}{}{Puente}
{322}{}{Cubierta}
#---------------------------------------
#41: Puerto3, PSBasa.MAP
#---------------------------------------
{323}{}{Cubierta}
{324}{}{Nivel bajo}
{325}{}{Interior}
#---------------------------------------
#42: RangersRoad, RRoad.MAP
#---------------------------------------
{326}{}{Carretera}
{327}{}{Escondite}
{328}{}{}
#---------------------------------------
#43: RangersBasa, RBasa.MAP
#---------------------------------------
{329}{}{Entrada}
{330}{}{Presa baja}
{331}{}{Presa alta}
#---------------------------------------
#44: RangersRadio, RRadio.MAP
#---------------------------------------
{332}{}{Estación}
{333}{}{Transmisor}
{334}{}{}
#---------------------------------------
#45: RangersDumba, RDumba.MAP
#---------------------------------------
{335}{}{Central}
{336}{}{Oficina}
{337}{}{Compuerta}
#---------------------------------------
#46: PhoenixSign, PXSign.MAP
#---------------------------------------
{338}{}{Entrada}
{339}{}{Alcantarilla}
{340}{}{}
#---------------------------------------
#47: PhoenixCenter, PXCenter.MAP
#---------------------------------------
{341}{}{Tianguis}
{342}{}{Sótano}
{343}{}{Segundo piso}
#---------------------------------------
#48: PhoenixBndcs, PXBndcs.MAP
#---------------------------------------
{344}{}{Barrios bajos}
{345}{}{Cuadrilátero}
{346}{}{Cardenales}
#---------------------------------------
#49: PhoenixCity, PXCity.MAP
#---------------------------------------
{347}{}{Catedral}
{348}{}{Cráter}
{349}{}{}
#---------------------------------------
#50: PhoenixVlt, PXVault.MAP
#---------------------------------------
{350}{}{Pasaje}
{351}{}{Laboratorio}
{352}{}{Centro de Control}
#----------------------------------------
# 51: PhoenixAnal, PXAnal.MAP
#----------------------------------------
{353}{}{Alcantarilla}
{354}{}{Alcantarilla}
{355}{}{Alcantarilla}
#----------------------------------------
# 52: PhoenixDstr, PXDstr.MAP
#----------------------------------------
{356}{}{Union Station}
{357}{}{Alcantarilla}
{358}{}{Escondite}
#---------------------------------------
#53: Car Desert out-of-gas, CarDesrt.MAP
#---------------------------------------
{359}{}{Desierto}
{360}{}{}
{361}{}{}
#---------------------------------------
#54: PhoenixElctr, PXElectr.MAP
#---------------------------------------
{362}{}{Entrada}
{363}{}{Sótano}
{364}{}{Habitaciones}
#---------------------------------------
#55: Vault27a, VaultA.MAP
#---------------------------------------
{365}{}{Estacionamiento}
{366}{}{Bajada}
{367}{}{}
#---------------------------------------
#56: Vault27b, VaultB.MAP
#---------------------------------------
{368}{}{Habitaciones}
{369}{}{Centro de Control}
{370}{}{Reactor}
#---------------------------------------
#57: CGrandeWater, CGWater.MAP
#---------------------------------------
{371}{}{Bomba de agua}
{372}{}{}
{373}{}{}
#---------------------------------------
#58: CGrandeHomes, CGGrande.MAP
#---------------------------------------
{374}{}{Mansión}
{375}{}{Sótano}
{376}{}{Mansión}
#---------------------------------------
#59: CGrandeGrave,CGGrave.MAP
#---------------------------------------
{377}{}{Cementerio}
{378}{}{Sótano}
{379}{}{}
#---------------------------------------
#60: InfernoRoad, INFERNOa.MAP
#---------------------------------------
{380}{}{Carretera}
{381}{}{Alcantarilla}
{382}{}{}
#---------------------------------------
#61: InfernoCity, InfCity.MAP
#---------------------------------------
{383}{}{Ruinas}
{384}{}{Alcantarilla}
{385}{}{}
#---------------------------------------
#62: InfernoShop, InfShop.Map
#---------------------------------------
{386}{}{Supermercado}
{387}{}{Alcantarilla}
{388}{}{}
#---------------------------------------
#63: InfernoPolic, InfPolic.MAP
#---------------------------------------
{389}{}{Policía}
{390}{}{Alcantarilla}
{391}{}{}
#---------------------------------------
#64: CnuevaCity, CNCity.MAP
#---------------------------------------
{392}{}{Asentamiento}
{393}{}{Sótano}
{394}{}{Segundo piso}
#---------------------------------------
#65: CNuevaGard, CNGard.MAP
#---------------------------------------
{395}{}{Agave}
{396}{}{}
{397}{}{}
#---------------------------------------
#66: CNuevaLab, CNLab.MAP
#---------------------------------------
{398}{}{Administración}
{399}{}{Complejo A}
{400}{}{Complejo B}
#----------------------------------------
# 67: RaidersMap, RAIDERS.MAP
#----------------------------------------
{401}{}{Bandidos}
{402}{}{Caseta de líder}
{403}{}{Combustible}
#---------------------------------------
#68: JackalsMap, JACKALS.MAP
#---------------------------------------
{404}{}{Casa}
{405}{}{Guarida}
{406}{}{Almacén}
#---------------------------------------
#69: PuertoDestroy, PSDstr.MAP
#---------------------------------------
{407}{}{Área}
{408}{}{}
{409}{}{}
#---------------------------------------
#70: FlagstaffCave, FlagCave.MAP
#---------------------------------------
{410}{}{Mina principal}
{411}{}{Mina agotada}
{412}{}{Mina}
#---------------------------------------
#71: MotelMap, MOTEL.MAP
#---------------------------------------
{413}{}{Motel}
{414}{}{Sótano}
{415}{}{}
#---------------------------------------
#72: SanFelipeLight, FelipeA.MAP
#---------------------------------------
{416}{}{Asentamiento}
{417}{}{Fuente de Agua}
{418}{}{Faro}
#---------------------------------------
#73: BSCamp1, BSCampA.MAP
#---------------------------------------
{419}{}{Campamento}
{420}{}{Campamento}
{421}{}{Campamento}
#---------------------------------------
#74: BSCamp2, BSCampB.MAP
#---------------------------------------
{422}{}{Campamento}
{423}{}{Campamento}
{424}{}{Campamento}
#---------------------------------------
#75: BSCamp3, BSCampC.MAP
#---------------------------------------
{425}{}{Campamento}
{426}{}{Campamento}
{427}{}{Campamento}
#---------------------------------------
#76: PhoenixChrch, PXChrch.MAP
#---------------------------------------
{428}{}{Primer Piso}
{429}{}{Segundo Piso}
{430}{}{Tercer Piso}
#---------------------------------------
#77: TwoSunGrave,TSGrave.MAP
#---------------------------------------
{431}{}{Zona Prohibida}
{432}{}{Cementerio}
{433}{}{Reciclaje}
#---------------------------------------
#78: TwoSunInn, TSInn.MAP
#---------------------------------------
{434}{}{Sitio del Ataque}
{435}{}{}
{436}{}{}
#---------------------------------------
#79: VillaRuins, VLRUINS.MAP
#---------------------------------------
{437}{}{Ruinas Antiguas}
{438}{}{Escondite}
{439}{}{}
#---------------------------------------
#80: RangersParom, RParom.MAP
#---------------------------------------
{440}{}{Litoral}
{441}{}{}
{442}{}{}
#---------------------------------------
#81: RangersRetrns, RRetrns.MAP
#---------------------------------------
{443}{}{Cabaña en el desierto}
{444}{}{}
{445}{}{}
#---------------------------------------
#82. RangersQuartz, RQuartz.MAP
#---------------------------------------
{446}{}{Pueblo}
{447}{}{Sótano}
{448}{}{Gasolinera}
#---------------------------------------
#83. RangersCave, RCave.MAP
#---------------------------------------
{449}{}{Caseta}
{450}{}{Caverna}
{451}{}{}
#---------------------------------------
#84: RangersCity, RCity.MAP
#---------------------------------------
{452}{}{Aldea}
{453}{}{Catacumbas}
{454}{}{Acueducto}
#---------------------------------------
#85. GarageHist, GCHist.MAP
#---------------------------------------
{455}{}{Kingman}
{456}{}{}
{457}{}{}
#---------------------------------------
#86. GarageBram, GCBram.MAP
#---------------------------------------
{458}{}{Campamento}
{459}{}{}
{460}{}{}
#---------------------------------------
#87. FlagstaffFarm, FlagFarm.MAP
#---------------------------------------
{461}{}{Molinos}
{462}{}{}
{463}{}{}
#---------------------------------------
#88. Hermosillo1, HERMO1.MAP
#---------------------------------------
{464}{}{Rancho Domínguez}
{465}{}{}
{466}{}{}
#---------------------------------------
#89. Hermosillo2, HERMO2.MAP
#---------------------------------------
{467}{}{Guarnición}
{468}{}{Alcantarilla}
{469}{}{Techos}
#---------------------------------------
#90. Hermosillo3, HERMO3.MAP
#---------------------------------------
{470}{}{Cerro}
{471}{}{Alcantarilla}
{472}{}{Cuartel}
#---------------------------------------
#91. CGrandeSchool, CGSchool.MAP
#---------------------------------------
{473}{}{Escuela}
{474}{}{Escondite}
{475}{}{Escuela}
#---------------------------------------
#92. CGrandeBar, CGBar.MAP
#---------------------------------------
{476}{}{Bar abandonado}
{477}{}{}
{478}{}{}
#---------------------------------------
#93. CGrandeStan, CGStan.MAP
#---------------------------------------
{479}{}{Estación de tren}
{480}{}{}
{481}{}{}
#---------------------------------------
#94. RangersWater, RMohave.MAP
#---------------------------------------
{482}{}{Mojave}
{483}{}{}
{484}{}{}
#---------------------------------------
#95. InfernoChurch, InfChrch.MAP
#---------------------------------------
{485}{}{Iglesia Misteriosa}
{486}{}{Laboratorio}
{487}{}{Iglesia Interior}
#---------------------------------------
#96. Special Gold Encounter, rndGold.MAP
#---------------------------------------
{488}{}{Carretera}
{489}{}{Escondite en la caverna}
{490}{}{}
#---------------------------------------
#97. Special Bibl Encounter, rndBibl.MAP
#---------------------------------------
{491}{}{Algún lado}
{492}{}{}
{493}{}{}
#---------------------------------------
#98. Special Cafe Encounter, rndCafe.MAP
#---------------------------------------
{494}{}{Cafetería}
{495}{}{Escondite}
{496}{}{}
#---------------------------------------
#99. Special Bomber Encounter, rndBomber.MAP
#---------------------------------------
{497}{}{Algún lado}
{498}{}{}
{499}{}{}
#---------------------------------------
# 100. Special Petro Encounter, rndPetro.MAP
#---------------------------------------
{500}{}{Algún lado}
{501}{}{}
{502}{}{}
#---------------------------------------
#101. Special Cry Encounter, rndCry.MAP
#---------------------------------------
{503}{}{Algún lado}
{504}{}{}
{505}{}{}
#---------------------------------------
#102. Special DriveIn Encounter, rndDrive.MAP
#---------------------------------------
{506}{}{Algún lado}
{507}{}{}
{508}{}{}
#---------------------------------------
#103. Special Padre Encounter, rndPadre.MAP
#---------------------------------------
{509}{}{Algún lado}
{510}{}{}
{511}{}{}
#---------------------------------------
#104. Special Baron Encounter, rndBaron.MAP
#---------------------------------------
{512}{}{Punto de Reunion para ir a Dayglow}
{513}{}{}
{514}{}{}
#---------------------------------------
#105. Special Snow Encounter, rndSnow.MAP
#---------------------------------------
{515}{}{Algún lado}
{516}{}{}
{517}{}{}
#---------------------------------------
#106. Special Vault Encounter, rndVault.MAP
#---------------------------------------
{518}{}{Ciudad Antigua}
{519}{}{Refugio}
{520}{}{Ciudad Antigua}
#---------------------------------------
#107. Special Army Encounter, rndArmy.MAP
#---------------------------------------
{521}{}{Fortaleza}
{522}{}{Tecnología}
{523}{}{Habitaciones}
#---------------------------------------
#108. Special LegendCity Encounter, rndRail.MAP
#---------------------------------------
{524}{}{Algún lado}
{525}{}{Algún lado}
{526}{}{Algún lado}
#---------------------------------------
# 109. VillaCrypt, VLCrypt.MAP
#---------------------------------------
{527}{}{Pasaje}
{528}{}{Galerías}
{529}{}{Cripta}
#---------------------------------------
#110. PhoenixCola, PXCola.MAP
#---------------------------------------
{530}{}{Almacén}
{531}{}{}
{532}{}{}
#---------------------------------------
# 111. InfernoMonument, InfMnmt.MAP
#---------------------------------------
{533}{}{Interestatal}
{534}{}{Túnel}
{535}{}{}
#---------------------------------------
# 112. CNUevaCarier, CNCarier.MAP
#---------------------------------------
{536}{}{Planta de concreto}
{537}{}{Nido}
{538}{}{}
#---------------------------------------
# 113. CNUevaGidro, CNGidr.MAP
#---------------------------------------
{539}{}{Domo}
{540}{}{Invernaderos, Este}
{541}{}{Invernaderos, Oeste}
#---------------------------------------
#114. SanBrahminCave, SBCave.MAP
#---------------------------------------
{542}{}{Ciudad Enterrada}
{543}{}{Catacumbas}
{544}{}{Alcantarilla}
#---------------------------------------
#115. SanFelipeCoast, FelipeB.MAP
#---------------------------------------
{545}{}{Cabaña en la costa}
{546}{}{Barco}
{547}{}{Barco}
#---------------------------------------
#116. SanFelipeCave, FelipeC.MAP
#---------------------------------------
{548}{}{Caverna}
{549}{}{Caverna}
{550}{}{Caverna}
#---------------------------------------
#117. GarageTrailer, GCTrlr.MAP
#---------------------------------------
{551}{}{Remolque}
{552}{}{Chapas Falsas}
{553}{}{Remolque}
#---------------------------------------
#118. FlagstaffWinon, FlagCamp.MAP
#---------------------------------------
{554}{}{Campamento}
{555}{}{Campamento}
{556}{}{Campamento}
#---------------------------------------
#119. SanBrahminOasis, SBOasis.MAP
#---------------------------------------
{557}{}{Lago Sullivan}
{558}{}{Lago Sullivan}
{559}{}{Lago Sullivan}
#---------------------------------------
#120. SantaAnaPlaza, SAPlaza.MAP
#---------------------------------------
{560}{}{Plaza Zaragoza}
{561}{}{Sótano}
{562}{}{Interior}
#---------------------------------------
#121. SantaAnaMonument, SAMnmnt.MAP
#---------------------------------------
{563}{}{Monumento}
{564}{}{Monumento}
{565}{}{Monumento}
#---------------------------------------
#122. SantaAnaGrave, SAGrave.MAP
#---------------------------------------
{566}{}{Cementerio}
{567}{}{Cementerio}
{568}{}{Cementerio}
#---------------------------------------
# 123. SanBrahminCaravanA, SBCrvnA.MAP
#---------------------------------------
{569}{}{Yermo}
{570}{}{}
{571}{}{}
#---------------------------------------
# 124. SanBrahminCaravanB, SBCrvnB.MAP
#---------------------------------------
{572}{}{Interestatal}
{573}{}{}
{574}{}{}
#---------------------------------------
#125. SanBrahminCaravanC, SBCrvnC.MAP
#---------------------------------------
{575}{}{Suburbio}
{576}{}{}
{577}{}{}
#---------------------------------------
# 126. OilCity, OilA.MAP
#---------------------------------------
{578}{}{Aldea}
{579}{}{Aldea}
{580}{}{Mar de Cortés}
#---------------------------------------
# 127. OilPlatformB, OilB.MAP
#---------------------------------------
{581}{}{Ascenso}
{582}{}{Plataforma}
{583}{}{Aterrizaje}
#---------------------------------------
# 128. OilPlatformC, OilC.MAP
#---------------------------------------
{584}{}{Residencial}
{585}{}{Recreación}
{586}{}{Administración}
#---------------------------------------
# 129. OilPlatformD, OilD.MAP
#---------------------------------------
{587}{}{Taladro}
{588}{}{Petróleo}
{589}{}{Plataforma}
#---------------------------------------
#130. OilCoast, OilE.MAP
#---------------------------------------
{590}{}{Laguna Negra}
{591}{}{Laguna Negra}
{592}{}{Laguna Negra}
#---------------------------------------
#131. DiegoTijuana, DiegoA.MAP
#---------------------------------------
{593}{}{Frontera}#Tijuana, Border Crossing
{594}{}{Avenida Revolución}#Tijuana, Revolucion Avenue
{595}{}{Plaza de Toros}
#----------------------------------------
# 132. DiegoCampA, DiegoC1.MAP
#----------------------------------------
{596}{}{Campamento}
{597}{}{Túnel}
{598}{}{Parada}
#----------------------------------------
# 133. DiegoCampB, DiegoC2.MAP
#----------------------------------------
{599}{}{Presa Bonita}
{600}{}{Sala Máquinas}
{601}{}{Centro de Mando}
#----------------------------------------
# 134. DiegoCampC, DiegoC3.MAP
#----------------------------------------
{602}{}{Campamento}
{603}{}{Cruce}
{604}{}{Parada}
#----------------------------------------
# 135. DiegoPatrulOffice, DiegoB1.MAP
#----------------------------------------
{605}{}{Oficina }
{606}{}{Ruta 5}
{607}{}{Ruta 805}
#----------------------------------------
# 136. DiegoChulaVista, DiegoB2.MAP
#----------------------------------------
{608}{}{Chula Vista}
{609}{}{Alcantarillado}
{610}{}{Mesa Otay}
#----------------------------------------
# 137. DiegoHospital, DiegoB3.MAP
#----------------------------------------
{611}{}{Hospital}
{612}{}{Cafetería "La Maz"}
{613}{}{Planta electrónica}
#----------------------------------------
# 138. DiegoCityHeart, DiegoHrt.MAP
#----------------------------------------
{614}{}{Centro}
{615}{}{Imprenta}
{616}{}{Edificios}
#----------------------------------------
# 139. DiegoPirs, DiegoPir.MAP
#----------------------------------------
{617}{}{Muelle Marina}
{618}{}{Little Italy}
{619}{}{Parque Balboa}
#----------------------------------------
# 140. DiegoVault, DiegoVlt.MAP
#----------------------------------------
{620}{}{Nivel 1}
{621}{}{Nivel 2}
{622}{}{Nivel 3}
#----------------------------------------
# 141. DiegoCoronado, DiegoCor.MAP
#----------------------------------------
{623}{}{Base naval}
{624}{}{Búnker}
{625}{}{Almacén}
#---------------------------------------
#142. Mountain Encounter 9, MOUNT9.MAP
#---------------------------------------
{626}{}{Acantilado}
{627}{}{}
{628}{}{}
#---------------------------------------
#143. Mountain Encounter 8, MOUNT8.MAP
#---------------------------------------
{629}{}{Bosque}
{630}{}{}
{631}{}{}
#---------------------------------------
#144. Desert Encounter 9, desert9.MAP
#---------------------------------------
{632}{}{Yermo}
{633}{}{}
{634}{}{}
#---------------------------------------
#145. Coast Encounter 4, COAST4.MAP
#---------------------------------------
{635}{}{Playa}
{636}{}{}
{637}{}{}
#---------------------------------------
#146. Road Encounter 5, ROAD5.MAP
#---------------------------------------
{638}{}{Parada}
{639}{}{}
{640}{}{}
#---------------------------------------
#147. Mountain Encounter 7, MOUNT7.MAP
#---------------------------------------
{641}{}{Cabaña}
{642}{}{}
{643}{}{}
#---------------------------------------
#148. City Encounter 9, CITY9.MAP
#---------------------------------------
{644}{}{Ruinas}
{645}{}{}
{646}{}{}
#---------------------------------------
#149. In Game Movie, gammovie.MAP
#---------------------------------------
{647}{}{Caravana}
{648}{}{}
{649}{}{}
#---------------------------------------
#150.mapreserv150
#---------------------------------------
{650}{}{Yermo}
{651}{}{}
{652}{}{}

################################################## #####
#
# Names of locations on the world map and mini-map
# Numbering: 1500+Area. For area number, see CITY.TXT sections like [Area ??]
#
################################################## #####
{1500}{}{La Villa}
{1501}{}{Flagstaff}
{1502}{}{Ciudad Garaje}
{1503}{}{San Brahman}
{1504}{}{Two-Sun}
{1505}{}{Puerto}
{1506}{}{Rangers}
{1507}{}{Fenix}
{1508}{}{El Faro}
{1509}{}{Casa Grande}
{1510}{}{Hermosillo}
{1511}{}{San Felipe}
{1512}{}{Infierno}
{1513}{}{Casa Nueva}
{1514}{}{-}
{1515}{}{Motel}
{1516}{}{Dayglow}
{1517}{}{Base Naval de EE.UU}
{1518}{}{Santa Ana}
{1519}{}{-}
{1520}{}{Chacales}
{1521}{}{Motocicleta sin gasolina}
{1522}{}{La Villa}
{1523}{}{Refugio 27}
{1524}{}{Campamento de la Hermandad}
{1525}{}{Escudos Azules}
{1526}{}{Yermo}
{1527}{}{Montes}
{1528}{}{Ruinas}
{1529}{}{Costa}
{1530}{}{Puerto}
{1531}{}{Oro}
{1532}{}{Henry Bemis}
{1533}{}{Cafeteria}
{1534}{}{Bombardero}
{1535}{}{Camion de Petro-Chico}
{1536}{}{El Grito del Silencio}
{1537}{}{Cine al aire libre}
{1538}{}{El Padre}
{1539}{}{Punto de Reunion}
{1540}{}{Una nevada}
{1541}{}{El Santuario Perdido}
{1542}{}{Fortaleza Movil}
{1543}{}{Legend City}
{1544}{}{-}
{1545}{}{-}
{1546}{}{Quartzsite}
{1547}{}{Encuentro aleatorio}
{1548}{}{Campamento Winon}

