###------- AMMUNITION
{100}{}{Batería nuclear}
{101}{}{Una pequeña y autónoma unidad para almacenar energía.}
{200}{}{Célula de Microfusión}
{201}{}{Una unidad de producción de energía de tamaño medio. Con reactor de fusión autónomo.}
{300}{}{Munición .22}
{301}{}{Munición. Calibre: .22, un calibre pequeño de percusión anular.}
{400}{}{9mm}
{401}{}{Munición. Calibre: 9mm.}
{500}{}{10mm}
{501}{}{Munición. Calibre: 10mm.}
{600}{}{10mm CPN}
{601}{}{Munición. Calibre: 10mm. Cartuchos de Proyectil Nanoestructurado.}
{700}{}{Calibre .44}
{701}{}{Munición. Calibre: .44}
{800}{}{Calibre .50}
{801}{}{Munición. Calibre: .50, se utiliza en algunas pistolas y revólveres.}
{900}{}{5mm}
{901}{}{Munición. Calibre: 5mm}
{1000}{}{Calibre .308}
{1001}{}{Munición Calibre .308, es un cartucho viejo, pero confiable.}
{1100}{}{Cartuchos de escopeta calibre 12}
{1101}{}{Munición de escopeta. Esta munición en particular indica que es: "munición calibre 12, prohibido su uso a menores de 3 años".}
{1200}{}{Cartuchos de escopeta calibre 12, con bala}
{1201}{}{Un cartucho de escopeta con una bala en su interior.}
{1300}{}{40mm de lanzagranadas}
{1301}{}{Munición para un lanzagranadas de mano.}
{1400}{}{Cartucho de bengala}
{1401}{}{Bengala de calibre 4, para una pistola de bengalas.}
{1500}{}{Cartucho de bengala modificado}
{1501}{}{Un cartucho de bengala calibre 4 modificado.}
{1600}{}{Cartucho de bengala reforzado}
{1601}{}{Un cartucho de bengala calibre 4 reforzado.}
{1700}{}{Contenedor Universal}
{1701}{}{Un contenedor para cualquier ocasión. Puedes dejar tus cosas aquí, antes de partir.}
###------- THROWN WEAPONS
{1800}{}{Roca}
{1801}{}{Es una roca. Modelo Granite-Inc., en una versión actualizada. Min FU: 1.}
{1900}{}{Cuchillo arrojadizo}
{1901}{}{Un cuchillo específicamente equilibrado para ser lanzado. Hecho de titanio, y afilado con láser. Min FU: 2.}
{2000}{}{Grenade de fragmentación}
{2001}{}{Una granada de fragmentación genérica. Contiene una pequeña cantidad de alto explosivo, y la propia carcasa forma parte de los fragmentos dañinos. Explota al contacto. Min FU: 3.}
{2100}{}{Granada de plasma}
{2101}{}{Una unidad de plasma sellada magnéticamente, con explosivos detonantes. Crea una ráfaga de plasma supercaliente al contacto. Min FU: 4.}
{2200}{}{Granada IEM}
{2201}{}{Una granada de impulso electromagnético, genera un intenso campo magnético al detonar. No afecta a las criaturas biológicas. Se funde al contacto. Min FU: 3.}
{2300}{}{Granada nuclear}
{2301}{}{Una granada improvisada hecha a partir de un poderoso proyectil nuclear. Al explotar, crea una ráfaga de energía tan poderosa que es capaz de demoler una casa. Min FU: 5}
###------- ARMOR
{2400}{}{Mono de refugio}
{2401}{}{Un mono ajustado de un refugio. Podrías venderlo en algún mercado. Efectos: +2 a la Reacción.}
{2500}{}{Chaqueta de cuero}
{2501}{}{Una chaqueta de cuero negra y pesada.}
{2600}{}{Chaqueta de cuero de combate}
{2601}{}{Esta chaqueta de cuero reforzada es inusual, ya que tiene dos mangas. Sin duda harás un pase de moda cuando y donde quieras, y arrasarás.}
{2700}{}{Armadura de cuero}
{2701}{}{Tu atuendo básico de cuero. Hecho artesanalmente con piel curtida de brahmán. Sólo los maestros curtidores de San Brahmán conocen los secretos de su fabricación.}
{2800}{}{Túnica}
{2801}{}{Túnica de los Seguidores del Fuego. Fabricadas usando tecnología secreta y materiales especiales. Otorga protección contra la radiación.}
{2900}{}{Túnica con armadura corporal}
{2901}{}{Túnica de los Seguidores del Fuego. Fabricadas usando tecnología secreta y materiales especiales con protección adicional ante la radiación. Tiene un chaleco antibalas bajo la túnica.}
{3000}{}{Armadura de metal}
{3001}{}{Placas de metal pulido, que forman toscamente una armadura. Otorga una excelente protección contra proyectiles y golpes, pero es pesada e incómoda de usar.}
{3100}{}{Armadura Tesla}
{3101}{}{Esta brillante armadura proporciona una protección superior contra los ataques de energía. Las tres bobinas Tesla de atracción dispersan un gran porcentaje de la energía recibida en un ataque.}
{3200}{}{Armadura de combate}
{3201}{}{Armadura de alta tecnología, elaborada con avanzados polímeros defensivos.}
{3300}{}{Armadura de la Hermandad}
{3301}{}{Una versión mejorada de la armadura de combate. La Hermandad del Acero ha hecho muchas mejoras sobre la versión estándar.}
{3400}{}{Servoarmadura T-51, dañada}
{3401}{}{Una armadura autónoma con tecnología avanzada. Este traje está parcialmente dañado.}
{3500}{}{Servoarmadura T-51b}
{3501}{}{Una armadura autónoma con tecnología avanzada. Alimentada con un reactor de micro-fusión, con suficiente combustible para cientos de años.}
{3600}{}{Armadura de la Carretera}
{3601}{}{Una chaqueta de cuero de la pre-guerra, reforzada con señales de tráfico. Tales chaquetas son utilizadas por los Escudos Azules.}
{3700}{}{Gabardina de Ranger}
{3701}{}{Una armadura fabricada artesanalmente utilizando cuero de brahmán, hecha a mano para los Rangers. Sólo los maestros curtidores de San Brahmán conocen los secretos de su fabricación.}
###------- DIFFERENT THINGS
{3800}{}{Célula de Fusión}
{3801}{}{Una gran unidad de almacenamiento de energía. Es una fuente de energía común para vehículos pequeños y ciertos tipos de equipamiento.}
{3900}{}{!Do not use}
{3901}{}{Originally - Small Energy Cell.}
{4000}{}{Estimulante}
{4001}{}{Un producto químico curativo. Cuando se inyecta, la sustancia química cura inmediatamente heridas menores. Efectos: +(20-30) de salud.}
{4100}{}{Chapas de botella}
{4101}{}{Esta bolsa contiene tus chapas. Hace poco, en los asentamientos grandes, se han estado utilizando como moneda de cambio para el comercio.}
{4200}{}{Dólar de la preguerra}
{4201}{}{Un dólar, fue reemplazado hace mucho. A pesar de ello, unos pocos residentes del yermo todavía lo usan.}
{4300}{}{Fichas de casino}
{4301}{}{Estas fichas son usadas en los casinos. Si no supieras esto, pensarías que son un juguete para niños de la preguerra.}
{4400}{}{Chapa de identificación de un soldado}
{4401}{}{Esta vieja chapa de identificación tiene grabada el nombre del soldado y su número de identificación.}
{4500}{}{Basura de bolsillo}
{4501}{}{Un montón de basura inútil proveniente de tu bolsillo. Si te encuentras con esto, parece que se te acabó la suerte. Quizás valga la pena conservarla.}
{4600}{}{Ficha}
{4601}{}{Esta ficha puede utilizarse como su dueño guste.}
{4700}{}{!Do not use}
{4701}{}{Original: First Aid Kit.}
{4800}{}{RadAway}
{4801}{}{Una solución química que enlaza con las partículas radiactivas y las elimina de tu sistema. Necesita tiempo para que funcione. Efectos: -(100-150) radiación.}
{4900}{}{Antídoto}
{4901}{}{Varias ampollas de un kit de primeros auxilios del ejército, que contienen poderosas antitoxinas. Neutralizan el veneno y sus efectos. Se incluye un torniquete. Efectos: -(45-60) envenenamiento.}
{5000}{}{Bolsa de doctor}
{5001}{}{Esta bolsa marrón contiene instrumentos y productos químicos que usan los médicos en el ejercicio de su profesión.}
{5100}{}{!Do not use}
{5101}{}{Original: Dynamite.}
{5200}{}{Contador Geiger}
{5201}{}{Un modelo C-Radz de contador Geiger de Wattz Electronics. Detecta la presencia y la intensidad de los campos radiactivos.}
{5300}{}{Mentats}
{5301}{}{Una caja de píldoras que alteran la mente. Incrementa las funciones relacionadas con la memoria, y la velocidad de otros procesos mentales. Altamente adictiva. Efectos: +2 IN, +2 PE, +1 CA.}
{5400}{}{Sigilante}
{5401}{}{Un dispositivo personal de sigilo Stealth Boy 3001, de RobCo. Genera un campo modulado que transmite la luz reflejada de la cara de un objeto sobre otra. Efectos: +20 a Sigilo, mientras esté encendido.}
{5500}{}{Walkie-Talkie}
{5501}{}{Modelo 2043B Radio Communicator, de la excelente marca Wattz Electronics. Fiable, resistente y de camuflaje.}
{5600}{}{Trampa para iguanas}
{5601}{}{Un dispositivo casero para atrapar lagartos del desierto.}
{5700}{}{Coraza}
{5701}{}{Un par de placas metálicas que cuelgan de los hombros con unos cinturones viejos. En la ausencia de armadura corporal, incluso esto podría salvar una vida. Quizás.}
{5800}{}{Pincho de planta}
{5801}{}{Una semilla-pincho orgánica que las plantas carnívoras escupen sobre portadores potenciales de alimentos o semillas.}
{5900}{}{Sensor de movimiento}
{5901}{}{Un sensor de movimiento modelo C-U de Wattz Electronics. Detecta el movimiento de la materia biológica a varios metros de distancia usando un radar sintonizado. Tener uno en tu inventario también te ayudará a evitar encuentros al aire libre (+20% a la habilidad Supervivencia).}
###------- PROVISION
{6000}{}{Pincho de iguana}
{6001}{}{Una iguana cocinada, asada en su propia piel. Efectos: +2 salud.}
{6100}{}{Fruta}
{6101}{}{Una extraña pieza de fruta. Sin conservantes ni colorantes. Efectos: +3 salud.}
{6200}{}{Cecina}
{6201}{}{Esta carne de bestia ahumada y seca se mantiene masticable y parcialmente nutritiva durante años, y años, y años... Efectos: +4 salud.}
{6300}{}{Caja de fideos}
{6301}{}{Una caja de fideos de una marca reconocida de la preguerra. Para tu sorpresa, todavía no caducan. Efectos: +7 salud.}
{6400}{}{Pequeña Caja Polvorienta de Algo}
{6401}{}{No estás seguro, pero seguramente no es comestible. No estás totalmente seguro de si alguna vez lo fue. Efectos: +10 salud, +5 velocidad de curación.}
{6500}{}{Larvas}
{6501}{}{Unas enormes larvas de alguna especie de mosca que se reproducieron en un cadáver. Para un habitante del yermo, esto es un festín lleno de proteína. Efectos: +2 salud.}
{6600}{}{Salchichas de Brahmán}
{6601}{}{Este platillo fue preparado acorde a una receta especial. Además de la obvia tripa de brahmán, podría tener... lo que sea. Efectos: +5 salud, +5 reacción.}
{6700}{}{Sopa de rata}
{6701}{}{Un delicioso platillo hecho a partir de rata y aditivos imposibles de deletrear. Un poco de todo. Efectos: +6 salud.}
{6800}{}{Ración Militar}
{6801}{}{Un almuerzo individual para un soldado de la Hermandad del Acero. El habitante promedio de Sonora jamás podría probar un almuerzo así. Efectos: +12 salud, +10 velocidad de curación.}
{6900}{}{Platillo podrido}
{6901}{}{Un platillo de carne podrida. Difícilmente podrías darle un uso a esto, pero te lo puedes comer. Si te atreves. Efectos: +(5-15) envenenamiento.}
{7000}{}{Cucaracha Tostada}
{7001}{}{Una cucaracha tostada al fuego con un poquito de sal. ¡Mmm, qué delicia! Efectos: +2 salud.}
{7100}{}{Botana}
{7101}{}{Una caja de "Bandito." Para tu sorpresa, siguen habiendo unos totopos rancios adentro. Efectos: +5 salud}
{7200}{}{Chaqueta de los Carroñeros}
{7201}{}{Una chaqueta gruesa de la preguerra, modificada para explorar las ruinas de Dayglow. Posee una capa de aluminio y tela sintética para proteger contra la radiación.}
###------- TOOLS
{7300}{}{!Reserve book}
{7301}{}{Do not use (Big Book of Science).}
{7400}{}{Ganzúa}
{7401}{}{Una ganzúa improvisada para que forzar una cerradura sea más fácil. De uso único.}
{7500}{}{Decodificador}
{7501}{}{Un dispositivo de alta potencia que ayuda a piratear un sistema electrónico. Tiene suficiente carga para una última operación.}
{7600}{}{!Reserve book}
{7601}{}{Do not use (Electronics).}
{7700}{}{Máscara de gas}
{7701}{}{Una vieja y maltrecha máscara de gas para civiles. Te protegerá de gases tóxicos por un tiempo.}
{7800}{}{Gafas de Hojalatero}
{7801}{}{Gafas electrónicas hechas por los Hojalateros de Two-Sun. Poseen visión nocturna, lentes de enfoque variable y varios sensores. La batería dura 10 minutos.}
{7900}{}{Bengala}
{7901}{}{Una bengala. Crea luz durante un corto periodo de tiempo. El papel está un poco usado, pero por lo demás está en buenas condiciones. Gira la parte superior para activarla.}
{8000}{}{!Reserve book}
{8001}{}{Do not use (First Aid, First Aid Book).}
{8100}{}{Botas de caucho}
{8101}{}{Un viejo par de botas de caucho. Parecen lo bastante duraderas como para librarte de los residuos, al menos durante un tiempo.}
{8200}{}{Pala}
{8201}{}{Es una pala, para excavar zanjas y otras cosas.}
{8300}{}{Cuerda}
{8301}{}{Una cuerda fuerte y fina. De unos 45 pies de longitud.}
{8400}{}{Encendedor}
{8401}{}{Un encendedor plateado, en buenas condiciones.}
{8500}{}{Explosivos plásticos}
{8501}{}{Un trozo de Cordex, una marca militar de explosivo plástico. Altamente inestable, y muy destructivo.}
{8600}{}{!Reserve book}
{8601}{}{Do not use (Scout's Handbook).}
{8700}{}{Esteroides}
{8701}{}{Esteroides altamente avanzados. Mientras hacen efecto, incrementan la fuerza y los reflejos. Muy adictivos. Efectos: +2 FU, +2 AG, +3 RE.}
{8800}{}{Chatarra}
{8801}{}{Piezas para varios tipos de maquinaria y dispositivos. Podrían hacer que reparar algo sea más fácil, pero también son valiosas durante un intercambio.}
{8900}{}{Partes electrónicas}
{8901}{}{Varias piezas de equipamiento electrónico: capacitores, tubos catódicos, bobinas y mucho más. Harán que reparar algo sea más fácil, también serían valiosas durante un intercambio.}
{9000}{}{Mezcla inflamable}
{9001}{}{Una botella que contiene una mezcla de varias sustancias inflamables. Un recurso relativamente valioso en las condiciones actuales.}
{9100}{}{!Do not use}
{9101}{}{Original: Doctor's case.}
{9200}{}{Cola de escorpión}
{9201}{}{La cola cortada de un escorpión rad.}
{9300}{}{Trinitita}
{9301}{}{Un tipo de vidrio formado como consecuencia de una explosión nuclear. No es nada especial a primera vista, pero es letal por su nivel de radioactividad.}
{9400}{}{Libro de la preguerra}
{9401}{}{Uno de los pocos libros de la preguerra que han sobrevivido. La mayoría lo verá como algo que echar a la fogata, pero unos pocos lo ven como una valiosa fuente de información.}
{9500}{}{Harina de maíz}
{9501}{}{Un alimento básico de la dieta moderna. Tiene algunas piedras que han entrado por accidente.}
{9600}{}{Limpiador}
{9601}{}{Un polvo especial para quitar la mugre Es capaz de quitar incluso tierra que ha estado ahí por siglos.}
{9700}{}{Toallitas húmedas}
{9701}{}{Un paquete sellado con toallitas sanitarias. Pueden reemplazar un baño cuando viajas por el yermo.}
{9800}{}{Hojas del Yermo}
{9801}{}{Hojas maduras de una planta del yermo. Muchos viajeros las ven como una buena fuente de micronutrientes, pero los citadinos como un afrodisíaco. Guárdalas para comerciar.}
{9900}{}{Café}
{9901}{}{Esta jarra contiene una especie de "granos de café". Parece que esto es una especie de producto del Viejo Mundo.}
{10000}{}{Chanclas}
{10001}{}{Un par de chanclas caseras hechas a partir de unos neumáticos viejos. Es mejor que nada.}
{10100}{}{Cerámica}
{10101}{}{Una simple jarra hecha de arcilla. Tales objetos se venden a buen precio en varios asentamientos.}
{10200}{}{!Reserve book}
{10201}{}{Do not use (Weapons and Ammo).}
{10300}{}{Equipamiento de San Brahmán}
{10301}{}{Parte del equipo de la tribu. Incluye un escudo de madera y una capa de cuero.}
{10400}{}{Armadura de combate de la NRM}
{10401}{}{Armadura de alta tecnología de la preguerra, porta la insignia de la Nueva República Mexicana.}
{10500}{}{Cantimplora}
{10501}{}{Esta cantimplora fue un regalo de los moradores del Refugio. Te ayudará a viajar por el árido y vacío desierto.}
{10600}{}{Nuka-Cola}
{10601}{}{Una botella de Nuka-Cola, la bebida más sabrosa del mundo post-nuclear. Está caliente e insípida. Efectos: +(3-5) salud.}
{10700}{}{Nuka-Cola Irradiada}
{10701}{}{Una asombrosa bebida de la preguerra en una botella un poco sucia. Deja una sensación genial en la lengua y tiene un muy cuestionable brillo en la oscuridad. Efectos: +(3-5) salud, +3 radiación.}
{10800}{}{Agua purificada}
{10801}{}{Agua potable, la fuente de la vida. Está purificada de suciedad y radiación. Debe usarse cautelosamente, especialmente en medio del yermo. Efectos: +(7-10) salud.}
{10900}{}{Rad-X}
{10901}{}{Producto químico anti-radiación que debe tomarse antes de la exposición. No tiene efectos secundarios conocidos. Efectos: +25 resistencia a la radiación.}
{11000}{}{Psico}
{11001}{}{Un elemento especial lleno de extraños y desconocidos componentes químicos de probable origen militar. Se supone que incrementa el potencial de combate de un soldado. Efectos: +3 AG, -3 IN, +25 resistencia al daño.}
{11100}{}{Rad-Polvo}
{11101}{}{Un polvo tóxico concentrado, es el resultado de una explosión nuclear. Al arrojar esto al rostro de un enemigo, podrás apreciar cómo sus ojos se deslizan desde sus cuencas hasta su barbilla. Efectos: -2 PE, -5 reacción, -3 AP}
{11200}{}{Jeringuilla vacía}
{11201}{}{Una jeringuilla vacía. Es un objeto útil para la medicina moderna.}
{11300}{}{Chapa de identificación del Caballero}
{11301}{}{Esta chapa de identificación tiene grabado un nombre y un número de identificación.}
{11400}{}{Chapa de identificación del Escudero}
{11401}{}{Esta chapa de identificación tiene grabado un nombre y un número de identificación.}
{11500}{}{Servoarmadura Mexicana}
{11501}{}{Una armadura autónoma adaptada a las necesidades de la Armada Mexicana. A diferencia de la original, pesa menos, pero tiene un rendimiento reducido.}
{11600}{}{Ácido}
{11601}{}{Una dosis de un fuerte ácido}
{11700}{}{Armadura de combate de necrófago}
{11701}{}{Una armadura de combate dañada. Algunas partes han sido reemplazadas con objetos caseros.}
{11800}{}{Ametralladora de Dixon}
{11801}{}{Una ametralladora pesada, fue fabricada para usarse desde los costados de un barco. Min FU: 7}
{11900}{}{Lanza de electrochoque}
{11901}{}{Un arma casera que emite una corriente eléctrica al entrar en contacto con la víctima. Min. FU: 3.}
###------- ALCOHOL
{12000}{}{Cerveza de la preguerra}
{12001}{}{Esta lata de cerveza fue producida antes de la Guerra. Era producida localmente. Efectos: -1 PE}
{12100}{}{Jarabe}
{12101}{}{Jarabe obtenido a partir del jugo del 'agave ardiente'. A pesar de su terrible hedor y sabor a quemado, contiene grandes cantidades de fructosa y azúcar.}
{12200}{}{Bazofia}
{12201}{}{Una bebida alcohólica diluida de baja calidad. Ya no podría determinarse su composición ni sus orígenes. Efectos: -1 PE, -1 IN.}
{12300}{}{Whiskey de la preguerra}
{12301}{}{Un fuerte trago alcohólico de la marca Atomic Whiskey. Tiene un valor mucho mayor en el mundo moderno comparado a otros tipos de alcohol. Efectos: -1 PE, +1 CA}
{12400}{}{Cerveza casera}
{12401}{}{Una de las pocas cervezas que se siguen produciendo en el yermo actual. Efectos: -1 PE.}
{12500}{}{Tequila del Yermo}
{12501}{}{Esta botella de tequila viene de Fénix y es de muy dudosa calidad. Hay un gusanito flotando adentro. Efectos: -1 PE.}
###------- WEAPON
{12600}{}{Nudilleras}
{12601}{}{Duras nudilleras hechas de auténtico acero. Protegen tu mano, y hacen más daño en un combate desarmado. Min FU: 1.}
{12700}{}{Nudillera con pinchos}
{12701}{}{Una versión mejorada de las clásicas nudilleras. Los nudillos con pinchos hacen más daño, rasgando la carne de tu oponente en un combate desarmado. Min FU: 1.}
{12800}{}{Garras}
{12801}{}{Un arma cuerpo a cuerpo improvisada. Consiste de dos cuchillas atornilladas juntas a un agarre. Min FU: 1.}
{12900}{}{Puño Neumático}
{12901}{}{Unas nudilleras mécanicas hechas manualmente. Al golpear, empuja unas púas afiladas hacia delante con fuerza, penetrando el cuerpo de la víctima. Min FU: 1.}
{13000}{}{Guante Eléctrico}
{13001}{}{Un taser policial modificado. Al entrar en contacto con la víctima, el arma transmite una poderosa corriente eléctrica a su cuerpo, y un viejo guante de cuero protege al portador del choque eléctrico. Min FU: 1.}
{13100}{}{Servopuño}
{13101}{}{Un servopuño "Acojonador" de BeatCo. Considerado por muchos la arma definitiva en combate desarmado. Otros se limitan a asustarse. Alimentado por células de microfusión. Min FU: 1.}
{13200}{}{Cuchillo}
{13201}{}{Una hoja afilada, cortante y punzante. Min FU: 1.}
{13300}{}{Cuchillo de combate}
{13301}{}{Un cuchillo de combate de alta calidad de SharpWit Inc. ¡Se garantiza el afilado de la hoja a lo largo de diez años de uso! Min FU: 1.}
{13400}{}{Cuchillo de doble hoja}
{13401}{}{Un cuchillo grande con una hoja de doble filo. Sigue tan afilado como el día que salió de la fábrica. Min. FU: 1.}
{13500}{}{Destripador}
{13501}{}{Una hoja vibratoria Destripador(tm). Alimentada con células de microfusión, la hoja destripa y desgarra a su objetivo. Min FU: 1.}
{13600}{}{Cortador Atómico}
{13601}{}{Una herramienta de trabajo para cortar material grueso. Rompe los enlaces moleculares usando una potente radiación. Alimentada por una batería que va en la cintura. Min. strength: 1.}
{13700}{}{Lanza}
{13701}{}{Un palo con una hoja afilada. El mango es de madera, y la punta es de acero. Min FU: 4.}
{13800}{}{Lanza Neumática}
{13801}{}{Una invención peculiar de unos ingenieros del área. Al entrar en contacto con la víctima, el arma empuja una púa afilada, y luego usa un resorte para devolverla a su lugar. Min FU: 4.}
{13900}{}{Lanza Eléctrica}
{13901}{}{Un arma policial de gran efectividad, utilizada para dispersar muchedumbres de protestantes. Se usaba a menudo antes de la Gran Guerra. Min FU: 4.}
{14000}{}{Porra}
{14001}{}{Una porra militar o de la policía. De madera maciza. Min FU: 3.}
{14100}{}{Palanca}
{14101}{}{Una pieza de metal muy sólida y pesada, especialmente diseñada para apalancar. O para golpear cabezas. Min FU: 3.}
{14200}{}{Picana}
{14201}{}{Una picana modelo 'La Mejor Amiga Del Granjero', de Wattz Electronics. Utiliza células de microfusión. Min FU: 3.}
{14300}{}{Super picana}
{14301}{}{Una picana modelo 'La Mejor Amiga Del Granjero', de Wattz Electronics. Este modelo se ha actualizado para incrementar su descarga eléctrica. Min FU: 3.}
{14400}{}{Superestimulante}
{14401}{}{Un avanzado producto químico curativo. Muy potente. Los superestimulantes producirán una pequeña cantidad de daño después de un periodo de tiempo, debido a la potencia de los productos químicos utilizados. Efectos: +75 salud, -1 FU.}
{14500}{}{Almádena}
{14501}{}{Un gran martillo con un mango también grande. Muy popular entre la gente musculosa. Min FU: 6.}
{14600}{}{Martillo}
{14601}{}{Un martillo balanceado y de peso ligero con una mejor maniobrabilidad. Antes se usaban para destrozar ladrillos, ahora tiene un uso más práctico. Min. FU: 5.}
{14700}{}{Super almádena}
{14701}{}{Una super almádena, elaborada por la Hermandad del Acero, que usa la mejor tecnología armamentística disponible. Incluye un dispositivo que almacena energía cinética, para aumentar la pegada. Min FU: 5.}
{14800}{}{Revólver viejo}
{14801}{}{Una antigua arma de grado civil. Como cualquier revólver, se le aprecia por su simplicidad y fiabilidad. Min. FU: 4.}
{14900}{}{Revólver policial}
{14901}{}{Un confiable revólver de S&W, fue popular en su época entre los oficiales de policía y patrullas de la carretera. Min. FU: 4.}
{15000}{}{Revólver de combate}
{15001}{}{Un poderoso revólver. El arma favorita de coleccionistas y pistoleros pretenciosos. Ahora te pertenece. Min. FU: 5.}
{15100}{}{Pistola de bengalas}
{15101}{}{Una pistola de bengalas. Difícilmente se le puede llamar un arma, pero si la usas en el momento indicado, puede asustar a un enemigo, especialmente si utilizas bengalas modificadas. Min. FU: 3.}
{15200}{}{Ametralladora .22}
{15201}{}{Un arma de deporte de un tiempo ya pasado. Ahora, su uso principal es cazar iguanas y asustar a los malhechores. Min. FU: 3.}
{15300}{}{Pistola de 10mm}
{15301}{}{Una pistola Colt 6520 con cargador automático de 10mm. Cada disparo recargará automáticamente el arma hasta que se vacíe el cargador. De un solo disparo, usa las potentes balas de 10mm. Min FU: 3.}
{15400}{}{SMG de 10mm}
{15401}{}{Sub-ametralladora H&K MP9 (variante de 10mm). Una SMG de tamaño medio, de disparo único o modo ráfaga. Min FU: 4.}
{15500}{}{Subfusil Mexicano}
{15501}{}{Un subfusil HM-23 desarrollado por Productos Mendoza. Fue utilizado por la Policía Mexicana y tuvo un buen rendimiento en la frontera antes de la Gran Guerra. Min. FU: 4.}
{15600}{}{Pistola .50}
{15601}{}{Una pistola automática de SIG-Sauer. Requiere una buena habilidad con las armas de fuego gracias al enorme retroceso de cada disparo y alto nivel de ruido. Min. FU: 5.}
{15700}{}{Rifle de caza}
{15701}{}{Un rifle semiautomático Colt Rangemaster. Viejo, pero confiable. Min. FU: 5.}
{15800}{}{Rifle de combate}
{15801}{}{Un rifle semiautomático americano de la serie AR, anteriormente estaba en servicio en los Estados Unidos y en México. Conveniente y confiable. Min. FU: 5.}
{15900}{}{Cóctel Molotov}
{15901}{}{Una granada inflamable casera. Min FU: 4.}
{16000}{}{Rifle de francotirador}
{16001}{}{Un rifle francotirador DKS-501. Un excelente arma de largo alcance. Min. FU: 6.}
{16100}{}{Rifle de asalto}
{16101}{}{Un rifle de asalto AK-112 de 5mm. Un antiguo modelo militar, en desuso en la época de la guerra. Puede disparar un único tiro o una ráfaga, usando balas de 5mm de alta velocidad. Min FU: 5.}
{16200}{}{Ametralladora ligera}
{16201}{}{Una ametralladora Mendoza C-2075 del modelo calibre 5mm. Cuando las relaciones con los Estados Unidos empeoraron, México volvió a desarrollar sus propias armas, ésta es una de ellas. Min. FU: 6.}
{16300}{}{Minicañón}
{16301}{}{Un minicañón personal Rockwell CZ53. Una ametralladora de cañón múltiple que dispara municiones de 5mm a 60.000 RPM. Min FU: 7}
{16400}{}{Escopeta}
{16401}{}{Una escopeta Winchester Widowmaker con dos cañones y calibre 12. De cañón corto, con asa en caoba. Min FU: 6.}
{16500}{}{Escopeta de combate}
{16501}{}{Una escopeta de combate Winchester City-Killer de calibre 12. En excelentes condiciones, tiene un sellador ambiental opcional DesertWarfare para una mayor fiabilidad. Min FU: 6.}
{16600}{}{Escopeta de asalto}
{16601}{}{Una escopeta de asalto para rango cuerpo a cuerpo. El diseño de novillo la hace fácil de usar. Min. FU: 6.}
{16700}{}{Lanzagranadas 40mm}
{16701}{}{Un lanzagranadas de mano para granadas calibre 40mm. Desarrollado por Rockwell. Min. FU: 6.}
{16800}{}{Emisor Láser}
{16801}{}{Un arma casera hecha a partir de partes de un robot industrial. Puede emitir un láser de baja potencia a corta distancia. Min FU: 3}
{16900}{}{Pistola láser}
{16901}{}{Una pistola láser Wattz 1000. Modelo civil, así que tiene menor potencia que las versiones militares y de la policía. Usa células de microfusión. Min FU: 3.}
{17000}{}{Rifle láser}
{17001}{}{Un rifle láser Wattz 2000. Usa células de microfusión para un láser más potente, y un cañón extendido para mayor alcance. Min FU: 4.}
{17100}{}{Pistola de plasma}
{17101}{}{Pistola de plasma Glock 86. Diseñada por la Gaston Glock AI. Dispara un pequeño rayo de plasma supercaliente. Alimentada por células de microfusión. Min FU: 3.}
{17200}{}{Rifle de plasma}
{17201}{}{Un rifle de plasma Winchester P94. Un arma energética de grado industrial, que dispara rayos de plasma supercalientes  por un cañón superconductor. Alimentado por células de microfusión. Min FU: 4.}
{17300}{}{Radiador}
{17301}{}{Un arma única que utiliza radiación de frecuencia ultra-alta. Algunos de sus componentes pertenecen a maquinaria industrial. Min FU: 4.}
{17400}{}{Coa}
{17401}{}{Una herramienta profesional para cortar y procesar agave. Fue fabricada hace poco. Min. FU: 4.}
{17500}{}{Pistola casera}
{17501}{}{Una pistola casera de disparo único. Es sorprendentemente efectiva, aunque podría explotar en tu mano. Min. FU: 3.}
{17600}{}{Rifle de caza con mira}
{17601}{}{Nada mejor que ver una mirada de sorpresa en el rostro de tu objetivo: la mira Unertl x10 de este rifle de caza lo hace más fácil que nunca. Precisa desde el primer al último tiro, sin que importe a lo que le estés disparando. Min FU: 5.}
{17700}{}{Ametralladora .22 (capacidad extra)}
{17701}{}{Un arma de deporte de un tiempo ya pasado. Ahora, su uso principal es cazar iguanas y asustar a los malhechores. Su cargador se expandió de 30 cartuchos a 60.  Min. FU: 3.}
{17800}{}{Lanzagranadas 40mm (capacidad extra)}
{17801}{}{Un lanzagranadas de mano para granadas calibre 40mm. Desarrollado por Rockwell. Su cargador se expandió de 1 disparo a 6. Min. FU: 6.}
{17900}{}{Rifle Winchester}
{17901}{}{Un rifle Winchester módelo 2073, con acción por palanca y cargador de tubo. Es uno de los únicos en existencia. Min. FU: 5.}
{18000}{}{Trapero}
{18001}{}{Un trapero. No es necesario decir más. Min. FU: 1.}
{18100}{}{Pistola .22}
{18101}{}{Una simple y confiable pistola de bajo calibre. Fue desarrollada por la compañía mexicana "Industrias Trejo". Min FU: 2.}
{18200}{}{Rifle de asalto (capacidad extra)}
{18201}{}{Un rifle de asalto AK-112 de 5mm. Un antiguo modelo militar, en desuso en la época de la guerra. Puede disparar un único tiro o una ráfaga, usando balas de 5mm de alta velocidad. Tiene un cargador extendido, de 24 cartuchos a 40. Min FU: 6.}
{18300}{}{Cañón de riel}
{18301}{}{Esta arma utiliza el poder electromagnético para lanzar proyectiles metálicos. Min. FU: 7.}
{18400}{}{Lanzallamas}
{18401}{}{Un lanzallamas modelo Flambe 450, variante 'varmiter'. Dispara un chorro corto de líquido inflamable extremadamente caliente. Requiere un combustible especial para que funcione correctamente. Min FU: 6.}
{18500}{}{Combustible de lanzallamas}
{18501}{}{Un cilindro que contiene un líquido combustible extremadamente inflamable para lanzallamas.}
{18600}{}{Ametralladora de los Tejada}
{18601}{}{Al ver de cerca esta vieja arma, sientes el deseo de gritar "¡Viva Tejada!" mientras corres al campo de batalla. Min. FU: 6.}
{18700}{}{Bláster}
{18701}{}{Esta pistola parece haber salido directo de una clásica película de ciencia ficción. Dispara un haz de partículas aceleradas a la velocidad de la luz. Min. FU: 3.}
{18800}{}{Gatling láser}
{18801}{}{Una Gatling H&K L30 láser. Diseñada para uso militar, estaba en fase de prototipo al principio de la gran guerra. Sus múltiples cañones le permiten disparar varias veces antes de sobrecalentarse. Alimentada por células MF de microfusión. Min FU: 6.}
{18900}{}{Cañón dual de plasma}
{18901}{}{Utilizado únicamente por torretas.}
{19000}{}{Hacha de batalla}
{19001}{}{Una vieja hacha para acampar, ahora puede utilizarse para el combate. Min. FU: 3.}
{19100}{}{Rifle de Turbo Plasma}
{19101}{}{Un rifle de plasma modificado Winchester P94. La cámara de plasma ha sido puenteada para acelerar el proceso de formación del rayo. Min FU: 4.}
###------- CONTAINERS
{19200}{}{Caja del ejército}
{19201}{}{Una caja de munición a prueba de balas.}
{19300}{}{Caja de comerciante}
{19301}{}{Una caja típicamente usada por mercaderes para guardar su mercancía.}
{19400}{}{Trampa para iguanas}
{19401}{}{Un dispositivo casero para atrapar lagartos del desierto.}
{19500}{}{Tumba de un perro}
{19501}{}{Alguien cavó aquí hace poco. Se pueden ver huesos y pedazos de pelo a través de la tierra.}
{19600}{}{Tierra recientemente cavada}
{19601}{}{Este suelo fue cavado hace poco. Puede que hayan enterrado un tesoro, o un cadáver.}
{19700}{}{Basura}
{19701}{}{Una selección de primera calidad de basura sin valor.}
{19800}{}{Caja de otra ciudad}
{19801}{}{Los paquetes de otras ciudades se guardan aquí.}
{19900}{}{Caja para otra ciudad}
{19901}{}{Los paquetes destinados a llegar a otras ciudades se guardan aquí.}
{20000}{}{Caja para Flagstaff}
{20001}{}{Una caja con objetos destinados a la ciudad de Flagstaff.}
{20100}{}{Caja para Fénix}
{20101}{}{Una caja con objetos destinados a la ciudad de Fénix.}
{20200}{}{Caja de Two-Sun}
{20201}{}{Una caja con objetos enviados desde la ciudad de Two-Sun.}
{20300}{}{Tierra recientemente cavada}
{20301}{}{Este suelo fue cavado hace poco. Puede que hayan enterrado un tesoro, o un cadáver.}
{20400}{}{Caja tachonada}
{20401}{}{Una caja de madera. Necesitarás una herramienta o la fuerza bruta para sacar los clavos.}
{20500}{}{Bengala}
{20501}{}{Una bengala. Ofrece luz durante un corto periodo de tiempo. El papel está un poco usado, pero por lo demás está en buenas condiciones. Está encendida.}
{20600}{}{!Do not use}
{20601}{}{Original: Dynamite.}
{20700}{}{Contador Geiger}
{20701}{}{Un modelo C-Radz de contador Geiger de Wattz Electronics. Detecta la presencia y la intensidad de los campos radiactivos. Está encendido..}
{20800}{}{Sensor de movimiento, encendido}
{20801}{}{Un sensor de movimiento modelo C-U de Wattz Electronics. Detecta el movimiento de la materia biológica a varios metros de distancia usando un radar sintonizado. Tener uno en tu inventario también te ayudará a evitar encuentros al aire libre. (+20% a la habilidad Supervivencia).}
{20900}{}{Explosivos plásticos}
{20901}{}{Un trozo de Cordex, una marca militar de explosivo plástico. Altamente inestable, y muy destructivo. Incluye un temporizador, porque está haciendo tic-tac.}
{21000}{}{Sigilante}
{21001}{}{Un dispositivo personal de sigilo Stealth Boy 3001, de RobCo. Genera un campo modulado que transmite la luz reflejada de la cara de un objeto sobre otra. Está encendido. Efectos: +20 a Sigilo.}
{21100}{}{Tumba}
{21101}{}{}
{21200}{}{Tumba}
{21201}{}{}
{21300}{}{Tumba}
{21301}{}{}
{21400}{}{Tumba}
{21401}{}{}
{21500}{}{Tumba}
{21501}{}{}
{21600}{}{Tumba}
{21601}{}{}
{21700}{}{Tumba}
{21701}{}{}
{21800}{}{Huesos}
{21801}{}{Varios huesos humanos.}
{21900}{}{Carro}
{21901}{}{Un carro de mercancías convertido a partir de restos destrozados de un antiguo automóvil.}
{22000}{}{Carro}
{22001}{}{Un carro de mercancías convertido a partir de restos destrozados de un antiguo automóvil.}
{22100}{}{Jarra}
{22101}{}{Una gran jarra para almacenar la cosecha o agua.}
{22200}{}{Jarrón}
{22201}{}{Un bonito jarrón de arcilla.}
{22300}{}{Jarrón}
{22301}{}{Un bonito jarrón de arcilla.}
{22400}{}{Caja}
{22401}{}{Una caja de madera, llena de varias cosas.}
{22500}{}{Cosas}
{22501}{}{Diversos objetos, también conocidos como "cosas".}
{22600}{}{Cosas}
{22601}{}{Diversos objetos, también conocidos como "cosas".}
{22700}{}{Cosas}
{22701}{}{Diversos objetos, también conocidos como "cosas".}
{22800}{}{Cosas}
{22801}{}{Diversos objetos, también conocidos como "cosas".}
{22900}{}{Caja fuerte}
{22901}{}{Una pequeña caja fuerte, está atornillada a una mesa de metal.}
{23000}{}{Cofre}
{23001}{}{Un cofre de madera.}
{23100}{}{Cofre}
{23101}{}{Un cofre de madera.}
{23200}{}{Estantería}
{23201}{}{Una estantería de madera.}
{23300}{}{Estantería}
{23301}{}{Una estantería de madera.}
{23400}{}{Estantería}
{23401}{}{Una gran estantería de madera llena de objetos polvorientos.}
{23500}{}{Estantería}
{23501}{}{Una gran estantería de madera llena de objetos polvorientos.}
{23600}{}{Estantería}
{23601}{}{Una gran estantería de madera llena de objetos polvorientos.}
{23700}{}{Estantería}
{23701}{}{Una gran estantería de madera llena de objetos polvorientos.}
{23800}{}{Estantería}
{23801}{}{Una gran estantería de madera llena de objetos polvorientos.}
{23900}{}{Estantería}
{23901}{}{Una gran estantería de madera llena de objetos polvorientos.}
{24000}{}{Contenedor de basura}
{24001}{}{Un contenedor de basura. Apenas puedes leer el letrero: ¡Mantén limpias las calles de tu ciudad!}
{24100}{}{Refrigerador}
{24101}{}{Un refrigerador. Se le acabó del refrigerante.}
{24200}{}{Caja refrigeradora}
{24201}{}{Una vieja caja refrigeradora. Las hebillas están en buenas condiciones.}
{24300}{}{Caja refrigeradora}
{24301}{}{Una vieja caja refrigeradora. Las hebillas están en buenas condiciones.}
{24400}{}{Mesa}
{24401}{}{Una mesa de madera con varios cajones.}
{24500}{}{Mesa}
{24501}{}{Una mesa de madera con varios cajones.}
{24600}{}{Mesa}
{24601}{}{Una mesa de madera con varios cajones. Trabajar aquí será riesgoso.}
{24700}{}{Mesa}
{24701}{}{Una mesa para el café, tiene unas tentadoras migajas.}
{24800}{}{Caja fuerte de pared}
{24801}{}{Una caja fuerte de pared bastante robusta.}
{24900}{}{Caja fuerte}
{24901}{}{Una caja fuerte bastante resistente.}
{25000}{}{Cajas de embalaje}
{25001}{}{Un montón de varias cajas de embalaje.}
{25100}{}{Cajas de embalaje}
{25101}{}{Un montón de varias cajas de embalaje, seguras y confiables.}
{25200}{}{Caja de embalaje}
{25201}{}{Una duradera caja de embalaje.}
{25300}{}{Caja de embalaje}
{25301}{}{Una duradera caja de embalaje.}
{25400}{}{Caja para botellas}
{25401}{}{Una caja de madera específicamente diseñada para almacenar y transporte de botellas.}
{25500}{}{Cómoda}
{25501}{}{Una cómoda común y corriente, tiene el hedor de la ropa sucia de alguien.}
{25600}{}{Cómoda}
{25601}{}{Una cómoda común y corriente, tiene el hedor de la ropa sucia de alguien.}
{25700}{}{Cómoda}
{25701}{}{Una cómoda común y corriente, tiene el hedor de la ropa sucia de alguien.}
{25800}{}{Cómoda}
{25801}{}{Una cómoda común y corriente, tiene el hedor de la ropa sucia de alguien.}
{25900}{}{!Do not use}
{25901}{}{Originally: Vint.}
{26000}{}{!Do not use}
{26001}{}{Originally: Antidote for the screw.}
{26100}{}{Estantería}
{26101}{}{Una estantería de madera en excelentes condiciones.}
{26200}{}{Estantería}
{26201}{}{Una estantería de madera en malas condiciones.}
{26300}{}{Estantería}
{26301}{}{Una estantería de madera, o mejor dicho, lo que queda de ella.}
{26400}{}{Estantería}
{26401}{}{Una estantería de madera en excelentes condiciones.}
{26500}{}{Estantería}
{26501}{}{Una estantería de madera en malas condiciones.}
{26600}{}{Estantería}
{26601}{}{Una estantería de madera, o mejor dicho, lo que queda de ella.}
{26700}{}{Lavabo}
{26701}{}{Un lavabo de porcelana que ha perdido la habilidad de funcionar.}
{26800}{}{Lavabo}
{26801}{}{Un lavabo de porcelana que ha perdido la habilidad de funcionar.}
{26900}{}{Mesa de trabajo}
{26901}{}{Bueno, es una mesa de trabajo, vieja, sin nada fuera de lo común.}
{27000}{}{Estante para herramientas}
{27001}{}{Este estante está cubierto de varias herramientas.}
{27100}{}{Refrigerador}
{27101}{}{Un refrigerador con ruedas para facilitar su transporte.}
{27200}{}{Mesa}
{27201}{}{Una mesa genérica. Si has visto una, ya las viste todas.}
{27300}{}{Mesa}
{27301}{}{Una mesa genérica. Mantiene a las cosas lejos del suelo.}
{27400}{}{Mesa}
{27401}{}{Una mesa genérica. Mantiene a las cosas lejos del suelo.}
{27500}{}{Mesa}
{27501}{}{Una mesa genérica. Mantiene a las cosas lejos del suelo.}
{27600}{}{Mesa}
{27601}{}{Una mesa genérica. Mantiene a las cosas lejos del suelo.}
{27700}{}{Mesa}
{27701}{}{Una mesa genérica. Mantiene a las cosas lejos del suelo.}
{27800}{}{Mesa}
{27801}{}{Una mesa genérica. Mantiene a las cosas lejos del suelo.}
{27900}{}{Casillero}
{27901}{}{Un recipiente de almacenamiento.}
{28000}{}{Casillero}
{28001}{}{Un recipiente de almacenamiento.}
{28100}{}{Casillero}
{28101}{}{Un recipiente de almacenamiento.}
{28200}{}{Casillero}
{28201}{}{Un recipiente de almacenamiento.}
{28300}{}{Baúl}
{28301}{}{Baúl básico. Guarda las cosas, se coloca a los pies de la cama, puede cerrarse con llave.}
{28400}{}{Baúl}
{28401}{}{Baúl básico. Guarda las cosas, se coloca a los pies de la cama, puede cerrarse con llave.}
{28500}{}{Baúl}
{28501}{}{Baúl básico. Guarda las cosas, se coloca a los pies de la cama, puede cerrarse con llave.}
{28600}{}{Baúl}
{28601}{}{Baúl básico. Guarda las cosas, se coloca a los pies de la cama, puede cerrarse con llave.}
{28700}{}{Baúl}
{28701}{}{Baúl básico. Guarda las cosas, se coloca a los pies de la cama, puede cerrarse con llave.}
{28800}{}{Baúl}
{28801}{}{Baúl básico. Guarda las cosas, se coloca a los pies de la cama, puede cerrarse con llave.}
{28900}{}{Casillero}
{28901}{}{Un casillero.}
{29000}{}{Casillero}
{29001}{}{Un casillero.}
{29100}{}{Casillero}
{29101}{}{Un casillero.}
{29200}{}{Casillero}
{29201}{}{Un casillero.}
{29300}{}{Casillero}
{29301}{}{Un casillero.}
{29400}{}{Casillero}
{29401}{}{Un casillero.}
{29500}{}{Cosas}
{29501}{}{Diversos objetos, también conocidos como "cosas".}
{29600}{}{Cosas}
{29601}{}{Diversos objetos, también conocidos como "cosas".}
{29700}{}{Cosas}
{29701}{}{Diversos objetos, también conocidos como "cosas".}
{29800}{}{Cosas}
{29801}{}{Diversos objetos, también conocidos como "cosas".}
{29900}{}{Caja del ejército}
{29901}{}{Una caja del ejército para almacenar y transportar armas.}
{30000}{}{Caja del ejército}
{30001}{}{Una caja del ejército para almacenar y transportar armas.}
{30100}{}{Caja del ejército}
{30101}{}{Una caja del ejército para almacenar y transportar munición.}
{30200}{}{Caja del ejército}
{30201}{}{Una caja del ejército para almacenar y transportar munición.}
{30300}{}{Cajas de embalaje}
{30301}{}{Un montón de varias cajas de embalaje.}
{30400}{}{Cajas de embalaje}
{30401}{}{Un montón de varias cajas de embalaje.}
{30500}{}{Caja de embalaje}
{30501}{}{Una duradera caja de embalaje.}
{30600}{}{Caja de embalaje}
{30601}{}{Una duradera caja de embalaje.}
{30700}{}{Casillero}
{30701}{}{Un casillero.}
{30800}{}{Casillero}
{30801}{}{Un casillero.}
{30900}{}{Casillero}
{30901}{}{Un casillero.}
{31000}{}{Casillero}
{31001}{}{Un casillero.}
{31100}{}{Contenedor}
{31101}{}{Un contenedor del ejército, dispone de blindaje contra la radiación.}
{31200}{}{Contenedor}
{31201}{}{Un contenedor del ejército, dispone de blindaje contra la radiación.}
{31300}{}{Alambique}
{31301}{}{Parece un alambique de alcohol de leña.}
{31400}{}{Mochila}
{31401}{}{Alguien dejó esta mochila tirada, tiene sus cosas dentro.}
{31500}{}{Máquina de Nuka-Cola}
{31501}{}{El anuncio del lateral de la máquina promociona su popular soda.}
{31600}{}{Cadáver de un convicto}
{31601}{}{El cadáver congelado de un prisionero fugitivo.}
{31700}{}{Jarrón con... ya sabes}
{31701}{}{No deberías meter la mano aquí.}
{31800}{}{Tótem roto}
{31801}{}{Un montón de basura que una vez fue un tótem de los Chacales.}
{31900}{}{Cadáver de un mercenario}
{31901}{}{El cadáver congelado de uno de los guardias de la expedición. Murió desangrado.}
{32000}{}{Sillón de mando}
{32001}{}{Aquí es donde se sienta habitualmente el Supervisor. Pero no se ha usado hace mucho tiempo.}
{32100}{}{Estanterías de metal}
{32101}{}{Unas antiguas estanterías de metal. Muy confiables.}
{32200}{}{Tanque con desperdicios orgánicos}
{32201}{}{Los restos de varios cadáveres humanos yacen en este tanque. Parece que el cirujano tuvo mucho trabajo.}
{32300}{}{Cadáver del sargento}
{32301}{}{El cadáver deshuesado de un sargento. Parece que fue asesinado por robots.}
{32400}{}{Expendedora de periódicos}
{32401}{}{Esta expendedora de periódicos está vacía... O tal vez no.}
{32500}{}{Pertenencias de los saqueadores}
{32501}{}{Para tu fortuna, los saqueadores olvidaron estos objetos antes de irse.}
{32600}{}{Micelio}
{32601}{}{Estos hongos resplandecientes crecen justo en el medio de una laguna tóxica y brillan en la oscuridad.}
{32700}{}{Caja de donaciones}
{32701}{}{Esta caja permite recolectar donaciones.}
{32800}{}{Mesa}
{32801}{}{Una mesa antigua y elegante, para aquellos con estándares altos. Se incluye una lujosa silla.}
{32900}{}{Armario de incendios}
{32901}{}{Te dijeron que esto se llama "Armario de incendios". Nadie recuerda de dónde vino el nombre.}
{33000}{}{Armario de incendios}
{33001}{}{Te dijeron que esto se llama "Armario de incendios". Nadie recuerda de dónde vino el nombre.}
{33100}{}{Libro de Bemis}
{33101}{}{Uno de los mejores libros de la pre-guerra. Contiene mucha información exclusiva, aún en su tiempo.}
{33200}{}{Mesa de billar}
{33201}{}{Una vieja mesa de billar. Ningún experto en billar que se precie jugaría aquí.}
{33300}{}{Mesa carnicera}
{33301}{}{Esta mesa es utilizada para cortar carne. Carne humana.}
{33400}{}{Ventilador bloqueado}
{33401}{}{Un viejo sistema de ventilación, está bloqueado con años de polvo y negligencia.}
{33500}{}{Tótem}
{33501}{}{Un tenebroso tótem hecho por los Segadores, a partir de varios pedazos de basura.}
{33600}{}{Caja registradora}
{33601}{}{Este escritorio tiene una caja registradora.}
{33700}{}{Cadáver de un mutante}
{33701}{}{Es el cadáver de un mutante deformado.}
{33800}{}{Tótem}
{33801}{}{Un tenebroso tótem hecho por los Segadores, a partir de varios pedazos de basura.}
{33900}{}{Tótem}
{33901}{}{Un tenebroso tótem hecho por los Segadores, a partir de varios pedazos de basura.}
{34000}{}{Tótem}
{34001}{}{Un tenebroso tótem hecho por los Segadores, a partir de varios pedazos de basura.}
{34100}{}{Tótem}
{34101}{}{Un tenebroso tótem hecho por los Segadores, a partir de varios pedazos de basura.}
{34200}{}{Espantapájaros}
{34201}{}{Un centinela cómicamente absurdo contra las plagas, improvisado con restos de la preguerra y harapos.}
{34300}{}{Cuerpo de un Merodeador}
{34301}{}{El cuerpo desgarrado de un chico joven. Al parecer, cayó en las garras de la fauna local.}
{34400}{}{Sarcófago}
{34401}{}{Aquí yace el cuerpo de tu ancestro.}
{34500}{}{Montón de hielo}
{34501}{}{Hay varias cosas congeladas en este montón de hielo.}
{34600}{}{Casillero}
{34601}{}{Un casillero.}
{34700}{}{Huesos}
{34701}{}{Ves a Ed. Y Ed está muerto. El mono tiene el número 13 en su espalda.}
{34800}{}{Máquina expendedora de Mentats}
{34801}{}{Según las grandes letras rojas que dicen "MENTATS", esta máquina debe vender mentats.}
{34900}{}{Restos de un robot}
{34901}{}{Este robot ha caído en esta laguna tóxica. ¡Qué muerte tan horrorosa!}
###------- HOLODICKS
{35000}{}{Registro del Fundador}
{35001}{}{Una maltrecha y antigua holocinta con notas del Fundador de la Villa. Parece que puedes insertarla en tu Pip-Boy.}
{35100}{}{Diario del Refugio 27}
{35101}{}{Una holocinta que contiene el diario de un morador del Refugio 27.}
{35200}{}{Informe de la expedición}
{35201}{}{Una holocinta bastante sucia, contiene los informes de la expedición al Refugio 27.}
{35300}{}{Holocinta de Quartz}
{35301}{}{Una vieja holocinta, carece de notas para identificar el remitente.}
{35400}{}{Grabación de McBain}
{35401}{}{Una holocinta de audio, contiene los últimos segundos de la vida del Sargento McBain.}
{35500}{}{Holodisco del Alcalde}
{35501}{}{Una holocinta con instrucciones para el alcalde de Casa Grande. El remitente se mantiene anónimo.}
{35600}{}{Notas de George Crook}
{35601}{}{Esta holocinta contiene notas escritas por el comandante misionario en San Brahmán.}
{35700}{}{Carta de Vault-Tec}
{35701}{}{Esta holocinta contiene un mensaje oficial de Vault-Tec.}
{35800}{}{Carta de la plataforma}
{35801}{}{Esta holocinta contiene una carta de la plataforma petrolífera de Petro-Chico.}
{35900}{}{Diario de Luther}
{35901}{}{El diario del Supervisor del Refugio 24.}
{36000}{}{Cuetes festivos}
{36001}{}{Una caja grande de pirotecnia mexicana.}
{36100}{}{Corona Ceremonial}
{36101}{}{Una corona hecha a partir de alambres y focos. Su apariencia es bizarra.}
{36200}{}{Brahmán}
{36201}{}{Estás apostando por este brahmán.}
{36300}{}{Llave magnética}
{36301}{}{Una llave magnética que abre las puertas de la Fortaleza Móvil Supermutante.}
{36400}{}{Radio}
{36401}{}{Una antigua radio de Wattz Electronics, todavía funciona..}
{36500}{}{Pertenencias de Brendley}
{36501}{}{Son las pertenencias de En Brendley, entre ellas está su libreta.}
{36600}{}{Paquete perdido}
{36601}{}{Un mensajero llevaba este paquete, está lleno de documentos y cartas destinadas para Fénix. Tiene pegada esta nota: "Si se encuentra, regresarlo a la oficina del Sonora Express por una recompensa."}
{36700}{}{Collar de tu Madre}
{36701}{}{Una reliquia familiar pasada de generación en generación por el lado femenino de la familia.}
{36800}{}{Sustancia Verde}
{36801}{}{Un químico de propósito desconocido del laboratorio de los Seguidores.}
{36900}{}{Sustancia Púrpura}
{36901}{}{Otro químico enigmático del laboratorio de los Seguidores.}
{37000}{}{Sustancia Roja}
{37001}{}{Otro misterioso químico del laboratorio de los Seguidores.}
{37100}{}{Holodisco de la biblioteca}
{37101}{}{La profesora de Casa Nueva te entregó este holodisco, para grabar los libros digitales de la Hermandad.}
{37200}{}{Sustancia Blanca}
{37201}{}{Es una sustancia cristalina e inodora, su composición es desconocida.}
{37300}{}{Notas de laboratorio}
{37301}{}{Esta holocinta contiene los últimos informes del Laboratorio Hidropónico Greenway.}
{37400}{}{Insecticida}
{37401}{}{Un contenedor con una mezcla de sustancias tóxicas.}
{37500}{}{Mapa de los Saqueadores}
{37501}{}{Un mapa que detalla áreas bajo control de los saqueadores, incluyendo su base principal en las montañas del este.}
{37600}{}{Reliquia Valiosa}
{37601}{}{Un antiguo dispositivo tecnológico con un propósito desconocido, con un medidor de dial y un par de interruptores.}
{37700}{}{Mutágeno}
{37701}{}{Un rociador lleno de un mutágeno, funciona a base de un primitivo mecanismo de resorte.}
{37800}{}{Kit de química}
{37801}{}{Una gran colección de herramientas químicas y sustancias de varios tipos.}
{37900}{}{Casco de servoarmadura}
{37901}{}{Es un casco de una servoarmadura T-51b.}
{38000}{}{Procesador de servoarmadura}
{38001}{}{Este es un procesador para una servoarmadura T-51b.}
{38100}{}{Caja con chapas}
{38101}{}{Una caja llena hasta reventar de chapas de Nuka-Cola. Para un ciudadano común, es una fortuna.}
{38200}{}{Figurita de madera}
{38201}{}{Una figura de un animal extinto, hecha a partir de madera.}
{38300}{}{!Do Not Use}
{38301}{}{Original: Shiloh.}
{38400}{}{Pistola pérdida}
{38401}{}{Esta es la pistola que desapareció del almacén de los rangers.}
{38500}{}{Gafas de Bemis}
{38501}{}{Estas son las gafas de lectura de Henry Beamis. Son enormes.}
{38600}{}{Neurochip}
{38601}{}{Un implante que anteriormente estaba en el cadáver de un Hojalatero.}
{38700}{}{Placa de Ranger}
{38701}{}{Una placa que terminó en las manos equivocadas.}
{38800}{}{Paquete sospechoso}
{38801}{}{Un paquete de químicos para un traficante en Fénix.}
{38900}{}{Paquete dudoso}
{38901}{}{Un paquete de químicos para los Escudos Azules.}
{39000}{}{!Do Not Use}
{39001}{}{Original: Sun Scorcher.}
{39100}{}{Contraseñas de Faber}
{39101}{}{Aquí están escritas varias contraseñas. Puede que sean útiles en la colonia de Flagstaff.}
{39200}{}{Contrato de Eugene}
{39201}{}{Un contrato entre los Rangers y Eugene Simon para su alistamiento.}
{39300}{}{Carta de Hiram}
{39301}{}{Una carta de recomendación escrita por Hiram de Flagstaff, para Aaron, el Señor de Fénix, y la Iglesia del Fuego Santo.}
{39400}{}{Informe del Asesor}
{39401}{}{Este holodisco fue entregado por Ulysses Grant. Debe ser entregado a la base militar en Puerto Peñasco.}
{39500}{}{Cartas pérdidas}
{39501}{}{Varias cartas pérdidas para ciudadanos de Fénix.}
{39600}{}{Cabeza de Ben}
{39601}{}{La cabeza cercenada del líder de los Escudos Azules.}
{39700}{}{Cabeza de Hernando}
{39701}{}{La cabeza cercenada de uno de los jefes de Los Panchos.}
{39800}{}{Cabeza de Chucho}
{39801}{}{Otra cabeza cercenada de uno de los jefes de Los Panchos.}
{39900}{}{Cabeza de Eydie}
{39901}{}{Esta es otra cabeza cercenada de uno de los jefes de Los Panchos.}
{40000}{}{La cabeza de Gil McCord}
{40001}{}{La cabeza cercenada del legendario pistolero del Gremio de Mercenarios}
{40100}{}{Pieza de una lanza}
{40101}{}{Un fragmento de una lanza, tomada del caparazón de un escorpión. Puede servir de evidencia para demostrar que el monstruo ha muerto.}
{40200}{}{Hongo Brillante}
{40201}{}{Un hongo inusual que crece en los charcos tóxicos, no es comestible para los humanos.}
{40300}{}{Dispositivo de Alta Tecnología}
{40301}{}{El Cartel Carroñero estará interesado en esta pieza de tecnología antigua.}
{40400}{}{Manivela}
{40401}{}{Una oxidada manivela que todavía funciona. Ya no las hacen como antes.}
{40500}{}{Amplificador de señal}
{40501}{}{Un amplificador de potencia de vibración eléctrica para un transmisor de radio, que utiliza la última generación de tecnología de tubos de vacío.}
{40600}{}{Máquina soldadora}
{40601}{}{Una máquina soldadora, es vieja, pero funciona.}
{40700}{}{Actualización para ZAX}
{40701}{}{Este holodisco contiene la actualización 1.1 para ZAX.}
{40800}{}{!Do Not Use}
{40801}{}{Original: First aid kit for a military paramedic.}
{40900}{}{!Do Not Use}
{40901}{}{Original: Paramedic Bag.}
{41000}{}{Unidad de almacenamiento de energía}
{41001}{}{Una unidad de almacenamiento de energía muy grande. Esta célula de fusión nuclear fue diseñada para generadores de Wattz Electronics.}
{41100}{}{Fusibles}
{41101}{}{Fusibles de una bomba nuclear. Sin ellos, es imposible que se active el detonador.}
{41200}{}{Tarjeta de acceso de la bodega}
{41201}{}{Una tarjeta de acceso para algunas habitaciones del Destructor de la Hermandad.}
{41300}{}{Tarjeta de acceso de los torpedos}
{41301}{}{Una tarjeta de acceso para la computadora de control de los torpedos.}
{41400}{}{Llave de la suite de lujo}
{41401}{}{La llave para la suite lujosa para el casino Atomic Rush.}
{41500}{}{Códigos de la estación de radio}
{41501}{}{Son los códigos de acceso para la estación de radio en la Catedral.}
{41600}{}{Tarjeta de acceso}
{41601}{}{Una tarjeta de acceso para el panel de control de la Presa.}
{41700}{}{Tarjeta de acceso para la computadora ZAX}
{41701}{}{Una tarjeta de acceso de alta seguridad, permite utilizar la terminal de emergencia para la computadora ZAX.}
{41800}{}{Tarjeta de acceso}
{41801}{}{Una tarjeta de acceso para el Refugio 25, con acceso limitado.}
{41900}{}{Tarjeta de acceso}
{41901}{}{Una tarjeta de acceso para el Refugio 25, permite la entrada a cualquier lugar del Refugio.}
{42000}{}{Tarjeta de acceso}
{42001}{}{Una tarjeta de acceso para el Refugio 27.}
{42100}{}{Llave de Aaron}
{42101}{}{Esta llave una vez perteneció a Aaron, el Señor de Fénix, parece que abre una cerradura especial.}
{42200}{}{Llave desgastada}
{42201}{}{Una llave para la habitación de un hotel, está vieja y desgastada.}
{42300}{}{Llaves de la guarida Chacal}
{42301}{}{Un conjunto de llaves sucias que abren las puertas de la guarida de la tribu Chacal.}
{42400}{}{Llave irradiada}
{42401}{}{Una pequeña llave encontrada en Quartzsite, probablemente sea de una cerradura pequeña.}
{42500}{}{Llave oxidada}
{42501}{}{Una llave que abre la puerta del almacén en las minas de Flagstaff.}
{42600}{}{Dientes del Rey Rata}
{42601}{}{Los incisivos de una rata mutante gigante de las minas de Flagstaff, son una prueba de que está muerta.}
{42700}{}{Llave del granero}
{42701}{}{Una llave que abre las puertas del granero en la plantación de la Villa.}
{42800}{}{Reliquias Familiares}
{42801}{}{Un mono azul, una computadora de muñeca y una cantimplora. Ha pasado de generación en generación, ahora esto te pertenece.}
{42900}{}{Cráneo de Monstruo}
{42901}{}{La cabeza de un monstruo, todavía inspira terror, aún en la muerte}
{43000}{}{Llave de la Moto}
{43001}{}{Una llave de acceso a la computadora de la motocicleta. Sin ella, piratear el sistema de arranque de la moto será difícil.}
{43100}{}{Collar}
{43101}{}{Un collar de balas atadas con un cordón viejo. Su anterior dueño no parecía entender su verdadero uso.}
{43200}{}{Foco de Halógeno}
{43201}{}{Un foco de 65-watts bien preservado, solían usarse en los faros de los coches.}
{43300}{}{Gafas chingonas}
{43301}{}{Un par de gafas de sol a la última moda. Efectos: +1 CA mientras estén equipados.}
{43400}{}{Reliquia Antigua}
{43401}{}{Un mecanismo de una caja musical. Dale cuerda para escuchar una antigua melodía, olvidada por el tiempo.}
{43500}{}{Reliquia Antigua}
{43501}{}{Un viejo reloj atómico, funciona cada cinco minutos, pero funciona.}
{43600}{}{Reliquia Antigua}
{43601}{}{Una especie de bola con granos blancos de arena dentro. Puede que sea la 'nieve' de la que escuchaste en tu niñez.}
{43700}{}{Reliquia Antigua}
{43701}{}{Una medalla otorgada por Valor durante la Batalla de Anchorage, año 2077. Un importante suceso histórico.}
{43800}{}{Reliquia Antigua}
{43801}{}{Una placa de policía auténtica, desgastada por su gran, gran edad.}
{43900}{}{Reliquia Antigua}
{43901}{}{Un libro sagrado del Santuario del Brahmán Divino, la tribu seguramente desconoce su propósito.}
{44000}{}{Reliquia Antigua}
{44001}{}{Una foto de una nube atómica sobre unas ruinas humeantes. La parte de atrás dice: "Mexicali, 2077."}
{44100}{}{Reliquia Antigua}
{44101}{}{Una cantimplora para almacenar agua u otro tipo de líquido. Tiene marcado el número 24.}
{44200}{}{Reliquia Antigua}
{44201}{}{Una bandera de Arizona, polvorosa, pero bien conservada.}
{44300}{}{Reliquia Antigua}
{44301}{}{Un holodisco con un videojuego para computadoras avanzadas.}
{44400}{}{Mapa de Fénix}
{44401}{}{Un mapa con información de la ciudad y sus alrededores. Un objeto valioso para un chatarrero novato.}
{44500}{}{Chapa de identificación del Pescador}
{44501}{}{Esta chapa de identificación tiene grabada el nombre del pescador Ferrino.}
{44600}{}{Tarjeta de acceso}
{44601}{}{Una tarjeta de acceso de seguridad para las puertas de la plataforma de Petro-Chico.}
{44700}{}{Fragmento del Mapa}
{44701}{}{Una pieza para algún tipo de mapa.}
{44800}{}{Cuerdas de guitarra}
{44801}{}{Cuerdas para una guitarra de cinco cuerdas.}
{44900}{}{Pipa de cobre}
{44901}{}{Un antiguo instrumento musical.}
{45000}{}{Cuerpo de Donovan}
{45001}{}{Este es el cuerpo de Donovan. Donovan está muerto.}
{45100}{}{Placa Antigua}
{45101}{}{Esta es una placa de la patrulla fronteriza. Está cubierta de una capa obscenamente gruesa de ceniza y tierra.}
{45200}{}{Placa Antigua}
{45201}{}{Esta es una placa de la patrulla fronteriza. El sol la hace brillar con elegancia, como una vez lo hizo en el Viejo Mundo.}
{45300}{}{Cristal Wattz 3000}
{45301}{}{Un cristal artificial de alta precisión, para una pistola láser de grado militar.}
{45400}{}{Pistola láser}
{45401}{}{Una pistola láser Wattz 1000, modelo civil mejorado. Está al nivel de los modelos militares, pues usa un cristal de alta precisión. Min FU: 3.}
{45500}{}{Maletera}
{45501}{}{Una vieja caja atada a la motocicleta. Permite almacenar y transportar objetos pequeños.}
{45600}{}{Bolsas de la moto}
{45601}{}{Resistentes bolsas hechas de cuero. Fueron hechas a medida para tu motocicleta.}
{45700}{}{Tarjeta de acceso para la Presa Bonita}
{45701}{}{Tarjeta de acceso para la estación hidroeléctrica de Bonita. Nivel de acceso: restringido.}
{45800}{}{Tarjeta de acceso para la Presa Bonita}
{45801}{}{Tarjeta de acceso para la estación hidroeléctrica de Bonita. Nivel de acceso: alto.}
{45900}{}{Mesa de café}
{45901}{}{Esta mesa está llena de basura.}
{46000}{}{Generador de Pulso PEM}
{46001}{}{Una herramienta de pulsos PEM que deshabilita el equipamiento electrónico.}
{46100}{}{Tableta con notas}
{46101}{}{Una tableta con notas del viejo Isaac. Se describen los pasos necesarios para reparar la presa.}
{46200}{}{Holodisco de Gustavo}
{46201}{}{El Señor Gustavo te pidió que entregues en secreto este holodisco al alcalde del Pueblo Viejo.}
{46300}{}{Tubo catódico}
{46301}{}{Un tubo de vacío de alta potencia. La mayoría de estos tubos se han quemado hace mucho tiempo, éste todavía funciona, lo que lo hace raro, y muy caro.}
{46400}{}{Módulo del monorriel}
{46401}{}{Para que el monorriel funcione correctamente, se necesita éste módulo. Pero no funciona y necesita ser reparado.}
{46500}{}{Módulo del monorriel}
{46501}{}{Para que el monorriel funcione correctamente, se necesita éste módulo. Ya está arreglado y debería volver a su lugar.}
{46600}{}{Códigos de la estación fronteriza}
{46601}{}{Estos son los códigos y comandos para el control de los robots fronterizos en la estación de San Isidro, se activan a través de la radio.}
{46700}{}{!Do not use}
{46701}{}{Originally - Jesse's Container. Used by the engine in the barter system.}
{46800}{}{Emisor Holográfico}
{46801}{}{Una parte para emitir imágenes holográficas.}
{46900}{}{Chip de agua}
{46901}{}{Un chip para un sistema de purificación de agua, se suelen encontrar en los sistemas de Vault-Tec.}
{47000}{}{Placa de Circuito Impreso}
{47001}{}{Una parte para una máquina de imprenta.}
{47100}{}{Placa de Diágnosticos}
{47101}{}{Una parte para un Auto-Doc, provee un rápido y preciso análisis médico.}
{47200}{}{Inyector de combustible}
{47201}{}{Este chip controla el flujo de energía que entra en el motor eléctrico del vehículo. Muchos conductores queman este chip debido a acelerones frecuentes.}
{47300}{}{Planos de vertibird}
{47301}{}{Son planos para algún tipo de equipamiento militar que desconoces. Posee una acotación: "Módelo experimental."}
{47400}{}{Máquina expendedora de baterías}
{47401}{}{Una máquina expendedora que vende baterías nucleares. Posee una selección muy limitada.}
{47500}{}{Holocinta de Hermosillo}
{47501}{}{Información recolectada por los espías del Ejército Mexicano, y robada por ti. Algunas personas del yermo pagarán un buen dinero por esto.}
{47600}{}{Libro sobre San Diego}
{47601}{}{Un libro de memorias sobre San Diego, publicado justo antes de la Gran Guerra. Puede que seas la primera persona que lo lee.}
{47700}{}{Máquina expendedora de medicinas}
{47701}{}{Una máquina expendedora que vende medicinas y suministros médicos. Posee una selección muy limitada.}
{47800}{}{Máquina expendedora de alcohol}
{47801}{}{Una máquina expendedora que contiene varios tragos. Posee una selección muy limitada.}
{47900}{}{Máquina expendedora de aceite}
{47901}{}{Una máquina expendedora para vender aceite. No le queda demasiado.}
{48000}{}{Gel biomédico}
{48001}{}{Un frasco herméticamente sellado de cristal inquebrantable. La etiqueta dice: "Gel biomédico"}
{48100}{}{Microchips}
{48101}{}{Microchips para equipamiento aéreo. Para la mayoría de personas, es chatarra inútil, pero para algunos, son invaluables.}
{48200}{}{Códigos de seguridad de la isla Coronado}
{48201}{}{Códigos de seguridad para la Base Naval Coronado. Se utilizan a través de la comunicación por radio. Es esencial para acceder a ella.}
{48300}{}{Lanza de electrochoque reforzada}
{48301}{}{Un arma casera que emite una corriente eléctrica al entrar en contacto con la víctima. Min FU: 3.}
{48400}{}{Taser}
{48401}{}{Un taser policial. Electrocuta al objetivo. Min FU: 4.}
{48500}{}{Programación de Administrador}
{48501}{}{Este holodisco contiene un módulo de programación para un Señor Mañoso, lo que permite al robot ejecutar las funciones del administrador de un hotel.}
{48600}{}{"Deep Throat"}
{48601}{}{Una clásica película de culto. No vas a verla.}
{48700}{}{Parte de un procesador de alimentos}
{48701}{}{Una parte de un procesador de alimentos. Tiene esta nota: "Propiedad privada. Si se encuentra, devolver a Edward en San Isidro."}
{48800}{}{Proyectil de Howitzer}
{48801}{}{Un proyectil de 75mm. de un cañón Howitzer. La mayoría del revestimiento esta corroído. En teoría, aún debería poder dispararse.}
{48900}{}{Partes de Howitzer}
{48901}{}{Estas partes pueden ser usadas para reparar un Howitzer dañado.}
{49000}{}{Tarjeta de acceso de la isla Coronado}
{49001}{}{Tarjeta de acceso militar para la Base Naval Coronado. Color: azul.}
{49100}{}{Tarjeta de acceso de la isla Coronado}
{49101}{}{Tarjeta de acceso militar para la Base Naval Coronado. Color: rojo.}
{49200}{}{Colgante de Bodas}
{49201}{}{Un colgante, que marca el lazo marital entre dos personas. Lo encontraste en las plantaciones de Casa Nueva.}
{49300}{}{Cuchillo de carnicero}
{49301}{}{Un cuchillo, hecho para cortar carne.}
{49400}{}{}
{49401}{}{}
{49500}{}{Escopeta Rota}
{49501}{}{Una escopeta Winchester Widowmaker con dos cañones y calibre 12. De cañón corto, con asa en caoba. No dispara.}
{49600}{}{Pistola casera}
{49601}{}{Una pistola casera, de disparo único.}
{49700}{}{Pistola de bengalas (Modificada)}
{49701}{}{Una pistola originalmente diseñada para disparar bengalas. El cañón fue modificado para que dispare cartuchos de escopeta. Necesitas más fuerza, pero es más letal. Min. FU: 5}
{49800}{}{Emisor Láser (Mejorado)}
{49801}{}{Un arma casera hecha a partir de partes de un robot industrial. Puede emitir un láser de baja potencia a corta distancia. Min FU: 3}
{49900}{}{¡Viva, Villa!}
{49901}{}{Una vieja historieta patriótica. Es gracioso que su contenido no haya perdido nada de su relevancia.}
{50000}{}{}
{50001}{}{}
{50100}{}{}
{50101}{}{}
{50200}{}{}
{50201}{}{}
{50300}{}{}
{50301}{}{}
{50400}{}{}
{50401}{}{}
{50500}{}{}
{50501}{}{}
{50600}{}{}
{50601}{}{}
{50700}{}{}
{50701}{}{}
{50800}{}{}
{50801}{}{}
{50900}{}{}
{50901}{}{}
{51000}{}{}
{51001}{}{}
{51100}{}{}
{51101}{}{}
{51200}{}{}
{51201}{}{}
{51300}{}{}
{51301}{}{}
{51400}{}{}
{51401}{}{}
{51500}{}{}
{51501}{}{}
{51600}{}{Amplificador de Pip-Boy}
{51601}{}{Un amplificador diseñado para un rápido análisis del ambiente. Diseñado por los escribas de la Hermandad.}
{51700}{}{}
{51701}{}{}
{51800}{}{}
{51801}{}{}
{51900}{}{}
{51901}{}{}
{52000}{}{}
{52001}{}{}
{52100}{}{}
{52101}{}{}
{52200}{}{}
{52201}{}{}
{52300}{}{Guía de Supervivencia}
{52301}{}{Una Guía de Supervivencia para la Guerra Nuclear. Preparado por Vault-Tec para los moradores de los Refugios.}
{52400}{}{}
{52401}{}{}
{52500}{}{}
{52501}{}{}
{52600}{}{}
{52601}{}{}
{52700}{}{}
{52701}{}{}
{52800}{}{}
{52801}{}{}
{52900}{}{}
{52901}{}{}
