################################################## ########
#
# DESCRIPTIONS OF QUESTS IN PIP-BOY
# (start each new section with 100 and its multiples)
#
################################################## ########

#---------------------------------------------------------------- --------
#Villa
#---------------------------------------------------------------- --------

{100}{}{Investiga el pueblo cercano para saber más de los saqueadores}  
{101}{}{Rescata a los demás aldeanos en Flagstaff}  
{102}{}{Libera a tus paisanos en Two-Sun}  
{103}{}{Habla con el Consejo de la Villa}  
{104}{}{Recupera las reliquias familiares del sótano}  
{105}{}{Presta asistencia médica al campesino herido}  
{106}{}{Erradica a la plaga de ratas}  
{107}{}{Localiza y rescata al niño perdido}  
{108}{}{Ahuyenta a los merodeadores del granero}  
{109}{}{Repara la estación meteorológica}  
{110}{}{Elimina a los cultistas en Fénix}  
{111}{}{Encuentra a Chris - no debe estar lejos}  
{112}{}{Haz explotar la mina de Flagstaff como ordenó el Consejo}  
{113}{}{Destruye la máquina en Ciudad Garaje tal como lo decidió el Consejo}  
{114}{}{Encuentra un aliado para la Villa como recomendó el Consejo}  

#---------------------------------------------------------------- --------
# Flagstaff
#---------------------------------------------------------------- --------

{200}{}{Localiza a los habitantes de la Villa dentro del corral de la prisión}  
{201}{}{Libera a tus familiares de la prisión sea como sea}  
{202}{}{Rescata a tus paisanos del interior de la mina}  
{203}{}{Repara la máquina perforadora de la mina}  
{204}{}{Elimina al Rey Rata de la mina}  
{205}{}{Averigua quién está atacando a las patrullas en el área abandonada}  
{206}{}{Entrégale su almuerzo al administrador de la mina}  
{207}{}{Recauda las cien chapas que Davis el Mercenario le debe al bar}  
{208}{}{Pon fin al hereje en nombre del Fuego Santo}  
{209}{}{Ayuda al niño irradiado}  
{210}{}{Ahuyenta a los invasores de la granja de Randy}  
{211}{}{Devuélvele sus pertenencias a la Señorita Brandley}  
{212}{}{Saca a Látigo de su posición de capataz}  
{213}{}{Averigua qué ocurre en el Campamento Winon}  

#---------------------------------------------------------------- --------
# GarageCity
#---------------------------------------------------------------- --------

{300}{}{Pon fin a la pelea en el dormitorio}  
{301}{}{Consigue una parte de la fábrica para el Sr. Kogan}  
{302}{}{Ve al trato con las caravanas}  
{303}{}{Obtén los datos de la computadora del garaje para Lucas}  
{304}{}{Ve al trato con las caravanas}  
{305}{}{Ayuda a capturar a los brahmanes}  
{306}{}{Restablece la ruta comercial con San Brahmán}  
{307}{}{Establece una ruta comercial hacia el territorio de los Rangers}  
{308}{}{Arregla un trato para traer alcohol desde Flagstaff}  
{309}{}{Detén la fabricación de chapas falsas}  
{310}{}{Encuentra y devuelve la máquina soldadora a Frank}  
{311}{}{Encuentra la guarida Chacal para el portero}  

#---------------------------------------------------------------- --------
# SanBrahmin
#---------------------------------------------------------------- --------

{400}{}{Ayuda al jefe a formar una alianza}  
{401}{}{Establece una alianza con la tribu junto a los misionarios}  
{402}{}{Expulsa a los misionarios de San Brahmán con la ayuda del ranger}  
{403}{}{Destruye la producción de tequila en Fénix}  
{404}{}{Limpia el corral de excremento de brahmán}  
{405}{}{Descubre el secreto de la Ciudad Enterrada}  
{406}{}{Extermina a los escorpiones del oasis}  
{407}{}{Sirve de escolta para la caravana en camino a Fénix}  
{408}{}{}  
{409}{}{}  

#---------------------------------------------------------------- --------  
# Two-Sun  
#---------------------------------------------------------------- --------  

{500}{}{Desactiva el campo de fuerza}  
{501}{}{Encuentra a tu padre en la Zona Prohibida}  
{502}{}{Libera a los aldeanos de la Villa en la Zona Prohibida}  
{503}{}{Convence o elimina a Carlos a petición de tu Padre}  
{504}{}{Desactiva el sistema de seguridad de la Zona Prohibida para los Hojalateros}  
{505}{}{Identifica y detén a los asaltantes de la caravana}  
{506}{}{Encuentra al Hojalatero desaparecido en Casa Grande}  
{507}{}{Descubre el destino de la familia de Cody en Casa Grande}  
{508}{}{Entrégale una batería nuclear al campesino}  
{509}{}{}  

#---------------------------------------------------------------- --------  
# Puerto Penasco  
#---------------------------------------------------------------- --------  

{600}{}{Lleva el holodisco de Ulysses Grant a Puerto Peñasco}  
{601}{}{Encuentra la patrulla pérdida de la Hermandad dentro del Infierno}  
{602}{}{Ayuda al Paladín Bell con su problema mental}  
{603}{}{Explora la región sureña para la Hermandad}  
{604}{}{Elimina a los Rangers}  
{605}{}{Únete al asalto contra los campamentos de los bandidos}  
{606}{}{Explora alrededor de San Felipe}  
{607}{}{}  
{608}{}{}  
{609}{}{}  

#---------------------------------------------------------------- --------  
# Rangers  
#---------------------------------------------------------------- --------  

{700}{}{Repara el tanque de agua de la granja}  
{701}{}{Descubre el código de la radio de los Rangers para el espía}  
{702}{}{Arregla el equipo de la central eléctrica}  
{703}{}{Trae al joven mecánico a la central eléctrica desde Ciudad Garaje}  
{704}{}{Amplía el alcance de emisión de la emisora}  
{705}{}{Obtén el informe del ranger en San Brahmán}
{706}{}{Escolta a la familia de marginados hacia la barcaza}  
{707}{}{Encuentra a la patrulla en el desierto del norte}  
{708}{}{Investiga qué ocurrió con los habitantes de Quartz}  
{709}{}{Registra los datos cartográficos en Quartz}  
{710}{}{Investiga qué le pasó a los refugiados de Ciudad Garaje}  
{711}{}{Ayuda al Cadete Presley}  
{712}{}{Identifica la causa de la enfermedad en el Acueducto}  
{713}{}{Rastrea y caza al escorpión legendario}  
{714}{}{Encuentra el equipamiento perdido}  
{715}{}{Ayuda a los rebeles en Fénix}  
{716}{}{Encuentra a los habitantes desaparecidos del Acueducto}  
{717}{}{Explora Puerto Peñasco para los Rangers}  
{718}{}{}  
{719}{}{}  

#---------------------------------------------------------------- --------
#Phoenix
#---------------------------------------------------------------- --------

{800}{}{Averigua sobre los esclavos de la Villa en Fénix}  
{801}{}{Encuentra al Tío Miguel en Fénix}  
{802}{}{Entrega las cabezas de Los Panchos}  
{803}{}{Mata al legendario pistolero, Gil McCord}  
{804}{}{Investiga el ataque a los monjes}  
{805}{}{Infíltrate entre los rebeldes}  
{806}{}{Ayuda a George Crook en San Brahmán}  
{807}{}{Elimina a George}  
{808}{}{Localiza al agente del Partido de la Liberación entre las ruinas}  
{809}{}{Sabotea la Catedral a petición del Partido de la Liberación}  
{810}{}{Recauda una gran deuda para el casino}  
{811}{}{Recupera las cartas robadas para el Sonora Express}  
{812}{}{Ayuda a la banda de los Cardenales Rojos con sus problemas}  
{813}{}{Investiga el accidente de la central nuclear}  
{814}{}{Ayuda a Iron Mike a buscar justicia}  
{815}{}{Apoya a los habitantes de los barrios bajos con sus problemas}  
{816}{}{}  
{817}{}{}  
{818}{}{}  
{819}{}{}  

#---------------------------------------------------------------- --------  
# Fishing Village (Oil Platform)  
#---------------------------------------------------------------- --------  

{900}{}{Detén el derrame de petróleo de la plataforma}  
{901}{}{Trata a los pacientes envenenados con petróleo}  
{902}{}{Encuentra el collar del padre de Selma}  
{903}{}{Entrégale el contador geiger al cantinero}  
{904}{}{Ayuda a Ruiz a encontrar el tesoro}  
{905}{}{Atrapa a la criatura que roba las redes de pesca}  
{906}{}{Investiga el asesinato misterioso en la costa}
{907}{}{}
{908}{}{}
{909}{}{}

#---------------------------------------------------------------- --------  
# Casa Grande  
#---------------------------------------------------------------- --------  

{1000}{}{Ayuda a Steve a reclamar la casa de baños}  
{1001}{}{Recauda el pago de Sullivan por el mantenimiento de la bomba de agua}  
{1002}{}{Lidia con el problema en el bar abandonado}  
{1003}{}{Enfréntate a los bandidos en Casa Grande}  
{1004}{}{Rescata a la ciudadana en la estación de tren}  
{1005}{}{Destruye el tanque de combustible de los Escudos Azules}  
{1006}{}{Cobra el precio de la cabeza del líder de los Escudos Azules para el Alcalde}  
{1007}{}{Pasa a saludar en el rancho Domínguez en Hermosillo}  
{1008}{}{}  
{1009}{}{}  

#---------------------------------------------------------------- --------  
# Hermosillo  
#---------------------------------------------------------------- --------  

{1100}{}{Regrésale la radio a los Domínguez}  
{1101}{}{Lleva al prisionero a Puerto Peñasco}  

#---------------------------------------------------------------- --------  
# San Felipe (Old Lighthouse)  
#---------------------------------------------------------------- --------  

{1200}{}{Repara el faro antiguo}
{1201}{}{Investiga a los monstruos en el cementerio de naves }
{1202}{}{Elimina el nido de las sanguijuelas}
{1203}{}{Rescata a  Gloria}
{1204}{}{Explora el área alrededor de San Felipe}
{1205}{}{Encuentra una fuente de agua limpia}
{1206}{}{Resiste el asalto de los salvajes}
{1207}{}{Convence al capitán de abandonar la bahía}

#---------------------------------------------------------------- --------  
# Inferno  
#---------------------------------------------------------------- --------  

{1300}{}{Localiza al escuadrón del Paladín Barkley}  
{1301}{}{Ayuda a Levi a crear un mutágeno para salvar a su rebaño}  
{1302}{}{Escolta a Diana a Casa Nueva}  
{1303}{}{}  
{1304}{}{}  
{1305}{}{}  
{1306}{}{}  
{1307}{}{}  
{1308}{}{}  
{1309}{}{}  

#---------------------------------------------------------------- --------  
# Casa Nueva  
#---------------------------------------------------------------- --------  

{1400}{}{}  
{1401}{}{Encuentra al campesino desaparecido}  
{1402}{}{Ayuda a los Seguidores para poner fin a la epidemia}  
{1403}{}{Investiga las desapariciones en la planta de concreto}  
{1404}{}{Cura a la mascota de Chip a pesar de la oposición local}  
{1405}{}{Entrega libros a la escuela local}  
{1406}{}{}  
{1407}{}{}  
{1408}{}{}  
{1409}{}{}  

#---------------------------------------------------------------- --------
# ! Free slot
#---------------------------------------------------------------- --------

{1500}{}{}

#---------------------------------------------------------------- --------
# Old Motel
#---------------------------------------------------------------- --------

{1600}{}{}

#---------------------------------------------------------------- --------
# !DLC Dayglow / San Diego
#---------------------------------------------------------------- --------

{1700}{}{Explora la misteriosa ciudad de los muertos}  
{1701}{}{Encuentra el Refugio 24}  
{1702}{}{Desactiva el robot militar en las ruinas de Tijuana}  
{1703}{}{Encárgate de Gonzo}  
{1704}{}{Repara la central eléctrica de la ciudad}  
{1705}{}{Restablece la comunicación por radio de la ciudad}  
{1706}{}{Entrégale el holodisco al Pueblo Viejo}  
{1707}{}{Recibe a la caravana del Eje}  
{1708}{}{Busca los tesoros de la Isla Coronado}  
{1709}{}{Repara el monorriel de la ciudad}  
{1710}{}{Organiza espectáculos de mariachis}  
{1711}{}{Encuentra a Donovan}  
{1712}{}{Consíguele los chips de la fábrica a los carroñeros}  
{1713}{}{Ayuda a la Abuela Judy a encontrar a su esposo Rupert}  
{1714}{}{Trabaja para el Sr. De Santi}  
{1715}{}{}  
{1716}{}{Ayuda a los Comerciantes de Ultramar con su contrato de reliquias antiguas}  
{1717}{}{Entrégale licor al Pueblo Viejo}  
{1718}{}{Llévale café a la cafetería de San Isidro}  
{1719}{}{Entrega los almuerzos a los trabajadores de Bonita}  
{1720}{}{Encuentra el nuevo libro de Mortimer}  

#---------------------------------------------------------------- --------
# ! Free slot
#---------------------------------------------------------------- --------

{1800}{}{}

#---------------------------------------------------------------- --------  
# Santa Ana  
#---------------------------------------------------------------- --------  

{1900}{}{Conversa con los aldeanos acerca de la celebración}  
{1901}{}{Recupera la corona ceremonial}  
{1902}{}{Encuentra y rescata a Lucía}  
{1903}{}{Pon fin a los planes de Hilario}  
{1904}{}{Establece una alianza comercial con Casa Nueva}  

#---------------------------------------------------------------- --------  
# ! Free slot  
#---------------------------------------------------------------- --------  

{2000}{}{}  

#---------------------------------------------------------------- --------  
# Jackals  
#---------------------------------------------------------------- --------  

{2100}{}{Rescata al Ranger capturado}  
{2101}{}{Ayuda a la Perra Loca a formar una alianza para lidiar con la hambruna}  
{2102}{}{Apoya a Colmillo Negro con su plan de abandonar el valle para encontrar comida}  
{2103}{}{Extermina a los Chacales}  
{2104}{}{Ataca la madriguera de los Chacales junto a los matones de Ciudad Garaje}  

#---------------------------------------------------------------- --------  
# Car outta Gas Quests  
#---------------------------------------------------------------- --------  

{2200}{}{}  

#---------------------------------------------------------------- --------  
# ! Free slot  
#---------------------------------------------------------------- --------  

{2300}{}{}  

#---------------------------------------------------------------- --------  
# Vault 27  
#---------------------------------------------------------------- --------  

{2400}{}{Encuentra el Refugio 27}  
{2401}{}{Descubre la historia del Refugio 27}  
{2402}{}{Activa el generador de respaldo}  
{2403}{}{Enciende el generador de respaldo y repara la ventilación}  
{2404}{}{Reúnete con el superviviente de la expedición}  
{2405}{}{Lleva a Arthur Carrington a un lugar seguro}  

#---------------------------------------------------------------- --------  
# Brotherhood of Steel Camp  
#---------------------------------------------------------------- --------  

{2500}{}{}  

#---------------------------------------------------------------- --------  
# Raiders (Highwaymen)  
#---------------------------------------------------------------- --------  

{2600}{}{Encárgate del saqueador en la prisión de Casa Grande}  
{2601}{}{Haz una tregua entre los Escudos Azules y los Hojalateros}  
{2602}{}{Establece una tregua entre los Escudos Azules y Casa Grande}  
{2603}{}{Entrégale el paquete sospechoso al camello en Fénix}  
{2604}{}{Prepara a Chuck para la ceremonia de iniciación}  
{2605}{}{}  
{2606}{}{}  
{2607}{}{}  
{2608}{}{}  
{2609}{}{}  

#---------------------------------------------------------------- --------
# Camp Winon
#---------------------------------------------------------------- --------

{4900}{}{}
