#include "..\headers\define.h"
//---------------------

#define NAME                            SCRIPT_NCMer
#define TOWN_REP_VAR                    GVAR_TOWN_REP_CASA_NUEVA // привязка к репутации (-1, если не нужно)

#define NUM_TEAM                        TEAM_CASANUEVA_PEASAN // группа, к которой принадлежит персонаж (-1 если нужно оставить Team, заданный в редакторе)
#define NUM_AI                          AI_PERSON_TOUGH       // AI персонажа (-1 если нужно оставить AI, заданный в редакторе)
#define KILL_SLAVA                      SLAVA_KILL_GOOD       // слава за убийство этого персонажа (SLAVA_KILL_GOOD, SLAVA_KILL_BAD, SLAVA_KILL_NEITRAL, SLAVA_KILL_CHILD)
#define KILL_TOWN_REP                   REP_KILL_CRITICAL     // репутация за убийство этого персонажа (REP_KILL_GOOD, REP_KILL_NEITRAL, REP_KILL_BAD, REP_KILL_CHILD, REP_KILL_CRITICAL)
#define KILL_FRAC_REP                   FRAC_NON              // принадлежность определенной фракции (-1, если не нужно)

#define FLAG_STEAL                      50 // Нижний порог навыка для кражи (для торговцев 200, для животных 300)
#define FLAG_ALCOHOL                    1  // Примет ли алкоголь от ГГ: 0 - принимает, 1 - не принимает
#define FLAG_FOOD                       1  // Примет ли пищу от ГГ: 0 - принимает, 1 - не принимает

//---------------------

procedure start;
procedure map_enter_p_proc;
procedure mer_is_dead;
procedure look_at_p_proc;
procedure description_p_proc;
procedure timed_event_p_proc;
procedure critter_p_proc;
procedure use_obj_on_p_proc;
procedure use_skill_on_p_proc;
procedure pickup_p_proc;
procedure combat_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure talk_p_proc;

procedure Node998;
procedure Node999;
procedure NodeStartDialog;
procedure NodeFstDialog;
procedure NodeFstDialog002;
procedure NodeFstDialog003;
procedure NodeFstDialog004;
procedure NodeFstDialog005;
procedure NodeFstDialog010;
procedure NodeFstDialog011;
procedure NodeFstDialog012;
procedure NodeFstDialog013;
procedure NodeStopDialog101;
procedure NodeStopDialog102;
procedure NodeStopDialog103;
procedure NodeStopDialog104;
procedure NodeStopDialog105;
procedure NodeStopDialog106;
procedure NodeStopDialog107;
procedure NodeSndDialog;
procedure NodeAnswer100;
procedure NodeAnswer101;
procedure NodeAnswer102;
procedure NodeAnswer103;
procedure NodeAnswer104;
procedure NodeAnswer105;
procedure NodeAnswer106;
procedure NodeAnswer107;
procedure NodeAnswer108;
procedure NodeAnswer109;
procedure NodeAnswerPinki;
procedure NodeAnswerPinki001;
procedure NodeAnswerSanta;
procedure NodeAnswerSanta2;
procedure NodeAnswerAkcent;
procedure NodeAnswerAkcent2;
procedure NodeAnswer200;
procedure NodeAnswer201;
procedure NodeAnswer202;

//---------------------

//#define LVAR_Flag_A                     (6) // отвечает за ...

import variable box_stop_use;

//---------------------



procedure start begin
end

procedure map_enter_p_proc begin
   if (is_loading_game == false) then begin
       set_start_home
       if ((global_var(GVAR_GAME_END) != 0) and (getQuest(GVAR_PUERTO_BOS_DESTROY) >= qEnd) and (global_var(GVAR_TWOSUN_STATUS_ZAX) > 0)) then begin
       call mer_is_dead;
       end
   end
end

#define safe_mer_obj                   tile_contains_pid_obj(10093, 0, 248) \

procedure mer_is_dead begin
   variable pistolPID;
   pistolPID := 0;
   rm_timer_event(self_obj);
   set_obj_visibility(self_obj, 1);
   obj_unlock(safe_mer_obj);

   if (item_amnt(safe_mer_obj,PID_W_REVOLVER_OLD) > 0) then begin
      pistolPID := PID_W_REVOLVER_OLD;
   end
   else if (item_amnt(safe_mer_obj,PID_W_REVOLVER_POLICE) > 0) then begin
      pistolPID := PID_W_REVOLVER_POLICE;
   end
   else if (item_amnt(safe_mer_obj,PID_W_REVOLVER_COMBAT) > 0) then begin
      pistolPID := PID_W_REVOLVER_COMBAT;
   end
   else if (item_amnt(safe_mer_obj,PID_W_PISTOL_ZIP) > 0) then begin
      pistolPID := PID_W_PISTOL_ZIP;
   end
   else if (item_amnt(safe_mer_obj,PID_W_PISTOL_22) > 0) then begin
      pistolPID := PID_W_PISTOL_22;
   end
   else if (item_amnt(safe_mer_obj,PID_W_PISTOL_10) > 0) then begin
      pistolPID := PID_W_PISTOL_10;
   end
   else if (item_amnt(safe_mer_obj,PID_W_PISTOL_50) > 0) then begin
      pistolPID := PID_W_PISTOL_50;
   end

   if (pistolPID>0) then begin
      create_object_sid(33556405,self_tile,self_elevation,-1);
      create_object_sid(pistolPID,tile_num_in_direction(self_tile,4,1),self_elevation,-1);
      item_remove(safe_mer_obj,pistolPID,1)
   end
   else begin
      create_object_sid(33556404,10097,self_elevation,-1);
   end

   set_global_var(GVAR_NUEVA_STATUS_MER,-999);
   destroy_object(self_obj);
end

procedure look_at_p_proc begin
   lookProcMsg
end

procedure description_p_proc begin
   dsrptProcMsg
end

procedure timed_event_p_proc begin
   // Таймер за номером 1 зарезервирован под перемещение персонажа по локации
   // Таймер за номером 2 зарезервирован под всплывающие реплики
   if (fixed_param == 1) then begin
       timer_move_to_home
   end
   if (fixed_param == 2) then begin
       //timer_float_reply(120,121)
   end
end

procedure critter_p_proc begin
   if town_rep_is_idolized then begin
   end
   else begin
   set_using_stop // привязка хозяина и объекта (удалить, если не нужно)
   end
   set_critter_options(1,0) //условие нападения (0 личная вражда, 1 вражда клановая, 2 всегда), разворот к ГГ
end

procedure use_skill_on_p_proc begin
   skillUseSteal
   skillUseFAid
end

procedure pickup_p_proc begin
   pickupProcCritter
end

procedure use_obj_on_p_proc begin
   UsedItemToCrit_Proc
end

procedure combat_p_proc begin
   effectAttak(0,0,1,1,1) //отравление min, облучение min, травма ног %, травма рук %, травма глаз %
end

procedure damage_p_proc begin
   set_damage_dude
end

procedure destroy_p_proc begin
   set_global_var(GVAR_NUEVA_STATUS_MER,-1);
   kill_critter_opt
end

procedure talk_p_proc begin
   if (bitDialog(bit_2) != 0) then begin
   floater(self_obj,105,COLOR_MSG_RED);
   end
   else if (game_time_hour < 0600) then begin
   floater(self_obj,104,COLOR_MSG_RED);
   end
   else begin
   setReaction(1) // Отношение к ГГ (1 - персонаж положительный, -1 отрицательный, 0 нейтральный)
   fracReaction(GVAR_TITUL_BOS,50) // Поправка к отношению за принадлежность к фракциям
   fracReaction(GVAR_TITUL_WARRIOR_ROAD,-35) // Поправка к отношению за принадлежность к фракциям
   fracReaction(GVAR_TITUL_DUDE_IS_SLAVE,20) // Поправка к отношению за принадлежность к фракциям
   dialog_proc(102,0,NodeStartDialog,-1,-1)
   end
end

procedure Node998 begin
   set_enemy_dude;
end

procedure Node999 begin
   if (map_var(MVAR_NUEVA_MER_DIALOG) == 0) then begin
   inc_map_var(MVAR_NUEVA_MER_DIALOG);
   end
end

procedure NodeStartDialog begin
   if (bitDialog(bit_1) == 0) then begin
   call NodeFstDialog;
   end
   else if ((bitDialog(bit_2) == 0) and (getQuest(GVAR_PUERTO_BOS_DESTROY)>=qEnd)) then begin
   call NodeStopDialog101;
   end
   else begin
   call NodeSndDialog;
   end
end

//--- ПЕРВЫЙ ДИАЛОГ

procedure NodeFstDialog begin
   bitDialogExp(bit_1,0)
   if (global_var(GVAR_TITUL_REBIRTH)>0) then begin
   Reply(2200)
   end
   else begin
   Reply(200)
   end
   NAnswer(201,4,NodeFstDialog002)
   BAnswer(203,4,NodeFstDialog004)
   GAnswer(mstr(204)+dude_name+mstr(205),4,NodeFstDialog003)
   GAnswer(216,-3,NodeFstDialog005)
end

procedure NodeFstDialog002 begin
   Reply(202)
   call NodeFstDialog010;
end

procedure NodeFstDialog003 begin
   variable selfname := false;
   if (dude_name == self_name) then begin
   selfname := true;
   end
   if (dude_name == mstr(110)) then begin
   selfname := true;
   end
   if (dude_name == mstr(111)) then begin
   selfname := true;
   end
   if (dude_name == mstr(112)) then begin
   selfname := true;
   end
   if (dude_name == mstr(113)) then begin
   selfname := true;
   end

   set_REP(1)
   setBonusReaction(10)

   if (selfname == true) then begin
   set_REP(1)
   setBonusReaction(10)
   Reply(207)
   end
   else begin
   Reply(206)
   end
   call NodeFstDialog010;
end

procedure NodeFstDialog004 begin
   set_REP(-1)
   setBonusReaction(-10)
   Reply(208)
   call NodeFstDialog010;
end

procedure NodeFstDialog005 begin
   Reply(217)
   NAnswer(218,4,NodeFstDialog011)
end

procedure NodeFstDialog010 begin
   if (global_var(GVAR_TITUL_BOS)>0) then begin
   GAnswer(211,4,NodeFstDialog013)
   end
   else if (town_known(AREA_PUERTO_STEEL) >= MARK_STATE_KNOWN) then begin
   NAnswer(215,4,NodeFstDialog011)
   end
   else if (getQuest(GVAR_RANGERS_QST_PUERTO) == qStart)  then begin
   NAnswer(215,4,NodeFstDialog011)
   end
   else if (getQuest(GVAR_PHENIX_QST_OWRS_HOLO) == qStart)  then begin
   NAnswer(215,4,NodeFstDialog011)
   end
   else if (global_var(GVAR_TWOSUN_STATUS_BOSS) > 0) then begin
   NAnswer(215,4,NodeFstDialog011)
   end
   NAnswer(209,4,NodeFstDialog011)
   BAnswer(210,4,NodeFstDialog012)
end

procedure NodeFstDialog011 begin
   if (getReaction>0) then begin
   Reply(220)
   NAnswer(221,4,Node999)
   BAnswer(222,4,Node999)
   end
   else begin
   Reply(223)
   NAnswer(224,4,Node999)
   BAnswer(225,4,Node999)
   end
   BAnswer(219,-3,Node999)
end

procedure NodeFstDialog012 begin
   set_REP(-1)
   setBonusReaction(-10)
   call NodeFstDialog011;
end

procedure NodeFstDialog013 begin
   Reply(212)
   NAnswer(213,4,Node999)
   BAnswer(214,4,Node999)
end

//--- СТОП-ДИАЛОГ

procedure NodeStopDialog101 begin
   bitDialogExp(bit_2,100)
   Reply(230)
   NAnswer(231,4,NodeStopDialog102)
   NAnswer(232,-3,NodeStopDialog102)
end

procedure NodeStopDialog102 begin
   Reply(233)
   NAnswer(234,4,NodeStopDialog103)
   NAnswer(235,-3,NodeStopDialog103)
end

procedure NodeStopDialog103 begin
   Reply(236)
   NAnswer(237,4,NodeStopDialog104)
   NAnswer(235,-3,NodeStopDialog104)
end

procedure NodeStopDialog104 begin
   Reply(238)
   BAnswer(240,4,NodeStopDialog105)
   GAnswer(239,4,NodeStopDialog105)
   NAnswer(235,-3,NodeStopDialog105)
end

procedure NodeStopDialog105 begin
   Reply(241)
   NAnswer(242,4,NodeStopDialog107)
   BAnswer(243,4,NodeStopDialog106)
end

procedure NodeStopDialog106 begin
   set_REP(-3)
   setBonusReaction(-25)
   call Node999;
end

procedure NodeStopDialog107 begin
   set_REP(3)
   setBonusReaction(25)
   call Node999;
end

//--- ВТОРОЙ ДИАЛОГ

procedure NodeSndDialog begin
   if town_rep_is_idolized then begin
   zReply(253)
   end
   else if town_rep_is_liked then begin
   zReply(252)
   end
   else begin
   Reply(250)
   end

   if (getQuest(GVAR_NUEVA_QST_PLANT_DEAD) == qStart) then begin
   if (map_var(MVAR_NUEVA_MER_ROSAKNOW) == 0) then begin
   BAnswer(260,4,NodeAnswer200)
   end
   end

   if (getQuest(GVAR_SANTAANA_QST_BARTER) == qStart) then begin
   NAnswer(340,4,NodeAnswerSanta)
   end

   if (getQuest(GVAR_NUEVA_QST_PINKI) == qStart) then begin
   NAnswer(330,4,NodeAnswerPinki)
   end

   if (bitDialog(bit_5) == 0) then begin
   if DudeTraitHas(TRAIT_espanol) then begin
   NAnswer(350,4,NodeAnswerAkcent)
   end
   end

   NAnswer(280,4,NodeAnswer100)
   NAnswer(251,4,Node999)
   NAnswer(254,-3,Node999)
end

//--- РАССПРОСЫ

procedure NodeAnswer100 begin
   Reply(281)

   NAnswer(290,4,NodeAnswer101)
   NAnswer(292,4,NodeAnswer102)
   NAnswer(295,4,NodeAnswer103)

   if (getQuest(GVAR_PUERTO_BOS_DESTROY) < qEnd) then begin
      if (bitDialog(bit_6) == 0) then begin
      NAnswer(299,7,NodeAnswer105)
      end
      if (bitDialog(bit_6) != 0) then begin
      if (bitDialog(bit_4) == 0) then begin
      if (town_known(AREA_PUERTO_STEEL) >= MARK_STATE_VISITED) then begin
      NAnswer(301,7,NodeAnswer106)
      end
      end
      end
   end

   NAnswer(282,4,NodeSndDialog)
end

procedure NodeAnswer101 begin
   Reply(291)
   NAnswer(283,4,NodeAnswer100)
end

procedure NodeAnswer102 begin
   mark_on_map(AREA_TWO_SUN)
   if (getQuest(GVAR_PUERTO_BOS_DESTROY) < qEnd) then begin
   mark_on_map(AREA_PUERTO_STEEL)
   Reply(293)
   end else begin
   Reply(294)
   end
   NAnswer(283,4,NodeAnswer100)
end

procedure NodeAnswer103 begin
   Reply(296)
   if (town_known(AREA_PHOENIX) >= MARK_STATE_VISITED) then begin
   GAnswer(297,7,NodeAnswer104)
   end
   NAnswer(283,4,NodeAnswer100)
end

procedure NodeAnswer104 begin
   bitDialogExp(bit_3,25)
   Reply(298)
   NAnswer(283,4,NodeAnswer100)
end

procedure NodeAnswer105 begin
   bitDialogExp(bit_6,25)
   Reply(300)
   NAnswer(283,4,NodeAnswer100)
end

procedure NodeAnswer106 begin
   Reply(302)
   NAnswerRep(315,4,NodeAnswer108,30,313,NodeAnswer107)
   NAnswer(283,4,NodeAnswer100)
end

procedure NodeAnswer107 begin
   Reply(314)
   NAnswer(283,4,NodeAnswer100)
end

procedure NodeAnswer108 begin
   Reply(316)
   NAnswer(317,4,NodeAnswer109)
end

procedure NodeAnswer109 begin
   bitDialogExp(bit_4,100)
   Reply(318)
   NAnswer(319,4,NodeAnswer100)
   BAnswer(320,4,NodeAnswer100)
   GAnswer(321,4,NodeAnswer100)
end

//---

procedure NodeAnswerPinki begin
   Reply(331)
   NAnswer(332,4,NodeAnswerPinki001)
end

procedure NodeAnswerPinki001 begin
   Reply(333)
   NAnswer(334,4,NodeSndDialog)
end

procedure NodeAnswerSanta begin
   Reply(341)
   NAnswer(342,4,NodeAnswerSanta2)
end

procedure NodeAnswerSanta2 begin
   setQuest(GVAR_SANTAANA_QST_BARTER, qEnd);
   set_CITY_REP(GVAR_TOWN_REP_SANTA_ANA,5)
   set_REP(2)
   set_SLAVA(5)
   setBonusReaction(20)
   exp_add(400);

   Reply(343)
   NAnswer(344,4,Node999)
end

procedure NodeAnswerAkcent begin
   Reply(351)
   GAnswer(352,4,NodeAnswerAkcent2)
end

procedure NodeAnswerAkcent2 begin
   bitDialogExp(bit_5,50)
   setBonusReaction(25)
   set_REP(3)
   Reply(353)
   NAnswer(354,4,NodeSndDialog)
end

procedure NodeAnswer200 begin
   Reply(261)
   BAnswer(262,4,NodeAnswer201)
   NAnswer(265,4,NodeAnswer202)
end

procedure NodeAnswer201 begin
   set_map_var(MVAR_NUEVA_MER_ROSAKNOW,-99);
   setBonusReaction(-25)
   Reply(263)
   NAnswer(264,4,Node999)
end

procedure NodeAnswer202 begin
   set_map_var(MVAR_NUEVA_MER_ROSAKNOW,1);
   setBonusReaction(25)
   set_SLAVA(-25)
   Reply(266)
   NAnswer(267,4,Node999)
end
