#include "..\headers\define.h"
//---------------------

#define NAME                            SCRIPT_TCBndBos
#define TOWN_REP_VAR                    GVAR_TOWN_REP_TWO_SUN_BAND // привязка к репутации (-1, если не нужно)

#define NUM_TEAM                        TEAM_TWOSUN_SLAVES    // группа, к которой принадлежит персонаж (-1 если нужно оставить Team, заданный в редакторе)
#define NUM_AI                          AI_BANDIT             // AI персонажа (-1 если нужно оставить AI, заданный в редакторе)
#define KILL_SLAVA                      SLAVA_KILL_GOOD       // слава за убийство этого персонажа (SLAVA_KILL_GOOD, SLAVA_KILL_BAD, SLAVA_KILL_NEITRAL, SLAVA_KILL_CHILD)
#define KILL_TOWN_REP                   REP_KILL_GOOD         // репутация за убийство этого персонажа (REP_KILL_GOOD, REP_KILL_BAD, REP_KILL_NEITRAL, REP_KILL_CRITICAL для враждебности всего поселения, REP_KILL_CHILD)
#define KILL_FRAC_REP                   FRAC_NON              // принадлежность определенной фракции (-1, если не нужно)

#define FLAG_STEAL                      70 // Нижний порог навыка для кражи (для торговцев 200, для животных 300)
#define FLAG_ALCOHOL                    1  // Примет ли алкоголь от ГГ: 0 - принимает, 1 - не принимает
#define FLAG_FOOD                       0  // Примет ли пищу от ГГ: 0 - принимает, 1 - не принимает

//---------------------

procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure timed_event_p_proc;
procedure critter_p_proc;
procedure use_obj_on_p_proc;
procedure use_skill_on_p_proc;
procedure pickup_p_proc;
procedure combat_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure talk_p_proc;
procedure Node998;
procedure Node999;
procedure NodeStartDialog;
procedure NodeFstDialog;
procedure NodeFstDialog100;
procedure NodeFstDialog101;
procedure NodeFstDialog102;
procedure NodeFstDialog200;
procedure NodeFstDialog300;
procedure NodeFstDialog301;
procedure NodeFstDialog302;
procedure NodeFstDialog303;
procedure NodeFstDialog304;
procedure NodeFstDialog2;
procedure NodeSndDialog;
procedure NodeEnd100;
procedure NodeEnd101;
procedure NodeEnd102;
procedure NodeEnd103;
procedure NodeEnd104;
procedure NodeEnd200;
procedure NodeAnswer101;
procedure NodeAnswer102;

//---------------------

//#define LVAR_Flag_A                     (6) // is responsible for ...

//---------------------



procedure start begin
end

procedure map_enter_p_proc begin
   if (is_loading_game == false) then begin
       set_start_home
       if (gvar_bit(GVAR_TWOSUN_QST_BAND_STATUS, bit_4) != 0) then begin
       rm_timer_event(self_obj);
       set_obj_visibility(self_obj, 1);
       end
   end
end

procedure map_update_p_proc begin
   if (gvar_bit(GVAR_TWOSUN_QST_BAND_STATUS, bit_5) != 0) then begin
      if (self_visible == true) then begin
      set_gvar_bit_on(GVAR_TWOSUN_QST_BAND_STATUS, bit_3);
      rm_timer_event(self_obj);
      kill_critter(self_obj, ANIM_fall_back_sf);
      end
   end
end

procedure look_at_p_proc begin
   lookProcMsg
end

procedure description_p_proc begin
   dsrptProcMsg
end

procedure timed_event_p_proc begin
   // Timer number 1 is reserved for character movement around the location
   // Timer number 2 is reserved for pop-up dialogue
   if (fixed_param == 1) then begin
       timer_move_to_home
   end
   if (fixed_param == 2) then begin
       //timer_float_reply(120,121)
   end
end

procedure critter_p_proc begin
   set_critter_options(1,0) //attack condition (0 personal feud, 1 clan feud, 2 always), turn to GG
end

procedure use_skill_on_p_proc begin
   skillUseSteal
   skillUseFAid
end

procedure pickup_p_proc begin
   pickupProcCritter
end

procedure use_obj_on_p_proc begin
   UsedItemToCrit_Proc
end

procedure combat_p_proc begin
   effectAttak(0,0,1,1,1) //poisoning min, radiation min, leg injury %, arm injury %, eye injury %
end

procedure damage_p_proc begin
   set_damage_dude
end

procedure destroy_p_proc begin
   set_gvar_bit_on(GVAR_TWOSUN_QST_BAND_STATUS, bit_3);
   if (source_obj == dude_obj) then begin
   set_map_var(MVAR_TsnBank_Enemy, -1);
   end
   kill_critter_opt
end

procedure talk_p_proc begin
   if (gvar_bit(GVAR_TWOSUN_QST_BAND_STATUS, bit_4) == 0) then begin
      set_gvar_bit_on(GVAR_TWOSUN_QST_BAND_STATUS, bit_2);
      dialog_proc(0,0,NodeStartDialog,-1,-1)
   end
   else if (map_var(MVAR_TsnBank_Enemy) < 0) then begin
      self_attack_dude;
   end
   else begin
      floater(self_obj,102,COLOR_MSG_NORMAL);
   end
end

procedure Node998 begin
   setNodeCombat;
end

procedure Node999 begin
end

procedure NodeStartDialog begin
   if (bitDialog(bit_1) == 0) then begin
   call NodeFstDialog;
   end
   else begin
   call NodeSndDialog;
   end
end

//--- FIRST DIALOGUE

procedure NodeFstDialog begin
   bitDialogExp(bit_1,0)
   Reply(200)
   NAnswer(201,1,NodeFstDialog100)
   zNAnswer(210,1,NodeFstDialog200)
   BAnswer(220,1,NodeFstDialog300)
end

procedure NodeFstDialog100 begin
   Reply(202)
   NAnswerSkill(203,1,NodeFstDialog101,SKILL_CONVERSANT,50,203,NodeFstDialog102)
   zNAnswer(210,1,NodeFstDialog200)
   BAnswer(220,1,NodeFstDialog300)
end

procedure NodeFstDialog101 begin
   bitDialogExp(bit_2,100)
   zReply(204)
   NAnswer(205,1,NodeFstDialog2)
end

procedure NodeFstDialog102 begin
   zReply(206)
   NAnswer(207,1,Node998)
end

procedure NodeFstDialog200 begin
   Reply(211)
   NAnswer(212,1,NodeFstDialog2)
end

procedure NodeFstDialog300 begin
   Reply(221)
   NAnswer(222,1,NodeFstDialog301)
end

procedure NodeFstDialog301 begin
   Reply(223)
   zNAnswer(224,1,NodeFstDialog302)
   NAnswer(225,1,Node998)
end

procedure NodeFstDialog302 begin
   Reply(226)
   if (get_SLAVA > 0) then begin
   NAnswer(227,1,NodeFstDialog303)
   end
   else begin
   NAnswer(227,1,NodeFstDialog304)
   end
end

procedure NodeFstDialog303 begin
   zReply(228)
   NAnswer(229,1,Node998)
end

procedure NodeFstDialog304 begin
   zReply(230)
   NAnswer(231,1,NodeFstDialog2)
end

procedure NodeFstDialog2 begin
   Reply(240)
   NAnswer(241,1,Node999)
end

//--- REPEAT DIALOGUE

procedure NodeSndDialog begin
   zReply(250)

   if (gvar_bit(GVAR_TWOSUN_QST_BAND_STATUS, bit_4) == 0) then begin
      if (global_var(GVAR_TWOSUN_STATUS_ZAX) > 0) then begin
      NAnswer(280,1,NodeEnd100)
      end
      else if (global_var(GVAR_TWOSUN_STATUS_BOSS) < 0) then begin
      NAnswer(283,1,NodeEnd101)
      end
      else begin
      NAnswerSkill(297,1,NodeEnd102,SKILL_CONVERSANT,80,286,NodeEnd103)
      end
   end

   NAnswer(266,1,NodeAnswer101)
   NAnswer(251,1,Node999)
end

procedure NodeEnd100 begin
   Reply(281)
   NAnswer(282,1,NodeEnd200)
end

procedure NodeEnd101 begin
   Reply(284)
   NAnswer(285,1,NodeEnd200)
end

procedure NodeEnd102 begin
   Reply(287)
   NAnswer(291,1,NodeEnd104)
   NAnswer(288,1,Node999)
end

procedure NodeEnd103 begin
   Reply(287)
   NAnswer(288,1,Node999)
end

procedure NodeEnd104 begin
   Reply(295)
   NAnswer(296,1,NodeEnd200)
end

procedure NodeEnd200 begin
   set_gvar_bit_on(GVAR_TWOSUN_QST_BAND_STATUS, bit_4);
   display_mstr(289);
   call Node999;
end

procedure NodeAnswer101 begin
   Reply(267)
   NAnswer(268,1,NodeAnswer102)
end

procedure NodeAnswer102 begin
   Reply(269)
   NAnswer(252,1,NodeSndDialog)
end
