#include "..\headers\define.h"
//---------------------

#define NAME                            SCRIPT_TCCrvQst
#define TOWN_REP_VAR                    -1 // привязка к репутации (-1, если не нужно)

#define NUM_TEAM                        TEAM_TWOSUN_PEASAN    // группа, к которой принадлежит персонаж (-1 если нужно оставить Team, заданный в редакторе)
#define NUM_AI                          AI_PERSON_TOUGH       // AI персонажа (-1 если нужно оставить AI, заданный в редакторе)
#define KILL_SLAVA                      SLAVA_KILL_GOOD       // слава за убийство этого персонажа (SLAVA_KILL_GOOD, SLAVA_KILL_BAD, SLAVA_KILL_NEITRAL, SLAVA_KILL_CHILD)
#define KILL_TOWN_REP                   REP_KILL_BAD          // репутация за убийство этого персонажа (REP_KILL_GOOD, REP_KILL_BAD, REP_KILL_NEITRAL, REP_KILL_CRITICAL для враждебности всего поселения, REP_KILL_CHILD)
#define KILL_FRAC_REP                   FRAC_NON              // принадлежность определенной фракции (-1, если не нужно)

#define FLAG_STEAL                      40 // Нижний порог навыка для кражи (для торговцев 200, для животных 300)
#define FLAG_ALCOHOL                    0  // Примет ли алкоголь от ГГ: 0 - принимает, 1 - не принимает
#define FLAG_FOOD                       0  // Примет ли пищу от ГГ: 0 - принимает, 1 - не принимает

//---------------------

procedure start;
procedure map_enter_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure timed_event_p_proc;
procedure critter_p_proc;
procedure use_obj_on_p_proc;
procedure use_skill_on_p_proc;
procedure pickup_p_proc;
procedure combat_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure talk_p_proc;

procedure Node998;
procedure Node999;
procedure NodeStartDialog;
procedure NodeFstDialog;
procedure NodeFstDialog2;
procedure NodeFstDialog3;
procedure NodeFstDialog4;
procedure NodeFstDialog5;
procedure NodeFstDialog6;
procedure NodeFstDialog7;
procedure NodeSndDialog;
procedure NodeSndDialog2;
procedure NodeQstDialogEnd;
procedure NodeQstDialogEnd1;
procedure NodeQstDialogEnd2;
procedure NodeQstDialogEnd3;

//---------------------

//#define LVAR_Flag_A                     (6) // is responsible for ...

//---------------------



procedure start begin
end

procedure map_enter_p_proc begin
   if (is_loading_game == false) then begin
       if (global_var(GVAR_TWOSUN_STATUS_ZAX) > 0) then begin
       set_local_var(LVAR_Home_Tile, 26517);
       end
       set_start_home
       if (getQuest(GVAR_TWOSUN_QST_POMPA) >= qEnd) then begin
       rm_timer_event(self_obj);
       set_obj_visibility(self_obj, 1);
       end
   end
end

procedure look_at_p_proc begin
   lookProcMsg
end

procedure description_p_proc begin
   dsrptProcMsg
end

procedure timed_event_p_proc begin
   // Timer number 1 is reserved for character movement around the location
   // Timer number 2 is reserved for pop-up dialogue
   if (fixed_param == 1) then begin
       timer_move_random_home(3)
   end
   if (fixed_param == 2) then begin
       //timer_float_reply(110,119)
   end
   if (fixed_param == 3) then begin
       set_local_var(LVAR_Home_Tile,10);
       dude_teleport_map(1,1,MAP_CASA_GRANDE_WATER,24+random(6,18));
   end
end

procedure critter_p_proc begin
   set_critter_options(1,0) //attack condition (0 personal feud, 1 clan feud, 2 always), turn to GG
end

procedure use_skill_on_p_proc begin
   skillUseSteal
   skillUseFAid
end

procedure pickup_p_proc begin
   pickupProcCritter
end

procedure use_obj_on_p_proc begin
   UsedItemToCrit_Proc
end

procedure combat_p_proc begin
   effectAttak(0,0,0,0,0) //poisoning min, radiation min, leg injury %, arm injury %, eye injury %
end

procedure damage_p_proc begin
   set_damage_dude
end

procedure destroy_p_proc begin
   if (getQuest(GVAR_TWOSUN_QST_POMPA) == qStart) then begin
   setQuest(GVAR_TWOSUN_QST_POMPA,qZero);
   end
   kill_critter_opt
end

procedure talk_p_proc begin
   setReaction(1) // Отношение к ГГ(1 - персонаж положительный, -1 отрицательный, 0 нейтральный)
   fracReaction(GVAR_TITUL_BOS,-50) // Поправка к отношению за принадлежность к фракциям
   fracReaction(GVAR_TITUL_PHENIX_CULT,-50) // Поправка к отношению за принадлежность к фракциям
   fracReaction(GVAR_TITUL_WARRIOR_ROAD,-50) // Поправка к отношению за принадлежность к фракциям
   fracReaction(GVAR_TITUL_DUDE_IS_SLAVE,25) // Поправка к отношению за принадлежность к фракциям

   dialog_proc(0,0,NodeStartDialog,-1,-1)
end

procedure Node998 begin
   set_enemy_dude;
end

procedure Node999 begin
end

procedure NodeStartDialog begin
   if (getQuest(GVAR_TWOSUN_QST_POMPA) >= qEnd) then begin
   call NodeSndDialog2;
   end
   else if (bitDialog(bit_1) == 0) then begin
   call NodeFstDialog;
   end
   else begin
   call NodeSndDialog;
   end
end

//--- FIRST DIALOGUE

procedure NodeFstDialog begin
   bitDialogExp(bit_1,0)
   Reply(200)
   NAnswer(201,1,NodeFstDialog2)
end

procedure NodeFstDialog2 begin
   Reply(202)
   NAnswer(203,1,NodeFstDialog3)
end

procedure NodeFstDialog3 begin
   Reply(204)
   NAnswer(250,1,NodeFstDialog4)
end

procedure NodeFstDialog4 begin
   if (getQuest(GVAR_TWOSUN_QST_POMPA) < qStart) then begin
   setQuest(GVAR_TWOSUN_QST_POMPA,qStart);
   end
   zReply(251)
   NAnswer(252,1,NodeFstDialog5)
   NAnswer(255,1,NodeFstDialog6)
   NAnswer(258,1,NodeFstDialog7)
end

procedure NodeFstDialog5 begin
   Reply(253)
   NAnswer(255,1,NodeFstDialog6)
   NAnswer(258,1,NodeFstDialog7)
end

procedure NodeFstDialog6 begin
   Reply(256)
   if (item_amnt(dude_obj,PID_GENERATOR_ENERGY) >0) then begin
   NAnswer(205,1,NodeQstDialogEnd)
   end
   NAnswer(254,1,Node999)
end

procedure NodeFstDialog7 begin
   Reply(259)
   if (item_amnt(dude_obj,PID_GENERATOR_ENERGY) >0) then begin
   NAnswer(205,1,NodeQstDialogEnd)
   end
   NAnswer(254,1,Node999)
end

//--- REPEAT DIALOGUE

procedure NodeSndDialog begin
   if (global_var(GVAR_TWOSUN_STATUS_ZAX) > 0) then begin
   Reply(260)
   end
   else begin
   Reply(210)
   end

   if (getQuest(GVAR_TWOSUN_QST_POMPA) == qStart) then begin
      if (item_amnt(dude_obj,PID_GENERATOR_ENERGY) >0) then begin
      NAnswer(300,1,NodeQstDialogEnd)
      end
   end

   NAnswer(211,1,Node999)
end

procedure NodeSndDialog2 begin
   Reply(306)
   NAnswer(304,1,NodeQstDialogEnd2)
   NAnswer(305,1,NodeQstDialogEnd3)
end

procedure NodeQstDialogEnd begin
   if (item_amnt(dude_obj,PID_GENERATOR_ENERGY) >0) then begin
   bitDialogExp(bit_2,350)
   item_add(dude_obj,PID_MANY,5)
   set_map_var(MVAR_TWOSUN_CaravanPompa,1);
   setQuest(GVAR_TWOSUN_QST_POMPA,qEnd);
   set_SLAVA(25)
   item_remove(dude_obj, PID_GENERATOR_ENERGY, 1)

   zReply(301)
   NAnswer(302,1,NodeQstDialogEnd1)
   end
   else begin
   call Node999;
   end
end

procedure NodeQstDialogEnd1 begin
   Reply(303)
   NAnswer(304,1,NodeQstDialogEnd2)
   NAnswer(305,1,NodeQstDialogEnd3)
end

procedure NodeQstDialogEnd2 begin
   rm_timer_event(self_obj);
   add_timer_event(self_obj, 2, 3);
   call Node999;
end

procedure NodeQstDialogEnd3 begin
   //disappearance?
   call Node999;
end
