#include "..\headers\define.h"
//---------------------

#define NAME                            SCRIPT_TCRobot
#define TOWN_REP_VAR                    -1   // привязка к репутации (-1, если не нужно)

#define NUM_TEAM                        TEAM_ROBOTS           // группа, к которой принадлежит персонаж (-1 если нужно оставить Team, заданный в редакторе)
#define NUM_AI                          -1                    // AI персонажа (-1 если нужно оставить AI, заданный в редакторе)
#define KILL_SLAVA                      SLAVA_KILL_NEITRAL    // слава за убийство этого персонажа (SLAVA_KILL_GOOD, SLAVA_KILL_BAD, SLAVA_KILL_NEITRAL, SLAVA_KILL_CHILD)
#define KILL_TOWN_REP                   REP_KILL_NEITRAL      // репутация за убийство этого персонажа (REP_KILL_GOOD, REP_KILL_BAD, REP_KILL_NEITRAL, REP_KILL_CRITICAL для враждебности всего поселения, REP_KILL_CHILD)
#define KILL_FRAC_REP                   FRAC_NON              // принадлежность определенной фракции (-1, если не нужно)

#define FLAG_STEAL                      100 // Нижний порог навыка для кражи (для торговцев 200, для животных 300)
#define FLAG_ALCOHOL                    1  // Примет ли алкоголь от ГГ: 0 - принимает, 1 - не принимает
#define FLAG_FOOD                       1  // Примет ли пищу от ГГ: 0 - принимает, 1 - не принимает

//---------------------

procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure timed_event_p_proc;
procedure critter_p_proc;
procedure use_obj_on_p_proc;
procedure use_skill_on_p_proc;
procedure pickup_p_proc;
procedure combat_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;

//---------------------

//#define LVAR_Flag_A                     (6) // is responsible for ...

//---------------------



procedure start begin
end

procedure map_enter_p_proc begin
   if (is_loading_game == false) then begin
       set_start_home
       if ((cur_map_index == MAP_TWO_SUN_GRAVE) or (global_var(GVAR_TWOSUN_STATUS_ZAX) != 0)) then begin
       set_obj_visibility(self_obj, 1);
       end
   end
end

procedure map_update_p_proc begin
   if (global_var(GVAR_TWOSUN_STATUS_ZAX) > 0) then begin
   set_obj_visibility(self_obj, 1);
   end
end

procedure timed_event_p_proc begin
   // Timer number 1 is reserved for character movement around the location
   // Timer number 2 is reserved for pop-up dialogue
   if (fixed_param == 1) then begin
       timer_move_to_home
   end
   if (fixed_param == 2) then begin
       //timer_float_reply(110,119)
   end
end

procedure critter_p_proc begin
   if (global_var(GVAR_TWOSUN_STATUS_ZAX) == 0) then begin
   invisToDude(10,102) // Скрывание нпс от ГГ до некоторой дистанции, в скобках реплика для лога
   set_critter_options(2,0) //attack condition (0 personal feud, 1 clan feud, 2 always), turn to GG
   end
   else begin
   set_critter_options(0,0) //attack condition (0 personal feud, 1 clan feud, 2 always), turn to GG
   end
end

procedure use_skill_on_p_proc begin
   skillUseSteal
   skillUseFAid
   skillUseScience(60)
end

procedure pickup_p_proc begin
   pickupProcCritter
end

procedure use_obj_on_p_proc begin
   UsedItemToCrit_Proc
end

procedure combat_p_proc begin
   effectAttak(0,0,1,2,1) //poisoning min, radiation min, leg injury %, arm injury %, eye injury %
end

procedure damage_p_proc begin
   set_damage_dude
end

procedure destroy_p_proc begin
   kill_critter_opt
end
