#include "..\headers\define.h"
//---------------------

#define NAME                            SCRIPT_TCTins
#define TOWN_REP_VAR                    GVAR_TOWN_REP_TWO_SUN   // привязка к репутации (-1, если не нужно)

#define NUM_TEAM                        TEAM_TWOSUN_PEASAN    // группа, к которой принадлежит персонаж (-1 если нужно оставить Team, заданный в редакторе)
#define NUM_AI                          AI_CULT_TWOSUN        // AI персонажа (-1 если нужно оставить AI, заданный в редакторе)
#define KILL_SLAVA                      SLAVA_KILL_GOOD       // слава за убийство этого персонажа (SLAVA_KILL_GOOD, SLAVA_KILL_BAD, SLAVA_KILL_NEITRAL, SLAVA_KILL_CHILD)
#define KILL_TOWN_REP                   REP_KILL_GOOD         // репутация за убийство этого персонажа (REP_KILL_GOOD, REP_KILL_BAD, REP_KILL_NEITRAL, REP_KILL_CRITICAL для враждебности всего поселения, REP_KILL_CHILD)
#define KILL_FRAC_REP                   FRAC_NON              // принадлежность определенной фракции (-1, если не нужно)

#define FLAG_STEAL                      60 // Нижний порог навыка для кражи (для торговцев 200, для животных 300)
#define FLAG_ALCOHOL                    0  // Примет ли алкоголь от ГГ: 0 - принимает, 1 - не принимает
#define FLAG_FOOD                       1  // Примет ли пищу от ГГ: 0 - принимает, 1 - не принимает

//---------------------

procedure start;
procedure map_enter_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure timed_event_p_proc;
procedure critter_p_proc;
procedure use_obj_on_p_proc;
procedure use_skill_on_p_proc;
procedure pickup_p_proc;
procedure combat_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure replyfloat_proc;
procedure talk_p_proc;

//---------------------

#define LVAR_Tile_B                     (6) // номер второго тайла для патрулирования

variable replyFloat;

import variable box_stop_use;

//---------------------



procedure start begin
end

procedure map_enter_p_proc begin
   if (is_loading_game == false) then begin
       set_start_home

       if (item_amnt(self_obj,PID_TEST) > 0) then begin
           if (cur_map_index == MAP_TWO_SUN_WORKSHOP) then begin
              if (item_amnt(self_obj,PID_TEST) == 1) then begin
              set_local_var(LVAR_Tile_B, tile_num_in_direction(self_tile,0,5)); // нижний в центре зала
              end
              if (item_amnt(self_obj,PID_TEST) == 2) then begin
              set_local_var(LVAR_Tile_B,tile_num_in_direction(self_tile,3,5)); // средний в центре зала
              end
              if (item_amnt(self_obj,PID_TEST) == 3) then begin
              set_local_var(LVAR_Tile_B,tile_num_in_direction(self_tile,0,4)); // верхний в центре зала
              end
           end
           item_remove(self_obj,PID_TEST,999)
       end

       if (global_var(GVAR_TWOSUN_STATUS_ZAX) > 0) then begin
       rm_timer_event(self_obj);
       //set_obj_visibility(self_obj, 1);
       kill_critter(self_obj, random(ANIM_fall_back_blood_sf,ANIM_fall_front_blood_sf));
       end
   end
end

// added this to differentiate between guard and worker tinsmiths - cambragol
procedure look_at_p_proc begin
      lookProcMsg
end

procedure description_p_proc begin
   if (cur_map_index == MAP_TWO_SUN_WORKSHOP) then begin
      dsrptProcMsg
   end
   else begin
      script_overrides;
      display_mstr(102);
   end
end

procedure timed_event_p_proc begin
   // Timer number 1 is reserved for character movement around the location
   // Timer number 2 is reserved for pop-up dialogue
   if (fixed_param == 1) then begin
       if (local_var(LVAR_Tile_B) > 0) then begin
       timer_move_patrol(HomeTile,local_var(LVAR_Tile_B))
       end
       else begin
       timer_move_to_home
       end
   end
   if (fixed_param == 2) then begin
       if (cur_map_index == MAP_TWO_SUN_WORKSHOP) then begin
          call replyfloat_proc;
          timer_float_reply(replyFloat,replyFloat)

          if (self_tile == HomeTile) then begin
             if (random(0,1) == 1) then begin
                   if (combat_is_initialized == false) then begin
                      if not(anim_busy(self_obj)) then begin
                         reg_anim_clear(self_obj);
                         reg_anim_begin();
                          anim(self_obj, ANIMATE_ROTATION, HomeRotat);
                          reg_anim_animate(self_obj, ANIM_magic_hands_middle, -1);
                         reg_anim_end();
                      end
                   end
             end
          end
       end
   end
end

procedure critter_p_proc begin
   set_using_stop
   set_critter_options(1,0) //attack condition (0 personal feud, 1 clan feud, 2 always), turn to GG
end

procedure use_skill_on_p_proc begin
   skillUseSteal
   skillUseFAid
end

procedure pickup_p_proc begin
   pickupProcCritter
end

procedure use_obj_on_p_proc begin
   UsedItemToCrit_Proc
end

procedure combat_p_proc begin
   effectAttak(0,0,1,1,1) //poisoning min, radiation min, leg injury %, arm injury %, eye injury %
end

procedure damage_p_proc begin
   set_damage_dude
end

procedure destroy_p_proc begin
   dec_global_var(GVAR_TWOSUN_STATUS_CTZN);
   kill_critter_opt
end

procedure replyfloat_proc begin
   replyFloat := random(-2,3);

   // added this so 'guards' in settlement area don't talk about workshop stuff - cambragol
   if (cur_map_index == MAP_TWO_SUN_WORKSHOP) then begin
      if (replyFloat <= 0) then begin
         replyFloat := random(110,119);
      end
   end
   else begin
      if (replyFloat <= 0) then begin
         replyFloat := random(150,159);
      end
   end

   if (replyFloat == 1) then begin
      replyFloat := random(120,123);
      if (getQuest(GVAR_PUERTO_BOS_DESTROY) >= qEnd) then begin
      replyFloat := random(125,127);
      end
   end

   if (replyFloat == 2) then begin
      replyFloat := random(130,133);
      if (getQuest(GVAR_FLAGSTAFF_MINES_DESTROY) >= qEnd) then begin
      replyFloat := random(135,139);
      end
   end

   if (replyFloat == 3) then begin
      replyFloat := random(140,144);
      if ((getQuest(GVAR_PHENIX_CULT_DESTROY) >= qEnd) or (getQuest(GVAR_PHENIX_PARTY_QST_B) >= qEnd)) then begin
      replyFloat := random(145,149);
      end
   end

end

procedure talk_p_proc begin
   call replyfloat_proc;
   floater(self_obj,replyFloat,COLOR_MSG_NORMAL);
end
