{100}{}{You see Gloria.}
{101}{}{You see a Mexican girl.}
{102}{}{You have revived the patient.}
{103}{}{Madre de Dios! Lo que sucederá?}

{110}{}{Ahhhh...}
{111}{}{The girl is unconscious. She is experiencing a medical emergency.}
{112}{}{«Thanks for saving my life. I need to catch my breath a little and calm down. Can you go to the village and tell them what happened?»}
{113}{}{Tú eres mi salvador. Le estoy muy reconocido.}
{114}{}{Okay, I'll explain what happened in the settlement. And you rest.}
{115}{}{Le estoy muy reconocido.}
{116}{}{«Thank you again.»}
{117}{}{Le estoy muy reconocido. Habla con Héctor.}
{118}{}{«Thank you again. Talk to Héctor about what happened.»}

{179}{}{«Take it easy. Everything's fine.»}
{180}{}{«Ahhhh... Monsters! They're here...they're here!»}
{181}{}{«Stay back...»}
{182}{}{«Okay, I'll explain what happened in the settlement. And you rest.»}

#First dialogue
{200}{}{Ahhhh... (speaks something unintelligible in Spanish)}
{201}{}{Sorry, I don't understand.}
{202}{}{What the hell are you talking about?}
{203}{}{¡Monstruos! ¡Están en todos lados!}
{204}{}{Calm down, you're in no danger now.}
{205}{}{You're not right in the head, are you?}
{206}{}{(looks around nervously)}
{207}{}{Do you want to get out of here? I know the way out. Let's go, let's go...}
{208}{}{Nope, I don't need a crazy traveling companions right now. Just stay here!}
{209}{}{No te preocupes. Todo bueno.}
{210}{}{«Monsters! They're everywhere!»}
{211}{}{«Calm down, you're in no danger now.»}
{212}{}{«You want them to find us? Then shut up, fool.»}
{213}{}{«Oh, sorry, they're so horrible! I just want to go home. Will you get me out of here?»}
{214}{}{«Of course, let's get you out of here. Let's go for some fresh air...»}
{215}{}{«Nope, I don't need an hysterical girl tagging along right now. Just sit here and don't make a sound!»}
{216}{}{Estará tan silencioso como un ratón.}
{217}{}{«I'll be as quiet as a mouse.»}
{218}{}{Stay back...}
{219}{}{}

#Re-dialogue
{220}{}{¡Por favor no me dejes aquí!}
{221}{}{Please don't leave me here!}
{222}{}{You can't stay here. Come with me...}
{223}{}{Sit here and don't make any noise.}
{224}{}{We'll be out of the cave soon. Go ahead.}

{230}{}{I need to ask you a couple of questions.}
{231}{}{¿Qué estás diciendo? No lo comprendo.}
{232}{}{Well, yes, the expected answer. Let's keep quiet then.}
{233}{}{What, right now?}
{234}{}{No, we'll talk later.}
{235}{}{Who are you?}
{236}{}{My name is Gloria.}
{237}{}{Where are you from?}
{238}{}{I'm from a fishing village on the coast. It's called San Felipe.}
{239}{}{How did you end up in the cave?}
{240}{}{It seems that I was walking along the shore, when suddenly this monster leaped out of an old boat. Then I guess that I lost consciousness and woke up in this cave. I think the monsters dragged me here... God, what a nightmare!}
{241}{}{What do you know about these monsters?}
{242}{}{Creepy creatures. They really creep me out. Could nature have created such monsters? No, these are creatures from hell itself. It's no wonder they reek of death and decay!}
{243}{}{Yes, they really do smell unhealthy.}
{244}{}{I think this nasty air comes from the leather bags on their bodies. Maybe this is how they hover above the ground? Oh, I should throw some fire there and see what happens!}
{245}{}{Good idea, a big flamethrower would be nice here.}
{246}{}{Sounds like methane.}
{247}{}{Wow, you know such difficult words? I don't know what this means. But I think they use the air in the leather bags on their bodies to float in the air. Oh, I wish I could throw some fire in there and see what happens!}
{248}{}{That's right, I really need a big flamethrower.}
{249}{}{Where are you from, Gloria?}
{250}{}{That's all I wanted to know.}
{251}{}{It seems that I was walking along the sea, when suddenly this monster jumped out of an old boat. It seems that I lost consciousness and woke up already in this cave. I think these monsters dragged me here... God, there were other bodies lying there too! Maybe they are still alive? No, I won't go back there...}
