{100}{}{You see a computer.}
{101}{}{You see a computer with access to a public network.}

#Dialogue
{200}{}{Enter command:}
{201}{}{End session}
{202}{}{Back}
{203}{}{Next}
{204}{}{Return to main menu}

{210}{}{October 23, 2077, 12:00}
{211}{}{This is the Platform calling the Operator. Do you read? (silence) I repeat. Platform calling the Operator. Do you read?}
{212}{}{October 23, 2077, 12:10 pm}
{213}{}{Platform calling! I'm reaching out to the Operator. Can you hear me? (silence) What the hell is going on over there...}
{214}{}{October 23, 2077, 13:00}
{215}{}{Platform speaking. We have no contact with the shore. If anyone can hear me, please respond with a counter signal.}
{216}{}{October 23, 2077, 21:00}
{217}{}{Still no contact with shore. Radio equipment checks out; no malfunctions found. Why is there no connection? Why is the coast guard silent? If anyone can hear me, please respond!}
{218}{}{October 24, 2077, 12:00}
{219}{}{Switching to emergency frequencies. Can anyone hear me? Respond! What's happening over there? Our technologist reports a notable outbreak from Mexicali two days ago. We suspect Chinese sabotage at the power plant. Requesting assistance from the coast guard. Anyone, please respond!}
{220}{}{October 30, 2077, 12:00}
{221}{}{It's been a week without contact. The platform is operational, workers are fine, but we have no idea what's happening onshore. No communication from the administration, civilian radio stations are silent. We've dealt with bad connections before, but a week of complete silence is unprecedented. We can't leave the platform without breaching our employment contract. Hoping for a resolution soon.}
{222}{}{November 6, 2077, 8:02 am}
{223}{}{We're due for a food delivery and shift change today. Where the hell are they? If no one makes contact soon, we'll be forced to abandon the platform.}
{224}{}{November 20, 2077, 5:48 am}
{225}{}{Attention! This is the Platform. We're evacuating on the only lifeboat. One person remains at the station. I implore anyone who hears this to send help.}
{226}{}{November 21, 2077, 12:33 pm}
{227}{}{The platform is active! Who's there?! - It's us, buddy. We have terrible news... Mexicali was hit by a nuclear blast... - Wha... Oh, my god! - ...And it seems we picked up a lethal dose of rads. I'm the only one who made it to shore to relay this... I'm suffocating... Don't do anything reckless... Conserve your food and water. We can't retrieve the boat. Farewell, amigo. It was an honor working with you...}
{228}{}{November 29, 2077, 15:00}
{229}{}{He said it... But who cares now, right? No one needs this station anymore. Nor me. I'm alone here and can't leave. When the station was automated, those cheapskates from the administration left just one boat to make room for new equipment. It's somewhere onshore now. I can't swim there on my own. Will help ever come? Who knows. My food and water will last a month, no more. For now, I'll ensure no disaster happens here. Although the Cortez coast is already an environmental disaster zone, even without our station. It's all down to human greed...}
{230}{}{December 25, 2077, 23:14}
{231}{}{Hey, you folks onshore! You're probably celebrating Christmas, huh? *Hic!* I just remembered a bottle one of the workers stashed away. *Hic!* Hello to everyone. This is a joke, right? There was no war, right? And Mexicali's fine, right? I'll be with you soon, just gotta put on a life jacket... so... wait for me, kids! Dad's coming home!}
