{100}{}{You see a computer.}
{101}{}{You see a computer with access to a public network.}

#Dialogue
{200}{}{Enter command:}
{201}{}{End session}
{202}{}{Back}
{203}{}{Next}
{204}{}{Return to main menu}

{210}{}{General message.}
{211}{}{Attention all personnel! The company management has decided to modernize our operations by fully automating the station. Only a select few will remain on the platform to monitor the systems, while the rest of the workforce will be released from duty. This measure is essential to enhance operational efficiency, reduce financial expenditures, and fortify our defenses against industrial espionage.}
{212}{}{Management regrets any inconvenience caused by the reduction in workforce and will provide compensation in accordance with your employment contracts. The transition from human labor to automated systems will be implemented gradually over a three-month period.}
{213}{}{Furthermore, please be advised that a new security protocol will be in effect during this period. All employees will be issued identification cards to ensure smooth operations.}
{214}{}{List of drilling platforms in the Sea of Cortez.}
{215}{}{(You find a long list of platforms. Almost all of them are marked as closed. Apparently, the oil in the sea was already on the verge of depletion before the Great War. Numerous rusted hulks of these structures are still visible on the horizon.)}
