{100}{}{You see Ruiz.}
{101}{}{You see a local resident. He is wearing a bandana and a light cape.}
{102}{}{Dig.}
{103}{}{You better not test my patience.}
{104}{}{If I come across any more treasure maps, I'll be sure to call you.}
{105}{}{How are you, companeras?}
{106}{}{How are you, companero?}
{1106}{}{How are you, companera?}

{200}{}{So, so, what do we have here?}
{201}{}{This isn't yours. Get out.}
{202}{}{Think about it, asshole. No one will help the dead here. Besides, I found this treasure. And it belongs to me. Now be so kind as to move over and GO TO HELL!}
{1202}{}{Think about it, you ugly cunt. No one will help the dead here. Besides, I found this treasure. And it belongs to me. Now be so kind as to move over and GO TO HELL!}
{203}{}{Make me, shorty.}
{204}{}{Oh, please. This is truly your treasure.}
{205}{}{Think about it, gringo. No one will help you here. I found this treasure. And it belongs to me. Now be so kind as to move over and GO TO HELL!}
{1205}{}{Think carefully, senora. No one will help you here. I found this treasure. And it belongs to me. Now be a good girl - move over and GO TO HELL!}
{206}{}{Oh, please, look.}
{207}{}{Is that all? Not much. The old man was a cheapskate; he could have put in something more serious. I wish I could take it all, but I have to share. What do you choose from this?}
{208}{}{50 pre-war dollars.}
{209}{}{Combat revolver.}
{210}{}{Rad-X, 3 pcs.}
{211}{}{I choose everything. Get away from my things!}
{212}{}{Hmm, how about we finish you off? With your reputation, we might even be praised.}
{213}{}{Just try it!}
{214}{}{Everyone was in the black, yet I can't shake this feeling of missed profits. Anyway, see you around.}
{215}{}{Bye.}
