{100}{}{You see a fisherman.}
{101}{}{You see a local resident going about his usual business.}

{110}{}{Hello.}

{200}{}{Hey, kid. How can I help you?}
{1200}{}{My respects, lady. How can I help?}
{201}{}{Nothing, I guess.}
{202}{}{That was a fire! The whole sky was black with smoke!}
{203}{}{Yeah.}

{210}{}{I was just wondering what you do.}
{211}{}{Right now I'm relaxing and admiring the sea. Maybe I should go look through the nets?}
{212}{}{Right now I'm just relaxing and admiring the sea. Shall we go and collect shellfish?}
{213}{}{Right now I'm relaxing and admiring the sea. Maybe I should go to the bar?}
{214}{}{Not a bad idea. Bye.}

{220}{}{I'm currently trying to get this beauty of a boat up and running. But she still has a lot of work to go.}
{221}{}{What's wrong with her?}
{222}{}{A couple of holes, cracks, rust. And there's nothing to charge the engine with. It needs a lot of work, in short, and without boats the entire town will collapse. So someone needs to rejuvenate this old lady.}
{223}{}{Hole, you say? Let me take a look...}
{224}{}{I see. Can I ask you a couple of questions?}

{230}{}{Can I ask you a couple of questions?}
{231}{}{Well, what about?}
{232}{}{Where are the other boats?}
{233}{}{We're having a hard time with boats, you know. Only one boat goes out to sea to fish. There are a few more boats, but you can't go far with them. We've already lost three boats for various reasons: one never returned from the platform, the other capsized and sank during a storm, and the third, so they say, was dragged to the bottom by a sea monster. Although I'm not sure about the last one.}
{234}{}{How do you power the boats?}
{235}{}{We get batteries from Puerto Penasco. And if we run out, then we row with our hands.}
{236}{}{What do you know about the oil platform?}
{237}{}{Scary place. First, some weird ...mutant creatures appeared there. And now it's pouring black poison into the sea. It would be nice to get rid of it, but how?}
{238}{}{Yeah, that's okay.}
{239}{}{Thanks for the chat. Bye.}
{240}{}{Tell me about your captain.}
{241}{}{What kind of... 'creatures'?}
{242}{}{Disgusting floating creatures... 'floaters'. They made a nest on an oil platform and attack any fishermen who approach it. We barely managed to get away from there when we went to check it out. We were lucky - it seems like they're not active during the daytime.}
