{100}{}{You see a villager.}
{101}{}{You see a fisherman with tanned skin.}
{102}{}{This is a sick villager.}
{103}{}{You see a fisherman that looks exhausted from a long illness.}
{104}{}{Your skills are not enough to cure this patient without special medications.}
{105}{}{(}
{106}{}{/3) of the patients are recovering.}
{107}{}{I feel better. Thanks, doc.}

{110}{}{*Cough cough*}
{111}{}{Oh...}

{120}{}{*Cough cough*}
{121}{}{I'm not feeling well. Are you kidding me?}
{122}{}{That sickness is gone, as if it never happened. You're doing wonders, Doc.}
{123}{}{Why did you bother to treat me if you hate this place so much?}
