{101}{}{You see a tribal child with long, black hair.}
{102}{}{Don't push!}
{103}{}{Save yourself! This is the evil iron spirit!}
{104}{}{You are not bad like the other strangers. Thank you.}

{110}{}{Shh!}
{111}{}{Quiet! They will hear us...}
{112}{}{It is better to remain silent}
{113}{}{Keep your voice quiet}
{114}{}{Mangas must not find out}
{115}{}{Should we call for help?}
{116}{}{We can not do it on our own}
{117}{}{What should we do?}
{118}{}{I never go back there}
{119}{}{ }

{200}{}{"...No, you can not tell, otherwise whole tribe hate us!" - "What, you have better idea? They will die there!" - "Yes, they are already dead, fool!" - "I will not go there again, we must tell..."}
{201}{}{Hey kids, I heard you talking. What's going on?}
{1201}{}{Hey kids, I heard you talking. What's going on?}
{202}{}{(one kid lunges forward nervously) "What do you care? You are a stranger!" - (the others grab him with apologies) "Calm down, fool, maybe he can help us? Or do you want to go to the shaman?" - "No, the shaman will punish us." - "That's the same..."}
{1202}{}{(one kid lunges forward nervously) "What do you care? You are a stranger!" - (the others grab him with apologies) "Calm down, fool, maybe she can help us? Or do you want to go to the shaman?" - "No, the shaman will punish us." - "That's the same..."}
{203}{}{Tell me what happened.}
{204}{}{Listen, stranger, you promise not speak of this? We walked in Buried City. It is west of here, in place where dunes cover old pueblo. Then we heard growling in catacombs, so we ran!}
{205}{}{Normal reaction, guys. You did the right thing.}
{206}{}{Hmm, you're chickens.}
{207}{}{But two of us did not return.}
{208}{}{You idiots!}
{209}{}{Poor kids, calm down, it's all behind you now.}
{210}{}{This is serious, guys.}
{211}{}{Can you save them?}
{212}{}{Why such secrecy? Why not tell everything to your elders?}
{213}{}{We... we were forbidden to go to catacombs... Many say that evil spirit lives there, cave-ins happen, and all that. But it was so interesting, we could not resist.}
{214}{}{I need to get ready. Grab my best... uh, spear, and toughest boots. Wait here, kids.}
{215}{}{Take me to these catacombs.}

{220}{}{Thank you. Now we will obey the elders.}
{221}{}{Correct. You were warned, but you didn't listen. Hopefully this lesson will stick with you for life.}
{222}{}{You don't have to listen to everything they say. Good luck, guys.}
