{100}{}{You see a tribal warrior.}
{101}{}{You see a dark-skinned man with war paint all over his body.}

{120}{}{I fight for my tribe. And you?}
{121}{}{If I die, I end up in Great Heavenly Pastures.}
{122}{}{The Divine Brahmin guards me in battle.}
{123}{}{We win if we fight side by side.}
{124}{}{Which side are you on?}
{125}{}{The tribe remembers our victories.}
{126}{}{I defend pueblo from raiders to final breath.}
{127}{}{Let my enemies tremble before my shield.}
{128}{}{An amulet made from bone of sacred Brahmin protects me.}
{129}{}{The shaman says he enchanted my amulets.}
