{100}{}{You see Mangas, the tribal elder.}
{101}{}{You see a shaman in traditional garb.}
{102}{}{Look! There it is, the evil metal spirit! Do you believe me now?}
{103}{}{Old Mangas has lost his mind completely!}

#Floating phrases in the square
{110}{}{Drive outsiders away!}
{111}{}{Outsiders divide our tribe!}
{112}{}{Look at what these outsiders do to our community!}
{113}{}{For so many generations we kept our traditions, not for outsiders to destroy them!}
{114}{}{Now, even among us, dissent appears. Where will this lead?}
{115}{}{Tribe is again on path of hostility. And it is all because of Phoenix.}
{116}{}{We were united, but Phoenix taught us to bicker over trifles!}
{117}{}{Look at Chatto and his friends. They are beyond redemption!}
{118}{}{Chatto learned to read from caravanners. What is next?}
{119}{}{It will only get worse! Phoenix will not share wasteland. Aaron wants everything!}
{120}{}{Because of missionaries, we cannot even gather in wasteland to graze brahmin.}
{121}{}{Bring all heathen things here! Burn them! Burn them!}
{122}{}{Look at these books and technologies - do we need this?}
{123}{}{Phoenix promises nothing but lies!}
{124}{}{Do not fall for missionaries' tricks!}
{125}{}{Close your ears when missionaries try to explain something to you.}
{126}{}{We have lived here for many generations! We will not give our land to outsiders!}

#Stop-dialogue about the bike
{200}{}{Look! This is what I spoke of! Outsiders have tamed iron! Playing god, they resurrect old technologies and bend them to their will. And what is next? Will they take our bodies and souls?}
{201}{}{No need to worry so much. This is just my bike. It doesn't threaten you.}
{202}{}{Do not believe words of outsider! Who knows what is on the mind of someone who goes against nature.}
{203}{}{Take it easy, you're overthinking this.}
{204}{}{I think you smoked the wrong herb, shaman.}
{205}{}{Calm down, old man. I haven't done anything bad to you. YET.}
{1205}{}{Calm down, old man. I haven't done anything bad to you. YET.}

#First meeting
{210}{}{...Look, see what these people brought us with all their progress!}
{211}{}{[Listen to the speech]}
{212}{}{[Interrupt the speech]}
{213}{}{We were united people, but fire worshippers brought us selfishness! We believed in one god, but they taught us to argue about religion! We wanted good for our tribesmen, but clans have once again taken path of hostility...}
{214}{}{Phoenix taught us to trade brahmin like mere objects. But brahmin are sacred! How much longer will we let outsiders destroy our ways? How many more conflicts within tribe will they cause just by their presence on our lands?}
{215}{}{And now look at Chatto. He learned to read pagan texts from the caravanners. Reading! He calls for trading brahmin for soulless technologies of outsiders. He and his friends want to trade our freedom for alliance with Phoenix. They want to give pueblo into hands of missionaries!}
{216}{}{Look at these pagan things - books, technologies, dubious and dangerous substances... We always rejected them because they are dangerous. Nothing is more valuable than life of our tribe and brahmin. And now Chatto, along with other youth, collects outsiders things and tries to learn and understand them. Dark Brahmin has taken minds of our youth!}
{217}{}{And this is our future? When did we fall so low that even our youth go against tribe? It is missionaries' fault! Drive them away! Our pueblo must remain ours...}
{218}{}{Oh, I see an outsider here now. Who are you? What are you doing in our tribe?}
{219}{}{Oh, I see a fire worshipper in the pueblo. What do you want? To take our children and our brahmin? We have already told those before you that the San Brahmin tribe cannot be bought, as you did with others. Go back to your stinking Phoenix, outsider!}
{220}{}{I am going to speak with your chief on behalf of the Villa. Nana let me in.}
{221}{}{Ah, Divine Brahmin of Peace! If Nana lets outsider in, there must be reasons. Alright, go ahead. But know that nothing will escape my eagle eye. I will watch your every step in pueblo.}
{222}{}{Thank you, Mangas. Please don't be angry with me for my intrusion.}
{223}{}{You've gone completely nuts in your old age. Leave me alone and get out of my way.}
{224}{}{See you, Mangas.}
{225}{}{[Continue]}

#Repeat dialogue
{230}{}{Greetings, outsider from Villa.}
{1230}{}{Greetings, woman from Villa.}
{231}{}{Your dark spirit on land of my tribe worries me.}
{232}{}{See you, shaman.}

{240}{}{Who are you?}
{241}{}{My name is Mangas. I am chief of western clan.}
{242}{}{Nice to meet you, Mangas, chief of the western clan.}
{1242}{}{Nice to meet you, Mangas, chief of the western clan.}
{243}{}{Are you the leader here, chief?}
{244}{}{You speak of high Chief Geronimo. He is in Sanctuary. Elders of each clan gathered in San Brahmin and chose him as our high Chief.}
{245}{}{Then why are you here, and not in the west?}
{246}{}{Struggle with Phoenix forced whole tribe to gather in San Brahmin to defend our freedom and our ways. This pueblo has also always been seasonal refuge during dust storms and droughts.}
{247}{}{Did you build this pueblo? It looks very old.}
{248}{}{There have always been ruins here, for as long as I can remember. Sand covered them over many generations, and no one knows what this place was before. Now it is main camp.}
{249}{}{Alright, but we'll deal with this later.}

{250}{}{What is happening here?}
{251}{}{Chatto and some other boys gather forbidden items. I found them and I will burn them so that others do not fall under their spell. And do not dare bring us new ones. It is not your concern, outsider from Villa.}
{1251}{}{Chatto and some other boys gather forbidden items. I found them and I will burn them so that others do not fall under their spell. And do not dare bring us new ones. It is not your concern, woman from Villa.}
{252}{}{I see.}
{253}{}{But what's wrong with these old things?}
{254}{}{We wander desert and live off what it provides. Our people and our herds are only things of value. The youth have no business with things of Old World. They are useless and unsafe.}
{255}{}{I see. Can I take these things then?}
{256}{}{That's a bunch of nonsense. These are just old things, they're everywhere in the ruins.}
{257}{}{But we do not live in those ruins! We wander Sonora desert. Our people and our herds are only things of value to us. Youth have no business with things of Old World. They are unsafe.}
{258}{}{I see. How about a trade? I can take them back to the ruins.}
{259}{}{You're doing the right thing. At Villa we need more people like you, shaman Mangas. Accept my words of respect.}
{260}{}{Hmm. If you are truly from Villa I've heard about, then perhaps I should treat you with more good will. Maybe our tribes have something in common.}
{261}{}{Don't burn these things. Let's trade and I'll take them away?}
{262}{}{I do not care what happens to forbidden items. It is much more important to punish dissenters and show others truth. But I can trade if you have something to offer.}
{263}{}{I think we can make a deal.}
{264}{}{These things really are quite dangerous.}
{265}{}{That is what I speak of! The outsiders' things bring disease, discord, or death.}
{266}{}{Burn everything! Immediately! Especially this one. [Point to the grenade]}
{267}{}{You are doing the right thing for your tribe.}
{268}{}{Do you want to trade for something useful?}
{269}{}{Look, this thing is imbued with demonic power! Destroy it immediately! [Throw the grenade into the fire]}

{270}{}{What's the conflict with the missionaries all about?}
{271}{}{They bring turmoil and discord to tribe. Their soulless technologies go against our ways, and with their weapons, Outsiders will try to conquer us and force us to work. Even firewater has become subject of discord.}
{272}{}{Got it. May I ask you something else?}
{273}{}{Turmoil and discord? Within the tribe?}
{274}{}{Missionaries of Phoenix want alliance and place near pueblo. Chatta and youth echo them, while others, like me, wish to drive them away.}
{275}{}{What kind of weapons do the missionaries have?}
{276}{}{Missionaries have firearms and strong metal armor. We cannot resist with our spears against such an army. Only cunning and knowledge of wasteland help us fight such strong enemy.}
{277}{}{What soulless technologies are you talking about?}
{278}{}{Old things, whose power comes from other old things. You call them "bat-teries" and "rad-ia-tion". For long time, no one in tribe dared to even touch these things. But now in Phoenix and Two-Sun they make them as easily and skillfully as we make bags from brahmin leather.}
{279}{}{What about firewater?}
{280}{}{This bitter, smelly liquid came to us from Phoenix. They call it 'tequila'. It clouds mind like Dark Brahmin. Those who drink it do strange things. I try to burn all supplies I find, but it is useless. As long as Phoenix makes and sells this drink to tribe, its evil will not fade.}
{281}{}{There must be a... factory or something making this tequila in Phoenix.}
{282}{}{Yes, and I have long looked for person who will find and destroy this place... this 'factory'. Without firewater, it will be easier for our tribe to resist outsiders. Find it and destroy it, and I will reward you generously.}
{283}{}{Alright. I'll do it.}
{284}{}{I will offer sacrifices to Divine Brahmin to guide and protect you on your journey. Good luck, my friend.}
{285}{}{Goodbye, Mangas.}
{286}{}{Wait, I want to ask something else.}
{287}{}{There's probably plenty of security there. And I don't even know where this 'place' is. Nope, I won't get involved with this crazy idea.}
{288}{}{Then go. You waste our time.}

{290}{}{Rejoice, Mangas! The tequila production in Phoenix is completely destroyed.}
{291}{}{Divine Brahmin must have helped you in this difficult task. Now I see that I was wrong about you. Not all outsiders try to conquer or rob us. Thank you, my friend from Villa.}
{292}{}{You're welcome.}
{293}{}{You mentioned a reward?}
{294}{}{You deserve respect and reward. Take these old things that I took from wayward tribesmen. I'm sure you will find use for them.}
{295}{}{Well, well, nuclear batteries, stimpaks, RadAway, and a bunch of caps... Quite good.}

{300}{}{...And this is our future? When did we fall so low that even youth go against tribe? This is fault of missionaries from Phoenix...}
{301}{}{It's too late to shout about freedom, Mangas. The chief has made an alliance with Phoenix. Accept it.}
{302}{}{I look to future of tribe with sorrow. It is shrouded in mist. We are like lost brahmin, separated from herd. Sad. Very sad.}
{303}{}{Uh-huh. Goodbye.}

{310}{}{I want you to support an alliance with the Phoenix missionaries.}
{311}{}{You must be broken in your mind, my friend. I try to drive the outsiders from our land with spells and clear minds of my tribesmen. And you ask me to stop and submit to will of Brahmin of Fate.}
{312}{}{Exactly.}
{313}{}{On second thought, it does sound crazy.}
{314}{}{What's wrong with you, outsider from Villa? It seems your village and our tribe are on same side of warpath. Is that not so?}
{1314}{}{What's wrong with you, woman from Villa? It seems your village and our tribe are on same side of warpath. Is that not so?}
{315}{}{Unfortunately, Mangas, you are detached from reality. The world is changing, and we can no longer live as we used to.}
{316}{}{Now you reveal your true face. If your tribe is so weak, let it be. But WE will not bend to outsiders from Phoenix!}
{317}{}{You will. Mark my words.}
{318}{}{You know best I guess. And I'm leaving.}
{319}{}{Unfortunately, Mangas, you are detached from reality. The world demands change. Otherwise, the tribe will be erased from the face of the earth.}
{320}{}{Strong words. They make my knees tremble with fear. But if we bend to New World, we will disappear anyway. Is that not so?}
{321}{}{Make an alliance with Phoenix and you will preserve your traditions. Remaining with the Rangers will only doom you to a war that ends in total defeat.}
{322}{}{I don't know. Decide for yourself. Goodbye.}
{323}{}{The tribe still manages to resist the missionaries and raiders. But their strength grows, and oppresses us more and more. Even united, the tribe barely holds on in San Brahmin.}
{324}{}{So be it. For sake of saving my clan, I will support an alliance. But I will also keep our alliance with Rangers. If threat appears, we will break all agreements.}
{325}{}{A reasonable decision.}
{326}{}{You have no choice. Phoenix will win anyway.}
{327}{}{Trust me. The Rangers are not your friends, and Phoenix will win anyway. You have no choice, or you, and your people, will perish in the sands.}
{328}{}{I listen to your words and become more and more dismayed... Is it really so bad that even Villa is ready to bend to Phoenix? Then we truely have no choice.}
{329}{}{I don't even know anymore, Mangas... I need to gather my thoughts.}
{330}{}{Of course. Until you change my mind, I will support alliance with Rangers. They wish us well.}
{331}{}{Alright. Goodbye.}
{332}{}{What if I bring you evidence of their treachery?}
{333}{}{Well, I will listen. But do not dare lie to me.}
{334}{}{Alright. Goodbye.}
{335}{}{The Rangers are defeated. Their dam is destroyed.}
{336}{}{Oh, why is Divine Brahmin of Fate so cruel!}
{337}{}{Now they're busy with their own survival. I doubt they'll be able to offer you much help.}
{338}{}{The Rangers have already destroyed the Jackal tribe. You could be next.}
{339}{}{An entire tribe was destroyed? Oh, why is Divine Brahmin of Fate so cruel!}
{340}{}{To these tough guys, you're all just savages.}
{341}{}{A convoy of peaceful settlers passed through your lands on the way to Garage City. The Rangers attacked and robbed them.}
{342}{}{What strange things Divine Brahmin of Fate has in store!}
{343}{}{The settlers simply refused to heed their demands. They do this to everyone who doesn't submit to them.}
