{100}{}{You see the elder Genaro.}
{101}{}{You see a shaman in traditional attire.}
{102}{}{Go in peace, strange iron spirit.}

{200}{}{Greetings to you and your tribe. Are you the one people in San Brahmin whisper about? I don't know how to treat you, but I don't mind your presence.}
{201}{}{Really? Pretty trusting for a savage.}
{202}{}{Great. You talk a little different than your fellow tribesmen, old man.}
{203}{}{I often deal with outsiders from the east, unlike the other clans of the tribe. Time will tell if you can be trusted.}
{204}{}{Got it. Thanks for the hospitality.}
{205}{}{Hmph. Not exactly the warmest welcome, huh?}

{210}{}{That thing you are riding spooked all my brahmin! Next time, choose another road, fool.}
{1210}{}{That thing you are riding spooked all my brahmin! Next time, choose another road, woman.}
{211}{}{Sorry about that. Didn't mean to scare them.}
{1211}{}{Sorry about that. Didn't mean to scare them.}
{212}{}{That's your problem. Not my fault your brahmin are so skittish.}

{220}{}{I see you are not planning to leave the pueblo. What keeps you here, friend?}
{221}{}{I see you are not planning to leave the pueblo. Speak your mind.}
{222}{}{Greetings, friend of the eastern tribe. How can I help you?}
{223}{}{Goodbye, Genaro.}

{230}{}{I want you to support an alliance with the Phoenix missionaries.}
{231}{}{Unlike the other elders, I have no ill will towards outsiders from Phoenix. My clan has spent much time next to them, engaging in trade. But I am not ready to stand against the rest of the tribe. Maybe the time has not yet come.}
{232}{}{If we don't convince the elders, there will be war.}
{233}{}{You underestimate the tribe. Our warriors have fought many battles across the Sonoran wastes. The Phoenix army? They'll be tangled up in this war for ages, if they've the courage to press on.}
{234}{}{Your words are pretty convincing. Forget I said anything.}
{1234}{}{Your words are pretty convincing. Forget I said anything.}
{235}{}{You are dooming your tribe to war. Mark my words.}
{236}{}{Maybe it's your voice that's needed to change things. You don't want war with Phoenix, do you?}
{237}{}{The tribe can defend itself, but this war will be endless. And someday it will end in defeat against the growing technologies of the missionaries.}
{238}{}{So you agree with me?}
{239}{}{I myself do not mind trading with Phoenix. The other elders do not understand that the world has changed. It's better to enter the new era now with full strength than to doom our people to an endless war. You can count on my support at the Council of Elders.}
{240}{}{You're making the right choice, Chief Genaro.}
{241}{}{Well, I get your point...}
{242}{}{You saved the children and livestock from the evil spirit. How can I refuse your request after that?}
{1242}{}{You saved the children and livestock from the evil spirit. How can I refuse your request after that?}
{243}{}{So, can I count on you?}
{244}{}{Perhaps the Divine Brahmin punished me by taking the life of the sacred brahmin right before the celebration of the Day of the Sun. This is a sign. He shows me that I have chosen the wrong path.}
{245}{}{Now you know what to do, don't you?}
{246}{}{Great. But let's not rush things. See you later.}
{247}{}{This is, uh... sad. But let's not rush things, okay?}

{250}{}{Tell me about yourself.}
{251}{}{I am an elder of the eastern clans of our tribe. And my name is Genaro.}
{252}{}{Hello, Elder Genaro.}
{253}{}{And who is in charge of the others?}
{254}{}{The supreme chief of the tribe is Geronimo. He is a wise and experienced warrior, a great unifier of the tribe. You will find him in the large house with columns.}
{255}{}{What are you doing here?}
{256}{}{I spend much time in San Brahmin. I need to watch over the brahmin after their grazing, prepare them for their fate, and in the end, I organize celebrations on the Day of the Great Sun. And I have more and more work; I am bent by the weight of my labors.}
{257}{}{I see.}
{258}{}{Maybe I can help you?}
{259}{}{It seems you have worked with corn before? So, working with the land should not be a burden for you. Take a shovel in the pen and clean it of... brahmin droppings. The brahmin must be kept clean while in captivity. Especially those I have chosen for the celebration of the Day of the Sun.}
{260}{}{Alright. I'll do it. I hope you'll at least feed me with fresh brahmin meat for this.}
{261}{}{What? Clean up after the brahmin?}
{262}{}{Is this not a usual task for you? Well, I have no other work to offer. You are unlikely to cope with tanning hides or caring for the brahmin. Frankly, I try not to let outsiders into the pen at all. It's a pity you do not appreciate the trust I've shown to you.}
{263}{}{I think you're just mocking me.}
{264}{}{The pen is cleaned.}
{265}{}{I see. You have done well.}
{1265}{}{I see. You have done well.}
{266}{}{Are you kidding? The pen's clean but I'm covered in brahmin shit!}
{267}{}{Oh, thanks, I love doing a flawless job.}
{268}{}{For such work, it's no trouble to offer you food and a place to sleep in my tent. Take this jerky. It satisfies hunger on the road and keeps for a very long time.}
{269}{}{Thanks.}
{270}{}{You better not be having a laugh at my expense.}

{280}{}{In the Villa, we heard rumors about a tribe that herds two-headed cattle.}
{281}{}{Hmm?}
{282}{}{These stories caused a lot of confusion. How did you manage to tame the wild brahmin?}
{283}{}{Oh, forget it.}
{284}{}{They weren't always like this. Several generations ago, brahmin were ordinary domestic animals. Legends say that the Heavens punished people for their transgressions, making the animals wild.}
{285}{}{Continue, elder Genaro.}
{286}{}{The brahmin scattered across the desert, refused to return to the pens, and hid from people. Their temperament became wild. But our ancestors tamed some brahmin through prayers and offerings to the Divine Brahmin.}
{287}{}{Thanks for the story.}
{288}{}{Why does a brahmin need a second head?}
{289}{}{(shrugs in surprise) The ways of the Divine Brahmin are inscrutable. But I believe that two brahmin merged into one body for better protection against people and beasts.}
{290}{}{Makes sense. Two heads are better than one.}
{291}{}{Divine explanations for common deformities. There's something wrong with that...}

{300}{}{Can I buy a brahmin here?}
{301}{}{Hold on to your ridiculous caps. Because of the war, we have halted the trade of brahmin, as well as meat and hides.}
{302}{}{Well, that's too bad. Can we discuss something else?}
{303}{}{The war is over, and trading has resumed. Do you want to buy a whole brahmin? It will cost you very dearly.}
{304}{}{Yes, I need a whole live brahmin.}
{305}{}{There are only three brahmin for sale in the pen - Breezy, River, and Sierra. But first, show what you have for trade. Then take this fruit and give it to the brahmin you fancy.}
{306}{}{Thanks, Genaro.}

{310}{}{Tell me, what's this Buried City that people talk about?}
{311}{}{Do not go there alone. That place is troubled by dark spirits. Sometimes animal bones are found there, and occasionally even human remains. The spirits cannot reveal the secret of this place to me.}
{312}{}{Is that why you forbid children from going there?}
{313}{}{Yes. Who knows what ancient evil lurks in the dark and winding catacomb of the old pueblo?}
{314}{}{Alright. Thanks for explaining.}
{315}{}{Here comes our hero. I know of your deeds in the Buried City. The children confessed. What did you find there?}
{1315}{}{Here comes our heroine. I know of your deeds in the Buried City. The children confessed. What did you find there?}
{316}{}{I found a monster. It was preying on people and brahmin.}
{317}{}{A monster! We had long been trying to understand who was stealing our cattle, but this dark spirit skillfully evaded my eagle vision. And yet it exists.}
{318}{}{The 'dark spirit' has been dispatched. It won't trouble you any longer.}
{319}{}{Praise the heavens! The Divine Brahmin himself must have sent you to us. Thank you, friend. We will remember your deeds for generations.}
{320}{}{Oh yes, I can already see the children gathered around the fire, and the elder in the center telling them about me... But I must go. There are still many lives to save.}
