{100}{}{You see Antonio.}
{101}{}{You see a local boy in wrinkled and dirty clothes, his eyes full of worry.}
{102}{}{This crown was for Lucia. I collected it for her.}

#First dialogue
{200}{}{What do you want, gringo?}
{201}{}{Oh, you speak English?}
{202}{}{A little. I'm Antonio. My parents were from the north, so I understand a bit of your language.}
{203}{}{I guess I'm lucky. How come your in here? Aren't you joining the celebrations with everyone?}
{204}{}{I don't like this holiday. I wish it would end.}
{205}{}{Why?}
{206}{}{How can you celebrate a Day of Life when so many people have died? This old man and everyone else are just happy they weren't the ones who died. Bastards.}
{207}{}{Can't argue with that. Only a bastard would thank a saint who allowed many to die.}
{208}{}{Exactly! I like you, gringo.}
{209}{}{Okay, I haven't looked around here yet. See you.}
{1209}{}{Alright, I haven't looked around everywhere yet. See you.}
{210}{}{Hey, don't be sad and ruin the holiday. Everyone deserves to be happy.}
{211}{}{Yeah...}
{212}{}{Hmm. Well, I'm going to have some fun. See you.}

#Re-dialogue
{220}{}{Hey, hi!}
{221}{}{Hey, gringo.}
{222}{}{What do you want, gringo?}
{223}{}{See you.}

{230}{}{Did you know someone stole the crown?}
{231}{}{No, I don't know anything about that.}
{232}{}{Okay. I believe you.}
{233}{}{But you did mention wanting to stop the celebration.}
{234}{}{(silently looks down)}
{235}{}{Is your silence a confession?}
{236}{}{I didn't want Lucia to be crowned.}
{237}{}{Is that so bad?}
{238}{}{You're a gringo, you don't understand! If she wears the crown, I'll never be able to... be her... And she... I love her...}
{239}{}{Boy, I think you're being selfish.}
{240}{}{Maybe so. I don't care!}
{241}{}{So where's the crown, kid?}
{242}{}{I buried it at the center of the monument so no one would find it.}
{243}{}{What kind of monument?}
{244}{}{An ancient one. Lucia and I met there secretly and even scratched our names on the pillars. So I thought of there right away.}
{245}{}{Good thing you confessed. Makes it easier for me. See you.}
{246}{}{Nobody cares about your reasons. Tell me where you hid the crown!}
{247}{}{Remind me where the crown is again.}

{250}{}{Lucia is safe now. I was so desperate, I thought I lost her forever. Thank you.}
{251}{}{Glad to help.}
{1251}{}{Glad to help.}
{252}{}{So that's why you didn't join the celebration? You wanted to save her?}
{253}{}{Yes. I even wanted to go to El Diablo instead of Lucia, but the headman wouldn't let me. Said the village needed more men to work.}
{254}{}{You were in a real bind.}
{255}{}{But it's over now. Here, take this comic book. I don't know how else to repay you.}
{256}{}{Hmm, looks interesting, boy. It might come in handy on the road.}
{257}{}{Curious thing. I'll look at it on the road.}

{260}{}{I saw Lucia run from the church! What happened? Did you really kill El Diablo?}
{1260}{}{I saw Lucia run from the church! What happened? Did you really kill El Diablo?}
{261}{}{Don't worry, everything's under control.}
{262}{}{Please bring Lucia back!}
{263}{}{I'll try.}
{264}{}{No guarantees, boy.}
