{100}{}{You see Lucia.}
{101}{}{You see a girl in ceremonial attire, her expression solemn yet resolute.}
{102}{}{«Thanks for everything.»}
{103}{}{Muchas gracias.}
{104}{}{The crown has been returned to its rightful owner.}
{105}{}{I think this is yours. Take it and do with it what you want.}
{106}{}{It's too early to give this to you.}
{107}{}{Lucia has returned to the Santa Ana settlement.}
{108}{}{«This is where Antonio and I often met in secret. They forbade me to have a relationship with anyone.»}
{109}{}{«Quiet peaceful place. I loved sitting here and thinking about my fate.»}

{110}{}{}
{115}{}{«I think this is yours. Take it and do with it what you want.»}
{116}{}{«It's too early to give this to you.»}

{200}{}{Tu otra vez?}
{201}{}{There you are. And I've been looking for you everywhere.}
{202}{}{(turns away)}
{203}{}{...And I'm not the only one. Antonio is looking for you too.}
{204}{}{(turns halfway) Antonio?}
{205}{}{Yes, miss. He was looking for you.}
{206}{}{(falls to her knees and sobs) El Diablo... *sob* *sob* You don't understand, gringo. I lived for this.}
{207}{}{I don't know what you're saying in your language, but there's no point in getting upset. Let's go to the others.}
{208}{}{(grabs your sleeve) This is my fate! I've lost all sense of life!}
{209}{}{Are you saying you've been groomed for sacrifice your whole life? Then it's clear why you're struggling to accept freedom.}
{210}{}{(exhausted) Bueno. I'll go home. Let it be.}
{211}{}{That's good. I'll make sure you get home.}
{212}{}{Stay here, I'll check outside.}

{213}{}{(falls to her knees and sobs) El Diablo... *whine whine* No entiendes, gringo. Vivi para esto.}
{214}{}{(grabs your sleeve) Este es mi destino! He perdido todo sentido de la vida!}
{215}{}{(exhausted) Bueno. Me ire a casa. Que sea lo que tenga que ser.}


{220}{}{«You again, gringo?»}
{221}{}{«There you are. I've been looking for you everywhere.»}
{222}{}{(turns away)}
{223}{}{«... And I'm not the only one. Antonio is looking for you too.»}
{224}{}{(turns back halfway) «Antonio?»}
{225}{}{«He's the one, senora. He's the one who stole the crown from the ceremony to save you from death.»}
{226}{}{(falls to her knees and sobs) «But El Diablo... *sob* *sob* You don't understand, gringo. I've been prepared for this my whole life. I knew this day would come.»}
{227}{}{«Isn't it better now that you're free?»}
{228}{}{(grabs your sleeve) «This was my destiny! I had to go to El Diablo to save the rest of the townspeople!»}
{229}{}{«Then I understand why you're so disheartened. But in all my travels, I have never seen such devilry. No one sacrifices their loved ones to monsters.»}
{230}{}{(exhausted) «Okay... okay... I'll be okay. Come what may.»}
{231}{}{«That's good. I'll make sure you get home.»}
{232}{}{«Stay here, I'll check outside.»}

{240}{}{Voy.}
{241}{}{Follow me. I'll make sure you get home.}
{242}{}{Wait here and don't go anywhere.}
{243}{}{Let's move on.}
{244}{}{Estoy cansada.}
{245}{}{«I'm coming.»}
{246}{}{«I'm tired.»}

{247}{}{«Wait here and don't go anywhere.»}
{248}{}{«Let's move on.»}
{249}{}{«Follow me. I'll make sure you get home.»}

