{100}{}{You see Enrique.}
{101}{}{You see a tough-looking Mexican.}

{110}{}{}

#First dialogue
{200}{}{Hola. Name's Enrique. What brings you to our village?}
{201}{}{I just stumbled across this place by chance. Didn't mean to end up here.}
{202}{}{Not many wanderers come by these days. I'd ask more, but we're in the middle of a celebration. My daughter Lucia has the honor of being its 'queen'.}
{203}{}{What's the occasion?}
{204}{}{Day of Life. A day to thank the saints we're still breathing. At the end, we crown someone. It's a way to remember we're all in this together, out here in the wasteland.}
{205}{}{Sounds like a good tradition. I'll join the festivities.}
{206}{}{Strange tradition, but not my business.}

#Re-dialogue
{220}{}{Hola, gringo.}
{221}{}{Hola, amigo.}
{1221}{}{Hola, amiga.}
{222}{}{Adios, Enrique.}

{230}{}{Did you know the ceremonial crown is missing?}
{231}{}{That's strange. Never happened before. But it couldn't just vanish. Lots of folks around the table, especially kids.}
{232}{}{I see.}
{233}{}{You speak English well.}
{234}{}{Traveled a lot around Sonora. Picked it up here and there.}
{235}{}{You have a lot of kids here.}
{236}{}{Of course. Kids are our joy and our future, even if most don't make it to old age.}
{237}{}{What about Hilario? How old is he?}
{238}{}{He's our permanent headman. No surprise he's still kicking. He gets nastier with age, but he's the reason we're alive.}
{239}{}{Any interesting places in Sonora?}
{240}{}{Really? Can you show me some interesting places?}
{241}{}{Closest city is Casa Nueva. Further west, ruins of Puerto Penasco. Far to the south, the fort at Hermosillo. We've been here ten years, so not sure how things are now.}
{242}{}{I don't know what to say, Enrique. I'm shocked.}

{250}{}{Hey amigo! You know our secret now, right? What do you think?}
{1250}{}{Hey amiga! You know our secret now, right? What do you think?}
{251}{}{I don't know what to say. I'm just shocked.}
{252}{}{You're all crazy cultists here.}
{253}{}{Not my place to judge. Guess you had no choice.}
{254}{}{Figured you'd say that. When did we fall so low to sell our souls to the devil? But it wasn't always like this. I remember days without El Diablo. Bright, beautiful days...}
{255}{}{Now's your chance to start over.}
{256}{}{So he *is* dead, huh? What a relief! But Hilario won't just let it go. He'll lie, say El Diablo didn't die. Fifteen years of power has changed him. I want to drive this parasite out. Help me. Not everyone here is against him like I am.}
{257}{}{With pleasure. Watching him scurry out of the village will be fun. Go to the church, I'll follow.}
{258}{}{Let me talk to him. I think I can convince him.}
{259}{}{My involvement ended with the monster's death. Your problem now.}

{260}{}{Will you help us get rid of the old fraud?}
{261}{}{Sorry, your problem, not mine.}
{262}{}{I swear - one more thing and I'll take him out myself!}
{263}{}{Let me talk to him.}
{264}{}{Hilario is dead. He won't bother you anymore.}
{265}{}{Hilario is gone. He won't be back.}
{266}{}{Yes! Good riddance at last. Without the old man and the monster, Santa Ana will finally flourish, I can already see it before me. No more sacrifices. No more lies. Gracias, amigo. Here, take my pistol as a sign of gratitude. From now on, *you* will be the patron saint of our community.}
{1266}{}{Yes! Good riddance at last. Without the old man and the monster, Santa Ana will finally flourish, I can already see it before me. No more sacrifices. No more lies. Gracias, amiga. Here, take my pistol as a sign of gratitude. From now on, *you* will be the patron saint of our community.}
{267}{}{It's always nice to help people. Goodbye, Enrique.}
{268}{}{Maybe there's one last thing I can help with?}
{269}{}{You know, I'm the village headman now. I want to establish trade with Casa Nueva. We don't have much to offer, but we must be able to reach some kind of an agreement. Can you pass on our interest? If you could, tell them to send a caravan for negotiations.}
{270}{}{Okay, I'll do it.}
{271}{}{I doubt I'll end up there. Still, I'll keep it in mind.}
{272}{}{Haven't there been enough deaths? Maybe we shouldn't.}
{273}{}{If we don't stop him now, we'll keep making sacrifices for his vanity. The longer we wait, the harder it'll be to fix.}
{274}{}{Then let's not waste time. Let's go to the church!}
{275}{}{This ancient church has been defiled enough, don't you think? Do you really want to commit yet another sin?}
{276}{}{You're right. But if Hilario goes back to his old ways, it effects all of us.}
{277}{}{Glad you came to your senses. Let's just leave the old man alone.}
{278}{}{What are you talking about? One life weighed against the lives of the many. Let's go to church and end this!}
{279}{}{Don't give up too quickly. I want to convince Hilario without using force. Wait here.}
{280}{}{You were right - I had to get rid of Hilario. Which is what I did.}
{1280}{}{You were right - I had to get rid of Hilario. Which is what I did.}
{281}{}{What are you talking about? One life weighed against the lives of the many. Let's end this here and now!}
{282}{}{Casa Nueva is going through hard times. Forget about trading with them.}
{283}{}{Sad news. We'll have to survive without them. Gracias for the warning.}
{1283}{}{Sad news. We'll have to survive without them. Gracias for the warning.}
{284}{}{You're welcome.}
{285}{}{Hola, amigo. A caravan came from Casa Nueva recently. Gracias for your help.}
{1285}{}{Hola, amiga. A caravan came from Casa Nueva recently. Gracias for your help.}
{286}{}{So, here's the thing... Hilario is ALSO dead. Don't ask how it happened.}
{287}{}{Hilario fled when he realized his power was gone. Doubt he'll come back.}

{290}{}{How did you end up living this life?}
{291}{}{It's a long story. Started over fifteen years ago.}
{292}{}{Hmph. Anyway, let's change the subject.}
{293}{}{Tell me more.}
{294}{}{We were nomadic, wandering the Sonoran Desert for a place to live. One day, this monster found us. He stalked our caravan, dragging away one person or animal at a time. We couldn't fight or escape - too strong, too fast.}
{295}{}{Go on...}
{296}{}{This is too scary! I'm out of here.}
{297}{}{Then Hilario had the idea to sacrifice animals to save people. But soon, the cattle ran out. We started giving the old and sick. Eventually, they ran out too. But, by that time, El Diablo had gotten his fill and began demanding fewer sacrifices. So, we found a balance.}
{298}{}{I see.}
{299}{}{El Diablo also attacked wild animals and raiders who threatened us. We became his herd, and he ate us when he was hungry.}
{300}{}{But you kept sacrificing to him?}
{301}{}{Every few months, we'd give a sacrifice we raised for this purpose. Hilario turned it into a ceremony, preaching divine purification. So we lived with the devil, until you showed up, gringo.}
{302}{}{Well, I hope you can return to normal life. Time for me to go.}
{303}{}{Shame on you. All of you. At the Villa, we stick together. Hearing your story makes me want to return to my home. Goodbye.}
