{100}{}{You see the gang leader.}
{101}{}{You see one of the highwaymen. Looks like he's running the show here.}
{102}{}{We're leaving now. Give the mayor our 'deepest apologies'.}

{200}{}{You got guts, walking into our turf like this. Either yer' brave or a damn fool. Who the hell are you?}
{1200}{}{The Count is so pathetic he sends a woman to do his dirty work. Fine. But who the hell are you?}
{201}{}{I'm the last thing you'll see.}
{202}{}{Doesn't matter who I am. The mayor sent me to negotiate.}
{203}{}{Figures. Bustos is a coward. Always ready to sacrifice someone else. Let's see if he values his daughter.}
{204}{}{The mayor demands you release the hostage. Otherwise, you're dead meat.}
{205}{}{Bustos can't be trusted. He's as slimy as a snake. Tell him if he doesn't meet our demands, his daughter dies.}
{206}{}{What do you want?}
{207}{}{Screw talking. You deserve nothing but death.}
{208}{}{Ten thousand caps.}
{209}{}{Ten thousand? You couldn't scrape that together from the whole damn town.}
{210}{}{Not my prob'. The mayor can take his daughter's place if he can't pay.}
{211}{}{I'll tell him your demands.}
{212}{}{What's your problem?}
{213}{}{Your not from around here, are ya'? I'd know you otherwise.}
{214}{}{What does it matter?}
{215}{}{Caps don't matter to me. There's an old cemetery east of the city. Mass grave. That's where the folks of Casa Grande rest, 'cluding my parents.}
{216}{}{[Listen]}
{217}{}{They tried to make a peaceful life here. Worked tirelessly on the water pump an' the city. Then Bustos came, killed 'em, and took over. He slaughtered anyone who stood in his way.}
{218}{}{And now you want revenge?}
{219}{}{Sure, why would I lie? Just tell the mayor what I said. Not that he'll listen.}
{220}{}{I'll pass on your demands to the mayor.}
{221}{}{You're lying. I'll kill you to set an example...}
{222}{}{You sure you want more blood on your parents' land?}
{223}{}{I'm done talking. Bring me the mayor. I'll only speak to him.}
{224}{}{This city's already drenched in blood. There's finally some peace here.}
{225}{}{No more talking. You're dying now...}
{226}{}{You think I'm selfish to disturb it? How'm I supposed to live after the mayor drove me off my land? I eat scraps and rob caravans to survive, all 'cause of that bastard.}
{227}{}{So leave this path. Live in Phoenix or somewhere else.}
{228}{}{I don't think I can start over. Too late to change. But your words hit me. The girl can go. She's innocent. If the mayor's got any dignity left, let 'im face me in a duel, old-school style.}
{229}{}{I'm glad you saw reason.}
{1229}{}{I'm glad you saw reason.}
{230}{}{What did the mayor say?}
{231}{}{He put a bounty on your head. I'm here to collect.}
{232}{}{Nothing's changed. He'll let you leave if you release the hostage.}
{233}{}{What kinda bullshit is this? Think I won't see through you posing as a highwayman?}
{234}{}{Well I...}
{235}{}{You get a thousand caps and leave the city. Otherwise, you're dead.}
{236}{}{Amazing. Thought Bustos wouldn't give even ten caps...}
{237}{}{[More]}
{238}{}{(One of the goons interrupts the leader, they have a heated discussion) Ah... fine... your right... (returns to you) We accept. Give me the caps, and you can take the girl.}
{239}{}{Why would the Count be so nice to raiders? I think I'll just kill you and keep the caps for myself...}
{240}{}{Hold on. I'll get the caps.}
{241}{}{Here's the caps.}
{242}{}{Tell the Count we're leaving, and he'd better not send anyone after us.}
{243}{}{It'd be stupid to let that many caps go. I think I'll kill you and take them back.}
{244}{}{The Count keeps his word.}
