{100}{}{You see Gil McCord.}
{101}{}{You see a wiry, unshaven man with a very sharp gaze. He peers at you doubtfully from under his cowboy hat.}
{102}{}{Still hanging around, huh? Reckon you got no sense of fear at all.}

{200}{}{Well, if it ain't the executioner's executioner. Don't worry, partner, I know all about you. Should've put you down when you took out the first Los Panchos. Guess I underestimated your grit.}
{201}{}{I'm still full of surprises, Gil McCord.}
{1201}{}{I'm still full of surprises, Gil McCord.}
{202}{}{Then show me your hand, 'cause one of us ain't riding off into the sunset.}
{203}{}{I don't want to fight you.}
{204}{}{I'll be the one riding off, partner...}
{205}{}{Looks like you're one of those fools who never learns. Ain't no good or evil out here. Show mercy, and you'll catch a bullet in the back. That's the law of the wasteland.}
{206}{}{What a speech. But enough chit chat. I'll be taking your head to Bruce Turner...}
{207}{}{Let's go our separate ways, no need for bloodshed.}
{208}{}{So you can bushwhack me later? Not a chance.}
{209}{}{[Await attack]}
{210}{}{Alright then, let's settle this like real cowboys - a showdown.}
{211}{}{You got grit, I'll give you that. I accept.}
{212}{}{[Step out onto the road, ready for the showdown]}
{213}{}{I really don't want any more deaths on my conscience.}
{214}{}{What are you yammering about? You lopped off the heads of three guys in cold blood, and who knows how many more. Then carried 'em for miles, savoring the stench. Now you're saying you don't want another death? Save yer bullshit for someone who cares.}
{1214}{}{What are you yammering about? You lopped off the heads of three guys in cold blood, and who knows how many more. Then carried 'em for miles, savoring the stench. Now you're saying you don't want another death? Save yer bullshit for someone who cares.}
{215}{}{It wasn't quite like that. They did all the dirty work for me.}
{216}{}{(Pauses, then breaks into a grin) Ha! Just as I thought. You're a charlatan. Now skedaddle, you ain't worth my time.}
{1216}{}{(Pauses, then breaks into a grin) Ha! Just as I thought. You're a charlatan. Now skedaddle, you ain't worth my time.}
{217}{}{Big mistake. I'm not afraid to take you on...}
{218}{}{As you say, time to skedaddle.}
