{100}{}{You see Count Bustos.}
{101}{}{You see a man in a respectable but shabby suit. His gray temples seem to hint at a difficult past.}
{102}{}{I heard about such armor, but thought it was fiction.}
{103}{}{I won't tolerate this highway scum in my city.}
{104}{}{I advise you two to leave the city immediately.}

#First meeting
{200}{}{(As you enter the office of the local mayor, you immediately notice the unpleasant smell of alcohol. Looking around, you finally notice a man in a chair, wearily looking at you through his fingers. "Huh?" he grumbles after a brief pause.)}
{201}{}{Where is the mayor? I'd like to talk with him.}
{202}{}{(With a heavy sigh, the man in the chair frees himself from his bent position and leans back tiredly). He's right in front of you. But who are you?}
{203}{}{You're the mayor? You look more like a clerk who's blown all his salary at the bar.}
{204}{}{Let's get something straight. I am the legitimate mayor of this city. If you're not going to recognize local authority and accept local rules, then get out of Casa Grande immediately. My city doesn't need troublesome outsiders. Got it?}
{205}{}{Yeah, I see.}
{206}{}{Sorry, Mr. Mayor. I'm not going to cause any trouble.}
{207}{}{That's good. So where did you come from?}
{1207}{}{That's good. So where did you come from?}
{208}{}{My name is }
{209}{}{, I'm traveling.}
{210}{}{Okay, }
{211}{}{. And where are you from?}
{212}{}{Why is this so important?}
{213}{}{Because in a small town like this, everyone wants to know who you're dealing with and how much they can trust. And no one here knows you at all.}
{214}{}{No one should care about my origins.}
{215}{}{So, don't you want to accept the rules? You're walking on a dangerous path, stranger. Then explain to me what the hell you're doing here?}
{1215}{}{So, don't you want to accept the rules? You're walking on a dangerous path, missy. Then explain to me what the hell you're doing here?}
{216}{}{I'm from a small village far away from here. We just call it Villa.}
{217}{}{Never heard of it. But let's assume this is true. What are you doing in my city so far from home?}
{218}{}{I'm just traveling. Can I spend the night at your place?}
{219}{}{I don't mind. Usually visitors spend the night near the water pump, in the barracks of the caravan workers.}
{220}{}{Thanks, Mr. Mayor.}
{221}{}{What kind of town do you have if there isn't even a motel? Okay, a barracks will do. Goodbye, mayor.}
{222}{}{Bustos. My name is Alfred Bustos. Now go. I've wasted too much time on you.}
{223}{}{[Done]}

{224}{}{I'm looking for my people. They were captured by slave traders.}
{225}{}{(raises one eyebrow) Slaves? Is there anything else you're counting on?}
{226}{}{Have you heard anything about them?}
{227}{}{Slave owners sometimes lead their slaves through my city. But I don't ask where they get them from.}
{228}{}{Where are they taking them?}
{229}{}{Some are being taken south to work. Others are just dragging their luggage... Listen, stranger... what's your name?}
{1229}{}{Some are being taken south to work. Others are just dragging their luggage... Listen, woman... what's your name?}
{230}{}{Never mind.}
{231}{}{.}
{232}{}{Slave owners are a serious force. If they took your family, then you have no chance of restoring their freedom. Besides, my city lives off the caravan people. Don't you dare muck up this order.}
{233}{}{I'm not afraid of the slavers or you. Goodbye, mayor.}
{234}{}{I just want my family back. You must understand this, Mr. Mayor.}

{235}{}{There are no vacancies in the city. You can spend the night in the barracks with caravan workers near the water pump.}
{236}{}{Bustos. My name is Alfred Bustos. Welcome to my city.}
{237}{}{I need the mayor of this city. I'm from the Church of the Holy Fire.}
{238}{}{What a surprise. Usually I am warned about the appearance of an ambassador from your church.}
{239}{}{Come in. Make yourself at home.}
{240}{}{What is it this time?}
{241}{}{You again? What is it this time?}
{242}{}{You again? I told you to get out of my town.}
{243}{}{Goodbye, Count Bustos.}
{244}{}{(As you enter the office, you find the local mayor leaning tiredly on the table. In his other hand he holds a bottle of alcohol. "Oh..." he says, seeing your colorful robe.) What a surprise. I'm usually warned about any visits of ambassadors from your church.}
{245}{}{I'm just passing through here.}
{246}{}{Of course. Make yourself comfortable. Heading to Two-Sun? Is there anything I can do to help?}
{247}{}{I'm interested in a slave convoy. Perhaps one of these passed here recently.}
{248}{}{Lately the Tinsmiths have been collecting slaves for some important task. Several such caravans passed through my city. But I don't ask where they got the slaves from.}
{249}{}{So, Two-Sun... Thanks, Mr. Mayor. See you.}

#Bath
{250}{}{I need to talk to you about the bathhouse.}
{251}{}{That old abandoned building across the street? What do you care about it?}
{252}{}{Just idle curiosity. I won't distract you anymore, Mr. Mayor.}
{253}{}{Well, there is a man hoping to reopen it.}
{254}{}{He and I have already discussed this. In our small town everyone knows each other. People here have been building relationships for years, and many are uncomfortable with a stranger with a questionable past in the neighborhood. I won't tolerate scammers in my city.}
{255}{}{Hmm. Where then is the real owner of the bathhouse?}
{256}{}{Must have been eaten by radscorpions. These creatures are rampant in our area.}
{257}{}{Well that's too bad. I'll have to tell him your refusal.}
{258}{}{Then before you go, remember that I don't like people prying into others' business.}
{259}{}{Ah, okay, I'll remember that.}
{260}{}{I see. I could rid you of this guy if you like.}
{261}{}{Sounds good. I'll pay 100 caps, but don't mention my name anywhere. I don't want my reputation to be damaged.}
{262}{}{You can count on me, Mr. Mayor.}
{263}{}{In that case, I want to buy the rights to the bathhouse for 250 caps.}
{264}{}{Well, that's fair. Bring in the caps, I'll draw up a bill of sale for the bathhouse.}
{265}{}{Okay, see you later.}
{266}{}{Here are the caps, Mr. Mayor.}
{267}{}{I hope you know what you're signing up for.}
{268}{}{Thanks, Mr. Mayor.}
{269}{}{He has a letter confirming his ownership of the bathhouse.}
{270}{}{Nobody knows where he got it. Stop testing my patience.}
{271}{}{Sorry, Mr. Mayor.}
{272}{}{That's pretty unfair of you.}
{273}{}{He has a letter confirming the rights to the bathhouse. And I confirm his identity.}
{274}{}{Okay, you managed to convince me. But let this rogue know that no one was waiting for him here.}
{275}{}{As you say, Mr. Mayor.}
{276}{}{That's not very neighborly of you.}
{277}{}{This has something to do with the recent war in Casa Grande, doesn't it? Are you afraid of revenge?}
{278}{}{(sigh) Although I didn't kill the owner of the bathhouse, others did... amid the war I started.}
{279}{}{I think the guy already knows. But it seems like he's only interested in business.}
{280}{}{Then this is a big risk for you. I'll tell the guy you refuse.}
{281}{}{Is this true? Then it's worth talking to him. Although this is unlikely to atone for my sins.}
{282}{}{Great. I'll go to talk with him.}
{283}{}{We know each other well. I guarantee he can be trusted.}
{284}{}{Then you should talk to him. Although this is unlikely to atone for my sins.}
{285}{}{Great. I'll go to encourage him.}
{286}{}{? Isn't it surprising that a person with such a name can't sit still. }
{287}{}{If this is a joke, it's a bad one. If something happens to you, they'll think about me, because no one will realize that there are two people with the same name in the city. This will be very unpleasant... }

{290}{}{The that guy won't bother you anymore.}
{291}{}{Very good. I don't like getting my hands dirty.}
{292}{}{[More]}
{293}{}{All work should be paid decently. Here's your 100 caps. But remember, I had nothing to do with this little incident.}
{294}{}{No one will know anything, Mr. Mayor.}
{295}{}{It's not in my best interest to ruin relationships with potential clients.}

#Stop the dialogue
{300}{}{I don't know what you want to achieve, but you've added more enemies to your list. Get out of my city. I don't need assholes like you.}
{301}{}{[Exit building]}
{302}{}{(Security escorts you outside.)}

{308}{}{Hey. Can you believe it? Some idiot's been digging up graves in our cemetery. Maybe you know who's behind it?}
{309}{}{Someone digging up graves? I don't know shit about it.}
{310}{}{I remember you. After you appeared, dug up graves were discovered in the cemetery.}
{311}{}{Strange coincidence, isn't it?}
{312}{}{So what? Are you accusing me of something?}
{313}{}{I don't believe in coincidences. If even one piece of evidence appears against you in this case, then severe punishment awaits you. Understand this and don't do anything stupid.}
{314}{}{Ooh, I'm shaking.}
{315}{}{It looks like you're out of your mind to act this way around a city official. Usually there is a lot of leniency towards fools, but not in this city. We are tired of endless problems. So don't test my patience. Got it?}
{316}{}{I see.}
{317}{}{I have nothing to do with this, Mr. Mayor.}
{318}{}{Okay. For now we'll consider it this way. Don't disappoint me.}
{319}{}{Of course, Count Bustos. No problem.}

{320}{}{Security says you fixed the street light?}
{1320}{}{Security says you fixed the street light?}
{321}{}{Yeah, I did.}
{322}{}{I don't really understand why you did this. But if you wanted to make an impression, then you succeeded. Thanks.}
{1322}{}{I don't really understand why you did this. But if you wanted to make an impression, then you succeeded. Thanks.}
{323}{}{Aren't you going to give me something for this?}
{324}{}{I didn't ask you to fix any street lights. But you can take some clean water as a reward.}
{325}{}{Thanks, Mr. Mayor.}
{326}{}{Is this the extent of your gratitude? Yeesh.}
{327}{}{I just like tinkering with old technology. You're welcome.}
{328}{}{You have increased your status in the eyes of the mayor, and therefore the rest of the city.}
{329}{}{Yeah.}

{330}{}{Your arrival's nothing but trouble.}
{331}{}{Really?}
{332}{}{What are you talking about?}
{333}{}{The body of one of the residents was found near the train station. Do you know anything about this?}
{334}{}{No, I don't know shit.}
{335}{}{Okay. We have yet to find out what happened there. Don't to hide anything if you know something. Now go, I have a lot of work to do.}
{336}{}{[Leave the mayor alone]}
{337}{}{One of the residents has gone missing. She was last seen near the train station, where she was catching iguanas. Do you know anything about this?}
{338}{}{The radscorpions probably devoured her. There are plenty of them there.}
{339}{}{Most likely. And yet you happen to know that radscorpions lurk there... If you find out anything, be sure to let me know. Now go, I have a lot of work to do.}
{340}{}{She was never meant to make it to the city. Radscorpions are to blame for this.}
{341}{}{That's it. Well, it sounds plausible. You can go for now.}
{342}{}{[Done]}

#Questions
{350}{}{I'm looking for a Tinsmith who was sent to you as an ambassador.}
{351}{}{Didn't he go back to Two-Sun? How would I know where he is?}
{352}{}{He was here?}
{353}{}{Yes, but he disappeared without saying a word. I thought he just left.}
{354}{}{And you didn't see anything strange in that?}
{355}{}{The Tinsmiths consider us mere mortals to be something close to savages. They're strange people, you never know what to expect from them. So, I didn't worry about the quiet departure of our guest. I'm sure he's already among his own.}
{356}{}{No, he didn't return to Two-Sun. Master Hard asked me to find him.}
{357}{}{Ah, I see. Well, I told you everything I know. You can ask around somewhere else.}
{358}{}{I will. Goodbye.}
{359}{}{I think there's something fishy here. I'll be surprised, mayor, if his disappearance has nothing to do with you.}
{360}{}{Seems the locals don't like Tinsmiths. Who would wish him harm?}
{361}{}{Stop right there, mercenary. We are indebted to the Tinsmiths for repairing the water pump and regular caravans. None of the locals would even think of harming them.}
{1361}{}{Stop right there, mercenary. We are indebted to the Tinsmiths for repairing the water pump and regular caravans. None of the locals would even think of harming them.}
{362}{}{Still, I'll check this story out. Goodbye.}
{363}{}{That kinda confidence just breeds more doubt, Mayor. Hope it doesn't turn on you.}
{364}{}{Don't you think it's strange that he disappeared?}
{365}{}{Did he really make it to Casa Grande?}
{366}{}{He never returned to Two-Sun. They asked me to find him.}
{367}{}{Looks like I'm wasting my time with you. I'll go look for the Tinsmith elsewhere.}
{368}{}{I'm sure it is. Sorry for distracting you from things.}
{1368}{}{I'm sure it is. Sorry for interrupting my work.}
{369}{}{Where did he stay during his visit?}

{370}{}{I want to ask about the city, I don't know it well yet.}
{371}{}{Casa Grande is my treasure. What do you want to know?}
{372}{}{All you need to know is the direction to exit the city.}
{373}{}{No one knows Casa Grande better than I do. What do you want to know?}
{374}{}{Now I know enough. Goodbye.}
{375}{}{Let me take a little more of your time.}
{376}{}{In the former moonshiner's shack to the east. Tinsmiths don't like to be around... "ordinary" people.}

{380}{}{What is there to do in this city?}
{381}{}{Casa Grande is a small town. We used to have a saloon, famous throughout the area for its home-brewed booze and old music. But the bar is closed and the music machine is broken, and now people entertain themselves.}
{382}{}{What happened?}
{383}{}{A big shootout in the bar. But that's a thing of the past. Just keep in mind that the bar is closed.}
{384}{}{We both know it wasn't exactly a shootout.}
{385}{}{You talk too much. Then, in the bar, my people took out an enemy clan. The bartender got hit by a stray bullet. I'm sorry, he was a nice guy.}
{386}{}{Thanks for your honest answer. I think it's best to change the subject.}
{387}{}{Wow, its own booze?}
{388}{}{Yes, locally made. Perhaps you've never tried this wonderful drink? The moonshiner supplied us with beer and traded it with Phoenix. Eh, if it weren't for those damn radscorpions, he would still continue to bring good income to the treasury.}
{389}{}{I've seen tequila production in Phoenix before.}
{390}{}{Really? Sometimes caravans bring fire agave syrup from the south for Phoenix. For our brewer, this competition was a tough pill to swallow. And actually, now we ourselves are buying this Phoenix swill.}
{391}{}{Enough about the sad stuff. Let's talk about something else.}
{392}{}{Is there a store here?}
{393}{}{If you need water, go to the water pump. We take the rest of the goods from the caravan workers at the parking lot nearby.}
{394}{}{Why are there so many caravans here?}
{395}{}{Because we have a lot of water and we are halfway between Phoenix and the Two-Sun settlement. Good situation, except for the damned highwaymen.}
{396}{}{Rumor has it that the Tinsmiths are no longer in business. How will this affect Casa Grande?}
{397}{}{Well, there are other settlements in the south. And we can still trade water. Also, having heard this story, many raiders and highwaymen rushed south. So we'll stay afloat for now, but what happens next?}
{398}{}{They say the Fire Church in Phoenix has been destroyed.}
{399}{}{Yes, and that's a problem. The Church, in a sense, actively supported this caravan route. Without it, there'll be fewer caravans. But in time, someone will eventually take their place.}
{400}{}{What are these highwaymen?}
{401}{}{You see all sorts of rabble along Interstate 10. They're just raiders who rob caravans and other travelers, rather than settlements. Hitting the caravans causes us to suffer losses.}
{402}{}{Did you try to catch them?}
{403}{}{Who? Two dozen disparate and constantly changing gangs? This fight will never end. If you kill a few, a swarm of others will take their place. It's more important to take care of security inside the city.}
{404}{}{Let's forget about the highwaymen for now, there are other questions.}
{405}{}{I'm interested in that water pump.}
{406}{}{Talk to Joe Sullivan at the pump about it. He knows it like the back of his hand.}
{407}{}{Talk to someone at the pump about it.}
{408}{}{Okay, I'll check there later.}
{409}{}{Great idea, I'll go there right now.}
{410}{}{Tell about this to Sullivan. Who is he?}
{411}{}{I don't discuss my people with strangers. If you want to know Sullivan, talk to him in person.}
{412}{}{One more question before I go.}
{413}{}{Then I'll go straight to him. Goodbye.}
{414}{}{Tell about this to Sullivan. He is a good man?}
{415}{}{He's like a brother to me. We started together. I knew how to negotiate with people, and he knew how to solve problems. It would have been hard without John.}
{416}{}{Seems like you really are like brothers. But I'm more interested in the city.}
{417}{}{Usually the word "brother" loses all meaning when it comes to business.}
{418}{}{I'll let this slide. Perhaps in a big city the caps are separated, but here this is not the case. I value John as a reliable person. The most reliable in Casa Grande.}
{419}{}{Was Sullivan your friend?}
{420}{}{Don't mention his name. We started together, and I could never have expected such a betrayal. Now I don't even want to hear about him.}
{421}{}{Didn't you call him "the most trusted man in Casa Grande" earlier?}
{422}{}{Looks like you're really hurt by this. Let's not talk about this anymore.}
{423}{}{(slams fist on table) Sullivan... He got what he deserved for his villainy. All I can do is erase this traitor from my life. You better hold your tongue before our relationship deteriorates completely.}
{424}{}{Sorry, let's not talk about this anymore.}
{425}{}{If you want to close your eyes to past mistakes, that's up to you. Let's talk about something else.}
{426}{}{You really are bringing death to your city. I've had enough of these creepy stories.}
{427}{}{}
{428}{}{You shouldn't have gotten involved in this crap in the first place. Goodbye, mayor.}
{429}{}{Weak argument, Mayor. Very weak.}

{430}{}{You have an unusually large cemetery for such a small population.}
{431}{}{You best steer clear of that place. And don't go prying into things that are none of your business.}
{432}{}{Sorry, I won't do it again.}
{433}{}{Still. What happened here?}
{434}{}{A little bit of everything - raider, scorpions... And enough of that. People don't like having their past brought up.}
{435}{}{I know what happened here in the past. You seized power in Casa Grande by force.}
{436}{}{That raider claimed that you killed half the population to come to power.}
{437}{}{Tough times call for tough decisions. If I hadn't started the fight then, someone else would have started it. This is the natural state of affairs.}
{438}{}{Was it inevitable?}
{439}{}{Too many people and too few resources. This town survives by water pumping and as a caravan camp. There is nothing left in this desert that could give life. As a result, many did not find a place for themselves, banditry and clan wars began.}
{440}{}{Now I understand why you're always drunk.}
{441}{}{So that's why you need so many bodyguards.}
{442}{}{You can't always let go of the past. This is my cross.}
{443}{}{I had a chance to visit a place where an ancient factory was restored. There, too, many people died in the struggle for it.}
{444}{}{Really? Heh, small consolation. But I'm glad the wasteland is finally getting a makeover. I hope that in my lifetime I'll see a Corvega on the move, like in the old books.}
{445}{}{You're a monster. How could you kill dozens of people for your own gain?}
{446}{}{If this conversation is too heavy for you, let's talk about something else.}
{447}{}{Now I know what to do with my head held high. Goodbye.}
{448}{}{Shut your mouth and listen. I AM THE MAYOR OF THIS CITY. I am responsible for it. And I won't allow ANYONE to tarnish its good name. Who are you to judge me? Just a drifter passing through. So keep drifting.}
{449}{}{You're right. I'm just a traveler stopping by for a drink. Goodbye, Mayor.}
{1449}{}{You're right. I'm just a traveler stopping by for a drink. Goodbye, Mayor.}

#First quest
{450}{}{Are there any jobs in town? I could use some income while I'm here.}
{451}{}{I don't have a job for you.}
{452}{}{I see. But maybe you can answer a couple of questions?}
{453}{}{Okay, I'll go ask the rest of the people around town.}
{454}{}{I don't have a job for you... However, you could solve one problem for me.}
{455}{}{What are we talking about?}
{456}{}{Some highwaymen robbed one of the caravans near the train station and locked themselves in with the goods inside. It looks like they're not going to leave, as if they're provoking or testing us. Go there and find out what they want.}
{457}{}{Are your guys standing around here just for show?}
{458}{}{Isn't there a sheriff here to deal with stuff like this?}
{459}{}{No one wants to risk their life over a box of old junk. We're just hoping that the highwaymen will get tired of being locked up and will eventually leave on their own.}
{460}{}{I need some caps, but I'm not taking that kind of risk. Find someone else.}
{461}{}{Okay, I'll rid you of these highwaymen.}
{462}{}{Great. The station is south of here.}
{463}{}{Get the reward ready. Those raider bastards will regret testing you.}

{470}{}{Here you are. Come in, have a seat. After that mess at the bar, I wanted to relax a little and have a drink. Pour yourself something too. After all, it's thanks to you that my daughter and I still enjoy our freedom.}
{471}{}{Strange business. Count, why did the highwaymen target the city?}
{472}{}{Highwaymen like them usually stick to robbing travelers on the highways and avoid cities and towns in general. But these knew what to do, because their leader once lived in Casa Grande... However, this is a long story, and I still haven't paid you for your help.}
{473}{}{[More]}
{474}{}{Here are 250 caps. And you can earn more.}
{475}{}{More? How much more?}
{476}{}{I'm listening. Who's the problem this time?}
{477}{}{Your freedom cost someone their life, didn't it?}
{478}{}{For a mercenary, you're rather talkative. As you know, highwaymen rob travelers on the highway. But the highwaymen in the bar had personal scores to settle. However, it's a long story, and I still haven't paid you back.}
{479}{}{[More]}
{480}{}{Here you are... Come in. After that bar fight, I... I need a drink.}
{481}{}{I'm so sorry your daughter died.}
{482}{}{Damn everything! I once made the mistake of driving some residents out of the city instead of executing them. And now they returned. And my daugh... All that's left is to take brutal, merciless revenge on these highwaymen...}
{483}{}{[More]}
{484}{}{Trying to drink away your problem? It won't work.}
{485}{}{What the fuck do you know... (calms himself) Whatever. I once made the mistake of driving some residents out of the city instead of executing them. And they've returned as highwaymen. Now I have to deal with them once and for all...}
{486}{}{[More]}
{487}{}{Seems like you needed caps, huh? I won't pay for the showdown at the bar. But I have some business I will pay you for.}
{488}{}{What do I have to do?}
{489}{}{Those highwaymen in the bar were members of the largest highway clan in the region -- the Blue Shields. They're infamous for their ruthless crimes. After robbing some caravans recently, these scum acquired top-notch weapons. Now, they're a threat to the whole city.}
{490}{}{Are you suggesting we stop them? But how?}
{491}{}{Kill their leader, Ben. I'll pay 500 caps for his head. I want his head.}
{492}{}{I've been looking for smart people like you for a long time to find their lair and finish off their leader Ben. Without him, the clan will fall apart and, at least for a while, will leave us alone.}
{493}{}{No need to explain the whole story. What's the price?}

#Second quest
{500}{}{Highwaymen are like scavengers - they form into packs and hunt down easy prey along the highways. Small clans do not pose a threat to the city. But there is one big one.}
{501}{}{Let me guess - this is where the highwaymen who grabbed your daughter came from?}
{502}{}{Yes. And this is not the first time they've come after us. They're part of the Blue Shield clan. They're known throughout the region for their ruthless crimes. The Blue Shields are filled with the most desperate and violent scum of this whole region.}
{503}{}{Sounds pretty bad. But do you really think you can take out the entire gang with just the help of a mercenary?}
{504}{}{To hell with the backstory. Just tell me how to find them.}
{505}{}{No need to wipe out the whole gang. I'll pay 500 caps for the head of their leader, Ben. You'll get the same amount if you destroy their fuel depot as well.}
{506}{}{All these deaths are gonna haunt my dreams for years to come. I'll have to pass.}
{507}{}{Well, that's a shame. I was hoping there was a real hero in front of me. But don't rush into a decision. The problem won't solve itself, and I'm always willing to pay for good work.}
{508}{}{Goodbye.}
{509}{}{Great, consider this Ben's head in your hands.}
{510}{}{Bring me his head and you'll receive a reward. Good luck.}
{511}{}{Goodbye.}
{512}{}{I need to know more about these Blue Shields.}

{520}{}{About the highwaymen.}
{521}{}{Well?}
{522}{}{Nothing yet. I just wanted to say that I'm still working on this problem. Bye.}
{523}{}{Why is this clan so strong?}
{524}{}{Well, after the attacks on the last caravans, these scum got their hands on some good equipment, made by Tinsmiths on their fancy machines. In addition, they have huge reserves of gasoline. If their strength continues to grow, the entire city will be threatened.}
{525}{}{Where did they get so much fuel?}
{526}{}{They say they've taken over an old gasoline fuel depot and are using it as a base. The fuel reserves give them power. Literally.}
{527}{}{Tell me about the Blue Shields' leader.}
{528}{}{His name is Ben. He once lived here, but I drove him and his gang out of the city. That's why I know about him.}
{529}{}{Why is it so important to kill the leader?}
{530}{}{Without a leader, the clan will fall apart, or at the least, leave us alone for a while.}
{531}{}{What's the point of destroying their fuel depot?}
{532}{}{Fuel is their lifeblood, both a weapon and a means of survival. In the future, it could serve as a valuable trade resource. Plus, the depot's destruction will cripple their fort's actual structure. Such a blow would seriously rock the gang.}
{533}{}{How will you know if I blow up this depot?}
{534}{}{I'll be able to see the smoke through binoculars. There are eyes and ears everywhere; something like that can't be hidden from anyone.}
{535}{}{Where is the Blue Shields main base?}
{536}{}{According to the caravan leaders, it's somewhere to the northeast of us.}
{537}{}{Why were some Casa Grande residents among the highwaymen?}
{538}{}{It's an old and long story. When I became mayor, the first thing I did was evict all the scum from the city. As it turned out, some of them survived and began to terrorize the highways.}
{539}{}{I've learned enough. See you again, Count.}
{1539}{}{I've learned enough. See you later, Count.}
{540}{}{Here's the head of your enemy. You recognize him, right?}
{541}{}{(looks silently at the head for a while with contempt and hatred, then waves it away with his hand) Throw this rubbish out in the wasteland. Let the radscorpions eat the last leader of the Blue Shields.}
{542}{}{As you say, Count.}
{543}{}{No, don't touch it. I'll hang his head above the railway at the entrance to the city. Let people know what awaits them if they go against authorities.}
{544}{}{Good idea.}
{545}{}{Sure, but don't forget to mention who killed him.}
{546}{}{I appreciate people who do their jobs well. You deserve a reward... (takes caps out of the safe) Here are 500 caps, as we agreed. Now leave me. I want to rest.}
{547}{}{Goodbye, Count.}
{548}{}{Hey, where's my reward? I didn't just trek across half the wasteland with a bag of rotting flesh for nothing.}
{549}{}{Of course. This is your honestly earned right... (takes out caps from the safe) There are 500 caps here, as we agreed. Now leave me.}

{550}{}{I destroyed the Blue Shields' fuel depots. This will definitely weaken the gang.}
{1550}{}{I destroyed the Blue Shields' fuel depots. This will definitely weaken the gang.}
{551}{}{So the rumors are true. The caravanners saw smoke along the trade route. If the fuel depot is destroyed, it will be a difficult time for the Blue Shields.}
{552}{}{Ahem. The services are not free, wasn't that the deal?}
{553}{}{Of course, here's the reward - 500 caps. And thanks. Your service is invaluable to the city.}
{554}{}{You're welcome, Count. As long as your city pays caps, it has a future.}
{555}{}{I've learned the hard way what happens when you allow violence against yourself, or your people. So, I consider it my duty to stop the Blue Shields.}
{556}{}{Is that so? Now it's clear why you have so much strength to fight. I really hope you'll save your people from captivity. Take your reward, there are 500 caps here. And thanks. Your service is invaluable to the city.}
{557}{}{Goodbye, Count Bustos.}
{558}{}{It will be. The raiders are definitely weakened and will hopefully turn on each other, or scatter.}
{559}{}{Great job. I don't mind paying all 500 caps for this. And thanks. Your service is invaluable to the city.}
{560}{}{You're welcome, Count Bustos.}

{569}{}{Your city is already suffering from highwaymen. This way there will be fewer of them.}
{570}{}{I hear you caught one of the highwaymen?}
{571}{}{It's true. We keep him locked up. First we need to get all the information about the gang out of him, and then we'll publicly execute him.}
{572}{}{Are you sure he's a criminal?}
{573}{}{Some residents recognized him as a highwayman. I believe them. In addition, he was wearing road signs, highwaymen often use them as armor during attacks.}
{574}{}{Well, congratulations, Mayor. It's time for me to go.}
{575}{}{I need to see him. Maybe I can learn something from him.}
{576}{}{He's downstairs, locked up. Tell the guards to let you through.}
{577}{}{You grabbed the wrong guy. He needs to be released.}
{578}{}{What, should I just let him go based on your word? I don't think so. Still, it'd be interesting to hear your reasons.}
{579}{}{It's my job to tell you, the rest is up to you.}
{580}{}{Isn't my testimony enough?}
{581}{}{No. I trust my people, but not you.}
{582}{}{Then the decision will be yours. Goodbye.}
{583}{}{I, well, um... worked with him in the same caravan. I can guarantee that he poses no threat to you.}
{584}{}{Hmm. To be honest, I don't know who he is or where he comes from, but residents always see a stranger as an enemy. Okay, I'll let this guy go for now, but on the condition that he leaves my city within the hour.}
{585}{}{Thanks, Mr. Mayor.}
{586}{}{How about collateral? I'll pay 100 caps for his freedom.}
{587}{}{Sounds reasonable. But tell him to get out of town within the hour.}
{588}{}{Thanks, Mr. Mayor.}
{589}{}{Sounds reasonable.}
{590}{}{I'll drop off the caps shortly.}
{591}{}{The Blue Shields propose an alliance. They've already made an agreement with the Tinsmiths.}
{592}{}{What? Are these highwaymen protected by the Tinsmiths? That's outrageous!}
{593}{}{The Tinsmiths recognized them as a peaceful, independent settlement.}
{594}{}{Damn. I should have acted faster. I guess it's good that the gang will lay off us and the caravans for a while. But highwaymen can't be trusted. Many of them seek revenge on me personally or on the whole of Casa Grande.}
{595}{}{You have no choice. The Tinsmiths will not tolerate resistance.}
{596}{}{Obviously so. I will sign the contract, taking into account your past achievements. But I'm gonna do everything to make the Shields pay dearly for it.}
{597}{}{I'll tell Ben what you said. Goodbye.}
{598}{}{I'll be damned if I sign onto some 'alliance'. Get out and tell Ben that the Tinsmiths won't be able to protect him and his gang from justice.}
{599}{}{I'll tell Ben what you said. Goodbye.}
