{100}{}{You are completely bankrupt.}
{101}{}{You see a farmer who is angry with the whole world.}

{110}{}{Die, you bastards!}
{111}{}{I won't let this go so easily!}
{112}{}{I'm gonna take back my land by force!}
{113}{}{They took my farm, and I'll take the rest.}
{114}{}{The Rangers are going to fucking pay for everything!}
{115}{}{Do you think I'm going crazy? No, I just want justice.}
{116}{}{Why should I pay someone for land?}
{117}{}{Now I don't care about laws and rules!}
{118}{}{The Rangers put me on trial, and I'll put them on trial.}
{119}{}{You'll all pay!}
