{100}{}{You see a super mutant.}
{101}{}{There is a huge super mutant in front of you.}
{102}{}{ }

{120}{}{For the Master!}
{121}{}{I hate when people stare at me.}

{150}{}{Are we in Texas land yet?}
{151}{}{No, the Captain says we still in Arizona.}
{152}{}{Arrr! We crawl like a legless ghoul with a chainsaw in ass.}
{153}{}{You can't go faster, it's dangerous for the fortress.}
{154}{}{I no want to wait! The captain promised us a glorious battle and the taking of lands.}
{155}{}{Remind why we left Mariposa?}
{156}{}{I 'member. I not stupid. But the Master would not approve.}
{157}{}{Yes. But the Master is no more...}
{158}{}{Arrr! We shouldn't have left, we should have fought back!}
{159}{}{Too many of us dead. Captain knows what he's doing.}
{160}{}{Yes, the Captain is in charge now. But I can be captain too!}
{161}{}{So what would you do?}
{162}{}{I would go back and smash Lost Hills citadel. And would smash all the cities along the way.}
{163}{}{That's why you not captain. The captain is smart. You stupid.}
{164}{}{Shut hole in face! I not stupid!}
{165}{}{It's okay, the Captain will straighten your brains out.}
{166}{}{Arrr!}
