{100}{}{You see a bar patron in a jittery state. He's a bit tipsy.}
{101}{}{You see a jittery settler nursing his drink. The alcohol seems to be doing its job.}
{102}{}{Stay back!}
{103}{}{Enough, no more! I'm the bad guy, It's all on me!}
{104}{}{Ah, now there's some potential in you.}
{105}{}{Alright, let's call it a draw.}
{106}{}{I think you took enough of a drubbing. Go grab me a drink now.}
{107}{}{Looks like someone's flaunting their shiny armor around here.}

{200}{}{Hey, you! I don't know you. New in town? Then fetch me a drink. Quick.}
{201}{}{What makes you think I should buy you a drink?}
{1201}{}{What makes you think I should buy you a drink?}
{202}{}{Look, I don't want any trouble. Just leave me be, alright?}
{1202}{}{Look, I don't want any trouble. Just don't touch me, okay?}
{203}{}{Drop dead.}

{204}{}{Because you see the living embodiment of power and order in this city! I'm working for Roy Faber himself. Got it? So bring me the booze, or you'll be asking for a brawl.}
{205}{}{I don't want any trouble. Just keep your distance.}
{206}{}{All bark, no bite. Been a while since you've had some teeth knocked out?}

{207}{}{Ha! Weak village swill. Leave the bar if you've got any brains. This city's no place for weaklings like you.}
{1207}{}{Touch a village kid like you? You better leave, that's where you belong.}
{208}{}{Alright, alright. You call the shots.}
{209}{}{That was rude. Wanted to start something? Well you did!}

{210}{}{What? Mouthy little, empty-headed shit! Now I'm gonna make you beg for mercy...}
{211}{}{Just spare my face...}
{212}{}{Alright, impress me then.}

{213}{}{I work for him too. So zip it.}
{214}{}{(through clenched teeth) Damn... (returns to his bottle, looking sadly at the table)}
{215}{}{'Nice' talking to you.}

{216}{}{Faber's dead! Did you hear? He's gone!}
{217}{}{Yeah, yeah, I got it. Take it easy...}
{218}{}{Quite the accomplishment. Beating up drunks in a bar because you're just someone's lackey, right?}
{219}{}{Well, no. I... I... Just fuck off!}

{220}{}{What's your deal?}
{221}{}{Nothing.}
{222}{}{Expected as much.}
{223}{}{Get lost.}
{224}{}{With pleasure.}
{225}{}{Don't come any closer!}
{226}{}{I have no intention to.}
{227}{}{My people from Villa are locked up. I need your help to free them.}
{228}{}{What?! You can't just free them. Faber would never release prisoners just like that. And trying to break them out? Impossible. You'd just be signing your and their own death warrants.}
{229}{}{Enlighten me. Why is it impossible?}
{230}{}{Even if the prisoners broke loose, those collars would finish them off. They'd get a taste of freedom for a few miles, then boom! No more head.}
{231}{}{That's brutal...}
{232}{}{The collars can be disabled at the radio station. But only two people know how: Faber and Smart Guy. So your chances are slim to none.}
{233}{}{I'll cross that bridge when I come to it.}
