{100}{}{You see the merchant Joshua.}
{101}{}{You see the caravan manager. His skin is bronzed from countless days in the sun.}
{102}{}{Have a nice trip.}
{103}{}{This is Phoenix, the largest city in the wasteland. You always have to be on your guard here.}

{200}{}{What do you want this time?}
{201}{}{Bye.}

#First dialogue
{210}{}{You lookin' for someone?}
{211}{}{Maybe. Who are you?}
{212}{}{He's not here. Bye.}
{213}{}{If your lookin' for business, we can't help you. We only work with the administration of this mine.}
{214}{}{So, what do you do?}
{215}{}{We transport heavy loads. Why do you ask?}
{216}{}{Hmm, I'm just curious.}
{217}{}{Nothing.}
{218}{}{Do you have a minute? I want to know more about your work.}

#Questions
{220}{}{Go ahead. What do you want to know?}

{221}{}{What's your caravan route?}
{222}{}{Our destination is the city of Phoenix to the south. Along the way, we check out the small stops along Route 17 and pass by San Brahmin.}
{223}{}{Tell me about San Brahmin.}
{224}{}{It's a large town on the way to Phoenix. The locals mainly engage in cattle breeding and see us outsiders primarily as Brahmin buyers.}
{225}{}{Tell me about Phoenix.}
{226}{}{The largest city I know of. You'll find everything there that can be found in the Wasteland, but you need to be careful. The city is not safe, ever since the fire worshippers took over.}
{227}{}{The route heads south. But why should I tell you any more than that?}
{228}{}{Fire worshippers?}
{229}{}{Strange folks. They worship pre-war atomic energy - that's all I understand. Too many words to take in. But they don't sit idle either - it was under their control that Phoenix became a real city.}

{230}{}{What kind of cargo are you transporting?}
{231}{}{Uranium. It's mined right here in this mine.}
{232}{}{Who needs it?}
{233}{}{Everyone who has good old nuclear-powered equipment. But the fire worshippers in Phoenix buy the uranium first and then sell it to smaller buyers at five times the price.}
{234}{}{Doesn't uranium cause radiation sickness?}
{235}{}{It does... if you eat it for breakfast, lunch, and dinner. This ore is slightly radioactive and harmless until it's in the reactor. Then it's better to stay as far away as possible.}

{236}{}{Do you realize the people you're helping are slavers?}
{237}{}{Are you talking about Faber and his mercenaries? I don't care. Me and my people need work. And the colony provides jobs and stable income. That's enough for me.}
{238}{}{I'll pay 30 caps.}
{239}{}{Well, that changes things.}
{240}{}{So tell me more.}
{241}{}{With your leaky pockets, you can't even hope for road dust.}
{242}{}{Oops, got lost somewhere...}
{243}{}{A local cult worships atomic energy. True, after the destruction of their main temple, little remained of them. Be that as it may, it was under their control that Phoenix became a real city.}

#Amendments for emergency situations
{250}{}{...I'm telling you, we're not going anywhere... Wait, you're not from the administration, are you? Then forget it.}
{251}{}{What's the problem with the caravan?}
{252}{}{You don't know what's been going on? The mine is out of business, and so are we.}
{253}{}{What's wrong with the mine?}
{254}{}{Bye.}
{255}{}{The mine is destroyed, and clearing it will take a lot of time and effort. I doubt this place will have any future.}
{256}{}{After the fire worshippers in Phoenix were pulverized into atoms, the mine lost its main customer. Of course, there's still demand for ore. Other settlements are ready to buy it, but it won't be enough to keep the mine running.}
{257}{}{The Flagstaff garrison has been wiped out, the prisoners have fled, and the warden is dead. Now we don't even know who we work for. Looks like no one needs our services now.}
{258}{}{You're caravanners. Do you really care who you work for?}
{259}{}{Others cared who we worked for. Because of our connections with the fire worshippers and Faber's mercenaries, not everyone will want to deal with us. Our competitors were always jealous. Setting up new routes is going to be very difficult. If it's even possible.}
{260}{}{So you're not heading out at all?}
{261}{}{Exactly. Until the situation improves, we'll have to stay in Flagstaff. I don't know what we'll do yet, but we'll figure something out.}

#Journey to the South
{300}{}{Hey, we're heading the same way. Can I tag along to Phoenix?}
{301}{}{We don't usually take on travel companions. Our clients prefer a secure convoy.}
{302}{}{Can you at least answer some questions?}
{303}{}{Fair enough.}
{304}{}{Phoenix doesn't offer a warm welcome, just a short drop and a sudden stop. We're still figuring out our next move.}
{305}{}{Sounds like a tough situation.}
{306}{}{In Phoenix, they don't take kindly to scammers. Lucky for you, we're not in Phoenix.}
{307}{}{Uh, got it.}

{310}{}{Will 500 caps secure a spot?}
{311}{}{Alright, you pay 500 caps and you can join the convoy. But there are some conditions.}
{312}{}{Here's the caps. What are the conditions?}
{313}{}{Perhaps another time.}
{314}{}{}
{315}{}{Fair point. There's something about you, so I'll make an exception. But it comes with conditions.}
{316}{}{What are the conditions?}
{317}{}{Maybe another time.}
{318}{}{Experience has taught us not to trust strangers.}
{319}{}{I see. Goodbye.}

{320}{}{First off, your luggage must be 50 pounds or less. Secondly, we'll rest at San Brahmin overnight before heading to Phoenix. Does that work for you? If so, we'll leave when you're ready.}
{321}{}{Sounds good. I'll get ready.}
{322}{}{Still, could be useful to just have an extra pair of hands. Can't I just tag along?}
{323}{}{An extra hand for free on the road is not something you should pass up.}

{330}{}{I'd like to join the caravan.}
{331}{}{We're not risking the caravan for your baggage. Clear the clutter, and we'll talk.}
{332}{}{Are you bringing all that? Sorry, can't slow down the convoy for excess baggage. Stick to 50 pounds or less.}
{333}{}{Alright, I'll lighten my load.}
{334}{}{I'll handle my belongings. Won't hold up the convoy.}
{335}{}{I had a few quesitons before we head out.}
{336}{}{Alright. But no one's babysitting your gear or waiting for you to catch up. If you lag behind, it's on you.}
{337}{}{No problem.}
{338}{}{(After a night's rest with the guards, you set off towards the south)}
{339}{}{[Embark on the journey]}

#Other locations
{400}{}{We're stopping here for a day. Feel free to explore, but remember, the caravan won't wait if you're late.}
{401}{}{Can you tell me anything about San Brahmin?}
{402}{}{It's a brahmin herder's town. They're a bit wary of outsiders, but they're always up for trade. Just mind your manners if you want to strike a deal.}
{403}{}{I'll make sure to keep an eye on the time.}
{404}{}{[Wait until the caravan departs for Phoenix]}
{405}{}{Go on without me, I'll make my own way from here.}
{406}{}{Take care.}
{407}{}{You too. Later.}
