{100}{}{You see a colonist.}
{101}{}{You see a citizen of Flagstaff.}
{102}{}{It's past curfew. Get out of here.}

#Dialogue
{200}{}{Hey, are you blind? This house is taken. What do you want?}
{201}{}{That's no way to greet someone.}
{202}{}{Why should I greet you when you barge into my house? Just so you know, this is a small town. Everyone knows each other by sight, and I don't know you.}
{203}{}{Right back at you.}
{204}{}{You're a real piece of work.}
{205}{}{Got a minute for some questions?}
{206}{}{I'll keep that in mind.}
{207}{}{Glad we understand each other.}
{208}{}{Thanks for the advice. Sorry to bother you.}
{209}{}{Good manners? That's a surprise.}

{210}{}{What do you want?}
{211}{}{Goodbye.}

{212}{}{Why do you hate strangers so much?}
{213}{}{Only savages live north of Phoenix. Am I right? Are you from there?}
{214}{}{No, I'm from a small village in the west.}
{215}{}{So you're a peasant? Digging in the dirt and all that?}
{1215}{}{So you're a peasant? Digging in the dirt and all that?}
{216}{}{Exactly. Unlike you city worms, I actually do something important.}
{1216}{}{Exactly. Unlike you city worms, I actually do something important.}
{217}{}{Not really. Why does it matter?}
{218}{}{Sort of. To get a harvest, you need to work from dawn to dusk.}
{219}{}{It's tough for people like you to grasp the joys of life in the south, where *real* civilization is being reborn. Any more questions?}
{220}{}{Actually, yeah.}
{221}{}{Goodbye.}
{222}{}{I'm from Phoenix.}
{223}{}{Oh, couldn't tell... Enjoy your stay in our humble colony. Any more questions?}
{224}{}{Actually, yes.}
{225}{}{None of your business.}
{226}{}{Then stop asking dumb questions.}
{227}{}{Yeah.}
{228}{}{}
{229}{}{Good to see you.}

{230}{}{What are you doing in this colony?}
{231}{}{While my husband is busy in the garrison, I keep his house in order. They used to call it "housekeeping." Got it?}
{232}{}{Yeah, I get it.}
{233}{}{Do you like it here?}
{234}{}{Well... It's kind of boring. If it weren't for my husband, I'd have stayed in Phoenix. Still, you can live and work here, and the garrison keeps the riff-raff away. You can even hire a servant if you've got the caps. Not many places offer that.}
{235}{}{Are you kidding me? Since the prisoners escaped, I can't step outside without a knife! This place is the pits. Even Phoenix was safer.}
{236}{}{Can I ask you another question?}
{237}{}{Got it. Well, goodbye.}
{238}{}{How long have you lived here?}
{239}{}{No, I came with the second wave of colonists from a big city in the south.}
{240}{}{Why did you leave?}
{241}{}{I wanted a fresh start. Thought there'd be more freedom and opportunities here.}
