{100}{}{You see a tribal raider.}
{101}{}{You see a raider, tattooed with tribal skull designs. They're not like the other inhabitants of Flagstaff.}
{102}{}{We are leaving this land.}
{103}{}{This is our land!}

{200}{}{Stop. You're trespassing on our land. You shouldn't have come.}
{201}{}{Uh...}
{202}{}{People like you don't belong here.}
{203}{}{[Defend]}
{204}{}{I come in peace. The farmer says you took his house and land.}
{1204}{}{I come in peace. The farmer says you took his house and land.}
{205}{}{The farmer is a hypocrite like everyone else. You came to these lands, killed our people, and took our land. We're just taking it back.}
{206}{}{You're just common thieves.}
{207}{}{I don't know this side of the story. What's going on?}
{208}{}{Of course, you don't know. Our ancestors lived here for generations. Then Faber's people came, enslaved us, and killed those who resisted. We were the only survivors. Now we want revenge. Blood for blood is our custom.}
{209}{}{But the farmer isn't to blame. Leave him alone.}
{210}{}{We kept him alive. He should be grateful and leave. But you aren't going anywhere.}
{211}{}{[Give them the middle finger]}
{212}{}{Hey, I don't want to fight...}
{213}{}{I'm sorry to hear that. But the farmer isn't at fault. He's a civilian, let him be.}
{214}{}{We know. That's why we spared his life. He should be grateful and move on.}
{215}{}{He's put a lot of work into this land. You should respect that.}
{216}{}{Maybe. None of us wanted war until the colonists crossed the line. But we can't fight the garrison.}
{217}{}{This is colonist land now. There's nothing you can do. Leave Flagstaff and start over.}
{218}{}{If you're so bent on revenge, I'll stop you. By force, if necessary.}
{219}{}{You outsiders talk too much. But you make sense. Fighting means death. Going to the mountains means survival. So be it. We'll gather the clan and leave. (signals to others) The farm isn't worth our lives. It's time to move on.}
{220}{}{Wise decision. Good luck.}
{221}{}{Yeah, get out of here. I mean, good luck and all that.}

{250}{}{Argh! An armored man! Damn colonists, what else will you come up with to drive us out of our lands?}
{251}{}{What are you even talking about?}
{252}{}{Not my problem.}
{253}{}{We don't want a fight with you, armored man. We'll leave. Don't follow us.}
{254}{}{Yeah, get out of here.}
{255}{}{Oh no, you'll have to pay for the inconvenience first. In blood.}

{260}{}{Stranger... Why do you look like the skin of a mutfruit left in the sun all day?}
{261}{}{Why do you think? Your skin isn't much better, savage.}
{262}{}{You suffer, don't you? From others who aren't like you. We get it, we understand you.}
{263}{}{You won't last long if you start mocking my appearance.}
{264}{}{Actually, I'm here for my farmer friend. He's suffering too.}
{265}{}{Farmer? We spared his life. He should be grateful and leave.}
{266}{}{Doesn't matter how you spin it, you just took his land. That's bad. Real bad.}
