{100}{}{You see a miner.}
{101}{}{You see a filthy man with rough manners.}

#Responses
{110}{}{*Coughs violently*}
{111}{}{This mine is the only reason we survive.}
{112}{}{Every shift underground could be your last.}
{113}{}{This shift is going to be a long one.}
{114}{}{Those mole rats are real giants.}
{115}{}{Mole rats eat the body but leave the head and clothing intact.}
{116}{}{I'm telling you, the rat king exists!}
{117}{}{I'm starving.}
{118}{}{Hey, you! Do you know how to get rid of the collar?}
{119}{}{Once you're in here, forget about freedom.}
