{100}{}{You see Sancho.}
{101}{}{You see a slave. When you look closely, you recognize your fellow villager despite his dirty, emaciated face.}

{102}{}{Oops, I hope no one in the Villa finds out about this...}
{103}{}{Traitor! You've been possessed by Diablo!}
{104}{}{Now Sancho will never return to Villa.}
{105}{}{Sancho returns to Villa.}
{106}{}{Alright, if it must be done.}
{107}{}{See you at the Villa, amigo.}

#First dialogue
{200}{}{? Is that you? It's a miracle! We thought we were done for.}
{201}{}{I'm here to free you.}
{202}{}{Just in time. Help us get to the exit. From there, we can find our own way.}
{203}{}{We're at the entrance. Freedom is very close.}
{204}{}{Where are the others?}
{205}{}{How did you end up in this trap?}
{206}{}{How did you manage to remove the collars?}
{207}{}{What can you tell me about this mine?}
{208}{}{Sancho, I remember you didn't like me back at the Villa and called me a "one-legged mantis."}
{209}{}{Alright, let's go.}

{210}{}{We were split up when we were first brought here. Some, including your madre, were left in the pen. The rest were taken out of Flagstaff; I haven't seen them since.}
{211}{}{It was a stupid plan. We tried to dig a tunnel out to the wasteland and escape, but we needed explosives. We messed it up, and collapsed the tunnel behind us.}
{212}{}{One of the slaves told us the collars don't work in the mine.}
{213}{}{Just a deep, damp hole with giant rats everywhere. You won't find creatures like this at the Villa. They say there are even more. We were lucky to avoid them.}
{214}{}{Why did the mercenaries bring you here?}
{215}{}{To shovel that damn ore! It's cleaned and taken to another city, supposedly for energy. At the Villa, we use wood and oil. How do you burn stones? We're probably being fooled.}
{216}{}{Okay, okay, I'm sorry! Let's forget the past; we're from the same village. I'll never speak ill of you again, I promise.}
{217}{}{Wait, first tell me what happened.}

{220}{}{What?}
{221}{}{That rat was huge!}
{222}{}{Thanks for the help! We'll find our way. It's easier to evade mercenaries in a small group. You focus on saving the rest of the Villa's residents. We'd help, but after what we've been through, we're not much use. Good luck.}
{223}{}{Okay. I'll see you back at the Villa.}
{224}{}{Yes, I'd hate for this to happen again. Try blowing up this mine. Maybe it'll bankrupt the operation and stop them from hunting for new slaves.}
{225}{}{Blow up the mine? I love it!}
{226}{}{Highly doubtful. It'll just mean more work for the slaves.}
{227}{}{There are explosives in a warehouse inside the mine. The administrator has the key. Good luck.}
{228}{}{Leaving these mine is like feeding the rat king! They'll just find new slaves and keep going. Don't you get it? Or are you too scared after what happened? Think about it; we need to go. Good luck.}
{229}{}{I'll think about it. Now get out of here.}
