{100}{}{You see a drunk.}
{101}{}{You see a customer. He's had way more than his fill and is making a fool of himself.}

{110}{}{I don't...*hic*...know you.}
{111}{}{Sorry, this table's...busy.}
{112}{}{*Hic*}
{113}{}{Ain't got no drinks for you. Got it?}
{114}{}{Come on, beat it.}
{115}{}{*Hic*...If ya wanna...introduce yourself...order a round for everyone.}
{116}{}{You wouldn't even... even cough up a couple caps for a friend.}
{117}{}{Nope, don't touch that!}
{118}{}{*Hic*...You ain't invited...find another table.}
{119}{}{I don't...drink with strangers.}

{120}{}{Hey, thanks... for the drink!}
{121}{}{I...I like you.}
{122}{}{You're alright...*hic*...for a hick.}
{123}{}{What's...your name again? Well, nice...to meet ya.}
{124}{}{Best way to...meet folks is drinkin'! You're off to a good start!}

{130}{}{You'd better...*hic*...get outta here. I'm...serious.}
{131}{}{Get outta town!}
{132}{}{You lookin' for trouble?}
{133}{}{You ain't welcome no more!}
{134}{}{Damn hick...get away!}
{135}{}{Can't find the door? I'll show ya...with a kick in the ass!}

{140}{}{Have a seat, you're...always welcome here.}
{141}{}{How's...life, buddy?}
{142}{}{Same old...same old. You?}
{143}{}{Oh...don't even ask. But you...how 'bout you?}
{144}{}{Yeah, life's as...empty as a tin can.}
