{100}{}{You see a scavenger.}
{101}{}{You see a guy, red in the face from exertion.}

{110}{}{Hey, keep what you saw quiet, got that?}
{111}{}{Please don't kill me! I'll never do it again, I promise!}

{200}{}{What... Who are you anyway? What do you want?}
{201}{}{I'm just watching you guys have fun.}
{202}{}{Got a problem with our fun?}
{203}{}{What are you doing?}
{204}{}{We're dancing here. On the mattress. Got it?}
{205}{}{Mind if I join in?}
{206}{}{What, are you crazy?! Get lost, idiot!}
{1206}{}{You're out of your mind. And we don't deal with rejected women. Get lost!}
{207}{}{Alright, I'm leaving...}
{208}{}{It's time for you to stop.}
{209}{}{Uh-oh, we gotta hero here. So what're ya gonna do? Huh? Well, speak up, BITCH?}
{210}{}{I'll just leave and not bother you. Have fun.}
{211}{}{I'm gonna kill you. Die, scum!}
{212}{}{I'll give you exactly three seconds, then my gun does the talking. One... two...}
{213}{}{}
{214}{}{Okay, okay! Calm down, dude! No need for guns. We're not animals, we can solve this calmly.}
{1214}{}{Okay, okay! Calm down, babe! No need for guns. We're not animals, we can solve this calmly.}
{215}{}{Get out of here.}
{216}{}{The door's open.}
{217}{}{You're keeping me awake.}
{218}{}{Look, we paid for the room and can do whatever we want. Got it?}
{219}{}{If you don't stop, you'll have trouble with the whole city.}
{220}{}{We know who you are, you lousy dirt digger. Nobody invited you to our city. You can't intimidate us.}
{221}{}{Okay. But you'll remember me.}
{222}{}{Know your place, punk. If you don't back off, you'll find out what I'm gonna do.}
{223}{}{Alright... We don't need trouble. We'll leave as if we were never here...}
