{102}{}{ receives one bottle cap.}
{103}{}{This item won't help here.}
{104}{}{This won't help here}
{105}{}{This skill will not help here.}
{106}{}{This man refuses to go any further.}
{107}{}{This creature refuses to go any further.}
{108}{}{This hostile person refuses to obey you.}
{109}{}{This hostile creature refuses to obey you.}

#----------------------------------------------
# Names of skills and basic parameters
#----------------------------------------------
{110}{}{Small Guns}
{111}{}{Big Guns}
{112}{}{Energy Weapons}
{113}{}{Unarmed}
{114}{}{Melee weapons}
{115}{}{Throwing}
{116}{}{First aid}
{117}{}{Doctor}
{118}{}{Sneak}
{119}{}{Lockpick}
{120}{}{Steal}
{121}{}{Traps}
{122}{}{Science}
{123}{}{Repair}
{124}{}{Speech}
{125}{}{Barter}
{126}{}{Gambling}
{127}{}{Outdoorsman}

{130}{}{You have increased your }
{131}{}{ skill by }
{132}{}{ points.}

{133}{}{[}
{134}{}{] }

{135}{}{Reaction}
{136}{}{Reputation}
{137}{}{Karma}
{138}{}{Level}

{140}{}{}
{141}{}{With your skills, that's not feasible.}
{142}{}{This creature cannot be pickpocketed.}
{143}{}{The target didn't see through your ruse. You escaped without consequences.}
{144}{}{This time, you managed to convince the target that it was a misunderstanding.}
{145}{}{A robot can't be pickpocketed while it's in active mode.}
{146}{}{ is watching you too closely.}
{147}{}{Your skills aren't sufficient to heal these wounds without medical supplies.}
{148}{}{You can't pickpocket while wearing Power Armor.}
{149}{}{It's not possible to do that.}

{150}{}{Strength}
{151}{}{Perception}
{152}{}{Endurance}
{153}{}{Charisma}
{154}{}{Intelligence}
{155}{}{Agility}
{156}{}{Luck}

#----------------------------------------------
# Gaining experience
#----------------------------------------------

{200}{}{You received }
{201}{}{ experience points.}
{202}{}{ experience points for a successful dialogue.}
{203}{}{ experience points and a reputation increase.}

#----------------------------------------------
#Injuries​
#----------------------------------------------

{300}{}{Your left leg is crippled! You are in severe pain.}
{301}{}{Your right leg is crippled! You are in severe pain.}
{302}{}{Your left arm is crippled! You are suffering from severe pain.}
{303}{}{Your right hand is crippled! You are suffering from severe pain.}
{304}{}{Your eyes are damaged! You are suffering from intense pain.}
{305}{}{Ugh, this is going to take a long time to heal...}

#----------------------------------------------
# Messages in battle
#----------------------------------------------

{320}{}{ hesitates to launch an attack.}
{321}{}{ regenerates and restores some health.}
{322}{}{!!!}
{323}{}{Frightened by the fire, }
{324}{}{ flees.}
{325}{}{Damn!}
{326}{}{ loses strength and perception as an EM pulse disables part of its electronics.}
{327}{}{!}
{328}{}{This can't be done in the middle of combat.}
{329}{}{Peep!}

#----------------------------------------------
# Comments about ineffectiveness (using the wrong item, skill, etc. )
#----------------------------------------------

{330}{}{Useless}
{331}{}{Not that}
{332}{}{Something's wrong}
{333}{}{No result}
{334}{}{Can't do it}
{335}{}{Hmm?}
{336}{}{Too difficult}
{337}{}{Useless}
{338}{}{Useless}
{339}{}{Useless}

#----------------------------------------------
# Replies upon completion of tasks ( clearing mines, repairs, refueling the bike, etc.)
#----------------------------------------------

{340}{}{Done}
{341}{}{Okay}
{342}{}{Great}
{343}{}{Done}
{344}{}{Got it}
{345}{}{Success}
{346}{}{Yes}
{347}{}{Done}
{348}{}{Done}
{349}{}{Done}

#----------------------------------------------
# Using different items on NPCs
#----------------------------------------------

# Consumables
{400}{}{ refuses to eat it.}
{401}{}{This experience brought you resourcefulness.}
{402}{}{ will not eat during battle.}
{403}{}{ refuses to take it.}
{404}{}{This does not apply to robots.}
{405}{}{Giving out free food brought you experience and karma.}
{406}{}{This does not apply to plants.}
{407}{}{ refuses to accept this.}
{408}{}{This creature becomes more friendly towards you.}
{409}{}{Stimpaks only affect humans.}
{410}{}{Animals and mutants do not drink alcohol.}
{411}{}{This will not affect floaters.}
{412}{}{ succumbs to the harmful effects of the chemical and goes into a rage.}
{413}{}{Alcohol? Not interested...}
{414}{}{That's what I've been missing!}
{415}{}{You shouldn't tease Brotherhood members with their own rations. You may be mistaken for a thief.}
{416}{}{Holy shit, what generosity!}
{417}{}{Are you really just going to give this to me?}
{418}{}{This item will not work through a Power Armor helmet.}
{419}{}{Free distribution of valuable liquid brought you experience and karma.}

# Items of clutter
{420}{}{I think this will come in handy}
{421}{}{Holy shit! Thank you!}
{422}{}{The child happily accepts your gift. He'll likely tell his friends about your actions.}
{423}{}{The child does not want to accept your gift. He seems to sense a hidden threat in you.}
{424}{}{A shovel definitely won't help here.}
{425}{}{Hacking a robot requires skills, a decoder will not help here.}
{426}{}{ poisoned!}
{427}{}{ dies in terrible convulsions.}
{428}{}{ falls dead.}
{429}{}{ loses consciousness and dies soon after.}
{430}{}{ stops breathing.}
{431}{}{This cannot be done during combat.}
{432}{}{Your partner knows what this means.}
{433}{}{Ooooh!}
{434}{}{You're needlessly scaring the child. There will probably be a more worthy use for this trophy.}
{435}{}{You have crafted 20 flare rounds from old holiday fireworks.}

# Items of ammunition
{440}{}{}
{441}{}{}
{442}{}{}
{443}{}{}
{444}{}{}
{445}{}{}
{446}{}{}
{447}{}{}
{448}{}{}
{449}{}{}
{450}{}{}
{451}{}{}
{452}{}{}
{453}{}{}
{454}{}{}
{455}{}{}
{456}{}{}
{457}{}{}
{458}{}{}
{459}{}{}

# Ammunition items
{460}{}{}
{461}{}{}
{462}{}{}
{463}{}{}
{464}{}{}
{465}{}{}
{466}{}{}
{467}{}{}
{468}{}{}
{469}{}{}
{470}{}{}
{471}{}{}
{472}{}{}
{473}{}{}
{474}{}{}
{475}{}{}
{476}{}{}
{477}{}{}
{478}{}{}
{479}{}{}

# Other items
{480}{}{Typically keys are used on locks.}
{481}{}{Amazing. And as soon as it occurred to you...}
{482}{}{The weapon must be used in combat mode while holding it in the hands.}
{483}{}{Using the doctor's bag, you have healed all your injuries.}
{484}{}{Use a doctor's bag to heal a patient's injuries.}
{485}{}{This item must be used from hand.}
{486}{}{This is unlikely to help in fixing the robot.}
{487}{}{ refuses your treatment.}
{488}{}{You do not require surgery.}
{489}{}{This item should be used on a motorcycle.}
{490}{}{This won't help here.}
{491}{}{You have found a use for an ancient relic.}
{492}{}{Your shovel has become unusable.}
{493}{}{The doctor's bag won't help here.}

#----------------------------------------------
# Dialogue options
#----------------------------------------------

#Critter
{500}{}{This hostile person will not talk to you.}
{501}{}{This robot has already been reprogrammed for your protection.}
{502}{}{You have reprogrammed the robot for your protection.}
{503}{}{}
{504}{}{You are unable to reconfigure the robot to protect yourself.}
{505}{}{What's this? Are you threatening me?}
{506}{}{This person will not communicate with you while you are holding a weapon.}
{507}{}{This man is dying and cannot speak right now.}
{508}{}{. . .}
{509}{}{Negotiations failed.}
{510}{}{?}
{511}{}{You see a crazed local.}
{512}{}{No fresh air }
{513}{}{ suffocating in the freezer.}
{514}{}{What is this? You are threatening me?}
{515}{}{Put your weapon away or I'll take out mine}
{516}{}{Power armor makes your interlocutor wary.}
{517}{}{...}
{518}{}{It seems this robot can't talk.}
{519}{}{This person refuses to obey you.}

# Computers
{550}{}{Access denied.}
{551}{}{This cannot be done during combat.}
{552}{}{The security system has already been breached.}
{553}{}{The security system has been compromised!}
{554}{}{Access granted.}
{555}{}{The game turned out to be quite exciting.}
{556}{}{You can't guess the password.}
{557}{}{You have installed a decoder. Now it will be much easier to hack the computer.}
{558}{}{The decoder won't help here anymore. Time to use your skills.}
{559}{}{}

#Equipment repair
{570}{}{ does not need repair.}
{571}{}{This cannot be done during combat.}
{572}{}{}
{573}{}{You have no idea how to fix this. Maybe you can make up for your lack of skill by replacing some parts.}  
{574}{}{You have no idea how to fix this.}
{575}{}{Bad luck! You were unlucky and got electrocuted.}
{576}{}{These parts will make repairs a little easier.}
{577}{}{These parts will make repairs much easier.}
{578}{}{Additional details won't help here. Time to use your skills.}
{579}{}{You see a Reaver.}

#----------------------------------------------
# Nicknames for the ring
#----------------------------------------------

#Important: male and female nicknames are antipodes and coincide in numbers with a difference of 50.
#- men's
{600}{}{Crusader}
{601}{}{Scorpio}
{602}{}{Cannibal}
{603}{}{King}
{604}{}{Caesar}
{605}{}{Hidalgo}
{606}{}{Sergeant}
{607}{}{Fang}
{608}{}{Sledgehammer}
{609}{}{Dynamite}
{610}{}{Smoker}
{611}{}{Hulk}
{612}{}{Sniper}
{613}{}{Macho}
{614}{}{Mr. X}
{615}{}{Big Brother}
{616}{}{Mad Dog}
{617}{}{Dud}
{618}{}{Reaver}
{619}{}{Butcher}
{620}{}{Leprechaun}
{621}{}{Whisper}

#- women's
{650}{}{Black Widow}
{651}{}{Centipede}
{652}{}{Brain Eater}
{653}{}{Queen}
{654}{}{Cleopatra}
{655}{}{Duchess}
{656}{}{Sergeant}
{657}{}{Claws}
{658}{}{Machete}
{659}{}{Magnum}
{660}{}{Napalm}
{661}{}{Ross}
{662}{}{Marine}
{663}{}{Muchacho}
{664}{}{Mrs. X}
{665}{}{Big Mom}
{666}{}{Mad Bitch}
{667}{}{Bad Girl}
{668}{}{Angel}
{669}{}{Wild Jane}
{670}{}{Snow White}
{671}{}{Ruby}

#----------------------------------------------
# Cartography
#----------------------------------------------

{1400}{}{A new location has been revealed on the world map}
{1401}{}{: }
{1402}{}{.}
{1403}{}{Suspicious sounds are coming from the cave.}

# Attention! The list should be copied unchanged from the file.../game/MAP.MSG
{1500}{}{Villa}
{1501}{}{Flagstaff}
{1502}{}{Garage City}
{1503}{}{San Brahmin}
{1504}{}{Two-Sun}
{1505}{}{Puerto}
{1506}{}{Rangers}
{1507}{}{Phoenix}
{1508}{}{El Faro Pier}
{1509}{}{Casa Grande}
{1510}{}{Hermosillo}
{1511}{}{San Felipe}
{1512}{}{Inferno}
{1513}{}{Casa Nueva}
{1514}{}{-}
{1515}{}{Motel}
{1516}{}{Dayglow}
{1517}{}{U.S. Navy Base}
{1518}{}{Santa Ana}
{1519}{}{-}
{1520}{}{Jackals}
{1521}{}{Pit Stop}
{1522}{}{Villa}
{1523}{}{Vault 27}
{1524}{}{Brotherhood Camp}
{1525}{}{Raiders}
{1526}{}{Wasteland}
{1527}{}{Mountains}
{1528}{}{Ruins}
{1529}{}{Coast}
{1530}{}{Puerto}
{1531}{}{Gold!}
{1532}{}{Henry Bemis}
{1533}{}{Roadside Cafe}
{1534}{}{Bomber}
{1535}{}{Petro-Chico Truck}
{1536}{}{The Cry of Silence}
{1537}{}{Outdoor Cinema}
{1538}{}{Padre}
{1539}{}{Baron of Arizona}
{1540}{}{Snowfall}
{1541}{}{The Lost Sanctuary}
{1542}{}{Mobile Fortress}
{1543}{}{Legend City}
{1544}{}{-}
{1545}{}{-}
{1546}{}{Quartzsite}
{1547}{}{Random Encounter}
{1548}{}{Camp Winon}
