{100}{}{You see a bitch.}
{101}{}{You see one of the females of the Jackal tribe.}

#Response
{200}{}{(grinding teeth) Shh! Don't come near me, stranger!}
{201}{}{Goodbye.}
{202}{}{I just want to talk about the tribe.}
{203}{}{Your empty words only tease my hunger. Bring food or leave me.}
{204}{}{Alright.}
{205}{}{The food was good. What do you want to know?}
{206}{}{Enough talk. Goodbye.}
{207}{}{Where did your tribe come from?}
{208}{}{I remember when I was a pup. Enemy tribes drove us from our lands. We wandered the desert, searching for a place to survive. Here, we waited out the dust storms. It was a hungry time. Only the strongest survived. Two generations have grown up in these dens since then.}
{209}{}{What do you eat?}
{210}{}{Whatever we can find or catch in the wasteland.}
{211}{}{Do you think it's okay to eat human flesh?}
{212}{}{What else can we eat when there's nothing else? Even grass doesn't grow in the desert. The river water makes our stomachs swell and bleed... Hmm. You have food.}
{213}{}{Are there other strangers here besides me?}
{214}{}{Yes... our lunch. A tough stranger. Very good meat. (grins) You can't get to him; the Night Beast guards the storerooms. Only the Mad Bitch knows how to talk to him.}
{215}{}{How do you feel about Mad Bitch?}
{216}{}{(with fear and trepidation) She leads us. She speaks for all of us. Don't ask about her again!}
{217}{}{What about Black Fang?}
{218}{}{Fang... (disapproving growl) Arrogant dog. Beats women, takes food. Beat Fang if you want his place.}
{219}{}{What's with the skull gear in the main hall?}
{220}{}{A relic from the past. Ask Mad Bitch about it.}
{221}{}{Tell me more.}
{222}{}{No one. Our last prey escaped. Left us hungry... (spits angrily)}
