{100}{}{You see Night Beast.}
{101}{}{You see a Jackal guard, fiercely protecting his tribe's storerooms.}
{102}{}{W-what kind of j-joke is t-this?!}

#Replicas floating
{120}{}{No one dares take my place.}
{121}{}{Only I can guard these dens, only me!}
{122}{}{I'll tear apart anyone who breaks into the storerooms!}
{123}{}{The Tribe needs me.}
{124}{}{Mad Bitch wants me to guard the storeroom. So I guard it.}
{125}{}{They say there's an outsider in the dens.}
{126}{}{Rrrr! I smell someone lurking!}
{127}{}{*Sniffs*}
{128}{}{I smell an outsider.}
{129}{}{These dens lack the pain-racked groans of outsiders.}

#Response
{200}{}{Get out! There's no place for an outsider in these storerooms!}
{201}{}{Okay.}
