{100}{}{You see a raider blocking your path.}
{101}{}{You recognize the highway bandit in front of you. He hasn't changed a bit since your meeting in the Casa Grande bar.}
{102}{}{You can't be here. Leave now. Let's pretend I didn't see you.}

{200}{}{Well, look who it is. What a surprise. How are the mayor and his spoiled daughter?}
{201}{}{They've got plenty on their minds. You still robbing and taking hostages since that bar incident?}
{202}{}{Stuff like that. But we got more going on here. Ben's got a plan. Talk to him; he might have use for you.}
{203}{}{I'll do that.}
{204}{}{Wait. I've been thinking about what happened at the bar. I don't know why you helped us, but you earned some respect. I've told the others about you, so they'll treat you better. Here, take a gun and some ammo. You might not want to hurt anyone, but you should still protect yourself.}
{205}{}{Thanks.}
{206}{}{Real survivors don't say "thank you" or "please." Remember that.}
{207}{}{Alright, bye.}
{208}{}{Nice survival kit.}
{209}{}{Good luck out there. May the road's dust hit your back and blur your enemies' eyes.}

{210}{}{Hey. How's it going?}
{211}{}{Okay I guess. Bye.}
