{100}{}{You see a highwayman.}
{101}{}{You see one of the Blue Shields.}
{102}{}{The raider is unwilling to negotiate.}

{110}{}{Hey, how's business?}
{111}{}{Good luck on the trail.}
{112}{}{You're tougher than we thought.}
{113}{}{Can't believe we're the route protectors now.}
{114}{}{The tracks are under our control now.}
{115}{}{You bring us luck.}
{116}{}{Ben trusts you.}

{120}{}{Keep staring at me, and I'll make you regret it.}
{121}{}{What do you want, trash?}
{122}{}{*Spits on your foot*}
{123}{}{Even though Ben let you in, you're not a gang member yet.}
{124}{}{I'm bored. Entertain me.}
{125}{}{You're taking a big risk being here.}
{126}{}{Don't cross us.}

{130}{}{Who the fuck are you? Are you from the Tinsmiths?}
{131}{}{It's him, keep quiet over there.}
{132}{}{I'd like armor like yours.}

{199}{}{ }
{200}{}{What are you staring at, cowboy?}
{201}{}{At you, bitch.}
{202}{}{I hate it when people call me that.}
{203}{}{Well, get used to it, BITCH.}
{204}{}{Watch your language, you piece of roadside crap, or...}
{205}{}{Or what? Ooh, you gonna put up a fight?}
{206}{}{Okay, one more word and...}
{207}{}{What are you going to do, baby? You want a bitch-slap? 'Cause I'm ready to spank you...}
{208}{}{Do you want a piece of me, mother fucker?}
{209}{}{You want some, huh?}
{210}{}{*Ugh*}
{211}{}{No, everything is fine... Sorry, I got a little worked up...}
{212}{}{Yeah, I know what you mean.}
{213}{}{. . .}
