{100}{}{You see Teresa.}
{101}{}{You see a short-haired woman in a robe, with a stern expression on her face.}
{102}{}{Sorry, but I need to get some sleep before class.}
{103}{}{How dare you scare children with your terrible armor?}
{104}{}{School is no place for weapons.}

{200}{}{Hello. What brings you here?}
{201}{}{What is this place?}
{202}{}{It's sad that people have forgotten what "school" means. This is a school, and here, we teach children basic skills, like literacy and mathematics. We are probably the only school currently operating in Sonora and Arizona.}
{203}{}{But why do they need this?}
{204}{}{So that the world doesn't slide back into the Stone Age. There are no schools or universities left in the wasteland. Ancient knowledge is forgotten, and new knowledge isn't accumulated because people are too busy surviving. A scientific approach could solve this problem.}
{205}{}{Who do you take me for? I know what a school is!}
{206}{}{Alright, but judging by your tone, it doesn't seem like you attended one.}
{1206}{}{Alright, but judging by your tone, it doesn't seem like you attended one.}
{207}{}{Amazing! A real school! I thought there were none left after the Great War.}
{208}{}{That's right, there weren't. We had to work hard to revive the old tradition. Many residents didn't even want to send their children at first.}
{209}{}{But who are you... why do you teach children to write and count?}
{210}{}{Who are you to teach children to write and count?}
{211}{}{How interesting. Who created this school?}
{212}{}{We are the Followers of the Apocalypse. Our mission is to bring enlightenment to the lands of Sonora.}
{213}{}{I see.}
{214}{}{I came across the Followers of Fire. They also have a library and teach children.}
{215}{}{Those crazy people don't know what they're talking about. What can they teach with their twisted faith? Don't confuse a scientific school with a theological one. We, the Followers of the Apocalypse, are the true torch bearers of pre-war science.}
{216}{}{Really?}
{217}{}{Don't trust zealots like them. Who knows what twisted ideologies control their minds.}
{218}{}{Okay.}

{220}{}{So, what do you want to know?}
{221}{}{I know enough. Goodbye.}
{222}{}{Wait a minute. Let's be clear - knowledge is taught here, not martial arts. We don't tolerate violence at school. So keep your fists, knives, and other weapons to yourself. And don't smile so brazenly. You've been warned.}
{223}{}{Agreed. My fighting skills will stay outside the school.}
{224}{}{Well, you'd have to use violence to not 'tolerate' it. Just saying.}

{230}{}{Tell me about the Followers.}
{231}{}{We started as a small group in the ruins of San Diego. But it was impossible to live there, so we moved to the Angel's Boneyard. There, in a barely surviving library, we established a headquarters that still exists today.}
{232}{}{Continue.}
{233}{}{Look at this old photo. It was taken a hundred years ago in Inferno.}
{234}{}{What is this... Oh my god, incredible! If the date is correct, this is a real piece of ancient history!}
{235}{}{I see you appreciate this a lot.}
{236}{}{We haven't seen a single document from the Great War. They say the War lasted just a few hours, with thousands of nuclear bombs exploding across the planet. Many documents didn't survive, and books have become very rare.}
{237}{}{Continue.}
{238}{}{Here we have direct evidence of what a nuclear explosion in Mexicali looked like... Well, that was the name of that town before the War.}
{239}{}{Nowadays it's called Inferno. Do you want to buy it?}
{240}{}{Of course! For the sake of science.}
{241}{}{Take it. Consider this my donation to the school.}
{242}{}{Thank you very much. We'll add your name to the list of benefactors.}
{243}{}{Not so fast. It took me a lot of effort to get this and bring it here.}
{244}{}{Alright. Let me put together a set of medications for you. It's the most valuable thing our town has.}
{245}{}{Okay, a decent trade. Thanks.}
{246}{}{I'll give you this item, but I'd like to hear some lectures about that era in return.}
{247}{}{Oh, what an honor.}
{248}{}{Since then, many people have joined us. Some, like me, travel to distant lands for missionary purposes to establish new temples of science.}
{249}{}{Temples of science? So you're still a religious organization?}
{250}{}{No, it's just an old expression. Science and religion rarely overlap. We don't call them churches because churches encourage arguments about God and belittle non-believers. But temples on the other hand...}
{251}{}{Thanks for the story.}

{260}{}{Where do these old books come from?}
{261}{}{They are mostly brought by caravans. We collected what was preserved in the surrounding ruins a long time ago.}
{262}{}{I see.}
{263}{}{Alas, these four small shelvess are nothing compared to the Boneyard library. Most of these books aren't very useful for teaching or science.}
{264}{}{I can bring you books I find on my travels.}
{265}{}{Oh, that would be great. We appreciate every find. Of course, we'll pay for them.}
{266}{}{I'll keep that in mind. Goodbye.}
{267}{}{I have an old book for your library.}
{268}{}{Wonderful. Where is it?}
{269}{}{It's in a different place. I'll bring it soon.}
{270}{}{Here is the book.}
{271}{}{I have two books here.}
{272}{}{Actually, I have three. Here they are.}
{273}{}{Take all the books I have. There's a whole stack of them.}
{274}{}{Thank you very much. Here's your payment - }
{275}{}{ caps.}
{276}{}{I'll find more if I can. Goodbye.}
{277}{}{Leave the caps for your school. This is my donation.}
{278}{}{Thanks. This will help our school.}
{279}{}{Goodbye.}

{280}{}{Where can I find old books?}
{281}{}{We and our mercenaries are already exploring the nearby ruins. I doubt there are any deposits of ancient books nearby. But there's one place, though access is closed: a military base in Puerto.}
{282}{}{Why would there be books at a military base?}
{283}{}{They're not exactly books, but electronic versions of them. I know this thanks to communication with the Brotherhood of Steel scribes. But they refused to share their knowledge.}
{284}{}{What cheapskates.}
{285}{}{They probably have their reasons.}
{286}{}{But old books belong to all humanity, not just a select few. Maybe you could infiltrate the base and copy the texts? I'll pay and give you an empty holotape for recording.}
{287}{}{That's not on my path. Sorry.}
{288}{}{Alright, I'll do it. Give me the holotape.}
{289}{}{Thank you! Here's the holotape. Copy at least the most important and useful texts for our school. Good luck.}
{290}{}{Goodbye.}
{291}{}{We and our mercenaries are already exploring the nearby ruins. I doubt there are any deposits of ancient books nearby.}
{292}{}{I see. We'll have to look in more distant areas.}
{293}{}{I managed to infiltrate the Brotherhood's base and record their books.}
{294}{}{Wow, that's great news! We need books in any form. The Brotherhood has no moral right to hide them from the public.}
{295}{}{Here's the holotape.}
{296}{}{I'll pay 100 caps for it. Thank you very much.}
{297}{}{You're welcome.}
