{100}{}{You see Alexandra.}
{101}{}{You see a smiling girl who doesn't quite understand where she's ended up yet.}
{102}{}{Sorry, you can't bring weapons in here.}
{103}{}{Sorry, you can't come in wearing armor.}
{104}{}{I... hnnnn... want to sleep. Come back in the morning...}

{200}{}{Oh, hi! This is the first time I've seen you.}
{201}{}{I'm }
{202}{}{. What's your name?}
{203}{}{Ditto. Who are you?}
{204}{}{Alexandra Titova. I'm Nestor's assistant. Nice to meet you.}
{205}{}{You have an unusual last name.}
{206}{}{That's a ridiculous name.}
{207}{}{My ancestors were from another part of the world. But now it doesn't matter. The name is just a tribute to the past.}
{208}{}{I see.}
{209}{}{Sounds like a tribute to insanity, if you ask me.}

{220}{}{Can I help you with something?}
{221}{}{I don't need help right now. See you.}
{222}{}{What's going on? Why are there so many people in the square?}
{223}{}{The residents are worried about the explosion in Puerto. It's unclear how we'll survive without the Brotherhood of Steel. I really hope they don't start a revolution and just settle down soon.}
{224}{}{So that's what's up...}
{225}{}{I need some medicine.}

{230}{}{Tell me about Nestor.}
{231}{}{Well, he's the only real doctor in town. He's also a nerd, but he's cool.}
{232}{}{What about you?}
{233}{}{I'm just learning from him. I still have a long way to go to become a doctor. But I can sew up a wound... I think.}
{234}{}{I see.}
{235}{}{What is this place?}
{236}{}{Saint Diego Followers of the Apocalypse Charity Clinic.}
{237}{}{Now I understand what the smell is around here.}
{238}{}{Wow, a real hospital! So can I heal my wounds here?}
{239}{}{We treat everyone in need, conduct experiments, and make medicine. Yes, because of all this, it sometimes smells kinda bad in here. But you quickly get used to it.}
{240}{}{Can I buy medicine for the road? I could use some radscorpion antidote.}
{241}{}{Of course. Just tell me what you need. But we hope that in return you'll also contribute something useful to our hospital.}
{242}{}{Great. I'll keep that in mind.}
{243}{}{Hey, you're back! We're going through some tough times here.}
{1243}{}{Hey, you're back! We're going through some tough times here.}
{244}{}{What do you mean?}
{245}{}{Imagine, the Brotherhood of Steel fort exploded! They say the explosion was like a nuclear bomb. Without them, trade in Casa Nueva is dwindling. And we'll have to spend a lot of caps on protecting our town...}
{246}{}{And?}
{247}{}{Well, it'll mean that prices have gone up, including our clinic's services.}
{248}{}{I see. I'll keep that in mind.}

{250}{}{Listen, is there anything stronger than bandages and stimpaks?}
{251}{}{Like what?}
{252}{}{No, it's okay, forget it.}
{253}{}{You know, like pre-war medicine. It was clearly better than today's.}
{254}{}{Yeah, I think so too. But we're prohibited from selling some old medicines and chemicals like Buffout and Psycho. They're considered unsafe.}
{255}{}{Then it's not worth discussing. Let's change the subject.}
{256}{}{Yes, yes, but that's exactly what I'm looking for. Is there really no way to get at least a pinch? For scientific purposes?}
{257}{}{I don't know what your scientific goals are, but I have clear instructions. Talk to Nestor if you don't like it.}
{258}{}{Okay. There seems to be no point in continuing. Bye.}
{259}{}{Come on - I'll give you a mountain of caps!}
{260}{}{Ahem. I think you need some fresh air. The door is over there.}
{261}{}{You should think about changing your mind, if you know what's good for you.}
{262}{}{Okay, I don't want any trouble. I'm leaving.}
{263}{}{Think about it, what good is it for your clinic to have damaged goods that people don't buy or use?}
{264}{}{Yes... of course... Hmm, maybe Nestor will make an exception for you. We really don't have enough caps.}
{265}{}{Thanks.}
{266}{}{Please make an exception for me. I won't tell anyone.}
{267}{}{Nestor will allow it. You could say I'm already a member of your team.}
{268}{}{I need a dose for...what's their name...for experiments, yes.}
{269}{}{I have a purely scientific interest, colleague. We both understand how important it is for scientists to support each other.}
{270}{}{You'd be surprised, but this has really become a problem in Phoenix. I personally know a drug addict from the slums.}
{271}{}{Poor people. Yet this is how science suffers because of someone's stupidity. Is drug addiction the fault of medicine?}
{272}{}{Right, still, isn't there a way to get at least a pinch of the drug? For scientific purposes?}
{273}{}{There's no need to discuss this anymore. Lets talk about something else.}
{274}{}{Diana knows I won't do anything stupid.}
