{100}{}{You see Wang Chong.}
{101}{}{You see a large, spreading tree. The pattern on its bark reminds you of a man's face. Wait a minute...}
{102}{}{*Cough cough*}
{103}{}{It's hard to talk in this smoke. We need to get out into the fresh air quickly.}

{110}{}{Hrrr}
{111}{}{Z-z-z}
{112}{}{Here, my sweet mantissas, yes, get into my mouth.}
{113}{}{Yum-yum, what a juicy mantissa.}
{114}{}{My roots sense the stranger.}
{115}{}{Hmm, I smell unfamiliar footsteps.}
{116}{}{What is this? What are you saying?}
{117}{}{Herbert, Bob, Nestor - you've grown so much lately.}
{118}{}{Now I understand how much you miss sunlight.}
{119}{}{We need more human compost fertilizer.}
{120}{}{Uh-oh...}
{121}{}{*Heavy sigh*}

{150}{}{Go, my little green friends!}
{151}{}{Grab them and rip them to shreds!}
{152}{}{Show off your prowess!}
{153}{}{Grab them with your sharp little paws!}

{200}{}{Ah... Uh... *Yaaawn* How long have I been sleeping... My goodness... Oh, a guest... So that's why my servants woke me up.}
{201}{}{Uh, who are you... or what are you?}
{202}{}{What the... A talking plant!}
{203}{}{I... I am Wang Chong, the scientist who cultivated these paradise gardens. And you are? Oh yes, I know. People like you are drawn to the scent of nectar like foolish butterflies, only to be devoured by predatory plants. Coming here was a grave mistake on your part.}
{204}{}{Why is that?}
{205}{}{You know, if I weren't so obsessed with science and the future of this world, I'd have left this place ages ago. But now, this is my home, my final resting place. From dust we came, and to dust we shall return.}
{206}{}{What are you talking about?}
{207}{}{Ah, the ceaseless cycle of nature. We are but clumps of sticky mud. Look at me now, rooted to the ground where once I roamed freely like a wind-blown tumbleweed.}
{208}{}{You're too talkative to be a plant.}
{209}{}{Amusing. I can't use my arms and legs anymore, but my mind remains active. I'm trying my best not to go mad. I've had a great deal of time to ponder on myself and the world around me.}
{210}{}{I'm so sorry. Are you in pain?}
{211}{}{Not anymore. My body is now a host to spores and plant cells. While I can't use my arms or legs, my mind remains sharp. I'm doing my best not to lose my sanity. I've had plenty of time to reflect on myself and the world around me.}
{212}{}{It's sad to see you like this. But I have important business here. Bye.}
{213}{}{No! Wait! I was just as foolish and reckless when I entered this dome, eager to taste the forbidden fruits of the Ancients. I rushed, made mistakes, and now this valley is a paradise for mutants. If this isn't stopped, the entire wasteland will transform. People will witness the birth of a new world, but there will be no place for them in it.}
{214}{}{I'm here on behalf of Nestor. I need documents and chemicals to fight the infection.}
{215}{}{I don't want to be exposed to the same infection. Is there any medicine against it?}
{216}{}{Infection? Do you mean people are still clinging to the remnants of the Old World? Oh, how blind I was when I first entered this dome, eager to taste the fruits of the Ancients! I rushed, made mistakes, and now this valley is a mutant's paradise. If we don't stop this, the wasteland will change, and there will be no place for people in this new world.}
{217}{}{How can that be? Can't this infection be stopped?}
{218}{}{It can be. But if the Followers obtain the lab records and materials from this complex, they will eventually continue the research, and the disaster will repeat itself.}
{219}{}{Then what are you suggesting?}
{220}{}{We need to destroy the ENTIRE complex! Fire is the best way to stop the infection from spreading beyond the valley. The dome is the main breeding ground.}
{221}{}{So, the main thing is to stop the infection here. I'll do it.}
{222}{}{Very good. Find the gas pipes. It's not easy to set them ablaze, but someone has tried before. Look for his remains in the greenhouses and take the explosives.}
{223}{}{Okay. I'll try.}
{224}{}{Too risky. Goodbye, Wang Chong.}
{225}{}{You're definitely losing it. There is no place in the wasteland more colorful and alive than this dome. There must be a way to stop the infection without destroying everything.}
{226}{}{Fool! I've searched for ways to limit the spread of harmful spores, but there's no way to be certain if it'll work! What if the spread of the mutations continues? If it spreads too far, it may never be stopped. Find the gas pipes and blow them up! It's the only way!}

{230}{}{*Heavy sigh*}
{231}{}{Z-z-z}
{232}{}{Hrrr}
{233}{}{Whatever it is, this creature is fast asleep.}
