{100}{}{You see Pinky.}
{101}{}{You see... a pet pig rat. Quite unusual...}
{102}{}{Squeak!}
{103}{}{Grunt!}
{104}{}{Pinky died suddenly.}
{105}{}{Squee...}
{106}{}{Grrrr...}
{107}{}{Grunt-grunt-squeal!}

{200}{}{Squeak!}
{201}{}{Yes, yes, squeak to you too.}
{202}{}{Can you talk, little guy?}
{203}{}{Hey, Pinky, follow me.}
{204}{}{Squeak! Squeak!}
{205}{}{Good Pinky.}
{206}{}{Wait here, Pinky.}
{207}{}{Go home, Pinky.}
