{100}{}{You see Rosalia.}
{101}{}{You see a woman in well-kept peasant clothes.}
{102}{}{Hello, stranger. What news from the wastelands?}
{1102}{}{Hello, stranger. What news from the wastelands?}
{103}{}{Bastards! They keep me locked up so I don't say too much and to make sure others stop trusting me.}

#First meeting
{200}{}{Hey, stranger... Uh, hi. This is your first time with us, right?}
{1200}{}{Hey, stranger... Uh, hi. This is your first time with us, right?}
{201}{}{Why do you ask?}
{202}{}{Well, I'd like to talk to you... in private, if that's okay.}
{203}{}{Of course. Why not?}
{204}{}{Sounds suspicious. What do you want from me?}
{205}{}{This is important. Let's meet outside the town gates where no one can overhear us, okay?}
{206}{}{Okay. Meet me near the billboard.}
{207}{}{Okay, but you better not be scamming me.}
{208}{}{Get lost.}

{210}{}{Thanks for coming. Were you being followed?}
{1210}{}{Thanks for coming. Were you being followed?}
{211}{}{No... What do you want from me?}
{212}{}{You see... My husband recently disappeared. He went to the plantation and never returned. I looked for him but couldn't find him. I need your help!}
{213}{}{But why be so secretive?}
{214}{}{I'm not allowed to talk about this! To avoid causing panic, that's what the mayor says. This is definitely a conspiracy! They're clearly hiding something.}
{215}{}{What about the others? Why isn't the whole village looking for him?}
{216}{}{This place isn't as peaceful as it seems. We're forced to remain silent, but believe me, this isn't the first time people have disappeared.}
{217}{}{Forced? How so?}
{218}{}{The rules here are very strict. From the outside, the town looks idyllic, but in reality, we pay for it with our freedom. Any dissenters are punished or thrown out of the gates.}
{219}{}{Okay. I'll look for him. What does he look like?}
{220}{}{Dark, short, wears a mustache... Oh, and he had a wedding pendant with him. The mayor gives these to everyone who gets married in our town.}
{221}{}{Don't worry, I'll see if I can find him.}
{222}{}{I don't promise anything.}
{223}{}{This is shady business and looks risky. I'll see what I can dig up, but it'll cost you.}
{224}{}{Of course. I'll get you some food and give you all my caps -- I have nothing else anyway.}
{225}{}{Please find him! I have no one else to turn to!}
{226}{}{Okay, calm down.}

{230}{}{How's everything? Not the best on my end, as you can tell.}
{231}{}{So? Did you manage to find him?}
{232}{}{Not yet.}
{233}{}{I see. Bye.}

{240}{}{We haven't been introduced yet. What's your name?}
{241}{}{Oh, sorry. I'm Rosalia, I handle harvest processing.}
{242}{}{I gotta go, Rosalia.}
{243}{}{They say you had a fight with your husband?}
{244}{}{Of course we had our fights! It wasn't a love marriage. The mayor's office is supportive of marriages and gives us some benefits. But over the years, my husband and I somehow got used to each other...}
{245}{}{I see...}
{246}{}{Hold on a second - who told you this? I hope you haven't mentioned it to Mayor Alvaro. He can't be trusted! Do you understand? Don't even think about discussing the missing people with him.}
{1246}{}{Hold on a second - who told you this? I hope you haven't mentioned it to Mayor Alvaro. He can't be trusted! Do you understand? Don't even think about discussing the missing people with him.}
{247}{}{Okay, calm down...}

{250}{}{Your husband is dead. I'm really sorry.}
{251}{}{Was your husband a green mutant freak? Because if so, he has completely withered away and lies rotting in a barn on the plantation.}
{252}{}{I knew it... I knew it. Was he killed? Tell me the truth!}
{253}{}{Something strange happened to him. It's some kind of a... disease. You better go and see.}
{254}{}{My god... What happened to him? We knew that some insects spread infection, but for the infection to spread through his body like THIS?}
{255}{}{So this isn't the first time this has happened?}
{256}{}{It's all the Followers' fault. They've killed him with their experiments! And he's not the only one! Devils!}
{257}{}{Followers of the Apocalypse? What kind of experiments?}
{258}{}{They have a laboratory in the desert. But we're forbidden to even approach there... Ah, damned scientists! They gave us the harvest, but they took our souls.}
{259}{}{[Keep silent]}
{260}{}{You have a good heart, stranger. Bless you. And stay away from those scientists.}
{1260}{}{You have a good heart, stranger. Bless you. And stay away from those scientists.}
{261}{}{Don't despair, Rosalia. Goodbye.}
{262}{}{I think I should discuss this with them, though. Goodbye.}
{263}{}{My job is done. How about payment?}
{264}{}{What do you need? Caps? Take it all and leave me alone! You wastelanders think of nothing but yourselves...}
{265}{}{Don't get so wound up, woman.}
