{100}{}{You see a power plant ghoul.}
{101}{}{You see a person with burnt, decaying skin, wearing a worn-out pre-war work uniform.}
{102}{}{Well, well, here's our main troublemaker. Get lost before you lose your teeth.}

{110}{}{Shh, that outsider might hear.}

{200}{}{Hey, wanderer. We don't let strangers in often.}
{201}{}{Got a pass? Never mind.}
{202}{}{Yeah, take a look around. It's interesting here.}
{203}{}{What are you sniffing around for?}
{204}{}{Huh? Speak up, I'm a bit deaf.}
{205}{}{Access to the power plant is restricted. But you can go in.}
{206}{}{Strange they let you in. You know, we prefer our *own* kind...}
{207}{}{We don't look like this for fun, kid.}

{210}{}{Hey buddy, how long have you been a mutant?}
{211}{}{You have nice skin... for a mutant.}
{212}{}{Come see me after work. We'll hang out.}
{213}{}{Huh? Speak up, I'm a bit deaf.}
{214}{}{Yeah, make yourself at home. It's pretty nice here.}
{215}{}{Smoothskins aren't allowed. But mutants are always welcome.}
{216}{}{Hey, how about some sunbathing in the reactor zone?}
{217}{}{New to being a mutant? I'm jealous.}
