{100}{}{You see a power plant ghoul before you.}
{101}{}{You see a man with burned, decaying skin. He's wearing worn work clothes with a pre-war symbol.}
{102}{}{Thanks, Doc. I really appreciate it.}
{103}{}{I've got a problem here. Do you know any doctors?}

{200}{}{Hey, thank you so much. I didn't think there were any doctors around these days.}
{201}{}{What happened to you?}
{202}{}{We were repairing some pipes when one burst, and I was thrown onto the railing. At least I didn't fall to the lower level. Otherwise, I'd be swimming in radioactive sludge like a duck in an bathtub.}
{203}{}{Well, you're definitely lucky. Take care.}
{204}{}{See you later.}
{205}{}{Duck?}
{206}{}{Yeah, you know, a bird. Before the nuclear war. Haven't seen a live one since. Probably went extinct like the dinosaurs...}
{207}{}{Dinosaurs?}
{208}{}{Ah, never mind. Let's drop it.}

{210}{}{Hey, Doc. Thanks again.}
{211}{}{Don't mention it.}
