{100}{}{You see a junkie.}
{101}{}{You see a disheveled guy. From the looks of it, things are going badly for him.}
{102}{}{Ah... I'm... choking...}

#Answers after Recovery
{110}{}{Leave me alone.}
{111}{}{I need to rest up.}
{112}{}{I'll start a new life tomorrow.}
{113}{}{Do you have any dope?}
{114}{}{You won't tell anyone, will you?}

{115}{}{(looking around) We might be being followed.}
{116}{}{Why did they kill Gonzalez?}
{117}{}{Gonzalez had everything, but I had nothing to pay with.}
{118}{}{The Followers must have killed Gonzalez.}
{119}{}{If they got to Gonzalez, I'm in danger too.}

#First Dialogue
{200}{}{(shuddering as if in a fever) W-what do you want?}
{201}{}{You don't look so good. Are you sick or something?}
{202}{}{I'm p-perfectly f-fine.}
{203}{}{I find that hard to believe.}
{204}{}{L-listen, I'm f-fine. Leave me alone.}
{205}{}{Whatever you say.}
{206}{}{With pleasure. You look like you might be infectious.}
{207}{}{Not so fast. Answer my questions first.}

#Re-dialogue
{210}{}{Leave m-me alone.}
{211}{}{Bye.}

{212}{}{You again?}
{213}{}{I see you're getting back to normal. You look better than when we last met.}
{214}{}{I'm worse than ever! Gonzalez is gone, and now there's nowhere to get the drugs he was cooking. Where will I get my next fix?}
{215}{}{You won't. And once the withdrawal is over, you won't want to go back to it.}
{216}{}{There won't be a next fix. And say "thank you" for not helping you follow your dealer's fate.}

{220}{}{Who are you anyway?}
{221}{}{Me? I'm Larry. W-what do you w-want?}
{222}{}{What are you doing here, Larry?}
{223}{}{Why are you pestering me? I just live here and earn caps any way I can.}
{1223}{}{Why are you pestering me, bitch? I just live here and earn caps any way I can.}
{224}{}{You don't really seem to be doing anything. Bye.}
{225}{}{I'm sorry to see you like this. Hang in there.}

{230}{}{You don't look good. You need a doctor.}
{231}{}{I don't n-need a doctor! I'm fine! Just leave me alone!}
{232}{}{Whoa, no need to freak out...}
{233}{}{Let me examine you, I'm a... doctor.}
{234}{}{I don't n-need a doctor, just some... uh... m-medicine. Then I'll be fine.}
{235}{}{Medicine. Right. Judging by your dilated pupils and other symptoms, you're pretty hooked on some nasty stuff.}
{236}{}{Maybe. What do you want anyway?}
{237}{}{Who supplies you?}
{238}{}{Gonzalez. Everyone knows he pushes treats on the street near the arena. He has killer dope, but I don't have enough caps for another fix. Just let me rest in peace; tomorrow I'll be as good as new.}
{239}{}{Alright. It's your problem.}

{240}{}{So you're the one who's wasting his life away with drugs?}
{241}{}{Go to hell! It's my business w-what kind of dope I take and when I t-take it.}
{242}{}{What kind of drugs *are* you taking?}
{243}{}{A mixture of Psycho, p-painkillers, and mentats. Killer stuff. You start s-s-seeing leprechauns and flying cars. At least there's some joy in these d-damn slums.}
{244}{}{Why did you even start with this crap?}
{245}{}{Well, it started with a f-fever medicine. It really cured me, made me f-feel great again, but then I r-realized I c-c-couldn't stop taking it. It's not easy to quit.}
{246}{}{Who supplies you?}
{247}{}{All the drugs in the slums c-c-come from Gonzalez.}
{248}{}{Hmm. I'll go talk to this Gonzalez guy.}

{250}{}{Larry, you need to give it up.}
{251}{}{Go to hell. I feel g-g-good. I don't need help. I've got it under c-control.}
{252}{}{Well, well. Typical.}
{253}{}{Your dealer won't sell you any more drugs.}
{254}{}{What?! What do you mean? Why?}
{255}{}{Because it's time for you to quit.}
{256}{}{I'll die without my fix! Where will I get a n-new fix now?}
{257}{}{Think about the future. This is not an option, Larry.}
{258}{}{What do you understand? I have everything under c-control. I know when to stop.}
{259}{}{Sure you do.}
{260}{}{Stop poisoning yourself. Your wife and children need you, Larry.}
{261}{}{Yes... I almost forgot about them... What a fool I've been... Thanks, I've gotta try to break this habit... start over.}
{262}{}{I'll take your word for it. Goodbye, Larry.}
{263}{}{If you keep doing this, you'll die.}
{264}{}{Your body's on the edge, Larry. You're gonna die soon.}
{265}{}{Are you a doctor? Why the h-hell are you scaring m-m-me so much?}
{266}{}{Yes, I'm a doctor. And I'm telling the truth.}
{267}{}{Damn... I know I don't have much time left. But I can't stop. What should I d-do?}
{268}{}{You'll have to quit cold-turkey. Otherwise you'll be dead in a few weeks. It'll be tough, but it's the only way.}
{269}{}{A few weeks!? Oh god... Looks like I have no choice but to quit. Thanks, doc.}
{270}{}{Good luck, Larry.}
{271}{}{No, sorry, I'm not a doctor.}
{272}{}{I have some mentats. Try them, maybe it'll clear your head. But this stuff is going to kill you in a few weeks.}
