{100}{}{You see Badi.}
{101}{}{You see an ordinary beggar, barely scraping by. It's a wonder he's still alive.}
{102}{}{Hello, partner. How are you?}
{103}{}{One day, I'll get my revenge.}

{200}{}{Here it is. Be careful, the robots are around here somewhere. If you take them out, all the caps are ours.}
{201}{}{Let's not waste time. Wait here.}
{202}{}{Well no shit. Wait here.}
{203}{}{I need more info about this place first.}

{210}{}{Let's not waste too much time.}
{211}{}{Wait here.}
{212}{}{It's almost night. Let's hurry, okay?}

{220}{}{What is this place anyway?}
{221}{}{Pre-war Nuka Cola warehouse. They stored the drink here before distribution. The bottling plant itself was destroyed in the nuclear blast.}
{222}{}{Why hasn't this place been ransacked by scavengers yet?}
{223}{}{The surrounding ruins make it pretty hard to get here. Plus, the nearby nuclear blast zone scares most people off. And, of course, the damn robots.}
{224}{}{Any ideas on how I could, maybe, disable the robots?}
{225}{}{I thought you'd know how to do that. Maybe there's a switch or something inside. I don't get tech stuff, especially the pre-war kind. No one does, except maybe the Cathedral's followers.}
{226}{}{Remind me what we're looking for?}
{227}{}{Caps! Lots and lots of bottle caps.}
{228}{}{Right.}
{229}{}{I'll be back soon.}

{250}{}{These are all the caps I found in there.}
{251}{}{A full box? Damn, that's a fortune! We're richer than most of the people in the city now. Can you believe it?}
{252}{}{Not so fast. First, you're gonna pay off your debt to the casino.}
{253}{}{Ah, yes. Right. I almost forgot in my excitement. Here you go.}
{254}{}{Great. Now give me my share -- half of what's left.}
{255}{}{Ugh, that leaves less than I expected. There's barely enough to cover my rent and other debts. I'll be broke again.}
{256}{}{That's how it goes. You shouldn't have let it get this bad. Now it's time to head back to the city. Bye.}
{257}{}{You know, I changed my mind. I'm taking ALL the caps for myself.}
{1257}{}{You know, I changed my mind. I'm taking ALL the caps for myself.}
{258}{}{No! You can't do this! We're partners, I showed you this place... Damn it, someday... someday I'll earn enough caps to hire mercenaries to hunt you down. And then I'll play football with your head. You'll remember this day.}
{259}{}{Good luck with that. Later, loser.}
{260}{}{Hmph. Then I guess I better finish you right now.}
