{100}{}{You see a big man.}
{101}{}{You see one of Don Diego's men.}

{110}{}{My respects. How is Don Diego?}
{111}{}{I can't figure out how you got along with the boss.}
{112}{}{Can I help you with something?}
{113}{}{Send my deepest respects to Don Diego.}
{114}{}{Could you ask the Don about my promotion?}

{115}{}{My respects.}
{116}{}{How are you?}
{117}{}{Go back to the casino.}
{118}{}{The boss won't like you being here.}
{119}{}{My job is to keep things safe.}

{120}{}{You better not stay here.}
{121}{}{This is a service area, what are you doing here?}
{122}{}{Do you have business with the boss? Then go to him.}
{123}{}{The boss won't like me talking to you.}
{124}{}{If I find out you're a spy...}

{125}{}{What are you doing here?}
{126}{}{Spying?}
{127}{}{Hey, get back to the casino now.}
{128}{}{These are service areas.}
{129}{}{You don't belong here.}
