{100}{}{You see a Follower of Fire.}
{101}{}{You see one of the Followers. He has become completely withdrawn due to fervent prayer.}

{200}{}{...Heaven will become earth... Fire is God... And he said that he is pitiful in His face... Fire... The infidels will fall... The sun is in our hands... Flowers...}
{201}{}{Hey, what are you muttering?}
{202}{}{...Fire is power...}
{203}{}{Your Fire is just made-up nonsense.}
{204}{}{(Distracted from his prayer, he looks through you with an empty gaze) Fire... is... truth...}
{205}{}{Ah, well, now everything makes sense.}
{206}{}{Eh, better not bother him...}
