{100}{}{You see a refugee.}
{101}{}{You see a very agitated man.}
{102}{}{We're leaving. We will no longer set foot in this savage city.}

{110}{}{We need to get out of here.} 
{111}{}{There's no other option.} 
{112}{}{Heading south is our best bet.} 
{113}{}{Where did everyone else go?} 
{114}{}{We can't make it across the desert.} 
{115}{}{Crossing the desert is a death sentence.} 
{116}{}{If not south, then where?} 
{117}{}{Maybe we should try the mountains to the west?} 
{118}{}{I heard whispers about a vault, but who knows where it is?} 
{119}{}{It's time to move.}

{200}{}{(A small group in front of you is deep in conversation)} 
{201}{}{Hey, what's going on?} 
{202}{}{(They all turn to face you; fear and tension are clear in their eyes) You already know. The disaster... a hole blown right into our city. Not just in the ground, but in its spirit too.} 
{203}{}{Are you talking about the cathedral explosion?} 
{204}{}{Of course. Half the city relied on that place! Now, what's left for us here? We have to leave, find somewhere safer.} 
{205}{}{Good decision. Well, good luck in your search.}
{206}{}{If you find someplace better, you should take it. Because I'm watching you...}
{207}{}{You're not running just because of the explosion, are you? Were you tied to the cult?} 
{208}{}{(They exchange uneasy glances) It doesn't matter anymore... Our close family were cult members, so we had privileges. People resented us for it. Now, with the cult gone, there's no one left to shield us. The townspeople are hunting down anyone tied to the cult. If we stay, we're dead.} 
{209}{}{Seems like you've really got no choice. Good luck out there.} 
{210}{}{Yeah, get out of Phoenix, you arrogant fools.}
