{100}{}{You see a guard.}
{101}{}{You see a caravan guard, preparing for the journey ahead.}

{110}{}{Great.}
{111}{}{Gimme a rest.}
{112}{}{I'm thirsty.}
{113}{}{Time to move out.}
{114}{}{It's hot.}

{115}{}{Talk to the boss; I'm just guarding the cargo.}
{116}{}{We're all full, just lettin' you know.}
{117}{}{We need to sell everything, or we'll go bankrupt.}
{118}{}{We deliver goods to almost every corner of the wasteland.}
{119}{}{You should check out Atomic Rush, we hang out there often.}

{120}{}{Today is going to be a long day.}
{121}{}{I can't wait until we're done.}
{122}{}{What day is it today?}
{123}{}{I'm so tired.}
{124}{}{Time to go to bed, I guess.}

{125}{}{We have a dangerous job.}
{126}{}{Dust storms are sometimes more dangerous than highwaymen on the road.}
{127}{}{Walking along the highway now is like courting death.}
{128}{}{Yeah, I've fought off raiders and highwaymen on all the routes.}
{129}{}{If this cart falls apart on the way, I won't be the one fixing it.}
