{100}{}{You see a thug.}
{101}{}{You see a determined gangster.}
{102}{}{Okay! We're leaving! It's fine, don't panic!}

{110}{}{Where do you think you're going? This is our turf now.}
{111}{}{You talk a big talk. Prove this is your turf, you piece of shit.}
{112}{}{Ok, I'm sorry...}
{113}{}{Please leave, the locals don't want any trouble...}
{114}{}{But you're getting trouble! Got it? Now beat it, you moron, while you still can!}
{115}{}{You're in Cardinal territory. They don't tolerate competitors. Get lost.}
{116}{}{The Cardinals have been out of the picture for a while. Do you see them anywhere?}
{117}{}{Doesn't matter. I'm in charge here now. Get lost.}
{118}{}{The Cardinals still run this area. Beat it.}
{119}{}{Grrr! (grits his teeth, fists up, and backs towards the exit)}
{120}{}{Yeah, get out. And don't come back, moron...}
{121}{}{Guys, here's 100 caps. Just leave us alone, okay?}
{122}{}{See, all you needed was some motivation. See you next month, morons.}
{123}{}{Yeah, uh, bye...}
