{100}{}{You see a guard in front of you.}
{101}{}{You see one of the guild's mercenaries. She's watching you closely.}

{110}{}{Bruce's got a temper tougher than old boots.}
{111}{}{Bruce doesn't just keep order, he *enforces* it.}
{112}{}{Tried my best, but I ain't ever seen Bruce crack a smile.}
{113}{}{Bruce starts twitchin' when folks come in packin' heat.}
{114}{}{I'm watchin' you.}
{115}{}{You. Up against the wall-drop your pants... Just messin' with ya.}
{116}{}{Hands behind your head, face to the floor... Nah, relax, just jokin'.}
{117}{}{Smile, pal. Welcome to the happiest place in Phoenix.}
{118}{}{Fresh outta the wasteland, huh? You're still wet behind the ears in this city.}
{119}{}{Wasteland's been kind to you, huh? How'd you even make it here?}
{120}{}{Speak up, I ain't got time for whisperin'.}
{121}{}{Got a smoke?}
{122}{}{First time seein' armor like this? Go on, touch it, won't bite.}
{123}{}{Alright, open the bag and gimme all the goods... Nah, just playin'.}

