# Encounter with Marcos
{100}{}{You see Marcos.}
{101}{}{You see a man in a balaclava, his eyes gleaming with readiness for a fight.}
{102}{}{Go ahead, friend. The whole of Phoenix lies at your feet.}
{103}{}{Everything will change now. No more Inquisition, no more tyranny, no more wars with neighbors. Thank you, friend.}

# Dialogue
{200}{}{I'm surprised to see you here. Few know about this place, and the traps scare off even the toughest. But here you are. It's damn inspiring. What brings you to our Party?}
{201}{}{Party? Yeah, I just stumbled on this place by accident. What are you doing here? What is this place?}
{202}{}{You found this hideout and dodged all our traps by pure luck? Doubtful. But you're here now - we're fighting the Followers of Fire and their leader, Aaron. What do you think of that?}
{203}{}{I'm here to take down your entire criminal gang.}
{204}{}{Very good. Capture the spy!}
{205}{}{Just try...}
{206}{}{Hey, they misunderstood me...}

{210}{}{Sounds like something I can get behind. I can't stand these cultists either.}
{211}{}{Then you're just criminals. You need to be stopped.}
{212}{}{Hmm, I like you so far. We seem to share common interests. What do you say to helping us in our fight?}
{213}{}{You can count me in.}
{214}{}{Depends on what you need.}
{215}{}{Uh no. Don't get me involved in anything!}
{216}{}{That's disappointing. First impressions are usually correct.}
{217}{}{I won't tell anyone about you guys. I promise.}
{218}{}{I guess you're not that good at reading people, because now I'm gonna kill you.}
{219}{}{I'm afraid that answer doesn't work for me. Take this spy down!}
{220}{}{Oh shi...}
{221}{}{That was a mistake...}
{222}{}{Can I just leave and we'll forget this happened?}
{223}{}{You expect to walk out of here unscathed, do you? Maybe you will. Maybe you won't.}
{224}{}{Um, I think I'll just go now. Bye.}
{225}{}{I want to join your group.}
{226}{}{Very good. But we can't take risks by trusting just anyone. Tell me about yourself. Who are you and how do you know about the Liberation Party?}
{227}{}{I'm looking for my family. They were enslaved and brought to this city. I need help finding them.}
{228}{}{Actually, I'm looking for some shady, dangerous types to eliminate. And it looks like I found them.}
{1228}{}{Actually, I'm looking for some shady, dangerous types to eliminate. And it looks like I found them.}
{229}{}{(nods meaningfully) I understand. Everyone here has lost someone. Our paths must have crossed for a reason. Few know that the main customer for slave labor is the Fire Worshipper's cult. We fight these bastards. We should join forces.}
{230}{}{Hmm. Take a look around and meet the team. I'm planning something now and need to think.}
{231}{}{Alright, I will.}
{232}{}{If it helps get my people back, I'm in.}
{233}{}{How can I help your group?}
{1233}{}{How can I help your group?}
{234}{}{The Rangers sent me. They offer their help against Aaron.}
{235}{}{Rangers. I hoped for their help, but I was expecting more... impressive reinforcements. Still, any help is appreciated.}
{236}{}{Your cause is just.}
{237}{}{I await your instructions.}
{238}{}{Prior Matthias sent me from the Cathedral. I know about your cause and I want to help.}
{239}{}{Matthias doesn't throw words around lightly. It seems we have less time than we thought, and we must act more decisively.}

{250}{}{Greetings, brother.}
{1250}{}{Greetings, sister.}
{251}{}{See you later.}

{260}{}{Tell me about your organization.}
{261}{}{We are the Phoenix Liberation Party. Our goal is to free the city from Aaron's grip and topple his false church.}
{262}{}{Why do you call the church false?}
{263}{}{The Fire Worshippers twist the old religion to justify their leader's inhumane actions. They've forgotten the pre-war covenants.}
{264}{}{Why is it so important to overthrow Aaron?}
{265}{}{Without its leader, the church will fall in the eyes of the city.}
{266}{}{What will you do after you achieve your goal?}
{267}{}{We'll build a new society. One based on community and equality, not on separation and subordination.}
{268}{}{Thanks. Now I know enough.}

# Background Conversation
{270}{}{Tell me about your past.}
{271}{}{It doesn't matter.}
{272}{}{Whatever you say.}
{273}{}{We should trust each other, shouldn't we?}
{274}{}{Sure, but remember, we're not here to socialize.}
{275}{}{Yeah, uh, got it.}
{276}{}{I was born several years after Aaron came to power in the city. The person I was before died.}
{277}{}{Sounds pretty personal to me. Did you lose someone close?}
{278}{}{And you're smarter than you look. When Aaron seized power, he eradicated anyone who could oppose him. Blood ran through the streets of the entire city.}
{279}{}{[More]}
{280}{}{Many lost their loved ones to his Inquisition. But like I said, the past doesn't matter.}
{281}{}{Why did people go along with this? With his Inquisition?}
{282}{}{At the time, Phoenix was in the grip of a famine. Getting rid of extra mouths and keeping the weak in line served a lot of interests. The church, with its sermons and guidance, swayed the masses and tightened Aaron's grip on power.}
{283}{}{Sounds like it was a real tragedy for the city. Let's talk about today.}

# Quests
{300}{}{What do you need me to do?}
{301}{}{I've got a job for you. One of our agents has gone missing. Elisa can fill you in on the details.}
{302}{}{Alright, I'll talk to her.}
{303}{}{I need gear for the mission.}
{304}{}{See Elisa. She's in charge of the warehouse. I've got more urgent things to deal with.}
{305}{}{Got it.}

{310}{}{Elisa told me about your success. Well done. With your help, our mission is moving forward.}
{311}{}{That's good to hear.}
{312}{}{I think I can handle any task you give me. No problem.}
{313}{}{It's a shame we couldn't save our agent. But maybe it's for the best, considering what the cultists could've gotten out of him.}
{314}{}{Leaving him to the monks would've been too risky. It was the only way.}
{315}{}{It was out of my control. Things just went down that way.}
{316}{}{The agent you rescued filled us in. Getting him out of that trap was impressive.}
{317}{}{Yeah, it was wild. Crossfire, explosions... You should've seen the firefight. Our lives were hanging by a thread.}
{318}{}{It wasn't that bad.}

{320}{}{Well, now's the time we're really going to need your skills. We're about to make our big move, and your help will be critical.}
{321}{}{What's the plan?}
{322}{}{Thanks to the signal booster, we've learned a lot about the cultists. Turns out those hidden levels under the cathedral? They're real. We don't know exactly what the monks are up to, but it looks like they're stockpiling or building some heavy-duty weapons. We can't let that slide.}
{323}{}{So, you're saying we go in and destroy the weapons? But how?}
{324}{}{More than that. As you know, in the cathedral, Matthias is aligned with our cause. Your task is to contact Matthias, help him take over the cathedral, and then destroy the weapons. He'll give you further instructions.}
{325}{}{The task is clear.}
{326}{}{Good luck. The city can no longer tolerate Aaron's unrestrained power.}
{327}{}{Contact Matthias, enter the laboratory, and destroy the weapon. Understood.}
{328}{}{More than just destroy the weapons. There's someone in the cathedral who sympathizes with us. His name is Matthias. He's not our agent, but he has his own vendetta against Aaron. Your task is to contact Matthias, help him take over the cathedral, and then destroy the weapons. He'll give further instructions.}
{329}{}{See you after, Marcos.}

{330}{}{Aaron is defeated.}
{331}{}{Wonderful news! But it's not enough. We must destroy the ENTIRE cult. As long as Aaron's followers live, this fight won't end. Moreover, we don't know what decisions the new church leaders will make.}
{332}{}{What should we do?}
{333}{}{This news doesn't change your primary mission - infiltrate the secret lair beneath the Cathedral and destroy it using local weapons. Our agent, Matthias, will help you. Good luck, partner.}
{334}{}{Now that was easy.}
