{100}{}{You see one of the Red Cardinals.}
{101}{}{You see a gangster with a stylish haircut and a gang logo on his back.}
{102}{}{Wish I had armor like yours; the whole city would be at my feet.}

{110}{}{You looking to start something?}
{111}{}{Who the hell are you, anyway?}
{112}{}{Our turf, our rules.}
{113}{}{Everyone around here answers to us.}
{114}{}{Watch your mouth.}
{115}{}{Keep talking, and you'll be eating a fist.}
{116}{}{You even know who you're messing with?}
{117}{}{Got an opinion? Shove it.}
{118}{}{What are you selling here?}
{119}{}{You lost or just looking for trouble in our territory?}

{120}{}{Damn, we should've trusted you from the start.}
{121}{}{You're tougher than you look.}
{122}{}{Hey, what's up?}
{123}{}{Want a beer?}
{124}{}{Got business? I'm all in.}
{125}{}{If anything goes down, I've got your back.}
{126}{}{Everyone here is part of the crew. Make yourself at home.}
{127}{}{}
{128}{}{}
{129}{}{}
