{100}{}{You see Gut.}
{101}{}{You see a thin man in dirty clothes.}
{102}{}{*Crunch-crunch* Tasty. Now we can talk.}
{103}{}{Uh, how did you manage to get down here wearing that? It's fucking big.}

{110}{}{The squatter is too hungry to talk.}
{111}{}{Any food?}
{112}{}{Can you share something to eat?}
{113}{}{Spare any of your supplies? Food?}
{114}{}{Everyone here is one of us. That means everyone shares their catch.}
{115}{}{Newbies should share something. That's the rule.}

#Dialogue
{200}{}{Thanks for the food. We don't often have tourists here. Usually if someone shows up, it's not good. You're not going to cause problems for us, right?}
{201}{}{Depends on what answers I hear from you.}
{202}{}{No, no problem, buddy.}

{210}{}{So what brings you to this sewer, pureskin?}
{1210}{}{So what brings you to this sewer, pureskin?}
{211}{}{Nothing. Bye.}
{212}{}{I think you've had enough. Goodbye.}
{213}{}{Very interesting. Can you tell me anything else?}

{220}{}{Who are you?}
{221}{}{People on the surface call us squatters. We have no home, no work, no friends up top. We live here in the underground.}
{222}{}{Do you have a leader?}
{223}{}{No, everyone is equal here.}
{224}{}{Who are you?}
{225}{}{Among my people, I am Gut. But you can call me Senor Hidalgo. Hee hee. It's a joke. Unclear? Well... Okay, forget it.}
{226}{}{How long have you been living in the underground?}
{227}{}{How long have you been living in the underground, Gut?}
{228}{}{I've been catching rats here since I was little. And in troubled times, my family hid underground from problems. Now I don't want to go back upstairs anymore.}

{230}{}{Why do you live underground?}
{231}{}{It's not bad here, once you get used to it. Up top, people shoot at each other, but here we are all equal. Understand? We help each other, share our catch. That's how we live.}
{232}{}{How do you survive here?}
{233}{}{We catch rats and collect glowing mushrooms. Sometimes we go to the surface to trade them for something we need.}
{234}{}{Ah, so that's where the market's been getting its rats.}
{235}{}{Yep, we're the best at it. Nobody catches rats like us.}
{236}{}{Disgusting, but impressive. Tell me more about the folks down here.}
{237}{}{Alright, I've seen enough. I'm heading out.}

{240}{}{Seen anything interesting down in these sewers?}
{241}{}{Not much. But lately, we've been seeing more strangers, and hearing some weird sounds.}
{242}{}{Weird sounds?}
{243}{}{Yeah, it's usually quiet down here. But sometimes... it's like a bunch of voices whispering into a trumpet. Some folks say it's a ghost, hehe, but I don't buy it.}
{244}{}{What's the story about this ghost?}
{245}{}{They say a family man hid underground during the Great War. But hunger drove him mad. He ate his wife, then his kid. When he finally died, his spirit stayed, wandering these sewers looking for his family. (looks around) Hear that? Sometimes, I think there's something to it.}
{246}{}{That's a sad story. But I've still got more questions for you.}
{247}{}{Ghost stories, really? I don't need to hear any more of that nonsense.}
{248}{}{Do you seriously believe in ghosts?}

{250}{}{Do you know how to get deeper into the sewers?}
{251}{}{No way from here. You'll have to climb to the surface and find another hatch. But trust me, it's better not to go there alone.}
{252}{}{Why? What's down there?}
{253}{}{Hordes of monsters, cave-ins, pits of toxic waste - you name it. Even we squatters don't know all the secrets of the underground. Lately, we're finding more and more corpses of pure-skins. I don't know what they're looking for down here.}
{254}{}{You seem to know these sewers inside out. Anything else you can tell me?}
{255}{}{Okay, I'm heading back to the surface. Right now.}
