{100}{}{You see a wanted poster.}
{101}{}{This poster features a man who looks suspiciously like you.}
{102}{}{You see a poster with your portrait and the inscription: "Wanted for crimes against the Church of the Holy Fire."}
{103}{}{You see a poster with your portrait and the inscription: "Wanted for crimes against the city. Reward 500 caps."}
{104}{}{You see a poster with your portrait and the inscription: "Wanted for crimes against the city. Reward 1000 caps."}
{105}{}{You see a poster with your portrait and the inscription: "Wanted for crimes against the city. Reward 2000 caps."}
{106}{}{The poster was torn down and destroyed.}
