{100}{}{You see Louis.}
{101}{}{You see a resident of Vault 25.}
{102}{}{Whatever you say...}
{103}{}{Do it, I beg you!}
{104}{}{As you wish, s-sir...}
{1104}{}{As you wish, m-madam...}

{200}{}{(You see a man with a toolbox. When he sees you, he hesitantly backs away and, looking at his feet, says: "M-my respect.")}
{201}{}{Wait a minute, who are you?}
{202}{}{M-my name is Louis... if you please. S-sir.}
{203}{}{What are you doing here, Louis?}
{204}{}{I-I'm checking th-pipelines... if you please.}
{205}{}{Maybe stop repeating yourself?}
{206}{}{S-sorry, sir. I'll leave immediately, sir.}
{1206}{}{S-sorry, lady. I'll leave immediately, ma'am.}
{207}{}{Hang on. I want to ask you something.}
{208}{}{Uh, okay.}
{209}{}{I'm asking who you are, not what your name is.}

{210}{}{H-how can I help?}
{211}{}{Nothing yet.}
{212}{}{Enough about that.}

{220}{}{Tell me about yourself.}
{221}{}{(confused) M-my name is Louis... I was born here... And grew up here.}
{222}{}{Is that all?}
{223}{}{S-sorry, sir. I've been setting up equipment here all my life. I have nothing more to tell about myself.}
{1223}{}{S-sorry, lady. I've been setting up equipment here all my life. I have nothing more to tell about myself.}
{224}{}{Have you ever left the vault?}
{225}{}{Sometimes I go up to the cathedral... but I've never been into the city.}
{226}{}{You seem to be attached to this vault.}
{227}{}{I p-pray to our Lord for keeping me alive and giving me a job. Glory to the Lord!}
{228}{}{Hmph. It seems that you're a prisoner here. Still, I have a couple more questions for you.}

{230}{}{Would you like to escape from here?}
{231}{}{No way, sir! Without the vault I'd die. That's what the Lord says, but I know it's true myself.}
{1231}{}{No way, lady! Without the vault I'd die. That's what the Lord says, but I know it's true myself.}
{232}{}{I see this question has really scared you.}
{233}{}{S-sorry, sir! I've been here all my life... I don't know how to act outside. I'm afraid, sir!}
{1233}{}{S-sorry, lady! I've been here all my life... I don't know how to act outside. I'm afraid, lady!}
{234}{}{I see. But will you at least answer some questions?}
{235}{}{What are you doing here?}
{236}{}{I humbly serve the Lord of Phoenix and his Advisor for the good of the Holy Fire. I was tr-entrusted with s-setting up the equipment, this is m-my sacred duty.}
{237}{}{I see.}
{238}{}{You don't really believe all that, do you?}
{239}{}{(Looks down, not knowing what to say; he looks like he's been seriously abused by the Fire Worshippers.)}

{240}{}{Tell me about this vault.}
{241}{}{Vault 25, built by Vault-Tec to protect people from nuclear war and its consequences...}
{242}{}{Wait, how did the Fire Worshippers end up here?}
{243}{}{(hesitantly) They... came from outside and... s-settled here.}
{244}{}{You're not telling me something.}
{245}{}{You can find out the story on the computer network, it's true.}
{246}{}{I'll look into it. In the meantime, tell me more about the vault.}
{247}{}{They don't talk about it here... The cult took over the vault... And they left me to maintain the equipment.}
{248}{}{Sad story. Let's talk about something else.}

{250}{}{You know the vault like the back of your hand, right?}
{251}{}{(smiling wryly) That's right, sir. I know, sir.}
{1251}{}{(smiling wryly) That's right, lady. I know, madam.}
{252}{}{Some of the doors are locked. Do you know how to open them?}
{253}{}{N-need an access card. Everyone has their own clearance level, security has the highest.}
{254}{}{Were there other vaults?}
{255}{}{Yes, lots of them! The scientists in the laboratory know about them.}
{256}{}{Tell me about the days when the vault was free.}
{257}{}{It... was wonderful here. We lived peacefully and amicably. We had enough food and energy. Nobody was going to go outside. Then the strangers came. They used a special signal to open the main vault door and then rushed inside. Only later did the cult of the Holy Fire appear, and the vault became its base.}
{260}{}{Bring me some clean water.}
{261}{}{(leaves and soon returns) Your w-water, sir.}
{1261}{}{(leaves and soon returns) Your w-water, lady.}
{262}{}{Now hop on one leg and get out of here!}
{263}{}{Thank you.}
{264}{}{As you wish...}
{265}{}{Do you always fulfill requests from strangers?}
{266}{}{(looks up in amazement for a moment, but immediately looks back down)}
{267}{}{Do you always fulfill requests from strangers?}
{268}{}{There are no strangers in the vault, only Followers of Fire. And my sacred mission is to be useful to them...}
{269}{}{Did you decide that yourself?}
{270}{}{The Advisor gives me instructions.}
{271}{}{Don't you obey the Lord of Phoenix?}
{272}{}{As long as it doesn't contradict the Advisor's words.}
{273}{}{While your master isn't looking, let's talk about something else.}
{274}{}{I see. Bye.}

{280}{}{Louis, do you really want to live like this?}
{281}{}{I've thought about it... ending it. None of my loved ones or friends are left. I can't leave the vault, even if the doors are open. What can I do? Just... serve the Advisor...}
{282}{}{But that's not what you want deep down, is it?}
{283}{}{Wait, this dialogue is going in the wrong direction. Let's go back.}
{284}{}{Well, it turns out you're a big loser. Have fun.}
{285}{}{I'm worthless... Worthless! These people never cared about me, I'm just a worthless slave to them, and always will be!}
{286}{}{It's high time you ended your suffering. Help me - together we'll destroy the vault.}
{287}{}{I... Please, just let me serve the Lord and th-the Holy Fire!}
{288}{}{Fine. Just stay here then, loser.}
{289}{}{Destroy? Destroy the vault... That's it... How come I didn't think of it before!}
{290}{}{Do you have any idea how it could be done?}
{291}{}{There's a nuclear bomb down here. It's almost finished, the scientists are waiting only for a few minor parts, but it can already be set off and... (stammers and breaks out in a cold sweat)}
{292}{}{Set off? Explode? That's exactly what we need, Louis. Tell me how to do it.}
{293}{}{The professor has parts in his office, without them it's i-impossible to detonate the bomb...}
{294}{}{I'll need an access card to get into his office.}
{295}{}{Yes... This card here has a high level of clearance. I'll pray that everything works out for you...}
{296}{}{Thanks, Louis, you have done not only me a favor, but the entire Wasteland. Now I gotta go.}
{297}{}{It's easy to gain your trust, Louis. And now I'll tell the Advisor about this. Bye, idiot.}
{298}{}{Why does the cult need a nuclear bomb?}
{299}{}{I d-don't know, but once it was fully assembled, it was going to be transported to the southwest, across the desert.}
