{102}{}{You have filled the container with synthetic raw materials.}

{200}{}{Enter command.}
{201}{}{End session.}
{202}{}{Check for synthetic material.}

{210}{}{Synthetic round is empty.}
{211}{}{Synthetic round is }
{212}{}{% full.}
{213}{}{Craft vault jumpsuit (25% material consumption).}
{214}{}{Craft a cassock of the Followers of Fire (50% material consumption).}
{215}{}{Done.}
