{100}{}{You see a stranger.}
{101}{}{You see a young boy in worn-out clothes.}
{102}{}{Good luck. I'm leaving the Aqueduct soon. Gonna try to find a place to live further up the Colorado River.}
{103}{}{What was... in that water...}
{104}{}{Ah-h...}

#Dialogue
{200}{}{Uh, hi?}
{201}{}{I'm new around here. Just getting to know everyone.}
{202}{}{Oh, that's... great. I'm new here too. Haven't had much luck meeting folks.}
{203}{}{Did something happen?}
{204}{}{I came with two friends, but they disappeared, and the locals don't want anything to do with me. Now I'm just sitting by the fire, fishing and thinking about the future.}
{205}{}{That's a sad story. A real bummer.}
{206}{}{The locals' distrust is understandable though.}

{210}{}{What do you want?}
{211}{}{Nothing. For now.}
{212}{}{Hi, any news?}
{213}{}{Sorry, nothing new to tell you.}
{214}{}{Hi.}
{215}{}{Goodbye.}

{220}{}{What about the Rangers? Can't they find your group?}
{221}{}{I talked to Garth, he's kind of like the sheriff here. But it doesn't seem like he's doing anything. And what can he do? I've already asked the locals, no one knows anything.}
{222}{}{Where are you and your group from?}
{223}{}{We fled from a small village far from here when life became unbearable. We heard the Rangers would take anyone under their protection. But it seems like we're not welcome here.}
{224}{}{I'll look for your people, and if I find anything, I'll let you know.}
{225}{}{Thank you. Tell me everything you find out.}
{226}{}{Goodbye. See you around.}

{230}{}{I found your friends... in the tunnels by the aqueduct.}
{231}{}{They're dead, right? God... Now I get why Garth forbids anyone going into that old place. We're probably not the first ones he and his goons have murdered and dumped there. Damn Rangers...}
{232}{}{What are you going to do now?}
{233}{}{I'd like to get revenge on that bastard so this doesn't happen again. But that would just make me more enemies. Either way, I can't stay here.}
{234}{}{How about reporting this to the base? I doubt the command knows about it.}
{235}{}{They won't let me near the commander, I've tried. Can you do it? If we don't stop Garth, he'll keep eliminating anyone he doesn't like.}
{236}{}{I'll try to reach the general. Though it won't be easy.}
{237}{}{You're a good person. Thank you.}
{238}{}{Wait for news, kid.}
{239}{}{Get lost, I'm already in deep trouble because of you.}
{240}{}{Fine, forget it. I'll just leave, and Garth will remain unpunished... Yeah. That would be BETTER.}
{241}{}{Don't play on my feelings! Adios, kid.}
{242}{}{How about we just kill Garth? It'd be simpler and more fun.}
{243}{}{Kill a Ranger and end up on the wanted list? Damn, I don't want to run from Rangers for the rest of my life. Better if I just leave.}
{244}{}{Well, safe travels, kid.}

{250}{}{Ranger Garth got what he deserved. Your friends are avenged.}
{251}{}{Yeah... but that won't bring them back. You know, we were friends more by misfortune. A lot happened on the road. We had to rob travelers and small settlements. Here, we felt part of something and lived a normal life. Despite the locals' distrust. But that Ranger ruined everything.}
{252}{}{Yeah. Too bad it ended like this.}
{253}{}{He had a point about distrusting your gang.}
{254}{}{Thanks for everything. Here, take these bullets. Honestly, I stole them from the Rangers, so it's fair to give them to you as a reward. It's time for me to hit the road. There's no life for me here.}
{255}{}{Safe travels.}
