{100}{}{You see a cadet.}
{101}{}{You see one of the recruits.}

{110}{}{They say combat's easier than this damn training.}  
{111}{}{Captain Agatha? That woman's a beast, not a person.}  
{112}{}{Commander Helford's something else. I really look up to him.}  
{113}{}{Word is, the general's covered in hair - that's why he always wears that duster.}  
{114}{}{Wish we knew what the hell was going on in California.}  
{115}{}{Man, I could go for lunch right about now.}  
{116}{}{How am I supposed to sleep after hearing all those stories about monsters?}  
{117}{}{This training's gotta end eventually... right?}  
{118}{}{Honestly? Not bad here so far.}  
{119}{}{Thinking about joining up, huh?}  

