{100}{}{You see Flick the trader.}
{101}{}{You see Flick the wandering trader.}
{102}{}{No more nuka-cola... honest.}
{103}{}{The merchant lost his harmful goods. Only thing left is to report the success to commander Helford.}

#Start of Dialogue
{200}{}{Hey there, wanderer! Need some gear for yer travels? I can get ya anythin'... Wait, sold all my stuff to them damn Rangers. Shit.}
{201}{}{So you're a trader?}
{202}{}{Name's Flick. I peddle goods in Ranger territory. What'cha need? Maybe I knows where to find it?}
{203}{}{I doubt you have what I need. So long, Flick.}
{210}{}{What'cha need? Maybe I know where to find it?}
{211}{}{So long.}
{212}{}{Let's change the subject.}

#Questions
{220}{}{What exactly do you trade, Flick?}
{221}{}{Whatever I can get - food, clothes, utensils. Now I got nothin' left but caps.}
{222}{}{What's the deal with caps?}
{223}{}{Ya don't know? In the big city to the east, folks started usin' bottle caps as money. Trade 'em for goods. Odd idea, but handy! Problem is, Rangers don't accept caps. Won't trade for 'em.}
{224}{}{Why's that?}
{225}{}{They think currency's a gamble. Ya never know the real worth of caps. Barterin' is fair, no "in-flation". But still, if folks got sacks of caps, maybe Rangers'll change their minds.}
{226}{}{Interesting. I had some more questions, since you don't seem to be in a hurry.}
{227}{}{I'm worried about my family, not currency. So long.}
{230}{}{Where'd you get that brahmin?}
{231}{}{Bought it from herders in a nearby town. Big investment, but paid off quick.}
{232}{}{I see. Enough about brahmin though.}
{233}{}{Alright. Bye.}
{234}{}{I was in San Brahmin. Herders aren't trading those animals anymore.}
{235}{}{What'cha implyin'? Hey, I didn't steal this beast! Can't say where the seller got it, though.}
{236}{}{Uh-huh. Sure. Any other interesting news you wanna share?}
{237}{}{Uhh, I've heard enough. Goodbye.}
{240}{}{Aren't you worried, wandering the desert?}
{241}{}{This is Ranger territory - safest place I know.}
{242}{}{Maybe, but I don't like the way your guard's eyein' me.}
{243}{}{Then I guess you'll answer a few more of my questions.}
{244}{}{Oh, and it just so happens I gotta go. Goodbye, Flick.}
{245}{}{(sighs) This is my son. He's a bit of a... retard, so don't bother him.}
{246}{}{I won't. Instead I'll bother you with a couple of more questions.}
{247}{}{You should've warned me earlier. I think I'll be moving along now...}
{250}{}{You ever been to Quartz?}
{251}{}{Once. Locals were real poor and real unfriendly, lost any desire to trade there right away.}
{252}{}{It's really that bad? I'll keep that in mind.}
{260}{}{I need to meet the Ranger general.}
{261}{}{Well, can't help ya there. But, ya know what? Rangers won't let ya on the dam without a damn good reason. Hahaha... Make some friends among 'em, might help. But why ya need the general?}
{262}{}{No special reason, just wanted to see him.}
{263}{}{Hmmm. Whatever ya say.}
{264}{}{Hmmm. (thinks, assessing prospects) Damn, too far and dangerous... Uhhh, I just can't help ya.}
{265}{}{My people were taken by slavers. I'm hoping the Rangers will help get them back.}
{266}{}{Doubt they would, buddy. But go see the commander in the infocenter. Where's yer settlement at?}
{267}{}{It's... far from here.}
{268}{}{Hmmm. Well, alright.}
{269}{}{To the north. We call it "Villa".}
{270}{}{Hey, I know you. You were here 'fore the dam got washed away by the Colorado.}
{271}{}{That was me. And what are *you* doing here?}
{272}{}{Rangers are in big trouble now, smells like chaos. But ya know what - my goods still sell, even in this mess. Gotta... change my stock a bit.}
{273}{}{Like sell weapons, drugs, and booze?}
{274}{}{Don't talk about this here, someone could hear. 'Til Rangers get control back, big profits in shady business. Ya catch my drift?}
{275}{}{Do what you gotta do.}
{276}{}{That business will end sooner or later. Our talk, however, ends now.}

#Dialogue on the road map
{300}{}{What can I do for ya? Rangers send ya?}
{301}{}{You sound worried. You know you're wanted, right?}
{302}{}{Yeah, I know. But prove that sickness is from irradiated cola! Besides, my goods are *clean*. Got it?}
{303}{}{Everyone says that. How about a rad check with a geiger counter then?}
{304}{}{Hell no, ain't lettin' ya near my goods! Back away from the cart!}
{305}{}{...}
{310}{}{Leave me be. Not givin' up my goods.}
{311}{}{Alright.}
{312}{}{I could take all your irradiated nuka-cola off your hands.}
{313}{}{That'll cost ya a heap of caps. But I'm always up for tradin' trash for treasure. Show me what ya got.}
{314}{}{[Continue]}
{315}{}{Take care.}
{316}{}{Hand over *all* that irradiated cola. No arguments.}
{317}{}{Damned if I will!}
{318}{}{[Attack]}
{319}{}{You should've listened.}
