{100}{}{You see a Ranger.}
{101}{}{You see a typical Ranger.}
{102}{}{This is a makeshift infirmary, not open to outsiders.}

# Floating Lines
{110}{}{Until we wipe out the Jackals, heading north is pretty much a death wish.}
{111}{}{Whoever put an end to those Jackals deserves a cold root beer on the house.}
{112}{}{Can't believe we struck a deal with those Jackals.}
{113}{}{Rumor has it there are lush green fields amidst the barren north.}
{114}{}{Those Villa folks have turned coat and joined the enemy.}
{115}{}{The northerners are charging an arm and a leg for their measly corn cobs.}
{116}{}{San Brahmin's herders won't last without our protection.}
{117}{}{Those herders will regret turning their backs on our alliance.}
{118}{}{The threat of Phoenix nearly took San Brahmin, but we held our ground.}
{119}{}{Flagstaff will pay the price for dabbling in slavery one day.}
{120}{}{As long as Flagstaff ditches slavery, I couldn't care less about what they do.}
{121}{}{Flagstaff's expansion spells trouble.}
{122}{}{We need to stamp out those fire worshippers before they incinerate everything.}
{123}{}{The fire cult, burnt out by their own flames.}
{124}{}{The cursed cultists keep seizing more territory.}
{125}{}{What's this mysterious "southern threat" everyone's whispering about?}
{126}{}{The Brotherhood of Steel got what was coming to them. Meddling in other people's affairs never ends well.}
{127}{}{But can we really stand up to the Brotherhood of Steel?}
{128}{}{Parker Dam was a marvel of the Old World's ingenuity.}
{129}{}{Finding a new base to replace this one won't be easy.}
{130}{}{Old Rufus tinkered with the power plant again.}
{131}{}{That farmer's got some real potential.}
{132}{}{Are all the folks in Villa as impressive as this one?}
{133}{}{I should keep an eye on that farmer.}
{134}{}{I should get better acquainted with that farmer.}
{135}{}{That farmer seems suspicious.}
{136}{}{I'm not fond of that farmer.}
{137}{}{One day, we'll change the Wasteland for the better.}
{138}{}{Word is, someone took out the ferryman.}
{139}{}{Someone's been digging up our fellow rangers' graves, and it ain't your typical Wasteland mutant.}
{140}{}{Peace and quiet reigns in Aqueduct.}
{141}{}{Who would've thought Garth was behind those disappearances all along?}
{142}{}{William Garth's a real piece of work, ain't he?}

#Response
{150}{}{Rangers fight for their cause to the bitter end.}
{151}{}{Our aim is true, our bullets find their mark.}
{152}{}{One day, we'll reshape the Wasteland.}
{153}{}{A working vehicle would make life a lot easier...}
{154}{}{Those bloodthirsty Jackals should've been dealt with ages ago.}
{155}{}{The menace of Phoenix looms larger in the east.}
{156}{}{Exercise caution out in the wastes.}
{157}{}{You're safe here under our watch.}
{158}{}{I'm not at liberty to discuss that.}
{159}{}{You've got the makings of a fine Ranger.}
{160}{}{The most dangerous creatures of the desert come out at night.}
{161}{}{Wishing you good fortune.}

{170}{}{Looking for trouble, stranger?}
{171}{}{Our shots never miss, remember that.}
{172}{}{You're just in time - we could use some live targets at our shooting range.}
{173}{}{You've picked a rather risky place for a stroll.}
{174}{}{What do you want?}
{175}{}{Hmm, you're giving off a suspicious vibe.}
{176}{}{I can't discuss that with you.}
{177}{}{You're on your own out here.}
{178}{}{Together, we'll reshape the Wasteland.}
{179}{}{Got a problem?}

{180}{}{Welcome, fellow Ranger.}
{181}{}{Sorry, but I can't escort you to the base.}
{182}{}{Your efforts are making a difference in the Wasteland.}
{183}{}{We're grateful to have you fighting alongside us.}
{184}{}{Drop by the base when you can.}
{185}{}{Stay vigilant, Ranger.}
{186}{}{Looking forward to hearing your report on the new territories.}
{187}{}{A working vehicle would be a game-changer...}
{188}{}{One day, we'll transform the Wasteland.}
{189}{}{Don't let the traders pull one over on you.}
