{100}{}{You see Ranger Stark.}
{101}{}{You see Private Stark.}
{102}{}{Thanks, Doc. I thought I would remain lame for the rest of my life.}

#First dialogue
{200}{}{(a bored Ranger seems to come to life when a stranger appears in the mess hall; he warmly invites you to a table) Hello, stranger! Haven't seen you before. Where are you from?}
{1200}{}{(a bored Ranger seems to come to life when a stranger appears in the mess hall; he warmly invites you to the table) Hello, stranger! Haven't seen you before. Where are you from?}
{201}{}{From the village to the north. We call it Villa.}
{202}{}{Well, I was patrolling in other directions. But I heard something about Villa. Was it you guys who grow crops in the middle of a barren desert? Marvelous. I thought it was just the usual bullshit you hear in the mess hall.}
{203}{}{And you are...}
{204}{}{None of your business.}
{205}{}{Hey, I thought I wasn't being rude to you? But I understand your mistrust. If you don't want to, don't tell me.}
{206}{}{Who are you?}
{207}{}{I'm Stark, Ranger Private, if that tells you anything.}
{208}{}{Hello, Stark. Do you have a minute to talk?}
{209}{}{Hello, Stark. And bye.}

#Re-dialogue
{210}{}{You've got all my attention.}
{211}{}{Bye.}
{212}{}{I have another question.}

#Questions
{220}{}{Why do you live right on the dam?}
{221}{}{What? This place is perfect - keeps out enemies and bad weather. No one would even think of storming it or spying on us.}  
{222}{}{Is this place really safe?}
{223}{}{This dam will be here for another couple of centuries. At least that's what Old Man Rufus says. And what could happen here? It's just a piece of concrete in the middle of the mountains.}
{224}{}{Who is Old Man Rufus?}
{225}{}{Dam Keeper. He's been in that position for more than a dozen years. Although many think that he's getting his rations in vain. You can always find him at the power plant.}
{226}{}{So this is where all the Arizona Rangers live?}
{227}{}{Of course not. This is just a temporary barracks. You can only get a bed here for a limited time or under special circumstances. The rest of the time? Find yourself a spot in the sun, like any proper Ranger would.}  

{230}{}{I was just wondering how to become a cadet?}
{231}{}{There are a few ways. Usually, we need a recommendation from someone we trust - like traders, leaders from friendly settlements, or other Rangers. If you don't have that, you'll have to prove yourself through action.}  
{232}{}{How long does the training last?}
{233}{}{At least five years, but it really depends on the cadet. Promotions have to be earned through real work in the field.}  
{234}{}{Are you a cadet too?}
{235}{}{Me? No, no. But I have to help the greenery grow. It's our custom: if you can't be useful in the field, help at the base.}
{236}{}{What's stopping you from joining in operations?}
{237}{}{That bad leg kind of holds you back, out in the field, huh?}
{238}{}{(pats his bandaged leg) Damn wolves. They attacked me while on patrol along the Colorado River. I lost my vigilance - and this is the price I paid.}
{239}{}{Maybe I could patch it up?}
{240}{}{If you pay, I could patch you up.}
{241}{}{Ooh, that's a real bummer. Maybe we can talk about something more positive?}
{242}{}{Seriously? I'd appreciate it. But do you really know what to do?}
{243}{}{Let me take a look...}
{244}{}{Use medical skills or medicine to treat the injury.}

{250}{}{Such an experienced Ranger must have a lot of interesting stories to tell.}
{251}{}{I never miss an opportunity to ask travelers about what they've seen. True, most of them embellish their stories a bit.}

{270}{}{You mentioned wolves. What other critters are found along the Colorado?}
{271}{}{Well, unlike the desert, it's full of all kinds of life.}
{272}{}{For example?}
{273}{}{Yeah, I notice that.}
{274}{}{Horned lizards the size of dogs roam the underbrush. They might not seem like tough opponents at first, but their spiked bodies make close combat tricky. On top of that, they're smart as hell and masters of camouflage.}  
{275}{}{Interesting... Tell me more.}
{276}{}{Creatures like that everywhere, nothing special.}
{277}{}{You want something scarier? The caves are home to bulldog bats - real devils. They wait for you at the entrance and quickly fly out, not giving you a chance to get your bearings. Just one of those creatures can lift a man into the air and drag him back to the cave. That'll be it for you.}
{278}{}{Seriously? That kind of freaks me out.}
{279}{}{It's kind of hard to believe. And are these all local creatures?}
{280}{}{Centipedes up to two yards long can be found among the rocks along the Colorado. They spit poison that causes death within seconds. Their shells cannot be pierced even with a knife, and their jaws are so strong that they can cut a person in half.}
{281}{}{Mother of...! Do things like this really exist?}
{282}{}{Sounds like someone is stretching things a bit. Don't you think?}
{283}{}{There are also rumors about stinging hypnotic butterflies and armadillos that use old cars as shells. But for myself, I've only met wolves, lizards and rodents of all kinds.}
{284}{}{Thanks for the story. It was very... educational.}
{285}{}{Stay alert.}
{286}{}{Let's chat some more.}
{287}{}{Then see you later, I gotta go.}
{288}{}{Your yarns gives me a headache. Are you trying to scare everyone who listesn to you?}
{289}{}{Well... I heard all this from other people. Don't blame me. But also, don't doubt that there's a lot of hostile creatures around. Stay vigilant.}
{290}{}{Tell about the creatures of the Colorado River.}

#Promotion Party
{310}{}{Hey, it's a new *star* in person!}
{311}{}{Yeah, it wasn't easy to get the badge. But how did you know?}
{312}{}{Rumours spread fast around the base. But you know what? Don't expect a gift from me. The rest spend years earning their star, and you just come and take it!}
{313}{}{You didn't like me from the moment we met. But I don't really care.}  
{314}{}{I hope you change your mind about me someday.}
{315}{}{Yeah, yeah.}
{316}{}{Are you busy? You have a minute?}
{317}{}{I think I'll head out.}
{318}{}{Enjoy. For today you're a hero.}
{1318}{}{Enjoy yourself. Today you're a star.}

{320}{}{Are you making fun of me?}
{321}{}{How'd you figure that out? Maybe it's 'cause no one's throwing a parade for you. The rest of us bust our backs for years to earn our rank, and you just stroll in and take it. So don't expect any pats on the back from me.}  
{322}{}{Word travels fast around the base. I'm happy for you. Not many folks rise through the ranks that quickly - actually, none do. In honor of the occasion, let me hook you up with something from my personal stash. Well done!}  
{323}{}{Thanks, a party on top of the dam is exactly what I've always wanted.}
{324}{}{A badge isn't much to celebrate, but I'll take the fruits.}

{330}{}{Listen, is there any truth to your stories?}
{331}{}{Well... there is one story that definitely cannot be called fiction. Interested?}
{332}{}{I'm listening.}
{333}{}{Another time.}
{334}{}{Out in the desert lives a massive radscorpion - bigger than any we've ever seen. Rumor has it, this beast's already taken down several groups of travelers. If you find it and take it out, you'd be doing everyone a real favor.}  
{335}{}{You know, I don't want to listen to this.}
{336}{}{Aren't all radscorpions giant?}
{337}{}{Yes, but this one will outshine all the rest with its size!}
{338}{}{Why don't the Rangers track it down and take it out?}
{339}{}{This beast prowls the wasteland, where even seasoned Rangers struggle to survive. It crawls out to hunt, then vanishes back into the wastes. To cross paths with it, you'll have to become its prey - one way or another.}  
{340}{}{But why do you think all this is true and not fiction?}
{341}{}{Because I saw it with my own eyes - I'm not the only one, either. We tracked it once, out in the desert between Quartz and San Brahmin. It tore through a bunch of us, and we barely made it out alive. After that, we figured it's best to steer clear of that scorpion.}  
{342}{}{Okay, I'll try to track down and kill this thing.}
{343}{}{Seriously? Commendable zeal. But if you become a monster's lunch, then blame yourself.}
{344}{}{No problem. I'll bring you a souvenir.}
{345}{}{Whoa, sounds like it's best to steer clear of this monster. Thanks for the warning.}
{346}{}{That's it.}
{347}{}{Thanks.}

{350}{}{I want to ask you again about that legendary radscorpion.}
{351}{}{Ah, you don't really want to head out into the wasteland after such a story, do you?}
{352}{}{Let's change the subject.}
{353}{}{I killed the scorpion.}
{1353}{}{I killed the scorpion.}
{354}{}{Really?! But of course, you have no proof, right?}
{355}{}{The corpse is easy to spot out in the desert. Send a patrol - they'll confirm it.}  
{356}{}{Hmm, that can be arranged. If it's true, then on behalf of all the Rangers, thank you. You've done a great service to the entire Wasteland.}  
{1356}{}{Hmm, that can be arranged. If it's true, then on behalf of all the Rangers, thank you. You've done a great service to the entire Wasteland.}  
{357}{}{I thought services like that deserved a... reward.}  
{358}{}{I thought claims like that needed proof. Isn't that right?}  
{359}{}{Yeah... damn. It's too late to dig up evidence. A mention in your stories will have to do then.}  
{360}{}{That's enough for me.}  
{361}{}{All I've got to show is this stump of a spear - it was stuck in the shell.}  
{362}{}{Damn! I remember that spear... So you *really* took down the beast? But how?}  
{363}{}{He was big, but slow as hell.}  
{364}{}{People like you are a rare breed. Here, take these bullets and this old revolver as a token of thanks. Don't be modest - I've got enough firepower to keep mutants at bay. Thanks again.}  
{365}{}{You're welcome.}  

