{100}{}{You see a child.}
{101}{}{You see the youngest member of the Milton family.}

#Dialogue
{110}{}{Hey there. Have you come to help us get rid of the pests?}
{111}{}{Please, save my parents!}
{112}{}{Rangers are awesome. When I grow up, I want to join you guys.}
{113}{}{This is all your fault! Get out of here!}
{114}{}{This is all your fault! Get out of here!}
{115}{}{Go away!}
{116}{}{Thank you for saving us from that monster.}

{200}{}{Wait! There's... there's a... a bandit!}
{201}{}{Where?}
{202}{}{Calm down, I can't understand you when you're speaking so fast.}
{203}{}{There's a bandit in our home! He's got a gun and he's tied up my mom and dad! Please, you have to save them!}
{204}{}{Stay here. We'll go investigate.}
{205}{}{Move aside, kid. Let the professionals deal with this.}
{206}{}{Nah, kid. It was probably just a big pig rat...}
