{100}{}{You see the Rangers' computer.}
{101}{}{You see a terminal with access to a shared server.}

#Dialogue
{200}{}{Enter command:}
{201}{}{End session}
{202}{}{Back}
{203}{}{Connect to the server.}
{204}{}{Access to the central server has been secured.}
{205}{}{Excellent.}

{210}{}{Ranger Dossier.}
{211}{}{Select a directory.}

{212}{}{Jackals}
{213}{}{The Jackals are a tribe of cannibalistic raiders in the Mojave Wasteland. Little is known about their history and daily life as they are extremely hostile to outsiders.}
{214}{}{[More]}
{215}{}{There are over a dozen clans, each with their own territory and rules. All practice cannibalism.}
{216}{}{Current threat}
{217}{}{The largest Jackal clan is dwindling, while the others pose minor or dormant threats.}
{218}{}{A truce exists between the Rangers and the Jackals. All Rangers are instructed to avoid conflict with this tribe unless absolutely necessary.}
{219}{}{The Jackals are a major threat to travelers between the north and south. They are skilled and cunning manhunters, dangerous even to a trained Ranger. The Council of Elders has decreed that the tribe must be eliminated.}

{230}{}{Villa}
{231}{}{A secluded agrarian community practicing subsistence farming. They avoid contact with outsiders and remain neutral in external affairs.}
{232}{}{Current threat}
{233}{}{The Villa peasants have sided with the enemy, but they are hardly a threat on their own. Conflicts with this settlement should be avoided, but any friendly relations with the Brotherhood of Steel must be suppressed.}
{234}{}{A mutual aid pact exists between the Villa villagers and the Rangers.}
{235}{}{The Villa villagers have great potential for the Rangers, but they have categorically refused the pact. We should work on establishing friendly relations with this settlement.}
{236}{}{Sabotage at Villa}
{237}{}{The Villa villagers have declined our cooperation, but they pose little threat by themselves. We should avoid conflicts with this settlement and work to disrupt any alliances they might form with our enemies.}

{250}{}{The Red Menace}
{251}{}{The Followers of Fire are a cult that worships nuclear power and Old World technology.}
{252}{}{Current threat}
{253}{}{The cult is in decline and under persecution. Their main base was presumably destroyed by an underground nuclear explosion. Details are scarce. Currently, only individual factions pose a danger, preying on previously friendly settlements or engaging in open banditry.}
{254}{}{The cult is rapidly expanding its influence throughout the region, including Southern Arizona and the entire Sonoran Desert. The Council of Elders has marked them as a top priority threat.}
{255}{}{Operations against the Red Menace}
{256}{}{Sabotage in Flagstaff (suspended), support for the San Brahmin fight, aid to runaway slaves in Two-Sun.}
{257}{}{Sabotage in Flagstaff}
{258}{}{The colony uses slave labor and is backed by the Church of the Holy Fire. All sabotage operations in Flagstaff are temporarily suspended.}
{259}{}{Support the fight in San Brahmin}
{260}{}{A faction of fire worshippers is stirring revolutionary sentiments in San Brahmin to expand their influence. We are forced to intervene. Advisors have been sent to San Brahmin to counter the empire's ambitions.}
{261}{}{Reconnaissance in Phoenix}
{262}{}{Several Rangers are operating covertly in Phoenix for intel gathering. Their current priority is to make contact with a guerrilla group opposing the Fire Cult.}
{263}{}{Support for runaway slaves in Two-Sun}
{264}{}{The activities of techno-worshippers in Two-Sun pose a significant threat to surrounding settlements. Fire worshippers in Phoenix collaborate with them to obtain goods and services. Due to the region's remoteness, control is difficult, so spies have been dispatched to assist fugitive slaves in sabotage activities. }

{290}{}{Threat from the south}
{291}{}{Scouts report the destruction of the main Brotherhood of Steel fort in the south. This day will be remembered in Arizona's history as a day of freedom and independence!}
{292}{}{The Brotherhood of Steel is a closed, militaristic faction with imperial ambitions. They practice slavery, coercing settlements into compliance, conducting military invasions, and committing other crimes. Currently, they control a significant portion of Southern Arizona's settlements, including Phoenix, through puppet leaders. It is our duty to halt their expansion.}
{293}{}{Scouts report a mysterious organization in the south. Assessment is impossible due to a lack of information.}
