{110}{}{This equipment is malfunctioning.}
{111}{}{You have managed to disable the radio transmitter. The Rangers are now without radio communications.}

#Dialogue
{200}{}{Enter command:}
{201}{}{End session}
{202}{}{Back}
{203}{}{The radio transmitter is not responding.}

{210}{}{I'll just copy the Ranger frequencies and code... This way I can eavesdrop on their radio conversations.}
{211}{}{Radio frequencies copied.}
