{110}{}{Launch cancellation is not possible.}
{111}{}{It might have made sense earlier, but not now that I'm with the Brotherhood.}

#Dialogue
{200}{}{Enter command:}
{201}{}{End session}
{202}{}{Back}
{203}{}{Cancel}
{204}{}{Accept}
{205}{}{Accept specified parameters}
{206}{}{Next}

{210}{}{Set torpedo parameters.}
{211}{}{Specify parameters.}
{212}{}{Cancel all entries.}
{213}{}{Stop entering data and end session.}
{214}{}{Restore to original settings.}

{220}{}{Viewing angle TARGET-US.}
{221}{}{Viewing angle WE ARE THE TARGET.}
{222}{}{Current angle: }
{223}{}{ degrees.}
{224}{}{+10 degrees.}
{225}{}{+1 degree.}
{226}{}{-1 degree.}
{227}{}{-10 degrees.}
{228}{}{Adjust viewing angle.}

{230}{}{Distance to target.}
{231}{}{Estimated distance: }
{232}{}{ yards.}
{233}{}{+100 yards.}
{234}{}{+10 yards.}
{235}{}{+1 yard.}
{236}{}{-1 yard.}
{237}{}{-10 yards.}
{238}{}{-100 yards.}

{240}{}{Valley mode.}
{241}{}{Current mode: }
{242}{}{ Scatter angle: }
{243}{}{One torpedo.}
{244}{}{Two torpedoes.}
{245}{}{All torpedoes.}
{246}{}{}
{247}{}{Spread angle: }
{248}{}{0.5 degrees.}
{249}{}{1 degree.}
{250}{}{1.5 degrees.}
{251}{}{2 degrees.}

{260}{}{Torpedo speed.}
{261}{}{Current speed: }
{262}{}{ knots.}
{263}{}{+5 knots.}
{264}{}{-5 knots.}

{270}{}{Depth of explosion.}
{271}{}{Explosion depth: }
{272}{}{ yards.}
{273}{}{+1 yard.}
{274}{}{-1 yard.}

{280}{}{Fuse type.}
{281}{}{Fuse type: }
{282}{}{undefined.}
{283}{}{Contact.}
{284}{}{Magnetic.}
{285}{}{Timer.}

{290}{}{Set timer to activate torpedoes.}
{291}{}{Time until explosion: }
{292}{}{ seconds.}
{293}{}{+10 seconds.}
{294}{}{-10 seconds.}

{300}{}{Launch torpedoes.}
{301}{}{Warning! Gate opening mechanism is not responding.}
{302}{}{Perfect, they won't float away. Activate torpedoes.}
{303}{}{Oh, no, no, not that. Cancel, cancel!}
{304}{}{Torpedoes primed. Launch in... }
{305}{}{ seconds.}
{306}{}{Time to abandon ship...}
{307}{}{Press buttons randomly.}
{308}{}{Uh-oh, looks like a countdown has started...}
