{110}{}{These are nuclear torpedoes.}
{111}{}{This must be one hell of a powerful weapon.}
{112}{}{These nuclear torpedoes are armed and ready. }
{113}{}{Time to get out of here...}
{114}{}{It made sense to do this earlier. But not now that I'm on the Brotherhood's side.}

{120}{}{It's a nuclear torpedo. The torpedo bay control panel should be nearby.}
{121}{}{There's nothing to fix here.}
{122}{}{This device is too complicated. There may be other ways to activate the torpedo.}
{123}{}{You have successfully activated the torpedo timer.}
{124}{}{You have successfully deactivated the torpedo timer.}
{125}{}{The timer cannot be deactivated.}

{150}{}{There are }
{151}{}{ seconds left until the explosion}
