{100}{}{You see Master Hard.}
{101}{}{You see the leader of the Tinsmiths. It appears more iron than flesh.}
{102}{}{Return to your virtual existence.}

# First Dialogue
{200}{}{(You see something part machine, part man; its voice grinds like metal on stone) A wanderer from the desert. You are not in my database. Identify yourself.}
{201}{}{Just a drifter from the wastes, searching for my kin from Villa.}
{202}{}{Villa... That name is in my data. A few slaves originated from there. But who are you to come here asking questions?}
{203}{}{Well, I'm no one, really.}
{204}{}{Direct and bold. These traits are recognized. Therefore, you, a mere wasteland entity, will be given a chance to prove your utility... as a volunteer.}
{205}{}{I'm with the Followers of the Holy Fire.}
{206}{}{Some units originated from that cult. But here, under the Two Suns, the protocols differ. You may remain in our city, but do not distract my units from their critical functions.}
{207}{}{I'm a representative of the Brotherhood of Steel.}
{208}{}{The Brotherhood of Steel. They provided us with energy and knowledge of lost technologies. How may we assist a fellow bearer of the metal?}
{209}{}{Actually, I'm here to locate my relatives. Are they here?}
{210}{}{(processing data) Peasants from Villa... Your request is too late. Your kin have already been assigned to the Forbidden Zone, excavating ancient tech.}
{211}{}{I need to ask you some questions.}
{212}{}{I'm on a mission for the Church of the Holy Fire to Puerto Penasco.}
{213}{}{You're a lunatic. You need to be stopped before you drag everyone in the wasteland into slavery.}
{214}{}{You are unaware of whom you challenge, fool. Submit, or be assimilated...}
{1214}{}{You do not comprehend who you are addressing, wasteland simpleton. Submit, or be assimilated...}
{215}{}{No chance!}
{216}{}{What are you on about? I'm leaving. Try to stop me, you iron freak.}
{217}{}{I'll be the one asking questions. You sit and answer.}

# Re-Dialogue
{220}{}{Speak.}
{221}{}{Later.}

# Questions
{230}{}{Speak.}
{231}{}{That's it. I'm outta here.}
{232}{}{One more question.}

{233}{}{What's a former Brotherhood scout doing here?}
{234}{}{The Gods of Steel have fallen. Their Olympus, a casualty of nuclear fire. But some survived. Though stripped of former glory, they retain knowledge beyond mortal reach. We offer them shelter, on our terms.}
{235}{}{In other words, you intend to extract all useful data from them and exploit them as you see fit?}
{236}{}{We are the warriors of the Old World, tasked with restoring its lost glory through technology. We will not be hindered by others' failures.}
{237}{}{Got it. Can I ask something else?}
{238}{}{Well, a difficult path lies ahead for that guy. He's now a mere mortal amidst his 'betters'.}

{240}{}{How can I save my people?}
{241}{}{Your only option is to enter the Forbidden Zone and rescue the slaves. To exit, you must deactivate the internal security systems. It's a rigorous trial, even for the Tinsmiths. Survival probabilities are low. Consult the instructor when ready.}
{242}{}{Why is the Forbidden Zone so crucial to you?}
{243}{}{It is where the ancients stored their military relics. Over time, it has become a repository of tech and knowledge. Access to its core could resurrect ancient technologies and spread the glory of Progress across the Wasteland!}
{244}{}{Do you even know what to do with all this tech once you have it?}
{245}{}{The Brotherhood of Steel will guide its use for the greater good. We, as custodians of Progress, are bound to assist the Brotherhood.}
{246}{}{What Brotherhood?}
{247}{}{You are uninformed? No surprise. You should not know, but I will inform you. The Brotherhood of Steel is a remnant of an ancient military order. They sought to revive the Old World. A noble endeavor, one the Tinsmiths support by any means necessary. We strive to restore the light of the Two Suns to the world.}
{248}{}{Two Suns? I've only ever heard of one.}
{249}{}{Indeed, poor flesh-bound creature. You are familiar only with the sun that warms the earth. But you do not know the brilliance of Nuclear Energy, which shines far brighter.}
{250}{}{So, where is this Brotherhood of Steel?}
{251}{}{You do not merit an answer, stranger.}
{1251}{}{You do not merit such knowledge, outsider.}
{252}{}{You are calculated to merit an answer. Head west past Casa Nueva. On the Sea of Cortez's shore, you will find the Steel Port - the Brotherhood's citadel.}
{253}{}{Who are you?}
{254}{}{Outsiders refer to us as Tinsmiths, due to our devotion to ancient tech. We dedicate ourselves to it, sacrificing even our humanity. For technology will save the world and prevent it from descending into barbarism. Humanity will persist as long as the Two Suns shine, or it will regress beyond redemption.}
{255}{}{Are you allied with the Followers of Fire?}
{256}{}{A church established to propagate Progress, in terms comprehensible to laypeople. We respect and cooperate with these amusing robed figures, as their faith draws people closer to our ideals. However, they remain a level below us.}
{257}{}{So, is this where Flagstaff's uranium comes to?}
{258}{}{Energy requires fuel, and we require ample supply. If not for the greed of primitive tribes from Phoenix and beyond, we would consume all of Flagstaff's uranium.}
{259}{}{What will you do now that the uranium mine are depleted?}
{260}{}{As always, we will seek out pre-war remnants. We rely on the Forbidden Zone, a vast repository of resources and secrets.}
{261}{}{Is it right to send people to their deaths?}
{262}{}{In the wasteland, survival is existence. Let these primitives endure in the Forbidden Zone, aiding Progress and the world. Each life is merely a cog in the grand machine.}
{263}{}{What if the slaves disable the defenses?}
{264}{}{Anyone who retrieves a valuable artifact or disables the defenses will be granted freedom and honors. We Tinsmiths keep our word.}
{265}{}{Did you know the Brotherhood of Steel no longer exists?}
{266}{}{Some relays of Progress are missing. Others will replace them. The Steel Port was not the primary hub of this great network. The headquarters in California remains operational. Arizona will feel the weight of the Brotherhood again.}
{267}{}{Now that the Cathedral of Fire is destroyed, do you trust that cult less?}
{268}{}{The church's faith is irrelevant. What matters is that they helped propagate the word of Progress. We will capitalize on this and continue to advance our ideals, assuming control in Phoenix.}

{270}{}{You've lost your humanity, turned into a soulless machine. Time to unplug you, you damn abomination.}
{271}{}{All I know is that this energy destroyed the Old World. Are you planning the same fate?}
{272}{}{Our ancestors' failure was in their lack of control. We have evolved beyond their weakness. The Old World died so we could rise. Technology is the key to restoring order.}
{273}{}{People like you shouldn't be trusted with a wrench. I'll destroy you before you destroy the world.}
{274}{}{I need time to mull over your words. See you... maybe.}
{275}{}{Intriguing. I'd like to know more about your views and goals.}
{276}{}{You know, you're right. A few past mistakes shouldn't limit our progress.}
{277}{}{Glad to see your organic processor can handle that.}
{278}{}{Yeah, sure. But I've got a few more questions.}

{300}{}{The Forbidden Zone is now under your control, Master Hard.}
{301}{}{ZAX has been neutralized. Its artifacts will return to the Collective, the true heirs of the Old World. The dawn of a new age is upon us.}
{302}{}{Let's say you're right. But what about my people?}
{303}{}{I demand my people's release from slavery.}
{304}{}{You and your people have earned your release. Depart, but remember this: you are all components in a larger mechanism. The Brotherhood of Steel will come. Will you embrace Progress, or be left in the wasteland's ashes?}
{305}{}{I'll consider your proposal. For now, I need to go.}
{306}{}{What does the Brotherhood of Steel have to do with this?}
{307}{}{We serve the gods of metal. They oversee our territory for Progress, optimizing our resources and technology for the Wasteland's resurgence. Villa's servitude was essential for this grand design. You are fortunate to witness this shift in history.}
{308}{}{Your point... has some merit.}
{309}{}{Spare that talk for the other Tinsmiths. I'm not buying it.}

# Cody
{350}{}{They say you kidnapped Cody from Casa Grande. Is that true?}
{351}{}{Typical wasteland ignorance.}
{352}{}{Then tell me your "official" version.}
{353}{}{Demanding answers... (metallic chuckle) I will indulge you. We did not kidnap Cody; we acquired him from his failing biological units. They were incapable of sustaining themselves.}
{354}{}{Was it that bad in Casa Grande?}
{355}{}{The settlement faced systemic failure - water pump malfunction. We were their only viable option for repair. In return, they offered their minimal assets, including Cody, who now contributes to our Collective.}
{356}{}{Why do you need children?}
{357}{}{Our advanced society faces biological reproduction inefficiencies. Integrating and reprogramming youth secures our future. Cody now has a purpose beyond mere survival.}
{358}{}{You don't think his true story will remain a secret, do you?}
{359}{}{Sentimentality is illogical. Cody is now assimilated into the Collective, detached from his past.}
{360}{}{Yeah, sure. I think we're done here.}
{361}{}{You're wrong. He deserves to choose his own fate. I'll make sure he does.}

{368}{}{This is compelling. We agree to the contract. Inform your leader that we'll send an ambassador to negotiate.}
{369}{}{Permission to leave, Master Hard.}
{370}{}{I'm here on behalf of the Blue Shields. We have a proposal.}
{371}{}{What can mere highwaymen offer the Tinsmiths?}
{372}{}{Fuel. Lots of it. In exchange, they want recognition of their independence and official trade status.}
{373}{}{Fuel would mitigate the uranium deficit. However, the Blue Shields are volatile. We cannot risk unstable alliances.}
{374}{}{Ben won't be pleased, but it's your decision. I'll convey your rejection.}
{375}{}{Is there any way I can change your mind?}
{376}{}{Prove your reliability. Then, we can discuss terms.}
{377}{}{Ok, I'll think of something.}
{378}{}{My reputation with your people is solid.}
{379}{}{My contributions to developing the Forbidden Zone prove our reliability.}

# Quests
{390}{}{You probably need someone for special assignments.}
{391}{}{We are... interested.}
{392}{}{What's the task?}
{393}{}{One of our caravans was attacked. We could not identify the assailants. Your job is to investigate. Consult the gatekeeper for the attack route.}
{394}{}{So, we need to walk a few miles? Sounds easy enough.}
{395}{}{I was expecting more, but this'll do.}
{1395}{}{I was expecting more, but this'll do.}
{396}{}{Report your findings before acting. You are dismissed.}
{397}{}{On my way.}

{400}{}{I've found out who's behind the attack on the caravan -- they're runaway slaves hiding in the Old City.}
{1400}{}{I've found out who's behind the attack on the caravan -- they're runaway slaves hiding in the Old City.}
{401}{}{Good work. You have confirmed our calculations. These slaves have caused disturbances before, but now they are escalating their defiance of Two-Sun.}
{402}{}{What's the plan now?}
{403}{}{These slaves ambush caravans and travelers. Eliminate them in Two-Sun and recover the stolen technology.}
{404}{}{Why can't your people handle this?}
{405}{}{These slaves have adapted guerrilla warfare techniques in the Forbidden Zone. They're elusive in the ruins, and their traps are lethal. We specialize in technology, not warfare.}
{406}{}{How can I face a whole host of enemies?}
{407}{}{Apply strategy where technology is insufficient.}
{408}{}{What's in it for me?}
{409}{}{We offer more than material rewards. Join us, and become part of Progress in the New World. Or remain in the wasteland's decay.}
{410}{}{Night vision goggles would help me in the ruins.}
{411}{}{(You receive the goggles) Use this technology strategically.}
{412}{}{This tech isn't for outsiders.}
{413}{}{No more tech for you. Use what you have acquired.}
{414}{}{I'll take care of it.}
{415}{}{Not interested. I've got more pressing matters.}
{416}{}{We need to discuss the runaway slaves.}

{420}{}{The runaway slaves are no longer a threat to you.}
{421}{}{Excellent. You've got a steel resolve we value. Now, give me a full report.}
{422}{}{Here's what happened...}
{423}{}{...We're satisfied with the results. The quartermaster will issue your reward. Wait, there's one more task for you.}
{424}{}{What is it?}
{425}{}{Completing this quest has increased your reputation with the Tinsmiths.}
{426}{}{One of our delegates went to Casa Grande and hasn't returned. We've had no communication from him. Find our brother and discover what happened.}
{427}{}{My boots won't survive another trip. Hope it's worth it.}
{428}{}{I'm on my way.}
{429}{}{...Your report is satisfactory. The quartermaster will handle your reward. Wait, there's one more task for you.}

{430}{}{I found the Tinsmith in Casa Grande. He's dead. Here's his neurochip as proof.}
{431}{}{What was the cause of death?}
{432}{}{He was killed by a Ranger spy.}
{433}{}{A Ranger... We didn't expect them to be such a problem.}
{434}{}{What do you mean by "such a problem"?}
{435}{}{After your mission, we found evidence in the runaway slaves' lair in the Old City that they were supplied and trained by Rangers. They aim to undermine our reputation and economy. In other settlements, they spread false rumors about us. Clearly, the Rangers have become a significant threat.}
{436}{}{So, what's the next move?}
{437}{}{We'll prepare for battle. With the Brotherhood of Steel out of the picture, we must fend for ourselves. You can go home. Villa is now recognized as a neutral settlement by us.}
{438}{}{Great, they really were waiting for me. Adios, amigo.}
{439}{}{Go to Steel Port and inform the Brotherhood of Steel about our conflict with the Rangers. If they need help, you can count on our recommendation. If this world has a future, it's with the Brotherhood of Steel. The Great Reflash is coming.}
{440}{}{The Brotherhood of Steel? Sounds good. I'm on it.}
{441}{}{Thanks for your trust, Master Hard. I won't let the ideals of Progress down.}
{442}{}{I get it, but how do I find a Tinsmith in a foreign city?}
{443}{}{Use the radio. Tune it to the frequency of the subcutaneous chip the delegate had to speed up the search.}
