{100}{}{You see a Tinsmith.}
{101}{}{You see an ordinary resident of Two-Sun.}

# Floating lines
{110}{}{The Gods of Steel are angry at our slowness.}
{111}{}{Why are the Gods of Steel silent? Have they forgotten us?}
{112}{}{The Gods are pleased.}

{113}{}{Casa Nueva may be running low on food supplies.}
{114}{}{They promised to send more food to Casa Nueva.}
{115}{}{Disturbing rumors are coming from Casa Nueva; it's unsafe there now.}

{116}{}{Highwaymen robbed another caravan from Phoenix.}
{117}{}{They say the Blue Shields have finally been shut down.}
{118}{}{The Blue Shields have grown stronger. Now they must be reckoned with.}

{119}{}{I always thought those fire worshippers were illogical.}
{120}{}{The Followers of Fire got what they dreamed of.}
{121}{}{Primitive fire worshippers are trying to dictate terms to us.}

{122}{}{The uranium reserves from Flagstaff are insufficient.}
{123}{}{Energy rationing is required until the Flagstaff mine resumes output.}
{124}{}{Energy conservation protocols lifted; Flagstaff's uranium reserves are now sufficient.}

{125}{}{Admission to the Forbidden Zone would change our entire lives.}
{126}{}{We must leave before ZAX finally unleashes its wrath on us.}
{127}{}{Entering the Forbidden Zone will change everything for us.}

{128}{}{Post-operation, Master Hard's empathy circuits have malfunctioned.}
{129}{}{Another visit to Doc Jones could cause a system shutdown.}
{130}{}{Maintain your function within the Collective's framework.}

{131}{}{Don't forget to pray to the God of Technology before eating.}
{132}{}{Pray to the Gods of Steel for our existence.}
{133}{}{Need to clean my joints.}
