{100}{}{You see a raider.}
{101}{}{You see a stranger. Judging by his appearance, he's had a rough time.}
{102}{}{You gained }
{103}{}{ experience points for resolving the conflict peacefully.}
{104}{}{   }
{105}{}{The raider peacefully leaves the Villa.}
{106}{}{My first kill... Strange feeling.}

#Floating Lines
{110}{}{*Heavy breathing*}
{111}{}{*Coughs*}
{112}{}{Grrr...}
{113}{}{Damn it...}
{114}{}{Why the hell did I get mixed up in this?}
{115}{}{What the hell am I even doing here?}
{116}{}{There's gotta be a way out of this.}
{117}{}{I'm not going down that easy.}
{118}{}{Where's my crew? Damn them!}
{119}{}{Is this it? Is this how it ends for me?}

{120}{}{Think what you want about me. I don't give a damn.}
{121}{}{I'm not coming back, so stop shaking in your boots.}
{122}{}{The conversation's over. Don't piss me off.}

#Dialogue Start
{200}{}{(You see a ragged, dirty raider - he looks wounded and exhausted) Hey, you... *cough* Kiss your ass goodbye, you stupid peasant!}
{201}{}{Hey, take it easy, I mean you no harm.}
{202}{}{I'll defend myself if you come at me.}
{203}{}{Shut up... *heavy breathing* I've been trapped down here for more than a day. Think I'll just let that slide? *cough* You're all gonna pay for this. Starting with you!}
{204}{}{You're not giving me a choice. I'll have to calm you down the hard way.}
{205}{}{Go to hell!}
{206}{}{Hey, hey, wait...}
{207}{}{Let's get busy then...}
{208}{}{Listen, there's no need for us to fight...}
{209}{}{Listen, there's no need for us to fight. Calm down. The raid is over. Your friends are gone.}
{210}{}{You look rough. I could help you.}
{211}{}{You're not seriously thinking about fighting in your condition, are you? I can help you, if you calm down.}
{212}{}{I wouldn't do that. There's traps all around.}
{213}{}{There's traps everywhere. You won't get out alive, without me. Only I know the way out.}
{214}{}{You're goint to attack a defenseless woman? What's wrong with you?}
{215}{}{(rubs his eyes and takes a breath) Fine... you're right. Help me get out of here, but don't try anything funny. Fuck me around and I'll gut you.}
{216}{}{Okay... Maybe you could start by telling me what happened?}

{220}{}{Stop dicking around. I'm dying here, for fuck's sake. Hurry up and help me get out of here.}
{221}{}{Fine, get out of here. Behind that shelf is a hidden exit to the cellars. You can get to the upper floors from any of them.}
{222}{}{And you really think I'll let you go after everything you've said? You're too dangerous for the Villa.}
{223}{}{A hidden exit? Clever... Damn, I'd kill you, but I'm in no shape for that. Need to save my strength. So you can live for now.}
{224}{}{Eh, whatever. We can do without goodbye hugs.}
{225}{}{Just go. Stop wasting my time.}
{226}{}{Yeah, you can take this. (throws you an old key stolen from your father by the raiders) There's nothing valuable there anyway.}
{227}{}{Hm...}

#About Himself
{250}{}{Who are you?}
{251}{}{None of your goddamn business.}
{252}{}{Hmph. That was a useless question.}
{253}{}{Sorry. I'm just asking because I've never talked to a stranger before.}
{254}{}{Just tell me how you ended up like this.}
{255}{}{I'm just a mercenary. Get it? No home, no family, no name.}
{256}{}{Oh, sorry. It must be tough growing up without a family or home?}
{257}{}{Are all of you wasteland folks this... uh, wild? Here in our Villa, we're like one big family.}
{258}{}{I don't know... I don't know what it's like to live in a big pack, like you. I probably couldn't do it. I can't share, or trust anyone but myself... Damn, you'd better shut up before I knock your teeth out.}
{259}{}{Why are you so pissed off?}
{260}{}{Oh, it bothers you, does it?}
{261}{}{You wouldn't understand. I was found in a dumpster in a big city. An ordinary story. Where I'm from, people aren't valued. The population is too large, and there's nothing to do. One person disappears - and no one notices.}
{262}{}{If things are so bad outside the Villa, I guess I can understand. A little bit, anyway.}
{263}{}{You should have fought for a place, a home. Sounds like you just ran away from the problem.}
{264}{}{I don't need your pity. Just get me out of here.}
{265}{}{Wait. Answer another question first.}
{266}{}{Think it's that easy, huh? Of course, you're here, not there. You don't know. Better shut up and get me out of here.}
{267}{}{Hold on. Answer one more question first.}

{270}{}{Why did you get involved in this raid business?}
{271}{}{Because I needed to earn caps for food. Got it? There was no work, and they were recruiting. I just wanted to make some easy caps on this raid and then split. And what happened? I'm here. Stuck in the basement, for fuck's sake.}
{272}{}{Wasn't there any other work? That's so sad.}
{273}{}{Or maybe you just didn't want to do real work?}
{274}{}{Doin' this work is a real grind. They pay you in scraps. I'm sick of it! I want to live nicely, too.}
{275}{}{What did you do before this?}
{276}{}{Your friends didn't think much of you. Just left you behind.}
{277}{}{No one gives a damn about you. Survive as you can. I've worked in all sorts of places, from a bartender to a raider slaver. I have to earn my food somehow.}
{278}{}{I see your pretty touchy about this. Don't want to talk about it anymore?}
{279}{}{No, I don't want to.}
{280}{}{Well, that's your right.}
{281}{}{In my opinion, it just sounds like your making excuses for your incompetence.}
{282}{}{Then shove your opinion up your ass.}
{283}{}{Hey, no need to get harsh.}
{284}{}{You're making yourself out to be a real 'bad' guy to match your current situation, aren't you?}
{285}{}{Damn, there's something to that. Maybe I'm just hanging out with the wrong people? Or maybe I should sit down and think... No, I need you to just shut up. Remember who's boss here.}
{286}{}{Sure, right now you're the boss.}

#About the Raid
{290}{}{Tell me, what happened here?}
{291}{}{You mean the collapse, the stairs? (spits) Stupid story.}
{292}{}{How did you end up down here?}
{293}{}{Well, of course, only a fool would get into such a mess.}
{294}{}{Alright, never mind then.}
{295}{}{We forced one of your people to show us the basement. Thought something valuable was stored here. I went down first, but got caught in, or maybe triggered, the trap. There was an explosion behind me, the ceiling collapsed, sent me flying'. I got knocked out. That's all I remember.}
{296}{}{Hmm, seems like that was one of my padre's traps. He set it up just in case the Villa was invaded by outsiders.}
{297}{}{And you thought it would be that easy? My padre prepared for the possibility of an attack on the Villa.}
{298}{}{Looks like we underestimated the cunning of your people. How many more tricks and secrets are hidden in these dungeons, huh?}
{299}{}{Did you try to get out or call for help?}
{300}{}{No one answered. Those bastards just left me. I couldn't get out of the basement by myself - the stairs were destroyed, and I couldn't find another exit. But... since you're here, there must be a way out, right?}
{301}{}{Uh, yeah, but first I need ask you something else.}
{302}{}{Found anything interesting in these cellars?}
{303}{}{Nothing worth risking my hide for. Although it's strange to see ancient tech in a dump like this. What do you need it for?}
{304}{}{What tech are you talking about?}
{305}{}{Tech? You must've bumped your head bad. Old World tech is banned in the Villa.}
{306}{}{Don't you know? There's Old World tech right in the next room. So old and broken down, it's not even worth scrapping. I wouldn't be surprised if you secretly worship those pieces of junk.}
{307}{}{You're crazy. Why would padre hide forbidden items from us? He's the first to scold us when something is brought from the Wastes.}
{308}{}{It's just ordinary junk, right? You must be mistaken.}
{309}{}{How should I know? You live here. But if your leader has a stash of hidden things he forbids, well, I wouldn't trust a hypocrite like that.}
{310}{}{He must have a good reason. But that's not the point right now.}
{311}{}{Don't you dare speak ill of my father. Got it?}
{312}{}{I don't know. My specialty isn't figuring out tech, it's smashing faces with it.}
{313}{}{I'm sure padre has a good reason. But that's not the main thing right now.}
{314}{}{Yeah, right. By the way - smashing faces is my specialty too.}
{315}{}{Not much else to expect from a wasteland raider. Alright, enough about that.}

{320}{}{What do you know about what happened upstairs? Before you got trapped down here.}
{321}{}{Not much. I was only involved in the beginning of the raid.}
{322}{}{Why did you attack us in the first place? Were you after our crops?}
{323}{}{Damn raiders. Is looting all you're good for, or do you have any use at all?}
{324}{}{Stupid peasant, you... (mocks you, then coughs bitterly) You don't have the slightest idea about the outside world, do you? Your folks were taken to work in the mine. Though I doubt you even know what that is.}
{1324}{}{Stupid peasant girl, you... (mocks you, then coughs bitterly) You don't have the slightest idea about the outside world, do you? Your folks were taken to work in the mine. Though I doubt you even know what that is.}
{325}{}{[Listen]}
{326}{}{Alright, watch your mouth, or else...}
{327}{}{They'll put collars on them and force them to work underground. Those who refuse to obey will be harshly punished. Face it, those people won't come back to the Villa. Some might never see the light of day again.}
{328}{}{I don't understand how you could go along with something like this.}
{329}{}{Too bad I wasn't here during the attack. You'd all be fertilizer by now.}
{330}{}{Open your eyes, peasant. It takes just one rifle for every three of you to bring this place to its knees. What can you do against a whole band of armed mercenaries? (spits) You've lived in your eden for too long and have no idea how cruel the world is outside.}
{1330}{}{Open your eyes, peasant girl. It takes just one rifle for every three of you to bring this place to its knees. What can you do against a whole band of armed mercenaries? (spits) You've lived in your eden for too long and have no idea how cruel the world is outside.}
{331}{}{Seems like you don't care much for this place.}
{332}{}{Don't speak ill of the Villa. This place *is* an eden.}
{333}{}{You have no idea what it's like to survive. I lived on the streets, fought for food, robbed people, and even killed. Like everyone in the Wastes... Everyone except you.}
{334}{}{[Continue]}
{335}{}{You're the only ones who eat and drink as much as you want. You're clean, chubby, and look down on people from the Wastes like we're trash. You disgust me. Your fuckin' Villa is a thorn in my side.}
{336}{}{Hmph. I have no idea what you've been through. And I don't want to know.}
{337}{}{That's your excuse for everything? You're the thorn.}
