{100}{}{You see the envoy.}
{101}{}{You see an official envoy from the Brotherhood of Steel.}
{102}{}{Our alliance is over, Envoy.}
{103}{}{You're under reliable protection.}

# First dialogue
{200}{}{Greetings. I'm the envoy from the Brotherhood of Steel. So then, was it you who managed to rally your tribe to ally with us? Good job. Many mutual benefits will come from our cooperation.}
{201}{}{Are you here alone?}
{202}{}{Don't worry, my squad is camped nearby in the wasteland. We thought our presence might... unsettle your fellow villagers a bit. If necessary, I can always call them by radio.}
{203}{}{Thanks for your service, Envoy. I gotta go.}
{204}{}{Okay. I hope that is the case, because if not, our cooperation would end before it even begins.}

{210}{}{Greetings.}
{211}{}{I gotta go.}
