{100}{}{You see Fernando.}
{101}{}{You see a ghoul in an old suit. A gray Mexican mustache hangs off his face.}
{102}{}{Hey. The robots aren't letting anyone into the station. Guarding it like it's their mama.}
{103}{}{Hey. What am I doing here? Nothing much, as you can see.}
{104}{}{What's going on? Why was the concert canceled?}
{105}{}{Hey, buddy!}
{1105}{}{My respects, senorita!}

{110}{}{We've gone too far. The Old Town is the other way.}
{111}{}{Could this be the legendary Ghost Station?}
{112}{}{The station comes to life, and with it, the town. All thanks to you.}
{113}{}{I hope Bonita gets up and running soon.}
{114}{}{Careful! Border patrol robots are often seen in this area.}
{115}{}{Ahead is a cliff leading to the Otay River.}
{116}{}{If we take the bridge, watch your step.}
{117}{}{Believe it or not, on weekends these places used to be packed. Now, not a soul.}
{118}{}{The Otay River basin. It used to be beautiful here.}
{119}{}{That big building is a military hospital. It's already been looted.}
{120}{}{}
{121}{}{I don't feel like going there.}
{122}{}{We're close to the blast epicenter. You shouldn't linger here.}
{123}{}{Little Italy - before the War, it was known for its cafes... and also its gangsters and pimps.}
{124}{}{Shall we cut through the park? Smart move, lower radiation here, but more critters.}

{200}{}{At your service, senor.}
{1200}{}{At your service, senorita.}
{201}{}{Goodbye.}
{202}{}{Who are you?}
{203}{}{My name is Fernando.}
{204}{}{What are you doing here?}
{205}{}{Nothing much, as you can see.}
{206}{}{Jose Solis sent me. He's trying to get his mariachi band back together.}
{207}{}{Really?! Great idea. I'm in. When do we perform?}
{208}{}{I don't know yet. Wait a bit.}
{209}{}{Let's go right now. I'll take you straight to Jose in Old Town.}
{210}{}{It's gonna be hard to get through the ruins. I hope you know the way?}
{211}{}{Yes, let's go.}
{212}{}{I'm up for getting Jose's band back together. Can you escort me to the Old Town?}
{213}{}{Yes, let's go.}
{214}{}{No, not right now.}
{215}{}{Yes?}
{216}{}{Nothing. Never mind.}
{217}{}{Come with me. The stage in the Old Town awaits you.}
{218}{}{Wait for me here. I'll be back soon.}
{219}{}{Thanks for the help, buddy. I'll play a funeral march in your honor.}
{1219}{}{Thanks for the help, senorita. I'll play a funeral march in your honor.}
{220}{}{Yeah. Enjoy.}
