{100}{}{You see a ghoul.}
{101}{}{You see one of the ghouls.}

{102}{}{It's kind of boring here without music, don't you think?}
{103}{}{Hey, thanks for the music!}

{110}{}{Do you know Talius?}
{111}{}{Well, he's not like us, he's a mutant.}
{112}{}{Talius preaches the word of God.}
{113}{}{I used to believe in God and went to church on weekends.}
{114}{}{But after many years of immortality, I believe in nothing.}
{115}{}{Don't let others get into your soul.}
