{100}{}{You see Rutger.}
{101}{}{You see the leader of the Far Go Traders.}
{102}{}{Quiet! We'll talk when we reach our camp.}
{103}{}{Rutger headed to the caravan camp.}
{104}{}{Don't come closer, mutant! I'll kill you, damn it!}

{200}{}{I didn't expect to see anyone here, least of all a normal human.}
{201}{}{The ghouls sent me to help.}
{202}{}{Mutants ambushed us. Luckily, we spotted them in time and took cover in these warehouses. They haven't attacked yet, but it's just a matter of time. Think you can get us out of here, from under their noses?}
{203}{}{I think I can. I managed to get in here, didn't I?}
{204}{}{Great. Then let's sneak out in small groups, one at a time. First, get my guards out.}
{205}{}{Alright.}
{206}{}{I'll distract the mutants while you get the guards out. It'll be better if break up into small groups - less likely for the super mutants to spot us.}
{207}{}{Okay.}
{208}{}{I'm the last one, right? Then let's move out!}
{209}{}{Let's go.}
{210}{}{It's too dangerous to leave now. We need to wait a bit.}
{211}{}{I saw the mutants leaving along the road. But it could be a trap. Try to get my guards out first.}
{212}{}{I doubt we can leave without being spotted. How about we attack them instead?}
{213}{}{I can't risk my people. I'd rather avoid a fight. First, let's get the guards out.}
{214}{}{Looks like you're gonna have a lot more company soon. You need some help?}
