{100}{}{You see Jane.}
{101}{}{You see a ghoul in a regular pre-war dress.}
{102}{}{Thank you for saving Donovan. We were already preparing for the worst.}
{103}{}{Sorry, I'm too wound-up right now.}

{200}{}{(Jane) ... Frank, I feel something has happened to him. He would have returned by now... Oh, we're being overheard.}
{1200}{}{(Frank) ... I'm telling you, Jane, he's in trouble! Otherwise, he would have returned by now... Hey, are you eavesdropping, smoothskin?}
{201}{}{You seem to be worried about something?}
{202}{}{(Frank) None of your business, human. This is our ghoul business.}
{203}{}{[Next]}
{204}{}{(Jane) Oh, forgive Frank, he's on edge right now.}
{205}{}{Okay... So, what's happened?}
{206}{}{I'll let it slide. Now tell me, what the hell is going on?}
{207}{}{(Jane) We've lost our friend, Donovan. He went to San Ysidro and didn't return. No one in San Ysidro has seen him either.}
{208}{}{[Next]}
{209}{}{(Frank) Jane, why are you blabbing in front of this smoothskin? We've had enough trouble from smoothskins. I wouldn't be surprised if Donovan was taken by scavengers.}
{210}{}{[Next]}
{211}{}{(Jane) Frank, we need help, isn't it obvious?}
{212}{}{[Next]}
{213}{}{(Frank) Hmm, listen, smoothskin, don't you have anything else to do? Either help us or get lost. I don't want to deal with humans. Got it? But... uh, we *could* use some help.}
{214}{}{I'll help you. Whether you want me to or not. Just to show you that not all humans are bad.}
{215}{}{(Jane) Oh, how wonderful! See, Frank, they're not all bad. Thank you, human. We'll be waiting to hear from you.}
{216}{}{Alright. See you.}
{217}{}{I really don't care about your problems. Goodbye.}
{218}{}{(Frank) Hey, hey, hey, don't rush off like that! Just keep in mind that our friend Donovan is somewhere in the ruins on the way to San Ysidro. If you meet him... well, at least remind him of us, okay?}
{219}{}{Sure, whatever. See you.}
{220}{}{(Jane) ... Frank, I feel something has happened to him. He would have returned by now... Oh, we're being overheard.}
{221}{}{[Next]}
{222}{}{(Frank) Hmm. I don't recognize you. Still, I'm glad to see you. Will you spare us some time?}
{223}{}{What do you need from me?}
{224}{}{(Jane) We've lost our friend, Donovan. He went to San Ysidro and didn't return. No one in San Ysidro has seen him either.}
{225}{}{Let me guess - you want me to find him?}
{226}{}{(Frank) You're pretty sharp for a ghoul. Anyway, we need help. Donovan is somewhere in the ruins on the way to San Ysidro. If you meet him... well, try not to leave him in trouble, okay?}
{227}{}{Alright. See you.}

{230}{}{Any news about our friend?}
{231}{}{Not yet. I'll keep searching.}
{232}{}{Where do you think he could be?}
{233}{}{He headed to San Ysidro. But he didn't get there and didn't return. So he could be somewhere along the way.}
{234}{}{Maybe he just found a crate of beer and decided to open it alone?}
{235}{}{Got it. I'll keep searching.}
{236}{}{What nonsense are you talking about? Donovan was the brains of our modest company...}
{237}{}{I have bad news. Here's Donovan's body. Donovan is dead.}
{238}{}{Why didn't you tell me Donovan was so short? He wasn't easy to find.}
{239}{}{(Jane) Oh, God, Donovan, wake up! (Frank) Donovan, you're joking again! Stop fooling around!}
{240}{}{Um. Are you guys stupid? He's dead. Dead as a doornail.}
{241}{}{You'll have to face the truth. His body was torn in half. No one survives that.}
{242}{}{Listen, we just need to take him to a doctor. Please, find Talius in San Ysidro. He'll get Donovan back on his feet. We just can't do it as quickly as you.}
{243}{}{You guys are crazy! Maybe Talius can at least explain to you that it's impossible to revive a dead person.}
{244}{}{Are you serious? Fine, I hope this will at least settle you down a bit.}
{245}{}{Don't waste time! Please! Take Donovan to Talius.}
{246}{}{Alright, alright. Yeesh.}
