{100}{}{You see Donovan.}
{101}{}{You see a robot, inside of which Donovan's brain functions.}

{110}{}{I'm a robot now. It's so unusual. And so cool!}
{111}{}{I feel much better in this body!}
{112}{}{I feel like I've become a hundred years younger.}
{113}{}{I've never felt as great as I do now.}
{114}{}{I think all ghouls should get a form like this.}
{115}{}{Pathetic humans, you have no idea how fragile you are!}
{116}{}{De Santi tried to kill me. He's a real bastard.}
{117}{}{}
{118}{}{}
{119}{}{}
