{100}{}{You see Phil.}
{101}{}{You see an elderly ghoul in glasses. He is weakly rocking back and forth in his chair.}

{200}{}{Hey, which book character are you, esteemed one? I don't remember reading about you.}
{201}{}{What are you babbling about, old fart?}
{202}{}{Oh, sorry, sorry! Can't a man fantasize anymore? By the way, I'm Phil. Sort of a scientist, if you can call it that.}
{203}{}{Nice to meet you, Phil. It's rare to meet scholars these days.}
{204}{}{Hello, biblioPHILE.}
{205}{}{I'm a real person, not a character.}
{206}{}{Hmm? (peering at you through his glasses) Where does this confidence come from? Well, it doesn't matter, it can't be proven or disproven anyway. By the way, I'm Phil. Sort of a scientist, if you can call it that.}
{207}{}{Hmm. Maybe I'm the main character of an adventure novel.}
{208}{}{Oh, I like it when people can be ironic about themselves. Unlike those gloomy types behind the wall. They got so serious with building their city, more than they ever were in their whole lives. By the way, I'm Phil. Sort of a scientist, if you can call it that.}
{209}{}{}

{210}{}{What can I do you for?}
{211}{}{Uh, nothing.}
{212}{}{Hey, who are you supposed to be, some character out of a book? Can't say I remember reading about you.}
{213}{}{Oh, excuse me, so sorry! Can't a man fantasize anymore?}
{214}{}{You seem a little *too* immersed in fantasy.}
{215}{}{Oh, I do like folks who can laugh at themselves. Not like those grim types behind the wall - got so serious about building that city, more serious than they've ever been in their whole lives.}
{216}{}{That's natural.}
{217}{}{Hmm? (peering at you over his glasses) Where's all that confidence coming from? Not that it matters - can't prove it or disprove it, now can we? Ah, the mundanity of life!}
{218}{}{Life is generally boring unless you entertain yourself.}
{219}{}{I won't argue with that.}

{220}{}{Who are you?}
{221}{}{I'm Phil. Sort of a scientist, if you can call it that. The brain of this city, if you will.}
{222}{}{Really?}
{223}{}{Well, I helped with everything that required pre-war knowledge - from old manuals to programs for Mr. Handy.}
{224}{}{I see.}
{225}{}{And I'm also the world chess champion. No one, not even those cunning commies, could beat me. And those were life-or-death matches!}
{226}{}{Interesting.}
{227}{}{How about a game of chess? I'm sure I can beat you, even though you're the world champion.}
{228}{}{How about a game of chess? I will beat you and break the world record.}
{229}{}{You? Don't make the old man laugh! You don't stand a chance. I'm the only one who managed to beat the ZAX supercomputer. What can you say about yourself?}
{230}{}{I still want to try.}
{231}{}{A waste of time.}
{232}{}{Then forget it. I'll find something else to do.}
{233}{}{You made a mistake by saying I don't have a chance. There's always a chance. I challenge you to a match.}
{234}{}{Oh, it sounds serious, like in a good novel. Ok, I'll give you one chance. Just one game. If you beat me - you'll get access to my library.}
{235}{}{I need to uh, mentally prepare for the match. Bye.}
{236}{}{I'm ready to take you on. Let the chess battle begin!}
{1236}{}{I'm ready to take you on. Let the chess battle begin!}
{237}{}{Not bad. Quite good for an amateur. However, you'll need a lot more practice to beat me.}
{238}{}{Well, I tried my best.}
{239}{}{Let's talk about something else.}
{240}{}{You actually beat me? Extraordinary!}
{241}{}{Do you want to play a game of chess?}
{242}{}{I guess you should never underestimate your opponent?}
{243}{}{It was definitely a fluke. Didn't mean to dethrone the champ.}
{1243}{}{It was definitely a fluke. Didn't mean to dethrone the champ.}
{244}{}{I don't get how that happened. In 90 years, I've studied every possible move in chess. But that move of yours... how did I miss it? Maybe I've lost my edge without any real competition. That's why you need a good rival! Keeps you sharp - we could definitely learn from each other.}
{245}{}{We could, yes. So, can I take a look at your books?}

{250}{}{Is there anything needing doing in this city?}
{251}{}{Let me think. Butler must have some jobs. He is trying to bring the city back to life, and also dealing with the influx of strangers from the north. Everyone else has problems too. Each has their own.}
{252}{}{Can't you be more specific?}
{253}{}{Sorry, but lately I've been so engrossed in reading that I've stopped keeping track of what's going on in the city.}
{254}{}{I see.}
{255}{}{What are you reading?}
{256}{}{Right now I'm reading some old book about conquistadors in Spanish. Real exciting. Don't want to put it down.}
{257}{}{Do you need a specific book? I could look for it.}
{258}{}{Alright, never mind. Keep reading.}
{259}{}{Oh, there is one book! Just before the war, a new book by Mortimer was announced in San Diego. His last I guess - Ha ha. I'm curious about what nonsense he could have written about this wonderful city.}
{260}{}{Where could I find it?}
{261}{}{Somewhere in the ruins, I suppose. I don't know exactly.}
{262}{}{Alright, I'll look for it.}
{263}{}{Well, you'll have to look for it yourself. I have more important things to do.}
{264}{}{You're in luck. I have that book right here.}
{265}{}{I found Mortimer's last book.}
{1265}{}{I found Mortimer's last book.}
{266}{}{A new book! Oh, how long it's been since I felt this thrill before a fresh edition. Let's see what sensational stuff Mortimer scraped together about San Diego... Oh yes, you probably expect some payment. Here's 100 hubbucks. Now go, go, don't bother me when I'm reading!}
{267}{}{Goodbye.}

{270}{}{Right now I'm reading an old book about conquistadors in Spanish. Boring. Not my thing.}
{271}{}{Right now I'm reading the Vancouver city phone directory. Very monotonous narrative.}
{272}{}{Right now I'm reading stories about the last oil wars. You know, back then whole countries were capturing our oil tankers. Good thing it's all over.}
{273}{}{Right now I'm reading a set of rules for flying a dirigible. You laugh? Well, someday someone will fly them again. Believe me.}
{274}{}{Right now I'm reading a story about how communists took over the USA and built a totalitarian state here. So far, it looks pretty good.}

{280}{}{I need a program for Mr. Handy.}
{281}{}{That's not difficult. But I'm so engrossed in this wonderful book. I can't tear myself away!}
{282}{}{What if I bring you even more books?}
{283}{}{More books?! Yes! Bring me five pre-war books, and I'll write that program. Easy.}
{284}{}{Alright.}
{285}{}{I have those books right here. Here they are.}
{286}{}{Ah, new additions! Well, it can't be helped, I'll have to tear myself away from reading. I'll write the program now. What was it you needed again?}
{287}{}{A hotel manager program...}
{288}{}{Or maybe you'll just help a good person out?}
{289}{}{I would certainly help a GOOD person, IF I see one.}
{290}{}{Jerk!}
{291}{}{So I'm definitely not the hero of one of your books. That's sad.}
{292}{}{Forget it. I have some books. Here they are.}
{293}{}{Come on Phil, how can you be so selfish? We're all in this together. Help me with this damn program!}

