{100}{}{You see a ghoul scavenger.}
{101}{}{You see a ghoul. He is carefully surveying the area.}
{102}{}{Hey, buddy, got a light? There's junk a plenty, but not much fire...}
{1102}{}{Hey, friend, got a light? There's junk a plenty, but not much fire...}
{103}{}{Fire! Fiiiire!}
{104}{}{One lighter should be enough for you.}

{200}{}{Flames descended from the heavens! Do you see it? Everything is burning around. Everything! Even the stones are burning!}
{201}{}{What are you crazy? I think you're seeing things.}
{202}{}{Am I going crazy? Nooo. The flames of the Great War still burn. They burn in my heart. And every time I see the slightest spark, I remember them. It can't be forgotten. So I want to... remember once more... Look, it's burning! Burning well!}
{203}{}{I see you have a thing for this. Maybe you have, uh, fuel you want to trade?}
{204}{}{Sure, fire is uh, mesmerizing.}
{205}{}{You also love FIRE? Yes, the flames of the Great War haven't extinguished. They burn in my heart. And every time I see the slightest spark, I remember them. It can't be forgotten. So I want to... remember once more... Look, how it's burning! Burning well!}
{206}{}{And now - create your own flame!}
{207}{}{Uh, sure, definitely.}
{208}{}{Actually, I do want to start a little fire. Do you have anything flammable?}
{209}{}{I think I'll step away while you play with fire. Bye.}
{210}{}{Do you like watching the flames?}
{211}{}{You definitely need the flame. Everyone needs it.}
{212}{}{Fire purifies. It takes away everything you owned. It creates emptiness. Isn't that wonderful?}
{213}{}{Hmm... like it or not, I'm taking all the fuel you have.}
