{100}{}{You see Knight Jerry.}
{101}{}{You see a Brotherhood of Steel knight. He looks quite worn out.}

{200}{}{Shh! There's a mutant lurking around the entrance. If he spots us, we're done for. I'm hurt pretty bad and can't fight. You're my only chance.}
{201}{}{The mutant's gone? Thank you, brother! Now I need to treat my wounds. Do you have a stimpak or anything?}
{1201}{}{The mutant's gone? Thank you, sister! Now I need to treat my wounds. Do you have a stimpak or anything?}
{202}{}{The mutant's dead? Thanks, brother! Now I need to treat my wounds. Do you have a stimpak or anything?}
{1202}{}{The mutant's dead? Thanks, sister! Now I need to treat my wounds. Do you have a stimpak or anything?}
{203}{}{I'm doing what I can. Stop whining!}
{204}{}{I'll do what I can.}
{205}{}{Thanks for fixing me up. Now I can fight at full strength. Although I'm low on ammo. Where's that mutant? He must be waiting at the entrance.}
{206}{}{Let's go, together we can give him a good beating!}
{207}{}{You better stay put or you're gonna reopen those wounds. I'll deal with that brute.}
{208}{}{The danger has passed. That brute has already left.}
{209}{}{That brute won't bother anyone anymore. We can leave our cover now.}
{210}{}{There he is! Careful!}
{211}{}{Don't shoot! This is Gomer, my partner.}
{212}{}{What the... I appreciate you saving me, but this is insane! Mutants are dangerous! They've wiped out entire human settlements. Why on earth are you walking around with this thing?}
{213}{}{He's harmless. It's natural to hate mutants, but we can always make exceptions, can't we?}
{214}{}{I'm not even sure why I need him. He just looks out for me and carries my stuff. Just... please don't touch him, alright?}
{215}{}{Who are you anyway? I knew a vault-dweller once. He tried to help his brothers and sisters. And when he did, he was just... cast out. Kindness without the strength of weapons ends sadly.}
{1215}{}{Who are you anyway? I knew a vault-dweller once. He tried to help his brothers and sisters. And when he did, he was just... cast out. Kindness without the strength of weapons ends sadly.}
{216}{}{Maybe so.}
{217}{}{Who knows?}
{218}{}{Ah, if only we'd had someone like you on the front lines six years ago - so many brothers could have been saved from the super mutants!}
{219}{}{Back then, I was working on the plantations and had no idea there was a war with super mutants. That's why I cherish my rural life.}
{220}{}{I did manage to save you, so that's something.}
{221}{}{Okay, now I need to find a place to clean up. Thanks, brother.}
{222}{}{By the way, what's the Brotherhood doing here?}
{223}{}{When the elders found out that mutants were moving toward San Diego, they dispatched me and my squad to scout the area. I never expected to find such chaos here - radiation, monsters, super mutants, ghouls, and robots; it's a nightmare! I need to report this to the commander. This place isn't safe for ordinary people.}
{224}{}{Got it. Well then, safe travels. Watch out for mutants.}
{225}{}{Thanks again.}

