{200}{}{Ahhh, I haven't slept so soundly in ages.}
{201}{}{What are you doing in here?}
{202}{}{Why the hell are you sitting in a fridge? I thought someone had stuffed a corpse in it!}
{1202}{}{Why the hell are you sitting in a fridge? I thought someone had stuffed a corpse in it!}
{203}{}{I hid from some mutants, then fell asleep. How long has it been? Probably just a couple of weeks. Well, I'll go catch up on sleep in town.}
{204}{}{Take care.}
{205}{}{Don't fall asleep on the way, you weirdo.}
{206}{}{I wanna sleep...}
