{100}{}{You see a ghoul before you.}
{101}{}{You see a regular ghoul before you.}

{200}{}{Hey, kid, wanna hear an amazing story?}
{1200}{}{Oh, lady, wanna hear an inspiring story?}
{201}{}{Well, I won't tell it then! Gotcha, huh?}
{1201}{}{Well, I won't tell it then! Gotcha, huh?}
{202}{}{Nah, but if you really wanna hear it, I'd tell it over a cold one.}
{1202}{}{Nah, but if you really wanna hear it, I'd tell it over a cold one.}

{210}{}{I lived in the sewers after the bombs fell. Survived on puddle water and rats. Not worth it, trust me.}
{211}{}{The Master used to be our leader. He ruled all ghouls with an iron fist. Luckily, he's no longer with us.}
{212}{}{Even before the Great War, oil ran out on the planet. It begs the question - what were we fighting for during the War?}
{213}{}{Up north, there are a few large settlements. But it's nothing compared to the megacities that existed before the War.}
{214}{}{The Master and his super mutants were a serious force. They tried to subjugate humans and ghouls alike. Good thing they're gone. But not entirely, right?}
{215}{}{Phew... I think I've had too much... interview's over...}

