{100}{}{You see Tobias.}
{101}{}{You see a ghoul in a border guard uniform and hat. His face is disfigured, and his gaze is unsettling.}
{104}{}{Thank you. I always felt like something was missing here.}
{105}{}{Tobias attaches a badge to his uniform. You notice a semblance of a smile on his disfigured face.}
{106}{}{Tobias already wears such a badge.}

{200}{}{[You can't pass. This place is for ghouls only.]}
{201}{}{[Alright, I'll leave.]}
{202}{}{[I'll force my way through.]}
{203}{}{[Give me a task to pass.]}
{204}{}{[Destroy the robot in Tijuana.]}
{205}{}{[Okay.]}
{206}{}{[Robot neutralized.]}

{210}{}{Human, you don't belong here. Leave.}
{211}{}{You can't keep me out.}
{212}{}{(raises rifle) You wanna bet?}
{213}{}{I'm going through anyway. Get out of the way, freak!}
{214}{}{Alright, alright, I don't want in that badly...}
{215}{}{Why don't you want to let me in?}
{216}{}{Normies like you have no place in our city of ghouls. You're the ones who drove us into these ruins in the first place.}
{217}{}{Listen, I've come a long way to get here. Maybe we can work something out?}
{1217}{}{Listen, I've come a long way to get here. Maybe we can work something out?}
{218}{}{Well, I guess I'll have to leave then. Sorry for the trouble.}
{219}{}{Hmm. Maybe I'll let you through if you do us ghouls a favor.}
{220}{}{What kind of favor?}
{221}{}{There's a giant military robot roaming the ruins of Tijuana, been there since before the War. It's keeping us from exploring the area freely. Take it out, and I'll let you through.}
{222}{}{I'd rather just take you out. It's much easier.}
{223}{}{Deal. I'll do it.}
{224}{}{The last sighting of this robot was near the bullring. We've set up electromagnetic traps there, but so far, no luck.}
{225}{}{Got it. I'll keep that in mind.}
{226}{}{I ran into this robot already. It's no longer a threat to anyone.}
{227}{}{I'm not suicidal. I'd rather just head back to Sonora...}
{228}{}{You're not getting through until I give you permission.}
{229}{}{About that robot. It's destroyed.}
{230}{}{You must have a really good reason to visit the city. Well, go ahead. Welcome to Dayglow.}
{231}{}{Thanks for the warm welcome.}
{232}{}{You should have just let me through from the start. What a waste of time...}
{233}{}{Greetings, brother. First time in Dayglow?}
{1233}{}{Greetings, sister. First time in Dayglow?}
{234}{}{Yes. Can I come in?}
{235}{}{Of course! But you'll need to undergo inspection. It's the rules, sorry.}
{236}{}{I understand.}
{237}{}{You know what, I've changed my mind about going in. Goodbye!}
{1237}{}{You know what, I've changed my mind about going in. Goodbye!}
{238}{}{Alright. What's your name and where are you from?}
{239}{}{I'm }
{240}{}{, from Southern Arizona.}
{241}{}{Show me your backpack. Any prohibited items?}
{242}{}{Depends on what's prohibited here...}
{243}{}{Ha, just kidding! You're free to go through to the camp.}
{244}{}{Seriously?}
{245}{}{Yup! Welcome to Dayglow!}
{246}{}{Thanks.}
{247}{}{Back in the day, crossing the border like this would've gotten you in trouble. But since you're here now, I'll allow it. Just don't go stirring up trouble with the ghouls.}
{248}{}{No problem.}
{249}{}{Well, that's unexpected. Thanks. And uh, ...welcome to Dayglow.}
{250}{}{You can pass.}
{251}{}{Goodbye.}
{252}{}{You can pass. I wouldn't have let you in, but someone at the camp made a fuss over you.}
{253}{}{I'll hang around here for a bit. Need any help?}

