{100}{}{You see a ghoul mechanic.}
{101}{}{You see a ghoul in a tattered work uniform. One of his eyes is replaced by some sort of built-in lens.}
{102}{}{Sorry, we only serve ghouls and ghoul friends here.}
{103}{}{I'm not going to serve an ass like you. Get lost.}
{104}{}{That won't work on me. But it looks cool.}

{200}{}{This is a workshop and general store. The boss says we can make a deal with you. But I'll still keep an eye on you.}
{201}{}{Well, you'll see that's not necessary.}
{202}{}{That's no way to talk to customers.}
{203}{}{This is all I've got. If you need other stuff, head to Old Town.}
{204}{}{Goodbye.}
{205}{}{Can I ask you about something else?}
{206}{}{Hello, friend! Glad to see you. This is a workshop and general store. Come on in, pick anything you like. Big discounts for ghouls and mutants.}
{207}{}{Sound's good.}
{208}{}{I need to take another look at what you have for sale.}
{209}{}{}

{210}{}{Hello, mutie. How're you doing?}
{211}{}{Hello, green guy. What do you need this time?}
{212}{}{Hello, you damn mutant. Sorry, but we're out of spare arms and legs. Ha-ha, just kidding.}
{213}{}{Hello, freak. How are you feeling today?}
{214}{}{What do you want? Make your choice and get out.}
{215}{}{Lookin' for something?}
{216}{}{Tell me what you're looking for. Nothing's too good for you.}
{217}{}{I need to buy some stuff.}
{218}{}{Goodbye.}

{220}{}{Some ghoul with rebar sticking out of his head asked me to fix this.}
{221}{}{Is that all? Alright, hand it over...}
{222}{}{Here you go.}
{223}{}{Actually, I want to try to fix it myself...}
{1223}{}{Actually, I want to try to fix it myself...}
{224}{}{I don't like that he's dealing with you. But since you're here, I'll have to help. Gimme that thing...}
{225}{}{Done. Be careful not to break it, it's delicate.}
{226}{}{Alright. Thanks.}
{227}{}{You don't have to tell me that.}

{230}{}{I have a holodisk with an old movie. Can you make a copy?}
{231}{}{Ah, feeling guilty, huh? Sure, stealing something important from an autistic person and then walking around without a care requires a real lack of morals. But why should I do as you say instead of just returning the disk to its rightful owner?}
{232}{}{I need a copy so I can return the original to him. Can you grasp that?}
{233}{}{Oh, that changes things. Alright. I'll make a copy for }
{234}{}{ caps. Pay up front.}
{235}{}{Wait a bit, I'll get the caps.}
{236}{}{Then do it. Here's the caps and the disk.}
{237}{}{You received a copy of the holodisk.}

{250}{}{I want to upgrade my weapon.}
{251}{}{Well, first show me your weapon.}
{252}{}{Hmm, I don't think I can do anything with that.}
{253}{}{[}
{254}{}{ for }
{255}{}{]}
{256}{}{There you go. Do you want to upgrade anything else?}
{257}{}{No. Thanks.}
{258}{}{Yes, maybe...}
{259}{}{Be honest: you can't afford it, can you?}
{260}{}{Oops.}

