{200}{}{Enter command:}
{201}{}{End session}
{202}{}{Back}
{203}{}{Next}
{204}{}{This system is too complicated for you.}
{205}{}{It would be nice to find a manual... or an instructor.}
{206}{}{Knowledge is needed here.}
{207}{}{Now you know what to do.}
{208}{}{Hey, it's not that hard!}
{209}{}{This technology is too complex. You need to study it thoroughly.}

{210}{}{System status check.}
{211}{}{First turbine status.}
{212}{}{Turbine 1: no signal.}
{213}{}{Turbine 1: active.}
{214}{}{Second turbine status.}
{215}{}{Turbine 2: no signal.}
{216}{}{Turbine 2: active.}
{217}{}{Substation check.}
{218}{}{Substation: no response. }
{219}{}{Substation: operational. }
{220}{}{Direct power to the substation.}
{221}{}{Done.}
{222}{}{Substation not responding.}
{223}{}{Turn on the lighting in the machine room.}
{224}{}{Turn off the lighting in the machine room.}
{225}{}{Turn on the lighting in the control center.}
{226}{}{Turn off the lighting in the control center.}
{227}{}{Open the door to the warehouse.}

