{100}{}{Now you can descend into the darkness below.}
{101}{}{It's hard to say why there is no ladder here. But there isn't one.}
{102}{}{You can't fix something that doesn't exist. This ladder needs a replacement.}
{103}{}{A deep ventilation shaft is visible behind the grate.}
{104}{}{There's nothing to repair here. On the contrary, the hole in the grate might come in handy.}
{105}{}{This bridge can't be repaired anymore. But you can descend from here if you tie a sturdy rope to the rail tie.}
{106}{}{You can't do anything here with bare hands.}
{107}{}{Now you can go down.}
{108}{}{You can descend here if you have a long and strong enough rope.}
