{100}{}{You see the monorail substation.}
{101}{}{This is the monorail's electrical substation. Wires from it extend towards the monorail track.}
{102}{}{This is the monorail's electrical substation. You have no idea why you might need it.}
{103}{}{It looks like this is the substation that should power the monorail track.}
{104}{}{The electricity has already been directed to the monorail track.}
{105}{}{The power to the monorail track has been restored.}
{106}{}{This substation is dead. No electricity is coming to it from the power station.}
