{100}{}{You see a patrolman.}
{101}{}{You see a private in typical military gear.}

{110}{}{¡Un intruso!}
{111}{}{Veo al intruso!}
{112}{}{Eres gringo, no?}
{113}{}{Bienvenido a Mexico!}
{114}{}{Que buscas aqui?}
{115}{}{Vienes del norte?}
{116}{}{Esto es Nuevo Mexico.}
{117}{}{Esta es nuestra tierra!}
{118}{}{Guarda tus armas!}
{119}{}{No nos caen bien los gringos.}
{120}{}{Quien eres?}

{210}{}{«Intruder!»}
{211}{}{«I see an intruder!»}
{212}{}{«You a yankee?»}
{213}{}{«This is Mexican territory.»}
{214}{}{«What are you looking for?»}
{215}{}{«Did you come from the north?»}
{216}{}{«This is New Mexico.»}
{217}{}{«This is our land!»}
{218}{}{«Holster your weapon.»}
{219}{}{«We don't need outsiders around here.»}
{220}{}{«Who the hell are you?»}
