{101}{}{This machine is perfect for brewing alcohol.}
{102}{}{This machine is great for making alchohol, but it needs a refill first.}
{103}{}{Making booze during a fight? That's not happening.}

{110}{}{To make tequila, you need to load the machine with raw materials.}
{111}{}{It's not as easy as it looks. You'll need to learn the recipe first.}
{112}{}{You've refilled the machine. Time for some wasteland chemistry to brew that tequila.}
{113}{}{The machine is fully loaded. No more raw materials will fit.}
{114}{}{Pour the raw stuff directly into the machine's container.}
{115}{}{Your wasteland tequila is ready and waiting to be bottled.}
{116}{}{You've got }
{117}{}{ bottles of tequila ready to go.}
{118}{}{Something's still missing...}

{120}{}{The machine is in good working order and doesn't need any repairs.}
{121}{}{Locking all these bottles in place takes some serious engineering. Why are you the only one who figured this out?}
{122}{}{The machine's been destroyed. That's a major loss for the local booze supply.}
{123}{}{Uh-oh...}
