#include "..\headers\define.h"
//---------------------

#define NAME                            SCRIPT_BCFortun
#define TOWN_REP_VAR                    GVAR_TOWN_REP_SAN_BRAHMIN // привязка к репутации (-1, если не нужно)

#define NUM_TEAM                        TEAM_SANBRAHMIN_PEASAN // группа, к которой принадлежит персонаж (-1 если нужно оставить Team, заданный в редакторе)
#define NUM_AI                          AI_CULT_BRAHMIN       // AI персонажа (-1 если нужно оставить AI, заданный в редакторе)
#define KILL_SLAVA                      SLAVA_KILL_GOOD       // слава за убийство этого персонажа (SLAVA_KILL_GOOD, SLAVA_KILL_BAD, SLAVA_KILL_NEITRAL, SLAVA_KILL_CHILD)
#define KILL_TOWN_REP                   REP_KILL_CRITICAL     // репутация за убийство этого персонажа (-100 для враждебности всего поселения)
#define KILL_FRAC_REP                   FRAC_NON              // принадлежность определенной фракции (-1, если не нужно)

#define FLAG_STEAL                      30 // Нижний порог навыка для кражи (для торговцев 200, для животных 300)
#define FLAG_ALCOHOL                    1  // Примет ли алкоголь от ГГ: 0 - принимает, 1 - не принимает
#define FLAG_FOOD                       1  // Примет ли пищу от ГГ: 0 - принимает, 1 - не принимает

//---------------------

procedure start;
procedure map_enter_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure timed_event_p_proc;
procedure critter_p_proc;
procedure use_obj_on_p_proc;
procedure use_skill_on_p_proc;
procedure pickup_p_proc;
procedure combat_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure talk_p_proc;

procedure Node998;
procedure Node999;
procedure NodeStartDialog;
procedure NodeFstDialog;
procedure NodeFstDialog101;
procedure NodeFstDialog102;
procedure NodeFstDialog103;
procedure NodeFstDialog104;
procedure NodeFstDialog105;
procedure NodeFstDialog106;
procedure NodeFstDialog107;
procedure NodeFstDialog108;
procedure NodeSndDialog;
procedure NodeAnswer100;
procedure NodeAnswer101;
procedure NodeAnswer102;
procedure NodeAnswer103;

//---------------------

//#define LVAR_Flag_A                     (6) // отвечает за ...

//---------------------



procedure start begin
end

procedure map_enter_p_proc begin
   if (is_loading_game == false) then begin
       set_start_home
   end
end

procedure look_at_p_proc begin
   lookProcMsg
end

procedure description_p_proc begin
   dsrptProcMsg
end

procedure timed_event_p_proc begin
   // Таймер за номером 1 рарезервирован под перемещение персонажа по локации
   // Таймер за номером 2 рарезервирован под всплывающие реплики
   if (fixed_param == 1) then begin
       timer_move_to_home
   end
   if (fixed_param == 2) then begin
       //timer_float_reply(110,119)
   end
end

procedure critter_p_proc begin
   set_critter_options(1,0) //условие нападения (0 личная вражда, 1 вражда клановая, 2 всегда), разворот к ГГ
end

procedure use_skill_on_p_proc begin
   skillUseSteal
   skillUseFAid
end

procedure pickup_p_proc begin
   pickupProcCritter
end

procedure use_obj_on_p_proc begin
   UsedItemToCrit_Proc
end

procedure combat_p_proc begin
   effectAttak(0,0,0,0,0) //отравление min, облучение min, травма ног %, травма рук %, травма глаз %
end

procedure damage_p_proc begin
   set_damage_dude
end

procedure destroy_p_proc begin
   kill_critter_opt
end

procedure talk_p_proc begin
   setReaction(0) // Отношение к ГГ(1 - персонаж положительный, -1 отрицательный, 0 нейтральный)
   dialog_proc(0,0,NodeStartDialog,-1,-1)
end

procedure Node998 begin
   set_enemy_dude;
end

procedure Node999 begin
end

procedure NodeStartDialog begin
   if (bitDialog(bit_1) == 0) then begin
   call NodeFstDialog;
   end
   else if (bitDialog(bit_2) == 0) then begin
   call NodeFstDialog108;
   end
   else begin
   call NodeSndDialog;
   end
end

//--- FIRST DIALOGUE

procedure NodeFstDialog begin
   bitDialogExp(bit_1,0)
   zReply(200)
   NAnswer(201,4,NodeFstDialog101)
   NAnswer(230,-3,NodeFstDialog101)
end

procedure NodeFstDialog101 begin
   Reply(202)
   NAnswer(206,4,NodeFstDialog102)
   NAnswer(205,4,Node999)
   NAnswer(206,-3,NodeFstDialog102)
   NAnswer(203,-3,Node999)
end

procedure NodeFstDialog102 begin
   Reply(207)
   NAnswer(209,4,NodeFstDialog103)
   NAnswer(231,-3,NodeFstDialog103)
   NAnswer(208,4,Node999)
   NAnswer(203,-3,Node999)
end

procedure NodeFstDialog103 begin
   Reply(210)
   if (item_amnt(dude_obj,PID_BOOTLE_CAPS)>=100) then begin
   NAnswer(211,4,NodeFstDialog104)
   NAnswer(232,-3,NodeFstDialog104)
   end
   NAnswer(212,4,Node999)
   NAnswer(203,-3,Node999)
end

procedure NodeFstDialog104 begin
   bitDialogExp(bit_2,100)
   item_remove(dude_obj,PID_BOOTLE_CAPS,100)
   PLAY_FADE
   /*
   Some players have suggested that Luck could be randomly increased or decreased here, similar to the Hubologist in NCR in F2.
   */
   Reply(213)
   NAnswer(214,4,NodeFstDialog105)
   NAnswer(233,-3,NodeFstDialog105)
end

procedure NodeFstDialog105 begin
   if ((getQuest(GVAR_GAME_END) != qZero) or (getQuest(GVAR_RANGERS_DUMB_DESTROY) >= qEnd) or (getQuest(GVAR_PUERTO_BOS_DESTROY) >= qEnd) or (getQuest(GVAR_MAIN_QUEST_SYNOD_VILLA) >= qEnd)) then begin
   Reply(226)
   zBAnswer(221,4,Node999)
   NAnswer(227,-3,Node999)
   end
   else begin
   Reply(215)
   NAnswer(216,4,NodeFstDialog106)
   NAnswer(233,-3,NodeFstDialog106)
   end
end

procedure NodeFstDialog106 begin
   Reply(217)
   NAnswer(218,4,NodeFstDialog107)
   BAnswer(219,4,NodeFstDialog107)
   NAnswer(231,-3,NodeFstDialog107)
end

procedure NodeFstDialog107 begin
   Reply(220)
   zBAnswer(221,4,Node999)
   NAnswer(222,4,Node999)
   NAnswer(234,-3,Node999)
end

procedure NodeFstDialog108 begin
   zReply(223)
   NAnswer(209,4,NodeFstDialog103)
   NAnswer(224,4,Node999)
   NAnswer(231,4,NodeFstDialog103)
   NAnswer(203,-3,Node999)
end

//--- REPEAT DIALOGUE

procedure NodeSndDialog begin
   Reply(240)
   NAnswer(242,4,NodeFstDialog107)
   NAnswer(243,4,NodeAnswer100)
   NAnswer(241,4,Node999)
   NAnswer(235,-3,Node999)
end

procedure NodeAnswer100 begin
   Reply(244)
   NAnswer(245,4,NodeAnswer101)
   NAnswer(247,4,NodeAnswer102)
   NAnswer(251,4,NodeAnswer103)
   NAnswer(241,4,Node999)
end

procedure NodeAnswer101 begin
   Reply(246)
   NAnswer(247,4,NodeAnswer102)
   NAnswer(251,4,NodeAnswer103)
   NAnswer(241,4,Node999)
end

procedure NodeAnswer102 begin
   Reply(248)
   NAnswer(245,4,NodeAnswer101)
   NAnswer(251,4,NodeAnswer103)
   NAnswer(241,4,Node999)
end

procedure NodeAnswer103 begin
   if (getQuest(GVAR_BRAHMIN_QST_GERONIMO) >= qEnd) then begin
   Reply(250)
   end
   else begin
   Reply(252)
   end
   NAnswer(245,4,NodeAnswer101)
   NAnswer(247,4,NodeAnswer102)
   NAnswer(241,4,Node999)
end
