#include "..\headers\define.h"
#define NAME                    SCRIPT_BSZaval

procedure start;
procedure map_enter_p_proc;
procedure use_p_proc;
procedure use_obj_on_p_proc;
procedure use_skill_on_p_proc;
procedure obval_proc;

import variable obj_critter_a; // указатель на криттера 1



procedure start begin
end

procedure map_enter_p_proc begin
end

procedure use_p_proc begin
   script_overrides;
   call obval_proc;
end

procedure use_obj_on_p_proc begin
   stopUseCarGaz
end

procedure use_skill_on_p_proc begin
   if (action_being_used == SKILL_TRAPS) then begin
      script_overrides;
      display_mstr(112);
   end
   if (action_being_used == SKILL_REPAIR) then begin
      script_overrides;
      display_mstr(112);
   end
   if (action_being_used == SKILL_SCIENCE) then begin
      script_overrides;
      display_mstr(112);
   end
end

procedure obval_proc begin
   variable damageAmnt; // размер урона
   damageAmnt := 0;

   //--- Определение урона
   if (obj_critter_a > 0) then begin
       if (tile_distance_objs(self_obj,obj_critter_a)<=4) then begin
       damageAmnt := get_critter_stat(obj_critter_a,STAT_max_hit_points)/5;
       damageAmnt += random(1,10);
       end
   end

   //--- Нанесение урона
   if (damageAmnt > 0) then begin
      play_sfx("ORE1");
      display_mstr(111);
      if (get_critter_stat(obj_critter_a,STAT_current_hp)>0) then begin
      critter_dmg(obj_critter_a, damageAmnt, (DMG_normal_dam BWOR DMG_BYPASS_ARMOR));
      end
      set_obj_visibility(self_obj, 1);
      destroy_object(self_obj);
   end
   else begin
      display_mstr(112);
   end
end
