{100}{}{You see a pueblo resident.}
{101}{}{You see a dark-skinned pueblo resident dressed in brahmin leather.}

{110}{}{Sandstorm comes.}
{111}{}{Next season will be hot.}
{112}{}{My brahmin got skinny.}
{113}{}{We need to take more water next time we graze.}
{114}{}{Staying in the nest is more dangerous now.}
{115}{}{This pueblo has always been ours.}
{116}{}{We must protect our families from raiders.}
{117}{}{Divine Brahmin, protect us from strangers!}
{118}{}{We must obey our leaders.}

{130}{}{Old Mangas will doom everyone.}
{131}{}{But old man Mangas warned us...}
{132}{}{Genaro will probably say to ally with Phoenix.}
{133}{}{Genaro died, he was best trader with strangers.}
{134}{}{Nana cares for tribe like woman and leader.}
{135}{}{Nana was killed by missionaries. Who else could do this?}
{136}{}{I worry about future of Chatto and his friends.}
{137}{}{We have not seen Chatto for long time...}
{138}{}{Chatto still young but already a leader. Yes, strange times.}
{139}{}{Chief Geronimo knows what is right for tribe.}
{140}{}{Geronimo... May the Sun always light your paths.}

{150}{}{The day has come. Phoenix has taken our tribe.}
{151}{}{The Phoenix missionaries have done their job.}
{152}{}{The High Chief makes his decision. We must obey.}
{153}{}{What about the pueblo? Must we leave?}
{154}{}{It is time for quail to leave her nest.}
{155}{}{Anyway, I am glad war is over.}
{156}{}{I hope Rangers keep their word.}
{157}{}{I pray to the spirits of Wasteland for war to end.}
{158}{}{O Divine Brahmin, show us wise way!}
{159}{}{Dark Brahmin's games led our tribe into dry pastures.}

{170}{}{You should not go to Buried City alone.}
{171}{}{So that is why elders said not to go into catacombs?}
{172}{}{There was a real monster in catacombs.}
{173}{}{Glory to the Divine Brahmin! The evil spirit is gone.}
{174}{}{No wonder people say bad things about Buried City.}
{175}{}{I am still afraid to go near Buried City.}
