{100}{}{You see a newcomer.}
{101}{}{You see a man in dusty clothes who appears to have journeyed miles in them.}
{102}{}{Impressive. Tinsmiths are known for their skill, but I never imagined this...}
{103}{}{What's the deal with this cursed town?}
{104}{}{...}

#First meeting
{200}{}{Well, well. If it isn't you. What a surprise to see you here.}
{201}{}{And you are...}
{202}{}{Remember that letter you brought me in Phoenix? Caught me off guard. Thought it was some kind of scam. Turns out, I was wrong.}
{1202}{}{Remember that letter you brought me in Phoenix? Caught me off guard. Thought it was some kind of scam. Turns out, I was wrong.}
{203}{}{Alright, spill it. What brings you to this godforsaken town?}
{204}{}{}
{205}{}{}
{206}{}{There's an abandoned bathhouse right in the center. I'm on the hunt for its owner.}
{207}{}{A bathhouse? Here in the desert?}
{208}{}{Yep, plenty of water in this city. Draws in caravans from all over. Though not everyone gets a sip.}
{209}{}{Why the search for the owner?}
{210}{}{He's family. Got a letter inviting me to come work there. So, here I am. But he's vanished.}
{211}{}{Just like that, you up and left for a foreign city?}
{212}{}{Why not? Things went south real quick in Phoenix after that damn explosion.}
{213}{}{Explosion? What's the story?}
{214}{}{You serious? Whole Route 10's buzzing about it. The Cathedral of Fire went up in flames. Literally.}
{215}{}{Well well... Any leads on your uncle from the locals?}
{216}{}{Locals ain't got a clue. Bathhouse's shuttered, owner's a ghost. Talked to the mayor, got branded a con and tossed out on my ass.}
{217}{}{So, what's the plan now?}
{218}{}{Beats me. Hanging around a bit longer, hoping my Uncle decides to show. If you hear anything, give me a holler, alright? I'll be in your debt.}
{219}{}{Best of luck with the search.}
{220}{}{Yeah.}
{221}{}{Later.}
{222}{}{Must be some mix-up.}
{223}{}{Doubt it.}
{224}{}{Keep living the dream.}
{225}{}{Or maybe you're just posing as kin to slide into his spot?}
{226}{}{Rubbish. Haven't crossed paths in ages. My uncle himself sent that letter via couriers, check the records. Plus, it was you who handed me his note.}
{1226}{}{Rubbish. Haven't crossed paths in ages. My uncle himself sent that letter via couriers, check the records. Plus, it was you who handed me his note.}

# Repeated dialogue at the parking lot
{250}{}{Well, well, if it isn't you again. Was just mulling over our chance encounter. Two strangers in one city, huh? Better stick together, don't you think?}
{251}{}{Seems a bit far-fetched. Later.}
{252}{}{Sure thing. Catch you later.}
{253}{}{By the way, what's your name?}
{254}{}{Just call me Steve.}
{255}{}{Got it, Steve. So, what's your story again?}
{256}{}{Later, Steve.}
{257}{}{Remind me, who exactly are you looking for?}

# Stage 1
{260}{}{Been to the local cemetery? Looks like your uncle's resting there.}
{261}{}{What? Is he... dead? Now I get why the mayor's been trying to give me the run around. But how did this happen?}
{262}{}{Based on those mass graves, looks like a lot of folks met their end here. Know anything about it?}
{263}{}{Well, word is there were some clan wars not too long ago. That's why the locals clam up when you poke around about the past. If my uncle got caught up in that mess, guess I'll have to accept it.}
{264}{}{Planning to leave empty-handed?}
{265}{}{Hell no. That bathhouse was my uncle's. And I'm his kin. Shouldn't I be inheriting it?}
{266}{}{You serious? After all the threats, you're sticking around?}
{267}{}{You see... Truth is, things weren't looking too good in Phoenix either. I was desperate, scraping by with fight money. But here? I can breathe life back into my uncle's business and make a killing. Why the hell would I pass up that chance?}
{268}{}{Ah, gotcha. Your relative's death's quite the stroke of luck, ain't it?}
{269}{}{What's that supposed to mean? I'm reviving my uncle's business and getting wealthy. Be foolish to let this opportunity slide.}
{270}{}{Okay, well, it's not a bad idea. Worth a shot. Need a partner?}
{271}{}{Taking quite the gamble there, partner.}
{272}{}{Well, key now's winning over the mayor. He's been avoiding me like the plague; security won't let me near him. Could you talk to him?}
{273}{}{What's in it for me if I do?}
{274}{}{Naturally, everyone's out for a buck. Don't fret; I'll pay up once I'm rolling in it. We're in this together. Just gotta be patient a little while longer.}
{275}{}{I'll see what I can do with the mayor.}
{276}{}{Appreciate it, partner. What would I do without you?}
{277}{}{Catch you later.}
{278}{}{Talking to that tyrant's a scary thought. Find someone else.}
{279}{}{Got it. No worries, I'll figure something out. Thanks for the offer anyway.}
{280}{}{Later.}
{281}{}{Just passing through; don't have time to wait for my first clients.}

# Stage 2
{300}{}{So, what did the mayor say? Did you manage to talk to him?}
{301}{}{Nope, didn't get a chance. Hang tight.}
{302}{}{The Mayor's croaked. Bathhouse is yours for the taking now.}
{303}{}{Dead? Damn, what's up with this city? Okay, spare me the details. But you're right - I gotta stake my claim on that bathhouse before someone else swoops in.}
{304}{}{Got it, I'll meet you there...}
{305}{}{The mayor's given you the green light for the bathhouse. You're in business.}
{306}{}{Your negotiation skills are impressive. Now let's secure that bathhouse before the mayor has a change of heart.}
{307}{}{Got it, I'll meet you there...}
{308}{}{Mayor's ordering you out of town. Now.}
{309}{}{Huh? What's gotten into you? Are you siding with him? Can't you see this isn't fair? That bathhouse is rightfully mine. And it's sitting empty now, isn't it?}
{310}{}{My bad. I'll try to get through to the mayor on this.}
{311}{}{If you value your hide, you'll skedaddle right now.}
{312}{}{Well, that's it. Thought we were gonna be partners. Turns out you're just another corrupt asshole.}
{1312}{}{Well, that's it. Thought we were gonna be partners. Turns out you're just another corrupt bitch.}
{313}{}{We'll hash this out later. But for now, you'd better just move on.}
{314}{}{I ain't joking. Get out of town.}
{315}{}{I'm not budging. This bathhouse is my family's legacy, and I ain't abandoning it.}
{316}{}{You're leaving me no choice. If you won't leave willingly, I'll make you.}
{317}{}{Suit yourself.}
{318}{}{Listen up. I'll count to five, then I'm drawing my gun. One... two...}
{319}{}{Hey, hey, hold on...}
{320}{}{...three.}
{321}{}{Alright, alright, it's just a prank. Stay, it's your problem.}
{322}{}{Fine, fine, I'm outta here. Look.}
{323}{}{And don't even think about coming back.}

{330}{}{Look at what the locals have done to this once wonderful establishment. Dirty savages.}
{331}{}{I'll take a look around, if you don't mind.}
{332}{}{What seems to be the problem?}
{333}{}{If you ignore the fact that everything valuable was stolen from here, then the real problem lies in the water heating system.}
{334}{}{It's not working?}
{335}{}{Someone tried to pilfer the tank, but while mucking about, they knocked it over and damaged it. I haven't figured out how to fix it yet.}
{336}{}{Well, best of luck. Count me out on that one.}
{337}{}{Let me have a look. I might be able to patch up this beast with some scrap metal.}
{338}{}{The tank is good as new. You can heat the water and have a wash.}
{339}{}{You managed to repair it? Outstanding! Business is bound to pick up now. Thanks for your help. Swing by if you need a quick refreshment.}
{1339}{}{You managed to repair it? Outstanding! Business is bound to pick up now. Thanks for your help. Swing by if you need to freshen up.}
{340}{}{I'll remember that.}

{350}{}{How are you?}
{351}{}{Feeling a bit grimy? Fancy a shower?}
{352}{}{Up for a shower? I just found some old sea salt.}
{353}{}{How about a shower? It's scorching outside.}
{354}{}{You are in desperate need of a wash. Don't be shy, I won't overcharge you.}
{355}{}{The bath is free. Dive in, it's time to scrub off that road grime.}
{356}{}{Catch you later, Steve.}

#Rest
{400}{}{I need to wash off this dust and filth. What's the cost for a shower?}
{401}{}{Just firewood and water. It'll be }
{402}{}{ caps.}
{403}{}{Can't afford it right now. Maybe next time.}
{404}{}{Sounds fair. Gimme a sec...}

{410}{}{By now, your business should be thriving.}
{411}{}{It's not always booming. Caravans come and go, so there are quiet periods. Not everyone splurges on such luxuries. But it's enough to get by.}
{412}{}{What about our deal?}
{413}{}{I'm running out of patience. Where's my cut of the profits?}
{414}{}{What are you on about? I don't owe you anything. Now scram, you're blocking my tub cleaning time.}
{415}{}{What?}
{416}{}{You're a real piece of work.}
{417}{}{Sure thing, partner. Kept a portion of the profits just for you. Here, 200 caps. Now if you'll excuse me, this tub isn't going to clean itself.}
{418}{}{Thanks, pleasure doing business with you. Enjoy, Steve.}
{419}{}{Is that it? Your business is lackluster, Steve. And spruce up that sign. It's an eyesore.}
{420}{}{If you won't hand over the caps willingly, I'll take them by force. Hold steady, you scammer...}

{430}{}{The Tinsmiths had a representative here. Any idea what that was about?}
{431}{}{Saw the Tinsmith, but he kept to himself, headed straight for the mayor's. Didn't see him after that.}
{432}{}{At least that's something. So long.}
{433}{}{A lot of help you were. So long.}
