{100}{}{You see Christina.}
{101}{}{You see the daughter of Count Bustos.}
{102}{}{If the highwaymen see us, they'll probably shoot us.}
{103}{}{I'm so glad it's over.}
{104}{}{*Crying*}

#First dialogue
{200}{}{Stay away from me, you filthy raider!}
{201}{}{Calm down. Your father sent me.}
{202}{}{My... dad? Daddy... Let's get out of here, quickly.}
{203}{}{I'll untie you... Let's go, but quietly.}
{204}{}{We shouldn't be noticed. If the robbers see us, they'll probably shoot us.}
{205}{}{Okay, let's go.}
{206}{}{Now's not the time. You'll have to wait a little longer.}
{207}{}{What? Are you leaving me? Untie me now!}
{208}{}{Be patient. I'll be back soon.}
{209}{}{Come on, we can go now.}

#Re-dialogue
{210}{}{Hello.}
{211}{}{Bye.}
{212}{}{You're free. I managed to negotiate with the raiders.}
{213}{}{Really? Then let's go quickly, before they change their minds.}
{214}{}{Sure, let's go.}
