{100}{}{You see a local resident.}
{101}{}{You see an emaciated townsperson. He looks quite unfriendly.}

{110}{}{I don't care about you.}
{111}{}{He got what he deserved.}
{112}{}{*Ignores you*}
{113}{}{Damn it all.}
{114}{}{Sorry. I don't know what came over me.}

{120}{}{Again? I told you - no water without...}
{121}{}{Shut up. You TOOK the water from the residents.}
{122}{}{What are you talking about? You should watch your mouth...}
{123}{}{Give me some water. Right now.}
{124}{}{Get out of my shack, motherfucker.}
{125}{}{Bastard, I'll smash your fuckin' head in!}
{126}{}{Hey, what are you up to? Get lost, asshole!}
{127}{}{. . .}
{128}{}{ }

{200}{}{I swear, I'll bash this fat guy's head in if he doesn't give me water!}
{201}{}{You wouldn't really do that, would you?}
{202}{}{Stay out of it, stranger. You have no idea how much blood was spilled for this water pump. They stole it from us! Now they demand payment for our own water! (yells past you) Give me water, you bastard!}
{203}{}{Okay, not my problem. Do whatever you want.}
{204}{}{I'm not letting you swing that sledgehammer around like a maniac. Walk away.}
{205}{}{Calm down. It's not worth losing your life over.}
{206}{}{Sacrifices? What do you know about sacrifices? People died by the dozens for this damned water. I've got nothing left to lose. Outta my way, scum!}
{207}{}{Hand over the sledgehammer. Now.}
{208}{}{Okay, give him what he deserves.}
{209}{}{Take a deep breath, man. It's not worth it.}
{210}{}{Sacrifices? What do you know about sacrifices? People died by the dozens for this damned water. I've got nothing left to lose...}
{211}{}{Alright, if you say so. Go ahead and give him hell.}
{212}{}{That's all in the past. No need for more bloodshed.}
{213}{}{(looks around confused, then at his sledgehammer) God... I think I've lost my mind. I need to clear my head.}
{214}{}{Yeah, you really do.}

