{100}{}{You see a settler.}
{101}{}{You see one of the cafe regulars.}
{102}{}{Best skedaddle, 'fore I change my mind about lettin' you walk outta here.}
{103}{}{Hmm, there's something fishy about this family.}
{104}{}{Well now, ain't he a juicy lookin' one? Darlin', go on an' fetch the carvin' knife.}
{105}{}{That takes care of the filth here.}
{106}{}{You should have treated your guests better.}

{200}{}{Heh, looky here, a traveler from the wilds! Mighty fine seein' a fresh face 'round these parts. Now, where ya from, stranger?}
{201}{}{A small village, far from here.}
{202}{}{None of your business. Is that clear?}
{203}{}{We been here a long time, y'see. Got plenty o' room if ya need a place to stay. Got pies on the stove too. Won't hurt ya to sit a spell, reckon you'll find 'em right tasty.}
{204}{}{Um, I'll think about it.}

{210}{}{Now, what can we do fer ya?}
{211}{}{I'm just looking around.}
{212}{}{Can I look around here?}
{213}{}{Well, sure thing, but steer clear of the back room. That there's our private territory.}
{214}{}{Understood, no problem.}
{215}{}{That sounds ominous. Duly noted.}
{216}{}{How do you manage to survive amidst this scorched desert?}
{217}{}{Oh, we make do just fine. Got ourselves lizards, scorpions, other critters. And the wasteland's got more than you'd think, if ya know where to dig. Sometimes wanderers leave behind little treats, like bullets. Keeps us goin' well enough.}
{218}{}{Do you live here alone?}
{219}{}{Ain't always been alone. Mama and Papa were with us once, 'til the desert took 'em. Every now an' then, we get company - travelers, caravanners. Reckon they get curious 'bout the pies.}
{220}{}{Genuine hospitality is a rarity these days.}
{221}{}{That it is. Ain't much trust left out here. But we hold to our own ways. We don't judge, and we sure don't deceive.}
{222}{}{This cafe looks very old. How long have you lived here?}
{223}{}{Been in the family longer than I can recall. This ol' cafe's got history, tales seeped into every splinter and crack.}
{224}{}{What is so important in your back room?}
{225}{}{Just our own private space, personal stuff, you know. Place where we lay our heads, where we keep things... quiet. Outsiders best keep their noses out. That's all we ask.}
{226}{}{Do you have anything to barter?}
{227}{}{Got somethin' worth tradin'? Look around, see if there's somethin' that strikes ya fancy. What d'ya need?}
{228}{}{Do you take bottle caps?}
{229}{}{Caps? Bah, what kinda fool's game is that? Tossed 'em away like trash years ago. Don't waste my time.}
{230}{}{Can we talk about something else?}
{231}{}{Anythin' else on your mind?}
{232}{}{Nothing, I'm going to take a rest.}

{250}{}{Well, well... shoulda plugged ya from the get-go. Always told my sis, "Don't go flappin' yer gums with strangers."}
{251}{}{Remember when I said I don't trust friendly folk in the wasteland? Well, I was right.}
{1251}{}{Remember when I said I don't trust friendly folk in the wasteland? Well, I was right.}
{252}{}{Ain't hard to understand, is it? This here desert's empty as a crow's belly - no crops, no critters, nothin' but the dust. Every poor soul who wanders by is a lifeline 'round here.}
{253}{}{Then why not get out of this hell? There are whole cities out there...}
{254}{}{Pffft! Cities? Hah! Just stories, spun by folks who ain't never been outta their own dusty holes. Leavin' this ol' cafe for some cockamamie tale is a fool's errand. No sir, we're stayin' right here.}
{255}{}{Then you're just a fool.}
{256}{}{Maybe I am, but this fool's survived more than a hundred o' your kind. And I'll be here long after you're gone.}
{257}{}{Hey...}
{258}{}{Exactly. You had your chance. Too late now, idiot...}
{1258}{}{Exactly. You had your chance. Too late now, stupid...}
{259}{}{So how do you survive in this barren desert? Snatch up travelers and turn them into kebabs?}
{260}{}{Then this conversation's got one outcome. Your death.}
{261}{}{Enough talk. I'm cleansing the wasteland of monsters like your family.}
{262}{}{Hold on. You're making a grave error...}
{263}{}{Hold up. I'm being honest. There are big cities out there in the wastes. Plenty of space for your family too. Living in the desert's just a slow death sentence.}
{264}{}{Cities, huh? Folks keep yammerin' 'bout those. Maybe there's somethin' to it... Reckon you could show me? Prove it?}
{265}{}{Fine, but after this, you let me go. Agreed?}
{266}{}{Forget it. Your kind's got no place in civilization.}
{267}{}{Well, well... what do we have here? A lil' sneak, huh? Reckon in the cities they cut hands off for stealin'. Might just try it myself. Bet that'll hurt somethin' fierce.}
{268}{}{Rot in hell, you vile cannibal.}
