{100}{}{You see Frank.}
{101}{}{You see a vault dweller. He looks notably fresh and clean compared to any wastelander.}

{200}{}{P-please don't hurt us! We're peaceful people and don't want any trouble.}
{201}{}{Why are you afraid of me? I haven't done anything wrong.}
{1201}{}{Why are you afraid of me? I haven't done anything wrong.}
{202}{}{Then stop whining, it's getting on my nerves.}
{203}{}{So... you're not a raider?}
{204}{}{No, I'm }
{205}{}{. And who are you?}
{206}{}{I'm Frank. Since the overseer passed away, I've been in charge here. And, honestly, it's been rough.}
{207}{}{Why's that?}
{208}{}{This old Vault is falling apart. The life support system is failing, the generator is barely running. And we don't know how to fix it.}
{209}{}{Sounds like a real disaster.}
{210}{}{Hmph. Glad it's not my problem.}
{211}{}{And to make it worse, there are raiders camped outside. They've tried breaking in a dozen times over the past few months, hoping to take the vault. The only thing stopping them is the main vault door, but with everything going wrong inside, we might have to go out soon just to avoid suffocating. I'm terrified of what they'll do to us. They already got Fred, and they're probably torturing him right now.}
{212}{}{How can I help you?}
{213}{}{I'm in the business of solving problems, but not for free, of course.}
{214}{}{You'd really help us? That would be incredible. We need to fix the generator and get the computer going so we can restart life support.}
{215}{}{Alright, I'll see what I can do.}
{216}{}{Stand back and watch a professional at work.}

{220}{}{Have you managed to restore the vault's generator yet? It doesn't sound like anything's changed. We need to fix the generator and get the computer going so we can restart life support.}
{1220}{}{Have you managed to restore the vault's generator yet? It doesn't sound like anything's changed. We need to fix the generator and get the computer going so we can restart life support.}
{221}{}{Time to get down to business. See you.}

{230}{}{Where's the generator room?}
{231}{}{The generator room is at the end of the corridor, to our left. But it's no use tying to get in without tools. The door's sealed.}
{232}{}{Bye.}
{233}{}{Where's the computer room?}
{234}{}{The computer room is down the hall to the right. But the computer won't function without electricity.}
{235}{}{How do we restore life support?}
{236}{}{Once we've started the generator, we can just use the computer to re-activate the life support system. Then, all that's left is to repair the floating eye bot to patrol the vault and keep our enemies out.}
{237}{}{Tell me about this vault.}
{238}{}{It was built like, a hundred years ago. Our ancestors survived the Great War here. But now, it's no can't really support us anymore. We only retreat here when there's a threat looming.}

{240}{}{Thanks for getting the life support system up and running. We're already feeling better!}
{241}{}{No problem.}
{242}{}{Glad to hear it.}
{243}{}{Anything else?}
{244}{}{We don't have much in the way of useful items. Here, take this jumpsuit. It's a bit worn, but it still holds up well against the elements.}
{245}{}{We don't have much in the way of useful items. Here, take this water flask. The overseer swore by it, said it brought him luck during his desert travels. With it, he never ran out of water, even in the hottest, driest places.}
{246}{}{Thanks for that.}
{247}{}{Are you kidding me? A measly flask for all this effort? Forget it! Take off your jumpsuit and make it worth my while!}
{248}{}{Alright, alright! I don't know how I'll manage without it... Here, take it.}
{249}{}{And wipe that pitiful look off your face. It's fair compensation for all the help I gave you.}
