{100}{}{You see a bar patron.}
{101}{}{You see a regular at the bar. This girls's always up for a chat over a stiff drink.}

{200}{}{Hey there, how's it going?}
{201}{}{Catch you later.}
{202}{}{Hey, buddy. Feeling generous today? Care to buy me a drink, or are you just here to people-watch?}
{1202}{}{Hey, sister, feeling generous today? Care to buy me a drink, or are you just here to people-watch?}
{203}{}{Hey, that was quite a brawl earlier. Feel like buying me a drink to celebrate, or do you come to the bar just for the fights?}

{204}{}{I'm a bit short on caps, sorry.}
{205}{}{Ha! Penny-pincher...}
{206}{}{What's that? You calling me cheap? Me?}
{207}{}{Well, later.}
{208}{}{Yep, and what about it?}
{209}{}{Seems like you're the one begging for a drink. Bitch.}
{210}{}{Uh, whatever.}
{211}{}{Alright, cool your jets, partner. It's best not to make a scene over small stuff in this town.}
{1211}{}{Alright, cool it, miss. It's best not to make a scene over small stuff in this town.}
{212}{}{Yeah, just sit and zip it then.}

{220}{}{Sure, let me just grab a drink for us.}
{221}{}{Okay, I'll be right here, friend.}
{1221}{}{Okay, I'll be right here.}
{222}{}{Alright, catch you later.}
{223}{}{Here's some nuclear beer. Not fancy, but it'll keep the conversation flowing, right?}
{224}{}{Let's crack open this bottle of bottom-shelf tequila. Perfect for unwinding, don't you think?}
{225}{}{Thanks for the drink. (pours a glass and falls silent)}
{226}{}{What's on your mind? Something bothering you?}
{227}{}{No... (takes a deep swig) Could be better.}
{228}{}{Listen, since I'm buying, how about telling me a bit about the city?}

{229}{}{I've only been here for a month, but it didn't take long to figure one thing out: making friends in this city isn't a good idea.}
{230}{}{Isn't that how it feels for any new place?}
{231}{}{Sounds like you've had a rough experience.}
{232}{}{I didn't ask for your opinion. But... I guess you're right.}
{233}{}{So, why don't you tell me your story?}
{234}{}{It's certainly felt like a rough experience...}
{235}{}{So, will you share your story with me?}
{236}{}{Well, I arrived here with my boyfriend. Things were going smoothly. We scavenged ruins, paid our dues to the colony.}
{237}{}{[Continue]}

{238}{}{But when caps started running low, Karl got tangled up in debt. And things spiraled from there. Finally, Faber ordered him thrown behind bars. Now he's in prison, and I'm... well, here. I don't know what to do next.}
{239}{}{Is he facing a long sentence?}
{240}{}{Faber gave him a year of hard labor, but Karl won't last that long. And neither will I.}
{241}{}{Is there any way to get him out?}
{242}{}{Only if we can scrape together enough caps to settle some of his debts. But there's no way we'll come up with that much.}
{243}{}{That's a tough break. I'm sorry to hear it.}
{244}{}{Yeah. Unfortunately.}
{245}{}{[Leave the girl to her thoughts with the bottle]}
{246}{}{What's your plan now?}
{247}{}{After this mess, there's no way they'll let me stay here. I gotta get out, maybe head back down south.}
{248}{}{Can you remind me what happened to your boyfriend?}
