{100}{}{You see a colonist.}
{101}{}{You see a citizen of the colony.}
{102}{}{I'm sleepy, leave me alone.}
{103}{}{Z-z-z...}
{104}{}{...}
{105}{}{ }
{106}{}{*Yawn*}
{107}{}{Where are you from?}
{108}{}{I'm sleepy, leave me alone.}

#Floating remarks (they are responses when you try to speak)
{110}{}{Do you know about the curfew? You can't go outside after it.}
{111}{}{This is the safest city in Arizona right now.}
{112}{}{Sometimes I miss the lights of Phoenix at night.}
{113}{}{I get shivers when I see Faber.}
{114}{}{They say there are raiders in the ruins to the east.}
{115}{}{When will the new caravan arrive?}
{116}{}{Never trust the servants.}
{117}{}{I'm a little afraid to go into the garrison area.}
{118}{}{Don't forget about the evening sermon.}
{119}{}{Taxes are high here, but it's worth it.}
{120}{}{Great view of Humphreys Peak.}

{150}{}{Now I'm afraid to go outside.}
{151}{}{Even a scorpion den is safer than here.}
{152}{}{We shouldn't have moved here.}
{153}{}{How could we be so wrong about Roy Faber?}
{154}{}{They say there are raiders in the eastern ruins.}
{155}{}{There are fewer and fewer caravans.}
{156}{}{Should you hire a maid? Well, I wouldn't.}
{157}{}{No way into the garrison now.}
{158}{}{Let this preacher talk some sense into the raiders first.}
{159}{}{And what do we pay taxes for?}
{160}{}{As soon as I smell trouble, I'll make for Humphreys Peak.}
