{100}{}{You see a mercenary.}
{101}{}{An old "acquaintance" stands before you.}

{110}{}{I've seen plantations out in the desert before. Not the most pleasant memories.}
{111}{}{Ah, Phoenix! Best and worst place I've ever known.}
{112}{}{Think your people are around here?}
{113}{}{This is Ranger territory. How'd we end up here?}
{114}{}{Are you crazy? We should've popped some Rad-X pills before coming here!}
{115}{}{Looks like there's civilization.}
{116}{}{Maybe they'll offer us fish, huh?}
{117}{}{This place gives me the creeps. Better check my weapon.}
{118}{}{Never set foot here. Wonder what sort of folks we'll find?}
{119}{}{Savage pueblos up ahead. They don't take kindly to strangers.}
{120}{}{Coming back here feels strange. Good thing you're the only one who recognizes me.}

{200}{}{(Suddenly, you encounter your old "acquaintance" - the raider from the Villa's cellars. His wounds are almost healed.) Well, well. Look who it is! Damn. How'd you end up here?}
{201}{}{Trying to save my family. What's so surprising?}
{202}{}{Well, isn't that somethin'. Long as you don't get in my way while you're here.}
{203}{}{How do you get off talking like that? I saved your life!}
{1203}{}{That's a little disrespectful. I saved your life!}
{204}{}{So, you reckon I owe you now? Listen up, maybe we can help each other.}
{205}{}{What are you jabbering about?}
{206}{}{My days as a mercenary are over. Faber won't take me on. I have nowhere else to go. Maybe you need help lookin' for your kin? For }
{207}{}{My days as a mercenary are over. Faber is dead. I have nowhere else to go. Do you need any help? For }
{208}{}{ caps, I'll tag along. You could definitely use a guide in this unfamiliar world.}
{209}{}{That's all? Fine. Here's the caps.}
{210}{}{I'm not paying you to be my "helper".}
{211}{}{I'll mull it over.}
{212}{}{Then get lost.}
{213}{}{Huh.}
{214}{}{}
{215}{}{Seriously? Trustin' me after all that went down at the Villa?}
{1215}{}{Seriously? Trustin' me after all that went down at the Villa?}
{216}{}{Yes. Stick with me. You're on bodyguard duty.}
{217}{}{Biggest load of crap I ever heard. But I got nothin' better to do.}
{218}{}{Fine. You're my bodyguard. Let's roll.}
{219}{}{Biggest load of crap I ever heard.}
{220}{}{You're pushing it with that attitude. Alright, how much you need then?}
{221}{}{Then keep rotting in this dump, loser.}
{222}{}{Got a better idea. Let's split any loot we find, fair and square?}

{230}{}{Boo-hoo!}
{231}{}{Ah, the wasteland has finally taken its toll on you. Spare me the unnecessary bruises on my fists - vanish!}
{232}{}{Buh, buh.}

{240}{}{Where to, boss?}
{241}{}{Just stick with me.}
{242}{}{Hold up. There are some things we need to talk about.}
{243}{}{I want you to tag along again.}
{244}{}{It's time we parted ways. You're free to go.}
{245}{}{That's it? Damn, I expected more. If you need me again, I'll be here waiting.}
{246}{}{Suit yourself.}
{247}{}{Nah, boss, I'm sick of your crappy company.}
{248}{}{I'll decide who stays.}

{250}{}{What's up?}
{251}{}{[Move along]}
{252}{}{Put your weapon away.}
{253}{}{Fine. But I'm not just gonna stand there if I'm attacked.}
{254}{}{Got it.}
{255}{}{Take off your armor.}
{256}{}{Do we really have to do this?}
{257}{}{Come on, let's get it over with.}
{258}{}{}
{259}{}{}

{260}{}{Need something?}
{261}{}{Who's the next target for a heist?}
{262}{}{I wouldn't mind some action.}
{263}{}{What's the plan here?}
{264}{}{Again? You're becoming a real bother!}
{265}{}{Here's an idea: let's find some tough guy and toss him off a building!}
{266}{}{I'm itching for a fight!}
{267}{}{When are we divvying up the caps?}
{268}{}{Ever thought about starting our own gang?}
{269}{}{I need a new weapon. Or better yet, two!}

{300}{}{Answer some pointless questions.}
{301}{}{What's up, boss?}
{302}{}{Nothing else for now.}
{303}{}{Got any goals?}
{304}{}{Survival. That's all that matters.}
{305}{}{Got it.}
{306}{}{Any guilt over the raid on the Villa?}
{307}{}{Not a one.}
{308}{}{What do you think of Faber?}
{309}{}{Not the worst scum in Arizona. But there's always room to find worse.}
{310}{}{Know the way to Phoenix?}
{311}{}{Yeah, I do.}
{312}{}{Show me on the map.}
{313}{}{Here. Heading to Phoenix? Smart move. All roads lead there.}
{314}{}{What's your weapon of choice?}
{315}{}{Pistols, submachine guns, and revolvers - my kind of arsenal.}
