{100}{}{You see a servant.}
{101}{}{You see a servant, his emaciated body covered in signs of beatings.}
{102}{}{Can I really go?}
{103}{}{Help! My owner will kill me!}

#First dialogue
{200}{}{(looks around confused) Is my owner... dead?}
{201}{}{Aren't you happy?}
{202}{}{What will I do without my master?! Master... Yes! I have to find a new owner! I need to get back to the pen. There is no other way...}
{203}{}{You don't seem to know any other way of life. Well, take care.}
{204}{}{(the servant falls at your feet and bows earnestly with his bald forehead) Thank you, mi senor! I am very grateful to you, sir! Thank you!}
{1204}{}{(the servant falls at your feet and bows earnestly with his bald forehead) Thank you, mi senora! I am very grateful to you, ma'am! Thank you!}
{205}{}{Come on, take it easy. By the way, I want to ask you something.}
{206}{}{Seems like you're not used to kindness. I'll be back when you calm down a bit.}
{207}{}{Hey, don't touch me with your dirty hands! Back off!}

{210}{}{Si, mi senor?}
{1210}{}{Si, mi senora?}
{211}{}{You're free.}
{212}{}{I have another question.}

{220}{}{Why did your master beat you?}
{221}{}{For losing a cap, sir. I, an insignificant lump of dirt, must have dropped it while shopping for my owner.}
{1221}{}{For losing a cap, ma'am. I, an insignificant lump of dirt, must have dropped it while shopping for my owner.}
{222}{}{He beat you for losing one cap?}
{223}{}{A cap is a lot, senor. You can buy half an iguana for a cap. But... (he glances up at you briefly before looking down again) Yes, it's a small amount, sir. My owner was angry because of debts and the city's unrest.}
{1223}{}{A cap is a lot, ma'am. You can buy half an iguana for a cap. But... (he glances up at you briefly before looking down again) Yes, it's a small amount, ma'am. My owner was angry because of debts and the city's unrest.}
{224}{}{It's clear that things are not going well here.}

{230}{}{I'm looking for my relatives. They were enslaved like you.}
{231}{}{All slaves are kept in a pen until they have work. The pen is further down the main street.}
{232}{}{Do you know how to help them escape?}
{233}{}{Escape? That's impossible, mi senor. There are guards all over the city, sirens would blare, and prisoners wear collars. But you can negotiate with the colony's warden. He's looking for people for special work.}
{1233}{}{Escape? That's impossible, mi senora. There are guards all over the city, sirens would blare, and prisoners wear collars. But you can negotiate with the colony's warden. He's looking for people for special work.}
{234}{}{So there might be a way to solve this peacefully? That's encouraging.}

{240}{}{How did you end up as a slave?}
{241}{}{I was sold from one owner to another until I ended up here.}
{242}{}{So you've lived your whole life as a slave?}
{243}{}{Si, senor. Except for the early years... when I took care of myself.}
{1243}{}{Si, senora. Except for the early years... when I took care of myself.}
{244}{}{That's a sad story.}
