{100}{}{You see a savage.}
{101}{}{You see one of the prisoners of the colony. His facial features are more pronounced than the others.}

#Dialogue
{200}{}{Keep your distance, stranger. The others won't take kindly to you.}
{1200}{}{Back off, woman. The others won't take kindly to you.}
{201}{}{Bye.}
{202}{}{What's your name?}
{203}{}{People around here call me Howler. But my real name would be hard for you to say.}
{204}{}{You're not from around here?}
{205}{}{I *am* from around here. My tribe lived in these mountains for three generations. Now I am the only real local left.}
{206}{}{What happened to your tribe?}
{207}{}{Some bad people came with guns. They took everything from us and forced us to work in the mine. Since then, I'm all that's left of the tribe.}  
{208}{}{Would you like to escape from here?}
{209}{}{I have nowhere to run. My home was destroyed and my kin were killed. All that remains is to wait for the Day of the Last Exhalation.}

{210}{}{If a break out starts, will you help me?}
{211}{}{Such a pointless battle is not for me.}
{212}{}{Hmm. To die in battle is death for a true warrior. I agree.}
{213}{}{Great. Wait for the signal to attack.}
{214}{}{Suit yourself, but it'll be too late after.}
