{100}{}{You see a miner.}
{101}{}{You see a filthy man with an intense, desperate look in his eyes.}
{102}{}{It's all over for me, friend.}
{1102}{}{It's all over for me.}

{200}{}{(You see an emaciated man in dirty, torn clothes. He holds a knife tensely near his slave collar, cold sweat dripping down his forehead.)}
{201}{}{What are you doing?}
{202}{}{Uh...}
{203}{}{Stay back! I'll do it! It's better to die than endure this hell!}
{204}{}{You won't. Look at you - you're a weakling.}
{205}{}{Don't say that! I was forced into this. What could I do?}
{206}{}{Typical. Just excuses...}
{207}{}{Shut up! Shut up!}
{208}{}{Doesn't it really hurt your eyes, sucker?}
{209}{}{And now you want to escape. But fooling with the collar will just kill you.}
{210}{}{Don't do this. That collar will kill you!}
{211}{}{Sorry, I can't help you. Go ahead, what are you waiting for?}
{212}{}{I KNOW! But my life is already over. If I die, at least I'll be free from suffering. And if not? What if they lied about the collars? Then I can escape from here.}
{213}{}{Then there's something to your idea. Will it work out? Be brave and do it.}
{214}{}{Weakling. I should hand you over to the overseer. Now that would be fuh.}
{215}{}{Think this through. Don't let your emotions control you.}
{216}{}{What do you know? I'm doing hard labor! Yes, I was imprisoned for a reason, but should I endure humiliation and beatings from the guards? It's not fair!}
{217}{}{Whatever you did, it's your fault. No one feels sorry for a criminal like you.}
{218}{}{So go ahead and do it. What are you waiting for?}
{219}{}{Alright. I'll try to help you. I still need to get my family out of here.}
{220}{}{Are you serious? Then I'm sorry, I got carried away. Listen, they say the collars are controlled by a radio antenna in the garrison territory. You just need to turn it off or destroy it. Think you can do it?}
{221}{}{Okay. I'll try. Wait for my signal.}
