{100}{}{You see a mercenary.}
{101}{}{You see an ordinary mercenary maintaining order in the colony.}
{102}{}{*Mumbling something under his breath*}

#Responses - good attitude
{110}{}{I'm keeping an eye on you.}
{111}{}{Interested in becoming a guard?}
{112}{}{What brings you here?}
{113}{}{Our colony is open to everyone... You know what I mean.}
{114}{}{There's good money to be made here.}
{115}{}{Heard the raid on Villa brought in some serious caps.}
{116}{}{Don't linger around here.}
{117}{}{Avoid talking to the prisoners.}
{118}{}{Best not to bother the boss when he's in a bad mood.}
{119}{}{If you need something, talk to the boss, not me.}

#Responses - bad attitude
{120}{}{I'm watching you.}
{121}{}{I can't stand people like you.}
{122}{}{Looking for trouble?}
{123}{}{This isn't a hangout, go loiter somewhere else.}
{124}{}{Don't bother me.}
{125}{}{Leave, this is a restricted area.}
{126}{}{You weren't invited here.}
{127}{}{Want to end up in the pen? We can arrange that...}
{128}{}{You better not piss me off.}
{129}{}{Don't be out late.}
