{100}{}{You see a mercenary.}
{101}{}{You see one of Faber's mercenaries. He is ready to help you drive out the savages.}

{110}{}{Don't worry, I got your back.}
{111}{}{There won't be a single savage left here shortly.}
{112}{}{Just point out who to shoot. I'll handle the rest.}
{113}{}{Together, we've got a better chance.}
{114}{}{Remember what Arizona was like before Faber came.}
{115}{}{Damn savages...}
{116}{}{This tribe's always been a thorn in our side.}
{117}{}{If you spot a savage, let me know.}
{118}{}{}
{119}{}{}
