{101}{}{The stiff corpse of a prisoner. Cause of death unknown.}  
{102}{}{The stiff corpse of a prisoner. He died trying to remove his collar.}  
{103}{}{You buried the prisoner's corpse. Someone had to do it.}  
{104}{}{Digging during a fight isn't your best idea.}  
{105}{}{The prisoner died from a massive electric shock while attempting to remove his collar.}  
{106}{}{His fate is not one to envy.}  
{107}{}{Ha! Pathetic loser.}  