{110}{}{It seems that this product of ancient technology could fly high in the sky. Very high.}
{111}{}{Another pile of scrap metal in another old building.}
{112}{}{You have removed all useful parts from this relic.}

{113}{}{This won't help here.}
{114}{}{Even though it didn't make sense, you put the pieces back in place.}
{115}{}{Huh, I've never done anything weirder.}
{116}{}{Wow, our ancestors sure were smart.}
