{100}{}{You see a buyer.}
{101}{}{You see a merchant who looks like he's been on the road for several days.}

{110}{}{Where's your boss? Tell him to hurry up. We're not staying in this dump.}
{111}{}{The buyer doesn't want to talk to you.}
{112}{}{A great deal for such a backwater place.}
{113}{}{A hole like this can only be a total disappointment. I'll have to leave empty-handed.}
{114}{}{Damn it! What's a Follower of Fire doing in a place like this?}
{115}{}{Hmm. I didn't expect to see actual Power Armor in such a dump. Interesting.}
