{100}{}{You see Lucas.}
{101}{}{You see Lucas.}
{102}{}{The transaction was successful.}

{110}{}{Keep your eyes peeled. We can't let Kogan's or Trayvon's crews interfere with the deal.}
{111}{}{Shit. Deal with Kogan's men while I take care of the caravan.}
{112}{}{Head back to the factory and we'll talk there.}
{113}{}{You'd better get out of here. Like, right now.}
{114}{}{Alright, we'll leave, Kogan won't hear from us again.}

{120}{}{All seems clear.}
{121}{}{Damn, these are Kogan's people. Tell them to get lost.}
{122}{}{It's done, go back to the factory and wait for me.}

{200}{}{We have no issues with you. Just get out of here and you won't get hurt.}
{201}{}{Kogan warns you not to interfere with the deal.}
{202}{}{Tell that fat bastard his reign is over. We're at the helm of this city now.}
{203}{}{You made the biggest mistake of your life by going against Kogan. And you're gonna pay for it. Right now!}
{204}{}{Okay, I'll tell him.}
{205}{}{Hey people, get your asses off the ground. It's go time!}
{206}{}{Let's get busy...}
{207}{}{You shouldn't have gone against Kogan. You'll never be able to match him.}
{208}{}{We had no choice. There was no work and the city was getting overcrowded. Looks like all we can do now is leave and lie low. There's plenty of room out in the wasteland.}
{209}{}{Sound decision.}
{210}{}{Only a fool would go against Kogan.}
