{100}{}{You see Dominguez's wife.}
{101}{}{You see a typical peasant's wife.}
{102}{}{Please, be careful! ¡Vas a... break all mis... dishes con that thing!}
{103}{}{The old zapatos... no have... worn out yet.}
{104}{}{La mujer is very... thrilled about nuevos... shoes.}
{105}{}{Thank you... mucho! Es so... difícil to find zapatos en este... desert...}

{106}{}{Please be careful! You'll break all my dishes in that thing!}
{107}{}{The old shoes haven't worn out yet.}
{108}{}{The woman is thrilled about new shoes.}
{109}{}{Thank you so much! It's so hard to find shoes in these desert regions...}

{110}{}{Eh... wha... Dear, check... *yawn* the... door.}
{111}{}{Uh... qué... honey, check... *yawn* la puerta...}
{112}{}{Get out, you damn yankee!}
{113}{}{Vete, dirty... gringo!}
{114}{}{I'm too busy. Habla con mi... husband.}
{115}{}{I'm too busy to talk. Speak with... mi... husband.}
{116}{}{You better leave. No nos gusta... strangers making preguntas.}

{117}{}{«I'm too busy. Talk to my husband.»}
{118}{}{«I'm too busy to talk. Speak with my husband.»}
{119}{}{«You better leave. We don't like strangers barging in with questions.»}

{200}{}{Ah, sorry about mi husband. Él está... shaken from la noche cuando patrol broke in y hizo una... late-night 'fiesta'.}
{201}{}{Shouldn't the military protect you?}
{202}{}{Oh sí, mostly they no bother us porque we... give carne to garrison. El general himself... signed un... decree for nuestra... protection. But esos soldiers were... jumpy from... chasing some spy y... overstepped their... bounds. They caught him eventually, but got themselves... en a mess.}
{203}{}{What did they want from you?}
{204}{}{They thought el spy might be hiding aquí, but... they caught him en el... desierto. On the way back, they... stopped to rest, eat, y get... agua. Es una... sad historia.}
{205}{}{[More]}
{206}{}{One of them quietly took nuestra... radio. As if we could usar it to... eavesdrop on their... comunicaciones. ¡Qué... nonsense!}
{207}{}{Indeed, that's not very neighborly. I don't think I'm going to get a very warm welcome around here. Goodbye, senora.}
{208}{}{What happened to that spy?}
{209}{}{Why do you need a radio?}

{210}{}{I'm too busy to talk. Speak with... mi husband.}
{211}{}{Goodbye.}

{220}{}{What happened to that spy?}
{221}{}{Well, él fue taken to garrison... prison. Eso es all I know.}
{222}{}{I see.}
{223}{}{Why do you need a radio?}
{224}{}{Sometimes, cuando el... weather es good, we catch news from... Los Mochis. Hay a small settlement allí under el nuevo... government. We also want to know qué está pasando en el... país.}
{225}{}{I see.}
{226}{}{Is this your radio?}
{227}{}{¡Es realmente it! How you... lo get?}
{228}{}{Nothing complicated. I just went in and took what's rightfully yours.}
{229}{}{Well, I had to sneak around a bit.}
{230}{}{¡Increíble! We tried to hablar with... alguien from the garrison, but they... no let us in. They even wanted us to... olvidar todo. But you got it back! ¡Muchas gracias!}
{231}{}{It was nothing, senora.}
{232}{}{You're welcome.}


# spanish lines
{300}{}{«Ah, sorry about my husband. He's still shaken from the night the patrol broke in and threw a late-night 'party'.»}
{301}{}{«Shouldn't the military protect you?»}
{302}{}{«Oh yes, mostly they don't bother us because we supply meat to the garrison. The general himself signed a decree for our protection. But those soldiers were jumpy from chasing some spy and overstepped their bounds. They caught him eventually, but got themselves into a mess.»}
{303}{}{«What did they want from you?»}
{304}{}{«They thought the spy might be hiding here, but they caught him in the desert. On the way back, they stopped by to rest, eat, and get water. It's just a sad story.»}
{305}{}{[More]}
{306}{}{«One of them quietly took our radio. As if we could use it to eavesdrop on their communications. What nonsense!}
{307}{}{«Indeed, that's not very neighborly. I don't think I'm going to get a very warm welcome around here. Goodbye, miss.»}
{308}{}{«What happened to that spy?»}
{309}{}{«Why do you need a radio?»}

{310}{}{«I'm too busy to talk. Speak with my husband.»}
{311}{}{«Goodbye.»}

{320}{}{«What happened to that spy?»}
{321}{}{«Well, he was taken to the garrison prison. That's all I know.»}
{322}{}{«I see.»}
{323}{}{«Why do you need a radio?»}
{324}{}{«Sometimes, when the weather is particularly good, we manage to catch news from Los Mochis. There's a small settlement there under the new government. We also want to know what's happening in the country.»}
{325}{}{«I see.»}
{326}{}{«Is this your radio?»}
{327}{}{«It is! This is really it! How did you manage to get it?»}
{328}{}{«Nothing complicated. I just went in and took what's rightfully yours.»}
{329}{}{«Well, I had to try not to be noticed.»}
{330}{}{«Unbelievable! We tried to talk to someone from the garrison, but they wouldn't let us in. They even wanted us to just forget the whole thing. But you got it back! Thank you so much!»}
{331}{}{«No problem, miss.»}
{332}{}{«You're welcome.»}
