{100}{}{You see Dominguez.}
{101}{}{You see a typical peasant.}

{102}{}{Damn militares, siempre armados y fully armored, ¿right?}
{103}{}{Get out antes de que te blow los sesos!}
{104}{}{Las old zapatos, no se han worn out yet.}
{105}{}{Old rubber sandals? ¡Cómo no pensé en eso antes!}
{106}{}{Parece que has solved el problema de los zapatos viejos de Dominguez. Está very happy about this.}

{107}{}{«Damn military, always armored and fully armed, right?»}
{108}{}{«Get out before I blow your brains out.»}
{109}{}{«The old shoes haven't worn out yet.»}
{110}{}{«Old rubber sandals? How come I didn't think of that before!»}
{111}{}{«Looks like you've solved Dominguez's old shoe problem. He's very happy about this.»}


{200}{}{Para. ¿Qué necesitas?}
{201}{}{I just want to talk. Why the hostility?}
{202}{}{Milit-ario close, but... no te conozco. If you here by... uh, acci-dente, better you leave.}
{203}{}{I'll do that. I don't want more trouble with the locals...}
{204}{}{Would you really turn away a traveler from the north? I just want to ask about this city.}
{205}{}{(raises his gun threateningly) Get off... mi ranch-o.}
{206}{}{Okay, whatever you say...}
{207}{}{You'll regret this...}
{208}{}{Tú otra vez. I said... vete off... mi ranch-o.}
{209}{}{Sure, no... problem.}

{210}{}{Okay, uh, pregunt...ask, but then you go, sí?}
{211}{}{I'm leaving now, relax.}
{212}{}{You live here alone?}
{213}{}{No, no, other familias...peaceful, aquí. Militar, ellos no like civiles cerca.}
{214}{}{Military? Who are you talking about?}
{215}{}{No sabes? Down carretera...road, garrison of la Nueva República Mexicana. Now, these tierras under General Sarabia.}
{216}{}{So I won't be able to settle down here?}
{217}{}{You, eh, really no sabe nada? Mira, situación...tough. Ejército del presidente, ellos try unificar tierras, pero we, campesinos, we pay. Nobody ask us. So, vivir cerca de fort...not best idea. Militares, no like squatters.}
{218}{}{How did you end up here?}
{219}{}{Tengo conexiones...eh, connections. Fort necesita...needs comida. Mi rancho, garrison protege, pero casi todo mi carne, tengo que dar.}
{220}{}{Got it. Thanks for the info. I should go.}
{221}{}{Oh, that changes things. Maybe I should leave. Immediately.}
{222}{}{General Sarabia - what do you know about him?}
{223}{}{Manuel Sarabia. Lo vi...seen him, sometimes. Motorcade y en reuniones generales. Usually, él está en el cuartel en la montaña.}
{224}{}{I think I should go see him. I hope he has a moment.}
{225}{}{Can civilians talk to him?}
{226}{}{¿Civiles? No. Y no quiero...meet him. Dicen que...dips bread in sangre de sus enemigos.}
{227}{}{This general sounds impressive. I need to meet him. Bye.}
{228}{}{So that changes things. Maybe I should go somewhere else. Goodbye.}
{229}{}{What did you say about the general?}
{230}{}{Do you know what his army's plans are for Arizona?}
{231}{}{No creo...garrison goes to Arizona soon. Cruzan desierto grande, and long time, we think no life norte. But if gobierno orders, army will go.}
{232}{}{Thanks, that was valuable information. I have something to take care of. Bye.}
{233}{}{Perhaps you've heard about his army's plans for Arizona?}
{234}{}{Do you know General Sarabia's plans for Arizona?}
{235}{}{Okay, pregunt...ask.}
{236}{}{Sí, pregunt...ask.}
{237}{}{I'm just a peaceful wanderer and I mean no harm. Let's talk, amigo?}

{238}{}{Gracias por el...eh, radio. Brightens nuestra vida un poco.}
{239}{}{Can I talk to you?}

{240}{}{Have you met old man Gallegos? He came north from these parts.}
{241}{}{¿Conoces a Gallegos? What a sorpresa...eh, surprise. That means he...eh, managed...cruzar el desierto...cross the desert. I thought...eh, that crazy idea...was like...suicide.}
{242}{}{Out of the entire group, he was the only one who survived. So you were almost right.}
{243}{}{Gallegos y los demás...eh, the others...were in...eh, una situación desesperada...desperate situation. Nuevo gobierno...new government, y tropas...eh, troops...oppressed...campesinos...peasants. People like yo...eh, me...lucky, pero muchos...eh, work like...slaves. Fleeing norte...eh, seemed only opción.}
{244}{}{He wasn't in the best of health, I guess the desert took a lot out of him.}
{245}{}{No puedo imaginar...eh, what he endured...en ese...hot desert. Aunque...eh, old man...was considered...un traidor...a traitor, he showed...us an example...de voluntad...eh, will...y perseverancia...perseverance. Gracias, me alegró escuchar...eh, glad to hear...news de un amigo...about a friend. And...eh, amigos de mis amigos...eh, friends too.}
{246}{}{You're welcome.}
{247}{}{Old Gallegos mentioned the Dominguez ranch. He said you were a good and honest man who wouldn't refuse a traveler a glass of water.}

{250}{}{Where do you get your brahmin from?}
{251}{}{¿Brahmin? ¿Qué es eso? Eh...what's that?}
{252}{}{The animals on your ranch.}
{253}{}{You don't know the name of your cattle? That's funny.}
{254}{}{Ah, waki. Ustedes...eh, northerners...siempre complican...things. Compré estos cattle...eh, as young...del ejército...from the military...after su raid...eh, for the vacs. Used to get...eh, su carne...meat that way...ahora...now, they take it from me. In a sense...es un préstamo...eh, a loan...I pay with provisions.}
{255}{}{Can I ask another question?}
{256}{}{I was just curious. Bye.}
{257}{}{I've been to San Brahmin. The locals revered these animals as sacred.}
{258}{}{¿Holy Brahmin? Nunca escuché eso...eh, never heard of it. Sounds estúpido...to me.}
{259}{}{Perhaps. But for them, it was a matter of survival.}
{260}{}{Exactly. Never seen anything dumber.}
{261}{}{Tus preguntas...eh, your questions...son cansadas...are tiresome. Tengo que...eh, I have to...mind mi propio negocio...own business.}
{262}{}{I'm already heading out, don't worry.}

{270}{}{You mentioned the difficult situation in Mexico. What's going on?}
{271}{}{Sí. During...eh, La Gran Guerra...capital was...destroyed, y muchas provincias...eh, gained independencia...independence. Most acquired...eh, small armies...and defended sus fronteras...eh, their borders.}
{272}{}{Continue.}
{273}{}{No need for details. You've made it pretty clear.}
{274}{}{Yo sé un poco...eh, I know...a bit. Los estados del norte...eh, northern states...taken by...eh, carteles...gangland cartels...with histories de...eh, trafficking armas...weapons, drogas...and people. Perdieron su negocio...eh, lost business, started...eh, defending...territorios...territories. Now, it's...eh, private property...de sus descendientes...of their descendants.}
{275}{}{What about the rest of the country?}
{276}{}{Fue especialmente difícil...eh, it was tough...en el sur...in the south, where nacionalistas...eh, nationalists...divided territorio...territory...en pequeños estados...into small states. Yucatán, Chiapas, Tabasco, Guerrero...todavía arguing...eh, about quién manda...who's in charge.}
{277}{}{That's all history. How are things now?}
{278}{}{Todo cambió...eh, everything changed...con el nuevo presidente...with the new president. Él reunió...eh, he gathered...un fuerte ejército...a strong army...and subjugó...eh, subjugated...todos los estados centrales...all central states...de Durango a Veracruz. Ahora...eh, right now, está luchando...eh, he's engaged...en el Istmo de Tehuantepec...in heavy fighting...east of the Isthmus. Tribus locales...eh, local tribes...son muy orgullosos...too proud, so this guerra...eh, war...will last...eh, años...years. Los estados del norte...eh, northern states...gradualmente...gradually...losing ground.}
{279}{}{Thanks for the story.}
{280}{}{De nada. Feliz de compartir...eh, share...la historia de mi gente...eh, history of my people...con folks like you. ¿Quién sabe?...eh, maybe...ancestros tuyos...eh, ancestors...once...came from Mexico.}
{281}{}{You've got a lot of interesting things to say. Will you give me some more time?}
{282}{}{Okay, Dominguez. Bye.}

{300}{}{«Stop. What do you need?»}
{301}{}{«I just want to talk. Why the hostility?»}
{302}{}{«The military is nearby, but I don't know you. If you're here by chance, you better leave.»}
{303}{}{«I'll do that. I don't want more trouble with the locals...»}
{304}{}{«Would you really turn away a traveler from the north? I just want to ask about this city.»}
{305}{}{(raises his gun threateningly) «Get off my ranch.»}
{306}{}{«Okay, whatever you say...»}
{307}{}{«You'll regret this...»}
{308}{}{«You again. I told you, get off my ranch.»}
{309}{}{«Sure, no problem.»}

{310}{}{«Ask your questions. But then you leave.»}
{311}{}{«I'm leaving now, relax.»}
{312}{}{«You live here alone?»}
{313}{}{«No, there are several other peaceful families in the area. The military doesn't like civilians under its nose.»}
{314}{}{«Military? Who are you talking about?»}
{315}{}{«Don't you know? Further along the main highway is the garrison of the New Mexican Republic. These lands are now under the protection of General Sarabia.»}
{316}{}{«So I won't be able to settle down here?»}
{317}{}{«You really don't know anything? Listen, the situation in the country is tough. The president's army is trying to unite the scattered lands, and we, ordinary peaceful peasants, are paying for it. They didn't even ask us. So, living next to a fort is not the best idea. The military does not tolerate self-settlers.»}
{318}{}{«How did you end up here?»}
{319}{}{«I had connections. And the fort needs food. My ranch is protected by the garrison, though I have to give up almost all of my meat in return.»}
{320}{}{«Got it. Thanks for the info. I should go.»}
{321}{}{«Oh, that changes things. Maybe I should leave. Immediately.»}
{322}{}{«General Sarabia - what do you know about him?»}
{323}{}{«Manuel Sarabia. I've seen him a few times in the motorcade and at general gatherings. Usually, he's at the headquarters on top of that mountain.»}
{324}{}{«I think I should go see him. I hope he has a moment.»}
{325}{}{«Can civilians talk to him?»}
{326}{}{«Civilians? No. And I don't want to encounter him. They say he dips his bread in the blood of his slain enemies.»}
{327}{}{«This general sounds impressive. I need to meet him. Bye.»}
{328}{}{«So that changes things. Maybe I should go somewhere else. Goodbye.»}
{329}{}{«What did you say about the general?»}
{330}{}{«Do you know what his army's plans are for Arizona?»}
{331}{}{«I doubt the garrison will head to Arizona anytime soon. They'd have to cross a huge barren desert, and for a long time, we thought there was no life in the north. But if the government orders it, the army will go.»}
{332}{}{«Thanks, that was valuable information. I have something to take care of. Bye.»}
{333}{}{«Perhaps you've heard about his army's plans for Arizona?»}
{334}{}{«Do you know General Sarabia's plans for Arizona?»}
{335}{}{«Okay, ask away.»}
{336}{}{«Of course, ask.»}
{337}{}{«I'm just a peaceful wanderer and I mean no harm. Let's talk, amigo?»}

{338}{}{«Thanks for the radio. It brightens up our drab everyday life at least a little.»}
{339}{}{«Can I talk to you?»}

{340}{}{«Have you met old man Gallegos? He came north from these parts.»}
{341}{}{«You know Gallegos? What a surprise. That means he managed to cross the desert. I thought that crazy idea was tantamount to suicide.»}
{342}{}{«Out of the entire group, he was the only one who survived. So you were almost right.»}
{343}{}{«Gallegos and the others were in a desperate situation. The new government and their troops were oppressing the peasants. People like me were, and are still lucky. Many work like slaves. Fleeing north seemed the only option.»}
{344}{}{«He wasn't in the best of health, I guess the desert crossing really took a lot out of him.»}
{345}{}{«I can't imagine what he endured in that hot desert. Although the old man was considered a traitor, he showed us an example of will and perseverance. Thank you, I was glad to hear news about an old friend. And the friends of my friends are my friends too.»}
{346}{}{«You're welcome.»}
{347}{}{«Old Gallegos mentioned the Dominguez ranch. He said you were a good and honest man who wouldn't refuse a traveler a glass of water.»}

{350}{}{«Where do you get your brahmin from?»}
{351}{}{«Brahmin? What's that?»}
{352}{}{«The animals on your ranch.»}
{353}{}{«You don't know the name of your cattle? That's funny.»}
{354}{}{«Ah, waki. You northerners always complicate things. I bought these cattle as young from the military after their raid for the vacs. They used to get their meat this way, now they take it from me. In a sense, it's a loan I pay back with provisions.»}
{355}{}{«Can I ask another question?»}
{356}{}{«I was just curious. Bye.»}
{357}{}{«I've been to San Brahmin. The locals revered these animals as sacred.»}
{358}{}{«Holy Brahmin? Never heard of it. Sounds stupid to me.»}
{359}{}{«Perhaps. But for them, it was a matter of survival.»}
{260}{}{«Exactly. Never seen anything dumber.»}
{361}{}{«Your questions are tiresome. I have to mind my own business.»}
{362}{}{«I'm already heading out, don't worry.»}

{370}{}{«You mentioned the difficult situation in Mexico. What's going on?»}
{371}{}{«Yes. During La Gran Guerra, our capital was destroyed, and many provinces gained independence. Most acquired small armies and defended their borders.»}
{372}{}{«Continue.»}
{373}{}{«No need for details. You've made it pretty clear.»}
{374}{}{«I know a bit myself. The northern states were taken over by gangland cartels with histories of trafficking weapons, drugs, and people. Losing their business, they started defending their territories. Now it's their descendants' private property.»}
{375}{}{«What about the rest of the country?»}
{376}{}{«It was especially tough in the south, where nationalists divided the territory into small states. Yucatan, Chiapas, Tabasco, and Guerrero are still arguing about who's in charge.»}
{377}{}{«That's all history. How are things now?»}
{378}{}{«Everything changed with the new president. He gathered a strong army and subjugated all the central states from Durango to Veracruz. Right now, he's engaged in heavy fighting east of the Isthmus of Tehuantepec. The local tribes are too proud, so this war will last for years. The northern states are also gradually losing ground.»}
{379}{}{«Thanks for the story.»}
{380}{}{«It's nothing. I'm happy to share the history of my people with folks like you. Who knows, maybe your ancestors once came from Mexico.»}
{381}{}{«You've got a lot of interesting things to say. Will you give me some more time?»}
{382}{}{«Okay, Dominguez. Bye.»}

