{100}{}{You see a super mutant.}
{105}{}{Bastards! Gonna smash you for what you did to my friends!}

{110}{}{Talk to Levi.}
{111}{}{Pathetic human.}
{112}{}{Don't you dare stare at me.}
{113}{}{I hate it when people stare.}
{114}{}{Hmmmm...}
{115}{}{You playin' dice?}
{116}{}{Don't make me mad.}
{117}{}{Levi answers questions. If he wants.}
{118}{}{Don't talk to me, normie.}
{119}{}{Bother me, and I'll tear you to pieces, feed you to the reavers.}

{120}{}{Hey, normie.}
{121}{}{Levi says you're a friend.}
{122}{}{Good thing you ain't dead yet.}
{123}{}{Wanna test your strength?}
{124}{}{Gettin' bored...}
{125}{}{Levi says cure is coming soon.}
{126}{}{Wanna be like me?}
{127}{}{Ahaha, my suffering's almost over!}
{128}{}{Love pissin' off reavers. They can't do nothing to me.}
{129}{}{Reavers dumb. I smart.}
