{100}{}{You see the Guide.}
{101}{}{You see a person in an old travel cloak. Their head and hands are wrapped in bandages.}
{102}{}{This is where our paths part. To return to Sonora, wait for the next caravan by this flag.}
{103}{}{Pleasure to meet you, smooth-skinned one.}

{200}{}{Child of humanity, this place is dangerous for one such as yourself.}
{201}{}{It's dangerous for you too. What are you doing here?}
{202}{}{Hmm. Have you encountered GHOULS? People with pockmarked skin, living for ages? I seek them to guide them to the ruins of San Diego.}
{203}{}{Why are the ghouls gathering at the ruins of San Diego?}
{204}{}{Our home was once Necropolis. Due to the super mutant army, the city was abandoned, and the ghouls scattered across the wasteland. We were driven away from everywhere. Finally, we created a new city - Dayglow. It is open to all ghouls and mutants willing to share our burden.}
{205}{}{I want to join you.}
{206}{}{Then our paths do not align. Goodbye.}
{207}{}{In Dayglow, you may die from radiation, smooth-skin. And even if you don't, the ghouls are unlikely to accept you. People have always driven us away. Consider if you are ready for such a trial.}
{1207}{}{In Dayglow, you may die from radiation, smooth-skin. And even if you don't, the ghouls are unlikely to accept you. People have always driven us away. Consider if you are ready for such a trial.}
{208}{}{I don't find a place for myself in this world either. I think visiting a new place could do me good.}
{209}{}{Some mysterious stranger invited me to Dayglow. I can't ignore that.}
{210}{}{This all sounds quite repulsive. I'll delay the trip for now. Goodbye.}
{211}{}{Well, the decision is yours.}
{212}{}{Tell me about the journey.}
{213}{}{Why are the ghouls gathering in San Diego?}

{220}{}{Our paths cross again. Could it be fate?}
{221}{}{No, it's just a coincidence. Goodbye.}
{222}{}{I want to go with you to Dayglow.}

{230}{}{Great Set! You remind me of the ghouls of Necropolis in the early stages of the disease. But I don't remember you. Are you a new child of the Master?}
{231}{}{I am not from Necropolis, nor a child of the Master. Someone named Levi made me this way.}
{232}{}{Levi? I know him. He is one of the Master's finest works. But he looks down on those like us. So, you're a victim of his experiments? I pity you. Now you will taste the full bitterness of ghoul life.}
{233}{}{I'm fine as I am. Don't know why you're so down.}
{234}{}{That's true - everyone avoids me. Even my kin.}
{235}{}{}
{236}{}{}
{237}{}{Then come with us. We are building a home for those like you and me.}
{238}{}{A home for mutants? Where is it?}
{239}{}{The ghouls are building a new city in the ruins of San Diego. A world of their own. I'm seeking and guiding all ghouls who still have some sanity left. You'd find a place there too.}
{240}{}{Alright. I'll go with you to San Diego.}
{241}{}{I can't leave these lands yet. But I'll keep in mind that there is another place in the wasteland where I'm awaited.}

{250}{}{You'll have to leave your friends behind here. You can only take the essentials, no more than 20 pounds. Through the scorched lands, you need to travel light - swift as the wind.}
{251}{}{No way. I'm not leaving my belongings behind!}
{252}{}{Can I come back if I don't like it there?}
{253}{}{Return - yes. But you can count on my escort only once.}
{254}{}{Then I need to think. I'll find you if I decide.}
{255}{}{I'm ready to set off.}
{1255}{}{I'm ready to set off.}
{256}{}{Soon you'll find yourself in another world, friend.}
{1256}{}{Soon you'll find yourself in another world, friend.}
{257}{}{[Embark on the journey]}
{258}{}{You have too many items.}
{259}{}{I have too many items. I'll come back after stashing them somewhere.}
