{103}{}{One less bitch to deal with.}
{104}{}{Foolish man, this poison has no effect on Jackals!}

#Counter dialogue
{200}{}{Seize the outsider! Tear him to shreds! Bring me his head!}
{1200}{}{Grab the outsider bitch! Tear her to shreds! Bring me her head!}
{201}{}{Seize the outsider! Get him out of his shell! Bring me his head!}
{1201}{}{Grab the outsider bitch! Get her out of her metal shell! Bring me her head!}
{202}{}{Man, you are one high-strung...}
{203}{}{Get back, you cannibal freaks! Get back!}

{210}{}{L-Look who came to us. An outsider from a strange tribe. How lucky, I won't have to chase my food across the wasteland.}
{1210}{}{L-Look who came to us. A bitch from a foreign tribe. How lucky, I won't have to chase my food across the wasteland.}
{211}{}{What do you want?}
{1211}{}{What do you want?}
{212}{}{Yeah, I don't really feel like running through the desert.}
{213}{}{I've had enough of this bullshit. I'm leaving.}
{214}{}{(laughter) The outsider doesn't understand. The outsider still has hope of getting out of here alive. It's amusing.}
{1214}{}{(laughter) B-bitch doesn't understand. The bitch still has hope of getting out of here alive. It's amusing.}
{215}{}{So you're going to try to kill me?}
{216}{}{Uh, you're not going to eat me, are you?}
{217}{}{(face changes sharply) We're hungry! W-we kill to survive. We are starving, and you, outsider, will become food for us. (turns to the others) We will feed our pups with his body! (the approving howl of a dozen mouths echoes through the dens)}
{218}{}{Actually, I had other plans...}
{219}{}{You're not serious, are you?}

{220}{}{Give me your name, outsider, before we tear the flesh from you.}
{1220}{}{Give me your name, outsider bitch, before we tear the flesh from you.}
{221}{}{My name: Shove-It-Up-Your-Ass, BITCH!}
{222}{}{Do you really need to know my name?}
{223}{}{(snorts like a dog) Your tongue is so deceitful that I will give it to the rats.}
{224}{}{That's not very kind of you.}
{225}{}{It won't come to that, lady.}
{226}{}{So be it. The dens are open for you. But don't look in the storerooms. The Night Beast guards them too jealously.}
{227}{}{Okay, I'll keep that in mind. Now I'll take a look around, if you don't mind.}
{228}{}{What is this? A man in an Iron Shell? What a s-surprise. You scared a lot of my people, Shell Man. But you don't fool me with this. Give up, we'll get you out of this ugly thing no matter how you squirm.}

{230}{}{I am the messenger of the Spirit of the Vaults. My suit is proof of that.}
{1230}{}{I am the messenger of the Spirit of the Vaults. My suit is proof of that.}
{231}{}{Spirit of the Vaults... I... remember! Our ancestors wore the same blue robes as you. S-so we all came out of the same den, we are members of the same tribe?}
{232}{}{Not dens, vaults. We came from vaults.}
{233}{}{Then tell me, why did the Spirit of the Vault abandon us? Why did he punish us with pestilence and famine? We called Him at night and made sacrifices to Him. If He finally heard our barking, then explain what we should do.}
{234}{}{Give me time to get to know the pack and learn about your life. Perhaps I can help you.}
{235}{}{They don't call me a ghoul for nothing. If you taste my dead flesh, you yourself will become dead.}
{236}{}{Living dead! The spirits are punishing us with pestilence again. (a plaintive howl echoes through the dens) But maybe YOU can teach us to survive in this world? If you manage to breathe in a dead body, then perhaps your wisdom could help us hold off the last journey to the Great Kennels.}
{237}{}{Give me time to get to know the pack and study your life. Perhaps I can help you.}
{238}{}{I want to help you.}
{239}{}{I'm an ambassador from the outside world. Neighboring cities are tired of your hostility and want to help solve your hunger problem.}
{240}{}{Will our enemies give us food in exchange for peace? This could be a trap. Or maybe an alliance that will save us from problems.}
{241}{}{If you kill me, you won't gain much anyway. So what do you say?}
{242}{}{Killing me will anger the... uh... Holy Jackal.}
{243}{}{I am guided by the Spirit of the Vault. He sent me to solve the problem of hunger.}
{244}{}{We prayed to the Spirit and made sacrifices to Him. But He never helped us. Generation after generation, brood after brood - we only became smaller and died out. Now he has mercy on his servants? Then tell me what we should do!}
{245}{}{First, I need to get to know the pack.}
{246}{}{No, you cannibal freak, no one is going to help you. Everyone just wants you dead!}

#Re-dialogue
{250}{}{The dens are open for you.}
{251}{}{The dens are open for you. But don't try to deceive us.}
{252}{}{I think I'll go.}
{253}{}{The Rangers fed us as promised. And although we do not like plant foods, hunger no longer threatens our stomachs. The whole pack is indebted to you, the messenger of the Holy Jackal.}

{260}{}{Let's talk about your hunger problems.}
{261}{}{There's desert all around, with little food and water. Hunger forces us to attack outsiders.}
{262}{}{Give me some time, and I'll try to find a solution to this.}
{263}{}{And then eat them? That's why everyone who has even heard of you shuns you.}
{264}{}{Outsiders have always driven us away. Why would anyone share food with us? We have to feed ourselves.}
{265}{}{In other words, take it by force or steal it. Don't you have anything to offer in exchange?}
{266}{}{Trade for food? We have nothing to offer.}
{267}{}{It won't be easy to find allies for you, but I'll try.}
{268}{}{I'm waiting, outsider. You gave your word that you would find us food.}
{1268}{}{I'm waiting, outsider bitch. You gave your word that you would find us food.}
{269}{}{I'm working on it.}
{270}{}{The Rangers are ready to form an alliance with you.}
{271}{}{(hisses) Shh! Rangers are enemies! They always attacked us first. And you want to lead them to the valley?}
{272}{}{They're also tired of this fighting. For now, just listen to them. They will send an ambassador to negotiate.}
{273}{}{Talking... It won't satisfy our hunger. But it won't make things worse either. Tell these... o-outsiders that I will listen to them.}
{274}{}{As a sign of good will, release the ranger you are holding. Otherwise, you'll lose your only chance to gain an ally.}
{275}{}{I'll tell them that you'll talk.}
{276}{}{Such juicy meat... I could feed half the pack with it. Alright... But if it's a trick, you'll pay dearly.}
{277}{}{Now disappear. And hurry. I'm not going to wait until the end of my days.}
{278}{}{Alright.}

{300}{}{Tell me about your tribe.}
{301}{}{We are all of the same blood. We have been living in these dens for three generations. Before, the pack was larger, but hunger thinned our numbers, and the brood began to be born sick and weak more often. What else do you want to know?}
{302}{}{Let's not talk about something else.}
{303}{}{So you haven't always lived in this valley?}
{304}{}{Our ancestors wandered many paths. They came from a place called "Vault 15". I don't know what this means. But then everything was different.}
{305}{}{I see.}
{306}{}{This gear-shaped structure is a reminder of those days, right?}
{307}{}{Yes... that is r-right.}
{308}{}{You don't know what it represents, do you?}
{309}{}{Represents? The Spirit doesn't talk to me about this. And the ancestors didn't tell us anything. With the coming of the hungry seasons, the story was lost...}
{310}{}{That's not surprising. Can I ask you something else?}
{311}{}{This is a depiction of an armored door. Your ancestors came from a Vault-Tec vault.}
{312}{}{(thoughtfully) Vault-Tec... You are truly wise. Then tell us how to fight hunger! Too many Jackals and too little food. That's what really matters.}
{313}{}{Can't argue with that. But before we start fighting over a handful of scraps, let me ask one more question.}
{314}{}{Why can't I go into the storerooms?}
{315}{}{Water and food supplies are kept in the storerooms. My faithful Jackals are trained to guard this place. They'll tear you apart if you go there alone.}
{316}{}{Looks like you trained everyone here well. Let me ask you something else.}
{317}{}{How do you feel about Black Fang?}
{318}{}{He is the best warrior of the tribe. The strongest, the most persistent, the best at wielding a spear, and the one who brings the most prey into the dens. }
{319}{}{I thought you weren't on the best terms with him.}
{320}{}{At the same time, he is the most arrogant, stubborn, and stupid male I have ever seen. When he becomes weak, I will be the first to tear out his eyes and rip the meat from his chest.}
{321}{}{Great morals here. I hope this fate doesn't befall me.}
