{100}{}{You see a savage.}
{101}{}{You see one of the bitches of the Jackal tribe. Her small red eyes stare at you from the darkness.}

#Replicas floating
{120}{}{Again, just maggots for lunch.}
{121}{}{Shhh, don't bark in vain!}
{122}{}{They say there's an outsider wandering around in the dens.}
{123}{}{The brood will die out if we don't find food.}
{124}{}{Time to sharpen my claws.}
{125}{}{Outsiders have no mercy.}
{126}{}{}
{127}{}{}
{128}{}{}
{129}{}{}

#Response
{200}{}{Give me a reason and I'll rip the meat off your bones!}
{201}{}{I will feed your flesh to my pups.}
{202}{}{My claws hunger for your flesh.}
{203}{}{}
{204}{}{}

{205}{}{My children thirst for your blood.}
{206}{}{My children hunger for your meat.}
{207}{}{Do you want to die, outsider?}
{208}{}{Mmm, you smell delicious.}
{209}{}{*Licks lips while examining your body*}

{210}{}{Hit me!}
{211}{}{I want to be your bitch!}
{212}{}{Mount me and bite my neck.}
{213}{}{}
{214}{}{}
