{100}{}{You see a victim of cannibals.}
{101}{}{You see an exhausted man.}
{102}{}{It's definitely better here than that old motel. I'll never stay there overnight again.}

{200}{}{Ahh! Don't touch me!}
{201}{}{I'm not going to touch you. Calm down.}
{202}{}{Shut up, idiot. We'll be heard.}
{203}{}{Huh? You're not a mutant? Oh... I'm so glad to see you...}
{204}{}{Why did the mutants lock you up?}
{205}{}{Can't you see all these bones? They're cannibals! They lure people into traps and butcher them like cattle.}
{206}{}{That's horrific.}

{210}{}{We need to get out of here! They killed everyone else... They'll kill us too!}
{211}{}{Stay here for now. I'll check if there's any danger ahead.}
{212}{}{Okay. I'll accompany you to the nearest settlement. Let's go. Just stay quiet.}
{213}{}{I'm still shaking with fear. We need to leave this place quickly.}
{214}{}{Then let's not waste time. Move.}
{215}{}{Sit here and keep your head down. I'm going to scout ahead.}

{220}{}{We're definitely safe now. Ugh. If it weren't for you, I would have been eaten by now. Thank you. I'll tell everyone who saved me.}
{221}{}{Glad I could help. Good luck.}
