{100}{}{You see a raider.}
{101}{}{You're looking at a highwayman with a wound in the shoulder.}
{102}{}{You're looking at a highwayman. He looks much more cheerful since your last meeting.}
{103}{}{I would have died if it weren't for you, Doc.}
{104}{}{B-bitches from the caravan got me in the shoulder during a raid... It fuckin' hurts!}
{105}{}{I was shot in the shoulder during a raid on a caravan. But we still took everything they had.}
{106}{}{Is this really medicine, Doc? It's just getting worse...}
{107}{}{Oops! He, uh, was in an advanced stage...}
{108}{}{Who let you in?}

{200}{}{I would have died if it weren't for you, Doc.}
{201}{}{You're welcome.}

{210}{}{Any help, Doc?}
{211}{}{Bye.}

{220}{}{Tell me how you got injured.}
{221}{}{I was shot in the shoulder during a raid on a caravan. But we still took everything they had. Ha!}
{222}{}{How did you end up joining the Blue Shields?}
{223}{}{I had nowhere to go, so I decided to sign up with Ben as one of his crew. It wasn't easy. I had to go through a tough initiation rite, and I still have the scars from it. But I proved I'm fit for the Blue Shields. A day I'll be proud of for the rest of my life.}
{224}{}{What do you do in the gang?}
{225}{}{Y'know, whatever tasks Ben or Rio set. Recently, I was in charge of handing out fuel before raids. Ben's very picky about conserving our supplies, so he keeps a tight grip on the fuel.}
{226}{}{Can you spare me a liter or two?}
{227}{}{After you heal me? For sure! I'll make you molotov cocktails or get you raw fuel, whatever, but not an unlimited amount, okay?}
{228}{}{Cool...}
