{100}{}{You see Ralph.}
{101}{}{You see a man with burnt and decaying skin. He's wearing some seriously worn-out work clothes with a pre-war emblem.}
{102}{}{I don't deal with traitors.}
{103}{}{Thanks for the help. Came in handy.}

{200}{}{Stop, no outsiders past this point. What do you want?}
{201}{}{I thought this place was just an abandoned ruin. What are you doing here?}
{202}{}{We've been living here for years. The whole city knows that. So, you can stop with the bullshit.}
{203}{}{But I'm not local. I'm from a village to the northwest.}
{1203}{}{But I'm not local. I'm from a village to the northwest.}
{204}{}{Oh, well, you don't look like the usual cityfolk... tanned skin, unusual accent. Very interesting...}
{1204}{}{Oh, well, you don't look like the usual cityfolk... tanned skin, unusual accent. Very interesting...}
{205}{}{Hmph. How about I just leave?}
{206}{}{What's so interesting about that?}
{207}{}{Alright, listen, we're in a bit of a crisis here. Maybe you could help. Go to the plant chief, and see what you can work out.}
{208}{}{Hmm... Alright.}

{210}{}{Wait, what the... Is that makeup?}
{211}{}{It's real skin. A bit green, but manageable.}
{212}{}{I hope you're not joking around about your skin with *us*.}
{213}{}{No, I'm not. It's the result of an experiment I went through in Inferno.}
{214}{}{(looks at you closely) Damn, you're serious. Well, I can't even remember what I looked like before the Transformation. Must've been tough for you. Good to meet you.}
{215}{}{Oh, now you're happy to see me? Sure thing.}
{216}{}{Likewise. So, what's going on in here?}
{217}{}{I never introduced myself. My name is Ralph. I'm, you could say, Theodore's right hand man. Sorry for the cold welcome, but we're not in a friendly mood lately.}
{218}{}{Can I ask you a few questions, Ralph?}

{220}{}{What do you need?}
{221}{}{See you around.}

{230}{}{Has this power plant really been running since pre-war times?}
{231}{}{It was mothballed for a long time. Only recently did we get the main reactor running.}
{232}{}{How did you manage that?}
{233}{}{Thank the fire worshippers and their colony in Flagstaff. They mine uranium for the church's use. Some of that uranium comes to us. It was a beneficial deal for the whole city.}
{234}{}{So it turns out the church folks do more than just pray.}
{235}{}{Beneficial, sure, except for the slaves working to death mining ore.}
{236}{}{How did you all end up here?}
{237}{}{We came from the west, from California. But that's a long story. We were offered a chance to restore the plant. You modern folks don't know jack about pre-war tech.}
{238}{}{Wait, are you saying you've lived since before the Great War?}
{239}{}{Kept in good shape, haven't we? Our favorite joke. They say our mutation was caused by some virus that got released when an old lab was bombed. But that's just a rumor.}
{240}{}{Tell me, what was the world like before the war?}
{241}{}{Hmm... A hundred years is a long time, much of it is foggy. I remember cars, skyscrapers, military checkpoints. I remember the war, the bombs dropping on the city. But how can I explain that to someone like you? It's just history to you.}
{242}{}{I see it's hard for you to remember. Let's change the subject.}
{243}{}{Someone like me? Keep your history to yourself then, Mr. Spotted Skin.}
{244}{}{Your boss says the pipeline was blown up, by someone. What do you think about that?}
{245}{}{Whoa, that's a strong statement. Don't take the old man's words too seriously. He's losing his mind, or hadn't you noticed?}
{246}{}{But he still owes me for the job.}
{247}{}{Then do what he says. He wants culprits? Find them then. How do you do that? That's the tricky part... You know, the saboteurs must've come through the sewers. Still... I thought we sealed all the entrances well.}
{248}{}{Sewers huh? I should check it out.}
{249}{}{The saboteurs probably came through the sewers. But I thought we sealed all the entrances well.}

{250}{}{Spawn of Electromagnetic Hell, just... leave! Everything was fine until you showed up.}
{251}{}{Game over, Ralph. You lost.}
{252}{}{Oh no, the fun's just starting. Now you'll see the real power of the Old World!}
{253}{}{Don't, just don't...}
{254}{}{Your funeral, idiot.}
{255}{}{Listen to me, Ralph. It was a bad deal from the start. You were used.}
{256}{}{It's a mutually beneficial contract. Only the fire worshippers could give the power plant new life and revive a piece of the Old World. No one else had the knowledge or resources for this. And old Theodore is just losing his mind. It's scary to think how this story will end under his leadership.}
{257}{}{Even if that's true, you're not leaving here alive.}
{258}{}{The church doesn't care about any of you or the world around. Can't you see that?}
{259}{}{Enough of this useless chatter! Now you'll see the real power of the Old World.}
{260}{}{I understand you. You want to bring back the Old World you knew. But look around - the fire worshippers are creating a different world.}
{261}{}{Different... Hmm... There's truth in that. Maybe Aaron is just using us to build himself an empire. I hadn't really thought about that. But if you *do* think about it... Damn, what should I do? Go back to ruined California? Or head east with the guys? Who knows, maybe we'll find oil in Texas or revive the old Chryslus Motors' factories.}
{262}{}{Believe me, you've got no future here. At best you'll just become a tool in the emperor's hands.}
{263}{}{Enough. I can't let a lunatic like you just walk away. You die here and now.}
{264}{}{Well said. I'll leave. Peacefully. Tell Theodore to remove the guards from the doors.}
{265}{}{Smart move, Ralph.}
{266}{}{Your boss asked me to fix the cooling system. Any pointers on where to start?}
{267}{}{What is that old man thinking, letting a stranger into the heart of the plant? Alright, let's see. First, check the damage on the lower level. You'll need materials and equipment for repairs. The easiest place to get them is at the Tinsmith's town. It's somewhere south of the city, the caravaners should know exactly where.}
{268}{}{Thanks.}

{270}{}{I know you helped the Cardinals sabotoge the cooling system.}
{271}{}{Speak softer, no need for such harshness. Now, let's move to a quieter spot...}
{272}{}{[Continue]}
{273}{}{So you must have connections with the fire worshippers, otherwise how would you know about our secret deal?}
{274}{}{I have plenty of connections. But what are *you* after? You want to take your boss's place?}
{275}{}{Such a shortsighted motive. Please. Remember, I'm a hundred years old. If we were in the Old World, I'd be climbing the corporate ladder. But what do we have now? Ruin, no infrastruture, no services, roads, running water...people only saw street lighting again thanks to us and the Church of the Holy Fire.}
{276}{}{Doesn't the church supply you with uranium?}
{277}{}{Yes, but simple trading, or bartering, is not enough. Theodore keeps them out of the power plant's affairs, and without them, progress is too slow. At first, things were purely technical - we took uranium and got energy from it. Now it's time for economics, business, and taxes. Theodore doesn't understand any of this and thinks it's enough to just sell energy left and right.}
{278}{}{So you want to renegotiate *exclusive* deals? What about Theodore?}
{279}{}{His problem is he's losing his mind, yet the workers still stand behind him. I need to take the helm of the plant for things to change. Help me. Get rid of Theodore, and you'll get a reward and respect. But more than that, you'll be doing a great service to the whole city.}
{280}{}{I'll think about it.}
{281}{}{My plan has already partially failed because you fixed the cooler. Don't screw things up this time.}
{1281}{}{My plan has already partially failed because you fixed the cooler. Don't screw things up this time.}
{282}{}{Goodbye.}
{283}{}{We've already discussed everything. Don't screw it up again.}
{284}{}{Goodbye.}
{285}{}{But how do I eliminate Theodore? It's a not an easy task.}
{286}{}{I've thought about that. Open murder would cause too many disputes and suspicions. Try using some poison or strong drugs. There's no way the old ghoul's heart will hold.}
{287}{}{Good idea. There was a drug dealer somewhere in the slums.}
{288}{}{It's done. The plant chief's position is now yours.}
{289}{}{You must've been sent to us by the Angel of Electromagnetism. Thank you. You did the right thing. Now go to the supply room and ask for your reward. He'll find a way to thank you.}
{1289}{}{You must've been sent to us by the Angel of Electromagnetism. Thank you. You did the right thing. Now go to the supply room and ask for your reward. He'll find a way to thank you.}
{290}{}{Goodbye, Ralph.}

{291}{}{I heard you get uranium from Flagstaff.}
{1291}{}{I heard you get uranium from Flagstaff.}
{292}{}{Not exactly. We get fuel rods with uranium cores, and they're made in the south. The uranium ore is shipped there. Why do you ask?}
{293}{}{Doesn't it bother you that this ore is mined with slave labor?}
{294}{}{We don't care who mines it or how. We need uranium, the rest isn't our concern.}
{295}{}{Hmm. I get it... But you're still indirectly responsible.}
{296}{}{I understand. It's just business.}
