{100}{}{You see a monk.}
{101}{}{You see a man in a cassock. He is clearly not here by accident.}
{102}{}{Your place is in the desert, savage.}
{1102}{}{Your place is in the desert, savage.}
{103}{}{May the Holy Fire bless you.}
{104}{}{Being here, you risk being punished at the gallows.}

{199}{}{I don't even know. A coincidence, I guess. Bye.}

{200}{}{Greetings, good man. How did you end up with these power plant ghouls?}
{201}{}{I don't even know. A coincidence, I guess. Who are you?}
{202}{}{Oh, I'm just a peaceful pilgrim of the Church of the Holy Fire. Our religion worships old knowledge and strives for the revival of the world. This nuclear power plant is very important to our mission. It would be very unfortunate to find out that it fell into the wrong hands.}
{203}{}{I don't think you have anything to fear. Ralph is in charge now. He's going to renegotiate the contract with the church. You'll be pleased.}
{204}{}{Hail the Atom! Should we be thanking you for this? Yes? Well, the world becomes a better place with your help. Thank you, stranger. Visit our church when you have time.}
{1204}{}{Hail the Atom! Should we be thanking you for this? Yes? Well, the world becomes a better place with your help. Thank you, stranger. Visit our church when you have time.}
{205}{}{Definitely. Goodbye.}

{250}{}{So, you're the reason our plans fell apart like the Old World? Why are you doing this?}
{251}{}{I don't like you, or your 'church'.}
{252}{}{You don't like the idea of Rebirth? A new beginning for civilization? Or you don't like our church and its symbols? Its ceremony? In either case, you're just an egocentric fool. An atomic nonentity with an inflated ego. The Church gave Knowledge to the world. With our help, light was brought into homes and people were taught forgotten literacy. And you? What are you trying to achieve?}
{253}{}{Because of your "rebirth," my home was attacked, and my people enslaved. That's enough.}
{254}{}{Oh, so we're dealing with base vengeance. In that case, we have nothing more to talk about. Base animals don't understand speech, only the whip. Get back into the desert and live your wild life like a savage. There's no place for people like you in the New World.}
{255}{}{Not before I beat the crap out of you, saint.}
{256}{}{With pleasure. I'd rather not set my eyes on this den of crime and sin ever again.}
{257}{}{Ralph paid less.}
{258}{}{So caps are your guide and moral compass? In that case, you're an egocentric fool. The Church gave Knowledge to the world. With our help, light was brought into homes and people taught forgotten literacy. What will a handful of caps in your pocket give to this city?}
{259}{}{I just fulfilled a deal. And the world was built on deals.}
{260}{}{Perhaps. Or perhaps the Old World fell because of the greed of your kind. And that's why people like you have no place in the New World. From now on, your presence in the city is not welcome by the Church of the Holy Fire. You will be better off to leave at once. Consider yourself warned.}
{261}{}{Not before I beat the crap out of you.}
{262}{}{With pleasure. I don't want to stay in a city run by tyrants anymore.}
{263}{}{You'll never know, dead man.}
