{100}{}{You see a junk dealer in front of you.}
{101}{}{You see a short man in ridiculous clothing. A helmet with numerous gadgets is awkwardly perched on his head.}

#Floating Lines
{110}{}{Best quality junk around!}
{111}{}{I'll find parts for any device.}
{112}{}{Ancient stuff was truly remarkable.}
{113}{}{Buy drumsticks, you never know when you might need them.}
{114}{}{If your toaster's acting up, bring it to me.}
{115}{}{The hardest part is finding intact light bulbs.}
{116}{}{Rusty, but it works.}
{117}{}{Got a manual for a Mr. Handy.}
{118}{}{Buy from me so you don't have to scavenge through dangerous ruins.}
{119}{}{Turn away for one second, and something just vanishes from the counter. Damn it.}

#First Dialogue
{200}{}{Come on over, senor! Junk and scrap - that's what you need. And you'll find it all in my shop.}
{1200}{}{Come on over, senorita! Junk and scrap - that's what you need. And you'll find it all in my shop.}
{201}{}{Wow, you've got quite the selection of junk here.}
{202}{}{}
{203}{}{Not junk, no-no! Everything here is essential. Take a closer look. Maybe you need these rusty spoons? Or do you prefer eating with dirty hands? Then you might be interested in this toaster. The button sticks a bit, but it definitely works. Or maybe you need...}
{204}{}{Hey, slow down, man. Let me figure it out myself.}
{205}{}{Shut up, you stupid mole rat. I can't hear myself think.}
{206}{}{Oh, by the way. I wanted to warn you that I've raised prices since all that commotion at the Cathedral. The whole market's raised prices.}
{207}{}{Why?}
{208}{}{Caps were Aaron's idea. His church kept the rate steady. But now there's no church, and caps are losing their value. We might have to ditch them altogether soon.}
{209}{}{I see. So it's the right time to stock up on essentials.}

{210}{}{Picked out anything yet?}
{1210}{}{Picked out anything yet?}
{211}{}{No, maybe another time.}
{212}{}{Can I take a closer look?}

#Questions
{220}{}{Where do you get these things?}
{221}{}{Usually brought in by scavengers, sometimes by caravanners. But I don't ask where they get them from.}
{222}{}{I suppose none of this is stolen too.}
{223}{}{I guess I could've guessed that.}

{224}{}{Who needs this junk when there's plenty of it in the ruins?}
{225}{}{Want to scavenge the ruins and find it yourself? Be my guest! Just don't forget about the radiation, beasts, raiders, cave-ins, and all the other hazards that could leave nothing but a wet spot of you. I don't just sell this stuff; I also repair it so it can serve its new owner for at least a little while.}
{226}{}{I think I've heard enough about this.}
{227}{}{Maybe I'll take a closer look at your wares.}

{228}{}{You're nuts. This stuff was obsolete 90 years ago.}
{229}{}{Got better sources for stuff? I'd love to see them. Though recently, there've been more caravans from the south. They bring actual new things.}
{230}{}{Whatever. Stop wasting my time with idle chatter.}
{231}{}{Okay, I'll keep that in mind.}

#Quest to Find Vault 27
{240}{}{Have you come across items from the Vaults?}
{241}{}{Vaults? What are you... Ah, I see! Vault-Tec Vaults - Legendary. They say some of our ancestors lived there after the Great War. But it's been so long that nobody knows where those Vaults are anymore.}
{242}{}{Who might know?}
{243}{}{You need to go to the Followers of Fire. They have so much knowledge in their library that they don't even know what to do with it all. Maybe they've got the coordinates of the Vaults. But they won't share without a good reason.}
{244}{}{What about scavengers?}
{245}{}{Heh, you think a scavenger worth his salt would reveal the location of a Vault? Legend has it there's a damn treasure trove of relics in them! But if you're a chatty type, go visit Bob in the slums. He's one of the oldest scavengers in Phoenix.}
{246}{}{Got it.}

#Consultation on Items
{250}{}{I need advice on old items.}
{251}{}{That's my life - things from the Old World. But my knowledge costs a few caps.}
{252}{}{[}
{253}{}{]}
{254}{}{Never mind. Maybe another time.}
{255}{}{Now look at another item.}
{256}{}{Enough talking about old stuff. Time to do something more relevant.}
{257}{}{Take care.}
{258}{}{Tell me about your wares.}
{259}{}{Of course, I'll pay.}


{260}{}{What exactly are you interested in?}
{261}{}{[Music Box]}
{262}{}{It's amazing that the mechanism still works. Kids would definitely love this.}
{263}{}{[Atomic Clock]}
{264}{}{Wow, it's rare to see a pocket watch in working condition. And this brand was always known for quality. Plus, an atomic battery lasts for decades. If the Tinsmiths were here, they'd snatch this thing up.}
{265}{}{[Snow Globe]}
{266}{}{Snow! I've never seen real snow, except on a few mountain peaks in the distance. Any rich person would pay a fortune for something like this. You know, I could find a use for this trinket.}
{267}{}{[Medal of Valor]}
{268}{}{Operation Anchorage... I read about that slaughter in some old newspapers. It seems the old U.S. was proud of their victory back then. I don't even know who would care about such a find now. Do you know any die-hard patriots of "Murica"? I don't.}
{269}{}{[Ranger Star]}
{270}{}{Looks really old... Arizona Ranger? I've heard their base is to the west. But I don't know exactly where.}
{271}{}{[Holy Book]}
{272}{}{I think this is a religious book. The Followers of Fire would definitely be interested in it.}
{273}{}{[Photograph]}
{274}{}{A photo of a big explosion? A nuke! So, this is how it looked... Scary. You shouldn't show this to the common folk. Better find a bald-headed old history buff if you want to discuss the Great War.}
{275}{}{[Tooth with Crown]}
{276}{}{It's just a tooth with a crown. Let me look at it under a magnifying glass... Hmm... No, there's something here. I need a microscope... Hmm... Wow. This isn't just a crown; it's some kind of chip. Or a magnetic key. Or maybe a data storage. Too complex for me. Only the Tinsmiths understand such advanced tech.}
{277}{}{[Arizona Flag]}
{278}{}{One of the Old World's flags. Mostly these flags have rotted away, but this one is surprisingly well-preserved. They'd be great for waving around by colonists up north. But we have few people who remember the old days left in our city.}
{279}{}{[Game Disk]}
{280}{}{Looks like a regular holodisk. But it seems to have a program on it, not data. Try inserting it into a working computer. Your Pip-Boy might not have enough power for this.}
{281}{}{[My Portable Pip-Boy]}
{282}{}{Hmm, it's the first time I've seen such a compact computer... Wait, there should be a section with output data... Hmm, Pip-Boy, model 2000, serial number... Wow, this is straight from Vault 27! One of those Vault-Tec Vaults they talk about in legends. So it does exist.}
{283}{}{[Pre-war book]}
{284}{}{A rare find. A valuable source of pre-war wisdom - that's what the Followers of Fire say about them. They're the ones who mostly buy these. Not many people in Phoenix can read. And the knowledge in these books doesn't really help the common folks.}
{285}{}{[Can of Coffee]}
{286}{}{You're in luck. These are coffee beans. They used to make a popular drink from them in the Old World. And now coffee has become so rare that it's only served to wealthy clients in the casino across the street.}
{287}{}{Can you tell me where to get batteries for a bike?}
{288}{}{Oh, that's a very rare and expensive thing these days. I heard the Tinsmiths in Two-Sun might be actually making them now though. Also, ask the ghouls at our power plant. For a while, they were getting batteries from junk colonies like Garage City. I think you can still find them on your own in the ruins where scavengers haven't picked things clean.}

{289}{}{The trader has lowered their prices by 5%.}
{290}{}{You might be interested in this. Look, if you shake it, it's like it's snowing inside...}
{291}{}{A snow globe! I've never seen real snow, except on a few mountain peaks in the distance. Any rich person would pay a fortune for something like this... Hey, listen, why don't you sell me this trinket? You won't need it.}
{292}{}{No way! I just needed to know what it is. That's it. Goodbye.}
{293}{}{Let me think about it. Meanwhile, let's deal with other things...}
{294}{}{Take it for free. I'm just glad to clear out some of the junk in my backpack.}
{1294}{}{Take it for free. I'm just glad to clear out some of the junk in my backpack.}
{295}{}{Seriously? You're just giving it to me? Thanks. If you need old stuff, come straight to me. I'll lay out the best stuff at the best prices.}
{296}{}{I'll keep that in mind. See you.}
{297}{}{You know, getting this was a lot of work. I'll give it to you for 350 caps. Not a cap less!}
{298}{}{That much? Phew... It'll be hard to find a buyer, but there's still a chance. Fine, here's 350 caps. Now give me the snow globe. (grabs the globe and stares at it mesmerized) Oooh...}
{299}{}{Be careful with that... Ah, whatever. Goodbye.}

#Attack on the Followers
{300}{}{Did you see the attack on the Followers in front of the casino?}
{301}{}{Yeah. Some gang attacked the monks. Desperate guys. Why do you care?}
{302}{}{Aaron asked me to investigate it.}
{303}{}{Aaron himself, you say? You've got guts. Coming to the market, questioning people, lying about our great leader. I've already told the Followers everything, and several times at that. Get out of here, I'm not telling you anything.}
{304}{}{Sorry for bothering you.}
{305}{}{I don't care how many times you've given statements. NOW you're going to tell ME.}
{306}{}{Alright, alright... damn you...}
{307}{}{Now, how did it happen?}
{308}{}{Take it easy, Aaron really did send me.}
{309}{}{You don't believe me? I'm a trusted person around this city.}
{310}{}{Don't flatter yourself, wanderer.}
{311}{}{You'll pay for your words someday.}
{312}{}{My apologies. No more of this.}
{313}{}{EITHER you tell me, OR I'll break your arm.}
{314}{}{Well, the monks were peacefully walking down the street. Suddenly, people in balaclavas burst out of several alleys. There were about five of them, I think. They were mostly shooting with submachine guns. They killed the monks and then quickly disappeared back into the alleys. These guys planned the attack well.}
{315}{}{I see. But if you're hiding something, it'll cost you dearly.}
{316}{}{Thanks, you've been very helpful.}
{317}{}{The situation is becoming clearer.}
{318}{}{Things are coming into focus. Time to talk to Aaron about this.}
