{100}{}{You see a preacher.} 
{101}{}{You see one of the Followers of Fire, fully absorbed in leading the Mass.} 
{102}{}{The preacher is too focused on the Mass to notice you.}

{110}{}{This is a test from the Great Atom. Stay calm, everyone.} 
{111}{}{I'm certain the Holy Fire will shine upon our cathedral again soon.} 
{112}{}{Don't let the darkness distract you from your devotion. It's no obstacle for us.} 
{113}{}{Look at yourselves, afraid of a little darkness. And you call yourselves true believers!}

#Prayer (see "Canticle to Leibowitz" by W. Miller, page 22)
{120}{}{...Let us begin the prayer, brothers and sisters!}
{121}{}{Let us praise the Holy Fire, for it has purified the world in order to restore it to its original form.}
{122}{}{A spiritu fomicationis, Domine, hibera nos.}
{123}{}{From the lightning and the tempest, Holy Fire, deliver us.}
{124}{}{From the scourge of the earthquake, Holy Fire, deliver us.}
{125}{}{From the epicenter and hypocenter, Holy Fire, deliver us.}
{126}{}{From plague, famine, and war, Holy Fire, deliver us.}
{127}{}{From the place of ground zero, Holy Fire, deliver us.}
{128}{}{From the rain of the cobalt, Holy Fire, deliver us.}
{129}{}{From the rain of the strontium, Holy Fire, deliver us.}
{130}{}{From the fall of the cesium, Holy Fire, deliver us.}
{131}{}{From the curse of the Fallout, Holy Fire, deliver us.}
{132}{}{From the begetting of monsters, Holy Fire, deliver us.}
{133}{}{From the curse of the Mutation, Holy Fire, deliver us.}
{134}{}{A morte perpetua, Domine, libera nos.}
{135}{}{Peccatores, te rogamus, audi nos.}
{136}{}{That thou wouldst pardon us, we beseech thee, hear us.}
{137}{}{That thou wouldst bring us truly to penance, te rogamus, audi nos.}
