{100}{}{You see a tramp.}
{101}{}{This vagrant wanders the square aimlessly.}
{102}{}{This ragged bum chants praises to the church.}
{103}{}{This goner can barely shuffle through the area.}
{104}{}{This refugee wanders the square aimlessly.}

#Floating lines
#- beggar
{110}{}{Just leave me alone.}
{111}{}{I don't know what to do anymore.}
{112}{}{People like me don't stand a chance in this city.}
{113}{}{Mind if I just lie down here?}
{114}{}{I want out of this life, but I can't seem to escape it.}
{115}{}{The Phoenix rises... but I keep falling.}
{116}{}{Got any food for a poor soul down here?}
{117}{}{Spare some caps? I swear, I'll pay you back.}
{118}{}{I need medicine for the baby. Please help me out.}
{119}{}{I'm starving. Even a rat's tail would do.}
{120}{}{Want to join me? Sorry, no room left.}
{121}{}{I'm waiting on the fanatics to bring us some food.}
{122}{}{The cathedral gives out scraps sometimes, after dinner.}
{123}{}{But you gotta kiss the priest's feet for it.}
{124}{}{Hail the Fire! We're all brothers, right? See, I believe too.}

#- adept
{130}{}{I want to become an acolyte, but they won't take me.}
{131}{}{I swear, I'm going to be an acolyte someday!}
{132}{}{You've got to pray a lot if you want to get accepted into the church.}
{133}{}{Peace! Love! Holy Fire!}
{134}{}{Do you believe in something too?}
{135}{}{What do YOU believe in?}
{136}{}{Hail the Holy Fire!}
{137}{}{Hail Phoenix! Hail Aaron!}
{138}{}{I love Aaron! Hail Aaron, Lord of Phoenix!}
{139}{}{My life belongs to Saint Aaron.}

#- sick or disabled
{150}{}{I came here hoping to be healed of my illness.}
{151}{}{There's no cure for what I've got, but the monks promised they'd help.}
{152}{}{People say the monks have ancient healing powers.}
{153}{}{I pray to Aaron every day to heal these wounds.}
{154}{}{I gave all my savings to the church, but my illness still lingers.}
{155}{}{The monks are healing me with prayers. I felt a surge of strength! Wait... no.}
{156}{}{The monks told me I need to cleanse my soul, to give everything to the church.}
{157}{}{Guess I'm just worthless, huh?}
{158}{}{I keep asking other believers for help.}
{159}{}{Only the Followers of Fire can heal like before the Great War.}

#- refugee
{170}{}{I came here hoping the Followers of Fire would take me in.}
{171}{}{People say the church helps refugees, but that's not the case.}
{172}{}{We escaped the raiders, but the church still won't let us in.}
{173}{}{Aren't the Followers of Fire supposed to help people like us?}
{174}{}{The monks here look pretty well-fed. Maybe something's wrong with them.}
{175}{}{The only place I feel safe is near the cathedral.}
{176}{}{These fire worshippers are a strange bunch.}
{177}{}{They keep promising heaven on earth.}
{178}{}{They tell us we should be afraid, but I don't get what of.}
{179}{}{Preaching is easy when you've got food to hand out.}
