{100}{}{You see a passerby in front of you.}
{101}{}{You see a mugger.}
{102}{}{You see a passerby in stealthy clothing, trying not to draw attention to himself.}
{103}{}{You see a street mugger. Best to steer clear.}
{104}{}{Are you following me?}
{105}{}{The mugger cowardly ran away.}

# Dialogue
{200}{}{(Walking down the street, you notice that you're being followed. A young man in nondescript clothing follows you hesitantly for a while. As you enter a deserted alley, he runs up and pulls out what appears to be a pistol.)}
{201}{}{[More]}
{202}{}{Stop! Gimme all your caps or I'll shoot.}
{203}{}{Hey, take it easy...}
{204}{}{Caps! Now! Or I swear I'll shoot! (His face is covered with a scarf, and you see the desperation in his eyes.)}
{205}{}{Caps! Now!}
{206}{}{Try and take them, bitch.}
{207}{}{Wha... It's a gun. It's loaded. You understand? Don't make me shoot.}
{208}{}{Then you'll have to. I'm attacking!}

{210}{}{Here's 30 caps, just don't shoot.}
{211}{}{Come here. (Takes the caps and looks around) Now walk away. Turn around and you're dead.}
{212}{}{Whatever you say...}
{213}{}{[Turn around and attack the mugger]}
{214}{}{I only have one cap. Here, take it.}
{215}{}{Here's two caps. That's it, seriously.}
{216}{}{Here's three caps. That's all I have.}
{217}{}{Damn... Okay. Now walk away. Turn around and you're dead.}
{218}{}{Don't shoot. Here's all the caps I have.}

{220}{}{I don't have any caps, seriously.}
{221}{}{Don't make me mad, bitch, HAND OVER YOUR CAPS!}
{222}{}{I really don't have any caps. Check my pockets if you want.}
{223}{}{Damn... (Looks around nervously) So... Walk away and don't look back.}
{224}{}{Stay back or I'll shoot!}
{225}{}{Whoa, calm down.}
{226}{}{Then shoot, coward.}
{227}{}{You're pushin' it, fool.}

{230}{}{Listen, are you a guy or a chick?}
{231}{}{Wha... Don't piss me off or I'll SHOOT!}
{232}{}{Seriously. I can't tell because of those rags.}
{233}{}{One more word and you're dead. HAND OVER THE CAPS!}
{234}{}{Uh, maybe we can talk this out?}
{235}{}{Then go for the head. It's your only shot.}
{236}{}{Damn, who the... (The mugger starts to get nervous and looks around in confusion) So... Don't turn around. Or I'll shoot. Seriously, I'll shoot!}
{237}{}{Sure, sure, I believe you...}
{238}{}{Then shoot, coward, shoot!}
{239}{}{You're making a big mistake, kid. Do you even know who I am? I took down the undefeated Mario in the ring.}
{240}{}{Damn... I really don't wanna shoot you. Alright, get moving, and don't look back. Got it?}
{241}{}{Of course, you're the boss.}
{242}{}{Not so fast. Time to pay the piper...}
{243}{}{How dare you stop a peaceful monk? The Punishment of the Nuclear Flame will consume you, worm!}
{244}{}{You're pathetic. We highwaymen hang people like you on road signs and bleed them dry.}
{245}{}{You should know, you're targeting a ranger. You won't get away with this.}
{246}{}{You'll be dead. Not me.}
