{100}{}{You see a rugged mercenary.}
{101}{}{You see a strong man, clad in heavy armor.}
{102}{}{You've lost your personal bodyguard.}
{103}{}{Time's up; your bodyguard has returned to the caravan site.}

{110}{}{This caravan site? Probably the safest spot in the whole city.}
{111}{}{Welcome to the marketplace. They won't kill you here, but they'll pick your pockets clean before you even notice.}
{112}{}{Watch yourself. The Cardinals gang runs these slums, and if you get into trouble, I won't be able to bail you out.}
{113}{}{Up ahead is an old power plant, still kicking thanks to the local ghouls keeping it running.}
{114}{}{This here's the Cathedral of the Holy Fire. Sorry, but I'm not stepping foot inside.}

#Dialogue without accompaniment
{200}{}{Hey, you're new in town, aren't you?}
{201}{}{Yeah. I'm pretty curious to find out what's in store for me here.}
{202}{}{I'll bet! Phoenix is huge, the largest city pretty much anywhere.}
{203}{}{It sounds like there's a "but" coming.}
{204}{}{Great, can't wait to explore it.}
{205}{}{But I gotta tell you, be careful; it's not the best place for 'exploring'.}
{206}{}{Why? Why not?}
{207}{}{Really? Aren't you just exaggerating to get something from me?}
{208}{}{What's it to you?}
{209}{}{Whoa, don't get so worked up. I handle all the stress around here. Maybe you'd like a tour of the great Phoenix?}
{210}{}{Maybe. Might be worthwhile.}
{211}{}{Of course!}
{212}{}{Then listen, be cautious; it's not the best season for this.}
{213}{}{The city's been unsettled for years now. Some areas are controlled by thugs, and there are muggings and robberies even in the main market. It's safer not to wander the streets alone.}
{214}{}{What are you suggesting?}
{215}{}{I take it you know how to deal with city's dangers?}
{216}{}{I escort important people within the city. The mere sight of an armed guard makes the trash scatter. But you seem to have security already. If you're ever left unprotected, contact us. I'm a professional.}
{217}{}{I'll keep that in mind. Bye.}
{218}{}{I escort important people within the city. The sight of an armed guard like myself is enough to make the scum leave you alone. If you need security, come to me. It's what I do.}
{219}{}{I'll think about it. For now, I've gotta go. Bye.}
{220}{}{I can take care of myself.}
{221}{}{I'm sure! But if you change your mind, you know where to find me.}
{1221}{}{Oh, I believe you, lady! But if you change your mind, you know where to find me.}
{222}{}{I'll think about it. Bye.}
{223}{}{It seems every big city starts with a scam. I'm leaving.}
{224}{}{Consider me interested. How much do your services cost?}
{225}{}{It'll cost you }
{226}{}{ caps per hour. And no haggling on that price.}
{227}{}{I can't afford that. Goodbye.}
{228}{}{Alright, here's the caps.}

{230}{}{Phoenix has got your back, pal. I'll watch your six.}
{231}{}{I'm all yours.}
{232}{}{With me around, you won't need a doctor or a priest.}
{233}{}{I'll be damned if I let anything happen to you.}
{234}{}{Relax, every dog in this town knows who I am.}
{235}{}{Don't worry, I know this city like the back of my hand.}
{236}{}{Now kick back and enjoy the ride. I've got you covered.}

{239}{}{Cool. Now I've got my own bodyguard.}

{240}{}{Do you need a bodyguard? I recommend one, or a hefty grenade launcher like this.}
{241}{}{Yeah. Bye.}
{242}{}{Are you still escorting people?}

#Escort Dialogue
{250}{}{Uh-huh?}
{251}{}{All clear ahead.}
{252}{}{The way looks clear.}
{253}{}{Don't wet your pants. Nothing to fear here.}
{254}{}{Relax, I'll get you out of any mess.}
{255}{}{What?}
{256}{}{Got a problem?}
{257}{}{Yeah?}
{258}{}{This area is run by the Cardinals gang. If you value your life, I'd suggest leaving right now.}
{259}{}{Alright, let's go.}

{260}{}{Wait here until I get back.}
{261}{}{Sure, as you say. But if time runs out, I'll head back to the caravan site.}
{262}{}{Don't go anywhere.}
{263}{}{Follow me.}
{264}{}{You got it, Chief.}
{265}{}{Go ahead.}
{266}{}{I no longer need your services.}
{267}{}{Are you sure? No refund for the remaining time.}
{1267}{}{Are you sure? No refund for the remaining time.}
{268}{}{Yes, you're free. If I need you, I know where to find you.}
{269}{}{Okay, stick around a bit longer.}
