{100}{}{You see Diego's man.}
{101}{}{You see Miguel.}
{102}{}{You see a charming man with a mustache. He looks strangely familiar.}
{103}{}{You see Miguel, your uncle who once escaped from the Villa.}

{110}{}{Hold up, who are you?}
{111}{}{Who are you?}
{112}{}{Who let you in here?}
{113}{}{What are you doing here?}
{114}{}{One more step and I'll call security.}
{115}{}{Don't tell me you're hiding from security.}
{116}{}{Your face looks oddly familiar.}
{117}{}{Do we know each other?}
{118}{}{Hey, do we know each other?}
{119}{}{}

{120}{}{I'm busy with, uh, important research. Yeah, that's it.}
{121}{}{I'm doing science here, kid.}
{122}{}{What do you know about plasma accelerators? I thought so...}
{123}{}{Pour some tequila and make yourself useful.}
{124}{}{If you bug me, I'll throw you out onto the casino floor.}
{125}{}{I've been doing a lot of research. You wouldn't understand.}
{126}{}{Today I'm going to get blackout drunk!}
{127}{}{}
{128}{}{}
{129}{}{}

#First meeting
{200}{}{Hey, who let you in? This place is off-limits... }
{201}{}{?! I'll be damned, you're }
{202}{}{, what...}
{203}{}{Uncle Miguel, is that you? Long time no see!}
{204}{}{Oh, how you've grown! I didn't recognize you at first. You still have your father's features... But, what a surprise! What brings you here?}
{1204}{}{Oh, how you've grown! I didn't recognize you at first. You still have your mother's features... But, what a surprise! What brings you here?}
{205}{}{I'm looking for my father. It's a long story. In short, he and the other Villa residents were taken by slavers.}
{206}{}{What?! That's bad news. But honestly, I don't know anything about it... Either way, you'd be smart to skip town while you still can.}
{207}{}{But we just reunited... Why would... Uncle Miguel, I walked half the wasteland just to get here!}
{1207}{}{But we just reunited... Why would... Uncle Miguel, I walked half the wasteland just to get here!}
{208}{}{You got any clue what's going on around you, kid? This ain't the Villa-Phoenix plays by different rules. I don't want you stirring up trouble. If the boss catches wind, it'll be bad news for both of us.}
{209}{}{The boss won't catch anything... Don Diego is gone. He had an "accident".}
{210}{}{Is this your doing? Idiot! Diego was my lifeline in this city. What am I supposed to do now?}
{1210}{}{Is this your doing? Fool! Diego was my lifeline in this city. What am I supposed to do now?}
{211}{}{It seems like he you under his thumb a bit...}
{212}{}{You shouldn't have come here. Everything's hanging by a thread. Sure, Diego was a criminal, but he built this city. Now what? The Fire Worshippers will probably take over the casino. Do you even get what that means? By the look in your eyes, I can tell you don't.}
{213}{}{It doesn't matter. Your brother? My Father? Are you gonna help me find him?}
{214}{}{Look, I'm comfortable here and I don't want any trouble. I haven't seen or spoken with your father in years. Look for help elsewhere. Maybe the Followers of Fire. They hire mercenaries all over Arizona for their missions.}
{215}{}{Fine. Goodbye, *Uncle* Miguel.}
{216}{}{Don't worry about it. I'll be leaving Phoenix soon anyway; my business here is done.}
{217}{}{Done huh? I've a feeling troubles have just got started for the Villa. This whole slaver business won't just go away. I wonder how the Villa will handle it...}
{218}{}{We'll manage. Goodbye, Uncle Miguel.}
{219}{}{Don't worry about it. Don Diego and I are on excellent terms.}
{220}{}{Is that right? You're a lot sharper than your old man. He didn't want to hear about the new opportunities the world had for the Villa. And here you are, already cozying up to one of the city's big players. Impressive.}
{221}{}{So will you help me find my father?}
{222}{}{It's time for me to continue my search. Goodbye, Uncle Miguel.}
{223}{}{Are owned by Don Diego? Like his slave or something?}
{224}{}{Slave? No... No, it's not like that. But if he wanted, he could sell anyone into slavery. He's a big deal here, running this whole area.}
{225}{}{Even more reason. Maybe he can help find my father?}
{226}{}{You're doing fine. It's time for me to head back to the Villa; my business here is done.}

{230}{}{Hey, who let you in? This place is off-limits... }
{1230}{}{Hey, who let you in? This place is off-limits... }
{231}{}{?! Damn, if it isn't my favorite nephew! It's good to see you, especially after all that's happened.}
{1231}{}{?! Damn, if it isn't my favorite neice! It's good to see you, especially after all that's happened.}
{232}{}{Long time no see, Uncle Miguel.}
{233}{}{And you've grown. I remember you barely reaching the top of the table. A lot has changed since then.}
{234}{}{Oh yeah. And I've got news. About Villa, about father, about the raiders...}
{235}{}{Wait, to be honest, I knew about you and your mission. I even wanted to step in and help while you were in Phoenix. But I hesitated. It felt like Villa was behind me, and now I regret being so careless.}
{236}{}{It really has. Villa's not what it used to be.}
{237}{}{It needed change! I've heard a bit about how you managed to save the Villa against all odds, and I'm amazed! You know, I thought those old fogeys would eventually lead Villa to ruin. And they almost did, if not for you.}
{238}{}{It needed change! ...But it seems you couldn't convince those musty old men of the need for real change, huh? I see it in your eyes. Villa needs people like you and me.}
{239}{}{Sounds like you never had much faith in the Villa.}
{240}{}{That's why I left. I became a man without a home, severing all ties with the past. Living out here, in the real world, you don't think about the past. You need to step outside your box and see the whole picture to understand this. And you did. Well done.}
{241}{}{Thanks, Uncle Miguel.}
{242}{}{You're welcome. But it's time for you to go save the world. I'd prefer if people at the casino didn't know about my past.}
{243}{}{I see. Goodbye Uncle Miguel.}
{244}{}{Maybe you saw the 'real' world. But you forgot the most important part, your family, leaving them to fend for themselves when you could have helped.}
{245}{}{Fair point. I won't argue. But it's time for you to go save the world. I'd prefer if people at the casino didn't know about my past.}
{246}{}{I see. Goodbye Miguel.}

#Re-dialogue
{300}{}{Pretend like you don't know me while we're at the casino.}
{301}{}{Goodbye.}

{310}{}{Do you know what happened at the Villa?}
{311}{}{I caught some news.}
{312}{}{Do you know where our people are being held?}
{313}{}{I don't know exactly. The Followers of Fire in the Cathedral might have that information.}
{314}{}{What do the Followers have to do with it?}
{315}{}{Mercenaries use slaves, and they're essentially working for the Followers, who are the real backers of the whole slave trade. Most folks don't see it though. But just look at the Flagstaff colony funded by the Cathedral or the Tinsmiths who are under contract with the Followers. Slaves are in demand everywhere these days.}
{316}{}{Your family is being forced to do slave labor, and you're talking about it so calmly?}
{317}{}{The whole thing is my brother's fault. If he had listened to me in the beginning, this tragedy would never have happened.}
{318}{}{I see. Let's change the subject.}

{320}{}{Tell me about your escape from the Villa.}
{321}{}{ESCAPE? Is that what my brother's calling it? I knew he'd twist things to make me look bad... Listen, dear nephew, I didn't want to leave, I was KICKED out. And honestly, I'm glad.}
{1321}{}{ESCAPE? Is that what my brother's calling it? I knew he'd twist things to make me look bad... Listen, dear niece, I didn't want to leave, I was KICKED out. And honestly, I'm glad.}
{322}{}{Why did you get kicked out?}
{323}{}{After our father died, your father, Andres took over the Villa as the elder brother. He stuck to tradition, but I had new ideas. Even then I knew the Villa had to change.}
{324}{}{Why?}
{325}{}{Even back then we ran into wasteland raiders, rangers, and caravans from neighboring towns. We knew there was life outside the valley. But Andres kept this hidden from the rest of the residents, just like the elders before him.}
{326}{}{And you argued about this?}
{327}{}{We disagreed on Villa's future. I wanted to make connections with nearby towns, trade, use pre-war tech for farming, but he wouldn't consider any of it. He said it wasn't the time, that I was possessed by the devil... In the end, I said I'd reveal the truth to people, and he kicked me out of the settlement.}
{328}{}{What happened next?}
{329}{}{I left, reached the next town... Garage City. There was an active scavenger guild, diggin' up stuff in their 'mine', and I made good money. I also learned about old tech. When the ruins started running dry, I headed straight to Phoenix.}
{330}{}{Go on.}
{331}{}{Here I saw all the grandeur of civilization! But even here, people don't appreciate old things. I was lucky Don Diego hired me. He needed someone with knowledge of old tech to help set up the casino. I've been here ever since.}
{332}{}{And now, all you do is drink and indulge in pleasure?}
{333}{}{Hold on, dear nephew. I've worked hard enough to live comfortably. And my machine is always ready to go.}
{1333}{}{Hold on, dear niece. I've worked hard enough to live comfortably. And my machine is always ready to go.}
{334}{}{Machine? What kind of machine?}
{335}{}{Are you talking about the 'machine' in your pants?}
{336}{}{Uh... How should I put it... I do some technical work for Don Diego.}
{337}{}{Like what?}
{338}{}{Sorry, but the boss wouldn't like me talking about this.}
{339}{}{I see. Let's change the subject then.}
{340}{}{Uh, does this story have an end?}
{341}{}{"Old tech"... you just mean slot machines, don't you?}
{342}{}{Hehe, you're smart, nephew. Let's just say Diego likes to be in the know about anything that brings caps, power and influence. I was a significant find for him.}
{1342}{}{Hehe, you're smart, niece. Let's just say Diego likes to be in the know about anything that brings caps, power and influence. I was a significant find for him.}
{343}{}{And what kind of work did you do for him?}
