{100}{}{You see the Inquisitor.}
{101}{}{You see a man in a worn cassock, scanning the ruins with intent, searching for someone.}
{102}{}{You will perish by the Holy Fire's decree.}
{103}{}{Tremble before the Holy Fire, scavenger.}
{104}{}{Praise the Holy Fire.}

#First dialogue
{200}{}{Halt. By the Holy Fire's command, explain what brings you here.}
{201}{}{What I do doesn't concern you. Get outta my way, you crazy cultist.}
{202}{}{Blasphemy and heresy! Beg the Holy Fire for mercy, or face its wrath.}
{203}{}{Big talk for someone with a spear. You sure you can back it up?}
{204}{}{I see you're serious. Fine, I'll be on my way.}
{205}{}{Just scavenging for some useful stuff.}
{206}{}{Then scavenge elsewhere. Your filth stains the Holy Fire's work.}
{207}{}{Why the hostility?}
{208}{}{Leave now, or face the Holy Fire's retribution from my spear.}
{209}{}{Is that a spear or a rusty pipe? Move aside, cultist.}
{210}{}{Alright, alright...}
{211}{}{You again? In the Holy Fire's name, leave this place.}
{212}{}{Alright, alright...}

{220}{}{I'm looking for someone. Have you seen anyone around here?}
{221}{}{Perhaps. What's your connection to this spy?}
{222}{}{Spy? You've got it wrong. We just sell scrap from the ruins. What did he do?}
{223}{}{Keep to your scavenging, filth, and stay out of trouble.}
{224}{}{Uh, okay...}
{225}{}{Filth? Again? I've put up with your crap enough, you sanctimonious rat.}
{226}{}{I don't believe your lies. Kneel, wretch, before the Holy Fire.}
{227}{}{Hands off...}
{228}{}{Spy? No, we were just scavenging the ruins together.}
{229}{}{Spy? You've got it all wrong.}
{230}{}{Is that so? Without proof, I suppose I must let you go... for now.}
{231}{}{Um, thanks.}
{232}{}{Speak of this to no one. And remember, fear the Holy Fire.}
{233}{}{Yes, yes, of course...}
{234}{}{Uh oh...}

{250}{}{Initiate? What brings you here?}
{251}{}{I believe we seek the same person. Don't impede my mission, or face Aaron's wrath.}
{252}{}{Aaron sent you? That changes things. We won't hinder you.}
{253}{}{Thank you brothers.}
{254}{}{Just searching for relics. Until next time, brother.}

{260}{}{Initiate? Hmm, I don't recall seeing you before. What's your purpose here?}
{261}{}{Fool! Mistaking me for an initiate will be your final error!}
{262}{}{Just looking for ancient relics. Until next time, brother.}
{263}{}{Initiate? No, I'm not sure what-}
{264}{}{It's a spy! Seize him, brothers!}
{265}{}{Oh crap...}
