{100}{}{You see Arthur Carrington.}
{101}{}{You see the archaeologist you met in Vault 27.}
{102}{}{Thanks for everything! Meet me in Casa Nueva.}
{103}{}{Thanks for everything! Meet me at the Villa.}

#First dialogue
{200}{}{Here comes my savior. I'm glad to see you.}
{201}{}{What are you doing here? I thought after the vault you'd head to the Cathedral of Fire and immerse yourself in science.}
{202}{}{So I did. But the Cathedral of Fire was destroyed. I don't know what happened there, but the fire worshippers are now in exile, and no one needs a scientist like me anymore.}
{203}{}{No one? Are you sure?}
{204}{}{I have one possibility. In the Cathedral library, I came across some reports of a scientifically inclined group called the Followers of the Apocalypse. Their base is in south, in a place called Casa Nueva, but there wasn't much information. If you know anything about them, fill me in. OK?}
{205}{}{Will do. I had some questions though.}

#Further conversation
{210}{}{So what now?}
{211}{}{Nothing. Bye.}
{212}{}{Bye.}

{220}{}{Why do you think the Cathedral of Fire collapsed?}
{221}{}{I heard they were building a nuke in the vault beneath the temple. But an accidental explosion? Almost impossible. Feels like sabotage to me. The fire worshippers had a lot of enemies, but the real shock is how someone got that far in. Must've been someone on the inside... someone they trusted.}
{222}{}{It was me.}
{1222}{}{It was me.}
{223}{}{Don't joke like that. It's hard to take you seriously sometimes, and besides, you don't need rumors spreading in the city. Trust me.}
{224}{}{Why were they building a bomb?}
{225}{}{All I know is it was made to order. So, someone or some group wanted it bad.}
{226}{}{What are you going to do now?}
{227}{}{I'll find a place that needs scientists like me. Outside of rumors about the Followers of the Apocalypse, I don't have much else to go on.}
{228}{}{Move to the Villa. We need people to help rebuild after the raid-and fresh minds that aren't stuck in old ways of thinking.}
{229}{}{The Villa, right? The one you mentioned back in the vault? I looked into it. Seems like a tight-knit rural community. The Cult of Fire actually gathered quite a bit of intel on you. I think it could be a great spot to push forward with new tech.}
{1229}{}{The Villa, right? The one you mentioned back in the vault? I looked into it. Seems like a tight-knit rural community. The Cult of Fire actually gathered quite a bit of intel on you. I think it could be a great spot to push forward with new tech.}
{230}{}{Agreed. When you get there, tell them you're from me. See you at the Villa.}
{231}{}{Take your time. I'm still going to try to learn more about the Followers of the Apocalypse.}
{232}{}{I tracked down the Followers in Casa Nueva. They'll welcome a fellow scientist like you, no problem. So go check them out.}
{233}{}{For a farm dweller, you've got an impressive amount of connections. Thanks. You're a real lifesaver.}
{234}{}{See you in Casa Nueva.}

#Further options
{240}{}{I'm going to look for a place that needs scientists like me. So far, I've only heard about the group in Casa Nueva, but... my views might not fit in there. Do you know of any other places?}
{241}{}{Move to the Villa. We need people to rebuild after the raid. And we could use fresh ideas-people not stuck in the old ways.}
{242}{}{The Villa, right? The one you mentioned in the vault? I checked into it. It's a small, closed-off community. The Followers of Fire collected a lot of intel on you. I think it'd be a great spot to push forward with new tech.}
{1242}{}{The Villa, right? The one you mentioned in the vault? I checked into it. It's a small, closed-off community. The Followers of Fire collected a lot of intel on you. I think it'd be a great spot to push forward with new tech.}
{243}{}{Agreed. When you get there, just say you're with me. I'll see you at the Villa soon.}
{244}{}{You know, this might not be the best idea. They aren't too fond of 'progress' over there. You'd probably have better luck in Casa Nueva.}
{245}{}{I'm sure Casa Nueva would welcome a fellow scientist. You should check it out sometime.}
{246}{}{I think so too. But the journey through the wasteland to get there won't be easy. Either way, maybe we'll cross paths again.}
{247}{}{Count on it. See you in Casa Nueva.}
{248}{}{Not likely. Goodbye, Arthur.}
