{100}{}{You see a guard.}
{101}{}{You see one of the cult's guards. He looks just like all the others.}

{104}{}{Someone's raised the alarm. Looks like I'll have to hold you back...}
{105}{}{Are you leaving already? Good.}
{106}{}{Stop! Who goes there?}
{107}{}{Intruder! Raise the alarm!}
{108}{}{Stop! Who's... hm, must've been the wind.}

{200}{}{Stop! State your name and purpose of visit.}
{201}{}{Sorry, brother, I'm new here and just wanted to look around.}
{1201}{}{Sorry, brother, I'm new here and just wanted to look around.}
{202}{}{Sorry, brother, I'm new and just want to look around.}
{203}{}{Why these questions, brother? Isn't my robe enough?}
{204}{}{Eh, I better get out of here...}
{205}{}{Tell your boss I have information for him.}
{206}{}{I'm here to see Ulysses Grant. Aaron himself sent me.}
{207}{}{Allow us to express our deepest respect. Go down to the lower level, Ulysses is at his post.}

{210}{}{Intruder! Raise the alarm!}
{211}{}{Damn, I'll have to shut you up!}
{212}{}{But I didn't do anything!}
{213}{}{Okay, come on in, brother.}
{1213}{}{Okay, come on in, sister.}
{214}{}{Praise the Holy Fire, brother.}
{215}{}{Thank you... brother.}

{220}{}{Leaving already?}
{221}{}{Yes, see you later.}
{222}{}{Come on in. You can find your way without us.}
{223}{}{Okay.}
{224}{}{I'm going to see the Advisor. His Holiness Aaron, Lord of Phoenix, sent me.}
