{100}{}{You see a child.}
{101}{}{You see a local kid. He smells like fish and dirt.}

{110}{}{Ranger Garth kills people like you.}
{111}{}{Don't touch me.}
{112}{}{What kind of hell are you from, huh?}
{113}{}{You talk funny.}
{114}{}{}
{115}{}{}
{116}{}{}
{117}{}{}
{118}{}{*Yawn*}
{119}{}{Z-z-z}

{120}{}{You been here long?}  
{121}{}{Where'd you come from?}  
{122}{}{Wanna play?}  
{123}{}{Know any cool places around here?}  
{124}{}{There's a monster down at the bottom of the reservoir.}  
{125}{}{If you swim in that water, you'll grow horns like a demon.}  
{126}{}{Got anything tasty on you?}  
{127}{}{Man, this fish stinks.}  
{128}{}{I'm looking for something useful.}  
{129}{}{ }  

{130}{}{That's called a "motorcycle," right?}  
{131}{}{No way! Can this thing really drive by itself?}  
{132}{}{You know old tech too, like Rufus?}  
{133}{}{Can you ride it?}  
{134}{}{Think this bike can catch fish or predict the weather?}  
{135}{}{The rangers should totally get motorcycles.}  
{136}{}{Where'd you find this bike?}  
