{100}{}{You see Pockmarked.}
{101}{}{You see a ghoul. He looks like he's in a lot of pain. If it weren't for your bike, the poor guy wouldn't have been hurt.}
{102}{}{Where'd you get your driver's license, mister? A cereal box?}
{1102}{}{Where'd you get your driver's license, woman? A cereal box?}
{103}{}{Oh shit!}

{110}{}{Oooh! How painful!}
{111}{}{Oh! My hip joint!}
{112}{}{Anyone seen my gallbladder?}
{113}{}{My spine! My spine!}
{114}{}{Doctors...}
{115}{}{Anyone got a stimpak?}
{116}{}{Why me?}
{117}{}{First a truck, then a pickup, now a bike...}
{118}{}{This is getting old...}
{119}{}{}

{200}{}{Oooh, that hurt! Why am I always the one under the wheels?}
{201}{}{Oh, sorry, are you okay?}
{202}{}{Am I okay? Just a few broken bones, a cracked hip, and a torn bladder... Sure, peachy.}
{203}{}{Sorry, It was an accident.}
{204}{}{Of course not! I told those idiots we need road signs here. They never listen! Like the time I got run over by a Nuka Cola truck. Bottle caps everywhere.}
{205}{}{That's uh... awful.}
{206}{}{Caps everywhere? Damn! Imagine stumbling on that in the desert.}
{207}{}{Ugh... Look, I hate to cut this chat short, but I need help getting up. You gonna help or what?}
{208}{}{Really?}
{209}{}{Are you sure? Maybe you should lay still...}
{210}{}{Don't worry. Eventually, everything heals. Have fun out there, dude.}
{211}{}{Bye.}
{212}{}{Oops...}
{213}{}{Gonna just stand there? How about some first aid? Or mouth-to-mouth? No? Fine, I'll manage.}
{214}{}{Well, thank God. I thought you were really hurt. See you around.}
{215}{}{Ahh! Damn it, I can barely move! Serious, I'm not whining. Guess I've had worse though... Like when that Nuka Cola truck ran me over. Caps everywhere.}
