{100}{}{You see Paul.}
{101}{}{You see a very emaciated man.}

{200}{}{Nice to see you again, friend. Remember when we escaped from those super mutants? That was wild.}
{1200}{}{Nice to see you again, sister. Remember when we escaped from those super mutants? That was wild.}
{201}{}{Yeah, those were good times.}
{202}{}{I told the Brotherhood all about it, and it definitely improved their opinion of you. As thanks from me, take three stimpaks and a laser pistol with batteries. Good luck out there.}
{203}{}{Thanks. Good luck to you.}

{210}{}{Welcome aboard. How can I help you?}
{211}{}{Nothing, thanks.}

{220}{}{Remind me, what's your rank?}
{221}{}{I'm Knight Paul. I used to head the Energy Weapons Research Department. Then I was sent into the field to assist the paladins. Eventually, I got captured by super mutants.}
{222}{}{Can I get a weapon here?}
{223}{}{Contact the quartermaster. I don't have any free weapons, but... I could upgrade something for you.}
{224}{}{Enjoy your work.}
{225}{}{Thanks. I gotta go.}
{226}{}{I need to go. Goodbye.}
{227}{}{Thanks, I have to go now.}
{228}{}{Thanks for the information, bye.}
{229}{}{}
{230}{}{Will you help me save my village?}
{231}{}{Sorry, but I have duties at this port. I've had enough adventures, I guess.}
{232}{}{Do you have any parts for Power Armor?}
{233}{}{No... I'm not good with Power Armor. Give it to the quartermaster; he might have spare parts. Although if you're not on good terms with him, it won't be easy.}
{234}{}{Is there any other option?}
{235}{}{Well... they say Tinsmiths can do it. But I suspect they'll charge a hefty price.}
{236}{}{Take a look at this plasma rifle. Can it be improved somehow?}
{237}{}{It's a Winchester P94! Great weapon. I've always admired its reliability and power. It seemed like it couldn't be improved on.}
{238}{}{Go on.}
{239}{}{But you know, a man once showed me a unique upgrade for his rifle. The plasma heated up faster than usual. I think I can replicate it.}
{240}{}{Do it! Here's the rifle.}
{241}{}{No, thanks. What if you break something...}
