{100}{}{You see a sentry in front of you.}
{101}{}{You see a man in Power Armor. He looks impressive.}
{102}{}{Now is not the time to chat with the locals.}
{103}{}{?}
{104}{}{You're taking a big risk by coming back here.}
{105}{}{Greetings, brother in arms. How was the patrol?}

#First dialogue
{200}{}{Stop. State the purpose of your visit.}
{201}{}{Never mind, I'm leaving.}
{202}{}{I was traveling along the coast and just stumbled upon you. What is this place?}
{203}{}{You're better off not knowing. Move along.}
{204}{}{You guys seem a bit surly.}
{205}{}{Wait... Why the hell are you staring? We don't need troublemakers here. Get out and don't come back. Move it...}
{206}{}{Uh... Uh...}
{207}{}{Closed? Like this? Don't know.}
{208}{}{Yes. We've gone a little mad here. Not enough convolutions, huh? Our clerks should run tests on you. But I don't want to get dirty. (threateningly) Get out of here.}
{209}{}{Oh, go. I understand it. Yes.}

#Re-dialogue
{210}{}{You may pass.}
{211}{}{Thanks.}
{212}{}{Greetings, brother in arms.}
{1212}{}{Greetings, sister in arms.}
{213}{}{See you, brother.}
{214}{}{(sarcastically evaluates your armor) Come on in. The galley lookin' for a lid for a saucepan.}
{215}{}{Permission to come aboard?}
{216}{}{Why are you asking? Sure, come on in, brother.}
{1216}{}{Why are you asking? Of course, come in, sister.}
{217}{}{Thank you, brother.}

{220}{}{Can I ask you a few questions?}
{221}{}{I'm forbidden to have idle conversations, especially about our Brotherhood.}
{222}{}{I see. Well, orders are orders. Goodbye.}
{223}{}{What are you doing here?}
{224}{}{Securing the ramp, obviously. Outsiders aren't allowed on board without permission. And you don't have it.}
{225}{}{What are you doing here?}
{226}{}{What is this place?}
{227}{}{This is our base. If that's all the questions, then you'd better just leave. There's no point in distracting sentries on duty.}
{228}{}{Okay, I'm leaving.}
{229}{}{Then at least tell me what this place is?}
{230}{}{You guys are cool. Can I join you?}
{231}{}{Don't count on it.}
{232}{}{Damn, no chance at all I guess.}
{233}{}{Uh... Perhaps you have some work for me?}
{234}{}{I don't think so. But talk to the patrol chief, maybe he has a task for you.}
{235}{}{I see, thanks.}
{236}{}{Wait. Can I ask you a few questions?}

{240}{}{I need to meet with your command.}
{241}{}{For what reason?}
{242}{}{It's, uh, personal. Can I go aboard?}
{243}{}{No.}
{244}{}{Too bad.}
{245}{}{I'll still find a way, you'll see.}
{246}{}{Okay, you can come aboard.}
{247}{}{Thanks.}
{248}{}{But while you're aboard, keep your weapon holstered and don't do anything stupid. The general's office is on the middle deck, the warehouse is to the right of the entrance. The remaining compartments are strictly off limits. Got it?}
{249}{}{Got it.}

{250}{}{I was sent by Master Hard of Two-Sun. Here's his recommendation.}
{251}{}{I've got a report from Ulysses Grant. To be delivered directly to General Dixon.}
{252}{}{Paladin Latham has given me permission to meet with the general.}
{253}{}{General Dixon is expecting me. This concerns the fort at Hermosillo.}
{254}{}{Looks like your fort's got a need for raw materials. I've got a loaded caravan nearby. I'm looking to make some big trades.}
{255}{}{I've got plenty of great items for sale in my caravan. Interested?}
{256}{}{No, we don't deal with lone traders.}
{257}{}{Too bad.}
{258}{}{I understand. But you should clean your armor, soldier. You look like a rust bucket.}
{259}{}{Paladin Latham has given me permission to meet with the quartermaster.}
