{100}{}{You see the innkeeper.}
{101}{}{You see the owner of the inn. He lazily scratches his belly, sitting heavily in an old pilot's seat.}
{102}{}{Close the door quickly! These robots are everywhere!}

# First dialogue
{200}{}{(reluctantly turns in your direction) All rooms are occupied.}
{201}{}{But half the keys are hanging there behind the counter...}
{202}{}{A big thing is coming up. Those rooms are reserved. If you need to spend the night, try knocking on some residential doors.}
{203}{}{I'm not feeling very welcome here.}
{204}{}{Not my problem.}
{205}{}{Uh, okay...}

{210}{}{I told you, the rooms are taken.}
{211}{}{I think you're just avoiding strangers.}
{212}{}{I remember.}

{213}{}{And I think some people are getting too nosy.}
{214}{}{Urm...}

{215}{}{(leaning towards you) The Tinsmiths are wary of spies and don't want their plans leaked. So, I gotta be cautious with strangers.}
{216}{}{Glad we understand each other.}
{217}{}{As a Follower of Fire, I am insulted by your service!}
{218}{}{I think the Brotherhood of Steel would frown upon such treatment of their members.}
{219}{}{Come on, why so unfriendly?}
{220}{}{You're not from around here.}
{221}{}{Well, yes, of course...}

# Re-dialogue
{250}{}{How can I help you?}
{251}{}{Thanks, I'll manage.}
{252}{}{Goodbye.}

{260}{}{What's going on around here?}
{261}{}{The Tinsmiths are trying to access an old military equipment storage facility. It's called the 'Forbidden Zone'. No success yet, but it's only a matter of time.}
{262}{}{The Tinsmiths have accessed an old military equipment storage facility. It's called the 'Forbidden Zone'. Looks like there's a lot of work ahead.}
{263}{}{Do you know anything about the slaves from Villa?}
{264}{}{No. Ask around in the hangar; they keep slaves there.}
{265}{}{How did you end up in this place?}
{266}{}{I came here a few years ago when the Tinsmiths opened a trade route with Phoenix. They needed a hotel for the caravanners, and I set it up. Without the Tinsmiths, I wouldn't have survived this long. I'd probably be rotting somewhere in the wasteland by now, sun-bleached bones and all.}
