{100}{}{You see the slave overseer.}
{101}{}{You see one of the Tinsmiths in charge of training the slaves.}

{200}{}{(addressing the group) Attention, primitives! You have been allocated to this facility to provide operational value to your otherwise useless existence!}
{201}{}{[More]}
{202}{}{You are assigned the task of retrieving ancient technology from the Forbidden Zone. This location contains valuable pre-war machinery. However, an advanced security protocol impedes access. Your objective is to breach the control center and deactivate the defenses. Successfully complete this mission, and you may be granted freedom.}
{203}{}{[More]}
{204}{}{Any questions?}
{205}{}{Yes.}
{206}{}{No.}
{207}{}{Then gather your rags and head to the parade ground! Anyone who attempts to escape the Forbidden Zone before mission completion will be permanently 'dismantled'.}
{208}{}{Looks like this will be a tough challenge...}
{209}{}{No more questions.}

{210}{}{You think you can do anything? Speak quickly, you worthless primitive!}
{211}{}{Can I get my stuff if I complete the mission?}
{212}{}{Pick it up from the quartermaster's box if you complete the mission. But do not expect to succeed.}
{213}{}{Is my father, Andres, also in the Forbidden Zone?}
{214}{}{I have no data on who you are referring to. With so many primitives disappearing in the Zone, remembering individual cases is pointless.}
{215}{}{What can we expect in the Forbidden Zone?}
{216}{}{Hostile robots, electromagnetic traps, and high radiation levels. The perimeter is surrounded by a force field. Escape without mission completion is not possible.}
{217}{}{Will we be given any weapons?}
{218}{}{Use what you salvage in the Zone.}
{219}{}{At least give me brass knuckles.}
{220}{}{At least give me a basic pistol.}
{221}{}{At least give me a stimpak.}
{222}{}{At least give me anti-robot grenades.}
{223}{}{I have had enough of your complaints, you worthless scrap! No weapons for you.}
{224}{}{I have had enough of your complaints, you worthless scrap! Here, take it and shut up.}
{225}{}{Another question.}

{230}{}{Any results? Report to our leader personally.}
{231}{}{Okay.}
{232}{}{What? A mercenary volunteer for the Forbidden Zone?}
{233}{}{Yes, I'm ready to go in too.}
{234}{}{No, just passing by.}
{235}{}{State your queries, volunteer.}
{236}{}{Talk to our leader, I only deal with primitive slaves.}
{237}{}{Okay.}
{238}{}{The great ZAX is defeated! Now we begin the real work. Time to find new slaves.}
{239}{}{I hope you can manage without me this time... Uh, bye.}
