{100}{}{You see your padre.}
{101}{}{You see Andres, your father.}
{102}{}{Your padre is dead.}
{103}{}{You receive }
{104}{}{ experience for freeing your fellow villagers.}
{105}{}{This is for my tough childhood, padre.}
{106}{}{Goodbye. I don't need my father's instructions anymore.}

#First dialogue
{200}{}{?!}
{201}{}{Hello, padre.}
{202}{}{How did you find us?}
{203}{}{Well, I had to do a lot of walking through the desert...}
{204}{}{Don't you understand the situation we're in?! You should be at home, not here!}
{205}{}{The Villa is being restored bit by bit. I managed to save our people who were in Flagstaff.}
{206}{}{I see now, I was wrong to think of you as a child still. This whole, terrible ordeal has given you a wealth of life experience. I'm glad you're here, son.}
{207}{}{I thought it would be better to save the leader of Villa first, then the others.}
{208}{}{That doesn't make any sense! Villa can survive without me. Who needs a leader in an abandoned settlement?! You should have gone to Flagstaff. Our people are being held there, including your madre.}
{209}{}{Okay. I'll digest that later. Right now we need to find a way out of here. Any ideas?}
{210}{}{We would have done that already if it weren't for the damn force field. There's no way to get through it. The only way out is to get into the bunker's control center and disable whatever's in there.}
{211}{}{So let's do it.}
{212}{}{Easy to say. But this area is crawling with robots and traps. No one knows what's inside the bunker. First, do some scouting around, find equipment and any help you can. We tried to create weapons to fight the robots, but our technician was killed while searching for parts, and I don't understand the tech.}
{213}{}{No problem, padre. I'll do some scouting and find a way out.}
{214}{}{A thank you would be nice. I'm saving you, after all.}
{215}{}{I'll figure it out without your guidance. Sit tight and wait for my instructions.}
{216}{}{Pa-adre-e, I've been looking for you forever!}
{1216}{}{Pa-adre-e, I've been looking for you forever!}

#Re-dialogue
{220}{}{Speak, }
{221}{}{.}
{222}{}{I'll be back soon.}

{230}{}{Let's discuss the plan again.}
{231}{}{Our plan is to get past the robots, go down into the bunker, find the controls for the force field, turn it off, and then escape this damned place back to the Villa.}
{232}{}{Got it.}

{233}{}{Where can I get weapons?}
{234}{}{Many slaves and mercenaries have died here. Look for bodies; maybe some still have weapons. I also saw something that looked like a weapon lying near a large plane, but, it looked too heavy to use.}
{235}{}{Are there other slaves here?}
{236}{}{There's a survivor camp near the bunker, but the guy there refused to cooperate with us. He seems a bit... unhinged, and looks rather sickly.}
{237}{}{How can we get past the robots?}
{238}{}{These things are smarter than mole rats. They hide in dark corners or in the sand. You won't see them right away, but you can hear them from ten yards out. They also react to movement. Move slowly or stay behind them, and they might not notice you.}
{239}{}{}

{240}{}{What is this place?}
{241}{}{As far as I can tell, it's a graveyard of long-forgotten technologies. The Tinsmiths want to revive them. I wouldn't want that to happen. They don't understand the dangers of Ancient tech!}
{242}{}{How do you know this tech is dangerous?}
{243}{}{Our ancestors taught us to fear old tech. They said it was unreliable and dangerous. And it's true. Have you come across things that explode in your hands or harm your health with invisible radiation? Entire communities have died from over-reliance on tech. In the wrong hands, these old things become weapons.}
{244}{}{I've come across such things...}
{245}{}{Remember Flagstaff. Remember how a group of raiders enslaved an entire settlement with just their weapons and electric collars. All this equipment must be destroyed! All of it!}
{246}{}{I'll think on what can be done...}
{247}{}{What about your pneumatic fist? I could use it.}
{248}{}{Leave the old man unprotected? (bitter laugh) Okay, you're our last hope.}
{249}{}{Thanks for the weapon, Padre.}

{250}{}{Tell me about the raid on Villa.}
{251}{}{Let's leave that talk until we get home. In short, the raiders attacked us at the end of the working day when our people were returning from the plantations, tired. I managed to hold the line at the town hall, but we were all caught, tied up, and brought to Flagstaff. Most were left to work in the local mine, and only the best were sent here.}
{252}{}{Have you been to Phoenix?}
{253}{}{Yes, we were taken to a church run by some kind of cult. Disgusting people, devoid of compassion, without pity. They studied us in detail, like lab rats - took blood for analysis, tortured us, and asked about Villa. Unfortunately, the church is now well aware of our home.}
{254}{}{More questions.}
{255}{}{Why were you sent to Two-Sun?}
{256}{}{Being the leader of the Villa, I knew a lot. So, of all our people, I was considered the best candidate for this job.}

# Joining the party
{260}{}{Let's go together. I need your experience.}
{261}{}{I'll help you get to the bunker. But you'll have to go down alone.}
{262}{}{Agreed.}
{263}{}{Why?}
{264}{}{This way you'll have a better chance of staying undetected. Besides, with all this old tech, I won't be much use. You've gained more knowledge and experience wandering through Sonora than I've ever had, son.}
{1264}{}{This way you'll have a better chance of staying undetected. Besides, with all this old tech, I won't be much use. You've gained more knowledge and experience wandering through Sonora than I've ever had, daughter.}
{265}{}{Hmm. Well, let's see what I can do.}
{266}{}{I'll go on alone.}
{1266}{}{I'll go on alone.}
{267}{}{I'll guard the entrance to the bunker. Good luck.}
{268}{}{[Go]}

# Completing the rescue quest
{300}{}{Hard has given you back your freedom. You can go.}
{301}{}{That makes leaving Two-Sun easy. But how do we get out of *here*?}
{302}{}{Hmm. Let me think about it.}
{303}{}{The force field is down, we can escape from Two-Sun.}
{304}{}{Good job, }
{305}{}{. The cost of our freedom is their gain. Now the Tinsmiths will have access to the old tech here, and God only knows how much trouble they'll cause. At least we have time to prepare.}
{306}{}{[More]}
{307}{}{Great job, }
{308}{}{. Not only did we gain our freedom, but we also kept the Tinsmiths from accessing this old tech. God only knows what chaos they'd unleash on the wasteland if they got their hands on that bunker tech.}
{309}{}{I'll rest for a while, then head home. I understand you have more to do still. Return to the Villa when you are done.}
{310}{}{Bye, padre.}
{311}{}{In the meantime, find Carlos and try to reason with him. The Tinsmiths won him over and filled his head with nonsense. If you can't talk him out of this path... you must eliminate him. Understand? I know I'm asking a lot, but he's a danger to the entire Villa now.}
{312}{}{I understand, padre. Trust me.}
{313}{}{Kill one of our own? I can't do that. But I'll convince him.}
