{100}{}{You see a clerk.}
{101}{}{You see a middle-aged man. Judging by his demeanor, he's obsessed with order and neatness.}

#Dialogue
{200}{}{Come in, wanderer. I keep order and accounting information here, so don't mess anything up.}
{1200}{}{Come in, wanderer. I keep order and accounting information here, so don't mess anything up.}
{201}{}{Goodbye.}
{202}{}{Back again? Amazing. How can I help?}
{203}{}{I need to send a package to Phoenix.}
{204}{}{I need to send a package to Flagstaff.}
{205}{}{I need to send a package to Puerto.}

#Sending a package
{210}{}{That's what I'm here for. The price for sending the package is }
{211}{}{ caps. No more, no less. Place your items in that box against the wall. After payment, we'll get them to their destination.}
{212}{}{Here's the fee. Send the package.}
{213}{}{Not now.}

{214}{}{No, no, that's not enough.}
{215}{}{Should we talk about something then?}
{216}{}{I'll be back when I have the money.}
{217}{}{Now I'll make an inventory and enter the data into the journal. The protocol requires this. Here... Thank you for choosing our company. The package will be waiting in Phoenix at the same Sonora Express office.}
{218}{}{Great.}

{220}{}{As a member of the Brotherhood of Steel, can I get special prices?}
{221}{}{Definitely. We have special agreements with the Brotherhood.}
{222}{}{Wonderful. Just great.}
{223}{}{Ah, it's you again... But I must inform you that the discount on our services has now been revoked. And there's no need to be indignant. This is a management decision, not mine.}
{224}{}{Yes, bad luck...}

#First dialogue
{230}{}{How can I help?}
{231}{}{What is this place?}
{232}{}{Regional office of the courier company "Sonora Express". We handle various types of deliveries.}
{233}{}{And how big is your caravan network?}
{234}{}{We deliver near or far. It all depends on the specific order. Our central office is in Phoenix, with routes extending to the surrounding settlements.}
{235}{}{I see. I'll keep that in mind for the future.}

# added by cambragol
{236}{}{Sonora Express again? Man, how big is your caravan network?}
