{101}{}{You see a surviving Brotherhood of Steel scout.}
{102}{}{Someday the Brotherhood of Steel will return to Arizona. It's only a matter of time.}

#Dialogue
{200}{}{(as a stranger passes by, he peers warily at your face) Hmm, I think I've seen you somewhere.}
{201}{}{Perhaps. You're not local, are you?}
{202}{}{No. And neither are you. Two strangers in an inhospitable town. Small world, isn't it?}
{203}{}{That's right. But I have business here. You don't mind, do you?}
{204}{}{No. Go ahead.}
{205}{}{Bye.}
{206}{}{}
{207}{}{}
{208}{}{(nods in greeting)}
{1208}{}{Only after you.}
{209}{}{[Do the same]}
{1209}{}{You're so kind.}

{210}{}{Oh, I remember. It was you I saw shortly before the explosion in Steel Port. Interesting coincidence, isn't it?}
{211}{}{Explosion? Hey, I had nothing to do with that.}
{212}{}{Is someone blaming you?}
{213}{}{I guess not.}
{214}{}{Then why so nervous? Relax, I don't believe a man like you could've gotten past all the defenses on the ship and detonated the torpedoes. Not even the base personnel had access to it.}
{215}{}{Uh, good. It just seemed like you suspected something. Uh, goodbye, sir. Have a good day.}
{216}{}{What if I said the explosion was my doing?}
{217}{}{Anyone could say that now. But why? I'd never believe some desert primitive could penetrate a well-guarded hold and launch torpedoes. Where would you get such skills and knowledge, farmer?}
{1217}{}{Anyone could say that now. But why? I'd never believe some hick from the desert could penetrate a well-guarded hold and launch torpedoes. Where would you get such skills and knowledge, peasant?}
{218}{}{It does sound fantastic. Just like in old comics. I guess that settles any suspicions?}
{219}{}{I guess so. But I'll keep an eye on you I think...}
{220}{}{That's not necessary. Goodbye.}
{221}{}{You should pipe down after recent events. Your Brotherhood is now part of history. Get over it.}
{222}{}{It's true. However, Puerto Penasco was just an outpost far from the main base. Perhaps we'll return here one day.}
{223}{}{But it won't be any time soon. And by then, you won't be welcome here. Better think about your own fate, soldier.}
{224}{}{Coming here seemed like the smartest and safest idea. Guess I was wrong. Okay, you won't hear from me again. Goodbye, stranger.}
{1224}{}{Coming here seemed like the smartest and safest idea. Guess I was wrong. Okay, you won't hear from me again. Goodbye, stranger.}
{225}{}{Goodbye, Brotherhood of Steel scout.}
{226}{}{Go on, hit the road.}
