{100}{}{You see a slave.}
{101}{}{You see a forced laborer. Exhausted from relentless toil, he still stands.}

{102}{}{Are you looking for your friends? They've probably been sent into the Forbidden Zone already.}

{110}{}{Please kill me! I can't take this torment any longer...}
{111}{}{I'm not allowed to talk to strangers.}
{112}{}{To the Tinsmiths, we're just expendable.}
{113}{}{I used to run with a gang, but I got captured and ended up here.}
{114}{}{I miss my gang.}
{115}{}{Back with the gang, I never thought about my victims.}
{116}{}{These Tinsmiths are obsessed with ancient tech.}
{117}{}{Hide your computer, or the Tinsmiths will take it by force.}
{118}{}{The Forbidden Zone is certain death.}
{119}{}{Got anything to eat?}
