{100}{}{You see an emergency terminal.}
{101}{}{You see a computer with the sign: "Use in case of emergency."}
{102}{}{ZAX has seized control of the system; emergency protocol cannot be initiated.}
{103}{}{The terminal is not functioning.}
{104}{}{The first port is connected. Insert the second access card.}
{105}{}{Second port connected.}

#Dialogue
{200}{}{Enter command:}
{201}{}{End session}
{202}{}{Back}

{210}{}{Initiate emergency protocol.}
{211}{}{Warning! The emergency protocol will trigger a series of electro-magnetic pulses to destroy all electronic equipment within the bunker. This procedure is irreversible and should only be used in an absolute emergency.}
{212}{}{Isn't this an absolute emergency?}
{213}{}{Okay.}
{214}{}{Are you sure you want to initiate the emergency protocol?}
{215}{}{No, cancel the pulses.}
{216}{}{Yes, initiate the electro-magnetic pulses.}
{217}{}{For security reasons, disable this terminal and remove the access cards.}
{218}{}{Starting emergency protocol...}
{219}{}{Come on, do it, damn it!}
