{102}{}{Don't push!}

#Response - reputation >5
{110}{}{You'll protect us, right?}
{111}{}{Kill those raiders! Get rid of them all!}
{112}{}{I don't want those raiders to come back.}
{113}{}{Strangers are bad. All of them.}
{114}{}{I just want to see my mom!}

#Response - reputation <-5
{115}{}{You scare me more than the raiders.}
{116}{}{Stay away from me! You're no better than them.}
{117}{}{I was told not to talk to people like you.}
{118}{}{Strangers are bad. That's what the adults say.}
{119}{}{I just want to see my mom!}

#Response - reputation from -5 to 5
{120}{}{If the raiders come back, who's gonna protect us?}
{121}{}{That was so scary... I'm still shaking.}
{122}{}{I'm afraid they'll come back. The raiders.}
{123}{}{Why do strangers have to be so bad?}
{124}{}{I just want to see my mom!}
{125}{}{Do you wanna play?}
