{100}{}{You see a peasant.}
{1100}{}{You see a peasant woman.}
{101}{}{You see one of your fellow villagers.}
{1101}{}{You see one of your fellow villagers.}
{102}{}{Someday, I'll get you too.}
{103}{}{ }

#Floating lines
{110}{}{Someone needs to drive those Jackals out of the desert.}
{111}{}{I'd love to see those Jackals chased right out of here.}
{112}{}{Did you hear about the Jackals? Can't even trust the Rangers anymore...}

{113}{}{I doubt we'll have good relations with the scavengers after this.}
{114}{}{Now those scum from Garage City know how we handle things.}
{115}{}{I don't think I'll ever forgive the scavengers for what they did.}

{116}{}{We could use some help from the Rangers right about now.}
{117}{}{Even the Rangers are struggling with their own mess.}
{118}{}{The Rangers are tough, but they won't stick around if we don't share.}

{119}{}{Our enemies in Flagstaff will get what's coming one day!}
{120}{}{They say things are getting bad in Flagstaff. Let's sing about it, amigos!}
{121}{}{If Flagstaff keeps expanding, our freedom's in danger.}

{122}{}{Caravans are bringing bad news from the southeast.}
{123}{}{Something's stirring in the southeast. Hope it doesn't reach us.}
{124}{}{Looks like there's a war brewing down southeast.}

{125}{}{Wish Señor Andres would come back from slavery.}
{126}{}{Our new leader just doesn't have the strength to lead us.}
{127}{}{We shouldn't question our leader's decisions.}

{128}{}{Someone has to rescue Señora Maria from slavery.}
{129}{}{It's going to be tough after what happened to Señora Maria.}
{130}{}{Thank heavens, Maria is back at the Villa!}

{131}{}{Glory to our savior!}
{132}{}{Señor Andres raised a real hero.}
{133}{}{Andres' deputy is showing a lot of promise.}

{134}{}{Shh! That degenerate, Señor Andres, is up to something.}
{135}{}{Señor Andres raised a real devil.}
{136}{}{When things get tough, we need a strong leader.}

{1131}{}{Glory to our savior!}
{1132}{}{Señor Andres raised a real heroine.}
{1133}{}{Andres' deputy is showing a lot of promise.}

{1134}{}{Shh! That degenerate, Señor Andres, is scheming something.}
{1135}{}{Señor Andres raised a she-devil.}
{1136}{}{When times get tough, we need a strong leader.}

#Response
{200}{}{You're always welcome here.}
{201}{}{Thank you for saving us, hero.}
{202}{}{You're an inspiration to all of us.}

{210}{}{I've got a lot to do, sorry.}
{211}{}{We're rebuilding the village. What about you?}
{212}{}{Stop bothering us and get to work.}

{220}{}{Try scaring the kids with that thing.}
{221}{}{Stay away from me!}
{222}{}{You'll scare anyone wearing that.}
{223}{}{Scare our enemies with that piece of iron, not us.}
{224}{}{How dare you walk around the Villa in that armor?}
{225}{}{Think that armor will hold off our enemies?}
{226}{}{Aren't you roasting in that tin can?}
{227}{}{Why don't you help us clean up the plantations?}
{228}{}{If that armor's so powerful, use it to fix up the houses.}
{229}{}{Watch it, you walking tank! People live here, you know.}
