{100}{}{You see a marauder.}
{101}{}{You see a stranger scouring the area for valuables.}

{110}{}{We're leaving. Don't bother following us.}
{111}{}{We'll leave for now. But there'll be others.}
{112}{}{That's all we wanted.}
{113}{}{We have nothing else to do here.}

{200}{}{Hey! Are you a local? Then you can tell us where the keys to this barn are.}
{1200}{}{Hey! Are you a local? Then you can tell us where the keys to this barn are.}
{201}{}{What do you want with the barn?}
{202}{}{We know there's a lot of cornmeal there. And this is the only barn that was not looted. So get the keys, get us some cornmeal, and we'll leave without hurting anyone.}
{203}{}{Cornmeal is that valuable to you?}
{204}{}{Don't you know anything about the Wasteland? There are barren lands all around, and only you peasants manage to grow crops. They say you fertilize the earth with human blood. But you know what - I don't care. Just give us the cornmeal and we'll leave. Got it?}
{205}{}{So you weren't part of the raid?}
{206}{}{No. We knew the raid was going down, so we came to collect what was left. Don't wanna let all this valuable food go to waste.}
{207}{}{If I give you all the cornmeal from this barn, will you leave?}
{208}{}{You have my word. Ten bags will be enough for us; we couldn't carry more anyway.}
{209}{}{The Villa's out to lynch you, you know? Pitchforks are already being handed out in the plaza.}
{210}{}{You're bluffing. There's only children and old folk left in the village. Who're we supposed to be afraid of?}
{211}{}{Old people and children. When they gather in a crowd, things could get ugly.}
{212}{}{Damn it! I told you they weren't all taken. Okay, let's get out of here...}
{213}{}{Here's 10 bags of corn. Will this be enough to get you out of the Villa?}
{214}{}{Quite. I don't want a bunch of peasants coming after us. Okay, let's get out of here...}
{215}{}{Give me time to figure it out. I'll be back.}
{216}{}{Better move it...}
{217}{}{The marauders leave the Villa peacefully.}
{218}{}{Get us some cornmeal, and we'll leave without harming anyone.}
{219}{}{I'm not bluffing.}
{220}{}{Get out of here!}
{221}{}{Well, we'll see what happens...}
{222}{}{Alright, I get it.}
{223}{}{The Villa is now under the protection of the Rangers. You're asking for trouble.}
{224}{}{Rangers? Here? That's bad. Let's get the hell out of here...}
{225}{}{Yeah, yeah, you better move it.}
{226}{}{Get out. And don't come back.}
