{100}{}{You see the envoy.}
{101}{}{You see an official envoy from the Rangers.}
{102}{}{Our alliance is over, Envoy.}
{103}{}{You're under reliable protection.}

# First dialogue
{200}{}{Hello, Guerrero. So we owe this strong union to you? You're the best of the best. But now you can relax and return to your former life. We, the Rangers, will keep peace and order in and around the Villa.}
{201}{}{I thought they would send more rangers here.}
{1201}{}{I thought they would send more rangers here.}
{202}{}{Don't worry, I'm not alone. The rest are patrolling and scouting the area. If needed, I can call them by radio.}
{203}{}{Then thanks for your service, Envoy. I gotta go.}
{204}{}{Okay. I hope that is the case, because if not, our alliance would end before it even begins.}

{210}{}{Greetings.}
{211}{}{I gotta go.}
