{100}{}{You see Senor Gustavo.}
{101}{}{You see Senor Gustavo, the manager of San Ysidro.}
{102}{}{Here, I am the law!}
{103}{}{Ghouls need radio comms? Let's help them out - then maybe Gomer will get some respect.}
{104}{}{Meet me at the pier.}

# First Meeting
{200}{}{Gustavo Obanel Vallejo at your service. I'm the manager of San Ysidro. Now, to hell with the niceties. I want to know why you disrupted our eternal rest.}
{1200}{}{Gustavo Obanel Vallejo at your service. I'm the manager of San Ysidro. Now, to hell with the niceties. I want to know why you disrupted our eternal rest.}
# Gustavo Obanel Vallejo at your service. I'm the manager of San Ysidro. Now, to hell with pleasantries. I want to know the reason why you're disturbing our posthumous peace. We don't tolerate smooth-skins here. Our family has suffered enough from you. Therefore, explain clearly and without lying - why should we tolerate your presence?
{201}{}{To hell with the ghouls. I'm here for profit. Heard there's good money to be made here.}
{202}{}{An honest answer. I can deal with people like you. I'm starting to like you.}
{203}{}{Depends on the terms, partner.}
{204}{}{Actually, I'm looking for a better place to live. Things are pretty bad back home.}
{205}{}{Running from your problems, huh? Not impressive, smoothskin. But you might still be useful.}
{1205}{}{Running from your problems, huh? Not impressive, smoothskin. But you might still be useful.}
{206}{}{Alright. What kind of work is available here?}
{207}{}{I've got no problem with you. I love ghouls and would like to live among them.}
{1207}{}{I've got no problem with you. I love ghouls and would like to live among them.}
{208}{}{Your skin is so smooth, you could be dessert, normie. I won't tolerate any more lies. But I'll give you one chance. Prove yourself, and you'll get your ghoul hugs for the rest of your days.}
{209}{}{Hey, I'm just trying to be friendly!}
{1209}{}{Hey, I'm just trying to be friendly!}
{210}{}{Gustavo Obanel Vallejo at your service. I'm the manager of San Ysidro. Glad to see you in our camp, brother. You'll find eternal rest here.}
{1210}{}{Gustavo Obanel Vallejo at your service. I'm the manager of San Ysidro. Glad to see you in our camp, sister. You'll find eternal rest here.}
{211}{}{Thanks, brother. So what can I do in this fine city?}
{212}{}{Dayglow still can't shine. You can head to the station and help our workers restore power to the city. I'll reward you generously and let you stay in San Ysidro for the rest of your days.}
{213}{}{Dayglow still can't shine. You can head to the station and help our workers restore power to the city. The city will be grateful to you till the end of days.}
{214}{}{Deal.}
{215}{}{Too much hassle.}
{216}{}{Too many words, normie. Get back to the nuclear wasteland! We don't need you.}
{217}{}{Oh-oh...}
{218}{}{After the incident at the border, this conversation will be brief. What do you need?}
{219}{}{What incident? I'm not aware of anything!}
{220}{}{My loyal guards were protecting the entrance. Now only the wind roams there. And here you are. What do you have to say for yourself?}
{221}{}{It's a coincidence. The entrance was open, so I walked in.}
{1221}{}{It's a coincidence. The entrance was open, so I walked in.}
{222}{}{Hmm, if I find out you're lying, I'll personally peel your smooth skin and sprinkle your raw flesh with radioactive ash. You'll feel all the pain ghouls experience every day.}
{223}{}{I believe every word. But who are you?}
{224}{}{That ghoul threatened me. I was just defending myself.}
{1224}{}{That ghoul threatened me. I was just defending myself.}
{225}{}{He was a loyal servant of the Light. He protected our city from normies. Think you can atone for your crime?}
{226}{}{You have no right to set boundaries. This wasteland is for everyone, not just you.}
{227}{}{We just want to live like normal people. No wars. No grand missions to save humanity. Maybe you can't understand that. But since you're here, you have little choice - atone or... die.}
{228}{}{I choose death. Yours!}
{229}{}{Can we negotiate? By the way, we haven't introduced ourselves.}
{230}{}{I don't remember being warned about your arrival. How did you get past the border?}
{231}{}{Well, I just walked through the gate.}
{232}{}{And the loyal servants of the Light didn't stop you? Someone's getting a good beating.}
{233}{}{Definitely not me. So you're in charge here?}
{234}{}{To live here, you'll have to work. Even a mutant like you should understand that. We've got enough freeloaders already.}
{235}{}{Alright...}
{236}{}{Any ideas on how to fix the radio station?}

# Repeat Dialogue
{250}{}{Speak, smoothskin.}
{1250}{}{Speak, smoothskin.}
{251}{}{Goodbye, Senor Gustavo.}
{252}{}{What are you up to, normie?}
{1252}{}{What are you up to, smoothskin?}
{253}{}{Look who we have here. Smoothskin looking for a beating. Don't worry, I'll save your skin for grafting onto my old body. But first, you're going to tell me everything.}
{254}{}{Sit down, amigo. I hope the ghouls at the Light treated you like one of their own.}
{255}{}{Sit down, amigo. How's the Light treating you? Everything alright? Let me know if there are any problems.}
{256}{}{Sit down, amigo. Talk to me. Maybe I can help.}
{257}{}{Sit down. I think it's high time we had a talk.}

{260}{}{Remind me what you wanted from me?}
{261}{}{Am I speaking Russian? (tired sigh) }
{262}{}{The power plant is working.}
{263}{}{Dayglow shines again! Electricity has returned to San Ysidro and Old Town. You've done a great deed, amigo. Let me hug you and thanks. Here are 1000 caps.}
{1263}{}{Dayglow shines again! Electricity has returned to San Ysidro and Old Town. You've done a great deed. Let me hug you and thank you. Here are 1000 caps.}
{264}{}{Thanks.}
{265}{}{Not bad.}
{266}{}{I owe you an apology. I gave you this task hoping you'd be killed by robots or radiation. And there'd be one less smoothskin in Dayglow. But I was wrong. You can stay in our city as long as you want.}
{267}{}{I understand and don't blame you.}
{268}{}{Don't expect me to shake your hand after that.}
{1268}{}{Don't expect me to hug you after that.}
{269}{}{Now that we have electricity, we need to fix the broken radio station. It's in the next room. This task is just for you.}
{270}{}{Is it too broken? Are you sure it can be fixed?}
{271}{}{Fix it - no. It needs a replacement. I know there's an identical one at the border patrol center. I'll pay if you bring the parts from there.}
{272}{}{Alright. I'll try.}
{273}{}{I'll try when I'm in the mood. But for now, I don't feel like it. See you.}
{274}{}{The radio station is working. Actually, I had to replace it with a new one from the border office.}
{275}{}{That's another great news in this scorched world! And I like you more and more, smoothskin. You're just like I was in my youth.}
{1275}{}{That's another great news in this scorched world! And I like you more and more, smoothskin. You're just like I was in my youth.}
{276}{}{That's another great news in this scorched world!}
{277}{}{Not the nicest comparison, you know.}
{278}{}{Let's skip the hugs, okay?}
{279}{}{Let's not waste time. Here's 500 caps for the job. Now I need you to take this holodisk to Mayor Butler in Old Town. It's very important.}
{280}{}{That's it? After my past deeds, this will be a walk in the park.}
{281}{}{Ahead are the grim ruins of San Diego. Many dangers lurk there. Be more careful. And ask Edward for supplies for the road.}
{282}{}{Alright, see you.}
{283}{}{Give me a weapon if you want me to survive the trip to Old Town.}
{284}{}{Hmm, that's reasonable. What weapon are you best with?}
{285}{}{[Take }
{286}{}{]}
{287}{}{Be so kind as not to die on the way.}
{1287}{}{Be so kind as not to die on the way.}
{288}{}{I'll try...}
{289}{}{I'll try to respond.}
{290}{}{Is it that important to you?}
{291}{}{We need this radio station. Dayglow's areas are torn apart by impassable ruins, and radiation blocks regular weak radios. Constant communication will change the entire city. Do your best for all of us.}
{292}{}{What's on this disk?}
{293}{}{First, data for radio broadcasts so we can communicate over distances. And second... Second, some warnings for my brother to keep him from making big mistakes.}


{296}{}{How do I get to the power plant?}
{297}{}{There are two ways. You can go straight on Federal Highway 805, then turn east at the sign. But the highway is patrolled by military robots. The less dangerous path lies through the toxic swamps in Chula Vista.}
{298}{}{Alright, I'll try to find it.}

#Inquiries
{300}{}{Can I ask a few questions?}
{301}{}{Amigo, I'm always happy to listen and answer your questions. But there are more important things to do now. You know what to do.}
{302}{}{It would be better if you got to work. You know what I mean.}
{303}{}{No talking. I'm not even sure I should be talking to you.}
{304}{}{Got it. We'll talk later.}
{305}{}{You could have just said you don't want to see me. Goodbye.}
{306}{}{Amigo, I'm always happy to listen and answer your questions. }
{307}{}{Alright, see you.}

{310}{}{I want to know more about you.}
{311}{}{Who am I? Strange question. I was once a doctor. But the War nullified my license. Now, as you see, I run a small town. You can learn anything if life forces you to.}
{312}{}{By the way, about this town. I don't understand, where is Dayglow then? What is it?}
{313}{}{It's in our heart. Dayglow is the ghouls' dream. A dream of a city where we can peacefully grow old. And San Ysidro is one of its districts. Here we are protected by the old border wall.}
{314}{}{So your goal is to build Dayglow?}
{315}{}{A city for ghouls is my goal. We just want to live like normal people. Without oppression. Without wars. Without grand missions to save humanity.}
{316}{}{Got it.}
{317}{}{Is Old Town also striving for this paradise?}
{318}{}{It doesn't seem like Old Town shares your dream.}
{319}{}{Old Town is making a mistake. It's too close to the caravan trail and therefore cannot get rid of the corrupting influence of smoothskins from the northern cities.}
{320}{}{How do I get to Old Town?}
{321}{}{Go north. You can go straight through the piers, in the most radioactive hell. Or you can go around through the suburban ruins, ensuring yourself new and not always welcome encounters.}
{322}{}{Got it.}
{323}{}{What is Dayglow? Where is it located?}
{324}{}{What kind of city are you trying to build?}
{325}{}{It will be a city as it was a hundred years ago. We collect everything that is left from the Old World. Here, no one cares about us, so we can relax and peacefully live out our days.}
{326}{}{Tell me about yourself.}

{350}{}{I gave the holodisk to Butler. Your message didn't convince him.}
{1350}{}{I gave the holodisk to Butler. Your message didn't convince him.}
{351}{}{Not surprising. John and I argue about Dayglow. About what the ghoul city should be like. He pays too much attention to smoothskins and has completely forgotten that we are people of the Old World. We can revive the city, rebuild it from scratch! Yes, ghouls are weak, but we have remnants of old machines and energy. With technology, we can create all the necessary living conditions for ourselves even in the middle of scorched ruins.}
{352}{}{By the way, after reading the holodisk, he asked me to help him get chips from the aircraft factory.}
{353}{}{What an idiot! That factory will still serve us, ghouls. Don't give the chips to Old Town, give them to me. Our technician will use them to repair the robots, and with their help, we will restore the city. This will give us more advantages in the future than a stupid exchange for food with caravanners.}
{354}{}{I'll think about it.}
{355}{}{Alright. I'll do it.}
{356}{}{I knew you'd say that, so I took these chips with me in advance. Here they are.}
{1356}{}{I knew you'd say that, so I took these chips with me in advance. Here they are.}
{357}{}{Thank you. Here's 1000 caps for the job. The factory will serve us too. We can't let it be destroyed. I think you should personally tell John that the factory is under my control and that I won't give him the chips.}
{358}{}{Alright.}
{359}{}{Here are the chips that Butler wanted to sell. But he won't be able to now.}
{360}{}{Then I have bad news for you - Butler has already taken the chips and is preparing to sell them.}
{361}{}{That's really bad news. I think you should keep an eye on Butler. Let me know if you find out what he's planning next.}
{362}{}{Alright.}
{363}{}{I have bad news for you - Butler has already taken the chips and is preparing to sell them.}
{364}{}{Yes, and also - keep me informed about what Butler is planning if you find out.}
{365}{}{Alright.}

{370}{}{Butler is planning to open the naval base on the island...}
{371}{}{He's making a mistake! He'll sell most of the finds to people! And this will provoke a big reshuffle in human settlements. The war with the super mutants has just subsided, and battles for old technologies will start again. Smoothskins don't understand how to handle the legacy of the Old World. Moreover, they can turn it against us. Technologies should stay with the ghouls! We need them more. And we know better how to use them.}
{372}{}{What are you going to do?}
{373}{}{Butler won't back down. We must land first and get everything for ourselves. I'll send a group to the pier for an interception. And you use the radio station as he asked, then head to the pier.}
{374}{}{Okay.}
