{100}{}{You see a ghoul.}
{101}{}{You see a ghoul. He has a collar with a built-in shocker.}
{102}{}{You're letting us go? Thank God! There are still good people on this earth.}

{110}{}{They captured us and are forcing us to collect these things.}
{111}{}{Don't hurt us, human. We're trying our best.}
{112}{}{One of us has gone mad. Better stay out of his sight.}
{113}{}{These scavengers don't even know what these things are for.}

{120}{}{They are making us work.}
{121}{}{Did they capture you too? Tough luck, friend.}
{122}{}{One of us has gone mad. Better stay out of his sight.}
{123}{}{These scavengers don't even know what these things are for.}

