{200}{}{Hey, it's Private Gomer! And he's with a normie?}
{201}{}{Gomer is my subordinate. You should follow my orders too.}
{202}{}{Grr! Gomer is a traitor! Death to normies!}
{203}{}{Wait...}
{204}{}{Gomer and I are friends. Surprised, greenie?}
{205}{}{Gomer friends with a normie? Ho-ho-ho, I don't believe it! You're his slave-squire. Gomer, you surprised me. Leave the slave aside and help us get the people out of that fortress.}
{206}{}{Don't you dare humiliate me, you green freak!}
{207}{}{You've been running your mouth too much, slave. I'm going to tear it out!}
{208}{}{Well, well.}
{209}{}{Gomer, explain to them that I'm not a slave and that they should leave the people alone.}
{210}{}{Gomer with normies now? That's bad! Gomer has disappointed us all again. Gomer is a traitor! Death to normies!}
{211}{}{Wait...}
{212}{}{Live, normie. You're lucky today.}
{213}{}{The Master watches me from the heavens. I will not disgrace His name!}
{214}{}{So you're letting me go, huh? Thanks.}
