{100}{}{You see a crazed ghoul.}
{101}{}{You see one of the ghouls. He's muttering something unintelligible.}

{110}{}{I'm a man without a heart. Without a heart! Do you know why? Do you know?}
{111}{}{A monster took root in my heart. It ate the heart. It's gone now.}
{112}{}{We have little time.}
{113}{}{We have one last chance.}
{114}{}{Where's my skull scraper?}
{115}{}{We've all lost something. We're all lost.}
{116}{}{Sing something for goodbye.}
{117}{}{I want only one thing - to see the light.}
{118}{}{Rest in peace, human.}
{119}{}{Welcome to hell, baby.}
{120}{}{*muttering*}
