{100}{}{You see a wandering ghoul.}
{101}{}{You see one of the ghouls. There's a cunning look in his twisted face.}
{102}{}{Hey, can you give me a lift to the Hub?}
{103}{}{Hello.}

{200}{}{Hey, what a surprise! Didn't think I'd see a pureblood around here. Nice to meet you. I'm Bradley. Need me to show you the way?}
{201}{}{Bradley, have you seen Steve Morgan?}
{202}{}{Nope. Why do you ask?}
{203}{}{He owes something to the Far Go Traders.}
{204}{}{I don't know how to help you. Steve is afraid of purebloods and hides from them. But I can contact him if you want and act as a middleman.}
{205}{}{Thanks, Bradley. I'd appreciate it if you could find out what he wants for the goods.}
{1205}{}{Thanks, Bradley. I'd appreciate it if you could find out what he wants for the goods.}
{206}{}{(leaves and soon returns) I found Steve. He wants 1000 Hubbucks for the fuel controller. Deal?}
{207}{}{I don't have that much.}
{208}{}{Then no deal. Goodbye.}
{209}{}{[Leave]}
{210}{}{Hey, wait, actually, I do have 1000 caps. Now bring the goods.}
{211}{}{Now that's what I call business! Well, all the best, partner.}
{212}{}{Goodbye.}
{213}{}{Now hand back the caps, you idiot.}
{214}{}{Are you lying? I was told Steve Morgan went down this road.}
{215}{}{No, I'm not Steve Morgan. Why do you ask?}
{216}{}{Don't give me that. Answer me, damn it, are you Steve Morgan?}
{217}{}{No, it's not me, not me!}
{218}{}{Liar!}
{219}{}{Sorry. So where's Morgan then?}
{220}{}{Just don't kill me! Alright, I took the fuel controller. The Far Go Traders pay too little. I was planning to sell it in the Hub for big money... Listen, how about a deal? I'll sell you the controller for 800 caps, and you can resell it to the Far Go Traders. How's that?}
{221}{}{But the Far Go Traders pay half that.}
{222}{}{Damn, you're right. But understand, it's my item, and I set the price, not them. So are you buying it?}
{223}{}{No.}
{224}{}{Then no deal. Goodbye.}
{225}{}{[Leave]}
{226}{}{Wait, I changed my mind. Here's 800 caps. Now bring the goods.}
{227}{}{If you don't want to hand over the controller, I'll take it by force...}
{228}{}{Yes. Here's 800 caps.}
{229}{}{Yes. Here's 1000 caps.}
{230}{}{Morgan still wants to sell the controller for 1000 Hubbucks. Deal?}
{231}{}{The terms haven't changed: 800 caps, and the controller is yours. So are you buying it?}

