{100}{}{You see Rutger.}
{101}{}{You see the leader of the Far Go Traders.}

{200}{}{We're damn lucky you were nearby. I don't have words to express my gratitude for saving our asses. Here, take this automatic rifle as a reward. Now, how can I help you?}
{1200}{}{We're damn lucky you were nearby. I don't have words to express my gratitude for saving our asses. Here, take this automatic rifle as a reward. Now, how can I help you?}
{201}{}{Let's just talk for a start.}
{202}{}{It seems you were carrying some goods. Can I take a look?}
{203}{}{This cargo was meant for the ghouls, but they weren't interested... }
{204}{}{[Barter]}
{205}{}{Yeah, by the way, I was hoping to buy some things from the ghouls. But they don't want to part with them or ask too high a price. I'll pay you if you can find them for me in the ruins.}
{206}{}{Alright. What do you need?}
{207}{}{No, I'm not interested in searching for old artifacts.}
{208}{}{What else do you need?}
{209}{}{That's all. Bye, Rutger.}
{210}{}{I want to ask something else.}
{211}{}{I need to look at your goods again.}
{212}{}{I'm looking for these items: 1) water chip, 2) circuit board, 3) diagnostic board, 4) fuel controller, 5) vertibird schematics.}
{213}{}{If I find them, I'll bring them. Bye.}
{214}{}{About those old things you're looking for.}
{215}{}{Did you manage to find anything useful?}
{216}{}{Not yet. If I find them, I'll bring them. Bye.}
{217}{}{Why do you need all these old artifacts?}
{218}{}{My boss Butch in the Hub will be terribly upset if I come back empty-handed. The Hub needs all sorts of things. And not just the Hub. All of California survives on ancient tech. And over time, there's less and less of it.}
{219}{}{Got it.}
{220}{}{Where can I find a water chip?}
{221}{}{That technology was used in Vault-Tec vaults. I know there was one such vault near San Diego. But I don't have the exact coordinates.}
{222}{}{Where can I find a circuit board?}
{223}{}{That kind of tech can only be found in old printing presses. The Hub folks want to print their own money, and for that, they need to start up a printing press. And that's the one part they lack.}
{224}{}{Where can I find a diagnostic board?}
{225}{}{It's a part from an autodoc. Such tech used to be found in big hospitals.}
{226}{}{Where can I find a fuel controller?}
{227}{}{Funny thing. The trader across the way says he already got that part from another camp. But he can't find it. The old geezer probably lost it among all his junk.}
{228}{}{Where can I find vertibird schematics?}
{229}{}{You know about the naval base on Coronado Island? And the military airfield? They were torn to shreds by nuclear blasts. But the ghouls say there was also a factory that serviced military equipment. The schematics might have survived there. And by the way, I have no idea what a "vertibird" is.}
{230}{}{I found the }
{231}{}{ you asked for.}
{232}{}{Great job! Here's your 400 caps. I'll take this to the Hub.}
{233}{}{Thanks for the caps.}
{234}{}{You have fully completed the Far Go Traders' contract. Excellent job!}
{235}{}{Good to see you.}
{236}{}{Goodbye.}
{237}{}{[Continue the conversation]}
{238}{}{Good to see you... You, but not your mutant friend.}
{239}{}{It seems we're no longer welcome in Dayglow. We'll be leaving soon.}

{240}{}{Where did your caravan come from?}
{241}{}{We're from the Hub. That's where our main office is.}
{242}{}{Tell me about the Hub.}
{243}{}{It's the largest city in California. The center of bottle cap currency and trade. The main supplier of clean water. Most people and companies are there. But it also has the most problems.}
{244}{}{I see.}
{245}{}{In Phoenix, they also use bottle caps for trading.}
{246}{}{Hubbucks are in Phoenix? Hmm! The bottle cap currency has been supported in the Hub for many years. Someone must have taken the idea east. But who could have crossed the Toxic Divide between Arizona and California? Interesting!}
{247}{}{Let's go back...}
{248}{}{Which company's office?}
{249}{}{Which company are you from?}
{250}{}{We're the Far Go Traders trading company from the Hub. We transport goods from one settlement to another.}
{251}{}{Tell me about the Hub.}
{252}{}{Tough job, huh?}
{253}{}{Very. For a while, we suffered from super mutant raids and all sorts of scum. Lost many people and brahmin until one person stopped it. The Vault Dweller - that's what everyone called him.}
{254}{}{Where did these super mutants come from?}
{255}{}{Those sons of bitches raided caravans and kidnapped people to turn them into freaks like themselves. Nobody in the Hub even knew about them. Then one person uncovered their secret. Everyone was horrified.}
{256}{}{Go on.}
{257}{}{I know this story. You don't need to continue.}
{258}{}{Then that mysterious person and the Brotherhood of Steel guys stirred up their nest. But part of the green army survived and scattered across the Wasteland.}
{259}{}{Thanks for the story, Rutger. I didn't know any of this.}
{1259}{}{Thanks for the story, Rutger. I didn't know any of this.}
{260}{}{Thanks for the story, Rutger. They didn't even tell me this in Inferno.}
{261}{}{By the way, about the super mutants. Do you know where they came from?}
{262}{}{Which office were you talking about?}
{263}{}{Some settlements were unlucky to be in their path. That's why people have been fighting mutants for years. It's no surprise some of the green bastards ended up here - far from human settlements.}
{264}{}{What happened to the Vault Dweller?}
{265}{}{I don't know. He seemed to vanish. Nobody has heard anything about him since.}
{266}{}{Butler promises big orders. Looks like he's struck gold.}

