{100}{}{You see Phil.}
{101}{}{You see an elderly ghoul in glasses. He is weakly rocking back and forth in his chair.}

{200}{}{Hey, which book character are you, esteemed one? I don't remember reading about you.}
{201}{}{What are you babbling about, old fart?}
{202}{}{Oh, sorry, sorry! Can't a man fantasize anymore? By the way, I'm Phil. Sort of a scientist, if you can call it that.}
{203}{}{Nice to meet you, Phil. It's rare to meet scholars these days.}
{204}{}{Hello, biblioPHILE.}
{205}{}{I'm a real person, not a character.}
{206}{}{Hmmm? (peering at you through his glasses) Where does this confidence come from? Well, it doesn't matter, it can't be proven or disproven anyway. By the way, I'm Phil. Sort of a scientist, if you can call it that.}
{207}{}{Hmm. Perhaps this is a heroic novella or something like that.}
{208}{}{Oh, I like it when people can be ironic about themselves. Unlike those gloomy types behind the wall. They got so serious with building their city, more than they ever were in their whole lives. By the way, I'm Phil. Sort of a scientist, if you can call it that.}
{209}{}{}

{210}{}{Do you need any help?}
{211}{}{No, nothing.}
{212}{}{Hey, which book character are you, esteemed one? I don't remember reading about you.}
{213}{}{Oh, sorry, sorry! Can't a man fantasize anymore?}
{214}{}{It seems you are completely immersed in literature.}
{215}{}{Oh, I like it when people can be ironic about themselves. Unlike those gloomy types behind the wall. They got so serious with building their city, more than they ever were in their whole lives.}
{216}{}{That's natural.}
{217}{}{Hmmm? (peering at you through his glasses) Where does this confidence come from? Well, it doesn't matter, it can't be proven or disproven anyway. Oh, what a mundanity!}
{218}{}{Life is generally a boring thing unless you entertain yourself.}
{219}{}{I won't argue with that.}

{220}{}{Who are you?}
{221}{}{I'm Phil. Sort of a scientist, if you can call it that. The brain of this city, if you will.}
{222}{}{Really?}
{223}{}{Well, I helped with everything that required pre-war knowledge - from old manuals to programs for Mr. Handy.}
{224}{}{Got it.}
{225}{}{And I'm also the world chess champion. No one, not even those cunning commies, could beat me. And those were life-or-death matches!}
{226}{}{Interesting.}
{227}{}{How about a game of chess? I'm sure I can beat you and break the world record.}
{228}{}{How about a game of chess? I will beat you and break the world record.}
{229}{}{You? Don't make the old man laugh! You don't stand a chance. I'm the only one who managed to beat the artificial intelligence of ZAX. What can you say about yourself?}
{230}{}{I still want to try.}
{231}{}{A waste of time.}
{232}{}{Then forget it. I'll find something else to do.}
{233}{}{You already made a mistake by saying I have no chance. There are always chances. I challenge you to a duel.}
{234}{}{Oh, it sounds tense, like in a good novel. I'll give you one chance. Just one game. If you beat me - you'll get access to my library.}
{235}{}{I need to prepare for the match. See you.}
{236}{}{I'm ready for a battle on the chessboard. Let's begin!}
{1236}{}{I'm ready for a battle on the chessboard. Let's begin!}
{237}{}{Not bad. Quite good for an amateur. However, you need a lot more practice to defeat me.}
{238}{}{Well, it didn't work out.}
{239}{}{Maybe we should talk about something else?}
{240}{}{You defeated me? Extraordinary!}
{241}{}{Do you want to play a game of chess?}
{242}{}{Now you see that it's not worth underestimating your opponents?}
{243}{}{It was definitely a fluke. Sorry for breaking your world record.}
{1243}{}{It was definitely a fluke. Sorry for breaking your world record.}
{244}{}{I don't understand how that could happen. After all, in 90 years I've studied ALL possible moves in chess. But that move of yours... Why couldn't I predict it? Maybe I've just lost my edge without competitors. That's why it's important to have an enemy! We definitely should learn from each other.}
{245}{}{By the way, yes. Will you let me read your library?}

{250}{}{What is there to do in this city?}
{251}{}{Let me think. Butler must have some tasks. He is trying to bring the city back to life, and also dealing with the influx of strangers from the north. Everyone else has problems too. Each has their own.}
{252}{}{Can't you be more specific?}
{253}{}{Sorry, but lately I've been so engrossed in this wonderful novel that I stopped keeping track of what's going on in the city.}
{254}{}{Got it.}
{255}{}{What are you reading?}
{256}{}{Right now I'm reading some old book about conquistadors in Spanish. Boring. Not my thing.}
{257}{}{Do you need a specific book? I can look for it.}
{258}{}{Alright, never mind. Keep reading.}
{259}{}{Oh, there is one book! Just before the war, a new book by Mortimer was announced in San Diego. I'm curious about what nonsense he could have written about this wonderful city.}
{260}{}{Where can I find it?}
{261}{}{Somewhere in the ruins, I suppose. I don't know exactly.}
{262}{}{Alright, I'll look for it.}
{263}{}{Then look for it yourself. I have more important things to do.}
{264}{}{You're in luck. I have that book right here.}
{265}{}{I found Mortimer's new book.}
{1265}{}{I found Mortimer's new book.}
{266}{}{A new book! Oh, how long it's been since I felt this thrill before a fresh edition. Let's see what sensational stuff Mortimer scraped together about San Diego... Oh yes, you probably expect some payment. Here's 100 hubbucks. Now go, go, don't bother me reading!}
{267}{}{Goodbye.}

{270}{}{Right now I'm reading an old book about conquistadors in Spanish. Boring. Not my thing.}
{271}{}{Right now I'm reading the Vancouver city phone directory. Very monotonous narrative.}
{272}{}{Right now I'm reading stories about the last oil wars. You know, back then whole countries were capturing our oil tankers. Good thing it's all over.}
{273}{}{Right now I'm reading a set of rules for flying a dirigible. You laugh? Well, someday someone will fly them again. Believe me.}
{274}{}{Right now I'm reading a story about how communists took over the USA and built a totalitarian state here. So far, it looks pretty good.}

{280}{}{I need a program for Mr. Handy.}
{281}{}{That's not difficult. But I'm so engrossed in this wonderful book. I can't tear myself away!}
{282}{}{What if I bring you even more books?}
{283}{}{More books?! Yes! Bring me five pre-war books, and I'll write that program. Easy.}
{284}{}{Alright.}
{285}{}{I have those books right here. Here they are.}
{286}{}{Ah, new additions! Well, nothing can be done, I'll have to tear myself away from reading. I'll write the program now. What was it you needed again?}
{287}{}{Hotel administrator program...}
{288}{}{Or maybe you'll just help a good person?}
{289}{}{I will certainly help a GOOD person, IF I see one.}
{290}{}{Jerk!}
{291}{}{So I'm definitely not a role model for you. That's sad.}
{292}{}{Forget it. I have books. Here they are.}
{293}{}{Phil, how can you be so selfish? We're all in this together. Come on, help me with this damn program!}

