{100}{}{You see Gomer.}
{101}{}{You see a super mutant. He is wearing an army helmet and camouflage pants.}

{102}{}{Don't you dare touch the Nightkin, normie!}
{103}{}{I won't forgive you for this, normie!}
{104}{}{Brothers, I am with you!}
{105}{}{My brothers are here? Ho-ho, then you know whose side I'm on.}
{106}{}{Don't you dare touch the Nightkin!}
{107}{}{I won't forgive you for this!}
{108}{}{Brothers, I am with you!}
{109}{}{I see my comrades-in-arms. Better not anger them.}

{110}{}{The Master was right - all of you should have been converted!}
{111}{}{Hello.}
{112}{}{[recruit to party]}
{113}{}{[remove from party]}
{114}{}{[holster weapon]}
{115}{}{Goodbye.}
{116}{}{That's right. No need to fight. Gomer approves.}
{117}{}{}
{118}{}{}
{119}{}{}

{150}{}{The dead live here. They don't like strangers. But they won't attack either.}
{151}{}{The largest ghoul camp. Normies come here too.}
{152}{}{The heart of the ruins. This place is poorly explored.}
{153}{}{Gomer hasn't been beyond the outpost yet.}
{154}{}{See the island? There was a naval base there. But it's destroyed.}
{155}{}{}
{156}{}{If you meet a wild beast, don't worry, Gomer will protect you.}
{157}{}{Gomer can't do that. Gomer is too big.}
{158}{}{You treat ghouls badly. Gomer is no longer in your team.}
{159}{}{Gomer leaves your company until you fix your reputation.}

#First Dialogue
{200}{}{A human among ghouls? Suspicious!}
{201}{}{No, I... never mind. Just don't touch me, big guy. Agreed?}
{202}{}{Even a human scolds Gomer. Ghouls don't want to see Gomer either. Gomer is not needed by anyone!}
{203}{}{Whoa-whoa, easy! I don't want you to get angry. I just thought ghouls don't get along with those like you.}
{204}{}{Humans are not welcome here either. Gomer was expelled from his squad. Ghouls said they would take care of Gomer if he was good and helped. Gomer is trying. But he is still not liked.}
{205}{}{Who needs you, a mountain of green meat?}
{206}{}{Gomer was expelled from his squad. Ghouls said they would take care of Gomer if he helped at the claim and behaved well. Gomer is trying. But he is still not liked.}
{207}{}{Sad. But understandable. }
{208}{}{What did you expect, you blockhead? You should have kept order while you were in the squad.}
{209}{}{Just a little more and Gomer will be respected. The ghouls will know how good I am. I will help the ghouls even if they don't want it.}
{210}{}{Great. I'm also helping the ghouls. Maybe we should join forces? You protect me on the road, and I'll help you earn respect.}
{211}{}{I have business here. What are you doing here? Are mutants and ghouls on the same side?}
{212}{}{Ghouls will never accept you. Forget about them and help me. I need your muscles.}
{213}{}{That's very noble of you. Good luck. I gotta go now.}
{214}{}{Go, human. I won't touch you as long as you don't touch the ghouls.}
{215}{}{Goodbye, Gomer.}
{216}{}{Maybe we should team up? I need your muscles on the road. I will help you regain respect.}
{217}{}{A mutant and a human in the same team? Ho-ho, funny. But if Gomer will be useful, he will be happy.}
{218}{}{Come with me. Together we will make a great team.}
{219}{}{Great. I'll come back when I need your help.}
{220}{}{What do you want, brother-mutant?}
{1220}{}{What do you want, sister?}
{221}{}{I don't need anything from you. Just don't touch me, big guy. Agreed?}
{222}{}{And you don't trust Gomer. Ghouls don't want to see Gomer. Gomer is not needed by anyone!}
{223}{}{What are you doing here? How did you end up among the ghouls?}
{224}{}{That's the spirit! You know, we could help each other: you protect me on the road, and I'll help you earn respect. Deal?}
{225}{}{If Gomer is useful to the ghouls, he will be happy.}
{226}{}{I need you. Come with me.}
{227}{}{Private Gomer will do his best!}
{228}{}{At ease, soldier.}
{229}{}{Private Gomer, you may be dismissed.}
{230}{}{Too bad. Gomer wanted to help. But don't forget Private Gomer.}
{231}{}{See you.}
{232}{}{Put away your weapon. It's not needed right now.}
{233}{}{Yes, putting away the weapon!}
{234}{}{Good boy.}

{240}{}{Awaiting orders, commander.}
{241}{}{At ease.}
{242}{}{Captain! Private Gomer is ready to help, captain!}

{250}{}{Will you come with me to the wasteland of Sonora? I could use your protection on the road.}
{251}{}{Leave for the humans? No way. Humans will not accept Gomer.}
{252}{}{Alright, as you say.}
{253}{}{Your comrades are currently besieging the caravaners. Can you talk them out of it?}
{254}{}{No, they won't listen to Gomer. They kicked Gomer out of the squad. Gomer has no authority over them. But Gomer will not allow his comrades to be killed!}
{255}{}{Got it.}

{260}{}{Tell me about yourself.}
{261}{}{Private Gomer. Why?}
{262}{}{Alright. Let's not talk about it.}
{263}{}{Is Gomer a name or a nickname?}
{264}{}{It's... uh... I totally forgot! Gomer is not a real name. It's a call sign for the radio. I don't remember my name. Everything before the Induction is forgotten.}
{265}{}{You don't remember who you were before the mutation?}
{266}{}{Exactly. And Gomer doesn't want to remember. Pathetic humans. They wallow in their petty problems. The Master tried to fix humans. But he didn't get to finish his work.}
{267}{}{You can tell me. The memories must torment you sometimes. You can't just erase an old life.}
{268}{}{Do you think that's why Gomer is so stupid? That's why he talks to himself at night? Gomer doesn't like to remember. He was a human, he ...................}
{269}{}{[Comfort]}
{270}{}{[Mock]}
{271}{}{How did you end up in Dayglow?}
{272}{}{With the squad. We walked through the desert for a long time. We were chased by the Brotherhood of Steel. Ugh, I hate the Brotherhood! They killed many comrades and drove us into the wasteland. There was no point in going back. We decided to leave.}
{273}{}{[Continue]}
{274}{}{On the way, we met ghouls. They told us about Dayglow. They were also fleeing from the normies. Normies hate everyone.}
{275}{}{Why aren't you with your squad?}
{276}{}{It was a time of hunger. Gomer was so hungry that he ate all the provisions. Shameful. For this, he was expelled from the squad. And he hasn't seen the squad since.}
{277}{}{Do you know where your squad is now?}
{278}{}{Somewhere in the ruins. Gomer will know if he listens to their communications on the radio.}
{279}{}{Now we know where your squad is. Do you want to meet your comrades?}
{280}{}{Gomer misses them. But Gomer is not needed by them.}
{281}{}{Don't worry about that. I'll take care of it. Let's go.}
{282}{}{Did you hear? Your captain is in trouble.}
{283}{}{Gomer is furious! Damn humans have caused so much trouble! They will pay!}
{284}{}{So you want to rescue the captain even though you were expelled from the squad?}
{285}{}{Gomer is ready to take the risk. Let's go, human! Forward!}
{286}{}{Alright. Let's go.}
{287}{}{Alright. If you don't want to, we won't deal with them.}
{288}{}{I have a radio, but due to high radiation, it won't work without a functioning radio station.}
{289}{}{I have a radio. Shall we try?}
{290}{}{It's useless. High radiation interferes. We need a strong antenna. Maybe the ghouls have one?}
{291}{}{So that's why the radio doesn't work! Alright, maybe we can find a relay.}
{292}{}{(Gomer adjusts the frequency and carefully listens to the communications. All the veins on his face bulge from concentration. Finally, he says: "They are in Balboa Park.")}
{293}{}{Good. Then we go to the park.}
{294}{}{There was a radio station in San Ysidro. Let's try to find out there.}
{295}{}{There's a radio station here. Shall we try?}
{296}{}{It's useless. It doesn't work.}
{297}{}{Indeed. It doesn't work.}
{298}{}{Nothing can be heard! We need to go to a higher area.}
{299}{}{Alright.}

{300}{}{This is it! The damned paladins are holding the captain here.}
{301}{}{What's your plan?}
{302}{}{Plan? Gomer doesn't need a plan! Gomer is stronger than any paladin. He'll kick their butts. That's the plan.}
{303}{}{Good plan. Reliable as atomic clocks. Go ahead, Gomer! Kick those bastards' butts!}
{304}{}{No, Gomer, you can't kill the paladins. It's dangerous and it's not right. We must rescue the captain without violence. Do you understand?}
{305}{}{Grrr! Damn humans! Gomer wants to fight! Gomer will not hide in the shadows!}
{306}{}{If you think about it, your idea is the simplest and most reliable. Go ahead, Gomer! Kick those bastards' butts!}
{307}{}{No way! We have little chance in an open fight. Let's scout first.}
{308}{}{If Gomer sees a paladin, he will not hold back. Keep that in mind, human.}
{309}{}{Alright. I'll keep that in mind.}
{310}{}{You know, it would be better if I scout first and you wait here. That's an order, Gomer.}
{311}{}{Gomer is grateful to you for saving the captain. He couldn't have done it alone without you. Thank you.}
{312}{}{A mutant saying "thank you"? That's something new!}
{313}{}{Don't thank me yet. We still need to meet with your squad.}
{314}{}{Yes. Gomer must meet the squad again.}
{315}{}{Then let's go to the camp. Let's go.}
{316}{}{So, what about the captain?}
{317}{}{Hang in there, Gomer. The captain is no more. And neither is your squad.}
{318}{}{DAMN BROTHERHOOD! I HATE THEM! I HATE THEM!}
{319}{}{I think it's best to leave you alone for now.}
{320}{}{Hang in there, Gomer. The captain is no more.}
{321}{}{What do you plan to do now without your squad?}
{322}{}{Gomer will work hard in the ghoul mines. The ghouls need his muscles. The ghouls won't regret taking him into service! Yes. So Gomer will be useful. He will be happy to be of service. That's what Gomer wanted.}
{323}{}{I see. Well, I hope you'll stick with me a bit longer before I return to Sonora.}
{324}{}{The squad is ready to accept you again.}
{325}{}{The comrades have forgiven Gomer? This brings joy to Gomer! But Gomer has already promised to help the ghouls. And can he justify the trust if he couldn't once before? Tell me, human, what should Gomer do? What is the best choice for Gomer?}
{326}{}{I think you should go with the squad. Only among your own will you be truly happy. And the ghouls don't owe you anything.}
{327}{}{You should stay with the ghouls and help them rebuild the city. Your strength will greatly help them. And your squad has already rejected you once; they might do it again. Besides, it's unknown what will happen to them on the road.}
{328}{}{Gomer will do everything to never lose trust again! The squad won't regret taking him back. Yes. So Gomer will be at peace among his own. He will be useful and happy. That's what Gomer wanted.}
{329}{}{Good that we sorted out your problem. I hope you'll stay with me a bit longer before your squad leaves Dayglow.}

