{100}{}{You see a ghoul.}
{101}{}{You see a regular ghoul.}
{102}{}{Z-z-z...}

{110}{}{Ugh...}
{111}{}{Ah...}
{112}{}{Pain...}
{113}{}{Still hurts...}

{200}{}{Hey, human, help me! I got a bit caught in a collapse and broke a couple of bones. These old houses are completely worthless now...}
{201}{}{Hey, buddy, help me! I got a bit caught in a collapse and broke a couple of bones. These old houses are completely worthless now...}
{202}{}{Oh my god! Don't move, I'll help you right away!}
{203}{}{Dream on. I don't even want to dirty my hands on a freak like you.}
{204}{}{I'm not going to help you. I'll just take your stuff and leave you to die. And by the way - no one else will hear you here.}
{205}{}{Oh no! No! Nooo...}
{206}{}{See you in the afterlife. Maybe.}
{207}{}{I'm just kidding, old man! Hold on, I'll heal you soon.}
{208}{}{I never expected a human to help me, especially in the heart of radioactive ruins. Thank you, friend.}
{209}{}{You're welcome. By the way, what were you doing here?}
{210}{}{Don't forget to tell the other ghouls about my heroics. How did you end up here, anyway?}
{211}{}{Exploring the ruins, obviously. But the floors here are very fragile. Tread carefully, friend. Oh, and that's not the main danger. From the window, I saw some creature. Huge, terrifying, with claws like sabers. Don't let it catch you. Now, good luck. I'll try to hobble to the nearest camp.}
{212}{}{Thanks for the warning. Goodbye.}
{213}{}{I don't recall your face. We didn't cross paths in the Necropolis, did we? Strange. But anyway - thank you, friend. Without you, I wouldn't have been able to even break down the front door.}
{1213}{}{I don't recall your face. We didn't cross paths in the Necropolis, did we? Strange. But anyway - thank you, friend. Without you, I wouldn't have been able to even break down the front door.}
