{100}{}{You see Mr. MedBot.}
{101}{}{You see a Mr. MedBot series medical robot.}
{102}{}{Wee-oo! Wee-oo! Make way for the medics!}

{200}{}{I deeply regret that I couldn't save these people!}
{201}{}{Sir, it is unsafe for you to be here.}
{202}{}{Sir, if you contract radiation sickness, I will not be able to help you.}
{203}{}{Sir, I am detecting elevated radiation levels. You should leave this place.}
{204}{}{I'm doing my best. But these people cannot be brought back to life.}
{205}{}{Sorry, sir, but I need to treat these people.}
{206}{}{There are so many injured here, it's like a war just happened.}
{207}{}{Do you know any of these patients?}
{208}{}{}
{209}{}{Oops, wrong door.}

{1200}{}{I deeply regret that I couldn't save these people!}
{1201}{}{Ma'am, it is unsafe for you to be here.}
{1202}{}{Ma'am, if you contract radiation sickness, I will not be able to help you.}
{1203}{}{Ma'am, I am detecting elevated radiation levels. You should leave this place.}
{1204}{}{I'm doing my best. But these people cannot be brought back to life.}
{1205}{}{Sorry, ma'am, but I need to treat these people.}
{1206}{}{There are so many injured here, it's like a war just happened.}
{1207}{}{Do you know any of these patients?}
{1208}{}{}
{1209}{}{Oops, wrong door.}

{210}{}{I have a fracture. Help me, doc!}
{211}{}{Oh, that's very bad. You need urgent hospitalization. Please lie down, I will try to help you.}
{212}{}{[Follow MedBot's instructions]}
{213}{}{You're okay. Be more careful in the future.}
{214}{}{Thanks.}
{215}{}{Can you heal?}
{216}{}{Of course. I am a medical assistant robot. But at the moment my capabilities are limited due to a lack of medical supplies. Can I help you in any way?}
{217}{}{No, not today.}
{218}{}{No way! I won't trust my life to some soulless machine.}
{219}{}{Private Gomer has a serious injury. Can you heal it?}
{220}{}{Private Gomer is fine.}
{221}{}{Thanks.}

