{100}{}{You see a ghoul guard.}
{101}{}{You see a ghoul dressed in combat armor.}
{102}{}{We don't tolerate competitors. Get out of here!}
{103}{}{If you were really a patrol officer, you wouldn't have any authority here.}
{104}{}{Were you allowed to be here?}
{105}{}{Big changes are coming for us.}

{200}{}{Let's get this straight right away, smoothskin. You're not welcome here. But if you behave, no one will harm you. Got it? Good. Now, tell me what you need.}
{201}{}{Welcome, brother. Have you been well received in San Ysidro? Do you need anything?}
{1201}{}{Welcome, sister. Have you been well received in San Ysidro? Do you need anything?}
{202}{}{I just want to ask a few questions about Dayglow.}
{203}{}{What do you need?}
{204}{}{Nothing. For now.}
{205}{}{Ask away.}
{206}{}{I gotta go. Thanks for your time.}
{207}{}{Got it. I've got some more questions, okay?}
{208}{}{}
{209}{}{}
{210}{}{Tell me about yourself?}
{211}{}{Retired Sergeant Robert Newsom. Before the war, I kept order in the streets of Bakersfield, and now I keep order in Dayglow. I love my job. And I won't let anyone mess around in my territory.}
{212}{}{What do you think of Gustavo?}
{213}{}{He's well-suited for the role of mayor. And the ghouls respect him. At least here, in San Ysidro. Though in Old Town, not everyone is as reasonable.}
{214}{}{Who runs Old Town?}
{215}{}{John Butler. A former military man. So his head is a mess. He has gathered around him not only ghouls but also super mutants and normies. Everyone needs something from him.}
{216}{}{What are the relations between Gustavo and Butler?}
{217}{}{They've had a lot of disagreements lately. But I'm sure it won't break their friendship.}
{218}{}{}
{219}{}{}
{220}{}{Tell me about the area around here.}
{221}{}{San Ysidro and Old Town are the main ghoul settlements. Between them are radioactive ruins and burnt parks. Rogue scavengers and monsters are often encountered in them.}
{222}{}{[Next]}
{223}{}{The nuclear strikes mostly hit the naval base and industrial zone. The center of San Diego also suffered greatly. Ruins, high radiation, skeletons - that's what you'll find in the ruins. And there are military robots everywhere. They wandered off after the alarms went off at the naval base.}
{224}{}{Tell me how to get to Chula Vista.}
{225}{}{You need to cross the Otay River valley. There's only one surviving bridge, but it's patrolled by robots and booby-trapped. So we either go around or straight through the valley. But there are a lot of horrible creatures in the valley.}
{226}{}{Tell me how to get to Bonita Dam.}
{227}{}{Follow Federal Highway 805 to the sign. Then turn right.}
{228}{}{Tell me how to get to Old Town.}
{229}{}{Going straight through the ruins will be very difficult. It's easier to get on Highway 805 and go to Balboa Park. Beware of monsters in the park. Go left into the Little Italy area. Then head north.}
{230}{}{What are your relations with the rogue scavengers?}
{231}{}{Mostly they're scavengers. They collect fragments of the Old World, often not even understanding what they are for. Then they sell them to caravans. Leaving the ghouls with mere crumbs. But they also kill whoever crosses their path. Gustavo is trying to drive them out of our ruins, and Butler wants to tame them, giving Set's Seal to the most obedient.}
{232}{}{What are your relations with the super mutants?}
{233}{}{Super mutants? The Master's army has split into many fragments and scattered around the ruins. There are many such groups in the vicinity. Some are aggressive, some cooperate with us, others are on their own. Lost souls.}

{241}{}{We are looking for his squad with Gomer. Have you heard about them?}
{242}{}{I've heard that the super mutants set up camp in Balboa Park. They are not aggressive, rather the opposite. Maybe it's the squad you're looking for.}
{243}{}{Got it. Thanks.}

