{100}{}{You see a ghoul.}
{101}{}{You see one of the ghouls. He looks especially worn out.}

{102}{}{Hello. Where did such a handsome guy come from?}
{1102}{}{Hello. Where did such a beautiful girl come from?}
{103}{}{Hello, friend. Be careful in the ruins.}
{1103}{}{Hello, friend. Be careful in the ruins.}
{104}{}{Save me from these dumb mutants!}
{105}{}{The last time I got roughed up like this was before the war. Criminals then, mutants now - not much has changed.}
{106}{}{Phew, I thought I was done for. Here, take a stimpak and my thanks as a reward. Thank you, friend.}
{1106}{}{Phew, I thought I was done for. Here, take a stimpak and my thanks as a reward. Thank you, friend.}

{110}{}{Don't touch me, we're of the same blood!}
{111}{}{I won't tell anyone I saw you. Honest.}
{112}{}{Just not the face! I only have one tooth left...}
{113}{}{Leave me alone!}
{114}{}{I have nothing edible!}
{115}{}{Somebody, help!}
{116}{}{What do you want from me?}
{117}{}{I told you - I don't have any food.}
{118}{}{Maybe you should hunt in the wasteland, huh?}
{119}{}{Guys, let's be friends, okay?}
