{100}{}{You see Falik.}
{101}{}{You see an ordinary ghoul.}
{102}{}{You eavesdropped on the ghoul's confession.}
{103}{}{Don't disturb my prayer!}
{104}{}{Sorry for treating you so badly at first.}

{105}{}{Hey, don't eavesdrop!}
{106}{}{Actually, I'm in confession. Do your business quickly.}
{107}{}{You're interrupting my confession, little human!}
{108}{}{Are you eavesdropping?}

{110}{}{Father, you can keep a grave secret, right?}
{111}{}{Can I tell you my story?}
{112}{}{Listen to me, Father.}
{113}{}{My friend Zerah, though a ghoul, is now literally a dead ghoul.}
{114}{}{Well, not exactly because of me...}
{115}{}{But I abandoned him.}
{116}{}{It happened in the hospital, damn it to hell.}
{117}{}{Zerah and I were foraging when we stumbled upon scavengers.}
{118}{}{I still get goosebumps! And I don't even have skin.}
{119}{}{The scavengers caught and killed Zerah. And I ran away and hid.}
{120}{}{Tell me, Father, will God forgive me?}

{200}{}{(Falik is praying fervently.)}
{201}{}{I accidentally overheard your confession.}
{1201}{}{I accidentally overheard your confession.}
{202}{}{[Leave him.]}
{203}{}{You bastard! Just dare to tell anyone!}
{204}{}{I'm not blaming you. I understand. You acted wisely.}
{205}{}{Oh, friend, please don't tell anyone!}
{206}{}{Really? Well, thank you. But Zerah can't be brought back.}
{207}{}{Are you even sure he died?}
{208}{}{Skags like you doesn't deserve my attention. A pathetic coward and weakling, how could you abandon your friend in trouble!}
{209}{}{It's easy for you to say! You weren't there! You didn't even know Zerah. Why do you care?}
{210}{}{Are you sure he's dead?}
{211}{}{It couldn't be any other way! His body is probably still lying in the hospital. But I don't dare go there to retrieve it and bury it with honor.}
{212}{}{I can do that. Not for free, of course.}
{213}{}{Okay, I'll look for his body. Your story moved me.}
{214}{}{I don't need your help! Just leave me alone and don't touch me again.}
{215}{}{Don't worry so much. Adios.}
{216}{}{I would appreciate that.}
{217}{}{Don't worry about it. Adios.}

{220}{}{(Falik is still praying fervently.)}
{221}{}{[Leave him.]}
{222}{}{Zerah really is dead. His body is lying in the hospital.}
{223}{}{(pause) Ahh. I knew it. I shouldn't have gotten my hopes up. But at least now I know for sure.}
{224}{}{Life is such a bitch. Goodbye.}
{225}{}{I'm very sorry.}
{226}{}{Zerah turned out to be alive. The scavengers captured and tortured him. But I managed to rescue him.}
{227}{}{HE'S ALIVE?! Oh my God, my prayers have been answered! You must have been sent to me by heaven.}
{228}{}{No, God has nothing to do with it.}
{229}{}{Let it be so, if you wish.}
{230}{}{Can I ask you for one more favor? Can you help me reconcile with him? Find him and tell him I want to ask for his forgiveness!}
{231}{}{}

