{100}{}{You see Rupert.}
{101}{}{You see a ghoul in a pre-war suit.}
{102}{}{You see a ghoul.}
{103}{}{If it weren't for De Santi, we would have reunited a long time ago.}
{104}{}{Hey, hello. You look pretty good for a corpse.}
{105}{}{Ugh! I can never get used to your disgusting smooth faces.}
{106}{}{Oh-h!}
{107}{}{You sure know how to ruin the fun.}

{200}{}{Hey, hello. You look pretty good for a corpse.}
{201}{}{I'm not a corpse.}
{202}{}{Well, then you're lucky. I'm lucky too. I keep scoring more points each time!}
{203}{}{Well, that...}
{204}{}{Ah, if only I were always this lucky! I thought my old age would be pretty sad, but in this hotel, I feel younger than ever! And it's so much fun!}
{205}{}{Actually, I...}
{206}{}{Glad that...}
{207}{}{And now, excuse me, daddy needs a new pair of shoes. Ah, what the heck! I'm betting on red!}
{208}{}{I won't interfere.}
{209}{}{Watch it, old man, don't lose your soul.}

{220}{}{Don't mumble under your breath, my cards are hot!}
{221}{}{[Ignore him]}
{222}{}{Tell me, old man, what's your name?}
{223}{}{My name is The-Luckiest-Son-of-a-Gun-in-the-World!}
{224}{}{I'm serious.}
{225}{}{Listen, don't be such a bore. I'm not planning to be friends with you anyway. Call me old man if you want. I don't care.}
{226}{}{Alright. As you say, old man.}
{227}{}{Your name is Rupert, isn't it?}
{228}{}{Cough-cough! I don't know who you're talking about. Never heard that name before.}
{229}{}{Maybe I should ask the receptionist? Or look in the guest book?}
{230}{}{Really? Well, then sorry for bothering you.}
{231}{}{What is it that you want? Who sent you?}
{232}{}{Miss Judy. She's looking for her missing husband. And it looks like he's secretly wasting all his money here.}
{233}{}{(sigh) Listen, buddy. Do you think I'd be hanging around here if I wanted to reunite with Judy?}
{234}{}{I don't really care.}
{235}{}{Then what's the reason for this behavior?}
{236}{}{You're a man, you should understand what it's like to be nagged by your wife for 80 years!}
{1236}{}{You're a woman, you can't understand what it's like to be nagged by your wife for 80 years!}
{237}{}{[Listen]}
{238}{}{I feel good here. I do what I want - drink, watch movies, play roulette! You know, Judy never let me play this damn roulette. And I've always wanted to.}
{239}{}{You know it's a pretend game, right?}
{240}{}{Well, yeah. But it doesn't matter - what matters is that I finally get to play it!}
{241}{}{She won't be happy if she finds out you've been hiding from her while she was looking for you.}
{242}{}{I know. Listen, tell her I'm dead, will you? It's no big deal for you, and I'll be able to live without her total supervision for a little longer.}
{243}{}{Alright. Why not?}
{244}{}{You'd really do that? Oh, I'm so lucky today! So lucky!}
{245}{}{Alright, goodbye.}
{246}{}{No. You have to meet with her. She's the closest person to you. It's not right to hide from her at the end of your life.}
{247}{}{Why do you have to ruin my fun? (sigh) Alright. You're right. She'll find out the truth from you anyway.}
{248}{}{Yeah. Go and talk to her. She lives in San Ysidro.}

{250}{}{As you asked, I told her you were dead. And you know what happened? Her heart couldn't take it and burst!}
{1250}{}{As you asked, I told her you were dead. And you know what happened? Her heart couldn't take it and burst!}
{251}{}{How... it can't be... I didn't expect that... Oh... ugh...}
{252}{}{Don't tell me you're going to kick the bucket now too.}

