{200}{}{Senor }
{1200}{}{Senora }
{201}{}{! Do not be afraid, this robot is a messenger. It has brought you an important message.}
{202}{}{What message?}
{203}{}{"Dear amigo, I know about your deeds in the Sonoran Desert. Whatever guided you and whatever you're striving for, your experience is invaluable."}
{204}{}{[Listen further]}
{205}{}{"History is being made in the ruins of San Diego right now. You should be there. The local ghouls do not trust humans. They are divided and weak. This may lead to a terrible mistake. They need a hero."}
{206}{}{[Listen further]}
{207}{}{"The caravan gathering for the journey to the ghoul city is taking place on the outskirts of Inferno. You will be given a special permit to freely explore the urban ruins around Old Town."}
{208}{}{[Listen further]}
{209}{}{"When you get to Old Town, drop by the junk shop and get an encrypted holodisk with instructions. I am counting on your help and wish you luck."}
{210}{}{[Listen to the message again]}
{211}{}{[End the message]}
{212}{}{Gah???}
