{100}{}{You see a paladin.}
{101}{}{You see a Brotherhood of Steel paladin.}
{102}{}{Greetings, brother.}
{1102}{}{Greetings, sister.}

{110}{}{What the hell is going on?}
{111}{}{Damn alarm!}
{112}{}{What's all this noise, damn it?}
{113}{}{Hmm, strange.}
{114}{}{Huh? A false alarm?}
{115}{}{Freaking alarm!}

{120}{}{Damn technology!}
{121}{}{Enough already with the ringing!}
{122}{}{How do I turn it off?}
{123}{}{Too bad there are no knights nearby...}
{124}{}{How does it even work?}
{125}{}{It's easier to blow it up than to turn it off, I swear!}

{130}{}{Strange. Why did it go off?}
{131}{}{This siren won't ring anymore.}
{132}{}{Amazing that the alarm still works.}
{133}{}{I think I've definitely turned it off now.}

{200}{}{Stop! This place under guard. You'll have to leave. Immediately.}
{201}{}{Alright, alright, I'll leave immediately.}
{202}{}{First, try to move me, idiot!}
{203}{}{I'm also from the Brotherhood of Steel. Scribe }
{204}{}{I'm also from the Brotherhood of Steel. Knight }
{205}{}{I'm also from the Brotherhood of Steel. Paladin }
{206}{}{I'm also from the Brotherhood of Steel. Scout }
{207}{}{, Sonoran division.}
{208}{}{Glad to meet you, brother. You can stay here, under our protection.}
{1208}{}{Glad to meet you, sister. You can stay here, under our protection.}
{209}{}{May I know what you're doing here?}
{210}{}{We have a small mission. We captured the super mutant captain and are currently interrogating him. Once we're done, we'll kill him. No need to worry, he's under secure guard.}
{211}{}{Oh, that's great. Congratulations.}
{212}{}{Stop! Let me explain again - you can't be here. Leave. Immediately.}
{213}{}{Don't make us angry. This is your last warning. YOU. CAN'T. BE. HERE.}
{214}{}{Enough! Idiots like you are beyond saving. You're in for a big beating!}
{215}{}{Oh, this is going to hurt...}
{216}{}{Dream on, braggart!}
{217}{}{I know who you have locked up. And I can tell you where his squad is located.}
{218}{}{Then speak! Any information will be valuable to us.}
{219}{}{The squad has set up camp in Balboa Park.}
{220}{}{We don't waste time with super mutants. They are an evil that must be eradicated. Thank you for the information. We appreciate your help.}
{221}{}{You're welcome.}
{222}{}{And what will you do with these super mutants?}
{223}{}{We don't waste time with super mutants. They are an evil that must be eradicated. So where are they located?}
{224}{}{Eradicate? You crazy fanatics! I won't let you kill the super mutants!}
{225}{}{We will soon send a team to eliminate the green threat. Thank you for the information. We appreciate your help.}

{226}{}{What the...how did you... No one's breaking out on my watch!}

