{100}{}{You see Tobias.}
{101}{}{You see a ghoul in a border guard uniform and hat. His face is disfigured, and his gaze is unsettling.}
{104}{}{Thank you. I always felt like something was missing here.}
{105}{}{Tobias attaches a badge to his uniform. You notice a semblance of a smile on his disfigured face.}
{106}{}{Tobias already wears such a badge.}

{200}{}{[You can't pass. This place is for ghouls only.]}
{201}{}{[Alright, I'll leave.]}
{202}{}{[I'll force my way through.]}
{203}{}{[Give me a task to pass.]}
{204}{}{[Destroy the robot in Tijuana.]}
{205}{}{[Okay.]}
{206}{}{[Robot neutralized.]}

{210}{}{Human, you don't belong here. Leave.}
{211}{}{You have no right to keep me out.}
{212}{}{(raises rifle) You won't pass until I allow it.}
{213}{}{I'm going through anyway. Get out of the way, freak!}
{214}{}{Alright, alright, I don't want it that badly...}
{215}{}{Why don't you want to let me in?}
{216}{}{Normies like you have no place in the city of ghouls. You're the ones who drove us into these ruins.}
{217}{}{Listen, I've come a long way here. Maybe we can work something out?}
{1217}{}{Listen, I've come a long way here. Maybe we can work something out?}
{218}{}{Well, I'll have to go. Sorry for the trouble.}
{219}{}{Hmm. Maybe I'll let you through if you do us ghouls a favor.}
{220}{}{What kind of favor?}
{221}{}{In the ruins of Tijuana, there's been a giant military robot roaming since before the War. It's preventing us from freely exploring the area. Destroy it, and I'll let you cross the border.}
{222}{}{I'd rather destroy you. It's much easier.}
{223}{}{Deal. I'll do it.}
{224}{}{The last sighting of this robot was near the bullring. We've set up electromagnetic traps there, but so far, no luck.}
{225}{}{Got it. I'll keep that in mind.}
{226}{}{I've encountered this robot already. It's no longer a threat to anyone.}
{227}{}{I'm not suicidal. I'd rather return to Sonora...}
{228}{}{You won't pass the border until I give you permission.}
{229}{}{The robot. It's destroyed.}
{230}{}{You must have a really good reason to cross into the city. Well, go ahead. Welcome to Dayglow.}
{231}{}{Thanks for the warm welcome.}
{232}{}{You should have just let me through from the start. What a waste of time...}
{233}{}{Greetings, brother. First time in Dayglow?}
{1233}{}{Greetings, sister. First time in Dayglow?}
{234}{}{Yes. Will you let me into the camp?}
{235}{}{Of course! But you'll need to undergo inspection. It's the rules, sorry.}
{236}{}{I understand.}
{237}{}{You know what, I've changed my mind about going to the camp. Goodbye!}
{1237}{}{You know what, I've changed my mind about going to the camp. Goodbye!}
{238}{}{Alright. What's your name and where are you from?}
{239}{}{I'm }
{240}{}{ from Southern Arizona.}
{241}{}{Show me your backpack. Any prohibited items?}
{242}{}{Depends on what's forbidden here...}
{243}{}{Just kidding! You can go through to the camp.}
{244}{}{Seriously?}
{245}{}{Welcome to Dayglow!}
{246}{}{Thanks.}
{247}{}{In the past, illegal border crossings were punished. But since you're already here, I'll accept it. Just don't disturb the peace of the ghouls.}
{248}{}{No problem.}
{249}{}{Unexpected. Thank you. And welcome to Dayglow.}
{250}{}{You may pass.}
{251}{}{Goodbye.}
{252}{}{You can pass. I wouldn't have let you in, but someone at the camp made a fuss over you.}
{253}{}{I'll hang around here for a bit. Need any help?}

