{100}{}{You see Mister Officer.}
{101}{}{This robot bears a heavily worn badge. It appears to represent some authority here.}
{102}{}{Be vigilant, citizen. It's currently unsafe on the road.}

{110}{}{Stop! You are violating traffic regulations.}
{111}{}{Being on the highway violates current legislation.}
{112}{}{It is prohibited to be on the highway outside a vehicle.}
{113}{}{You are under arrest. Leave the roadway and lie face down on the ground.}
{114}{}{You will come with me to the police station.}
{115}{}{Surrender. You cannot escape justice.}
{116}{}{I mean you no harm. You have created this problem yourself.}
{117}{}{My program requires me to stop you.}
{118}{}{You can address all complaints in the presence of a lawyer.}
{119}{}{I won't let you escape until you pay the fine.}
{120}{}{It is my duty to stop you before you cause a traffic accident.}
