{100}{}{You see Kurt.}
{101}{}{You see an ordinary ghoul.}
{102}{}{I don't have any caps! NONE! NOT A SINGLE ONE!}
{103}{}{OKAY! OKAY! Here are the caps. Just don't hit me anymore!}
{104}{}{OKAY! OKAY! Here are all my caps. I don't have any more!}
{105}{}{Kurt surrenders.}
{106}{}{Hey, what do you want from me?}
{107}{}{What a mess!}

{200}{}{I'm feeling great today! Haven't relaxed like this in a long time... Hey, what do you want from me?}
{201}{}{Who are you?}
{202}{}{They call me Kurt. So what?}
{203}{}{I'm looking for you. I'm here for Mr. DeSantos' debts.}
{204}{}{Mr. DeSantos is really mad, huh? Let him be mad at himself! I'm not paying for his awful services in a crappy room. And anyway - a ghoul taking money from another ghoul - what a disgrace! Who does he think he is? Don't we look like we're trying to build communism here? Is it not obvious?}
{205}{}{Don't give me that. Fork over the caps!}
{206}{}{Mr. DeSantos won't leave you alone.}
{207}{}{I'm not paying! If he wants money, he can get it from you!}
{208}{}{Then I'll take the caps by force. Empty your pockets!}
{209}{}{Fine, I'll have to pay instead of you.}
