{100}{}{You see a rogue scavenger.}
{101}{}{You see a rogue scavenger.}
{102}{}{This is our turf. Get lost from here.}
{103}{}{We work with De Santi. If you need anything, negotiate with him.}

{200}{}{This is our turf. Get lost from here.}
{201}{}{I apologize. I will leave your territory right away.}
{202}{}{And what if I refuse? Is intimidation all you're capable of?}
{203}{}{This isn't your turf. This is Mister De Santi's turf.}
{204}{}{Who's that? Just another ghoul overgrown? Why should we care about him?}
{205}{}{You're operating illegally, aren't you? De Santi can provide you with Set's seal if you work for him.}
{206}{}{We don't need Set's seal! Otherwise, we would have had it by now. Get it?}
{207}{}{Looks like talking to you is pointless. You only understand brute force...}
{208}{}{[Walk away]}
