{100}{}{You see Derrick.}
{101}{}{You see a ghoul. He watches carefully those who walk the streets.}
{102}{}{My business collapsed with De Santi's death.}
{103}{}{Okay! Okay! I'll work for him. Just don't touch my fragile delicate body!}
{104}{}{Derrick isn't looking for another fight.}

{200}{}{Hey, smooth face. Where are you heading?}
{201}{}{None of your business.}
{202}{}{Okay, as you say.}
{203}{}{Adios.}
{204}{}{Maybe to Old Town, or maybe to the place across the street, or maybe nowhere. Why do you ask?}
{205}{}{Why do you ask?}
{206}{}{I can give you a lift. Or are you heading to the sanatorium? But it's only for ghouls. So I don't advise smooth faces to go there. Besides, there's nothing to do there. But I can get you all kinds of relaxation at a low price. Come to me, you won't regret it.}
{207}{}{Alright, let's see what you've got.}
{208}{}{I can give you a lift. Or are you heading to the sanatorium? It's only for ghouls. But beware, the prices there are as high as my late wife's nagging. I can get you all kinds of relaxation at a low price. Come to me, you won't regret it.}
{209}{}{Hmm, I'll keep that in mind.}
{210}{}{Hello, good-looking. Where are you heading?}
{211}{}{You'll come back for another dose.}
{212}{}{Sure. Bye.}
{213}{}{I doubt it very much.}
{214}{}{What do you mean by "I can give you a lift"?}

{220}{}{Ah, it's you again. What do you want this time?}
{221}{}{Oh, nothing special. Goodbye.}
{222}{}{Show me what you've got.}
{223}{}{"Where" isn't the question, it's "what". Let me see what you're selling here.}

{230}{}{Well, Derrick, you've caught my attention. De Santi isn't happy that you're intercepting his clients.}
{231}{}{This is free land. I want to trade here, and I will.}
{232}{}{Aren't you afraid this land will become your grave?}
{233}{}{I can understand admiring Wild West banditos. They faced each other in an honest duel. But De Santi was just a small fry in Bakerfield's bandit scene. And that's how he stayed. He can't scare me.}
{234}{}{Oh, alright. I don't want to get involved in this.}
{235}{}{You're talking too much, Derrick. I'll have to teach you a lesson.}
{236}{}{You'll regret this. Someday.}
{237}{}{Now you have a choice - die or work for De Santi. So, I'm waiting for your answer. One...}
{238}{}{Hey, hey, you're not really going to do dirty work for some former thug, are you?}
{239}{}{I'm not. I'm just kidding. Bye, Derrick.}
{240}{}{I don't care, as long as he pays. And I'm wasting my time with you. It's time to finish this!}
{241}{}{Two...}
{242}{}{Whoa, whoa, whoa, De Santi really ordered me? Seriously? Damn it!}
{243}{}{Three!}
{244}{}{Okay! Okay! I'll work for him. Just don't touch my fragile delicate body!}
{245}{}{Too late, Derrick. You've annoyed me. I'll have to punish you!}
{246}{}{Great. And let's keep it without nonsense. De Santi's the boss now.}

{250}{}{You said you "can give a lift."}
{251}{}{Well, I haven't had a car for a long time. But I know fast and safe routes. Where do you need to go?}
{252}{}{[San Ysidro for }
{253}{}{[Bonita Dam for }
{254}{}{ hubbucks]}
{255}{}{I think I'll walk.}
{256}{}{Not enough, huh? Too bad.}
{257}{}{Yes, I'll have to walk on my own.}
{258}{}{Wait, there's something else I need to find out.}
{259}{}{[Chula Vista for }

