{100}{}{You see a bath attendant.}
{101}{}{You see a regular ghoul woman in an old robe.}

{110}{}{I can give you a back rub, darling. Just pay the fee to the administrator first.}
{111}{}{Want to take a bath? I'll wash EVERY part of your body.}
{112}{}{We have radium water, radon baths, uranium jacuzzis, and plutonium showers here. Choose what you like best.}
{113}{}{A good scrub costs money. And my tenderness costs even more.}
{114}{}{With me, you'll forget all your problems, honey.}
{115}{}{Come on, take off your pants. I know where you can touch and where you can't.}
{116}{}{}
{117}{}{}
{118}{}{}
{119}{}{}
