{100}{}{You see a stranger.}
{101}{}{You see a man in a blue jumpsuit.}

#Cutscenes
{110}{}{   }
{111}{}{Who are you guys?}
{112}{}{None of your ghoul business. You'll be asking questions to Butler. Now get out of here.}
{113}{}{Mercenaries, huh. Of course, Butler won't back down so easily.}
{114}{}{But it's too late. Coronado belongs to the ghouls of San Ysidro. And you have no place here.}
{115}{}{Tch! We're just getting more radiation from this scum. Throw them off the pier, guys!}

{122}{}{None of your ghoul business. We won't let anyone sail to the island without our permission.}
{123}{}{Ah, rogue scavengers? Sure, everyone wants to get the treasures of Coronado.}
{124}{}{But Coronado belongs to ALL ghouls! San Ysidro has a claim too!}
{125}{}{Tch! We're just getting more radiation from this scum. We need to chase them away!}
{126}{}{But Coronado belongs to the GHOULS! Get off our land, smoothskins!}

#Final Dialogue
{200}{}{Hey, hey! Are you okay? Wake up!}
{201}{}{Wha... What happened?}
{202}{}{You passed out after the explosion. But it looks like you're fine. I was afraid you didn't get my invitation.}
{1202}{}{You passed out after the explosion. But it looks like you're fine. I was afraid you didn't get my invitation.}
{203}{}{There was a fight here. Someone threw a grenade, and you passed out from it. But it looks like you're fine. I was afraid you didn't get my invitation.}
{1203}{}{There was a fight here. Someone threw a grenade, and you passed out from it. But it looks like you're fine. I was afraid you didn't get my invitation.}
{204}{}{And who are you?}
{205}{}{You might have heard of me. But it doesn't matter. I'm glad you managed to complete this mission.}
{1205}{}{You might have heard of me. But it doesn't matter. I'm glad you managed to complete this mission.}
{206}{}{Do you think I made the right choice?}
{1206}{}{Do you think I made the right choice?}
{207}{}{I'm not here to judge your decisions. You did what you thought was right.}
{1207}{}{I'm not here to judge your decisions. You did what you thought was right.}
{208}{}{[Listen]}
{209}{}{}

{210}{}{Of course, the ghouls will be terribly upset that the remnants of the Old World won't be theirs.}
{211}{}{They could have been very useful to this world. But they could also fall into the wrong hands.}
{212}{}{Who knows, maybe because of that explosion the world avoided another catastrophe. Or maybe it was exactly those things from that base that were needed to bring civilization back on track. Either way, the base is finally destroyed. And with it, the discord among the ghouls.}

{220}{}{Of course, there will be some discord among the ghouls over the rights to the remnants of the Old World.}
{221}{}{Gustavo will try to take everything for himself and use it for the development of San Ysidro. He won't share with the human settlements, which also desperately need pre-war items. Butler will try to stop him.}
{222}{}{In the end, Gustavo will be stronger, he will lure most of the ghouls to his side. And then Dayglow will live its usual, dreary, peaceful life, closed off from the rest of the world. As many ghouls wanted.}
{223}{}{Gustavo will try to take everything for himself and use it for the development of San Ysidro. He won't share with the human settlements, although they also desperately need pre-war items.}
{224}{}{Dayglow will live its little closed xenophobic life. As many ghouls wanted.}

{230}{}{Of course, there will be some discord among the ghouls over the rights to the remnants of the Old World.}
{231}{}{Butler will start active trade with the human settlements to the north. For some of them, pre-war items will be lifesaving, for others - ruinous. San Ysidro will get mere scraps, turning it into a slum.}
{232}{}{Gradually, the resources will be exhausted. But thanks to trade, Dayglow will survive and live its usual, dreary, peaceful life. As many ghouls wanted.}

{240}{}{Of course, the ghouls will be terribly upset that the remnants of the Old World won't be theirs.}
{241}{}{The Brotherhood of Steel won't let anyone near this goldmine. The Order will take everything valuable and transport it to the main base.}
{242}{}{The ghouls will get mere scraps. Over time, people will forget about them. And then Dayglow will live its usual dreary life.}

{250}{}{Of course, there will be a great discord among the ghouls over the rights to the remnants of the Old World.}
{251}{}{Without their leaders, it will take them a long time to find a compromise of forces and interests. It will be a period of chaos and confusion. Including in the northern human settlements.}
{252}{}{Some pre-war items will fall into good hands, some - into bad ones. The ghouls will get the least. But they are used to it. Dayglow will become what Necropolis was before the ghouls left it. Apparently, that's their fate.}

{260}{}{Well. My business here is done. Yours probably is too. It was good to see you. Adios, amigo.}
{261}{}{Goodbye, stranger.}

