{100}{}{You see an old ghoul.}
{101}{}{You see a lone living dead. If it weren't for his frighteningly decayed appearance, he would seem quite friendly.}
{102}{}{The border guards are looking for you. I won't help you even for a pile of hubbucks.}
{103}{}{How did you find out about the secret passage? Even Tobias didn't know about it!}
{1103}{}{How did you find out about the secret passage? Even Tobias didn't know about it!}

#Introduction
{200}{}{(At first, it seems as if a withered corpse is sitting in the chair. But as you approach, the body slowly raises its head and, in a hoarse, drawn-out voice, says) Why are you here, human?}
{201}{}{I'm looking for a way to get into Dayglow.}
{202}{}{Our city is open only to the dead. The living have no business there.}
{203}{}{Oh, then I really shouldn't go there. Goodbye.}
{204}{}{And yet, I want to get there.}
{205}{}{I won't try to dissuade you. But Tobias is unlikely to let you across the border.}
{206}{}{Then I'll try to convince him. Goodbye, old man.}
{207}{}{Is there a way around?}
{208}{}{All other roads are extremely dangerous. But there's no need to go that far. I know a shortcut. I can guide you, but not for free. How many hubbucks do you have?}
{209}{}{Hubbucks?}
{210}{}{So, you're suggesting something clearly illegal. I'm not going THAT far. Goodbye.}
{211}{}{Caps! Bottle caps! They were invented in the Hub to replace pre-war money. So how many bottle caps do you have?}
{212}{}{I don't have any bottle caps.}
{213}{}{I don't have any hubbucks.}
{214}{}{You're lying. I know you came here with caps. How? (points a finger to his temple) X-ray vision. Hehe, just kidding.}
{1214}{}{You're lying. I know you came here with caps. How? (points a finger to his temple) X-ray vision. Hehe, just kidding.}
#Note: In reality, it's not X-ray vision, the ghoul guide just studied the PC and their belongings while they slept at one of the campsites.
{215}{}{You're raving, old man. I'd better leave.}
{216}{}{Alright, here's all my caps. Now take me to the city!}
{217}{}{Now - lower your head... Don't worry, I'll remove this bag when we reach the city. Trust me. Hehe, you're not the first one I've guided across the border.}
{1217}{}{Now - lower your head... Don't worry, I'll remove this bag when we reach the city. Trust me. Hehe, you're not the first one I've guided across the border.}
{218}{}{Ugh... Alright. But be careful.}
{219}{}{Don't even think of deceiving me, old man.}
{220}{}{I believe you. It's foolish, of course, to go across the border completely broke. What to do with you now? Alright, bring me three cans of good old Mexican beer. They can still be found in the ruins on Revolution Avenue.}
{221}{}{I hope they really are there.}
{222}{}{How about some irradiated Nuka-Cola? I found five whole bottles in the ruins.}
{223}{}{I have five bottles of non-irradiated Nuka-Cola. Will that do?}
{224}{}{Here are three cans of old beer.}
{225}{}{Deal. Looks like there's nothing else I can get from you.}
{226}{}{So you'll take me to the city?}
{227}{}{Did you find what I asked for?}
{228}{}{No. Maybe I was looking in the wrong place? I'll try searching the ruins again.}
{1228}{}{No. Maybe I was looking in the wrong place? I'll try searching the ruins again.}
{229}{}{}
{230}{}{Still can't get across the border, can you? I know a shortcut. I can guide you, but not for free. How many hubbucks do you have?}
{231}{}{Already leaving Dayglow? Well, it really is time for you to go.}
{232}{}{Goodbye.}
{233}{}{(You see the old man sitting in a chair; he slowly raises his head, showing his disfigured face; in a hoarse, drawn-out voice, he calls out to you) Ah, fresh blood! Glad to see you in our dead kingdom. If you need to cross the border, talk to Tobias, he'll be happy to let you through.}
{234}{}{Will do. Goodbye.}
{235}{}{Who is Tobias?}
{236}{}{Tobias is the guardian of the city gates. You could say he's the mediator between the world of the living and the world of the dead.}
