{100}{}{In front of you is an arcade machine.}
{101}{}{You see an arcade-style gaming machine. A timeless classic.}
{102}{}{To start the game, you need to pay. Current record: }
{103}{}{ (Unknown).}
{104}{}{ (}
{105}{}{).}

{200}{}{"Your spaceship is heading towards the center of the galaxy. Watch out! There's an asteroid field ahead! Dodge them up or down or fire plasma charges to destroy them. The longer you last, the more points you get!"}
{201}{}{Forward!}
{202}{}{Read the rules.}
{203}{}{Decline and take back the money.}
{204}{}{Decline.}

{210}{}{Control the spaceship (  }
{211}{}{) to avoid colliding with asteroids (}
{212}{}{). A collision with an asteroid takes one life. Dodge asteroids by moving up or down, but only within the three lines.}
{213}{}{}
{214}{}{You can also collect points (}
{215}{}{) and plasma charges (}
{216}{}{) during the flight. One charge destroys one obstacle, and a super shot clears the entire line ahead. Picking up an extra life (}
{217}{}{) is a great fortune.}
{218}{}{Close help.}
{219}{}{Next.}

# Do not remove spaces in the lines!
{220}{}{-|>  }
{221}{}{ [X] }
{222}{}{ -o- }
{223}{}{ -z- }
{224}{}{ ---}
{225}{}{ -Y-}
{226}{}{) }
{227}{}{ -Z-}
{228}{}{(}

{230}{}{Up.}
{231}{}{Forward.}
{232}{}{Down.}
{233}{}{-Up-}
{234}{}{-Down-}
{235}{}{Shot! (}
{236}{}{-Shot-}
{237}{}{Super shot!}
{238}{}{)}
{239}{}{Explosion! (}

{240}{}{Pause.}
{241}{}{Game paused. Lives: }
{242}{}{. Charges: }
{243}{}{. Points: }
{244}{}{. Your record: }
{245}{}{.}
{246}{}{}
{247}{}{}
{248}{}{}
{249}{}{-Explosion-}

{250}{}{Continue game.}
{251}{}{End game.}
{252}{}{Are you sure you want to end the game and lose your accumulated points (}
{253}{}{)?}
{254}{}{Return and continue the game.}
{255}{}{Yes. End the game.}
{256}{}{You lost!}
{257}{}{Stupid game! I won't play it anymore.}
{258}{}{Alright. I'll last longer next time.}
{259}{}{}

{260}{}{}
{261}{}{Decline. I don't need any of these prizes.}
{262}{}{Strength +1.}
{263}{}{Perception +1.}
{264}{}{Endurance +1.}
{265}{}{Charisma +1.}
{266}{}{Intelligence +1.}
{267}{}{Agility +1.}
{268}{}{Luck +1.}
{269}{}{Gambling +20.}
{270}{}{"Victory! You've beaten your own record. Do you wish to continue?"}
{271}{}{Yes.}
{272}{}{No.}
{273}{}{Enable survival mode.}
{274}{}{Disable survival mode.}
{275}{}{}
{276}{}{"Victory! You've broken the record and become the absolute champion."}
{277}{}{Cool!}
{278}{}{Finally.}
{279}{}{"Take your prize coupon."}
{280}{}{"Now you can play this machine for free. And that's not all. If the game seemed too easy, you can try survival mode. Good luck in space!"}
{281}{}{Alright.}
{282}{}{Really?}
{283}{}{In survival mode, transitions between lines (up and down) count as flight steps. Therefore, you need to remember the state of the lines and plan your moves ahead.}
{284}{}{Read more.}
{285}{}{Got it.}
{286}{}{However, you get twice as many lives and shots at the start, the path is visible two steps further, and the explosive shot destroys not only the asteroid ahead but also the ones on adjacent lines.}
{287}{}{Moreover, you get 1 point for each game step. You can exchange your points.}
{288}{}{}
{289}{}{}

{290}{}{Exchange points.}
{291}{}{You have }
{292}{}{ points.}
{293}{}{Continue game.}
{294}{}{1 shot for }
{295}{}{1 super shot for }
{296}{}{1 life for }
{297}{}{.}
{298}{}{The right to study the paths until the next move for }

