{110}{}{The substation is de-energized. No electricity is being supplied to it.}
{111}{}{The substation is operating normally.}
{112}{}{Following the instructions, you lower all the levers except for a few. Now the current is directed exactly where it needs to go.}
{113}{}{You press various switches, but nothing happens.}
{114}{}{The substation is currently disconnected from the grid.}

{200}{}{(Before you is a huge panel with numerous sockets.)}
{201}{}{[LEAVE]}
{202}{}{Hmm. Which sockets should the cable be plugged into?}

{210}{}{Socket }
{211}{}{8AVI}
{212}{}{W7VE}
{213}{}{PA3L}
{214}{}{ACM4}
{215}{}{SFX1}
{216}{}{2LIP}
{217}{}{DAT5}

{220}{}{Connect.}
{221}{}{Disconnect.}
{222}{}{[BACK]}
{223}{}{ (disconnected)}
{224}{}{ (connected)}

{230}{}{Start the substation with the main switch.}
{231}{}{Something went wrong. The fuse tripped and cut off the power.}
{232}{}{Oops. I'll try again.}

{250}{}{Some notes remain on the board:}
{251}{}{San Ysidro}
{252}{}{National City}
{253}{}{Chula Vista}
{254}{}{Old Town}
{255}{}{Otay Ranch}
{256}{}{La Mesa}
{257}{}{Otay Mesa}
{258}{}{ - }
{259}{}{}
{260}{}{Bulletin board.}
{261}{}{Someone left notes here. A quick glance at them doesn't give you any clues.}
{262}{}{These notes are now useless.}

