{100}{}{This is the substation computer.}
{101}{}{This is the substation control computer.}
{102}{}{The computer won't turn on.}
{103}{}{There might be no power coming to it.}

{200}{}{System is operating normally. Enter command.}
{201}{}{Leave the computer alone.}
{202}{}{Status of the power plant?}
{203}{}{The power plant is not responding.}
{204}{}{Status of the substation?}
{205}{}{The substation is not responding.}
{206}{}{Back}
{207}{}{Turn on the outdoor lighting at the station.}
{208}{}{Outdoor lighting is on.}
{209}{}{Turn on the indoor lighting at the station.}
{210}{}{Indoor lighting is on.}
{211}{}{Cancel the general alarm.}
{212}{}{General alarm canceled.}
{213}{}{Cancel combat readiness mode.}
{214}{}{Warning! Combat readiness mode canceled. All security robots are ordered to adopt passive protocol.}
{215}{}{Send repair robots to fix the monorail network.}
{216}{}{The power network has been restored.}

