{100}{}{You see Stanley.}
{101}{}{You see a terribly bony corpse in dirty, worn-out overalls. A piece of rebar sticks out of his head.}
{102}{}{Hello, pale one. You no longer look like a real ghost.}

{200}{}{Ah, don't take me, I still want to live!}
{201}{}{What are you talking about?}
{202}{}{What the hell are you screaming about?!}
{203}{}{Oh, dear, you're a human?! Whew, I thought you were a ghost. Why are you scaring me?}
{204}{}{I have the same question for you. Walking around here all dark in the night, with glowing eyes!}
{205}{}{Sorry, pale one, but I got so scared! You know, it's so lonely at these stations. There used to be rumors about a ghost train that took people's souls to hell. Now it's silly to believe in that, of course. We're already in hell.}
{206}{}{Sorry, it was an accident. I didn't expect to meet anyone here either.}
{1206}{}{Sorry, it was an accident. I didn't expect to meet anyone here either.}
{207}{}{Once upon a time, these stations were crowded with people. And now it's really deserted. Maybe the ghost train already took everyone to hell. Don't believe me? Well, look around-we're already in hell.}
{208}{}{So, what are you doing here?}
{209}{}{My comrades asked me to prepare the Blue Line for launch. I used to work in the metro, so I can do something. But not everything.}
{210}{}{What's needed for the launch?}
{211}{}{Firstly, we currently have no power. And it looks like the only place to get it is at the Bonita hydroelectric station, which has been well guarded since the War. We need to not only start the station but also direct it to the monorail substation.}
{212}{}{And secondly?}
{213}{}{Secondly, we need to repair the monorail line. The Mister Handy robots will do that for us once we power it up. They will dismantle some old lines for it. But we'll have to fix the tram depot's automation ourselves. I can't do it without an experienced electronics specialist. That thing is in the control room. Maybe a technician in San Ysidro can fix it, but it's damn heavy. Will you help me?}
{214}{}{Of course. Then I can use the monorail too.}
{215}{}{I'll do everything to make your lives easier, guys.}
{216}{}{Wonderful! Help, and I'll share part of the fee the city administration promised me.}
{217}{}{Alright. See you later.}
{218}{}{Before we start, I have a few questions for you.}

{220}{}{What do you say, pale one?}
{221}{}{What are you staring at, pale one?}
{1221}{}{What are you staring at, pale face?}
{222}{}{Hey, it's my pale-skinned brother! How are you?}
{1222}{}{Hey, it's my pale-skinned sister! Are you alright?}
{223}{}{Bye. See you.}

{230}{}{What is a monorail?}
{231}{}{You really don't know? What a bummer! Once, elevated trains ran on these rails. And it was cool. Help fix the line-you'll see it with your own eyes.}
{232}{}{Got it.}
{233}{}{What needs to be done to start the tram?}
{234}{}{First, power needs to be supplied to the Blue Line substation. Then repair the electronics in the control room. If you lack the skills, take the equipment to the technician in San Ysidro.}
{235}{}{Alright.}
{236}{}{Doesn't that thing in your head bother you?}
{237}{}{Thing? Oh, you mean the rebar. It's been sticking out of this head for about a hundred years. It's no big deal, I'm used to it. But it's better not to pull it out.}
{238}{}{Alright. As you say.}
{239}{}{It's a miracle! To be honest, I thought nothing would work. It's so surprising that I can hardly believe it. You're restoring my faith in people. Maybe not all is lost for you yet.}
{240}{}{Uh, okay.}
{241}{}{I'm not doing this for you.}
{242}{}{I guess I should share the fee with you - 1000 caps. And thank you... friend.}
{1242}{}{I guess I should share the fee with you - 1000 caps. And thank you... friend.}
{243}{}{You're always welcome... friend.}
{244}{}{I guess I should share the fee with you - 1000 caps. And thank you... partner.}
{245}{}{You're always welcome... partner.}
{246}{}{I guess I should share the fee with you - 500 caps. And thank you... partner.}
{247}{}{Is that all? You're no longer my "partner".}

