{110}{}{This is an operational radio station. It's working thanks to you.}
{111}{}{This equipment is running at full capacity.}
{112}{}{This radio station is used by the ghouls to communicate with other areas of Dayglow.}
{113}{}{This equipment does not require any repairs.}
{114}{}{You send a stand-down signal to all the border robots of San Ysidro.}
{115}{}{You transmit data about the new transponder to the naval base. The automation grants landing permission.}
{116}{}{No power.}
