{100}{}{This is a service computer.}
{101}{}{This computer is connected to the vault database.}
{102}{}{Studying the vault's history increased your experience.}

#Dialog
{200}{}{Access granted. Enter command.}
{201}{}{End session:}
{202}{}{Back}
{203}{}{Next}
{204}{}{Return to main menu}
{205}{}{Cancel}

{210}{}{Read security service reports.}
{211}{}{Select reporting period.}
{212}{}{February 2131}
{213}{}{"We have gathered data from the latest reconnaissance groups."}
{214}{}{"Alpha Group, sent to downtown San Diego, has not reported back. The last message mentioned high radiation levels and significant urban destruction."}
{215}{}{"Beta Group, which explored the piers, returned early, not even halfway through the route. They report high radiation levels and significant destruction. All bridges to Coronado Island are destroyed, and all military and civilian ships at the piers are either sunken or severely damaged. High robot activity, likely from a naval base, was observed along the shore. The group members have radiation sickness."}
{216}{}{"Gamma Group, which explored the southern areas, returned with a small amount of useful items and pre-war provisions. They report moderate destruction and elevated radiation levels."}
{217}{}{"Delta Group, exploring the eastern regions, reports a decrease in radiation inland and minor destruction. Unusual animals of unknown forms or sizes were found. Part of the group perished."}
{218}{}{"None of the groups could find any living people or recent traces of their presence."}
{219}{}{Return to the general list.}
{220}{}{April 2131}
{221}{}{"Zeta Group has returned from the West-Tek research complex. Only one person from the entire group survived. The survivor reports extremely high radiation levels and destruction in the complex. Security robots and animals of unknown forms were encountered around the complex."}
{222}{}{"Medical examination showed that the scout suffers from severe radiation sickness and unusual mutations, and is expected to die soon. Further exploration of the West-Tek complex is not recommended."}
{223}{}{May 2132}
{224}{}{"Epsilon Group returned from Los Angeles. The group reports a series of small settlements and camps, the largest of which is called Adytum. It is inhabited by people who survived the aftermath of the nuclear war in various parts of Southern California. These people survive by scavenging pre-war items from the ruins and then trading them."}
{225}{}{"It is also known about a large city called the Hub, north of Adytum, but there is very little information about it."}
{226}{}{"Scouts have conflicting views on the local population. Some of the group fear strangers, while others express a desire to merge with them into one settlement. Many scouts are likely experiencing cultural shock."}
