{110}{}{    }
{111}{}{Report, brother.}
{112}{}{They did it. The ghouls actually started the power plant.}
{113}{}{Those idiots! Now we have less time to prepare.}
{114}{}{So, maybe we should seize the dam? It's not right to leave such power to the outcasts...}
{115}{}{No, that will only distract us from the main objective.}
{116}{}{Besides, the station is needed by the ghouls for their city. They are unlikely to use it for harm.}
{117}{}{We need to act swiftly. Let's return to base. We need to discuss everything.}
