{110}{}{Vile creature!}
{111}{}{You're worse than a beast.}
{112}{}{I'll avenge every child you've murdered.}
{113}{}{Revenge for the children is inevitable.}
{114}{}{Do you hear the wails of the children you killed, you monster?}
{115}{}{You think you can just go around slaughtering children, don't you?}
{116}{}{You bastard, remember those innocent children!}
{117}{}{Children... How dare you harm these pure souls?}
{118}{}{I'm gonna end anyone who harms children.}
{119}{}{Even if those children's deaths were an accident, you'll pay.}
