#General
{110}{}{Before you can lock the door, you should close it.}
{111}{}{You lock the door.}
{112}{}{You unlock the door.}
{113}{}{It's too difficult to do this in the middle of a fight.}
{114}{}{The door is locked.}
{115}{}{You haven't even left a mark on the door.}
{116}{}{The explosion didn't even leave a scratch on the door.}
{117}{}{Before you can lock the door, you should close it.}

#Attempt to open
{120}{}{You discover that the }
{121}{}{ is rigged with a dangerous trap.}
{122}{}{You discover that the }
{123}{}{ has a trap!}
{124}{}{ turned out to be trapped!}

#Skills
{130}{}{This skill is useless here.}
{131}{}{ locked.}
{132}{}{ has a lock with difficulty level }
{133}{}{.}
{134}{}{ It's a good idea to check for traps.}
{135}{}{You were not able to pick the lock. Try again.}
{136}{}{}
{137}{}{You were not able to pick the lock.}
{138}{}{With such a low skill, you won't learn anything useful.}
{139}{}{The lock is beyond your ability to pick.}

#Broken lock
{140}{}{Alas, this lock is jammed. Permanently.}
{141}{}{This lock is already jammed.}
{142}{}{No point in picking an open lock.}
{143}{}{This lock cannot be broken by brute force.}
{144}{}{It will take *massive* strength to break this lock.}
{145}{}{Using brute force, you break the lock. It won't be locking anything again.}
{148}{}{ turned out to be trapped!}
{149}{}{Weapons should be used in combat mode.}

#Traps
{150}{}{You are unable to detect a trap.}
{151}{}{}
{152}{}{}
{153}{}{You have discovered a trap, but cannot disarm it.}
{154}{}{That was a mistake! Perhaps you'll remember that for next time.}
{155}{}{You have successfully disarmed a primitive trap.}
{156}{}{You have successfully disarmed a trap using an old 12-gauge shell.}
{157}{}{You have successfully disarmed a frag grenade trap.}
{158}{}{You have successfully disarmed the electronic trap.}
{159}{}{You have successfully disabled the alarm.}

#Items
{160}{}{Not likely to help with the broken lock.}
{161}{}{Lockpicks are inserted. Now it will be easier for you to pick this lock.}
{162}{}{The lock already has the required number of lockpicks.}
{163}{}{The electronic decoder isn't suitable for picking mechanical locks.}
{164}{}{This lock needs a different key.}
{165}{}{This key doesn't work. It's unlikely you will find the key to this lock at all.}
{166}{}{The explosion blows the door to pieces.}
{167}{}{A lockpick won't help with picking electronic locks.}
{168}{}{One decoder is already installed.}
{169}{}{The decoder is installed. Now it will be easier for you to pick this lock.}
{170}{}{A shovel won't help here.}
{171}{}{This key doesn't fit.}
