{110}{}{You haven't learned anything new yet. Maybe you should explore more methodically.}
{111}{}{}
{112}{}{Systematic analysis isn't your strong suit.}
{113}{}{This can't be repaired.}
{114}{}{To study the object, you should use scientific methods.}
{115}{}{What is THIS doing here?}

# One location is allocated 20 lines.
# Each object is given 2 adjacent lines:
#   - the first for the log message
#   - the second for the remark above the character (if not needed, put spaces, otherwise the character will say Error)

#Villa
{200}{}{This is an old birthing chair. You were born in it.}
{201}{}{Not the most pleasant memories}
{202}{}{This ancient equipment doesn't function, as it's rusted through from the damp.}
{203}{}{Doesn't work. And it never will.}
{204}{}{This computer is so old that its parts are rusted through. It hasn't been used for at least forty years. Not surprising for the Villa.}
{205}{}{Padre never told me...}
{206}{}{You conclude that the symbol depicts a winged creature emerging from the fire. But this isn't certain.}
{207}{}{This symbol was left by raiders}
{208}{}{One of the achievements of local engineering. You were never allowed near it as a child, as all the seats were taken.}
{209}{}{It seems some of our ceramics were sold to neighboring settlements}

#Jackals
{210}{}{}
{211}{}{}
{212}{}{}
{213}{}{}
{214}{}{It's probably a nuclear ramjet engine. Too complex a technology for the modern world.}
{215}{}{It'll take a LOT of work to get this moving on its own}
{216}{}{This equipment controlled the supply of a complex gas mixture to the sarcophagi. It was recently shut down automatically by an internal timer.}
{217}{}{Wow, they must have been asleep for decades}
{218}{}{This structure of boards and skulls likely depicts something from the pre-war era. The number 15 is painted on a piece of hide.}
{219}{}{An echo of ancient times, lost to meaning}

#Flagstaff
{220}{}{Looks like surgical operations are occasionally performed here, and the basement hides the screams of the patients.}
{221}{}{And no hygiene...}
{222}{}{The information on the stand doesn't match reality. Looks like this mine is from pre-war times.}
{223}{}{This stand is older than the colony}
{224}{}{This ancient poster urges women to work hard during the war.}
{225}{}{And in the Villa, they work without any urging}
{226}{}{The sign reads: "Museum of Northern Arizona". Below, it says: "Museum, shop, and library".}
{227}{}{I don't know what a "museum" is.}
{228}{}{While studying the ancient exhibit, you unexpectedly find a forgotten grenade at its base.}
{229}{}{And what's this doing here?}

#San Brahmin
{230}{}{This exhibit evokes both awe and fear.}
{231}{}{Good thing such monsters no longer exist in the world... probably.}
{232}{}{Here are the titles of movies. You've never seen them. You haven't seen any movies at all.}
{233}{}{ }

#Phoenix
{240}{}{Hidden surveillance cameras allow Aaron to monitor the cathedral premises.}
{241}{}{Looks like the Lord of Phoenix is obsessed with security and control}
{242}{}{After studying the winning statistics, you've come to some conclusions. Playing roulette will now be 15% more successful.}
{243}{}{Heh, sometimes wear and tear can be turned to your advantage}
{244}{}{You've learned the recipe for making wasteland tequila.}
{245}{}{Now it's clear why no one but the casino deals with it}
{246}{}{You've already learned the recipe for making wasteland tequila.}
{247}{}{I've had enough of these numbers}
{248}{}{This statue has no inscriptions left. It's anyone's guess why it was placed here.}
{249}{}{Looks quite... fitting. For these ruins.}

#Tucson, Vault 27
{250}{}{This computer was made by Tinsmiths from various components. Surprisingly, it works perfectly.}
{251}{}{Looks like the Tinsmiths have outdone themselves}
{252}{}{Blackened gold bars. They say they used to be of high value, but now no one will pay even a single cap for them.}
{253}{}{This gold has long since devalued}
{254}{}{Among the payment orders, you find data on slaves. Mostly, they're transported to Two-Sun.}
{255}{}{Perhaps it's worth visiting Two-Sun to checkout these slaves}
{256}{}{On the back of the painting, you find some code.}
{257}{}{Hmm, what do these numbers mean?}
{258}{}{These mercenaries died from a powerful explosion. But one of them died from a shot to the head with a 10mm bullet.}
{259}{}{Not something to stare at for long}

#Rangers, Quartzsite
{260}{}{This ancient sign shows the distance to the dam. A painted inscription on top reads: "Rangers' Territory".}
{261}{}{Up the road is Parker Dam - the Rangers' citadel}
{262}{}{You carefully studied the Rangers' maps. Traveling around the area will now be much easier.}
{263}{}{Wow, the cartographer really knows his stuff.}
{264}{}{The cartographer won't let you look through his maps.}
{265}{}{   }
{266}{}{Rangers rely more on themselves than on technology, even with such tech right under their noses.}
{267}{}{This computer hasn't been used in a long time}
{268}{}{"Warning! Restricted area. All persons in this area are subject to Federal law protecting this site."}
{269}{}{Looks like this sign has been here since pre-war times}
{270}{}{A homemade "reactor" that locals unsuccessfully tried to build. The failure resulted in an accident and radiation contamination of the area.}
{271}{}{So this is what happened here}
{272}{}{Visitor information: "Quartzsite, founded in 1879, elevation 879".}
{273}{}{Probably a lot of people used to pass through this town}
{274}{}{"Parker Dam, founded in 1934-1938, reconstructed in 2055".}
{275}{}{That's a *very* old structure}
{276}{}{An old road sign. A Ranger mark is painted on it.}
{277}{}{This mark means the settlement is under Rangers' protection}
{278}{}{}
{279}{}{}

#Other Locations
{280}{}{"Monument to the victims of the 2051 annexation and border unrest".}
{281}{}{So the US did annex Mexico after all}
{282}{}{Security system is disabled.}
{283}{}{How about that, rusty tin can?}
{284}{}{"Attention, traveler! No alcohol, drugs, or open carry of weapons allowed here. Theft of crops is punishable by death. A curfew is in effect at night."}
{285}{}{Strict rules around here}
{286}{}{The guest log ends in 2077.}
{287}{}{Nothing interesting}
{288}{}{This painting is over a hundred years old. It's amazing it survived at all.}
{289}{}{Was this really painted by hand?}

#Puerto
{290}{}{Brotherhood of Steel radio frequencies copied.}
{291}{}{Great, now I can eavesdrop on Brotherhood patrols}
{292}{}{This trap door leads down. What a surprise.}
{293}{}{?}
{294}{}{You carefully studied the Brotherhood of Steel's maps. Traveling around the area will now be much easier.}
{295}{}{Brotherhood scouts earn their rations well}
{296}{}{You unsuccessfully try to find the Villa. But the vastness of the continent amazes you.}
{297}{}{Is the world really this big?}
{298}{}{This welcome sign is written in two languages - Spanish and English.}
{299}{}{This place must have been quite charming once...}

{300}{}{This equipment is used to communicate with Puerto Penasco.}
{301}{}{Standard radio transmitter.}
{302}{}{This equipment used to be used to communicate with Puerto Penasco.}
{303}{}{Standard radio transmitter.}

#Dayglow
{310}{}{Religious meetings were held in this hall.}
{311}{}{"... And we shall call ourselves the Followers of the Apocalypse. To cleanse the world of the sins of our ancestors."}
{312}{}{Scientific conferences were held in this hall.}
{313}{}{"... And we must use our knowledge to restore civilization after the nuclear war."}
{314}{}{Route #8 leads north to Old Town. Route #805 leads east to the dam.}
{315}{}{According to these signs, there's a fork in the road ahead.}
{316}{}{Among the trash, you find a scrap of paper with six numbers and decide to remember them.}
{317}{}{This looks like some kind of code.}
{318}{}{You see a television working for the first time. The sight is rather... disappointing.}
{319}{}{Is this noise what people used to watch in the past?}

