{110}{}{Components for various types of ammunition are gathered here. With the right skills, you could craft something useful.}
{111}{}{All that's left here is useless trash.}
{112}{}{With your skill level, you'll just ruin the materials.}
{113}{}{The ammo is crafted and in your backpack.}
{114}{}{You have made: }
{115}{}{.}
{116}{}{You've crafted some fuel.}

{200}{}{Components for various types of ammunition are gathered here. You'll need to choose wisely, as supplies of lead and gunpowder are limited.}
{201}{}{Not now.}
{202}{}{Other.}
{203}{}{Back.}
{204}{}{.}
{205}{}{Enough components for }
{206}{}{ rounds (based on your current repair skills).}
{207}{}{Just what I needed. Now let's get to work!}
{208}{}{Set aside.}
