#Welcome messages in the log upon first entering the map
#   The number is determined as 100+the map number in MAPS.TXT
#   If no message is needed, leave the line empty (without any characters or spaces).
#   Do not delete empty lines between 100-150! Otherwise, an error will appear in the log during the game.
{100}{}{}
{101}{}{}
{102}{}{}
{103}{}{}
{104}{}{}
{105}{}{}
{106}{}{}
{107}{}{}
{108}{}{}
{109}{}{}
{110}{}{}
{111}{}{}
{112}{}{}
{113}{}{}
{114}{}{}
{115}{}{}
{116}{}{}
{117}{}{}
{118}{}{}
{119}{}{}
{120}{}{}
{121}{}{After a long journey, you return to your home village. But instead of a warm greeting, you are met with mournful, tense silence.}
{122}{}{}
{123}{}{You climb down into the cellars. It reeks of dampness and rat droppings.}
{124}{}{}
{125}{}{You have arrived at Flagstaff Colony. It's surprisingly bustling with activity.}
{126}{}{This is a garrison and prison camp for the colony. Behind bars, you find criminals and innocents alike.}
{127}{}{}
{128}{}{Ruins of the old city. The depressing sight of these ruins does little to inspire confidence.}
{129}{}{You are standing at the gates of Garage City. This settlement reeks of rust and rubber a mile away.}
{130}{}{}
{131}{}{}
{132}{}{The path to the nomad camp is suddenly blocked by a military detachment.}
{133}{}{You have entered a tribal camp hidden among the dunes.}
{134}{}{You have arrived at the pens. The lingering smell of cattle can be felt from a mile away.}
{135}{}{You have come to the settlement of the Tinsmiths. Outside the gates, you see unusual buildings made from aircraft parts.}
{136}{}{}
{137}{}{}
{138}{}{This vault seems abandoned, probably for over a hundred years.}
{139}{}{You notice old ruins ahead. Judging by the damp air, the sea must be behind them.}
{140}{}{You find yourself at a small pier.}
{141}{}{For the first time in your life, you are standing on the deck of a destroyer.}
{142}{}{}
{143}{}{The road led you to a dam. The Ranger bastion at its top looks impregnable.}
{144}{}{}
{145}{}{}
{146}{}{You have reached a huge city nestled among ancient ruins. Its gloomy streets greet you with heavy smog.}
{147}{}{}
{148}{}{These slums seem unsafe. You'll need to stay on your guard here.}
{149}{}{An ornate building looms over the city. A crowd of people wander aimlessly in front of it.}
{150}{}{}
{151}{}{}
{152}{}{}
{153}{}{}
{154}{}{}
{155}{}{This place is surrounded by impenetrable ruins. No wonder it's hard to find.}
{156}{}{The premises of the vault appear deserted. It seems like everything useful was taken out a long time ago.}
{157}{}{You have arrived in the small town of Casa Grande, located in the middle of a caravan route.}
{158}{}{}
{159}{}{}
{160}{}{This place holds memories of all the horrors of the Great War.}
{161}{}{Before you are the charred ruins of a once-great city. Now its streets are overrun with dangerous creatures.}
{162}{}{}
{163}{}{}
{164}{}{You have discovered a small town surrounded by green plantations. There's a lot of life in this oasis.}
{165}{}{In the middle of the desert lies a huge plantation. A landscape so familiar yet so alien to you...}
{166}{}{}
{167}{}{A deserted road leads you to a highwaymen's base. Looks like no one is expecting you here.}
{168}{}{This place looks abandoned, but something about it makes you uneasy.}
{169}{}{What a dismal sight. This place will be uninhabitable for another hundred years.}
{170}{}{You have gone down into the uranium mine.}
{171}{}{A lonely motel looms on the roadside like a ghost.}
{172}{}{The tall old lighthouse on the shore beckons the weary traveler.}
{173}{}{}
{174}{}{}
{175}{}{}
{176}{}{The echo of your footsteps shatters the silence of the cathedral.}
{177}{}{Before you lies a graveyard of ancient and long-forgotten military equipment.}
{178}{}{}
{179}{}{You have reached ancient ruins. No one has lived here for a very long time.}
{180}{}{The banks of the Colorado are overgrown with thorny vegetation, hiding various game.}
{181}{}{}
{182}{}{Time has not been kind to this place -- dilapidated buildings have collapsed, and sandstorms have buried the ruins in sand.}
{183}{}{}
{184}{}{}
{185}{}{}
{186}{}{}
{187}{}{}
{188}{}{You have almost given up on finding any human settlements when a small ranch suddenly appears ahead.}
{189}{}{The desert fades into shabby one-story neighborhoods. It looks like there's a military garrison here.}
{190}{}{After passing through the old quarters, you ascend to the fort on the hill of Cerro de la Campana.}
{191}{}{From the outside, this old school looks rundown and abandoned. Be cautious inside.}
{192}{}{}
{193}{}{}
{194}{}{It seems the rangers check on this water pump from time to time. At least it's working.}
{195}{}{Ahead, you see a surviving building with illuminated windows. A crowd of reavers is milling about in front of it.}
{196}{}{}
{197}{}{}
{198}{}{}
{199}{}{}
{200}{}{}
{201}{}{This place is eerily silent, yet the air is thick with tension.}
{202}{}{}
{203}{}{}
{204}{}{}
{205}{}{}
{206}{}{}
{207}{}{}
{208}{}{}
{209}{}{}
{210}{}{The warehouse building is heavily damaged by the shock wave. Most of the goods are probably unusable.}
{211}{}{}
{212}{}{Work at this concrete plant appears to have been abruptly halted.}
{213}{}{}
{214}{}{}
{215}{}{}
{216}{}{}
{217}{}{}
{218}{}{}
{219}{}{}
{220}{}{Looks like you stumbled into someone's party by accident.}
{221}{}{An ancient monument stands before you, seemingly untouched for decades or more.}
{222}{}{You find yourself in an ancient cemetery, so overgrown with desert plants that it's barely recognizable.}
{223}{}{}
{224}{}{}
{225}{}{}
{226}{}{}
{227}{}{}
{228}{}{}
{229}{}{}
{230}{}{}
{231}{}{}
{232}{}{}
{233}{}{}
{234}{}{}
{235}{}{}
{236}{}{}
{237}{}{}
{238}{}{}
{239}{}{}
{240}{}{You've descended into a cave. If you didn't know the exact coordinates, you'd likely never have found it in the middle of Otay Park.}
{241}{}{}
{242}{}{}
{243}{}{}
{244}{}{You have entered a radioactive area.}
{245}{}{}
{246}{}{}
{247}{}{}
{248}{}{You have entered a radioactive area.}
{249}{}{}
{250}{}{Before you stretches a barren wasteland.}

{500}{}{You get }
{501}{}{ experience for surviving the Villa cellars.}
{502}{}{Prisoners have escaped from the prison camp!}
{503}{}{You receive }
{504}{}{ experience for destroying the Cathedral of the Holy Fire.}
{505}{}{There are }
{506}{}{ seconds left until the explosion.}
{507}{}{You receive }
{508}{}{ experience for destroying the Ranger Base.}
{509}{}{ experience for destroying the Brotherhood of Steel fort.}
{510}{}{You illegally entered the Brotherhood of Steel headquarters, bypassing the sentries at the ramp.}
{511}{}{Now, the main thing is not to burn yourself.}
{512}{}{You receive }
{513}{}{ experience for crossing the border.}
{514}{}{ experience for successfully landing on Coronado Island.}
{515}{}{ experience for the final destruction of Coronado Island.}
{516}{}{ experience for freeing Coronado Island from military control.}

