#include "..\headers\define.h"
//--------------------- Заложник Пауль

#define NAME                            SCRIPT_EncMtntC
#define TOWN_REP_VAR                    GVAR_TOWN_REP_PUERTO  // привязка к репутации (-1, если не нужно)

#define NUM_TEAM                        TEAM_BROTHERS_STEEL   // группа, к которой принадлежит персонаж (-1 если нужно оставить Team, заданный в редакторе)
#define NUM_AI                          AI_BOS_CAVALER        // AI персонажа (-1 если нужно оставить AI, заданный в редакторе)
#define KILL_SLAVA                      SLAVA_KILL_NEITRAL    // слава за убийство этого персонажа (SLAVA_KILL_GOOD, SLAVA_KILL_BAD, SLAVA_KILL_NEITRAL, SLAVA_KILL_CHILD)
#define KILL_TOWN_REP                   REP_KILL_NEITRAL      // репутация за убийство этого персонажа (REP_KILL_GOOD, REP_KILL_BAD, REP_KILL_NEITRAL, REP_KILL_CRITICAL для враждебности всего поселения, REP_KILL_CHILD)
#define KILL_FRAC_REP                   FRAC_NON              // принадлежность определенной фракции (-1, если не нужно)

#define FLAG_STEAL                      20 // Нижний порог навыка для кражи (для торговцев 200, для животных 300)
#define FLAG_ALCOHOL                    1  // Примет ли алкоголь от ГГ: 0 - принимает, 1 - не принимает
#define FLAG_FOOD                       0  // Примет ли пищу от ГГ: 0 - принимает, 1 - не принимает

//---------------------

procedure start;
procedure map_enter_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure timed_event_p_proc;
procedure critter_p_proc;
procedure push_p_proc;
procedure use_obj_on_p_proc;
procedure use_skill_on_p_proc;
procedure pickup_p_proc;
procedure combat_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure talk_p_proc;

procedure Node998;
procedure Node999;
procedure NodeStartDialog;
procedure NodeFstDialog;
procedure NodeFstDialog002;
procedure NodeFstDialog003;
procedure NodeFstDialog004;
procedure NodeFstDialog005;
procedure NodeFstDialog005b;
procedure NodeFstDialog006;
procedure NodeFstDialog007;
procedure NodeSndDialog;
procedure NodeAnswer101;
procedure NodeAnswer102;
procedure NodeAnswer103;
procedure NodeAnswer200;
procedure NodeAnswer201;
procedure NodeEndDialog;
procedure NodeEndDialog2;
procedure NodeEndDialog3;

//---------------------

#define LVAR_Party_Status               (6) // 1 бежит из крепости, 2 покинул карту

//---------------------



procedure start begin
end

procedure map_enter_p_proc begin
   if (is_loading_game == false) then begin
       set_start_home
       set_obj_visibility(self_obj, 0);
       if ((local_var(LVAR_Party_Status) != 0) or (global_var(GVAR_PUERTO_STATUS_PAUL) != 0)) then begin
       set_obj_visibility(self_obj, 1);
       end
   end
end

procedure look_at_p_proc begin
   lookProcMsg
end

procedure description_p_proc begin
   dsrptProcMsg
end

procedure timed_event_p_proc begin
   // Таймер за номером 1 рарезервирован под перемещение персонажа по локации
   // Таймер за номером 2 рарезервирован под всплывающие реплики
   if (fixed_param == 1) then begin
       //timer_move_to_home
   end
   if (fixed_param == 2) then begin
       //timer_float_reply(110,119)
   end
   if (fixed_param == 3) then begin
       self_attack_dude;
   end
end

procedure critter_p_proc begin
   set_critter_options(0,0) //условие нападения (0 личная вражда, 1 вражда клановая, 2 всегда), разворот к ГГ
   //--- Следует за ГГ
   if (local_var(LVAR_Party_Status) > 0) then begin
   partyRunToDude
   end
end

procedure push_p_proc begin
end

procedure use_skill_on_p_proc begin
   skillUseSteal
   skillUseFAid
end

procedure pickup_p_proc begin
   pickupProcCritter
end

procedure use_obj_on_p_proc begin
   UsedItemToCrit_Proc
end

procedure combat_p_proc begin
   effectAttak(0,0,1,1,1) //отравление min, облучение min, травма ног %, травма рук %, травма глаз %
end

procedure damage_p_proc begin
   set_damage_dude
end

procedure destroy_p_proc begin
   set_global_var(GVAR_PUERTO_STATUS_PAUL, -1);
   kill_critter_BoS_item
   kill_critter_opt
end

procedure talk_p_proc begin
   setReaction(0) // Attitude towards the main character (1 - positive character, -1 negative, 0 neutral)
   dialog_proc(0,0,NodeStartDialog,HEAD_ENCOUNTER_PAUL,BACKGROUND_WASTELND)
end

procedure Node998 begin
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,NUM_TEAM);
   set_local_var(LVAR_Party_Status,0);
   add_timer_event(self_obj, 1, 3);
   set_enemy_dude;
end

procedure Node999 begin
end

procedure NodeStartDialog begin
   if (local_var(LVAR_Party_Status) != 0) then begin
   call NodeEndDialog;
   end
   else if (bitDialog(bit_1) == 0) then begin
   call NodeFstDialog;
   end
   else begin
   call NodeSndDialog;
   end
end

//--- FIRST DIALOGUE

procedure NodeFstDialog begin
   Reply(200)
   NAnswer(201,4,NodeFstDialog002)
   NAnswer(202,4,Node999)
   NAnswer(203,-3,NodeFstDialog002)
end

procedure NodeFstDialog002 begin
   bitDialogExp(bit_1,0)
   Reply(220)
   NAnswer(221,4,NodeFstDialog003)
   BAnswer(222,4,NodeFstDialog003)
   NAnswer(223,-3,NodeFstDialog003)
end

procedure NodeFstDialog003 begin
   Reply(224)
   if ((getQuest(GVAR_PUERTO_BOS_DESTROY) >= qEnd) or town_rep_is_vilified) then begin
   zBAnswer(240,4,Node998)
   BAnswer(241,-3,Node998)
   end
   if (town_known(AREA_PUERTO_DESTROY) >= MARK_STATE_KNOWN) then begin
   GAnswer(239,4,NodeFstDialog005)
   end
   else if (town_known(AREA_PUERTO_STEEL) >= MARK_STATE_KNOWN) then begin
   GAnswer(230,4,NodeFstDialog005)
   end
   if (global_var(GVAR_TITUL_BOS)>0) then begin
   zGAnswer(243,4,NodeFstDialog005b)
   end
   NAnswer(225,4,NodeFstDialog004)
   NAnswer(226,-3,NodeFstDialog004)
end

procedure NodeFstDialog004 begin
   Reply(227)
   NAnswer(228,4,NodeFstDialog006)
   NAnswer(229,-3,NodeFstDialog006)
end

procedure NodeFstDialog005 begin
   Reply(231)
   NAnswer(228,4,NodeFstDialog006)
   NAnswer(229,-3,NodeFstDialog006)
end

procedure NodeFstDialog005b begin
   bitDialogExp(bit_2,0)
   Reply(244)
   NAnswer(228,4,NodeFstDialog006)
   NAnswer(229,-3,NodeFstDialog006)
end

procedure NodeFstDialog006 begin
   Reply(232)
   NAnswer(233,4,NodeFstDialog007)
   NAnswer(234,-3,NodeFstDialog007)
end

procedure NodeFstDialog007 begin
   Reply(235)

   if (map_var(MVAR_ENC_SMUTANT_REACTOR)>0) then begin
   GAnswer(304,4,NodeAnswer200)
   GAnswer(303,-3,NodeAnswer200)
   end
   else if (map_var(MVAR_ENC_SMUTANT_DEAD)>=8) then begin
   GAnswer(314,4,NodeAnswer201)
   GAnswer(311,-3,NodeAnswer201)
   end

   NAnswer(238,4,NodeSndDialog)
   NAnswer(236,4,Node999)
   NAnswer(237,-3,Node999)
end

//--- REPEAT DIALOGUE

procedure NodeSndDialog begin
   if (bitDialog(bit_2) != 0) then begin
   zReply(215)
   end
   else begin
   Reply(random(210,214))
   end

   NAnswer(250,4,NodeAnswer101)
   NAnswer(260,4,NodeAnswer103)

   if (map_var(MVAR_ENC_SMUTANT_REACTOR)>0) then begin
   GAnswer(300,4,NodeAnswer200)
   GAnswer(303,-3,NodeAnswer200)
   end
   else if (map_var(MVAR_ENC_SMUTANT_DEAD)>=8) then begin
   GAnswer(310,4,NodeAnswer201)
   GAnswer(311,-3,NodeAnswer201)
   end

   if ((getQuest(GVAR_PUERTO_BOS_DESTROY) >= qEnd) or town_rep_is_vilified) then begin
   zBAnswer(242,4,Node998)
   BAnswer(241,-3,Node998)
   end
   NAnswer(219,4,Node999)
   NAnswer(218,-3,Node999)
end

//---

procedure NodeAnswer101 begin
   Reply(251)
   NAnswer(252,4,NodeAnswer102)
   NAnswer(253,-3,NodeAnswer102)
end

procedure NodeAnswer102 begin
   Reply(254)
   NAnswer(255,4,NodeSndDialog)
   NAnswer(256,-3,NodeSndDialog)
end

procedure NodeAnswer103 begin
   Reply(261)
   NAnswer(255,4,NodeSndDialog)
   NAnswer(256,-3,NodeSndDialog)
end

//---

procedure NodeAnswer200 begin
   inc_local_var(LVAR_Party_Status);
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_PLAYER);
   rm_timer_event(self_obj);
   Reply(301)
   NAnswer(302,4,Node999)
end

procedure NodeAnswer201 begin
   inc_local_var(LVAR_Party_Status);
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_PLAYER);
   rm_timer_event(self_obj);
   Reply(312)
   NAnswer(313,4,Node999)
end

//---

procedure NodeEndDialog begin
   Reply(320)
   if ((cur_map_index != MAP_SPECIAL_ARMY) or (self_elevation == 0)) then begin
   GAnswer(322,4,NodeEndDialog2)
   end
   NAnswer(321,4,Node999)
   NAnswer(323,-3,Node999)
end

procedure NodeEndDialog2 begin
   Reply(324)
   NAnswer(325,4,NodeEndDialog3)
   NAnswer(326,-3,NodeEndDialog3)
end

procedure NodeEndDialog3 begin
   set_local_var(LVAR_Party_Status,-1);
   set_global_var(GVAR_PUERTO_STATUS_PAUL, 1);
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,NUM_TEAM);
   exp_add(350);
   set_REP(5)
   set_SLAVA(5)
   set_obj_visibility(self_obj, 1);

   call Node999;
end
