#include "..\headers\define.h"
//---------------------

#define NAME                            SCRIPT_SCPatrul
#define TOWN_REP_VAR                    GVAR_TOWN_REP_PUERTO // привязка к репутации (-1, если не нужно)

#define NUM_TEAM                        TEAM_BROTHERS_STEEL   // группа, к которой принадлежит персонаж (-1 если нужно оставить Team, заданный в редакторе)
#define NUM_AI                          AI_BOS_PALADIN         // AI персонажа (-1 если нужно оставить AI, заданный в редакторе)
#define KILL_SLAVA                      SLAVA_KILL_GOOD       // слава за убийство этого персонажа (SLAVA_KILL_GOOD, SLAVA_KILL_BAD, SLAVA_KILL_NEITRAL, SLAVA_KILL_CHILD)
#define KILL_TOWN_REP                   REP_KILL_CRITICAL     // репутация за убийство этого персонажа (-100 для враждебности всего поселения)
#define KILL_FRAC_REP                   FRAC_BOS              // принадлежность определенной фракции (-1, если не нужно)

#define FLAG_STEAL                      100 // Нижний порог навыка для кражи (для торговцев 200, для животных 300)
#define FLAG_ALCOHOL                    1  // Примет ли алкоголь от ГГ: 0 - принимает, 1 - не принимает
#define FLAG_FOOD                       1  // Примет ли пищу от ГГ: 0 - принимает, 1 - не принимает

//---------------------

procedure start;
procedure map_enter_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure timed_event_p_proc;
procedure critter_p_proc;
procedure use_obj_on_p_proc;
procedure use_skill_on_p_proc;
procedure pickup_p_proc;
procedure combat_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure talk_p_proc;

procedure Node998;
procedure Node999;
procedure NodeStartDialog;
procedure NodeFstDialog;
procedure NodeFstDialog2;
procedure NodeFstDialog3;
procedure NodeFstDialog4;
procedure NodeFstDialog5;
procedure NodeFstDialog6;
procedure NodeFstDialog7;
procedure NodeSndDialog;
procedure NodeAnswer100;
procedure NodeAnswer101;
procedure NodeAnswer102;
procedure NodeQst100;
procedure NodeQst101;
procedure NodeQst200;
procedure NodeQst201;
procedure NodeQst202;
procedure NodeQst203;
procedure NodeQst204;
procedure NodeQst205;
procedure NodeQst300;
procedure NodeQst301;
procedure NodeQst302;
procedure NodeQst303;
procedure NodeQst304;
procedure NodeQst305;
procedure NodeQst400;
procedure NodeQst401;
procedure NodeQst402;
procedure NodeQst403;
procedure NodeQst404;
procedure NodeQst405;
procedure NodeQst406;
procedure NodeQst407;
procedure NodeQst408;
procedure NodeQst500;
procedure NodeQst501;
procedure NodeQst502;
procedure NodeQst503;
procedure NodeQst504;
procedure NodeQst505;
procedure NodeQst506;
procedure NodeQst507;
procedure NodeQst508;
procedure NodeQst509;
procedure NodeQst510;
procedure NodeQst600;
procedure NodeQst601;
procedure NodeQst602;
procedure NodeQst603;
procedure NodeQst604;
procedure NodeQst605;
procedure NodeQst606;

//---------------------

//#define LVAR_Flag_A                     (6) // отвечает за ...

import variable box_stop_use;

//---------------------



procedure start begin
end

procedure map_enter_p_proc begin
   if (is_loading_game == false) then begin
       set_start_home
   end
end

procedure look_at_p_proc begin
   lookProcMsg
end

procedure description_p_proc begin
   dsrptProcMsg
end

procedure timed_event_p_proc begin
   // Таймер за номером 1 рарезервирован под перемещение персонажа по локации
   // Таймер за номером 2 рарезервирован под всплывающие реплики
   if (fixed_param == 1) then begin
       timer_move_to_home
   end
   if (fixed_param == 2) then begin
       //timer_float_reply(110,119)
   end
end

procedure critter_p_proc begin
   set_using_stop // привязка хозяина и объекта (удалить, если не нужно)
   set_critter_options(1,0) //условие нападения (0 личная вражда, 1 вражда клановая, 2 всегда), разворот к ГГ
   if self_enemy_dude then begin
   BarklyAttakDude
   end
end

procedure use_skill_on_p_proc begin
   skillUseSteal
   skillUseFAid
end

procedure pickup_p_proc begin
   pickupProcCritter
end

procedure use_obj_on_p_proc begin
   UsedItemToCrit_Proc
end

procedure combat_p_proc begin
   effectAttak(0,0,3,3,3) //отравление min, облучение min, травма ног %, травма рук %, травма глаз %
end

procedure damage_p_proc begin
   if (source_obj == dude_obj) then begin
   BarklyAttakDude
   end
   set_damage_dude
end

procedure destroy_p_proc begin
   //mark_area_known(MARK_TYPE_TOWN, AREA_BOS_CAMPS, MARK_STATE_INVISIBLE);
   set_map_var(MVAR_PUERTO_PATRLBOSS_DEAD, -1);
   set_map_var(MVAR_PUERTO_JECK_DIALOG_FLAG, -1);
   if (getQuest(GVAR_PUERTO_QST_BANDITS_PIP) == qStart) then begin
   setQuest(GVAR_PUERTO_QST_BANDITS_PIP,qStop);
   end
   if (getQuest(GVAR_PUERTO_QST_INFERNO) <= qStart) then begin
   setQuest(GVAR_PUERTO_QST_INFERNO,qStop);
   end
   if (getQuest(GVAR_PUERTO_QST_HERMOSILLO) <= qStart) then begin
   setQuest(GVAR_PUERTO_QST_HERMOSILLO,qStop);
   end
   setQuest(GVAR_PUERTO_QST_SANFELIPE_PIP,qStop);
   kill_critter_opt
   kill_critter_BoS_item
end

procedure talk_p_proc begin
   if (global_var(GVAR_PUERTO_BOS_DESTROY_TIMER) != 0) then begin
   floater(dude_obj,102,COLOR_MSG_GREY);
   floater(self_obj,103,COLOR_MSG_NORMAL);
   end
   else begin
   setReaction(0) // Отношение к ГГ (1 - персонаж положительный, -1 отрицательный, 0 нейтральный)

   fracReaction(GVAR_TITUL_ARIZONA_RANGER,-40) // Поправка к отношению за принадлежность к фракциям
   fracReaction(GVAR_TITUL_BOS,25) // Поправка к отношению за принадлежность к фракциям
   fracReaction(GVAR_TITUL_BOS_TRAITOR,-90) // Поправка к отношению за принадлежность к фракциям
   fracReaction(GVAR_TITUL_DUDE_IS_SLAVE,-20) // Поправка к отношению за принадлежность к фракциям

   dialog_proc(0,0,NodeStartDialog,-1,-1)
   end
end

procedure Node998 begin
   set_enemy_dude;
end

procedure Node999 begin
end

procedure NodeStartDialog begin
   if (getQuest(GVAR_PUERTO_QST_INFERNO) != qZero) then begin
   bitDialogExp(bit_1,0)
   bitDialogExp(bit_2,0)
   end

   if ((getQuest(GVAR_PUERTO_QST_INFERNO) <= qStart) and (armor_pid_dude_var == PID_ARMOR_POWER_A)) then begin
   call NodeQst204;
   end
   else if ((global_var(GVAR_TITUL_REBIRTH) > 0) and (bitDialog(bit_3) == 0)) then begin
   call NodeFstDialog2;
   end
   else if (bitDialog(bit_1) == 0) then begin
   call NodeFstDialog;
   end
   else if (bitDialog(bit_2) == 0) then begin
   call NodeFstDialog5;
   end
   else begin
   call NodeSndDialog;
   end
end

//--- ПЕРВЫЙ ДИАЛОГ

procedure NodeFstDialog begin
   bitDialogExp(bit_1,0)
   Reply(200)
   NAnswer(201,0,NodeFstDialog3)
end

procedure NodeFstDialog2 begin
   bitDialogExp(bit_3,0)
   Reply(225)
   NAnswer(226,0,NodeStartDialog)
   BAnswer(227,0,NodeStartDialog)
end

procedure NodeFstDialog3 begin
   Reply(208)
   if (getQuest(GVAR_VILLA_ALLIANCE_PIP) >= qStart) then begin
   NAnswer(209,0,NodeFstDialog4)
   end
   else begin
   NAnswer(210,0,NodeFstDialog4)
   end
end

procedure NodeFstDialog4 begin
   Reply(211)
   NAnswer(213,0,NodeFstDialog6)
   BAnswer(212,0,Node998)
   NAnswer(214,0,Node999)
end

procedure NodeFstDialog5 begin
   Reply(215)
   NAnswer(213,0,NodeFstDialog6)
   BAnswer(212,0,Node998)
   NAnswer(214,0,Node999)
end

procedure NodeFstDialog6 begin
   Reply(216)
   NAnswer(217,0,NodeFstDialog7)
end

procedure NodeFstDialog7 begin
   bitDialogExp(bit_2,0)
   zReply(218)
   NAnswer(219,0,NodeSndDialog)
end

//--- ПОВТОРНЫЙ ДИАЛОГ

procedure NodeSndDialog begin
   if (global_var(GVAR_TITUL_BOS) != 0) then begin
      if (global_var(GVAR_TITUL_BOS_SCRIBE) != 0) then begin
      Reply(mstr(235)+dude_name+mstr(236))
      end
      else if (global_var(GVAR_TITUL_BOS_CAVALER) != 0) then begin
      Reply(mstr(234)+dude_name+mstr(236))
      end
      else if (global_var(GVAR_TITUL_BOS_PALADIN) != 0) then begin
      Reply(mstr(233)+dude_name+mstr(236))
      end
      else if (global_var(GVAR_TITUL_BOS_SCOUT) != 0) then begin
      Reply(mstr(232)+dude_name+mstr(236))
      end
      else if dude_is_female then begin
      Reply(mstr(1237)+dude_name+mstr(236))
      end
      else begin
      Reply(mstr(237)+dude_name+mstr(236))
      end
   end
   else begin
      Reply(230)
   end

   //--- Поиск пропавшего отряда

   if (getQuest(GVAR_PUERTO_QST_INFERNO) == qZero) then begin
      NAnswer(258,0,NodeQst100)
   end
   if (getQuest(GVAR_PUERTO_QST_INFERNO) == qStart) then begin
      NAnswer(240,0,NodeQst200)
      if ((getQuest(GVAR_INF_QST_PALADIN_A) >= qEnd) or (global_var(GVAR_INF_STATUS_PALADIN)>0)) then begin
      GAnswer(247,0,NodeQst202)
      end
      else if ((getQuest(GVAR_INF_QST_PALADIN_A) <= qStop) or (global_var(GVAR_INF_STATUS_PALADIN)<0)) then begin
      GAnswer(247,0,NodeQst202)
      end
   end

   //--- Разведка в Эрмосильо
   if (getQuest(GVAR_PUERTO_QST_HERMOSILLO) == qZero) then begin
      if (gvar_bit(GVAR_DIALOGS_FLAGS_BIT, bit_20) != 0) then begin
      NAnswer(277,0,NodeQst300)
      end
      else begin
      NAnswer(261,0,NodeQst300)
      end
   end

   if (getQuest(GVAR_PUERTO_QST_HERMOSILLO) == qStart) then begin
      if (town_known(AREA_HERMOSILLO) >= MARK_STATE_VISITED) then begin
      NAnswer(270,0,NodeQst303)
      end
   end

   //--- Рейды на бандитские лагеря
   if (getQuest(GVAR_PUERTO_QST_BANDITS_PIP) == qZero) then begin
      if (bitDialog(bit_5) == 0) then begin
         NAnswer(300,0,NodeQst400)
      end
      else if (global_var(GVAR_TITUL_BOS) != 0) then begin
         GAnswer(329,0,NodeQst404)
      end
      else if (getQuest(GVAR_PUERTO_QST_INFERNO) >= qEnd) then begin
         GAnswer(317,0,NodeQst405)
      end
      else if (getQuest(GVAR_PUERTO_QST_HERMOSILLO) >= qEnd) then begin
         GAnswer(318,0,NodeQst405)
      end
      else begin
         GAnswer(329,0,NodeQst402)
      end
   end

   if (getQuest(GVAR_PUERTO_QST_BANDITS_PIP) == qStart) then begin
      if (getQuest(GVAR_PUERTO_QST_BANDITS_CMP) <= -10) then begin
         BAnswer(350,0,NodeQst507)
      end
      else if (getQuest(GVAR_PUERTO_QST_BANDITS_CMP) <= qStop) then begin
         BAnswer(354,0,NodeQst508)
      end
      else if (getQuest(GVAR_PUERTO_QST_BANDITS_CMP) == qEnd) then begin
         NAnswer(330,0,NodeQst500)
      end
      if (global_var(GVAR_PUERTO_SKLAD_DOPUSK) == 0) then begin
         NAnswer(360,0,NodeQst510)
      end
   end

   //--- Разведка в Сан-Фелипе
   if (getQuest(GVAR_PUERTO_QST_SANFELIPE_PIP) == qZero) then begin
      NAnswer(370,0,NodeQst600)
   end
   if (getQuest(GVAR_PUERTO_QST_SANFELIPE_PIP) == qStart) then begin
      NAnswer(373,0,NodeQst601)
   end

   //--- Увольнительный на берег
   if (getQuest(GVAR_PUERTO_QST_FAREWELL) == qStart) then begin
      NAnswer(280,0,NodeAnswer100)
   end

   NAnswer(231,0,Node999)
end

procedure NodeAnswer100 begin
   Reply(281)
   NAnswerReaction(282,0,NodeAnswer102,75,282,NodeAnswer101)
   /*
   if (getQuest(GVAR_PUERTO_QST_BANDITS_PIP) >= qEnd) then begin
   NAnswer(282,0,NodeAnswer102)
   end
   else begin
   NAnswerReaction(282,0,NodeAnswer102,75,282,NodeAnswer101)
   end
   */
end

procedure NodeAnswer101 begin
   if (global_var(GVAR_TITUL_BOS)>0) then begin
   Reply(285)
   NAnswer(286,0,Node999)
   end
   else begin
   zReply(283)
   zNAnswer(284,0,Node999)
   end
end

procedure NodeAnswer102 begin
   setQuest(GVAR_PUERTO_QST_FAREWELL,qEnd);
   Reply(287)
   NAnswer(288,0,Node999)
end

//--- КВЕСТЫ

procedure NodeQst100 begin
   Reply(220)
   NAnswer(221,0,NodeQst101)
end

procedure NodeQst101 begin
   bitDialogExp(bit_2,0)
   mark_on_map(AREA_INFIERNO)
   setQuest(GVAR_PUERTO_QST_INFERNO,qStart);
   Reply(222)
   NAnswer(223,0,Node999)
   BAnswer(224,0,Node999)
end

procedure NodeQst200 begin
   Reply(241)
   NAnswer(242,0,NodeQst201)
end

procedure NodeQst201 begin
   Reply(243)
   NAnswer(246,0,NodeSndDialog)
   NAnswer(244,0,Node999)
   BAnswer(245,0,Node999)
end

procedure NodeQst202 begin
   PLAY_FADE
   setQuest(GVAR_PUERTO_QST_INFERNO,qEnd);
   exp_add(500);
   setBonusReaction(25)
   set_REP(5)

   Reply(248)
   NAnswer(249,0,NodeQst203)
end

procedure NodeQst203 begin
   Reply(250)
   NAnswer(251,0,Node999)
   BAnswer(252,0,Node999)
end

procedure NodeQst204 begin
   Reply(253)
   GAnswer(254,0,NodeQst205)
end

procedure NodeQst205 begin
   Reply(255)
   NAnswer(256,0,NodeQst202)
   BAnswer(257,0,Node999)
end

procedure NodeQst300 begin
   if (gvar_bit(GVAR_DIALOGS_FLAGS_BIT, bit_20) != 0) then begin
      Reply(276)
      NAnswer(270,0,NodeQst303)
   end
   else begin
      Reply(262)
      NAnswer(263,0,NodeQst301)
      GAnswer(266,0,NodeQst302)
      if (town_known(AREA_HERMOSILLO) >= MARK_STATE_VISITED) then begin
      NAnswer(270,0,NodeQst303)
      end
      NAnswer(265,0,Node999)
   end
end

procedure NodeQst301 begin
   Reply(264)
   GAnswer(267,0,NodeQst302)
   NAnswer(265,0,Node999)
end

procedure NodeQst302 begin
   setQuest(GVAR_PUERTO_QST_HERMOSILLO,qStart);
   Reply(268)
   NAnswer(263,0,NodeQst301)
   NAnswer(269,0,Node999)
end

procedure NodeQst303 begin
   set_map_var(MVAR_PUERTO_JECK_DIALOG_FLAG, 1);
   zReply(278)

   if (item_amnt(dude_obj,PID_Q_HERMO_INFO_DISK) > 0) then begin
   NAnswer(289,0,NodeQst304)
   end
   if (gvar_bit(GVAR_DIALOGS_FLAGS_BIT, bit_20) != 0) then begin
   //NAnswer(290,0,NodeQst304) - инфа от разведчика
   end

   NAnswer(279,0,Node999)
end

procedure NodeQst304 begin
   PLAY_FADE
   item_remove(dude_obj,PID_Q_HERMO_INFO_DISK,1)
   Reply(271)
   NAnswer(272,0,NodeQst305)
   BAnswer(273,0,NodeQst305)
end

procedure NodeQst305 begin
   setQuest(GVAR_PUERTO_QST_HERMOSILLO,qEnd);
   exp_add(1000);
   setBonusReaction(25)
   set_REP(5)
   item_add(dude_obj,PID_BOOTLE_CAPS,1000)
   Reply(274)
   NAnswer(275,0,Node999)
end

//--- ПАТРУЛЬ (РЕЙДЫ НА ЛАГЕРЯ)

procedure NodeQst400 begin
   Reply(301)
   NAnswer(304,0,NodeQst401)
   NAnswer(303,0,NodeSndDialog)
   NAnswer(302,0,Node999)
end

procedure NodeQst401 begin
   Reply(305)
   GAnswer(307,0,NodeQst402)
   NAnswer(306,0,Node999)
end

procedure NodeQst402 begin
   bitDialogExp(bit_5,0)
   Reply(308)
   GAnswer(310,0,NodeQst403)
   NAnswer(309,0,Node999)
end

procedure NodeQst403 begin
   if (dude_level>=12) then begin
   Reply(312)
   NAnswer(313,0,NodeQst406)
   end
   else begin
   Reply(311)
   NAnswer(309,0,Node999)
   end
end

procedure NodeQst404 begin
   Reply(315)
   NAnswer(316,0,NodeQst406)
end

procedure NodeQst405 begin
   Reply(319)
   NAnswer(320,0,NodeQst406)
end

procedure NodeQst406 begin
   setQuest(GVAR_PUERTO_QST_BANDITS_PIP,qStart);
   mark_on_map(AREA_BOS_CAMPS)
   Reply(321)
   NAnswer(322,0,NodeQst407)
   BAnswer(323,0,NodeQst407)
end

procedure NodeQst407 begin
   Reply(324)
   NAnswer(325,0,NodeQst408)
end

procedure NodeQst408 begin
   Reply(326)
   zNAnswer(327,0,Node999)
   BAnswer(328,0,Node999)
end

procedure NodeQst500 begin
   PLAY_FADE
   if (global_var(GVAR_PUERTO_STATUS_BANDITS) == 0) then begin
   Reply(331)
   NAnswer(332,0,NodeQst501)
   end
   else if (global_var(GVAR_PUERTO_STATUS_BANDITS) == 1) then begin
   Reply(340)
   NAnswer(341,0,NodeQst504)
   end
   else begin
   Reply(346)
   NAnswer(347,0,NodeQst506)
   end
end

procedure NodeQst501 begin
   Reply(333)
   NAnswer(334,0,NodeQst502)
   BAnswer(337,0,NodeQst503)
end

procedure NodeQst502 begin
   inc_global_var(GVAR_PUERTO_STATUS_BANDITS);
   setQuest(GVAR_PUERTO_QST_BANDITS_CMP,qZero);
   setBonusReaction(25)
   set_REP(3)
   exp_add(750);
   wm_area_set_pos(AREA_BOS_CAMPS, 834, 1384); //! уточнить координаты
   mark_area_known(MARK_TYPE_TOWN, AREA_BOS_CAMPS, MARK_STATE_KNOWN);

   Reply(335)
   NAnswer(336,0,Node999)
end

procedure NodeQst503 begin
   setBonusReaction(-5)
   Reply(338)
   NAnswer(339,0,NodeQst502)
end

procedure NodeQst504 begin
   Reply(342)
   NAnswer(343,0,NodeQst505)
end

procedure NodeQst505 begin
   inc_global_var(GVAR_PUERTO_STATUS_BANDITS);
   setQuest(GVAR_PUERTO_QST_BANDITS_CMP,qZero);
   setBonusReaction(35)
   set_REP(5)
   exp_add(1000);
   wm_area_set_pos(AREA_BOS_CAMPS, 984, 1284); //! уточнить координаты
   mark_area_known(MARK_TYPE_TOWN, AREA_BOS_CAMPS, MARK_STATE_KNOWN);

   Reply(344)
   NAnswer(345,0,Node999)
end

procedure NodeQst506 begin
   inc_global_var(GVAR_PUERTO_STATUS_BANDITS);
   setQuest(GVAR_PUERTO_QST_BANDITS_PIP,qEnd);
   setQuest(GVAR_PUERTO_QST_BANDITS_CMP,qZero);
   setBonusReaction(50)
   set_REP(7)
   exp_add(1500);
   //mark_area_known(MARK_TYPE_TOWN, AREA_BOS_CAMPS, MARK_STATE_INVISIBLE);

   Reply(348)
   NAnswer(349,0,Node999)
end

procedure NodeQst507 begin
   setQuest(GVAR_PUERTO_QST_BANDITS_PIP,qStop);
   setQuest(GVAR_PUERTO_QST_BANDITS_CMP,qStop);
   setBonusReaction(-75)
   //mark_area_known(MARK_TYPE_TOWN, AREA_BOS_CAMPS, MARK_STATE_INVISIBLE);

   Reply(351)
   NAnswer(352,0,Node999)
   BAnswer(353,0,Node999)
end

procedure NodeQst508 begin
   Reply(355)
   NAnswer(356,0,NodeQst509)
end

procedure NodeQst509 begin
   setQuest(GVAR_PUERTO_QST_BANDITS_PIP,qStop);
   setQuest(GVAR_PUERTO_QST_BANDITS_CMP,qStop);
   setBonusReaction(-25)
   exp_add(500);
   //mark_area_known(MARK_TYPE_TOWN, AREA_BOS_CAMPS, MARK_STATE_INVISIBLE);

   zReply(357)
   NAnswer(358,0,Node999)
end

procedure NodeQst510 begin
   set_global_var(GVAR_PUERTO_SKLAD_DOPUSK,2);
   Reply(361)
   NAnswer(362,0,Node999)
end

procedure NodeQst600 begin
   setQuest(GVAR_PUERTO_QST_SANFELIPE_PIP,qStart);
   Reply(371)
   NAnswer(372,0,Node999)
end

procedure NodeQst601 begin
   Reply(374)

   if (getQuest(GVAR_SANFELIPE_QST_RUN) >= qEnd) then begin
      NAnswer(389,0,NodeQst606)
   end
   else if (global_var(GVAR_SANFELIPE_STATUS_BOSS)<0) then begin
      NAnswer(387,0,NodeQst605)
   end
   else if (gvar_bit(GVAR_SANFELIPE_BITS,bit_4) != 0) then begin
      NAnswer(384,0,NodeQst604)
   end
   else if (town_known(AREA_SAN_FELIPE) >= MARK_STATE_VISITED) then begin
      NAnswer(380,0,NodeQst603)
   end

   NAnswer(376,0,NodeQst602)
   NAnswer(375,0,Node999)
end

procedure NodeQst602 begin
   Reply(377)
   NAnswer(378,0,Node999)
   NAnswer(379,0,Node999)
end

procedure NodeQst603 begin
   Reply(381)
   NAnswer(382,0,Node999)
   NAnswer(383,0,Node999)
end

procedure NodeQst604 begin
   setQuest(GVAR_PUERTO_QST_SANFELIPE_PIP, qEnd);
   set_global_var(GVAR_SANFELIPE_STATUS_LAMPARA, 1);
   setQuest(GVAR_SANFELIPE_QST_RUN, qStop);
   set_REP(4)
   setReaction(20)
   exp_add(500);
   Reply(385)
   zNAnswer(386,0,Node999)
end

procedure NodeQst605 begin
   setQuest(GVAR_PUERTO_QST_SANFELIPE_PIP, qEnd);
   setQuest(GVAR_SANFELIPE_QST_RUN, qStop);
   set_REP(6)
   setReaction(25)
   exp_add(500);
   Reply(388)
   zNAnswer(386,0,Node999)
end

procedure NodeQst606 begin
   setQuest(GVAR_PUERTO_QST_SANFELIPE_PIP, qEnd);
   setQuest(GVAR_SANFELIPE_QST_RUN, qStop);
   set_REP(6)
   setReaction(25)
   exp_add(500);
   Reply(390)
   zNAnswer(386,0,Node999)
end
