#include "..\headers\define.h"
//---------------------

#define NAME                            SCRIPT_SCSldTlk
#define TOWN_REP_VAR                    GVAR_TOWN_REP_PUERTO // привязка к репутации (-1, если не нужно)

#define NUM_TEAM                        TEAM_BROTHERS_STEEL   // группа, к которой принадлежит персонаж (-1 если нужно оставить Team, заданный в редакторе)
#define NUM_AI                          AI_BOS_PALADIN        // AI персонажа (-1 если нужно оставить AI, заданный в редакторе)
#define KILL_SLAVA                      SLAVA_KILL_GOOD       // слава за убийство этого персонажа (SLAVA_KILL_GOOD, SLAVA_KILL_BAD, SLAVA_KILL_NEITRAL, SLAVA_KILL_CHILD)
#define KILL_TOWN_REP                   REP_KILL_CRITICAL     // репутация за убийство этого персонажа (-100 для враждебности всего поселения)
#define KILL_FRAC_REP                   FRAC_BOS              // принадлежность определенной фракции (-1, если не нужно)

#define FLAG_STEAL                      90 // Нижний порог навыка для кражи (для торговцев 200, для животных 300)
#define FLAG_ALCOHOL                    1  // Примет ли алкоголь от ГГ: 0 - принимает, 1 - не принимает
#define FLAG_FOOD                       1  // Примет ли пищу от ГГ: 0 - принимает, 1 - не принимает

//---------------------

procedure start;
procedure map_enter_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure timed_event_p_proc;
procedure critter_p_proc;
procedure use_obj_on_p_proc;
procedure use_skill_on_p_proc;
procedure pickup_p_proc;
procedure combat_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure talk_p_proc;

procedure Node998;
procedure Node999;
procedure NodeStartDialog;
procedure NodeBellEnd;
procedure NodeFstDialog;
procedure NodeFstDialog101;
procedure NodeFstDialog102;
procedure NodeFstDialog102b;
procedure NodeFstDialog103;
procedure NodeFstDialog104;
procedure NodeFstDialog105;
procedure NodeFstDialog106;
procedure NodeSndDialog;
procedure NodeSndDialog2;
procedure NodeGame;
procedure NodeGame2;
procedure NodeGame3;
procedure NodeGame4;
procedure NodeGame5;
procedure NodeGame6;
procedure NodeGame7;
procedure NodeGame8;
procedure NodeGame9;
procedure NodeAnswer100;
procedure NodeAnswer101;
procedure NodeAnswer102;
procedure NodeAnswer103;
procedure NodeAnswer104;
procedure NodeAnswer105;
procedure NodeAnswer200;
procedure NodeAnswer201;
procedure NodeAnswer202;
procedure NodeAnswer203;
procedure NodeAnswer204;
procedure NodeAnswer205;
procedure NodeAnswer206;
procedure NodeAnswer207;
procedure NodeAnswer208;
procedure NodeAnswer209;
procedure NodeAnswer210;
procedure NodeAnswer211;
procedure NodeAnswer212;
procedure NodeAnswer213;
procedure NodeAnswer214;
procedure NodeAnswer215;
procedure NodeAnswer216;
procedure NodeAnswer217;
procedure NodeAnswer218;
procedure NodeAnswer300;
procedure NodeAnswer301;
procedure NodeAnswer301b;
procedure NodeAnswer302;
procedure NodeAnswer303;
procedure NodeAnswer304;

//---------------------

#define LVAR_Game_Point                (6) // число выигрышей (выше 100 очков персонаж отказывает в игре)

variable gameStatus;

//---------------------



procedure start begin
end

procedure map_enter_p_proc begin
   if (is_loading_game == false) then begin
       set_start_home
   end
end

procedure look_at_p_proc begin
   lookProcMsg
end

procedure description_p_proc begin
   dsrptProcMsg
end

procedure timed_event_p_proc begin
   // Timer number 1 is reserved for character movement around the location
   // Timer number 2 is reserved for pop-up dialogue
   if (fixed_param == 1) then begin
       timer_move_to_home
   end
   if (fixed_param == 2) then begin
       //timer_float_reply(110,119)
   end
end

procedure critter_p_proc begin
   set_critter_options(1,0) //attack condition (0 personal feud, 1 clan feud, 2 always), turn to GG
   if self_enemy_dude then begin
   BarklyAttakDude
   end
end

procedure use_skill_on_p_proc begin
   skillUseSteal
   skillUseFAid
end

procedure pickup_p_proc begin
   pickupProcCritter
end

procedure use_obj_on_p_proc begin
   UsedItemToCrit_Proc
end

procedure combat_p_proc begin
   effectAttak(0,0,1,1,1) //poisoning min, radiation min, leg injury %, arm injury %, eye injury %
end

procedure damage_p_proc begin
   if (source_obj == dude_obj) then begin
   BarklyAttakDude
   end
   set_damage_dude
end

procedure destroy_p_proc begin
   kill_critter_opt
   kill_critter_BoS_item
end

procedure talk_p_proc begin
   setReaction(0) // Attitude towards the main character (1 - positive character, -1 negative, 0 neutral)
   dialog_proc(0,0,NodeStartDialog,-1,-1)
   /*
   if (global_var(GVAR_PUERTO_DOPUSK)>=0) then begin
   dialog_proc(0,0,NodeStartDialog,-1,-1)
   end
   else begin
   floater(dude_obj,102,COLOR_MSG_RED);
   end
   */
end

procedure Node998 begin
   set_enemy_dude;
end

procedure Node999 begin
end

procedure NodeStartDialog begin
   if (bitDialog(bit_1) == 0) then begin
   call NodeFstDialog;
   end
   else if ((getQuest(GVAR_PUERTO_QST_BELL)>=qEnd) and (bitDialog(bit_4) == 0)) then begin
   call NodeBellEnd;
   end
   else begin
   call NodeSndDialog;
   end
end

procedure NodeBellEnd begin
   bitDialogExp(bit_4,0)
   setBonusReaction(35)
   Reply(352)
   NAnswer(353,4,NodeSndDialog)
   NAnswer(354,-3,NodeSndDialog)
end

//--- FIRST DIALOGUE

procedure NodeFstDialog begin
   bitDialogExp(bit_1,0)
   if (global_var(GVAR_TITUL_BOS)>0) then begin
   zReply(210)
   GAnswer(211,4,NodeFstDialog103)
   BAnswer(213,4,NodeFstDialog104)
   BAnswer(217,-3,NodeFstDialog106)
   end
   else begin
   zReply(200)
   GAnswer(201,4,NodeFstDialog101)
   BAnswer(203,4,NodeFstDialog102b)
   BAnswer(218,-3,NodeFstDialog102)
   end
end

procedure NodeFstDialog101 begin
   set_REP(1)
   setBonusReaction(10)
   zReply(202)
   NAnswer(205,4,NodeFstDialog105)
end

procedure NodeFstDialog102b begin
   set_REP(-1)
   setBonusReaction(-10)
   call NodeFstDialog102;
end

procedure NodeFstDialog102 begin
   zReply(204)
   NAnswer(205,4,NodeFstDialog105)
   NAnswer(219,-3,NodeFstDialog105)
end

procedure NodeFstDialog103 begin
   set_REP(1)
   setBonusReaction(10)
   Reply(212)
   NAnswer(205,4,NodeFstDialog105)
end

procedure NodeFstDialog104 begin
   set_REP(-1)
   setBonusReaction(-10)
   Reply(214)
   NAnswer(205,4,NodeFstDialog105)
end

procedure NodeFstDialog105 begin
   Reply(206)
   GAnswer(207,4,NodeSndDialog)
   NAnswer(208,4,NodeSndDialog)
   BAnswer(209,4,NodeSndDialog)
   NAnswer(225,-3,NodeSndDialog)
end

procedure NodeFstDialog106 begin
   Reply(216)
   NAnswer(217,-3,NodeSndDialog)
end

//--- REPEAT DIALOGUE

procedure NodeSndDialog begin
   if (global_var(GVAR_TITUL_BOS)>0) then begin
   zReply(221)
   end
   else begin
   zReply(220)
   end

   NAnswer(230,4,NodeAnswer101)
   NAnswer(234,4,NodeAnswer100)
   //? боевой рассказ на 100 опыта
   if (getQuest(GVAR_PUERTO_QST_BELL) < qEnd) then begin
   if (gvar_bit(GVAR_DIALOGS_FLAGS_BIT, bit_32) != 0) then begin
   if (map_var(MVAR_PUERTO_MEDIC_BELL_INFO)==0) then begin
   NAnswer(340,4,NodeAnswer300)
   end
   end
   end
   if (local_var(LVAR_Game_Point)<10) then begin
   NAnswerSkill(250,4,NodeGame,SKILL_GAMBLING,50,250,NodeGame2)
   end
   else begin
   NAnswer(270,4,NodeGame9)
   end

   NAnswer(222,4,NodeSndDialog2)
   NAnswer(226,-3,Node999)
end

procedure NodeSndDialog2 begin
   Reply(223)
   NAnswer(224,4,Node999)
end

//--- АЗАРТНАЯ ИГРА

procedure NodeGame begin
   gameStatus := 0;
   Reply(251)
   if (item_amnt(dude_obj,PID_BOOTLE_CAPS)>=25) then begin
   NAnswer(253,4,NodeGame5)
   end
   NAnswer(254,4,NodeGame3)
   NAnswer(252,4,Node999)
end

procedure NodeGame2 begin
   Reply(257)
   NAnswer(258,4,Node999)
   BAnswer(259,4,Node999)
end

procedure NodeGame3 begin
   zReply(255)
   if (item_amnt(dude_obj,PID_BOOTLE_CAPS)>=50) then begin
   NAnswer(253,4,NodeGame4)
   end
   NAnswer(252,4,Node999)
end

procedure NodeGame4 begin
   gameStatus := 1;
   call NodeGame5;
end

procedure NodeGame5 begin
   Reply(260)
   NAnswer(261,4,NodeGame6)
   NAnswer(262,4,Node999)
end

procedure NodeGame6 begin
   if (has_skill(dude_obj, SKILL_GAMBLING) >= random(20,120)) then begin
   call NodeGame7;
   end
   else begin
   call NodeGame8;
   end
end

procedure NodeGame7 begin
   if (gameStatus == 0) then begin
   item_add(dude_obj,PID_AMMO_5_MM,1)
   end
   else begin
   item_add(dude_obj,PID_M_IRP,1)
   end
   exp_add(35);
   inc_local_var(LVAR_Game_Point);
   zReply(263)
   NAnswer(264,4,Node999)
   BAnswer(265,4,Node999)
end

procedure NodeGame8 begin
   if (gameStatus == 0) then begin
   item_remove(dude_obj,PID_BOOTLE_CAPS,25)
   end
   else begin
   item_remove(dude_obj,PID_BOOTLE_CAPS,50)
   end
   dec_local_var(LVAR_Game_Point);
   Reply(266)
   NAnswer(267,4,Node999)
   BAnswer(268,4,Node999)
end

procedure NodeGame9 begin
   Reply(271)
   NAnswer(272,4,Node999)
end

//--- QUESTIONS

procedure NodeAnswer100 begin
   Reply(235)
   NAnswer(290,4,NodeAnswer200)
   if (getQuest(GVAR_PUERTO_QST_TOY) != qZero) then begin
   NAnswer(280,4,NodeAnswer102)
   end
   NAnswer(236,4,Node999)
end

procedure NodeAnswer101 begin
   Reply(231)
   NAnswer(232,4,NodeAnswer100)
   NAnswer(233,4,Node999)
end

procedure NodeAnswer102 begin
   Reply(281)
   NAnswer(283,4,NodeAnswer103)
   NAnswer(285,4,NodeAnswer104)
   NAnswer(287,4,NodeAnswer105)
   NAnswer(282,4,NodeAnswer100)
end

procedure NodeAnswer103 begin
   Reply(284)
   NAnswer(285,4,NodeAnswer104)
   NAnswer(287,4,NodeAnswer105)
   NAnswer(282,4,NodeAnswer100)
end

procedure NodeAnswer104 begin
   Reply(286)
   NAnswer(283,4,NodeAnswer103)
   NAnswer(287,4,NodeAnswer105)
   NAnswer(282,4,NodeAnswer100)
end

procedure NodeAnswer105 begin
   Reply(288)
   NAnswer(283,4,NodeAnswer103)
   NAnswer(285,4,NodeAnswer104)
   NAnswer(282,4,NodeAnswer100)
end

procedure NodeAnswer200 begin
   Reply(291)
   if (bitDialog(bit_2) == 0) then begin
   NAnswer(295,4,NodeAnswer202)
   GAnswer(297,4,NodeAnswer203)
   BAnswer(293,4,NodeAnswer201)
   end
   NAnswer(292,4,NodeAnswer100)
end

procedure NodeAnswer201 begin
   setBonusReaction(-10)
   Reply(294)
   NAnswer(299,4,NodeAnswer204)
   GAnswer(300,4,NodeAnswer204)
   BAnswer(301,4,NodeAnswer204)
end

procedure NodeAnswer202 begin
   Reply(296)
   NAnswer(299,4,NodeAnswer204)
   GAnswer(300,4,NodeAnswer204)
   BAnswer(301,4,NodeAnswer204)
end

procedure NodeAnswer203 begin
   setBonusReaction(10)
   Reply(298)
   NAnswer(299,4,NodeAnswer204)
   GAnswer(300,4,NodeAnswer204)
   BAnswer(301,4,NodeAnswer204)
end

procedure NodeAnswer204 begin
   Reply(302)
   NAnswer(303,4,NodeAnswer205)
   BAnswer(304,4,NodeAnswer205)
end

procedure NodeAnswer205 begin
   Reply(305)
   NAnswer(306,4,NodeAnswer206)
   BAnswer(307,4,NodeAnswer206)
end

procedure NodeAnswer206 begin
   Reply(308)
   NAnswer(309,4,NodeAnswer208)
   GAnswer(310,4,NodeAnswer207)
   BAnswer(312,4,NodeAnswer209)
end

procedure NodeAnswer207 begin
   setBonusReaction(10)
   set_REP(1)
   call NodeAnswer209;
end

procedure NodeAnswer208 begin
   Reply(311)
   NAnswer(314,4,NodeAnswer210)
   BAnswer(315,4,NodeAnswer210)
end

procedure NodeAnswer209 begin
   setBonusReaction(-10)
   set_REP(-1)
   Reply(313)
   NAnswer(314,4,NodeAnswer210)
   BAnswer(315,4,NodeAnswer210)
end

procedure NodeAnswer210 begin
   Reply(316)
   NAnswer(317,4,NodeAnswer211)
   BAnswer(318,4,NodeAnswer212)
end

procedure NodeAnswer211 begin
   Reply(319)
   NAnswer(320,4,NodeAnswer213)
   BAnswer(321,4,NodeAnswer214)
end

procedure NodeAnswer212 begin
   setBonusReaction(-10)
   call NodeAnswer211;
end

procedure NodeAnswer213 begin
   Reply(322)
   NAnswer(323,4,NodeAnswer215)
   BAnswer(324,4,NodeAnswer216)
end

procedure NodeAnswer214 begin
   setBonusReaction(-10)
   call NodeAnswer213;
end

procedure NodeAnswer215 begin
   Reply(325)
   NAnswer(327,4,NodeAnswer216)
   GAnswer(326,4,NodeAnswer217)
   BAnswer(328,4,NodeAnswer218)
end

procedure NodeAnswer216 begin
   bitDialogExp(bit_2,100)
   zReply(329)
   NAnswer(330,4,Node999)
   GAnswer(331,4,Node999)
   BAnswer(332,4,Node999)
end

procedure NodeAnswer217 begin
   setBonusReaction(10)
   set_REP(1)
   call NodeAnswer216;
end

procedure NodeAnswer218 begin
   setBonusReaction(-10)
   set_REP(-1)
   call NodeAnswer216;
end

procedure NodeAnswer300 begin
   bitDialogExp(bit_3,100)
   zReply(341)
   GAnswer(342,4,NodeAnswer301)
   BAnswer(343,4,NodeAnswer301b)
end

procedure NodeAnswer301 begin
   Reply(344)
   NAnswer(345,4,NodeAnswer302)
end

procedure NodeAnswer301b begin
   set_REP(-1)
   call NodeAnswer301;
end

procedure NodeAnswer302 begin
   Reply(346)
   NAnswer(347,4,NodeAnswer303)
end

procedure NodeAnswer303 begin
   Reply(348)
   NAnswer(349,4,NodeAnswer304)
end

procedure NodeAnswer304 begin
   set_map_var(MVAR_PUERTO_MEDIC_BELL_INFO, 1);
   mark_on_map(AREA_CASA_NUEVA)
   mark_map_entrance_state(MAP_CASA_NUEVA_CEMENT, 1);
   Reply(350)
   NAnswer(351,4,Node999)
end
