#include "..\headers\define.h"
//---------------------

#define NAME                            SCRIPT_DCBarShf
#define TOWN_REP_VAR                    GVAR_TOWN_REP_CASA_GRANDE // привязка к репутации (-1, если не нужно)

#define NUM_TEAM                        TEAM_CASAGRANDE_CITYHALL // группа, к которой принадлежит персонаж (-1 если нужно оставить Team, заданный в редакторе)
#define NUM_AI                          AI_PERSON_TOUGH       // AI персонажа (-1 если нужно оставить AI, заданный в редакторе)
#define KILL_SLAVA                      SLAVA_KILL_GOOD       // слава за убийство этого персонажа (SLAVA_KILL_GOOD, SLAVA_KILL_BAD, SLAVA_KILL_NEITRAL, SLAVA_KILL_CHILD)
#define KILL_TOWN_REP                   REP_KILL_CRITICAL     // репутация за убийство этого персонажа (REP_KILL_GOOD, REP_KILL_BAD, REP_KILL_NEITRAL, REP_KILL_CRITICAL для враждебности всего поселения, REP_KILL_CHILD)
#define KILL_FRAC_REP                   FRAC_NON              // принадлежность определенной фракции (-1, если не нужно)

#define FLAG_STEAL                      75 // Нижний порог навыка для кражи (для торговцев 200, для животных 300)
#define FLAG_ALCOHOL                    1  // Примет ли алкоголь от ГГ: 0 - принимает, 1 - не принимает
#define FLAG_FOOD                       1  // Примет ли пищу от ГГ: 0 - принимает, 1 - не принимает

//---------------------

procedure start;
procedure map_enter_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure timed_event_p_proc;
procedure critter_p_proc;
procedure use_obj_on_p_proc;
procedure use_skill_on_p_proc;
procedure pickup_p_proc;
procedure push_p_proc;
procedure combat_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure talk_p_proc;

/*
procedure Node998;
procedure Node999;
procedure NodeStartDialog;
procedure NodeFstDialog;
procedure NodeSndDialog;
*/

//---------------------

//#define LVAR_Flag_A                     (6) // отвечает за ...

import variable obj_critter_a; // указатель на мэра

//---------------------



procedure start begin
end

procedure map_enter_p_proc begin
   if (is_loading_game == false) then begin
       set_start_home
       set_obj_visibility(self_obj, 1);
       if (cur_map_index == MAP_CASA_GRANDE_BAR) then begin
          if (getQuest(GVAR_CGRANDE_ATTAK_TO_BAR) == qStart) then begin
          set_obj_visibility(self_obj, 0);
          end
       end
       if (cur_map_index == MAP_CASA_GRANDE_CITY) then begin
          if (bitGrande_shrf_attak_mer != 0) then begin
          critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_PLAYER); // TEAM_CASAGRANDE_WATERSTAN
          set_obj_visibility(self_obj, 0);
          end
       end
       if (global_var(GVAR_CGRANDE_STATUS_SHEFF) < 0) then begin
          set_obj_visibility(self_obj, 1);
          destroy_object(self_obj);
       end
   end
end

procedure look_at_p_proc begin
   lookProcMsg
end

procedure description_p_proc begin
   dsrptProcMsg
end

procedure timed_event_p_proc begin
   // Таймер за номером 1 рарезервирован под перемещение персонажа по локации
   // Таймер за номером 2 рарезервирован под всплывающие реплики
   if (fixed_param == 1) then begin
       if (cur_map_index == MAP_CASA_GRANDE_BAR) then begin
       timer_move_to_home
       end
   end
   if (fixed_param == 2) then begin
       //timer_float_reply(110,119)
   end
end

procedure critter_p_proc begin
   variable attakParam;
   attakParam := 0;
   if (cur_map_index == MAP_CASA_GRANDE_BAR) then begin
   attakParam := map_var(MVAR_CGRANDE_BAR_MER);
   end
   set_critter_options(attakParam,0) //условие нападения (0 личная вражда, 1 вражда клановая, 2 всегда), разворот к ГГ

   if (cur_map_index == MAP_CASA_GRANDE_CITY) then begin
   if (self_visible == true) then begin
       if (bitGrande_shrf_attak_mer != 0) then begin
          if (obj_critter_a > 0) then begin
             if (obj_can_see_obj(self_obj,obj_critter_a) == true) then begin
                  attack(obj_critter_a);
             end
             else if ((anim_busy(self_obj) == false) and ((critter_state(self_obj) bwand DAM_KNOCKED_OUT) == FALSE)) then begin
                  if (tile_distance_objs(self_obj,obj_critter_a)<25) then begin
                  animate_run_to_tile(tile_num(obj_critter_a));
                  end
                  else begin
                  animate_run_to_tile(tile_num_in_direction(self_tile,rotation_to_tile(self_tile, tile_num(obj_critter_a)),20));
                  end
             end
          end
       end
   end
   end
end

procedure use_skill_on_p_proc begin
   skillUseSteal
   skillUseFAid
end

procedure pickup_p_proc begin
   pickupProcCritter
end

procedure push_p_proc begin
   if (cur_map_index == MAP_CASA_GRANDE_BAR) then begin
   script_overrides;
   end
   else begin
   push_options(self_tile,3,-1) // толкать (точка отсчета, макс расстояние, фраза над нпс при толкании), удалить если не надо
   end
end

procedure use_obj_on_p_proc begin
   UsedItemToCrit_Proc
end

procedure combat_p_proc begin
   effectAttak(0,0,1,1,1) //отравление min, облучение min, травма ног %, травма рук %, травма глаз %
end

procedure damage_p_proc begin
   set_damage_dude
end

procedure destroy_p_proc begin
   dec_global_var(GVAR_CGRANDE_STATUS_CTZN);
   set_global_var(GVAR_CGRANDE_STATUS_SHEFF,-2);
   if (source_obj == dude_obj) then begin
   set_map_var(MVAR_CGRANDE_BAR_MER,2);
   end
   kill_critter_opt
end

procedure talk_p_proc begin
   if (cur_map_index == MAP_CASA_GRANDE_CITY) then begin
      if (global_var(GVAR_CGRANDE_STATUS_MER) < 0) then begin
      floater(self_obj,106,COLOR_MSG_GREEN);
      end
      else begin
      floater(self_obj,105,COLOR_MSG_RED);
      end
   end
   else if (cur_map_index == MAP_CASA_GRANDE_BAR) then begin
      if (global_var(GVAR_CGRANDE_STATUS_MER) < 0) then begin
      floater(self_obj,104,COLOR_MSG_NORMAL);
      end
      else if (getQuest(GVAR_CGRANDE_ATTAK_TO_BAR) == qStart) then begin
      floater(self_obj,102,COLOR_MSG_RED);
      end
      else begin
      floater(self_obj,103,COLOR_MSG_NORMAL);
      end
   end
end

/*
Салливан нападает на мэра в баре после успешного разруливания ситуации с грабителями (мэр жив, дочь спасена, Салливан жив).
При этом устанавливать set_gvar_bit_on(GVAR_DIALOGS_FLAGS_BIT, bit_26);

- Ты не уйдешь отсюда, Альфред. (угрожающе достает оружие) Не волнуйся, я позабочусь о твоих похорах. - Ривера... Что ты...
- Я и подумать не мог, что все так удачно сложится. Грабители нападают на город и убивают мэра, а я убиваю грабителей. Какой правдоподобный финал. - Ты не можешь так со мной поступить! Мы с тобой знакомы с самого детства...
- Ты сам виноват, друг. Ты обмяг и потерял свою силу из-за этой девчонки. А значит и свое право указывать мне. В старые времена у тебя хватало яиц, чтобы править этим городом. Мне же доставалась жалкая участь помощника. Теперь *я* буду мэром Каса-Гранде. - Предатель!
- Замолкни. На тебя тошно смотреть.
*/
