#include "..\headers\define.h"
//---------------------

#define NAME                            SCRIPT_DCMerStp
#define TOWN_REP_VAR                    GVAR_TOWN_REP_CASA_GRANDE // привязка к репутации (-1, если не нужно)

#define NUM_TEAM                        TEAM_CASAGRANDE_CITYHALL // группа, к которой принадлежит персонаж (-1 если нужно оставить Team, заданный в редакторе)
#define NUM_AI                          AI_GUARDS             // AI персонажа (-1 если нужно оставить AI, заданный в редакторе)
#define KILL_SLAVA                      SLAVA_KILL_GOOD       // слава за убийство этого персонажа (SLAVA_KILL_GOOD, SLAVA_KILL_BAD, SLAVA_KILL_NEITRAL, SLAVA_KILL_CHILD)
#define KILL_TOWN_REP                   REP_KILL_GOOD         // репутация за убийство этого персонажа (REP_KILL_GOOD, REP_KILL_BAD, REP_KILL_NEITRAL, REP_KILL_CRITICAL для враждебности всего поселения, REP_KILL_CHILD)
#define KILL_FRAC_REP                   FRAC_NON              // принадлежность определенной фракции (-1, если не нужно)

#define FLAG_STEAL                      50 // Нижний порог навыка для кражи (для торговцев 200, для животных 300)
#define FLAG_ALCOHOL                    0  // Примет ли алкоголь от ГГ: 0 - принимает, 1 - не принимает
#define FLAG_FOOD                       1  // Примет ли пищу от ГГ: 0 - принимает, 1 - не принимает

//---------------------

procedure start;
procedure map_enter_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure timed_event_p_proc;
procedure critter_p_proc;
procedure use_obj_on_p_proc;
procedure use_skill_on_p_proc;
procedure pickup_p_proc;
procedure combat_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure talk_p_proc;

procedure Node998;
procedure Node999;
procedure NodeStartDialog;
procedure NodeStopDialog;
procedure NodeStopDialog2;
procedure NodeStopDialog200;
procedure NodeStopDialog201;
procedure NodeStopDialog202;
procedure NodeFstDialog;
procedure NodeFstDialog2;
procedure NodeFstDialog3;
procedure NodeFstDialog4;
procedure NodeFstDialog5;
procedure NodeFstDialog6;
procedure NodeSndDialog;
procedure NodeAnswer100;
procedure NodeAnswer101;
procedure NodeAnswer102;
procedure NodeAnswer103;
procedure NodeAnswer200;
procedure NodeAnswer201;
procedure NodeAnswer202;
procedure NodeAnswer203;
procedure NodeAnswer204;

//---------------------

//#define LVAR_Flag_A                     (6) // is responsible for ...

//---------------------



procedure start begin
end

procedure map_enter_p_proc begin
   if (is_loading_game == false) then begin
       set_start_home
       if (global_var(GVAR_CGRANDE_STATUS_MER) < 0) then begin
       set_obj_visibility(self_obj, 1);
       end
       if (bitGrande_shrf_attak_mer != 0) then begin
       critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_BANDITS);
       add_timer_event(self_obj, 10, 3);
       end
   end
end

procedure look_at_p_proc begin
   lookProcMsg
end

procedure description_p_proc begin
   dsrptProcMsg
end

procedure timed_event_p_proc begin
   // Timer number 1 is reserved for character movement around the location
   // Timer number 2 is reserved for pop-up dialogue
   if (fixed_param == 1) then begin
       if (bitGrande_shrf_attak_mer != 0) then begin
       timer_move_to_tile(1,tile_num_in_direction(HomeTile,1,20),0)
       end
       else begin
       timer_move_to_home
       end
   end
   if (fixed_param == 2) then begin
       //timer_float_reply(110,119)
   end
   if (fixed_param == 3) then begin
       floater(self_obj, 104, COLOR_MSG_RED);
   end
end

procedure critter_p_proc begin
   set_critter_options(1,0) //attack condition (0 personal feud, 1 clan feud, 2 always), turn to GG
end

procedure use_skill_on_p_proc begin
   skillUseSteal
   skillUseFAid
end

procedure pickup_p_proc begin
   pickupProcCritter
end

procedure use_obj_on_p_proc begin
   UsedItemToCrit_Proc
end

procedure combat_p_proc begin
   effectAttak(0,0,1,1,1) //poisoning min, radiation min, leg injury %, arm injury %, eye injury %
end

procedure damage_p_proc begin
   set_damage_dude
end

procedure destroy_p_proc begin
   dec_global_var(GVAR_CGRANDE_STATUS_CTZN);
   kill_critter_opt
end

procedure talk_p_proc begin
   if (bitGrande_shrf_attak_mer != 0) then begin
   floater(self_obj,105,COLOR_MSG_RED);
   end
   else if (bitDialog(bit_2) != 0) then begin
   floater(self_obj,106,COLOR_MSG_RED);
   end
   else if ((armor_pid_dude_var == PID_ARMOR_ROAD) or (global_var(GVAR_TITUL_WARRIOR_ROAD) > 0)) then begin
   floater(self_obj,103,COLOR_MSG_RED);
   end
   else begin
   setReaction(0) // Attitude towards the main character (1 - positive character, -1 negative, 0 neutral)
   fracReaction(GVAR_TITUL_WARRIOR_ROAD,-25) // Поправка к отношению за принадлежность к фракциям
   dialog_proc(0,0,NodeStartDialog,-1,-1)
   end
end

procedure Node998 begin
   set_enemy_dude;
end

procedure Node999 begin
end

procedure NodeStartDialog begin
   if (global_var(GVAR_CGRANDE_STATUS_MER) < 0)then begin
      call NodeStopDialog200;
   end
   else if (getQuest(GVAR_CGRANDE_ATTAK_TO_BAR) == qStart) then begin
      call NodeStopDialog;
   end
   else begin
      if (bitDialog(bit_1) == 0) then begin
      call NodeFstDialog;
      end
      else begin
      call NodeSndDialog;
      end
   end
end

//--- STOP DIALOGUE

procedure NodeStopDialog begin
   Reply(200)
   NAnswer(201,4,Node999)
   NAnswer(202,4,NodeStopDialog2)
   NAnswer(205,-3,Node999)
end

procedure NodeStopDialog2 begin
   Reply(203)
   NAnswer(204,4,Node999)
end

procedure NodeStopDialog200 begin
   bitDialogExp(bit_2,0)
   Reply(210)
   NAnswer(211,4,NodeStopDialog201)
   NAnswer(213,4,NodeStopDialog202)
   NAnswer(218,-3,NodeStopDialog201)
end

procedure NodeStopDialog201 begin
   Reply(212)
   BAnswer(215,4,Node999)
   NAnswer(216,4,Node999)
   NAnswer(217,-3,Node999)
end

procedure NodeStopDialog202 begin
   Reply(214)
   BAnswer(215,4,Node999)
   NAnswer(216,4,Node999)
   NAnswer(217,-3,Node999)
end

//--- FIRST DIALOGUE

procedure NodeFstDialog begin
   bitDialogExp(bit_1,0)
   Reply(250)
   NAnswer(251,4,NodeFstDialog2)
   NAnswer(257,4,NodeFstDialog4)
   NAnswer(264,-3,NodeFstDialog6)
end

procedure NodeFstDialog2 begin
   Reply(252)
   NAnswer(253,4,NodeFstDialog3)
end

procedure NodeFstDialog3 begin
   Reply(254)
   NAnswer(256,4,NodeAnswer100)
   NAnswer(255,4,Node999)
end

procedure NodeFstDialog4 begin
   Reply(258)
   NAnswer(259,4,NodeFstDialog5)
   BAnswer(263,4,NodeFstDialog2)
end

procedure NodeFstDialog5 begin
   Reply(260)
   NAnswer(262,4,NodeAnswer100)
   NAnswer(261,4,Node999)
end

procedure NodeFstDialog6 begin
   Reply(265)
   NAnswer(266,-3,Node999)
end

//--- REPEAT DIALOGUE

procedure NodeSndDialog begin
   if ((getQuest(GVAR_CGRANDE_ATTAK_TO_BAR) >= qEnd) and (getQuest(GVAR_CGRANDE_QST_ROADSTOP) == qZero)) then begin
   Reply(231)
   end
   else begin
   Reply(230)
   end

   NAnswer(300,4,NodeAnswer100)
   if (bitDialog(bit_5) == 0) then begin
   NAnswer(310,4,NodeAnswer200)
   end
   if (global_var(GVAR_RAIDER_STATUS_PRISON) == 0) then begin
   if (getQuest(GVAR_RAIDER_QST_PRISON) == qStart) then begin
   NAnswer(270,4,NodeAnswer103)
   end
   end
   NAnswer(232,4,Node999)
   NAnswer(234,-3,Node999)
end

procedure NodeAnswer100 begin
   Reply(301)
   NAnswer(302,4,NodeAnswer101)
   NAnswer(304,4,NodeAnswer102)
end

procedure NodeAnswer101 begin
   Reply(303)
   NAnswer(304,4,NodeAnswer102)
   if (bitDialog(bit_5) == 0) then begin
   NAnswer(306,4,NodeAnswer200)
   end
   NAnswer(319,4,Node999)
end

procedure NodeAnswer102 begin
   Reply(305)
   NAnswer(302,4,NodeAnswer101)
   if (bitDialog(bit_5) == 0) then begin
   NAnswer(306,4,NodeAnswer200)
   end
   NAnswer(319,4,Node999)
end

procedure NodeAnswer103 begin
   Reply(271)
   NAnswer(272,4,Node999)
end

procedure NodeAnswer200 begin
   bitDialogExp(bit_5,0)
   Reply(311)
   NAnswer(312,4,NodeAnswer201)
end

procedure NodeAnswer201 begin
   Reply(313)
   BAnswer(316,4,NodeAnswer202)
   NAnswer(314,4,NodeAnswer203)
   GAnswer(325,4,NodeAnswer204)
end

procedure NodeAnswer202 begin
   setBonusReaction(-25)
   set_REP(-1)
   zReply(317)
   NAnswer(318,4,Node999)
end

procedure NodeAnswer203 begin
   Reply(315)
   BAnswer(323,4,Node999)
   NAnswer(324,4,Node999)
end

procedure NodeAnswer204 begin
   setBonusReaction(25)
   set_REP(1)
   Reply(326)
   NAnswer(328,4,Node999)
   BAnswer(327,4,Node999)
end
