{100}{}{Ves a Héctor.}
{101}{}{Estás viendo a un Mexicano de cabellera larga. Lleva puesta una camiseta de tela gruesa y áspera, con un pañuelo rojo atado a su cabeza.}
{102}{}{No hablaré con un gringo.}
{103}{}{«Me retracto, parece que acá sí se puede sobrevivir.»}
{104}{}{«Veo que juzgue mal al capitán. Parece que acá sí se puede sobrevivir.»}
{105}{}{«¡Vamos a navegar de vuelta a casa!»}

{200}{}{«Oye, amigo. ¿No eres gringo, cierto? Bien. Tenemos que hablar.»}
{201}{}{«¿Sobre qué?»}
{202}{}{«¿Ya has hablado con Cesareo? Está intentando que nos asentemos en esta bahía. Yo digo que es una pésima idea.»}
{1202}{}{«¿Ya has hablado con Cesareo? Está intentando que nos asentemos en esta bahía. Yo digo que es una pésima idea.»}
{203}{}{«¿Por qué?»}
{204}{}{«Estamos aislados de la civilización. Acá, se vive y se muere solo. ¿Y con qué contamos? Un solo bote. Ruinas llenas de chatarra. Si nos alejamos de la costa para irnos más adentro, hay puro pinche cerro. ¡Acá no hay NADA! Hasta pescar significa que debemos pescar lejos de la costa, porque está envenenada.»}
{205}{}{«Pues, ¿qué sugieres?»}
{206}{}{«¡El capitán nos trajo directo al infierno! Yo digo que es hora de decirle que chingue a su madre y devolvernos a México, y yo no soy el único que piensa así. Ayúdanos a que cambie de parecer. Si él te pide que hagas algo, haz lo contrario. Y si aún así no nos escucha... Entonces, habrá que encobijarlo. ¿Me captas?»}
{207}{}{«De acuerdo, lo tendré en mente.»}
{208}{}{«Mierda... La vida te tiene de lo peor. Ojalá que cuando salgamos de acá, no acabemos igual que tú. No eres gringo, ¿cierto? Bien. Tenemos que hablar.»}

{210}{}{«Aquí nadie ha puesto un pie desde el Apocalipsis. Hay que irnos. Ahora.»}
{211}{}{«Puede ser.»}
{212}{}{«¡El capitán nos ha llevado por mal camino! Hora de que chingue a su madre.»}
{213}{}{«Su capitán ha muerto. Ahora podrán hacer lo que quieran.»}
{214}{}{«¡Es nuestra oportunidad! Hora de irnos de aquí, está maldito. Solo hay un último problema; la bomba de agua de la goleta está rota. Y sin ella, no llegaremos lejos. Está atracado en Fondeport.»}
{215}{}{«Bien, veré que puedo hacerle.»}
{216}{}{«La goleta está lista para partir.»}
{217}{}{«Cesareo ha cambiado de parecer, también quiere marcharse.»}
{218}{}{(te da un apretón de manos muy fuerte) «Es como si el destino mismo te hubiese mandado con nosotros. Adiós, amigo.»}
{1218}{}{(te da un abrazo fuerte) «Es como si el destino mismo te hubiese mandado con nosotros. Adiós, amiga.»}
{219}{}{«Es como si el destino mismo te hubiese mandado con nosotros. Adiós, amigo.»}
{1219}{}{«Es como si el destino mismo te hubiese mandado con nosotros. Adiós, amiga.»}
{220}{}{«Buena suerte, nos vemos.»}
{221}{}{«Así que es esto lo que esta tierra le hace a la gente... Los reduce a ser animales como tú. Eso es malo, y debemos marcharnos. Ahora.»}

{230}{}{«¿Cómo podríamos hacerle cambiar de parecer a Cesareo?»}
{231}{}{«Debe comprender que sobrevivir acá es imposible. De lo contrario... Puede que alguien le mezcle veneno de escorpión a su ceviche, jeje.»}
{232}{}{«Eso no será fácil.»}
{233}{}{«Aún así... Esa idea del veneno podría resultar útil.»}
{234}{}{«Me pidió que reparase el faro.»}
{235}{}{«Será mejor que descompongas la maquinaria del faro para que jamás vuelva a encenderse.»}
{236}{}{«Me ha pedido que verifique los rumores de monstruos junto a la costa.»}
{237}{}{«Cesareo me ha dicho que lidie con las sanguijuelas gigantes.»}
{238}{}{«Ahí está, es prueba de que este sitio no es seguro.»}
{239}{}{«Él quiere que explore el área cercana a San Felipe.»}
{240}{}{«Pues mírale la cara de pendejo y miéntele, de todos modos, acá no hay nada por lo que valga la pena sacrificarse..»}
