{100}{}{Ves a Jan.}
{101}{}{Ves a un mexicano con una barba poblada y desaliñada.}
{102}{}{Ante ti, se encuentra un mexicano visiblemente nervioso.}

{110}{}{«¡Ellos sí existen!»}
{111}{}{«¡Digo la verdad! ¿¡Por qué no me creen!?»}
{112}{}{«¡Algún día van a llegar, se arrastrarán hasta acá!»}
{113}{}{«¡Tenemos que hacer algo, ahora!»}

{120}{}{¡Ellos sí existen!}
{121}{}{¡Digo la verdad! ¿¡Por qué no me creen!?}
{122}{}{¡Algún día van a llegar, se arrastrarán hasta acá!}
{123}{}{¡Tenemos que hacer algo, ahora!}

# First dialogue
{200}{}{«¡Hola, amigo! ¿Cómo fue que la vida te trajo para acá?»}
{201}{}{«Bueno, yo...»}
{202}{}{«¡Shh! ¡No digas ni una palabra! A estos güeyes no les gustan los forasteros. Me miran a los ojos como si ya tuviesen el cuchillo en mano.»}
{203}{}{«¿Por qué? ¿Acaso pasó algo entre ustedes?»}
{204}{}{(lanza miradas a su alrededor, claramente está nervioso) «¡Los monstruos!»}
{205}{}{«¿Monstruos?»}
{206}{}{«¡Sanguijuelas gigantes! ¡Unas criaturas horrendas y apestosas! Aparecen en la costa, en donde me pongo a recoger mariscos. Pero esos tontos no me escuchan, ¡creen que estoy loco! Pero el viejo Jan no está loco. ¡Ni un poquito!»}
{207}{}{«Están cometiendo un grave error al ignorarte.»}
{208}{}{«Me parece que perdiste la cabeza, viejo.»}
{209}{}{«No me dejes sólo, amigo. ¡Necesito ayuda!»}
{210}{}{«Está bien, ¿en dónde dirías que tienen su nido?»}
{211}{}{«Está por allá, cerca de la goleta encallada. solo sigue bajando por la costa. Con cuidado.»}
{212}{}{«Entendido. Nos vemos.»}

# English only path
{213}{}{Hola, amigo. ¿De dónde eres?}
{214}{}{¿Qué tal? No soy de por aquí.}
{215}{}{Ah, ¿no? (mira a su alrededor) Sígueme, amigo. (te hace una señal para que lo sigas)}
{1215}{}{Ah, ¿no? (mira a su alrededor) Sígueme, amigo. (te hace una señal para que lo sigas)}
{216}{}{¿Quieres mostrarme algo? Claro, te sigo.}
{217}{}{No, no. Antes que nada, necesito hablar con tu jefe. Adiós.}
{218}{}{(conforme te acercas a la costa, el aldeano señala a su choza en la lejanía, y suelta un grito de terror) ¡Allí, compadre! ¡Por allá hay monstruos!}
{219}{}{¿'Monstruos'? Hm... Gracias por el aviso. Adiós.}

# Repeat dialogue
{220}{}{Hola, amigo.}
{1220}{}{Hola, amiga.}
{221}{}{«Adiós, Jan.»}
{222}{}{«¿Qué hubo, compadre?»}
{1222}{}{«Muy buenas, señorita.»}
{223}{}{«Adiós, forastero.»}

{230}{}{«¿Quién está a cargo aquí?»}
{231}{}{«Cesareo. Él nuestro capitán.»}
{232}{}{«¿Por qué le llamas capitán?»}
{233}{}{«Llegamos acá por una goleta, y Cesareo era nuestro capitán. Se nos pegó el apodo.»}
{234}{}{«Qué interesante, cuéntame más.»}
{235}{}{«Ya veo. Adiós.»}
{236}{}{«¿Quién eres, y a qué te dedicas?»}
{237}{}{«Me llamo Jan, vivo acá cerca y soy quien recoge mariscos al lado de la costa... ¡O eso hacía, hasta que las condenadas sanguijuelas se apareciesen!»}
{238}{}{Mi nombre es Jan.}
{239}{}{Jan... Entendido.}
{240}{}{Pues, nuestro jefe vendría a ser el Capitán Cesareo.}
{241}{}{Comprendo.}
{242}{}{«¿Por qué no te ayudan los tuyos?»}
{243}{}{«¡Porque no me creen! ¡Según ellos, se me cayó la olla! ¡Pero yo digo la verdad, he visto a los monstruos!»}
{244}{}{«Ustedes son un grupo interesante, ¿podrías contarme más de tu asentamiento?»}
{245}{}{«Quizás deban ponerte más atención. Adiós.»}
{246}{}{«¿Hace cuánto tiempo que vives aquí?»}
{247}{}{«Hace poco, porque llegamos hace un par de años; habíamos usado la goleta para llegar. Pregúntaselo al capitán.»}
{248}{}{«Está bien.»}
{249}{}{«¿Qué sabes de los monstruos?»}
{250}{}{«Se ven como... Sanguijuelas marinas gigantes, con unos tentáculos asquerosos saliéndoles del hocico. ¡Yo jamás había visto algo así! Hace poco hubo una tormenta y se aparecieron luego de eso. Supongo eso los sacó de las profundidades. ¿Quién hubiera dicho que el peligro nos encontraría en un lugar tan abandonado como este?»}
{251}{}{«Resulta que sí habían monstruos cerca de tu choza. Ya no hay por qué preocuparse de ellos.»}
{252}{}{«¿¡Ves!? ¡Es lo que yo decía! Ahora Cesareo no podrá ignorarlo. ¡Todos sabrán que yo decía la pura verdad! ¡Porque se ríeron de mí! De todos modos, ten cuidado, porque no sabemos con certeza cuántas de esas cosas hay rondando por acá. Habla con Cesareo, él te escuchará. Yo me regreso a mi choza.»}
{253}{}{«Bien. Nos vemos.»}
{254}{}{Ya no hay de qué preocuparse, los monstruos ya no están.}
{255}{}{¡Ah! ¡Gracias, amigo! Dile al Capitán Cesareo lo que has hecho por nosotros, sí?}
{1255}{}{¡Ah! ¡Gracias, amiga! Dile al Capitán Cesareo lo que has hecho por nosotros, sí?}
{256}{}{Bien, puedes regresar a tu choza.}

{257}{}{«¡Muchas gracias, compadre! ¡Ahora todos tendrán clarito que no andaba mintiendo!»}
{1257}{}{«¡Muchas gracias, señorita! ¡Ahora todos tendrán clarito que no andaba mintiendo!»}
{258}{}{«¿Sabes de dónde provienen las sanguijuelas!»}
{259}{}{«A ver, yo he notado que se salen de su agujero por la noche. Mira, es por la gruta esa, la de allá.»}
{260}{}{«Indícame en dónde está la gruta.»}
{261}{}{«De acuerdo, iré a echarle una mirada.».}
{262}{}{(Te señala a la costa) Por allá, en la gruta.}

# Added for Espanol trait handling
{421}{}{Adiós, Jan.}
{423}{}{Adiós, forastero}
{430}{}{¿Quién está a cargo aquí?}
{436}{}{¿Quién eres, y a qué te dedicas?}
{460}{}{¿Podrías mostrarme en dónde está la gruta?}
{461}{}{Está bien, iré a echar un vistazo.}
