{100}{}{Ves a Gloria.}
{101}{}{Ves a una chica mexicana.}
{102}{}{Has resucitado a tu paciente.}
{103}{}{¡Virgencita! ¿Qué sucederá ahora?}

{110}{}{Ahhhh...}
{111}{}{(La chica está inconsciente. Esto es una emergencia médica.)}
{112}{}{«Gracias por salvarme la vida. ¡Tengo que advertirle a Cesareo de estos monstruos, de inmediato!»}
{113}{}{Me has salvado, te lo agradezco mucho.}
{114}{}{«Claro, nos vemos en la aldea.»}
{115}{}{Te estoy muy agradecida.}
{116}{}{«Gracias, de verdad.»}
{117}{}{Te lo agradezco muchísimo. Habla con Cesareo.}
{118}{}{«Gracias, en serio. Habla con Cesareo acerca de lo que ocurrió.»}

{179}{}{«Relájate, todo está bien.»}
{180}{}{«Ahhhh... ¡Monstruos! ¡Están aquí, están aquí!»}
{181}{}{«Es mejor que descanses...»}
{182}{}{«Claro, le diré a los demás lo que pasó. Por mientras, debes descansar.»}

#First dialogue
{200}{}{Ahhhh... (habla en voz baja y no consigues entenderla)}
{201}{}{¿Qué?}
{202}{}{¿De qué carajos hablas?}
{203}{}{¡Monstruos! ¡Están en todos lados!}
{204}{}{Cálmate, ya estás a salvo.}
{205}{}{No estás bien de la cabeza, ¿cierto?}
{206}{}{(mira nerviosa a su alrededor, incluyéndote a ti)}
{207}{}{¿Quieres salir de aquí? Sígueme, sé en dónde está la salida. Vamos, muévete.}
{208}{}{No, no quiero a ninguna pinche loca siguiéndome. ¡Quédate ahí!}
{209}{}{No te preocupes. Todo está bien.}
{210}{}{«¡Monstruos! ¡Están en todos lados!»}
{211}{}{«Cálmate, ya estás a salvo.»}
{212}{}{«¿Quieres que nos escuchen? Silencio, idiota.»}
{213}{}{«Ah, perdón. ¡Es que son bien feos! Sólo quiero irme a casa. ¿Me ayudarás a escapar?»}
{214}{}{«Por supuesto, salgamos de aquí. Necesitas aire fresco...»}
{215}{}{«No, no necesito a una vieja loca siguiéndome. Quédate ahí y no hagas ruido.»}
{216}{}{Estaré más calladita que un ratón.}
{217}{}{«Estaré más calladita que un ratón.»}
{218}{}{«Quédate ahí...»}
{219}{}{}

#Re-dialogue
{220}{}{¡Por favor, no me dejes aquí!}
{221}{}{«¡Por favor, no te vayas!»}
{222}{}{«No puedo dejarte aquí. Ven conmigo...»}
{223}{}{«Espérame ahí y no hagas ruido.»}
{224}{}{«Ya casi salimos de la cueva, vamos.»}

{230}{}{«Tengo que hacerte unas cuantas preguntas.»}
{231}{}{Sigo un poco aturdida como para hablar... Lo siento.}
{232}{}{Bueno, no era lo que esperaba. Entonces, no hagas ruido.}
{233}{}{«¿Qué, ahora?»}
{234}{}{«Bien, hablemos en otro momento.»}
{235}{}{«¿Quién eres?»}
{236}{}{«Me llamo Gloria.»}
{237}{}{«¿De dónde eres?»}
{238}{}{«Soy de un pueblito pesquero, junto a la costa. Se llama San Felipe.»}
{239}{}{«¿Cómo acabaste aquí adentro?»}
{240}{}{«Andaba caminando en la costa, cuando un monstruo saltó de un bote antiguo. Y creo que me desmayé y desperté acá adentro. Parece que los monstruos me arrastraron aquí... ¡Dios mío, qué pesadilla!»}
{241}{}{«¿Qué sabes de estos monstruos?»}
{242}{}{«Son criaturas horribles, de verdad me dan miedo. ¿La naturaleza habrá creado cosas así? ¡No, es porque ellos vienen del infierno! ¡No me sorprende que apesten a muerte y a podrido!»}
{243}{}{«Sí, huelen realmente mal.»}
{244}{}{«Pienso que el olor viene de esas bolsas de cuero en sus cuerpos. ¿Quizás por eso flotan? ¡Claro, debería tirarles fuego y ver qué pasa!»}
{245}{}{«Bien pensado, un lanzallamas sería de ayuda.»}
{246}{}{«Eso me suena a gas metano.»}
{247}{}{«Vaya, eso es una palabra muy complicada. No sé lo que signifique. Pero parece que usan el aire en sus bolsas para flotar. ¡Ojalá pudiera tirarles fuego y ver qué pasa!»}
{248}{}{«Tienes razón, un lanzallamas nos vendría bien.»}
{249}{}{«¿De dónde eres, Gloria?»}
{250}{}{«Eso es todo lo que quería saber.»}
{251}{}{«Andaba caminando en la costa, cuando un monstruo saltó de un bote antiguo. Y creo que me desmayé y desperté acá adentro. Parece que los monstruos me arrastraron aquí... Dios, ¡incluso también habían cadáveres de algunas personas!»}

// added for Espanol Trait handling - cambragol

{314}{}{Em... Sí, nos vemos en la aldea.}

{418}{}{Sígueme.}
{422}{}{No podemos quedarnos aquí. Sígueme.}
{423}{}{Quédate aquí y no hagas ruido.}
{424}{}{Pronto saldremos de la cueva, vamos.}
{430}{}{Necesito hacerte unas preguntas.}
