{100}{}{Ves a un explorador de San Felipe.}
{101}{}{Ves a uno de los aldeanos de San Felipe. Debes escoltarlo a la fuente de agua.}
{102}{}{«¡Ya tenemos agua limpia! Deberías contárselo a Cesareo.»}
{103}{}{¡Olé! Cuéntale esto a Cesareo.}

{110}{}{«Oye, ¡resulta que no andamos solos!»}
{111}{}{«Verga... Salvajes. ¡Ya se apropiaron de este lugar!»}
{112}{}{«Los salvajes se apoderaron de la fuente de agua, no podemos hacerles frente.»}
{113}{}{«En toda el área, esta es la única fuente de agua limpia.»}
{114}{}{«No nos la van a dar. ¿Qué vamos a hacer ahora?»}

{120}{}{¡Salvajes!}
