{110}{}{Ves el cadáver de un jovencito. Si lo inspeccionas más de cerca, quizás puedas determinar de qué murió.}
{111}{}{Es difícil hacer eso durante el combate.}

{200}{}{Ves el cadáver de un adolescente. Parece que ha estado ahí por un buen rato.}
{201}{}{Pobre tipo, ¿qué te habrá pasado?}
{202}{}{Se te acabó la suerte, pequeñín.}
{203}{}{Parece haber muerto por estrangulación. Los moretones del cuello sugieren uso de una cuerda, además de que ya hay un flujo de deposiciones entre sus pantalones. Puedes deducir que intentó liberarse, por señales en la arena.}
{204}{}{Alguien lo mató, los pescadores deberían enterarse de ésto.}
{205}{}{Deja el cadáver en paz.}