{110}{}{En este momento, el bote solo es adecuado para navegar al fondo del mar. El casco necesita ser reparado y el motor necesita energía.}
{111}{}{El motor no arranca. El medidor indica que la célula de energía está agotada.}
{112}{}{}
{113}{}{Arreglaste las grietas y agujeros en el casco.}
{114}{}{La célula ha sido recargada. Hay suficiente energía para una ida y vuelta.}
{115}{}{La célula ya fue recargada.}
{116}{}{Ya no tienes ningún lugar a donde ir.}
{117}{}{El bote no puede resistir tanto peso. Vacía todo lo innecesario de tu inventario.}
{118}{}{Puedes llevar el bote de vuelta a la costa. Utiliza la habilidad de Ciencia para regresar.}
{119}{}{Este bote tiene suficiente combustible para regresar a la costa.}

{200}{}{El bote está listo para partir.}
{201}{}{De momento, se ha cancelado el viaje por bote.}
{202}{}{Ve a la plataforma petrolífera.}
{203}{}{Ve a Puerto Peñasco.}
{204}{}{Ve al asentamiento cerca del Faro de San Felipe.}
{205}{}{Regresa hacia El Faro.}
{206}{}{Regresa hacia El Faro.}
