{100}{}{Ves a Thelma.}
{101}{}{Ves a una joven de expresión melancólica.}
{102}{}{Es bueno verte.}
{103}{}{¡Hay demonios por todos lados! ¿Acaso se trata de un apocalipsis zombi?}

#First dialogue
{200}{}{Hola, ¿eres un viajero? No te había visto antes. Me llamo Thelma Ferrino. ¿Cómo estás?}
{1200}{}{Hola, ¿eres una viajera? No te había visto antes. Me llamo Thelma Ferrino. ¿Cómo estás?}
{201}{}{Estoy bien. ¿Qué hay de ti?}
{202}{}{He estado mejor, pero gracias por preguntar.}
{1202}{}{He estado mejor, pero gracias por preguntar.}
{203}{}{¿Por qué lo preguntas?}
{204}{}{Bueno, sólo quería conocerte. Apenas vienen a visitarnos, más aún por lo que está pasando. Antes teníamos muchos más visitantes.}
{205}{}{Pero, ¿qué pasó?}
{206}{}{¿Qué tal si me invitas un trago? Así te lo cuento.}
{207}{}{Está bien, iré por algo.}
{208}{}{Beber es malo, señorita. Adiós.}
{209}{}{Toma, son 5 chapas. Ve a comprarla tú.}
{210}{}{¡Muchas gracias!}
{211}{}{Dime lo que está pasando.}
{212}{}{Bueno, ya compartiste una copa conmigo. Creo que te la debo.}
{1212}{}{Bueno, ya compartiste una copa conmigo. Creo que te la debo.}
{213}{}{Sigues aquí... Parece que te gusta el pueblo. ¿Hablamos?}
{214}{}{¿Qué puedes contarme acerca de este lugar?}
{215}{}{¿Qué está pasando aquí, y por qué estás tan triste?}

{220}{}{Es todo culpa de esa maldita... 'plataforma' que está en el mar. Desde siempre que ha estado ahí, incluso los pescadores descansaban en ella mientras pescaban. Era así, hasta que la invadieron unos... monstruos. Y hace un tiempo, la plataforma empezó a derramar un moco venenoso. Seguro que eso ya mató a la mitad del mar.}
{221}{}{¿Y por qué te enoja tanto?}
{222}{}{Bueno, no es que me enoje. Verás, cuando no pudimos soportarlo más, mi papá y otros pescadores fueron a la plataforma. Ellos sabían lo peligroso que era, pero había que lidiar con ello.}
{223}{}{¿Qué ocurrió?}
{224}{}{Los miré a través de mis binoculares. Vi como entraron, pero no hemos vuelto a saber de ellos. Creo que ya deben de haber... muerto. (bebe directo de la botella y se traga la mitad)}
{225}{}{Lo siento mucho. ¿Amabas mucho a tu papá?}
{226}{}{Bueno, era mi papá. Y yo... las cosas serán difíciles sin él. Me haría muy feliz que alguien me traiga sus cosas, como recuerdo.}
{227}{}{No creo que me suba a esa plataforma en mi vida. Lo siento, pero se lo estás pidiendo a la persona equivocada.}
{228}{}{Lo tendré en cuenta. Ánimo, Thelma.}
{229}{}{}

{230}{}{¿Fuiste tú el que incendió la plataforma, verdad? ¡Eso fue genial!}
{1230}{}{¿Fuiste tú la que incendió la plataforma, verdad? ¡Eso fue genial!}
{231}{}{Sí, yo lo hice. El petróleo ya no será ningún problema, los 'nómadas' tampoco.}
{232}{}{Te lo agradezco de corazón. De casualidad, ¿encontraste los cadáveres de los aldeanos? Mi papá era uno de ellos.}
{233}{}{No, lo siento. Lo más seguro es que los nómadas se los comieron.}
{234}{}{Era... de esperarse. Eso está bien. Tengo que superarlo, debo pensar en otras cosas. Hay mucho trabajo por delante...}
{235}{}{Eso es cierto.}
{236}{}{Sólo encontré estas chapas de identificación entre unos huesos.}
{237}{}{¡Es su chapa! Muchísimas gracias, no sabes cuánto lo aprecio.}
{238}{}{De nada.}
{239}{}{No tan rápido. Lo normal es dar algo a cambio por tales cosas.}
{240}{}{No pensé que dirías eso. Así que nos ayudaste porque querías dinero... Genial. Llévate mis cien chapas, son lo último que tengo. ¿Suficiente?}
{1240}{}{No pensé que dirías eso. Así que nos ayudaste porque querías dinero... Genial. Llévate mis cien chapas, son lo último que tengo. ¿Suficiente?}
{241}{}{Suficiente. Adiós.}
{242}{}{Encontré una chapa de identificación entre un montón de huesos. Creo que le pertenecía a tu papá.}
{243}{}{Resulta que estaba en la plataforma y encontré esta chapa de identificación. Tiene tu apellido.}
{1243}{}{Resulta que estaba en la plataforma y encontré esta chapa de identificación. Tiene tu apellido.}

{250}{}{Hola.}
{251}{}{Adiós.}
{252}{}{Hola. ¿Cómo estás?}
