{101}{}{Ves a un niño tribal de pelo largo y negro.}
{102}{}{¡No me empujes!}
{103}{}{¡Corran! ¡Es el espíritu de metal!}
{104}{}{No eres como los demás, tú eres un buen hombre. Gracias.}
{1104}{}{No eres como los demás, tú eres una buena mujer. Gracias.}

{110}{}{¡Shh!}
{111}{}{¡Cállate! Nos escuchará...}
{112}{}{¿En serio ser mejor callarse?}
{113}{}{Tú hablar más bajo.}
{114}{}{Mangas no deber enterarse de esto.}
{115}{}{¿Deberíamos pedir ayuda?}
{116}{}{No poder hacer eso solos.}
{117}{}{¿Qué hacer nosotros?}
{118}{}{Jamás volveré a bajar.}
{119}{}{ }

{200}{}{"...No, tú no poder decirles, ¡tribu entera nos odiará!" - "¿Tú tener mejor idea? ¡Ellos morirán abajo!" - "Sí, ellos ya estar muertos, ¡tonto!" - "Yo no volver a bajar, tener que avisar..."}
{201}{}{Hola, niños. Los escuché hablar, ¿pasó algo?}
{1201}{}{Hola, niños. Los escuché hablar, ¿pasó algo?}
{202}{}{(uno de los niños se te acerca con temor)  "¿Por qué importarte? ¡Tú no ser de acá!" - (los demás lo agarran y te piden una disculpa) "Calmarte, tonto, quizás él poder ayuda. ¿O tu hablar con chamán?" - "No, chamán castigarnos." - "Ser lo mismo..."}
{1202}{}{(uno de los niños se te acerca con temor)  "¿Por qué importarte? ¡Tú no ser de acá!" - (los demás lo agarran y te piden una disculpa) "Calmarte, tonto, quizás ella poder ayuda. ¿O tu hablar con chamán?" - "No, chamán castigarnos." - "Ser lo mismo..."}
{203}{}{Cuéntenme lo que pasó.}
{204}{}{¿Tú prometer no hablar de esto? Nosotros entrar a Ciudad Enterrada, estar a oeste de aquí, lugar en donde arena cubrir viejo pueblo. Nosotros escuchar gruñido en ca... Catacumbas, ¡y nosotros correr!}
{205}{}{Hicieron lo correcto, niños.}
{206}{}{Ustedes son unas gallinas.}
{207}{}{Pero dos de nosotros no volver.}
{208}{}{¡Idiotas!}
{209}{}{Pobrecitos, cálmense, ya pasó.}
{210}{}{Esto es algo muy serio.}
{211}{}{¿Seguirán vivos?}
{212}{}{¿Por qué tanto secreto? ¿Por qué no decirle a los mayores?}
{213}{}{Nosotros... nosotros tener prohibido bajar a catacumbas... Muchos decir que espíritu malo vivir ahí, haber derrumbes, todo eso. Pero ser muy interesante, no aguantarnos.}
{214}{}{Tengo que prepararme y llevar mi mejor... eh, lanza. No se muevan.}
{215}{}{Llévame a las catacumbas.}

{220}{}{Gracias. Ahora nosotros obedecer a mayores.}
{221}{}{Así es. No hicieron caso y casi muere alguien. Jamás olviden esta lección.}
{222}{}{No es necesario que hagas caso a *todo* lo que dicen. Adiós, niños.}