{100}{}{Ves a una mujer.}
{101}{}{Ves a una de las mujeres de la tribu. Está cocinando.}

{210}{}{¿Qué quieres?}
{211}{}{Te doy la bienvenida, todos te vemos como ejemplo a seguir.}
{212}{}{¿Estás invitado?}
{213}{}{Adiós.}

{220}{}{¿Qué huele así?}
{221}{}{Cocino unas salchichas de brahmán. ¡Quita las manos! Ni siquiera te dejaré lamer el plato. ¡Fuera!}
{222}{}{Ya, ya.}
{223}{}{Estoy haciendo salchichas de brahmán. Son mi comida favorita, pero es difícil encontrar los condimentos.}
{224}{}{¡Huele delicioso! ¿Puedo probarlas?}
{225}{}{Vaya tufo. ¿Siquiera es comestible?}
{226}{}{Nuestro héroe debería estar bien alimentado. Ten, come.}
{1226}{}{Nuestra heroína debería estar bien alimentada. Ten, come.}
{227}{}{Muchas gracias.}
