{100}{}{Ves a Lozen.}
{101}{}{Ves a una anciana vestida de forma extraña para su tribu. Está hablando en voz baja, posiblemente esté conjurando un hechizo.}

{200}{}{Sabía que vendrías aquí. Los espíritus me contaron acerca de tu triste historia.}
{201}{}{¿Cómo lo sabes?}
{202}{}{Veo muchas cosas, la sangre de un animal sagrado lo muestra todo. Soy Lozen, vidente del destino.}
{203}{}{¿La sangre de brahmán te muestra el futuro o algo así?}
{204}{}{Puedo ver como fluyen los ríos del tiempo, pasado y futuro. Llámalo como quieras. Enséñame tus manos, y leeré tu destino.}
{205}{}{Eh, no gracias.}
{206}{}{Claro, aquí tienes.}
{207}{}{Hmm... se avecina una gran tormenta, y te veo en su centro. Para ver más, tengo que hacer el ritual completo.}
{208}{}{Quizás otro día.}
{209}{}{Muy bien, acepto. ¿Qué necesitas para el ritual?}
{210}{}{Un sacrificio, algo que aprecies. Las chapas funcionan. Es únicamente en la pérdida que se aprecia la vida.}
{211}{}{Aquí tienes 100 chapas. ¡Quiero saberlo todo!}
{212}{}{En otra ocasión.}
{213}{}{(lleva a cabo un complicado ritual con la sangre de un animal sagrado) Um-mm... Um-mm... Los espíritus hablan... Sí...}
{214}{}{¿Qué es lo que ves?}
{215}{}{Veo guerreros estrellados... otros que crean fuego con solo pensarlo, están luchando. Estás entre ambos, en medio de la batalla...}
{216}{}{Eso no suena bien.}
{217}{}{¡Pero no temas! El Brahmán Divino no dejará que mueras en esta pelea. El destino te ha hecho un sendero, ¡no te alejes de él! ¡Te espera una gran misión!}
{218}{}{Eso fue intenso, pero, ¿cómo voy a interpretar todo esto?}
{219}{}{¡Mentirosa! Eso no puede ser una visión del futuro.}
{220}{}{¡Escúchame! El Brahmán Divino otorga visiones, no órdenes. Debes entenderlas. Quizás no fue el momento adecuado. Cuando tu corazón y tu menté estén de acuerdo, lo verás todo.}
{221}{}{Esto fue un desperdicio de dinero. Adiós.}
{1221}{}{Esto fue un desperdicio de dinero. Adiós.}
{222}{}{Gracias, Lozen. Tus palabras me inspiran.}
{223}{}{Has vuelto, veo que sigues pensando en tu destino. ¿Quieres verlo otra vez?}
{1223}{}{Has vuelto, veo que sigues pensando en tu destino. ¿Quieres verlo otra vez?}
{224}{}{No gracias.}
{225}{}{No.}
{226}{}{Qué extraño, los espíritus no tienen nada qué decir sobre tu futuro. Tal vez, todo lo que haya importado, ya ha sucedido.}
{227}{}{¡Ah!}

{230}{}{¿Sí?}
{231}{}{¿Hm?}
{232}{}{[Entrégale 100 chapas]}
{233}{}{[Más]}
{234}{}{¡Ja!}
{235}{}{Shoo.}
{236}{}{}


{240}{}{No tengo nada más que contarte.}
{241}{}{De acuerdo, adiós.}
{242}{}{Pero, ¿qué significaba la visión?}
{243}{}{¿Qué le pasó al brahmán cuya sangre utilizaste?}
{244}{}{Era un animal sagrado. Genaro lo preparó para el Día del Sol. En ese día, la bestia es sacrificada, y con su sangre sagrada, nos lavamos nuestros fracasos y vergüenzas. Yo uso la sangre para ver futuros y compartirlos con nuestra gente.}
{245}{}{¿Qué es el Día del Sol?}
{246}{}{Cuando el desierto de Sonora está cercado por tormentas de arena, los brahmanes no pueden pastorear. Nos quedamos en el pueblo hasta que acabe. Durante esos días escasea la comida, y le agradecemos al Brahmán Divino.}
{247}{}{¿Por qué es sagrado? ¿Qué lo hace distinto?}
{248}{}{Es un brahmán de mucha fuerza. Genaro lo mantiene apartado en un corral para que esté seguro, hasta el Día del Sol. Si fallece o enferma, sería una tragedia.}
{249}{}{¿No sientes pena por el brahmán?}
{250}{}{Nuestro futuro ya está aquí. Y eso no puede cambiarse.}
{251}{}{Y, ¿qué hay de tu tribu? ¿Qué les espera en el futuro?}
{252}{}{Estamos al borde del abismo, cubiertos de niebla. El futuro no está claro.}
{253}{}{Intrigante.}
