{100}{}{Ves a Mangas, el anciano tribal.}
{101}{}{Ves a un chamán con atuendo tradicional.}
{102}{}{¡Miren! Ahí está, ¡el espíritu metálico maligno! ¿Ahora me creen?}
{103}{}{¡El viejo Mangas ha perdido la cabeza por completo!}

#Floating phrases in the square
{110}{}{¡Expulsen a los forasteros!}
{111}{}{¡Los forasteros dividen nuestra tribu!}
{112}{}{¡Miren lo que estos forasteros le hacen a nuestra comunidad!}
{113}{}{¡No mantuvimos nuestras tradiciones durante generaciones para que forasteros las destruyan!}
{114}{}{Ahora, hasta entre nosotros hay discordia. ¿A dónde nos llevará esto?}
{115}{}{La tribu vuelve al camino de la hostilidad. ¡Y todo por culpa de Fénix!}
{116}{}{Estábamos unidos, ¡pero Fénix nos enseñó a pelear por tonterías!}
{117}{}{Miren a Chatto y sus amigos. ¡Perdieron su camino!}
{118}{}{Los caravaneros le enseñaron a leer a Chatto. ¿Qué sigue?}
{119}{}{¡Esto solo empeorará! Fénix no compartirá el yermo. ¡Aaron lo quiere todo para él!}
{120}{}{Por culpa de los misioneros, ni siquiera podemos pastar a los brahmanes en el yermo.}
{121}{}{¡Traigan todas las cosas paganas aquí! ¡Quémenlas! ¡Quémenlas!}
{122}{}{Miren estos libros y tecnologías: ¿para qué las necesitamos?}
{123}{}{¡Fénix solo trae mentiras!}
{124}{}{¡No caigan en los trucos de los misioneros!}
{125}{}{¡Tápense los oídos cuando los misioneros intenten explicarles algo!}
{126}{}{¡Hemos vivido aquí por generaciones! ¡No le daremos nuestra tierra a forasteros!}

#Stop-dialogue about the bike
{200}{}{¡Miren! Esto es de lo que hablaba. Los forasteros han domado el hierro. Juegan a ser dioses, resucitan tecnologías viejas y las doblegan. ¿Qué sigue? ¿Será que tomarán nuestros cuerpos y almas?}
{201}{}{No te preocupes Es mi motocicleta, nada más, no es ninguna amenaza.}
{202}{}{¡No le crean al forastero! ¿Quién sabe qué planea alguien que va en contra la naturaleza?}
{203}{}{Tranquilo, está exagerando.}
{204}{}{Creo que fumaste la hierba equivocada, chamán.}
{205}{}{Cálmate, viejo. No te he hecho nada malo... POR AHORA.}
{1205}{}{Cálmate, viejo. No te he hecho nada malo... POR AHORA.}

#First meeting
{210}{}{...Miren, ¡miren lo que esta gente nos trajo con todo su progreso!}
{211}{}{[Escucha el discurso]}
{212}{}{[Interrumpe el discurso]}
{213}{}{Éramos un pueblo unido, ¡pero los Seguidores del Fuego nos inculcaron el egoísmo! Creíamos en un dios, ¡pero nos enseñaron a discutir por la religión! Queríamos el bien de la tribu, ¡pero los clanes vuelven a ser hostiles entre sí...!}
{214}{}{Fénix nos enseñó a comerciar los brahmanes como si fueran objetos. ¡Pero los brahmanes son sagrados! ¿Hasta cuándo dejaremos que los forasteros destruyan nuestras costumbres? ¿Cuántos conflictos más causarán con su presencia?}
{215}{}{Y ahora miren a Chatto. Aprendió a leer los textos paganos. ¡A leer! Quiere cambiar a los brahmanes por las desalmadas tecnologías. Él y sus amigos quieren vender nuestra libertad a cambio de una alianza con Fénix. ¡Quieren entregarle el pueblo a los misionarios!}
{216}{}{Miren estas cosas paganas: libros, tecnologías, sustancias dudosas y peligrosas... Siempre las hemos rechazado por esta razón, son peligrosas. Nada vale más que la vida de nuestra tribu y los brahmanes ¡Pero Chatto y los jóvenes coleccionan estos objetos! ¡El Brahmán Oscuro poseyó las mentes de la juventud!}
{217}{}{¿Y esto es nuestro futuro? ¿Cuándo caímos tan bajo que hasta los jóvenes se rebelan contra la tribu? ¡Es culpa de los misionarios! ¡Expúlsenlos de nuestro hogar! El pueblo debe seguir siendo nuestro...}
{218}{}{Ah, veo que un forastero está aquí. ¿Quién eres? ¿Qué haces aquí entre nuestra tribu?}
{1218}{}{Ah, veo que una forastera está aquí. ¿Quién eres, mujer? ¿Qué haces aquí entre nuestra tribu?}
{219}{}{Ah, veo que un Seguidor del Fuego ha venido a nuestro pueblo. ¿Qué es lo que quieres? ¿Llevarte a nuestros niños y a nuestros brahmanes? Hubieron otros además de ti y te diremos lo mismo que a ellos, ustedes han comprado a otras personas pero no pueden hacer eso con la tribu de San Brahmán. ¡Regresa a tu apestosa Fénix, forastero!}
{220}{}{En nombre de la Villa, voy a hablar con tu jefe. Nana me dejó pasar.}
{221}{}{¡Ah, Brahmán Divino de la Paz! Si Nana ha dejado pasar a un forastero, debe tener sus razones. De acuerdo, adelante. Pero que sepas que tengo un ojo de águila, nada escapa de mi vista. Voy a vigilar cada paso que des en nuestro pueblo.}
{222}{}{Gracias, Mangas. Perdona mi intrusión, por favor.}
{223}{}{La vejez te dejó loco de remate. Déjame en paz y quítate de mi camino.}
{224}{}{Nos vemos, Mangas.}
{225}{}{[Más]}

#Repeat dialogue
{230}{}{Bienvenido, forastero de la Villa.}
{1230}{}{Bienvenida, mujer de la Villa.}
{231}{}{Me preocupa que estés en las tierras de mi tribu, posees un espíritu oscuro.}
{232}{}{Nos vemos, chamán.}

{240}{}{¿Quién eres?}
{241}{}{Soy Mangas, el jefe del clan del oeste.}
{242}{}{Un gusto, Mangas.}
{1242}{}{Un gusto, Mangas.}
{243}{}{¿Eres el líder de este lugar?}
{244}{}{Con eso te refieres a Jerónimo, nuestro Gran Jefe. Él se encuentra en el Santuario. Los ancianos de cada clan se unieron aquí en San Brahmán y lo elegimos como nuestro Gran Jefe.}
{245}{}{¿Y entonces por qué estás aquí y no en el oeste?}
{246}{}{Nuestra lucha contra Fénix obligó a toda la tribu a reunirse en San Brahmán para defender nuestra libertad y tradiciones. Además, este pueblo siempre ha sido un refugio de temporada en contra de las sequías y las tormentas de polvo.}
{247}{}{¿Ustedes construyeron este pueblo? Se ve muy viejo.}
{248}{}{Estas ruinas han estado aquí desde que tengo memoria. A través de muchas generaciones han sido cubiertas por la arena y nadie sabe qué solía ser este lugar. Ahora es nuestro campamento principal.}
{249}{}{De acuerdo, hablaremos de esto después.}

{250}{}{¿Qué está pasando aquí?}
{251}{}{Chatto y los demás chicos han recolectado una variedad de objetos prohibidos. Los he encontrado y los haré arder para que los demás no caigan en sus hechizos. No te atrevas a traer más de estos objetos. No es asunto tuyo, forastero de la Villa.}
{1251}{}{Chatto y los demás chicos han recolectado una variedad de objetos prohibidos. Los he encontrado y los haré arder para que los demás no caigan en sus hechizos. No te atrevas a traer más de estos objetos. No es asunto tuyo, forastera de la Villa.}
{252}{}{Ya veo.}
{253}{}{Pero, ¿qué hay de malo con estas cosas viejas?}
{254}{}{Vagamos por el desierto y nos sustentamos con lo que nos entrega. Nuestro pueblo y rebaño son lo único que tiene valor. La juventud no tiene nada que hacer con los objetos del Viejo Mundo, son inútiles y para nada seguros.}
{255}{}{Ya veo. ¿Podrías entregarme esas cosas, entonces?}
{256}{}{Eso es un montón de idioteces. Sólo son cosas viejas que te encontrarías en cualquier ruina.}
{257}{}{¡Pero no vivimos en esas ruinas! Vagamos por el desierto de Sonora y para nosotros, nuestro pueblo y rebaño son lo único que tiene valor. La juventud no tiene por qué tener objetos del Viejo Mundo, no son seguros.}
{258}{}{Entiendo. ¿Y si hacemos un trato? Podría llevarlas de vuelta a las ruinas.}
{259}{}{Estás haciendo lo correcto. La Villa necesita más gente como tú, chamán. Mis respetos.}
{260}{}{Hmm. Si de verdad eres de aquella Villa de la que he escuchado, entonces puede que deba tratarte con una voluntad más buena. Quizás nuestras tribus tengan algo en común.}
{261}{}{No quemes estas cosas, ¿qué tal si hacemos un trueque y me las llevo yo?}
{262}{}{No me importa qué ocurra con los objetos prohibidos, es mucho más importante castigar a los disidentes y mostrarle la verdad a los demás. Pero, si tienes algo que ofrecerme, podemos hacer un trueque.}
{263}{}{Creo que podemos hacer un trato.}
{264}{}{Estas cosas sí son muy peligrosas.}
{265}{}{¡Eso es justo de lo que hablaba! Las pertenencias de los forasteros traen la pestilencia, la discordia o la muerte.}
{266}{}{¡Quémalo todo! ¡De inmediato! Especialmente esa cosa. [Apunta a la granada]}
{267}{}{Estás haciendo lo que es correcto para tu tribu.}
{268}{}{¿Quieres hacer un trueque? Quizás pueda darte algo útil a cambio.}
{269}{}{¡Mira, esa cosa está repleta de un poder demoníaco! ¡Destrúyela, ahora! [Lanza la granada al fuego]}

{270}{}{¿De qué se trata el conflicto con los misionarios?}
{271}{}{Ellos traen la discordia y la división a nuestra tribu. Sus tecnologías no poseen alma y van en contra de nuestras tradiciones. Y con sus armas, los forasteros intentarán conquistarnos para obligarnos a trabajar. Incluso nuestra tribu ha hecho del aguardiente una razón por la cual pelearse.}
{272}{}{Comprendo. ¿Te puedo preguntar otra cosa?}
{273}{}{¿Discordia y división? ¿Dentro de la tribu?}
{274}{}{Los misionarios de Fénix quieren una alianza y su propio lugar junto al pueblo. Chatto y la juventud se han hecho sus ecos, mientras que otros, como yo, buscan expulsarlos de aquí.}
{275}{}{¿Con qué clase de armamento cuentan los misionarios?}
{276}{}{Los misionarios poseen armas de fuego y poderosas armaduras de metal. Contra tal enemigo, no podemos resistirnos con nuestras lanzas. Sólo podemos usar nuestra astucia y nuestro conocimiento del yermo para luchar contra un enemigo tan poderoso.}
{277}{}{¿De qué son esas tecnologías desalmadas a las que te refieres?}
{278}{}{Me refiero a las cosas viejas cuyo poder absorben de otras cosas viejas. Ustedes las llaman 'bat-terías' y 'rad-dia-ción'. Durante mucho tiempo, no había nadie en la tribu que se atreviera a tocar estas cosas. Y ahora, en Fénix y Two-Sun son capaces de hacerlas con tanta facilidad y habilidad como nosotros podemos producir nuestras bolsas de cuero de brahmán.}
{279}{}{¿Qué hay del aguardiente?}
{280}{}{Es un líquido amargo y apestoso que nos llegó desde Fénix, le dicen 'tequila'. Puede nublar las mentes, igual que el Brahmán Oscuro y aquellos que lo beben hacen cosas extrañas. Intento quemar todo el 'tequila' que encuentre, pero es inútil. Mientras Fénix haga y le venda esta bebida a la tribu, su maldad jamás se disipará.}
{281}{}{En Fénix, debe haber una... fábrica o algo así, allí se debe estar haciendo el tequila.}
{282}{}{Sí, y hace mucho que he querido hallar una persona que pueda encontrar y destruir ese lugar... esa 'fábrica'. Si no hay aguardiente, será más fácil que nuestra tribu se resista a los forasteros. Cuando encuentres ese lugar, debes destruirlo y tu recompensa será generosa.}
{283}{}{De acuerdo, lo haré.}
{284}{}{Le ofreceré sacrificios al Brahmán Divino para que te guíe y proteja durante tus viajes. Te deseo suerte.}
{1284}{}{Le ofreceré sacrificios al Brahmán Divino para que te guíe y proteja durante tus viajes. Te deseo suerte.}
{285}{}{Adiós, Mangas.}
{286}{}{Espera, te quiero hacer otra pregunta.}
{287}{}{Ese lugar debe tener muchos guardias y ni siquiera sé en dónde está. No, no me meteré en esto.}
{288}{}{Entonces vete. Nos haces perder el tiempo.}

{290}{}{¡Te traigo buenas noticias, Mangas! La producción de tequila en Fénix fue destruida por completo.}
{291}{}{El Brahmán Divino tuvo que haberte ayudado con esta tarea, no tuvo que haber sido fácil. Ahora lo entiendo, te había juzgado mal, no todos los forasteros buscan conquistarnos o robarnos. Te lo agradezco, campesino.}
{1291}{}{El Brahmán Divino tuvo que haberte ayudado con esta tarea, no tuvo que haber sido fácil. Ahora lo entiendo, te había juzgado mal, no todos los forasteros buscan conquistarnos o robarnos. Te lo agradezco, campesina.}
{292}{}{De nada.}
{293}{}{Habías mencionado que me darías una recompensa.}
{294}{}{Te mereces respeto y una recompensa. Te entrego estas cosas, se las quité a algunos miembros de la tribu que se alejaban del camino. Estoy seguro de que les encontrarás un uso.}
{295}{}{Bueno, bueno, baterías nucleares, estimulantes, RadAway y un montón de chapas... Nada mal.}

{300}{}{¿...Y este es nuestro futuro? ¿Cuándo caímos tan bajo que hasta la juventud está en contra de la tribu? Esto es culpa de los misionarios de Fénix...}
{301}{}{Es demasiado tarde para hablar sobre la libertad, Mangas. El jefe hizo una alianza con Fénix, acéptalo.}
{302}{}{Mis ojos se llenan de tristeza mientras veo el futuro de nuestra tribu, es un destino nublado. Somos como un brahmán perdido que se separó del rebaño. Esto es triste. Muy triste.}
{303}{}{Ajá. Adiós.}

{310}{}{Quiero que apoyes una alianza con los misionarios de Fénix.}
{311}{}{Debes de haber quebrado tu mente, campesino. Hago el intento de expulsar a los forasteros de nuestras tierras usando hechizos y limpiando las mentes de la tribu. Y me pides que me detenga y me arrodille ante la voluntad del Brahmán del Destino.}
{312}{}{Exacto.}
{313}{}{Pensándolo bien, esto es una locura. Tienes razón.}
{314}{}{¿Qué te pasa, campesino? Parece que tu aldea y nuestra tribu están en el sendero de la guerra. ¿O me equivoco?}
{1314}{}{¿Qué te pasa, campesino? Parece que tu aldea y nuestra tribu están en el sendero de la guerra. ¿O me equivoco?}
{315}{}{Mangas, estás desconectado de la realidad. El mundo está cambiando y ya no podemos vivir como antes.}
{316}{}{Se ha caído tu máscara, forastero. Si tu tribu es así de débil, que así sea. ¡Pero NUESTRA tribu jamás se arrodillará ante Fénix!}
{317}{}{Lo harás. Recuerda mis palabras.}
{318}{}{Sabes lo que haces, supongo. Yo me voy.}
{319}{}{Mangas, la verdad es que estás desconectado de la realidad. El mundo exige cambios. Si eso no ocurre, la tribu será borrada de la faz de la tierra.}
{320}{}{Tus palabras son poderosas, hace que mis rodillas tiemblen de miedo. Pero si nos doblegamos ante el Nuevo Mundo, vamos a desaparecer de todas formas. ¿No es así?}
{321}{}{Has una alianza con Fénix y podrás preservar tus tradiciones. Quédate con los Rangers y te condenarás a una guerra que acabará en una derrota total.}
{322}{}{No lo sé, deberías decidirlo tú. Adiós.}
{323}{}{La tribu aún puede resistirse ante los misionarios y saqueadores. Pero ellos se hacen más fuertes y nos oprimen más y más. Incluso unidos, la tribu apenas consigue controlar a San Brahmán.}
{324}{}{Que así sea. Para salvar a mi tribu, apoyaré la alianza. Pero también voy a mantener nuestra alianza con los Rangers. Si Fénix llega a ser una amenaza, quebraremos todo acuerdo que haya con ellos.}
{325}{}{Has tomado una decisión razonable.}
{326}{}{No tienes otra opción, Fénix ganará de todas formas.}
{327}{}{Confía en mí. Los Rangers no son tus amigos y Fénix ganará de todas formas. Debes hacerlo o tú, y tú gente, morirán entre las arenas.}
{328}{}{Entre más escucho tus palabras, me pongo más y más desesperanzado... ¿Tan mal están las cosas que hasta la Villa está lista para arrodillarse ante Fénix? Entonces no hay ninguna otra opción.}
{329}{}{Ni siquiera yo lo sé, Mangas... Tengo que pensar.}
{330}{}{Por supuesto. Hasta que me hagas cambiar de parecer, apoyaré una alianza con los Rangers. Ellos quieren el bien para nosotros.}
{331}{}{De acuerdo. Adiós.}
{332}{}{¿Qué tal si te traigo evidencia de su traición?}
{333}{}{Bueno, te escucharé. Pero no te atrevas a engañarme.}
{334}{}{Está bien. Adiós.}
{335}{}{Los Rangers fueron derrotados, su presa fue destruida.}
{336}{}{¡Oh! ¡Por qué debe ser tan cruel el Brahmán del Destino!}
{337}{}{Ahora mismos están ocupados con su propia supervivencia, no creo que puedan serte de mucha ayuda.}
{338}{}{Los Rangers ya destruyeron la tribu de los Chacales, puede que tú sigas.}
{339}{}{¿Se destruyó a toda una tribu? ¡Oh! ¡Por qué debe ser tan cruel el Brahmán del Destino!}
{340}{}{Estos tipos son duros, ustedes no son nada más que unos salvajes para ellos.}
{341}{}{Una caravana de colonos que no querían problemas pasaron por tu territorio para llegar a Ciudad Garaje. Fueron asaltados por los Rangers.}
{342}{}{¡El Brahmán del Destino siempre tiene cosas tan extrañas que mostrarnos!}
{343}{}{Los colonos simplemente se negaron a darles lo que exigían, le hacen esto a cualquiera que no se doblegue ante ellos.}
