{100}{}{Ves a un cazador tribal.}
{101}{}{Ves a uno de los cazadores de la tribu. No usa más que una toga.}
{102}{}{Eres un amigo para la tribu, gracias. Todavía hay gente buena en el yermo.}
{103}{}{Gracias por ayudarnos en el oasis, parece que en un interior hay un buen espíritu.}

#Before receiving the quest
{200}{}{Saludos, forastero. Puedes entrar a nuestro campamento, pero dudo que nos seas de ayuda.}
{1200}{}{Saludos, forastera. Puedes entrar a nuestro campamento, pero dudo que nos seas de ayuda.}
{201}{}{¿Por qué?}
{202}{}{Gracias a los misionarios y los ladrones de brahmanes, hemos perdido la confianza en los desconocidos.}
{203}{}{Lo entiendo, pero te lo prometo, no quiero hacerte mal y tampoco busco hacerte problemas.}
{204}{}{Ya no podemos confiar en un forastero. Aún así, tus palabras me convencen.}
{205}{}{Ojalá que podamos llevarnos bien.}
{206}{}{Pero no he hecho nada y ya desconfías de mí.}
{1206}{}{Pero no he hecho nada y ya desconfías de mí.}
{207}{}{Eso no es sabio de tu parte. No deberías abusar de nosotros.}
{208}{}{No me importa, sólo vengo de visita.}
{209}{}{Lo siento, no era lo que quería decir.}

{220}{}{¿Qué necesitas, forastero?}
{1220}{}{¿Qué necesitas, mujer?}
{221}{}{¿Qué quieres, campesino?}
{1221}{}{¿Qué quieres, campesina?}
{222}{}{Es bueno verte, amigo mío.}
{1222}{}{Es bueno verte, amiga mía.}
{223}{}{No necesito nada. Adiós.}

{230}{}{¿Qué haces aquí?}
{231}{}{Los ancianos nos reunieron en el pueblo para luchar contra los forasteros. Me parece una tontería.}
{232}{}{¿Por qué?}
{233}{}{Hay pocos cazadores que vigilan el desierto. Al volver de un oasis, me encontré con un montón de escorpiones. Los pastores no pueden usar el agua.}
{234}{}{Eso es muy malo... ¿Qué se puede hacer?}
{235}{}{¿Le has contado esto a alguien más?}
{236}{}{Quiero reunir guerreros para deshacerme de los monstruos. Pero el líder nos prohibió dejar el pueblo a no ser sea necesario.}
{237}{}{Creo que los escorpiones se irán por sí mismos. Igual que yo.}
{238}{}{Eso no suena bien. Quizás pueda ayudarte.}
{239}{}{¿Te podrás encargar de un montón de escorpiones? No será fácil.}
{240}{}{Sabes, ni siquiera me metería con un escorpioncito. Hazlo sólo.}
{241}{}{Ya se me ocurrirá algo, llévame.}

{250}{}{He acabado con los escorpiones del oasis.}
{1250}{}{He acabado con los escorpiones del oasis.}
{251}{}{¡Alabado sea el Brahmán Divino! Has ayudado a todos nuestros pastores, el oasis era vital para ellos. Gracias, eres un verdadero aliado para nuestra tribu.}
{252}{}{De nada.}
