{100}{}{Ves a George Crook.}
{101}{}{Ves a un hombre con un gran bigote y mirada decidida.}
{102}{}{Muy bien. Ahora ve y extermina a los salvajes. Entiendes las órdenes, ¿cierto, robot?}
{103}{}{Cuídate. Tal vez nos veamos de nuevo.}
{104}{}{Tendré que volver a Fénix. Dios sabe que hice todo lo que pude.}

#First meeting
{200}{}{Alto. ¿Qué haces aquí?}
{201}{}{No lo sé. Solo estoy explorando la zona.}
{202}{}{No me subestimes, sé bien cuando un paleto me anda mintiendo. Está claro que no eres de Fénix, así que eres del yermo. ¿De dónde? Responde.}
{203}{}{No tengo por qué decírtelo.}
{1203}{}{No tengo por qué decírtelo.}
{204}{}{Bueno, bueno. Acá tenemos a un campesino orgulloso e inflexible. ¿Crees que tienes razón? ¡Pronto el yermo entero se arrastrará bajo la suela de Aaron! Y ahí veremos hasta dónde llega tu orgullo.}
{1204}{}{Bueno, bueno. Acá tenemos a una campesina orgullosa e inflexible. ¿Crees que tienes razón? ¡Pronto el yermo entero se arrastrará bajo la suela de Aaron! Y ahí veremos hasta dónde llega tu orgullo.}
{205}{}{¿En serio?}
{206}{}{Tú, campesino, te arrodillarás como todos los demás. Lo entenderás pronto. Por el momento, te daré una oportunidad: vuelve al yermo y cuéntale a todos la grandeza del ejército de Fénix.}
{1206}{}{Tú, campesina, te arrodillarás como todos los demás. Lo entenderás pronto. Por el momento, te daré una oportunidad: vuelve al yermo y cuéntale a todos la grandeza del ejército de Fénix.}
{207}{}{Me voy.}
{208}{}{Tengo preguntas y no me iré sin respuestas.}
{209}{}{Aaron me envió aquí para ayudarte. Aquí está su orden, está sellada.}
{210}{}{Mi aldea está vacía, así que voy a donde el destino me lleve.}
{211}{}{Pues escucha, pequeñín: ve a Fénix. En el desierto no tienes ningún futuro, pero en la gran ciudad hay muchas oportunidades. Solo no elijas las equivocadas. Ya me entiendes.}
{212}{}{Sí, entiendo.}
{213}{}{Bien. Por ahora, asumiré que estamos en el mismo bando.}
{214}{}{Vale. ¿Qué está pasando aquí?}
{215}{}{Eh... la verdad es que no.}
{216}{}{Soy quien representa la autoridad de Aaron por estos lados. Él aprecia a aquellos que lo honran y es muy duro con quienes se le oponen. Más te vale que elijas tu bando con cuidado.}
{217}{}{Entiendo.}
{218}{}{Vale, pero, ¿qué es lo que está pasando aquí?}

{220}{}{Espera... Esa túnica... ¿Te envió Aaron?}
{221}{}{No sé de quién hablas. Es solo un trapo viejo que me encontré.}
{222}{}{En ese caso, olvídalo. ¿Qué estás haciendo aquí?}
{223}{}{Sí, Aaron me envió. Quiere un informe de la situación.}
{224}{}{No entiendo su lógica. Ya casi no tengo comida para mi escuadrón y él me manda otra boca que alimentar.}
{225}{}{Tengo una misión especial. Aaron perdió la paciencia y quiere ver resultados.}
{226}{}{Supongo que quiere una solución rápida.}
{227}{}{Hmm. Me da curiosidad saber el cómo te ganaste la confianza de Aaron. Si tomamos eso en cuenta, debería escuchar tus consejos. Pero el que manda aquí soy yo, soy el Comandante. No lo olvides.}
{1227}{}{Hmm. Me da curiosidad saber el cómo te ganaste la confianza de Aaron. Si tomamos eso en cuenta, debería escuchar tus consejos. Pero el que manda aquí soy yo, soy el Comandante. No lo olvides.}
{228}{}{De acuerdo.}
{229}{}{Tu mando me importa menos que una cucaracha.}

{230}{}{Represento a los Rangers. Oímos que intentan destruir a esta tribu de pastores.}
{231}{}{Sólo somos colonos pacíficos. Vinimos a estas tierras, estaban desiertas y queremos fundar un asentamiento. ¿Qué hay de malo en eso?}
{232}{}{Están intentando expulsar a la tribu.}
{233}{}{Escucha bien, perro de los Rangers. Estas tierras no te pertenecen ni a ti ni a estos salvajes. Su dueño es Aaron, el Señor de Fénix, todo este valle le pertenece. Vuelve con tu gente y no te metas en nuestro camino.}
{234}{}{Ya has dicho suficiente.}
{235}{}{No me moveré de aquí hasta que respondas mis preguntas. ¿Qué andan tramando?}

#Re-dialogue
{250}{}{¿Y bien? Habla, te escucho.}
{251}{}{Permíteme, debo irme.}
{252}{}{¿Qué es lo que ustedes están haciendo aquí?}

{260}{}{Estas tierras le pertenecen a Su Majestad Aaron, el Señor de la Iglesia del Fuego Santo y el Señor de Fénix. Él decidió fundar una colonia en este lugar, pero unos salvajes interfieren con nuestra misión.}
{261}{}{¿Cuál es el problema con estos salvajes?}
{262}{}{No habían sido agresivos en el pasado. Ahora intentan expulsarnos de aquí a la fuerza, incluso nos amenazan. No queremos que se derrame sangre, de hecho, les estamos ofreciendo una alianza que nos beneficiará a los dos.}
{263}{}{¿Y entonces por qué no los dejas en paz?}
{264}{}{En Fénix, sus brahmanes son muy valiosos. Y sin ellos habrá una escasez de alimentos. Además, si resulta que ahora serán agresivos, no podemos permitir que estén cerca de nosotros.}
{265}{}{[Más]}
{266}{}{De todas formas, yo no estoy a cargo de todo esto. Sólo estoy siguiendo las órdenes que me llegan desde Fénix. Mi orden es fundar un asentamiento, eso lo tengo claro. Por lo tanto, no veo por qué debería considerar lo que me exije una tribu de salvajes analfabetos.}
{267}{}{Ya veo.}
{268}{}{Escúchame, los salvajes ya no quieren ni mirarme. Pero tú sí podrías negociar con ellos, habla con su líder y convéncelo de que la alianza es lo que más le conviene.}
{269}{}{No voy a meterme en una guerra que no es mía. Mis problemas son más importantes.}
{270}{}{¿De verdad piensas que tus problemas se comparan a una guerra entre dos facciones? Entonces reza que esto no te afecte a ti ni a tu familia.}
{271}{}{Tengo que irme.}
{272}{}{Lo intentaré, te haré saber cómo van las cosas.}

{280}{}{Pude hablar con su líder, pero se niega por completo a la alianza.}
{281}{}{Jerónimo es demasiado testarudo, hablar con él es una pérdida de tiempo. Debemos tomar una decisión drástica.}
{282}{}{¿Qué tienes en mente?}
{283}{}{Los salvajes nos odian, a excepción de unos pocos. Los jóvenes incluso intentan ayudarnos y entre ellos está el hijo del jefe, se llama Chatto. Habla con él y averigua qué es lo que quiere. Si toma el lugar de su padre, podremos llegar a algún acuerdo.}
{284}{}{De acuerdo, vale la pena intentarlo.}
{285}{}{He matado a Jerónimo y Chatto, su sucesor.}
{1285}{}{He matado a Jerónimo y a Chatto, su sucesor.}
{286}{}{¡Qué carajos acabas de hacer! Jerónimo se resistía a la alianza, pero Chatto la habría aceptado si lo hubiéramos dejado ocupar el lugar de su padre. Ahora no tenemos nadie con quién negociar, porque las tribus se dividirán en clanes pequeños otra vez y se esparcirán por el desierto.}
{287}{}{No lo pensé bien...}
{288}{}{Pero me habías sugerido que querías deshacerte del líder.}
{289}{}{Bueno, en cualquier caso, las cosas serán más fáciles. Podremos asentarnos en este pueblo y obligar a los salvajes que acepten nuestras reglas. Será a la fuerza, porque no podrán resistirse a nosotros, ni siquiera tienen un líder.}
{290}{}{Entonces supongo que debería felicitarte por tu victoria.}
{291}{}{Todavía no, los exploradores ya averiguaron quién estaba causando alborotos entre la tribu. Resulta que era un hombre llamado Oscar, ¡un ranger! Ya entiendo de dónde estaba sacando la tribu sus tácticas y estrategias de guerrilla.}
{292}{}{[Más]}
{293}{}{¡Ese ranger debe ser expulsado de San Brahmán! Ni siquiera queremos recordar su nombre. Si no se va, lo haremos correr a latigazos, igual que a un brahmán.}
{294}{}{De acuerdo, veré qué puedo hacer.}
{295}{}{Chatto ha tomado el puesto de jefe de la tribu. Y está de acuerdo con la alianza.}
{296}{}{¡Qué buenas noticias! En los ojos de la tribu, Chatto ahora tiene el poder, su autoridad podrá mantener a la tribu unida en este lugar y podremos usarlas en nuestros planes. Has hecho un muy buen trabajo, sí que sabes de la 'diplomacia'.}
{297}{}{El Gran Jefe está de acuerdo con la alianza, pude convencerlo, pero no fue nada fácil.}
{298}{}{Qué buenas noticias. Pero dudo que de verdad haya cambiado de parecer, lo más seguro es que los demás ancianos estén asustados de entrar en una guerra y lo hayan presionado. Pero hiciste un buen trabajo. Eres un excelente 'diplómata'.}

{300}{}{Oscar ha muerto. Los seguidores que tenía en su campamento se arrodillarán ante ti, Comandante.}
{301}{}{¡Esto es una victoria! Le hemos dado un golpe fuerte a la reputación de los Rangers en frente de toda la tribu. Ahora entenderán quién es el que manda en el yermo.}
{302}{}{Oscar ha escapado de San Brahmán y ya no será un problema.}
{303}{}{¡Esto es una victoria! En la perspectiva de los salvajes, ese ranger es más cobarde que una iguana. ¡Ahora entenderán quién es el que manda en el yermo!}
{304}{}{¡Me alegra haberlo ayudado, Comandante!}
{1304}{}{¡Me alegra haberlo ayudado, Comandante!}
{305}{}{Ajá. La verdad es que esto lo hiciste *tú*.}
{306}{}{Le has hecho un buen servicio al Imperio. Si los demás tuvieran la mitad de tu fuerza y espíritu, seríamos imparables. Me alegra que estemos en el mismo bando.}
{1306}{}{Le has hecho un buen servicio al Imperio. Si los demás tuvieran la mitad de tu fuerza y espíritu, seríamos imparables. Me alegra que estemos en el mismo bando.}
{307}{}{¿Crees que haya lugar en el imperio de Aaron para una persona más?}
{308}{}{Claro, voy a firmar una carta de recomendación que contenga tu nombre, la enviaré hacia Fénix. Podrás hablar con Aaron, él valora mis palabras.}
{309}{}{Gracias.}
{310}{}{No, no me lo agradezcas. Tú y yo tenemos una causa en común. Te deseo suerte en tus viajes, camarada.}
{311}{}{Buena suerte.}

{320}{}{¿Quién eres? ¿Y quién es toda esta gente?}
{321}{}{Cuéntame de ti y de tu escuadrón.}
{322}{}{Soy George Crook, el comandante de campo de Su Majestad Aaron, el Señor de la Iglesia del Fuego Santo y el Señor de Fénix. Y este es mi escuadrón. Una vez que nos encarguemos de los enemigos en este territorio, nos seguirá un grupo de colonos.}
{323}{}{Fue un gusto hablar contigo, pero ya debo irme.}
{324}{}{¿No crees que su título es un poquito largo?}
{325}{}{Cuidado con lo que dices. El imperio de Aaron es muy grande y se expande constantemente. Pronto, toda Arizona estará al alcance de su mano.}
{326}{}{¿Podrías repetirme quién eres?}
{327}{}{¿De dónde vinieron todos ustedes?}
{328}{}{Somos de Fénix, vinimos aquí para establecer una colonia pero resulta que los salvajes ya se habían asentado en este lugar.}
{329}{}{¿En dónde se ubica esa tal Fénix?}
{330}{}{Es una ciudad al sureste de aquí. Aunque me extraña que jamás hayas oído hablar de ella, es la ciudad más grande de la región.}
{331}{}{No lo sé, yo estoy en la dirección opuesta, soy de una aldea que está aislada del mundo, así que...}
{332}{}{Ya veo, eso es territorio de los Rangers. No me sorprende que en tu área no haya más que unas aldeas y nada de civilización. Échale un vistazo a Fénix y entenderás lo que es una ciudad de verdad.}
{333}{}{Lo haré, gracias por tu consejo.}
{334}{}{No me importa esa 'civilización' de la que hablas.}
{335}{}{Háblame sobre la tribu.}
{336}{}{Son una tribu de salvajes, compuestos por pastores y nómadas. Ya ha pasado tiempo que Fénix ha tenido una relación difícil con ellos. Ya hemos sido atacados por ellos.}
{337}{}{Por cierto, ¿qué es lo que sabes acerca de los lugareños?}
{338}{}{No parece que te agraden.}
{339}{}{¡Son salvajes! Se arrastran como un montón de alimañas por el desierto. Y apenas te asientas en un sitio, ellos vienen a decirte que es 'su tierra'.}
{340}{}{Sigue, te escucho.}
{341}{}{Los clanes más particularmente salvajes atacan a los civiles. Fénix ya ha intentado hacer las paces durante varios años e incluso algunos clanes se han pasado a nuestro bando, pero no todos. Y ahora mi escuadrón puede ser testigo de la terquedad de estos salvajes.}
{342}{}{Ya entiendo el por qué andas armado hasta los dientes. Ya me voy. Paz.}
{343}{}{¿También eres de Fénix?}

{350}{}{Debes irte de San Brahmán, tú y todo tu escuadrón.}
{351}{}{¿De qué estás hablando?}
{352}{}{Bueno, no quieres hacer enojar a la tribu, ¿no?}
{353}{}{Primero, quiero poner a estos salvajes en su lugar. Y respecto a ti, no te vendría mal replantearte tu vida.}
{354}{}{Bueno, dije lo que tenía que decir.}
{355}{}{Si no te vas de aquí, correrá la sangre.}
{356}{}{Quien sea que te haya enviado a hablar conmigo, dile que George Crook no conoce el miedo. Tus palabras no me asustan.}
{357}{}{No digas que no te lo advertí. La sangre correrá como el agua. ¡Ahora!}
{1357}{}{No digas que no te lo advertí. La sangre correrá como el agua. ¡Ahora!}
{358}{}{Vale, lo entiendo.}
{1358}{}{Valen, lo entiendo.}
{359}{}{La tribu está lista para ir a la guerra, tu presencia sólo los está provocando a ello.}
{360}{}{Sé que los salvajes no se rendirán tan fácilmente. Mi maestro está construyendo su ideal del Nuevo Mundo, y estos tribales están demasiado lejos de esa visión. Es justamente por esa razón que mi misión es así de importante - debo demostrarle a estos salvajes que tienen un estilo de vida anticuado y que no los llevará a ningún lado. Debemos mostrarles que el mundo puede ser mejor.}
{361}{}{Ya, no te llevaré la contraria.}
{362}{}{Lo entiendo, pero enojarlos sólo acercará a la tribu hacia sus tradiciones y los aleja de tus ideales, dales tiempo de pensar, porque si te atacan, has fallado.}
{363}{}{¡Malditos sean, estos salvajes! Ya estaba considerando en una retirada hacia Fénix. Mis hombres están cansados y se nos acaban los suministros, y ahora, nos acechan detrás de cada duna.}
{364}{}{¿Entonces qué harás?}
{365}{}{No tenemos mucha opción, pero tenemos que irnos. Pero regresaremos, con más hombres y con más vigor.}
{366}{}{Bien pensado, comandante. Te deseo suerte en el viaje de vuelta.}
