{100}{}{Ves al Ranger Oscar.}
{101}{}{Estás viendo a un hombre de mediana edad con guantes y un revólver en su cinturón.}
{102}{}{Necesito esa tecnología para expulsar a esos malditos misionarios.}
{103}{}{Pronto me iré de San Brahmán, los Rangers ya no son bienvenidos aquí. Es una pena.}
{104}{}{Agradezco tu ayuda, tu valentía pasará a la historia.}
{105}{}{Nos volveremos a ver.}
{106}{}{Más te vale que no volvamos a vernos.}
{107}{}{Necesito prepararme para la batalla, te veré cerca del campamento de los misionarios.}

#Before receiving the quest
{200}{}{Hola.}
{201}{}{Adiós.}
{202}{}{[Trampa: fuera del pueblo, ranger]}
{203}{}{[Trampa: ganaste]}
{204}{}{[Trampa: da la misión para matar a los misionarios]}

{210}{}{Un segundo. ¿Quién eres? ¿Estás con los misionarios?}
{211}{}{No, sólo estoy viajando. Y ya me voy.}
{212}{}{No, no, soy de una aldea al noroeste.}
{213}{}{¿Vienes de por allá? No hay tantos asentamientos en esa dirección, creo que estás mintiendo...}
{214}{}{Te digo que... No importa. ¿De dónde eres tú?}
{215}{}{Eso no es asunto tuyo. Ocúpate con lo que sí lo es.}
{216}{}{Nos vemos, forastero.}
{217}{}{¿Y qué si lo soy?}
{218}{}{No me agradas. Igual que cualquier persona del este. Si me entero que los misionarios te tienen de espía, te meteré una bala en el cráneo.}
{219}{}{Los líderes me dejaron pasar.}
{220}{}{Tienes mucha suerte. Yo no lo hubiera permitido.}
{221}{}{No soy del este, soy el noroeste.}
{222}{}{Nos vemos, forastero.}
{223}{}{¿Por qué te dejaron pasar? ¿También eres un forastero?}
{224}{}{El Jefe Jerónimo me dijo que hablara contigo. ¿En qué te puedo ayudar?}
{225}{}{Me vendría bien que me eches una mano.}
{226}{}{Si yo fuera él, no confiaría tan rápido en alguien. Pero sí, nos vendría bien la ayuda.}
{227}{}{Infórmame sobre la situación, Ranger.}
{228}{}{¿Eres el Ranger Oscar? Me envía el General Mossman, quiere un informe sobre la situación.}
{229}{}{Eso es raro. No sé por qué te escogió a ti y no a uno de los rangers... Pero, el general sabe lo que hace.}

{230}{}{Me enviaron a San Brahmán para restaurar el orden. La tribu está intentando mantenerse independiente pues el Imperio de Fénix intenta conquistarlos. La situación es difícil y podría estalar una guerra a gran escala en cualquier momento.}
{231}{}{Sigue.}
{232}{}{Ve al grano.}
{233}{}{Llegó un destacamento de misionarios de Fénix. Están acampados cerca del pueblo e intentan expulsar a la tribu. Según ellos, quieren un acuerdo comercial. Una sucia y total mentira.}
{234}{}{¿Cuál es el problema?}
{235}{}{No hay ningún imperio en la historia que haya sido tan amable durante su expansión. Una vez que se haga el acuerdo, desarmarán a la tribu y los brahmanes serán distribuidos a aquellos que obedecen al emperador.}
{236}{}{[Escucha]}
{237}{}{No se puede confiar en Fénix, son sólo un montón de aventureros y tiranos. La tribu tiene su propia cultura y tradiciones, eso es todo lo que conocen. No podemos permitir que unos tipos codiciosos de la ciudad arruinen sus vidas.}
{238}{}{Comprendo. ¿Entonces quieres hacer que los misionarios retrocedan a la ciudad?}
{239}{}{No podemos igualar sus números para luchar contra ellos de cabeza. Y gracias a la influencia de Fénix sobre la juventud, la tribu está dividida. Ayúdame a preparar un equipo para expulsar a los misionarios, debemos tratar a los heridos y hacer que Chatto entre en razón, pues es el hijo de Jerónimo, el líder de la tribu.}
{240}{}{De acuerdo, veré qué puedo hacer.}
{241}{}{Dudo que tu equipo sea capaz de hacerlo. Voy a buscar otra manera.}

{242}{}{Vaya. Hola, cultista. Tengo un arma capaz de volarte los sesos de un tiro.}
{243}{}{Espera un momento...}
{244}{}{¿Qué estás...?}
{245}{}{¡Lárgate de una maldita vez! Que no te vuelva a ver por aquí. Nadie le pidió a los perros falderos de Aaron que vinieran a este lugar.}
{246}{}{Ya, cálmate... Me voy.}
{247}{}{¿Un ranger? Qué sorpresa. El cuartel general no me avisó de tu llegada. ¿Estás aquí por cuenta propia?}
{248}{}{No exactamente. Sólo estoy de paso. ¿Qué está pasando? ¿Necesitas ayuda?}
{249}{}{Sólo estoy de paso. Lo lamento, pero ya debo irme. Quizás volvamos a vernos.}

{250}{}{¿No te había dicho que te largases de San Brahmán? Sigue jodiéndome y te echaré a patadas.}
{251}{}{Fue un error. ¡Dame otra oportunidad y arreglaré las cosas!}
{252}{}{No tienes ninguna autoridad aquí. Eres un forastero, igual que yo. Así que siéntate y cállate.}
{253}{}{Te puedo apostar a que no harás nada. ¿Verdad que sí, vago?}
{254}{}{Repasemos el plan. ¿Cuál es el siguiente paso?}

{260}{}{Debes irte de San Brahmán de inmediato. El Comandante Crook te está dando una última oportunidad para que salgas de aquí con vida.}
{261}{}{No me asustan tus amenazas, porque ya sé que me estoy arriesgando. Mi meta es más importante que mi vida. Intento salvar a la tribu de la exterminación o su esclavitud.}
{262}{}{Se acabó, los ancianos ya no quieren una guerra contra los misionarios.}
{263}{}{Ya veo. De alguna forma, los misionarios han nublado por completo el juicio de los ancianos. El pueblo de San Brahmán está a punto de entrar a tiempos oscuros.}
{264}{}{La mayoría de la tribu está en contra de ti. ¿Te vas, o qué?}
{265}{}{Hmph. Supongo que tendré que volver a la base con las manos vacías. Pero no creas que los Rangers se olvidarán de esto, no se puede permitir que Fénix aplaste un pueblo entero para ganar poder y recursos.}
{266}{}{No pongas esa cara, todavía podrás vengarte. O eso creo.}
{267}{}{Lárgate de una vez.}
{268}{}{¿Te irás de aquí o qué?}
{269}{}{No. Me quedaré y lucharé junto a la tribu durante el asalto. Y no estaré sólo, hay otros que están preparados para luchar.}
{270}{}{Como tú quieras. Considérate advertido.}
{271}{}{Has lo que quieras, mi trabajo era darte un aviso.}
{272}{}{El desierto te enseña a ser paciente, ¿no es así? Ve a esconderte a las sombras y espera el momento correcto.}
{273}{}{A veces es mejor dar una retirada para reunir tus fuerzas. ¿No crees que este es uno de esos momentos?}
{274}{}{La Presa Parker se inundó y fue destruida. Los Rangers ya no pueden seguir apoyando la lucha de San Brahmán.}
{275}{}{Se acabó, Jerónimo ha dejado de apoyar a los rangers.}
{276}{}{¡Veamos si siquiera eres capaz de cuidarte a ti mismo, idiota!}

#After receiving the quest
{300}{}{¿Algo que reportar? Toda información sobre el enemigo que poseas será valiosa.}
{301}{}{Nada que reportar.}
{302}{}{Estoy feliz de verte, Ranger.}
{303}{}{Es bueno verte, amigo.}
{1303}{}{Es bueno verte, amiga.}


{310}{}{Quiero preguntarte sobre los Rangers de Arizona.}
{311}{}{Le traemos la Ley y el Orden a estas tierras.}
{312}{}{¿Los Rangers tienen alguna base principal?}
{313}{}{El cuartel general está ubicado en el oeste y hay muchos puestos avanzados a través del sur de Arizona. Pero sería estúpido decirte en dónde están.}
{314}{}{El cuartel general está ubicado en el oeste y hay muchos puestos avanzados a través del sur de Arizona. Pero tú ya sabes en dónde están.}
{315}{}{¿En dónde está tu placa, ranger?}
{316}{}{Me la quité para simplificar las cosas. Una vez que la tribu esté a salvo, volverá a mi pecho.}
{317}{}{¿Por qué los rangers se involucraron en esta guerra?}
{318}{}{Tenemos dos objetivos: hacernos aliados de la tribu y poner alto a la expansión de Fénix.}
{319}{}{Las leyes de los rangers deben hacer conflicto con las tradiciones de la tribu, ¿no?}
{320}{}{Todos deben seguir reglas muy simples: no mates sin razón ni tampoco robes. Respecto a las tradiciones locales, debemos adaptarnos a ellas.}
{321}{}{Ya veo.}

{330}{}{Los misionarios han huido de vuelta hacia Fénix.}
{331}{}{Sí que tienes una buena capacidad del habla. No sé cómo lo conseguiste, pero lo agradezco.}
{332}{}{No fue nada. Resulta que no querían presionar el gatillo.}
{333}{}{Fue difícil, pero lo hice lo mejor que pude.}
{334}{}{El General Mossman tomó una buena decisión al confiar en ti. Él es bueno encontrando gente capaz. Y ahora que por fin ha acabado esta misión, podré volver a la base.}
{335}{}{Buena suerte, Oscar.}
{336}{}{Los Rangers necesitan más gente como tú. Dale una visita a nuestra base en la Presa Parker. Voy a recomendarte con el General.}
{337}{}{Gracias, Ranger. Si llego a estar por allá, iré a hablar con él.}

{340}{}{Chatto dejará de apoyar a Fénix.}
{341}{}{Que buenas noticias, tendremos más oportunidad ahora que Chatto no va a causarnos problemas.}
{342}{}{¿Qué más falta hacerse?}
{343}{}{Lo único que queda es reunir a los guerreros e ir a la batalla. Pero algunos de ellos están heridos, eso preocupa a los pastores. Algunos de ellos podrían unirse a la lucha si sus heridas fueran sanadas.}
{344}{}{Veré si puedo ayudarlos con sus heridas.}
{345}{}{Gracias, si no eres capaz de tratarlos, prueba a usar algún medicamento. Quizás puedas robarle un poco a los misionarios.}
{346}{}{Estoy en ello.}
{347}{}{Pero, yo no sé de medicina.}
{348}{}{Entonces encuentra medicamentos, puedes robarle a los misionarios si es necesario.}
{349}{}{Estoy en ello.}
{350}{}{Los heridos ya están de vuelta en acción. Estamos listos.}
{351}{}{Eso es genial, debemos reunir a nuestro escuadrón y hacer un plan. Nos vemos al norte del campamento de los misionarios. Prepárate, no será una pelea fácil.}
{352}{}{Ya voy.}
{353}{}{Chatto ha fallecido, ya no podrá interferir más.}
{354}{}{Que malas noticias. Chatto era un líder entre los jóvenes y podría haber cambiado sus mentes. Sólo nos queda esperar que ninguno de sus amigos se meta en nuestro camino.}
{355}{}{Ya no hay otra opción. Crook anticipa tu ataque. ¡Muéstrale lo que puede hacer un Ranger!}
{356}{}{Dile a Crook que acepto su desafío. Ya encontró la pelea que buscaba.}
{357}{}{Adiós.}
{358}{}{Buen trabajo. ¿Qué hay de Chatto? ¿Lo has convencido?}
{359}{}{Todavía no he hablado con él.}

#During a skirmish
{360}{}{Hmm. Me parece que los misionarios no esperaban que de verdad fuéramos a luchar. Nuestra ventaja yace en su arrogancia. Vamos a hacerlos pedazos.}
{361}{}{Oscar, voy a hacer reconocimiento del área. Volveré pronto.}
{362}{}{¡Que la batalla comience!}
{363}{}{¡Los misionarios han huido!}
{364}{}{¡La victoria es nuestra! (Los guerreros de la tribu celebran) Necesitaré un momento para registrar el área. Por el momento regresa al campamento, terminaremos de hablar allá.}
{365}{}{Nos vemos luego.}
{366}{}{En ese caso, morirás igual que un perro. Lloriqueando y pidiendo misericordia.}
{367}{}{¡Suficiente! Se te acabó el tiempo, Ranger...}
{368}{}{¡Háganlos retroceder!}
{369}{}{¡A la carga!}
{370}{}{Si Crook y sus perros no se rinden de inmediato, vamos a expulsarlos de aquí a golpes.}
{371}{}{Le diré lo que estás exigiendo.}
{372}{}{La batalla ha acabado. ¡Fuimos victoriosos!}
