{100}{}{Ves a Hilario.}
{101}{}{Estás viendo a un anciano fuerte con un atuendo religioso de apariencia magnífica, al menos por el estándar local.}
{102}{}{No tienes ni idea de lo que has hecho.}
{1102}{}{No tienes ni idea de lo que has hecho.}
{103}{}{(}
{104}{}{/3) de los aldeanos te hablaron sobre la festividad.}

{110}{}{}

# Phrases from the opening cutscene
{120}{}{¡Hermanos y hermanas! Hoy es un día importante para nosotros. Hoy es el Día de la Vida, hoy honramos a Lucía.}
{121}{}{Este día, ella será nuestra 'reina', el día en el que declaramos lo siguiente con orgullo: sí, seguimos con vida. Hemos logrado vivir un día más.}
{122}{}{Hay muchos que no fueron tan afortunados, pero nosotros sí. A nuestro santo le damos las gracias por esta bendición, él nos protege de las bestias salvajes y de los saqueadores...}
{123}{}{Y entonces... Entonces... Oh, ah...}
{124}{}{Lucía, hoy es tu gran día.}
{125}{}{Ve a la iglesia y finaliza la ceremonia. Ya sabes qué hacer. Vamos a rezar.}

# First dialogue
{200}{}{(Al verte, la multitud se calla y se hace a un lado; ocurre una pausa llena de tensión) Ah... em... Parece que tenemos huéspedes... ¡Qué sorpresa!}
{201}{}{Sólo estaba pasando por al lado y escuché su... ¿festival? ¿Qué está pasando aquí?}
{1201}{}{Sólo estaba pasando por al lado y escuché su... ¿festival? ¿Qué está pasando aquí?}
{202}{}{¿Qué está pasando? Verás, gringo. Estamos celebrando el día de nuestro santo. ¡Estás en la celebración del Día de la Vida! Por favor, disfruta el festival y siéntete como en casa. Nosotros le damos la bienvenida a cualquiera... que venga con buenas intenciones.}
{1202}{}{¿Qué está pasando? Verás, gringa. Estamos celebrando el día de nuestro santo. ¡Estás en la celebración del Día de la Vida! Por favor, disfruta el festival y siéntete como en casa. Nosotros le damos la bienvenida a cualquiera... que venga con buenas intenciones.}
{203}{}{Durante todo mi viaje, esta es la primera vez que veo un lugar tan alegre. Estaré contento de unirme a sus festividades.}
{1203}{}{Durante todo mi viaje, esta es la primera vez que veo un lugar tan alegre. Estaré contenta de unirme a sus festividades.}
{204}{}{Casi toda la gente amistosa con la que me he cruzado ha intentado engañarme. Ojalá que ustedes sean la excepción.}
{205}{}{Bueno, entonces te damos la bienvenida, gringo. Si tienes alguna pregunta, por favor, habla conmigo. Me llamo Hilario López Andrade. Soy el jefe de la aldea y también su sacerdote. ¡Bueno! ¿Por qué están tan callados? ¡Sigamos celebrando, hermanos y hermanas!}
{206}{}{Gracias por acogerme.}
{207}{}{De acuerdo, me quedaré un tiempo.}
{208}{}{¿Qué está pasando? Ah, gringos, estamos celebrando el día de nuestro santo. ¡Estás en la celebración del Día de la Vida! Por favor, disfruta el festival y siéntete como en casa. Nosotros le damos la bienvenida a cualquiera... que venga con buenas intenciones.}
{209}{}{}
{210}{}{Debes tener muchas preguntas, amigo. A mí también me gustaría saber más de ti, pero por desgracia, en este momento estoy muy ocupado. Alguien robó la corona de la ceremonia y no podemos encontrarla. No puedes coronar a alguien sin una corona, eso va en contra de nuestras tradiciones.}
{1210}{}{Debes tener muchas preguntas, amiga. A mí también me gustaría saber más de ti, pero por desgracia, en este momento estoy muy ocupado. Alguien robó la corona de la ceremonia y no podemos encontrarla. No puedes coronar a alguien sin una corona, eso va en contra de nuestras tradiciones.}
{211}{}{Entonces no tienes tiempo para hablar. Volveré luego.}
{212}{}{Entonces intentaré encontrar esa corona.}
{213}{}{¿Esta es la corona que estás buscando?}
{214}{}{¡Sí, es esa! ¿En dónde la encontraste?}
{215}{}{Bueno, estaba tirado en el piso por aquí cerca.}
{216}{}{¿Estás diciendo que la dejaron caer por accidente? Que alivio, me preocupaba que alguien de mi rebaño se haya alejado de nuestra fe. Eso es reconfortante. ¿Sabes? Te encuentras en el asentamiento más pacífico en todo el mundo de Dios. Hace años que no cometen ningún crimen por aquí.}
{217}{}{Eso es bueno.}
{218}{}{¿En serio?}
{219}{}{Un adolescente se la robó, no sé por qué lo hizo.}
{220}{}{Ah, déjame adivinar... Quería divertirse, eso está en la sangre de un jovencito. No hay nada por lo que preocuparse.}
{221}{}{Bueno, si tú lo dices.}
{222}{}{¿En serio?}
{223}{}{Ahora podemos finalizar la ceremonia. Te haré saber que hemos seguido esta tradición por un largo tiempo y es de gran importancia para esta comunidad. Cada ciertos meses, coronamos a uno de los nuestros como recuerdo de que todos somos iguales y que todos podemos ayudar a la comunidad. Es la hora de honrar a Lucía. Mija, ven aquí, acércate...}
{224}{}{[Observa la ceremonia]}
{225}{}{Llevar a cabo la ceremonia es tan agotador. Ya no soy tan joven. Necesito recostarme y descansar.}
{226}{}{[Deja al jefe en paz]}
{227}{}{¿Por qué cerraron la iglesia?}
{228}{}{No deberías entrar ahí. Ni siquiera los aldeanos tienen permitido entrar durante la ceremonia. Para nosotros, es suelo santo, así que por favor no entres ahí. No podemos permitir que ese lugar sea profanado.}
{229}{}{Comprendo.}


{230}{}{¿¡Qué estás haciendo acá, pinche gringo!? ¿¡Cómo te atreves a profanar nuestro santuario!?}
{1230}{}{¿¡Qué estás haciendo acá, pinche gringa!? ¿¡Cómo te atreves a profanar nuestro santuario!?}
{231}{}{No te preocupes, anciano. He matado al monstruo del sótano, ya no tienes nada que temer.}
{232}{}{¿¡L-lo mataste!? (confundido) Pero... ¡¡¡QUÉ HAS HECHO!!!}
{1232}{}{¿¡L-lo mataste!? (confundido) Pero... ¡¡¡QUÉ HAS HECHO!!!}
{233}{}{Pues, maté al monstruo. Está muerto. Bien muerto. Lo mandé al infierno. ¿Ahora así?}
{1233}{}{Pues, maté al monstruo. Está muerto. Bien muerto. Lo mandé al infierno. ¿Ahora así?}
{234}{}{¿¡Por qué nos haces esto!? ¿Acaso no te das cuenta de que El Diablo era nuestro protector, nuestro santo?}
{235}{}{¿Ustedes veneraban a un monstruo? ¿En serio?}
{236}{}{Él nos protegía de los forasteros y los animales salvajes, él limpió a la comunidad de los leprosos y los enfermos, la gente estaba unida gracias al Diablo. Entre nuestra gente no ha habido ningún robo durante años. Sin El Diablo, nuestro estilo de vida se hará pedazos. Y ahora, ¿qué nos aguarda el destino?}
{237}{}{Pues, lo más seguro es que algo se te va a ocurrir. Porque tarde o temprano, ese "santo" hubiera muerto.}
{238}{}{Ah, estás preocupado por tu poder, ¿a poco sí, jefecito? Ahora será más difícil unir a todos usando el miedo, no podrás gobernarlos.}
{239}{}{Sé lo que estás haciendo, gringo. Si es que... cuando te mueras, el mundo será un lugar mejor. No voy a permitir que salgas de esta iglesia.}
{1239}{}{Sé lo que estás haciendo, gringa. Si es que... cuando te mueras, el mundo será un lugar mejor. No voy a permitir que salgas de esta iglesia.}
{240}{}{Inténtalo, viejo.}
{241}{}{Estás cometiendo un grave error...}
{242}{}{Suficiente, gringo. Vete y no vuelvas nunca.}
{1242}{}{Suficiente, gringa. Vete y no vuelvas nunca.}
{243}{}{Es mejor que no me amenaces, anciano. Créeme, no es buena idea.}
{244}{}{Ya no tengo nada que hacer aquí. Adiós, Hilario.}
{245}{}{Luego de todo lo que has hecho y escuchado, ejecutarte no sería suficiente.}
{246}{}{¡No te atrevas a volver aquí! ¿Me escuchas? ¡Lárgate!}
{247}{}{Sí, sí. Lo que tú digas, viejo pendejo.}
{248}{}{¿Por qué sigues aquí?}
{249}{}{Ya me voy. Es sólo que me olvide de... mis cosas. Adiós.}
{1249}{}{Ya me voy. Es sólo que me olvide de... mis cosas. Adiós.}
{250}{}{Todo el pueblo de Santa Ana quiere que te vayas. ¿No lo entiendes? Tus acciones los pusieron en tu contra.}
{251}{}{He protegido a esta gente por quince años. ¡Y así me pagan! Ahora que se fue El Diablo me culparán por todo. ¿Sabes lo que sacrifiqué? ¿El tormento por el que pasé los primeros años? Pero fui elegido como el jefe, e hice lo que tuve que hacer - los salvé. ¿Y vienes a decirme que estuvo mal? ¡Al carajo con lo que pienses, gringo!}
{1251}{}{He protegido a esta gente por quince años. ¡Y así me pagan! Ahora que se fue El Diablo me culparán por todo. ¿Sabes lo que sacrifiqué? ¿El tormento por el que pasé los primeros años? Pero fui elegido como el jefe, e hice lo que tuve que hacer - los salvé. ¿Y vienes a decirme que estuvo mal? ¡Al carajo con lo que pienses, gringa!}
{252}{}{Parece que no puedo convencerte. ¡Es mejor que te mueras!}
{253}{}{Como tú gustes. Ahora, todo esto es asunto tuyo. Adiós, Hilario.}
{254}{}{Ya no tienes lugar en Santa Ana. El pueblo entero está en tu contra, es hora de que te largues.}
{255}{}{¿¡Así es como me pagan después de cuidarlos por 15 años!? Ahora que el Diablo no está, me darán la espalda. ¿Sabes cuánto sacrifiqué? ¿Todo lo que sufrí en los primeros años? Fui elegido como jefe e hice lo que tenía que hacer. ¡Yo los salvé! Al menos, no fue para nada, me iré con una consciencia limpia. Si el exilio es el precio que debo pagar para que mi gente viva en paz, que así sea. Me voy.}
{256}{}{No esperaba que estuvieras de acuerdo. Adiós, anciano.}
{257}{}{Te daré otro lugar en el que puedes vivir... ¡en el infierno!}

{258}{}{¿Tienes otra pregunta, joven?}

