{100}{}{Ves a Lucía.}
{101}{}{Ves a una niña con ropa ceremonial. Parece estar triste, pero determinada.}
{102}{}{«Gracias. ¡Gracias, gracias!»}
{103}{}{Muchas gracias.}
{104}{}{Has regresado la corona a su dueña.}
{105}{}{Creo que esto es tuyo, tómala y haz lo que quieras con ella.}
{106}{}{Es demasiado pronto como para darte esto.}
{107}{}{Lucía ha regresado a Santa Ana.}
{108}{}{«Antonio y yo solíamos venir aquí a escondidas. Me prohibieron tener una relación.»}
{109}{}{«Este lugar es silencioso y pacífico. Me encantaba sentarme aquí y pensar en mi destino.»}

{110}{}{}
{115}{}{«¿Esto es tuyo, no? Toma, sé que lo perdiste.»}
{116}{}{«No debería darte esto, es muy pronto..»}

{200}{}{¿Tú otra vez?}
{201}{}{Ahí estás, te estuve buscando por todos lados.}
{202}{}{(se da la vuelta)}
{203}{}{¿Sabes? Antonio también te está buscando.}
{204}{}{(se da una media vuelta) ¿Antonio?}
{205}{}{Sí, señorita. Te está buscando.}
{206}{}{(se pone de rodillas y empieza a llorar) Pero, El Diablo... *sollozo* No lo entiendes, gringo. Había esperado toda mi vida por ese momento.}
{1206}{}{(se pone de rodillas y empieza a llorar) Pero, El Diablo... *sollozo* No lo entiendes, gringa. Había esperado toda mi vida por ese momento.}
{207}{}{¿Acaso te van a...? Mira, hablemos de esto en el pueblo, es peligroso estar aquí.}
{208}{}{(te agarra la manga) ¡Este es mi destino! ¡Es mi razón de vivir!}
{209}{}{¿O sea que te han querido sacrificar desde que naciste? Tiene sentido que no quieras ser libre.}
{210}{}{(exhausta) Bueno. Iré a casa. Que pase lo que tenga que pasar.}
{211}{}{Está bien, vámonos, tienes que llegar a salvo.}
{212}{}{Quédate aquí, iré a revisar el área.}

{213}{}{(se pone de rodillas y empieza a llorar) Pero, El Diablo... *sollozo* No lo entiendes, gringo. Había esperado toda mi vida por ese momento. }
{1213}{}{(se pone de rodillas y empieza a llorar) Pero, El Diablo... *sollozo* No lo entiendes, gringa. Había esperado toda mi vida por ese momento. }
{214}{}{(te agarra la manga) ¡Este es mi destino! ¡Es mi razón de vivir!}
{215}{}{(exhausta) Bueno. Iré a casa. Que pase lo que tenga que pasar.}


{220}{}{«¿Tú otra vez, gringo?»}
{1220}{}{«¿Tú otra vez, gringa?»}
{221}{}{«Ahí estás. Te estaba buscando, ¿estás bien?»}
{222}{}{(mira a otro lado)}
{223}{}{«¿Sabes quién te está buscando? Antonio, debes volver a casa.»}
{224}{}{(vuelve a mirarte) «¿Antonio? ¿En serio?»}
{225}{}{«Sí, señorita. Fue el quien robó la corona, no quería que murieras.»}
{226}{}{(se pone de rodillas y empieza a llorar) Pero, El Diablo... *sollozo* No lo entiendes, gringo. Desde que soy pequeña lo tenía claro, yo sabía que este día llegaría.»}
{1226}{}{(se pone de rodillas y empieza a llorar) Pero, El Diablo... *sollozo* No lo entiendo, gringa. Desde que soy pequeña lo tenía claro, yo sabía que este día llegaría.»}
{227}{}{«Pero, ser libre es mucho mejor.»}
{228}{}{(te agarra la manga) «¡Era mi destino! ¡Tenía que ir con El Diablo para salvar a todos los demás!»}
{229}{}{«Entiendo el por qué te sientes así. Pero en todo lo que he viajado, jamás he visto tanta maldad. Nadie sacrificaría un ser querido a un monstruo.»}
{1229}{}{«Entiendo el por qué te sientes así. Pero en todo lo que he viajado, jamás he visto tanta maldad. Nadie sacrificaría un ser querido a un monstruo.»}
{230}{}{(exhausta) «Ya... ya... Estaré bien. Pase lo que pase.»}
{231}{}{«Muy bien, te llevaré a casa.»}
{232}{}{«Espérame, debo asegurarme de que no haya ningún peligro.»}

{240}{}{¿Qué pasa?}
{241}{}{Sígueme.}
{242}{}{Espérame aquí.}
{243}{}{Vámonos.}
{244}{}{Estoy cansada.}
{245}{}{«Ya voy, espérame.»}
{246}{}{«Me siento cansada, quiero ir a casa.»}

{247}{}{«Espérame aquí, no te muevas.»}
{248}{}{«Sígueme, ya casi estamos.»}
{249}{}{«Ven conmigo, todo estará bien.»}

