{100}{}{Ves a Antonio.}
{101}{}{Ves a un niño con la ropa sucia y arrugada, sus ojos revelan preocupación.}
{102}{}{Esta corona era para Lucía. Yo quería dársela.}

#First dialogue
{200}{}{¿Qué quieres, gringo?}
{1200}{}{¿Qué quieres, gringa?}
{201}{}{¿A quién le dices gringo, chamaco?}
{202}{}{Solo bromeo. Soy Antonio, mis padres eran del norte. ¿Acaso tú igual?}
{203}{}{Sí, mi hogar está lejos. ¿Y tú? Todos están celebrando, ¿por qué tú no?}
{204}{}{Porque no me gusta. Ojalá terminara de una vez.}
{205}{}{¿Por qué?}
{206}{}{¿Cómo puedes celebrar el Día de la Vida si tanta gente ha muerto? El viejo y los demás se sienten felices porque no se murieron ellos. Babosos.}
{207}{}{Tienes razón, solo un idiota le agradecería a un santo que dejó morir a muchos.}
{208}{}{¡Exacto! Me agradas, gringo.}
{1208}{}{¡Exacto! Me agradas, gringa.}
{209}{}{Iré a ver el resto del pueblo. Nos vemos.}
{1209}{}{Iré a ver el resto del pueblo. Nos vemos.}
{210}{}{Oye, no deberías arruinarle el día a los demás. Todos merecen ser felices.}
{211}{}{Lo que tú digas...}
{212}{}{Hmm. Bueno, iré a divertirme. Adiós.}

#Re-dialogue
{220}{}{¡Hola!}
{221}{}{Hola, gringo.}
{1221}{}{Hola, gringa.}
{222}{}{¿Qué quieres, gringo?}
{1222}{}{¿Qué quieres, gringa?}
{223}{}{Nos vemos.}

{230}{}{¿Sabías que alguien robó la corona?}
{231}{}{No, no sé nada de eso.}
{232}{}{Bueno, te creo.}
{233}{}{Tú lo dijiste, querías que la fiesta terminara.}
{234}{}{(mira hacia el suelo)}
{235}{}{¿Así que fuiste tú?}
{236}{}{No quiero que coronen a Lucía.}
{237}{}{¿Por qué no? ¿Es malo?}
{238}{}{Eres un gringo, ¡no lo entiendes! Si se coloca la corona jamás podré... ser su... Y ella... La amo.}
{1238}{}{Eres una gringa, ¡no lo entiendes! Si se coloca la corona jamás podré... ser su... Y ella... La amo.}
{239}{}{Creo que estás siendo un egoísta, pequeño.}
{240}{}{Quizás tengas razón. ¡No me importa!}
{241}{}{¿En dónde la escondiste, niño?}
{242}{}{La enterré en el centro del monumento para que nadie lo encuentre.}
{243}{}{¿Cuál monumento?}
{244}{}{Es un monumento muy antiguo. Lucía y yo nos veíamos ahí en secreto, incluso escribimos nuestros nombres en los pilares. Así que pensé que sería el mejor lugar.}
{245}{}{Gracias por decírmelo, me lo hará más fácil. Adiós.}
{246}{}{A nadie le importan tus razones. ¡Dime en dónde la escondiste!}
{247}{}{Recuérdame en dónde escondiste la corona.}

{250}{}{Lucía está a salvo, pensé que la perdería para siempre. Gracias.}
{251}{}{De nada.}
{1251}{}{De nada.}
{252}{}{¿Es por eso que no querías celebrar con los demás? ¿Para salvarla?}
{253}{}{Sí, incluso quise ir con El Diablo para que Lucía no lo hiciera, pero el viejo pendejo me dijo que no, que el pueblo necesitaba hombres para trabajar.}
{254}{}{De verdad que estabas en problemas.}
{255}{}{Pero, por fin se acabó. Toma, llévate esta historieta. No tengo nada más que ofrecerte.}
{256}{}{Hmm, se ve interesante. Puede que me sea útil.}
{257}{}{Que cosa tan rara, le echaré un vistazo.}

{260}{}{¡Vi que Lucía escapaba de la iglesia! ¿Qué pasó? ¿Mataste al Diablo?}
{1260}{}{¡Vi que Lucía escapaba de la iglesia! ¿Qué pasó? ¿Mataste al Diablo?}
{261}{}{No te preocupes, lo tengo todo bajo control.}
{262}{}{¡Por favor, devuélveme a Lucía!}
{263}{}{Lo intentaré.}
{264}{}{No te prometo nada.}
