{100}{}{Ves a Lucía.}
{101}{}{Ves a una niña de traje ceremonial, brilla como el sol.}
{102}{}{Gracias, por todo.}
{103}{}{Muchas gracias.}
{104}{}{La corona ha sido devuelta a su dueña.}
{105}{}{Creo que esto es tuyo. Tómala y haz lo que quieras con ella.}
{106}{}{Es demasiado pronto para darte esto.}

{110}{}{}

{198}{}{«Buenas noches.»}
{199}{}{«Buenos días.»}

#Dialogue before the ceremony
{200}{}{Em... buenas noches.}
{201}{}{Em... buenos días.}
{202}{}{Ya debo irme.}
{203}{}{Hola, ¿quién eres? ¿Cómo te llamas?}
{204}{}{Me llamo Lucía... perdón, pero no te conozco.}
{205}{}{Sí, ¿es malo? ¿Qué es eso que llevas puesto? ¿Esta celebración es en tu honor? }
{206}{}{Pues... hoy me harán una reina. Es un gran honor para mí... (se tapa los ojos para esconder su alegría) Perdón, pero no debería hablar con desconocidos.}
{207}{}{Está bien, lo entiendo.}
{208}{}{(se cubre el rostro) Adiós.}
{209}{}{Iré a divertirme, adiós.}
{210}{}{«Hola, ¿puedo hablar contigo?»}
{211}{}{«Sí... me llamo Lucía.»}
{212}{}{«Eres muy tímida, pero tu vestido es muy impresionante. ¿La celebración es en tu honor?»}
{213}{}{«Hoy me convertiré en una reina, es nuestra tradición. Es un gran honor para mí...» (se tapa los ojos para esconder su alegría) «Dime, ¿qué piensas de nuestro pueblo y la celebración?»}
{214}{}{«Por supuesto. ¡Es el sitio más hermoso y amigable en el que he estado!»}
{1214}{}{«Por supuesto. ¡Es el sitio más hermoso y amigable en el que he estado!»}
{215}{}{«¿En serio? Ay, que bueno. Haré... h-haré lo que sea para que siga así. L-lo que sea.»}
{216}{}{«Claro, eres la reina, pero... No lo entiendo, ¿te sientes bien? O... ¿estás llorando?»}
{217}{}{(se cubre el rostro) «Estoy bien... Por favor, háblale a alguien más.»}
{218}{}{«Está bien, iré a celebrar.»}
{219}{}{«No es tan linda como mi Villa. No tienes la menor idea de lo preciosa que es.»}
{220}{}{«¿En serio? E-estaría encantada de ver tu hogar. Pero... n-nunca me iré de aquí. S-sé que no.»}
{221}{}{«No lo entiendo... ¿Te estás aguantado la risa o estás llorando?»}
{222}{}{«¿Sabes en dónde podría estar tu corona?»}
{223}{}{«¿Desapareció? Esto es muy malo... por favor, ¡encuéntrala! Tengo que estar en la ceremonia, ¡o se enojará el santo!»}
{224}{}{«Ya, ya. Hablaré con alguien más. Quizás vieron algo.»}


#Dialogue after the ceremony
{230}{}{(Está sentada en el suelo con una mirada triste)}
{231}{}{[Hecho]}
{232}{}{Oye, ¿estás bien?}
{233}{}{(Baja la cabeza a sus rodillas)}
{234}{}{¿Estás bien?}
{235}{}{(te empuja hacia atrás) ¡Sal de aquí, gringo! ¡El Diablo está aquí!}
{1235}{}{(te empuja hacia atrás) ¡Sal de aquí, gringa! ¡El Diablo está aquí!}
{236}{}{¿El Diablo? No lo entiendo, ¿acaso hay algo aquí abajo?}
{237}{}{El Diablo está muerto. (le das tu mejor sonrisa) ¡Muerto!}
{238}{}{(abre los ojos como platos) ¿Está muerto...? No... ¡No, no, no! (sale corriendo)}
{239}{}{Ve a respirar aire fresco, sé que te hará bien.}

{240}{}{«El Diablo está muerto.»}
{241}{}{«¿Te encuentras bien, pequeña?»}
{242}{}{«¿Está todo bien?»}
{243}{}{(te empuja hacia atrás) ¡Por favor, sal de aquí, gringo! ¡El Diablo está con nosotros!»}
{1243}{}{(te empuja hacia atrás) ¡Por favor, sal de aquí, gringa! ¡El Diablo está con nosotros!»}
{244}{}{«¿El Diablo? Pero... espera, ¿qué fue eso?»}
{245}{}{(abre los ojos como platos) ¿Está muerto...? No... No puede ser. ¡No, no, no! (sale corriendo)}
{246}{}{«Está asustada, pero, ¿por qué?»}

