{100}{}{Ves a Enrique.}
{101}{}{Estás viendo a un mexicano de aspecto rudo.}

{110}{}{}

#First dialogue
{200}{}{Hola. Mi nombre es Enrique. ¿Qué te trajo a nuestro pueblo?}
{201}{}{Llegué aquí por pura casualidad, no era mi intención estar aquí.}
{202}{}{Estos días, no nos llegan demasiados viajeros. Te haría más preguntas, pero estamos en medio de una celebración. Mi hija, Lucía, ha tenido el honor de ser la 'reina'.}
{203}{}{¿Qué se celebra?}
{204}{}{El Día de la Vida, le agradecemos a los santos porque todavía seguimos con vida. Al acabarse, coronamos a alguien. Es una forma de recordar que aunque estemos en el yermo, todos estamos juntos.}
{205}{}{Eso me suena a que debe ser una tradición entretenida. Voy a celebrar con los demás.}
{206}{}{Es una tradición extraña, pero no es asunto mío.}

#Re-dialogue
{220}{}{Hola, gringo.}
{1220}{}{Hola, gringa.}
{221}{}{Hola, amigo.}
{1221}{}{Hola, amiga.}
{222}{}{Adiós, Enrique.}

{230}{}{¿Sabías que la corona ceremonial ha desaparecido?}
{231}{}{Eso es raro, jamás había pasado antes, pero no pudo haber desaparecido así como así. Había mucha gente alrededor de la mesa, en especial niños.}
{232}{}{Entiendo.}
{233}{}{Eres un poco más abierto que los demás, ¿has salido de aquí?}
{234}{}{Sí, en mis tiempos viajé un poco a través de Sonora.}
{235}{}{Hay muchos niños en este lugar.}
{236}{}{Por supuesto, nuestros hijos nos dan una razón para sonreír y son nuestro futuro, incluso si la mayoría no llega a la adultez.}
{237}{}{¿Qué hay de Hilario? ¿Cuántos años tiene?}
{238}{}{Él es el jefe y siempre ha sido así, no me sorprende que siga en pie. Se vuelve más desagradable con cada verano, pero es gracias a él que seguimos con vida.}
{239}{}{¿Podrías contarme de algún sitio interesante en Sonora?}
{240}{}{¿De verdad? ¿Podrías mostrarme algún lugar interesante?}
{241}{}{La ciudad más cercana es Casa Nueva, al oeste. Sigue por esa dirección y verás las ruinas de Puerto Peñasco. Viaja al sur y encontrarás el fuerte en Hermosillo. Hemos estado aquí durante diez años, así que ni idea de cómo deben estar las cosas hoy en día.}
{242}{}{Enrique, no sé qué decir. No tengo palabras.}

{250}{}{¡Oye, amigo! Ahora que sabes de nuestro secreto, ¿qué opinas?}
{1250}{}{¡Oye, amiga! Ahora que sabes de nuestro secreto, ¿qué opinas?}
{251}{}{No sé qué decir. No tengo palabras.}
{252}{}{Ustedes son unos cultistas, están locos.}
{253}{}{¿Por qué voy a juzgarlos? Lo seguro es que no tenían otra opción.}
{254}{}{Ya pensaba que dirías eso. ¿Cuándo caímos tan bajo que estamos dispuestos a venderle nuestra alma al Diablo? Pero, no siempre fue así. Recuerdo los días en los que no estaba el Diablo. Eran días cálidos y hermosos...}
{255}{}{Es tu oportunidad, pueden empezar de nuevo.}
{256}{}{¿Así que está muerto? ¡Qué alivio! Pero sé que Hilario no lo dejará ir, nos mentirá y alegará que el Diablo sigue vivo. Ha estado quince años en el poder, eso lo ha cambiado. Quiero sacar a ese parásito de aquí, ayúdame, no todo el pueblo está en su contra, como yo lo estoy.}
{257}{}{Será un placer, ver como sale arrastrándose de la aldea será chistoso. Vamos a la iglesia.}
{258}{}{Déjame hablar con él, quizás pueda convencerlo de que se vaya.}
{259}{}{Yo no me meto más en esto, maté al monstruo y es todo lo que haré. Es problema tuyo.}

{260}{}{¿Nos ayudarás a deshacernos de ese fraude?}
{261}{}{Perdón, pero no es mi problema, es tuyo.}
{262}{}{¡Un poco más y lo mato yo, lo juro!}
{263}{}{Déjame hablar con él.}
{264}{}{Hilario ha muerto, ya no volverá a molestarte.}
{265}{}{Hilario se ha ido de pueblo, no volverá.}
{266}{}{¡Sí, por fin! ¡Adiós, Hilario! Santa Ana podrá prosperar ahora que el viejo y el monstruo se han ido. Ya puedo imaginarlo, no habrán más sacrificios, no habrán más mentiras. Gracias, amigo. Toma, quiero darte mi pistola como muestra de mi gratitud. Desde ahora en adelante, el santo de nuestra comunidad vas a ser *tú*.}
{1266}{}{¡Sí, por fin! ¡Adiós, Hilario! Santa Ana podrá prosperar ahora que el viejo y el monstruo se han ido. Ya puedo imaginarlo, no habrán más sacrificios, no habrán más mentiras. Gracias, amiga. Toma, quiero darte mi pistola como muestra de mi gratitud. Desde ahora en adelante, la santa de nuestra comunidad vas a ser *tú*.}
{267}{}{Siempre me alegra ayudar a alguien. Adiós, Enrique.}
{268}{}{¿Hay alguna otra cosa en la que pueda ayudarte?}
{269}{}{Pensándolo bien, ahora soy el jefe de la aldea. Quiero establecer una ruta comercial con Casa Nueva, no tenemos mucho que ofrecerles, pero debemos llegar a algún tipo de acuerdo. ¿Podrías contarle de nuestro interés? Si es posible, diles que envíen a una caravana para negociar con ellos.}
{270}{}{Vale, lo haré.}
{271}{}{Dudo que vaya hacia allá, pero, lo tendré en cuenta.}
{272}{}{¿No crees que ya hubieron suficientes muertes?}
{273}{}{Él seguirá sacrificando gente en nombre de la vanidad si no lo detenemos, entre más tiempo pase, más difícil será arreglarlo.}
{274}{}{Entonces, no hay por qué perder el tiempo. ¡A la iglesia!}
{275}{}{Piénsalo, es una iglesia y ya la han profanado lo suficiente. ¿De verdad quieres pecar otra vez?}
{276}{}{Tienes razón, pero si Hilario vuelve a sus viejas andanzas, nos afectará a todos.}
{277}{}{Me alegra que hayas entrado en razón, deja en paz al viejo.}
{278}{}{¿De qué hablas? Las vidas de Santa Ana pesan más que la suya. ¡Vamos a la iglesia y acabemos con esto!}
{279}{}{No te rindas tan fácilmente, quiero convencer a Hilario para que no debamos usar la violencia. Espérame aquí.}
{280}{}{Tenías razón - había que deshacerse de Hilario. Y eso fue lo que hice.}
{1280}{}{Tenías razón - había que deshacerse de Hilario. Y eso fue lo que hice.}
{281}{}{¿De qué hablas? Las vidas de Santa Ana pesan más que la suya. ¡Vamos a la iglesia y acabemos con esto!}
{282}{}{Casa Nueva está pasando por tiempos oscuros, olvídate de comerciar con ellos.}
{283}{}{Que noticias más amargas, tendremos que sobrevivir sin ellos. Gracias por el aviso.}
{1283}{}{Que noticias más amargas, tendremos que sobrevivir sin ellos. Gracias por el aviso.}
{284}{}{De nada.}
{285}{}{Hola, amigo. Hace un rato, nos llegó una caravana de Casa Nueva. Agradezco tu ayuda.}
{1285}{}{Hola, amiga. Hace un rato, nos llegó una caravana de Casa Nueva. Agradezco tu ayuda.}
{286}{}{Bueno, es que... Hilario también está muerto. No preguntes qué pasó.}
{287}{}{Una vez que Hilario se dio cuenta de que su poder se acabó, salió corriendo. No creo que regrese.}

{290}{}{¿Qué los llevó a esta situación?}
{291}{}{Es una larga historia. Empezó hace unos quince años.}
{292}{}{Hmph. Cambiemos de tema.}
{293}{}{Cuéntame más.}
{294}{}{Solíamos viajar por el desierto Sonorense para encontrar un lugar en donde vivir, éramos nómadas. Y un día, ese monstruo nos encontró. Empezó a acechar nuestra caravana y se llevaba a una persona o un animal, uno por uno. No podíamos luchar contra él, o salir corriendo - era demasiado rápido, demasiado fuerte.}
{295}{}{Te escucho...}
{296}{}{¡Ay no, qué miedo! Yo me voy.}
{297}{}{Y entonces, a Hilario se le ocurrió sacrificar a los animales para salvar a la gente. Pero el rebaño no tardó en morirse, por lo que empezamos a cederle a los viejos y a los enfermos. Y eventualmente, también se habían muerto todos. Pero, para ese entonces, El Diablo ya había comido lo suficiente y empezó a pedir menos sacrificios. Así que hallamos un balance.}
{298}{}{Comprendo.}
{299}{}{El Diablo también atacaba a los animales salvajes o a los saqueadores que nos amenazaban, nos hicimos su rebaño, pues nos comía cuando tenía hambre.}
{300}{}{¿Y siguieron haciéndole sacrificios?}
{301}{}{Cada cuantos meses, le entregábamos un sacrificio al que habíamos criado específicamente para ese propósito. Hilario lo convirtió en una ceremonia y predicaba una purificación divina. Así que vivíamos con el demonio... hasta que llegaste tú, gringo.}
{1301}{}{Cada cuantos meses, le entregábamos un sacrificio al que habíamos criado específicamente para ese propósito. Hilario lo convirtió en una ceremonia y predicaba una purificación divina. Así que vivíamos con el demonio... hasta que llegaste tú, gringa.}
{302}{}{Bueno, ojalá que puedan regresar a una vida normal. Adiós.}
{303}{}{Deberían estar avergonzados. Todos ustedes. En la Villa nos mantenemos unidos pase lo que pase. Escuchar esto me hace querer volver a casa. Adiós.}