{100}{}{Ves a un recién llegado.}
{101}{}{Estás viendo a un hombre vestido con ropa polvorienta, parece haber viajado millas con ella puesta.}
{102}{}{Esto es impresionante. Los Hojalateros son conocidos por sus habilidades, pero jamás me imagine esto...}
{103}{}{¿Qué le pasa a este pueblo? ¿Está maldito?}
{104}{}{...}

#First meeting
{200}{}{Vaya, vaya. Eres tú, verte aquí es una sorpresa.}
{201}{}{Y tú eres...}
{202}{}{¿Recuerdas esa carta que me entregaste en Fénix? Me tomó desprevenido, pensé que debía ser algún tipo de estafa. Y resulta que estaba equivocado.}
{1202}{}{¿Recuerdas esa carta que me entregaste en Fénix? Me tomó desprevenido, pensé que debía ser algún tipo de estafa. Y resulta que estaba equivocado.}
{203}{}{De acuerdo. Dime, ¿qué te trajo a este pueblo? Está perdido de la mano de Dios.}
{204}{}{}
{205}{}{}
{206}{}{Allí en el centro, hay una casa de baños abandonada. Estoy en la búsqueda de su dueño.}
{207}{}{¿Una casa de baños? ¿En medio del desierto?}
{208}{}{Sí, en este pueblo hay mucha agua, atrae a caravanas de todos lados. Aunque no todos pueden beber.}
{209}{}{¿Por qué buscas al dueño?}
{210}{}{Él es de mi familia. Su carta me estaba invitando a venir a trabajar acá. Así que, aquí estoy. Pero ha desaparecido.}
{211}{}{¿Te mudaste a otro pueblo así sin más?}
{212}{}{¿Por qué no? Tras la caída de la iglesia en Fénix, las cosas se pusieron muy mal de un momento a otro.}
{213}{}{¿Explosión? ¿A qué te refieres?}
{214}{}{¿Lo dices en serio? Toda la Ruta 10 está hablando de ello. La Catedral del Fuego le hizo honor a su nombre, se quemó y explotó.}
{215}{}{Vaya, que inesperado... ¿Has escuchado sobre tu tío? Quizás los lugareños digan algo.}
{216}{}{Los demás habitantes no saben nada. La casa de baños está cerrada y no se ha visto al dueño. Le hable al alcalde, me acusó de ser un estafador y me lanzaron a la calle.}
{217}{}{¿Cuál es el plan?}
{218}{}{Ni idea. Me quedaré un tiempo más, ojalá que llegue mi Tío. Si te enteras de algo, avísame, ¿bien? Estaré en tu deuda.}
{219}{}{Te deseo suerte con la búsqueda.}
{220}{}{Sí.}
{221}{}{Hasta luego.}
{222}{}{Quizás sea algún tipo de error.}
{223}{}{Lo dudo.}
{224}{}{Bueno, sigue viviendo entre sueños.}
{225}{}{O, quizás te haces pasar por un pariente suyo para tomar su lugar.}
{226}{}{Tonterías. No nos hemos visto en años. Fue mi tío el que envió la carta a través de los mensajeros, puedes verificarlo en los registros. Además, tú me entregaste la carta.}
{1226}{}{Tonterías. No nos hemos visto en años. Fue mi tío el que envió la carta a través de los mensajeros, puedes verificarlo en los registros. Además, tú me entregaste la carta.}

# Repeated dialogue at the parking lot
{250}{}{Ah, ahí estás. Pensaba sobre lo que hablamos antes. Somos dos forasteros en una ciudad, deberíamos apoyarnos, ¿no crees?}
{251}{}{Es mejor que eso no ocurra. Adiós.}
{252}{}{Claro que sí. Nos vemos luego.}
{253}{}{Por cierto, ¿cómo te llamas?}
{254}{}{Llámame Steve.}
{255}{}{De acuerdo, Steve. ¿Me podrías repetir lo que estás haciendo aquí?}
{256}{}{Hasta luego, Steve.}
{257}{}{¿Me puedes recordar a quién estás buscando?}

# Stage 1
{260}{}{¿Has ido al cementerio? Parece que tu tío está descansando allí.}
{261}{}{¿Cómo? ¿Está... muerto? Ya entiendo por qué el alcalde intentaba echarme. Pero, ¿qué pasó?}
{262}{}{Es una fosa común, a juzgar por eso, parece que aquí ha muerto mucha gente. ¿Sabes algo sobre eso?}
{263}{}{Pues, se dice que hace un tiempo hubieron algunas guerras de clanes. Es por eso que los lugareños cierran la boca si les preguntas sobre el pasado. Si mi tío acabó metido en todo eso, tendré que aceptarlo.}
{264}{}{¿Te irás de aquí con las manos vacías?}
{265}{}{Claro que no. Esa casa de baños era de mi tío, y yo soy un familiar suyo. Debería heredarla, ¿no?}
{266}{}{¿Lo dices en serio? ¿Te vas a quedar, incluso después de las amenazas?}
{267}{}{Verás.. Lo cierto es que las cosas tampoco me iban bien en Fénix. Apenas podía sobrevivir con el dinero de las luchas. Pero, aquí podría darle un nuevo comienzo al negocio de mi tío y ganarme la vida. ¿Por qué demonios no haría eso?}
{268}{}{Ah, ya veo. La muerte de tu tío fue todo un golpe de suerte, ¿no es así?}
{269}{}{¿Qué quieres decir con eso? Puedo darle un nuevo comienzo al negocio de mi tío y hacerme rico. Sería estúpido dejar que se me escape esta oportunidad.}
{270}{}{Bueno, pues, no es una mala idea. Vale la pena intentarlo. ¿Te hace falta un socio?}
{271}{}{Te estás arriesgando, socio.}
{272}{}{Ahora lo importante es ganarse el favor del alcalde. No quiere ni mirarme; sus guardias no me dejan acercarme. ¿Podrías hablar con él?}
{273}{}{¿Qué gano yo, si hago eso?}
{274}{}{Como siempre, la gente quiere ganar dinero. No temas; te pagaré una vez que tenga las chapas. Estamos juntos en esto, solo necesito que seas paciente.}
{275}{}{Veré que puedo hacer con respecto al alcalde.}
{276}{}{Lo agradezco, socio. ¿Qué haría sin ti?}
{1276}{}{Lo agradezco, socia. ¿Qué haría sin ti?}
{277}{}{Nos vemos luego.}
{278}{}{Me da miedo hablarle a ese tirano, pídeselo a otra persona.}
{279}{}{Está bien. No te preocupes, ya se me ocurrirá algo. Gracias por la ayuda, de todas formas.}
{280}{}{Hasta luego.}
{281}{}{Sólo estoy de paso, no tengo tiempo para esperar a los clientes.}

# Stage 2
{300}{}{Y, ¿qué te dijo el alcalde? ¿Has podido hablar con él?}
{301}{}{No, no he tenido la oportunidad. Espérame.}
{302}{}{El Alcalde está tieso. Podrás apoderarte de la casa de baños.}
{303}{}{¿Está muerto? ¿Qué carajos le pasa a esta ciudad? No me cuentes los detalles. Pero tienes razón, tengo que adueñarme de la casa de baños antes de que alguien más se meta.}
{304}{}{De acuerdo, nos vemos allí...}
{305}{}{Puedes hacer negocios, el alcalde te ha dado el permiso de tener la casa de baños.}
{306}{}{Sí que sabes como negociar. Vamos a entrar a la casa de baños, antes de que el alcalde cambie de parecer.}
{307}{}{De acuerdo, nos vemos allí...}
{308}{}{El alcalde quiere que te vayas del pueblo. Ahora.}
{309}{}{¿Eh? ¿Qué te pasó? ¿Estás de su lado? ¿Acaso no ves que esto es injusto? La casa de baños me pertenece por derecho, y ahora está vacía, ¿no es así?}
{310}{}{Tienes razón, intentaré convencer al alcalde.}
{311}{}{Es mejor que te largues, si te gusta tener la cabeza sobre los hombros.}
{312}{}{Ya escuché suficiente. Pensaba que seríamos socios, pero resulta que eres como cualquier otro hijo de puta corrupto.}
{1312}{}{Ya escuché suficiente. Pensaba que seríamos socios, pero resulta que eres como cualquier otra perra corrupta.}
{313}{}{Hablaremos de esto, pero en otro momento.}
{314}{}{No estoy jugando. Lárgate de aquí.}
{315}{}{No me sacarás de aquí, esa casa es el legado de mi familia y no lo voy a dejar atrás.}
{316}{}{Entonces haré que te vayas, no me dejas otra opción.}
{317}{}{Has lo que quieras.}
{318}{}{Voy a contar hasta cinco, y sacaré mi arma. Uno... dos...}
{319}{}{Oye, espera...}
{320}{}{...tres.}
{321}{}{No seas así, era una broma. Quédate, es cosa tuya.}
{322}{}{Ya me voy, mira, ya voy a la puerta.}
{323}{}{Y ni pienses en volver.}

{330}{}{Este lugar era hermoso, y mira lo que los lugareños le hicieron. Esos salvajes.}
{331}{}{Si no te importa, voy a echar un vistazo.}
{332}{}{¿Cuál es el problema?}
{333}{}{Si ignoras el hecho de que se han robado todo lo valioso, el verdadero problema yace en el sistema para calentar el agua.}
{334}{}{¿No funciona?}
{335}{}{Alguien intentó robárselo, pero mientras le metían la mano, se les cayó y lo dañaron. Todavía no se me ocurre cómo repararlo.}
{336}{}{Bueno, te deseo suerte. No cuentes conmigo en esta.}
{337}{}{Déjame echarle un vistazo, quizás pueda reparar esta cosa con algo de chatarra.}
{338}{}{El tanque está como nuevo, podrás calentar el agua y darte un baño.}
{339}{}{¿Conseguiste repararlo? ¡Genial! Ahora sí que entrará gente al negocio. Gracias por ayudarme, pásate por aquí si necesitas una ducha.}
{1339}{}{¿Conseguiste repararlo? ¡Genial! Ahora sí que entrará gente al negocio. Gracias por ayudarme, pásate por aquí si necesitas una ducha.}
{340}{}{Lo pensaré.}

{350}{}{¿Cómo estás?}
{351}{}{¿Sientes que ya se acumuló la mugre? ¿Quieres una ducha?}
{352}{}{¿Te gustaría ducharte? Encontré un poco de sal de mar, es vieja.}
{353}{}{¿Qué tal si te das un baño? Hace calor.}
{354}{}{De verdad necesitas un baño. No te preocupes, no te cobraré de más.}
{355}{}{El baño es gratis. Entra, es hora de quitarte la mugre.}
{356}{}{Nos vemos luego, Steve.}

#Rest
{400}{}{Necesito quitarme la suciedad y el polvo. ¿Cuánto cuesta una ducha?}
{401}{}{Sólo cobro la leña y el agua. Serán }
{402}{}{ chapas.}
{403}{}{No puedo permitirme eso. Quizás otro día.}
{404}{}{Suena bien, dame un segundo...}

{410}{}{Ya ha pasado un tiempo, tu negocio debe ser exitoso.}
{411}{}{No, no exactamente. Las caravanas van y vienen, así que hay períodos en los que nadie entra. No todos pueden derrochar para un lujo así. Pero gano lo suficiente para seguir adelante.}
{412}{}{¿Qué hay de nuestro trato?}
{413}{}{Se me está agotando la paciencia. ¿Y mi parte de las ganancias?}
{414}{}{¿De qué hablas? No te debo nada. Ahora vete, ya es hora, tengo que limpiar la bañera.}
{415}{}{¿Cómo?}
{416}{}{Eres escoria.}
{417}{}{Por supuesto, somos socios. He apartado algunas de las ganancias para ti, son 200 chapas. Si me disculpas, la bañera no se limpiará sola.}
{418}{}{Gracias, fue un placer. Ten un buen día, Steve.}
{419}{}{¿Nada más? Tu negocio es una mugre, Steve. Y cambia el letrero, es horrendo.}
{420}{}{Si no me darás las chapas por las buenas, me las llevaré por las malas. Quieto, maldito estafador...}

{430}{}{Los Hojalateros enviaron a un representante a este lugar. ¿Alguna idea de qué le pasó?}
{431}{}{Vi el Hojalatero, pero no habló con los demás, fue a hablarle al alcalde de inmediato. Después de eso, no lo volví a ver.}
{432}{}{Algo es algo. Adiós.}
{433}{}{No sirves de nada. Adiós.}
