{100}{}{Ves a un huérfano.}
{101}{}{Ves a un chico desaliñado con una mirada salvaje.}
{102}{}{Hrrr...}
{1102}{}{Ma... má... hrrr...}
{103}{}{Tengo zapatos.}
{104}{}{¡Vaya, muchas gracias!}
{105}{}{Un cambio de zapatos hace feliz a un niño.}
{106}{}{Has recibido: (}
{107}{}{).}

{200}{}{(En la vereda, ves a un niño con una apariencia salvaje y desaliñada. Su ropa está raída y manchada, está observando tu reacción cautelosamente, pues lanza un objeto de metal entre sus manos. Tiene una apariencia sospechosamente similar a una granada.)}
{201}{}{Oye, niño. Esa cosa es peligrosa, ¿sabías eso?}
{202}{}{(deja de lanzar la granada y se pone tenso, como si esperara que fueras a atacarlo) No. Soy. Un. Niño.}
{203}{}{Sí, eh, lo que sea. Pero esa cosa es peligrosa, no deberías hacer eso.}
{204}{}{No. Eres un niño. Un infante. Y estás sosteniendo algo que es extremadamente peligroso.}
{205}{}{(el niño guarda su granada en su bolsillo y escupe en la vereda) ¿Y qué?}
{206}{}{De acuerdo, ahí nos vemos.}

{210}{}{¿Qué quieres?}
{211}{}{Nada. Olvídalo.}

{212}{}{Mmm, linda ropa. Quiero ropa así. Pero es demasiado brillante, debe ser un color distinto para camuflarse con la arena, o los enemigos te encontrarán y te matarán.}
{213}{}{Bueno, sí, pero este mono no es para el combate, sabes..}
{214}{}{Pides demasiado.}
{215}{}{No te me acerques, cara fea.}
{1215}{}{No te me acerques, vieja fea.}
{216}{}{¡Un Escudo Azul! ¡Hay un bandido aquí!}
{217}{}{Oh, no...}
{218}{}{Pequeño demonio...}

{220}{}{Cuando un ranger te dije que bajes tu arma, tienes que hacerle caso, niño.}
{221}{}{(te da una mirada confundida, luego mira a la granada, otra vez te mira y niega con la cabeza)}
{222}{}{Hazme caso, niño. No deberías jugar así con una granada, he visto gente hacerse daño con esas cosas.}
{223}{}{No te preocupes, ya te acordarás de mí.}
{224}{}{¿Qué les pasó?}
{225}{}{Es una pena. La explosión les arranca las manos, luego se revientan sus ojos y se les caen de las cuencas. Si viven, sufren por horas...}
{226}{}{No es nada especial. Sigue jugando y lo verás por ti mismo.}
{227}{}{(El niño te lanza la granada y corre a otro lado)}
{228}{}{Oye, todavía no te cuento lo peor...}
{1228}{}{Oye, todavía no te cuento lo peor...}

{230}{}{Quiero esa granada. ¿Hacemos un trueque?}
{231}{}{¿Qué tienes?}
{232}{}{Veamos...}
{233}{}{(Espera tu oferta.)}
{234}{}{[Hecho]}

{240}{}{¿Sabes qué pasará si le quitas la argolla?}
{241}{}{Sí.}
{242}{}{Bueno, me alegro por ti. Adiós.}
{1242}{}{Bueno, me alegro por ti. Adiós.}
{243}{}{No, no sabes. Esa cosa hará una canción genial. Vamos, inténtalo.}
{244}{}{(lo piensa por un momento y coloca su dedo en la argolla)}
{245}{}{Espera, no hagas eso. Controla tus impulsos.}
{1245}{}{Espera, no hagas eso. Controla tus impulsos.}
{246}{}{[Deja que arranque la argolla]}

{250}{}{¿Sabes qué pasará si quitas la argolla?}
{251}{}{Lo sé.}
{252}{}{No, no sabes. Primero, la fuerza de la explosión te arrancará los brazos. Caerán al piso y será un baño de sangre.}
{253}{}{(te escucha con los ojos abiertos)}
{254}{}{Luego, la metralla se abrirá paso a tu pecho y estómago. Tus intestinos explotarán y empezarás a ahogarte en tu propia sangre.}
{255}{}{(te escucha con una respiración agitada)}
{256}{}{La metralla también te romperá los ojos, haciendo que se salgan de las órbitas. Quedarás ciego y caerás inconsciente. Y al despertarte, estarás en un dolor inimaginable durante horas bañado en tu propia sangre, hasta que...}
{257}{}{(el niño lanza la granada y sale corriendo)}
{258}{}{Oye, todavía no te cuento lo peor...}
{1258}{}{Oye, todavía no te cuento lo peor...}


{260}{}{Dame la granada. Ahora.}
{261}{}{(al ver que fanfarroneas, hace un sonido burlesco)}
{262}{}{Vaya...}
{263}{}{}
{264}{}{Dame la granada y nadie saldrá herido. No te haré nada.}
{265}{}{(se eriza como un cachorro en peligro)}
{266}{}{¿Me estás escuchando? Dame la granada. AHORA.}
{267}{}{No temas, no quiero herirte.}
{268}{}{(Al ser intimidado, te entrega la granada, pero rápidamente recobra la cabeza y sale corriendo despavorido)}
{269}{}{Bien hecho, pequeña mierda.}
{270}{}{Buen chico.}

{271}{}{¿Jugamos un juego? Si pierdo, te daré 5 chapas, si gano yo, me das la granada.}
{272}{}{(Sus ojos se llenan de emoción) Bueno.}
{273}{}{Genial, empecemos...}
{274}{}{Hagámoslo luego, tengo otras cosas que hacer.}
{275}{}{¿Jugamos un juego? Si pierdes, me darás la granada.}
{276}{}{No, no soy tan tonto.}
{277}{}{Sí, lo que tú digas.}
{278}{}{Sí, ya veo. Adiós.}
{279}{}{No tienes las 5 chapas necesarias para jugar.}
{280}{}{¡No!}
{281}{}{Oh, sí. La granada ahora es mía. Así es la vida, bebé.}
{282}{}{Cállate de una vez, ahora me pertenece.}
{283}{}{¡Ja! No puedes vencerme.}
{284}{}{Bueno, pues, ya lo veremos luego..}
{285}{}{Sigue burlándote, y voy a quitarte mis chapas y tu granada.}

{290}{}{Niño, ¿en dónde están tus padres?}
{291}{}{No tengo. ¿Por qué te importa?}
{292}{}{Ah, perdón. No sabía.}
{1292}{}{De verdad lo siento, no lo sabía.}
{293}{}{De acuerdo. Deja de ser tan maleducado.}

{300}{}{[Agarra la manivela de la caja musical y dale cuerda]}
{301}{}{(El niño escucha fascinado la melodía; la sorpresa aparece de repente en su rostro salvaje, que no ha conocido los sentimientos de un niño desde hace mucho tiempo.)}
{302}{}{Es genial, ¿no?}
{303}{}{(El niño asiente la cabeza con felicidad, expresando en cada forma posible su deseo de poseer un objeto así)}
{304}{}{Aquí tienes.}
{305}{}{[Entrégale la caja musical, pero aléjala un momento después]}
{306}{}{(el niño sonríe con nerviosismo, expresando en cada forma posible su deseo de poseer un objeto así.)}
{307}{}{¿Eh? [Hazlo otra vez]}
{308}{}{(el niño frunce el ceño, y se echa un poco para atrás)}
{309}{}{Aquí tienes.}
{310}{}{(El niño agarra la caja musical, mientras las emociones de una felicidad puramente infantil aparecen en su rostro por la primera vez en su vida.)}
{311}{}{Ahora dime, ¿en dónde encontraste esa granada?}
{312}{}{En la escuela abandonada de por allá. Pero los forajidos suelen estar allí, es peligroso.}
{313}{}{Ellos no me preocupan. Llévame allá.}
{314}{}{Es mío. No te lo daré porque sí.}
