{100}{}{Ves a un guardaespaldas de aspecto firme.}
{101}{}{Ves a un hombre bien equipado, te observa como ojos de halcón.}
{102}{}{Vuelve con los Hojalateros, pedazo de chatarra. No queremos verte aquí.}
{103}{}{E-eres tú... ¿Qué quieres? ¡Sal de aquí!}
{104}{}{Hora de salir de aquí...}
{105}{}{¡Oye, oye! ¡Yo no me voy a meter en esto!}
{106}{}{Veo que es momento de que me vaya de esta ciudad. Mierda, y eso que todo iba tan bien...}

{200}{}{El Don y los demás se encuentran en el bar abandonado, pasó algo por allá, pero no sé el qué.}
{201}{}{El bar, entiendo. Gracias, te veo luego.}
{202}{}{¿Y por qué no estás allá?}
{203}{}{Tengo que cuidar la mansión, el Don tiene todas sus riquezas aquí adentro.}
{204}{}{Comprendo. Entonces, debo ir al bar...}

{210}{}{El Don está muerto. ¿Me escuchas? ¡Muerto! ¿Entiendes lo que eso significa para la ciudad?}
{211}{}{Estás exagerando, cálmate.}
{212}{}{¿Quieres que me calme? Por fin tenía un trabajo decente, y ahora tendré que volver a la calle. Sin trabajo, sin chapas, sin conexiones. ¿Qué voy a hacer ahora?}
{213}{}{Pero ahora la ciudad es libre, él era un tirano. ¿Acaso no son buenas noticias?}
{214}{}{Claro, ¡ESTOY MUY FELIZ! Acabo de perder un buen empleo, era ese tirano el que me lo daba. Y ahora, por ese maldito accidente, tendré que volver a la calle. ¿Qué voy a hacer ahora?}
{215}{}{Encontrarás otro trabajo, ya no eres un niño. Adiós.}
{216}{}{Ojalá que encuentres otro empleo. Buena suerte.}
{217}{}{Jeje.}
{218}{}{¿Eh?}
{219}{}{¿Qué quieres?}
{220}{}{La verdad, nada.}
{221}{}{Tu cabeza.}

{230}{}{Em, hola. El Don está arriba.}
{231}{}{Ah, eres tú. El Don te estaba buscando, quiere hablar contigo}
{232}{}{Necesito hablar con él.}
{233}{}{Ajá.}

{250}{}{Eh, oye, un segundo. ¿A dónde vas?}
{251}{}{Estoy dando un paseo por la ciudad.}
{252}{}{Eso es un poco sospechoso, pero... No le daré importancia, sólo por hoy.}
{253}{}{¿Cómo? ¿A qué no le darás importancia?}
{254}{}{Pues... Mira, esta es la residencia de Don Bustos. No le gusta NADA que alguien se ande dando vueltas por ahí. ¿Lo entiendes? Muévete, y no causes problemas.}
{255}{}{De acuerdo, ya entendí. Nos vemos.}
{256}{}{Sí, lo entiendo. Por cierto, ¿qué puedes contarme acerca del Don? ¿Quién es y qué hace?}
{257}{}{Esta mansión es muy lujosa, ¿quién vive aquí?}
{258}{}{Don Bustos. Es el alcalde de nuestra ciudad.}
{259}{}{Entonces debería habla con él. ¿Recibe visitas?}
{260}{}{Puede ser. Aunque, es mejor que tengas una buena razón para hablarle, porque no le gusta que lo molesten con pequeñeces.}
{261}{}{Debo hablar con él, quiera o no. Adiós.}
{262}{}{¿Entonces es el alcalde de la ciudad? Háblame de él.}
{263}{}{Gracias, era todo lo que quería saber.}
{264}{}{¿Coo-coo?}
{265}{}{¿Eh?}
{266}{}{¡Ah!}

{270}{}{¿Es cierto que Bustos tiene a un forajido tras las rejas?}
{271}{}{Sí, en el baño. Lo estaban torturando hace poco. Aunque, esa pequeña sabandija es bastante dura, no podrás romperlo tan fácilmente.}
{272}{}{Ya veo.}

{300}{}{¿Qué puedes contarme del alcalde?}
{301}{}{Es el Don Alfred Bustos. Es el alcalde de nuestra ciudad y líder de la cámara de comercio. Y, es mi jefe. Aunque, yo sigo en libertad condicional.}
{302}{}{Pero, ¿por qué le dicen Don?}
{303}{}{Pues, es eso, un Don. Suena genial. La gente empezó a llamarlo así cuando asumió el control de la ciudad.}
{304}{}{¿Crees que esté contratando más guardias?}
{305}{}{No estoy seguro. Deberías preguntarle tú.}
{306}{}{¿Qué hay de ti? ¿Quién eres?}
{307}{}{Cuéntame más acerca de Don Bustos.}

{310}{}{¿Quién eres tú?}
{311}{}{Sólo soy un guardia de seguridad.}
{312}{}{¿Eres de por aquí?}
{313}{}{No, mi comunidad estaba cerca de Fénix, pero colapsó, así que fui hacia la ciudad. Tampoco me fue bien allá, así que me uní a una caravana para ganarme unas chapas. Pero me dejaron aquí tirado. No los he visto desde ese entonces. Ni siquiera me pagaron todo lo debido.}
{314}{}{Entonces, ¿desde ese día que trabajas como guardia?}
{315}{}{No, sólo he estado aquí unos meses. El Don necesitaba guardias, y no quedaba nadie a quién contratar en la ciudad. Si no hubiera sido así, no tendría este trabajo.}
{316}{}{Parece que fue muy duro. De todas formas, nadie necesita a un flojo como tú.}
{317}{}{¡Yo no soy ningún flojo! ¿Y por qué me dices esas cosas? Ocúpate de tus asuntos, yo no tengo por qué escucharte.}
{1317}{}{¡No soy ningún inútil! No pienses que tus encantos funcionarán conmigo, mujer. Lárgate, no tengo por qué escucharte.}
{318}{}{Ya, ya.}
{319}{}{Tengo que irme.}
{320}{}{Por cierto, casi no hay nadie en las calles, ¿por qué?}
{321}{}{No estás en Fénix, no hay tantas personas. Aunque, yo tampoco lo entiendo. Aquí hay bastantes chapas, y las caravanas siempre pasan por aquí cerca.}
{322}{}{Empezaba a creer que esto era un pueblo fantasma. Iré a ver qué encuentro por ahí.}
{323}{}{Me parece que te contrataron porque no había nadie más. Pierdo el tiempo contigo.}
{324}{}{El Don supo que eras especial y por eso te contrató, no hay duda. Debo hablar con él.}
{325}{}{Eso es muy injusto. No deberían haberte tratado así.}
{326}{}{Exactamente. Ojalá que esos tipos hayan sido devorados por escorpiones. Pero gracias a ellos tengo un trabajo que paga bien, no puedo quejarme.}
{327}{}{Tuviste suerte. Eso es todo.}
{328}{}{Es hora de que vaya a hablarle a tu jefe. Adiós.}
