{100}{}{Ves a Christina.}
{101}{}{Estás viendo a una chica de mirada astuta y ansiosa. Parece que no ha aprendido mucho debido a su vida fácil.}
{102}{}{Estás viendo a una chica de mirada apenada. Parece que los sucesos recientes han hecho que reflexione profundamente.}
{103}{}{Vaya, ¿cómo vas al baño con esa cosa puesta?}
{104}{}{Papá... papá... se nos fue...}
{105}{}{¿En dónde conseguiste eso? Escóndelo antes de que los demás lo vean, los guardaespaldas de mi papá abrirán fuego a cualquier forajido que vean.}
{106}{}{¿Qué está pasando? ¿En dónde está mi papá?}
{107}{}{Papá ya no está, y Sullivan se apoderó de la ciudad. Y ahora, también soy suya. ¿¡Cómo fue que todo terminó así!?}

{110}{}{Z-z-z...}
{111}{}{Hrr...}
{112}{}{...Papá, es muy temprano...}
{113}{}{...No estoy soñando...}
{114}{}{Estoy... durmiendo...}
{115}{}{...Es... un sueño...}
{116}{}{¿Sabes qué hora es?}
{117}{}{Tengo sueño.}
{118}{}{No me despiertes.}
{119}{}{Déjame dormir.}

{120}{}{*Tarareando*}
{121}{}{Es un buen día para hacer bromas.}
{122}{}{¿Qué me dices de una partida de póquer?}
{123}{}{Necesito pedirle más chapas a mi papi.}
{124}{}{Estaré bien, papá me perdonará.}
{125}{}{Ah, que aburrimiento...}
{126}{}{¿Qué debería hacer?}
{127}{}{Agua, chapas. Chapas, agua. ¿No saben hablar de nada más?}
{128}{}{Fénix tiene luces de neón, ojalá pudiera verlas de nuevo.}
{129}{}{Las cosas están aburridas sin el bar.}

{130}{}{Ah...}
{131}{}{*Suspiro*}
{132}{}{Ni siquiera puedo jugar a las cartas.}
{133}{}{¿Por qué las cosas tuvieron que acabar así?}
{134}{}{Estoy en una historia terrible.}
{135}{}{Supongo que no podré vivir como antes.}
{136}{}{No entiendo, ¿por qué llegamos a esto?}
{137}{}{¿Por qué los demás están tan enojados?}
{138}{}{}
{139}{}{}

#Acquaintance
{200}{}{Ah, holi. Siempre es interesante ver una cara nueva, me llamo Christina. ¿Por cuánto tiempo te vas a quedar?}
{201}{}{Bueno, yo...}
{202}{}{Anda, quédate, este es un buen lugar. Pero la ciudad es aburrida, obvio. Me muero, porque no puedo ir a apostar tampoco.}
{203}{}{Quizás me quede, pero necesito hablar con el alcalde.}
{204}{}{Como siempre. Bueno, anda, debe estar en su oficina. Recuerda tocar la puerta antes de pasar.}
{205}{}{De acuerdo.}
{206}{}{No estoy de humor para hablar. Necesito ver qué hay por aquí.}
{207}{}{¡Que aburridoooo! Bueno, anda. Ojalá cambies de parecer. Pero, no te pasees por nuestra casa sin hacer nada, a mi papá no le gusta.}
{208}{}{Está bien.}
{209}{}{No me importan los gustos de tu papá.}

{210}{}{Ah, holi.}
{211}{}{Adiós.}
{212}{}{Quiero hacerte preguntas sobre la ciudad.}
{213}{}{Eh, mira, no quiero hablarte de cosas aburridas, ¿sí? Si me molestas, llamaré a mis guardaespaldas.}
{214}{}{Bueno, quédate sola, perra. Es obvio el por qué no le interesas a nadie.}
{215}{}{¿Por qué esta ciudad es tan poco amistosa? No importa.}

#A game
{220}{}{Ah, holi. ¿Quieres jugar a las cartas?}
{221}{}{Vamos a jugar. Apostaré 10 chapas.}
{222}{}{Ah, holi. ¿Quieres jugar a las cartas? Hace tanto que no juego con alguien más, me muero de aburrimiento.}
{223}{}{Lo siento, pero no apuesto.}
{224}{}{Me parece que te da miedo perder.}
{225}{}{Eh, no lo creo. Adiós.}
{226}{}{¿Es con apuestas?}
{227}{}{¡Pues claro! Si no apuestas nada, el juego es aburrido. Si sabes que puedes perder tus cosas, ahí empieza la diversión.}
{228}{}{Em, ¿estás segura de que tienes chapas para apostar?}
{229}{}{¡Obvio! Mi papá es el jefe de la ciudad, incluso si pierdo, él me dará más. Tiene una caja fuerte llena de chapas.}
{230}{}{Lo siento, pero no puedo perder el tiempo jugando a las cartas. Quizás otro día.}
{231}{}{Que pena. Bueno, adelante, ve a hacer tus cosas 'importantes'.}
{232}{}{¿Sabes? Debería relajarme un rato. Voy a apostar 10 chapas.}
{233}{}{Eh, adiós.}
{234}{}{De acuerdo, juguemos. Apostaré 10 chapas.}
{235}{}{Genial, esto se pone interesante.}
{236}{}{Y estaría haciendo lo correcto. Deja de gastar su dinero.}
{237}{}{Nos vemos luego, no te aburras.}
{238}{}{Ay, parece que no tengo las chapas suficientes...}
{239}{}{[Empieza la partida]}
{240}{}{¡Hurra! ¡Gané!}
{241}{}{¿Cómo? No, dame una revancha.}
{242}{}{Tengo que irme.}
{243}{}{¿Qué? ¿Tan temprano? Pero si recién empezamos. Bueno, está bien. Juntarme contigo es algo aburrido.}
{244}{}{Adiós.}
{245}{}{¿Qué? ¿Perdí? Ay, no, papá me va a matar... Pero... sólo son 10 chapas. La pasé bien contigo.}
{246}{}{¿Quieres jugar un poco más?}
{247}{}{Tengo que irme.}
{248}{}{No, creo que papá no me dará más dinero para apostar.}
{249}{}{Pfft. ¡Aburridooo!}

#Questions
{300}{}{¿Quién eres?}
{301}{}{Soy Christina. ¿Acaso perdiste tu memoria?}
{302}{}{¿Eres la hija del alcalde?}
{303}{}{Bueno, sí. ¿Acaso no nos parecemos? Mira - tengo su nariz y sus ojos.}
{304}{}{Exacto, y me da la sensación de que de verdad debería hablarle a tu padre. Ahora.}
{305}{}{Eso es bueno. Debes saber mucho de esta ciudad, ¿no?}
{306}{}{¿Qué puedes contarme sobre la ciudad?}
{307}{}{Sólo que aquí es aburridísimo. Aunque hay temporadas en las que vienen un montón de caravanas, en ese entonces pasan muchas cosas interesantes.}
{308}{}{Que interesante. Pero, ¿quién eres?}
{309}{}{No me sirves. Iré a buscar a alguien que sí sepa.}
{310}{}{¿Por qué hay un cementerio tan grande en el este de la ciudad?}
{311}{}{¿Por qué no? La gente muere y necesitan ser enterradas en algún sitio. ¿No es así en los demás lugares?}
{312}{}{Jamás había visto un cementerio tan grande.}
{313}{}{No lo sé, he estado aquí mi vida entera y sólo he ido una vez a Fénix.}
{314}{}{Tengo que irme.}

{320}{}{Hola, ¿cómo estás?}
{321}{}{Sólo quería ver cómo estabas. Tú puedes. Adiós.}
{322}{}{¿Quieres jugar a las cartas?}
{323}{}{No, ya no juego a las cartas. Ya no juego a nada.}
{324}{}{Lo entiendo. Adiós.}
{325}{}{Y, ¿qué querían los forajidos de ti?}
{326}{}{Querían vengarse de mi padre por las atrocidades que cometió. Yo no sabía de las cosas horrendas que hizo en esta ciudad.}
{327}{}{Ya veo. No lo pienses mucho.}

{330}{}{Ah, eres tú... Mataron a mi papá, ¿sabes?}
{331}{}{Sí, lo vi con mis propios ojos. ¿Cómo estás?}
{1331}{}{Sí, lo vi con mis propios ojos. ¿Cómo estás?}
{332}{}{Estoy bien. Lo digo en serio. Pero mientras me tenían de rehén, los forajidos hablaban de mi padre. Dijeron que le robó el poder al alcalde anterior y que mató despiadadamente a la mitad de los ciudadanos que estaban en contra de su poder. Yo era demasiado joven para recordar todo eso. ¿Es verdad?}
{333}{}{Deja de ser una ingenua, abre los ojos - cualquier forma de poder es violenta. Tu papá es sólo un ejemplo de eso.}
{334}{}{Lo entiendo... Puede que haya sido un tirano y que haya cometido esos terribles crímenes. Pero para mí, él era... mi papá. Él siempre cumplía mis deseos y me daba lo mejor. ¿Cómo es que las cosas acabaron así?}
{1334}{}{Lo entiendo... Puede que haya sido un tirano y que haya cometido esos terribles crímenes. Pero para mí, él era... mi papá. Él siempre cumplía mis deseos y me daba lo mejor. ¿Cómo es que las cosas acabaron así?}
{335}{}{Bienvenida a la realidad. Este mundo está hecho de sangre.}
{336}{}{Sí, ahora lo entiendo. Y voy a hacer todo lo que pueda para evitar que esto ocurra otra vez.}
{337}{}{Eso depende de ti. Yo he terminado mis asuntos en esta ciudad. Es hora de que me vaya.}
{338}{}{Eso parece. De verdad lo siento.}
{339}{}{Al menos te amaba, eso quiere decir que en su interior no era un tirano. Es sólo que las cosas terminaron así.}
{340}{}{Espera, seguramente vas a necesitar chapas para el viaje. Toma, llévatelas. Es lo que me quedaba en mis bolsillos. Tú las necesitas más.}
{341}{}{Gracias, y adiós.}
{342}{}{Espera, seguramente vas a necesitar chapas para el viaje. Toma, llévatelas. Es lo que me quedaba en mis bolsillos. También incluí lo que perdiste en las cartas. Tú las necesitas más.}
{1342}{}{Espera, seguramente vas a necesitar chapas para el viaje. Toma, llévatelas. Es lo que me quedaba en mis bolsillos. También incluí lo que perdiste en las cartas. Tú las necesitas más.}
{343}{}{Te deseo suerte, es hora de que me vaya, tengo un largo viaje por delante.}
{344}{}{Ten cuidado allá afuera.}
{345}{}{Adiós.}
{346}{}{Ah, eres tú... Me salvaste, siempre te estaré agradecida.}
{347}{}{Entonces, ¿por qué la cara larga?}
{348}{}{Oye, ¿en dónde están esos ojos ansiosos de una chica joven e ingenua?}
{349}{}{Al menos te ama. Eso quiere decir que en su interior, no es ningún tirano. Es sólo que las cosas terminaron así.}

{350}{}{¿Sabes qué pasó con el embajador de los Hojalateros?}
{351}{}{Esto no te lo dije yo, pero... Digamos que ya está en la tumba. Si no me crees, ve al cementerio.}
{352}{}{Mierda, no me gusta como suena eso...}
{353}{}{No, no lo sé.}
{354}{}{De acuerdo.}
