{100}{}{Ves a un habitante de Casa Nueva.}
{101}{}{Ves a un pueblerino escuálido, no parece ser muy amigable.}

{110}{}{No me importa.}
{111}{}{Le di su merecido.}
{112}{}{*Te ignora*}
{113}{}{A la mierda todo.}
{114}{}{Lo siento, no sé que estaba pensando.}

{120}{}{¿Tú otra vez? Ya te lo dije, si no pagas, no hay...}
{121}{}{¡DAME AGUA! ¡Se la arrebataste a los ciudadanos!}
{122}{}{¿De qué hablas? Cuidado con lo que dices...}
{123}{}{Dame agua. Ahora.}
{124}{}{Lárgate, imbécil.}
{125}{}{¡Te reventaré el cráneo, pendejo!}
{126}{}{Oye, ¿qué haces? ¡Aleja esa cosa de mí, imbécil!}
{127}{}{. . .}
{128}{}{ }

{200}{}{¡Te lo juro, le partiré la cabeza a este puerco de mierda si no me da agua!}
{201}{}{No quieres hacer eso, lo sabes.}
{202}{}{Tú no te metas, no tienes idea de cuánta sangre se derramó por esa bomba de agua. ¡Ellos nos la robaron! ¡Y ahora nos exigen que paguemos por nuestra propia agua! (le grita al vendedor) ¡Dame agua, hijo de puta!}
{1202}{}{Señorita, no se meta en esto, no tiene idea de cuánta sangre se derramó por esa bomba de agua. ¡Ellos nos la robaron! ¡Y ahora nos exigen que paguemos por nuestra propia agua! (le grita al vendedor) ¡Dame agua, hijo de puta!}
{203}{}{Bueno, no es mi problema. Haz lo que quieras.}
{204}{}{No dejaré que te comportes como un demente.}
{205}{}{Cálmate, no deberías derramar sangre por algo así.}
{206}{}{¿Derramar sangre? ¿Qué vas a saber tú de eso? No sabes cuánta gente murió por esa maldita bomba de agua. Ya no tengo nada que perder. ¡Quítate!}
{207}{}{Dame el martillo, ahora.}
{208}{}{Está bien, se lo merece. Hazlo.}
{209}{}{Párate a pensar un momento, no vale la pena sacrificarse por esto.}
{210}{}{¿Sacrificarse? ¿Qué sabes tú de sacrificarse? No sabes cuánta gente murió por esa maldita bomba de agua. No tengo nada que perder...}
{211}{}{Bueno, si tú lo dices. Adelante, Hazlo pagar.}
{212}{}{Eso ya está en el pasado. No hay por qué cobrar otra vida.}
{213}{}{(mira a su alrededor, y luego al martillo) Dios... creo que perdí la cabeza. Necesito calmarme.}
{214}{}{Sí, es mejor que lo hagas eso.}
{215}{}{¿Boom-boom?}
{216}{}{¡No-no!}
{217}{}{¡No-no! [Intenta abrazarlo para que se calme]}
{218}{}{¡Z-z-ziii!}
{219}{}{Uf.}

