{100}{}{Ves a un guardia.}
{101}{}{Ves a un guardia de la bomba de agua. No parece saber qué hacer con su vida.}

{110}{}{¿Qué quieres?}
{111}{}{Es mejor que salgas de nuestro territorio.}
{112}{}{Si quieres agua, habla con el vendedor de la entrada.}
{113}{}{Habla con el jefe.}
{114}{}{¿Conoces al alcalde?}
{115}{}{Aquí encontrarás el agua más limpia del yermo.}
{116}{}{Aquí le cortamos las manos a los ladrones, así que ni se te ocurra.}
{117}{}{Siempre estamos alerta.}
{118}{}{Mantener la bomba a salvo se vuelve cansino.}
{119}{}{Los forajidos afectan nuestro negocio.}
{120}{}{Es mejor que evites a los forajidos.}

{130}{}{Sullivan solía dirigir esta bomba de agua con puño de hierro.}
{131}{}{Nos hace falta un jefe nuevo, de lo contrario, este lugar se caerá a pedazos.}
{132}{}{Sullivan era todo un bastardo.}
{133}{}{¿Qué demonios haremos ahora?}

{140}{}{Sullivan es un tipo duro.}
{141}{}{¡Ahora estamos a cargo nosotros!}
{142}{}{Sullivan es quien dirige esta ciudad ahora.}
{143}{}{El alcalde era un inútil, deberíamos haberlo sacado de aquí hace mucho.}

{150}{}{Entre más pronto terminemos, más pronto volveremos a casa.}











