{100}{}{Ves a John Sullivan.}
{101}{}{Estás viendo a un hombre que se hace respetar. Se ve limpio y bien cuidado.}
{102}{}{No vas a pasearte por nuestra ciudad con esa cosa, ¿no?}
{103}{}{¿Acaso quieres morir? Sal de nuestra ciudad, maldito forajido.}
{1103}{}{¿Acaso quieres morir? Sal de nuestra ciudad, maldito forajida.}
{104}{}{Yo seré quien traiga el orden a esta ciudad. Relájate y ve a darte un baño. Le dije al comerciante que te de un descuento.}


# First Meeting
{200}{}{Hola, forastero. No me gusta que un desconocido se ande paseando cerca de la bomba.}
{1200}{}{Vaya, no me esperaba ver a una señorita. Aún así, no me gusta que los desconocidos se anden paseando cerca de la bomba.}
{201}{}{¿Esta bomba de agua es tuya?}
{202}{}{¿Quién demonios eres?}
{203}{}{John Sullivan. Soy el dueño de toda la maldita bomba de agua. ¿Tienes algo que tratar conmigo?}

{204}{}{No soy de por aquí. ¿Te puedo hacer unas preguntas sobre la ciudad?}
{205}{}{¿Acaso no me escuchas? NO TENGO TIEMPO PARA HABLARTE.}
{206}{}{Ah, pues ya me voy.}
{207}{}{¿A quién debería hablarle acerca de la ciudad?}
{208}{}{Al viejo Bustos, llegarás a su mansión si bajas por la calle de allá.}
{209}{}{Gracias, adiós.}
{210}{}{¿Por qué no la reparas?}
{211}{}{¿En serio no hay nadie más que sea capaz de arreglar esta cosa?}
{212}{}{Los Hojalateros nos cobran un ojo de la cara por cualquier tipo de servicio. Ellos saben que el agua es un negocio rentable, pero no podemos entregarles lo que nos piden. Y aparte de los Hojalateros no hay nadie más que pueda hacer un trabajo así. Son los únicos con la maquinaria y las habilidades.}
{213}{}{Ah, lo siento, entonces no molesto.}
{214}{}{¿Y crees que lo podrás reparar por ti mismo?}
{215}{}{A veces funciona. Es uno de los filtros, es sólo que está atascado con tierra... o algo más.}
{216}{}{Puedo arreglarlo.}
{217}{}{¿De verdad? Si arreglas el filtro, te pagaré. Menos que los Hojalateros, por supuesto. Pero al final, todos ganamos.}
{218}{}{Bien... Esto llevará un rato.}
{219}{}{Hmm, esta tecnología es demasiado complicada para mí. Me temo que no soy capaz de arreglarla.}

{220}{}{¿Vienes a hacer negocios, o solo pierdes el tiempo?}
{221}{}{Nada en especial, ya me voy.}
{222}{}{De acuerdo.}
{223}{}{No estás pensando en andar por aquí vestido de ESA FORMA, ¿verdad?}
{224}{}{¿Tú otra vez? ¿Qué quieres ahora?}

{230}{}{Sé lo que pasó con el mercader. La pobreza lleva a la gente a hacer locuras. Olvida lo que sucedió, y que no se vuelva a repetir.}
{231}{}{No hay problema. No vi nada, ni oí nada.}
{1231}{}{No hay problema. No vi nada, ni oí nada.}
{232}{}{Esa es la respuesta correcta.}
{233}{}{Em... Entiendo.}
{234}{}{El silencio tiene un precio.}
{235}{}{Es simple: Cierra la boca y no tendrás problemas.}
{236}{}{Así que así son las cosas...}
{237}{}{El silencio tiene un precio. No crees que esta historia se enterrará sola, ¿verdad?}
{238}{}{Ah, un método más mercantil. (cuenta }
{239}{}{ chapas) Aún así, cuidado con lo que dices. De lo contrario, esta pequeña ciudad te presentará problemas.}
{240}{}{Oh, te entiendo perfectamente...}

{241}{}{¿Qué clase de desacuerdo tuviste con el alcalde?}
{242}{}{Ese viejo tirano fue ablandado por el tiempo y su hija. Ha perdido su toque y ya no tiene el derecho de estar mandándome. Antes tenía que conformarme con el papel de gerente. Pero ahora es mi turno de vivir bien.}
{243}{}{Supongo que sí, al menos por ahora.}
{244}{}{Encuentra a alguien más con quien conversar. Yo no tengo el tiempo ni el interés.}
{245}{}{Bueno, entonces no te molesto.}

# Questions
{250}{}{Estoy buscando a un Hojalatero. ¿Ha habido alguno aquí recientemente?}
{251}{}{Sí, él estuvo aquí. Revisó la bomba, hablamos de unos arreglos menores y fue a ver al alcalde. No lo he visto desde ese entonces.}
{252}{}{Gracias, iré a hablar con el alcalde.}
{253}{}{De hecho, estoy rastreando a algunos esclavos que llevaron a Two-Sun.}
{254}{}{Entonces anda a Two-Sun. Sólo atendemos a las caravanas y dejamos que sigan con su camino. Es parte del negocio, eso es todo.}
{255}{}{Gracias, ahora sé a dónde ir.}

{260}{}{La bomba de agua es enorme, es impresionante.}
{261}{}{Esta vieja dama ya tiene más de cien años. Ha visto más de lo que podrías imaginar. Y sigue en pie, gracias a mí y los Hojalateros.}
{262}{}{Debe ser una operación rentable.}
{263}{}{Ya veo. Debo marcharme.}
{264}{}{¿Te puedo hacer una última pregunta?}
{265}{}{Por supuesto que sí. Todos necesitan agua, especialmente aquí, durante el recorrido entre Fénix y Two-Sun. Es por eso que las caravanas hacen una parada aquí tan a menudo. Se podría decir que la bomba alimenta a toda la ciudad.}
{266}{}{¿Cómo fue que repararon un ejemplar tan complicado de maquinaria?}
{267}{}{Lo cierto es que las reparaciones más complicadas fueron realizadas por los Hojalateros. Me costó mucho, pero ellos eran los únicos capaces de ello. Además, los Hojalateros también se benefician de las caravanas.}
{268}{}{¿Sabías que desaparecieron? Es irónico, adoraban la tecnología, pero fue eso lo que acabó con ellos.}
{269}{}{Así es, eso oí. Y son muy malas noticias. En primer lugar, significa que habrán menos caravanas. Además, ¿qué haremos cuando haya que reparar la bomba otra vez? Sin los Hojalateros, la ciudad está prácticamente muerta.}

{270}{}{Bueno, retrocedamos un poco.}
{271}{}{¿En dónde aprendiste tanto sobre la tecnología de la preguerra?}
{272}{}{Para ser sincero, los Hojalateros se encargan de los arreglos de verdad. Yo sólo me conozco algunos trucos por experiencia, pero los demás tipos de por aquí sólo deben presionar botones.}
{273}{}{No confías en ellos, ¿no?}
{274}{}{}
{275}{}{¿Qué tienen de especial los Hojalateros?}
{276}{}{Hemos sacrificado mucho para restaurar este lugar, ellos son y eran los únicos capaces de hacer algo así. Además, tienen un interés personal en las rutas comerciales.}
{277}{}{¿Sabías que esos tipos cayeron víctima a la tecnología que veneraban?}
{278}{}{Escuché sobre eso, no me molesta, pero... ¿Qué haremos cuando la bomba necesite un mantenimiento a fondo? No quiero ni pensarlo.}
{279}{}{Retrocedamos un poco.}
{280}{}{¿Quién está a cargo en este lugar?}
{281}{}{Yo.}
{282}{}{Pues, supongo que entonces debería estar hablando contigo.}
{283}{}{El nombre del alcalde es Don Bustos. Vive en su hacienda, está por la calle de allá, más abajo.}
{284}{}{Cuéntame sobre el alcalde. ¿Qué clase de hombre es él?}
{285}{}{Llevamos mucho tiempo siendo socios. Nos llevamos bien, pero a veces discutimos - especialmente sobre su hija. Siempre deja que se salga con la suya.}
{286}{}{¿Tiene una hija?}
{287}{}{Sí, es una niña agradable, pero es muy cabezota. No entiendo por qué Bustos es tan poco estricto con ella. Si fuera mía, ya la hubiera corregido hace mucho, con una correa.}
{288}{}{Ya veo. Hablemos de otra cosa.}
{289}{}{¿Qué opinas de él, realmente?}
{290}{}{Llevamos mucho tiempo siendo socios. Eso es todo lo que necesitas saber. No esperas que vaya a hablar a espaldas de mi mejor amigo, ¿cierto?}
{291}{}{¿Qué clase de desacuerdos has tenido con el alcalde?}
{292}{}{Ese viejo lobo cambiado, debido al tiempo y a su hija. Perdió el derecho de decirme qué hacer. Solía conformarme con hacer sus deberes, pero ahora, la vida buena me toca a mí.}
{293}{}{Bueno, no es que pueda llevarte la contraria. O al menos, ya no.}

# Quest - Repairs
{300}{}{¿Hay algo de trabajo en la ciudad?}
{301}{}{¿Sabes de maquinaria? En ese caso, podrías arreglar el maldito filtro.}
{302}{}{No, eso no es lo mío.}
{303}{}{No tengo nada más que ofrecerte.}
{304}{}{No tengo otro empleo que ofrecerte. Prueba con el alcalde.}
{305}{}{Bien, pues cambiemos de tema.}
{306}{}{En ese caso, iré a hablar con él de inmediato.}
{307}{}{Iré a darle un vistazo, quizás pueda solucionarlo.}
{308}{}{¿De verdad? Si reparas el filtro, te pagaré. Menos que a los Hojalateros, pero a ambos nos conviene.}
{309}{}{Creo que podré solucionarlo rápidamente.}
{310}{}{Bien, pero quizás tome algo de tiempo.}

{320}{}{Prueba a hablar con el alcalde. La bomba no tiene más trabajo que ofrecer.}
{321}{}{No, ya no hay más trabajo por aquí.}
{322}{}{Bien, ¿te importa si ocupo un poco más de tu tiempo.}
{323}{}{Ya veo.}

{330}{}{Hablando de la bomba, ¿qué tiene de malo el filtro?}
{331}{}{Los Hojalateros nos cobran un ojo de la cara por cualquier tipo de servicio. Ellos saben que el agua es un negocio rentable, pero no podemos entregarles lo que nos piden. Y aparte de los Hojalateros, no hay nadie más que pueda hacer un trabajo así. Son los únicos con la maquinaria, los conocimientos, y las habilidades.}
{332}{}{Entiendo.}
{333}{}{He arreglado el filtro. La tierra y la arena habían dañado algunas partes, pero conseguí repararlas.}
{334}{}{Esa clase de trabajo merece una paga. Aquí tienes, }
{335}{}{ chapas.}
{336}{}{Gracias.}
{337}{}{¡Eso no es suficiente!}
{338}{}{Si tuviese que pagarte más, no te habría ofrecido el trabajo en primer lugar.}
{339}{}{Eres un tacaño.}
{340}{}{Gracias, de todos modos.}
{341}{}{Eso apenas cubre las piezas de repuesto.}
{342}{}{Está bien. Aquí tienes otras }
{343}{}{ chapas más. No vuelvas a pedírmelo.}
{344}{}{Sigues siendo un tacaño.}
{345}{}{Eso es suficiente. Gracias.}

# Overthrowing the Mayor
{350}{}{Sé que tú y Bustos no se llevan bien. ¿Quieres hablar de ello?}
{351}{}{Eso no es asunto tuyo.}
{352}{}{Técnicamente, tienes razón.}
{353}{}{Has tenido problemas con Bustos, igual que los forajidos. Quizás podamos trabajar juntos.}
{354}{}{¿De qué demonios estás hablando?}
{355}{}{Solo hablaba tonterías. Olvídalo.}
{356}{}{Los forajidos quieren derrocar al alcalde. Jamás querrán tratar con él, pero puede que contigo sí.}
{357}{}{A decir verdad, Bustos ya me ha hartado. Puede que una vez haya traído el orden... ¡Pero ahora, no hace más que embriagarse mientras me quiebro la espalda con la maldita bomba de agua!}
{358}{}{Veo que es hora de que retire.}
{359}{}{¡Ya tomé mi decisión! Reuniré a mis hombres y asumiré el control de la ciudad! Vayamos al ayuntamiento...}
{360}{}{Vaya, ¿tan rápido?}
{361}{}{Quizás para él tampoco es tan fácil. Relájate por ahora.}

