{100}{}{Ves al comisario.}
{101}{}{Ves a un hombre vestido con una túnica de color llamativo. Mientras observa la caravana, parece estar por encima del mundo entero.}
{102}{}{Este hombre no quiere hablar contigo.}

{200}{}{Es sorprendente ver a un viajero pacífico. Pero no queremos que nos sigan, así que aléjate de nosotros y de los esclavos. Gracias, ahora lárgate.}
{201}{}{¿Te puedo hacer una pregunta?}
{202}{}{¿Por qué los Seguidores del Fuego evitan compartir lo que saben?}
{203}{}{No me iré sin respuestas.}
{204}{}{Ya veo. Me largo.}

{205}{}{Tienes una mente minúscula, igual que un átomo en un útero nuclear. ¡Te haremos pedazos hasta que no quede rastro de ti!}
{206}{}{¿De qué hablas...?}
{207}{}{Si en serio eres uno de nuestros Hermanos, ya deberías saberlo; si no estás iniciado en los asuntos más importantes, no eres digno.}
{1207}{}{Si en serio eres una de nuestras Hermanas, ya deberías saberlo; si no estás iniciado en los asuntos más importantes, no eres digna.}
{208}{}{Entonces, ¿te puedo hacer una pregunta?}
{209}{}{Pareces ser un listillo. ¿Qué importa si hablamos un poco?}

{210}{}{Sólo una.}
{211}{}{¿Qué estás transportando?}
{212}{}{Un artefacto antiguo. Algo demasiado importante para hablarlo con los no iniciados.}
{213}{}{¿Quién eres?}
{214}{}{De todo lo que podías preguntarme, escogiste lo más irrelevante. Allí están mis mercenarios, aquí mis esclavos, yo soy el líder de la caravana.}
{215}{}{¿No hace mucho calor como para llevar una túnica?}
{216}{}{(sonríe) No. La tela sintética y el compresor de fluidos capilares la hacen perfecta para el desierto.}
{217}{}{Necesito llegar a la ciudad más cercana. ¿Me puedes mostrar en dónde está?}
{218}{}{¿Hm? (levanta una ceja misteriosamente)}
{219}{}{¿Eso es todo? Esperaba más...}
{220}{}{Eh, gracias.}
{221}{}{(te indica el pueblo de Flagstaff en tu mapa)}
{222}{}{(te indicia la ciudad de Fénix en tu mapa)}
{223}{}{(te indica la ciudad de Two-Sun en tu mapa)}
{224}{}{Suficiente. Sal de aquí si valoras tu miserable vida.}
{225}{}{¡Muero de sed! ¿Podrías darme un sorbo de agua?}
{226}{}{Salvar una vida tan insignificante no es parte de mis planes. Y aún así, tal desinteresado acto de piedad tiene lugar entre el gran diseño de reconstruir el mundo. Bebe un sorbo de agua pura, y que quede como ejemplo de la misión de los Seguidores del Fuego. Cuéntale a todo el mundo que soñamos con brindarle agua a todos... a todos los que sean dignos.}
{227}{}{No voy a perder el tiempo con un idiota que exige hablar pero es incapaz de escuchar. ¡Vete, ahora!}
