{100}{}{Ves a Frank.}
{101}{}{Ves a un morador del refugio. Es notablemente suave y limpio comparado a cualquier habitante del yermo.}

{200}{}{¡N-no nos hagas daño, por favor! Somos gente de paz, no queremos problemas.}
{201}{}{¿Por qué me tienes miedo? No he hecho nada malo.}
{1201}{}{¿Por qué me tienes miedo? No he hecho nada malo.}
{202}{}{Entonces deja de chillar, porque me estás irritando.}
{203}{}{Pero entonces... ¿no eres un saqueador?}
{1203}{}{Pero entonces... ¿no eres una saqueadora?}
{204}{}{No, soy }
{205}{}{. ¿Y tú eres?}
{206}{}{Me llamo Frank. Desde que falleció nuestro supervisor, he estado a cargo. Y si te soy sincero, ha sido difícil.}
{207}{}{¿Por qué?}
{208}{}{El refugio es viejo y se cae a pedazos. El sistema de soporte vital está fallando pues el generador apenas funciona. No sabemos cómo arreglarlo.}
{209}{}{Suena a que es todo un desastre.}
{210}{}{Hmph. Que bueno que no es mi problema.}
{211}{}{Y si eso no era suficiente, afuera hay unos saqueadores. Han intentado meterse al refugio una docena de veces durante los últimos meses, buscan conquistarlo. Lo único que los detiene es la puerta del refugio, pero todo está funcionando mal aquí dentro, puede que debamos salir para no sofocarnos. Me da terror pensar en qué nos harán. Ya capturaron a Fred, y seguramente lo están torturando.}
{212}{}{¿Y cómo puedo ayudarte?}
{213}{}{Puedo resolver tu problema, pero te costará.}
{214}{}{¿En serio nos ayudarás? Eso sería genial. Tienes que arreglar el generador y hacer funcionar la computadora para reiniciar el soporte vital.}
{215}{}{Ya entiendo, veré qué hacer.}
{216}{}{Hazte para atrás y mira cómo lo hace un profesional.}

{220}{}{¿Conseguiste reparar el generador? No parece que haya cambiado nada. Tienes que arreglar el generador y hacer funcionar la computadora para reiniciar el soporte vital.}
{1220}{}{¿Conseguiste reparar el generador? No parece que haya cambiado nada. Tienes que arreglar el generador y hacer funcionar la computadora para reiniciar el soporte vital.}
{221}{}{Es hora de ponerme con ello. Nos vemos.}

{230}{}{¿En dónde está el cuarto del generador?}
{231}{}{Se encuentra al fin del pasillo, a la nuestra izquierda. Pero no servirá de nada si no tienes herramientas, la puerta está sellada.}
{232}{}{Adiós.}
{233}{}{¿Cuál es el cuarto de las computadoras?}
{234}{}{Está al fin del pasillo a la derecha. Pero la computadora no funciona si no hay corriente.}
{235}{}{¿Cómo puedo reiniciar el soporte vital?}
{236}{}{Una vez que hayas encendido el generador, puedes usar la computadora y reiniciar el sistema de soporte vital. En ese entonces, sólo faltará reparar el ojobot para que patrulle el refugio y mantenga afuera a nuestros enemigos.}
{237}{}{Háblame acerca de este refugio.}
{238}{}{Lo construyeron hace unos cien años. Nuestros ancestros sobrevivieron a la Gran Guerra gracias a él. Pero ahora no hay nadie quien pueda ayudarnos. Sólo nos resguardamos aquí cuando algo nos amenaza.}

{240}{}{Gracias por reparar el sistema de soporte vital. ¡Ya nos sentimos mucho mejor?}
{241}{}{No fue ningún problema.}
{242}{}{Me alegra escuchar eso.}
{243}{}{¿Algo más?}
{244}{}{No tenemos muchos objetos de utilidad. Pero toma, es un mono del refugio. Está algo desgastado, pero es ligero y debería ayudarte a reaccionar más rápido.}
{245}{}{No tenemos muchos objetos de utilidad. Pero toma, es una cantimplora. El supervisor la apreciaba mucho, dijo que le trajo la suerte durante sus viajes al desierto. Si la llevaba, jamás se le acababa el agua, por caluroso y árido que haya sido el lugar.}
{246}{}{Gracias.}
{247}{}{¿Pero qué es esta mierda? Después de todo lo que hice, ¿me das una maldita cantimplora? ¡Claro que no! ¡Quítate la ropa y dámela!}
{248}{}{¡Ya, ya! No sé que haré sin él... Toma, llévatelo.}
{249}{}{Y cambia la cara, es lo menos que podías hacer por todo lo que te ayudé.}
