{100}{}{Ves a una clienta del bar.}
{101}{}{Ves a una de las clientas del bar. Siempre estará dispuesta a hablar, mientras haya un trago en su mesa.}

# first meeting
{200}{}{H-hola...}
{201}{}{[Deja en paz a la chica y a su botella]}
{202}{}{Oye, amigo. ¿Te sientes generoso? ¿Qué tal si me invitas una cerveza? ¿O acaso te quedarás ahí parado?}
{1202}{}{Oye, hermana. ¿Te sientes generosa? ¿Qué tal si me invitas una cerveza? ¿O acaso te quedarás ahí mirando?}
{203}{}{Sí que tuviste una buena pelea. ¿Qué tal si bebemos un poco para celebrarlo? ¿O acaso sólo viniste al bar para pelear?}

{204}{}{No tengo dinero, lo siento.}
{205}{}{¡Ja! Que avaro...}
{206}{}{¿A quién le acabas de decir eso? ¿A mí?}
{207}{}{Bueno, adiós.}
{208}{}{Sí, ¿y qué?}
{209}{}{Pero si la que anda rogando por un trago eres tú, puta.}
{210}{}{Eh, no importa.}
{211}{}{Tranquilo, vaquero. En esta ciudad, es mejor que no hagas escándalos por algo tan pequeño.}
{1211}{}{Tranquila, señora. En esta ciudad, es mejor que no haga escándalos por algo tan pequeño.}
{212}{}{Entonces cierra la boca.}
{213}{}{Agh, que asco... Ni te me acerques, a no ser que vayas a invitarme una botella.}
{214}{}{Hola, señor. ¿Tú eres quien se deshizo de Faber, cierto? Guau... ¿Me invitas un trago?}
{1214}{}{Hola. ¿Tú eres quien se deshizo de Faber, cierto? Guau... ¿Me invitas un trago?}


{220}{}{Claro, déjame ir por algo.}
{221}{}{Aquí te espero.}
{1221}{}{Aquí te espero.}
{222}{}{Nos vemos luego.}
{223}{}{Tengo una cerveza. No es nada impresionante, pero sirve. ¿No?}
{224}{}{Tengo una botella de tequila. Será perfecta para relajarse. ¿No crees?}

# got the drink
{225}{}{Gracias. (vierte un poco en el vaso y se queda callada)}
{226}{}{¿Eso era todo? ¿No me vas a contar nada?}
{227}{}{(bebe la mitad de la botella) ¿Cómo qué?}
{228}{}{Pues, dado que te invité la bebida, ¿te importaría contarme un poco sobre esta ciudad?}

{229}{}{Sólo he estado en la ciudad por un mes, pero no me tomó mucho tiempo darme cuenta de una cosa: es mejor que no hagas amigos por aquí.}
{230}{}{Puedes decir eso de cualquier ciudad que no conozcas bien.}

{231}{}{Así que, ¿vas a culpar a la ciudad por tus errores?}
{232}{}{(se encoge de hombros) Tienes razón.}
{233}{}{Entonces, ¿por qué no me cuentas tu historia?}
{234}{}{Maldita sea, ¿cuál es tu problema?}

# story
{240}{}{Pues, llegué aquí junto a mi novio. Las cosas iban bien. Solíamos explorar las ruinas y de allí ganarnos chapas para pagar los impuestos de la colonia.}
{241}{}{[Más]}
{242}{}{Pero, nos faltaban chapas, así que Karl, eh... Robó unas cuantas chapas. Y por eso, Faber lo metió a la cárcel. Y ahora él está ahí. Y yo estoy acá. Así que no sé qué hacer.}
{243}{}{¿Por cuánto tiempo estará ahí?}
{244}{}{¡Fue condenado a cinco años de trabajo duro! Karl no sobrevivirá eso. Y yo tampoco. Ahora, no sé qué hacer, ¿me voy sin él? ¿O espero a que lo saquen de ahí? La verdad, ¡ya no lo sé!}
{245}{}{Dudo que vaya a salir de ahí. Deberías marcharte y seguir con tu vida.}
{246}{}{¿En serio crees eso? Dudo que vuelva a ver a Karl. Supongo que haré eso, me iré con la primera caravana que vea.}
{247}{}{No dudes tanto. De todos modos, Karl no te habría dejado avanzar como deberías.}
{248}{}{¡Claro que deberías esperarlo! En primer lugar, tienes suerte de tener un novio. Al menos podrás visitarlo.}
{249}{}{¿De verdad crees eso? No quiero perderlo. Supongo que debería asentarme por aquí.}
{250}{}{No dudes tanto. Me suena a que Karl está tras las rejas porque quería cuidarte. No deberías abandonarlo.}
{251}{}{Gracias por el consejo.}
{252}{}{Buena suerte.}

# low intelligence
{260}{}{¡Mí buscar alcohol!}
{261}{}{¿Y-y-y qué?}
{262}{}{(bebe un poco, ligeramente incómoda) Eh, como sea. Aunque no seas muy listo, te contaré mi historia.}
{263}{}{¡Sigue!}
{264}{}{[More]}
{265}{}{[Niega con la cabeza]}
{266}{}{[Coloca una mano en su hombro y asiente con la cabeza hand on shoulder and nod]}
{267}{}{¡Okey!}
{268}{}{Puede que no me entiendas muy bien. Pero he tomado mi decisión, gracias a ti. Gracias.}
{269}{}{Ayooos.}