{100}{}{Ves a Hiram, el predicador. Su túnica está raída y desgastada.}
{101}{}{Ante ti se encuentra un hombre de sotana raída.}
{102}{}{Qué... que estás haciendo...}
{103}{}{...*cof*... hrrr...}
{104}{}{¡Hereje! La tecnología de los Antiguos no es para ser usada casualmente. Esta armadura debería estar en la Catedral en Fénix.}

#First dialogue
{200}{}{Saludos, viajero. Has sido muy valiente al aventurarte en esta ciudad.}
{1200}{}{Saludos, viajera. Has sido muy valiente al aventurarte en esta ciudad.}
{201}{}{¿Por qué lo dices?}
{202}{}{Flagstaff es uno de los últimos bastiones del orden en el Yermo. Y aquí los forasteros podrían ser obligados a trabajar, o peor, como leña para el Fuego Santo. Pero en última instancia, aquello que dicta tu destino, son tus decisiones.}
{203}{}{Ya veo. Me gustaría hablar contigo.}
{204}{}{Entiendo. Adiós.}
{205}{}{Bienvenido seas. Que los rayos del Fuego Santo te iluminen el camino en esta ciudad. Espero que no rechaces nuestras costumbres.}
{206}{}{¿A qué te refieres con costumbres?}
{207}{}{Bienvenido seas. ¿Cómo puedo serte de ayuda?}
{208}{}{Pues, recién llegué aquí, me vendría bien un guía.}
{209}{}{Hmm, esta no es una buena forma de empezar. Aprende a aceptar la fe tal como es. Las palabras no hacen más que esconder las verdades.}

#Re-dialogue
{210}{}{¿En qué puedo ayudarte?}
{211}{}{Adiós.}
{212}{}{¿Quién eres, y qué es este lugar?}
{213}{}{Te encuentras en la Iglesia del Fuego Santo, yo soy Hiram, su humilde sacerdote. Te doy la bienvenida a nuestro al radiante santuario de nuestra fe.}
{214}{}{¿Por qué hablas... así?}
{215}{}{Bueno... para ser honesto, difícilmente puedo recordar los días en los que hablaba distinto. Las Enseñanzas del Fuego Santo han transformado mi existencia por completo.}

#About knowledge
{216}{}{¿Tu iglesia es útil para Flagstaff, de alguna forma?}
{217}{}{¡Sin duda alguna! Primero, debo explicar que Flagstaff fue establecida gracias a nuestra iglesia... o mejor dicho, la Catedral, que está ubicada en Fénix.}
{218}{}{¿Y?}
{219}{}{El uranio es uno de los recursos sagrados que nuestros antepasados dejaron atrás. Utilizamos su energía, pues es radiante y nos ayuda a glorificar al Fuego Santo...}
{220}{}{Te escucho.}
{221}{}{Podemos alfabetizar y otorgar conocimiento de la preguerra a aquellos que lo busquen. Y además, como un humilde sirviente del Fuego Santo, tengo la bendición del don de la curación.}
{222}{}{Y supongo que cobras por eso, ¿no?}
{223}{}{¡Ah, un escéptico! Y sin embargo, debo admitir que tu sospecha no es del todo incierta. Para acceder al conocimiento del Viejo Mundo, uno debe pagar con chapas o hacerse miembro de nuestra iglesia. No todos están listos para absorber el conocimiento de las eras ya pasadas.}
{224}{}{Ya veo. ¿Puedo hacerte otra pregunta?}
{225}{}{Ya escuché suficiente. Adiós.}
{226}{}{Me gustaría que me enseñes algo.}
{227}{}{Oh, ciertamente. Sin embargo, no puedo aceptarte como un hermano en la fe hasta que obtenga la aprobación de la Catedral. Esto quiere decir que tendrás que hacer un pago. ¿Sabes leer?}
{1227}{}{Oh, ciertamente. Sin embargo, no puedo aceptarte como una hermana en la fe hasta que obtenga la aprobación de la Catedral. Esto quiere decir que tendrás que hacer un pago. ¿Sabes leer?}
{228}{}{Sí.}
{229}{}{Un poco... me sé las sílabas.}
{230}{}{¡Entonces los secretos del Fuego Santo eludirán tu mente! Iniciemos con lo básico - la alfabetización. El costo de una lección es de cien chapas.}
{231}{}{Toma mis chapas. ¡Busco la iluminación!}
{232}{}{Ahora no. Tengo otras preguntas.}
{233}{}{No puedo permitirme eso ahora mismo.}
{234}{}{Muy bien, aquí termina la lección de hoy. Si sigues practicando la escritura y la lectura, serás capaz de desbloquear los misterios de la preguerra. ¡Recuerda quién te guió en este sagrado viaje!}
{235}{}{Vaya... me duele un poco la cabeza, debo ir a tomar un respiro.}
{236}{}{No podemos confiarle los secretos del Fuego Santo a cualquiera. Este conocimiento podría potenciar tanto el bien como el mal. Demuestra tu devoción a nuestra fe a través de una gran donación. Pido 300 chapas a cambio.}
{237}{}{Creo que ya he donado lo suficiente a tu iglesia.}
{238}{}{Entonces quiero hacer una donación.}
{239}{}{Ah, estoy de acuerdo. Muy bien, debo cumplir con mi palabra. Tras esa puerta yace mi morada. Su interior contiene los manuscritos antiguos. Trátalos con cuidado y reverencia.}
{240}{}{Excelente, me vendrá bien leer esto antes de irme a la cama.}
{241}{}{¡Gracias, eres un santo del yermo!}
{242}{}{Ya escuché suficiente sobre tu iglesia; ya entendí de que se trata.}

#About faith
{245}{}{Cuéntame sobre tu iglesia.}
{246}{}{Podría hablar de esto para siempre. El mundo fue forjado por el Fuego Santo, el cual bajó a la tierra hace ya un siglo. Limpió a la tierra de aquellos que estaban sumidos en el pecado, perdonando la vida de unas pocas familias selectas, para así garantizar la supervivencia de la humanidad.}
{247}{}{Te escucho.}
{248}{}{Y ahora nosotros, la descendencia de esos supervivientes, tenemos el fin de construir un Nuevo Mundo, en donde los errores y los vicios del pasado se encuentren ausentes.}
{249}{}{¿A quién te refieres con "nosotros"?}
{250}{}{'Nosotros' se refiere a nuestra iglesia y sus seguidores, por supuesto. Para nuestra desgracia, hay otros que han olvidado las lecciones del pasado. Recae sobre nuestros hombros el deber de guiarlos hacia la iluminación.}
{251}{}{Pensé que fue la guerra lo que lo destruyó todo, la Gran Guerra.}
{252}{}{La guerra y la lucha por lo material están afligiendo a muchos en nuestros tiempos. Han dejado atrás la fe en sus almas y se reducieron al simple materialismo. La Gran Guerra no hace más que difuminar la verdadera naturaleza del Fuego Santo. No fueron las bombas atómicas las que castigaron a la humanidad, sino su propia estupidez y codicia. Ese es el punto, y la verdad.}
{253}{}{¿Hasta dónde se ha expandido tu fe?}
{254}{}{Nuestro Catedral yace en Fénix, sin embargo, su localización es de poca importancia. Hay numerosos pueblos, asentamientos y tribus que han aceptado la fe en el Fuego Santo, aunque bajo distintos nombres e interpretaciones de los sucesos antiguos. Por lo tanto, nuestra iglesia prolifera sin esfuerzo alguno y nuestras doctrinas retumban por toda Sonora.}
{255}{}{¿Qué opinan los colonos de tu iglesia?}
{256}{}{La mayoría de los colonos veneran al Fuego Santo, o al menos fingen esto. No obstante, los mercenarios de Faber son impíos en su mayoría y el escepticismo prevalece entre la población. Pero no temas; eventualmente, el Fuego Santo iluminará sus mentes. Mi preocupación recae en aquellos que luchan en contra de su sabiduría.}
{257}{}{}
{258}{}{Tengo unas cosas que quiero preguntarte.}
{259}{}{Ya debo irme. Adiós.}

#Donation
{260}{}{Deseo hacer una donación a tu iglesia.}
{261}{}{Toda contribución nos acerca a la esencia del Fuego Santo. ¿Qué puedes ofrecer?}
{262}{}{Em, la verdad no tengo nada. Solo tengo preguntas.}
{263}{}{Por hoy, nada. Adiós.}
{264}{}{Puedo permitirme 10 chapas.}
{265}{}{Te daré 50 chapas.}
{266}{}{Voy a donar 100 chapas.}
{267}{}{(esconde con rapidez las chapas dentro de su túnica) Gracias.}
{268}{}{(velozmente transfiere tus chapas a un bolso de cuero que está colgando de su correa) ¡Tu generosidad no conoce límite alguno!}
{269}{}{(vierte rápidamente tus chapas a un bolso de cuero que está colgando de su correa) ¡Que el Fuego Santo esté contigo!}

#Treatment
{270}{}{Necesito asistencia médica.}
{271}{}{Por el nombre del Fuego Santo, ¿qué te ha ocurrido?}
{272}{}{[Cura tus heridas por }
{273}{}{[Cura tus miembros rotos por }
{274}{}{[Cura tu radiación por }
{275}{}{[Cura tu envenenamiento por }
{276}{}{Pensándolo bien, no es nada grave.}
{277}{}{En el nombre del Fuego Santo, ¿qué pasó?}
{278}{}{ chapas]}
{279}{}{Está bien, voy a donar.}
{280}{}{¡Pero no tengo tantas chapas!}
{281}{}{Esto me apena, pero sin una donación, no puedo serte de ayuda.}
{282}{}{Demonios...}
{283}{}{No hace falta, ya se me pasará.}
{284}{}{¡Alabado sea el Fuego Santo por permitirte vivir un poco más!}
{285}{}{Ah, mucho mejor.}
{286}{}{Gracias, pero eso no era todo.}
{287}{}{¡Hombre de bolsa grande! ¡Oh, oh!}
{288}{}{¿Te refieres a mi túnica? (niega con la cabeza) Ah, desafortunado hijo del Átomo, siento pena por ti. Desearía poder ayudarte en recuperar los Átomos de la Consciencia que has perdido, pero por desgracia, no puedo hacer nada al respecto. Puedes irte, Hijo de la Radiación. Ve a jugar afuera.}
{289}{}{¿Ir fuera? Yo gustar ir fuera. Mi jugar.}

#Receiving a letter of recommendation
{290}{}{Si pudiera acercarme al líder de la iglesia, podría contribuir mucho más a la iglesia.}
{291}{}{Es una posibilidad. Podría redactar una carta de recomendación para ti, podrías presentarla ante la Catedral. No obstante, no parece que hayas aceptado del todo a nuestra fe.}
{1291}{}{Es una posibilidad. Podría redactar una carta de recomendación para ti, podrías presentarla ante la Catedral. No obstante, no parece que hayas aceptado del todo a nuestra fe.}
{292}{}{Ya veo.}
{293}{}{Podría redactar una carta de recomendación para ti, podrías presentarla ante la Catedral. Esto estaría marcando el inicio de tu camino. Pero, ¿realmente estás preparado para las pruebas que hay ante ti?}
{1293}{}{Podría redactar una carta de recomendación para ti, podrías presentarla ante la Catedral. Esto estaría marcando el inicio de tu camino. Pero, ¿realmente estás preparada para las pruebas que hay ante ti?}
{294}{}{¡Claro que sí!}
{295}{}{Tengo que pensármelo.}
{296}{}{Excelente. Aquí tienes la carta. Cuídala bien hasta que llegues a la Catedral. Esa será tu primera prueba.}
{297}{}{¡Entregaré esta carta en nombre del Fuego Santo! O como sea.}
{298}{}{Dada tu reputación en Flagstaff, dudo que seas una persona apropiada para nuestra iglesia.}
{299}{}{}

#Quest - beginning:
{300}{}{¿Son las chapas el único problema?}
{301}{}{Mientras que muchos desprecian nuestra fe en silencio, hay algunos que no son tan discretos.}
{302}{}{¿Alguien amenaza a tu iglesia?}
{303}{}{Un asaltante desconocido ha cometido fechorías despreciables bajo el manto de la noche - dibuja cruces en las paredes, prende fuegos, ensucia mi puerta con basura. Está claro que busca intimidarme para que huya de la colonia. Pero todavía me falta tener a este hereje puesto ante mí.}
{304}{}{Puede que consiga encontrarlo, me interesa descubrir qué problema tiene contigo.}
{305}{}{Preferiría no meterme en asuntos religiosos. Hablemos de otra cosa.}
{306}{}{Apreciaría mucho tu ayuda.}
{307}{}{De acuerdo, intentaré averiguar qué ocurre..}
{308}{}{No creo que haga falta un 'accidente'.}

#Quest - detecting a saboteur:
{310}{}{Hablemos sobre tus problemas nocturnos.}
{311}{}{¿Has descubierto alguna novedad?}
{312}{}{Todavía no, pero tengo una pregunta.}
{313}{}{No, nada nuevo. Te hablaré cuando me entere de algo.}
{314}{}{Logré atrapar al vándalo con las manos en la masa. Resulta que es el colono calvo de la casa que está al sur.}
{315}{}{Ah, Festus... Una víctima trágica de la ceniza radioactiva.}
{316}{}{¿Lo conoces?}
{317}{}{Solía atender la misa, pero no conseguía entender las radiantes verdades del Fuego. Cuando buscaba entrar, Festus estaba repleto de furia y orgullo. Por lo tanto, le cerré las puertas de la iglesia.}
{318}{}{¿Qué pasó después?}
{319}{}{El hijo de Festus se volvió una fuente de la discordia. Es un niño talentoso, le rogué que lo enviará a la Catedral para que sea educado apropiadamente, pero Festus se negó por completo. Lo triste es que en Flagstaff, hay muchos que no reconocen el valor del conocimiento y prefieren depender de la fuerza bruta.}
{320}{}{Sigue...}
{321}{}{Una vez que el niño fue presa de la radiación, ofrecí un tratamiento gratuito a cambio de que Festus cambiase de opinión y enviara al niño a la Catedral. Pero la animosidad de Festus resultó ser insuperable. Y ahora parece que está vengándose.}
{322}{}{¿Qué se puede hacer al respecto?}
{323}{}{Razonar con Festus para detenga sus fechorías y envíe al niño a la Catedral es un desafío formidable.}
{324}{}{¿Y según tú, eso nos deja una sola opción?}
{325}{}{Intentaré hacerlo cambiar de parecer.}
{326}{}{Necesito un tiempo para pensarlo.}
{327}{}{Una vez que el material nuclear se vuelve peligroso, debe aislarse y sumergirse en la oscuridad, para que no sea un peligro para los demás, o podría causar un 'accidente'.}
{328}{}{Que el Fuego Santo esté contigo.}
{329}{}{Sí...}

#Quest - completion of the quest:
{330}{}{Hablemos sobre Festus.}
{331}{}{Te escucho.}
{332}{}{Tengo otras preguntas.}
{333}{}{Te hablaré cuando haya resuelto la situación.}
{334}{}{He persuadido a Festus, enviará a su hijo a la Catedral y dejará de vandalizar la iglesia.}
{335}{}{¡Alabado sea el Poder del Átomo! Festus se arrepentirá en público y su hijo tendrá un futuro lleno de esplendor, podrá ser un clérigo y científico en la Catedral del Fuego. Muy bien hecho.}
{336}{}{Festus tuvo un... accidente. Ya no será ningún problema..}
{337}{}{¡Que el Fuego Santo consuma su alma! Festus era incapaz de ser redimido y convertirlo sólo habría causado daño. No obstante, su hijo tendrá un futuro lleno de esplendor en el interior de la Catedral del Fuego. Bien hecho.}
{338}{}{¿Cómo puedo agradecer tus esfuerzos?}
{339}{}{No es necesario que me lo agradezcas, lo hice por la fe.}
{340}{}{Necesito algo de medicina - un RadAway y un par de estimulantes.}
{341}{}{¿Podrías ofrecerme un 20% de descuento en tratamientos?}
{342}{}{Me hacen falta chapas, para librar a mis parientes de la prisión.}
{343}{}{Tengo una gran ambición - quiero viajar a la Catedral del Fuego y tener una audiencia con su líder.}
{344}{}{Me gustaría tener acceso a tu biblioteca.}
{345}{}{[Más]}
{346}{}{}
{347}{}{Pero, ¿cómo podemos hacer esto sin enojar a los demás colonos?}
{348}{}{Hmm. La radiación aflige a Festus. Al introducirle algo verdaderamente radiactivo podría apresurar la descomposición de su alma para que regrese a los átomos. Estoy seguro de que podrías encontrar algo así dentro de la mina de uranio.}
{349}{}{¿Un accidente, una dosis letal de radiación, veneno? No sé de estos temas.}

{350}{}{Gracias.}
{351}{}{Que la Llama Divina te proteja. Haré mención de tu generosidad en la siguiente misa, lo que elevará tu reputación entre la gente común.}
{352}{}{Lo mereces. Toma.}
{353}{}{Por supuesto, está bien merecido. Podrás contar con ese 'descuento' desde ahora en adelante.}
{354}{}{Únicamente podría ofrecerte 100 chapas, debido a las escasas donaciones a nuestra iglesia. Aún así, debería bastarte para llamar la atención de Faber.}
{355}{}{Hmm. Puedo redactar una carta de recomendación para la Catedral del Fuego en Fénix. Sin embargo, es necesario que demuestres tu mérito con una donación más grande.}
{356}{}{Es una colección del invaluable conocimiento de la preguerra. Trátalo con respeto y cuidado.}
{357}{}{Su hijo fue curado, has perdido tu oportunidad.}
{358}{}{¿Verdaderamente se ha recuperado? Pensé que era imposible resolver esto sin mi ayuda. Tristemente, he perdido mi única oportunidad para convencer al padre.}
{359}{}{consideralo como una lección.}

#Treatment of Festus's son
{360}{}{El hijo de Festus necesita tratamiento médico.}
{361}{}{Y con gusto lo ayudaré, pero únicamente si acepta visitar el templo.}
{362}{}{Entendido.}
{363}{}{Festus ya no será ninguna molestia, es hora de cumplir con tu promesa.}
{364}{}{Si esto se sigue retrasando, no le gustará a la Catedral del Fuego.}
{365}{}{Tus 'principios' podrían poner a los demás en tu contra.}
{366}{}{Si muestras piedad, podría ayudar con la reputación de la iglesia.}
{367}{}{Empezaré su tratamiento apenas me encuentre listo.}
{368}{}{Me parece bien.}
{369}{}{Debo ser firme.}
{370}{}{Eso pensaba...}
{371}{}{¿Por qué has decidido actuar así?}
{372}{}{Intentar que un adulto cambie de parecer suele ser inútil. Las semillas de la fe deben plantarse en los niños. Y además, eventualmente se olvidaría del 'trato' y simplemente quedaría la deuda de la gratitud.}
{373}{}{Ya veo.}

#Dialogue adjustments after the events in the Phoenix Temple
{400}{}{Déjame en paz... Ah, eres tú. Olvídalo.}
{401}{}{¿Alguien te está molestando?}
{402}{}{Desde los sucesos en el sur, los colonos se han vuelto intolerantes hacia mi fe. Algunos buscan expulsarme del pueblo, pero ya no tengo otro lugar a donde ir.}
{403}{}{Parece que lo tienes difícil. Te dejaré en paz.}
{404}{}{Bienvenido. Estoy feliz de ver a otro creyente en nuestro monasterio. ¡Bienvenido a la radiante Flagstaff!}
{1404}{}{Bienvenida. Estoy feliz de ver a otra creyente en nuestro monasterio. ¡Bienvenida a la radiante Flagstaff!}
{405}{}{¿Cómo te enteraste de mi ascenso?}
{406}{}{Cuando se trata de nuestra fe, la distancia es inconsecuente. Los mensajeros del Renacimiento me informaron de tu ascenso.}
{407}{}{Ah, te refieres al servicio postal...}
{408}{}{}
{409}{}{}
{410}{}{Y bien, ¿en qué puedo ayudarte, hermano?}
{1410}{}{Y bien, ¿en qué puedo ayudarte, hermana?}
{411}{}{¡Alto! Hermano en fe, ¿qué es lo que sabes acerca de los sucesos en Fénix?}
{1411}{}{¡Alto! Hermana en fe, ¿qué es lo que sabes acerca de los sucesos en Fénix?}
{412}{}{Supongo que lo mismo que tú.}
{413}{}{Hice explotar a la Catedral del Fuego. Fue culpable de la tragedia en la Villa, por lo que impartí lo que le hizo a mi persona.}
{1413}{}{Hice explotar a la Catedral del Fuego. Fue culpable de la tragedia en la Villa, por lo que impartí lo que le hizo a mi persona.}
{414}{}{Hmm. Eso es una pena.}
{415}{}{Sí, ya debo irme.}
{416}{}{Así que eso fue lo que ocurrió. Fue en nombre de... ¿la venganza? ¡Qué razón más salvaje! Pero si la iglesia ha desaparecido, entonces me queda abandonar mi existencia como predicador y abandonar Flagstaff. Tus acciones me han dado la oportunidad de un nuevo comienzo. Quizás no todo esté perdido.}
{417}{}{Es justo.}
{418}{}{He oído que se te expulsó de la Hermandad del Fuego. Necesito entender el por qué.}
{419}{}{¿Te importan mis razones? ¡Te las puedes meter por el culo, maldito cultista!}
{420}{}{¡No permitiré que profanen a mi fe! El Fuego Santo no es ningún mito. ¡Vino hace cien años y fue real! Si hasta después de escuchar mis sermones te rehúsas a ver la verdad, entonces ojalá que pronto vuelvas a los átomos y se olviden de ti para siempre.}
{421}{}{Lo que sea.}
{422}{}{Tu fe está predicando las ideas equivocadas.}
{423}{}{¿Acaso sugieres que el Fuego Santo jamás existo? ¿Que no deberíamos corregir al mundo de sus arrogantes errores y traerlo de vuelta a su antigua gloria? ¿Qué alternativa propones? ¿Marchitarnos entre sus ruinas y en el desolado yermo? Entonces puedes sumirte en tu ignorancia.}
{424}{}{Lo que sea.}
{425}{}{Sigo creyendo en el Fuego y todavía estoy en la búsqueda de la iluminación, hermano.}
{426}{}{Tus mentiras son una ofensa ante la fe. Abandona Flagstaff hasta que el Fuego te guíe hacia la verdad.}
{427}{}{Lo que sea..}
{428}{}{¿Puedo confiar en ti... hermano? Quizás todavía puedas redimirte. Adelante. Demuestra tu dedicación a nuestra fe a través de tus acciones. Bajo el estandarte de nuestro templo, o sin él.}
{1428}{}{¿Puedo confiar en ti... hermana? Quizás todavía puedas redimirte. Adelante. Demuestra tu dedicación a nuestra fe a través de tus acciones. Bajo el estandarte de nuestro templo, o sin él.}
{429}{}{De acuerdo.}
{430}{}{Tu presencia de por sí ayuda a la iglesia. Pero siempre estaremos felices de recibir chapas de cualquier fuente.}
{431}{}{No debe permitirse que cualquiera hurgue entre los misterios del Fuego Santo, este conocimiento puede usarse tanto para el bien como para el mal...}
{432}{}{Por supuesto. Ya he demostrado lo devoto que soy ante la fe.}
{1432}{}{Por supuesto. Ya he demostrado lo devota que soy ante la fe.}
{433}{}{Somos hermanos, tal pregunta es extraña. Soy Hiram, el sacerdote de este templo.}
{1433}{}{Eres mi hermana, tal pregunta es extraña. Soy Hiram, el sacerdote de este templo.}
{434}{}{Por supuesto. Pero, ¿sabes leer?}
