{100}{}{Ves a Roy Faber.}
{101}{}{Estás viendo al jefe de esta colonia. Su mirada es firme y es difícil soportarla.}
{102}{}{Tu reinado acaba aquí, bastardo.}
{103}{}{Tu reinado acaba aquí.}

#First Dialogue
{200}{}{(te mira con detenimiento, como si estuviera determinando cuánto vales) Es la primera vez que te veo. ¿Quién demonios eres?}
{1200}{}{Disculpa mi ignorancia, pero una señorita no debería caminar sola en un lugar así. No la había visto antes. ¿De dónde vienes?}
{201}{}{Eres un esclavista, no tengo por qué decirte quién soy.}
{202}{}{¿Hmph? Es la primera vez en mucho tiempo que alguien se atreve a hablarme así. Todos los que lo hicieron, pues, ya están muertos. Eres valiente, así que te daré un minuto más de vida. Me da curiosidad saber qué dirás.}
{203}{}{No necesito un minuto, ¡te mataré ahora!}
{204}{}{¿En serio?}
{205}{}{Estoy buscando a mi gente, son aldeanos de la Villa. Me han dicho que están en tu corral.}
{206}{}{(lo dice con un tono indiferente) Sí, esos mugrosos campesinos están acá.}
{207}{}{Pero, ¿por qué los tienes encerrados?}
{208}{}{Estuve a punto de dispararte, pero luego recordé haber hablado con unos necrófagos en Fénix. ¿Eres uno de ellos? Si es así, ¿qué demonios estás haciendo en Flagstaff?}
{1208}{}{Estuve a punto de dispararte, pero luego recordé haber hablado con unos necrófagos en Fénix. ¿Eres una de ellos? Si es así, ¿qué demonios estás haciendo en Flagstaff?}
{209}{}{Sólo quiero hablar contigo.}

{210}{}{¿Y bien?}
{211}{}{Déjame hablar con mis parientes.}
{212}{}{Te exijo que liberes a los aldeanos de la Villa.}
{213}{}{¿Por qué necesitas tantos prisioneros?}
{214}{}{¿Tienes algún trabajo que pueda hacer?}
{215}{}{}
{216}{}{Retrocedamos un poco.}
{217}{}{Hablemos de otra cosa.}
{218}{}{Cambiemos de tema.}
{219}{}{Eso era todo, ya me voy.}

#Access to the Pen
{220}{}{¿Eso es todo? Te dejaré hablar con ellos por un minuto, a cambio de 100 chapas.}
{221}{}{Claro, aquí tienes. ¿Ya puedo entrar?}
{222}{}{Un momento, tengo algunas preguntas que hacerte.}
{223}{}{No tengo tantas chapas, volveré cuando las tenga.}
{224}{}{No hay problema. Mis guardias te dejarán salir y entrar de allí... si te comportas.}
{225}{}{Lo intentaré.}
{226}{}{No tengo tantas chapas. ¡Por favor, es sólo un minuto!}
{227}{}{Ya te dije cuánto vale. Si no puedes pagarlo, piérdete.}
{228}{}{Demonios...}
{229}{}{Los aldeanos tienen un sentido del gregarismo muy desarrollado... Está bien, puedes pasar. Pero compórtate, o te quedarás ahí adentro para siempre.}

#Topic of Slaves
{230}{}{Ellos son escoria, los inútiles del yermo. En esta colonia penal por fin pueden servir de algo, a través de su labor.}
{231}{}{¿De qué clase de labor estamos hablando?}
{232}{}{Puede ser minar el uranio que hay aquí, trabajar para las caravanas en el sur, reconstruir Flagstaff, a veces Fénix nos envía órdenes... No puedo recordarlo todo.}
{233}{}{Entonces, esto no es una ciudad esclavista, sino una prisión.}
{234}{}{Lo era, hasta hace poco. La mitad de la escoria en nuestra colonia fue arrestada por agentes de la ley en el sur, y luego los trajeron aquí. Son todos saqueadores, violadores o deudores - le hallamos un uso a cualquier persona.}
{235}{}{Llámalo como quieras, pero encierras a la gente en contra de su voluntad.}
{236}{}{Mira a tu alrededor - es gracias a la prisión que Flagstaff ha prosperado. Somos los únicos que pueden imponer el orden en este lugar. Además, la sola mención de esta colonia hace que la gente no quiera cometer crímenes. ¿Todavía no te agradamos? Entonces piérdete.}
{237}{}{Pero los aldeanos de la Villa no son criminales.}
{238}{}{Resultaba que justo se nos acababan los prisioneros y la forma más rápida de reabastecernos era capturar a algunos salvajes. La Villa era el candidato perfecto, eran un excelente material y era difícil decir que no.}
{239}{}{Los aldeanos de la Villa no son salvajes y no merecen esto.}
{240}{}{Los salvajes como tú no entienden cómo son las cosas. ¿Has oído hablar de las ciudades en el sur? Allí se está reviviendo a la civilización. Igual que en los viejos días.}
{241}{}{¿Y?}
{242}{}{Flagstaff se encarga de suministrar el uranio y nuestros prisioneros son los trabajadores más importantes de la cadena. Sin nosotros, no puede haber progreso en el sur. Estamos escribiendo la historia y ahora tu patética aldea podrá ser parte de ella. Le estarán haciendo un gran servicio al resto del mundo.}
{243}{}{Ustedes no parecen ser agentes de la ley.}
{244}{}{¿Qué tan distinto crees que es? Los agentes de la ley pueden sobrevivir gracias a los criminales. A cambio de impuestos, protegen asentamientos de saqueadores y otros indeseables. Nosotros podemos sobrevivir por la labor de los criminales. (levanta una nudillera, la cual inspecciona con cariño) El poder te trae autoridad. Depende de ti el cómo lo ejerces.}
{245}{}{¿Por qué necesitan el mineral de uranio?}
{246}{}{Ah, los salvajes como ustedes ya se olvidaron del Viejo Mundo. Hace muchas generaciones, las personas utilizaban el mineral de uranio para generar electricidad. Con eso potenciaban la tecnología antigua - desde una ampolleta hasta los dispositivos más avanzados. Todavía se utilizan los restos de esas tecnologías, dentro de las grandes ciudades.}
{247}{}{¿Quién lo está comprando?}
{248}{}{Hay algunos compradores en el sur, el más grande es la Iglesia del Fuego Santo.}
{249}{}{Hay algunos compradores en el sur. La Iglesia del Fuego Santo solía comprar la mayoría de nuestros bienes, pero ahora es un poco más complicado.}

#Liberation
{250}{}{No tengo ninguna razón por la cual hacer eso.}
{251}{}{He conseguido resolver los problemas de la mina.}
{252}{}{Sí, eso me han dicho. Hemos tenido esos problemas por mucho tiempo, me cuesta creer que un campesino los haya resuelto. Está bien, cumpliré con mi palabra. Puedes ir al corral y liberar a tu gente, están libres.}
{1252}{}{Sí, eso me han dicho. Hemos tenido esos problemas por mucho tiempo, me cuesta creer que una campesina los haya resuelto. Está bien, cumpliré con mi palabra. Puedes ir al corral y liberar a tu gente, están libres.}
{253}{}{Bien.}
{254}{}{Entonces busquemos una razón.}
{255}{}{Bien, hagamos un trato. Hay algunos problemas que necesitan ser resueltos. Cumple con eso y liberaré a los campesinos que están en el corral.}
{256}{}{¿Qué necesitas que haga?}
{257}{}{Necesito que la mina esté funcionando como debería. Habla con el administrador; él te lo explicará todo.}
{258}{}{Tengo algunas preguntas que hacerte antes de irme.}
{259}{}{Entonces hablaré con él y volveré a hablarte cuando esté resuelto.}
{260}{}{¿¡De qué mierda estás hablando!? ¡La mina está arruinada, nos llevará meses poder despejarla! ¿Crees que eso es resolver un problema? No. ¡Lárgate de una maldita vez!}
{261}{}{Ya...}
{262}{}{Recuérdame de qué fue el trato que hicimos.}
{263}{}{¿No lo entendiste la primera vez? Habla con el administrador de la mina. Él te dirá qué hacer.}
{264}{}{En una semana tendrás una razón, los aldeanos infectarán a la colonia entera.}
{265}{}{¿De qué demonios estás hablando?}
{266}{}{Es obvio que hablo acerca de la "enfermedad del yermo". Los aldeanos de la Villa son inmunes, pero te aseguro que los colonos no. ¿No habías oído al respecto?}
{267}{}{Mierda... en el sur, hay asentamientos enteros que fueron eliminados por una plaga... ¿Puedes probar que lo tienen?}
{268}{}{Una vez que la enfermedad presente síntomas, lo verás con tus propios ojos. Es decisión tuya si vale la pena arriesgarse.}
{269}{}{Maldita sea... Está bien, dejaré que los aldeanos se vayan. ¡Pero más te vale que se vayan de inmediato! ¡Y tú también!}
{270}{}{Has tomado la decisión correcta.}
{271}{}{Bueno... los aldeanos ya están enfermos. ¿Que no lo ves?}
{272}{}{Sigue así y acabarás peor que ellos.}
{273}{}{Oye, cálmate...}

{274}{}{Me han dicho que alguien está buscando información entre mi gente. Eso no me gusta. Si alguien vuelve a reportarte, te voy a colgar.}
{275}{}{¡Esto es un error! ¡Te están mintiendo!}
{276}{}{Eh... bueno.}
{277}{}{¡Cállate! La colonia tiene reglas estrictas. Si quiebras una, te castigamos. Si quiebras otra, te colgamos de un poste. Y yo soy el que hace las reglas por aquí.}

{278}{}{(gritando) ¡Pedazo de mierda! ¡Siquiera te das cuenta de que un montón de aldeanos mugrosos están amenazando a toda Flagstaff! Todos esos años en los que trabajamos duro para establecer y controlar esta ciudad, todo el sur tenía esperanzas de prosperar - ahora todo eso vale menos que la mierda de un brahmán. ¡Anda, muéstrame de que estás hecho!}
{279}{}{Espera, un momento...}

#Quests
{280}{}{Quizás pueda trabajar para pagar esas chapas.}
{281}{}{Puede ser. Hay un problema que me ha estado molestando por un tiempo.}
{282}{}{Cuéntame más.}
{283}{}{Al este, se ubican las ruinas de la ciudad, hay varias patrullas que han desaparecido por allí. Los demás dicen que escucharon disparos. Averigua qué ocurrió y elimina el problema - te daré 300 chapas a cambio de eso.}
{284}{}{Trato hecho, volveré cuando lo haya resuelto.}
{285}{}{Voy a considerarlo.}
{286}{}{Me parece bien, pero si debo matar a alguien, estoy fuera.}
{287}{}{¿Por qué no lo hacen tus mercenarios?}
{288}{}{Las ruinas de la ciudad son demasiado peligrosas y difíciles de explorar. Estaría perdiendo más gente si los envío a explorar. Pero ahora te tengo a ti... ¿Qué pasa? ¿Acaso ya te arrepentiste?}
{289}{}{Entonces no tengo otra opción. ¡Estás muerto!}
{290}{}{¿Era un ranger? Era otro criminal intentando hacerse el héroe. Bueno, has hecho un buen trabajo. Lo que prometí, 300 chapas.}
{291}{}{¿No dirás nada más? No parece que las vidas humanas te importen mucho.}
{292}{}{Genial.}
{293}{}{Exacto. Eso te incluye a *ti*, porque tu vida es patética y no tiene ningún valor. Los salvajes de los alrededores sólo les ha importado sobrevivir, hasta el momento. Pero en mi colonia, la gente vive por una razón más grande que ellos mismos... Pero sé que no entenderías eso, sólo eres un salvaje.}
{294}{}{Sí. Nos vemos.}
{295}{}{¿Era un ranger? Era otro criminal intentando hacerse el héroe. Bueno, has hecho un buen trabajo. Toma, son 200 chapas.}
{296}{}{¡Oye, habíamos acordado que eran 300!}
{297}{}{No te daré más.}
{298}{}{Bueno, como sea... Hasta luego.}
{299}{}{¿Se te ocurre qué podría ser?}
{300}{}{Podría ser cualquier cosa, un mutante, una pandilla, o algo más.}

{301}{}{Uno de tus subordinados le debe 100 chapas al bar.}
{302}{}{Sí, había oído algo al respecto, pero es una cantidad pequeña y no voy a intervenir en eso.}
{303}{}{Entonces yo me encargaré de ello.}
{304}{}{Hmm. Como quieras. Le diré a mis hombres que no interfieran, en caso de que haya una pelea.}

{305}{}{Quiero mi recompensa. Había un saboteador de los Rangers entre las ruinas, pero ya está muerto.}
{306}{}{Había un saboteador de los Rangers entre las ruinas, pero ya se fue de Flagstaff.}
{307}{}{¿Un ranger? No me lo esperaba, pero tampoco me sorprende. Creen que son agentes de la ley, pero son estrechos de mente y ya sentía que tendríamos problemas con ellos.}
{308}{}{¿Qué hay de mis chapas?}
{309}{}{No eliminaste el problema. Pero te daré 50 chapas por haberme informado de esto.}
{310}{}{¡Oye, habíamos acordado que eran 300!}
{311}{}{Es mejor que nada.}
{312}{}{Habíamos acordado que *eliminarías* el problema, sólo lo retrasaste. Llévate las chapas y piérdete, antes de que cambie de opinión.}
{313}{}{Hijo de...}
{314}{}{Está bien, ya me voy.}
{315}{}{No puede ser... si estás intentando joderme, pagarás con tu vida. Saca a los aldeanos de aquí antes de que cambie de opinión.}
{316}{}{Tomaste la decisión correcta, voy a liberar a mi gente del corral.}
{317}{}{Es difícil creer que un campesino fuera capaz de resolver tantos problemas. Lo que me deja aún más perplejo es lo diligente que eres. Tu gente ya ha estado libre durante un buen rato.}
{1317}{}{Es difícil creer que una campesina fuera capaz de resolver tantos problemas. Lo que me deja aún más perplejo es lo diligente que eres. Tu gente ya ha estado libre durante un buen rato.}
{318}{}{En nuestra aldea, la gente cumple con su palabra. Si prometo que haré algo, lo voy a hacer. Adiós, Roy.}
{319}{}{Es aburrido vivir en una aldea, sólo quería una aventura. Adiós, Roy.}
{320}{}{Tengo otras preguntas.}
{321}{}{Eres un desquiciado, ¡Le pondré fin a esto!}
{322}{}{Puede que estés diciendo la verdad. Tengo que pensarlo.}
{323}{}{La esclavitud sigue siendo esclavitud, no importa cómo lo justifiques. Te detendré aquí y ahora.}
{324}{}{No sabía nada de esto. ¿Me puedes contar más?}
{325}{}{El Campamento Winon fue atacado por unos salvajes.}
{326}{}{¡Esos malditos salvajes! Siempre nos causan problemas en el peor momento posible. Esos son nuestros terrenos de caza, son muy importantes para la colonia. Tendré que enviar a unos soldados para que despejen el área.}
{327}{}{Buena idea, me adelantaré y los veré allá.}
{328}{}{Espera, todavía no lo hagas. Quizás pueda encargarme de ello sin la ayuda de tus mercenarios.}

{330}{}{¿Quién? ¿Yo? Eh...}
{331}{}{No necesitamos idiotas. Piérdete.}
{332}{}{Perderse... ¡Ah! Sí, yo ir casa. Villa ser casa mía, sí.}
{333}{}{Espera... ¿De qué hablas? Hace poco nos llegaron unos esclavos de la Villa. ¿Eres de allá? No me sorprende que te hayan dejado en casa - hasta agarrar una pala debe ser difícil para alguien como tú.}
{334}{}{¿Qué ser pa-la?}
{335}{}{Creo que estás buscando a tus amigos. Están aquí, en el corral. Pero si quieres verlos, tendrás que hacerme un favor. ¿Lo entiendes?}
{336}{}{¡Oh! ¡Sí! ¡Amigos!}
{337}{}{Sí, tus amigos... Escúchame, burro. Entra a la mina y baja. Hay una rata grande ahí. Mata a la rata y te dejaré hablar con tus amigos. ¿Lo entendiste?}
{338}{}{¡No, yo querer ver mis amigos ahora!}
{339}{}{¡Rata! ¡Mata rata! ¡Maaataaarrr!}
{340}{}{No los verás hasta que hayas matado a la rata gigante de la mina. Y no me vuelvas a enojar.}
{341}{}{Ooh, hombre nojado.}
{342}{}{¡Rata! ¡Mata rata! ¡Maaataaarrr!}
{343}{}{Mina, esto... Sí, no haber problema.}

{344}{}{Soy un miembro honrado de la Hermandad del Acero. Te exijo que liberes a estos inocentes aldeanos, o sentirás la furia de la Hermandad.}
{345}{}{Pff. ¿La Hermandad está llena de gente así de pretenciosa? Bueno, lo haré. ¿Pero por qué cambiaron de opinión tan repentinamente? Ustedes nos exigieron que consiguieramos esclavos sea como sea.}
{346}{}{No es asunto tuyo. Es lo que decidió el general.}
{347}{}{Está bien, no quiero problemas. Dejaré que los aldeanos se vayan.}
{348}{}{Excelente, hagamos el papeleo.}
{349}{}{Que no vuelva a ocurrir.}

{350}{}{Tenemos que hablar del capataz, Látigo está golpeando a los prisioneros.}
{351}{}{Lo sé, lo valoro porque es de mano firme. Si tiene que matar a alguien, no lo piensa dos veces.}
{352}{}{Oh. Bueno, supongo que reportarlo no servirá de mucho.}
{353}{}{Pero no es sólo una golpiza, los está lisiando y sin razón alguna.}
{354}{}{Espera un momento. ¿De qué estás hablando?}
{355}{}{El administrador debe escribir informes falsos y decir que quedaron lisiados por accidentes laborales, Látigo lo está obligando a hacer eso.}
{356}{}{No me gusta como suena esto. Puse a Látigo a cargo para que mantenga el orden, dado que es una persona muy firme. Si se está pasando de la raya, no lo permitiré. Los trabajadores son muy caros y no podemos desperdiciarlos de esta forma.}
{357}{}{Quizás deberías investigar esto y despedirlo, es una amenaza.}
{358}{}{No necesito tu opinión en qué debería hacer. Pero si estás diciendo la verdad, no será fácil reemplazar a Látigo. Si encuentro un reemplazo, lo tendré en cuenta, pero no creo que eso ocurra pronto... Ten, te daré 5 chapas por la información.}
{359}{}{Gracias... señor.}
{360}{}{[Sal sin decir nada]}
{361}{}{Acerca de Látigo, conozco a un reemplazo...}
{362}{}{...Me parece bien. No estoy en contra de deshacerse de Látigo. Será divertido ver a un capataz reemplazar a otro. Pero, sigo sin entender el por qué te importa esto.}
{363}{}{Ninguna razón en específico.}
{364}{}{No puedo soportar las injusticias.}

{370}{}{Las patrullas habían sido eliminas por un saboteador de los rangers. Está escondido en el sótano del museo.}
{371}{}{¿Un ranger? Es solo un criminal intentando hacerse el héroe. Enviaré a un escuadrón de mis hombres, ¡y sacaremos a ese hijo de puta de ahí adentro! En cuanto a ti, creo que 50 chapas debería compensar la información.}
{372}{}{Quería una solución al problema. Lo único que hiciste fue traerme información. Eso es todo lo que vale.}
{1372}{}{Quería una solución al problema. Lo único que hiciste fue traerme información. Eso es todo lo que vale.}
{373}{}{Como sea...}

{380}{}{Hay otra cosa de la que quiero hablar. Mis ancianos tienen miedo de volver a ser esclavizados.}
{381}{}{Es normal temerle a los forasteros. Pero, mi mina ya no necesita tantos esclavos, pues está funcionando a su máxima capacidad. Dudo que vuelva a organizar otra caravana esclavista.}
{382}{}{Eso es... Un poco tranquilizante. Se los haré saber.}
{383}{}{Si la mina estuviese funcionando a su máxima capacidad, no tendría que depender de la esclavitud. Hasta que todo esté en orden, tendré que seguir buscando esclavos, sea en donde sea.}
{384}{}{Ya veo.}
{385}{}{Y, ¿qué hay de malo con la mina?}
