{100}{}{Ves a un saqueador tribal.}
{101}{}{Ves a un saqueador, tiene varios tatuajes de calaveras tribales. No se parece a los demás habitantes de Flagstaff.}
{102}{}{Nos vamos.}
{103}{}{¡Estas tierras son nuestras!}

{200}{}{Alto ahí. Esto es nuestro territorio, no puedes estar aquí.}
{201}{}{Eh...}
{202}{}{Las personas como tú no tienen lugar aquí.}
{203}{}{[Defiéndete]}
{204}{}{Vengo en son de paz. El granjero me dijo que le arrebataron su hogar y sus tierras.}
{1204}{}{Vengo en son de paz. El granjero me dijo que le arrebataron su hogar y sus tierras.}
{205}{}{Él es un hipócrita, igual que todos los demás. Llegaron a nuestras tierras, masacraron a nuestra gente y nos quitaron todo. Tomaremos lo que es nuestro.}
{1205}{}{Él es un hipócrita, igual que todos los demás. Llegaron a nuestras tierras, masacraron a nuestra gente y nos quitaron todo. Tomaremos lo que es nuestro.}
{206}{}{Ustedes no son más que ladrones.}
{207}{}{Un momento, eso no lo sabía. ¿Qué pasó?}
{208}{}{Qué conveniente que no te lo haya dicho. Nuestros ancestros vivieron aquí por generaciones. Y luego llegó Faber y su gente, nos esclavizaron y mataron a quienes se resistieron. Fuimos los únicos supervivientes, y ahora queremos venganza. Ojo por ojo.}
{209}{}{Pero el granjero no tiene nada que ver en esto, déjenlo en paz.}
{210}{}{Lo dejamos vivir, así que debería agradecernos y marcharse. Pero tú no irás a ningún lado.}
{211}{}{[Muéstrale el dedo de al medio]}
{212}{}{Espera, no quiero pelear...}
{213}{}{Siento oír eso. Pero el granjero no tiene la culpa, déjalo en paz.}
{214}{}{Lo sabemos, es por eso que tuvimos piedad. Debería agradecernos eso y marcharse.}
{215}{}{Pero él se esforzó mucho trabajando en sus campos. Deberías respetar eso.}
{216}{}{Tal vez. Nosotros no queríamos pelear, pero los colonos cruzaron la línea. Pero, no podemos luchar contra Faber.}
{217}{}{Ahora, este lugar le pertenece a los colonos. No hay nada que puedas hacer al respecto. Abandona Flagstaff y empieza de nuevo.}
{218}{}{Si tanto quieres vengarte, yo te detendré. A la fuerza, si es necesario.}
{219}{}{Los citadinos como ustedes hablan demasiado, pero lo que dices tiene sentido. Si luchamos, morimos. Si escapamos, vivimos. Que así sea. Reuniremos a nuestro clan y nos marcharemos. (le da una señal a los demás) La granja no vale la pena, tenemos que irnos.}
{220}{}{Es lo correcto. Buena suerte.}
{221}{}{Sí, váyanse... O sea, tengan un buen día, y todo eso.}

{250}{}{¡Agh! ¡Un hombre de metal! Malditos colonos, ¿qué más harán para sacarnos de aquí?}
{251}{}{¿De qué estás hablando?}
{252}{}{No es problema mío.}
{253}{}{No queremos pelear contigo. Nos vamos, no nos sigas.}
{254}{}{Así me gusta, lárguense.}
{255}{}{Ustedes no se irán a ningún lado, las van a pagar.}

{260}{}{¿Pero qué...? ¿Por qué pareces una fruta que se quedó en el sol?}
{261}{}{¿Por qué crees? Tu piel tampoco es linda, salvaje.}
{262}{}{Estás sufriendo, ¿verdad? Por culpa de personas que no son como tú. Lo entendemos.}
{263}{}{No vas a durar mucho si empiezas a burlarte de cómo me veo.}
{264}{}{De hecho, estoy aquí por mi amigo el granjero. También está sufriendo.}
{265}{}{¿El granjero? Le perdonamos la vida, debería agradecernos eso y marcharse.}
{266}{}{No me importa lo que pienses, le quitaste lo que le pertenece. Eso es malo. Muy malo.}
