{100}{}{Ves a Gray.}
{101}{}{Ves a un colono de Flagstaff. Está agotado.}
{102}{}{Tengo sueño, déjame sólo.}
{103}{}{*Bostezo*}
{104}{}{Z-z-z}
{105}{}{Las cosas están mejorando.}
{106}{}{No me moveré de aquí hasta que ese estúpido brahmán se quite del camino.}

#On the city map
{200}{}{¿Qué necesitas?}
{201}{}{Solo estoy explorando la ciudad.}
{202}{}{Tus hijos me dijeron que intentan echarte del pueblo. ¿Es cierto?}
{203}{}{Así es. No puedo pagar el impuesto de la casa, perdí mi trabajo.}
{204}{}{¿En qué trabajabas?}
{205}{}{Era el líder de la patrulla, en la guarnición.}
{206}{}{Aquí respetan que trabajes con la guarnición, ¿no? ¿Qué pasó?}
{207}{}{Me quitaron mi rango por conducta inadecuada. Para ser exactos, me emborraché y causé problemas.}
{208}{}{Eras un comandante, ¿nadie te contratará?}
{209}{}{Una vez que te echan del cargo, nadie te quiere contratar. Todos dudan sobre ti.}
{210}{}{[Más]}
{211}{}{No tengo más opciones. Está la mina, pero no puedo hacer eso. Tengo una familia grande a la que alimentar. Puede que deba unirme a una caravana para estar de guardia, y eventualmente mudarnos a Fénix, otra vez.}
{212}{}{¿Tan mal están las cosas?}
{213}{}{Nos mudamos porque teníamos mejores oportunidades aquí. Dejamos todo atrás en Fénix, no hay nadie que nos reciba por allá. Mi carrera en Flagstaff se acabó. Es una pena, porque empezó muy bien.}
{214}{}{Si me entero de algún trabajo, te lo diré. Adiós.}
{215}{}{Lo siento mucho. Tengo que irme.}
{216}{}{El capataz de la mina no está haciendo bien su trabajo. Quizás puedas reemplazarlo.}

{220}{}{La mina necesita un nuevo capataz. Podrías reemplazar a ese tirano.}
{221}{}{¿Hablas de Látigo? Es un hombre cruel, creo que no está bien de la cabeza.}
{222}{}{Después de golpear a los esclavos, lo excusa diciendo que fueron accidentes de trabajo. Los trabajadores quieren a un nuevo capataz.}
{223}{}{Dudo que renuncie por voluntad propia. ¿Cómo voy a reemplazarlo?}
{224}{}{Déjamelo a mí. Yo me encargo de eso.}
{225}{}{¿De verdad tendrá algo de malo el capataz? Espero que no estés intentando estafarme.}
{226}{}{Estoy ganando muchas chapas, y las cosas están mejorando. Es todo gracias a ti.}

{230}{}{Faber está de acuerdo. Ahora tienes el puesto de capataz.}
{231}{}{No quiero ni imaginar como lo convenciste. Gracias.}
{232}{}{Hay un problema - tendrás que decírselo a Látigo. En la cara.}
{233}{}{Suena fácil, pero no creo que Látigo quiera irse por cuenta propia. Necesitaré un refuerzo, ¿podrías quedarte conmigo mientras hablo con él?}
{234}{}{Me parece bien. Nos vemos en la mina.}
{235}{}{Adiós, buena suerte.}

#On the mine map (used by the FCMinPap script)
{240}{}{Santa Catarina, ¡era muy fuerte! Si no hubiera sido por tu ayuda, ya estaría muerto. Gracias.}
{241}{}{No importa, fue divertido.}
{242}{}{¡Casi nos mata!}
{243}{}{No sé por qué me ayudaste, pero te recordaré. No dejaré que mis ambiciones nublen mi consciencia, como ocurrió con él. Bajo mi mando, se mantendrá la ley y la justicia.}
{244}{}{Buena suerte. Nos vemos.}
{245}{}{Me salvaste, si no hubieras estado ahí, habría terminado en una pelea. Gracias.}
{246}{}{Como puedes ver, siempre es posible hablar las cosas.}
{247}{}{La violencia no siempre es la solución.}
{248}{}{Tú hiciste esto, ¿verdad? Bueno, de todas formas, me alegra que no deba preocuparme al respecto. Sé que me hubiera dado muchos problemas.}
{249}{}{Se lo merecía.}
