{100}{}{Ves a Anne Brandley.}
{101}{}{Estás viendo a una mujer que no destaca mucho. Lleva puesto un traje de negocios.}
{102}{}{Z-z-z...}
{103}{}{Lo siento, hemos cerrado. Ya no hay nadie que siga necesitando nuestros servicios...}

# Remarks when attacking a prisoner
{120}{}{¡Por favor, cálmate!}
{121}{}{¡La caja registradora está vacía! ¡En serio!}
{122}{}{¡No toques nada!}
{123}{}{Escucha, de verdad siento que estés así...}
{124}{}{¡No puedo ayudarte, en serio!}
{125}{}{¡Por favor, vete! ¡No tengo nada!}
{126}{}{¡Déjame en paz!}
{127}{}{}
{128}{}{}
{129}{}{¡Ayuda! ¡Me están robando!}

# Dialogue
{200}{}{(ves a una mujer con un atuendo inusualmente limpio; parece que se cuida y desprecia a las personas de su alrededor)}
{201}{}{Hola. ¿Cuál es su nombre, señorita?}
{202}{}{Hola.}
{203}{}{Anne Brandley. Y llámame señora.}
{204}{}{Como usted diga, señora Brandley.}
{205}{}{(te observa con desdén) Hmm. Buenas tardes. ¿En dónde te enseñaron a hablarle así a las damas? ¿En una plantación?}
{206}{}{Jamás me enseñaron a hablarle a las damas.}

{210}{}{¿En qué te puedo ayudar?}
{211}{}{Adiós.}
{212}{}{Retrocedamos al inicio de la conversación.}
{213}{}{Retrocedamos un poco.}

{218}{}{¡Gracias por haberme rescatado! Eso fue muy peligroso. Como muestra de gratitud, te daré un buen descuento si necesitas nuestros servicios de transporte.}
{219}{}{Me parece bien.}

# Sending a package
{220}{}{Necesito enviar un paquete hacia Fénix.}
{221}{}{Necesito enviar un paquete hacia Two-Sun.}
{222}{}{Maravilloso. El costo de envío será de }
{223}{}{ chapas. Coloca tu paquete en la caja cerca de la pared y hazme saber cuando esté listo. Luego de la paga, será llevado a Fénix.}
{224}{}{Puedes enviar el paquete, aquí tienes las chapas.}
{225}{}{El paquete puede esperar, hablemos de otra cosa.}
{226}{}{No tengo tantas chapas en los bolsillos. Volveré en otro momento.}
{227}{}{(tras complicarse al escribir cada palabra, redacta el contrato y escribe tu nombre en el registro) Gracias por preferirnos. El paquete te estará esperando en su destino.}
{228}{}{}
{229}{}{Genial. Adiós.}
{230}{}{Lo lamento, pero eso no es suficiente.}
{231}{}{¿Podemos hablar de otra cosa?}
{232}{}{Bueno, iré a obtener más chapas.}

{240}{}{¿Puedo pagar con dinero viejo?}
{241}{}{¿Te refieres a los dólares y centavos de la preguerra? No, hace mucho que ya no se utilizan. Sin embargo, hay un casino en Fénix que los intercambia por chapas, pero es únicamente para sus clientes.}
{242}{}{Hablemos sobre mi paquete.}
{243}{}{Hmm. Eso cambia las cosas. No enviaré nada por el momento.}
{244}{}{Pronto vendrán unas caravanas del sur, deberíamos cooperar.}
{245}{}{Me temo que no podemos ofrecer descuentos. Esto no cubrirá los costos de envío.}
{246}{}{Que pena.}
{247}{}{Eso suena interesante. Podríamos cobrarte unas 50 chapas menos.}
{248}{}{No te arrepentirás.}
{249}{}{¿Qué tan confiable es este acuerdo?}

{250}{}{¿Estás segura de que sabes escribir?}
{251}{}{Mucho mejor que la mayoría de los "alfabetizados" de la ciudad. Hice cursos con los Seguidores del Fuego... pero no he tenido la práctica suficiente.}
{252}{}{Eh, sí, claro.}
{253}{}{Entregamos paquetes una vez al mes y raramente se han extraviado. Contamos con mensajeros experimentados, conocen bien tanto el terreno como técnicas de supervivencia. En el caso de que el paquete se pierda, podrás exigir una indemnización.}
{254}{}{¡Sé escribir, eso es OBVIO! Si no fuera así, no podría trabajar en esto.}
{255}{}{Como tú digas.}

{260}{}{¿Puedo dejar mi equipamiento contigo?}
{261}{}{Así es. Contamos con una taquilla de almacenamiento. Tus pertenencias serán protegidas bajo una cerradura de combinación segura y estará bajo supervisión. Cada taquilla tiene un precio de }
{262}{}{ chapas.}
{263}{}{Eso es demasiado caro.}
{264}{}{Está bien, me gustaría rentar una taquilla.}
{265}{}{Muy bien. Podrás accederla en todo momento.}
{266}{}{Gracias.}
{267}{}{Necesito otra taquilla.}

# Quest
{270}{}{Estoy buscando trabajo. ¿Están contratando?}
{271}{}{Por desgracia, no. Para serte honesta, hay un montón de personas que desean ser guardias en nuestras caravanas.}
{272}{}{Eso es una pena, de verdad necesito el dinero.}
{273}{}{¿En serio no hay ni un trabajo disponible en este lugar?}
{274}{}{Bueno, ¿crees que puedas hacerme un pequeño favor? Hace poco que perdí mi monedero. Tenía unas cositas adentro, pero lo que me importa importante es mi libreta. Lo más seguro es que me la hayan robado. Si la encuentras, tráemela y te pagaré.}
{275}{}{Dalo por hecho, tengo un buen olfato para hallar ladrones.}
{276}{}{Ah, entonces tu nariz tendrá que distinguir entre los cientos de olores que hay en esta ciudad. Buena suerte.}
{277}{}{No se preocupe, señora. Lo encontraré con facilidad.}
{278}{}{Todavía no.}
{279}{}{¡Esto es un desastre! ¿Y qué están haciendo los soldados de la guarnición? ¿Para qué pagarle impuestos a esos holgazanes?}

{280}{}{Acerca de tu monedero y tu libreta...}
{281}{}{¿Qué pasó? ¿Las encontraste?}
{282}{}{Me preguntaba si se te ocurre qué pudo haber pasado.}
{283}{}{No lo sé. Esta mañana tenía mis cosas, pero luego de salir a caminar por la colonia, desaparecieron. ¿Quizás los demás colonos vieron algo?}
{284}{}{Puede ser, le preguntaré a los demás.}
{285}{}{Claro que sí. Las tengo aquí.}
{286}{}{¡Oh! ¡Las encontraste! Me temía que jamás las iba a recuperar. Sabes, la información que hay aquí me importa mucho. Pero, ¿quién era el ladrón?}
{287}{}{Fueron los hijos de tu vecino.}
{288}{}{¿Fueron niños? ¡No puedo creerlo! Siempre hemos valorado a Flagstaff por lo segura que es, gracias a la guarnición y la barricada. Y resulta que los ladrones estaban adentro, no afuera. ¡Y además son niños!}
{289}{}{Sí, es terrible. Es imposible confiar en los demás.}
{290}{}{Obviamente no voy a hacer una denuncia a la guarnición. Pero tampoco me será fácil perdonar a mis vecinos. Alguien tiene que mantener el orden por aquí.}
{291}{}{Son niños, realmente no fue un robo, sólo estaban jugándote una broma.}
{292}{}{La gente que hace ese tipo de bromas terminan trabajando como esclavos. Obviamente no voy a hacer una denuncia a la guarnición. Pero tampoco me será fácil perdonar a mis vecinos.}
{293}{}{Parece que se te cayeron, las encontré en la calle.}
{1293}{}{Parece que se te cayeron, las encontré en la calle.}
{294}{}{¿En serio? No sé si creerte, pero no importa.}
{295}{}{Es bueno que tu problema ya esté resuelto.}
{296}{}{Ejem. Ya hice lo que me pediste, me falta mi recompensa...}
{297}{}{Muchísimas gracias. Te daré 20 chapas por haber encontrado mis cosas.}
{298}{}{Gracias a ti.}
{299}{}{Es mejor que nada...}

# Questions
{300}{}{¿Qué es este lugar?}
{301}{}{Esto es una oficina del Sonora Express, el único servicio postal en toda Arizona.}
{302}{}{Y, ¿qué cosas entregan?}
{303}{}{Entregamos paquetes pequeños, transferencias monetarias y cartas. Para paquetes más grandes, hay otra compañía, ellos trabajan con la mina de uranio.}
{304}{}{Jamás había oído algo así, es un negocio extraño.}
{305}{}{Así es. Antes no había necesidad de paquetes o de cartas; hay mucha gente que ni sabía escribir. Pero hubo una revolución más al sur y con ella vinieron muchos cambios. El Sonora Express es uno de ellos.}
{306}{}{Y, ¿qué es este lugar?}
{307}{}{¿Estás aquí sola, sin ningún guardia?}
{308}{}{El interior de la colonia es segura; debido a la guarnición y las patrullas, los saqueadores no pueden entrar. Pero más allá de este valle hay más y más forajidos, especialmente junto a las carreteras.}
{309}{}{¿Por qué?}
{310}{}{En el pasado, lo único que había junto a las rutas eran lobos y alguna tribu; los forajidos no tenían a nadie que asaltar. Pero eso cambió, porque hay personas y caravanas que vienen a Flagstaff, pues buscan ganar dinero.}
{320}{}{Cuéntame de ti.}
{321}{}{Me llamo Anne Brandley y soy la dueña de esta oficina.}
{322}{}{¿De dónde eres}
{323}{}{Soy de Fénix, eso está al sur de Flagstaff. Allí pasé toda mi niñez y mi juventud. Luego entregué paquetes y hacía intercambios hasta que terminé en el Sonora Express.}
{324}{}{¿Por qué te fuiste de Fénix?}
{325}{}{Es una ciudad grande pero congestionada, hay mucha competencia en todos los aspectos y eso impide que los negocios se expandan. Allí me hacía falta libertad y seguridad.}
{326}{}{¿Te fue difícil llegar aquí?}
{327}{}{Llegué por caravana junto a los primeros colonos. El camino fue difícil - nos movíamos lento a causa de nuestras maletas, no teníamos el agua limpia que nos hacía falta y nos atacaron varias tribus. Pero en ese entonces no habían tantos saqueadores como los hay ahora.}
{328}{}{¿Los mercenarios no te molestan?}
{329}{}{¿Te refieres a los soldados de la guarnición? No, no del todo. Esta oficina no estará en ningún peligro mientras mi esposo sea uno de ellos.}
{330}{}{¿Por qué los llamas 'soldados'?}
{331}{}{Bueno, hace tiempo solían ser una banda de esclavistas, pero ya salieron de eso. Ahora son como un pequeño ejército, protegen la ciudad e incluso tienen un 'general', es como en las historias de la preguerra. Aunque no parece que leas mucho.}
{332}{}{¿Te gusta cómo es la vida en este lugar?}
{333}{}{Las reglas son estrictas, pero no es malo si las aceptas. Estoy aquí para ganar dinero.}

# added by cambragol
{334}{}{Hm... El Sonora Express... Ustedes están en todos lados, ¿no?}

{350}{}{¿Cómo puedo llegar a Fénix?}
{351}{}{Fénix está al sur, es una gran ciudad, está justo aquí. (te la marca en el mapa) Sólo debes seguir la Ruta 17 sin desviarte.}
{352}{}{¿Puedo ir junto a sus mensajeros?}
{353}{}{No ofrecemos transportes de ese tipo; está en contra de la política de la compañía. Podrías intentar hablar con la caravana que transporta uranio; a veces necesitan un empleado extra.}
{354}{}{Genial, hablaré con ellos cuando tenga tiempo.}
{355}{}{Gracias, iré a hablarles de inmediato.}
