{100}{}{Ves a un ranger en frente tuyo.}
{101}{}{Ante ti se encuentra un ranger, sus ojos demuestran una determinación inquebrantable.}
{102}{}{Me iré de aquí tan pronto como empaque mis cosas.}

#First dialogue
{200}{}{¡Alto ahí! Da un paso más y te volaré los sesos.}
{201}{}{Está bien, te escucho, aquí me quedo. Pero no me dispares.}
{202}{}{Bien. Sé lo que estoy haciendo, así que no intentes nada.}
{203}{}{[Más]}
{204}{}{¿Me estás amenazando? ¡Sí que los tienes bien puestos!}
{205}{}{(dispara a unos centímetros de tus pies) La siguiente bala te reventará el cráneo.}
{206}{}{¡Espera, no me dispares!}
{207}{}{¡Hijo de perra!}
{208}{}{Cálmate. ¿Qué está ocurriendo?}
{209}{}{El rifle es de verdad. Y está cargado. Si te mueves, te mueres.}
{210}{}{Sí, entendí.}

{211}{}{Hmm. (baja el arma) No parece que seas un mercenario. ¿Quién eres y qué haces aquí?}
{1211}{}{Hmm. (baja el arma) No parece que seas una mercenaria. ¿Quién eres y qué haces aquí?}
{212}{}{Habla, antes de que te desparrame la cabeza.}
{213}{}{Uno de los dos va a morir, y no seré yo.}

{214}{}{¿Qué? ¿Qué quieres?}
{215}{}{(baja el arma) Hmm. Te perdiste, ¿verdad? La gente como tú me da pena. Tengo una bala, quizás debería dispararte y sacarte de tu miseria.}
{216}{}{¿Disparar? ¿Yo? ¿Miseria?}
{217}{}{No, no debería hacer eso. Es mejor que hagas de cebo para los mercenarios. Ve a dar una caminata. ¿Lo entendiste? ¡Anda, muévete!}
{218}{}{Ve a dar una caminata. ¡Anda!}

{220}{}{Sólo soy un viajero, estoy revisando si estas ruinas contienen algo de valor.}
{1220}{}{Sólo soy una viajera, estoy revisando si estas ruinas contienen algo de valor.}
{221}{}{Eso no me convence, debes estar aquí en contra de tu voluntad, o trabajas para los mercenarios de la guarnición.}
{222}{}{No es posible pedirle comida a la guarnición, hay que hurgar entre las ruinas.}
{223}{}{Estoy buscando chatarra, eso es todo.}
{224}{}{Esto solía ser el Museo de Arizona del Norte, era una de las atracciones de la ciudad.}
{225}{}{Te estoy diciendo la verdad.}
{226}{}{Te mentí, pero tengo una razón por la que estar aquí.}
{227}{}{Exacto. Y planeo llevarles tu cabeza.}
{228}{}{Al demonio con esto, ¡A PELEAR!}
{229}{}{¡Mí querer comer!}

{230}{}{(vuelve a levantar el arma) Debes pensar que soy un idiota.}
{231}{}{No puedo engañarte, ¿verdad? Estoy aquí por otra razón.}
{232}{}{Me llevaría demasiado tiempo explicártelo, es mejor que acabe contigo de una vez.}

{233}{}{De acuerdo, digamos que eso es verdad. Pero, ¿cómo conseguiste evadir mis trampas?}
{234}{}{Quizás atrapes a un niño con esas cosas, pero yo cuento con la experiencia de un trampero.}
{235}{}{Puse mucha atención, eso es todo.}
{236}{}{¿Trampas, en serio? Deberías haber colocado un aviso afuera.}
{237}{}{(muestras tus heridas) Bueno, no exactamente.}
{238}{}{No lo sé, supongo que tuve mucha suerte.}
{239}{}{Puede que funcionen con un niño. Pero no con alguien con experiencia.}

{240}{}{Supongo que debería haber prestado más atención en las clases de trampas.}
{241}{}{Entonces, ¿no me vas a disparar?}
{242}{}{Que respuesta más estúpida... (se prepara para dispararte)}
{243}{}{¡Espera, dame un momento! ¡Estoy aquí por otra razón, lo juro!}
{244}{}{[Prepárate para el ataque]}
{250}{}{No debería matarte. Por ahora. Puedes irte, pero ten cuidado por donde pisas.}
{251}{}{Está bien.}
{252}{}{Espera, necesito preguntarte algunas cosas.}
{253}{}{¡Chinga tu madre!}
{254}{}{(muestra tus heridas) ¡Mí doler!}
{255}{}{¿No dispararás?}
{256}{}{Hhh...}
{257}{}{«¡Chinga tu madre!»}

{260}{}{Se podría decir que soy un cazarrecompensas. He oído que me pagarán bien por tu cabeza.}
{261}{}{Eso es cierto, a Faber le pesa la consciencia porque sabe que algún día, la justicia lo encontrará. Tu muerte servirá como un pequeño recordatorio...}
{262}{}{Empecemos de una vez.}
{263}{}{Espera, no vine aquí para pelear.}
{264}{}{Sí, claro. Especialmente porque te estoy apuntando a la cabeza.}
{265}{}{Yo estoy pensando en apuntar a la cabeza de Faber. Hagamos un equipo, ¿qué me dices?}
{266}{}{¡Al diablo con esto, peleemos!}
{267}{}{¿Qué estás tramando?}
{268}{}{Mis parientes están encerrados en el corral de la guarnición. Necesito liberarlos.}
{1268}{}{Mis parientes están encerrados en el corral de la guarnición. Necesito liberarlos.}
{269}{}{¿Así que eso te trajo aquí? (empieza a bajar su arma) Tiene sentido, es justo lo que haría Faber.}
{270}{}{¿No me dispararás?}
{271}{}{Te engañé. ¡Cómete esta!}

{280}{}{Tengo una misión, estoy intentando liberar a mis parientes de la esclavitud.}
{281}{}{¿También los esclavizaron a ustedes? Los matones de Faber cada vez son más audaces. Solían capturar únicamente a criminales para hacerlos trabajar, pero ahora traen a personas inocentes.}
{282}{}{¿Y qué hay de tu arma? ¿Acaso planeas usarla contra mí?}

{283}{}{Estoy con los rangers, he venido a impartir la justicia a esta colonia.}
{284}{}{Es un gusto conocerte, pero no pedí refuerzos. Esto pondrá a mi cobertura en peligro.}
{285}{}{He venido aquí por voluntad propia.}
{286}{}{Entonces podremos llegar a un acuerdo. Pero si vienes aquí, asegúrate de que nadie te siga.}
{287}{}{Entiendo.}

# Re-dialogue
{300}{}{Te escucho.}
{301}{}{Hasta otro día, Ranger.}
{302}{}{Hasta luego.}

# Traps
{310}{}{Muéstrame en dónde están tus trampas, o saldré de aquí con una sola pierna.}
{311}{}{Esas trampas son la razón por la que sigo con vida. ¿Y quieres que suelte esa ventaja?}
{312}{}{Bueno, entonces mi destino depende de tus secretos. Adiós.}

{313}{}{Los dos somos rangers, puedes confiar en mí.}
{314}{}{Jeje, los nuevos reclutas siempre creen que son especiales. Ten cuidado con las puertas y no toques la puerta trasera.}
{315}{}{Te lo agradezco.}

{316}{}{¿Te preocupa que sea un espía de la colonia, no? No te preocupes, estoy contigo.}
{317}{}{Sí, quizás tengas razón... Ten cuidado con las puertas y no toques la puerta trasera.}
{318}{}{Gracias.}
{319}{}{Lo siento, no puedo.}
{320}{}{El ranger te ha revelado todas sus trampas en el interior del edificio.}
{321}{}{¿De verdad quieres verme morir?}
{322}{}{Bien, te indicaré. Evita las puertas y no toques la puerta trasera.}
{323}{}{Gracias.}
{324}{}{No. Pero yo no te traje aquí adentro.}

# Questions
{330}{}{Háblame de ti.}
{331}{}{Soy el Ranger Kuyuk, de la División Este de los Rangers de Arizona.}
{332}{}{Tengo algunas preguntas más.}
{333}{}{Ya veo.}
{334}{}{¿Cómo te volviste un ranger?}
{335}{}{Los Rangers me acogieron cuando era un niño. Mi aldea fue atacada por esclavistas, he dedicado mi vida entera a prevenir que esas tragedias vuelvan a ocurrir.}
{336}{}{¿Viniste sólo?}
{337}{}{En lugares como Flagstaff, es más fácil trabajar por tu cuenta, hace que evadir a los mercenarios sea más fácil.}
{338}{}{No debe ser nada fácil, porque es un ranger contra una banda entera.}
{339}{}{Exacto. Cuando se trata de asuntos locales, nuestros comandantes prefieren no interferir, así que decidí lidiar con esto por cuenta propia. Sin embargo, nadie intentó detenerme cuando me fui.}
{340}{}{¿Crees que los Rangers vuelvan a aceptarte después de esto?}
{341}{}{Sigo siendo un ranger, con la placa y todo. Puede que me den una reprimenda por cómo he actuado, pero sigo siendo uno de ellos.}
{342}{}{Tienes un nombre interesante.}
{343}{}{Ya no quedan muchos de mi tribu, dudo que hayas oído hablar de nosotros.}
{1343}{}{Ya no quedan muchos de mi tribu, dudo que hayas oído hablar de nosotros.}
{344}{}{Debe ser un nombre Indio. Mojave, Hopi... ¿Quizás Navajo?}
{345}{}{Hm. Me sorprendes. Tras la Lluvia de Fuego, mi tribu mantuvo la distancia de los blancos.}
{346}{}{Nuestras historias son parecidas, mi aldea sufrió ese mismo destino.}
{347}{}{Lo lamento... (te entrega varias balas de rifle) Úsalas. Véngate.}
{348}{}{Eh, gracias.}
{349}{}{Eso haré.}

# About the rangers
{370}{}{¿Podrías hablarme sobre los rangers?}
{371}{}{¿Qué quieres saber?}
{372}{}{Dame más detalles sobre los rangers.}
{373}{}{Ya hablamos suficiente de los rangers.}
{374}{}{¿Quiénes son los rangers, realmente?}
{375}{}{Nos encargamos de defender a la Ley y el Orden en el yermo. Nos dedicamos a cazar criminales, proteger asentamientos y a reconstruir un estilo de vida normal. Un ranger, antes que todo lo demás, debe tratarse de un guerrero y un superviviente.}

{380}{}{¿Qué se necesita para ser un ranger?}
{381}{}{Debes realizar años de entrenamiento, para después demostrar que estás listo a través de una misión. Hay muchos que no lo soportan.}

{384}{}{¿En dónde está tu base?}
{385}{}{¿Por qué te diría eso?}
{386}{}{No tengo malas intenciones.}
{387}{}{Quiero unirme a los rangers.}
{388}{}{Los rangers podrían ayudarme a salvar a mi pueblo.}
{390}{}{No me arriesgaré a darte las coordenadas, podrías entregárselas a nuestros enemigos.}
{391}{}{Entendible. Haz que no pregunté nada.}
{392}{}{En ese caso, lo conseguiré sin tu ayuda.}
{393}{}{En el Río Colorado, dentro de la presa. Lo marcaré en tu mapa.}
{394}{}{Gracias.}

# What you're doing here
{400}{}{Hablemos sobre tu misión.}
{401}{}{Soy un ranger. Mi misión es defender a la ley y la justicia. Los colonos acaban de cruzar la línea; han hecho las paces con la esclavitud. Mis cartuchos serán su sentencia.}
{402}{}{¿Qué era lo que decías sobre tu misión?}
{403}{}{Hablemos de otra cosa.}
{404}{}{Volvamos al tema de tu misión.}
{405}{}{Pero, según los colonos, ellos también defienden la ley y el orden, incluso si tú lo ves de otra manera.}
{406}{}{¡Tonterías! Sus leyes son falsas. En realidad, todo es como lo dictan los ricos, a quienes les dan igual todos los demás. Eso está mal, y yo estoy arreglándolo.}
{407}{}{Tienes razón. Usan esclavos, y merecen ser castigados por eso.}
{408}{}{Bien. Estamos de acuerdo. Los ricos lo deciden todo, y eso no puede seguir así.}
{411}{}{Bien. ¿Qué estás intentando conseguir, exactamente?}
{412}{}{Mientras que Roy Faber respire el aire de Arizona, yo no descansaré. Sin él, las cosas cambiarán. Su muerte servirá de advertencia para los demás.}
{413}{}{Ya veo. Me lo dejas claro, ranger.}
{414}{}{Hm, ¿esto significa que tu eres quien eliminó a las patrullas de la guarnición?}
{415}{}{Afirmativo. Recibieron su merecido.}
{416}{}{¿No te pesa la consciencia?}
{417}{}{No.}
{418}{}{Ya veo.}

{419}{}{Únicamente en defensa propia, o por el bien mayor.}
{420}{}{¿Sabías que Faber puso una recompensa por tu cabeza?}
{421}{}{Le convendría triplicarla.}
{422}{}{¿Qué opinas de Faber?}
{423}{}{Es un tirano, que sueña con sus propias ambiciones, uno que busca formar su propio imperio. En realidad, es un criminal cualquiera, que controla a los demás con el uso del miedo y la violencia.}
{424}{}{Gracias.}

# Leaving Flagstaff
{450}{}{Debo pedirte que te vayas de Flagstaff.}
{451}{}{Me quedaré aquí.}
{452}{}{Entonces quédate, no te detendré.}
{453}{}{Veremos qué tienen que decir alguno de tus altos mandos. Hasta luego.}
{454}{}{¿Qué puedo hacer para cambiarte de parecer?}
{455}{}{No voy a descansar hasta ponerle fin a la esclavitud aquí presente.}
{456}{}{La presa de los rangers fue inundada, ¿no crees que deberías regresar?}
{457}{}{¡Demonios! Si no hubiese sido por el silencio de la radio, jamás me habría enterado. Qué malas noticias. Hablaré con alguno de los puestos, y si me lo confirman, regresaré.}
{458}{}{Entonces, estamos de acuerdo. Adiós, ranger.}
{459}{}{El General Mossman ha ordenado que regreses a la base. Es una orden.}
{460}{}{Maldita sea, ¿¡por qué no puede dejarme en paz!? Esta misión también es importante... Está bien, contactaré a uno de nuestros puestos. Si confirman lo que dices, regresaré.}
{461}{}{Bien. Adiós, ranger.}
{462}{}{Tus acciones no solo hieren a los criminales, también has herido inocentes.}
{463}{}{A veces, se necesita una mala acción para solucionar un problema. No es una justificación, es una necesidad.}
{464}{}{No... No lo había pensado así. Quizás sí deba coordinarme con el cuartel general. Voy a regresar y tendré una charla con el general.}
{465}{}{Has tomado una sabia decisión. Adiós, ranger.}

{467}{}{Sé honesto contigo mismo. Considera tus motivos.}
{468}{}{Mi motivo es erradicar a la injusticia. ¿Acaso no es suficiente?}
{469}{}{Bueno, creo que tienes razón.}
{470}{}{Veo que no podré convencerte. Me marcho.}
{471}{}{Estás obsesionado con eso, por culpa de tu pasado.}
{472}{}{¿Qué sabrás tu de mi pasado? He luchado tanto, que me olvidé de lo que era la paz... O el hogar, o la familia... ¡Y es todo por culpa de los desgraciados como Faber!}
{473}{}{Sí, eso es lo que quiero decir. No estás siendo honesto contigo mismo, estás matando en nombre de la venganza.}
{474}{}{Quizás... Quizás tengas razón. Tal vez sí estoy obsesionado con ello. El general dijo algo muy parecido. Está bien, regresaré y tendré una charla con él.}
{475}{}{Hasta luego, ranger.}

{480}{}{Faber está muerto. ¿Eso es suficiente para ti?}
{481}{}{¿De verdad? ¿Está muerto? (inhala rápidamente y toma una pausa repentina) Puedo sentirlo. El aire de Arizona ha quedado un poco más limpio. Gracias. Por fin, puedo regresar a la base.}
{482}{}{Adiós, ranger.}