{100}{}{Ves a un colono.}
{101}{}{Ves a un colono de Flagstaff.}
{102}{}{No me molestes.}
{103}{}{¡Estás loco! ¿¡Por qué mataste a mi sirviente!? ¿¡Quién me lo va a pagar!?}
{1103}{}{¡Perra de mierda, estás loca! ¿¡Por qué mataste a mi sirviente!? ¿¡Quién me lo va a pagar!?}


#Random remarks
{110}{}{Eres un inútil.}
{111}{}{¡Hijo de tu chingada madre!}
{112}{}{¡Bueno para nada!}
{113}{}{Levántate y sécate las lágrimas, pedazo de mierda.}
{114}{}{Ni siquiera debería tocarte con mi zapato sucio.}
{115}{}{¿Y para esto me gasté las chapas?}
{116}{}{Parece que los carceleros me cobraron más de la cuenta, eres una basura.}
{117}{}{*Empuja al sirviente con el pie*}
{118}{}{¿¡Me acabas de mirar mal!?}
{119}{}{¡Vas a cavar tu propia tumba! ¿¡Me escuchas!?}
{120}{}{Recuerda que tu dueño soy yo.}

#First dialogue
{200}{}{(Ves a un hombre delgado y furioso que golpea a un sirviente, mientras éste se disculpa)}
{201}{}{¡Oye! ¿Por qué golpeas a este hombre?}
{202}{}{Eso no es un hombre, es propiedad mía. Necesitaba un sirviente, y ni para eso sirve. Tengo que sacarle la mugre a golpes para que aprenda a ser útil. ¿Y a ti qué te importa? Lárgate, no es asunto tuyo.}
{203}{}{Tienes razón, no tengo nada que ver en esto.}
{204}{}{Me alegra que nos entendamos. ¡Levántate! Hoy vas a dormir afuera. Anda a limpiar el piso de la cocina. ¡Y Hazlo bien!}
{205}{}{[Más]}
{206}{}{Tratar así a tu sirviente te hace ver mal ante los demás.}
{207}{}{¡No pedí tu opinión!}
{208}{}{Hmm, buen punto. Está bien, por hoy lo dejaré pasar. Pero sólo hoy.}
{209}{}{[Más]}
{210}{}{Te daré cinco chapas para que lo dejes en paz.}
{211}{}{¿Escuchaste eso, perro asqueroso? Alguien pagará cinco chapas por ti. Vales algo, ¿quién lo diría?}
{212}{}{Ten, son cinco chapas.}
{213}{}{Nada mal. ¡Tú! Por hoy tienes el día libre.}
{214}{}{[Más]}
{215}{}{Dale un golpe más y te arrepentirás.}
{216}{}{¿EN SERIO? Escúchame, paleto de mierda. Aquí tenemos nuestras propias reglas, y si no las cumples, llamaré a los guardias. Ahí veremos quién se arrepiente.}
{217}{}{Ya, ya, sólo estaba de mal humor... Pero si me tocas, llamaré a los guardias, y te vas a arrepentir tú.}
{218}{}{[Más]}
{219}{}{}
{220}{}{Déjame darte un consejo. No sé qué estás pensando, pero a los sirvientes tenemos que mantenerlos en su lugar. O las cosas podrían terminal mal... Adiós.}
{221}{}{Adiós.}
