{100}{}{Ves a un minero.}
{101}{}{Ves a un hombre sucio y desnutrido.}
{102}{}{Me salvaste.}
{103}{}{Eres muy valiente, no le diré a nadie que mataste a Látigo.}

{110}{}{¡Ah! ¡Aah!}
{111}{}{¡Por favor, ten piedad!}
{112}{}{¡Eso duele mucho!}
{113}{}{¡Ayúdame! ¡Te lo ruego!}
{114}{}{¡Aahh! ¡Ayuda! ¡Me muero!}

{120}{}{Jamás te olvidaré.}
{121}{}{Ojalá fuera igual de valiente que tú.}
{122}{}{No tengo palabras para expresar mi agradecimiento.}
{123}{}{El supervisor nuevo es mucho mejor que el anterior.}
{124}{}{Látigo era un maldito animal.}
{125}{}{¿Cómo te deshiciste de Látigo?}

#Dialogue
{200}{}{Gracias amigo, pensé que me iba a morir. Pero no sé que es mejor - seguir sufriendo en esta vida o encontrar la paz en la siguiente.}
{1200}{}{Gracias señorita, pensé que me iba a morir. Pero no sé que es mejor - seguir sufriendo en esta vida o encontrar la paz en la siguiente.}
{201}{}{¿Quién te hizo esto?}
{202}{}{Fue el capataz. Todos los prisioneros lo odiamos; hasta le pusieron un apodo - Látigo. Es peor que el Diablo, apenas se enoja, nos azota.}
{203}{}{¿Qué hiciste para provocarlo?}
{204}{}{Debido a todo el trabajo, ya no me quedan fuerzas. Colapsé mientras empujaba la vagoneta y se cayó todo el mineral.}
{205}{}{¿Y te golpeó por algo así? La tienes difícil...}
{206}{}{'Difícil' es quedarse corto, nos pasamos del plazo de entrega, y además hay rumores de ratas gigantes en la mina. Nuestros jefes están furiosos, y se desquitan con nosotros.}
{207}{}{Ya veo.}
{208}{}{Espera, tú no eres un guardia. ¿Eres parte de una caravana o algo así?}
{1208}{}{Espera, tú no eres una guardia. ¿Eres parte de una caravana o algo así?}
{209}{}{No. Busco a mis parientes, son campesinos de la Villa. ¿Sabes algo al respecto?}
{210}{}{¡Todos los conocemos! Pero, tengo malas noticias - Sancho y Hugo bajaron a la mina, y desde ese entonces no sabemos nada de ellos.}
{211}{}{Gracias por contármelo. Descansa lo que puedas.}
{212}{}{No es asunto tuyo.}
{213}{}{Ya, ya. Sólo existo para obedecerle, señor. Pero, gracias por la ayuda. Te debo una.}
{1213}{}{Ya, ya. Sólo existo para obedecerle, señora. Pero, gracias por la ayuda. Te debo una.}
{214}{}{Así es. Fuera de mi camino.}
{215}{}{De nada. Adiós.}
{1215}{}{De nada. Adiós.}
{216}{}{De hecho, busco a mi familia. Son campesinos de la Villa, ¿sabes algo de ellos?}

{220}{}{¡Mi salvador!}
{1220}{}{¡Mi salvadora!}
{221}{}{Cuídate.}
{222}{}{Silencio, idiota.}
