{100}{}{Ves al Centinela Davis.}
{101}{}{Ves a un mercenario que mantiene el orden en la guarnición.}
{102}{}{¡Basta! ¡Te voy a pagar, pero cálmate!}

{200}{}{¡Alto ahí! ¿Por qué quieres entrar en la guarnición?}
{201}{}{No es asunto tuyo..}
{202}{}{Creo que mi gente está ahí dentro.}
{203}{}{La verdad nada. Déjame pasar.}
{204}{}{Bueno, pasa. La verdad no me importa, pero tengo que preguntar.}
{205}{}{Vale.}
{206}{}{No puedes andar allá afuera luego del toque de queda. Vuelve por donde viniste antes de que te reventemos a tiros.}

{210}{}{¿Qué quieres?}
{211}{}{Tengo que hablar contigo sobre el dinero que le debes al bar.}
{1211}{}{Tengo que hablar contigo sobre el dinero que le debes al bar.}
{212}{}{Nada.}
{213}{}{¡Ja! Nunca te pagaré esas chapas.}
{214}{}{¿Por qué no puedes pagar tu deuda y ya?}
{215}{}{Paga tus deudas, o terminarás siendo un esclavo en las minas.}
{216}{}{Si ese es el caso, entonces tendré que quitártelas a la fuerza.}
{217}{}{Ya lo veremos.}

{218}{}{¿Por qué debería saldar la deuda? Gracias a mi posición, es más fácil quitar que dar. ¿Quieres probar mi teoría?}
{219}{}{Porque te saldrá el tiro por la culata. Si no les pagas, te enviarán a la mina como a un esclavo.}
{220}{}{Me haces perder el tiempo, te quitaré las chapas a la fuerza.}
{221}{}{Ya no me importa. Adiós.}

{222}{}{Deja de fanfarronear, tengo a un ejército entero ahí adentro, me cubrirán la espalda.}
{223}{}{Bueno, ya lo veremos.}
{224}{}{Sal de vista antes de que pierda la paciencia.}
{225}{}{Cálmate, no es necesario amenazarme... Toma las chapas. Ahora déjame en paz.}
{226}{}{Buen chico.}
{227}{}{¡Ya, ya! ¡Llévate mis chapas, pero déjame en paz!}
{228}{}{Muy bien hecho.}
{229}{}{Está bien, no quiero problemas.}

// added for the case that the player robs him of the money before asking for it - cambragol
{230}{}{¿¡Qué!? No sé por qué te importa. Además, alguien robó mis chapas. Estoy quebrado.}
{231}{}{Por alguna razón, te creo. Tuviste suerte.}

