{100}{}{Ves a Sancho.}
{101}{}{Ves a un esclavo. Al mirar más de cerca, reconoces a uno de tus paisanos, a pesar de su rostro sucio y demacrado.}

{102}{}{Ay, ojalá que nadie en la Villa se entere de esto...}
{103}{}{¡Eres un pinche traidor! ¡Se te metió el Diablo!}
{1103}{}{¡Eres una puta traidora! ¡Se te metió el Diablo!}
{104}{}{Sancho jamás regresará a la villa.}
{105}{}{Sancho regresó a la Villa. Por haberlo salvado, recibes }
{106}{}{Bueno, es lo que es.}
{107}{}{Nos vemos en la Villa.}
{1107}{}{Nos vemos en la Villa, amiga.}
{108}{}{ puntos de experiencia.}

#First dialogue
{200}{}{, ¿Eres tú? ¡Es un milagro! Pensábamos que nadie vendría.}
{201}{}{Voy a sacarlos de aquí.}
{202}{}{Justo a tiempo, llévanos a la salida. Desde ahí, podremos salir de aquí por cuenta propia.}
{203}{}{Ya llegamos a la entrada. La libertad está cerca.}
{204}{}{¿Dónde están los demás?}
{205}{}{¿Cómo acabaron aquí?}
{206}{}{¿Se quitaron los collares? ¿Cómo?}
{207}{}{¿Qué puedes contarme sobre la mina?}
{208}{}{Sancho, un día me herí la pierna y me cantaste "la cucaracha", ¿te acuerdas?}
{209}{}{Bueno, vámonos.}

{210}{}{Nos separaron apenas llegamos. Dejaron a algunos en el corral, incluyendo a tu madre. A los demás los sacaron de Flagstaff, no los he visto desde entonces.}
{211}{}{Fue un mal plan. Intentamos cavar un túnel hacia el yermo y así escaparnos, pero ocupábamos explosivos. Nos salió mal, y colapsó el túnel.}
{212}{}{Uno de los esclavos nos dijo que los collares no funcionan en la mina.}
{213}{}{No es más que un agujero horrendo con ratas por todos lados. No hay ni una criatura así en la Villa, y hasta dicen que hay más. Tuvimos suerte, los evitamos.}
{214}{}{Los mercenarios metieron aquí dentro, ¿por qué?}
{215}{}{¡Para sacar ese maldito mineral! Lo limpian y lo envían a otra ciudad, creo que para producir energía. En la Villa usamos madera y aceite. ¿Cómo van a quemar una piedra? Seguro que nos ven la cara de tontos.}
{216}{}{¡Perdóname, por favor! Dejemos atrás el pasado; somos de la misma Villa, jamás volveré a hablar mal de ti, lo juro.}
{217}{}{Espera, primero dime lo que ocurrió.}

{220}{}{¿Qué?}
{221}{}{¡Esa rata era inmensa!}
{222}{}{¡Gracias por ayudarnos! Podremos irnos por cuenta propia, será más fácil escaparnos si somos dos. Debes rescatar a los demás, te ayudaríamos, pero luego de pasar por todo esto no seremos de mucha ayuda. Buena suerte.}
{223}{}{Te veo en la Villa.}
{224}{}{Sí, odiaría que esto ocurra de nuevo. Intenta colapsar la mina, quizás destruya sus operaciones y no necesitarán más esclavos.}
{225}{}{Usar explosivos para colapsar la mina... ¡Qué buena idea!}
{226}{}{Lo dudo mucho. Será más trabajo para los esclavos.}
{227}{}{Hay algunos explosivos dentro de un almacén en la mina, el administrador tiene la llave. Buena suerte.}
{228}{}{¡Pero eso sería como alimentar al Rey Rata! Sólo van a buscar más esclavos. ¿Acaso no lo entiendes? ¿O estás asustado por lo que pasó? Piénsalo; es lo correcto. Adiós.}
{229}{}{Lo pensaré. Ahora váyanse.}
