{100}{}{Ves a Larry.}
{101}{}{Ves a un cliente, tiene un aspecto desaliñado y malos modales.}
{102}{}{Eso es otra cosa. Tu turno. No, vete al infierno.}
{103}{}{¡Oye, tú! Cómpranos un trago.}

{200}{}{¡Oye! Los pueblerinos mugrosos como tú no suelen aparecerse en Ciudad Garaje.}
{201}{}{[Ignóralo]}
{202}{}{Miren, chicos, la vida de esta ciudad es demasiado rápida para un pendejo como él. Seguro pensaste que podías sobrevivir aquí, ¿no?}
{1202}{}{Miren, chicos, la vida de esta ciudad es demasiado rápida para una pendeja como ella. Seguro pensaste que podías sobrevivir aquí, ¿no?}
{203}{}{No soy tan idiota como piensas.}
{204}{}{(Cierra la boca y luego de una corta pausa vuelve a su asiento) Si tú lo dices. Pero la gente suele olvidar muchas cosas, como invitarle unas copas a los demás.}
{205}{}{No te compraré nada.}
{206}{}{Lo tendré en mente.}
{207}{}{Mira, déjame en paz. Sólo quiero encontrar a mi familia.}

{208}{}{No te gusta mi compañía, por lo que veo. Si ese es el caso, tampoco te gustará el resto de la ciudad. Si fuera tú, le compraría un trago a todos los demás para dejarles una buena impresión.}
{209}{}{Púdrete, no voy a perder el tiempo con esto.}
{210}{}{(frunce el labio con desdén y odio) En esta ciudad, responderle así a la gente es una buena forma de ganarse una golpiza. Cómprame algo para beber y olvidaré lo que dijiste.}
{211}{}{¿Cómo me acabas de llamar?}
{212}{}{¿Qué, acaso no me escuchaste? Mira, la vida en esta ciudad es demasiado rápida para alguien como tú. Seguro pensaste que podrías sobrevivir aquí, ¿no?}
{213}{}{Voy a irme, ahora mismo, no quiero problemas.}
{214}{}{¿Crees que te puedes ir así sin más? ¿Luego de entrar a nuestra ciudad y joder la paz de nuestro bar?}
{215}{}{Eh, sí.}
{216}{}{Cómpranos algo para beber. O vete al infierno.}

{220}{}{¿Qué quieres?}
{221}{}{Nada.}
{222}{}{¿Nada? ¿Entonces por qué demonios me molestas?}
{223}{}{Olvídalo.}

{230}{}{¿Quién eres?}
{231}{}{¿Quién soy? Soy el que conoce cada rincón de esta ciudad, con el que compartes, y al que le hablas con respeto. Ten cuidado con lo que dices.}
{232}{}{¿No tienes nombre?}
{233}{}{Me llamo Larry. No te volveré a repetir.}
{234}{}{Lo que tú digas, Larry.}
{235}{}{No te soporto, te voy a quitar esa sonrisa de la cara.}
{236}{}{Me llamo Larry. En esta ciudad, hago... distintas cosas. Por ejemplo, protejo la ciudad si es necesario. No lo hago gratis, por supuesto.}
{237}{}{¿No eres parte de los chatarreros?}
{238}{}{No, imbécil. Soy parte de un equipo de chatarreros bastante bueno, a los que no les gusta que gente sospechosa llegue a su ciudad.}
{239}{}{Y según tú, soy una de esas personas. ¿No?}
{240}{}{¿Y qué me vas a hacer? ¡Muéstrame lo que tienes, mamón!}
{241}{}{No, ya no busco chatarra. Mientras que el Sr. Kogan me pague, no tengo por qué hacerlo.}
{242}{}{No, ya no busco chatarra. Ensucia mucho las manos.}
{243}{}{Comprendo.}

{250}{}{Estar aquí dentro es lo único que haces, ¿no es así?}
{251}{}{Tengo mucho trabajo que hacer, sólo estoy aquí para beber un rato. ¿Alguna otra pregunta?}
{252}{}{No, creo que no.}
{253}{}{El cantinero sólo tiene tragos aguados, pero eso es suficiente para pasar el rato. He esperado el año entero por una bebida de verdad, pero sólo vende basura. Y así estamos, todo el año.}
{254}{}{Siento oir eso.}
{255}{}{Algún día tendrás que salir de aquí.}
{256}{}{Estoy buscando una caravana que transportaba esclavos, ¿sabes algo de eso?}
{257}{}{Sí, yo la vi. Pero no te diré nada. Piérdete.}
{258}{}{De acuerdo. Si no me lo dices tú, alguien más lo hará.}
{259}{}{Estás cometiendo un grave error.}

{300}{}{¿Qué te pasa? ¿Acaso te caemos mal?}
{301}{}{Vete a la mierda, pendejo.}
{302}{}{¡Nadie me habla así! ¡Estás muerto!}
{303}{}{[Defiéndete]}
{304}{}{Mira, de verdad tengo que irme. Es importante.}
{305}{}{¡Escuchen, todos! ¡Tiene que hacer cosas muy importantes!}
{306}{}{Tengo que salvar a mi gente...}
{307}{}{¡Pero mírenlo! ¡Está en una noble misión para salvarlos a todos! ¡Hagan paso!}
{1307}{}{¡Pero mírenla! ¡Está en una noble misión para salvarlos a todos! ¡Hagan paso!}
{308}{}{¡Suficiente! ¡Te voy a cortar la lengua!}
{309}{}{En serio, tengo que irme.}
{310}{}{¿Qué tal si te doy diez chapas y nos olvidamos de esto?}
{311}{}{Bien pensado, amigo. Lárgate de aquí.}
{1311}{}{Bien pensado, amiga. Lárgate de aquí.}
{312}{}{Pensándolo bien, quiero mis chapas de vuelta. ¡Dámelas!}
{1312}{}{Pensándolo bien, quiero mis chapas de vuelta. ¡Dámelas!}
{313}{}{Como tú digas...}
