{100}{}{Ves al Sr. Kogan.}
{101}{}{Ves a un gordo desaliñado con un traje de negocios sucio. Parece que está al mando aquí.}
{102}{}{¡Traga plomo, maldita rata cerdo!}
{103}{}{¿Qué debe sentir un chatarrero cuando su destino depende de la basura?}
{104}{}{¡Oye! No tengo nada que ver en esto. ¡Le está dando un ataque al corazón!}
{105}{}{No estoy en contra de hablar contigo, pero debes salir de esa cosa.}
{106}{}{Lárgate de mi ciudad.}
{107}{}{Fuera de mi garaje.}

#Floating replicas (do not delete empty lines!)
{110}{}{*Cof cof*}
{111}{}{*Agh*}
{112}{}{*Urp*}
{113}{}{*Eructo*}
{114}{}{Maldita acidez...}
{115}{}{ }
{116}{}{ }
{117}{}{ }
{118}{}{ }
{119}{}{ }

#Cut-scene
{120}{}{ }
{121}{}{¡Sr. Kogan! ¡Sr. Kogan!}
{122}{}{¡Puta madre, Larry! ¿Por qué carajo entraste así a mi oficina?}
{123}{}{¿Qué demonios haces? Sabes lo que pasa si entras así a mi oficina.}
{124}{}{¡Sr. Kogan! ¡Hay un problema grave en el dormitorio!}
{125}{}{¡Siempre lo mismo con esta ciudad! Bueno, ¿y qué pasa ahora? Probablemente otro par de borrachos peleándose.}
{126}{}{No, creo que no es eso. Es algo mucho más serio, no entendí por qué peleaban, vine corriendo hasta acá...}
{127}{}{¡Pues ve y averigua, idiota!}

#Dialogue
{170}{}{He visto ese tipo de ropa antes. ¿Qué conexión tienes con los Seguidores del Fuego?}
{171}{}{La más directa que puede haber, soy parte de la iglesia.}
{172}{}{Hmm... que interesante. Suelo evitar la religión, pero los Seguidores han contribuido al progreso de Arizona y como resultado, al desarrollo de mi cartel. Puedes sentirte a salvo aquí.}
{173}{}{Pues, es bueno saber eso.}
{174}{}{¿Puedo contar con que tu garaje me de el servicio completo?}
{175}{}{Por supuesto, se lo diré a Pete.}
{176}{}{Gracias.}
{177}{}{Esta es la primera vez que escucho hablar acerca de los "Seguidores del Fuego.". Me encontré esta túnica en un cadáver en el yermo.}
{1177}{}{Esta es la primera vez que escucho hablar acerca de los "Seguidores del Fuego.". Me encontré esta túnica en un cadáver en el yermo.}
{178}{}{¿En serio? Entonces olvida lo que dije.}
{179}{}{Lo haré.}

{180}{}{He escuchado que tuviste un... problema, con Larry. ¿Es cierto?}
{181}{}{No fue nada, es sólo que él estaba buscando problemas en el bar.}
{182}{}{Debes tenerlas bien puestas si crees que puedes matar a mi gente. Por otro lado, he querido deshacerme de ese maldito borracho por un largo tiempo. Jamás dejaba de causar problemas.}
{183}{}{¿Así que no me harás nada?}
{184}{}{Tendrás que trabajar arduamente para ganarte mi respeto. Eso depende de ti.}
{185}{}{Está bien...}
{186}{}{¡Él empezó! Yo me defendí, eso es todo.}
{1186}{}{¡Él empezó! Yo me defendí, eso es todo.}
{187}{}{Lo que pasó fue entre él y yo. No es asunto tuyo.}

{190}{}{Tú otra vez... (suspiro) ¿Has escuchado sobre los Rangers? Detesto a esos tipos, siempre meten mano en asuntos que no les incumben, como si el yermo entero les perteneciera. No estarás pensando en hacer eso en *mi* ciudad, ¿verdad?}
{191}{}{No, Sr. Kogan. No estoy aquí por eso.}
{192}{}{Muy bien, entonces creo que nos entendemos. No olvides a quién le pertenece este lugar.}
{193}{}{Entendido.}
{194}{}{Más te vale que hables de los Rangers con respeto, algún día tendremos a toda Arizona bajo nuestro control.}
{195}{}{Lo dudo mucho, los Rangers tienen muchos enemigos y sus filas demasiado pequeñas como para controlar a la población por sí mismos. Y ciertamente nunca ganarán el control de esta ciudad mientras yo esté vivo.}
{196}{}{¿Cuál es tu problema con los Rangers?}
{197}{}{No tengo *ningún* problema con ellos, pero no voy a compartir mi poder con nadie. Le he puesto mucho esfuerzo a este lugar, cuando fundé esta ciudad, fue prácticamente desde cero.}
{198}{}{Tienes razón, debería pensármelo.}
{199}{}{Los Rangers están ocupados con sus propios intereses y no son capaces de producir nada nuevo. Y en este momento, eso es exactamente lo que la gente necesita.}

{200}{}{(Estás viendo a un hombre obeso con un desgastado traje de negocios, al verlo junto a las ruinas, está muy fuera de lugar. Al verte, deja de prestarle atención a un dispositivo y se quita los audífonos conectados a él.)}
{201}{}{Ejem. ¿Estás a cargo aquí?}
{202}{}{(hace los audífonos a un lado y presiona algunos botones del dispositivo, entonces lo señala) Esto es un viejo reproductor de cintas. Antes de la Gran Guerra, solían ser producidos por una compañía famosa, se llamaba Wattz Electronics. Este modelo no era de gama alta, pero estaba bien hecho. El hecho de que todavía funcione es prueba de eso.}
{203}{}{[Escúchalo]}
{204}{}{Es por esto que me encantan las cosas antiguas, nuestros ancestros cometieron muchos errores, pero sí que sabían como hacer reproductores de cintas. En aquel entonces, habían muchas fábricas operando en Arizona, producían una variedad de dispositivos, herramientas y maquinaria. Y ahora, todas se esfumaron.}
{205}{}{¿Y quién necesita cosas así de viejas?}
{206}{}{Sabía que no lo entenderías. ¿Qué quieres, niño?}
{1206}{}{Sabía que no lo entenderías. ¿Qué quiere, señorita?}
{207}{}{Sí... El mundo ha perdido mucho, de eso no cabe duda.}
{208}{}{Hmm. Pensaba que no estarías de acuerdo. Aunque al fin ya al cabo, ni tú ni yo tenemos el poder para traer el pasado de vuelta. Así que, ¿qué necesitas, joven?}
{1208}{}{Hmm. Pensaba que no estarías de acuerdo. Aunque al fin ya al cabo, ni tú ni yo tenemos el poder para traer el pasado de vuelta. Así que, ¿qué necesita, señorita?}
{209}{}{¡Deja de perder el tiempo con un reproductor! No vine hasta acá para escucharte hablar sobre esa cosa vieja.}
{1209}{}{¡Deja de perder el tiempo con un reproductor! No vine hasta acá para escucharte hablar sobre esa cosa vieja.}
{210}{}{No eres muy intelectual, ¿cierto? ¿Qué quieres, niño?}
{1210}{}{No eres muy intelectual, ¿cierto? ¿Qué quiere, señorita?}

{211}{}{Soy de la Villa, he venido aquí porque alguien esclavizó a los nuestros y los trajeron por aquí.}
{212}{}{A nadie le gusta que le estropeen la rutina. Yo detesto cuando las ruinas quedan vacías de artefactos - porque entonces hay que buscar otro lugar, lo que pone nerviosos a mis empleados. Tengo unas docenas de chatarreros bajo mi mando, además de tratos comerciales con otros grupos por Arizona y más allá.}
{213}{}{[Más]}
{214}{}{Si los comparamos con nosotros, la Villa lo tiene fácil. Ustedes cosechan maíz, nosotros recogemos chatarra. Pero la chatarra no vuelve a crecer. Ustedes no lo entienden, su mundo es su pueblo y nada más. Nosotros, los chatarreros, mantenemos al sur de Arizona en marcha con lo que hallamos. A nadie le importa lo que le pase a la Villa, sólo a ustedes.}
{215}{}{¿Eres el responsable de la captura de mi pueblo, hijo de perra?}
{216}{}{¿Así que no niegas que tuviste algo que ver en el asunto?}
{217}{}{¿Yo? Claro que no. Eso fue la acción de otra organización, una mucho más poderosa. No éramos más que una parada en su viaje. Si estuviera en tus zapatos, me olvidaría de todo esto, regresaría a mi casa y empezaría de nuevo.}
{218}{}{¿Crees que es así de simple?}
{219}{}{Es tu única opción. Sin embargo, podrías quedarte a trabajar, serías parte de los chatarreros. ¿Qué dices?}
{220}{}{Yo...}
{221}{}{Parece que estás disfrutando el sufrimiento de mi Villa.}
{222}{}{¿Que lo disfruto? No. Pero en el pasado, NOSOTROS nos estábamos muriendo de hambre y USTEDES le sacaron provecho a nuestro sufrimiento al cobrarnos más por la comida. ¿Y bien? ¿Qué se siente que te lo hagan a ti?}
{223}{}{Eso no es lo que te pregunté.}

{230}{}{Los chatarreros pueden ser muy brutos cuando se emborrachan. Escucha, si planeas estar aquí, vas a necesitar mi protección. Esta es tu oportunidad para demostrarme lo que vales.}
{231}{}{¿Estás diciendo de que resuelva el problema con los trabajadores?}
{232}{}{Ve al dormitorio y averigua qué pasó ahí. No necesito que hayan más problemas en esta ciudad.}
{233}{}{Voy a ver qué puedo hacer.}
{234}{}{No sé si quiero trabajar para ti.}
{235}{}{Genial. Ah, cierto, no me presenté. Mi nombre es Karl Kogan, yo estoy a cargo en esta ciudad. Ve, ponte a trabajar.}
{236}{}{. . .}
{237}{}{Entonces no tienes lugar en Ciudad Garaje. Piérdete.}
{238}{}{. . .}
{239}{}{¿Por qué debería meterme en una disputa local?}
{240}{}{¿Acaso mi buena voluntad no te basta? Sé todo acerca de tus enemigos, no olvides eso - sé más que cualquiera en Ciudad Garaje.}
{241}{}{¿Qué descubriste acerca de la pelea en el dormitorio?}
{1241}{}{¿Qué descubriste acerca de la pelea en el dormitorio?}
{242}{}{Nada, me pondré en ello.}
{243}{}{¿Te puedo hacer un par de preguntas?}
{244}{}{Primero demuestra que mereces mi atención. ¿O acaso ya estás pensando en irte de la ciudad?}
{1244}{}{Primero demuestra que mereces mi atención. ¿O acaso ya estás pensando en irte de la ciudad?}
{245}{}{Está bien, haré lo que me pides.}
{246}{}{Eso es justo lo que voy a hacer.}
{247}{}{Los chicos de Lucas le robaron un decodificador a los hombres de Trayvon y luego se fueron de la ciudad. Hablaban sobre un decodificador.}
{248}{}{¡Ya lo sé, idiota! ¿Hace cuánto que te encargué esto? Tu oportunidad de demostrarme que eres útil está a punto de irse al caño.}
{1248}{}{¡Ya lo sé! ¿Hace cuánto que te encargué esto? Tu oportunidad de demostrarme que eres útil está a punto de irse al caño.}
{249}{}{¿De qué se trata todo esto?}
{250}{}{No esperaba que Lucas hiciera esto, su clan tenía una reputación de ser un equipo pequeño pero duro. Si decide estar en mi contra, tendrá que pagarlo caro.}
{251}{}{Tengo preguntas acerca del problema con Lucas.}
{252}{}{¿Puedo hacer algo más para ayudarlo, Sr. Kogan?}
{1252}{}{¿Puedo hacer algo más para ayudarlo, Sr. Kogan?}

{253}{}{Tengo las respuestas.}
{254}{}{Los clanes tienen rencor entre sí, ¿por qué?}
{255}{}{Las ruinas ya casi no tienen chatarra, lo que dificulta que los chatarreros puedan sobrevivir. Los clanes solían llevarse bien - había suficiente para todos. Pero ahora compiten ferozmente entre ellos.}
{256}{}{¿Qué tiene de especial el decodificador?}
{257}{}{Es un dispositivo escaso, ayuda a piratear sistemas electrónicos. Usando a las caravanas sureñas, pagué una gran cantidad de chapas por un decodificador y se lo entregué al clan de Trayvon para que abra la fábrica antigua. Es el único lugar al que no hemos podido acceder a causa del maldito sistema de seguridad. Y parece que Lucas decidió arrebatarnos el botín a todos.}
{258}{}{¿Por qué era necesario dividir a los chatarreros en clanes distintos?}
{259}{}{Ellos mismos lo quisieron. Las personas quieren seguir a una autoridad, así es como piensan. No me importa quién esté dando las ordenes, lo importante es que me obedezcan y no causen problemas.}
{260}{}{Ya hablamos suficiente de los chatarreros.}
{261}{}{Creo que ya conversamos mucho sobre el cartel.}
{262}{}{He escuchado suficiente de sus problemas. Adiós.}

{270}{}{¿Eres el anciano de este lugar, no? Eres el líder.}
{271}{}{Anciano... ¿Los campesinos le dicen así al alcalde? No, la ciudad no necesita uno, al menos por ahora. Soy el jefe del cartel de chatarreros, pero dado que la ciudad entera está involucrada en este negocio, es imposible que se tome una decisión importante si no soy parte de ella. En ese sentido, sí podrías considerarme un "anciano".}
{272}{}{¿Así que eres el alcalde de esta ciudad?}
{273}{}{No, la ciudad no necesita un alcalde, al menos por ahora. Soy el jefe del cartel de chatarreros, pero dado que la ciudad entera está involucrada en este negocio, es imposible que se tome una decisión importante si no soy parte de ella. En ese sentido, sí podrías considerarme un "anciano".}
{274}{}{¿Cómo terminaste siendo el jefe del cartel? ¿Eliminaste a tus rivales o algo así?}
{275}{}{No fue nada de eso. Yo empecé como un chatarrero en la Gran Ciudad. El cartel ya existía y pude ocupar un puesto vacante en la administración. Entonces abrimos una sucursal entre estas ruinas y decidí mudarme aquí para supervisar el trabajo.}
{276}{}{No me parece que quieras regresar.}
{277}{}{Me tengo algunos... desacuerdos con la oficina principal.}
{278}{}{¿A qué se dedica tu cartel?}
{279}{}{A hurgar entre ruinas antiguas, eso es lo principal. Han pasado cien años desde la Gran Guerra y muchas cosas se han deteriorado, pero algunas siguen en buen estado y pueden serle de ayuda a la sociedad. También hacemos un intento por arreglar las cosas que hallamos, pero es mucho más difícil.}

{280}{}{A mi aldea no le agrada que estés reconstruyendo la fábrica.}
{281}{}{¿Por qué? Ah, cierto, había escuchado mucho acerca del miedo y supersticiones que tienen sobre la tecnología antigua. Perdona, pero no puedes hacer nada al respecto.}
{282}{}{¿En serio?}
{283}{}{Tu aldea es pacífica, prosperan utilizando nada más que el trabajo manual y siguen sus propias reglas. Pero de ahora en adelante, nadie les permitirá eso. Las ciudades están renaciendo y alguien tendrá que venir aquí a restaurar la producción en la fábrica, si eso no pasa ahora, ocurrirá luego. Es inevitable.}
{284}{}{Es imposible resistirnos a esto. Adiós.}
{285}{}{Los Ancianos buscan estar aislados del mundo exterior. No les gusta la idea de que vengan forasteros al valle.}
{286}{}{Como te dije, no pueden hacer nada, es inevitable. Lo único que pueden hacer, es prepararse para el futuro. Podrían comprar armas, construir vallas, recuperar las propiedades que hayan perdido e incluso crear un sistema de riego más eficiente. Y curiosamente, para eso, les harán falta los servicios de mi garaje.}
{287}{}{¿Me estás ofreciendo un trato?}
{288}{}{Tengamos en cuenta que la ciudad es la fuente de tus problemas y que tú abriste la fábrica con tus propias manos. Puedo ofrecerle nuestros servicios a tu Villa a un costo muy bajo, esto creará trabajos para la ciudad y permitirá que tu gente se prepare para lo inevitable. Todos ganamos.}
{289}{}{Eso es interesante, pero convencer a los ancianos no será fácil. Me lo pensaré.}

{300}{}{¿En qué estás pensando?}
{301}{}{En nada, la verdad. Tengo cosas que hacer..}

#Quest 2
{310}{}{El viejo Lucas ha cometido un grave error. Esto ha dañado mi reputación y lo más importante, es que arruinó mis planes.}
{311}{}{[Escucha]}
{312}{}{Pero ese no es el punto, ya me encargaré de eso luego. Me hacen falta unos componentes especiales de una radio, están en la fábrica. Los necesito tan pronto como sea posible. ¿Podrías traerme lo que necesito?}
{313}{}{¿Qué tal si mato a Lucas?}
{314}{}{No creo que tengas las agallas o la habilidad. Y si acaban contigo, entonces nada de esto habrá importado. Sólo tráeme lo que te pedí.}
{315}{}{Ya veo. Me encargaré de ello.}
{316}{}{De ninguna manera. Encuentra a otro idiota que lo haga.}
{317}{}{Por supuesto, lo haré.}
{318}{}{¿Y qué gano yo?}
{319}{}{Te pagaré por el trabajo, por supuesto. Y te ganarás mi respeto, lo cual vale mucho más.}
{320}{}{¿En qué más puedo ayudarlo, Sr. Kogan?}
{1320}{}{¿En qué más puedo ayudarlo, Sr. Kogan?}

{330}{}{He traído las partes de la fábrica que necesitabas.}
{331}{}{Genial, empiezas a agradarme. Lo único que hace falta es entregársela al cliente.}
{332}{}{¿Qué hay de mi recompensa?}
{333}{}{La tendrás una vez que el trato sea un éxito.}
{334}{}{¿De qué clase de trato estamos hablando?}
{335}{}{Estoy esperando a una caravana muy importante la cual será un hito en la historia de esta ciudad. La caravana sabe esto. Necesito gente confiable la cual pueda protegerme durante la transacción. ¿Estás conmigo?}
{336}{}{¿Qué tal si me niego?}
{337}{}{Me enojaría bastante. Y es mejor que no me hagas enojar.}
{338}{}{Entonces tendré que enojarte, gordo.}
{1338}{}{Entonces tendré que enojarte, gordo.}
{339}{}{Eso fue muy estúpido de tu parte. Lárgate de mi ciudad. No te daré ni una chapa.}
{340}{}{...}
{341}{}{Estoy contigo.}
{342}{}{Muy bien. Prepárate para recibir a la caravana. Así que trae todo lo que necesites y vuelves aquí.}
{343}{}{Entendido.}
{344}{}{De acuerdo, pero, ¿qué deberíamos hacer?}

#Quest 3
{350}{}{}
{351}{}{¿Estás listo?}
{1351}{}{¿Estás lista?}
{352}{}{Sí, estoy listo.}
{1352}{}{Sí, estoy lista.}
{353}{}{No, necesito prepararme. No me tardo.}
{354}{}{Ten cuidado, somos los únicos que saben de este trato, pero no sabemos qué podría pasar. Voy a hablar con la caravana mientras tú te aseguras de que todo salga como debe. El cliente debe irse satisfecho.}
{355}{}{De acuerdo.}
{356}{}{Eh... Tengo que ir a orinar, ya sabes, es lo más importante antes de un trabajo así... Ya vengo.}
{1356}{}{Eh... Tengo que ir a arreglarme, ya sabes, es lo más importante antes de un trabajo así... Ya vengo.}

{360}{}{El trato fue un éxito, ¿no es así?}
{361}{}{Ese fue un buen trato, no puedes imaginarte cuánto. Las chapas no son lo único que ganamos, sino que la ciudad obtuvo una oportunidad para sobrevivir.}
{362}{}{¿A qué te refieres?}
{363}{}{La ciudad está muriendo. Solíamos sobrevivir al extraer chatarra de las ruinas, pero sus recursos ya se acabaron. Entonces, para sobrevivir, no podemos confiar en nuestras viejas costumbres. Necesitamos ir en una dirección completamente nueva.}
{364}{}{¿Así que vas a restaurar la fábrica?}
{365}{}{Correcto. Sin embargo, eso sería inútil si no tenemos una poderosa fuente de energía. Sólo podemos obtener eso en Flagstaff - la ciudad de donde venía esa caravana.}
{366}{}{Que buena idea, este mundo está en ruinas y eso es justo lo que necesita.}
{367}{}{Me alegra que estemos de acuerdo. Algún día, verás a Ciudad Garaje de antaño - decorada con brillantes tubos de vacío, llena de moteros y sus motocicletas, todo mientras escuchas un bebop alegre de fondo.}
{368}{}{Y, ¿qué hay de lo que acordamos?}
{369}{}{Jamás conseguirás restaurar esa fábrica, es una locura.}
{370}{}{Así piensa la mayoría, pero yo confío en mis habilidades. Algún día, verás a Ciudad Garaje de antaño - decorada con brillantes tubos de vacío, llena de moteros y sus motocicletas, todo mientras escuchas un bebop alegre de fondo.}
{371}{}{Y, ¿qué hay de lo que acordamos?}
{372}{}{Sí, eso es lindo y todo. ¿Pero qué hay de mi dinero?}
{373}{}{No me importa. Lo único que me interesa es lo que acordamos.}

{380}{}{Yo valoro a mis socios comerciales, este es el monto que te corresponde por tu trabajo - son 200 chapas. Le haré saber a Pete que puede atenderte de la mejor manera posible. Siéntete como en casa.}
{381}{}{Iré a gastármelas.}
{382}{}{¿Qué hay de la Villa y los saqueadores?}
{383}{}{Todavía te obsesiona eso, ¿eh? La caravana esclavista que tenía a tu gente fue hacia la ciudad de Flagstaff. Está ubicada en el este, a una semana desde aquí. Toma la Interestatal 40 y la verás.}
{384}{}{Genial, voy a encargarme de esos malditos saqueadores.}
{385}{}{Ojalá que allí tengan algo en lo que pueda gastar mis chapas.}
{386}{}{¿Cómo pudiste tratar con unos esclavistas? ¿Acaso no te pesa la consciencia?}
{387}{}{¿Sabes algo, panzón? Si tuviera una bomba nuclear, la haría explotar en medio de esta ciudad. Pero tristemente no tengo una.}
{1387}{}{¿Sabes algo, panzón? Si tuviera una bomba nuclear, la haría explotar en medio de esta ciudad. Pero tristemente no tengo una.}
{388}{}{Ah, bueno. Adiós.}

{390}{}{Creo que te hará feliz saber que Lucas ha muerto.}
{391}{}{Vaya, vaya. Has hecho un buen trabajo, te daré 100 chapas como recompensa. Podrías gastarlas en el bar, pero después de esto, no creo que nuestra ciudad te reciba con los brazos abiertos.}
{392}{}{Gracias por las chapas, Sr. Kogan.}
{393}{}{Con un trabajo así, pensé que la recompensa sería mejor. Pero tendré que conformarme con eso, supongo.}
{1393}{}{Con un trabajo así, pensé que la recompensa sería mejor. Pero tendré que conformarme con eso, supongo.}
{394}{}{¿Te puedo hacer una pregunta? ¿Qué es lo que sientes al deshacerte de un competidor?}
{395}{}{¿Qué debería sentir una persona después de sacar la basura? Debe estar relajado, supongo. Aunque te confieso que siento una leve sensación de pérdida.}
{396}{}{Te escucho.}
{397}{}{¿De verdad?}
{398}{}{Lucas era uno de los mejores chatarreros, antes, solíamos ser amigos. Pero incluso alguien así de experimentado e importante resultó ser un traidor, lo que ponía un mal ejemplo para los demás. Y definitivamente se me pasará rápido la sensación.}
{399}{}{Comprendo lo que quieres decir.}
