{100}{}{Ves a un chatarrero.}
{101}{}{Ves a un chatarrero listo para cazar brahmanes.}
{102}{}{¡Demonios! El brahmán tiene dueño, pero lo necesitamos.}

{110}{}{No nos decepciones.}
{111}{}{El brahmán es nuestro, regresa a la ciudad y avísale al cantinero.}
{112}{}{¡No pensé que esto terminaría así!}

{200}{}{Parece que el brahmán tiene un dueño. Mira, de verdad lo necesitamos.}
{201}{}{¿Los vas a atacar?}

{202}{}{¡La ciudad muere de hambre, ya nadie comercia con nosotros, necesitamos ese brahmán, no hay de otra! ¿Se te ocurre algo mejor?}
{203}{}{Estoy dentro. ¡Vamos!}
{204}{}{No es necesario cometer un crimen, quizás pueda negociar con ellos.}
{205}{}{¡Pero tiene que haber otra forma!}
{206}{}{Eres un debilucho. Si no nos quieres ayudar, Hazte a un lado. A no ser... que puedas traernos al brahmán sin que se den cuenta.}
{1206}{}{Eres una niña estúpida. Si no nos quieres ayudar, Hazte a un lado. A no ser... que puedas traernos al brahmán sin que se den cuenta.}
{207}{}{Bueno, hagámoslo.}
{208}{}{No dejaré que hagan esto.}
{209}{}{¿En serio? ¿Y qué harás al respecto?}
{210}{}{A diferencia de ellos, yo sí sé pelear. Te daré tu merecido.}
{211}{}{Déjame hablar con ellos, sé que podemos llegar a un acuerdo.}
{212}{}{Te arrepentirás de esto. (escupe en tus pies) Vámonos, chicos.}
{213}{}{Cambié de opinión. ¡Te voy a matar!}
{1213}{}{Cambié de opinión. ¡Te voy a matar!}
{214}{}{Es mejor que salgas corriendo.}
{215}{}{Encontraré alguna forma de resolver esto.}
{216}{}{Tu palabra no vale nada para nosotros.}
{217}{}{Entonces no tenemos otra opción, hay que atacar a los pastores. Estoy contigo.}
{218}{}{Espérame, dame unos minutos. Quizás pueda hablar con ellos.}
{219}{}{¿Harás que las caravanas vuelvan a tratar con nosotros? Hmm, supongo que puedo confiar en ti. Es mejor que no nos decepciones... Vámonos, chicos.}
{220}{}{Gracias por escucharme.}
{221}{}{Buena idea. Intentaré traerte el brahmán.}
{222}{}{Prometo resolver su problema de la comida. Tienes mi palabra.}

{250}{}{Espera, déjame hablar con los pastores. Quizás pueda persuadirlos para que nos den el brahmán.}
{251}{}{¡Ja! Ellos no sólo cuidan a su rebaño, los tratan como si fueran DIOSES. Pedirles que dejen ir a un brahmán es como pedirles que se corten la mano.}
{252}{}{Lo intentaré.}
{253}{}{No tenemos otra opción. ¡Hay que rodearlos, chicos!}
{254}{}{Pero son gente pacífica, ¿en serio vas a atacarlos?}
{255}{}{Aquí tienes el brahmán. Llévatelo antes de que se arrepientan.}
{256}{}{El brahmán es nuestro, esos salvajes no se arriesgarán a quitárnoslo.}
{257}{}{¡Genial, es lo que queríamos! Imagina el festín que podemos hacer con su carne. Gracias.}
{258}{}{Nos vemos en Ciudad Garaje.}
{259}{}{Ya casi tenemos al brahmán. Espera a que lo acerque un poco más...}

// added this to have better responses for buying the brahmin - cambragol
{260}{}{Pude llegar a un acuerdo por el brahmán. Ahora es nuestro.}

