{100}{}{Ves al guardia de la puerta.}
{101}{}{Estás viendo a un guardia moreno y barbudo. Tiene una mirada firme, la cual te atraviesa.}
{102}{}{¡No es posible! ¿¡Esa motocicleta funciona de verdad!?}
{103}{}{¡Eso cambia las cosas! Te doy la bienvenida a Ciudad Garaje.}
{104}{}{Saludos, estás en Ciudad Garaje. Debes responder unas preguntas antes de entrar.}

#First dialogue
{200}{}{Bien, forastero, ¿qué vienes a hacer aquí?}
{1200}{}{Bien, señorita, ¿qué viene a hacer aquí?}
{201}{}{Estoy buscando a mi gente, fueron raptados y se los llevaron en esta dirección.}
{202}{}{Necesito un lugar en donde pasar la noche.}
{203}{}{Nada. Llegue aquí de casualidad.}

{204}{}{No sé nada acerca de eso.}
{205}{}{Entonces, ¿puedo entrar?}
{206}{}{Estuvieron aquí, de eso no tengo dudas.}
{207}{}{Puede ser. Tendrás que hablar con los chicos del bar, o con el jefe del cartel.}
{208}{}{Comprendo. ¿Puedo entrar?}
{209}{}{Ya te dije que no sé nada.}
{210}{}{Voy a preguntarle a los demás. ¿Puedo pasar?}

{211}{}{Aquí tenemos un motel, pero no sé si tengan habitaciones libres.}
{212}{}{Entonces supongo que debería echarle un vistazo.}
{213}{}{Eso es un poco sospechoso. Si en serio llegaste por 'casualidad', entonces no deberías molestar a nuestros ciudadanos.}
{214}{}{De todas formas, quiero ver qué hay en la ciudad.}

{215}{}{¿Ya te vas? Y con buena razón... dado que murió el Sr. Kogan, la ciudad se está volviendo un poco loca.}
{216}{}{Siento oír eso.}
{217}{}{Para que vean. No tenían por qué hacerse amigos de esclavistas.}
{218}{}{¿Te refieres a la caravana de Flagstaff? Sí, ese trato no fue el mejor, pero le trajo buenas ganancias a la ciudad. Pero dudo que estas dos cosas estén conectadas... ¿o sí?}
{219}{}{Piénsatelo un rato. Yo hice todo lo que tenía que hacer en esta ciudad.}

{220}{}{¡Un momento! Muéstrame tus manos.}
{221}{}{¿Mis manos? ¿Para qué?}
{222}{}{(te amenaza con su arma) ¡Muéstramelas de una vez!}
{223}{}{¿Qué tal si te muestro mis puños?}
{224}{}{Cálmate, no quiero llegar a una pelea por algo así. Pero ten en cuenta que no nos gustan los vándalos. Así que, muéstrame tus manos.}
{225}{}{¿Para qué necesitas ver mis manos?}
{226}{}{Está bien, mira.}
{227}{}{Hmm... Parece que estás bien. Puedes pasar.}
{228}{}{¿Qué demonios fue eso?}
{229}{}{Es sólo un control que debo hacer a los recién llegados. Los Chacales tienen una enfermedad y debemos tener cuidado con ella. Les tiemblan las manos y además tartamudean.}
{230}{}{Por como lo describes, parecen ser los efectos secundarios que puede tener el canibalismo.}
{231}{}{Hmm... puede ser... No lo había pensado, pero tiene sentido. Eso es lo que todos dicen de los Chacales, que son caníbales.}
{232}{}{Bueno, voy a olvidar que hiciste eso. Hazte a un lado.}
{233}{}{¿Me puedes explicar por qué hiciste eso?}
{234}{}{Ojalá que no te hayan quedado dudas. Voy a pasar.}
{235}{}{Bueno, entonces no hay por qué preocuparse, no soy uno de esos 'Chacales'.}
{236}{}{Un momento. No me malinterpretes, pero antes de dejarte pasar, necesito que me muestres tus manos.}
{237}{}{¿Quizás sea una condición?}
{238}{}{¿Cómo voy a saber? Ni siquiera voy a hablar con ellos - les pondré una bala en la cabeza y se acabó.}

# Re-dialogue
{240}{}{Bienvenido a nuestro vertedero. Siéntete como en casa.}
{241}{}{Bienvenido a Ciudad Garaje. Te encantará el sitio... una vez que te acostumbres.}
{242}{}{¿En serio no quieres irte?}
{243}{}{Este basural es nuestro hogar. Nuestro dulce y acogedor hogar.}
{244}{}{Esa cosa que tienes en la muñeca es genial. ¿Es una computadora? Nunca había visto algo así.}
{245}{}{Alto, ¿quién anda ahí? Ah, eres tú...}

{246}{}{Ah, sigues aquí. Eso es raro, pensé que no te gustaría la ciudad.}
{247}{}{Que sepas que la gente de aquí es terca. Debes tener cuidado cuando salgas a la calle.}
{248}{}{¿Vienes a hacer algún trato por aquí? Más te vale, o los ciudadanos se pondrán impacientes contigo.}
{249}{}{Por favor, molesta a otro. Puede que me meta en problemas si hablo contigo.}

{250}{}{¿Conoces al niño que quiere unirse a los Rangers?}
{251}{}{¿Y por qué ayudaría a los Rangers?}
{252}{}{Esto no te afecta en nada.}
{253}{}{Está bien. A quien debes estar buscando es Eugene Simon. Su choza está cerca del dormitorio.}
{254}{}{Gracias.}
{255}{}{No es asunto tuyo. Hazte a un lado y quítate de mi camino.}
{256}{}{Oh, claro que no, todo lo que pase por esta puerta es asunto mío.}
{257}{}{Perdón si fui descortés, es solo que no es normal hablar con alguien mientras te apunta. Y bien, ¿dejan que la gente pase la noche aquí?}
{258}{}{Sólo quiero un lugar en donde pasar la noche. No voy a quedarme aquí.}
{259}{}{Adiós.}

{260}{}{Habíamos mencionado a unos Chacales. ¿Quiénes son?}
{261}{}{Son una tribu de salvajes que vive en el desierto, pero no sabemos mucho sobre ellos. Lo único que sabemos que esos hijos de perra son astutos, pues atraen a viajeros débiles utilizando trampas, o emboscándolos.}
{262}{}{Ya veo.}
{263}{}{¿Por qué no acaban con ellos?}
{264}{}{Nos encantaría lidiar con ellos, pero no sabemos en dónde está su base. ¿Sabes en dónde está su campamento?}
{265}{}{No, no lo sé.}
{266}{}{Eso pensaba. Si llegas a encontrar su guarida, házmelo saber. Seguramente esté al norte, o al noroeste.}
{267}{}{Lo tendré en mente.}
{268}{}{La verdad, sí.}
{269}{}{¿Neta? ¡Eso cambia las cosas! Mira, tenemos a un par de tipos que tienen ganas de acabar con esa tribu. Si los llevas a su guarida, podríamos acabar con ellos de una vez por todas.}
{270}{}{Cuenta conmigo. Su campamento está al norte, junto a un río seco. Hay que seguirlo hasta llegar a una vieja casa de ladrillo. Los veré allí.}
{271}{}{La verdad es que no conozco a esos tipos. Es mejor que lo haga por mi cuenta.}
{272}{}{¿Escuchaste lo que pasó con los Chacales?}
{273}{}{Sí, me enteré. Resulta que no eres tan malo como pensábamos. Te estás ganando amigos en Ciudad Garaje.}
{1273}{}{Sí, me enteré. Resulta que no eres tan mala como pensábamos. Te estás ganando amigos en Ciudad Garaje.}
{274}{}{Eso es bueno.}
{275}{}{Desde que lidiaste con los Chacales, tu reputación en Ciudad Garaje ha mejorado.}
{276}{}{Sí, eso escuché. Los Rangers se fueron de madre. Luego de esto, no los vamos a dejar estar cerca de Ciudad Garaje. Si te cruzas con ellos, diles eso.}
{277}{}{De acuerdo.}
{278}{}{Esa armadura que tienes es bonita.}
{279}{}{Conversemos un poco sobre los Chacales...}

# Refugees
{280}{}{He oído que tienen refugiados.}
{281}{}{Sí, se asentaron en una choza abandonada en el área residencial. Está al lado de la granja hidropónica. Pero, no creo que vayan a quedarse.}
{282}{}{¿Por qué?}
{283}{}{Aquí no hay trabajo para ellos, y no todos son capaces de perseverar en un sitio como este.}
{284}{}{Gracias, iré a buscarlos.}
{285}{}{Tienes razón - es mejor que no se queden en un vertedero como este. Es hora de que también me vaya.}

# Brahmin
{287}{}{Ya es hora, podemos ir por los brahmanes.}
{288}{}{Genial, sólo falta esperar a los demás...}
{289}{}{[Dirígete al yermo]}
{290}{}{He escuchado que planearon una caza de brahmanes.}
{291}{}{Sí, hay un rumor de que un brahmán salvaje anda suelto por ahí. Nuestros chicos quieren atraparlo y trincharlo. Pero cazar a un animal así de fuerte no es para nada fácil, nos hace falta un refuerzo. ¿Te interesa?}
{292}{}{He oído de los brahmanes, pero nunca he visto uno.}
{293}{}{Un brahmán es... bueno... es una bestia de dos cabezas y cuatro patas. Vive en el desierto, come pasto. ¿Te lo imaginas?}
{294}{}{Necesito un momento para prepararme. No se vayan sin mí.}
{295}{}{La caza no es lo mío. Cambiemos de tema.}
{296}{}{Claro, cuenta conmigo. ¿Cuándo nos vamos?}
{297}{}{Una vez que todos estemos listos. Luego de asegurarte de que te has equipado, habla conmigo.}
{298}{}{De acuerdo.}
{299}{}{Espera, necesito más tiempo. Ya vengo.}

# Questions
{300}{}{Es la primera vez que estoy tan lejos de casa. ¿Qué puedes contarme sobre este lugar?}
{301}{}{¿Está bien si hablamos un poco sobre Ciudad Garaje?}
{302}{}{Para que el guardia hable contigo, intenta traerle alcohol del bar y usa el objeto sobre él.}
{303}{}{Me encantaría hablar contigo, pero mi garganta está seca.}
{304}{}{Espera, te traeré algo para beber.}
{305}{}{¿Tienes sed? Aquí debe haber mucho para beber.}
{306}{}{¿Qué quieres saber?}
{307}{}{Tengo otra pregunta.}
{308}{}{Ya charlamos lo suficiente, tengo que irme.}

{310}{}{¿Cómo se sustenta esta ciudad? No parecen que hayan plantaciones.}
{311}{}{Podemos sustentarnos gracias a las ruinas antiguas, nosotros le decimos la 'mina'. Nuestros chatarreros hurgan por allí, buscan cosas viejas y se las dan al cartel, quienes se las venden a las caravanas.}
{312}{}{¿Quién está a cargo aquí?}
{313}{}{No hay alcalde ni sheriff. Los chatarreros se dividen en clanes, cada uno con su propio líder. Pero todos obedecen al Sr. Kogan. Aunque, a él solo le interesan las operaciones de la mina.}
{314}{}{Háblame sobre Kogan.}
{315}{}{El Sr. Kogan es el jefe del cartel de chatarreros, también hace negocios con las caravanas. Dejémoslo ahí, porque al 'jefe' no le gusta que hablen de él.}
{316}{}{No hay alcalde ni sheriff. Los chatarreros se dividen en clanes, cada uno con su propio líder. Solían obedecer al Sr. Kogan, pero desde que murió, ha habido una lucha por el poder que tiene a la ciudad conmocionada.}
{317}{}{Háblame de ti.}
{318}{}{No tengo mucho que contar, vine aquí junto a otras personas y quería ganarme la vida siendo un chatarrero. Pero por suerte, el Sr. Kogan me puso a trabajar como el guardia de la puerta. Ahora puedo mantener a los indeseables afuera y asustar a las alimañas.}
{319}{}{¿Qué clase de alimañas?}
{320}{}{Coyotes, escorpiones y la ocasional rata gigante que viene de las ruinas. Para los tramperos, no hay mucho que hacer aquí. Dicen que la caza es mucho mejor en las montañas hacia el este. A veces me pregunto si debería irme hacia allá si las cosas se ponen muy difíciles en Ciudad Garaje.}
{321}{}{¿Qué tan viejas son estas ruinas?}
{322}{}{Son más viejas que tú y yo juntos. Se remontan a antes de la Gran Guerra, hace unos 90 años. Desde ese entonces, se han oxidado y la arena las ha enterrado.}
{323}{}{¿Y que había aquí *antes* de la Guerra?}
{324}{}{Un sitio llamado Kingman. Pero, ¿a quién le importa, realmente? Eso ya es historia.}
{325}{}{Sólo me daba curiosidad. Cambiemos de tema.}
{326}{}{¿Por qué viven entre medio de tanta basura y ruina?}
{327}{}{¿Tienes una mejor idea? Los edificios viejos se caen a pedazos, así que construimos unos nuevos usando chatarra.}

# About slave convoy
{330}{}{Dicen que una caravana esclavista pasó por aquí. Tú debes saber sobre eso.}
{331}{}{No sé de qué hablas, no ha pasado ninguna caravana de ese tipo por aquí. Habla con los tipos del bar o con el jefe del cartel. Quizás los chatarreros sepan algo.}
{332}{}{Por favor, si sabes algo, dímelo. Ellos capturaron a mi familia y a mi pueblo. ¿Alguna vez has perdido a un ser querido?}
{333}{}{Bien, voy a preguntar.}
{334}{}{(suspiro) No te lo dije antes, pero, esa caravana va hacia Flagstaff. Ve hacia el este y sigue la Interestatal 40. Dicen que el viaje dura una semana.}
{335}{}{Entonces debo ir hacia Flagstaff, al este de aquí... Muchas gracias, amigo. Eres buen tipo.}
{336}{}{¿¡Y por qué chingados no me lo dijiste antes!? José tenía la razón acerca de ustedes.}
{337}{}{Perdona, pero no te puedo ayudar.}
{338}{}{Si me estás mintiendo, te arrepentirás.}
{339}{}{De acuerdo, le voy a preguntar a los demás.}
{340}{}{Y recuerda que la caravana está bien armada y organizada, son más peligros que un saqueador cualquiera del yermo.}
{341}{}{Gracias por decírmelo.}
{342}{}{Ya tengo que irme. Adiós.}
{343}{}{¿Cómo puedo llegar a Flagstaff desde aquí?}
{344}{}{Toma la carretera que se dirije al este de aquí. Te tomará unos días de viaje. Aunque, si fuera tú, iría en esa dirección sin tomar la carretera. Recuerda mis palabras: En el yermo, es mejor encontrarte con un animal, que con un hombre.}

{345}{}{¡A-ba-boo-ba-gee!}
{346}{}{Eh... (se te queda mirando, totalmente confuso) Mira, pienso que no deberías entrar... puede que te confundan con un Chacal. ¿Bien? Así que si entras, no digas no te advertí.}
{347}{}{Boog.}
{348}{}{Ayos.}

#Weapons
{350}{}{Ese rifle que tienes es genial.}
{351}{}{Así es, es un buen rifle.}
{352}{}{Eh, hablemos de otra cosa, supongo.}
{353}{}{Que buena charla. Adiós.}

{354}{}{¿En dónde lo conseguiste?}
{355}{}{Se lo compré a algún perdedor con mala suerte.}
{356}{}{Pero si fuera un buen rifle, el tipo no tendría mala suerte. ¿Qué estás escondiendo?}
{357}{}{¿Qué tal dispara?}
{358}{}{Jamás me ha errado un disparo. Este rifle me ha salvado la vida más veces de las que podría contar.}
{359}{}{A juzgar por la mugre, hace tiempo que no ha disparado.}
{360}{}{¿Puedo comprártelo?}
{361}{}{Hmm... No.}
{362}{}{Esa respuesta me dice que algo anda mal. No dispara, ¿verdad?}

{363}{}{¡Carajo, me atrapaste! (suspiro) Es cierto, no funciona. Y puedo contar las balas que le quedan con una mano. ¿Qué voy a hacer?}
{1363}{}{¡Carajo, me atrapaste! (suspiro) Es cierto, no funciona. Y puedo contar las balas que le quedan con una mano. Anda, ríete.}
{364}{}{¿Cuál es el propósito de un arma que no dispara?}
{365}{}{¡Para intimidar! Y si hay una emergencia, siempre podría golpear a alguien con la culata, ¿no?}
{366}{}{¿No hay nadie que sepa arreglarla?}
{367}{}{A nuestro mecánico le escasean las partes. Es poco común ver un arma funcional por aquí.}
{368}{}{Puedo arreglarla.}
{369}{}{¿En serio? Eso sería un milagro. Te voy a dar 25 chapas, si lo consigues.}
{370}{}{Ahora no puedo hacerlo. Lo intentaré después.}
{371}{}{Sí, no funciona. Y las balas que tiene, puedo contarlas con una mano. ¿Qué voy a hacer?}
{372}{}{Quiero comprarla.}
{373}{}{Nada, supongo.}
{374}{}{Entendido. Parece que debería irme.}
{375}{}{Eso es todo un problema. Ya me voy.}
{376}{}{Veamos qué le ocurre...}
{377}{}{No puede ser, ¡lo hiciste! Pero, es raro ver a un campesino con un arma, ¿no crees? (carcajada) Te lo agradezco. Toma las 25 chapas que te prometí. Ojalá pudiera encontrar más munición...}
{378}{}{Te deseo lo mejor, ya hice suficiente.}
{379}{}{La verdad... No creo que sea capaz de arreglarlo.}
{380}{}{Eso pensaba.}
{381}{}{No puedo arreglarlo ahora. Quizás luego.}
{382}{}{Olvídalo, no voy a tocar tu arma, por el momento.}
{383}{}{Si eso es lo que me vas a pagar, mejor la tiro al basurero. Búscate a alguien más.}
{384}{}{Tengo un arma adicional, probemos a quitarle algunas partes.}

{390}{}{Oye, ¿no que ibas a unirte a esos tipos para atacar a los Chacales?}
{391}{}{Cambié de parecer.}
{392}{}{Bueno, yo me cuidaría la espalda si fueras tú. Esos tipos están bien encabronados contigo.}
{393}{}{Lo tendré en cuenta. Tengo que irme.}
{394}{}{Gracias por el aviso. ¿Te puedo preguntar algo?}
