{100}{}{Ves a Lucas.}
{101}{}{Estás viendo a un chatarrero veterano que lleva puesto un pañuelo.}
{102}{}{¡Fuera de mi fábrica!}

#First quest
{150}{}{(Ves a un chatarrero veterano; te mira con el ceño fruncido, sentado en una posición relajada) No esperaba que Kogan enviara a un forastero. ¿Quién eres?}
{1150}{}{(Ves a un chatarrero veterano; te mira con el ceño fruncido, sentado en una posición relajada) No esperaba que Kogan enviara a una forastera. ¿Quién eres?}
{151}{}{No tengo idea de quién es Kogan, estoy buscando a la caravana de unos esclavistas.}
{152}{}{Hmm. Así que eres de la aldea que asaltaron los colonos, escuché de eso. Kogan intentó hacerse amigo de los colonos con la esperanza de tener contratos con ellos en el futuro. Él fue quien les contó sobre la Villa, esos tipos estaban buscando salvajes; ni siquiera sabían de ustedes.}
{153}{}{Kogan te exige una explicación.}
{154}{}{Se las voy a dar. Pero quiero que TÚ me expliques esto, ¿por qué trabajas para ese maldito avaro? ¿Qué te prometió a cambio de tu trabajo?}
{155}{}{En realidad, estoy rastreando a la gente que raptó a mis parientes. Kogan sabe algo sobre eso.}
{156}{}{¿Sabes hacia dónde fue la caravana?}
{157}{}{Sí, lo sé. hazme un favor y te diré todo. Al fin y al cabo, no seguirás trabajando para Kogan después de lo que te conté, ¿verdad?}
{158}{}{Habla y no saldrás herido.}
{159}{}{¿Hay algún cerebro en esa cabezota? ¿Sí? Pues úsalo, o te mataremos.}
{160}{}{¿Qué quieres que haga?}
{161}{}{Bien, ¿de qué se trata ese "favor"?}
{162}{}{Necesito los últimos contratos de Kogan, cada uno de ellos. Tienen que estar registrados en la computadora de su garaje, sólo debes copiarlos y traérmelos. Cuando hagas eso, podemos hablar.}
{163}{}{Está bien, conseguiré esos contratos. Ya vuelvo.}
{164}{}{Decir que eso es arriesgado se queda corto. Pides demasiado.}
{165}{}{¿Quieres saber acerca de la caravana esclavista? Entonces ve y no vuelvas sin esos contratos.}
{166}{}{Ya, ya. Lo haré.}
{167}{}{Me lo pensaré.}
{168}{}{Tengo algunas preguntas.}
{169}{}{¡Oye, te veo! Sale a la luz, rata. ¿Nos estás espiando para Kogan?}
{1169}{}{¡Oye, te veo! Sale a la luz, zorra. ¿Nos estás espiando para Kogan?}
{170}{}{Y bien, ¿trajiste los contratos?}
{171}{}{Todavía no.}
{172}{}{¿Quién dijo que te los traería?}
{173}{}{Puede que no sepas, pero Kogan está muerto.}
{174}{}{Si es así, entonces te será mucho más fácil conseguir los contratos. Sigo necesitando esa información.}
{175}{}{Voy a ir y ponerme con ello.}
{176}{}{Sabes, no sé de computadoras. Así que... me será difícil hacerte ese "favor".}
{177}{}{¿Entonces no puedes acceder a la computadora? Puede que Kogan le haya colocado una contraseña...  Hmm... No quiero hacer esto, pero tendré que darte el decodificador. Es capaz de piratear el sistema por sí mismo, pero tendrás que esperar un rato.}
{178}{}{Esto lo cambia todo. Le daré una oportunidad.}
{179}{}{}
{180}{}{Tengo los contratos, toma.}
{181}{}{Muy bien, veamos... Sí... Ya lo entiendo...}
{182}{}{¿Qué entiendes?}
{183}{}{Te gusta hablar sólo, ¿verdad?}
{184}{}{Kogan hizo un trato con una ciudad vecina por partes de esta fábrica. La caravana ya está en camino, lo único que debemos hacer es adelantarnos y recibirla antes que Kogan.}
{185}{}{¿Para qué necesitas hacer eso?}
{186}{}{¡Esta fábrica es una mina de oro! Lo único que le hace falta es ponerla a funcionar y encontrar clientes. No hay muchos, pero existen.}
{187}{}{Bien, pero, ¿qué hay de lo que acordamos?}
{188}{}{Es mejor que te quedes de nuestro lado, una vez que esto acabe, podemos hablar.}
{189}{}{¡Pero yo no quiero ser parte de esto!}
{190}{}{Si todo sale bien, no tendrás que ser parte de esto. Vamos a encontrarnos con la caravana, intercambiar unas cosas y seguir con nuestras vidas.}
{191}{}{Has lo que quieras, yo no me meto.}
{192}{}{Me parece bien. ¿Cuándo salimos?}
{193}{}{Primero, hay que conseguir las partes. Da una vuelta por la fábrica y encuentra lo listado en el contrato. Todo lo de la lista debería estar en esta fábrica.}
{194}{}{De acuerdo.}
{195}{}{Tengo que hacerte una pregunta.}
{196}{}{No hasta que obtengas los contratos.}
{197}{}{Bueno, voy por ellos.}
{198}{}{¡Ah, así que así están las cosas!}

{210}{}{¿Qué pasa?}
{211}{}{Creo que ya me voy.}

{220}{}{¿Qué es este lugar?}
{221}{}{¿En serio no sabes lo que es una fábrica? Tienes la piel oscura, debes vivir en el desierto... Bueno, las fábricas solían producir equipamiento y dispositivos. Hoy en día ya no lo hacen, obviamente.}
{222}{}{Ya escuché suficiente sobre la fábrica. ¿Podemos hablar de otra cosa?}
{223}{}{¿Por qué?}
{224}{}{Dijiste que las fábricas están inactivas. ¿Por qué?}
{225}{}{Ya no hay ningún lugar en donde conseguir la energía necesaria. Y aunque existiera una fuente, solo unos pocos poseen las habilidades y el conocimiento para usarlas. Desde la Gran Guerra que la gente ha aplastado los logros del pasado...}
{226}{}{¿Qué producían aquí?}
{227}{}{Esto solía ser una fábrica de Wattz Electronics. Se producían partes para equipos electrónicos y varios tipos de baterías nucleares.}
{228}{}{¿Por qué hay tanta luz aquí adentro?}
{229}{}{Son las viejas lámparas. Funcionan con la electricidad, que es producida por los generadores de emergencia dado que el reactor local ha estado inactivo desde la Guerra. En teoría, podríamos encenderlo, pero eso necesita combustible nuclear y no hay ningún lugar en donde conseguir eso... por ahora.}
{230}{}{¿Cómo sabes tanto sobre cosas de la preguerra?}
{231}{}{Soy un chatarrero, he estado trabajando con cosas viejas durante años.}
{232}{}{Esas invenciones metálicas no me dan mucha confianza.}
{233}{}{¿Te refieres a los robots? Todavía no nos dejan pasar al resto de la fábrica, fue gracias al decodificador que pudimos piratear el sistema para apagar la alarma. Ahora los robots son inofensivos y eventualmente podemos usarlos como trabajadores.}

{240}{}{¿Sabías que Kogan ha muerto?}
{241}{}{Sí, en esta ciudad los rumores se difunden rápidamente. Para serte honesto, siento un poco de pena.}
{242}{}{[Más]}
{243}{}{Kogan era un bastardo codicioso, pero era un buen empresario digno. Y pienso que habría sido posible llegar a un acuerdo con él. Y sin él, los chatarreros destruirán todo lo que hay aquí.}
{244}{}{Suena a que las cosas de verdad se pondrán mal aquí. Cambiemos de tema.}
{245}{}{Me parece que tu jefe está enojado contigo de verdad.}
{246}{}{No me importa, el jefe necesita una nueva inversión en el negocio y entre todos los chatarreros de la ciudad, soy el único que puede dársela. Tendrá que lidiar conmigo.}
{247}{}{Lo entiendo.}
{248}{}{¿Qué hay del resto de los chatarreros? ¿Has pensado acerca de ellos?}
{249}{}{Abre los ojos - Ciudad Garaje está devastada. Ya no hay espacio para tantos trabajadores, tendrán que irse a otro lado.}

{250}{}{Aquí está la parte que estaba listada en el contrato.}
{251}{}{(estudia el dispositivo de alta tecnología con detenimiento) Sí, era esto. Prepárate para recibir a la caravana, nos veremos cerca de la vieja bomba de agua. No sé qué ocurrirá ahí, así que trae un arma y una armadura.}
{252}{}{Ya puedo ir con ustedes.}
{253}{}{Necesito un momento para alistarme.}
{254}{}{Puedes relajarte, esto llevará un tiempo...}
{255}{}{[Acompaña a los chatarreros]}
{256}{}{No, espérame, necesito más tiempo.}
{257}{}{Está bien, nos vemos en la bomba de agua.}

{260}{}{¡El trato fue un éxito! Sin tu ayuda, hubiera sido mucho más difícil, te debemos una. Aquí tienes 200 chapas, es lo que te corresponde del trato.}
{261}{}{¿Qué piensas hacer ahora}
{262}{}{Empezaré a restaurar la fábrica, nos prometieron traer combustible para el reactor, en ese entonces podríamos encender las máquinas y empezar a producir partes nuevas.}
{263}{}{Te deseo suerte. Entonces, mi trabajo aquí ha terminado.}
{264}{}{Bueno, veremos como resulta todo en el futuro. Adiós, soñador.}
{265}{}{El trato fue un éxito, pero no fuiste de mucha ayuda. Lo hablamos y decidimos que no te mereces una parte del trato.}
{266}{}{Las chapas me vendrán bien. ¿Qué piensan hacer ahora?}
{267}{}{¿Es eso un arma láser? Me sería de más ayuda que las chapas.}
{268}{}{Claro, tómalo. Es un emisor láser, lo improvisé utilizando partes de por ahí. Puede que fabrique más en el futuro.}

{270}{}{Habías prometido que me contarías más de la caravana esclavista.}
{271}{}{Sí, es complicado. Verás, lo cierto es que eran mercenarios de asentamientos de por aquí. Pero eran liderados por unos tipos de Flagstaff, así se llama la colonia. Está hacia el este, tardarás una semana en llegar allá.}
{272}{}{¿Para qué necesitan esclavos?}
{273}{}{Primero, estaban buscando la guarida de los Chacales, pensaban en esclavizarlos a todos. Necesitan trabajadores para una mina, pero una de verdad. Pero Kogan pensó en las ganancias y les sugirió un ataque a la Villa, un objetivo más fácil. Quería quedar bien con ellos, porque Flagstaff promete ser un buen cliente para el cartel.}
{274}{}{Así que ustedes están todos conectados, ¿cierto?}
{275}{}{Tienes que entenderlo, ese trato era bueno para Ciudad Garaje. Y el trato con la caravana fue parte de todo este asunto. Puede que no te guste, pero los chatarreros también tenemos que cuidarnos.}
{276}{}{Lo entiendo, ahora debo ir hacia esa tal... Flagstaff.}
{277}{}{Bueno, yo no olvidaré esto. Los aldeanos de la Villa tienen buena memoria.}

{280}{}{Hola Lucas, tengo que hablarte sobre la fábrica y tus planes de producción. Mi comunidad teme que afectará negativamente a la Villa.}
{281}{}{Tonterías. Llegarán trabajadores nuevos y aumentará el comercio de la ciudad. Eso es mejor para ustedes, porque podrán intercambiar más cosechas y cerámicas con nosotros, además de otras ciudades.}
{282}{}{Puede que tengas razón, pero nuestros ancianos quieren estar aislados.}
{283}{}{¿Los viejos están rechazando el cambio! ¡Una pena! El mundo está cambiando y ellos tendrán que hacerlo, tarde o temprano.}
{284}{}{Quizás estés en lo cierto, pero no les gustará.}
{285}{}{Luego de todos mis viajes, creo que debo estar de acuerdo contigo. ¿Pero cómo puedo persuadir a los ancianos? Necesitan algún tipo de garantía.}
{286}{}{¿En qué clase de fantasía vive tu gente? Las garantías no existen, sólo hay acuerdos. Y sabes - podemos estar de acuerdo.}
{287}{}{¿En serio?}
{288}{}{Hay mucha gente desempleada en la ciudad, mi fábrica les dará un trabajo a todos ellos en un futuro cercano. También podríamos prestarle varios servicios a tu Villa por un costo muy bajo. Estarías restaurando tu aldea, fortalecerías tus tierras y nosotros ganaríamos un poco de dinero... o 'elote', supongo. Y lo más importante, estarías evitando 'conflictos' con tus vecinos.}
{289}{}{Le hablaré de tu propuesta a la comunidad. Puede que estén de acuerdos.}
{290}{}{Me temo que a los ancianos no les gustará esto. Adiós.}
