{100}{}{Ves a un chatarrero.}
{101}{}{Ves a un hombre con la cara roja del esfuerzo.}

{110}{}{Oye, mantén la boca cerrada. ¿Entendido?}
{111}{}{¡Por favor, no me mates! ¡No lo haré de nuevo, lo juro!}

{200}{}{¿Qué...? ¿Quién eres? ¿Qué es lo que quieres?}
{201}{}{Solo quiero ver cómo se divierten.}
{202}{}{Nos vamos a divertir. ¿Tienes algún problema?}
{203}{}{¿Qué están haciendo?}
{204}{}{Vamos a jugar a las luchas. En el colchón. ¿Comprendes?}
{205}{}{¿Tienes espacio para alguien más?}
{206}{}{¿¡Te volviste loco!? ¡Piérdete, pendejo!}
{1206}{}{Estás loca. No nos gustan las viejas locas. ¡Lárgate!}
{207}{}{Bueno, me voy...}
{208}{}{Es mejor que pares.}
{209}{}{Oh, no, alguien que se quiere hacer el héroe. ¿Qué nos vas a hacer? ¿Eh? ¿Qué nos vas a hacer, PERRA?}
{210}{}{Me iré y no los molestaré. Pásenla bien.}
{211}{}{Voy a matarte. ¡Muere!}
{212}{}{Te daré tres segundos. Y entonces tendrás que vértelas conmigo. Uno... dos...}
{213}{}{}
{214}{}{¡Ya, ya! ¡Cálmate! No es necesario llegar a eso, no somos animales, podemos hablarlo.}
{1214}{}{¡Ya, ya! ¡Cálmate, preciosa! No es necesario llegar a eso, no somos animales, podemos hablarlo.}
{215}{}{Fuera de aquí.}
{216}{}{La puerta está abierta.}
{217}{}{No me dejan dormir.}
{218}{}{Mira, pagamos por el cuarto y puedo hacer lo que me de la gana.}
{219}{}{Si no te detienes, tendrás problemas con toda la ciudad.}
{220}{}{Sabemos quién eres, pendejo miserable. Nadie te quiere aquí, no nos asustas.}
{1220}{}{Sabemos quién eres, zorra harapienta. Nadie te quiere aquí, no nos asustas.}
{221}{}{Está bien. Pero no olvidaré esto.}
{222}{}{Cierra la boca. Si no te calmas, vas a ver de lo que soy capaz.}
{223}{}{No queremos problemas... Puedes pretender que nunca estuvimos aquí...}
