{102}{}{¡Alerta! ¡Un intruso!}
{103}{}{«¡Alerta! ¡Un intruso!»}

{200}{}{Dios mío, ¿quién eres?}
{201}{}{Para un tirano como tú, soy la muerte.}
{202}{}{Me preguntaba si podía unirme a tu ejército.}
{203}{}{¿De qué demonios hablas? ¡Atrapen a este espía!}
{1203}{}{¿De qué demonios hablas? ¡Atrapen a este espía!}
{204}{}{Vaya...}
{205}{}{Está cometiendo un error, General.}
{206}{}{Un civil. ¡Quiero unirme a su ejército, General!}
{207}{}{Una acción admirable. Pero por cómo entraste, no puedo permitirte el servicio militar. El Comisario te llevará a la salida. Si vuelves - habrán consecuencias graves. ¿Entendido? Sal de aquí.}
{1207}{}{Una acción admirable. Pero por cómo entraste, no puedo permitirte el servicio militar. El Comisario te llevará a la salida. Si vuelves - habrán consecuencias graves. ¿Entendido? No hay excepciones, ni siquiera para las damas. Sal de aquí.}
{208}{}{Como usted diga, General.}
{209}{}{No me iré a ningún lado.}

{210}{}{Te lo advertí. ¡Arréstenlo! Que se pudra junto a los demás prisioneros.}
{1210}{}{Te lo advertí. ¡Arréstenla! Que se pudra junto a los demás prisioneros.}
{211}{}{No, no, a la cárcel no, tengo claustrofobia...}
{212}{}{No me iré a ningún lado.}


{300}{}{«Dios mío, ¿quién eres?»}
{301}{}{«Para un tirano como tú, soy la muerte.»}
{302}{}{«Me preguntaba si podía unirme a tu ejército.»}
{303}{}{«¿De qué demonios hablas? ¡Atrapen a este espía!»}
{304}{}{«Vaya...»}
{305}{}{«Está cometiendo un error, General.»}
{306}{}{«Un civil. ¡Quiero unirme a su ejército, General!»}
{307}{}{«Una acción admirable. Pero por cómo entraste, no puedo permitirte el servicio militar. El Comisario te llevará a la salida. Si vuelves - habrán consecuencias graves. ¿Entendido? Sal de aquí.»}
{1307}{}{«Una acción admirable. Pero por cómo entraste, no puedo permitirte el servicio militar. El Comisario te llevará a la salida. Si vuelves - habrán consecuencias graves. ¿Entendido? No hay excepciones, ni siquiera para las damas. Sal de aquí.»}
{308}{}{«Como usted diga, General.»}
{309}{}{«No me iré a ningún lado.»}

{310}{}{«Te lo advertí. ¡Arréstenlo! Que se pudra junto a los demás prisioneros.»}
{1310}{}{«Te lo advertí. ¡Arréstenla! Que se pudra junto a los demás prisioneros.»}
{311}{}{«No, no, a la cárcel no, tengo claustrofobia...»}
{312}{}{«No me iré a ningún lado.»}