{100}{}{Ves a un centinela.}
{101}{}{Ves un soldado, su armadura lleva un símbolo que no reconoces. Vigila a los forasteros para que no entren en la guarnición.}
{102}{}{¡Un intruso!}

{110}{}{*Bostezo*}
{111}{}{Estoy aburrido...}
{112}{}{¿Acaso viene alguien?}
{113}{}{¿Dónde está mi reemplazo? Ya es hora...}
{114}{}{Qué calor.}
{115}{}{Tengo que escribir un informe al respecto.}
{116}{}{Malditos insectos.}
{117}{}{Ocupo algunos zapatos nuevos...}
{118}{}{}
{119}{}{}

{120}{}{*Bostezo*}
{121}{}{«Que día más aburrido...»}
{122}{}{«¿Acaso viene alguien?»}
{123}{}{«¿Dónde está mi reemplazo? Ya es hora...»}
{124}{}{«Qué calor.»}
{125}{}{«Tengo que escribir un informe al respecto...»}
{126}{}{«Malditos insectos...»}
{127}{}{«Ocupo algunos zapatos nuevos.»}
{128}{}{}
{129}{}{}

{190}{}{«¡Alto ahí! No te muevas.»}
{191}{}{«No quiero problemas, tranquilo.»}
{192}{}{«¿Me estás amenazando?»}

{200}{}{¡Alto ahí! No te muevas.}
{201}{}{¿Qué?}
{202}{}{Eres gringo, ¿verdad? ¿Vienes del norte?}
{203}{}{Tengo que entrar a la ciudad. Déjame pasar. Ahora.}
{204}{}{Pues, sí. ¿Por?}
{205}{}{Un americano... No puedes pasar, ¿lo comprendes? Vuelve por dónde viniste, rápido.}
{206}{}{Pero, ¿por qué me echas?}
{207}{}{A mí nadie me dice que hacer. ¡Quítate!}
{208}{}{Eres un civil - no puedes pasar, está prohibido. Lárgate, o te disparo. ¡Vamos!}
{209}{}{No parece que estés bromeando. Me voy.}
{210}{}{¡Vete al carajo!}
{211}{}{«No, vivo allá, pero no soy gringo.»}
{212}{}{¿Me estás amenazando?}

{213}{}{«¿Un gringo? ¿vienes del norte?»}
{214}{}{«Tengo que entrar a la ciudad. Déjame pasar. Ahora.»}


{220}{}{«¡Un intruso! ¡Suenen la alarma!»}
{221}{}{¡Un intruso! ¡Suenen la alarma!}
{222}{}{No debiste haber hecho eso.}
{223}{}{Oye, esto es un malentendido...}

{224}{}{«Cometiste un error...»}
{225}{}{«Oye, esto es un malentendido...»}

{230}{}{«Pero... Hm. ¿De dónde eres?»}
{231}{}{«Soy de un pueblo, en el extremo norte. Tuve que viajar mucho, busco a mis parientes.»}
{232}{}{«¿Cruzaste el desierto Sonorense? Me cuesta creerlo. De todas formas, tienes que darte la vuelta e irte de aquí.»}
{1232}{}{«¿Cruzaste el desierto Sonorense? Me cuesta creerlo. De todas formas, tienes que darte la vuelta e irte de aquí.»}
{233}{}{«¿Qué? ¿Por qué?»}
{234}{}{«Porque este fuerte le pertenece al Ejército Unido de México, se le prohíbe el acceso a los civiles. Debo matar a cualquiera que entre sin permiso, esas son mis órdenes.»}
{235}{}{«Lo entiendo. Está bien, me voy.»}
{236}{}{«¿Puedo unirme a ustedes?»}
{237}{}{«¿Crees que queremos a un chicano entre nosotros? Claro que no. Lárgate.»}
{1237}{}{«¿Crees que queremos a una chicana entre nosotros? Claro que no. Lárgate.»}
{238}{}{«Ouch...»}
{239}{}{«Vete a la mierda, de aquí no me voy.»}

{240}{}{«¿Acaso no te quedó claro? Si intentas pasar, tendremos que matarte. ¿Comprendes?»}
{241}{}{Ya, ya entendí, me voy...}
{242}{}{Si vuelves a hacer eso, no me haré responsable de lo que pase.}
{243}{}{¿Tú otra vez? (te apunta con el arma) ¡Vete! ¡Voy a dispararte!}
{244}{}{«Uno de ustedes le quitó la radio a la familia Domínguez.»}
{245}{}{«¿En serio? No lo sabía, no me gusta saber que los trataron así..»}
{246}{}{«Deberías devolverles la radio.»}
{247}{}{«Dudo que de verdad te importen esos granjeros. Desconfío de ti...»}
{248}{}{«Los entiendo, me han ocurrido cosas similares a punta de pistola.»}
{249}{}{«Sólo quiero ayudar.»}
{250}{}{«Olvídalo, no vale la pena.»}
{251}{}{[Te apunta] «¿La radio, o tu vida?»}
{252}{}{«No podemos confiar en un gringo como tú.»}
{253}{}{«Bueno, tienes razón, no debería ser así. Hablaré con el comandante...»}
{254}{}{«Yo te espero...»}
{255}{}{«Encontramos la radio en los barracones, devuélvesela a los Domínguez. No queremos arruinar nuestra reputación.»}
{256}{}{«Hiciste lo correcto. Tuviste que haberlo hecho desde un principio.»}
{257}{}{«Gracias.»}
{258}{}{«¿Y si te doy una botella de alcohol?»}
{259}{}{«Claro, hablaré con el comandante...}
{260}{}{«Dásela de vuelta.»}
{261}{}{«Debes devolver eso, no es para nada justo.»}


{262}{}{«Ya, ya entendí, me voy...»}
{263}{}{«Si vuelves a hacer eso, no me haré responsable de lo que pase.»}