{100}{}{Ves a un prisionero de guerra.}
{101}{}{Estás viendo a un hombre, su cuerpo indica que fue golpeado hace poco.}
{102}{}{Este es Pancho.}
{103}{}{¿Y esta es tu casa? Un poco anticuada, pero está tranquila. Me late.}
{104}{}{¡Lo estás haciendo muy bien! Casa Nueva es el único lugar que se parece a esto, hay muchas plantas.}
{105}{}{No me digas que tenemos que meternos en un hoyo de nuevo.}
{106}{}{Fénix... Yo me críe acá, pero ya no quiero volver.}

{200}{}{¿Quién eres y qué quieres?}
{201}{}{Eso no importa. Quédate ahí y no hagas ruido.}
{202}{}{No hagas ruido, no es que me hayan autorizado para estar aquí. ¿Por qué te encerraron aquí adentro?}
{203}{}{¿Esto es un truco para hacerme hablar, no? ¡Ya les dije todo lo que sabía durante la interrogación? Unos mercaderes me contrataron para explorar estas tierras, querían encontrar nuevas rutas de caravanas. Eso es todo. ¡Déjame en paz!}
{204}{}{Eso suena un poco aburrido. No me sorprende que crean que eres un espía.}
{205}{}{Este lugar está desierto, ¿qué más voy a estar haciendo acá? En el norte ni siquiera saben que acá hay un fuerte militar.}
{206}{}{Te creo. ¿Quieres salir de aquí? Me vendría bien un compañero.}
{207}{}{Bueno, por tu situación, mentir no te ayudará en nada. Quédate aquí y no hagas ruido.}
{208}{}{No sé si deba confiar en ti, pero ya no tengo nada que perder. Si me quedo, ya mero me van a colgar. Pero si no tengo armas ni armadura, no te sirvo de nada. ¿Sabes en dónde está su armería?}
{209}{}{Ya veremos como hacerle, vámonos.}

{210}{}{Ya te dije todo lo que sabía. ¡Déjame en paz!}
{211}{}{Tu historia no es nada convincente.}
{212}{}{Está bien, estamos juntos en esto. ¿Quieres escapar?}
{213}{}{Quédate ahí y deja de hacer ruido.}
{214}{}{Es demasiado pronto para irnos, espera a mi señal.}

{220}{}{Oye, ¿a dónde vamos?}
{221}{}{No hagas ruido, ya lo verás.}
{222}{}{Tendrás que esperarme aquí.}
{223}{}{Pensaba que no ibas a volver. ¿Ya nos vamos?}
{224}{}{Sí, vámonos.}
{225}{}{No, todavía no.}
{226}{}{Yo te sigo, compadre.}
{1226}{}{Yo la sigo, señorita.}
{227}{}{Vamos.}
{228}{}{Chale. Pero no te olvides de mí.}
{229}{}{No te muevas de aquí.}

{230}{}{Deberías guardar tu arma.}
{231}{}{Eso me suena a una muy mala idea. Bueno, la voy a guardar, pero apenas vea problemas, la saco.}
{232}{}{En este momento no deberíamos mostrar hostilidad.}
{233}{}{Tendrás que quitarte esa armadura.}
{234}{}{Bueno, la verdad es muy incómoda.}
{235}{}{Así está bien.}
{236}{}{Espera un momento, con tanta gente vas a alertar a todos. Mejor no, intentaré salir de aquí por mi cuenta.}
{237}{}{¿Estás seguro? Bueno, es cosa tuya.}
{238}{}{Vale, voy a dejar a mi equipo en algún lugar seguro y volveré por ti.}

{250}{}{¿Qué sabes acerca de este lugar?}
{251}{}{No estoy familiarizado con esta zona, pero no deberíamos quedarnos mucho tiempo.}
{252}{}{Comprendo.}
{253}{}{Estas son las ruinas desiertas de una ciudad antigua llamada Hermosillo. Nadie vivía acá hasta que las tropas Mexicanas colocaron su fuerte. No hay mucho que ver, además de las ruinas, los militares y unos civiles.}
{254}{}{Esto es Fénix, la ciudad más grande de la región. Pero no te confíes, este lugar está lleno de víboras.}
{255}{}{Estamos en los barrios bajos de Fénix. Por mi parte, yo no viviría acá. Anda con cuidado.}
{256}{}{¿Un alcantarillado? Eh... ¿Me puedes decir a qué vinimos?}
{257}{}{He pasado por acá algunas veces, pero jamás he estado en la base de los Hojalateros. Los recién llegados no les caen bien y los ven como ciudadanos de segunda clase. Pero, si a ti te gusta la tecnología, puede que te lleves bien con ellos.}
{258}{}{Es un oasis en medio de la ruta comercial. Lo digo en serio. La bomba de agua que hay acá todavía funciona, así que las caravanas se quedan a pasar la noche. Si no molestas al pueblo, no tendrás ningún problema.}
{259}{}{Es una ciudad pacífica pero medio cerrada. Más que nada, cosechan agave y elote... Mira, Puerto Peñasco está más al oeste. Estaría bien ir para allá cuanto antes, no está tan lejos.}
{260}{}{Nunca he venido a esta zona, nos alejamos mucho. ¡Oye, si seguimos así nunca voy a llegar a Puerto Peñasco!}
{261}{}{La Catedral del Fuego es una de monumentos locales. Su gente es bien devota, pero eso no quiere decir que no saben como usar un arma.}
{262}{}{Este lugar da miedo, se siente como si alguien nos mirara...}
{263}{}{¿Qué es esta mamada? ¡La base de la Hermandad ya no está!}
{264}{}{La Hermandad del Acero gobierna este lugar, son buenos tipos, mientras no los estés chingando. Guarda tu arma y cuidadito con lo que dices; no les gustan los vaqueros o los que echan desmadre.}
{265}{}{Algunos llaman a este lugar la Ciudad del Diablo. Se dice que los demonios caminan por estas calles, o algo así. Mira, ¿en serio tenemos que andar por acá?}
{266}{}{¿Así que los monjes mantuvieron este refugio como un secreto durante años y años? Carajo, ¿qué otros secretos tendrán guardados?}
{267}{}{Nunca había andado por acá antes, ¿este es tu rancho?}

{300}{}{Háblame sobre ti.}
{301}{}{No hay mucho que contar. Llámame Pancho, si te late. Estoy aquí por ordenes de unos caravaneros del norte, ocupaban gente que explorara el sur. Tenían la esperanza de encontrar asentamientos adecuados con los que comerciar, pero parece que la idea había fallado desde un principio.}
{302}{}{¿Por qué te encerraron?}
{303}{}{Los militares no creyeron en mis explicaciones y decidieron que era un espía. Para ellos, hay enemigos en todos lados.}
{304}{}{¿Cuáles son tus planes?}
{305}{}{Lo primero, es salir de Hermosillo y quedarnos lejos de la guarnición. Ya luego veremos que hacerle.}
{306}{}{Entonces, salgamos de aquí.}
{307}{}{Creo que sí puedo confiar en ti. Mira, tengo que llegar a Puerto Peñasco. Es un puerto antiguo en la costa del Mar de Cortés. Yo no puedo llegar sólo, así que quizás podamos ir juntos. Hasta quizás igual te den chamba allá.}
{308}{}{¿Qué hay en el puerto?}
{309}{}{Mi patrón está allá. Tengo que informarle de lo que visto... Pero no he podido encontrar nada en especial. Sería bueno encontrar más información acerca de Hermosillo para ellos, seguro que encontramos algo para llevarles.}
{310}{}{Eso es un buen trato. Claro, estoy dentro.}
{311}{}{Me alegro de oír eso, compadre. No te arrepentirás.}
{1311}{}{Me alegro de oír eso, señorita. No te arrepentirás.}
{312}{}{Entonces, vámonos a Puerto Peñasco...}
{313}{}{Te llevaré hacia allá, pero si esto es algún tipo de estafa, lo pagarás.}
{314}{}{Te digo que no hay ningún problema. No te preocupes, te daré una parte de la paga.}
{315}{}{Bueno, vámonos a Puerto Peñasco...}
{316}{}{Lo siento, pero no iré hacia allá.}
{317}{}{Bueno, lo que tú digas. En ese caso, te sugiero que lleguemos al área poblada más cercana y ahí podemos separarnos.}
{318}{}{De acuerdo.}
{319}{}{Parece que ya pudimos escapar. ¿Qué harás ahora?}

{320}{}{¿Me puedes recordar a dónde tenemos que ir?}
{321}{}{Puerto Peñasco, es una ciudad costera junto al Mar de Cortés.}
{322}{}{Entonces, no perdamos el tiempo.}
{323}{}{No puedo ir hacia allá en este momento, perdón.}
{324}{}{Siento decepcionarte, pero explotó la nave que había en Puerto Peñasco. Ese lugar es un cráter.}
{325}{}{No estés chingando. Lo creeré cuando lo vea.}
{326}{}{Bueno, entonces vamos hacia Puerto Peñasco.}
{327}{}{No digas que no te lo advertí.}

{330}{}{Pero qué... ¿Qué carajos pasó acá?}
{331}{}{Este era el lugar en el que tenías que hablar con tu patrón, ¿no?}
{332}{}{Sí, pero... ¿qué pudo haber destruido el puerto entero?}
{333}{}{Me parece que esos 'caravaneros' tenían una mercancía muy peligrosa, ¿no es así?}
{334}{}{Espera... bueno... a ver, me explico. Te mentí, un poquito. No me contrataron los caravaneros; fue la Hermandad del Acero. Y no estaba buscando rutas comerciales, sino... el potencial militar del ejército Mexicano. Pero, ¿qué importa ahora? ¡La base de la Hermandad fue destruida!}
{335}{}{Parece que te quedaste sin tu dinero.}
{336}{}{Entonces, *nosotros* nos quedamos sin el dinero. Mierda, este viaje no fue para nada.}
{337}{}{¿Qué vas a hacer ahora?}
{338}{}{No sé. Sin la Hermandad, las ciudades de por acá van a ir cuesta abajo... y sin las chapas, no hay por qué regresar a Fénix. Tendré que vagar por el yermo, buscando chamba.}
{339}{}{Deberías acompañarme. Me vendrá bien tu ayuda con mi... misión, y podrías tener un lugar en nuestra Villa una vez que todo esté bien por allá.}
{340}{}{¿Crees que tus parientes me van a aceptar? Bueno, vale la pena intentarlo. Eso debe ser genial, tener un hogar propio con tu familia. Vamos, yo te cuido la espalda.}
{1340}{}{¿Crees que tus parientes me van a aceptar? Bueno, vale la pena intentarlo. Eso debe ser genial, tener un hogar propio con tu familia. Vamos, yo te cuido la espalda.}
{341}{}{Vamos, Pancho.}
{342}{}{Tienes razón, estás completamente jodido. Creo que deberíamos separarnos.}
{343}{}{¿Me vas a dejar así? ¿Después de todo lo que hemos pasado juntos?}
{344}{}{Sí, me has demostrado que no puedo confiar en ti. Dame mis cosas y vete.}
{345}{}{¿Sabes? Me gustó escapar de Hermosillo junto a ti. Creo que podrías tener un lugar en nuestra Villa cuando todo esté bien por allá.}

{350}{}{Ya estamos aquí, tendrás que esperarme un rato mientras hablo con el patrón.}
{351}{}{Un segundo, ¿te contrató la Hermandad del Acero? Me habías dicho que...}
{352}{}{Sí, sí, mentí acerca de los caravaneros. La Hermandad del Acero estaba pagando un chingo de chapas por explorar el sur... Espérame acá, esto llevará un rato.}
{353}{}{[Más]}
{354}{}{(Tres horas después, Pancho se te acerca con una mirada arrepentida)}
{355}{}{¿Cómo te fue en la negociación?}
{356}{}{¡Estos pinches cabrones no nos quisieron pagar! Según, la información que conseguí no es útil. Tuve que hablarles de ti y mi rescate. Y les interesas, por alguna razón. Anda a hablar con el Paladín Latham; quiere hablarte. Yo voy a descansar acá, te espero.}
{357}{}{Mierda. Bueno, Pancho. Te veré en un momento.}
{358}{}{El Paladín Latham quería hablar contigo. ¿Lo olvidaste?}
{359}{}{Algo ha cambiado, ya no somos bienvenidos por acá. Creo que deberíamos salir de aquí antes de que nos duerman.}
{360}{}{¿Qué hay de las chapas? ¿Te pagaron?}
{361}{}{Sí, pero me dijeron que ya no quieren trabajar contigo. Lo siento.}
{362}{}{Esos bastardos... ¿Por qué pasé por todo esto? Este viaje no fue para nada.}
{363}{}{¿Qué harás ahora, Pancho?}
{364}{}{No sé. Dado que ya no tengo el contrato con la Hermandad y no tengo chapas, tendré que viajar por el yermo en busca de chamba.}
{365}{}{Podemos hablar de esto en otro momento.}
{366}{}{No, no me resultó hablar con el Paladín Latham.}
{367}{}{Pancho ha dejado de acompañarte, por el momento.}
{368}{}{Según, piensan que la información que tenemos acerca de Hermosillo es inútil. Tendremos que volver allá y obtener más información si queremos que nos paguen.}