{100}{}{Ves a Domínguez.}
{101}{}{Ves a un campesino común y corriente.}

{102}{}{Los militares siempre andan armados y blindados, ¿no?}
{103}{}{¡Piérdete antes de que te vuele los sesos!}
{104}{}{Mis zapatos están a punto de romperse.}
{105}{}{¿Chanclas de goma? ¡Cómo no pensé en eso antes!}
{106}{}{Parece que has resuelto el problema de los zapatos viejos de Domínguez. Está muy feliz al respecto.}

{107}{}{«Pinches militares, siempre andan armados y blindados.»}
{108}{}{«No quiero hacerte daño, ¡sal de aquí!»}
{109}{}{«Mis zapatos están a punto de romperse.»}
{110}{}{«¿Chanclas de goma? ¡Cómo no pensé en eso antes! ¡Gracias!»}
{111}{}{«Parece que has resuelto el problema de los zapatos viejos de Domínguez. Está muy feliz al respecto.»}


{200}{}{Para, gringo. ¿Qué necesitas?}
{201}{}{Sólo quiero hablar. ¿Por qué tanta agresividad?}
{202}{}{Hay militares cerca, pero no te conozco. Si llegaste acá por accidente, es mejor que te vayas.}
{203}{}{Tienes razón. No quiero tener problemas con ustedes...}
{204}{}{Vengo del norte, ¿de verdad me vas a echar? Sólo quiero hacerte unas preguntas sobre la ciudad.}
{205}{}{(te apunta con su arma) Fuera de mi rancho.}
{206}{}{Si así lo quieres...}
{207}{}{Te arrepentirás de esto...}
{208}{}{Tú otra vez. Te dije que te fueras de mi rancho.}
{209}{}{Claro, no hay problema...}

{210}{}{Hagamos esto, responderé tus dudas y luego te vas, ¿bien?}
{211}{}{Ya me voy, cálmate.}
{212}{}{¿Están solos por aquí? ¿No hay nadie más?}
{213}{}{No, no hay ninguna otra familia por aquí, es tranquilo. A los militares no le gusta tener civiles cerca.}
{214}{}{¿Los militares? ¿De quiénes hablas?}
{215}{}{¿No sabes? Si sigues la carretera verás una guarnición de la Nueva República Mexicana. Ahora estas tierras están bajo la protección del General Sarabia.}
{216}{}{¿Así que no podría quedarme aquí si lo quisiera?}
{217}{}{¿No sabes nada acerca de esto, verdad? Mira, nuestra situación es difícil. El ejército del presidente intenta unificar los territorios, pero los que pagamos somos los campesinos. Nadie nos pregunta lo que queremos. Así que vivir cerca del fuerte no es la mejor idea. A los militares no les gustan los vagos que se asientan en donde quieren.}
{218}{}{¿Cómo acabaste viviendo en este lugar?}
{219}{}{Tengo contactos... El fuerte necesita comida, por lo que la guarnición me protege el rancho y a cambio tengo que dar casi toda mi carne.}
{220}{}{Entiendo. Gracias por contármelo, debería irme.}
{221}{}{Eso cambia las cosas... Es mejor que me vaya, de inmediato.}
{222}{}{El General Sarabia... ¿qué sabes de él?}
{223}{}{Su nombre es Manuel Sarabia. Lo vi un par de veces, cuando llegó y en reuniones generales. Suele estar en el cuartel del cerro.}
{224}{}{Creo que debería hablar con él, ojalá que tenga un rato libre.}
{225}{}{¿Los civiles tienen permitido hablar con él?}
{226}{}{¿Los civiles? No. Y no quiero conocerlo. Dicen que hace pozole de sus enemigos.}
{227}{}{Suena a que es alguien impresionante. Debería ir a hablar con él. Adiós.}
{228}{}{Eso cambia las cosas. Es mejor que me vaya. Y lejos. Adiós.}
{229}{}{¿Qué era lo que dijiste del General?}
{230}{}{¿Qué planes tiene su ejército para Arizona?}
{231}{}{No creo que la guarnición piense en dirigirse a Arizona, al menos no creo que pronto. Hay un desierto grande, y por mucho tiempo pensamos que no había nadie vivo hacia allá. Pero si el gobierno lo ordena, el ejército lo hará.}
{232}{}{Gracias, esa información es muy valiosa. Tengo algo de lo que ocuparme. Adiós.}
{233}{}{¿Sabrás que planea su ejército respecto a Arizona?}
{234}{}{¿Conoces los planes del General Sarabia respecto a Arizona?}
{235}{}{Claro, pregunta.}
{236}{}{Sí, pregunta lo que quieras.}
{237}{}{Solo vengo a explorar, no quiero hacerte daño. Hablemos, amigo.}

{238}{}{Gracias por la radio. Nos alegra la vida, al menos un poco.}
{239}{}{¿Puedo hablar contigo?}

{240}{}{¿Has oído de un tal Gallegos? Llegó al norte desde acá.}
{241}{}{¿Conoces a Gallegos? Eso es sorprendente, significa que pudo cruzar el desierto. Pensé que estaba demente y que sería un suicidio.}
{242}{}{De todo su grupo, fue el único que sobrevivió. Así que tenías razón.}
{243}{}{Gallegos y los demás estaban desesperados. El nuevo gobierno y sus tropas oprimen a los campesinos como yo. Algunos como yo tuvimos suerte, pero muchos trabajan como esclavos. Huir al norte era su única opción.}
{244}{}{No estaba para nada bien, supongo que el desierto le quitó unos años.}
{245}{}{No puedo imaginar lo que debió haber pasado en el desierto. Aunque el viejo haya sido considerado un traidor, nos dio un ejemplo de voluntad y perseverancia. Gracias, me alegró escuchar noticias de un amigo. Además, si eres amigo de un amigo, con gusto te recibo aquí.}
{246}{}{De nada.}
{247}{}{Gallegos mencionó el Rancho Domínguez, dijo que eras honesto y un buen hombre.}

{250}{}{¿De dónde sacaste al brahmán?}
{251}{}{¿Brahmán? ¿Qué es eso?}
{252}{}{Los animales del rancho.}
{253}{}{¿No sabes cómo se llama tu rebaño? Eso es chistoso.}
{254}{}{Ah, las wakas. Ustedes los norteños siempre andan complicando las cosas. El ejército llevó a cabo una redada de wakas y les compré algunas, en ese entonces eran jóvenes. Así es como solían conseguir carne, antes de que comenzaran a quitármela. En cierto modo, era un préstamo que ahora estoy pagando con comida.}
{255}{}{¿Te puedo hacer otra pregunta?}
{256}{}{Sólo preguntaba. Adiós.}
{257}{}{Yo he ido a San Brahmán, allí creen que estos animales son sagrados.}
{258}{}{¿San Brahmán? Nunca escuché de algo así. Pienso que es una pendejada.}
{259}{}{Puede ser, pero ellos estaban dispuestos a arriesgarse la vida por los animales.}
{260}{}{Así es. Jamás había visto semejante idiotez.}
{261}{}{Me están cansando tus preguntas, tengo que ir a hacer mis cosas.}
{262}{}{Ya me voy, no te preocupes.}

{270}{}{Mencionaste que México estaba en una situación difícil. ¿Qué está ocurriendo allá?}
{271}{}{Sí. Destruyeron la capital durante la Gran Guerra, y muchas provincias ganaron independencia. La mayoría formaron pequeños ejércitos y defendieron sus fronteras.}
{272}{}{Sigue hablando, te escucho.}
{273}{}{No es necesario que sigas, ya entendí.}
{274}{}{Yo solo sé un poco. Los carteles se apoderaron de los estados del norte, antes traficaban armas, drogas y personas. Como perdieron su negocio, se enfocaron en defender sus territorios. Ahora son propiedad privada de sus descendientes.}
{275}{}{¿Qué pasó en el resto del país?}
{276}{}{El sur tuvo lo más difícil, los nacionalistas se dividieron en pequeños estados. Yucatán, Chiapas, Tabasco y Guerrero siguen discutiendo sobre quién manda por allá.}
{277}{}{Pero eso ya es historia. ¿Qué está pasando actualmente?}
{278}{}{Todo cambió con el nuevo presidente. Él reunió un poderoso ejército y subyugó todos los estados centrales, desde Durango a Veracruz. Ahora está luchando al este del Istmo de Tehuantepec. Las tribus locales son muy orgullosas, así que esta guerra durará años. Los estados del norte están empezando a perder territorio.}
{279}{}{Gracias por hablarme de tu historia.}
{280}{}{De nada. Estoy feliz de compartir la historia de mi gente con personas como tú. ¿Quién sabe? Quizás hasta tus ancestros hayan venido de México.}
{281}{}{Tienes muchas cosas interesantes que contarme. ¿Te puedo preguntar otra cosa?}
{282}{}{Gracias, Domínguez. Adiós.}

{300}{}{«¿Qué necesitas? No te conozco.»}
{301}{}{«Sólo quiero hablar. ¿Por qué tanta agresividad?»}
{302}{}{«Hay militares cerca, pero no te conozco. Si llegaste acá por accidente, es mejor que te vayas.»}
{303}{}{«Tienes razón. No quiero tener problemas con ustedes...»}
{304}{}{«Vengo del norte, ¿de verdad me vas a echar? Sólo quiero hacerte unas preguntas sobre la ciudad.»}
{305}{}{(te apunta con su arma) «Fuera de mi rancho.»}
{306}{}{«Si así lo quieres...»}
{307}{}{«Te arrepentirás de esto...»}
{308}{}{«Tú otra vez. Te dije que te fueras de mi rancho.»}
{309}{}{«Claro, no hay problema.»}

{310}{}{«Hagamos esto, responderé tus dudas y luego te vas, ¿bien?»}
{311}{}{«Ya me voy, cálmate.»}
{312}{}{«¿Están solos por aquí? ¿No hay nadie más?»}
{313}{}{«No, no hay ninguna otra familia por aquí, es tranquilo. A los militares no le gusta tener civiles cerca.»}
{314}{}{«¿Los militares? ¿De quiénes hablas?»}
{315}{}{«¿No sabes? Si sigues la carretera verás una guarnición de la Nueva República Mexicana. Ahora estas tierras están bajo la protección del General Sarabia.»}
{316}{}{«¿Así que no podría quedarme aquí si lo quisiera?»}
{317}{}{«¿No sabes nada acerca de esto, verdad? Mira, nuestra situación es difícil. El ejército del presidente intenta unificar los territorios, pero los que pagamos somos los campesinos. Nadie nos pregunta lo que queremos. Así que vivir cerca del fuerte no es la mejor idea. A los militares no les gustan los vagos que se asientan en donde quieren.»}
{318}{}{«¿Cómo acabaste viviendo en este lugar?»}
{319}{}{«Tengo contactos... El fuerte necesita comida, por lo que la guarnición me protege el rancho y a cambio tengo que dar casi toda mi carne.»}
{320}{}{«Entiendo. Gracias por contármelo, debería irme.»}
{321}{}{«Eso cambia las cosas... Es mejor que me vaya, de inmediato.»}
{322}{}{«El General Sarabia... ¿qué sabes de él?»}
{323}{}{«Su nombre es Manuel Sarabia. Lo vi un par de veces, cuando llegó y en reuniones generales. Suele estar en el cuartel del cerro.»}
{324}{}{«Creo que debería hablar con él, ojalá que tenga un rato libre.»}
{325}{}{«¿Los civiles tienen permitido hablar con él?»}
{326}{}{«¿Los civiles? No. Y no quiero conocerlo. Dicen que hace pozole de sus enemigos.»}
{327}{}{«Suena a que es alguien impresionante. Debería ir a hablar con él. Adiós.»}
{328}{}{«Eso cambia las cosas. Es mejor que me vaya. Y lejos. Adiós.»}
{329}{}{«¿Qué era lo que dijiste del General?»}
{330}{}{«¿Qué planes tiene su ejército para Arizona?»}
{331}{}{«No creo que la guarnición piense en dirigirse a Arizona, al menos no creo que pronto. Hay un desierto grande, y por mucho tiempo pensamos que no había nadie vivo hacia allá. Pero si el gobierno lo ordena, el ejército lo hará.»}
{332}{}{«Gracias, esa información es muy valiosa. Tengo algo de lo que ocuparme. Adiós.»}
{333}{}{«¿Sabrás que planea su ejército respecto a Arizona?»}
{334}{}{«¿Conoces los planes del General Sarabia respecto a Arizona?»}
{335}{}{«Claro, pregunta.»}
{336}{}{«Sí, pregunta lo que quieras.»}
{337}{}{«Solo vengo a explorar, no quiero hacerte daño. Hablemos, amigo.»}

{338}{}{«Gracias por la radio. Nos alegra la vida, al menos un poco.»}
{339}{}{«¿Puedo hablar contigo?»}

{340}{}{«¿Has oído de un tal Gallegos? Llegó al norte desde acá.»}
{341}{}{«¿Conoces a Gallegos? Eso es sorprendente, significa que pudo cruzar el desierto. Pensé que estaba demente y que sería un suicidio.»}
{342}{}{«De todo su grupo, fue el único que sobrevivió. Así que tenías razón.»}
{343}{}{«Gallegos y los demás estaban desesperados. El nuevo gobierno y sus tropas oprimen a los campesinos como yo. Algunos como yo tuvimos suerte, pero muchos trabajan como esclavos. Huir al norte era su única opción.»}
{344}{}{«No estaba para nada bien, supongo que el desierto le quitó unos años.»}
{345}{}{«No puedo imaginar lo que debió haber pasado en el desierto. Aunque el viejo haya sido considerado un traidor, nos dio un ejemplo de voluntad y perseverancia. Gracias, me alegró escuchar noticias de un amigo. Además, si eres amigo de un amigo, con gusto te recibo aquí.»}
{346}{}{«De nada.»}
{347}{}{«Gallegos mencionó el Rancho Domínguez, dijo que eras honesto y un buen hombre.»}

{350}{}{«¿De dónde sacaste al brahmán?»}
{351}{}{«¿Brahmán? ¿Qué es eso?»}
{352}{}{«Los animales del rancho.»}
{353}{}{«¿No sabes cómo se llama tu rebaño? Eso es chistoso.»}
{354}{}{«Ah, las wakas. Ustedes los norteños siempre andan complicando las cosas. El ejército llevó a cabo una redada de wakas y les compré algunas, en ese entonces eran jóvenes. Así es como solían conseguir carne, antes de que comenzaran a quitármela. En cierto modo, era un préstamo que ahora estoy pagando con comida.»}
{355}{}{«¿Te puedo hacer otra pregunta?»}
{356}{}{«Sólo preguntaba. Adiós.»}
{357}{}{«Yo he ido a San Brahmán, allí creen que estos animales son sagrados.»}
{358}{}{«¿San Brahmán? Nunca escuché de algo así. Me suena a que es una tarugada.»}
{359}{}{«Puede ser, pero ellos estaban dispuestos a arriesgarse la vida por los animales.»}
{260}{}{«Así es. Jamás había visto semejante idiotez.»}
{361}{}{«Me están cansando tus preguntas, tengo que ir a hacer mis cosas.»}
{362}{}{«Ya me voy, no te preocupes.»}

{370}{}{«Mencionaste que México estaba en una situación difícil. ¿Qué está ocurriendo allá?»}
{371}{}{«Sí. Destruyeron la capital durante la Gran Guerra, y muchas provincias ganaron independencia. La mayoría formaron pequeños ejércitos y defendieron sus fronteras.»}
{372}{}{«Sigue hablando, te escucho.»}
{373}{}{«No es necesario que sigas, ya entendí.»}
{374}{}{«Yo solo sé un poco. Los carteles se apoderaron de los estados del norte, antes traficaban armas, drogas y personas. Como perdieron su negocio, se enfocaron en defender sus territorios. Ahora son propiedad privada de sus descendientes.»}
{375}{}{«¿Qué pasó en el resto del país?»}
{376}{}{«El sur tuvo lo más difícil, los nacionalistas se dividieron en pequeños estados. Yucatán, Chiapas, Tabasco y Guerrero siguen discutiendo sobre quién manda por allá.»}
{377}{}{«Pero eso ya es historia. ¿Qué está pasando actualmente?»}
{378}{}{«Todo cambió con el nuevo presidente. Él reunió un poderoso ejército y subyugó todos los estados centrales, desde Durango a Veracruz. Ahora está luchando al este del Istmo de Tehuantepec. Las tribus locales son muy orgullosas, así que esta guerra durará años. Los estados del norte están empezando a perder territorio.»}
{379}{}{«Gracias por hablarme de tu historia.»}
{380}{}{«De nada. Estoy feliz de compartir la historia de mi gente con personas como tú. ¿Quién sabe? Quizás hasta tus ancestros hayan venido de México.»}
{381}{}{«Tienes muchas cosas interesantes que contarme. ¿Te puedo preguntar otra cosa?»}
{382}{}{«Gracias, Domínguez. Adiós.»}

