{100}{}{Ves a Garrett.}
{105}{}{¡Bastardos! ¡Los haré pedazos por lo que le hicieron a mis amigos!}

{200}{}{¿Eh? ¿Otro normalucho? ¿Y te acercas a mí? ¡Ja! ¿Eres tonto o qué?}
{1200}{}{¿Eh? ¿Otra normalucha? ¿Y te acercas a mí? ¡Ja! ¿Eres tonta o qué?}
{201}{}{¿Qué es este lugar? ¿Y quién eres tú?}
{202}{}{¿Por qué eres tan verde, gordo y feo?}
{203}{}{Guardar tus armas y seguirme. Levi hablar contigo.}
{204}{}{Claro, llévame con él. Quiero hacerle unas preguntas.}
{205}{}{Escúchame, grandulón, yo hablaré contigo.}
{206}{}{¡Dije, que tú irás con Levi! Si tú no escuchar, yo quebrarte las piernas, y arrastrarte hasta allá, y tirarte como basura.}
{207}{}{Ya entendí, voy, pero no me pegues.}
{208}{}{Inténtalo, fenómeno.}
{209}{}{Por favor, escúchame. Vengo en son de paz.}
{1209}{}{Por favor, escúchame. Vengo en son de paz.}

{210}{}{¿Qué querer tú, normalucho?}
{211}{}{Nada, adiós.}
{212}{}{Sí, señor.}

{220}{}{Charlemos un poco. ¿Cómo te llamas?}
{221}{}{Garrett. No hablo con normales.}
{222}{}{Garrett. No confío en tu gente.}
{223}{}{}
{224}{}{Comprendo. Fue un gusto conocerte. Adiós.}
{225}{}{¿Por qué? ¿Acaso te hicimos algo?}
{226}{}{Cállate o te aplastaré.}
{227}{}{Tus amigos no hablan mucho. ¿Por qué tanto enojo contra los humanos?}
{228}{}{¿Enojo? No. El Maestro enseñó a respetar la vida. Pero los normaluchos como tú nos echaron del Oeste. Ahora, si tú no callarte, yo callarte.}
{229}{}{Ya, ya...}
{230}{}{¿Siempre has sido... así?}
{231}{}{Yo era como tú. Tenía sentimientos - miedo, odio, envidia. Maestro darnos nueva vida, deshacernos de idiotez humana. Y entonces los normaluchos mataron al Maestro.}
{232}{}{Lo siento, no quería hacerte enojar. Me largo-}
{233}{}{¿'Nueva vida'? ¿Te refieres al mutágeno?}
{234}{}{El mutágeno es sólo una parte. La cosa entera toma un año. Yo entrenar, ayuna, meditar en escombros. Uno no recibir mutágeno si no estar listo.}
{235}{}{Parece que has pasado por mucho, debería ir a ocuparme de mis asuntos. Adiós.}
{236}{}{¿Maestro? ¿Quién es?}
{237}{}{¿Quién es ese Maestro del que hablas?}
{238}{}{Es mi dios.}
{239}{}{Eso me lo deja un... poquito más claro.}
{240}{}{¡Ja! Humano estúpido, tú jamas ver a dios. ¡Tú matarlo!}
{241}{}{¿Matar a un dios? ¿Cómo es eso posible?}
{242}{}{Ya no hay dios. Estar solos. Eso es todo.}
{243}{}{Comprendo. Dejémoslo así.}
{244}{}{¿Entonces Levi está a cargo?}
{245}{}{Él es la mano de mi dios. Yo moriría por él.}
{246}{}{Pensé que eras el más duro de la iglesia.}
{247}{}{Eres muy leal.}
{248}{}{Levi nos salvó. Sin él, no hay futuro. Yo servirle como yo serví a Maestro. Pero humano como tú no entender nuestro dolor.}
{249}{}{Bien, asumamos que eso es cierto.}

{250}{}{Hola, Garrett. ¿Qué tal el día?}
{251}{}{Estamos bien. Mis chicos protegerte si ser necesario.}
{252}{}{Parece que las cosas cambiaron.}
{253}{}{¡Ja! Tú tener razón, humano. Pero tú necesitar ayuda. Ten, llevarte este Radiador.}
{254}{}{¿Radiador? Supongo que lo inventó Levi. ¿Puedes enseñarme a usarla?}
{255}{}{Tenemos que enseñar todo a los humanos. Bueno, yo enseñar... Si tú me traes comida buena.}
{256}{}{De acuerdo, te traeré algo.}
{257}{}{¿Comida? ¿En esta ciudad? Pides mucho, verdecito.}

{260}{}{Me prometiste que me enseñarías a usar el Radiador.}
{261}{}{¡Tengo hambre!}
{262}{}{Bueno, yo enseñarte. No es difícil.}
{263}{}{No perdamos el tiempo, no quisiera que te gruña la panza en medio de mi entrenamiento...}
{264}{}{Genial, pero hagámoslo luego.}
{265}{}{Pensándolo bien, no me interesan las armas de energía. Pero lo que tienes es impresionante, ¡enséñame cómo usar un arma grande!}
