{100}{}{Ves al Paladín Barkley.}
{101}{}{Este guerrero tiene la piel encurtida, su rostro es inquebrantable y muestra que está listo para la batalla.}
{102}{}{Hora de reposicionarse.}
{103}{}{Gracias, Doc.}
{104}{}{¡Nos has traicionado! ¡Vas a morir como un perro!}
{1104}{}{¡Nos has traicionado! ¡Vas a morir como una sucia puta!}
{105}{}{¡Pagarán por las muertes de mis amigos, malditos bastardos!}
{106}{}{¡M-malditos mutantes! Da un paso más y te disparo. ¿Estás con ellos?}

{110}{}{¡No puedo creer esto! ¿Qué ocurrió?}
{111}{}{Te doy la bienvenida a la Hermandad.}
{112}{}{No me hice un paladín para esto.}
{113}{}{Hmm, parece que debemos agregarle un par de ceros a la cuenta de enemigos.}
{114}{}{Ah, esto me recuerda a los viejos tiempos...}

#Counter dialogue
{200}{}{Grr, maldita sea... Casi te vuelo la cabeza, pensé que eras otro mutante más. ¿Eres parte del equipo de apoyo?}
{201}{}{¿Qué equipo? ¿De qué estás hablando?}
{202}{}{Demonios. ¿Así que la Hermandad no fue lo que te trajo aquí? Que malas noticias. ¿Qué estás haciendo en este lugar? Está maldito.}
{203}{}{Sólo estoy registrando este lugar, las ruinas abandonadas suelen tener cosas valiosas.}
{204}{}{No puede ser, un chatarrero... (suspiro) Soy muy desafortunado, se me acabó la suerte.}
{1204}{}{No puede ser, una chatarrera... (suspiro) Soy muy desafortunado, se me acabó la suerte.}
{205}{}{¿Qué está pasando?}
{206}{}{Estoy buscando a alguien, pero eso es personal.}
{207}{}{Bien... Pretendamos que eso es verdad. ¿Me ayudarías a encontrar a alguien?}
{208}{}{¿Acaso perdiste a alguien?}
{209}{}{Escuché tu llamado de auxilio en la radio y vine a ayudarte.}
{1209}{}{Escuché tu llamado de auxilio en la radio y vine a ayudarte.}
{210}{}{Por fin, ocurre algo bueno en este día horroroso.}
{211}{}{Cuéntame lo que pasó.}
{212}{}{Deberías haberme disparado, idiota. Ahora, presionaré el gatillo...}
{213}{}{¿Así que eres parte de la Hermandad del Acero? Los odio a todos ustedes. ¡Muere, bastardo!}

{220}{}{Sí, la Hermandad me encargó una misión de rescate.}
{221}{}{Hmm. No te reconozco, muéstrame tu placa.}
{222}{}{¿Placa? No estoy con la Hermandad, sólo me contrataron.}
{223}{}{Entiendo. Ya había oído que la Hermandad no estaba teniendo mucho éxito en Arizona. Eso es triste. ¿En dónde está el resto de tu equipo?}
{224}{}{¿De qué estás hablando? Estoy sólo.}
{1224}{}{¿De qué estás hablando? Estoy sola.}
{225}{}{¡Mierda! ¿En qué estaban pensando? ¿Cómo creen que una sola persona podrá resolver esto? Aunque, un grupo pequeño posee una ventaja táctica en las ruinas... Está bien, pero no te metas en camino.}
{226}{}{¿Qué pasó?}
{227}{}{Eh... Toma, tengo una placa de la Hermandad. ¿Ahora me crees?}
{228}{}{Reconozco el nombre de la placa, dejaré que te expliques. Tienes una sola oportunidad.}
{229}{}{Em... Al diablo. ¡Muere!}
{230}{}{Sí, no soy parte de la Hermandad. Pensaba que me ibas a matar...}
{231}{}{Agh, cobarde de mierda, ¿y ahora cómo quieres que confíe en ti?}
{232}{}{¿Podrías contarme lo que pasó? Así podremos ayudarnos el uno al otro.}
{233}{}{Escucha, sé que estás en problemas. No importa en qué bando estemos, tenemos que ayudarnos.}
{234}{}{De acuerdo, pero no vuelvas a intentar engañarme. No toleraré una mentira.}
{235}{}{Eh, bueno. Entonces, quizás puedes contarme lo que realmente estás haciendo aquí.}

{240}{}{Los necrófagos, esos 'segadores'... Le tendieron una emboscada a mi escuadrón. Durante el caos, perdí el rastro del resto de mi equipo y no perdí el contacto con ellos. Además, durante la pelea, mi pierna fue herida.}
{241}{}{¿Pero eres un militar, no? Y estás totalmente armado.}
{242}{}{Ya veo. La misión fracasó antes de que siquiera empezara.}
{243}{}{Nadie esperaba encontrar hostiles entre estas ruinas, pensábamos que estaban abandonadas, así que atravesamos la ciudad para evadir a los mutantes del desierto.}
{244}{}{Bien. ¿Y cuál es tu plan?}
{245}{}{Tengo que reunir a mi escuadrón, si es que alguno sigue con vida. También debo curarme la pierna para llegar hasta nuestro objetivo... Oye, sé un buen samaritano - ¿podrías ayudarme con esto?}
{246}{}{Por supuesto, no ignoraré a alguien que está en problemas.}
{247}{}{Sabía que podía contar contigo. Si completo mi misión, no lo olvidaré.}
{248}{}{Espero que no.}
{249}{}{No es tu día de suerte, soldado. Tendré que registrar tu cadáver...}
{250}{}{Esto es un trabajo peligroso. ¿Por qué debería arriesgarme?}
{251}{}{No te preocupes, una vez que lleguemos a la base, se te recompensará muy bien.}
{252}{}{De verdad espero que ese sea el caso.}
{253}{}{Oh, por cierto, soy el Paladín Barkley. Ahora, ve a encontrar a mi escuadrón. Pero ten cuidado al salir de aquí, he tendido varias trampas.}
{254}{}{Estoy en ello.}
{255}{}{No me interesan las recompensas, mi aldea necesita protección, y aliados.}
{256}{}{Si llegamos a la base, le hablaré a los ancianos acerca de tu problema. Pero por el momento, ayúdame.}
{257}{}{De acuerdo.}

{260}{}{¿Cómo puedo salir de aquí sin herirme?}
{261}{}{Hay varias trampas en el pasillo, mira por dónde pisas.}
{262}{}{Gracias.}
{263}{}{Mira, tengo muchas preguntas.}

#Re-dialogue
{300}{}{¿Cuál es tu informe de la situación?}
{301}{}{Todo se encuentra bien.}
{302}{}{¿Sí?}
{303}{}{Tenemos que hablar.}
{304}{}{¿Qué quieres saber?}
{305}{}{Ya hablamos lo suficiente.}
{306}{}{Deja de charlar, no tenemos tiempo para esto.}
{307}{}{Sí, tienes razón.}
{308}{}{¡Estoy a punto de dispararle a estos mutantes!}
{309}{}{Eso era todo por el momento.}

{310}{}{¿Qué es lo que debo hacer?}
{311}{}{Curar mi herida y encontrar al resto del equipo. Una vez que hayas hecho, hablaremos del plan.}
{312}{}{De acuerdo.}
{313}{}{Esto es una herida seria, seguramente no pueda curarla.}
{314}{}{Sólo encuentra algún medicamento, había un poco entre el cargamento de la caravana. Apresúrate, antes de que los necrófagos se lleven todo.}
{315}{}{¿Cómo acabaste así?}
{316}{}{Caí en una emboscada. Los necrófagos nos tendieron trampas y crearon una cortina de polvo. Esos hijos de puta, caí en su trampa igual que un novato...}
{317}{}{Ya veo. Hablemos sobre el plan.}
{318}{}{Empezaré con la misión.}
{319}{}{Voy a ir a buscar a los demás.}

{320}{}{¿Quién más estaba en el equipo?}
{321}{}{Varias personas, la mitad debe estar muerta, de eso no tengo dudas; no sé que ocurrió con los demás.}
{322}{}{Sigue.}
{323}{}{Voy a ir a buscar a los demás.}
{324}{}{La última vez que escuché del escudero fue cerca del supermercado, pero luego de eso perdimos contacto.}
{325}{}{El caballero mantuvo su posición cerca del punto de la emboscada, fue cerca del monumento.}
{326}{}{Nos acompañaba Diana de los Seguidores del Apocalipsis. Pude escuchar sus gritos; los necrófagos la arrastraban hacia algún lado.}
{327}{}{¿Quién más estaba en el equipo?}
{328}{}{¿Qué pasa si todos murieron?}
{329}{}{En ese caso, es mi deber recuperar sus chapas de identificación para informar a nuestros líderes y así poder honrarlos.}
{330}{}{¿En dónde ocurrió el ataque a la caravana?}
{331}{}{Hacia el noroeste, en la Carretera 5, junto a un monumento.}
{332}{}{Ya veo.}
{333}{}{Ustedes eran una caravana armada, ¿cómo los derrotaron unos necrófagos?}
{334}{}{Puede que estos necrófagos sean salvajes, pero siguen siendo lo suficientemente listos como para luchar. Han tenido una vida larga entre las ruinas y eso les ha enseñado mucho.}
{335}{}{¿Qué fue lo que hicieron?}
{336}{}{Nos emboscaron. Los necrófagos... bueno, he escuchado que aquí los llaman segadores. Ellos tendieron trampas y nos atrajeron a un sitio que fuera difícil de defender. Nos rodearon y lanzaron bolsas de polvo, lo que hizo una cortina de humo y arrastraron a todos hacia el polvo, uno por uno.}
{337}{}{Sigue, te escucho.}
{338}{}{Pudimos matar a unos cuantos, pero habían demasiados. Una vez que empezó el ataque frontal, fui el único que pudo mantener su posición. Tuve que hacer una retirada... Mierda, ¡si sólo hubiera tenido el tiempo de haber entrado a la servoarmadura!}
{339}{}{Lo siento mucho.}
{340}{}{Todos podemos fallar, paladín. No eres una excepción.}
{341}{}{¿Alguien más?}
{342}{}{De acuerdo, vamos a ver que quedó por allá.}
{343}{}{Tu herida no es grave. ¿Qué puedo hacer?}
{344}{}{Ya casi estoy de vuelta a la normalidad, sólo falta encontrar a los demás miembros del escuadrón. Luego de eso, podremos decidir qué hacer.}
{345}{}{Debemos encontrar a Diana, puede que siga con vida y necesite ayuda.}
{346}{}{Debemos encontrar a Diana, puede que siga con vida y necesite ayuda. Y a mí me vendría bien una ayuda con mi pierna.}
{347}{}{Encontré el cadáver del caballero, seguiré con la búsqueda.}
{348}{}{Hallé al escudero, pero estaba muerto. Voy a seguir con la búsqueda.}

{350}{}{Tus hermanos han muerto, aquí están sus chapas de identificación.}
{351}{}{Fallecieron luchando como guerreros de verdad. Que se honre su memoria... ¿Y qué hay de la chica? Una civil de los Seguidores de los Apocalipsis nos estaba acompañando.}
{352}{}{No sé nada de ella.}
{353}{}{Debemos estar seguros, el alto mando me ordenó que la escoltara. Si la abandono estaría desobedeciendo mis órdenes y no puedo hacer eso.}
{354}{}{Voy a intentar averiguar qué le ocurrió.}
{355}{}{Tienen retenida a Diana en la vieja iglesia.}
{356}{}{¿Retenida? Pero, ¿por quién? Los segadores apenas son capaces de hablar.}
{357}{}{No, no son ellos. Allí adentro hay una especie de... culto.}
{358}{}{No entiendo. ¿Un culto? ¿Quizás ese culto controle a los Segadores? Nos hace falta más información, pero rescatar a Diana es nuestra prioridad.}
{359}{}{Voy a pensar en cómo hacer eso.}
{360}{}{Diana ha muerto, no tengo dudas.}
{361}{}{Esto son malas noticias, por esa chica me van a reprender severamente, quizás hasta me lleven a la corte. Demonios, no quiero volver a ese congestionado búnker en California. Gracias por la ayuda.}
{362}{}{¿Eso era todo lo que estabas buscando?}
{363}{}{Diana nos está esperando en la salida, allí podrás hablar con ella.}
{364}{}{Hiciste un buen trabajo. Te debo una.}
{365}{}{¿Eso era todo lo que estabas buscando?}
{366}{}{Diana se fue de la ciudad, no quería quedarse en un lugar como este.}
{367}{}{¿Se fue sin mí? Mierda, y yo arriesgué mi vida por ella... Bueno, la dejaré ir. Ya no es asunto mío.}
{368}{}{¿Entonces ya no queda nada que hacer aquí?}
{369}{}{Encontré a Diana.}
{370}{}{¿En qué condición se encuentra? ¿Está viva?}
{371}{}{Iré a encontrar a los demás.}
{372}{}{Fallecieron luchando como guerreros de verdad. Que se bendiga su memoria...}
{373}{}{Así es. Pero no puedo regresar a la base sin completar el objetivo principal.}
{374}{}{¿Cuál es el objetivo principal?}
{375}{}{Entregar la servoarmadura. Se encontraba en el cargamento que llevábamos hacia nuestra base en Puerto Peñasco. Ahora está en las garras de los Segadores, es una gran pérdida.}
{376}{}{No había ninguna servoarmadura en el sitio del ataque, los mutantes la llevaron hacia la iglesia.}
{377}{}{Entonces debemos recuperarla, ya sabes cómo entrar y salir de forma segura. Así que cuento con tu ingeniosidad.}
{378}{}{No será fácil, pero parece que soy la única persona que puede hacerlo. Ya voy.}
{379}{}{Tengo la servoarmadura. Estaría muerto si no fuera por ella, fue lo que me dejó escapar de allí.}
{1379}{}{Tengo la servoarmadura. Estaría muerta si no fuera por ella, fue lo que me dejó escapar de allí.}
{380}{}{Entregar la servoarmadura, la estábamos llevando hacia nuestra base en Puerto Peñasco. Debes regresarla a nuestra base.}
{381}{}{Has hecho un buen trabajo, pero debes regresarla a nuestra base.}
{382}{}{¿Cómo? ¿Quieres que devuelva una armadura así de chingona? ¿No crees que estás pidiendo mucho?}
{383}{}{Esto es propiedad de la Hermandad del Acero. ¿Tienes algún problema con eso, civil?}
{384}{}{No, el problema es tuyo. ¡Porque ahora la armadura es mía!}
{385}{}{No hay ningún problema. Esta cosa es una carga, la devolveré.}
{386}{}{Claro, esta cosa es una carga, la devolveré.}
{387}{}{Gracias por tu ayuda, a la Hermandad le vendría bien alguien como tú. Una vez que llegue a la base, le contaré todo lo ocurrido al alto mando. Por el momento, llévale la armadura al intendente. Yo necesitaré recuperar fuerzas antes de seguir.}
{388}{}{Nos vemos en la base, Barkley.}
{389}{}{Lo siento, pero ya fui a Puerto Peñasco y le entregué la armadura al intendente.}
{1389}{}{Lo siento, pero ya fui a Puerto Peñasco y le entregué la armadura al intendente.}
{390}{}{Gracias por tu ayuda, a la Hermandad le vendría bien alguien como tú. Una vez que llegue a la base, le contaré todo lo ocurrido al alto mando. Yo necesitaré recuperar fuerzas antes de seguir.}
{391}{}{Nos vemos en la base, Barkley.}
{392}{}{Agradezco tu ayuda, me recuerdas a un Morador del Refugio que nos ayudó a luchar contra los supermutantes en California. Desde ese entonces, ningún civil había ayudado tanto a la Hermandad. Sigue así.}
{393}{}{Si es por la Hermandad, vale la pena seguir intentándolo. ¿Quieres que sigamos viajando?}
{394}{}{Exactamente. Ahora podré regresar la base con la consciencia limpia, aunque no puedo imaginar la vergüenza que me espera allí. Demonios, mataron al escuadrón entero y perdimos nuestra carga, esto no se olvidará por mucho tiempo, incluso si la corte decide que no cometí ningún error.}
{395}{}{Tus hermanos lo entenderán, de eso estoy seguro.}
{396}{}{Sí que estás en problemas, eso no lo dudo.}
{397}{}{Gracias por tu ayuda, a la Hermandad le vendría bien alguien como tú. Una vez que llegue a la base, le contaré todo lo ocurrido al alto mando. Yo necesitaré recuperar fuerzas antes de seguir.}
{398}{}{Volveremos a vernos en algún punto. Buena suerte.}
{399}{}{Entonces, ¿quieres venir conmigo? Necesito apoyo de combate.}

#Team
{400}{}{¿No quieres venir conmigo? Eres un veterano y me vendría bien tu ayuda.}
{401}{}{Eso no lo dudo, pero como puedes ver, estoy en mal estado. Apenas puedo defenderme con una herida así.}
{402}{}{Está bien. Pero, ¿al menos podemos hablar?}
{403}{}{Está bien, lo haré yo.}
{404}{}{Eso no lo dudo. Pero si vamos juntos atraería demasiado la atención de los necrófagos. Por el momento, esto no es la mejor estrategia.}
{405}{}{Si ustedes fueran soldados, yo asumiría el mando. Pero con un grupo como este, estaríamos perdiendo toda ventaja táctica. Si quieres mi ayuda, debes deshacerte del 'peso' que llevas encima.}
{406}{}{Olvídalo.}
{407}{}{De acuerdo, hablaré con mi acompañante.}
{408}{}{Te debo una, si te diriges hacia nuestra base en Puerto Peñasco, voy a ir contigo.}
{409}{}{De acuerdo, yo voy hacia allá. Vamos juntos.}
{410}{}{No. Yo debo ir hacia otro lado, quizás nos veamos en otro momento.}
{411}{}{Por el momento, debemos guardar nuestras armas.}
{412}{}{¿Perdiste la cabeza? ¿Quieres que me maten?}
{413}{}{Tienes razón, es una estupidez. Olvídalo.}
{414}{}{No, pero hay que demostrar que no seremos agresivos para evitar una pelea.}
{415}{}{Hmm. Está bien, pero recuerda esto - soy capaz de desenfundar mi arma en menos de un segundo.}
{416}{}{Eso es bueno.}
{417}{}{Vamos a colocarte tu otra armadura. Dame la que tienes puesta.}
{418}{}{Será un placer, mi otra armadura era de mi talla.}
{419}{}{Genial.}
{420}{}{Defiende esta posición, debo alejarme.}
{421}{}{Buena idea, puedes explorar el área mientras limpio mi equipamiento.}
{422}{}{Eh, vale.}
{423}{}{Prepárate, ya podemos seguir.}
{424}{}{Te sigo, espero que la ruta que conozcas sea segura.}
{425}{}{Sí... claro. Vamos.}
{426}{}{Es hora de decir adiós. Debemos separarnos.}
{427}{}{¿Estás seguro? Pero, no te olvides de Barkley, soldado.}
{1427}{}{¿Estás segura? Pero, no te olvides de Barkley, hermana.}
{428}{}{No me olvidaré de ti. Nos vemos luego, Barkley.}
{429}{}{¿En qué estoy pensando? Te necesito o las hormigas me comerán con todo y huesos.}
{430}{}{Acompáñame, necesito la protección de un veterano como tú.}
{431}{}{Pero si no me ayudas, podría morir.}
{432}{}{Créeme, tendrás mejores posibilidades si te escondes entre las sombras, por cuenta propia. Yo atraeré demasiado la atención de los necrófagos.}
{433}{}{Ya veo.}
{434}{}{No podré hacer esto sin ti, de ninguna manera. Si no quieres ayudarme, me largo.}
{435}{}{Sabía que no podía contar contigo... De acuerdo, mi pierna ya no duele tanto, puedo caminar.}
{436}{}{Así está mejor.}
{437}{}{¿Sabes? Si cojeas así, atraerás mucho la atención. Es mejor que vaya sin ti.}
{438}{}{Te debo una. Puedes contar conmigo si necesitas protección o un compañero.}
{439}{}{Entonces vamos, tenemos un largo camino por delante.}

#Place
{450}{}{¿Qué es lo que piensas sobre este lugar?}
{451}{}{No es nada especial, no hay razón por la cual quedarnos aquí.}
{452}{}{Comprendo.}
{453}{}{Esto es un puesto avanzado de la Hermandad. Te doy la bienvenida. Pero recuerda que esto es una instalación de alta seguridad, a nuestros comandantes no les agradarán que andes por ahí sin permiso.}
{454}{}{Sigo sin procesar que nuestro fuerte haya sido destruido. Aquí sólo estaban sirviendo los mejores soldados que podía ofrecer la Hermandad.}
{455}{}{Es otra ruina del Viejo Mundo, casi todas las ciudades de California yacen sobre ruinas como estas.}
{456}{}{Este sitio es el cielo, comparado a lo que vimos en el Infierno. Me parece que la Hermandad se involucró con este lugar.}
{457}{}{Me parece que los Hojalateros viven aquí, sé que la Hermandad firmó un contrato con ellos para hacer manutención al puesto avanzado.}
{458}{}{Esta ciudad está prosperando. El único lugar en California con el que podría compararlo, es el Eje. Es bueno ver que la civilización está regresando.}
{459}{}{Había leído sobre esta iglesia en los informes de los escribas. El líder ha tenido buenas relaciones con la Hermandad.}
{460}{}{Lo siento, pero eso es información clasificada. No puedo hablarlo contigo.}
{461}{}{No es una mala colonia, pero todavía tienen mucho trabajo por hacer para compararse al orden de la Hermandad.}
{462}{}{Esto no es un refugio. Es una cripta.}
{463}{}{Es un puesto avanzado. Es obvio que no podemos compararlo al cuartel general, pero es mejor que nada.}
{464}{}{Hay mucho que podría contarte, pero ya lo sabes todo, hermano.}
{1464}{}{Hay mucho que podría contarte, pero ya lo sabes todo, hermana.}
{465}{}{Me siento perdido sin la Hermandad. Supongo que tendré que ayudar a la gente como tú.}
{466}{}{Este era el fuerte al que querías llegar. ¿No estás contento?}
{467}{}{Esto es una completa decepción. El cuartel general en California estará furioso una vez que se enteren de cómo están las cosas aquí. La verdad es que no me vendría mal ir a alguno de los asentamientos cercanos junto a ti. Me gustaría despejarme un poco la mente antes de volver a mis deberes.}
{468}{}{¿Todavía te molesta lo que ocurrió en el Infierno, verdad? Lo entiendo.}

#Brotherhood
{470}{}{Háblame sobre tu Hermandad.}
{471}{}{No puedo contarte mucho, hay información que podría contener un valor estratégico.}
{472}{}{En ese caso, dejémoslo ahí.}
{473}{}{¿En dónde está la base principal de la Hermandad?}
{474}{}{Ya veo. Eso era todo lo que quería saber sobre la Hermandad.}
{475}{}{¿En dónde está la base local de la Hermandad?}
{476}{}{En la costa del golfo, en Rocky Point. Pero los locales lo llaman Puerto Peñasco.}
{477}{}{Eso tendrás que preguntárselo al cuartel general. Yo sólo soy un soldado y sigo mis órdenes.}
{478}{}{¿Qué estás haciendo en el desierto de Sonora?}
{479}{}{El cuartel general está lejos, ubicado en California. Aquí, en el desierto Sonorense, tenemos un puesto pequeño.}
{480}{}{No quiero hablar de eso ahora mismo. Nuestra derrota en Puerto... es tan ridículo, sólo me llena de rabia.}
{481}{}{No puedo creerlo...}
{482}{}{¿Estás bien?}
{483}{}{Mis hermanos y hermanas... Sufrieron una muerte tan ridícula... ¿Qué pudo haber pasado?}
{484}{}{Es probable que haya sido un descuido del intendente, o algún tipo de fuga.}
{485}{}{¡Tonterías! ¡Siempre hemos cuidado a nuestro equipamiento y nuestras instalaciones! Me niego a creer que esto fue un error del personal, sólo pudo haber sido sabotaje.}
{486}{}{Bueno, ustedes sí tienen muchos enemigos...}
{487}{}{Bien, perdona por haber gritado. Luego de lo que ocurrió en el Infierno, que la Hermandad haya recibido otro golpe más es demasiado.}
{488}{}{Lo entiendo, pero al menos ahora estás liberado de todas las órdenes y regulaciones, ¿no?}
{489}{}{No creo que pueda tener una vida rural en una tierra así de salvaje. Tenemos que seguir moviéndonos. Mira, seguiré estando a tu lado.}
{490}{}{Vámonos.}
{491}{}{Parece que a alguien no le gustaba tu Hermandad para nada.}
{492}{}{¡Exacto! Esto sólo pudo haber sido sabotaje.}
{493}{}{Hice explotar un par de torpedos ahí adentro. ¿Cuál es el problema?}
{1493}{}{Hice explotar un par de torpedos ahí adentro. ¿Cuál es el problema?}
{494}{}{¿¡Por qué!? ¿¡Qué te ha hecho la Hermandad!?}
{495}{}{Le han causado demasiados problemas a toda Sonora, ustedes no tienen lugar aquí.}
{496}{}{La verdad, ni yo lo sé. Sólo quería ver una explosión.}
{497}{}{Creo que presioné el botón equivocado. No sabía que esto pasaría.}
{1497}{}{Creo que presioné el botón equivocado. No sabía que esto pasaría.}
{498}{}{¡Estás demente, paleto de mierda! ¡Deberías haber nacido tieso!}
{1498}{}{¡Estás demente, paleta de mierda! ¡Deberías haber nacido tieso!}
{499}{}{Sí, sí...}
