{102}{}{ recibe una chapa de botella.}
{103}{}{Este objeto no te será de ayuda con esto.}
{104}{}{Esto no te será de ayuda}
{105}{}{Esa habilidad no te será de ayuda con esto.}
{106}{}{Esta persona se rehúsa a ir más lejos.}
{107}{}{Esta criatura se rehúsa a ir más lejos.}
{108}{}{Esta persona hostil se rehúsa a obedecerte.}
{109}{}{Esta criatura hostil se rehúsa a obedecerte.}

#----------------------------------------------
# Names of skills and basic parameters
#----------------------------------------------
{110}{}{Armas pequeñas}
{111}{}{Armas grandes}
{112}{}{Armas de energía}
{113}{}{Desarmado}
{114}{}{Armas melee}
{115}{}{Armas arrojadizas}
{116}{}{Primeros auxilios}
{117}{}{Doctor}
{118}{}{Sigilo}
{119}{}{Ganzúa}
{120}{}{Robar}
{121}{}{Trampas}
{122}{}{Ciencia}
{123}{}{Reparar}
{124}{}{Conversación}
{125}{}{Trueque}
{126}{}{Apostar}
{127}{}{Supervivencia}

{130}{}{Tu habilidad de }
{131}{}{ ha incrementado }
{132}{}{ puntos.}

{133}{}{[}
{134}{}{] }

{135}{}{Reacción}
{136}{}{Reputación}
{137}{}{Karma}
{138}{}{Nivel}

{140}{}{}
{141}{}{No es posible hacer eso con tus habilidades.}
{142}{}{No es posible robarle a esta criatura.}
{143}{}{El objetivo no consiguió ver tu trampa. Escapaste sin consecuencias.}
{144}{}{Pudiste convencer al objetivo de que fue un malentendido.}
{145}{}{No es posible robarle a un robot mientras está activo.}
{146}{}{ te está observando muy de cerca.}
{147}{}{Tus habilidades no serán suficientes para curar esta herida, necesitas suministros médicos.}
{148}{}{No puedes robar si llevas puesta una servoarmadura.}
{149}{}{Es imposible hacer eso.}

{150}{}{Fuerza}
{151}{}{Percepción}
{152}{}{Resistencia}
{153}{}{Carisma}
{154}{}{Inteligencia}
{155}{}{Agilidad}
{156}{}{Suerte}

#----------------------------------------------
# Gaining experience
#----------------------------------------------

{200}{}{Has obtenido }
{201}{}{ puntos de experiencia.}
{202}{}{ puntos de experiencia por un diálogo exitoso.}
{203}{}{ puntos de experiencia y una mejora a tu reputación.}

#----------------------------------------------
#Injuries?
#----------------------------------------------

{300}{}{¡Tu pierna izquierda fue lisiada! Sufres un dolor intenso.}
{301}{}{¡Tu pierna derecha fue lisiada! Sufres un dolor intenso.}
{302}{}{¡Tu brazo izquierdo fue lisiado! Sufres un dolor intenso.}
{303}{}{¡Tu mano derecha fue lisiada! Sufres un dolor intenso.}
{304}{}{¡Tus ojos han sido lisiados! Sufres un dolor intenso.}
{305}{}{Agh, esto va a tardar mucho en curarse...}

#----------------------------------------------
# Messages in battle
#----------------------------------------------

{320}{}{ tiene dudas acerca de atacar.}
{321}{}{ se regenera y recupera algo de salud.}
{322}{}{!!!}
{323}{}{El fuego aterra a }
{324}{}{ y escapa.}
{325}{}{¡Demonios!}
{326}{}{ pierde fuerza y percepción debido a que el pulso electromagnético dejó fritas algunas de sus partes.}
{327}{}{!}
{328}{}{No es posible hacer esto durante el combate.}
{329}{}{¡Peep!}

#----------------------------------------------
# Comments about ineffectiveness (using the wrong item, skill, etc. )
#----------------------------------------------

{330}{}{Esto es inútil}
{331}{}{Eso no sirve}
{332}{}{Algo anda mal}
{333}{}{Nada}
{334}{}{No puedo hacerlo}
{335}{}{¿Hmm?}
{336}{}{Es demasiado difícil}
{337}{}{Esto es inútil}
{338}{}{Esto es inútil}
{339}{}{Esto es inútil}

#----------------------------------------------
# Replies upon completion of tasks ( clearing mines, repairs, refueling the bike, etc.)
#----------------------------------------------

{340}{}{Hecho}
{341}{}{Bien}
{342}{}{Genial}
{343}{}{Hecho}
{344}{}{Lo tengo}
{345}{}{Tuve éxito}
{346}{}{Bien}
{347}{}{Hecho}
{348}{}{Hecho}
{349}{}{Hecho}

#----------------------------------------------
# Using different items on NPCs
#----------------------------------------------

# Consumables
{400}{}{ se rehúsa a comer eso.}
{401}{}{Esta experiencia te ha dado una lección.}
{402}{}{ no puede comer durante el combate.}
{403}{}{ se rehúsa a tomar eso.}
{404}{}{Esto no aplica a los robots.}
{405}{}{Entregar comida gratis te ha otorgado experiencia y karma.}
{406}{}{Esto no aplica a las plantas.}
{407}{}{ se rehúsa a aceptar eso.}
{408}{}{Esta criatura se ha hecho más amistosa contigo.}
{409}{}{Los estimulantes afectan únicamente a los humanos.}
{410}{}{Los animales y los mutantes no beben alcohol.}
{411}{}{Esto no afectará a un nómada.}
{412}{}{ sucumbe a los efectos nocivos de la sustancia química y entra en cólera.}
{413}{}{¿Alcohol? No me interesa...}
{414}{}{¡Eso era justo lo que me faltaba!}
{415}{}{A los miembros de la Hermandad no les gusta que les muestres sus propias raciones. Quizás piensen que eres un ladrón.}
{416}{}{¡Santo cielo, cuánta generosidad!}
{417}{}{¿En serio me quieres dar esto?}
{418}{}{Este objeto no funcionará a través de un casco de servoarmadura.}
{419}{}{La distribución gratis de este valioso líquido te otorgó experiencia y karma.}

# Items of clutter
{420}{}{Creo que esto me vendrá bien}
{421}{}{¡Santo cielo! ¡Gracias!}
{422}{}{El niño felizmente acepta tu regalo. Puede que le cuente a sus amigos sobre ti.}
{423}{}{El niño no quiere aceptar tu regalo, parece ser que piensa que eres una amenaza.}
{424}{}{La pala no te ayudará con esto, para nada.}
{425}{}{Un decodificador no te ayudará a piratear el robot, sólo hará falta tu habilidad.}
{426}{}{ ha recibido una dosis de veneno.}
{427}{}{ muere debido a una convulsión terrible.}
{428}{}{ fallece y cae al piso.}
{429}{}{ queda inconsciente y muere un momento después.}
{430}{}{ deja de respirar.}
{431}{}{No es posible hacer esto durante el combate.}
{432}{}{Tu compañero sabe lo que esto significa.}
{433}{}{¡Ooooh!}
{434}{}{No tienes por qué estar asustando al niño, debe haber un propósito más digno para este trofeo.}
{435}{}{Has fabricado 20 bengalas a partir de los cuetes viejos.}

# Items of ammunition
{440}{}{}
{441}{}{}
{442}{}{}
{443}{}{}
{444}{}{}
{445}{}{}
{446}{}{}
{447}{}{}
{448}{}{}
{449}{}{}
{450}{}{}
{451}{}{}
{452}{}{}
{453}{}{}
{454}{}{}
{455}{}{}
{456}{}{}
{457}{}{}
{458}{}{}
{459}{}{}

# Ammunition items
{460}{}{}
{461}{}{}
{462}{}{}
{463}{}{}
{464}{}{}
{465}{}{}
{466}{}{}
{467}{}{}
{468}{}{}
{469}{}{}
{470}{}{}
{471}{}{}
{472}{}{}
{473}{}{}
{474}{}{}
{475}{}{}
{476}{}{}
{477}{}{}
{478}{}{}
{479}{}{}

# Other items
{480}{}{Lo normal es utilizar una llave en una cerradura.}
{481}{}{Increíble. Y tan pronto como se te ocurrió...}
{482}{}{El arma debe ser utilizada en el modo de combate, mientras la sostienes en tu arma.}
{483}{}{Al utilizar la bolsa de doctor, has curado todas tus heridas.}
{484}{}{Utiliza una bolsa de doctor para curar las heridas del paciente.}
{485}{}{Debes colocar este objeto en tu mano para utilizarlo.}
{486}{}{Es poco probable que esto te ayude a reparar al robot.}
{487}{}{ se rehúsa a que tu tratamiento.}
{488}{}{No necesitas cirugía.}
{489}{}{Debes usar este objeto en una motocicleta.}
{490}{}{Eso no te ayudará con esto.}
{491}{}{Has encontrado un uso para una reliquia antigua.}
{492}{}{La pala ya no funciona.}
{493}{}{La bolsa de doctor no te ayudará con esto.}

#----------------------------------------------
# Dialogue options
#----------------------------------------------

#Critter
{500}{}{Esta persona es hostil y no hablará contigo.}
{501}{}{Ya has programado a este robot para que te proteja.}
{502}{}{Has programado a este robot para que te proteja.}
{503}{}{}
{504}{}{Eres incapaz de reprogramar al robot para que te proteja.}
{505}{}{¿Qué estás haciendo? ¿Me estás amenazando?}
{506}{}{Esta persona no hablará contigo mientras sostengas un arma.}
{507}{}{Este hombre se está muriendo, no puede hablar contigo.}
{508}{}{. . .}
{509}{}{La negociación ha fracasado.}
{510}{}{?}
{511}{}{Ves a un lugareño enloquecido.}
{512}{}{Se ha acabado el oxígeno y }
{513}{}{ se está asfixiando en el congelador.}
{514}{}{¿Qué estás haciendo? ¿Me estás amenazando?}
{515}{}{Enfunda tu arma o desenfundo la mía}
{516}{}{Esta persona no hablará contigo mientras utilices una servoarmadura.}
{517}{}{...}
{518}{}{Parece que este robot no puede hablar.}
{519}{}{Esta persona se rehúsa a ayudarte.}

# Computers
{550}{}{Acceso denegado.}
{551}{}{No es posible hacer eso durante el combate.}
{552}{}{El sistema de seguridad ya fue pirateado.}
{553}{}{¡El sistema de seguridad ha sido pirateado!}
{554}{}{Acceso concedido.}
{555}{}{El juego resultó ser muy emocionante.}
{556}{}{No consigues adivinar la contraseña.}
{557}{}{Has instalado un decodificador. Ahora será mucho más fácil piratear la computadora.}
{558}{}{Colocar otro codificador no te ayudará, es hora de usar tus habilidades.}
{559}{}{}

#Equipment repair
{570}{}{ no necesita ninguna reparación.}
{571}{}{No es posible hacer esto durante el combate.}
{572}{}{}
{573}{}{No tienes la menor idea de cómo arreglar esto. Quizás podrías compensar tu falta de habilidad al agregar partes de repuesto.}  
{574}{}{No tienes idea de cómo arreglar esto.}
{575}{}{¡Que mala suerte! Te electrocutaste.}
{576}{}{Estas partes harán que reparar esto sea un poco más fácil.}
{577}{}{Estas partes harán que reparar esto sea mucho más fácil.}
{578}{}{Colocar más repuestos no te ayudará. Usa tus habilidades.}
{579}{}{Ves a un Segador.}

#----------------------------------------------
# Nicknames for the ring
#----------------------------------------------

#Important: male and female nicknames are antipodes and coincide in numbers with a difference of 50.
#- men's
{600}{}{Crusado}
{601}{}{Escorpión}
{602}{}{Caníbal}
{603}{}{Rey}
{604}{}{César}
{605}{}{Hidalgo}
{606}{}{Sargento}
{607}{}{Colmillo}
{608}{}{Mazo}
{609}{}{Dinamita}
{610}{}{Fumador}
{611}{}{Hulk}
{612}{}{Francotirador}
{613}{}{Macho}
{614}{}{Mr. X}
{615}{}{Gran Hermano}
{616}{}{Perro Rabioso}
{617}{}{Fiasco}
{618}{}{Segador}
{619}{}{Carnicero}
{620}{}{Duende}
{621}{}{Susurro}

#- women's
{650}{}{Viuda Negra}
{651}{}{Ciempiés}
{652}{}{Comecerebros}
{653}{}{Reina}
{654}{}{Cleopatra}
{655}{}{Duquesa}
{656}{}{Sargenta}
{657}{}{Garras}
{658}{}{Machete}
{659}{}{Mágnum}
{660}{}{Napalm}
{661}{}{Ross}
{662}{}{Marina}
{663}{}{Muchacha}
{664}{}{Srita. X}
{665}{}{Mamasota}
{666}{}{Perra Loca}
{667}{}{Chica Mala}
{668}{}{Ángel}
{669}{}{Jane la Loca}
{670}{}{Blancanieves}
{671}{}{Rubí}

#----------------------------------------------
# Cartography
#----------------------------------------------

{1400}{}{Se ha revelado una nueva localización en el mapa}
{1401}{}{: }
{1402}{}{.}
{1403}{}{Provienen ruidos sospechosos de la caverna.}

# Attention! The list should be copied unchanged from the file.../game/MAP.MSG
{1500}{}{La Villa}
{1501}{}{Flagstaff}
{1502}{}{Ciudad Garaje}
{1503}{}{San Brahman}
{1504}{}{Two-Sun}
{1505}{}{Puerto}
{1506}{}{Rangers}
{1507}{}{Fenix}
{1508}{}{El Faro}
{1509}{}{Casa Grande}
{1510}{}{Hermosillo}
{1511}{}{San Felipe}
{1512}{}{Infierno}
{1513}{}{Casa Nueva}
{1514}{}{-}
{1515}{}{Motel}
{1516}{}{Dayglow}
{1517}{}{Base Naval de EE.UU}
{1518}{}{Santa Ana}
{1519}{}{-}
{1520}{}{Chacales}
{1521}{}{Motocicleta sin gasolina}
{1522}{}{La Villa}
{1523}{}{Refugio 27}
{1524}{}{Campamento de la Hermandad}
{1525}{}{Escudos Azules}
{1526}{}{Yermo}
{1527}{}{Montes}
{1528}{}{Ruinas}
{1529}{}{Costa}
{1530}{}{Puerto}
{1531}{}{Oro}
{1532}{}{Henry Bemis}
{1533}{}{Cafeteria}
{1534}{}{Bombardero}
{1535}{}{Camion de Petro-Chico}
{1536}{}{El Grito del Silencio}
{1537}{}{Cine al aire libre}
{1538}{}{El Padre}
{1539}{}{Punto de Reunion}
{1540}{}{Una nevada}
{1541}{}{El Santuario Perdido}
{1542}{}{Fortaleza Movil}
{1543}{}{Legend City}
{1544}{}{-}
{1545}{}{-}
{1546}{}{Quartzsite}
{1547}{}{Encuentro aleatorio}
{1548}{}{Campamento Winon}
