{100}{}{Ves una computadora.}
{101}{}{Estás viendo una antigua computadora. Es sorprendente que siga funcionando.}

**#Dialogue**
{200}{}{Se ha cargado el sistema.}
{201}{}{Cerrar sesión}
{202}{}{Regresar}
{203}{}{Bienvenido a los archivos electrónicos de la Policía Municipal de Mexicali.}
{204}{}{Cargando la base de datos...}

{210}{}{Ataque en el supermercado}
{211}{}{"...Lo conoces hace mucho tiempo. ¿Qué crees que causó esto?"}
{212}{}{[Siguiente]}
{213}{}{"¿Qué puedo decir? Es un veterano, ya sabes lo horroroso que fue Anchorage. Él sirvió y lo condecoraron por eso, pero no le quitó el trauma de la cabeza."}
{214}{}{[Siguiente]}
{215}{}{"¿Te refieres a una herida o algo así?"}
{216}{}{[Siguiente]}
{217}{}{"¡No, no, perdió la cabeza! Él empezó a dispararles por tu culpa. En su cabeza, todavía estaba en la guerra, pensó que le estaba disparando a los Rojos..."}
{218}{}{[Detén la grabación]}

{220}{}{Quejas acerca de una construcción}
{221}{}{"¡Te estoy diciendo que los planos están dentro de la ley, no infringe nada! ¿Y cómo te pueden probar los vecinos que invadí su propiedad durante la excavación?"}
{222}{}{[Siguiente]}
{223}{}{"Supongamos que lo que dices es cierto. ¿Pero qué hay del ruido que haces con la construcción? No los dejas dormir. ¿Y qué hay del polvo, los vidrios rotos y los camiones que siempre van y vienen? También nos han dicho que usas trabajadores que no están licenciados."}
{224}{}{[Siguiente]}
{225}{}{"Es un proyecto caro... ¿¡Qué acaso no lo entiendes!? ¡Cuando empiece la guerra mundial, que sé que lo hará, a nadie le importará el ruido o los camiones! Estoy construyendo un refugio para mí y mi familia. ¿Y qué van a hacer los vecinos en ese entonces? Claro, vendrán corriendo conmigo. Ya lo verá, oficial..."}
{226}{}{[Detén la grabación]}

{230}{}{Quejas acerca de amenazas}
{231}{}{"...Señora, por favor, cálmese..."}
{232}{}{[Siguiente]}
{233}{}{"¿Calmarme? ¡Sí, claro, esos animales me quieren muerta! Hace tiempo que los vecinos me quieren correr de la ciudad, los he aguantado durante años. ¡Pero ya se pasaron de la raya! Yo he pagado mucho dinero por mi casa y no dejaré que me acusen de estar compinchada a los Rojos sólo porque tengo sangre china. ¡Hagan algo, son la policía!"}
{234}{}{[Siguiente]}
{235}{}{"Claro, señora, pero... Entienda que la evidencia no es suficiente para acusar a sus vecinos. Un gato muerto, notas anónimas y grafitis en su pared - nada de esto indica que de verdad está en peligro. No podemos..."}
{236}{}{[Siguiente]}
{237}{}{"¿¡Por qué pierdo el tiempo contigo!? ¡Es obvio que ustedes igual están de su lado! Dame mi declaración, me voy..."}
{238}{}{[Siguiente]}
{239}{}{"Mierda... Es una perra. Ya es la tercera vez que pasa en el mes. ¿Qué piensas tú, Rodrigo? ¿De verdad será una de 'ellos'?"}
{240}{}{[Siguiente]}
{241}{}{"Déjala ir, Nick. Es mejor que se vuelva loca a que de verdad tenga lazos con los Rojos... Ah, carajo, no apagué la grabadora..."}
{242}{}{[Detén la grabación]}

{250}{}{Respecto al nopal}
{251}{}{"A ver, chicos. Cuénteme lo que pasó. Digan la verdad."}
{252}{}{[Siguiente]}
{253}{}{"Pues, sólo estábamos andando por el desierto y nos sentamos cerca de un nopal. ¡Y entonces se le cayó encima a Paco! ¡No hicimos nada malo, se lo juro, señor!"}
{254}{}{[Siguiente]}
{255}{}{"Hm. La base del nopal estaba chamuscada por los disparos de una pistola láser. (silencio) Chicos, no quiero presionarlos, sólo quiero ayudar. Digan la verdad y lo único que recibirán sera una advertencia. (silencio) Si así lo quieres, vamos a recordar lo que pasó."}
{256}{}{[Siguiente]}
{257}{}{"Paco se llevó la pistola láser de su papá sin permiso. Luego decidieron usarla en un nopal. ¿Eso pasó, cierto? (silencio) Resulta que era más fuerte de lo que pensabas y se le acabó la carga a la pistola, entonces decidiste tirarlo abajo con las manos. (silencio) Chicos, dispararle a los cactus está prohibido en este estado, sin mencionar que usaron un arma..."}
{258}{}{[Siguiente]}
{259}{}{"¡Señor, señor! ¡No le diga a nuestros papás!"}
{260}{}{[Detén la grabación]}

{270}{}{Respecto al robot}
{271}{}{"¿...Entonces, según tú, el robot no tenía defectos y actuó por sí mismo?"}
{272}{}{[Siguiente]}
{273}{}{"Me temo que no es del todo así, señor... Los Señores Mañosos sólo se encarga de tareas que se le asignan. ¡Pero usted vea las peticiones de la familia Wilson! Me parece que tenían... problemas familiares."}
{274}{}{[Siguiente]}
{275}{}{"¿Problemas? Sí, sabemos que tenían peleas constantes dentro de su familia. ¿Pero cómo va a afectar eso a un robot que sólo se encarga de tareas 'que se le asignan'?"}
{276}{}{[Siguiente]}
{277}{}{"Pues... El interpretador del robot no es perfecto. Y si la mamá amenazó con 'rebanar' a su hijo, y el hijo le pidió al robot que 'cocine' a sus padres, puede que haya habido un malentendido..."}
{278}{}{[Siguiente]}
{279}{}{"¿Siquiera entiendes lo que estás diciendo? Tu centro de mantenimiento revisa a robots que están programados para no dañar a los humanos. Y ahora esos mismos robots, según tú, 'malentendieron' lo ordenado. ¡Deja de intentar engañarnos! ¡Admite que fue un defecto y estarás menos tiempo entre rejas!"}
{280}{}{[Detén la grabación]}

{290}{}{Protesta Anti-Americana}
{291}{}{"¿Estás admitiendo que fuiste parte de una manifestación ilegal en donde se buscaba derrocar al gobierno actual? Por lo tanto, eres culpable."}
{292}{}{[Siguiente]}
{293}{}{"¿Culpable? ¡De qué chingados hablas! ¡Los americanos tienen de esclavos a toda Sonora! ¡Los criminales son ellos, junto al gobierno corrupto que tenemos! Era una manifestación, ¿cómo vas a decir que es ilegal?"}
{294}{}{[Siguiente]}
{295}{}{"A ver, te lo vuelvo a repetir..."}
{296}{}{[Siguiente]}
{297}{}{"¡México para los Mexicanos! ¡México para los Mexicanos!"}
{298}{}{[Siguiente]}
{299}{}{"¡Basta, silencio! ¡Cállense!"}
{300}{}{[Siguiente]}
{301}{}{"¿Qué, nos vas a arrestar?" - "¡Queremos un abogado!" - "¿Y para esto pagamos impuestos?" - "Cuando teníamos a Madera en el cargo, los Americanos no se metían con nosotros..." - "¿Acaso ya te olvidaste de la masacre que hubo en la frontera?" - "¡México para los Mexicanos!"}
{302}{}{[Detén la grabación]}
