{100}{}{Ves a un salvaje.}
{101}{}{Ves a uno de los machos de la tribu Chacal. Sus ojos arden como la mirada de un lobo.}
{102}{}{ }

#Replicas floating
{120}{}{Cuando tengo hambre, le aúllo a la luna.}
{121}{}{Es un hermoso día, deberíamos sacrificar a alguien.}
{122}{}{Apenas tienes pelaje.}
{123}{}{¡Shh, deja de ladrar! El forastero nos oye...}
{124}{}{Los parásitos en mis intestinos no me dejan dormir.}
{125}{}{¡Esa perra será mía!}
{126}{}{*Olfatea*}
{127}{}{*Se rasca detrás de las orejas con la pata*}
{128}{}{Hay que reponer la carnada de las trampas.}
{129}{}{Debo afilar mis colmillos.}

#Response
{200}{}{*Te enseña los dientes*}
{201}{}{Cuando te mueras, te arrancaré la carne de los huesos.}
{202}{}{Mis colmillos quieren probar tu sangre.}
{203}{}{Me comeré tu cerebro cuando te mueras.}

{205}{}{Si te mato, seré famoso y me respetarán más.}
{206}{}{¿Buscas la muerte, forastero?}
{207}{}{Mmm, te ves jugoso.}

{1205}{}{Si te mato, seré famoso y me respetarán más.}
{1206}{}{¿Buscas la muerte, perra?}
{1207}{}{Mmm, te ves jugosa, perra.}

{210}{}{M-mi vida te pertenece.}
{211}{}{*Quejido penoso*}

