{100}{}{Ves a un saqueador.}
{101}{}{Ves a un saqueador, está preparado para el asalto.}
{102}{}{Fue un buen ataque, ¿no crees?}

#Response
{200}{}{Llegó el momento. ¿Estás con nosotros?}
{201}{}{¿Algún consejo antes de que empecemos?}
{202}{}{Los Chacales son débiles, no necesitamos armamento pesado. Pero son muchos y nos atacarán en grupo en los pasillos estrechos de su madriguera. Sería bueno lanzar una granda o simplemente usar una escopeta.}
{203}{}{Claro, vamos.}
{204}{}{Vamos.}
{205}{}{¿Qué más?}
{206}{}{Ten cuidado con sus garras y especialmente sus cuchillos, pues los envenenan. También necesitaremos luz ahí dentro. Deberían haber antorchas en los túneles, valdrá la pena encontrarlas y encenderlas.}
{207}{}{No es un buen momento para hablar. Vámonos.}
{208}{}{No esperaba ver a un ranger aquí dentro. Parece que no son tan fuertes como parecen.}
{209}{}{}
{210}{}{Parece que esos fueron los últimos. Solo falta registrar los cadáveres e irnos a casa.}
{211}{}{Bien.}
{212}{}{[Más]}
