{110}{}{Es un tótem tribal hecho con cráneos, los salvajes consideran que es "espiritual". Puede que tu opinión sea distinta a la suya.}
{111}{}{Has destruido el tótem. Quizás haya algo útil en ese montón de basura.}

{130}{}{}
{131}{}{¿No temes que esto enojará a los salvajes?}
{132}{}{}
{133}{}{Es parte de su 'cultura'. ¿Por qué molestarse con esto?}
{134}{}{}
{135}{}{}
{136}{}{¡Ja! Imagina la cara que los salvajes pondrán al ver esto.}