{100}{}{Ves a un hombre oriundo de Fénix.}
{101}{}{Ves a un hombre de ropa polvorienta, sus manos están llenas de tierra.}
{102}{}{Hola.}

{200}{}{Qué sorpresa. Sabíamos que por aquí pasaban viajeros, pero no esperaba que llegara alguien tan pronto.}
{201}{}{¿Eres nuevo aquí?}
{202}{}{Sí, nos mudamos hace poco. Si quieres un lugar en donde dormir - lo siento, estamos llenos.}
{203}{}{No, sólo quiero hablar.}
{204}{}{¿Dormir aquí adentro? Preferiría dormir bajo las estrellas.}
{205}{}{Sí, nos mudamos hace poco. Si quieres dormir aquí, lo siento, estamos llenos. Pero, estaría bien conversar un poco.}

{210}{}{No tenemos ninguna habitación libre, pero estaría bien conversar un poco.}
{211}{}{¿De dónde eres?}
{212}{}{Somos de Fénix, nos mudamos aquí para empezar una nueva comunidad. El mismísimo Aaron nos dio la propiedad.}
{213}{}{¿Qué hiciste para ganarte eso?}
{214}{}{Nos esforzamos por la gloria de Sus ideas. Además, Aaron busca colonizar el área alrededor de Fénix, así estarán bajo su mando.}
{215}{}{¿Puedes probar eso?}
{216}{}{Tenemos el documento que nos entregaron, debido a nuestra labor en honor a las ideas de Aaron. ¿Por qué dudas de nosotros?}
{217}{}{¿Y cuándo obtuvo el derecho de proclamar el motel como suyo?}
{218}{}{Sólo Aaron controla las tierras alrededor de Fénix. Desafíalo, si te atreves.}
{219}{}{Eso no es verdad.}
{220}{}{¿Cómo osas a profanar el nombre de un hombre santo? Cierra tu mugrosa boca antes de que pierda la paciencia. ¡Fuera!}
{221}{}{Ya, ya...}
{222}{}{Oye, cálmate...}
{223}{}{Está haciendo un gran trabajo.}
{224}{}{¡Alabado sea el nombre de Aaron! El hombre que trajo la vida al desierto.}
{225}{}{Aaron está muerto. ¿Lo sabías?}
{226}{}{La catedral fue destruida, igual que Aaron. ¿Sabías eso?}
{227}{}{¿Cómo te atreves a mentir así? Aaron está vivo, y su Catedral sigue en pie. Cierra la boca, o perderé la paciencia.}
{228}{}{Lo que más les ofende es la verdad...}
{229}{}{Oye, cálmate...}

{230}{}{¿Sabías que aquí vivían unos mutantes?}
{231}{}{Pasó lo que pasó. Tenemos que empezar de nuevo, y dejar el pasado atrás de nosotros.}
{232}{}{¿Y vivirás aquí así como así? ¿Aún teniendo en cuenta los horrores que vio este motel?}
{233}{}{Los mutantes eran caníbales y unos enfermos, pero mantuvieron el hotel en buen estado. Es por eso que vinimos aquí, es el único lugar decente para vivir.}
{234}{}{¿Le hacían manutención al motel? ¿En serio?}
{235}{}{Repararon el techo y el cercado, fertilizaron los cultivos, e instalaron tanques de agua - es un lugar maravilloso en donde empezar una nueva vida.}
{236}{}{Así que viniste a aprovecharte del trabajo de otro.}
{237}{}{Creo que deberías irte.}
{238}{}{Sí, tengo que irme. Adiós.}
{239}{}{Que maleducado. Ahora sí que no quiero quedarme.}
{240}{}{Al menos este motel por fin será usado para el bien.}
{241}{}{Ahora todo será distinto. Aaron nos dio una segunda oportunidad, tanto a nosotros como al hotel. Pronto este desierto será una tierra prometida.}
{242}{}{Amén.}
{243}{}{Buena suerte.}

{250}{}{Aaron y su catedral han caído. Lo sabes, ¿verdad?}
{251}{}{¿¡Cómo te atreves a difundir tal mentira!? Es obvio que Aaron aún lidera a su iglesia, ¡la cual sigue prosperando! Cierra tu sucia boca, antes de que pierda la paciencia.}