{100}{}{Ves a Chuck.}
{101}{}{Ves a uno de los Escudos Azules.}
{102}{}{Hola, ¿cómo estás?}

{200}{}{Hola, soy Chuck. Es la primera vez que te veo. ¿Cómo te llamas?}
{201}{}{No necesitas saber eso.}
{202}{}{¿En serio? Pues, lo que tú digas, pero no sé por qué tanto secreto.}
{203}{}{Eres demasiado amable como para encajar con los demás. ¿No crees?}
{204}{}{Sí, tienes razón. Soy un novato, apenas sé lo básico, ni siquiera me han iniciado.}
{205}{}{¿A qué te refieres con la 'iniciación'?}
{206}{}{Soy }
{207}{}{ , acabo de unirme.}
{208}{}{Ah, así que también eres nuevo. Por fin, ya no soy el único. Es un gusto conocerte. ¿Ya estás iniciado?}
{1208}{}{Ah, así que también eres nueva. Por fin, ya no soy el único. Es un gusto conocerte. ¿Ya estás iniciada?}
{209}{}{¿De qué se trata esa 'iniciación'?}
{210}{}{Ah, hola. Como ves, estoy entrenando... Quiero ser igual de fuerte que tú.}
{211}{}{Si quieres quitarme mi lugar con Ben, es demasiado tarde.}
{212}{}{No, ni siquiera te llego a los talones. Por eso estoy entrenando, para la iniciación.}
{213}{}{¿Iniciación?}
{214}{}{Tengo que pasar por una ceremonia de iniciación para demostrarle a la banda lo que valgo. Me dijeron que me darán una golpiza en grupo para ver si me aguanto. Pero no creo que se detengan.}
{215}{}{¿Te molesta?}
{216}{}{Claro, no estoy seguro de mi fuerza o resistencia. Puede que me maten.}
{217}{}{¿Entonces por qué sigues preparándote?}
{218}{}{No tengo otra opción, desde que el alcalde de Casa Grande mató a la mitad del pueblo, me acusó de ser un traidor y puso una recompensa por mi cabeza. Ben es el único que quiso aceptarme.}
{219}{}{Buena suerte con tu entrenamiento.}

{220}{}{Hola, ¿qué tal?}
{221}{}{Adiós.}
{222}{}{Puedo ayudarte con tu prueba.}
{223}{}{¿En serio? ¿Cómo?}
{224}{}{He escuchado que las drogas de la preguerra pueden aliviar el dolor.}
{225}{}{Sí, eso pensé. El Psico sería perfecto para aguantar la golpiza, pero además de ser raro de encontrar, es caro. ¿Podrías traerme una dosis?}
{226}{}{Por supuesto, pero necesitaré un tiempo.}
{227}{}{Genial. Te estaré esperando.}
{228}{}{Adiós.}
{229}{}{No, lo siento, no tengo nada.}
{230}{}{Que pena. Sé que podrías comprar el Psico en Fénix. Yo no puedo ir, los matones de allá tienen permiso de capturarme.}
{231}{}{Entiendo. Si encuentro Psico, te lo traeré.}
{232}{}{No deberías meterte a una banda. Quiero ayudarte a limpiar tu nombre.}
{233}{}{¿Has pensado en limpiar tu nombre y quebrar el contrato de los cazarrecompensas?}
{234}{}{Mierda, te lo agradecería de por vida. El contrato se encuentra en Fénix, y el cliente es el alcalde de Casa Grande.}
{235}{}{Eso suena difícil. Creo que sería más fácil conseguirte unas drogas para que aguantes el dolor.}
{236}{}{¿Has pensado en limpiar tu nombre y volver a una vida normal?}
{237}{}{Te conseguí un poco de Psico.}
{1237}{}{Te conseguí un poco de Psico.}
{238}{}{Esta dosis será suficiente para la ceremonia. Gracias, amigo. ¿Qué habría hecho sin ti?}
{1238}{}{Esta dosis será suficiente para la ceremonia. Gracias, amiga. ¿Qué habría hecho sin ti?}
{239}{}{Es un favor por un favor. Recuérdalo, aquí, tu verdadero amigo soy yo.}
{1239}{}{Es un favor por un favor. Recuérdalo, aquí, tu verdadera amiga soy yo.}
{240}{}{Todos los cargos contra ti han sido retirados. Eres libre.}
{241}{}{¿Lo dices en serio? ¿Puedo volver a la ciudad y vivir como una persona normal?}
{242}{}{Adiós, Chuck.}
{243}{}{Ya no tendrás que meterte con criminales.}
{244}{}{Veré que puedo hacer. Adiós.}
{245}{}{¿Por qué sigues entrenando? Podrías morir.}
{246}{}{El Alcalde Bustos ha muerto, lo que quiere decir que su contrato está nulo.}
{247}{}{¿En serio? No puede ser. ¿Así que puedo volver a la ciudad y tener una vida normal?}
{248}{}{¿Qué tal te va con tu entrenamiento para la iniciación?}
{249}{}{No sé lo que me espera. Dicen que la banda entera me dará una golpiza para probar mi resistencia. Estoy asustado. ¿Y si no lo aguanto?}
{250}{}{Ya veo.}
{251}{}{Cuéntame de ti.}
{252}{}{Solía vivir con mis padres en Casa Grande. Ellos pertenecían al clan que controlaba la bomba de agua. Pero el Alcalde Bustos se apoderó de la ciudad y capturó la bomba, matando a todos los que se resistieran.}
{253}{}{¿Cómo sobreviviste?}
{254}{}{Pude huir justo a tiempo, luego descubrí que me estaban buscando por ser un 'traidor'. Así que viajé mucho, busqué entre las ruinas, sólo quería un nuevo hogar. Por suerte, Ben me dejó entrar a la banda.}
{255}{}{Eso es muy triste.}
{256}{}{Dadas las circunstancias, podrías dudar de cualquier historia que te cuenten aquí dentro.}
{257}{}{Exactamente, Chuck.}
{258}{}{¡Gracias! Toma, es un estimulante. Iba a usarlo durante la ceremonia, pero ya no lo necesitaré. (mira a su alrededor y baja la voz) Pero no le digas a nadie que escaparé.}
