{100}{}{Ves a Néstor.}
{101}{}{Estás viendo a un hombre alto y rubio vestido con una túnica inmaculada. Sus gafas están sentadas sobre su nariz y las ajusta delicadamente.}
{102}{}{Por favor, guarda tu arma. No las necesitas en este lugar.}
{103}{}{Por favor, deja tu armadura afuera de la clínica. En este lugar valoramos la limpieza y el orden.}

#First Meeting
{200}{}{Bienvenido, viajero. Hmm. Puedo sentir que debes tener muchas preguntas y peticiones. Déjame clarificarte algo de antemano: esto es una clínica, lugar en el que tratamos a la gente. Yo soy su gerente, mi nombre es Néstor. Y bien, ¿te has enfermado? ¿Estás herido? ¿O acaso buscas aprender más?}
{1200}{}{Bienvenida, viajera. Hmm. Puedo sentir que debes tener muchas preguntas y peticiones. Déjame clarificarte algo de antemano: esto es una clínica, lugar en el que tratamos a la gente. Yo soy su gerente, mi nombre es Néstor. Y bien, ¿te has enfermado? ¿Estás herida? ¿O acaso buscas aprender más?}
{201}{}{Bueno, la verdad es que si tengo algunas preguntas que hacerte.}

#Repeated Meeting
{210}{}{De acuerdo. Te escucho.}
{211}{}{Ya hablamos lo suficiente, tengo que irme.}
{212}{}{Me alegro de volver a verte.}
{213}{}{¿Por qué razón has regresado?}
{1213}{}{¿Por qué razón has regresado?}

#Medicine
{220}{}{Necesito que me cures.}
{221}{}{Oh, lo lamento... Puedo curarte, pero la medicina no es gratis.}
{222}{}{No tengo nada valioso que ofrecer.}
{223}{}{[Curar heridas por }
{224}{}{ chapas]}
{225}{}{[Curar miembros rotos por }
{226}{}{[Curar toda la radiación por }
{227}{}{[Curar todo el envenenamiento por }
{228}{}{¿No tienes nada con qué pagar? Porque parece que eres bien acomodado.}
{229}{}{Lo siento, no quería verte la cara de tonto...}

{230}{}{Espera un momento, ¿te encuentras bien? No parece ser el caso.}
{231}{}{Doctor, me duele... ¡Tengo que dejar mi adicción!}
{1231}{}{Doctor, me duele... ¡Tengo que dejar mi adicción!}
{232}{}{Al verte sufrir, me duele hasta el corazón. Si de verdad QUIERES parar, haré todo lo que esté en mi poder para ayudarte.}
{233}{}{¡Quiero parar! Pero, ¿qué es lo que necesitas para eso?}
{234}{}{La rehabilitación es un proceso largo y caro. Me temo que en este momento, la clínica no puede cubrir los gastos.}
{235}{}{Lo único que hace tu clínica es robarle chapas a la gente. ¡Me voy!}
{236}{}{No tengo que dar. Iré a preguntarle a alguien que de verdad quiera ayudarme.}
{237}{}{Lo entiendo. Voy a pagar }
{238}{}{ chapas. ¿Eso bastará?}
{239}{}{Hmm. No es demasiado, pero qué se puede hacer - hay que salvarte, después de todo.}
{240}{}{Me gustaría ir por un poco de aire fresco antes de empezar. Ya vengo.}
{241}{}{Tengo las chapas. ¿Cuándo empezamos?}
{242}{}{Entre más pronto, mejor. Primero, debes darte un baño.}
{243}{}{¿Un baño? ¡Vaya!}
{244}{}{Has adquirido el extra de Rehabilitación.}
{245}{}{Durante una semana, se te entrenó y trató, has superado tu adicción y serás más fuerte contra las reincidencias.}
{246}{}{La verdad, no necesito ningún tratamiento.}
{247}{}{¿Te sigue doliendo?}
{248}{}{Estoy bien, Doc.}
{249}{}{Sí, gracias, pero quería una última cosa.}

#Dialogue
{250}{}{Habías mencionado la medicina de la preguerra y unos experimentos.}
{251}{}{Ah, sí. Contamos con vacunas para una diversas enfermedades, un procedimiento de la preguerra para mejorar la salud y equipamiento de Vault-Tec que fue utilizado para un entrenamiento especial dentro de los refugios antiaéreos. Pero, ninguno de nosotros ha llevado a cabo el procedimiento de manera seria.}
{252}{}{Eso suena prometedor.}
{253}{}{El problema es su alto costo, tales procedimientos no son esenciales y consumen una gran cantidad de tiempo y recursos. Por lo tanto, la clínica no puede ofrecer esos servicios por cuenta propia.}
{254}{}{¿Cuánto cuesta ese procedimiento de la salud?}
{255}{}{Hmm. Déjame calcular... El costo sería de }
{256}{}{ chapas y necesita diez días de una rutina muy estricta. Es caro, pero tu salud se verá beneficiada.}
{257}{}{Eh, no. Agradezco la oferta, Doc, pero no tengo tantas chapas.}
{258}{}{Me parece bien, Doc. Aquí tengo las chapas.}
{259}{}{Muy bien. Primero, debemos llevar a cabo un examen...}
{260}{}{¡Ay! Eso me da cosquillas...}
{261}{}{Has recibido una bonificación a tus puntos de salud.}
{262}{}{Después de completar el procedimiento, ¡sientes que eres mucho más fuerte!}
{263}{}{¿Puedo tomar el procedimiento otra vez?}
{264}{}{Es posible, pero el efecto no será tan notorio. Esta vez, tendrás que dedicar más tiempo y esfuerzo para lograr un resultado similar.}
{265}{}{¿Cuánto costará?}
{266}{}{Serán }
{267}{}{ chapas y durará dos semanas.}
{268}{}{Ah, eso es demasiado.}
{269}{}{Claro, toma las chapas. ¿Cuándo empezamos?}

### Quest to Clean Up Plantations

{300}{}{Tengo que hablarte acerca de mi amigo, se llama Carlos.}
{301}{}{Por supuesto. ¿Qué ocurre con él?}
{302}{}{Está interesado en la tecnología antigua. ¿Podrías darle un lugar aquí?}
{303}{}{Eso es una oferta interesante. Pero, ¿en dónde está?}
{304}{}{Se encuentra en Two-Sun, está esperando tu respuesta.}
{305}{}{¡Two-Sun! ¿Así que es un... Hojalatero?}
{306}{}{No, no, él es de mi pueblo. Los Hojalateros aceptaron a Carlos debido a sus talentos.}
{307}{}{Pensándolo bien, creo que esto no importa tanto. Disculpa las molestias.}
{308}{}{Ah, eso es interesante. Tienes una buena reputación, así que si él tiene tu recomendación, es suficiente para mí. Dile a tu amigo que lo recibiremos con los brazos abiertos.}
{309}{}{¡Gracias!}
{310}{}{Ah, eso es interesante. Pero, me temo que en este momento no podemos arriesgarnos al aceptar a otro asistente.}
{311}{}{Lo entiendo, supongo que mi reputación no debe ser suficiente para ti.}

{320}{}{Sé sobre la infección que transforma a los campesinos en monstruos.}
{321}{}{Así que estás al tanto...}
{322}{}{No es necesario que suspires profundamente. Esto es cosa tuya, ¿no es así?}
{323}{}{Sí, es nuestro error y cada vez es más difícil ocultarlo. Pero pido que me entiendas - no podemos dejar que cunda el pánico. De por sí es difícil lidiar con los problemas que este pueblo ya posee.}
{324}{}{¿Por qué no declaras una cuarentena?}
{325}{}{¡Eso es impensable! La gente debe cuidar las plantaciones o serán tragadas por las arenas. Y en caso de que escape la población, los saqueadores vendrán aquí y llevarán la infección a otros lugares.}
{326}{}{¿En serio?}
{327}{}{Además, el riesgo de una epidemia general sigue siendo muy bajo. Todas las víctimas se encontraban cerca del laboratorio una vez que ocurrió la fuga. Aunque los insectos también han empezado a propagarla.}
{328}{}{¿El riesgo de verdad es tan bajo?}
{329}{}{No me gusta como suena eso de los insectos.}
{330}{}{No hay por qué entrar en pánico. Ya casi tenemos una solución al problema, pero nos faltan unas piezas del rompecabezas.}
{331}{}{Hmm. No sé si creerte.}
{332}{}{¿Cómo dejaste que esto ocurriera en primer lugar?}
{333}{}{Intentábamos solucionar la escasez alimenticia al crear flora capaz de dar frutos y que fuera lo más resistente posible. La infección es un efecto secundario de los experimentos llevados a cabo en plantas e insectos, lo que fue difícil de predecir.}
{334}{}{Hmm. No sé si creerte.}
{335}{}{¿Vas a corregir tu error?}
{336}{}{Por supuesto. Todo nuestro tiempo libre es dirigido a hacer cálculos y experimentos. Pero todavía nos faltan algunos datos.}
{337}{}{Espero que puedan resolver este problema. Por que si no sería muy malo, para todos.}
{338}{}{Un momento. No vas a crear pánico, ¿cierto? Lo que necesitamos no son problemas, sino ayuda. Si nos prestas tus servicios, te pagaremos muy generosamente.}
{339}{}{¿Qué quieres que haga?}
{340}{}{¿Puedo ayudarte de alguna forma?}
{341}{}{En este momento, necesitamos más ayuda que nunca. Si nos prestas tus servicios, te pagaremos muy generosamente.}
{342}{}{¿Qué puedo hacer para ayudar?}
{343}{}{Nuestro laboratorio está afuera del pueblo y se ha vuelto el foco de propagación de la infección. Allí también hay documentos y algunos reactivos químicos que necesitamos para combatir la infección.}
{344}{}{¿Estás diciendo que vaya hacia allá?}
{345}{}{El laboratorio se encuentra bajo cuarentena y los residentes tienen prohibido acercarse. Sólo Dios sabe qué está pasando allí adentro, pero está la vegetación se ha apoderado del lugar. Hay muchos insectos y puede que todavía haya infectados con vida.}
{346}{}{Pero en ese caso también me estoy arriesgando a infectarme, ¿no?}
{347}{}{Sí. Ese es el mayor problema. Te daremos un antídoto para las mordidas de insecto. Pero las esporas se propagan por el aire, así que necesitarás una máscara de gas. Se las pedimos a los Hojalateros, pero tienen órdenes con más prioridad.}
{348}{}{De acuerdo, te ayudaré.}
{349}{}{Gracias. Cuando te hayas preparado, habla conmigo. Te llevaré al laboratorio sin que los demás residentes se den cuenta.}
{350}{}{Nos vemos.}
{351}{}{Eres igual que esos científicos locos que crearon la bomba nuclear antes de la Guerra. No te ayudaré.}
{352}{}{Lo entiendo, no confías en nosotros y no quieres tomar riesgos. Pero en este momento no importa el culpable; lo que importa es resolver el problema. Piénsalo, le harías un servicio heroico al pueblo, todos te recordarán durante generaciones. Yo seguiré aquí, si cambias de parecer.}
{353}{}{Adiós.}
{354}{}{No tengo claro el cómo utilizar este insecticida.}
{355}{}{Ve hacia la plantación de agave, debes verterlo en el tanque de agua. Eso propagará el insecticida a través de las tuberías de riego a todos los cultivos que estén infectados.}#modified to make sense of in game actions - cambragol
{356}{}{De acuerdo.}
{357}{}{Bueno, eso ya es otra cosa.}

{360}{}{Te ayudaré. ¡Es hora de acabar con esta infección!}
{361}{}{Estoy feliz de oír eso. Puede que no podamos hacerlo sin ti.}
{362}{}{Estoy listo para ir.}
{1362}{}{Estoy lista para ir.}
{363}{}{Espera, necesito ir por un par de cosas. Ya vuelvo.}
{364}{}{Tu misión es la siguiente; debes encontrar documentos del laboratorio y los componentes para crear un insecticida que se encontraba en desarrollo. Entre más rápido lo consigas, habrá menos probabilidad de que te afecte la infección. Llévate un antídoto y un estimulante. Buena suerte.}
{365}{}{[Ve al laboratorio]}
{366}{}{Obtuve los datos del laboratorio y los componentes.}
{367}{}{¡Por fin! Ya nos acercamos a la victoria. Necesito tiempo para estudiar y verificar los componentes...}
{368}{}{Adelante.}
{369}{}{¿...Así que esta era la dirección que estaba tomando nuestro colega?¡Cómo no lo había pensado antes! Esto hace obvio lo mucho que afecta que estemos especializados en cosas distintas. Los insectos no son lo mío, así que no podría haber tomado en cuenta esta relación simbiótica con las esporas de los hongos... Ah, Wang Chong, no sabes cuánto te extrañamos.}
{370}{}{¿Qué piensas hacer?}
{371}{}{Primero, voy a crear un insecticida para detener que la infección se propague. No me llevará mucho tiempo; los reactivos del laboratorio ya están bien preservados. Por favor, espérame en el pasillo durante unas cuántas horas.}
{372}{}{Bien...}
{373}{}{¡Está listo! Se trata de una mezcla de un fungicida para las esporas y un insecticida para los portadores parasitarios. Debes verterlo en el tanque de agua en las plantaciones de agave, nosotros nos encargaremos de limpiar los invernaderos.}#added to make sense of ingame actions - cambragol
{374}{}{Entiendo.}
{375}{}{He vertido el insecticida en el tanque de agua de las plantaciones. Pero no vi ningún efecto inmediato...}#modified to make sense of in game actions - cambragol
{1375}{}{He vertido el insecticida en el tanque de agua de las plantaciones. Pero no vi ningún efecto inmediato...}#modified to make sense of in game actions - cambragol
{376}{}{El efecto se verá presente a su debido tiempo. El buen desempeño debe estar en tus genes, esta habilidad con el control de plagas le servirá de ejemplo al resto de los Seguidores. Algún día le enviaremos un informe al Cementerio que detalle esta historia.}
{377}{}{Lo siento, cuatro ojos. Pero yo hacía esto por las chapas, no por la ciencia.}
{1377}{}{Lo siento, cuatro ojos. Pero yo hacía esto por las chapas, no por la ciencia.}
{378}{}{Todo trabajo debe remunerarse. Le pedí al alcalde que te diera un extra - se te deben 350 chapas. Úsalas sabiamente. Y te lo diré de nuevo, gracias.}
{379}{}{Me alegra que las cosas hayan salido bien.}

{380}{}{El laboratorio ya no existe. Se incendió.}
{381}{}{Podíamos ver el humo. Lo hiciste tú, ¿no es así? (suspiro) Qué idiota...}
{1381}{}{Podíamos ver el humo. Lo hiciste tú, ¿no es así? (suspiro) Qué desastre...}
{382}{}{¿Hay algún problema? Eso quiere decir que la fuente de la infección fue destruida.}
{383}{}{¡Habían otras formas de destruirla! ¡Ahora todo el trabajo científico fue en vano, podría haber ayudado a las personas!}
{384}{}{No lo había pensado.}
{1384}{}{No lo había pensado.}
{385}{}{Era la forma más efectiva para detener la infección.}
{386}{}{¡Claro! Deja que un vagabundo del yermo resuelva tus problemas... Dios mío, necesito calmarme.}
{387}{}{¿Eh?}
{388}{}{Lo siento, tus acciones son dignas de elogio. La seguridad es lo primero. Pero, ¿qué haremos si la infección aparece en otro lugar? Sin los datos del laboratorio, lidiar con ella será mucho más difícil. Por el otro lado, ahora hay mucho tiempo para prepararnos. Así que, de todas formas - gracias.}
{389}{}{Lo más importante es que el problema fue resuelto. Suerte con tu investigación, Néstor.}
{390}{}{¡Oye, oye! ¿No me vas a pagar? No fue nada fácil.}
{391}{}{Técnicamente, has fallado. Lo que pedí fueron los documentos y los químicos. Pero para ser justo, voy a pagarte 100 chapas. Es suficiente.}
{1391}{}{Técnicamente, has fallado. Lo que pedí fueron los documentos y los químicos. Pero para ser justo, voy a pagarte 100 chapas. Es suficiente.}
{392}{}{Es mejor que nada.}
{393}{}{¡Me engañaste! Esta es la última vez que ayudo a los Seguidores.}
{394}{}{Lamento que haya terminado así. Adiós.}
{395}{}{Me encontré con estos químicos en el laboratorio.}
{396}{}{Estos químicos podrían ser útiles para la creación de un insecticida. Registra el laboratorio por completo, también deberías poder encontrar una documentación detallada y el equipo necesario para crearlo.}
{397}{}{De acuerdo, seguiré buscando.}
{398}{}{Hmph, y yo pensaba que ya había terminado el trabajo...}

# Questions
{400}{}{Cuéntame sobre los Seguidores.}
{401}{}{Estoy yo, me encargo de la clínica y el laboratorio químico. También está Teresa, ella se dedica a enseñar e investigar.}
{402}{}{Diana también llegó hace poco.}
{403}{}{Gracias, pero tengo unas preguntas más.}
{404}{}{¿Quién de ustedes es el jefe?}
{405}{}{No tenemos jefes. Cada Seguidor hace lo suyo y juntos formamos una junta directiva para resolver problemas en común. Es distinto a las relaciones toscas y primitivas a las que el yermo está acostumbrado.}
{406}{}{¿Qué piensas de Diana?}
{407}{}{Valoramos a cada uno de nuestros miembros, en especial si está motivado y cuenta con una experiencia tan rica. Además, los datos que recolectó en el trayecto no tienen precio. Estoy seguro de que nos será muy útil.}
{408}{}{Eso es bueno.}
{409}{}{Por desgracia, todavía no entiende que en Casa Nueva es importante seguir las reglas y no estar en contra de las autoridades. Y sí, sé que Diana sobrevivió gracias a ti. Te lo agradezco.}
{410}{}{Ya veo. ¿Puedes recordarme quién más está aquí?}
{411}{}{Teresa es muy obstinada, ¿por qué?}
{412}{}{Te pido que la disculpes. Es duro trabajar con niños y hoy en día casi nadie tiene esa experiencia. Lo único que puede hacer es leer libros viejos sobre la psicología infantil y aprender en la marcha. Además, también debe llevar a cabo investigaciones.}
{413}{}{¿Por qué necesitas un asistente?}
{414}{}{No puedo manejar todo esto sólo. Tengo una clínica y un laboratorio químico, aunque yo no soy un especialista de química. Alexandra me permite estar un poco menos presionado.}
{415}{}{¿Quién estaba involucrado en las plantaciones?}
{416}{}{Ese hombre no está con nosotros. Se sacrificó en nombre de la ciencia. Por favor, intenta no preguntar acerca de él para no herir los sentimientos de los demás.}
{417}{}{Pero había otro Seguidor, ¿no?}
{418}{}{Wang Chong... Fue desafortunado. Pasaba la mayoría de su tiempo en los invernaderos. No le gustaba hablar con los demás, pero amaba a las plantas y a la ciencia.  Pero al final, fue eso lo que lo destruyó una vez que unas esporas mutagénicas se apoderaron de su cuerpo. Es mejor que no preguntes de él, para no herir los sentimientos de los demás.}
{419}{}{¿Las plantaciones también son creación tuya?}
{420}{}{Correcto.}
{421}{}{¿No es raro cultivar plantas en medio del desierto?}
{422}{}{Créeme, tenemos nuestras propias razones para estar aquí. Esta decisión fue el resultado de una extensa investigación preliminar.}

{429}{}{¿Qué más necesitas saber?}

{430}{}{Háblame sobre la clínica.}
{431}{}{Bien, ¿qué puedo decirte...? La razón principal de su apertura fue para servirle a los soldados de Puerto. Esa era parte de nuestro acuerdo con el ejército; de lo contrario, no tendríamos permitido estar aquí. Y luego, los trabajadores locales empezaron a pedirnos ayuda.}
{432}{}{Entiendo. ¿Te puedo preguntar otra cosa?}
{433}{}{¿De dónde viene todo este equipamiento?}
{434}{}{Parte de él fue encargado a los Hojalateros y ellos lo fabricaron. Hay algunas cosas que fueron traídas por caravanas de distintos lugares.}
{435}{}{Ya veo.}
{436}{}{Tus métodos me interesan. En mi Villa, es difícil encontrar algo que no sean hierbas u hongos.}
{437}{}{No tengo ningún prejuicio en particular en contra de la medicina tradicional, durante su tiempo fue útil. Pero las técnicas de la preguerra están regresando. Por fin hemos conseguido poner en marcha un sistema de vacunación contra la enfermedad del yermo. ¿No es eso un milagro?}
{438}{}{¿De dónde consiguen sus medicamentos?}
{439}{}{Lo fabricamos nosotros mismos. Por ejemplo, es fácil producir etanol a partir del agave ardiente. Y con las drogas resultantes podemos intercambiarlas por los materiales químicos brutos, o simplemente venderlos.}

{440}{}{¿Qué piensas de la vida en este lugar?}
{441}{}{Es maravillosa. Estos días sería difícil encontrar un pueblo mejor que este.}
{442}{}{Me alegro por ti. Tengo más preguntas.}
{443}{}{¿Incluso con todas las reglas?}
{444}{}{¿Qué tienen de confusas las reglas? Ya estaban allí antes de la Guerra. Las autoridades tenían sus razones por las cuales restringirle algo al ciudadano común y también deberíamos tener en cuenta esas razones.}
{445}{}{¿Alguna vez eso a hecho a la gente feliz? Es decir, la falta de libre albedrío y el totalitarismo.}
{446}{}{¿Alguna vez la persona común ha sido del todo libre? Tal escenario únicamente es factible al estar totalmente aislado del mundo, y seguramente sólo por completo. La conclusión es obvia: hay que apreciar lo que tenemos.}
{447}{}{Hmm. Vale la pena reflexionar acerca de eso.}
{448}{}{¿Qué puedes contarme sobre el alcalde?}
{449}{}{Álvaro tiene una carga pesada. Debe hacerse responsable por el pueblo entero, únicamente porque no hay nadie más que lo haga. No deberías causarle problemas.}
{450}{}{Jamás pensaría en hacer algo así.}

{451}{}{¿Sabes algo del Refugio 24? }
{452}{}{Por supuesto, se encuentra en las ruinas de San Diego. Los fundadores de nuestra misión provienen de allí. Pero jamás he estado ahí dado que está maldito por la radiación, será así por muchas generaciones.}
{453}{}{¿Pero entonces cómo fue que tus ancestros vivían allí?}
{454}{}{Los refugios se construyeron para sobrevivir a la dura época que seguiría luego de un ataque nuclear. Según la leyenda, los fundadores abandonaron el Refugio para ayudar a que el mundo renaciera. Este sacrificio es apreciado por todos los Seguidores.}
{455}{}{Yo estuve ahí, el lugar está maldito de verdad. Ya fue saqueado, se llevaron todo lo que fuera útil.}
{1455}{}{Yo estuve ahí, el lugar está maldito de verdad. Ya fue saqueado, se llevaron todo lo que fuera útil.}
{456}{}{Eso no me sorprende. Había oído que los necrófagos tuvieron un Gran Éxodo hacia el sur, en dirección al Ardor. Suena a que encontraron un lugar que les sienta bien. Que esa zona radiactiva sea indulgente con ellos.}
{457}{}{Sí, ocurrió algo así. ¿Hablamos de otra cosa?}
{458}{}{Tengo una reliquia de ese Refugio. Mira, es una copia del diario del supervisor.}
{459}{}{¿Lo dices en serio? ¿¡Del Refugio 24!? Por favor, déjame verlo... Bien... Hmph... ¿Entonces los fundadores abandonaron el refugio dada la situación en su interior...? Que cosa tan... común. La leyenda era más hermosa, más noble. Pero me entristece ver que eran iguales a todos los demás. Te lo agradezco, es un tesoro de nuestro pasado. Lo guardaré, por nuestra historia.}
{460}{}{De nada. ¿Podemos hablar de otra cosa?}
{461}{}{¿Cambiamos de tema?}
