{100}{}{Ves a un jimador.}
{101}{}{Estás viendo a un moreno con sombrero de charro y una camiseta de lino.}
{102}{}{Acá no se permite llevar armas, escóndela rápido.}
{103}{}{Em, hola, mis respetos... Tengo que ir a... trabajar, si eso está bien...}
{104}{}{«Por favor, ahora no, hay toque de queda...»}
{105}{}{Estás viendo a Juan.}


{107}{}{«Me presento, soy }
{108}{}{, vengo de un pueblo lejano en el norte.»}

{109}{}{Eh... hola. Soy }
{110}{}{. Vengo de un pueblo del norte.}

{111}{}{Contrólate, idiota.}
{112}{}{No puedo hablar ahora, hay toque de queda.}


#First encounter
{200}{}{Hola. Soy Juan. ¿A qué vienes?}
{1200}{}{Hola. Soy Juan. ¿A qué vienes?}
{2200}{}{(al verte, se desconcierta y habla en voz baja) Poca madre, un extranjero... Eh... Hola, soy Juan.}
{201}{}{«¿Por qué sospechas tanto de la gente nueva?»}
{202}{}{«¡Claro que no, amigo! Sólo me preguntaba qué te trajo a nuestro pueblo. Somos una comunidad muy unida, aquí nos conocemos todos y es difícil que alguien nuevo encaje entre nosotros.»}
{1202}{}{«¡Claro que no, amiga! Sólo me preguntaba qué te trajo a nuestro pueblo. Somos una comunidad muy unida, aquí nos conocemos todos y es difícil que alguien nuevo encaje entre nosotros.»}
{203}{}{«Ah, ya veo. Perdón.»}
{204}{}{«No sé si te creo. De todas formas, me quitaste todas las ganas de quedarme aquí.»}
{205}{}{Es un gusto conocerte, Juan. Soy }
{206}{}{, vengo de un pueblo en el norte.}
{207}{}{«¡Ah, así que igual eres de rancho! Bienvenido, necesitamos más gente como tú.»}
{1207}{}{«¡Ah, así que igual eres de rancho! Bienvenida, necesitamos más gente como tú.»}
{208}{}{«Gracias, parece que ustedes son buena gente.»}
{209}{}{«¿Y me habrías recibido si no fuera así? Eso no es muy amable, Juan.»}

#Repeated meeting
{210}{}{Hola. Buenas noches.}
{211}{}{Hola. Buenos días.}
{212}{}{Adiós, amigo.}
{213}{}{Necesito comprarte algo de jarabe.}
{2213}{}{«Ocupo algo de jarabe.»}
{214}{}{¡Hmph! Me largo.}
{215}{}{«Adiós, Juan.»}
{216}{}{Hola. Buenas noches.}
{217}{}{Hola. Buenos días.}
{218}{}{Hola.}
{219}{}{«Tienes preguntas que hacerme, ¿no?»}

{220}{}{«Háblame de este pueblo. ¿Quién está a cargo?»}
{221}{}{«Nuestro alcalde se llama Álvaro. Deberías hablar con él, vive en esa casa grande de allá, la que tiene la marquesina.»}
{222}{}{«Gracias, iré a hablar con él en un rato.»}
{223}{}{«Cuéntame de ti.»}
{224}{}{«Soy Juan, aquí chambeo de jimador. ¿Qué más quieres saber?»}
{225}{}{«¿Qué puedes contarme de tu trabajo, Juan?»}
{226}{}{«Suelo trabajar con el agave ardiente y otros cultivos. Mientras crecen, me ocupo de la mercancía que traen las caravanas y de otros encargos menores.»}
{227}{}{«Juan, sé sincero... ¿Tú quieres estar aquí?»}
{228}{}{«Sí, señor. Yo elijo trabajar acá, puedo irme cuando quiera, pero no tengo otro lado a donde irme. Debo seguir las reglas y respetar mi contrato.»}
{1228}{}{«Sí, señorita. Yo elijo trabajar acá, puedo irme cuando quiera, pero no tengo otro lado a donde irme. Debo seguir las reglas y respetar mi contrato.»}
{229}{}{«Ya veo. Gracias.»}

{230}{}{«Tengo preguntas al respecto de su plantación.»}
{231}{}{«En su mayoría, cosechamos elotes y agave ardiente. ¿Por qué te interesa?»}
{232}{}{«¿Qué es el 'agave ardiente'? Me da curiosidad.»}
{233}{}{«He oído del agave normal. ¿Pero qué hay del 'agave ardiente'?»}
{234}{}{«Según los Seguidores, es un agave mutado que cultivaban antes de la Gran Guerra. Desde ese entonces, se hizo más grande, más tóxico y más pinchudo. Pero todavía tiene la piña. Esa parte es la que solemos sacar.»}
{235}{}{«Pero, ¿para qué usan la planta?»}
{236}{}{«Nosotros usamos toda la planta, amigo. La piña y el jugo se puede usar en la cocina, las hojas para hacer fertilizante y telas. ¡Incluso los Seguidores saben hacer medicina con él!»}
{1236}{}{«Nosotros usamos toda la planta, amiga. La piña y el jugo se puede usar en la cocina, las hojas para hacer fertilizante y telas. ¡Incluso los Seguidores saben hacer medicina con él!»}
{237}{}{«¿En dónde tienen su plantación?»}
{238}{}{«Allá, al oeste... Pero no recomiendo que vayas, a los demás no les va a gustar.»}
{239}{}{«Que interesante. ¿Puedo comprarte un poco? Necesito el jarabe.»}
{240}{}{«La verdad es que no hay suficiente para todos, no tengo permitido venderle a cualquiera.»}
{241}{}{«Comprendo. Gracias.»}
{242}{}{«Mira, de verdad necesito comprar un poco. Por favor.»}
{243}{}{«Amigo, perdóname, pero no puedo. Si el Alcalde se entera, me va a madrear.»}
{1243}{}{«Amiga, perdóname, pero no puedo. Si el Alcalde se entera, me va a madrear.»}
{244}{}{«Está bien, olvídalo.»}
{245}{}{«¿Quién está a cargo de este pueblo?»}
{246}{}{«Nadie se dará cuenta si falta un poco, y tengo chapas que te vendrían bien...»}
{247}{}{«Tú sí que sabes como negociar. Ya, si necesitas comprar, habla conmigo. Pero entiendo para qué lo necesitas. ¿Acaso harás tequila?»}
{248}{}{«Puede ser. Lo estoy pensando.»}
{249}{}{«No seas así, Juan. Ya me conoces, ¿no somos amigos?»}

{250}{}{«¿Por qué está prohibido tener un arma?»}
{251}{}{«¿Viste las reglas en el cartel de la entrada? No te conviene para nada quebrarlas, querido viajero. Podría costarte muy caro.»}
{1251}{}{«¿Viste las reglas en el cartel de la entrada? No te conviene para nada quebrarlas, querida viajera. Podría costarte muy caro.»}
{252}{}{«Lo siento, no debí haber preguntado. Olvídalo.»}
{253}{}{«¿Y entonces qué es esa lanza que llevas? Es rara.»}
{254}{}{«Jeje, no es un arma, es una coa. Durante la cosecha, la uso para cortar el agave. Incluso llevar una coa está prohibido, pero yo tengo permiso del alcalde.»}
{255}{}{«Jamás había visto algo así.»}
{1255}{}{«Jamás había visto algo así.»}
{256}{}{«El Alcalde le encargó varias a los Hojalateros, nos cobraron parte de la cosecha por ellas. Nos salió caro, pero nuestro trabajo es difícil sin una herramienta. Y los únicos que saben hacerlas, son los Hojalateros.»}
{257}{}{«Sé como se siente, en mi Villa, también tenemos que hacerlo todo a mano.»}
{258}{}{«¿Cómo? Nunca había oído de otros asentamientos que tuvieran cosechas. ¿Lo dices en serio?»}
{259}{}{«Si no me crees, entonces hablemos de otra cosa.»}
{260}{}{«Ya entiendo. Entonces hablemos de otra cosa.»}
{261}{}{«Jamás había visto una herramienta de ese tipo.»}
{262}{}{«¿Yo, una persona cualquiera? ¿Cómo crees?»}
{263}{}{«¿Por qué?»}
{264}{}{«¿Te gustaría si alguien se metiera a tu casa sin tu permiso? Además, a veces atrapamos a gente que se roba la cosecha. Créeme que casi nunca termina bien.»}
{265}{}{«¿Tienes más preguntas?»}

{269}{}{«Disculpe, señor.» No tengo tiempo para hablar con usted. }
{1269}{}{«Disculpe, señorita.» No tengo tiempo para hablar con usted. }

{270}{}{Ah... Lo siento, señor. Pero no sé si pueda hablar con usted. }
{1270}{}{Ah... Lo siento, señor. Pero no sé si pueda hablar con usted. }
{271}{}{Eso es malo, supongo que tendremos problemas comunicándonos.}
{272}{}{«Somos de la misma raza, compadre.»}
{273}{}{«¡Me alegra mucho saber eso!»}
{274}{}{¿Puedo ver qué tienes en el carro?}
{275}{}{¡No, no, no, señor! El jarabe está reservado para las caravanas. No está a la venta.}
{1275}{}{¡No, no, no, señorita! El jarabe está reservado para las caravanas. No está a la venta.}
{276}{}{Lo siento, señor.}
{1276}{}{Lo siento, señorita.}
{277}{}{Sí, por supuesto, señor.}
{1277}{}{Sí, por supuesto, señorita.}
{278}{}{[Continuar]}
{279}{}{[Intenta convencer a José de que hable contigo]}
{280}{}{(conforme te acercas, se echa para atrás) ¿Q-qué necesita?}
{281}{}{(al verte, su rostro se pone pálido) Y-yo... ¡No hablar ahora! ¡Déjame!}

{282}{}{(al darte un vistazo, se pone nervioso) «Hola, eh... ¿Q-qué necesitas?»}
{283}{}{(al darte un vistazo, es obvio que se pone nervioso) «Hola, te... ¿t-te ayudo en algo?»}
