{100}{}{Ves a Frank.}
{101}{}{Estás viendo a un hombre de aspecto sombrío, lleva puesta una armadura de combate.}
{102}{}{}
{103}{}{}
{104}{}{}
{105}{}{¡Presencia hostil en la ciudad! ¡Todo el mundo a cubierto!}

{200}{}{¿Algo anda mal?}
{201}{}{No. ¿Debería haberlo?}
{202}{}{No voy a perder el tiempo contigo. ¿Sabes leer? Entonces estudia y recuerda las reglas que están en el cartel de la entrada principal. Son muy simples.}
{203}{}{Ah, las reglas... Pero, acabo de llegar a la ciudad. Necesitaba hablar con alguien.}
{1203}{}{Ah, las reglas... Pero, acabo de llegar a la ciudad. Necesitaba hablar con alguien.}
{204}{}{¡Me alegro de verte, hermano! Te felicito por tu ascenso.}
{1204}{}{¡Me alegro de verte, hermana! Te felicito por tu ascenso.}
{205}{}{¿Tú también eres parte de la Hermandad?}
{206}{}{Así es. La Hermandad se asegura de que no le ocurra nada malo a este pueblo, es un lugar tranquilo y seguro. Nuestras patrullas suelen hacer una parada en este lugar e incluso algunos vienen a descansar y a recuperarse. La nave no es muy placentera que digamos, eso ya lo sabes.}
{207}{}{Claro. ¿No te importa si me quedo un momento, verdad? Genial.}
{208}{}{(has un gesto sarcástico con la mano)}
{209}{}{¿Qué? Oh, ja ja. Qué chistoso. Mira, lo único que quiero es que no te metas en problemas. No hagas escándalos y guarda tu arma. Es muy simple.}

{210}{}{Te escucho.}
{211}{}{Soy todo oídos.}
{2211}{}{Dame una sola razón y dejaré que las mutarachas devoren tu asqueroso cuerpo, fenómeno.}
{212}{}{¿Sigues aquí?}
{213}{}{No te molestaré más. Adiós.}
{214}{}{Eres un imbécil.}
{215}{}{Pero somos amigos, ¿no?}
{216}{}{Adiós.}
{217}{}{He escuchado sobre ti. Debes respetar nuestras reglas y no nos causes problemas. Eso es todo lo que debes hacer y nos llevaremos bien.}
{2217}{}{He escuchado sobre ti. Respeta nuestras reglas y no nos causes problemas, eso es todo lo que debes hacer. Aunque, odio a los mutantes, en cualquier otra situación ya te hubiera disparado.}
{218}{}{Eso no lo dudo.}
{219}{}{Será difícil que entres a mi lista de amigos. Ten eso en cuenta.}

{220}{}{Se dice que han habido desapariciones en la plantación y que no haces nada al respecto.}
{221}{}{Eso es una acusación grave.}
{222}{}{Es lo que dice a gente...}
{223}{}{Recuerda esto, forastero. No me gusta que hayan rumores o pánico en mi pueblo. Si no quieres problemas, no empeores las cosas. Es así de simple.}
{1223}{}{Recuerda esto, mujer. No me gusta que hayan rumores o pánico en mi pueblo. Si no quieres problemas, no empeores las cosas. Es así de simple.}
{224}{}{Sí, no quiero ningún problema.}
{225}{}{Te digo lo mismo, la justicia le llega a todos, tarde o temprano.}
{226}{}{Has hecho mucho por nosotros, debería agradecértelo.}
{2226}{}{Eres un mutante, pero debo agradecértelo, has hecho mucho por nosotros.}

{230}{}{¿Está prohibido portar armas abiertamente?}
{231}{}{Lo está. Y deberías respetar nuestras reglas.}
{232}{}{¿Y entonces por qué llevas un arma?}
{233}{}{Porque soy el que hace las reglas.}
{234}{}{Ya veo. Fue una pregunta estúpida, lo siento. Adiós.}
{235}{}{Claro, que conveniente...}
{236}{}{No me agradas. Nadie te pidió que vinieras aquí y cuestionas nuestras reglas. Pero te daré dos opciones.}
{237}{}{¿Cuáles son?}
{238}{}{O sigues las reglas y dejas de molestar a todos, o te largas de aquí. Piénsatelo bien.}
{239}{}{El único que molesta a los demás eres tú, me aseguraré de arruinarte el día.}
{240}{}{Está bien, voy a seguir las reglas.}
{241}{}{Está prohibido, los campesinos tienen que entender quién está a cargo. Si no, habrá caos. Y todos deben seguir esa regla, tú también.}
{242}{}{Eso es obvio.}

{243}{}{¡Alto! (te apunta con su rifle) Enfunda tu arma, no está permitido portarlas abiertamente.}
{244}{}{Perdona, sheriff. No conozco bien las reglas de este sitio.}
{1244}{}{Perdona, sheriff. No conozco bien las reglas de este sitio.}
{245}{}{Tus reglas no me importan.}
{246}{}{¡Ja! [Haz caso a la regla]}
{247}{}{¡Claro que no! [Mantén tu arma en mano]}
{248}{}{¿Lo dices en serio? Lo voy a dejar pasar, pero sólo por esta vez. Es únicamente porque respeto tu reputación.}
{249}{}{Bien pensado, sheriff.}
{250}{}{¿Hay algún problema? ¿Por qué estás aquí?}
{251}{}{No podía dormir. Quería salir a tomar aire.}
{252}{}{No te creo. Todos deberían estar en casa durante el toque de queda. Tienes dos minutos para ir hacia allá y quedarte ahí hasta las 6 de la mañana.}
{253}{}{Sí, señor. No hay problema...}
{254}{}{¿Algún problema?}
{255}{}{No, ninguno.}
{256}{}{Estoy patrullando. No deberías estar aquí afuera si no es por una buena razón. Podría confundirte con un ladrón o alguna bestia del desierto.}
{257}{}{Lo siento, ya me voy.}
{258}{}{Ya conoces las reglas. La principal es no hacerme enojar.}
{259}{}{Lo siento, ya me voy.}
{260}{}{Tú otra vez, ya te había dicho que no deberías salir cuando es de noche. ¿Hay algún problema?}
{261}{}{Sólo tengo insomnio, señor. Perdón...}
{262}{}{Intenté ser amable contigo, pero ya tuve suficiente y te daré una lección. Estarás dentro de la celda durante 10 horas, te dará tiempo para pensar en lo que has hecho. Muévete, y ni pienses en salir corriendo.}
{263}{}{De acuerdo, señor, no voy a escaparme...}
{264}{}{¡Oblígame!}
{265}{}{¡Ya me cansé de esta mierda!}
{266}{}{Ay...}
{267}{}{¡Oblígame!}

{270}{}{Así que por fin te veo, basura. No tendré que encontrarte, lo cual es bueno. ¿Pensabas que podrías escapar de la Hermandad?}
{1270}{}{Así que por fin te veo, escoria. No tendré que encontrarte, lo cual es bueno. ¿Pensabas que podrías escapar de la Hermandad?}
{271}{}{Claro que sí. Te haré pedazos.}
{272}{}{Nadie escapa de la Hermandad. Eres un criminal y mi deber es traerte a la justicia. Aquí y ahora. ¿Alguna última palabra? ¿No? Eso es bueno, porque no las mereces...}
{273}{}{Ups...}
{274}{}{No sé de qué estás hablando. Creo que te equivocaste de persona...}
{275}{}{Te estás equivocando de persona. No sé una mierda sobre esa tal Hermandad.}
{276}{}{Hmm, tal vez. Pero eres igual a la persona descrita. Está bien, perdón. Pero te estoy vigilando.}
{277}{}{Eso estuvo cerca...}

{280}{}{¿Podrías hablarme sobre el pueblo?}
{281}{}{Esto es lo que debes saber acerca de nuestro pueblo, forastero. Sigue las reglas y no molestes a los demás. Si quieres encajar, lo harás. Pero la verdad es que deberías limitarte a hablar con el alcalde y los Seguidores, evita a todos los demás.}
{1281}{}{Esto es lo que debes saber acerca de nuestro pueblo, forastera. Sigue las reglas y no molestes a los demás. Si quieres encajar, lo harás. Pero la verdad es que deberías limitarte a hablar con el alcalde y los Seguidores, evita a todos los demás.}
{282}{}{Entiendo.}
{283}{}{¿Quién está a cargo del pueblo?}
{284}{}{Álvaro es el alcalde del pueblo, está al final de la calle, en la casa grande con el pórtico.}
{285}{}{Vale.}
{286}{}{¿A qué te dedicas?}
{287}{}{Soy el sheriff del pueblo, mi responsabilidad es que todos respeten la ley y mantener este lugar a salvo.}
{288}{}{Ya veo. Te deseo suerte con tus deberes.}
{289}{}{¿Qué tan seguro es este lugar?}
{290}{}{Totalmente seguro.}
{291}{}{¿Estás seguro?}
{292}{}{Creeré en ti.}
{293}{}{Ley, seguridad, qué aburrido. ¡Quiero pelear!}
{294}{}{Hmm... Hay un lugar que está maldito y deberías evitarlo. Te lo advierto ahora, así no debo sacarte de ahí después.}
{295}{}{Cuéntame.}
{296}{}{En las afueras del pueblo hay una planta de concreto y una cantera. Se cerró la planta porque empezó a desaparecer gente allí. Hay muchos rumores, pero nadie tiene claro lo que realmente pasó.}
{297}{}{De acuerdo, gracias por el aviso.}

#El Gigante
{300}{}{Respecto a la planta de concreto.}
{301}{}{¿Sí?}
{302}{}{Pensándolo bien, ese lugar da miedo. Tengo otras preguntas.}
{303}{}{Puedo resolver ese problema por 300 chapas.}
{304}{}{Eso es lo que dijeron los demás mercenarios. Si valoras tu vida, no te acerques a la planta.}
{305}{}{No importa lo que digas, voy a ir. Llévame a la planta de concreto.}
{306}{}{Está bien, te haré caso.}
{307}{}{Había un monstruo en la planta, conseguí cazarlo. Era un bastardo, muy, duro...}
{308}{}{Vaya... ¡Lo veo y no lo creo! ¿Un Garra Mortal? ¿Aquí? Esas criaturas sí que llegan lejos.}
{309}{}{Ahora no podrá hacerle daño a nadie.}
{310}{}{Has hecho un excelente trabajo, el pueblo entero te debe una. Por lo tanto, te daré una recompensa directo de la tesorería del pueblo.}
{311}{}{Gracias.}
{312}{}{¿Cómo sabes de los Garras Mortales?}
{313}{}{Había oído de ellos durante mi entrenamiento, pero jamás había visto uno. Los veteranos cuentan que viven en las montañas al oeste, en donde pocos se atreven a explorar.}
{314}{}{Interesante.}
{315}{}{Conozco de una sola vez en la que un Garra Mortal entró a una ciudad y creó un montón de problemas. Fue en el Cementerio, una hembra se anidó en un sótano abandonado e incluso puso huevos. Pero hubo un mercenario que los encontró y se encargó de ellos al destruir los huevos. Imagina si esas cosas hubieran eclosionado.}
{316}{}{Eso es terrorífico.}
{317}{}{Bueno, hiciste un buen trabajo, guerrero. Deberías unirte a nosotros.}
{1317}{}{Bueno, hiciste un buen trabajo, señorita. Deberías unirte a nosotros.}
{318}{}{Tal vez, tal vez... Tengo otras preguntas.}
{319}{}{Habías mencionado tu entrenamiento. ¿En dónde fue eso?}
{320}{}{Soy un paladín de la Hermandad del Acero. Nuestra base local se encuentra en Puerto Peñasco, mientras que el cuartel general está lejos en California. Me entrenaron allí y luego me ofrecí de voluntario para esta misión.}
{321}{}{Vaya. Es bueno saber eso.}
{322}{}{Quiero ayudar con este problema. ¿Puedes mostrarme este lugar?}

#Pinky
{330}{}{Me he cruzado con Meñique. Dicen que quieres verlo muerto.}
{331}{}{Debería cortarle la lengua a Chip por decir eso. Yo no quiero violencia porque sí, pero tengo una misión - mantener a este pueblo a salvo. En este momento no hay ninguna razón por la cual exterminar a esa cosa. Pero a la más mínima ofensa, lo enviaré al cielo de las ratas.}
{332}{}{¿Por qué te desagrada tanto?}
{333}{}{En este momento es una cría inofensiva, ¿pero qué ocurrirá cuando sea mayor y huela sangre? Las ratas cerdo son depredadores agresivos. No tienen ningún lugar entre la gente.}
{334}{}{Hmm.}
{335}{}{Sí, entiendo bien lo que dices.}
{336}{}{¿Y a ti por qué te importa el animal? Debe ser curiosidad, supongo. Bueno, te tengo una propuesta. Voy a pagarte 30 chapas si 'duermes' a esa bestia. ¿Qué dices?}
{337}{}{De ninguna manera, no quiero herir los sentimientos de ese niño.}
{338}{}{¡Es la culpa de Chip! Él no debería haber traído a esa bestia a casa y Álvaro tampoco tiene las agallas para hacer lo que debería. Es una pena. Una pena de que hayan cobardes por todos lados.}
{339}{}{Adiós, sheriff.}
{340}{}{No me tardaré mucho. Cuenta bien esas chapas.}
{341}{}{Cuento contigo.}
{342}{}{Nos vemos, sheriff.}
{343}{}{La rata cerdo ya está dormida.}
{344}{}{Chip debe estar muy molesto. Es una pena, pero es culpa suya. Esto le enseñará una importante lección.}
{345}{}{Si tú lo dices.}
{346}{}{Debes asegurarte de que esa lección sea la correcta.}
{347}{}{Has hecho un buen trabajo, puede que seas útil en el futuro. Toma, las 30 chapas que te prometí.}
{348}{}{Nos vemos otro día, sheriff.}

{350}{}{Necesito saber si un tal Tin-Tan ha estado aquí.}
{351}{}{¿Tin-Tan? Debe ser un apodo. ¿Sabes su nombre real?}
{352}{}{Germán Henaro Cipriano Gómez Valdés-y-Castillo. Estaba viajando con una caravana, partieron en Fénix e iban hacia el pueblo pesquero de El Faro.}
{353}{}{Déjame revisar los registros migratorios... Dame un momento... No, no hay ningún registro de que él haya visitado Casa Nueva.}
{354}{}{¿Qué ocurrió con la caravana del "Sonora Express"?}
{355}{}{Déjame ver... Sí, veo que el nombre estaba allí, pero... Dice que unos forajidos asesinaron a toda la caravana antes de que llegara a nosotros.}
{356}{}{Bueno, no hubo suerte. Gracias, sheriff.}

{360}{}{¡Bienvenido, hermano! Estoy feliz de ver esa armadura otra vez. Pero... ¿en dónde está la insignia de...? Un momento... ¿Quién eres? ¡Da la cara!}
{361}{}{¿Hermano? ¿A qué te refieres con eso? ¿De quién hablas?}
{362}{}{Demonios, ¿no eres uno de los nuestros? ¿Entonces cómo carajo obtuviste esa servoarmadura? }
{363}{}{Es mi trofeo. Pero responde la pregunta. ¿A qué te refieres con 'uno de los nuestros'?}
{364}{}{(piensa en lo que dirá) Mira, no eres una amenaza para los demás, ¿así que por qué no te quitas la armadura y me muestras tu cara? Este es un pueblo pacífico, nadie te hará daño a no ser seas una amenaza. Sé razonable y responderé tus preguntas. ¿Te parece?}
{365}{}{¿Y qué te hace pensar que no soy una amenaza? ¡Es por eso que estoy aquí, imbécil!}
{366}{}{Está bien, haré caso a lo que dices.}
{367}{}{Dijiste 'hermano', así que eres parte de la Hermandad del Acero, ¿no?}
{368}{}{¡Boo-boo!}
{369}{}{¡Bubba-bubba!}
{370}{}{¡Wow!}
