{100}{}{Ves al gerente.}
{101}{}{Ves a un hombre con ropas de trabajo.}

{200}{}{Ah, es nuestro héroe. Escuché que tú mataste al monstruo. Todo el pueblo está agradecido contigo.}
{1200}{}{Ah, es nuestra salvadora. Escuché que tú mataste al monstruo. Todo el pueblo está agradecido contigo.}
{201}{}{Veo que no perdieron el tiempo en volver a poner las cosas en marcha.}
{202}{}{Antes producíamos concreto y ladrillos, hasta que apareció el Gigante. Mató a muchos trabajadores, así que tuvimos que cerrar. Pero como ya no está, podemos seguir trabajando.}
{203}{}{Ya veo.}
{204}{}{Pasa, siempre estaré feliz de verte.}
{205}{}{Tengo que irme.}
{206}{}{Ya veo.}

{207}{}{¿Te ayudo en algo?} // added this to make the dialogue smoother - cambragol


{210}{}{¿Cuánto le pagas a los trabajadores?}
{211}{}{Casi todos son prisioneros o esclavos. Les damos lo suficiente, comida, agua y ropa. También tenemos unos pocos mercenarios.}
{212}{}{¿Por qué es tan importante este lugar?}
{213}{}{Que yo sepa, no hay ninguna otra planta de cemento que funcione. Cuando alguien necesita construir una casa, tiene que buscar ladrillos entre las ruinas. Pero aquí podemos fabricar ladrillos nuevos.}
{214}{}{¿Ustedes venden cemento y ladrillos?}
{215}{}{Al principio, la planta solo funcionaba para Casa Nueva. Pero ahora vendemos a las obras en Puerto Peñasco y Two-Sun. Pronto le venderemos a Fénix, si es que convencemos a los Seguidores. Pero primero, tenemos que poner todo en órden.}
