{100}{}{Ves la computadora del laboratorio.}
{101}{}{Ves una computadora de laboratorio.}
{102}{}{La computadora no enciende por la falta de energía.}
{103}{}{No enciende.}

Dialogue

{200}{}{Introducir comando:}
{201}{}{Cerrar sesión}
{202}{}{Regresar}
{203}{}{Siguiente}
{204}{}{Regresar al menú principal}

{210}{}{Notas científicas de Wang Chong}
{211}{}{"Establezco el objetivo de la investigación para los próximos cinco años: desarrollar cultivos frutales resistentes a las sequías, aptos para cultivo masivo. Con esto se pretende resolver la escasez de alimentos en Arizona y California, como respuesta a las necesidades de una población que está en aumento."}
{212}{}{Localización del experimento}
{213}{}{"Nuestra investigación se lleva a cabo en el bien conservado laboratorio de 'Hidroponía Greenway', donde se pretendía desarrollar plantas resistentes a las sequías y la radiación durante la preguerra. La instalación también preparaba los materiales incluidos en los kits de supervivencia post-nuclear de Vault-Tec."}
{214}{}{Siguiente}
{215}{}{"El laboratorio contiene: equipamiento, sistemas hidropónicos automatizados, semillas libres de radiación de varias plantas y hongos, extensa documentación del laboratorio y literatura de la preguerra, además de un diverso conjunto de químicos, aditivos biológicos, y múltiples virus."}
{216}{}{Objetivos del proyecto}
{217}{}{"Nuestro primer objetivo es estudiar la instalación e investigaciones previas de la Hidroponía Greenway y de tal forma volver a operar en el complejo y el laboratorio. Entre los desarrollos locales, hay soluciones ya preparadas que pueden utilizarse para Casa Nueva."}
{218}{}{Siguiente}
{219}{}{"Nuestro segundo objetivo es criar plantas para incrementar las reservas de semillas. Esta labor debe llevarse a cabo en invernaderos aislados para crear el ambiente más limpio y controlado que sea posible."}
{220}{}{Siguiente}
{221}{}{"Nuestro tercer objetivo es desarrollar nuevas variedades de plantas que sean adecuadas para sobrevivir en el desierto de Sonora y el yermo radioactivo de California."}
{222}{}{Nota importante}
{223}{}{"Una importante condición del experimento es estimular el crecimiento de plantas, especialmente de las raíces. Se propone una variedad de métodos: aditivos biológicos, la irradiación, esporas fúngicas, y múltiples virus que tiene disponible la Hidroponía Greenway. Como medida de seguridad, el acceso al laboratorio debería estar altamente restringido."}
{224}{}{Copiar datos de la investigación}
{225}{}{Los archivos se han copiado al holodisco con éxito.}
