{100}{}{Ves a un bandido.}
{101}{}{Ves a un jovenzuelo de conducta rebelde.}
{102}{}{¿Esta moto es tuya? Ah, ya veo. Pensé que estaba abandonada. Eh, llévatela, no importa.}
{103}{}{Piérdete.}
{104}{}{Oye, ¿la moto es tuya?}

{200}{}{¿Oye, ¿la moto es tuya?}
{201}{}{Así es.}
{202}{}{Puede ser. ¿Qué te importa?} 
{203}{}{¿Cómo? Esa moto es mía. ¿Algún problema? ¿O acaso quieres comprármela? Es una ganga, te la vendo por 500 chapas. Tráelas antes de que me arrepienta.}
{204}{}{¿Y para qué la quieres? Seguro que ni sabes conducir.}
{205}{}{¿Acaso tengo cara de tonto? Una moto es muy útil, si no pagas, alguien más lo hará.}
{206}{}{Entrégame la motocicleta. No te lo pediré una segunda vez.}
{207}{}{Dame un momento, intentaré conseguirme unas chapas.}

{210}{}{¿Tienes las 500 chapas?}
{1210}{}{¿Tienes las 500 chapas?}
{211}{}{¿Tienes las 700 chapas?}
{1211}{}{¿Tienes las 700 chapas?}
{212}{}{Intento conseguir las chapas, dame tiempo.}

{220}{}{La motocicleta es *mía*. Pásame las llaves. Ahora.}
{221}{}{¿O qué? ¿Qué me harás? Estás en el territorio de mi pandilla. Si me pones un dedo encima, te harán pedazos.}
{222}{}{Tú y esa manga de inútiles no podrían importarme menos. Dame las llaves, o morirás.}
{223}{}{Ya, ya. Cambié de parecer, no quiero problemas.}
{224}{}{¿En serio? Tienes razón, me arrepiento... porque 500 chapas era muy poco, ahora me darás 700.}
{225}{}{Hmph.}
{226}{}{Esto es una estupidez. Mejor, te mato y ya.}

{230}{}{Ya tengo las chapas. Quiero mis llaves.}
{231}{}{(tira las llaves al piso) Ahí tienes. Ni siquiera sé conducir. (con una sonrisa y una mirada satisfecha, se adentra en la ciudad, disfrutando del peso de las chapas en su mano)}
{232}{}{Gracias, al menos fuiste honesto.}
{233}{}{Algún día te encontraré mientras duermes, y te degollaré. Y me reiré. Mucho.} 
{234}{}{No irás a ningún lado, porque esas chapas son mías.}

{240}{}{Eres un idiota si crees que puedes meterte con el campeón.}
{1240}{}{Eres un idiota si crees que puedes meterte con la campeona.}
{241}{}{Soy uno de los Seguidores, si me pones un dedo encima, mis hermanos te encontrarán.}
{242}{}{¿Sabes quiénes son los forajidos? Soy parte de ellos, y nadie se mete con nosotros.}
{243}{}{(su rostro se llena de terror) Mierda, no lo sabía... Perdóname, aquí tienes la llave. ¿Me perdonas, verdad? Yo, eh... me tengo que ir.}
{244}{}{Lárgate de aquí.}
{245}{}{No te preocupes, sólo fue un malentendido.}
