{100}{}{Ves a Vernon.}
{101}{}{Estás viendo a un hombre que lleva puesto un traje hecho jirones. Sus ojeras poseen un color negruzco y posee tics nerviosos, lo que indica que trabaja más de la cuenta.}
{102}{}{Nuestra área es peligrosa, eso es obvio, pero no pensaba que tanto...}
{103}{}{¡Por favor, tienes que detenerlos! ¡Van a destruirlo todo!}

# First dialogue
{200}{}{(conforme te acercas, el hombre se da cuenta de ti y le da un tic nervioso bajo su ojo derecho) No creo haberte visto antes. ¿Qué haces aquí?}
{2200}{}{(conforme te acercas, el hombre frunce el ceño y su ojo derecho sufre un tic nervioso) Me recuerdas a los necrófagos de la central eléctrica, pero ya los reconozco a todos si los miro de cerca. ¿Quién eres? ¿A qué viniste?}
{201}{}{Necesito un lugar para pasar la noche, ¿podría arrendar alguna habitación?}
{202}{}{Perdona, pero todas nuestras habitaciones están ocupadas. Estamos tan apretados que apenas tenemos privacidad.}
{203}{}{¿Qué es este lugar?}
{204}{}{Es algo como una casa comunal, si estás aquí por pura casualidad, es mejor que te vayas.}
{205}{}{¿Por qué?}
{206}{}{Esta comunidad es muy unida, todos se conocen y desconfían de los recién llegados.}
{2206}{}{Esta comunidad es muy unida, todos se conocen y desconfían de los recién llegados. Especialmente si son mutantes. Te seré honesto, los demás tienen miedo de que les contagies tu... condición.}
{207}{}{Lo entiendo. En ese caso, mejor me voy.}
{208}{}{Eso no me sorprende, en un área como esta. Adiós.}
{209}{}{No me iré hasta que hayas respondido mis preguntas.}

{210}{}{Eh... nada, la verdad. ¿Qué es este lugar?}
{211}{}{Esto es una casa comunal. ¿Tienes algo que hacer aquí, o conoces a alguien? Si eso era todo, es mejor que te largues.}
{212}{}{¿Por qué me echas?}
{213}{}{(da un gruñido poco satisfecho) Eh... hm... Maldita sea, ¿sabes qué hora es...?}
{214}{}{Perdona, no quería interrumpir tu sueño.}
{215}{}{Anda, despierta.}

{220}{}{(tu apariencia provoca que el hombre se quede congelado de asombro y acto seguido le da un tic nervioso bajo el ojo derecho) Me sorprende ver a una persona tan respetable en nuestro barrio. ¿Estás buscando algo?}
{221}{}{La verdad es que busco un sitio en donde pasar la noche. ¿Te queda alguna habitación disponible?}
{222}{}{Me temo de que todas nuestras habitaciones están ocupadas. Además, no creo que te guste este lugar.}
{223}{}{¿Por qué?}
{224}{}{¿Cómo lo digo...? No encajas en estos barrios, vivimos en malas condiciones y algunos de nuestros inquilinos pueden ser agresivos. Puede que hasta te roben.}
{225}{}{Nada de eso me sorprende, considerando el área. Adiós.}
{226}{}{Entonces es hora de que me vaya.}
{227}{}{Bueno, tengo unas preguntas que hacerte, antes de irme.}
{228}{}{Tenía curiosidad de saber qué es este lugar.}
{229}{}{Es como una casa comunal, si estás aquí por casualidad, entonces no deberías quedarte.}
{230}{}{¿Por qué?}

{240}{}{¡Hola, campeón! Esa lucha fue asombrosa. ¿En qué te ayudo?}
{1240}{}{¡Hola, campeona! Esa lucha fue asombrosa. ¿En qué te ayudo?}
{241}{}{No sabría decirte. ¿Qué es este lugar?}
{242}{}{Esta es una casa comunal y yo soy su gerente. Sin embargo, no creo que a alguien de tu estatuto le interese un lugar como este. Nuestro barrio está habitado por... ciudadanos menos exitosos.}
{243}{}{En ese caso, ¿podrías responderme unas dudas?}
{244}{}{Tienes razón, un vertedero como este no me interesa ni un poco. Adiós.}
{245}{}{¿Te importa si echo un vistazo? ¿No? Genial, nos vemos.}
{246}{}{¡Hola, campeón! Esa lucha fue asombrosa. ¿En qué te ayudo?}
{1246}{}{¡Hola, campeona! Esa lucha fue asombrosa. ¿En qué te ayudo?}
{247}{}{Quiero hablar contigo.}

# Death of a pusher
{250}{}{(Vernon está sentado con las manos en su cabeza; se mueve hacia adelante y atrás muy lentamente, dejando salir un quejido leve)}
{251}{}{¿Qué te pasa?}
{252}{}{¿Eh? Ah, eres tú... Este maldito dolor de cabeza... Gónzales solía encontrar drogas y yo las tomaba, pero ahora está muerto y no sé en dónde puedo conseguir más... Agh...}
{253}{}{Eso es malo. Bueno, adiós.}
{254}{}{Ah, perdón, pensé que matar al camello sería bueno para todos.}
{255}{}{¿En qué DEMONIOS pensabas? ¡Mierda! Sí, es cierto que Gonzáles le daba unas drogas malas a los inquilinos, lo que, eh... los arruinaba, un poco. Pero para los demás, nos abastecía con medicamentos para nuestras enfermedades, además de analgésicos. ¿Por qué carajo tenías que hacer esto?}
{256}{}{Ya está hecho, así que deberías pasar página.}
{257}{}{Sí, claro... Lárgate de mi oficina de una puta vez.}
{258}{}{Cuidado con como me hablas, o acabarás igual que él.}
{259}{}{Lo que sea.}
{260}{}{Su 'medicina' no era nada buena para los demás.}
{261}{}{¿Esa es tu única razón? Mierda, ¡estás demente! Fuera de nuestro barrio, ahora.}
{262}{}{}
{263}{}{Ni siquiera yo lo sé. ¿De verdad hace falta una razón?}
{264}{}{¡Estás demente! Sal del área y no vuelvas jamás.}

# Racket after the final game
{270}{}{Oh, gracias, amigo. Si no hubieras estado aquí, esos matones hubieran destrozado este sitio y puede que nos hayan herido.}
{1270}{}{Oh, gracias, amiga. Si no hubieras estado aquí, esos matones hubieran destrozado este sitio y puede que nos hayan herido.}
{271}{}{¿Qué era lo que buscaban?}
{272}{}{Sólo querían problemas, después de que se separó la banda de los Cardenales Rojos, sólo Dios sabe lo que empezó en los barrios bajos. Antes habían matones que tenían miedo hasta de salir, pero ahora pueden robar y dar golpizas todo lo que quieran.}
{273}{}{Los Cardenales eran matones, ¿no?}
{274}{}{Sí, pero vigilaban el área y no permitían que las cosas se salieran de control... Hasta cierto punto. De verdad espero que esta ola de violencia se acabe pronto, estoy seguro de que algún otro bastardo se apoderará del barrio y ocurrirá lo mismo de antes.}
{275}{}{Que vecindad tan bonita. Adiós.}
{276}{}{No es el resultado que esperaba. Buena suerte.}

# Re-dialogue
{300}{}{Y bien, ¿qué quieres?}
{301}{}{¿En qué te ayudo?}
{302}{}{Deberías irte, si sabes lo que te conviene.}
{303}{}{Adiós.}
{304}{}{¿Qué quieres?}
{305}{}{Oye, compadre, estás asustando a los inquilinos. Deberías irte a la central eléctrica, con los demás fenómenos.}
{1305}{}{Oiga... ¿señorita, creo...? Está asustando a los inquilinos. Debería irse a la central eléctrica, con los demás fenómenos.}


{310}{}{Los Seguidores fueron atacados e investigo el asunto. ¿Qué sabes al respecto?}
{311}{}{(2/3) Se ha obtenido un testimonio inicial relacionado a los ataques.}
{312}{}{(3/3) Se ha obtenido el testimonio final relacionado a los ataques. Hora de hablar con Aaron.}
{313}{}{(frunce el ceño y le dan tics nerviosos) ¿Así que eres otro lacayo de los seguidores? Ya les dije todo lo que sabía a los monjes, déjanos en paz.}
{314}{}{(frunce el ceño y le dan tics nerviosos) No pensaba que fueran capaces de convertirte. Pero, ya les dije todo lo que sabía a los monjes.}
{315}{}{Bueno, tendrás que repetirme tu historia.}
{316}{}{No matamos a nadie. Los monjes estaban pidiendo limosna en el barrio, pero no recaudaron nada. Una vez que salieron, unos tipos enmascarados los agarraron y fueron colgados en los postes de luz. No sabemos quién lo hizo, pero estaban preparados, eso es obvio.}
{317}{}{¿Hay algún lugareño que haya estado involucrado en esto?}
{318}{}{Los lugareños le tienen miedo a la gente de la iglesia. Nadie se atrevería a hacer algo así, menos si es tan cerca de nuestro hogar.}
{319}{}{Hay rumores de que a los lugareños no les agradan los monjes.}
{320}{}{¿Por qué deberían agradarnos? Mientras vivimos en la pobreza, los monjes gozan de una vida de lujo. Nos arrebatan nuestras armas y le prohíben la venta de medicamentos a Gónzales. Además, míranos - ¿en serio crees que uno de nosotros sería capaz de un ataque tan organizado?}
{321}{}{¿Quién podría haber hecho algo así?}
{322}{}{Sólo los necrófagos de la central eléctrica y la pandilla de Orris. Aunque, los necrófagos no se meten en los asuntos de la ciudad y Orris no querría meterse con la iglesia.}
{323}{}{Esas fueron todas mis preguntas.}
{324}{}{No te creo. Me estás ocultando algo.}
{325}{}{No sé nada más, si crees que estoy mintiéndote, dímelo con evidencia.}
{326}{}{Por hoy seré bueno y lo único que quebraré serán tus dedos, uno por uno, hasta que me lo cuentes todo.}
{1326}{}{Por hoy seré buena y lo único que quebraré serán tus dedos, uno por uno, hasta que me lo cuentes todo.}
{327}{}{Hmm...}
{328}{}{¡Por favor! ¡Basta! Piénsalo - ¿por qué atacaríamos a los monjes tan cerca de nuestro hogar? Es una locura. Pero, sé algo... hay rumores de un grupo secreto de 'pirofóbicos'. Recuerda que Aaron llevó a cabo una revolución con la ayuda de la Iglesia del Fuego Santo y asumió el control de la ciudad. Desde ese entonces, hay mucha gente que ha querido vengarse de él.}
{329}{}{Esta información es interesante, así que te dejaré ir.}
{330}{}{Basta de mentiras, es hora de quebrarte los dedos.}
{331}{}{Tienes muchas ganas de pelear, pero te demostraré que si es necesario, también podemos hacerlo.}
{1331}{}{Tienes muchas ganas de pelear, pero te demostraré que si es necesario, también podemos hacerlo.}
{332}{}{¡Bah!}
{333}{}{Vuelve a contarme lo que sabes sobre el ataque a los Seguidores.}

# Questions
{350}{}{¿Quién eres y qué es este lugar?}
{351}{}{Ya te lo dije, esto es una casa comunal. Soy Vernon, el gerente.}
{352}{}{Eso era todo lo que quería saber.}
{353}{}{¿Por qué habías dicho que esta área es peligrosa?}
{354}{}{Hay pobres y bandas, no son buenos compañeros en ninguna ciudad.}
{355}{}{¿De qué bandas estamos hablando?}
{356}{}{No debería haberlo dicho. Bueno, hay varias 'bandas' por aquí. Al este se encuentran los necrófagos de la central eléctrica, al norte de aquí está la pandilla de Orris, también hay bandas más pequeñas en cada esquina.}
{357}{}{¿Qué puedes contarme acerca de los necrófagos de la central eléctrica?}
{358}{}{Son gente extraña, se mantienen neutrales en todo momento y no se meten en los asuntos de la ciudad. La verdad no son una banda, pero de todas formas, sólo hay unos pocos que se les pueden acercar.}
{359}{}{¿Quién es Orris y por qué es conocida su pandilla?}
{360}{}{Orris es prácticamente el dueño de este barrio, no te metas con su pandilla, o vivirás muy poco.}
{361}{}{Estoy buscando a Steve, me han dicho que vive en esta área.}
{362}{}{No sé por qué quieres ver a ese canalla, ni me importa. Sé que últimamente ha estado viendo las peleas del cuadrilátero, espera ganarse unas chapas al apostar. Idiota.}
{363}{}{Vale, debo ir al cuadrilátero.}

# Quests
{370}{}{Me parece que estás en problemas. Puedo ayudarte.}
{371}{}{¿Lo dices en serio? Esta ciudad me ha enseñado que no puedes confiar en la gente amable. ¿Qué es lo que intentas hacer?}
{372}{}{Quiero ayudarte, de verdad.}
{373}{}{No te creo, así que para que sepas, no te daremos ni una sola chapa.}
{374}{}{Bueno, tenía la esperanza de hacerme una buena reputación en la ciudad.}
{375}{}{Ah, entiendo. Pero, si nos ayudas, no te podrás ganar ni una chapa. Sin embargo, una buena reputación puede ser igual de valiosa que el dinero.}
{376}{}{Si no quieres mi ayuda, eso está bien. Sólo te la ofrecía.}
{377}{}{Ya lo sé. ¿Qué problemas tienes?}
{378}{}{Hay un par de inquilinos que nos traen todo tipo de problemas. ¿Crees que puedas echarlos?}
{379}{}{Claro, ¿quiénes son?}
{380}{}{Preferiría no meterme en una disputa personal.}
{381}{}{El primero es Larry, es un adicto a las drogas y eso está arruinando su cabeza, aunque es un tipo listo. No puedo desalojarlo yo, pues a su camello no le gustaría perder a un cliente.}
{382}{}{Comprendo. ¿Y el otro?}
{383}{}{Badi. Vive en el otro extremo de la casa. No provocaba ningún problema hasta que se volvió un ludópata. Ahora está tan endeudado que hasta los guardias del casino me están amenazando a mí.}
{384}{}{Ya nadie quiere saber de él, o me paga la renta o lo sacas a la calle. Ya estoy cansado de esto.}
{385}{}{Recuérdame quién era el drogadicto que querías que desalojara.}
{386}{}{Larry. Debe estar en su habitación, desperdiciando su vida.}
{387}{}{Bien. Hasta luego.}
{388}{}{¿Quién era el inquilino que te debía la renta?}
{389}{}{Todos me la deben, pero Badi es el que me debe más. Además, sus problemas con el casino son un dolor de cabeza que no necesito.}
{390}{}{Una deuda al casino... eso es grave.}
{391}{}{Larry ya no molestará a nadie, ha muerto.}
{392}{}{¿COMO? Dios mío, ¿por qué tuvo que llegar a esto?}
{393}{}{Querías que me deshiciera de él.}
{394}{}{¡Pero así no! De por sí, los barrios bajos tienen una mala reputación, ahora la gente ni querrá acercarse a este lugar.}
{395}{}{Tendrías que haberme especificado eso, ya es demasiado tarde.}
{396}{}{Sí, supongo. Ojalá que pronto se olviden de esto. Al menos, sin Larry, este lugar será más silencioso.}
{397}{}{Le puedes encontrar algo bueno a todo. Adiós.}
{398}{}{Larry no volverá a molestar a nadie. Ha superado su adicción.}
{399}{}{¡Eso es increíble! ¿Cómo lo inspiraste? Ya nadie creía en Larry, todos pensábamos que era una caso perdido.}
{400}{}{Tengo mis métodos, lo que hacía falta era motivarlo.}
{401}{}{No sé qué decir. Gracias.}
{402}{}{De nada, Vernon.}
{403}{}{Vale, lo primero que haré será hablar con él.}

{404}{}{Badi ha dicho que podrá pagarte la renta, sólo debes darle un poco de tiempo.}
{405}{}{¡Eso es genial! Ya creía yo que nada lo salvaría de un castigo muy sangriento. ¿Cómo lo hiciste?}
{406}{}{La clave es encontrar el método correcto para cada persona, todos son distintos. Adiós.}
{407}{}{Badi ya no vivirá aquí, vivirá en la calle, igual que un perro.}
{408}{}{Eso es bueno, no nos hacen falta más problemas. Gracias por tu ayuda.}
{409}{}{De nada.}
{410}{}{Badi ya no vivirá aquí. O en ningún lado, realmente, porque está muerto.}
{411}{}{¿Lo... mataron? Dios mío, los guardias del casino son unas bestias.}
{412}{}{Fue su culpa.}
{413}{}{No me cuentes los detalles, sólo espero que su deuda no nos afecte a nosotros. Hubiera sido mucho mejor que se hubiera largado de aquí.}
{414}{}{No fue una solución limpia, pero al menos se resolvió tu problema. Adiós.}
{415}{}{Badi ha conseguido pagarle su deuda al casino, ya pronto podrá pagarte la renta.}
{416}{}{¡Eso es genial! ¿Cómo lo hiciste?}
{417}{}{La clave es encontrar el método correcto para cada persona, todos son distintos.}
{418}{}{Hiciste un buen trabajo, ya creía yo que nada lo salvaría de un castigo muy sangriento. Ya sabes cómo se pueden poner los guardias del casino, son unas bestias. Gracias por la ayuda.}
{419}{}{De nada, Vernon.}

{420}{}{He lidiado con tus problemas, al menos con los pequeños. ¿Te puedo ayudar en algo más?}
{421}{}{Somos pobres, no puedo creer que nos estés ayudando sin pedir algo a cambio. No he conocido a nadie que se parezca a ti. Sin embargo, siguen siendo problemas menores comparado a las dificultades de cada día.}
{422}{}{¿A qué te refieres?}
{423}{}{Nuestro problema principal es la pandilla de los Cardenales Rojos, porque controlan toda el área y a todos dentro de ella. Nadie se atreve a ir en su contra, hasta el gremio de mercenarios los evitan. Nos tienen controlados y cada vez se hacen más fuertes.}
{424}{}{Un momento, ¿me estás diciendo que quieres que los detenga? Estás loco. ¿Tienes idea de lo que estás pidiéndome?}
{425}{}{¿Cómo? No, no te pido nada, sólo me desahogo. Sé que detener a la pandilla debe parecer una locura. Pero... ya has hecho tanto por nosotros, quizás a ti se te ocurra algo. Podríamos ofrecerte las últimas chapas que nos quedan a cambio de la cabeza de Orris, la pandilla se desmoronaría sin él y nos dará algo de tranquilidad.}
{426}{}{Tendré que pensarme esto muy bien, si decido hacerlo. Nos vemos luego, Vernon.}
{427}{}{Vale, lo haré. Más te vale que tengas suficientes chapas para que esto valga la pena.}
{428}{}{¿Quieres que me encargue de esa banda? Claro. Son pandilleros, jamás han visto una pelea de *verdad*.}
{429}{}{¡Oh! Si consigues lidiar con Orris, te daré todas nuestras chapas. Si te encargas de él, su banda se debilitaría y nos dará algo de tranquilidad.}
{430}{}{Las chapas no importan, sólo quiero deshacerme de ese idiota.}
{431}{}{Prepara las chapas, porque su cabeza te costará todo lo que tienes.}
{432}{}{Dime qué sabes sobre los Cardenales Rojos.}
{433}{}{Ellos controlan el área entera, hay decenas de ellos y están bien armados, y por si fuera poco, saben luchar muy bien. Su líder se llama Orris, es un tipo que da miedo, es duro con cualquiera. Por favor, sálvanos del caos que provoca. Eres la única persona que quiere ayudarnos.}
{434}{}{He lidiado con Orris, así que durante un tiempo su pandilla no será ningún problema.}
{435}{}{¡Eres un verdadero héroe! Esperábamos a que sucediera un milagro, ¡y aquí lo tenemos! Ahora podemos tener la esperanza de que nuestra vida será distinta. Gracias, en serio.}
{1435}{}{¡Eres toda una heroína! Esperábamos a que sucediera un milagro, ¡y aquí lo tenemos! Ahora podemos tener la esperanza de que nuestra vida será distinta. Gracias, en serio.}
{436}{}{Eso es bueno. Lo importante es que ahora no hay nadie que los amenace.}
{437}{}{¿Por qué crees que me importa eso? Dame las chapas de una vez, no lo hice por ser amable.}
{438}{}{Eh, sí, puedes llevarte nuestras chapas. Son 217. Es todo lo que pudimos reunir.}
{439}{}{¡Imbécil! ¡Si hubiera sabido que era tan poco dinero, no hubiera arriesgado mi vida! Mierda. Dámelas.}
{1439}{}{¡Imbécil! ¡Si hubiera sabido que era tan poco dinero, no hubiera arriesgado mi vida! Mierda. Dámelas.}
{440}{}{Hmph. Eso es mejor que nada.}
{441}{}{Perdona, ya sé que es poco. Puedes quedarte aquí todo el tiempo que quieras.}
{442}{}{Adiós, Vernon.}
{443}{}{Puedes regresar las chapas que recolectaste, no hice esto por dinero, quería justicia.}
{444}{}{Eres sorprendente. Siempre te vamos a recibir con los brazos abiertos, jamás lo olvides, por favor.}
{445}{}{Adiós, Vernon.}
{446}{}{Gracias por habernos ayudado con Badi y con Larry, pero deberías irte y seguir con tu vida... No quiero tener más problemas.}
{447}{}{Intento ayudarte y esto me das a cambio...}
{448}{}{Tú te lo pierdes.}

{449}{}{Entre más me cuentas de él, más quiero matarlo.}
{450}{}{¿Son decenas? ¿Y están bien equipados? Esto se pone cada vez se pone mejor.}
