{100}{}{Ves a uno de los residentes de los barrios bajos de Fénix.}
{101}{}{Ves a un habitante de la casa comunal, es lamentable.}
{102}{}{Ves a un habitante de la casa comunal, se está metiendo el dedo en la oreja.}
{103}{}{Ves a un habitante de la casa comunal. Se está quitando la tierra del pelo con un cepillo.}
{104}{}{Ves a un habitante de la casa comunal. Enderezan con cariño sus harapos sucios.}
{105}{}{Ves a uno de los residentes locales. Tiene varios puntos calvos en su cabello, lo que indica sus terribles condiciones de vida.}
{1101}{}{Ves a una habitante de la casa comunal, es lamentable.}
{1102}{}{Ves a una habitante de la casa comunal, se está metiendo el dedo en la oreja.}
{1103}{}{Ves a una habitante de la casa comunal. Se está quitando la tierra del pelo con un cepillo.}
{1104}{}{Ves a una habitante de la casa comunal. Enderezan con cariño sus harapos sucios.}
{1105}{}{Ves a una de los residentes locales. Tiene varios puntos calvos en su cabello, lo que indica sus terribles condiciones de vida.}


{110}{}{Me estoy muriendo de hambre.}
{111}{}{Ojalá encuentre alguna rata para la cena.}
{112}{}{No puedo creer que antes tiraban el agua *limpia* por el retrete.}
{113}{}{No puedo hablar, eso da hambre.}
{114}{}{Necesitamos comida.}
{115}{}{Me han dicho que en las alcantarillas hay mutantes, y viven ahí desde la Gran Guerra.}
{116}{}{Encontraron a alguien muerto en el otro barrio.}
{117}{}{Ni se te ocurra apostar en el casino, o te harán un esclavo.}
{118}{}{Los Seguidores tienen espías por todos lados..}
{119}{}{Me daría miedo unirme a los cultistas.}
{120}{}{Hola.}
{121}{}{Nos vemos.}
{122}{}{Tengo que irme.}
{123}{}{Por favor, no nos causes problemas.}
{124}{}{¿Alguna vez te quitas esa cosa del brazo?}
{125}{}{¿Qué es una "televisión"?}
{126}{}{¿No se supone que un "buzón" es un basurero?}
{127}{}{Lo siento, pero tengo que quedarme quieto, o me da hambre.}
{128}{}{El agua sucia no sirve ni para apagar el fuego.}
{129}{}{¿Es cierto que en las montañas hay agua sólida y blanca?}
{130}{}{Aquí el cielo siempre está gris.}
{131}{}{No llueve hace años.}
{132}{}{Pude sobrevivir otro día. Vaya suerte.}
{133}{}{Los chatarreros revisaron por completo las ruinas.}
