{100}{}{Ante ti se encuentra un vendedor de chatarra.}
{101}{}{Estás viendo a un hombre bajo de atuendo ridículo. Su cabeza está torpemente adornada con un casco de numerosos artilugios.}

#Floating Lines
{110}{}{¡Tengo la mejor chatarra de toda la ciudad!}
{111}{}{Puedo encontrarte la parte que necesites para cualquier dispositivo.}
{112}{}{La tecnología antigua sí que era destacable.}
{113}{}{Compren un par de baquetas, nunca sabes cuándo las necesitarás.}
{114}{}{Si tu tostadora funciona mal, tráemela.}
{115}{}{La parte más difícil es hallar un foco intacto.}
{116}{}{Está oxidado, pero funciona.}
{117}{}{Aquí tengo un manual para un Sr. Mañoso.}
{118}{}{En vez de arriesgarte en una ruina, cómprame a mí.}
{119}{}{Me doy la vuelta un segundo y desaparece algo de la mesa. Maldita sea.}

#First Dialogue
{200}{}{¡Acérquese sin miedo, señor! Vendo basura y chatarra - eso es lo que usted necesita y lo puede encontrar justo aquí, en mi tienda.}
{1200}{}{¡Acérquese sin miedo, señorita! Vendo basura y chatarra - eso es lo que usted necesita y lo puede encontrar justo aquí, en mi tienda.}
{201}{}{Vaya, sí que tienes una buena selección de basura.}
{202}{}{}
{203}{}{¡No es basura, para nada! Todo lo que ve aquí es indispensable. Mire más de cerca. ¿Quizás necesite estas cucharas oxidadas? ¿O acaso prefiere comer con las manos sucias? Entonces, quizás le interese este tostador. Se le está saliendo el botón, pero sí que funciona. O puede que...}
{204}{}{Ve más lento, estoy intentando decidirme.}
{205}{}{Cállate de una vez, estúpida rata. No puedo pensar con tanto ruido.}
{206}{}{Ah, por cierto. Quería avisarte que desde la conmoción que hubo en la Catedral, el mercado entero subió sus precios, yo incluido.}
{207}{}{¿Por qué?}
{208}{}{Las chapas fueron idea de Aaron, su iglesia mantenía estable la tasa de cambio. Pero ya no hay iglesia y las chapas están perdiendo su valor. Puede que pronto debamos abandonarlas por completo.}
{209}{}{Ya veo. Supongo que es el momento adecuado para comprar todo lo que haga falta.}

{210}{}{¿Ya eligió algo, señor? Usted mire, sin compromiso.}
{1210}{}{¿Ya eligió algo, señorita? Usted mire, sin compromiso.}
{211}{}{No, quizás en otro momento.}
{212}{}{Déjame echar un vistazo a lo que tienes.}

#Questions
{220}{}{¿De dónde consigues estas cosas?}
{221}{}{Lo normal es que me las traigan los chatarreros y a veces las caravanas. Pero no les pregunto de dónde las consiguieron.}
{222}{}{Tendré que asumir que nada de esto es robado.}
{223}{}{Debí de haberlo adivinado.}

{224}{}{¿Quién comprará toda esta chatarra? Ya hay bastante en las ruinas.}
{225}{}{¿Quieres buscar entre las ruinas y encontrar algo tú? ¡Adelante! Pero no te olvides de la radiación, las bestias, los saqueadores, derrumbes y cualquier otro peligro que no dejarían ni un rastro de ti. No me dedico únicamente a vender estas cosas; también la reparo para que pueda serle de ayuda a su nuevo dueño, al menos por un rato.}
{226}{}{Ya escuché suficiente acerca de este tema.}
{227}{}{Tal vez te compre algo, déjame ver lo que tienes.}

{228}{}{Estás loco. Estas cosas quedaron obsoletas hace 90 años.}
{229}{}{¿Tienes una fuente mejor para conseguir cosas? Me encantaría verlas. Aunque, hace poco que han empezado a llegar más caravanas del sur. Traen cosas nuevas, hechas hace poco.}
{230}{}{Como sea. No voy a perder el tiempo charlando.}
{231}{}{Bueno, voy a tener eso en cuenta.}

#Quest to Find Vault 27
{240}{}{¿Te has topado con objetos de los Refugios?}
{241}{}{¿Refugios? De qué estás... ¡Ah, ya entiendo! Los Refugios de Vault-Tec; esos lugares son de leyenda. Se dice que algunos de nuestros ancestros vivieron allí después de la Gran Guerra, pero ya ha pasado tanto tiempo que ya nadie sabe en dónde están esos Refugios.}
{242}{}{¿Quién podría saberlo?}
{243}{}{Prueba a hablar con los Seguidores del Fuego. Hay tanta información en su biblioteca que ni saben que hacer con ella. Puede que tengan las coordenadas de los Refugios, pero no te las darán sin una buena razón.}
{244}{}{¿Qué hay de los chatarreros?}
{245}{}{Ja, ¿crees que un chatarrero que valga su peso en oro te revelaría la localización de un Refugio? ¡Las leyendas dicen que su interior está lleno de tesoros! Pero si eres de piquito de oro, prueba a hablar con Bob en los barrios bajos. Es uno de los chatarreros más viejos que hay en Fénix.}
{246}{}{De acuerdo.}

#Consultation on Items
{250}{}{Necesito tu consejo acerca de unos objetos antiguos.}
{251}{}{De eso se trata mi vida - los objetos del Viejo Mundo. Pero mi conocimiento no es gratis, cuesta algunas chapas.}
{252}{}{[}
{253}{}{]}
{254}{}{No importa. Quizás en otro momento.}
{255}{}{Quiero que veas otro objeto.}
{256}{}{Ya hablamos suficiente acerca de cosas viejas. Hablemos de algo más relevante.}
{257}{}{Cuídate.}
{258}{}{Háblame sobre lo que vendes.}
{259}{}{Claro, te pagaré.}


{260}{}{¿Qué es lo que te interesa, exactamente?}
{261}{}{[Caja Musical]}
{262}{}{Es sorprendente que el mecanismo todavía funcione. A un niño le encantaría algo así, eso es obvio.}
{263}{}{[Reloj Atómico]}
{264}{}{Vaya, no es normal ver un reloj de bolsillo en buenas condiciones. Y siempre se conoció a esta marca por su calidad. Además, la batería atómica va a durar décadas. Si los Hojalateros estuvieran aquí, la comprarían sin pensarlo dos veces.}
{265}{}{[Globo de Nieve]}
{266}{}{¡Nieve! Nunca he visto nieve de verdad, excepto en los picos de las montañas allá en el horizonte. Cualquier persona con dinero podría pagar una fortuna por un objeto como este. ¿Sabes? Yo podría hallarle un uso a este artefacto.}
{267}{}{[Medalla de Valor]}
{268}{}{La Operación Anchorage... He leído sobre esa masacre en unos periódicos viejos. Me parece que en ese entonces los Estados Unidos estaban muy orgullosos por su victoria. Ni siquiera sé a quién le interesaría un objeto así en estos tiempos. ¿Conoces a algún patriota que moriría por 'América'? Porque yo no.}
{269}{}{[Estrella de los Rangers]}
{270}{}{Esto se ve viejísimo... ¿Ranger de Arizona? He oído que su base está ubicada hacia el oeste, pero no sé exactamente en dónde.}
{271}{}{[Libro Sagrado]}
{272}{}{Creo que esto es un libro religioso, a los Seguidores del Fuego les interesaría un objeto así, eso no lo dudo.}
{273}{}{[Fotografía]}
{274}{}{¿Una fotografía de una explosión? ¡Es una bomba nuclear! Entonces así es como se veía... Da miedo. No deberías mostrarle esto a una persona cualquiera. Si quieres hablar de la Gran Guerra, deberías a encontrar a algún calvo al que le guste la historia.}
{275}{}{[Diente con una Corona]}
{276}{}{Es un diente con una corona. Déjame verlo con una lupa... Hmm... No, hay algo ahí. Necesito el microscopio... Hmm... Vaya. No es sólo una corona, es algún tipo de chip, o una llave magnética, o algo que almacene datos. Es demasiado complejo para mí, solo los Hojalateros podrían entender tecnología tan avanzada.}
{277}{}{[Bandera de Arizona]}
{278}{}{Una de las banderas del Viejo Mundo. La mayoría de estas banderas se han podrido, pero esta en particular está muy bien conservada, me sorprende. A esos colonos que hay al norte les gustaría tener algo así colgado, pero en nuestra ciudad hay pocas personas que recuerden los viejos días.}
{279}{}{[Holodisco de Videojuego]}
{280}{}{Parece que es un holodisco normal. Pero creo que no contiene datos, sino un programa. Prueba a insertarlo en una computadora funcional, no creo que tu Pip-Boy tenga tanta energía para eso.}
{281}{}{[Mi Pip-Boy]}
{282}{}{Hmm, es la primera vez que veo una computadora así de compacta... Espera, debería haber una sección acerca de los datos de salida... Hmm, Pip-Boy, modelo 2000, número serial... ¡Vaya, esto vino del Refugio 27! Es una de esos Refugios de Vault-Tec de los que hablan las leyendas. Así que sí existen.}
{283}{}{[Libro de la preguerra]}
{284}{}{Esto es un hallazgo poco frecuente. Es una fuente valiosa de la sabiduría de la preguerra - eso es lo que los Seguidores del Fuego dicen al respecto. Son los que suelen comprarlos, no hay mucha gente en Fénix que sepa leer y el conocimiento que hay en estos libros no le es de ayuda a la gente común.}
{285}{}{[Lata de Café]}
{286}{}{Estás de suerte, son granos de café. En el Viejo Mundo, solían hacer una bebida muy popular a partir de ellos. Y ahora el café se ha vuelto tan poco común que sólo se lo sirven a clientes con dinero en el casino de allá, en la otra calle.}
{287}{}{¿Podrías decirme en dónde puedo conseguir baterías para una motocicleta?}
{288}{}{Oh, en estos tiempos, eso es muy raro de encontrar y también es muy caro. Aunque he oído que los Hojalateros las fabrican en Two-Sun. Además, prueba a preguntárselo a los necrófagos de la central eléctrica, solían recibir baterías de colonias chatarreras como Ciudad Garaje. Y si llegas a pasar por unas ruinas que no hayan sido exploradas por chatarreros, puede que las encuentres allí.}

{289}{}{El comerciante ha bajado sus precios en un 5%.}
{290}{}{Quizás te interese esta cosa. Mira, si la agitas, parece que está nevando en su interior...}
{291}{}{¡Un globo de nieve! Jamás he visto la nieve de verdad, la única excepción es al ver los picos de las montañas que hay en el horizonte. Cualquier persona con dinero pagaría una fortuna por algo así... Oye, ¿qué tal si me vendes esta cosa? No lo necesitarás.}
{292}{}{¡De ninguna manera! Sólo quería saber lo que era. Eso es todo. Adiós.}
{293}{}{Déjame pensarlo. Por el momento, hablemos de otra cosa...}
{294}{}{No quiero nada, te lo regalo. Sólo está ocupando espacio en mi mochila y quiero librarme de él.}
{1294}{}{No quiero nada, te lo regalo. Sólo está ocupando espacio en mi mochila y quiero librarme de él.}
{295}{}{¿En serio? ¿Me lo vas a regalar? Gracias. Si alguna vez necesitas cosas viejas, ven directo a hablarme. Te daré lo mejor que tenga al mejor precio.}
{296}{}{Tendré eso en cuenta. Nos vemos.}
{297}{}{¿Sabes? Conseguir esta cosa no fue nada fácil, te la voy a dar por 350 chapas. ¡Y ni una chapa menos!}
{298}{}{¿Tanto? Uf... No será fácil encontrar a un comprador, pero hay una oportunidad. Bueno, aquí tienes las 350 chapas. Ahora dámelo. (agarra el globo y se queda mirándolo, encantado) Oooh...}
{299}{}{Ten cuidado con eso... Ah, lo que sea. Adiós.}

#Attack on the Followers
{300}{}{¿Viste lo que le ocurrió a los Seguidores? Fueron atacados en frente del casino.}
{301}{}{Sí, una pandilla atacó a los monjes. Que tipos más desesperados. ¿Por qué te importa?}
{302}{}{Aaron me pidió que lo investigara.}
{303}{}{¿Aaron, dices? Tienes agallas, vienes al mercado, interrogas a la gente y mientes acerca de conocer a nuestro gran líder. Ya le he dicho todo lo que sé a los Seguidores, y varias veces. Sal de aquí, yo no te diré nada.}
{304}{}{Perdona, no quería molestar.}
{305}{}{No me importa cuántas veces hayas hablado, porque AHORA me lo vas a decir a MÍ.}
{306}{}{Bueno, bueno, cálmate...}
{307}{}{¿Qué fue lo que pasó?}
{308}{}{Relájate, Aaron me envió, de verdad. Puedes confiar en mí.}
{309}{}{¿No confías en mí? En esta ciudad, no hay nadie que no confíe en mí.}
{310}{}{No te eches flores, viajero.}
{311}{}{Algún día, vas a pagar por esto.}
{312}{}{Mis disculpas, ya no te molestaré más.}
{313}{}{O me lo dices, o te quiebro el brazo.}
{314}{}{Bueno, los monjes andaban por la calle, no eran ninguna molestia. De repente, de varios callejones salieron unos tipos con pasamontañas, creo que eran unos cinco. En su mayoría estaban usando subfusiles. Luego de matar a los monjes, regresaron rápidamente a los callejones. Esos tipos planearon bien su ataque.}
{315}{}{Ya veo, pero si me estás ocultando algo, lo pagarás.}
{316}{}{Gracias, has sido de mucha ayuda.}
{317}{}{(2/3) Has adquirido un testimonio inicial relacionado al ataque.}
{318}{}{(3/3) Has adquirido un testimonio final relacionado al ataque. Hora de hablarle a Aaron acerca de esto.}
