{100}{}{Ves a un vendedor callejero.}
{101}{}{Ves a un negro despeinado con un delantal sucio.}

# Floating Lines
{110}{}{¿Tienes una mosca en la sopa? Pues... cómetela.}
{111}{}{Solo tengo que quitarle el moho - y listo, a la sopa.}
{112}{}{La carne de las ratas topo debe ser hervida durante un buen rato.}
{113}{}{¡Vengan, que se me está acabando lo bueno!}
{114}{}{¿Quieres más? Genial.}
{115}{}{¡Rata fresca!}
{116}{}{Carajo, me pica todo el cuerpo...}
{117}{}{Los pastores de San Brahmán te cobran un chingo.}
{118}{}{Sé que la carne se ve un poco... distinta... pero te gustará.}
{119}{}{¡Tengo carne de los mejores tramperos de la ciudad!}

# Start of Dialogue
{200}{}{(Conforme te acercas, el vendedor deja de golpear las moscas y pretende que no están paradas en la comida) ¿Qué te sirvo?}
{201}{}{¿Qué vendes?}
{202}{}{Sólo lo más fresco, directo del yermo. ¿Quieres una sopa de rata? ¡Están frescas! Justo hoy andaban dando su último paseo por la alcantarilla.}
{203}{}{Hmm, déjame pensar...}
{204}{}{Por cierto, tuve que subir mis precios después de lo que pasó con la Catedral.}
{205}{}{Bueno, es tu derecho.}

{210}{}{Bien, ¿qué quieres hoy?}
{211}{}{Nada.}
{220}{}{Me da miedo preguntarlo. ¿De dónde sacas la carne?}
{221}{}{Oye, ¿por qué te importaría de qué alcantarilla viene la rata? Me las traen de toda la ciudad. ¿Qué, acaso crees que voy a revisarlas todas?}
{222}{}{No debería haber preguntado...}
{223}{}{¿Tienes algo menos... asqueroso?}
{224}{}{A veces los chatarreros nos traen estas inolvidables cenas instantáneas de la preguerra. ¡Mmm! Pero sólo son para clientes especiales.}
{225}{}{Dame una antes de que se echen a perder.}
{226}{}{Quédate con esas cochinadas de la preguerra, yo quiero comida fresca.}
{227}{}{¿De la preguerra? Entonces no, no es lo que busco.}
{228}{}{...Pues, claro. (Saca unas cajas viejas del refrigerador)}
{229}{}{[Sigue]}
{230}{}{¿Tus clientes especiales incluyen a los Seguidores del Fuego, cierto?}
{231}{}{Creo que una propina te hará cambiar de parecer.}
{232}{}{(cuando te sonríe, te percatas de que sus dientes están chuecos) Gracias, compadre, gracias.}
{1232}{}{(cuando te sonríe, te percatas de que sus dientes están chuecos) Gracias, señorita, gracias.}
{233}{}{Bien, ¿y qué hay de esas cenas?}
{234}{}{La mitad de Fénix me conoce. ¿No me merezco algo de respeto?}
{235}{}{¿No crees que merezco respeto?}
{236}{}{No me hagas enojar, o haré pedazos tu negocio.}
{237}{}{Mis clientes regulares me piden que guarde esas cajas, me conviene más hacer eso que vendérselas a alguien que no conozco.}
{238}{}{Hmph. Bueno, ni las quería.}
{239}{}{(Abre los brazos) ¡Deja de chingar! Si no tienes chapas, ¡entonces piérdete! No alimento a los vagabundos.}
{240}{}{[Salir]}
{241}{}{¿De dónde sacaste tanta carne fresca?}
{242}{}{Son de esos pastores que están al oeste, por fin les funcionó la cabeza y decidieron comerciar con Fénix.}
{243}{}{Sí, creo que sé de qué hablas.}
{244}{}{¿En serio? Entonces sabes de lo que hablo. ¡Está muy fresca! Es carne de la mejor calidad, es cara, pero vale la pena. Mira, hasta engordé con un sólo filete. Parezco una rata embarazada. ¡Jaja!}
{245}{}{Pues, bien por ti. Ojalá que esa grasa te venga bien.}
{1245}{}{Pues, bien por ti. Ojalá que esa grasa te venga bien.}

{250}{}{¿Qué le pasó a Lloyd?}
{251}{}{Un matón de por ahí lo apuñaló hasta matarlo. Le pasa por andar presumiendo su traje nuevo.}
{252}{}{Pero, se lo compró con las chapas que yo...}
{253}{}{Vaya, entonces eres un cómplice, jeje...}
{1253}{}{Vaya, entonces eres una cómplice, jeje...}
{254}{}{Quizás tengas razón.}
{255}{}{Cuidado con lo que dices, o haré que las ratas te coman a ti.}

# Attack on the Followers
{300}{}{¿Qué sabes acerca del ataque a los Seguidores?}
{301}{}{Estoy ocupado cocinando. ¿Quieres una sopa de rata? No te arrepentirás.}
{302}{}{No tengo chapas, lo siento.}
{303}{}{Y yo no tengo tiempo para hablar. Perdón.}
{304}{}{Ya veo. Adiós.}
{305}{}{Ya entendí. Dame un platillo, por mientras, cuéntame lo que pasó.}
{306}{}{Perdona, pero con eso no te alcanza ni una cucharadita de sopa.}
{307}{}{Hmm, parece que conté mal.}
{1307}{}{Hmm, parece que conté mal.}
{308}{}{Mucho mejor. Come, pero no me ensucies el puesto. Bueno, ¿qué era lo que querías saber?}
{309}{}{Dime lo que sabes del ataque a los Seguidores cuando pasaban por el casino... Ay, me salió la cola de la rata.}
{310}{}{¡Insecto! ¡Métete la rata por el culo y dime lo que viste!}
{311}{}{¡Oye, oye! Ya entendí, perdón, no te quería enojar.}
{312}{}{Habla.}
{313}{}{Fue muy malo, los monjes estaban caminando por la calle, y entonces unos tipos con pasamontañas salieron de la nada, como si fueran ratas del alcantarillado. Los rodearon y empezaron a dispararles, jamás había oído tantos disparos juntos. Después de eso desaparecieron, como si nunca hubieran estado ahí, todo fue tan rápido.}
{314}{}{Muy bien. En el futuro, no me vuelvas a hacer enojar, porque te haré algo peor.}
{315}{}{Hmm, esto me deja más clara la situación.}
{316}{}{(2/3) Se adquirieron los primeros testimonios relacionados al ataque.}
{317}{}{(3/3) Se adquirieron los testimonios finales relacionados al ataque. Hora de hablar con Aaron.}
