{100}{}{Ves a una patachera.}
{101}{}{Estás viendo a una mujer con un mohicano y una chaqueta de cuero. Está a la última moda.}

#Floating Lines
{110}{}{Tira esos trapos viejos, yo tengo ropa decente.}  
{111}{}{Definitivamente necesitas un cambio de imagen.}  
{112}{}{Puedo coser bolsillos rotos.}  
{113}{}{Esa chaqueta se está descosiendo por las costuras.}  
{114}{}{¿Necesitas chanclas nuevas? Están hechas de neumáticos.}  
{115}{}{¡Tengo vendajes para los pies!}  
{116}{}{Este pijama ocultará tus muchos defectos.}  
{117}{}{Vendo ropa, directa de los almacenes de antes de la guerra.}  
{118}{}{Los sombreros de fieltro y los trajes de negocios ya no están de moda.}  
{119}{}{Los Seguidores del Fuego saben un par de cosas sobre como vestirse.}

#First Dialogue
{200}{}{Hola. Tengo topo tipo de ropa, desde la casual hasta de trabajo. Adelante, sin miedo.}
{201}{}{Vaya, esto es mejor que los trapos sucios que usan en mi pueblo.}
{202}{}{Esta ropa debe tener unos cien años, no es sorpresa que todos den tanto miedo.}

{210}{}{¿Qué te llama la atención?}
{211}{}{Nada.}
{212}{}{Hmm, déjame probarme eso de ahí...}

#Questions
{220}{}{¿De dónde consigues toda esta ropa?}
{221}{}{La mitad está hecha a mano, la otra mitad me la traen los exploradores. A veces encontramos almacenes intactos con ropa de la preguerra, pero no es algo común estos días.}
{222}{}{Ya veo.}
{223}{}{¿De dónde consiguen sus túnicas los Seguidores del Fuego?}
{224}{}{Las hacen ellos mismos, obvio. Y sé que no están dispuestos a compartir sus secretos con nosotros, los mortales.}
{225}{}{Entonces, ¿esta ropa era considerada buena antes de la Gran Guerra?}
{226}{}{Eso parece, no la diseñaron pensando en que las usarías mientras caminas entre las ruinas de Fénix. Hoy en día, la gente necesita ropa distinta - más práctica, supongo.}
{227}{}{Ya veo.}
{228}{}{No quiero usar ropa vieja...}
{229}{}{Hmm. Creo que nuestros ancestros pensaban que esos trajes estaban a la moda. Ah, los viejos tiempos... Bueno, olvídalo.}

#Glasses
{230}{}{¿Esto es todo lo que vendes?}
{231}{}{Te puedo hacer algo a la orden.}
{232}{}{De acuerdo, necesito algo especial para impresionar a los demás.}
{233}{}{Me lo pensaré.}
{234}{}{Pues... La gente de hoy en día no se impresiona con la ropa... Pero estás de suerte, tengo estas gafas de sol, están en excelente estado. No es normal encontrarse algo así en estos tiempos.}
{235}{}{Sí, te vendría bien. Te recomiendo estas gafas de sol para cubrir tus... eh... quemaduras. Al menos desde lejos no asustarás a la gente.}
{236}{}{Sí, no te haría daño. Tengo unas gafas de sol, están a la última moda. Son geniales para esconder tu vista, así nadie sabrá a dónde mirás o qué estás pensando.}
{237}{}{Puedes quedártelas, lo pensaré.}
{238}{}{Veamos, ¿qué puedo darte a cambio...?}
{239}{}{Muéstrame lo que tienes.}

#Metal Armor
{240}{}{¿Y una armadura? ¿Puedes hacer eso?}
{241}{}{Esa no es mi especialidad, la gente normal no necesita armaduras y en primer lugar muy pocos se la pueden permitir. Pero si alguien la necesita, puedo hacerla a la orden, con un avance.}
{242}{}{Te puedo dar 50 chapas.}
{243}{}{No seas así, sé que debes tener un alijo secreto para los clientes especiales.}
{244}{}{¿Para qué quieres una armadura? No irás a la guerra; llévate una chaqueta de cuero.}
{245}{}{Puede que sí. Bueno, olvídalo.}
{246}{}{De acuerdo, olvídalo.}
{247}{}{Está bien, pero recuerda: no hay reembolsos. Y tampoco te garantizo protección contra las balas.}
{248}{}{Sólo toma las chapas, me arriesgaré.}
{249}{}{Gracias por el aviso.}
{250}{}{¿Siquiera haz visto 50 chapas juntas en tu vida?}
{251}{}{¡Las tenía a mano, lo juro!}

#Follower's Robe
{260}{}{Necesito una túnica de los Seguidores del Fuego.}
{261}{}{(observa a su alrededor con cautela) Escúchame, no sé por qué buscas eso, pero no quiero problemas.}
{262}{}{Te pagaré lo que sea, nadie lo sabrá.}
{263}{}{No temas, tenemos un amigo en común que me envió a hablar contigo.}
{264}{}{¿Se te cayó el cerebro? ¡Si vendo una de sus túnicas me van a matar!}
{265}{}{Te acabas de perder un montón de chapas. Enhorabuena.}
{266}{}{Perdona, no quería molestar.}
{267}{}{Ah, eso cambia las cosas. Espero que sepas lo que haces.}
{268}{}{No hay problema, sólo estaba de paso.}
{269}{}{Está bien, esto es lo que tengo. Pero no vuelvas a pedírmelo - es demasiado peligroso.}
{270}{}{De acuerdo.}

#Vault Suit
{280}{}{Oye, eso es uno de esos legendarios monos del refugio. ¿En dónde lo conseguiste?}
{281}{}{Me lo encontré.}
{1281}{}{Me lo encontré.}
{282}{}{Es herencia de mis ancestros.}
{283}{}{Cuánta suerte. Déjame adivinar, no sabes en dónde encontrar más, ¿verdad? Quiero que sepas que son un verdadero hallazgo. Si encuentras más, tráemelos, a cambio te daré un *buen* precio.}
{284}{}{Claro. Pero primero, muéstrame lo que vendes.}
{285}{}{Entonces iré a buscar más.}
{286}{}{Aquí tienes un mono del refugio, justo lo que querías.}
{287}{}{¡Vaya! Por fin, puedo tirar esta chaqueta apestosa. Oye, no te olvides de tus chapas. Y, gracias.}
{288}{}{De nada.}
{289}{}{Las chapas son lo más importante. No es necesario agradecerme.}
{290}{}{¿Cuál es la historia de estos monos?}
{291}{}{Bueno, es una antigua leyenda. Dicen que antes de la Gran Guerra, construyeron varios refugios alrededor de Fénix. Algunas personas sobrevivieron a la Guerra y luego salieron de allí para reconstruir la ciudad. Pero, las historias no son muy claras.}
{292}{}{[Seguir]}
{293}{}{Además, mis padres tenían un mono del refugio. Para mí, era un recuerdo especial. Pero por desgracia, hace un buen tiempo que el traje se quebró.}
{294}{}{Eso es una historia interesante.}
{295}{}{Tengo un mono del refugio para ti.}
{296}{}{¿Otro? Vaya, sí que te encuentras todo lo bueno. Aquí están tus chapas.}
{297}{}{De nada.}
{298}{}{Genial, pero necesito una cosa más.}

#Attack on the Monks
{300}{}{¿Qué fue lo que viste durante el ataque a los Seguidores?}
{301}{}{¡Oye! No me metas en esto, yo solo vendo ropa, no vi nada.}
{302}{}{Pues perdón, no te preguntaré nada más.}
{303}{}{Más te vale que hables, perra. O haré pedazos a tu miserable tienda.}
{304}{}{¿Qué es lo que quieres? Dios... Ya, unas personas en pasamontañas salieron de los callejones y empezaron a dispararle a los monjes. Luego desaparecieron, no le hicieron nada a los demás. ¡Eso es todo lo que sé!}
{305}{}{Gracias, ahora no le haré nada a tu tienda.}
{306}{}{Te creeré. Por ahora.}
{307}{}{Relájate, puedes confiar en mí.}
{308}{}{Supongo, pero de verdad no sé nada del ataque. Déjame sola}
{309}{}{Te lo prometo, no estás en ningún peligro.}
{310}{}{Claro... O le desagrado a los Seguidores o a sus enemigos.}
{311}{}{Pues, sí. Dime lo que pasó.}
{312}{}{Bueno... unas personas en pasamontañas salieron de los callejones y empezaron a dispararle a los monjes. Luego desaparecieron, no le hicieron nada a los demás. Eso es todo lo que sé.}
{313}{}{Hmm, eso es interesante. Gracias.}
{314}{}{Te creeré. Por ahora.}
{315}{}{(2/3) Se ha adquirido un testimonio inicial relacionado a los ataques.}
{316}{}{(3/3) Se ha adquirido el testimonio final relacionado a los ataques. Es hora de hablar con Aaron acerca de esto.}
