{100}{}{Ves a Bart Thur.}
{101}{}{Estás viendo al dueño de la tienda de armas, está obsesionado con ellas.}
{102}{}{¡Oh, es la servoarmadura! He oído tanto acerca de ella, pero jamás la había visto.}
{103}{}{No toques eso. No atiendo a los drogadictos, ¿quién sabe en qué andas pensando?}

#Start of dialogue
{200}{}{(te observa con recelo, mientras considera qué podría venderte) ¿Qué clase arma necesita, señor? ¿Una de caza, o para asustar a los saqueadores? Tengo muchas armas, para cualquier propósito.}
{1200}{}{(te observa con recelo, mientras considera qué podría venderte) ¿Qué clase arma necesita, señorita? ¿Una de defensa personal? Tengo muchas armas, para cualquier propósito y presupuesto.}
{201}{}{Déjame echar un vistazo...}
{202}{}{Déjame ver tus armas más de cerca.}

{210}{}{(limpia un arma cariñosamente, mientras espera que digas algo)}
{211}{}{Bueno, ya debo irme.}
{212}{}{Ya veo.}

{213}{}{Alguien entró al gremio de mercenarios y mató a Bruce Turner.}
{214}{}{Sí, lo sé.}
{215}{}{Quien sea que haya sido el culpable, ojalá que ese cabrón recibida su merecido. Perdí un buen cliente por culpa suya.}
{216}{}{No te pongas así, puede que haya otro gremio en el futuro.}
{217}{}{¿Así que los abastecías con armas? No deberías haber hecho eso.}

#Questions
{220}{}{¿De dónde consigues estas armas?}
{221}{}{Toda arma que veas aquí tiene una historia. Pongamos de ejemplo a este revólver, me lo vendió un apostador del casino al que se le acabó la suerte. Esta otra arma, se la quitaron a un saqueador luego de un asalto a su campamento. Las caravanas traen algunas del sur. Pero, ¿importa? Lo importante sobre un arma no es su origen, sino que no te defraude durante una batalla.}
{222}{}{¿Qué es eso que dijiste acerca de las caravanas sureñas?}
{223}{}{Más al sur, está el asentamiento de los Hojalateros. Saben mucho acerca de la tecnología antigua y prácticamente la veneran. Han arreglado un montón de máquinas y ahora están reparando cosas y produciendo objetos. Por ejemplo, aquí está su última creación... (saca algo y te lo muestra)}
{224}{}{[Más]}
{225}{}{Una lanza neumática. Su mecanismo funciona a través de un pistón y un resorte. No utiliza electrónica ni pólvora. (te demuestra la lanza con talento) La empujas contra el cuerpo del enemigo, y - ¡Toma! - sale dispara una pequeña cuchilla y penetra la carne. No te preocupes, luego de eso, regresa automáticamente con el resorte. Entonces, lo que más cuenta será tu habilidad.}
{226}{}{¿Todavía traen armas del sur?}
{227}{}{Hay algunos aventureros de por aquí que fueron allá y consiguieron algo de carroña. Pero tarde o temprano, el flujo de armas del sur se acabará. Lo importante es que los Hojalateros se han separado y ya no hay más reparos o producción de su parte. Para toda Fénix, su trabajo era esencial.}

#Product Reveal
{230}{}{¿Qué hay en esas estanterías cubiertas?}
{231}{}{Es mi mejor mercancía. Pero está reservada para mis clientes especiales. No eres uno de ellos, por el momento.}
{232}{}{¿Por qué esa restricción?}
{233}{}{A los Seguidores del Fuego no les agrada que le venda armas potentes a cualquiera. Piensan que podrían utilizarlas en contra de la iglesia. Así que lo mejor que tengo va para ellos, los guardias del casino, el gremio de los cazarrecompensas y otras personas de confianza.}
{234}{}{¿Por qué cubres parte de la mercancía}
{235}{}{Quiero ver tu armamento especial.}
{236}{}{Lo siento, pero mi mejor mercancía está reservada para mis clientes especiales. Todavía no eres uno de ellos.}
{237}{}{¿Por qué esa restricción?}
{238}{}{En ese caso, estoy perdiendo el tiempo en este lugar.}
{239}{}{Bueno, entonces muéstrame lo que tienes a la venta para una persona común.}

{240}{}{Hmm... De acuerdo. (te muestra sus bienes y las presenta con una mirada satisfecha) Aquí está lo mejor que Fénix puede ofrecer.}
{241}{}{Santo Dios, esto es suficiente para capturar una ciudad entera.}
{242}{}{¿Y esto era la mercancía especial? Que decepción.}

{243}{}{Los Seguidores del Fuego están acabados, su culto no durará mucho más. Olvida ese acuerdo.}
{244}{}{Hace poco me volví un iniciado de la Catedral.}
{1244}{}{Hace poco me volví una iniciada de la Catedral.}
{245}{}{Después de tantas victorias en el cuadrilátero, ¿crees que no soy de confianza?}
{246}{}{Soy parte de los Rangers de Arizona. Necesito un arma confiable.}
{247}{}{Don Diego me recomendó tu tienda. No lo decepciones.}
{248}{}{¿Tus clientes son muy variados, no? [Di la contraseña del Partido de la Liberación]}
{249}{}{Anda, te daré buenas ganancias.}
{250}{}{Eso no es nada convincente.}
{251}{}{Bueno, ¿pero qué hay del resto de las armas?}
{252}{}{En ese caso, me largo.}
{253}{}{Poseo contactos a través de toda Arizona, hacer tratos conmigo está entre tus mejores intereses.}
{254}{}{No seas así. ¡Soy de confianza!}
{255}{}{Yo no te traeré ningún problema. Mi reputación habla por sí misma.}
{256}{}{Si no me vendes tu mejor material, puedo matarte y ya.}
{257}{}{Mis amigos son saqueadores. ¿Quieres que los llame?}
{258}{}{Lo entiendo. Enséñame lo que tienes a la venta para una persona común.}
{259}{}{También puedes confiar en mí. "Prefiero morir de pie que vivir de rodillas."}

{260}{}{¿Algo más?}
{261}{}{Sí, una última cosa.}
{262}{}{No necesito nada más. Adiós.}

#Discounts and fines
{280}{}{(al reconocerte, el vendedor se anima) Ah, eres tú. Me alegra verte en mi tienda.}
{281}{}{Eso me suena a que me harás un descuento..}
{282}{}{Claro, claro... Siempre le daré un descuento a la gente respetada. Tengo que respetar el crecimiento de la ciudad, incluso al hacer negocios.}
{283}{}{Genial, lo agradezco.}
{284}{}{(al reconocerte, el vendedor cambia cautelosamente de postura, como si esperase que hicieras algo) Hola. ¿Necesitas algo?}
{285}{}{Estaba pensando en comprar un arma...}
{286}{}{Escoge algo rápido y piérdete. Este no es una guarida de saqueadores. Y recuerda, los pendejos como tú tendrán que pagar extra si quieren que los atienda.}
{287}{}{Lo que tú digas, güey. Necesito un arma, no importa el precio.}
{288}{}{Deberías tratar bien a todos tus clientes. El mundo está cambiando, y rápido.}

{290}{}{Oye, ¿crees que puedes venir aquí después de la explosión en la Catedral? A los ciudadanos no les gustará que siga haciendo negocios con ustedes, cultistas...}
{291}{}{Es precisamente por eso que necesito un arma, debo defenderme.}
{292}{}{Hmm, vale. Te venderé lo que necesites, pero nada de descuentos, ¿bien?}
{293}{}{Las chapas no serán ningún problema. Muéstrame lo que tienes.}
{294}{}{No necesito ni tus condolencias ni tu mercancía, imbécil.}
{295}{}{Me parece que no quieres que esté aquí. Me voy.}

#Education
{300}{}{¿Puedo probar un arma antes de comprarla? Me gustaría practicar en mis habilidades de tiro.}
{301}{}{Puedes practicar en el campo de tiro todo lo que gustes y así practicar tus habilidades, mientras pagues por la munición y la renta del arma.}
{302}{}{Necesito practicar con armas pequeñas, aquí tienes 500 chapas.}
{303}{}{Voy a usar practicar con las armas grandes, te daré 1.000 chapas.}
{304}{}{Me vendría bien practicar con armas de energía. Toma, 2.000 chapas.}
{305}{}{Tengo que practicar con armas arrojadizas, ten, 250 chapas.}
{306}{}{Con estos precios, me vendría mejor comprarme el arma y ya.}
{307}{}{Esto es una estafa, me largo.}
{308}{}{Ahorra algunas chapas si quieres mejorar tus habilidades.}
{309}{}{De acuerdo.}

#Equipment of bullets
{330}{}{Necesito modificar mi munición.}
{331}{}{Puedo modificar la munición de bengalas y de escopeta. No hay por qué meterse con las pistolas y los rifles.}
{332}{}{[Mejora los cartuchos de bengala]}
{333}{}{[Mejora los cartuchos de bengala mejorados]}
{334}{}{[Reemplaza el cartucho de escopeta por el tipo bala]}
{335}{}{1 chapa por cartucho. ¿Cuántos necesitas?}
{336}{}{2 chapas por cartucho. ¿Cuántos necesitas?}
{337}{}{Todavía no lo sé, sólo quería saber los precios.}
{338}{}{Son demasiado débiles, ¿no? No están hechas para golpear a objetivos que tengan vida. Pero puedes hacerlos más fuertes y que así sean letales.}
{339}{}{No necesito esto.}

{340}{}{Hecho. ¿Algo más?}
{341}{}{Sigo teniendo munición que necesita ser modificada.}
{342}{}{Puede que me interese algo distinto a la munición.}
{343}{}{No, adiós.}
{344}{}{Te falta algo, ¿verdad? Ve a mirar, tengo muchos bienes a la venta.}
{345}{}{Un cartucho.}
{346}{}{Dos cartuchos.}
{347}{}{Tres cartuchos.}
{348}{}{Cuatro cartuchos.}
{349}{}{Cinco cartuchos.}

#Improving weapons
{350}{}{¿Sabes modificar armas?}
{351}{}{Muéstrame tus juguetes y veré qué puedo hacer con ellos.}
{352}{}{Creo que no puedo hacer nada con eso.}
{353}{}{Quizás no, por ahora.}
{354}{}{}
{355}{}{¿Podrías montar una mira en mi rifle de caza?}
{356}{}{Puedo montar una mira de francotirador x10 de la marca Unertl. Es fantástica para disparos a una distancia lejana, pero de cerca no te ayudará en nada. De hecho, hará lo contrario.}
{357}{}{¿Cuánto cuesta?}
{358}{}{ chapas. Se paga de inmediato.}
{359}{}{Necesito esa mira. Toma, las chapas y el rifle.}
{360}{}{¿Te falta algo?}
{361}{}{Sí, tendremos que hacer esto después.}
{362}{}{(con una mirada satisfecha, evalúa su trabajo y te otorga el producto final) ¿Algo más?}
{363}{}{Sí, no cierres.}
{364}{}{No, no necesito nada más.}
{365}{}{Necesito un cargador más grande para un subfusil del calibre 22.}
{366}{}{Sí, ese cargador de la vieja .22 no da a basto. Pero estás de suerte, tengo un cargador tipo tambor que le quedará perfecto. Aumentará el cargador de 30 cartuchos a 60.}
{367}{}{Eso me vendrá bien, quiero el tambor. Ten, las chapas y el arma.}
{368}{}{¿Hay alguna forma de hacer que esta picana sea más fuerte?}
{369}{}{Sí, me puedo encargar de eso.}
{370}{}{Vale la pena. Hazlo.}
{371}{}{¿Tienes alguna mejora de capacidad para mi AK-112?}
{372}{}{Sí, un cargador de 40 cartuchos en vez de las 24 estándar. Sólo me queda uno.}
{373}{}{Dámelo.}
{374}{}{Diez cartuchos.}
{375}{}{Toda la munición que tengo.}
{376}{}{¿Podrías convertir mi pistola de bengalas para que dispare cartuchos de escopeta?}
{377}{}{Fácil. Pero recuerda que no es una escopeta. El cartucho será más poderoso que una bengala, pero será más difícil dispararlo con una sola mano.}
{378}{}{¿Podrías mejorar esta pistola láser?}
{379}{}{He trabajado con este modelo antes. Hay una forma de mejorar la emisión del láser.}
{380}{}{Arregla este rifle roto.}
{381}{}{Bien, solo tendré que reemplazar unas cuantas partes.}

#Quests
{400}{}{¿Será que una de tus armas le disparó a los monjes afuera del casino?}
{401}{}{¿Cómo? ¿Quién eres tú como para hacerme una pregunta así?}
{402}{}{Lo siento. Estoy investigando el ataque, en el nombre de Aaron. ¿Te puedo hacer unas preguntas?}
{403}{}{No sé nada que tú no sepas sobre el ataque. Y dudo que hayan comprado las armas en mi tienda.}
{404}{}{¿Por qué?}
{405}{}{Yo hago las preguntas, tú las respondes. ¿O acaso quieres tener problemas con los Seguidores del Fuego?}
{406}{}{Ya me interrogaron cuatro personas antes de que llegaras tú, les dije todo lo que sé. Dudo que hayan utilizado armas de mi tienda.}
{407}{}{Eso es sospechoso. Esta es la única tienda de armas que hay, ¿no?}
{408}{}{Puede que mi tienda sea la única en la ciudad, pero puedes conseguir armas en todos lados. Las personas con más armamento en la ciudad deben ser los Seguidores del Fuego. Por un tiempo, amasaron todas las armas posibles para empezar una revolución. Además, como parte de nuestro acuerdo, debo abastecerlos con el mejor armamento posible.}
{409}{}{Entonces, ¿quién pudo haber atacado a los monjes?}
{410}{}{¿Me lo preguntas a mí? Para detective, no vales nada. Habla con los del tianguis... es decir, el mercado. Ellos lo vieron todos.}
{411}{}{De acuerdo, hablaré con ellos. Pero recuerda, todo el que haga mal a los Seguidores será castigado. No hay escape.}
{412}{}{Gracias, fuiste de mucha ayuda. Cuídate.}
