{100}{}{Ves al cantinero.}
{101}{}{Ves al cantinero. No es ninguna sorpresa hallarlo aquí adentro.}
{102}{}{No, no, si lleva puesta esa cosa... ese 'traje', romperá todo los platos...}
{103}{}{Por favor, tome asiento.}
{104}{}{Necesito volver al bar.}

#Floating lines
{110}{}{Luces de las Vegas y un filete de brahmán.}
{111}{}{Lo siento, pero se nos acabo el Nuka-Ron.}
{112}{}{Ya preparé el "Ceniza de Los Angeles", está listo.}
{113}{}{Aquí tiene su "Nuclear Mary."}
{114}{}{¿Quién ordenó el Cóctel Atómico?}
{115}{}{Ya bebiste suficiente, amigo.}
{116}{}{No lo bebas de un sólo trago.}
{117}{}{Te lo juro, este cóctel te dará una erección.}
{118}{}{¿Tus padres te dieron permiso, verdad? Bromeo.}
{119}{}{¿Café? Puta madre, eres todo un experto.}

#Dialogue
{200}{}{¿Es tu primera vez en el casino? Espero que disfrutes tu estadía.}
{201}{}{Eso espero...}
{202}{}{¿Por qué te preocupas tanto? Relájate, este es el único lugar de la ciudad en donde puedes darte un respiro.}
{203}{}{No necesito tu compasión.}
{204}{}{¿Sí? Bueno, quizás deba quedarme un rato.}
{205}{}{Sírveme algo fuerte, porque voy a ganar en grande.}
{206}{}{¡Ese es el espíritu! Buena suerte.}
{207}{}{Los que necesitarán eso son ustedes.}
{208}{}{Gracias.}

{210}{}{¿Quieres algo para beber?}
{211}{}{Por ahora no.}

{212}{}{¡Vaya, pero si eres el nuevo campeón! Esto es genial. Mira, sé que me estoy saliendo de las reglas, pero toma, una cerveza - la casa invita. De verdad, eres genial. (habla en voz baja) Ahora se lo podré contar a todos...}
{1212}{}{¡Vaya, pero si eres la nueva campeona! Esto es genial. Mira, sé que me estoy saliendo de las reglas, pero toma, una cerveza - la casa invita. De verdad, eres genial. (habla en voz baja) Ahora se lo podré contar a todos...}
{213}{}{Gracias, eso es muy amable de tu parte.}
{214}{}{Tus tragos saben a meado, pero me gusta tu actitud.}

{215}{}{Ah, eres tú. ¿Cómo está Don Diego? Parece que se llevan bien.}
{216}{}{Cállate y sírveme un trago.}
{217}{}{Nos llevamos bien, sí. ¿Cuál era la bebida de la que estaba hablando?}
{218}{}{Te sugiero que pruebes nuestro tequila, es el mejor que te podrás encontrar. (se te acerca y baja la voz) Por cierto, el casino tiene precios más bajos para su propia gente.}
{219}{}{¿Precios más bajos? Eso es bueno.}

{220}{}{¿Qué hay del tiroteo que pasó allá afuera?}
{221}{}{Es sospechoso. Alguien atacó a unos monjes mientras caminaban sin molestar a nadie. Yo no vi nada, pero escuché muchas versiones de lo que pasó. No te creas todos los rumores que escuches.}
{222}{}{Dime lo que sabes y te ganarás unas chapas.}
{223}{}{Mira, no nos gusta hablar de estas cosas. Dejémoslo ahí.}
{224}{}{Hmph. Si me entero de que estás escondiendo algo, lo pagarás.}
{225}{}{Claro, lo entiendo. Olvida esto.}

{230}{}{¿Quién está a cargo por aquí?}
{231}{}{Estamos en un periodo de... transición. Desde que mataron a Don Diego, a veces me cuestiono quién está a cargo realmente. (pensativo) Bueno, al menos no estoy desempleado.}
{232}{}{Ya veo.}
{233}{}{¿Quieres hablar con el gerente? Está en ese cuarto de allá, al lado del escenario.}
{234}{}{No, te pregunto quién es el dueño de este lugar.}
{235}{}{El dueño del negocio es Don Diego. Él fue quien puso en marcha todo esto y restauró el casino. ¿Por qué lo preguntas?}
{236}{}{Me daba curiosidad, eso es todo.}
{237}{}{Quiero hablar con él.}
{238}{}{Eso no será fácil. Habla con el gerente, él decide quién tiene permitido ver al jefe.}
{239}{}{De acuerdo.}

{240}{}{¿Has visto a George Crook?}
{241}{}{(apunta hacia arriba con desagrado)}
{242}{}{¿Qué? ¿¡Está muerto!? No puede ser, que pena... Ah, está arriba, claro.}
{243}{}{¿Está en el segundo piso? Bien.}

{250}{}{Tú sabes todo lo que ocurre por aquí, ¿verdad?}
{251}{}{Lo siento, pero no vendo rumores o información. Al jefe no le gusta.}
{252}{}{Entonces no tengo nada que hacer aquí..}
{253}{}{Ya veo, no hay problema.}
{254}{}{Pensaba que los cantineros lo sabían todo.}
{255}{}{No te equivocas, pero tengo que seguir las reglas.}
{256}{}{Te... daré propina.}
{257}{}{Eso no cambiará nada, señor.}
{1257}{}{Eso no cambiará nada, señorita.}
{258}{}{Hmm. Entonces hagamos esto - te pagaré si creas rumores buenos acerca de mí.}
{259}{}{No lo entiendo, ¿acaso es una broma? Ya tienes una reputación excelente en esta ciudad, ¿acaso buscas ser una leyenda o algo así?}
{260}{}{Sí, puede ser... Bueno, olvídalo.}
{261}{}{Bueno, iré a gastar mis chapas en algo más significativo.}
{262}{}{Ah, ya entiendo, necesitas una buena reputación para tu... carrera. Sí, te puedo ayudar con eso.}
{263}{}{No hay prisa. Hablemos de esto después.}
{264}{}{Tengo que ir a buscar mis chapas. Nos vemos.}
{265}{}{Te pagaré 100 chapas, sólo necesito algunos rumores en mi favor.}
{266}{}{Hmm, puedo crear alguna historia acerca de lo confiable que eres. No hay problema.}
{267}{}{Necesito que crees algo bueno, pero no tanto. Te daré 200 chapas.}
{268}{}{¿Una emocionante lucha callejera, o una historia impresionante del yermo? Inventaré algo y los demás hablarán de ello.}
{269}{}{Aquí tienes 300 chapas, necesito que lo hagas lo mejor que puedas.}
{270}{}{Quizás... (chasque los dedos) ¡Una leyenda! Ya sé que hacer, cuenta conmigo.}
{271}{}{Aquí están tus chapas. Esperaré los resultados, compañero.}
{272}{}{Lo haré lo mejor que pueda, señor.}
{1272}{}{Lo haré lo mejor que pueda, señorita.}
{273}{}{Nos vemos.}
{274}{}{¿Algún problema? Está bien, puedo esperar.}
{275}{}{Eh, espera, tengo que contar mis chapas...}

{280}{}{¿Sólo sirves bebidas alcohólicas?}
{281}{}{Sí. Puedo ofrecerte agua limpia, si gustas. Pero sólo unos pocos pueden permitirse ese lujo.}
{282}{}{¿En dónde consiguen el alcohol?}
{283}{}{Tenemos muchas fuentes, unos destiladores locales producen la cerveza, y a veces entre las ruinas se encuentra algo especial, como whiskey de la preguerra. Pero nosotros producimos el tequila.}
{284}{}{¿Ustedes lo producen? ¿Bromeas?}
{285}{}{Es nuestro orgullo, encargamos la materias prima a las plantaciones del sur. A partir de ello, preparamos bebidas y alcohol médico. Por lo que sé, somos los únicos en el negocio.}
{286}{}{¿Entonces de verdad lo producen? Eso es impresionante.}
{287}{}{Hmm, ¿alcohol casero? Eso no suena muy seguro.}
{288}{}{Agua, cerveza, whiskey y por supuesto, nuestro tequila casero.}
{289}{}{De acuerdo.}
{290}{}{Quiero ordenar un poco de su famoso tequila, pero no tienen, por lo que veo.}
{291}{}{Lo siento, pero tenemos algunos problemas en la producción. Estamos trabajando para solucionar el problema, pero llevará un tiempo.}
{292}{}{Eso es una pena, ojalá que encuentren una solución.}
{293}{}{¿Un casino sin bebidas? Este lugar es un chiste.}
{294}{}{Tenemos muchas fuentes, unos destiladores locales producen la cerveza, y a veces entre las ruinas se encuentra algo especial, como whiskey de la preguerra. Solíamos destilar tequila, pero se quebró el alambique. Estamos intentando ponerlo en marcha otra vez.}
{295}{}{¿Solían destilar su propio tequila? Vaya, vaya. Sigue hablando.}
{296}{}{¿Eran productores caseros? Que pena que no sigan con ello.}
