{100}{}{Ves al gerente del casino.}
{101}{}{Estás viendo a un hombre bien vestido que vigila el casino.}
{102}{}{No deberías llevar puesta esa cosa dentro del casino.}

#First dialogue
{200}{}{Bienvenido a nuestro casino, el *único* funcional en toda Arizona.}
{201}{}{Esto no es nada impresionante, pensé que estaría más... lleno.}
{202}{}{Debería estarlo, pero los ciudadanos de Fénix están pasando por tiempos difíciles y eso afecta nuestro negocio. Pero que puede hacer uno, ¿no?}
{203}{}{Sí, tienes razón.}
{204}{}{Este lugar es increíble. Cuesta creer que hayan conseguido repararlo.}
{205}{}{Se requirieron años de esfuerzo y determinación. Es todo gracias a Don Diego.}
{206}{}{Ya veo..}
{207}{}{¡Guau!}

#Re-dialogue
{210}{}{¿Puedo ayudarle en algo?}
{211}{}{No, estoy bien.}
{212}{}{Hasta luego.}

#Banning casino games
{220}{}{Eso espero. ¿Por qué no me dejan jugar en el casino?}
{221}{}{}
{222}{}{Con gusto seguiremos dándote la oportunidad de jugar, pero únicamente con las chapas que posees. No te daremos más.}
{223}{}{¿Por qué?}
{224}{}{¿Me lo puedes explicar?}
{225}{}{No es difícil deducir que si alguien gana demasiado, le hace daño a las ganancias del casino. Ya has ganado suficiente como para vivir el resto de tu vida cómodamente.}
{1225}{}{No es difícil deducir que si alguien gana demasiado, le hace daño a las ganancias del casino. Ya has ganado suficiente como para vivir el resto de tu vida cómodamente.}
{226}{}{Entonces eso de 'La casa siempre gana' es mentira. No me engañas.}
{227}{}{Entiendo tu lógica, pero que porquería.}
{228}{}{Por favor, no te molestes. Siempre apreciamos a un cliente con dinero. Déjame darte un pequeño regalo de parte del casino para demostrar que somos amistosos. Esta botella contiene whiskey de la preguerra, el de *verdad*. No está ni envenenado ni irradiado. Estos días, es un placer poco común y muy caro.}
{229}{}{¿Nada más? Esto no será suficiente para curar el dolor de mi alma.}
{230}{}{Gracias por el regalo.}
{231}{}{También te invitamos a quedarte en nuestra habitación de lujo y así disfrutar la comodidad de nuestro casino. Aquí tienes la llave.}
{232}{}{Así está mejor.}
{233}{}{Eres muy agradable.}
{234}{}{Disfrute su estadía... Ah, por cierto. Don Diego... sabe de ti, y quiere hablar contigo. Ya le he hecho saber a los guardias que te dejen pasar.}
{235}{}{Dile que lo visitaré cuando tenga tiempo libre. Adiós.}
{236}{}{Me gustaría tener una charla con él, ciertamente.}
{237}{}{Disfruta tu estadía con nosotros.}
{238}{}{Sí, lo que sea.}
{239}{}{Nos vemos.}

#Questions
{250}{}{¿Tú diriges este casino?}
{251}{}{En cierto modo. Mi nombre es Bill Gatsby, soy el gerente. Pero, Don Diego es el dueño de este lugar.}
{252}{}{Don Diego - ¿quién es él?}
{253}{}{Ya veo.}
{254}{}{¿Cómo? ¿Nunca has oído hablar de él? Es un hombre, con H mayúscula. Es una de las personas más respetadas de la ciudad, pero usualmente se mantiene en su oficina y dirige las cosas desde allí.}
{1254}{}{¿Cómo? ¿Nunca has oído hablar de él? Es un hombre, con H mayúscula. Es una de las personas más respetadas de la ciudad, pero usualmente se mantiene en su oficina y dirige las cosas desde allí.}
{255}{}{¿Por qué le dicen Don?}
{256}{}{Supongo que es una señal de respeto. No sé cómo o por qué empezaron a decirle así.}
{257}{}{¿Puedo hablar con él?}
{258}{}{No lo creo. Él sólo recibe a gente cuando se trata de algo particularmente importante.}
{259}{}{En cierto modo. Mi nombre es Bill Gatsby, soy el gerente.}

{270}{}{¿Cómo estás lidiando con la muerte de Don Diego?}
{271}{}{El casino prácticamente funcionaba por sí mismo. Y ahora debo ocuparme del trabajo de dos personas, por supuesto. Pero estos son problemas momentáneos. Al fin y al cabo, Diego no hacía más que estar sentado en su silla, yo era quien hacía el trabajo de verdad.}
{272}{}{Ya veo.}
{273}{}{Pienso que subestimas su contribución a este negocio... De todas formas, cambiemos de tema.}

{275}{}{Veo que el casino sigue abierto después de la explosión.}
{276}{}{Sí, fue un suceso terrible. Tuvimos suerte de que la explosión fuera subterránea y lejana. Y aun así, el edificio sufrió daños graves. Lo habremos reparado para que esté en su estado original dentro de un año... Bueno, eso espero.}
{277}{}{Ya veo.}
{278}{}{Eso es difícil de creer.}

{280}{}{Dicen que algunos Seguidores fueron asesinados cerca del casino.}
{281}{}{Sí, es una tragedia. Personalmente, yo no vi nada y no me gustaría parafrasear los rumores que he escuchado. Háblale a aquellos que estaban en la calle ese mismo día.}
{282}{}{Claro que lo haré.}
{283}{}{O, ¿quizás estás protegiendo a tu casino? Tal vez no fue un accidente que el ataque haya sucedido cerca.}
{284}{}{(el rostro del gerente se retuerce debido a la tensión) No merecemos tal calumnia. ¿Posees evidencia en nuestra contra? Eso creía. Entonces es mejor que terminemos esta conversación. Gracias por su comprensión.}
{285}{}{Eres demasiado escurridizo. Más te vale que el casino no esté metido en esto.}
{286}{}{Por supuesto, te creo. Olvida lo que dije.}

#GG is your own man
{290}{}{Adelante, amigo. Bienvenido a la familia de Don Diego. Ahora eres uno de nuestros hombres, la familia valora a su gente y no la abandona cuando se meten en problemas. Pero también debes seguir las reglas. No hagas enojar a tu jefe - esa es la primera.}
{1290}{}{Adelante, señorita. Bienvenida a la familia de Don Diego. Ahora eres uno de nuestros hom... Digo, una de nosotros. La familia valora a su gente y no la abandona cuando se meten en problemas. Pero también debes seguir las reglas. No hagas enojar a tu jefe - esa es la primera.}
{291}{}{Eso está claro, Bill. Lo entiendo.}
{292}{}{Genial, por fin te lo puedo decir a la cara - eres un pésimo administrador. ¿Lo sabías?}
{293}{}{Sabes, tus palabras son parcialmente verdad. Pero Don Diego no encontró a nadie mejor para esta posición. Como mínimo, al menos él y yo tenemos una confianza total cuando se trata de dirigir el casino.}
{294}{}{Sí, claro.}
{295}{}{Adelante, toma asiento. Ahora eres uno de los nuestros, la familia valora a su gente y no la abandona cuando se meten en problemas. Pero recuerda, no toleramos a los traidores. No hagas enojar a Don Diego - de esa forma no sólo salvarás tu pellejo, sino también a tu familia entera. Espero que no deba repetírtelo.}
{296}{}{Eso está claro, Bill. Lo entiendo.}
{297}{}{Sé que no te agrado, pero debemos trabajar juntos.}
{298}{}{Soy el gerente, estoy por encima de tales cosas. Si el jefe confía en ti, entonces puedo ignorar mis prejuicios personales.}
{299}{}{Bien pensado, Bill.}
{300}{}{Es bueno que nos entendamos. (te entrega una llave con una etiqueta) El jefe me dijo que te otorgue una habitación. Ni siquiera yo he tenido tal honor. Aprecia su generosidad.}
{301}{}{¡Por fin! Puedo vivir en condiciones más humanas.}
{302}{}{Por cierto, si decides relajarte en el casino, ten en cuenta que todos deben seguir las mismas reglas. Si quieres jugar a la ruleta, compra fichas como cualquier otro jugador. Si te endeudas, el casino no lo borrará de tu cuenta. ¿Entendido? Bien.}
{303}{}{Me parece justo. Bueno, debo irme.}
{304}{}{Voy a tratar este casino como si me perteneciera.}
{305}{}{¡Guau!}
{306}{}{Ajá.}
{307}{}{¡Guau!}

#Work and access to the boss
{320}{}{¿Están contratando? Busco trabajo.}
{321}{}{No, ya tenemos suficientes empleados. Don Diego me pidió que ya no lo moleste con ese tipo de preguntas.}
{322}{}{Entonces adiós.}
{323}{}{Dame una oportunidad, yo podré encargarme de cualquier trabajo que me des.}
{324}{}{Hmm. Demuestra de lo que eres capaz y veremos si vales la pena.}
{325}{}{Te escucho.}
{326}{}{Aún así, díselo a tu jefe. ¿Y si resulta que está interesado en tenerme como socio?}
{327}{}{Eso no servirá de nada. Tu perfil... no posee lo que necesitamos para verte como socio. ¿Lo entiendes?}
{328}{}{Sí, lo entiendo. Algunas personas son muy arrogantes.}
{329}{}{No hay problema, lo entiendo.}
{330}{}{Ambos somos personas respetadas en la ciudad, deberíamos hablar. ¿No crees?}
{331}{}{Puede ser. Tu presencia ya es conocida en la ciudad. Puede que a Don Diego le interese hablar contigo.}
{332}{}{Genial. ¿Cuándo podré verlo?}
{333}{}{Tu jefe debe tener algún trabajo para mí. ¡Es por algo que vencí a todos en el cuadrilátero!}
{334}{}{Hmm, siempre nos viene bien alguien capaz. En especial alguien con tu nivel de talento.}
{335}{}{Genial. ¿Puedo hablar con tu jefe?}
{336}{}{Don Diego me dijo que podía pedirte un trabajo. ¿Cuál es tu problema?}
{337}{}{Ah, así que eres nuestro nuevo empleado. Es muy agradable que uno pueda aliviarse el peso de la responsabilidad de sus hombros, al menos en cosas menores.}
{1337}{}{Ah, así que eres nuestra nueva empleada. Es muy agradable que uno pueda aliviarse el peso de la responsabilidad de sus hombros, al menos en cosas menores.}
{338}{}{Te escucho.}
{339}{}{No imaginas el desastre que dejó la muerte de Don Diego. De verdad me vendría bien un empleado con cerebro.}

{340}{}{Don Diego hablará contigo y nuestros guardias ya saben que estás de camino. La oficina de Don Diego está en el segundo piso. Demuéstrale respeto, enfunda tu arma y puede que las cosas terminen bien. ¿Lo entendiste? Ve.}
{341}{}{Sí, eso es obvio, no hacía falta explicarlo.}
{342}{}{Ah, no te preocupes. Seré la cortesía misma.}

{350}{}{Uno de nuestros clientes habituales se ha olvidado por completo acerca de pagar sus deudas. Hace falta darle un... recordatorio. Y asegurarse de que su deuda se pague.}
{351}{}{Eso debe ser muy fácil. ¿Cuál es el detalle?}
{352}{}{No creo que tenga una sola chapa a su disposición. Se dice que está completamente borracho y está a punto de ser echado de su hogar. Si es así, perderemos un cliente y junto a él, las chapas. Por cierto, nos debe }
{353}{}{ chapas... Hay que anotar eso.}
{354}{}{Se llama Badi, lo encontrarás en los barrios bajos, hacia el este. Ve, soy un hombre ocupado.}
{355}{}{De acuerdo, consideralo hecho.}
{356}{}{Acerca de Badi y su deuda...}
{357}{}{¿Tienes sus chapas a mano?}
{358}{}{Tristemente no, todavía estoy trabajando en ello.}
{359}{}{¿Me puedes recordar en donde vive ese perdedor?}
{360}{}{(frunce el ceño con disgusto) Vive en los barrios bajos, hacia el este. Se llama Badi.}
{361}{}{Comprendo. Gracias.}
{362}{}{¿Cuánto le debe al casino?}
{363}{}{ chapas. Chapas. No dejes que ese perdedor te engañe con un trueque o algún tipo de servicio. Debes tener cuidado con gente como él.}
{364}{}{ chapas, se las debe al casino.}
{365}{}{Badi está muerto. No puedo hacer nada más.}
{366}{}{¿Está muerto? (niega con la cabeza) Me temo que estas desagradables noticias van a decepcionar mucho a mi jefe. Bueno, has fallado con lo que se te encargó. Piérdete. No nos hace falta gente que es incapaz de hacer lo que se le pide.}
{367}{}{Está bien...}
{368}{}{Tengo su deuda, las }
{369}{}{ chapas. No preguntes cómo lo hice.}
{370}{}{(levanta las cejas con algo de sorpresa) Bien hecha. Agradecemos tu... asistencia en este problema. Quizás *sí* valgas la pena. Esto es lo que te corresponde - un quinto del monto de la deuda.}
{371}{}{Gracias. Adiós.}
{372}{}{Entonces, ¿he demostrado lo que valgo? ¿Quizás tu jefe tenga otro trabajo para mí?}
