{100}{}{Ves a Matthias.}
{101}{}{Estás viendo a uno de los Seguidores. Parece estar sumido en sus pensamientos.}
{102}{}{Adelante, acólito.}
{1102}{}{Adelante, acólita.}
{103}{}{Matthias se encuentra orando lo más rápido que puede, está rogando por la salvación de toda la humanidad.}
{104}{}{. . .}
{105}{}{Puedes contar con mi eterna gratitud, porque de ahora en adelante, la iglesia podrá regresar a su misión original.}
{106}{}{La operación fue un fracaso, pero esto no es el fin. Debes asesinar a Aaron y a su Asesor, por el bien de toda Fénix.}
{107}{}{La operación fue un fracaso, pero esto no es el fin. Debes asesinar a Aaron, por el bien de toda Fénix.}
{108}{}{La operación fue un fracaso, pero esto no es el fin. Debes asesinar al Asesor, por el bien de toda Fénix.}

{200}{}{¿Cómo osas interrumpirme mientras estoy orando? Sal de aquí.}
{201}{}{Eh...}

#Questions
{210}{}{Por favor, estoy orando, no me interrumpas.}
{211}{}{Lo que tú digas.}
{212}{}{¿Quién eres?}
{213}{}{Soy Matthias. Ahora sal de aquí y deja la puerta cerrada.}
{214}{}{Pero...}
{215}{}{Matthias, cuéntame lo que haces aquí.}
{216}{}{Estoy perdiendo el tiempo, porque hablo contigo. Sal de mi habitación.}
{217}{}{Espera...}
{218}{}{Por lo que vi, no me parecía que estuvieras rezando.}
{219}{}{Argh... Podría estar más concentrado, si sólo no interrumpieran mi meditación a todo momento.}
{220}{}{Bueno, ¿estás rezando, o estás meditando? Parece que ni tú lo sabes.}
{221}{}{Hmm. Eres peor que una mosca en verano. ¿Qué es lo que quieres?}
{222}{}{Quiero hablarte, eso es todo.}
{223}{}{No es nada, olvídalo.}

{230}{}{Esto es ridículo. Si necesitas respuestas, deberías bajar al salón del primer piso y hablar con los predicadores.}
{231}{}{Entonces haré eso. Adiós.}
{232}{}{Tienes razón, hermano. Perdona, no quería molestarte.}
{233}{}{¿A dónde debo ir para conseguir un mentor?}
{234}{}{No necesitas uno, eso es obvio.}
{235}{}{Antes de hacer una pregunta así, deberías preguntarte si lo necesitas.}

#Rebel Quest
{250}{}{Marcos me dijo que hablara contigo.}
{1250}{}{Marcos me dijo que hablara contigo.}
{251}{}{Marcos... ¿Quién es él?}
{252}{}{Espera, ¿no te avisó que yo iba a venir?}
{253}{}{Tu incertidumbre es similar a los susurros atómicos en el vientre de una explosión nuclear. Sal de aquí y vuelve sólo cuando tus ideas estén claras.}
{254}{}{Eh, lo que tú digas...}
{255}{}{Ya sabes de quién hablo. El tipo que se esconde en el subterráneo y busca vengarse, igual que tú.}
{256}{}{Sí, por supuesto... La venganza... El vil sentimiento de los seres atómicos que se ganan la vida a duras penas. No te atrevas a compararme a él, el residente de esas pútridas alcantarillas. Todo mi ser se ve sumido en la depresión al siquiera pensar en lo que Aaron le hizo a la Iglesia del Fuego Santo.}
{257}{}{Entonces, debes estar en contra de las decisiones de Aaron.}
{258}{}{Tus motivos no nos importan, lo que importa es que tenemos el mismo objetivo.}
{259}{}{Nuestro mundo está hecho trizas, y la iglesia solía iluminarlo con el conocimiento de la preguerra. Nuestro estandarte no era un símbolo de guerra, sino de paz. No derramábamos sangre, sino que evitábamos que fluyera en primer lugar. Sin embargo, Aaron le vendió su alma al diablo. Ya no puedo soportar esto.}
{260}{}{Bien, ¿y qué podemos hacer para arreglar eso?}
{261}{}{El punto no es matar a Aaron. A fin de cuentas, la iglesia es mucho más grande de lo que aparenta ser. Nos encontramos enlazados a otras facciones de Arizona, pues nuestro estandarte está liderando a comunidades enteras por un nuevo camino. No puedes eliminar a una sola persona y esperar a que detenga todo el proceso.}
{262}{}{¿Qué es lo que propones, Matthias?}
{263}{}{Es necesario que destruyas la Catedral, y con eso, a la Iglesia. Sé que esto debe parecerte una locura, pero tal cosa es posible. Bajo la Catedral existen niveles subterráneos en donde unos científicos junto al Asesor han estado desarrollando un arma nueva durante varios años. Es capaz de destruir la Catedral.}
{264}{}{Un arma de ese tipo le hará daño al resto de la ciudad.}
{265}{}{Este mundo es frágil y la Iglesia ya le ha hecho suficiente daño. No temas, puedo asegurarte de que la ciudad se mantendrá intacta.}
{266}{}{¿Por qué no lo haces tú?}
{267}{}{Sólo se me permite descender allí si cuento con una buena razón. Ya lo he intentado. Pero, tú posees la ventaja del elemento sorpresa.}
{268}{}{No es una mala idea, pero, me gustaría salir de eso con vida.}
{269}{}{Debes infiltrarte en la oficina del profesor e instalar los fusibles que el arma necesita, al activarla, contarás con algunos minutos para escapar de la Catedral.}
{270}{}{Entiendo... Pero, ¿cómo voy a entrar? Debe ser un área restringida.}
{271}{}{Voy a otorgarte con la llave y una túnica de los Seguidores. Debes presentarte ante los guardias como un novato y que se te pidió que te presentes al profesor.}
{1271}{}{Voy a otorgarte con la llave y una túnica de los Seguidores. Debes presentarte ante los guardias como una novata y que se te pidió que te presentes al profesor.}
{272}{}{Dame esa llave y la túnica, iré de inmediato.}
{273}{}{Que el Fuego Santo nos perdone. Amén.}
{274}{}{Eh... Lo que tú digas, Matthias.}

{275}{}{Aaron y su Asesor se encuentran bien protegidos, pero si actúas de forma decidida y con rapidez, ya contarás con la fuerza que necesitas. Es necesario que los tomemos por sorpresa en las distintas partes de la Catedral para que no puedan unir fuerzas. Hay monjes que no son violentos y me aseguraré de que no interfieran durante tu ataque.}
{276}{}{Genial, voy a dar la señal para que empiece el ataque, habla con los monjes ahora mismo.}
{277}{}{¿Crees que sea posible hacer esto sin matar a nadie?}
{278}{}{Por desgracia, Aaron y sus aliados no estarán dispuestos a rendirse sin dar pelea. Sin embargo, hay otra opción. Bajo la Catedral existen niveles subterráneos en donde unos científicos junto al Asesor han estado desarrollando un arma nueva durante varios años. Es capaz de destruir la Catedral.}
{279}{}{Creo que eso sería muy complicado, es mejor que sólo ataquemos la iglesia. Voy a dar la señal para que empiece el ataque, por el momento, da el aviso a los monjes.}
{280}{}{Ese plan es una locura. Me encanta.}
{281}{}{Si queremos la paz, eres nuestra última esperanza. Te daré esta llave que te permitirá bajar al sótano en donde se ubica el Asesor y le daré la señal a los demás monjes que piensen igual a mí, de esa forma no te atacarán. Ve, y Hazlo.}
{282}{}{Fantástico.}

# Aaron's Quest
{300}{}{Tengo algo de lo que hablarte, se trata de los ataques contra los monjes.}
{301}{}{Si tienes que contárselo a la primera persona que te encuentras, es obvio que tu investigación ha llegado a un callejón sin salida.}
{302}{}{Te doy la razón, no sé cómo puedo avanzar. ¿Qué crees que debería hacer?}
{303}{}{No desesperes, pero tampoco bajes la guardia. Los acólitos no son los únicos que están en peligro - si alguien le lleva la contraria a nuestros adversarios, también serán un objetivo.}
{304}{}{No me ayudas en nada.}
{305}{}{Eh, gracias por tu "consejo".}

{310}{}{Al contrario, debido a los informes de la biblioteca, es obvio que *tú* estás muy atento a la agenda de los acólitos.}
{311}{}{Por supuesto. Cuento con acceso a esa información, pues soy uno de los guardianes de la Catedral. Y, si no deseas arder en la hoguera junto a los demás herejes, te sugiero que busques evidencia más significativa antes de que empieces a acusarme. Fuera de mi vista.}
{312}{}{No tan rápido, también sé que has utilizado la radio para enviar mensajes encriptados.}
{313}{}{Pero...}
{314}{}{De hecho, *tengo* evidencia, estabas enviando mensajes encriptados por radio. ¿A quién? Y, ¿por qué?}
{315}{}{Como un guardián de la iglesia, no puedo permitir que un forastero escuche mis comunicaciones. Pero TU, ¿cómo conseguiste acceso a la estación de radio? Esto es muy sospechoso.}
{316}{}{Deberías preocuparte de los registros de la biblioteca, porque es obvio que estabas vigilando a los acólitos.}
{317}{}{No es lo que piensas...}
{318}{}{Puedo convencer a Aaron de que lleve a cabo una investigación completa de tus pertenencias y contactos. ¿Qué tienes que decir sobre eso?}
{319}{}{Estás agotando mi paciencia, gusano atómico. Fuera de aquí.}
{1319}{}{Estás agotando mi paciencia, larva atómica. Fuera de aquí.}
{320}{}{Si haces eso, el que saldrá mal parado no seré yo.}
{321}{}{¡Ah, santo cielo! Llegaste hace poco a la Catedral y ya has indagado más a fondo que los profetas de Vault-Tec.}
{322}{}{¿Vault... qué?}
{323}{}{Así que lo admites, le has estado filtrando información a los enemigos de la iglesia.}
{324}{}{No irrumpas la paz que hay en estas habitaciones. Si tus preguntas necesitan respuestas, te las daré, pero en un lugar más tranquilo. Te veré en el confesionario del primer piso. No temas, hace años que no he podido correr.}
{325}{}{Claro, pero ni te atrevas a intentar engañarme, o si no...}
{326}{}{Por supuesto, en un lugar como este, hasta las paredes tienen que tener ojos y oídos.}

# Dialogue in the confessional
{330}{}{Debo decirlo, no esperaba que un novato que vino del yermo podría resolver este caso. Había conseguido esconder mis acciones, incluso de Aaron... hasta ahora.}
{1330}{}{Debo decirlo, no esperaba que una novata que vino del yermo podría resolver este caso. Había conseguido esconder mis acciones, incluso de Aaron... hasta ahora.}
{331}{}{Eres uno de los 'leales' siervos de Aaron, ¿por qué ayudas a sus enemigos?}
{332}{}{Porque la iglesia ha alterado sus creencias bajo el liderazgo de Aaron. Una vez fue una fortaleza de santidad y sabiduría, pero en este momento es un receptáculo de pecado. Ya no puedo soportar esto.}
{333}{}{Cuéntame lo que pasó.}
{334}{}{Hace una década, solíamos ser una iglesia pacífica, estábamos aislados de los demás. Preservábamos las reliquias y el conocimiento de la preguerra para heredarlo a aquellos que fueran dignos de recibirlos.}
{335}{}{Y, ¿encontraron a esas personas, no?}
{336}{}{Desde el sur provino un nuevo grupo de hombres, pero resultaron ser para nada dignos. Consiguieron atraer a los demás priores a su lado, y junto al apoyo del resto de la iglesia, consiguieron llevar a cabo una revolución en la ciudad. Aaron se hizo el Señor de Fénix, pero antes de eso, sólo era un clérigo de rango medio.}
{337}{}{Y eso no te gustó para nada, por lo que veo.}
{338}{}{Debíamos preservar el conocimiento antiguo, esa era nuestra misión. Deberíamos de haber sido más cuidadosos con quienes tenían permitido estar cerca de nosotros. Hemos cometido un terrible error, y por eso, todos nosotros acabaremos en el Infierno Nuclear.}
{339}{}{Entonces, ¿quiénes están atacando a los acólitos?}
{340}{}{¿Quién es la gente a la que estás ayudando?}
{341}{}{Es una larga historia... Desde que ocurrió la revolución, ha habido un grupo de rebeldes que opera en Fénix, se hacen llamar el 'Partido de la Liberación'. Hasta el momento, han intentado mantener un perfil bajo para amasar sus fuerzas y eventualmente, derrocar a Aaron. Aunque no esté de acuerdo con ellos en todo, hemos llegado a un acuerdo para expulsar a la iglesia de la ciudad.}
{342}{}{¿Me puedes explicar por qué no debería estropear tus planes?}
{1342}{}{¿Me puedes explicar por qué no debería estropear tus planes?}
{343}{}{Pero eres un prior de la Catedral, ¿por qué estás ayudando a sus enemigos?}
{344}{}{No me importa qué te motiva, sólo dime por qué no debería cerrar este caso de una vez.}
{345}{}{Tarde o temprano, Aaron descubrirá quién está filtrando información. Pero no es mi vida la que me preocupa, sino la misión de la iglesia.}
{346}{}{¿Estás intentando que me pase a tu lado?}
{347}{}{Así es. Te sugiero que te encuentres con los rebeldes y hablen de todo esto, cara a cara.}
{348}{}{Esto es una idiotez, voy a decirle todo esto a Aaron.}
{349}{}{En ese caso, no me dejas opción. Que el Fuego Santo nos perdone...}
{350}{}{Eh...}
{350}{}{Eh...}
{351}{}{Bien, estoy contigo. Será interesante saber la otra versión de este conflicto.}
{1351}{}{Bien, estoy contigo. Será interesante saber la otra versión de este conflicto.}
{352}{}{Que así sea. Debes hallar el cuartel general de los rebeldes bajo Union Station. El alcantarillado es la única forma de llegar allí, diles que te he enviado yo, mientras lo consigues, intentaré avisarles de tu llegada. Te deseo suerte.}
{353}{}{Nos vemos, Matthias.}
{354}{}{He cambiado de opinión, voy a contárselo a Aaron.}
{1354}{}{He cambiado de opinión, voy a contárselo a Aaron.}
{355}{}{Has lo que debas hacer, acólito.}
{1355}{}{Has lo que debas hacer, acólita.}
{356}{}{Vale.}
{357}{}{Necesito saber cuál de los Cardenales Rojos le está filtrando información a la iglesia.}
{358}{}{¡Qué pregunta tan insolente! Incluso si lo supiera, ciertamente no te lo diría.}
{359}{}{Pero no niegas que hay un espía.}
{360}{}{Hemos posicionado espías a través de toda la ciudad y ellos nos proporcionan informaciones de formas muy distintas. Eso no es ninguna sorpresa.}
{361}{}{Por el momento, eso es todo lo que quería saber.}
{362}{}{Puedo confiar en ti, ¿o me equivoco? Murphy es uno de nosotros, se infiltró en la pandilla y ascendió de rango para que esas pobres almas pudieran acercarse al camino correcto.}
{363}{}{Gracias por contarme esto.}
