{100}{}{Ves a un guardia.}
{101}{}{Ves a un guardia de caravana, se prepara para un largo viaje.}
{1101}{}{Ves a una guardia de caravana, se prepara para un largo viaje.}

{110}{}{Genial.}
{111}{}{Dame un respiro.}
{112}{}{Tengo sed.}
{113}{}{Ya hora de irnos.}
{114}{}{¡Qué pinche calor hace!}

{115}{}{Háblale al jefe, yo sólo cuido la carga.}
{116}{}{No tenemos más espacio, para que sepas.}
{117}{}{Tenemos que venderlo todo, o vamos a quebrar.}
{118}{}{Llevamos bienes a casi cualquier lugar del yermo.}
{119}{}{Deberías ir al Atomic Rush, nos gusta relajarnos allá.}

{120}{}{Hoy será un largo día.}
{121}{}{Ya quiero que esto se acabe.}
{122}{}{¿Qué día es hoy?}
{123}{}{Estoy muy cansado.}
{124}{}{Es hora de la siesta, supongo.}

{125}{}{Nuestro trabajo es muy peligroso.}
{126}{}{Las tormentas de polvo llegan a ser peores que los forajidos.}
{127}{}{Estos días, caminar por la carretera es como bailar con el diablo.}
{128}{}{Sí, he luchado contra saqueadores y forajidos durante mis viajes.}
{129}{}{Si se nos rompe el carro, yo no lo voy a arreglar.}
