{100}{}{Ves a un ciudadano.}
{101}{}{Ves a un típico ciudadano de Fénix, el yermo lo ha endurecido.}
{102}{}{Ves a una mujer de Fénix, sus ojos están llenos de cautela.}
{103}{}{ }

{110}{}{Estás viendo a un ciudadano de Fénix. No es nada especial.}
{111}{}{Ves a un hombre sin nada fuera de lo común, camina por la calle sin rumbo fijo.}
{112}{}{Estás viendo a un hombre con la ropa sucia, claramente está enfrentándose a una resaca.}
{113}{}{Estás viendo a un habitante local de mirada poco amistosa.}
{114}{}{Ves a un habitante local que mira hacia otro lado, está fingiendo que no sabe que estás ahí.}

{120}{}{Una ciudadana común y corriente de Fénix, no destaca en medio del yermo.}
{121}{}{Estás viendo a una mujer sin nada de especial, camina por la calle, indiferente.}
{122}{}{Una mujer de ropa desgastada, claramente necesita cambiarse.}
{123}{}{Ves a una ciudadana de Fénix de mirada irritada.}
{124}{}{Estás viendo a una habitante local de Fénix, resopla cuando la ves a los ojos.}

#########################################
#Response
#########################################

#- reputation
{200}{}{Buenas tardes.}
{201}{}{Después de ti, por favor.}
{202}{}{*Te saluda amistosamente*}
{203}{}{Claro, claro, ni siquiera pensaría en asaltarte.}
{204}{}{¿Te puedo ayudarte?}
{205}{}{Te compraría un trago, pero no tengo ni una chapa.}
{206}{}{Hola, ¿qué tal te va?}
{207}{}{Nos hace falta más gente como tú en la ciudad.}
{208}{}{No sé por qué, pero la gente habla bien de ti.}
{209}{}{Mis respetos.}

{210}{}{Hola.}
{211}{}{Mira por donde pisas.}
{212}{}{Agh, malditos turistas...}
{213}{}{No me molestes, o te golpearé en la cara.}
{214}{}{No eres de aquí, ¿verdad?}
{215}{}{¿Es tu primera vez en Fénix?}
{216}{}{*te ignora*}
{217}{}{Genial, otro mendigo más.}
{218}{}{Deja de molestarme.}
{219}{}{¿Qué quieres?}

{220}{}{Piérdete.}
{221}{}{Muévete.}
{222}{}{Fuera de mi camino.}
{223}{}{Me voy a reír cuando te cuelguen.}
{224}{}{Otro campesino que viene a la ciudad.}
{225}{}{¿Se les está acabando el espacio en el yermo?}
{226}{}{Aléjate de mí.}
{227}{}{No tienes por qué estar en Fénix.}
{228}{}{Ya pronto te colgaremos.}
{229}{}{La ciudad estará mejor sin ti.}

#- Power Armor
{230}{}{¡No me toques, hombre de hierro!}
{231}{}{Hola, eh... ¿señor? ¿Señorita? Lo que seas.}
{232}{}{¿Me puedo subir a tus hombros?}
{233}{}{¿Podrías deshacerte de algunos de mis enemigos?}
{234}{}{¿Buscas a otros robots como tú?}
{235}{}{Si estás buscando robots, ya no hay muchos por aquí.}
{236}{}{Es un poco triste, ¿no crees? Un robot totalmente sólo en un mundo humano.}
{237}{}{*Toc-toc* ¿Hay alguien ahí?}
{238}{}{Perdona, pero no están ni el Espantapájaros ni Totó.}
{239}{}{¿Necesitas un poco de aceite, grandulón?}

#- GG follower
{240}{}{Le rezo al Fuego Santo todos los días... en serio.}
{241}{}{Lo siento, me quitaré de su camino, ahora mismo...}
{242}{}{Me comportaré, lo juro.}
{243}{}{Gloria al Fuego Santo... ¿Qué tenía que hacer ahora...?}
{244}{}{Perdón, perdón, dejaré de respirar su aire.}
{245}{}{Yo respeto a Aaron, nuestro salvador.}
{246}{}{¿Cómo puedo unirme a los Seguidores?}
{247}{}{No quiero problemas, lo juro.}
{248}{}{Un momento, ¿es cierto que no tienen permitido...? Ya sabes... ¿'Jugar'?}
{249}{}{No me pidas limosna - estoy en la quiebra.}

#- GG arena champion
{250}{}{Te invitaría una bebida, pero aposté al luchador equivocado.}
{251}{}{Mierda, si hubieras perdido, ya tendría chapas hasta para regalar.}
{252}{}{Perdona, no quería estorbarte, ya me haré a un lado... quizás me vaya de la ciudad.}
{253}{}{No tienes el aspecto de un campeón.}
{254}{}{¿Por cuánto tiempo entrenaste?}
{255}{}{Si pierdes la siguiente pelea, me voy a enojar MUCHO.}
{256}{}{Voy a llevar a mis hijos a ver tu siguiente pelea.}
{257}{}{Esa pelea fue increíble, campeón.}
{258}{}{¿Por qué ya no te vemos en el cuadrilátero?}
{259}{}{Sin ti, las peleas del cuadrilátero son aburridas.}

{1250}{}{Te invitaría una bebida, pero aposté al luchador equivocado.}
{1251}{}{Mierda, si hubieras perdido, estaría nadando en chapas.}
{1252}{}{Perdona, no quería estorbarte, me haré a un lado... quizás me vaya de la ciudad.}
{1253}{}{No tienes el aspecto de una campeona.}
{1254}{}{¿Por cuánto tiempo entrenaste?}
{1255}{}{Si pierdes la siguiente pelea, de verdad me voy a enojar.}
{1256}{}{Voy a llevar a mis niños a ver la siguiente pelea.}
{1257}{}{Esa pelea fue increíble, campeona.}
{1258}{}{¿Por qué ya no te vemos en el cuadrilátero?}
{1259}{}{Sin ti, las peleas se han vuelto aburridas.}

#- GG is high
{260}{}{Sí, sí, hay duendes por ahí, detrás del palo... sí.}
{261}{}{¿Te drogaste?}
{262}{}{Yo también tenía problemas con eso que estás tomando.}
{263}{}{No tengo droga para ti, lo siento.}
{264}{}{Piérdete, maldito drogadicto.}
{265}{}{Siento pena por la gente como tú.}
{266}{}{¿Estás bien?}
{267}{}{A juzgar por tus pupilas, te estás divirtiendo...}
{268}{}{Esto no terminará bien.}
{269}{}{¿Estás buscando drogas? Vete a los barrios bajos, idiota.}

#- about the city
{270}{}{El cielo jamás estará despejado, ¿verdad?}
{271}{}{Siento que la noche será muy calurosa.}
{272}{}{El viento de occidente sólo trae polvo y cenizas, nada más.}
{273}{}{Este sitio siempre está tan contaminado.}
{274}{}{Ya viene la temporada de tormentas de polvo.}

{275}{}{Ya no soporto esta ciudad.}
{276}{}{He estado aquí por demasiado tiempo.}
{277}{}{La ciudad ha estado demasiado llena estos últimos días.}
{278}{}{Tengo que irme de aquí de una vez.}
{279}{}{Fénix está llena, tanto de gente como de dolores de cabeza...}

{280}{}{Me parece que por fin se me acabó la suerte.}
{281}{}{Hoy dejaré al casino sin una sola chapa.}
{282}{}{Intento parar, pero no puedo...}
{283}{}{¡Esta noche la pasaré en grande!}
{284}{}{Creo que veré si tengo suerte en la ruleta.}

{285}{}{No puedo esperar a ver a Verónica cantar otra vez.}
{286}{}{Verónica tiene una figura muy linda.}
{287}{}{Otro día perdido.}
{288}{}{Si te aburres, ve al cuadrilátero.}
{289}{}{Han pasado años y no ha habido una gota de lluvia.}

{290}{}{Escuché que los mercenarios están preparando un nuevo grupo de esclavos.}
{291}{}{El casino está repleto de tramposos.}
{292}{}{Las bandas callejeras están muy descontroladas.}
{293}{}{Ir a los barrios bajos es una forma rápida de morir.}
{294}{}{Estos días, hay caravaneros por doquier...}

{295}{}{}
{296}{}{}
{297}{}{}
{298}{}{}
{299}{}{}

#########################################
#Floating lines
#########################################

#- reputation
{300}{}{}

#- Power Armor
{330}{}{Ay, no, ¡Me está mirando!}
{331}{}{¿Crees que vino para atacar a alguien?}
{332}{}{Haz como que no está ahí, ignóralo...}
{333}{}{Esa cosa me da escalofríos.}
{334}{}{Esa cosa no se parece a ningún robot que haya visto.}
{335}{}{Eso es la legendaria servoarmadura, ¿no?}
{336}{}{Ojalá que esa cosa no sea radioactiva.}
{337}{}{Está parada ahí, es como una lavadora andante.}
{338}{}{Dicen que ese pedazo de metal mató a cinco personas ayer.}
{339}{}{Oh oh, mejor me hago a un lado.}

#- GG follower
{340}{}{Aléjense de esa persona.}
{341}{}{Ese cultista parece ser peligroso.}
{342}{}{Estos cultistas están dementes... ay, mejor cierro la boca.}
{343}{}{No hables mal de los Seguidores.}
{344}{}{Es mala idea quedarse mirando a un Seguidor.}
{345}{}{Hay un Seguidor ahí, rápido, dile algo bueno.}
{346}{}{Los Seguidores tienen espías por todos lados.}
{347}{}{Los cultistas se creen muy gallos al caminar así por ahí.}
{348}{}{Estos Seguidores creen que Fénix les pertenece.}
{349}{}{No me pidas donaciones, cultista.}

#- GG arena champion - husband
{350}{}{Ahí está ese loco del cuadrilátero.}
{351}{}{¿Crees que me duerma si me acerco?}
{352}{}{Ese tipo es un luchador, hecho y derecho.}
{353}{}{No lo mires a los ojos...}
{354}{}{¡Luchaste muy bien, campeón!}
{355}{}{*silba* ¡Oye! ¡Campeón!}
{356}{}{Me pregunto si ese grandulón se daría cuenta de que estoy aquí.}
{357}{}{Hombres que se golpean por dinero... que mundo más raro.}
{358}{}{¿Por qué habrá dejado de pelear?}
{359}{}{¡Muéstrame ese gancho izquierdo, grandulón!}

#- GG arena champion - women
{360}{}{Ahí está esa loca del cuadrilátero.}
{361}{}{¿Crees que me golpee si me acerco?}
{362}{}{Esa chica podría matar al que sea.}
{363}{}{No la mires a los ojos, no lo hagas...}
{364}{}{¡Peleas muy bien, campeona!}
{365}{}{*silba* ¡Oye, campeona!}
{366}{}{Me pregunto si se dará cuenta de que estoy aquí.}
{367}{}{¿Una luchadora? ¿Qué le está pasando a este mundo?}
{368}{}{¿Por qué dejaste de pelear?}
{369}{}{¡Muéstreme ese gancho izquierdo, señorita!}

#- about the city
{370}{}{*¡Achoo!*}
{371}{}{Este aire se siente como respirar tierra.}
{372}{}{Con toda la contaminación, ni siquiera puedes ver la ciudad desde las montañas.}
{373}{}{Alguien tiene que limpiar toda esta basura.}
{374}{}{Me parece que esta noche hará calor.}
{375}{}{La ciudad se está llenando de gente.}
{376}{}{Que bueno, por fin colgaron a ese bastardo...}
{377}{}{En estos lados no hay más que mendigos y desempleados.}
{378}{}{Ya no soporto vivir así.}
{379}{}{Ya es hora de que me vaya de aquí.}

{380}{}{El banco se apiadó de mí, por fin.}
{381}{}{Jamás volveré a entrar a un casino.}
{382}{}{Voy a entrar al casino una hora... o quizás dos.}
{383}{}{La suerte me dio la espalda.}
{384}{}{Últimamente todo ha estado en mi contra.}

{385}{}{Si los Seguidores me vuelven a sermonear...}
{386}{}{Los barrios bajos son peligrosos, incluso de día.}
{387}{}{Parece que estos días hay más caravanas.}
{388}{}{¿En serio hay vida afuera de la ciudad?}
{389}{}{Sólo a un desesperado se le ocurriría viajar por el desierto.}

#- explosion of the Cathedral
{390}{}{Esos cultistas recibieron su merecido.}
{391}{}{Fénix tendrá problemas sin los Seguidores.}
{392}{}{La Catedral desapareció, los Seguidores escaparon... ¿Ahora qué?}
{393}{}{No sé que es peor, la vida con los Seguidores o sin ellos.}
{394}{}{No puedo creerlo, era una bomba nuclear.}
{395}{}{¿Así que esos bastardos tenían una bomba nuclear? ¿En serio?}
{396}{}{¿Una bomba nuclear? Sí que estaban chiflados.}
{397}{}{Las chapas empezaron a devaluarse después de que explotó la Catedral.}
{398}{}{¿Quién controlará el precio de los chapas ahora?}
{399}{}{Parece que las chapas serán chatarra sin ningún valor, otra vez.}

{400}{}{Se dice que Aaron está muerto. ¿Será verdad?}