{102}{}{No voy a tolerar eso en mi casino. Deja tus juguetitos afuera.}
{103}{}{¿Me estás amenazando?}

#Acquaintance
{200}{}{Sí que tienes huevos para entrar así sin más. ¿Quién eres y qué quieres?}
{1200}{}{Sí que tienes agallas para entrar así sin más. ¿Quién eres y qué quieres?}
{201}{}{Soy }
{202}{}{ de la Villa. Quiero trabajar para usted, Don Diego.}
{203}{}{Hay muchos que me dijeron eso y salieron corriendo apenas hubo problemas. Este casino es una familia, no es sólo un negocio. Necesitaré una buena razón para aceptarte.}
{204}{}{Si necesita razones, entonces buscaré dárselas. Nos vemos, Don Diego.}
{205}{}{Bill me advirtió de que venías a verme. ¿Quién eres? ¿Qué es lo que buscas?}
{206}{}{Don Diego, escúcheme, por favor. Esclavizaron a mi familia e intento arreglar las cosas.}
{207}{}{¿Entonces por qué no le pides ayuda a Aaron? Su culto le da chapas a los esclavizadores. No tengo razón por la cuál estar metido en eso.}
{208}{}{Siento oír eso. Nos vemos, Don Diego.}
{209}{}{Interesante. ¿Acaso me estás pidiendo ayuda?}
{210}{}{Sugiero que cooperemos, porque tenemos un enemigo en común - los Seguidores del Fuego.}
{211}{}{Entonces lo dices en serio. Pero este casino es mi familia, y no puedo arriesgarla en una pelea directa. De todas formas, Aaron cada vez me presiona más y más, puede que algún día deba actuar en su contra.}
{212}{}{Ojalá que cuando lo haga, no sea demasiado tarde. Adiós, Don Diego.}
{213}{}{Entonces déjeme trabajar para usted. Deme una oportunidad, no se arrepentirá.}
{214}{}{No le pido ayuda, le pido justicia, Don Diego.}
{215}{}{Una vez era igual que tú, nada más que un campesino. Me tomó mucho trabajo salir de ese agujero y ganarme mi lugar en esta ciudad.}
{216}{}{Así que entiende lo que me está pasando.}
{217}{}{Pero eso fue hace mucho tiempo. Me conmueves, pero necesito una buena razón por la cual confiar en ti.}
{218}{}{Puede confiar en mí, le demostraré que valgo la pena.}
{219}{}{Lamento oír eso. Adiós, Don Diego.}
{220}{}{Habla con García, te dará algunos trabajos para empezar. Veamos qué tal lo haces.}
{221}{}{No lo decepcionaré, Don Diego.}
{222}{}{Está bien. Lo que tú digas.}
{223}{}{Perdón, pero no tengo ningún trabajo para ti.}
{224}{}{Comprendo. Entonces debo irme.}

{250}{}{¿Qué quieres?}
{251}{}{Cuéntame lo que necesitas.}
{252}{}{¿Y bien? ¿Qué pasa?}
{253}{}{Mis respetos, Don Diego.}

{260}{}{Don Diego, ¿cuáles son sus planes ahora que la Catedral fue destruida?}
{261}{}{Preguntas cosas que no deberías, dada tu posición.}
{262}{}{Perdóneme, Don Diego.}
{263}{}{Solo tenía curiosidad.}
{264}{}{Lo mismo que antes. Ganar dinero, expandir nuestra influencia. Ahora será más fácil que nunca.}
{265}{}{El Culto del Fuego era un dolor de muelas, ¿cierto?}
{266}{}{Su caída nos abre nuevas puertas, pero es un desastre para muchos en nuestra ciudad. Debemos considerar muchas cosas; mantener el valor de las chapas, las pérdidas de trabajo, aumentará el crimen. Pero, es cierto que nos pone en ventaja.}
{267}{}{Gracias por contármelo, Don Diego.}

#Attack on Followers
{300}{}{Estoy investigando el ataque contra los Seguidores. ¿Qué sabes al respecto?}
{301}{}{¿Quién te crees que eres para entrar e interrogarme? Saquen a este mugroso de aquí, chicos.}
{1301}{}{¿Quién te crees que eres para entrar e interrogarme? Saquen a esta zorra de aquí, chicos.}
{302}{}{¡Grave error!}
{303}{}{No es necesario, ya me iba.}
{304}{}{¿Desde cuándo los Seguidores tienen la costumbre de interrogar a cualquiera? Te diré lo que sé, pero sólo es por mostrar respeto ante la iglesia que alimenta la ciudad.}
{305}{}{Genial, déjame encender mi PipBoy... Cuéntame lo que pasó.}
{306}{}{No sé nada al respecto de... eso.}
{307}{}{Eh, ¿cómo?}
{308}{}{Sé que rodearon a los monjes en la calle y les dispararon a quemarropa. Yo no estaba ahí, hay muchos rumores, pero puedo asegurarte de que no tuvimos nada que ver. Es todo lo que sé.}
{309}{}{Perdón, Don Diego. Veo que sólo le estoy quitando el tiempo.}
{310}{}{Suerte con tu investigación, pero no me vuelvas a molestar acerca de esto.}
{311}{}{Adiós.}
{312}{}{¿Qué coartada poseen ustedes?}
{313}{}{Es simple, nuestro casino le debe mucho a la Iglesia del Fuego Santo. Ellos regulan el valor de las chapas y crean trabajos. No hay por qué matar al brahmán que nos da la leche. No fuimos nosotros.}
{314}{}{Hmm, ya veo... Me voy, pero no les quitaré el ojo de encima.}
{315}{}{Gracias, ya entiendo. Adiós.}
{316}{}{Hablemos cara a cara, Don Diego.}
{317}{}{¿Estás escuchando lo que dice este niño, García? Cree que puede hablarme de esa manera. Sácala de aquí.}
{1317}{}{¿Estás escuchando lo que dice este niño, García? Cree que puede hablarme de esa manera. Sácala de aquí.}
{318}{}{(asienta con la cabeza) Hay muchos en nuestra ciudad que odian a los Seguidores. Deberías saberlo, eres uno de ellos.}
{319}{}{¿Por qué?}
{320}{}{Primero, por la sangrienta revolución que llevó a Aaron al poder, mucha gente tiene que saldar cuentas al respecto. Luego, con su gran inquisición para expandir su control, la gente no olvidará cosas así. Aquellos que estás buscando no pueden ser matones o mercenarios de poca monta, porque están organizados y bien armados.}
{321}{}{Debo pensar en quiénes podrían ser los culpables...}
{322}{}{Organizados y bien armados, igual que tu casino... No, no te acuso de nada. Adiós, Don Diego.}
