{100}{}{Ves a un camello.}
{101}{}{Estás viendo a un traficante de drogas, o algo así.}
{102}{}{El traficante ha subido sus precios.}
{103}{}{El traficante te ha dado un descuento en sus bienes.}
{104}{}{Cuidado con eso, niño. Te estás buscando problemas.}

#First Encounter
{200}{}{Oye, amigo, hoy te ves bien. ¿Qué tal si te diviertes un poco antes de que las cosas empeoren?}  
{1200}{}{Oye, nena, hoy te ves bien. ¿Qué tal si te diviertes un poco antes de que las cosas empeoren?}  
{201}{}{¿Qué me ofreces?}  
{202}{}{Todo tipo de placeres. Trágate esta pastilla y te dará un subidón que ningún casino podría darte. Yo la he probado, confía en mí.}  
{203}{}{Así que vendes drogas, ¿no?}  
{204}{}{No creo que tengas algo que valga la pena.}  
{205}{}{Claro, claro, lo que tú digas. Pero créeme, te estás perdiendo del último pedacito de felicidad que queda en este horrible mundo.}  
{206}{}{¿Placer? Creo que ya nos estamos entendiendo.}  
{207}{}{¿Qué es lo que estás traficando, exactamente?}  
{208}{}{No sé a qué te refieres. Tengo estimulantes, antídotos - todo limpio, nada ilegal. La verdadera pregunta es, para qué los usas. Pero, oye, eso es asunto tuyo, no mío. (guiño)}  
{209}{}{Ya entiendo.}  

#Follow-Up Dialogue
{210}{}{Oye, ¿necesitas algo?}
{211}{}{Tengo algo que te puede relajar, mira lo que tengo.}
{212}{}{Quieres de lo bueno, ¿verdad?}
{213}{}{¿Buscas una dosis?}
{214}{}{¿Tienes ansias? Tengo justo lo que necesitas.}
{215}{}{¿Qué es lo que necesitas el día de hoy?}

{216}{}{Disimula. Nos veremos luego.}
{217}{}{Ten cuidado.}
{218}{}{Anda, no hagas ruido. Ahí nos vemos.}
{219}{}{Esto jamás pasó. ¿Entendido? Nos vemos.}

#Rude Reply and Fight
{220}{}{Escúchame, pendejo. Conozco gente que *controla* esta zona. ¿Quién eres tú para decirme qué hacer? ¿Crees que no te harán nada? No hagas un escándalo, o habrán problemas.}
{1220}{}{Escúchame, pendeja. Conozco gente que *controla* esta zona. ¿Quién eres tú para decirme qué hacer? ¿Crees que no te harán nada? No hagas un escándalo, o habrán problemas.}
{221}{}{¿Escándalo? ¿Crees que tu cadáver en el suelo sea un escándalo?}
{222}{}{Perdona, eso fue una tontería. Ya me calmo.}
{223}{}{Hermano, me estás haciendo enojar. Relájate o llamaré a mi gente.}
{1223}{}{Señorita, me está haciendo enojar. Relájate, o te las verás con mi mano.}
{224}{}{Hazlo, perro. Te reto.}
{225}{}{Perdona, no es necesario que hagas eso. Me voy a calmar.}
{226}{}{¡Estás loco! ¡Muere, pendejo!}
{1226}{}{¡Estás loca! ¡Muere, pendeja!}
{227}{}{¡El que morirá eres tú, idiota!}
{228}{}{Hora de dormirte.}

#Inquiries
{230}{}{¿Qué clase de drogas vendes?}
{231}{}{¿Qué necesitas? Dímelo y te lo consigo, un estimulante, RadAway, o... (guiño) algo más fuerte. ¿Me entiendes?}
{232}{}{Lo tendré en mente. Nos vemos.}
{233}{}{Pero, ¿de dónde consigues todo esto?}
{234}{}{¿Algo más fuerte? ¿Cómo los Esteroides y el Psico?}
{235}{}{Lo siento, pero los Seguidores del Fuego me prohibieron vender esa clase de cosas. Compran todas las drogas militares y las acaparan para ellos mismos.}
{236}{}{¿Por qué querrían las viejas drogas del ejército?}
{237}{}{Dicen que es por el bien de la ciudad... Mira, la verdad no sé el por qué, pero no quiero romper las reglas. Sin embargo... (se te acerca y te susurra)}
{238}{}{¿Sí?}
{239}{}{Tengo muchas conexiones, por unas 100 chapas, puedo ser tu traficante personal. Pero esto se tiene que quedar entre los dos. ¿Lo comprendes?}
{240}{}{Me lo pensaré.}
{241}{}{Eres un peligro para la sociedad, tengo que eliminarte.}
{242}{}{No tan rápido. Primero quiero que me digas en dónde conseguiste todas estas drogas.}
{243}{}{Aquí están las chapas. Muéstrame lo que le escondes a los demás compradores.}
{244}{}{Ya hablamos de esto. ¿Quieres las drogas o no?}
{245}{}{Otro día.}
{246}{}{Por cierto, ¿de dónde consigues estas drogas?}
{247}{}{Soy uno de los Seguidores, ¿quieres que la Catedral se entere de tu negocio? Puedo arreglarlo.}
{248}{}{¡Espera, no! ¿Por qué tanta prisa? Siempre se puede hacer un trato.}
{249}{}{Entonces déjame ver *toda* tu mercancía.}
{250}{}{O-oye, e-estoy temblando. ¡No seas así, lo necesito, dame algo!}
{251}{}{Necesito algo que me de una ventaja en el cuadrilátero.}
{252}{}{¿Por qué tanto secretismo? Los cultistas tienen problemas más grandes que resolver, ya no les interesan tus drogas.}
{253}{}{Vayamos directo al grano, me interesa tu mercancía.}
{254}{}{Aléjate de mí.}
{255}{}{Orris me recomendó que hablara contigo para... ya sabes.}
{256}{}{Muéstrame lo que tienes.}

{260}{}{Ya, tengo todo lo que necesitas. No te preocupes, ya pronto te sentirás mejor.}
{261}{}{Uf, hay tanto de donde elegir. Pero ahora sé de donde abastecerme en drogas.}
{262}{}{Así está mejor. Pero dejemos esto como un secreto.}
{263}{}{No veo el por qué, no necesito un mediador para abastecerme.}
{264}{}{Volveré después.}
{265}{}{Eres un idiota. Hasta luego.}
{266}{}{Entonces te quebraré los dedos.}

{270}{}{¿De dónde consigues toda tu mercancía?}
{271}{}{De todos lados, por supuesto. Me consigo un poco con los chatarreros, le compro un poco a las caravanas sureñas y fabrico por mi cuenta con mi cocina. No te preocupes, todo está limpio.}
{272}{}{Eso suena muy poco confiable, ¿no crees?}
{273}{}{Relájate, las drogas casi están puras. Es de lo mejor que te encontrarás en la ciudad... A excepción de los Seguidores del Fuego, quizás. Pero ellos no comparten con nadie.}
{274}{}{¿Y qué clase de 'mercancía' vendes?}
{275}{}{¿'Casi' puras? Necesito las drogas de la mejor calidad.}
{276}{}{Ya te lo dije, yo tengo lo mejor. Si no confías en mí, piérdete.}
{277}{}{Bueno, me voy...}
{278}{}{Vuelve a hablarme así y te arrancaré los dientes.}
{279}{}{Necesito drogas que sean de calidad, hay vidas que dependen de ellas.}
{280}{}{¿Así que sabes de medicina? Deberías haber empezado con eso, no es normal ver a un doctor en estos tiempos y siempre estaré feliz de conocer a uno. No te preocupes, te daré lo mejor de lo mejor. Y con un descuento.}
{281}{}{Gracias, eso me ayudará mucho.}
{282}{}{Así está mejor.}
{283}{}{Me sigue pareciendo muy sospechoso. Me voy de aquí.}
{284}{}{Murphy me dijo que hablara contigo. Estoy buscando algo que pueda... 'dormir' a alguien.}
{285}{}{No sé para qué necesitas eso, y no quiero saberlo. Pero tengo veneno de escorpión y psico. Tú eliges, pero recuerda que te costará.}
{286}{}{Déjame ver...}
{287}{}{Si alguien te lo pregunta, yo no tuve nada que ver con esto.}
{288}{}{Vale.}

{290}{}{¿Cómo te llamas?}
{291}{}{Llámame Gónzales.}
{292}{}{No creo que ese sea tu verdadero nombre.}
{293}{}{Ja, diste en el clavo. ¿Por qué te importa?}
{294}{}{¿Por qué tanto secretismo?}
{295}{}{Hay algunas personas a las que no les gusta mi negocio. Mis competidores, malditos sean. Pero en su mayoría, son los cultistas de la Catedral. Están buscando controlar todo el suministro de drogas y pagarle una miseria a los traficantes como yo. Me conviene trabajar por mi cuenta, pero no puedes explicarle eso a esos tipos.}
{296}{}{Si no son los Seguidores los que te abastecen, ¿de dónde consigues las drogas?}
{297}{}{Tener tu propio negocio en un sitio como este debe ser arriesgado.}
{298}{}{No me estés chingando. ¿Conoces a los Cardenales Rojos? Suelen andar por el gimnasio, Orris es su líder. Él se asegura de que mi negocio no tenga problemas. No lo hace gratis, por supuesto.}
{299}{}{No me estés chingando. Solía estar bajo la protección de Orris y sus chicos. Pero su muerte afectó mucho a mi negocio. Ya no sé cómo voy a sobrevivir.}

#Addict Killed by Player
{300}{}{Se dice que mataste a Larry. ¿Por qué le haces eso a mis clientes?}
{301}{}{Sólo estoy sacando la basura. ¿Algún problema?}
{302}{}{¡Sí, lo tengo! Puede que Larry haya sido basura, pero tenía sus momentos de claridad, así juntaba las chapas y venía a gastárselas acá. ¿Qué se supone que voy a hacer con un drogadicto muerto? No puedo ganar chapas con un cadáver.}
{303}{}{¿Eh?}
{304}{}{No es cosa mía.}
{305}{}{Eh, te arrepentirás de esto. Tendrás que compensarme esa perdida de ganancias cuando tú y yo estemos haciendo un trato.}
{306}{}{¿Así que ya no me darás ningún descuento? Eso es una pena.}
{307}{}{Al cabo que ni quería comprar tus drogas. Adiós.}
{308}{}{Perdón, fue un accidente.}
{309}{}{¿Perdón? ¿¡Matas a mi cliente y me pides PERDON!? Pedazo de mierda, ¿crees que olvidaré esto?}
{1309}{}{¿Perdón? ¿¡Matas a mi cliente y me pides PERDON!? Pedazo de mierda, ¿crees que olvidaré esto?}
{310}{}{Eh, sí.}
{311}{}{¿Acaso quieres empezar una pelea?}
{312}{}{Eso fue entre yo y Larry, no tienes nada que ver.}
{313}{}{(entrecierra los ojos) ¿Qué clase de problemas podrías tener con Larry?}
{314}{}{No es asunto tuyo.}
{315}{}{Si te lo dijera, tendría que matarte.}
{316}{}{Así que tú fuiste quien ayudó a Larry... odio cuando alguien se mete con mis clientes.}
{317}{}{Larry... ah, el drogadicto, ¿no?}
{317}{}{Larry... ah, el drogadicto, ¿no?}
{318}{}{Sí, Larry. Puede que el tipo haya sido una basura, pero gracias a él ganaba algunas chapas muy fáciles. ¿Qué voy a hacer ahora?}
{319}{}{Luego de un tiempo, él no te iba a hacer tanto dinero. Piénsatelo.}

{320}{}{Deberías tener cuidado con los tipos que se llevaron tu moto. Son parte de la pandilla de los Cardenales Rojos, prácticamente son los dueños de esta zona. Si enojas a uno, estás muerto. Pero, es cosa tuya.}
{321}{}{Lo tendré en cuenta.}
{322}{}{Tengo un paquete para ti, de parte de los Escudos Azules.}
{323}{}{Por fin, dámelo. He esperado mucho tiempo. ¿Sabes lo difícil que es conseguir hidrocarburos?}
{324}{}{Eh, ¿cuánto?}
{325}{}{No importa. Toma, esto es el producto final. Y dile a tu gente que a causa de los Seguidores del Fuego, cada vez se hace más difícil producir drogas.}
{326}{}{Hasta luego.}
{327}{}{Hubo un problema con el mensajero anterior. ¿Sabes lo difícil que es viajar por la Ruta Diez?}
{328}{}{Sí, como sea. ¿Cómo se supone que voy a fabricar drogas sin la materia prima? Toma, es el producto final. Dáselo a Río y dile que cuide a sus mensajeros, antes de que los Seguidores del Fuego se encarguen de mí.}
{329}{}{Hasta luego.}

{330}{}{¿Eres el que le está vendiendo drogas a Larry?}
{331}{}{Si no lo hago yo, lo haría alguien más. ¿Qué te importa?}
{332}{}{No es nada.}
{333}{}{Entonces no te metas en los asuntos de otros.}
{334}{}{Eh, bueno...}
{335}{}{La gente de ahí adentro no está muy contenta con eso.}
{336}{}{Que lo resuelvan ellos mismos, no es problema mío, sino el de Larry. Yo sólo le estoy vendiendo su medicamento.}
{337}{}{¿Medicamentos? ¿De verdad?}
{338}{}{Bueno, tiene fiebre debido a alguna enfermedad del yermo, ya sabes. Así que vino a pedirme un tratamiento, si alguien necesita ayuda, ¿cómo voy a decir que no?}
{339}{}{Que 'amable' de tu parte. Adiós, doc.}
{340}{}{Si le vendes aunque sea una dosis más, te las verás conmigo.}
{341}{}{¿Qué dijiste? Repítemelo, hijo de puta, a lo mejor te escuché mal.}
{1341}{}{¿Qué dijiste? Repítemelo, perra, a lo mejor te escuché mal.}
{342}{}{Eh, mejor te dejo, cálmate. Adiós, amigo.}
{343}{}{Te lo diré una sola vez. Deja de envenenar a Larry. O estás muerto.}
{344}{}{Lo siento, es culpa mía. Claro, no volveré a venderle a Larry, no hay ningún problema.}
{345}{}{Me alegra que nos entendamos.}
{346}{}{Ten cuidado con lo que me dices, discutir conmigo es como discutir con Orris.}
{347}{}{Ah, ¿así que ahora eres uno de los Cardenales? Lo tendré en cuenta. Eh, no te enojes, ¿bien?}
{348}{}{Exacto.}
{349}{}{Desde ahora, Larry está bajo mi protección. Lo que quiere decir que ahora está bajo la protección de Don Diego.}
{350}{}{No lo he hecho todavía, pero puedo contarle a Aaron de tu 'negocio'. Tienes suerte de que no le he dicho nada.}
{1350}{}{No lo he hecho todavía, pero puedo contarle a Aaron de tu 'negocio'. Tienes suerte de que no le he dicho nada.}
