{100}{}{Ves al Señor Supremo de Fénix.}
{101}{}{Ves a un hombre de aspecto serio con túnicas ceremoniales. Su mirada autoritaria te hace sentir incómodo.}
{102}{}{Esta es una iglesia pacífica. ¿Por qué las medidas de seguridad son tan serias?}
{103}{}{Has renunciado a la placa de ranger.}
{104}{}{Ahora eres oficialmente un miembro de la Hermandad de Mojes.}

# Primer diálogo (reunión)
{200}{}{¿¡Cómo osas a entrar en mi dominio sin previo aviso!? ¿Quién eres, y qué quieres? En el nombre del Fuego Santo, habla rápido y con claridad.}
{201}{}{Pensé que nunca volvería a verte. ¿Qué quieres ahora?}
{202}{}{Solo quiero hablar contigo.}
{203}{}{Solo quiero tener una conversación contigo.}
{204}{}{Mi nombre es }
{205}{}{, y represento a la comunidad de la Villa.}
{206}{}{Deseo unirme a la iglesia, santo Padre.}

{210}{}{Parece que me perdí. ¿Puedes decirme dónde está la salida?}
{1210}{}{Parece que me perdí. ¿Puedes decirme dónde está la salida?}
{211}{}{Qué absurdo. Te daré una última oportunidad. ¿*Qué* quieres?}
{212}{}{Ya te lo dije, busco la salida.}
{213}{}{O eres muy estúpido o intencionadamente insolente. ¡Guardias! ¡Atrapen al espía!}
{1213}{}{O eres muy estúpida o intencionadamente insolente. ¡Guardias! ¡Atrapen a la espía!}
{214}{}{¿Espía? ¿Yo?}
{215}{}{¡No puedes atraparme!}
{216}{}{¡Espera! Vengo en son de paz. ¿Podemos hablar?}
{217}{}{Pobre y retorcida alma. Fuera de mi vista. Tu sufrimiento me entristece, espero que algún matón acabe con tu vida pronto.}
{218}{}{Sigue soñando, vejestorio.}
{219}{}{Está bien, me voy.}

{220}{}{Muy bien. No nos gustan los visitantes agresivos. ¿Qué estás haciendo aquí?}
{221}{}{Solo quiero hablar contigo. Tengo preguntas.}
{222}{}{No, el que hará las preguntas soy yo. Tú las responderás.}
{223}{}{Soy un mensajero de la Hermandad del Acero.}
{224}{}{Pones a prueba mi paciencia... (un asesor le susurra al oído) Hmm, de acuerdo. Te dejaré ir, pero no vuelvas a molestarme. ¡Lárgate!}
{225}{}{Por supuesto, señor Aaron. Pido disculpas por molestarlo.}
{226}{}{Ajá.}
{227}{}{¿La Villa? Ese lugar me resulta desconocido. ¿Qué quieres, }
{228}{}{ , de la Villa?}
{229}{}{Necesito hablar con usted respecto a la Villa, señor Aaron.}

{230}{}{¡Suficiente! ¡Serás azotado y ahorcado públicamente! ¡Agarren al hereje!}
{1230}{}{¡Suficiente! ¡Serás azotado y ahorcado públicamente! ¡Agarren a la hereje!}
{231}{}{¡Eres un tirano! ¡Acabaré contigo!}
{232}{}{Estás loco...}
{233}{}{¡Un asesino! ¡En nombre del Fuego, deténganlo!}
{234}{}{Relájate, ahora mando yo aquí.}
{235}{}{No van a ayudarte.}
{236}{}{Hermanos, en nombre del Fuego, tiren a esta basura pagana a la calle.}
{237}{}{¡Guardias! ¡Maten a este espía, inmediatamente!}
{238}{}{No pueden detenerme...}
{239}{}{Te quiero ver muerto. ¡Eres un vil tirano y un opresor!}

{240}{}{Usted no está siendo muy cortés conmigo, señor.}
{241}{}{Sigue así y te haremos un esclavo, como a muchos antes que tú.}
{242}{}{¿Es así como resuelven los problemas en la iglesia? Pensé que este era un santuario de paz y fraternidad.}
{243}{}{Sí, así es. Hasta que llegan alimañas irradiadas como tú y empiezan a causarnos problemas. El mundo que nos rodea se ha vuelto tan salvaje que incluso una iglesia pacífica tiene que armarse. Ustedes tienen mucho que aprender, salvajes.}
{244}{}{[Continuar]}
{245}{}{Te lo pregunto por última vez, ¿qué es lo que quieres?}
{246}{}{Sólo quiero hablar contigo.}
{247}{}{Después de esta breve conversación, no veo por qué seguir hablándote. Fuera.}
{248}{}{¡Algún día pagarás por tratarme así! ¡Lo juro!}
{249}{}{Está bien, me iré en paz.}

{250}{}{Me temo que no tengo tiempo para charlas triviales. ¿Tienes algo IMPORTANTE que discutir conmigo?}
{251}{}{En realidad, sí. Vengo a hablar de mi aldea.}
{252}{}{Me temo que no. Perdón por hacerle perder el tiempo con mi ociosa curiosidad.}
{1252}{}{Me temo que no. Perdón por hacerle perder el tiempo con mi ociosa curiosidad.}
{253}{}{No, sólo estoy vagando sin nada que hacer. Si no me hacen caso aquí, me iré a otra parte.}
{254}{}{Por favor, es importante que lo escuche de ti.}

{255}{}{Excelente. Los hermanos te mostrarán la salida.}
{256}{}{No necesito un guía para encontrarla.}
{257}{}{Que amable eres.}

{260}{}{Esto se está tornando interesante. ¿Qué *quieres* de mí?}
{261}{}{Obviamente, tu vida. Sería imprudente dejar vivo a un tirano como tú.}
{262}{}{Se trata de la Villa. Mi nombre es }
{263}{}{, mi comunidad ya no es lo que era.}

{264}{}{Soy un mensajero de la Hermandad del Acero. Espero que me des una cálida bienvenida y tu plena cooperación}
{1264}{}{Soy una mensajera de la Hermandad del Acero. Espero que me des una cálida bienvenida y tu plena cooperación}
{265}{}{La Hermandad del Acero es nuestra leal amiga y fiel colaboradora. Es un placer conocerle. Se le proporcionará toda la asistencia que necesite.}
{266}{}{No pensé que la Hermandad pudiera tener reclutas tan arrogantes. Pero la Hermandad es nuestra leal amiga y fiel colaboradora. Quédate en la catedral. Se te dará toda la asistencia que necesites.}
{267}{}{Gracias, señor Aaron. Usted es muy amable.}
{268}{}{Basta de ser formales, Aaron. Estoy aquí en una misión.}

{270}{}{Ulysses me hizo saber que vendrías. Dijo que serás muy útil para nuestra causa. Bueno, no me decepciones, }
{271}{}{ , de la Villa.}
{272}{}{Haré todo lo que esté a mi alcance, señor Aaron.}
{273}{}{Soy el mejor en lo que hago, no te preocupes.}
{1273}{}{Soy la mejor en lo que hago, no te preocupes.}
{274}{}{Ulysses Grant me dijo que viniera aquí.}

# Después de ser enviado a la fuerza a Two-Sun
{280}{}{¡Santo Átomo! ¡Te envié a ser un esclavo a Two-Sun! ¿Cómo es posible que estés libre?}
{281}{}{Logré escapar. ¡Y ahora vas a pagar por todo lo que has hecho!}
{282}{}{¡Hermanos, deténganlo! ¡Deténganlo!}
{283}{}{¡No pueden detenerme!}
{284}{}{Logré llegar a un acuerdo con los Hojalateros.}
{285}{}{Esto me parece muy sospechoso. Pero hasta que ocurra algo que invalide tus palabras, eres libre. Aprecia este tiempo que te concede el Fuego Santo.}
{286}{}{¿Sospechoso? Por supuesto, sólo estoy aquí para vengarme.}
{287}{}{Es lo que intento.}
{288}{}{Abre los ojos, no eres todopoderoso.}
{289}{}{Hmm. Puedes respirar el aire de la libertad, por ahora. Aprecia este tiempo que te concede el Fuego Santo. ¡Ahora, lárgate!}
{290}{}{No tan rápido, tirano. No me iré de aquí sin tu vida.}
{291}{}{Me parece una decisión razonable.}
{292}{}{Enviarte a Two-Sun fue un error.}
{293}{}{¿Un error? Depende de a quién le preguntes. A mí me parece perfecto.}
{294}{}{Hermanos, desháganse de este ser miserable.}
{295}{}{Ajá.}
{296}{}{[Entrar al combate]}
{297}{}{N-no...}
{298}{}{Asegúrate de que esté error no termine siendo fatal para ti. Y agradece al Fuego Santo por haberte concedido la libertad.}
{299}{}{Vaya, vaya.}

# Diálogo repetido
{300}{}{¿Qué es lo que quieres?}
{301}{}{¿Te atreves a distraerme de mis importantes asuntos, campesino?}
{1301}{}{¿Te atreves a distraerme de mis importantes asuntos, campesina?}
{302}{}{Vale. ¿Qué puedes decirme?}
{303}{}{Mensajero de la Hermandad, me alegro de verte.}
{1303}{}{Mensajera de la Hermandad, me alegro de verte.}
{304}{}{Es bueno verte.}
{305}{}{Estoy feliz de verte, acólito.}
{1305}{}{Estoy feliz de verte, acólita.}
{306}{}{Pensé que nunca te volvería a ver. ¿Qué pasó?}
{307}{}{Que el Fuego Santo te bendiga.}
{308}{}{Adiós.}
{309}{}{Me iré, con su permiso.}

# Preguntas sobre la iglesia y la fe
{310}{}{¿Podría aprender más sobre tu fe?}
{311}{}{Me gustaría aprender más de tu religión.}
{312}{}{Tenemos sermones regularmente en el auditorio del primer piso. No tengo tiempo para esto.}
{313}{}{Me gustaría escucharlo de la fuente más confiable.}
{314}{}{Tenemos sermones regularmente en el auditorio del primer piso. No tengo tiempo para explicarle esto a cualquier hereje.}
{315}{}{Entonces le preguntaré a alguien más.}
{316}{}{¿Hereje, dices? Ya veo, ya veo.}
{317}{}{}
{318}{}{Teme al Fuego Santo, hijo mío.}
{319}{}{Sí, eh, por supuesto.}

{320}{}{Si te interesa nuestra fe, ven a los sermones en el auditorio del primer piso. No tengo tiempo para responder a todos. ¿Tienes algo IMPORTANTE que discutir conmigo?}
{321}{}{En realidad, sí. Vengo a hablar de mi aldea.}
{322}{}{Me temo que no. Perdón por hacerle perder el tiempo con mi ociosa curiosidad.}
{1322}{}{Me temo que no. Perdón por hacerle perder el tiempo con mi ociosa curiosidad.}
{323}{}{No, sólo estoy vagando sin nada que hacer. Si no me hacen caso aquí, me iré a otra parte.}
{324}{}{Por favor, es importante que lo escuche de ti.}

{330}{}{Esto se está tornando interesante. ¿Qué *quieres* de mí?}
{331}{}{Se trata de la Villa.}
{332}{}{Obviamente, tu vida. Sería imprudente dejar vivo a un tirano como tú.}
{333}{}{Excelente. Los hermanos te mostrarán la salida.}
{334}{}{No necesito un guía para encontrarla.}
{335}{}{Que amable eres.}
{336}{}{¡Un asesino! ¡En nombre del Fuego, deténganlo!}
{1336}{}{¡Una asesina! ¡En nombre del Fuego, deténganla!}
{337}{}{Relájate, soy yo quién está a cargo aquí.}
{338}{}{No van a ayudarte.}
{339}{}{El Fuego Santo te bendiga.}

{340}{}{Por supuesto.}
{341}{}{¿Podemos hablar de la Villa?}
{342}{}{Entonces, ¿de qué se trata tu fe?}
{343}{}{Eres el líder de la iglesia, ¿verdad?}
{344}{}{He oído suficiente por hoy. Gracias por hablar conmigo.}
{1344}{}{He oído suficiente por hoy. Gracias por hablar conmigo.}
{345}{}{Te lo voy a repetir, no tengo tiempo para eso.}
{346}{}{Bien, iré a hablar con alguien más.}
{347}{}{Solo estás intentando deshacerte de mí.}

{350}{}{Ya sabes lo suficiente, no es necesario que sepas más.}
{351}{}{Respeto tu interés en nuestras enseñanzas. Pero no todos son capaces de entenderlas.}
{352}{}{[Siguiente]}
{353}{}{Nuestra iglesia pide la aceptación del Fuego Santo como un acto de sanación, como una oportunidad para comenzar la vida de nuevo. Un... renacimiento. Pues sin un renacimiento, las personas siempre estarán en conflictos sin fin entre sí.}
{354}{}{¿Qué es este Fuego Santo?}
{355}{}{Ya lo entiendo. No es necesario que sigas.}
{356}{}{El fuego que abrasó el mundo hace cien años. Lo llamamos santo porque castigó a la corrupta humanidad y limpió la tierra de corrupción, dando así a los descendientes la oportunidad de vivir una vida nueva.}
{357}{}{Pero, ¿Eso no fue algún tipo de arma muy poderosa?}
{358}{}{Técnicamente, sí. Pero eso no importa. Pues el Señor castigó a la gente con sus propias manos. El hombre común ve una bomba nuclear, nosotros vemos el plan de Dios.}
{359}{}{Dijiste "renacimiento". Entonces, ¿la iglesia está tratando de cambiar el mundo?}
{360}{}{Sí, al unir y consolidar las tierras para el objetivo común de la supervivencia. Para hacer eso, debemos regresar y pensar una vez más en la tecnología antigua, resucitar a la energía nuclear y alfabetizar a la gente.}
{361}{}{¿Entonces obligas a otros a aceptar tu fe?}
{362}{}{No, para nada. Tales seguidores serían dañinos a la iglesia. Debe ser voluntario. Además, somos muy selectivos a la hora de aceptar nuevos miembros; cada persona necesita alguien que los recomiende.}
{363}{}{¿Qué quieres decir con "unir las tierras"?}
{364}{}{Una bandera, una nación, un pueblo... una fe. La humanidad debe rechazar estos conflictos mutuamente devastadores y dedicarse por completo al Renacimiento.}
{365}{}{¿Hasta dónde se ha extendido tu iglesia?}
{366}{}{Tenemos capillas en la zona de Fénix y en varias ciudades vecinas. Para los estándares modernos, se trata de un vasto territorio. Pero aún tenemos espacio para crecer.}
{367}{}{Ahora entiendo cómo la iglesia está conectada con los esclavistas.}
{368}{}{Tú también creas conflicto. ¿No se te considera un tirano que usurpó el poder?}

{370}{}{El hombre común ha caído al mismo nivel que un animal y es incapaz de participar en la gran causa del Renacimiento por voluntad propia. La esclavitud es sólo una medida necesaria y temporal para nuestra misión. Además, jamás hemos esclavizado a alguien nosotros mismos, sólo pagamos a mercenarios y hacemos la vista gorda a sus salvajes métodos.}
{371}{}{Suena bien. ¿Puedo unirme a tu secta?}
{372}{}{¡Suficiente! Una religión así no tiene lugar en nuestro mundo. Voy a destruirlos a todos.}
{373}{}{Gracias por hablar conmigo, ahora lo entiendo mejor.}
{374}{}{Por cierto, ¿No son ustedes los que están detrás del secuestro y la esclavitud de los campesinos de la Villa?}
{375}{}{Por cierto, sobre el secuestro y la esclavitud de los campesinos de la Villa.}

{380}{}{¿Y eres tú quien maneja todo este proceso?}
{381}{}{Por supuesto.}
{382}{}{Eso significa que serás la mejor persona para explicarme tu religión.}
{383}{}{Fue bueno conocerte. No me interesa escuchar nada más.}
{384}{}{La gente te considera un tirano. ¿Sabes algo de eso?}
{385}{}{Nada más que palabras maliciosas. Parece ser que la iglesia adquirió esa reputación luego de la revolución. Sí, llegamos al poder a la fuerza. Fue una medida necesaria. Pero nuestros corazones siempre estuvieron llenos de paz. }
{386}{}{Me da la impresión de que tu secta controla la ciudad...}
{387}{}{La iglesia sí pasó a ser algo mucho más grande para Fénix. Gracias a nosotros, la ciencia, la educación y la medicina regresaron a la ciudad. Introducimos la moneda conocida como "chapa", y estamos estableciendo lazos comerciales. Gracias a nosotros, el crimen en la ciudad se ha reducido. Pero la mayoría de los ciudadanos viven fuera de nuestra atención.}
{388}{}{Oh, vaya, esto cambia las cosas. Me gustaría saber más sobre tu religión.}
{389}{}{No importa cómo intentes justificarlo con palabras bonitas, no eres más que un tirano, y te mataré para poner un ejemplo.}
{390}{}{Me temo que debo irme. Mis respetos, señor Aaron.}
{391}{}{Me parece que eres más un tirano que un abad.}
{392}{}{La Iglesia tuvo que asumir la carga de gobernar esta ciudad. Esto es necesario hasta que la sociedad esté preparada para un ayuntamiento y una policía de pleno derecho.}

# Villa
{400}{}{Quiero hablar contigo sobre la Villa.}
{401}{}{}
{402}{}{La Villa... Sí, recuerdo nuestra conversación sobre ese pueblo.}
{403}{}{Creo que hemos discutido todo lo necesario. Adiós, señor Aaron.}
{404}{}{Hm... La Villa... Nunca he oído hablar de ella. Bueno, ¿Qué es lo que quieres? Habla.}
{405}{}{Estoy buscando a mis parientes. Fueron esclavizados.}
{406}{}{Oh, pobre gente. Simpatizo sin cesar contigo y voy a rezar por la salvación de sus almas. Pero, ¿Por qué tu búsqueda te trajo a nosotros?}
{407}{}{¡Tu secta está claramente involucrada en esto! ¡Devuélveme a mis parientes!}
{408}{}{Eso no fue muy cortés de tu parte. No somos más que una iglesia pacífica, no esclavizamos a nadie.}
{409}{}{Estás mintiendo.}
{410}{}{Es triste ver tanta ignorancia. Me obligas a... (uno de los asesores interrumpe al Señor y le susurra algo al oído) Ya veo. ¿Deseas reunirte con tu familia? Podemos arreglar eso.}
{411}{}{¿De verdad? ¿Cómo?}
{412}{}{Entrega tus armas y levanta las manos. Ni siquiera pienses en resistirte. Serás enviado a realizar trabajo forzado, como los demás aldeanos.}
{413}{}{Bueno, si me ayuda a encontrar a mi gente, iré, voluntariamente.}
{414}{}{No me asustas. Saldré justo como entré, como un hombre libre.}
{1414}{}{No me asustas. Saldré justo como entré, como una mujer libre.}
{415}{}{Es una pena que hayamos llegado a esto. ¡Atrápenlo!}
{1415}{}{Es una pena que hayamos llegado a esto. ¡Atrápenla!}
{416}{}{Tus palabras suenan más patéticas que el gemido de un átomo en una nube de fuego. Llévalo a nuestros hermanos en Two-Sun, déjalo servir al Fuego Santo.}
{1416}{}{Tus palabras suenan más patéticas que el gemido de un átomo en una nube de fuego. Llévala a nuestros hermanos en Two-Sun, déjala servir al Fuego Santo.}
{417}{}{(uno de los asesores interrumpe al Señor y le susurra algo al oído) Hm. Parece que tendré que dejarte ir. Pero recuerda, ninguna persona que vaya en contra de la iglesia del Fuego Santo quedará impune.}
{418}{}{De acuerdo, lo tendré en cuenta.}
{419}{}{Solo dime qué tengo que hacer.}
{420}{}{Pensé que sabías todo lo que hay que saber aquí.}
{421}{}{Desafortunadamente, eso no es cierto.}
{422}{}{Bueno, discúlpame. Supongo que iré a otro lado...}
{423}{}{Espera, no me resistiré.}
{424}{}{Como un miembro de la Hermandad del Acero, espero tu plena cooperación en la búsqueda de los campesinos desaparecidos.}
{425}{}{Es extraño que la Hermandad se haya interesado en esos campesinos. Sí, por supuesto, te ayudaremos.}
{426}{}{Entonces, ¿qué sabes sobre ellos?}
{427}{}{Estás mintiendo. No me iré hasta que sepa toda la verdad.}
{428}{}{¡Todos, deténganse! ¡No se acerquen más! ¡Me defenderé!}
{429}{}{Nadie me pondrá un dedo encima. ¿Entendido?}

{430}{}{Basta de esta farsa. Yo *SÉ* que esta iglesia financió la caravana de esclavos.}
{431}{}{Tu insolencia no conoce límites.}
{432}{}{No me iré hasta que sepa qué está pasando.}
{433}{}{Vete en paz, mensajero de la Hermandad.}
{434}{}{Mis respetos.}
{435}{}{¿Estás pretendiendo ser amable? Lo tendré en cuenta.}

{436}{}{¿Quién se atrevió a ponerle una mano encima a tu familia? ¡No toleraré tal acto ante mi obispo!}
{437}{}{Eso es lo que intento averiguar. ¿Me puedes ayudar?}
{438}{}{(le hace un gesto al escriba, quien busca algo en la computadora y luego susurra el resultado) Lo siento mucho, pero tus familiares ya fueron enviados a trabajar en la Zona Prohibida hacia del sur.}

{450}{}{Hmm. ¿Me puedes recordar el nombre de la aldea? (uno de los asesores se acerca al Señor y susurra algo a su oído) Hm... Sí, sabemos donde están los demás aldeanos. Se les dio una segunda oportunidad y están pagando por sus pecados en el sur.}
{452}{}{Recuerdo hablar de esto contigo. Se les dio una segunda oportunidad a los campesinos y están pagando por sus pecados en el sur.}
{453}{}{¿El sur? ¿Dónde, exactamente?}
{454}{}{Algunos fueron dejados en Flagstaff para trabajar en las minas. El resto fueron enviados a Two-Sun para el beneficio del Progreso. Los Hojalateros locales no tienen suficientes trabajadores para la Zona Prohibida. Tal destino es honorable, pues con su sacrificio estos esclavos ayudarán a todo el mundo.}
{459}{}{¿Por qué haces preguntas innecesarias? Mientras estabas bajo su control, tenías la oportunidad de conocer mejor a los Hojalateros. Esta tribu adora a la tecnología antigua, aunque la ven de una manera muy específica.}
{460}{}{¿Quiénes son los Hojalateros?}
{461}{}{Una tribu ocultista de adoradores de la tecnología antigua. Como nosotros, buscan el renacimiento del Viejo Mundo, pero lo ven de una manera exclusivamente tecnólogica. Por ahora, compartimos objetivos comunes, pero algún día los malentendidos llevarán a un conflicto.}
{462}{}{¿Por qué te importa su tecnología?}
{463}{}{Sin la capacidad de manufacturación de los Hojalateros, ni siquiera podríamos tener electricidad en esta catedral. Necesitamos sus máquinas y habilidades.}
{464}{}{Ambos necesitan ser destruidos. Empezando con esta patética e impía catedral.}
{465}{}{Eso lo explica todo. No tengo más preguntas.}
{466}{}{Entonces, ¿La prisión en Flagstaff es tuya?}
{467}{}{La colonia en Flagstaff fue fundada con nuestras chapas. Pero con el tiempo, se volvió libre e independiente.}
{468}{}{¿Por qué necesitas esa colonia?}
{469}{}{Por el uranio de la mina local, obviamente.}
{470}{}{Pero, ¿Por qué la iglesia necesita uranio?}
{471}{}{Es necesario para generar energía nuclear. Sin uranio, es imposible utilizar tecnología antigua. Y sin ella, el 'Renacimiento' de la civilización sería imposible.}
{472}{}{¿Faber no te causa problemas?}
{473}{}{¿Está Faber empezando a causarte problemas?}
{474}{}{Algo así. A veces te comes a la rata y a veces la rata te come a ti. Faber comparte nuestros puntos de vista, pero los interpreta a su manera. Esto a veces causa pequeños conflictos.}
# - Cita de la película "El Gran Lebowski": A veces te comes al oso y, bueno, a veces el oso te come a ti.
{475}{}{Genial. Entonces seguiré sus pasos y me haré cargo de esta iglesia indefensa.}
{476}{}{Creo que debería dirigirme a Flagstaff y ver todo esto personalmente. Adiós.}
{477}{}{En cierto modo. Al permitir que la gente llegue al poder, siempre se corre el riesgo de convertir a un amigo en enemigo. Sin embargo, me he enterado que Faber ya no es... relevante. No está claro si fue asesinado accidentalmente o si se trata de un astuto complot de la revolución local. Aún estamos tratando este asunto.}
{478}{}{¿Qué fue lo que dijiste acerca de los Hojalateros?}

{480}{}{Basta de mentiras. Me voy de aquí.}
{481}{}{Parece que tienes grandes planes. Ahora puedo salir de aquí en paz.}
{482}{}{Pero, ¿por qué patrocinas la esclavitud?}
{483}{}{¿Es por eso que patrocinas la esclavitud?}
{484}{}{La sociedad no está preparada para ser independiente. El hombre común nunca podrá levantarse por sí mismo. Para esto, necesita un tirano y un guía.}
{485}{}{Entonces, ¿eres responsable por la esclavitud de la Villa?}
{486}{}{No seas tan imprudente con tus acusaciones. Simplemente patrocinamos nuestras colonias y demás proyectos con chapas. Y si son necesarios esclavos, las chapas se utilizarán para comprarlos.}
{487}{}{Esto es una desgracia para la iglesia. Debes ser erradicado.}
{488}{}{Un punto de vista interesante. Aunque es poco probable que nos guste.}
{489}{}{La coerción es la peor forma de desarrollar una sociedad.}
{490}{}{Oh, estás equivocado. La sociedad no está preparada para ser independiente. Necesita de un tirano y un guía.}
{491}{}{¿Cómo se relaciona esto con los Hojalateros de Two-Sun?}
{492}{}{Ahora veo la relación entre tú y los carceleros de Flagstaff.}

# Convertirse en seguidor
{500}{}{Estoy considerando unirme a tu iglesia.}
{501}{}{No es tan fácil como crees. Para ser aceptado, necesitas que alguien te recomiende a la iglesia o realizar una gran contribución a nuestra tarea. ¿Qué tienes que decir al respecto?}
{502}{}{Nadie me ha recomendado a la iglesia.}
{503}{}{La iglesia está constantemente bajo ataque. Demuéstranos que podemos confiar en ti, y en ese entonces hablaremos de tu iniciación.}
{504}{}{Intentaré encontrar a alguien que me patrocine.}
{505}{}{¿Cómo puedo demostrar mi lealtad?}
{506}{}{. . . [una prueba]}
{507}{}{Volveré cuando me haya encargado de ello.}
{508}{}{Haré lo que sea por la gloria del Fuego Santo.}
{509}{}{Un vagabundo desconocido como tú no podría cumplir los requisitos.}
{510}{}{Bien, buscaré a alguien que me recomiende.}
{511}{}{Pero, de verdad quiero unirme a tu iglesia.}
{512}{}{Para ser aceptado, necesitas alguien que te recomiende a la iglesia... Pero dudo de la pureza de tus intenciones, campesino.}
{1512}{}{Para ser aceptado, necesitas alguien que te recomiende a la iglesia... Pero dudo de la pureza de tus intenciones, campesina.}
{513}{}{Ulysses Grant me sugirió que hablara contigo.}
{514}{}{Soy parte de la Hermandad del Acero, ¿Es suficiente?}
{515}{}{Tengo una carta de recomendación escrita por un predicador en Flagstaff.}
{516}{}{(escucha los susurros del asesor) Esta carta ya no significa nada. Fuera.}
{517}{}{Pero...}
{518}{}{Tenía una carta de recomendación de Flagstaff, pero parece que la perdí.}
{519}{}{Ya no quiero unirme a tu religión. Adiós.}
{520}{}{Arthur Carrington puede recomendarme.}
{521}{}{El Hermano Francis puede recomendarme.}
{522}{}{Dame una oportunidad.}
{523}{}{Tengo una carta de recomendación escrita por George Crook.}

{530}{}{En ese caso, me alegra verte en nuestra morada de sabiduría y progreso. Nuestra iglesia busca sanar al mundo de las heridas infligidas por la Gran Guerra. Y tú nos ayudarás en esta dura misión.}
{531}{}{Genial. ¿Qué puedo hacer por la iglesia?}
{532}{}{Espero que tengas claro que la iglesia tiene muchos enemigos. Y últimamente, esa hostilidad va en aumento. Varios acólitos fueron asesinados en la calle, a plena luz del día. Te pido que investigues estos crímenes.}
{533}{}{Lamentarán haberles hecho daño. Pero, ¿por dónde debería empezar?}
{534}{}{Encuentra a Gabriel; suele predicar en las puertas de la ciudad y está bien informado sobre lo que ocurre en ella. Pero debes tener... cuidado. Su fanatismo a veces asusta incluso a los miembros de nuestra iglesia.}
{535}{}{Volveré cuando haya resuelto el asunto.}
{536}{}{Lo haré lo mejor que pueda.}

# Primera misión
{550}{}{Quiero hablarte acerca de los crímenes contra la iglesia.}
{551}{}{¿Ya estás más cerca de la verdad?}
{552}{}{Desafortunadamente, no. Este caso tiene demasiadas incógnitas.}
{553}{}{Lamento oír eso. Pero no pierdas la esperanza, habla con Gabriel en las puertas de la ciudad, él te contará los detalles de los ataques.}
{554}{}{Bien, iré a hablarle.}
{555}{}{Parece que tus enemigos son peligrosos. Están bien organizados y cuentan con buen equipamiento. Lo más importante, es que te están vigilando.}
{556}{}{¿Quieres decir que esos ataques fueron planeados? ¿Que alguien estaba vigilando a los acólitos y preparando los ataques desde hace tiempo?}
{557}{}{Sí.}
{558}{}{(se acerca al altar, con los labios fruncidos) Es posible que así sea. Pero nadie más allá de este edificio conoce nuestras rutinas. Los horarios para los acólitos se agendan con una semana de antelación. Si los atacantes estaban preparados, como dijiste, ¿cómo se enteraron de esos planes?}
{559}{}{¿Quién tiene acceso al horario?}
{560}{}{Cada sacerdote elabora el horario de sus acólitos y lo envía a la biblioteca. Sólo unas pocas personas tienen acceso a la lista general.}
{561}{}{Parece que necesito visitar la biblioteca. Me voy, con su permiso.}
{562}{}{Entonces, iré a averiguarlo.}
{563}{}{Bueno, no sé. Quizás sea verdad...}

{570}{}{Matthias era el espía. Vigilaba el horario de los acólitos y enviaba la información a tus enemigos por radio.}
{571}{}{(Los labios de Aaron se enrojecen de ira) Matthias... Debería haberlo adivinado. ¿Cómo podría uno de mis asesores más confiados haberme traicionado? ¡Guardias! Arresten a Matthias.}
{572}{}{Sé amable con él, es un hombre respetable.}
{573}{}{Por supuesto. Deberías rostizarlo con una pica de ganado.}
{574}{}{(deambula pensativo) Hay traición en todos lados... No puedo confiar ni siquiera en mis subordinados más cercanos. A nadie se le podría haber ocurrido que Matthias odiaba tanto la situación en la iglesia.}
{575}{}{¿Estaba en contra de tus políticas, verdad?}
{576}{}{Matthias abogó por el aislamiento de la iglesia del mundo exterior y la conservación total de nuestros artefactos. No quería compartirlas con forasteros y no veía a nadie que fuera digno de ellas. Yo no estuve de acuerdo. Ha llegado el momento de que ese conocimiento sea sacado del polvo y la mugre, en nombre del Fuego Santo.}
{577}{}{Parece que eso no le gustó a todos.}
{578}{}{(pone una cara amable) Lo has hecho bien, hermano. Lo más importante es que demostraste tu lealtad. Necesitaré tu ayuda para limpiar la inmundicia de Fénix.}
{1578}{}{(pone una cara amable) Lo has hecho bien, hermana. Lo más importante es que demostraste tu lealtad. Necesitaré tu ayuda para limpiar la inmundicia de Fénix.}
{579}{}{Lo que sea por el Fuego Santo, su santidad.}
{580}{}{¿Qué es lo que necesita de mí?}
{581}{}{Parece ser que una pandilla de rebeldes está operando en nuestra ciudad. Están bien organizados y armados. Tendremos que sacarle toda la información posible a Matthias, pero eso no será suficiente. Tienes que encontrar su escondite e infiltrarte en su organización. ¿Puedes hacerlo?}
{582}{}{Tal vez. Pero, ¿Por qué yo?}
{583}{}{Para nuestra iglesia, eres una cara nueva. Dudo que los rebeldes te reconozcan como uno de nosotros.}
{584}{}{Si encuentro dónde su escondite, ¿qué debería hacer?}
{585}{}{Ven y cuéntamelo. Entonces decidiremos qué hacer.}
{586}{}{¿Y cómo voy a hacer eso?}
{587}{}{Matthias utilizó la radio para comunicarse con los rebeldes. Además, muchos ciudadanos podrían estar conectados a este grupo. Has lo que sea necesario.}
{588}{}{Haré lo que pueda. Con su permiso, me voy.}
{589}{}{Pero, ¿Por qué yo?}
{590}{}{Resultaste ser bastante exigente con lo que consideras "digno", ¿verdad?}

#Cosas incluidas por Cambragol, no tengo claro cómo funcionan pero las dejo aquí por si acaso
{591}{}{Sí, Matthias parece haber estado vigilando las rutinas de los acólitos últimamente...}
{592}{}{Sí, Matthias parece haber estado usando la radio para comunicarse con alguien afuera de la catedral...}
{593}{}{¿Matthias? ¿Perdiste la cabeza? Es uno de los asesores en los que más confío. Busca en otro lado, idiota.}
{594}{}{Eh, sí, claro, mi señor.}

# Segunda misión
{600}{}{Ya tengo más clara la situación con los rebeldes.}
{601}{}{¿En serio? Cuéntame más.}
{602}{}{Sinceramente, todo esto son rumores. Es mejor que no nos apresuremos a sacar conclusiones.}
{603}{}{Los rebeldes están escondidos en las alcantarillas. Su líder está muerto, y su facción está divida y aplastada.}
{604}{}{...Bien. Enviaré unos súbditos a limpiar su guarida, a ti, debo felicitarte. Parece ser que el Fuego Santo decidió iluminarnos usando tu cuerpo.}
{605}{}{Puedo seguir sirviendo a la iglesia, si es necesario.}
{606}{}{No lo dudo, joven acólito. Necesitamos aliados, más que nunca.}
{607}{}{¿Cómo puedo ayudar, Señor Aaron?}
{608}{}{Ya sé dónde está el escondite del Partido de la Liberación.}
{609}{}{Puede que hayas encontrado a nuestros predicadores afuera de Fénix. La iglesia crece y abre sus capillas en donde la gente esté lista para escucharnos. Pero la aldea de San Brahmán se ha vuelto un obstáculo para nuestra fe.}
{610}{}{[Siguiente]}
{611}{}{Los lugareños, al inicio amistosos, se han vuelto agresivos a la iglesia por alguna razón. Hemos intentado razonar con ellos y sólo ha empeorado la situación, no sabemos exactamente qué ocurre. Por ahora, el destacamento de George Crook está estacionado cerca de su pueblo. Encuéntralo y ofrece tu ayuda. Necesitamos a alguien que restaure nuestros acuerdos comerciales con la aldea.}
{612}{}{[Siguiente]}
{613}{}{Aquí tienes 350 chapas, para el camino y para comprar todo lo que necesites. Ve, y que el Fuego Santo te bendiga.}
{614}{}{Ya me voy, Señor Aaron. San Brahmán creerá en el poder del Fuego Santo.}
{615}{}{Lo haré lo mejor que pueda.}
{616}{}{Ya has ayudado a muchos, amigo mío. George Crook me habló de tu hazaña. Iba a enviarte a ayudarlo, pero te adelantaste. Quiero escucharlo todo de ti: ¿Cómo va nuestra misión en San Brahmán?}
{1616}{}{Ya has ayudado a muchos, dama del Átomo. George Crook me habló de tu hazaña. Iba a enviarte a ayudarlo, pero te adelantaste. Quiero escucharlo todo de ti: ¿Cómo va nuestra misión en San Brahmán?}
{617}{}{Así es, tengo mucho que contarte.}

#Third quest
{630}{}{Necesito hablar contigo sobre la situación San Brahmán.}
{631}{}{Por supuesto. ¿Qué noticias tienes, joven acólito?}
{632}{}{Pronto iré y me enteraré de los detalles. Adiós.}
{633}{}{[TRAMPA: el trabajo está hecho con el mejor resultado posible para el Señor Supremo]}
{634}{}{[Bla bla gloria al Fuego - bla bla habla con el Asesor del refugio, aquí tienes la llave y la autorización bla bla mata a George Crook]}
{635}{}{[TRAMPA: termina misiones - obtén el título + eres enviado al refugio + recompensa + frecuencia de radio de la catedral]}
{636}{}{He sido victorioso, Señor Aaron. El jefe de la tribu selló la alianza, y el destacamento de Crook se asentó cerca de la villa.}
{1636}{}{He sido victoriosa, Señor Aaron. El jefe de la tribu selló la alianza, y el destacamento de Crook se asentó cerca de la villa.}
{637}{}{¡Gloria al Fuego Santo! ¿Será que Dios te trajo con nosotros en estos tiempos difíciles? Es un milagro. Y mereces la recompensa más alta posible.}
{638}{}{Para mí, esto fue una misión sagrada.}
{639}{}{No sé si ayudó el Fuego Santo, pero ya está hecho.}
{640}{}{Hmm, en su informe, George Crook elogia tus habilidades y lealtad al Imperio Fénix. Considerando lo que has hecho por la iglesia, no podría negarte una recompensa.}
{641}{}{Sería un honor, Su Santidad.}
{642}{}{¿Cuál sería esa recompensa?}
{643}{}{Por tus servicios al Imperio Fénix, solemnemente te nombro mi obispo. Toma esta bendecida túnica como una muestra de mi gratitud. Que te proteja de tus enemigos y de las mentiras.}
{644}{}{Gracias.}
{645}{}{También es hora de iniciarte en nuestro círculo interno. Aquí tienes la llave al sótano. Allí encontrarás un antiguo santuario, diles a los guardias que te lleven con Ulysses Grant. Le avisaré que harás una visita.}
{646}{}{[Más]}
{647}{}{Ve, amigo mío. Que el Fuego Santo te bendiga.}
{648}{}{Gracias por el honor, Señor Aaron.}

{650}{}{Mi señor, tengo terribles noticias - George Crook murió durante su misión.}
{651}{}{(respira hondo y cruza los dedos) Que el Fuego Santo cuide su alma. Fue el mejor guerrero que haya conocido. Pero, incluso si él no pudo con los salvajes, ¿Quién podría ocuparse de su misión?}
{652}{}{No creo que yo pueda.}
{653}{}{Quizás yo pueda.}
{654}{}{¡Regresa a San Brahmán y conquista la tribu en nombre del Fuego! Esta es tu misión sagrada. Y si no puedes, siembra la discordia en la tribu. Mata a su líder supremo para que los salvajes luchen entre sí por el trono. Has que los rangers se vayan del pueblo. Ve. ¡Ve!}
{655}{}{Sí, mi señor...}
{656}{}{Malas noticias. La tribu formó una alianza con los rangers, quiénes expulsaron a los misioneros del pueblo y los alrededores.}
{657}{}{(respira hondo y cruza los dedos) Es demasiado tarde. ¿¡Cuánto nos esforzamos en conquistar a la tribu!? ¡Fue todo en vano!}
{658}{}{¿Está todo perdido?}
{659}{}{Quizás pueda convencer al jefe.}
{660}{}{El líder está muerto. La tribu está dividida. Ahora será difícil que los rangers se aprovechen de la situación.}
{661}{}{Es difícil aceptar la derrota. ¿Pero cuánta persecución hemos soportado antes? Está bien, podemos esperar. Los salvajes cayeron a su nivel después de muchas generaciones. Probablemente lleve todo ese tiempo traerlos de vuelta a un estado civilizado.}
{662}{}{[Escucha]}
{663}{}{Y tu servicio se ha acabado. Por mucho que me gustaría echarte de la catedral por tus tantos fracasos, mis asesores no piensan así. Permitiré que hables con mi Asesor principal, Ulysses Grant. Toma esta llave y baja al sótano. Los guardias te llevarán con Ulysses, él está esperándote.}
{664}{}{Gracias, mi señor.}
