{100}{}{Ves a Bruce.}
{101}{}{Estás viendo a un hombre que lleva puesto un traje de negocios, su mirada es tranquila y expresa una clara indiferencia a la vida humana.}
{102}{}{Así que esto es una servoarmadura... Es impresionante, pero no creas que hablaremos si la llevas puesta.}
{103}{}{Otro drogadicto más. Lárgate y regresa cuando estés limpio.}

#Introductory threads
{200}{}{Soy Bruce Turner, te doy la bienvenida al Gremio de Mercenarios. ¿Estás buscando guardias con experiencia? ¿O buscas poner una recompensa... o cobrarla?}
{201}{}{Tal vez.}
{202}{}{...}

{210}{}{Mierda, ¿qué demonios le pasó a tu piel?}
{211}{}{Una pizca de virus y una cucharadita de radiación. No es nada.}
{212}{}{Hm. No bromearía acerca de eso, si fuera tú.}
{213}{}{Ya me acostumbré a estas cosas, suavecito.}
{214}{}{Si fueras yo, ya estarías muerto.}
{215}{}{¿Acaso te da risa, normalucho?}
{216}{}{(frunce el ceño) No. Para nada, grandulón.}
{1216}{}{(frunce el ceño) No. Para nada, preciosa.}
{217}{}{Bien.}
{218}{}{Puede que me lo tome personalmente, si lo haces de nuevo.}

{220}{}{Buen día, señor. El placer es mío. ¿Acaso alguien ha resultado ser una molestia para usted?}
{1220}{}{Buen día, señorita. El placer es mío. ¿Acaso alguien ha resultado ser una molestia para usted?}
{221}{}{¿Por qué estás siendo tan educado de repente?}
{222}{}{Sin duda, se merece un trato adecuado... señor.}
{1222}{}{Sin duda, se merece un trato adecuado... señorita.}
{223}{}{Vaya, así que tú eres el campesino del que todos están hablando. No creo que entiendas cómo comportarte en una ciudad como esta. ¿Te crees intocable?}
{224}{}{Los citadinos son tan maleducados. Nosotros somos mucho más amistosos.}
{225}{}{Deberías haberte quedado en tu pueblo. Voy a enterrarte entre las arenas...}
{226}{}{¿Qué estás haciendo...?}
{227}{}{Sé cómo defenderme.}
{228}{}{Lo que hago, es porque necesito sobrevivir. No puedes juzgarme.}
{229}{}{Oh, claro que no. La ciudad me paga por capturar criminales, y resulta que estás en mi lista. Oigan, chicos... (te apunta con el dedo)}
{230}{}{Bruce, no hagas esto...}
{231}{}{Sé cómo defenderme.}
{232}{}{No quiero luchar, ¿no podemos llegar a algún acuerdo?}
{233}{}{Todos están sobreviviendo a duras penas, y tú tampoco te estás ganando la vida honestamente.}
{234}{}{Hmph. Quizás tengas razón... No sé a quién creerle. Pero, no lo olvides - si no te largas de esta ciudad, quedarás colgando de un poste de luz. ¿Lo entendiste?}
{235}{}{Lo entiendo.}
{236}{}{¿Sabes qué? Púdrete, Bruce, tú y todo tu maldito gremio.}
{237}{}{Me agrada saber eso.}
{238}{}{No esperaba que alguien como tú sea un adulador, pero lo aprecio.}

{240}{}{No te muevas. Primero, quiero saber qué pasó entre los Seguidores del Fuego y tú.}
{241}{}{Eso era entre ellos y yo. No es asunto tuyo.}
{242}{}{No, no funciona así. Esto es el Gremio de Mercenarios. He trabajado con los Seguidores del Fuego durante años, al transportar esclavos y convictos por el yermo. Y de repente, llegas y me tiras a la basura un montón de contratos. ¿Qué te pasa?}
{243}{}{Ya te lo dije, era entre ellos y yo. Es personal.}
{244}{}{Por lo tanto, tienes que estar hablando de rencor, una venganza o algo así. Entiendo. Pero, tienes suerte de que los Seguidores no hayan ofrecido una recompensa por ti. Si lo hacen, tendré tu cabeza, lo prometo.}
{245}{}{No creo que quieras verme aquí, mejor me voy.}
{246}{}{Bruce, no creo que llegue a eso. Hasta luego.}

{247}{}{Adiós, bandidos.}
{248}{}{[levántale el dedo]}
{249}{}{Lo que tú digas, 'jefe'.}
{250}{}{Qué sorpresa. Lo normal es que perseguir a los criminales, no que vengan a nosotros.}
{251}{}{Pero, no he cometido crímenes.}
{252}{}{¿A quién le dices criminal?}
{1252}{}{¿A quién le dices criminal?}
{253}{}{¿Sabías que Flagstaff te declaró como su persona más buscada? Tienes suerte, porque no han ofrecido alguna recompensa por ti. Sin embargo, ahora te conozco y sé en dónde podría encontrarte. Recuérdalo, compórtate.}
{254}{}{Claro que sí, sheriff.}
{255}{}{Pendejo, no soy el sheriff. Pero si me obligas, voy a ser peor que cualquier sheriff.}
{1255}{}{Pendeja, no soy el sheriff. Pero si me obligas, voy a ser peor que cualquier sheriff.}
{256}{}{Sí, te creo.}
{257}{}{No puedo creer que no conozcas el sarcasmo. Hablamos cuando te hayas relajado, 'sheriff'.}
{258}{}{Lo mismo digo. Sé en dónde encontrarte, no lo olvides.}
{259}{}{(con lentitud, coloca la mano sobre su ametralladora mientras te mira a los ojos) Sal de mi oficina. Ahora.}

{260}{}{Te doy la bienvenida a... Alto, muéstrame tu cuello. Los collares de esclavos dejan marcas de ese tipo, es muy extraño que un esclavo fugitivo decida venir aquí. ¿Qué quieres, *esclavo*?}
{1260}{}{Te doy la bienvenida a... Alto, muéstrame tu cuello. Los collares de esclavos dejan marcas de ese tipo, es muy extraño que una esclava fugitiva decida venir aquí. ¿Qué quieres, *esclava*?}
{261}{}{No me llames así, o te arrepentirás.}
{262}{}{Parece que no entiendes la situación en la que te encuentras. Chicos... (te apunta con el dedo)}
{263}{}{¡No me hagas nada...!}
{264}{}{Los voy a matar a todos, esclavistas...}
{265}{}{Quiero mi libertad de vuelta, los Hojalateros me trataron muy mal.}
{266}{}{Hmm. Los Hojalateros no querrán comprarme un fugitivo al mismo precio. Me has dejado en una posición incómoda. Pues, estoy dispuesto a comprar tus derechos y así firmar tu libertad, pero eso te costará 1.000 chapas. Y dudo que tengas ese monto.}
{1266}{}{Hmm. Los Hojalateros no querrán comprarme una fugitiva al mismo precio. Me has dejado en una posición incómoda. Pues, estoy dispuesto a comprar tus derechos y así firmar tu libertad, pero eso te costará 1.000 chapas. Y dudo que tengas ese monto.}
{267}{}{Lo conseguiré.}
{268}{}{Entonces, no me dejas elección... Hora de morir.}
{269}{}{Hmm. Vale, es un trato. Estaré esperando esas 1.000 chapas.}

{270}{}{(entrecierra los ojos al verte el rostro) Hmm. Hace unos días, me llegó una descripción acerca de uno de los Escudos Azules. Y es sospechoso, porque te pareces mucho.}
{1270}{}{(entrecierra los ojos al verte el rostro) Hmm. Hace unos días, me llegó una descripción acerca de una de los Escudos Azules. Y es sospechoso, porque te pareces mucho.}
{271}{}{Es sólo una coincidencia, ¿qué evidencia tienes?}
{272}{}{No. Pero no te quitaré el ojo de encima.}
{273}{}{Vale.}
{274}{}{¿Qué tal si te enfocas en tus propios asuntos?}
{275}{}{Los Escudos Azules han estado negociando, fui su mediador.}
{276}{}{Hmph. Eso es muy interesante, si resulta ser verdad, puede que seas una persona decente. Bueno, es mejor que te cuides la espalda mientras estés en Fénix. A sus ciudadanos no les agradan los forajidos.}
{277}{}{Se han hecho un montón de enemigos, eso no lo dudo.}
{278}{}{Eres muy metiche para tu propio bien, Bruce. Perdona, pero tengo que matarte...}

{280}{}{Esa armadura... ¿En dónde la conseguiste?}
{281}{}{Es un trofeo, lo gané en batalla.}
{282}{}{Hmm. Está bien, te creo. Es mejor que no la andes mostrando en esta ciudad, mucha gente ha oído hablar de los forajidos y puede asuman que eres uno de ellos.}
{283}{}{Gracias por el aviso.}
{284}{}{Los ciudadanos no me preocupan ni un poco.}
{285}{}{Fue un regalo, de un buen amigo.}
{286}{}{Tus amigos son peligrosos. Te recomiendo quitarte esa cosa mientras estés en Fénix, los ciudadanos han oído hablar de los forajidos, entonces, puede que accidentalmente te disparen por al espalda.}

{290}{}{Ahí estás, otra víctima del yermo. Se dice que provocaste un montón de problemas en Casa Grande. ¿Es eso cierto?}
{1290}{}{Ahí estás, otra víctima del yermo. Se dice que provocaste un montón de problemas en Casa Grande. ¿Es eso cierto?}
{291}{}{¿De qué hablas? Me llevo muy bien con su gente.}
{292}{}{Amigo, no me mientas. Mis fuentes rara vez se equivocan.}
{1292}{}{Cariño, no me mientas. Mis fuentes rara vez se equivocan}
{293}{}{¿Por qué te importa?}
{294}{}{Sí, tuve un problemita por allá. Se lo merecían.}
{295}{}{(levanta una ceja) ¿Es una confesión? Eso lo hace más fácil, casi nadie es honesto.}
{296}{}{¿Cuál es el problema?}
{297}{}{Estás de suerte, porque sus ciudadanos siguen sin ofrecer una recompensa por ti. Eso podría cambiar en cualquier momento, no lo olvides.}
{298}{}{Hmph. Voy a mantener un perfil bajo.}
{299}{}{Lo dudo mucho.}

# Basic dialogue
{300}{}{Te doy la bienvenida. ¿Qué necesitas?}
{301}{}{Te lo advierto, no hagas nada raro. ¿Qué quieres?}
{302}{}{He venido a representar a Chuck, de los Escudos Azules.}
{303}{}{Claro, dame un minuto... Ya veo, es un ladrón de ninguna importancia, el alcalde de Casa Grande ofrece una recompensa por él. ¿Has venido a pagar la fianza, o a recolectar el dinero? Se ofrecen 250 chapas por él.}
{304}{}{Voy a pagar su fianza, aquí tienes.}
{305}{}{He sacado a ese criminal de nuestra lista, también se lo haré saber a Casa Grande.}
{306}{}{Gracias.}
{307}{}{No puedo permitirme eso. Adiós.}
{308}{}{}
{309}{}{Ahí nos vemos.}

# Slave title
{310}{}{Quiero comprar mi libertad.}
{311}{}{Ya hablamos sobre esto, ¿cuentas con 1.000 chapas?}
{312}{}{No.}
{313}{}{Entonces, ¿para qué preguntas?}
{314}{}{Carajo...}
{315}{}{Aquí las tienes.}
{316}{}{Te seré honesto, me sorprendes. Dudo que hayas obtenido esas chapas de forma honesta, pero prefiero no saberlo.}
{317}{}{¿Y qué hay de mi libertad?}
{318}{}{Esto nos va a llevar un rato...}
{319}{}{Yo te espero...}
{320}{}{Hecho. Desde hoy, oficialmente, eres un hombre libre. Te felicito. Es tu segunda oportunidad, aprovechala.}
{1320}{}{Hecho. Desde hoy, oficialmente, eres una mujer libre. Te felicito. Es tu segunda oportunidad, aprovechala.}
{321}{}{Por supuesto, lo haré. Adiós.}
{322}{}{Oye, no es como si me hubieras liberado de verdad, siempre fui libre, sólo quería salirme de tu estúpida lista.}
{1322}{}{Oye, no es como si me hubieras liberado de verdad, siempre fui libre, sólo quería salirme de tu estúpida lista.}

# Quest of the Cardinals
{323}{}{Te arrepentirás de esto.}
{324}{}{Bruce, déjalo ir. Es un viejo amigo. ¿No me dirás que no, verdad?}
{325}{}{Eres una persona respetada en la ciudad, así que haré lo que me pides. Pero te lo advierto, no te metas con los Cardenales. Si trabajas con ellos, manchar tu reputación será muy fácil.}
{326}{}{Ya veré qué hacerle. Gracias por ser tan comprensivo, Bruce.}
{327}{}{Es un viejo amigo mío, no es culpable de nada. Déjalo ir.}
{328}{}{Ni puta idea de quién eres y en esta ciudad tu palabra no vale nada. Si vuelves a interferir con mi trabajo, terminarás en la misma celda que él por intentar ayudarlo y ser su cómplice.}
{329}{}{Ya, ya entendí.}
{330}{}{Me enteré de que capturaste a un Cardenal Rojo.}
{331}{}{Sí, está sentado en la jaula de allá, reflexionando sobre su futuro. Dime, ¿cómo es que TU lo sabes? Además del equipo que lo capturó, nadie sabe de esto.}
{332}{}{Tengo mis contactos. ¿De qué se le acusa?}
{333}{}{A este asunto no le hace falta la atención pública. Nuestro cliente quería que pusiéramos fin al trato, eso es lo único que sé.}
{334}{}{Entiendo. Ojalá atrapes más criminales.}
{335}{}{Necesito hablarle, te daré 10 chapas.}
{336}{}{Vale, tienes 10 minutos.}
{337}{}{Aquí tienes.}
{338}{}{En otro momento.}
{339}{}{¿Cuánto te pagaron por capturarlo? Puedo darte más, a cambio de su libertad.}
{340}{}{Hmm. De por sí, fue un asunto de poca importancia. La fianza es de 100 chapas.}

{341}{}{Vale, aquí están las 100 chapas.}
{342}{}{Eso es demasiado, él no vale tanto dinero.}
{343}{}{¿Está bien si hablo con él? Puedo darte 10 chapas.}
{344}{}{De acuerdo, puede irse. Sin embargo, lo más probable es que en algún punto lo volvamos a capturar. ¿Conoces a los Cardenales, no? Sólo son un montón de matones y criminales. Son una amenaza para la sociedad.}
{345}{}{Eso no te lo niego.}
{346}{}{A la Iglesia del Fuego Santo le preocupa lo sucedido, este hombre era parte de nuestro servicio de espionaje. Déjalo ir. De inmediato.}
{347}{}{Justo lo que pensé, ya decía yo que este caso era sospechoso. Vale, no quiero problemas con la iglesia, así que lo dejaré ir. Pero en ese caso, ya no nos hacemos responsables por él, es asunto suyo.}
{348}{}{Gracias por ser tan comprensivo, Bruce.}
{349}{}{De acuerdo..}

# Questions about slaves
{350}{}{Dime qué se hace aquí.}
{351}{}{Este es el Gremio de Mercenarios. Ofrecemos personas fuertes para trabajos peligrosos. Los trabajos más comunes son los de guardias, o capturar criminales. ¿Necesitas algo así?}
{352}{}{No, nada de ese estilo.}
{353}{}{Bueno, si te llega a hacer falta, con gusto te ayudo. Por una suma de chapas, por supuesto.}
{354}{}{Sí, eso es obvio..}

{360}{}{¿Estás involucrado en la trata de esclavos?}
{361}{}{¿Te refieres a los contratos por esclavos? No hay mucha gente que pueda permitirse eso.}
{362}{}{¿Quiénes, por ejemplo?}
{363}{}{Los clientes principales son la colonia de Flagstaff y los Hojalateros. Pero yo no los llamaría esclavos. Lo normal es que sean criminales cumpliendo su sentencia. ¿Por qué lo preguntas?}
{364}{}{Eh, sólo tenía curiosidad.}
{365}{}{La curiosidad puede levantar sospechas. Ojalá que entiendas lo que eso implica.}
{366}{}{Eh, eso creo.}
{367}{}{Estaba pensando en comprarme un par de esclavos.}
{368}{}{Eso no va a ocurrir, no te daremos un sólo prisionero.}
{369}{}{Olvídalo.}
{370}{}{Estoy buscando a unos esclavos, provienen de la Villa.}
{371}{}{La Villa... No me suena de nada.}
{372}{}{IEstoy buscando a unos esclavos, provienen de la Villa y los trajeron aquí desde Flagstaff.}
{373}{}{La Villa... No me suena de nada, pero si esos esclavos venían de Flagstaff, no será fácil encontrarlos.}
{374}{}{Ya veo. Disculpa las molestias.}
{375}{}{Vale, tendré que averiguarlo por cuenta propia. Adiós.}
{376}{}{Puedo darte 100 chapas a cambio de esa información.}
{377}{}{Eso me parece razonable. Puedo revisar las facturas de los envíos recientes y contactar a nuestros agentes. Pero, tendrás que pagarme de inmediato.}
{378}{}{Claro, aquí están las chapas. Yo te espero.}
{379}{}{No hace falta, lo averiguaré yo.}
{380}{}{Vale, he revisado las facturas... Hay varios esclavos de la Villa que acabaron en la colonia de Flagstaff. Los Seguidores del Fuego los compraron y fueron trasladados hacia su Catedral. Para darse un viaje así, tuvieron que haber sido muy buenos esclavos. Lo que les haya pasado después de eso, sólo deben saberlo los monjes.}
{381}{}{Gracias, Bruce. Es hora de visitar la Catedral del Fuego.}
{382}{}{Hmph. Podría haber descubierto eso por cuenta propia.}
{1382}{}{Hmph. Podría haber descubierto eso por cuenta propia.}
{383}{}{Vale, he revisado las facturas... Hay varios esclavos de la Villa que acabaron en la colonia de Flagstaff. Los Seguidores del Fuego los compraron y fueron trasladados hacia Two-Sun. Para darse un viaje así, tuvieron que haber sido muy buenos esclavos.}
{384}{}{Gracias, Bruce. Es hora de que visite a esa tal Two-Sun, ojalá que hayan caravanas yendo hacia allá.}
{385}{}{Bruce, te diré la verdad, no me ayudaste casi nada. Adiós.}
{386}{}{Volveré en otro momento, no tengo tantas chapas ahora mismo.}

# Eliminating George Crook
{390}{}{Necesito que lidies con un buscapleitos, se llama George Crook.}
{391}{}{¿El mismo George Crook que derrotó a esa tribu del oeste? ¿Por qué quieres verlo muerto?}
{392}{}{Sólo represento al cliente.}
{393}{}{Comprendo. Ese viejo guerrero se ha hecho muchos enemigos en esta ciudad. Joder, hasta algunos de mis mejores hombres decidieron unirse a él. Y ahora, Crook está despilfarrando chapas, porque está aburridísimo. No entiendo qué hace el casino para aguantar lo que hace mientras anda borracho.}
{394}{}{¿Aceptarás el trabajo?}
{395}{}{Bueno, jamás te dije que lo haría... pero a cambio de 500 chapas, el mundo podrá pretender que él jamás existió.}
{396}{}{Tendré que pensar acerca de esto, tú lo entiendes, es un trabajo difícil.}
{397}{}{Trato hecho. Aquí están las chapas. Y recuerda, esta conversación jamás pasó.}
{398}{}{No te preocupes, nos encargaremos de todo.}
{399}{}{Cuento con ustedes.}

# Headhunting
{400}{}{Me interesa ese asunto de atrapar criminales. ¿A quién buscas y cuánto pagas?}
{401}{}{(suspiro) Otro cazarrecompensas más...}
{1401}{}{¿No preferirías estar en la cocina...? Una mujer cazarrecompensas. ¿Qué le pasa a este mundo?}
{402}{}{¿Qué sucede?}
{1402}{}{Ejem. Tu guardaespaldas también es mujer, ¿lo olvidas?}
{403}{}{Ah, un momento, toda la ciudad anda hablando de un campeón del cuadrilátero, ¿eres tú? Eso cambia las cosas.}
{404}{}{Sé cómo defenderme, te lo aseguro.}
{405}{}{}
{406}{}{}
{407}{}{¿Siquiera tienes un rifle? Este trabajo no es para principiantes, es peligroso. Pero si de verdad quieres arriesgar tu vida, es cosa tuya.}
{408}{}{Puedo hacerlo.}
{409}{}{Si sales de aquí, verás un tablón de noticias, tiene las últimas recompensas que se han ofrecido. Su funcionamiento es simple, encuentras al criminal que se parezca a la descripción, me traes su cabeza y recibes la recompensa. Búscalos en las afueras de Fénix, si caminas un rato seguramente los veas. ¿Alguna otra pregunta? ¿No? Entonces, adelante. Buena suerte.}
{410}{}{Nos vemos luego, Bruce.}
{411}{}{Oye, respecto al tablón de noticias...}
{412}{}{¿Has venido a reclamar una recompensa?}
{413}{}{No. Todavía no.}
{414}{}{Eso pensé. Regresa cuando hayas atrapado a alguien.}
{415}{}{Vale.}
{416}{}{Soy parte de los rangers, estoy interesado en el trabajo que ofreces.}
{417}{}{Por lo general, a los Rangers no les gusta nuestro negocio. Es extraño que a ti sí te interese.}
{418}{}{Podría decirse que soy un llanero solitario.}
{419}{}{De acuerdo...}
{420}{}{Sí, quiero reclamar la recompensa por la cabeza de Hernando Avilés.}
{421}{}{Ah, Fernando, mi viejo amigo. ¡Ya no podrás burlarte de mí, ahora que estás muerto! Déjame ver su cabeza.}
{422}{}{Aquí la tienes.}
{423}{}{Hijo de puta, no sabes el ruido que hacía. Me hace feliz saber que esa bocota jamás volverá a hacer ruido. ¿Y su cabeza? ¿En dónde está?}
{424}{}{Así es. Vengo por la recompensa de Eydie Gormé.}
{425}{}{Eh, hace una vez, fue una belleza que daba espectáculos en el casino. Su vida tomó un giro extraño, no entiendo por qué perdió la cabeza... Mejor dicho, la cordura. ¿En dónde tienes su bella cabecita?}
{426}{}{Voy a cobrar la recompensa por Chucho Navarro.}
{427}{}{Hernando Avilés está muerto, pero no pude agarrar su cabeza.}
{428}{}{No he podido traerte su cabeza, pero Chucho Navarro ha fallecido.}
{429}{}{Eydie Gormé ha muerto, pero se me quedó su cabeza en alguna parte del yermo.}
{430}{}{Si no hay cabeza, no hay recompensa. Pero me alegra enterarme de esto. Vamos a asumir que dices la verdad, hasta que se te refute.}
{431}{}{Eh, bueno.}
{432}{}{¿No me darás ni una chapa? Que mal.}
{433}{}{Has hecho un buen trabajo, aquí están tus 500 chapas. Ojalá que no estés pensando en retirarte como cazarrecompensas, nos hace falta más gente como tú.}
{434}{}{Voy a pensármelo.}
{435}{}{No lo sé, esta actividad es muy peligrosa.}

{436}{}{Hiciste un buen trabajo, ten, tus 500 chapas. Estoy ansioso de que me traigas otra cabeza.}


{440}{}{Un segundo... ese era el último jefe de Los Panchos. Joder, por fin, esa banda está acabada. Tú imagina lo rápido que se hablará de esto en toda Fénix. Estoy seguro de que esto será una especie de celebración para los ciudadanos.}
{441}{}{Claro que sí. Aunque, ¿no se supone que deben haber más jefes?}
{442}{}{Esos tres lideraban los clanes más grandes y letales dentro de Los Panchos. Y el resto no son demasiada amenaza. Sin los jefes, todo su imperio colapsará y los demás saqueadores serán presa fácil. Te apuesto a que los demás clanes ya se están matando entre sí, a ver quién ocupa el cuesto de líder.}
{443}{}{Eso es un poco raro. Pero, ¿sabes qué es más raro? Que esos jefes tenían el mismo aire que tú y tus mercenarios.}
{444}{}{Hmm. Ya tenía que decírtelo algún día... Hemos exagerado un poco sus leyendas. De hecho, esos tres trabajaban como mercenarios en nuestro gremio, aprendieron mucho, pero al sentir cómo era tener poder y control sobre otras personas, les dejó de interesar el trabajo honesto.}
{445}{}{Deberías habérmelo advertido.}
{446}{}{Esas personas eran una desgracia para nuestro gremio, no podemos permitir que nuestra reputación sufra por su culpa.}
{447}{}{Bueno, es entendible.}
{448}{}{La verdad, es que no me importa.}
{449}{}{Ya tuviste suficiente de completar contratos. Por el momento, relájate, pásala bien. Ya se me ocurrirá algún trabajo que darte.}
{450}{}{¿Más trabajo? Eso es genial.}
{451}{}{Después de enterarme de todo esto, no sé si siga trabajando para ti. Adiós, Bruce.}
{452}{}{Eso son buenas noticias, supongo.}
{453}{}{No podría importarme menos, mientras me pagues.}
{454}{}{Claro. Por el momento. Por el momento, relájate, pásala bien. Ya se me ocurrirá algún trabajo que darte.}
{455}{}{¿Más trabajo? Genial, ojalá sea pronto. Hasta luego.}
{456}{}{Ya gané tantas chapas que puedo dejar el negocio. Adiós, Bruce.}
{457}{}{¿Tienes algún trabajo para mí?}

{460}{}{Llegaste justo a tiempo, ya pensaba en enviar a alguien para que te trajera. Tengo un objetivo que ofrecerte. Y esta vez, te pagaré muy bien.}
{461}{}{Hmph. Si estás pagando más, no será nada fácil. ¿Qué fue lo que hizo?}
{462}{}{(te enseña una portada) Este hombre es Gil McCord. Se le conoce como uno de los mejores pistoleros y rastreadores de Arizona. Es bueno en lo que hace y puede lidiar con cualquier problema. Debes eliminarlo.}
{463}{}{Gil McCord... Esto no tiene sentido, me estás ocultando algo. ¿Por qué los mercenarios cazarían a uno de los suyos?}
{464}{}{(suspiro) Vale, puede que haya omitido un par de detalles sobre los demás objetivos. Lo cierto es que, los jefes de Los Panchos... hubo una vez en la que fueron parte del Gremio, eran mercenarios. Aprendieron mucho de nosotros, fue así como establecieron su territorio en las afueras de la ciudad.}
{465}{}{¿Y qué hay de Gil McCord?}
{466}{}{Era tanto su intermediario como su espía. Descubrimos eso después de limpiar las bases de Los Panchos. Resulta que Gil era demasiado codicioso y paranoico, estaba jugando en los dos bandos y así tener un plan de respaldo, en caso de que las cosas empeoraran.}
{467}{}{Deberías haberme contado la verdad desde un principio.}
{468}{}{Gil es una desgracia ante nuestro gremio, no podemos permitir que perjudique nuestra reputación.}
{469}{}{Bueno, lo que sea. Ya es historia.}
{470}{}{Lo entiendo.}
{471}{}{Mata a Gil McCord y tráeme su cabeza.}
{472}{}{Lo haré. Cuenta conmigo.}
{473}{}{Luego de oír todo esto, no sé creo que siga trabajando para ti. Adiós, Bruce.}

{474}{}{Hice tu trabajo sucio. Tengo su cabeza.}
{1474}{}{Hice tu trabajo sucio. Tengo su cabeza.}
{475}{}{(asiente triste con la cabeza) Gil McCord. Fuiste uno de nosotros. Y este fue el resultado de tu codicia. Su historia hará de ejemplo para todos los demás. Se te deben 750 chapas, como acordamos. Sólo espero que este monto no haga que gires la cabeza, como lo hizo Gil. Y... te pido que en el futuro, evites hablar acerca de nuestro secreto.}
{476}{}{No hay problema, jefe. Adiós.}
{477}{}{Luego de todo lo que has visto, no volveré a poner un pie en este lugar.}

{480}{}{Oye, quiero hablarte sobre Gil McCord.}
{481}{}{¿Traes alguna noticia?}
{482}{}{Todavía no.}
{483}{}{¿Se te ocurre en dónde podría estar?}
{484}{}{Dudo que siga aquí en la ciudad. Además, nuestros agentes vieron a alguien con una descripción similar que iba hacia el sur, junto a una caravana. No hay demasiados asentamientos por allá, así que deberías buscar en esa dirección.}
{485}{}{Entonces, podría estar en cualquier lado... No debo perder el tiempo.}
{486}{}{¿Podrías darme alguna cosa para el viaje?}
{487}{}{De por sí, este trabajo te está pagando bien. ¿Qué más quieres?}
{488}{}{Está bien.}
{489}{}{Creo que necesitaré chapas para cubrir el viaje, también necesito munición.}
{490}{}{Pero, ¿cómo se supone que encontraré a este tipo?}

{491}{}{Si es para este trabajo, me parece justo. Te daré 100 chapas para tu viaje. ¿Qué clase de munición necesitas?}
{492}{}{[Munición de 10mm]}
{493}{}{[Calibre .44]}
{494}{}{[Calibre .50]}
{495}{}{[Calibre 5mm]}
{496}{}{¿Tendrás granadas de 40mm para un lanzagranadas?}
{497}{}{Sólo utilizo armas de energía.}
{498}{}{Ahora, ve y encuentra a ese bastardo. Y si no traes su cabeza, no vuelvas. ¿Lo entendiste?}
{499}{}{Entendido, jefe.}
{1499}{}{Entendido, jefe.}

{500}{}{¿Cuánto dirías que se puede confiar en tu gente? ¿Qué habilidades tienen?}
{501}{}{Mi gente recibe una formación periódica, ellos saben lo que valen. Y yo sé quién es más adecuado para un trabajo o el otro. No te preocupes, en su campo, son profesionales.}
{502}{}{¿En el campo de asesinar?}
{503}{}{Exacto. Son asesinos. Fríos y calculadores.}
{504}{}{Eso me parece genial. ¿Cómo puedo volverme un ASESINO? ¿Podrías entrenarme también?}
{505}{}{Eh, ya hablamos demasiado acerca de matar. ¿Podemos cambiar de tema?}
{506}{}{Debes saber que es costoso, y tú no estás en el gremio. Si consideramos todos los costos, serán 50.000 chapas. Pero una vez que te hayamos entrenado, te ganarás la vida asesinando a todo tipo de escoria.}
{507}{}{¡No tengo tanto dinero! Y dudo que pueda recuperar la inversión, incluso con ese 'entrenamiento' tuyo. Adiós.}
{508}{}{Me parece bien.}
{509}{}{Pon las chapas sobre la mesa y podemos empezar.}
{510}{}{Ahora no, tengo que ir por ellas.}
{511}{}{[Coloca las chapas sobre la mesa, en silencio]}
{512}{}{Hijo de perra, eres durísimo. Serás un cazarrecompensas de primera.}
{1512}{}{Eres una perra durísima. Serás una cazarrecompensas de primera.}
{513}{}{Has adquirido el extra Asesino.}
{514}{}{A pesar de que ya te encuentras en el gremio, todavía tendrás que cubrir los costos. Es caro - son 35.000 chapas.}
{515}{}{Después del último trabajo que hiciste, deberías empezar a entrenar a los reclutas. Pero, por ti, voy a hacer una excepción y cubriré los costos por completo.}
{516}{}{[Sigue las instrucciones de Bruce, en silencio]}
{517}{}{Todavía estás muy verde para pensar en esas cosas, necesitas más experiencia.}
{518}{}{Vale.}
