{100}{}{Ves a un guardia.}
{1100}{}{Ves a una guardia.}
{101}{}{Ves a uno de los mercenarios del gremio. Te observa con atención.}
{1101}{}{Ves a una de las mercenarias del gremio. Te observa con atención.}

{110}{}{Bruce tiene un temperamento tan duro como una piedra.}
{111}{}{Bruce no sólo mantiene el orden, él lo impone.}
{112}{}{Lo intenté muchas veces, pero nunca pude hacer sonreír a Bruce.}
{113}{}{Bruce se pone nervioso cuando los clientes portan armas.}
{114}{}{Te estoy observando.}
{115}{}{Tú. Ponte de cara a la pared y quítate los pantalones... es broma.}
{116}{}{Pon las manos detrás de la cabeza. De cara al suelo... Bromeo.}
{117}{}{Sonríe, estás en el lugar más alegre de Fénix.}
{118}{}{Directo desde el yermo, ¿eh? Eres un niño inocente en una gran ciudad.}
{119}{}{Dios mío, ¿cómo terminaste aquí?}
{120}{}{Habla más alto, ¿por qué hablas tan bajo?}
{121}{}{¿Tienes un cigarrillo?}
{122}{}{¿Primera vez que ves una armadura como esta? Adelante, puedes tocarla.}
{123}{}{¡Arriba las manos! ...Relájate. Sólo bromeo.}

