{100}{}{Ves al Inquisidor.}
{101}{}{Ves a un hombre con una sotana desgastada, contempla la ruinas con recelo, como si buscara a alguien.}
{102}{}{En nombre del Fuego Santo, perecerás.}
{103}{}{Tiembla ante el Fuego Santo, chatarrero.}
{1103}{}{Tiembla ante el Fuego Santo, chatarrero.}
{104}{}{Alabado sea el Fuego Santo.}

#First dialogue
{200}{}{Alto. Por orden del Fuego Santo, explica qué te trae por aquí.}
{201}{}{Lo que hago es asunto mío. Fuera de mi camino, loco.}
{202}{}{¡Blasfemia! ¡Herejía! Arrodíllate ante el Fuego Santo, o serás tragado por su furia.}
{1202}{}{¡Blasfemia! ¡Herejía! Arrodíllate ante el Fuego Santo, o serás tragada por su furia.}
{203}{}{Perro que ladra no muerde.}
{204}{}{Veo que lo dices en serio. Bueno, me voy.}
{205}{}{Sólo estoy buscando chatarra.}
{206}{}{Entonces busca en otro lado. Tu presencia mancha de mugre a la labor del Fuego Santo.}
{1206}{}{Entonces busca en otro lado. Tu obscena presencia de puta mancha de mugre a la labor del Fuego Santo.}
{207}{}{¿Por qué eres tan hostil?}
{208}{}{Lárgate, o mi lanza te hará sentir el castigo del Fuego Santo.}
{209}{}{¿Eso es una lanza? Parece un palito. Hazte a un lado.}
{210}{}{Ya, ya...}
{211}{}{¿Tú otra vez? En el nombre del Fuego Santo, vete de aquí.}
{212}{}{Ya, ya...}

{220}{}{Busco a alguien. ¿Habrás visto a alguna persona por aquí?}
{221}{}{Quizás. ¿Qué relación tienes con ese espía?}
{222}{}{¿Espía? ¿Cómo crees? Nos ganamos la vida vendiendo chatarra. ¿Qué hizo?}
{223}{}{Sigue buscando entre la basura, y no te metas en problemas, pequeña mancha de mugre.}
{1223}{}{Sigue buscando entre la basura, puta, y no te metas en problemas, pequeña mancha de mugre.}
{224}{}{Em, bueno...}
{225}{}{¿Mugre? ¿Qué te pasa? Tuve suficiente de ti, rata de dos patas.}
{226}{}{No creo en tus mentiras. Eres un miserable, arrodíllate ante el Fuego Santo.}
{227}{}{Quita las manos...}
{228}{}{¿Espía? Claro que no, sólo estábamos buscando chapas entre las ruinas.}
{229}{}{¿Espía? Estás equivocado.}
{230}{}{¿En serio? No tengo pruebas, así que debo dejarte ir... por hoy.}
{231}{}{Gracias, supongo.}
{232}{}{No hables con nadie sobre esto. Teme al Fuego Santo, recuerda eso.}
{233}{}{Sí, sí, por supuesto.}
{234}{}{Ups..}

{250}{}{¿Qué te trae por aquí, Iniciado?}
{1250}{}{¿Qué te trae por aquí, Iniciada?}
{251}{}{Me parece que buscamos a la misma persona. No te interpongas entre yo y mi misión, o Aaron te castigará.}
{252}{}{¿Te envía Aaron? Eso cambia las cosas. No te molestaremos.}
{253}{}{Gracias, hermano.}
{254}{}{Sólo estoy buscando reliquias. Hasta luego, hermano.}

{260}{}{¿Eres un Iniciado, no? No recuerdo haberte visto antes. ¿Qué haces aquí?}
{1260}{}{¿Eres una Iniciada, no? No recuerdo haberte visto antes. ¿Qué haces aquí?}
{261}{}{¡Idiota! ¡Haberme confundido por uno de los tuyos fue tu último error!}
{1261}{}{¡Idiota! ¡Haberme confundido por uno de los tuyos fue tu último error!}
{262}{}{Estoy buscando reliquias. Hasta luego, hermano.}
{263}{}{¿Iniciado? No, no sé de qué est-}
{1263}{}{¿Iniciada? No, no sé de qué est-}
{264}{}{¡Es un espía! ¡Atrápenlo, hermanos!}
{1264}{}{¡Es un espía! ¡Atrápenla, hermanos!}
{265}{}{Ay, carajo...}
