# Encounter with Marcos
{100}{}{Ves a Marcos.}
{101}{}{Estás viendo a un hombre con un pasamontañas, sus ojos demuestran que está listo para luchar.}
{102}{}{Ven, acércate. Toda Fénix yace a tus pies.}
{103}{}{Ahora todo cambiará. Se acabó la Inquisición, se acabó la tiranía, se acabaron las guerras con nuestros vecinos. Es todo gracias a ti.}

# Dialogue
{200}{}{Me sorprende verte aquí, hay pocas personas que saben sobre este lugar y las trampas asustan hasta a los más duros. Pero aquí estás, es jodidamente inspirador. ¿Qué te trae al Partido?}
{201}{}{¿Partido? Pues, me topé con este lugar por accidente. ¿Qué estás haciendo aquí? ¿Qué es este lugar?}
{202}{}{¿Encontraste el escondite y esquivaste las trampas con nada más que tu suerte? Lo dudo. Pero como ya estás aquí, te lo diré - estamos luchando contra la Iglesia y su líder, Aaron. ¿Qué piensas de eso?}
{203}{}{Estoy aquí para acabar contigo y a toda tu banda de criminales.}
{204}{}{Agradezco tu honestidad. ¡Atrapen al espía!}
{205}{}{Inténtalo...}
{206}{}{Oye, no me malentiendas...}

{210}{}{Suena como algo a lo que puedo apoyar. Tampoco soporto a los cultistas.}
{211}{}{Entonces, ustedes son criminales. Hay que acabar con ustedes.}
{212}{}{Hmm, hasta ahora, me agradas. Parece ser que tenemos un interés en común. Únete a nosotros y ayúdanos en nuestra lucha. ¿Qué dices?}
{213}{}{Cuenta conmigo.}
{214}{}{Depende de qué necesites.}
{215}{}{Eh, no. ¡No quiero meterme en esto!}
{216}{}{La primera impresión suele ser correcta, que decepcionante.}
{217}{}{No le diré a nadie acerca de ustedes, lo prometo.}
{218}{}{Supongo que eres más perceptivo de lo que pareces, supongo no me dejarás ir sin una pelea.}
{219}{}{Me temo que sería imposible. ¡Maten al espía!}
{220}{}{Oh, mierda...}
{221}{}{Ese fue tu último error...}
{222}{}{Déjame ir y hagamos que esto nunca pasó. ¿Sí?}
{223}{}{Me la pones difícil. Te creeré, pero veremos qué sucede.}
{224}{}{Eh, me voy, o eso creo. Adiós.}
{225}{}{Quiero unirme a tu grupo.}
{226}{}{Muy bien, sin embargo, no podemos arriesgarnos al aceptar a cualquiera. Cuéntame de ti. ¿Quién eres y qué sabes sobre el Partido de la Liberación?}
{227}{}{Estoy buscando a mi familia, fueron esclavizados y los trajeron a esta ciudad. Necesito ayuda para encontrarlos.}
{228}{}{La verdad es que estoy buscando a unos tipos peligrosos que debo eliminar. Y parece que los encontré.}
{1228}{}{La verdad es que estoy buscando a unos tipos peligrosos que debo eliminar. Y parece que los encontré.}
{229}{}{(asiente con la cabeza) Lo entiendo. Cada uno de nosotros ha perdido algo, debe haber una razón por la que nuestros caminos se cruzaron. Sólo unos pocos saben que el culto de los Seguidores son los mayores compradores de esclavos. Nosotros luchamos contra estos bastardos, deberíamos unir nuestras fuerzas.}
{230}{}{Hmm. Ve a echar un vistazo y conoce a los demás. Ahora estoy planeando algo y necesito pensarlo.}
{231}{}{De acuerdo, lo haré.}
{232}{}{Si me ayuda a rescatar a mi gente, estoy dentro.}
{233}{}{¿Cómo puedo ayudar a tu grupo?}
{1233}{}{¿Cómo puedo ayudar a tu grupo?}
{234}{}{Los Rangers me enviaron, ofrecen ayudarte contra Aaron.}
{235}{}{Los Rangers. Esperaba que nos ayudaran, pero pensé que sus refuerzos serían más... impresionantes. De todas formas, cualquier ayuda nos vendrá bien.}
{236}{}{Tu causa es justa.}
{237}{}{Espero tus ordenes.}
{238}{}{Me ha enviado el Prior Matthias de la Catedral, sé acerca de su causa y quiero ayudarlos.}
{239}{}{Matthias no se anda con rodeos. Parece que tenemos menos tiempo del que pensábamos, debemos actuar de forma más decisiva.}

{250}{}{Bienvenido, hermano.}
{1250}{}{Bienvenida, hermana.}
{251}{}{Nos vemos luego.}

{260}{}{Cuéntame sobre tu organización.}
{261}{}{Somos el Partido de la Liberación de Fénix. Nuestra meta es liberar a la ciudad de las garras de Aaron y derribar a su falsa iglesia.}
{262}{}{¿Por qué dices que la Iglesia es falsa?}
{263}{}{Los Seguidores del Fuego han retorcido una religión antigua para justificar los actos inhumanos de su líder. Han olvidado los testamentos de la preguerra.}
{264}{}{¿Por qué es tan importante derrocar a Aaron?}
{265}{}{Sin su líder, la iglesia caerá en frente de los ojos de la ciudad.}
{266}{}{¿Qué es lo que harán después de cumplir su objetivo?}
{267}{}{Vamos a construir una sociedad nueva. Una sociedad basada en la comunidad y la igualdad, y no en la separación y la subordinación.}
{268}{}{Gracias. Ahora sé lo suficiente.}

# Background Conversation
{270}{}{Háblame sobre tu pasado.}
{271}{}{Eso no importa.}
{272}{}{Lo que tú digas.}
{273}{}{Debemos confiar el uno en el otro, ¿no?}
{274}{}{Claro, pero recuerda que no estamos aquí para socializar.}
{275}{}{Eh, bueno, ya entendí.}
{276}{}{Yo nací años antes de que Aaron llegara al poder en la ciudad. La persona que fui en ese entonces ya murió.}
{277}{}{Me suena a que es algo muy personal. ¿Perdiste a alguien querido?}
{278}{}{Eres más inteligente de lo que pareces. Cuando Aaron llegó al poder, erradicó a cualquiera que estuviera opuesto a él. La sangre fluía por todas las calles de la ciudad. Todos perdimos a alguien.}
{279}{}{}
{280}{}{}
{281}{}{¿Por qué la gente toleró a esto y a la Inquisición?}
{282}{}{En ese entonces, Fénix estaba pasando por una hambruna. Deshacerse de las bocas innecesarias y mantener a los débiles a raya servía muchos intereses. La iglesia utilizó sus sermones y orientación para influir en las masas y reforzó el control de Aaron sobre el poder.}
{283}{}{Suena a que fue toda una tragedia para la ciudad. Volvamos al 'presente'.}

# Quests
{300}{}{¿Qué quieres que haga?}
{301}{}{Tengo un trabajo para ti. Uno de nuestros agentes ha desaparecido, Elisa te hablará de los detalles.}
{302}{}{De acuerdo, iré a hablar con ella.}
{303}{}{Necesito equipamiento para la misión.}
{304}{}{Habla con Elisa. Ella está a cargo del almacén, yo tengo cosas más importantes que hacer.}
{305}{}{Entendido.}

{310}{}{Elisa me contó que tuviste éxito en la misión, bien hecho. Con tu ayuda, nos acercamos a nuestra meta.}
{311}{}{Me alegra oír eso.}
{312}{}{Creo que puedo manejar cualquier misión que me des.}
{313}{}{Es una pena que no hayamos podido salvar a nuestro agente. Quizás haya sido lo mejor, teniendo en cuenta lo que los cultistas le podrían haber sacado.}
{314}{}{Dejárselo a los monjes era demasiado arriesgado. Era la única manera.}
{315}{}{Estaba fuera de mi control y pasó lo que pasó.}
{316}{}{El agente que salvaste nos contó lo que ocurrió. Sacarlo de esa trampa fue impresionante.}
{317}{}{Sí, fue una locura. Disparos, explosiones... Deberías haberlo visto. Nuestras vidas colgaban de un hilo.}
{318}{}{No fue nada.}

{320}{}{Ha llegado el momento en el que realmente necesitamos tus habilidades. Vamos a dar nuestro gran golpe, y tu ayuda será fundamental.}
{321}{}{¿Cuál es el plan?}
{322}{}{Gracias al amplificador de la señal, hemos aprendido mucho acerca de los cultistas. Resulta que los rumores de un sótano secreto bajo la Catedral eran reales. Qué hacen los monjes allí, no tenemos idea. Pero parece que están acumulando o fabricando armas pesadas. No podemos dejar que eso ocurra.}
{323}{}{Entonces, ¿dices que entremos y destruyamos las armas? Pero, ¿cómo?}
{324}{}{Es más que eso. Como ya sabes, dentro de la Catedral, el prior Matthias está de nuestro lado. Tu objetivo es contactar a Matthias, ayudarlo a apoderarse de la Catedral y luego destruir las armas. Él te dirá lo que debes hacer.}
{325}{}{De acuerdo, ya entendí.}
{326}{}{Buena suerte. La ciudad ya no puede tolerar el poder desenfrenado de Aaron.}
{327}{}{Debo hablar con Matthias, entrar al laboratorio y destruir las armas. Entendido.}
{328}{}{Es más que destruir las armas. Hay alguien en la Catedral que simpatiza con nosotros. Su nombre es Matthias, no es nuestro agente, pero tiene algo personal en contra de Aaron. Tu objetivo es contactar a Matthias, ayudarlo a apoderarse de la Catedral y luego destruir las armas. Él te dirá lo que debes hacer.}
{329}{}{Nos vemos luego, Marcos.}

{330}{}{Aaron ha sido derrotado.}
{331}{}{¡Eso es maravilloso! Pero no es suficiente. Debemos destruir al culto ENTERO. Mientras los seguidores de Aaron sigan vivos, esta lucha nunca terminará. Es más, no sabemos qué decisiones tomarán los nuevos líderes de la iglesia.}
{332}{}{¿Qué deberíamos hacer?}
{333}{}{Esto no cambia tu misión principal - debes infiltrarte en el sótano secreto debajo de la Catedral y destruirla usando el arma que están guardando. Matthias te ayudará. Buena suerte.}
{334}{}{Eso fue fácil.}