{100}{}{Ves a un Cardenal Rojo.}
{101}{}{Ves a un matón con un corte de pelo elegante y la insignia de su pandilla en la espalda.}

{200}{}{Oye, ¿qué haces aquí? ¿No sabes a quién le pertenece este territorio?}
{201}{}{No lo sé. ¿A quién?}
{202}{}{¿Jamás has escuchado de los Cardenales Rojos? ¿Vives debajo de una roca?}
{1202}{}{¿Jamás has escuchado de los Cardenales Rojos? ¿Vives debajo de una roca?}
{203}{}{No, vivo muy lejos.}
{204}{}{Sí, bueno, piérdete si sabes lo que es bueno. Es tu primer aviso.}
{205}{}{De acuerdo.}
{206}{}{Lo que sea. Voy a entrar.}
{207}{}{Eso es decisión tuya, pero a Orris y los demás no les gustará para nada. ¿Buscas a Orris? Está adentro, pero más te vale que tengas una buena razón.}
{208}{}{Yo me encargaré de eso.}
{209}{}{¿Territorio? Las calles no le pertenecen a nadie.}
{210}{}{¿Qué, tienes retraso? Lárgate.}
{211}{}{Deberías largarte de aquí.}
{1211}{}{Hola, nena... no tengo ganas de una cariñosa. Quizás luego. Por ahora, piérdete.}
{212}{}{Está bien, me voy.}
{213}{}{Hola. ¿Qué tal?}

{214}{}{¿Sabías que alguien le contó tus planes a los Seguidores?}
{215}{}{¿Qué? ¿Tenemos un espía de los cultistas entre nosotros? No puede ser. Ni siquiera se me ocurre quién podría ser.}
{216}{}{Si eres tú, estás muerto.}
{217}{}{No te preocupes, descubriré de quién se trata.}
{218}{}{¡Mierda! ¡Un fenómeno! Lárgate.}
{1218}{}{¡Carajo! ¡Pero que vieja más fea! Es mejor que te vayas de aquí.}


#Quest for letters
{220}{}{Uno de ustedes le robó a un mensajero y se llevó sus cartas.}
{221}{}{¿Y?}
{222}{}{¿Sabes quién fue?}
{223}{}{Sí.}
{224}{}{¿Quién?}
{225}{}{Yo.}
{226}{}{Hm. Eso aclara las cosas. Dame las cartas.}
{227}{}{Ja, ¿me estás amenazando? ¿A MÍ? Dame una buena razón por la que debería escucharte. Unas chapas me vendrían bien.}
{228}{}{Siempre se trata de chapas, ¿cierto?}
{229}{}{¿Cuánto quieres por las cartas?}
{230}{}{Las chapas mueven el mundo, bebé. ¿Sabes a qué me refiero?}
{231}{}{Siempre se trata de chapas, ¿cierto?}
{232}{}{¿Crees que lo hago para divertirme? Todos necesitamos chapas. No hay trabajos para gente como yo en esta ciudad. Si los trabajos de 'verdad' no me quieren, tendré que ganarme la vida así.}
{233}{}{Te daré 30 chapas.}
{234}{}{}
{235}{}{Respecto a las cartas del Sonora Express, ¿todavía las tienes?}
{236}{}{No se irán a ningún lado hasta que reciba lo que merezco.}
{237}{}{Quieres chapas, ¿no es así?}
{238}{}{Necesito más tiempo para conseguir las chapas.}
{239}{}{Parece que necesitas las chapas más que yo.}
{240}{}{Conseguiré las chapas, sólo dame tiempo.}
{241}{}{Pensándolo bien, esto no tiene sentido. Mejor te mato y me llevo las cartas.}
{242}{}{Tú tienes chapas, y yo las cartas. Llévatelas.}
{243}{}{Sí, em, adiós.}
{244}{}{Será mucho más fácil si te mato y me llevo las cartas.}
{245}{}{Esta mierda ya me cansó. Adiós.}
{246}{}{Esas cartas son de interés para mi iglesia. Sugiero que las entregues, no sea que provoques la furia del Fuego Santo.}
{247}{}{Argh. Deberías haberlo dicho desde un principio. No quiero problemas con ustedes, llévate las malditas cartas.}
{248}{}{Que el Fuego Santo tenga piedad contigo, hijo de la Radiación y Desolación.}
{249}{}{Don Diego está... interesado en esas cartas. Será mejor que las entregues.}
{250}{}{(exagerando) Ah, mi más sincero pésame, señor. Debería haberlo dicho desde un principio, quién hubiera sabido que alguien tan importante visitaría nuestra pocilga. (te entrega las cartas) Por favor, salude a Don Diego de mi parte. ¡Adi-ós!}
{1250}{}{(exagerando) Ah, lo lamento, señorita. Debería haberlo dicho desde un principio, quién hubiera sabido que una persona tan importante visitaría nuestra humilde morada. (te entrega las cartas) Por favor, salude a Don Diego de mi parte. ¡Adi-ós!}
{251}{}{No me hables así, Cardenal. En Fénix hay fuerzas más grandes que tu banda.}
{252}{}{Orris me dijo que eras muy terco. ¿Quieres que te echen de la banda? Puedo arreglar eso.}
{253}{}{Carajo, juegas demasiado sucio, incluso para mí. Toma las cartas, ni las quiero.}
{1253}{}{Carajo, juegas demasiado sucio, incluso para mí. Toma las cartas, ni las quiero.}
{254}{}{Bien.}
{255}{}{Yo también puedo amenazarte. ¿Sabes por qué? Le estás hablando al campeón del cuadrilátero.}
{256}{}{Sé que eres uno de los que sobrevivió a esas peleas. Lo respeto. Toma las cartas. ¿Me enseñarás a pelear algún día?}
{1256}{}{Sé que eres una de las que sobrevivió a esas peleas. Lo respeto. Toma las cartas. ¿Me enseñarás a pelear algún día?}
{257}{}{Me lo pensaré. Tengo cosas que hacer.}
