{100}{}{Ves a Angelo.}
{101}{}{Estás viendo al pequeño jefe de un negocio no tan pequeño. Te examina cuidadosamente.}
{102}{}{Hasta que te vea sin la servoarmadura, no te diré una sola palabra.}
{103}{}{¡MUERE!}
{104}{}{¡NOS VEMOS EN EL INFIERNO!}
{105}{}{¡VAS A MORIR!}
{106}{}{¡AR-RGH!}
{107}{}{¡MUERTE A LOS HUMANOS!}

#Before participating in battles
{200}{}{(Ante ti se encuentra un enano de aspecto rudo, por su actitud, está claro que no se presta para bromas) ¿Qué quieres? ¿Vas a apostar en una pelea, o quieres unirte a nosotros?}
{201}{}{Ninguna. Sólo me preguntaba cómo alguien tan... pequeño, podía ser el jefe del cuadrilátero.}
{202}{}{(el guardaespaldas se eriza y empieza a gruñirte) ¡Rico, quieto! Hermano, cálmate, todo está bien. Este salvaje debe venir del yermo y no sabe cómo es la vida en la ciudad, relájate...}
{203}{}{[Más]}
{204}{}{Te daré un consejo - cuidado con lo que dices. (vierte un poco de tequila en un vaso mugriento, igual que un gánster) A esta ciudad le gusta que uses los CEREBROS, no los MUSCULOS. En este lugar, el cerebro soy yo, fui el que estableció este negocio y me llevó la mejor parte de las chapas. O me respetas, o haré que Rico te haga picadillo. ¿Lo comprendes?}
{205}{}{Sí... señor.}
{206}{}{Genial. ¿Qué es lo que quieres?}
{207}{}{Quiero apostar en una pelea.}
{208}{}{Quiero pelear en el cuadrilátero.}
{209}{}{Me haces perder el tiempo. Adiós, Sr. Cerebrito.}

{210}{}{Rico es tu mascota, no es nadie.}
{211}{}{Rico, saca a este imbécil de aquí...}
{212}{}{Si me tocas, estás muerto.}
{213}{}{Ya, ya, no empujes...}
{214}{}{¿Tú otra vez? Empiezas a enojarme.}
{215}{}{¡No puedes sacarme de aquí de esa forma! Te exijo que me des una compensación.}
{216}{}{Perdona, ya entendí, debo mostrarte más respeto.}
{217}{}{Rico, saca a este imbécil a la calle. Si vuelve a entrar, quiébrale el cuello.}
{1217}{}{Rico, saca a este imbécil a la calle. Si vuelve a entrar, quiébrale el cuello.}
{218}{}{¡Eres un puto idiota, Rico!}
{219}{}{Ni te atrevas...}

{220}{}{Quiero apostar.}
{221}{}{No es un buen momento, todavía no hemos agendado las luchas porque no tenemos suficientes luchadores nuevos.}
{222}{}{¿Qué hay de mí? ¿Puedo intentarlo?}
{223}{}{Qué pena. En ese caso, regresaré cuando empiecen las luchas.}
{224}{}{¿Quién es el dueño de este lugar?}
{225}{}{Soy el gerente, me llamo Angelo Rossito. ¿Necesitas algo más?}
{226}{}{¿Tú? ¿El gerente? Bromeas.}
{227}{}{Eso era todo, adiós.}
{228}{}{En ese caso, te tengo una propuesta - quiero participar en el cuadrilátero.}
{229}{}{¿Puedo unirme a las luchas?}
{230}{}{(Te mira de pies a cabeza y le hace una señal a su guardaespaldas) Rico, analiza a este tipo.}
{1230}{}{¿Una mujer en el cuadrilátero? Qué interesante... Podría hacernos publicidad. Rico, quiero que inspecciones su mercancía.}
{231}{}{Oye, oye, ¿qué estás haciendo?}
{232}{}{Con cuidado, grandulón.}
{233}{}{(Rico examina tus reflejos y tus músculos, luego procede a mirar a su jefe y niega con la cabeza)}
{234}{}{¿Y eso qué significa?}
{235}{}{Quiere decir que no tienes lo que buscamos. Ponte más fuerte y ya podremos hablar.}
{236}{}{Luego de esto, no sé si quiera regresar. Adiós.}
{237}{}{De acuerdo, acepto tu desafío.}
{238}{}{(Rico examina tus reflejos y tus músculos, luego procede a mirar a su jefe y asienta con la cabeza)}
{239}{}{¿Y eso qué significa?}
{240}{}{Tienes potencial. Podríamos encontrarte algún contrincante, pero la verdad, tus habilidades no me convencen. Primero, quiero que entrenes, y si todavía quieres luchar, habla conmigo y podemos arreglarlo.}
{241}{}{Entonces haré eso.}
{242}{}{Tienes potencial, pero esto es arriesgado. Piénsatelo un rato y si de verdad quieres luchar, habla conmigo y te podremos encontrar un contrincante.}
{243}{}{Voy a pensármelo.}

{250}{}{Bueno, ¿qué quieres?}
{251}{}{Sólo quería saludarte, ya me voy.}
{252}{}{¿Puedo apostar en alguna pelea?}
{253}{}{Quiero luchar en el cuadrilátero, por favor.}
{254}{}{Llama al gerente.}

{260}{}{¿Cómo estás, campeón? La audiencia te extraña, pero debes darle una oportunidad a los jóvenes.}
{1260}{}{¿Cómo estás, campeona? La audiencia te extraña, pero debes darle una oportunidad a los jóvenes.}
{261}{}{Todo anda bien. Adiós, Angelo.}
{262}{}{Me voy, no quiero oír tus excusas.}
{263}{}{¿Cómo te trata la vida, }
{264}{}{? Tus fanáticos te extrañan, pero debes darle una oportunidad a los jóvenes. Ya sabes cómo son las cosas.}

{270}{}{¿Qué necesitas?}
{271}{}{Nos vemos.}
{272}{}{¿Cómo terminaste siendo el gerente del cuadrilátero?}
{273}{}{Pregúntame lo que quieras, }
{274}{}{.}
{275}{}{Eso era todo. Adiós.}

{280}{}{¿En dónde puedo practicar?}
{281}{}{El salón de entrenamiento está cerca de las escaleras, pero lo difícil será encontrar a un entrenador. Solía haber un hombre llamado Iron Mike, él entrenaba a los luchadores, pero ahora es un borracho y está retirado.}
{282}{}{Me gustaría hablar con él, ¿en dónde está?}
{283}{}{Vive por aquí, en la casa que está cruzando la calle desde la salida. Pero puede que ni te reciba, así que debes ser persistente.}
{284}{}{¿Cómo terminaste siendo el gerente del cuadrilátero?}
{285}{}{Si un luchador experimentado se hizo un entrenador, entonces, ¿cómo te hiciste el gerente?}
{286}{}{Debes utilizar tu cerebro. Yo soy el cerebro y Rico es el músculo. Es simple, ¿no crees?}
{287}{}{Ya veo. Si eres tan inteligente, entonces dime en dónde puedo practicar.}
{288}{}{Para llegar al éxito, hace falta más que sólo usar el cerebro. Es difícil avanzar en esta ciudad.}
{289}{}{Claro...}
{290}{}{¿Qué le pasó a Mike?}
{291}{}{No sé si debería contártelo, pero una vez, unos estudiantes de Mike mataron a su novia durante un robo. Mike dejó de tenerle esperanza a los demás en ese entonces.}


# Participation in battles
{300}{}{(te mira y asienta con la cabeza) Nada mal. Hemos preparado un oponente para ti, ¿piensas en luchar?}
{301}{}{Dame un momento, quiero preguntarte algo.}
{302}{}{Claro. ¿Quién es mi contrincante?}
{303}{}{Todavía no estoy en forma, dame un poco más de tiempo.}
{304}{}{Un vagabundo del yermo, igual de polvoriento y desconocido que tú.}
{305}{}{¿Cuánto dinero ganaré si consigo noquearlo?}
{306}{}{Sólo te importan las chapas, ¿cierto? Apenas empiezas, no esperes ganar tanto, porque primero debes mostrarnos tus habilidades. Es tu primera pelea, así que te ganarás 100 chapas. Es lo mejor que te darán en Fénix a cambio de una pelea normal.}
{307}{}{Tengo una última pregunta - ¿tengo que matarlo?}
{308}{}{Eso depende de tu voluntad y habilidad. Si matas a alguien, eso emociona a los espectadores y te dará más fama. Tú decides.}
{309}{}{Eso está bien y todo, pero tengo más preguntas.}
{310}{}{Ya me he preparado, puedo luchar. ¿A qué hora es la pelea?}
{311}{}{Dame unos minutos, debo prepararme.}
{312}{}{Debes estar aquí a las 20:00. Una última cosa - si vas a luchar a menudo, necesitarás un apodo. Algo memorable, algo poderoso. ¿Qué se te ocurre?}
{313}{}{[Más]}
{314}{}{[Anterior]}
{315}{}{... Nada mal. No te olvides, debes estar aquí a las 20:00, si llegas tarde, tendré que organizar otra pelea. Así que no me decepciones, }
{316}{}{Vale, estaré allí.}
{317}{}{Llegaste demasiado temprano, vuelve a las 20:00.}
{318}{}{Vale.}
{319}{}{Bueno, bueno, miren quién vino. Ya decía yo que no tenías las agallas para subirte al cuadrilátero. Supongo que tienes algo de valentía.}
{320}{}{Más de lo que crees. Llévame al cuadrilátero.}
{321}{}{Espera, tengo que ir al baño. Vuelvo en un segundo.}
{322}{}{Lo sé, sólo quería hablar contigo antes de empezar.}
{323}{}{Has llegado justo a tiempo. Los fanáticos los están esperando a los dos.}
{324}{}{Estoy listo para partirle la madre a alguien. ¡Llévame al cuadrilátero!}
{1324}{}{Estoy lista para partirle la madre a alguien. ¡Llévame al cuadrilátero!}
{325}{}{Dame un poco más de tiempo, debo prepararme.}
{326}{}{Big Mario te espera, pero no sólo él - si consigues derrotarlo, también ganarás mucha gloria. Y bien, }
{327}{}{. Esta será tu pelea más importante, ¿puedes hacerlo?}
{328}{}{Hoy, voy a derribar a Big Mario Albright. Vamos, Angelo, camina conmigo, porque el cuadrilátero verá a su nuevo campeón.}
{1328}{}{Hoy, voy a derribar a Big Mario Albright. Vamos, Angelo, camina conmigo, porque el cuadrilátero verá a su nueva campeona.}
{329}{}{Mario tendrá que esperarme, ya vengo.}

# First fight
{330}{}{Bastante bien... para un novato. Además, recibiste unos cuantos golpes. De todas formas, el potencial está ahí, así que no te detengas.}
{1330}{}{Bastante bien... para una chica. Además, recibiste unos cuantos golpes. De todas formas, el potencial está ahí, así que no te detengas.}
{331}{}{Bastante bien, para ser un novato. Tienes potencial, debes desarrollarlo.}
{1331}{}{Bastante bien, para ser una chica. Tienes potencial, debes desarrollarlo.}
{332}{}{¿De verdad? Eso me motiva mucho.}
{333}{}{No estoy aquí para lucirme, yo quiero chapas.}
{334}{}{Te daré 100 chapas, es lo que te corresponde. Fue una pelea limpia. Si quieres volver a luchar, ven cuándo quieras y podemos hablarlo.}
{335}{}{Puedes agendar otra pelea cuando quieras, estaré allí.}
{336}{}{Angelo, estuve a punto de morir, no quiero hacer esto de nuevo. Adiós.}
{337}{}{No habrá una siguiente vez.}
{338}{}{.}

# Second fight
{340}{}{Estás progresando, }
{341}{}{. Muy bien. Espero que no vayas a detenerte aquí.}
{342}{}{Muy bien hecho, le empiezas a gustar al público, pero también a una persona más importante. ¡A mí!}
{343}{}{¿Puedo cobrar?}
{344}{}{Conmigo, el trato siempre será justo. Ten las 200 chapas que te corresponde, no te las gastes en un solo lugar. Y, prepárate para tu siguiente lucha.}
{345}{}{¿Quién es mi contrincante?}
{346}{}{Déjame pensar... Necesitas un desafío más grande... ¿Quizás Canelo? Ha ganado diez veces seguidas, así que es un oponente digno. Al público le encantan las peleas así.}
{347}{}{Genial. Me enfrentaré a Canelo, lo haré pedazos.}
{348}{}{Voy a considerarlo. Adiós, Angelo.}

# Third fight
{350}{}{Esa pelea fue asombrosa, }
{351}{}{. No había visto luchas tan emocionantes en años. Ya casi podría agendarte la pelea del campeonato, CASI.}
{352}{}{¿Podrías agendarme otra pelea?}
{353}{}{Claro, si tienes las agallas. Tu paga, son 400 chapas.}
{354}{}{Así que mi siguiente pelea es contra un verdadero profesional, ¿no?}
{355}{}{No es cualquier profesional, ¡es el invicto Big Mario Albright! Se muere por luchar contra ti, así que prepárate - nadie ha podido noquearlo.}
{356}{}{Puedo sentir a una bestia en mi interior. No me echaré para atrás, de ninguna forma.}
{357}{}{No sé si tenga el espíritu para seguir luchando. Adiós, Angelo.}
{358}{}{¿Cómo que casi? Muéstrame la cara de mi oponente y se la aplastaré, quiero ser el mejor.}
{1358}{}{¿Cómo que casi? Muéstrame la cara de mi oponente y se la aplastaré, quiero ser la mejor.}

# - last Stand
{360}{}{¡Esa fue una pelea inolvidable, }
{361}{}{! Los espectadores estaban locos; hace años que no veíamos tanta emoción. Nos ganamos un montón de apuestas porque todos pensaban que Big Mario se mantendría invicto. ¡Pero les demostraste que estaban equivocados! Bien hecho, ten, tus 800 chapas. Aunque... tenemos un problema.}
{362}{}{¿Qué pasó?}
{363}{}{Bueno, pues, tienes el título de campeón. Eres invencible, ¿lo entiendes? Ya no nos queda nadie que pueda luchar contra ti. Y si la gente sigue apostando por ti mientras sigues ganando, no tendremos ninguna ganancia. La mayoría de nuestros ingresos vienen de las apuestas, ¿lo comprendes?}
{1363}{}{Bueno, pues, tienes el título de campeona. Eres invencible, ¿lo entiendes? Ya no nos queda nadie que pueda luchar contra ti. Y si la gente sigue apostando por ti mientras sigues ganando, no tendremos ninguna ganancia. La mayoría de nuestros ingresos vienen de las apuestas, ¿lo comprendes?}
{364}{}{Así que, ¿mi carrera se acabó?}
{365}{}{¡Pero qué demonios! ¿O sea que me estás echando del cuadrilátero?}
{366}{}{Exacto. Perdón, amigo mío, pero todo luchador tiene su época de oro. Fue un placer hacer negocios contigo, pero es momento de que sigamos con nuestras vidas.}
{1366}{}{Exacto. Perdón, amiga mía, pero toda luchadora tiene su época de oro. Fue un placer hacer negocios contigo, pero es momento de que sigamos con nuestras vidas.}
{367}{}{Demonios, Angelo, tú sólo piensas en las chapas. Supongo que ya no tengo nada que hacer aquí.}
{368}{}{¡Vete a la mierda!}

{370}{}{Cuéntame sobre mi oponente.}
{371}{}{Dime algo acerca de mi nuevo oponente.}
{372}{}{Quiero saber de mi siguiente oponente.}
{373}{}{Háblame sobre mi oponente.}
{374}{}{Es un vagabundo del yermo, se le ve bastante en el cuadrilátero, no es nada especial.}
{375}{}{Solía ser un saqueador en el yermo, se hace llamar Savage. Después de que eliminaron a su pandilla, llegó a Fénix para luchar y así ganarse algunas chapas. Es lo único que sabe hacer, le encanta pelear, pero ya no está en buena forma. No me sorprende, ha vivido como un perro callejero su vida entera.}
{376}{}{Te verás contra uno de los mejores luchadores del cuadrilátero, se llama Canelo. Son los contrincantes perfectos. Ha estado entrenando, así que cuidado - es más fuerte y veloz que cualquier persona con la que te hayas cruzado hasta el momento.}
{377}{}{Ahora, tendrás que enfrentarte contra un verdadero monstruo, le dicen Big Mario. Ha ganado tantas veces que ya perdí la cuenta y nadie quiere luchar contra él... excepto tú. Te aseguro que será brutal, pero piensa en las chapas que vamos a ganar.}
{1377}{}{Ahora, tendrás que enfrentarte contra un verdadero monstruo, le dicen Big Mario. Ha ganado tantas veces que ya perdí la cuenta y nadie quiere luchar contra él... excepto tú. Te aseguro que será brutal, pero piensa en las chapas que vamos a ganar.}
{378}{}{De acuerdo. Debo prepararme para esta lucha.}

{380}{}{¿Qué tal te trata la vida, }
{381}{}{? Nuestra audiencia te extraña, pero, ¿sabes qué? Tengo un nuevo contrincante para ti. Es como si estuvieran hechos el uno para el otro. ¿Te interesa?}
{382}{}{No. Ya no quiero luchar más.}
{1382}{}{No. Ya no quiero luchar más.}
{383}{}{Me apena saber eso, pero si cambias de parecer, dímelo.}
{384}{}{De acuerdo.}
{385}{}{Claro, ¿por qué no? Háblame sobre él.}
{386}{}{¡Tráelo aquí de inmediato!}
{387}{}{¡Cuánto entusiasmo! No te arrepentirás.}
{388}{}{Bueno, cuéntame sobre él.}
{389}{}{Adivina qué, llegó un hijo de puta enorme, es un bruto, de piel verde. Es un maldito mutante. Tiene los brazos como las vigas de los puentes. Nadie ha conseguido derribarlo, nadie. Pero, tú... Puede que tú lo consigas.}
{390}{}{Entonces dile que venga, volveré a las 20:00, como siempre.}
{391}{}{Oh, claro que no, ya me he encontrado con esos tipos. Paso.}
{392}{}{El Hijo de Puta Grande y Verde te está esperando en el cuadrilátero, }
{393}{}{.}
{394}{}{Está a punto de morir. Ahí voy.}
{395}{}{¿¡Esa cosa es mi oponente!? Necesito ir a... tomar agua, ya vuelvo.}
{396}{}{¡Nunca jamás ha habido un espectáculo de este calibre en Fénix! Tal pelea será recordada en las décadas por venir y se escribirán leyendas al respecto. Bien, ¿cómo te sientes? Parece que te dio una buena golpiza. Te daré 1.500 chapas, te harán falta para que el doctor te revise.}
{397}{}{Hoy sí que estás elocuente, Angelo. Gracias por las chapas.}
{398}{}{Casi me matan y estás igual de emocionado que un niño. He tenido suficiente, me largo.}
