{100}{}{Ves a Iron Mike.}
{101}{}{Estás viendo a un luchador que fue formidable en el pasado, las batallas y los años lo han hecho más débil.}
{102}{}{¿Qué quieres? No hablo con cobardes que se esconden detrás de servoarmaduras.}
{103}{}{Alguien mató a Angelo, juro que encontraré a ese bastardo y le torceré el cuello.}
{104}{}{Otro drogadicto más... La salida está por allá. Te dije, QUE LA SALIDA ESTA POR ALLA.}
{105}{}{No quiero saber nada de los Cardenales, así que vete.}

#First Dialogue 1
{200}{}{(Entras a una habitación oscura y húmeda, la cual inmediatamente ataca tus sentidos con el olor a alcohol y a podrido. Te percatas de una silueta sentada sobre una silla andrajosa, hace un movimiento repentino y te grita, "¡Oye, fuera de aquí!" antes de lanzarte una botella.)}
{201}{}{¿¡Qué mierda te pasa, hijo de perra!?}
{202}{}{Perdona, no quería molestarte...}
{1202}{}{Perdona, no quería molestarte...}
{203}{}{(Estás viendo a un hombre fuerte y calvo, sus brazos y cabeza están cubiertos de tatuajes cuya tinta se ha desvanecido. Te observa desde su silla.) No quiero ver a nadie. ¡Fuera de aquí!}
{204}{}{Bueno, lo que tú digas...}
{205}{}{No creas que me olvidaré de esto.}
{206}{}{Sal de aquí, no quiero ver a nadie.}
{207}{}{¿Podemos hablar?}
{208}{}{¿Acaso no me escuchaste la primera vez? ¡Sal de aquí!}
{209}{}{Pero, yo...}

#First Dialogue 2
{210}{}{Perdona si te grité, a veces no puedo controlarme, en especial después de la segunda botella de tequila.}
{211}{}{Lo entiendo.}
{212}{}{Puede que te lance una botella de vuelta si vuelve a ocurrir.}
{213}{}{Me llamo Mike, algunos me dicen Iron Mike, porque nadie nunca me ganó dentro del cuadrilátero. Pero, ¿sabes qué? ¡Qué se pudran! Ya tuve suficiente de esas peleas, la gente lucha por las chapas, pero yo luchaba por ser el mejor. No es lo mismo.}
{214}{}{¿Entonces qué haces, si ya no peleas?}
{215}{}{(bebe lo poco que queda en la botella y suspira.) ¡Beber! Y recordar. Es obvio que podría ganarme unas chapas al entrenar a otros, pero no quiero. Esta ciudad está podrida... ¿Me estás escuchando?}
{216}{}{Sí, eh, está podrida. ¿A qué te refieres?}
{217}{}{Oye, no te lo tomes todo, déjame un poco.}
{218}{}{Solía entrenar a los luchadores jóvenes para las peleas callejeras, pero siempre se unían a alguna pandilla o a trabajar para algún criminal. Así que ya no entreno a nadie. Yo me quedo bebiendo y todos salimos ganando.}
{219}{}{Eso suena muy aburrido.}
{220}{}{Eres un completo perdedor.}
{221}{}{Todos estos revolucionarios, cultistas, gánsteres, los del mercado negro - sólo les importa su propio bien, el de nadie más. Nadie se preocupa por ti, ni por la ciudad. Bueno, ¿qué te trae por aquí?}
{222}{}{Sólo estoy intentando conocer gente, no soy de esta ciudad.}
{223}{}{(se rasca la barbilla mientras te mira con indiferencia) Escogiste un lugar horrendo para hacer eso, niño. Pero, puede que si peleas bien en el cuadrilátero, los demás lleguen a percatarse de ti.}
{224}{}{¿De verdad? Buena idea, estaba pensando en intentarlo.}
{225}{}{Bueno, estoy buscando a mi familia, los esclavistas los secuestraron.}
{226}{}{Perdona, pero no me meto en ese tipo de cosas. Pero, he oído que los Seguidores del Fuego están conectados a los esclavistas. Ten cuidado, porque es peligroso.}
{227}{}{Gracias, Mike. Supongo que es el momento de hablar con los Seguidores del Fuego.}
{228}{}{Quiero aprender a luchar.}
{229}{}{Ya te lo dije, tuve suficiente de entrenar a otros.}
{230}{}{Eso es una pena.}

{240}{}{Cuéntame sobre el cuadrilátero.}
{241}{}{Su dueño es Angelo Rossito, es un tipo decente y sabe cómo dirigir un negocio. Pero a veces, quieres meterle la cabeza en un inodoro.}
{242}{}{Háblame de tus victorias en el cuadrilátero.}
{243}{}{Yo gané todas mis peleas, las calles me enseñaron cómo luchar y entrenaba sin parar, lo que perfeccionó mis habilidades. Incluso aprendí algunas técnicas de los libros viejos y de algunas películas.}
{244}{}{¿Películas?}
{245}{}{Sí, algunos chatarreros encontraron un proyector en buen estado y unas películas viejas. En ese entonces, era nuestro único entretenimiento. Pero el cine no duró mucho, porque unos saqueadores mataron al dueño y el proyector desapareció.}

{250}{}{Ah, otra víctima del cuadrilátero. (te mira de pies a cabeza, teniendo en cuenta toda su experiencia) Yo no te habría permitido subirte al cuadrilátero, eso es obvio, pero no es que Angelo tenga otra opción. Disfruta de tu victoria. Y - lárgate, fuera de mi habitación.}
{251}{}{Hmph. Me voy de aquí.}
{252}{}{Sólo estás celoso. Quédate en tu silla, eres un borracho.}
{253}{}{Ah, ahí estás, el nuevo campeón. Parece que nuestro entrenamiento valió la pena. Usa tus habilidades para hacer el bien.}
{1253}{}{Ah, ahí estás, el nuevo campeón. Parece que nuestro entrenamiento valió la pena. Usa tus habilidades para hacer el bien.}
{254}{}{No te preocupes, Mike. Ahí nos vemos.}
{255}{}{Ah, eres el nuevo campeón. (Te observa, evaluándote) No sé por qué te molestas en pelear, pero al menos parece que eres un tipo decente. (hace un brindis) Salud.}
{1255}{}{Ah, eres la campeona. (Te observa, evaluándote) No sé por qué te molestas en pelear, pero al menos parece que eres una tipa decente. (hace un brindis) Salud.}
{256}{}{Hasta luego.}

{260}{}{Angelo me contó sobre tu tragedia. ¿Podrías contármelo?}
{261}{}{Mike, yo no soy así. No heriría a nadie, a no ser que lo merezcan.}
{1261}{}{Mike, yo no soy así. No heriría a nadie, a no ser que lo merezcan.}
{262}{}{La tentación es de los profesores más duros que hay. No lo entiendes hasta que te encuentras entre la espada y la pared. Aprendí eso por las malas.}
{263}{}{¿Pasó algo?}
{264}{}{Lo dices como si te hubiera pasado algo terrible. ¿De qué se trata?}
{265}{}{Puedo pagarte, Mike. ¿Cuánto cobras por una lección?}
{266}{}{Chapas. Obvio. Ahora, todos se arrodillan ante esas malditas cosas. Pero, ya no voy a vender el derecho a ejercer la violencia, si me entiendes.}
{267}{}{¿De verdad quieres saberlo? (suspiro) Vale, escúchame. Antes, solía entrenar a cualquiera que pudiera pagarme. No me importaba qué pensaban hacer con sus vidas. Algunos se unieron a pandillas, otros se dedicaron a robar. Yo lo ignoraba... hasta que un día...}
{268}{}{Sigue.}
{269}{}{Típico. Jamás piensas acerca de las consecuencias de tus acciones.}
{270}{}{Era de noche, y estaba llevando a mi novia a su casa, su nombre era Sabrina. Nos asaltaron unos pandilleros, pude ahuyentarlos, pero no pude salvar a mi novia. La... la mataron. En medio de la pelea, me di cuenta de que había sido el maestro de algunos de los asaltantes.}
{271}{}{¿Qué pasó con ellos?}
{272}{}{Ojalá que los hayas dejado desangrándose en el piso.}
{273}{}{Después de esa noche, todos se escondieron, entraron en algunas pandillas para protegerse. No podía alcanzarlos. Pero, los gánsteres no viven mucho, sólo queda uno de ellos, pero trabaja como guardia en el casino. Si le toco un pelo, Don Diego y sus matones vendrán por mí. Así que ahogo mis penas en la bebida, lo mismo que me sirve el casino.}
{274}{}{Eso es horrible. Ya entiendo el por qué no me entrenarás. Adiós, Mike.}
{275}{}{Puedo vengarte, Mike. Haré justicia.}
{276}{}{¿Crees que eso me dará consuelo? No. Sólo quiero estar cara a cara con él, y mirarlo a los ojos.}
{277}{}{Entonces, ¿se volvieron unos pandilleros cualquiera?}
{278}{}{¿En qué estabas pensando al enseñarle a esos idiotas?}
{279}{}{Esto se trata de lo que pasó con Sabrina, ¿no?}
{280}{}{Cuéntame sobre ese ataque.}
{281}{}{No quiero hablar de ello, sólo quedó vivo un atacante, trabaja en el casino.}
{282}{}{Vale, olvídalo.}
{283}{}{Creo que deberías saberlo, pero tuvo un 'accidente' ¿Qué piensas?}
{284}{}{En parte, aunque no sé que hubiera hecho en tu lugar...}
{285}{}{Los gánsteres no suelen vivir mucho, no quiero ser uno de ellos. Lo único que puedo hacer es ahogar mis penas en el alcohol. Me quedo aquí a beber, no le hago daño a nadie y todos están felices.}
{286}{}{Eso es muy triste, Mike. Ya entiendo el por qué no me entrenarás.}
{287}{}{Vuelve cuando seas un santo que irradie paz y amabilidad. Puede que en ese entonces, te enseñe todo lo que sé.}
{1287}{}{Vuelve cuando seas un ángel que irradie paz y amabilidad. Puede que en ese entonces, te enseñe todo lo que sé.}
{288}{}{Vale. Te demostraré que puedes confiar en mí.}
{289}{}{Dudo que pueda hacerle bien a esta ciudad. Adiós, Mike.}
{290}{}{¿Sigues estando en contra de entrenarme?}
{291}{}{He oído sobre el bien que le has hecho a los barrios bajos. ¿Por qué? ¿Por qué te importan estas pobres almas?}
{292}{}{No puedo soportar la injusticia.}
{293}{}{He oído que has hecho buenas cosas por esta ciudad, por podrida que esté. ¿Por qué? ¿Qué es lo que ganas?}
{294}{}{Dicen que eres un héroe, incluso afuera de esta ciudad. Se dice que ayudas a la gente del yermo. ¿Por qué? ¿Qué te impulsa a hacerlo?}
{1294}{}{TDicen que eres un héroe, incluso afuera de esta ciudad. Se dice que ayudas a la gente del yermo. ¿Por qué? ¿Qué te impulsa a hacerlo?}
{295}{}{Sabes, me agradas. No sé el por qué, pero tu presencia me sube los ánimos. No quiero que acabes como Sabrina, o peor.}
{296}{}{¿Puedes entrenarme?}

#Workout
{300}{}{Pasa, pero si no te gusta alguna cosa, te lanzo a la calle.}
{301}{}{Pasa, amigo. ¿Trajiste más cerveza?}
{1301}{}{Pasa, niña. ¿Trajiste más cerveza?}
{302}{}{Pasa, siéntate.}
{303}{}{No tengo nada más que enseñarte. Debes entrenar por tu cuenta. Yo creo en ti.}
{309}{}{Hasta luego, Mike.}

{310}{}{Entrenador, enséñame a luchar.}
{311}{}{¿Enseñarle a una mujer? Jamás he hecho eso, pero dicen que las mujeres lucharon durante la Gran Guerra, o al menos eso dicen los pósteres de esos tiempos.}
{312}{}{Exacto.}
{313}{}{Ya te lo he dicho, no voy a entrenar a nadie.}
{314}{}{Pero, ¿por qué?}
{315}{}{Puede que lo uses para asaltar a la gente en la calle, o te vuelvas otro criminal más. Muchos hicieron eso. No quiero cometer el mismo error otra vez.}
{316}{}{No voy a discutir contigo. Adiós, Mike.}
{317}{}{Te pagaré.}
{318}{}{Chapas. Claro. En estos tiempos, las chapas lo resuelven todo. Pero primero, quiero que me digas, ¿para qué quieres utilizar estas habilidades? ¿Quieres ganar dinero en el cuadrilátero? ¿Es por defensa personal? Quiero que me prometas... No, quiero que me JURES que usarás lo que te enseñaré para el bien de la gente común.}
{319}{}{No puedo jurarte eso.}
{320}{}{En ese caso, ya no tenemos nada de qué hablar. Fuera de aquí.}
{321}{}{Vale.}
{322}{}{Mike, te juro que no te decepcionaré.}
{323}{}{Chapas. Claro. Pero no voy a perder el tiempo con alguien como tú. Piérdete..}
{324}{}{Vale.}
{325}{}{Hmm... No lo sé... Déjame pensarlo. Y trae más cerveza.}
{326}{}{De acuerdo.}
{327}{}{¿Y bien? ¿Ya te decidiste? ¿Me entrenarás?}
{328}{}{Quizás haya estado equivocado todos estos años... Está bien. Cada sesión te costará 500 chapas, así que ahorra y vuelves luego.}
{329}{}{Nos vemos luego, Mike.}
{330}{}{Quizás haya estado equivocado todos estos años... Está bien. Empezaremos mañana en la mañana, prepárate.}
{331}{}{Nos vemos mañana, Mike.}

{332}{}{(con desdén) Sabía que no podía confiar en ti, me juraste que usarías tus habilidades para el bien, pero ahora no creo ni una sola palabra de lo que dices. Piérdete.}
{1332}{}{(con desdén) Sabía que no podía confiar en ti, me juraste que usarías tus habilidades para el bien, pero ahora no creo ni una sola palabra de lo que dices. Piérdete.}
{333}{}{Eh...}
{334}{}{Fuera de mi vista, eres una desgracia.}
{335}{}{Bueno, olvídalo.}

{340}{}{Estoy aquí para aprender el arte del combate cuerpo a cuerpo.}
{341}{}{No tenías que decirlo tan dramáticamente, pero bueno. ¿Tienes 500 chapas?}
{1341}{}{No tenías que decirlo tan dramáticamente, pero bueno. ¿Tienes 500 chapas?}
{342}{}{No, no lo había pensado, perdona.}
{1342}{}{No, no lo había pensado, perdona.}
{343}{}{Puede que te enseñe sin cobrarte nada, pero cuando pagas, lo valoras más.}
{344}{}{Sí, por supuesto.}
{345}{}{Claro, aquí tienes las chapas. ¿Qué aprenderemos hoy?}
{346}{}{Suena bien, guárdate las chapas. Vamos a entrenar hoy, yo invito. Es sólo porque me agradas.}
{347}{}{Genial. ¿Qué aprenderemos hoy?}
{348}{}{He oído rumores acerca de ti, de que has matado a niños. No sé si sea verdad, pero confío en la persona que me lo dijo. Ya no eres mi estudiante. Sal de aquí.}
{1348}{}{He oído rumores acerca de ti, de que has matado a niños. No sé si sea verdad, pero confío en la persona que me lo dijo. Ya no eres mi estudiante. Sal de aquí.}
{349}{}{...}

{350}{}{Vamos a empezar con lo básico, tu postura, la respiración y el enfoque.}
{351}{}{Es hora de la acción. Vamos a practicar los golpes básicos y los agarres.}
{352}{}{Estás aprendiendo, chico. De ahora en adelante, vamos a esforzarnos más. Nos enfocaremos en la resistencia y a luchar contra oponentes armados.}
{1352}{}{Estás aprendiendo, niña. De ahora en adelante, vamos a esforzarnos más. Nos enfocaremos en la resistencia y a luchar contra oponentes armados.}
{353}{}{Has aprendido mucho. La lección más importante es cuidarte, debes mantener el balance y el control en medio de situaciones críticas, algún día, eso te salvará la vida.}
{354}{}{[Empieza a entrenar]}
{355}{}{Ya tuvimos mucho por hoy. Vuelve en un día, más o menos.}
{356}{}{De acuerdo, entrenador.}
