{100}{}{Ves una computadora.}
{101}{}{Ves una computadora viejísima, apenas funciona, pero sigue conectada a la red pública.}

Dialogue
{200}{}{Introducir comando.}
{201}{}{Cerrar sesión.}
{202}{}{Regresar.}

{210}{}{Activa los sistemas de emergencia y cierra el cuarto de control.}
{211}{}{¡Cuidado! Asegúrese de que todo el personal esté fuera del cuarto de control.}
{212}{}{Deshabilitar los sistemas de emergencia.}
{213}{}{Se ha iniciado el apagado del sistema.}

{220}{}{Registro de conservación de la estación.}
{221}{}{23 de Octubre, año 2077: Se ha declarado un estado de emergencia. Se han activado los protocolos de protección automáticos. Se ha apagado el reactor.}
{222}{}{[Más]}
{223}{}{16 de Agosto, año 2163: Se ha cancelado el estado de emergencia. Se han desactivado los protocolos de protección automáticos. Se ha iniciado el reactor.}
{224}{}{Hmm. Los necrófagos sabían lo que estaban haciendo.}

{230}{}{Tratado con la Iglesia del Fuego Santo}
{231}{}{Se firma un acuerdo para el suministro de células de fusión a la Central Nuclear Theodore Roosevelt, Fénix, Arizona. Firmado el 17 de Agosto del año 2163.}
{232}{}{Información general sobre la estación.}
{233}{}{.....}
{234}{}{Contrato de partes desde... ¿Ciudad Garaje?}
{235}{}{(Resulta que los Seguidores del Fuego trajeron la parte que le entregaste a los chatarreros en Ciudad Garaje. La trajeron para reemplazar la parte vieja, que estaba dañada.)}
{236}{}{Ah, ya me acuerdo.}
