{100}{}{Ves a un cirujano.}
{101}{}{Ves a un cirujano con una bata manchada de sangre.}
{102}{}{Si no me apuro, ningún tipo de medicina me ayudará con esto...}

# Primer diálogo
{200}{}{¿Cuál es tu problema?}
{201}{}{¿Siempre tienes una actitud tan arrogante hacia los pacientes?}
{202}{}{(se quita los guantes y se frota las manos) Mira, soy un solo tipo, y tengo muchos pacientes que atender. ¿Te crees especial, acaso?}
{1202}{}{(se quita los guantes y se frota las manos) Mira, soy un solo tipo, y tengo muchos pacientes que atender. ¿Te crees especial, acaso?}
{203}{}{No lo sé... ¿Qué me haría especial?}
{1203}{}{No lo sé... ¿Qué me haría especial?}
{204}{}{Que seas parte de los Seguidores... o que tengas muchas chapas. Bueno, ¿necesitas algo?}
{205}{}{Supongo.}
{206}{}{No, no es nada, solo tenía curiosidad.}

# Diálogo repetido
{210}{}{¿Cuál es tu problema?}
{211}{}{Ninguno.}

# Curación
{220}{}{Necesito curación.}
{221}{}{Bueno, veamos. ¿Qué quieres que revise?}
{222}{}{[Cura heridas por }
{223}{}{[Cura miembros rotos }
{224}{}{[Cura toda la radiación por }
{225}{}{[Cura todo el envenenamiento por }
{226}{}{Olvídalo, sanará por sí mismo.}
{227}{}{Es un caso típico. Me encargaré de ello. Pero como no eres un Seguidor, tendrás que hacer una donación.}
{228}{}{ chapas]}
{229}{}{Oh.}
{230}{}{Es un caso típico. Te cuidaremos.}
{231}{}{El tratamiento no es gratis. ¡Anda!}
{232}{}{Tendré que ir por algunas chapas...}
{233}{}{}
{234}{}{Alabado sea el Fuego Santo. Ahora, vete, tengo otras cosas que hacer.}
{235}{}{Necesito algo más, doctor.}
{236}{}{Adelante, doctor.}
{237}{}{Con mucho gusto.}

{240}{}{¿Has visto algún campesino de la Villa?}
{241}{}{Hmm, uno de los esclavos mencionó a la Villa durante su examen.}
{242}{}{¿Qué le pasó?}
{243}{}{Ni idea. Mi único trabajo es examinarlos físicamente.}
{244}{}{Ya veo.}
