{102}{}{Es imposible robar desapercibido en tales condiciones.}
{103}{}{No... puedes... detenernos...}
{104}{}{}
{105}{}{¡Lárgate!}

# Primer diálogo
{200}{}{Impresionante. Entraste en el refugio sin activar la alarma, evadiste a los guardias y llegaste al centro de mando. Tales habilidades de espionaje son extremadamente raras de encontrar. ¿Por qué estás aquí?}
{201}{}{Impresionante. Activaste la alarma y aún así llegaste al centro de mando. No hay muchas personas que sean capaces de eso. ¿Qué es lo que quieres?}
{202}{}{Siempre es sospechoso ver un forastero en el refugio. ¿Por qué estás aquí?}
{203}{}{Aaron me envía, estoy aquí para servir al Fuego Sagrado.}
{204}{}{Estoy aquí por un sólo propósito: matarte.}
{205}{}{Entonces no perdamos el tiempo...}
{206}{}{¡Muere! ¡Por la libertad de la Villa!}
{207}{}{No responderé hasta que sepa con quién estoy hablando.}
{208}{}{Parece ser que no entiendes tu situación. Mi nombre es Ulysses Grant, primer Asesor de Aaron, Señor de Fénix. Eso debería ser suficiente.}
{209}{}{Eres justo a quién estaba buscando... tengo que matarte.}

# Primer diálogo si el jugador es un campesino
{210}{}{Busco a mi gente de la Villa. Dicen que los Seguidores del Fuego Sagrado los esclavizaron.}
{211}{}{La Villa... Lo recuerdo. Uno de esos pueblos primitivos del noroeste. Los esclavos que capturamos allí fueron enviados a Two-Sun, y ahora se convertirán en combustible para la máquina del progreso. Es un honor recibir este destino, incluso si no lo ves así.}
{212}{}{¿Por qué necesitas esclavos?}
{213}{}{Hay muchas razones: restaurar la infraestructura, mano de obra para la mina, mover carga entre asentamientos y muchas otras cosas que serían mucho más difíciles de hacer con trabajadores independientes. El progreso de la civilización exige una mano de obra numerosa, y la esclavitud es la forma más eficaz de conseguirla.}
{214}{}{¿No crees que está mal esclavizar a personas inocentes?}
{215}{}{La mayoría de la población local se limita a sobrevivir, sin aportar nada al desarrollo regional. Discuten y se niegan a cooperar. El egoísmo de mente estrecha es en lo que se basan tribus como tu Villa. Utilizar su mano de obra para un bien mayor justifica el sacrificio ético.}
{216}{}{¿De qué tipo de progreso estás hablando?}
{217}{}{Has recorrido un largo camino, ¿verdad? Ya lo has visto: todo es yermos y ruinas. Pero algunos lugares ven el regreso de la civilización: electricidad, medicina, educación. El renacimiento de Sonora es obra nuestra. Comparadas con eso, las preocupaciones de la Villa son triviales.}
{218}{}{¿Qué sigue? ¿Vas a esclavizar a toda Sonora?}
{219}{}{Eso sería ineficaz. Sería mejor crear cómodos centros de civilización. Estas colonias servirán de modelo para que otros las sigan.}
{220}{}{Villa no necesitaba tu "civilización". Teníamos comida y orden.}
{221}{}{Estás equivocado. Tu comunidad está en las últimas: agotamiento de la diversidad genética, mutaciones, alta mortalidad, amenazas externas, y las mentes cerradas de siempre. Hemos visto comunidades desmoronarse por una bomba de agua rota.}
{222}{}{¿Y qué ofrece tu secta?}
{223}{}{Un regreso a la civilización, naturalmente. Hemos logrado mucho. Y aún tenemos mucho que lograr.}
{224}{}{Tonterías. Ustedes sólo son parásitos.}
{225}{}{Tienes razón. Sonora carece de una mano fuerte que una a su población.}
{226}{}{Es una pena que no hayas podido ver la grandeza de nuestras ideas. Como tantos otros, no eres más que un obstáculo. Un obstáculo que está a punto de ser removido...}
{227}{}{Espera, no hemos terminado...}
{228}{}{Para eso, debes abandonar tus previas supersticiones, tradiciones e incluso lazos familiares. ¿Estás preparado para semejante sacrificio?}
{1228}{}{Para eso, debes abandonar tus previas supersticiones, tradiciones e incluso lazos familiares. ¿Estás preparada para semejante sacrificio?}
{229}{}{Por supuesto. Quiero que la Villa se una al camino del progreso y la civilización.}
{230}{}{Eso es imposible. ¡Vete al infierno!}
{231}{}{En ese caso, demuestra tus intenciones: únete al culto del Fuego Sagrado. Serás un ejemplo a seguir para tu gente.}
{232}{}{¿Ser un Seguidor? Tendré que hablar con Aaron primero. ¿Y entonces qué?}
{233}{}{La Villa debe convertirse en nuestra colonia, o el tiempo la borrará. Convence a tu gente de esto y liberaré a todos los esclavos de Villa.}
{234}{}{Trato hecho.}
{235}{}{Estás ofreciendo lo imposible. ¡Vete al infierno!}
{236}{}{Habla con Aaron. Él te dará más instrucciones.}
{237}{}{Bien.}
{238}{}{¡Esto es impensable! ¡Las personas como tú deben ser destruidas!}
{239}{}{Sólo estás cubriendo el mal con palabras bonitas. No me engañarás..}

# Primer diálogo si el jugador es miembro de la hermandad del acero
{240}{}{Encantado de conocerte, hermano. Los agentes de la Hermandad han enviado informes de tu servicio. Los Ancianos consideran que tienes potencial, pero mis agentes piensan lo contrario.}
{1240}{}{Encantado de conocerte, hermana. Los agentes de la Hermandad han enviado informes de tu servicio. Los Ancianos consideran que tienes potencial, pero mis agentes piensan lo contrario.}
{241}{}{Encantado de conocerte, hermano. Los agentes de la Hermandad han enviado informes de tu servicio. Tengo que decir que tienes un gran potencial.}
{1241}{}{Encantado de conocerte, hermana. Los agentes de la Hermandad han enviado informes de tu servicio. Tengo que decir que tienes un gran potencial.}
{242}{}{¿También eres miembro de la Hermandad?}
{243}{}{Paladín Ulysses Grant. Pero aquí, soy el Asesor. Trato de ocultar mi verdadera identidad en esta ciudad.}
{244}{}{¿Qué hace un paladín de la Hermandad en el centro de un culto extraño?}
{245}{}{Yo dirijo esta secta. La Iglesia del Fuego Sagrado fue creada por la Hermandad hace años. Esos fueron tiempos difíciles para Fénix. Ayudamos a un clan a tomar el poder en Fénix y poner a nuestra gente en control. Todavía lidero esta élite en beneficio de la Hermandad.}
{246}{}{Entonces, ¿Aaron y los demás cultistas son solo títeres de la Hermandad?}
{247}{}{Exactamente. Necesitamos recursos y poder sobre la región. Pero simplemente somos muy pocos para mantener el control directamente. El culto demostró ser una solución perfecta. Nosotros damos las órdenes; ellos se encargan del trabajo.}
{248}{}{Que conveniente. ¿Y qué hay de la esclavitud de la secta?}
{249}{}{A los ancianos no les gusta la esclavitud, pero es un sacrificio necesario para el desarrollo regional. Pasarán generaciones antes de que podamos abandonar el uso de esclavos. Los lugareños no están preparados para progresar por sí solos.}
{250}{}{¿Y la Villa?}
{251}{}{Ah, sí, la Villa... Un pueblo primitivo en el noroeste. El informe dice que eres de allí. Lo siento. Tu gente está ahora impulsando el progreso. Como miembro de la Hermandad, deberías entenderlo y aceptarlo.}
{252}{}{¿Puede la Villa ser liberada de la esclavitud?}
{253}{}{Por supuesto. Pero la Villa tiene que convertirse en una de nuestras colonias. Estoy demasiado ocupado para ocuparme de eso ahora. Tendrás que hacerlo tú. Habla con Aaron, él te dirá qué hacer.}
{254}{}{Entonces iré a hablar con él.}
{255}{}{Por supuesto. Pero la Villa tiene que convertirse en una de nuestras colonias. Resolver eso llevará un tiempo.}
{256}{}{Entonces hablemos de esto luego.}
{257}{}{Encantado de conocerte, hermano. Los agentes de la Hermandad han enviado informes de tu servicio. Tengo que decir que tienes un gran potencial. Aunque fue bastante imprudente de tu parte activar la alarma de camino hacia aquí.}
{1257}{}{Encantado de conocerte, hermana. Los agentes de la Hermandad han enviado informes de tu servicio. Tengo que decir que tienes un gran potencial. Aunque fue bastante imprudente de tu parte activar la alarma de camino hacia aquí.}
{258}{}{}
{259}{}{La Hermandad me habló de tu ascenso. Me alegro de verte, hermano.}
{1259}{}{La Hermandad me habló de tu ascenso. Me alegro de verte, hermana.}

# Después de la destrucción de Puerto
{260}{}{Sabía que vendrías... Salvaje. }
{1260}{}{Sabía que vendrías... Salvaje.}  
{261}{}{En otras palabras, la Hermandad ha sufrido la derrota en Sonora. Gracias a mí. Sopórtalo, idiota.}
{262}{}{Estás retrasando lo inevitable. Tarde o temprano, los ancianos de California establecerán un nuevo fuerte en Sonora. Y para ese entonces, Fénix ya estará lista. Esto es solo el comienzo.}
{263}{}{Oye, ¿por qué necesitas esas ametralladoras...? Espera, no vas a...}
{264}{}{Te equivocas. La Hermandad fracasó por su ideología defectuosa, no por el supuesto primitivismo de la región.}
{265}{}{¡Tonterías!}
{266}{}{En lo absoluto. Le impusiste ideas a gente que no estaba preparada para aceptarlas. Por eso encontraste resistencia.}
{267}{}{¡Intentamos cambiarlos, hacer que sean mejores! En lugar de gratitud, nos apuñalan por la espalda. Miren lo que la Hermandad ha hecho por ustedes: electricidad, educación, economía. ¿No significa nada para ti?}
{268}{}{No, no intentabas hacernos mejores. Intentabas hacernos tus súbditos. Siempre fuimos secundarios para ti, y siempre lo seremos.}
{269}{}{Quizás. Pero no pudimos hacerlo de la forma pacífica. Tuvimos que imponer nuestras ideas por la fuerza.}
{270}{}{¿Quién dijo que tus opiniones sobre cómo debería ser el mundo son correctas? ¿Porque vienen de antes de la guerra? Ya sabes cómo terminó la civilización que creó esas ideas.}
{271}{}{La guerra... la guerra nunca cambia. Queríamos devolver la grandeza a estas tierras.}
{272}{}{Y al final, se convirtieron en invasores regulares.}
{273}{}{¡Suficiente! Vuelve a tu casucha y vive como un ignorante. Estas tierras no merecen nuestra atención...}
{1273}{}{¡Suficiente! Vuelve a tu casucha y vive como una ignorante. Estas tierras no merecen nuestra atención...}
{274}{}{Hm...}
{275}{}{Parece que no puedo hacerte cambiar de opinión.}
{276}{}{Incluso después de destruir nuestra base en Puerto, no puedes detener tu sed de venganza. Ese es el problema de todas las tribus locales: se aferran al pasado mientras un futuro brillante está al alcance de sus manos. Solo deben aceptar el progreso y abandonar sus viejos prejuicios. Pero no, eso requiere de valentía, una que a ustedes les falta.}

# Diálogo repetido
{300}{}{Habla.}
{301}{}{No tengo nada que reportar. Me iré.}
{302}{}{¿Podrías darme acceso al resto del refugio?}
{303}{}{No creo que sea necesario.}
{304}{}{Los miembros de la Hermandad debemos confiar unos en otros.}
{305}{}{Como miembro de la iglesia del Fuego Sagrado, juro tener cuidado.}
{1305}{}{Formo parte de la iglesia del Fuego Sagrado, juro tener cuidado.}
{306}{}{Sabes, es difícil cumplir mi misión cuando ni siquiera recibo apoyo.}
{307}{}{Entonces me las voy a arreglar.}
{308}{}{Buen punto. Toma esta tarjeta. Otorga un nivel de autorización medio, eso será suficiente. }
{309}{}{Es mejor que nada.}
{310}{}{No puedo darte acceso en este momento.}
{311}{}{Gracias.}

# Preguntas
{320}{}{¿Puedo preguntarte algo?}
{321}{}{¿Sobre qué?}
{322}{}{Ya me voy. Con su permiso, asesor.}
{323}{}{¿Puedo hacerte una pregunta más?}
{324}{}{¿Podemos hablar de la iglesia del Fuego Santo?}
{325}{}{Una secta que inspira el progreso y el conocimiento.}
{326}{}{¿Este culto también fue creado por la Hermandad?}
{327}{}{En cierto modo. Nos inspiramos en otra secta que operaba en California. Resultó ser una buena idea.}
{328}{}{¿Qué tipo de refugio es este?}
{329}{}{Antes de la Gran Guerra, se construyeron refugios como este por todos los Estados Unidos. Estaban destinados a proteger a la población de las explosiones atómicas y sus consecuencias. Este es el refugio número 25.}
{330}{}{¿Qué sabes sobre la Gran Guerra?}
{331}{}{Varias naciones se destruyeron unas a otras por un puñado de recursos naturales y el dominio del mundo. Es una historia común, pero con una escala y una destrucción sin precedentes.}
{332}{}{¿Qué piensas de Aaron?}
{333}{}{No hablaré de él contigo.}
{334}{}{Una marioneta confiable con ambiciones y una mente subdesarrollada. Exactamente lo que necesitamos.}
{335}{}{Comenzará a resistir su posición algún día.}
{336}{}{Sin el apoyo de la Hermandad, tiene pocas posibilidades de tomar el poder. Afortunadamente, entiende eso bien.}
{337}{}{¿Qué tal otra pregunta?}
{338}{}{¿Por qué necesitas una bomba atómica?}
{339}{}{No hablaré de esto contigo.}
{340}{}{La Hermandad tiene muchas razones para tener un arma así, especialmente después de recientes sucesos en California. Pero eso no significa nada para ti.}
{341}{}{¿Podemos hablar de la Hermandad del Acero?}
{342}{}{La Hermandad es superior a los lugareños de la región en todos los sentidos... Excepto los números.}
{343}{}{Entonces, ¿cómo terminó la Hermandad controlando un culto?}
{344}{}{La Hermandad necesita el control de estas tierras, que no podemos mantener directamente. Así que establecimos un gobierno títere en Fénix para administrar la región. Creamos esta secta y lideramos una revolución bajo su bandera.}
{345}{}{¿Qué planes tiene la Hermandad para la región?}
{346}{}{Estamos recopilando tecnología y recursos de antes de la guerra. Nuestra sede en California necesita combustible nuclear, lo que requiere trabajadores. Establecer, reforzar y ampliar nuestro poder en Arizona es nuestra misión inmediata.}

{350}{}{Seguiré en Fénix por un tiempo. ¿Tienes algo que pueda hacer?}
{351}{}{No. Ve hacia el Puerto, es lo más importante en este momento.}
{352}{}{Tu misión está clara.}
{353}{}{Creo que sí. Desde su regreso a Fénix, George Crook no ha hecho más que causar problemas. Es un viejo guerrero que habla demasiado y exige demasiado. Debes silenciarlo.}
{354}{}{¿Cuál es la trampa?}
{355}{}{Crook y Aaron son viejos amigos. No quiero que Aaron supiera quién ordenó su muerte. Pero Crook no sale del casino, por lo que debes hacerlo en silencio.}
{356}{}{¿Cómo puedo hacerlo silenciosamente?}
{1356}{}{¿Cómo puedo hacerlo silenciosamente?}
{357}{}{Tendrás que pensar en algo. Te pagaré 500 chapas por su asesinato.}
{358}{}{Me ocuparé de ello y te lo haré saber cuando termine.}
{359}{}{Es demasiado arriesgado. Será mejor que me ocupe del holodisco.}
{360}{}{El comandante Crook tuvo un "accidente".}
{361}{}{Ya escuché los rumores. Buen trabajo.}
{362}{}{Encantado de ser de ayuda.}
{1362}{}{Encantada de ser de ayuda.}
{363}{}{Aquí está tu recompensa. Confío en que no revelarás nada sobre nuestro acuerdo. Nadie te creerá de todas formas.}
{364}{}{Solo tengo una pregunta: ¿por qué matar a Crook? ¿No sirvió gloriosamente al imperio?}
{365}{}{Entendido, señor. ¿Puedo irme?}
{1365}{}{Entendido, señor. ¿Puedo irme?}
{366}{}{Hay dos razones. En primer lugar, Crook ha cumplido su propósito; ahora sólo será una carga. El imperio ya no tiene enemigos fuertes, y a los viejos veteranos de guerra no les gusta estar sentados sin hacer nada.}
{367}{}{¿Y la segunda razón?}
{368}{}{Aaron necesitaba un pequeño recordatorio. Con sus recientes victorias, ha empezado a pensar demasiado sobre sí mismo y a exigir demasiado. Tenemos que recordarle dónde empezó y quién es el verdadero jefe aquí.}
{369}{}{Vale.}
{370}{}{Esto no cambia nada para ti, recluta. Tu tarea está en Puerto. Ve.}
{371}{}{Ha sido un honor.}

# Su propia búsqueda
{400}{}{Lograste engañar a Aaron y ganarte su confianza. Pero eso no funcionará conmigo. Después del incidente de la Villa, debes tener ambiciones completamente diferentes.}
{401}{}{¿Qué...? ¿Cómo...?}
{402}{}{Sé todo lo que pasa en esta ciudad. Tengo ojos y oídos por todas partes. Por supuesto, los informes sobre la Villa no pasaron desapercibidos. Entonces, ¿qué intentas conseguir con esta conspiración tuya?}
{403}{}{No quiero nada más que que mi gente sea libre.}
{404}{}{Un objetivo digno para alguien que no sabe nada de la libertad. Como decían los Antiguos, la libertad tiene un precio. Tu pueblo no puede sobrevivir ni mantener la libertad en este mundo. Tu única opción es unirte al progreso y convertirte en parte de este mundo.}
{405}{}{Entonces... ¿convertirnos en una colonia?}
{406}{}{Después de todo lo que he visto, reconozco que la Villa tiene que cambiar.}
{407}{}{Hmm, interesante. En ese caso, el único futuro para la Villa es convertirse en nuestra colonia.}
{408}{}{¿Una colonia?}
{409}{}{Exacto. Perderás parcialmente tu independencia, pero a cambio recibirás conocimientos, tecnologías y productos. Es un sistema mutuamente beneficioso, pero tu sociedad debe cambiar. Tendrás que explicar a tu pueblo la necesidad de deshacerse de las tradiciones anticuadas y pasar a un nuevo modo de vida.}
{410}{}{No será fácil, pero haré todo lo que sea necesario. Ellos me escucharán.}
{411}{}{Bien. En ese caso, debes hacer un viaje corto y peligroso. Lleva este importante holodisco a la base militar de Steel Port. La forma más segura de llegar es por caravana.}
{412}{}{Pero, ¿Qué ocurrirá con los campesinos esclavizados?}
{413}{}{No te preocupes por ellos. Daré instrucciones para que estén seguros. Pero la cuestión de la colonia debe ser decidida por el cuartel general. Ve a Puerto Peñasco y muéstrale mi informe al comandante en jefe.}
{414}{}{Iré de inmediato.}
{415}{}{He hecho todo lo pedido por Aaron. Ahora te pido que liberes a los campesinos de la Villa.}
{1415}{}{He hecho todo lo pedido por Aaron. Ahora te pido que liberes a los campesinos de la Villa.}
{416}{}{Tu valor impresiona a hombres como él. Pero tengo algo más que decirte. ¿Qué es lo que realmente quieres para tu pequeña y orgullosa tribu?}
{417}{}{¿Cuál es la base a donde tengo que llevar el holodisco?}
{418}{}{La base militar en Puerto Peñasco, a orillas del Golfo de California. Pocos saben de ella. Entenderás todo cuando llegues allí.}
{419}{}{Bien. ¿Puedo hacerte otras preguntas?}
{420}{}{Iré allí de inmediato.}
{421}{}{Al menos podrías haber explicado más las cosas. Bien, iré allí.}
{422}{}{¿Qué hay en el holodisco?}
{423}{}{Un informe secreto para el cuartel general, que incluye información sobre la Villa. No se lo enseñes a nadie ni intentes leerlo; está encriptado.}
{424}{}{Parece que descubriste mi plan. ¡Tendré que matarte!}
{425}{}{¡Basta ya! Esto nunca sucederá. Ustedes sólo son ladrones y extorsionadores.}
{426}{}{Qué estrechez de miras... Parece que no puedes sernos útil, tendremos que sacarte de nuestro camino.}
{1426}{}{Qué estrechez de miras... Parece que no puedes sernos útil, tendremos que sacarte de nuestro camino.}
{427}{}{Espera, ¿eso es un arma?}
