{100}{}{Ves a un sujeto de prueba.}

{101}{}{Ves a un loco. Está mirando silenciosamente hacia arriba.}
{102}{}{Ves a una mujer con el pelo alborotado y los ojos rojos. Está mirando hacia la pared.}
{103}{}{Ves a un psicópata. Está sentado en el suelo y se balancea mientras se agarra la cabeza.}

{111}{}{Uh-uh-uh...}
{112}{}{¡Tus trucos no funcionarán en mí! ¡Aléjate, maldito cultista!}
{1112}{}{¡Tus trucos no funcionarán en mí! ¡Aléjate, maldita cultista!}
{113}{}{¡Mi cabeza! Escucho tantos pensamientos... tantos... Tus pensamientos... ¡son horribles!} 
