{110}{}{Esta bomba podría ser muy peligrosa, pero le faltan algunos componentes.}
{111}{}{La bomba está lista para ser detonada.}
{112}{}{Has instalado los fusibles exitosamente.}
{113}{}{La bomba está lista para explotar. Utiliza la habilidad de Trampas para activarla.}
{114}{}{Es la bomba más grande que jamás hayas visto.}
{115}{}{Eso no será necesario. Todo ya pasó como debía.}
{116}{}{Eso no será necesario. La Iglesia ya ha sido derrocada.}

{120}{}{Ves una ojiva nuclear de potencia baja. No está terminada, pero podría activarse.}
{121}{}{La bomba no tiene los fusibles necesarios, así que no es un peligro.}
{122}{}{Has activado el temporizador de la bomba con éxito.}
{123}{}{Has desactivado el temporizador de la bomba con éxito.}
{124}{}{No es necesario reparar la bomba.}
{125}{}{No es posible desactivar el temporizador.}

{505}{}{La bomba detonará en }
{506}{}{ segundos.}
