{100}{}{Ves a Keel.}
{101}{}{Estás viendo a un chico con una chaqueta de cuero, juega con su lanza.}
{102}{}{Les harías un favor a todos si te largas de aquí.}
{103}{}{Agh... creo que tuve demasiado...}

{110}{}{¿Eh? ¿Qué quieres?}
{111}{}{Es mejor que no molestes a los demás.}
{112}{}{No te conozco.}
{113}{}{Muévete.}
{114}{}{En el Acueducto, sólo cabe la gente honesta.}
{115}{}{Dudo que encuentres un sitio en dónde descansar por aquí.}
{116}{}{Te lo advierto - si vienes a robarnos, perderás las manos.}

#Dialogue
{200}{}{Un momento, ¿qué estás haciendo aquí?}
{201}{}{No es asunto tuyo.}
{202}{}{No deberías de haber dicho eso, haré que te arrepientas...}
{203}{}{Espera, cálmate...}
{204}{}{Inténtalo.}
{205}{}{Hay un montón de cadáveres allá abajo. ¿Qué sabes al respecto?}
{206}{}{Ah, claro. Deben ser esos idiotas a los que se les dijo que se mantuvieran alejados del acueducto. Y no hicieron caso. Como tú.}
{207}{}{Fueron asesinados, no fue una bestia, sino un hombre.}
{208}{}{No me digas. ¿Y ahora qué, genio?}
{1208}{}{No me digas. ¿Y ahora qué, listilla?}
{209}{}{Voy a matar a todos los responsables. Empezando contigo.}
{210}{}{Garth tenía razón, eres peligroso. Es tu funeral, forastero.}
{1210}{}{Garth tenía razón, eres peligrosa. Es tu funeral, forastera.}
{211}{}{No, será el tuyo...}
{212}{}{No quería encontrarme esto, fue un accidente. ¿Qué tal si salimos de aquí y olvidamos que esto pasó?}
{213}{}{¿En serio eres tan tonto? Garth me ordenó que te matara si descubrías algo. Lo siento, no es nada personal...}
{1213}{}{¿En serio eres tan tonta? Garth me ordenó que te matara si descubrías algo. Lo siento, no es nada personal...}
{214}{}{Espera, no quiero pelear...}
{215}{}{No me dejas otra opción.}
{216}{}{Lo único que tienes es una lanza, ¿en serio crees que eso te ayudará?}
{217}{}{Mi lanza acabó con muchas vidas, la siguiente será la tuya.}
{218}{}{Muéstrame lo que tienes...}
{219}{}{Los demás Rangers saben que estoy aquí. Si me haces algo, ellos lo sabrán.}
{220}{}{Demonios... No quiero problemas, pero una vez que Garth se entere de esto, los habrán.}
{221}{}{Le pondré fin a esto, Garth cruzó la raya que ningún Ranger debería cruzar. ¿Acaso no lo ves?}
{222}{}{Suficiente. Veamos si de verdad estás tan vergas.}
{223}{}{¿Lo ves? Eres una amenaza para nuestro pueblo, Garth los mató, pero no fue sin motivo. No necesitamos a gente como tú. Te enviaré al infierno...}
{224}{}{Ya lo veremos...}
{225}{}{Espera, ¿entonces Garth es el culpable? Hay que detenerlo, Garth cruzó la raya que ningún Ranger debería cruzar. Entiendes eso, ¿no?}
{226}{}{Pues... es cierto. Garth está perdiendo la cabeza, antes se encargaba de las amenazas de verdad, y ahora mata a cualquiera que no le guste. Tienes razón, es demasiado. Haz lo que tengas que hacer.}
{227}{}{Gracias, me encargaré de ello. Eres un buen tipo.}
{228}{}{Pensándolo bien, no me das confianza. Debería deshacerme de ti, ahora mismo...}
{229}{}{Tendré que informar al cuartel general acerca de esto.}
{230}{}{Garth me ordenó que te matara si descubrías algo. Lo siento, no es nada personal...}
{231}{}{¿Vas a matar a un Ranger?}
{232}{}{No tengo otra opción. Debo detenerte, Garth me lo ordenó. Si no lo hago, será un desastre para todos.}
{233}{}{Entonces eres un idiota. Y morirás un idiota...}
{234}{}{¿En serio le vas a pegar a una mujer! ¿Qué clase de hombre eres?}
{235}{}{Mierda, no quiero golpear a una mujer. Pero, ¿qué otra opción tengo? Garth no perdona los errores, y no deberías de haberte metido en donde no te llamaron...}
{236}{}{Entonces dame lo mejor que tengas...}

{240}{}{Oye, oye, espera. No quiero problemas contigo, pero Garth me ordenó que te detuviera.}
{241}{}{¿Detenerme? Esa lanza no penetrará una servoarmadura. ¿No eres un suicida, cierto?}
{242}{}{¿Qué piensas hacer? ¿Nos matarás, o nos delatarás?}
{243}{}{Los mataré. Tú serás el primero.}
{244}{}{Quiero que me cuentes lo que pasó, hay cadáveres allá abajo, y no fue ningún animal.}
{245}{}{Fue Garth, se deshace de los forasteros si él piensa que no merecen vivir aquí. Al principio, si algo de verdad nos amenazaba, esa era su solución. Pero algo cambió dentro suyo, y ahora se deshace de cualquiera que le parezca sospechoso.}
{246}{}{Eso es repugnante. Garth pagará por esto, y tú también...}
{247}{}{Entonces, ¿eres su lacayo? Mira, tenemos que detenerlo.}
{248}{}{Sólo hago el trabajo sucio, espero que sepas lo que haces.}
{249}{}{Quédate aquí y escóndete. Reza que los Rangers te den un juicio justo.}
{250}{}{Lo sé. Los mataré a los dos, empezando contigo.}

{260}{}{Quieto, mutante. Te ves como si hubieras salido de la basura. ¿Qué haces aquí?}
{1260}{}{Quieta, mutante. Te ves como si hubieras salido de la basura. ¿Qué haces aquí?}
