{100}{}{Ves a un niño.}
{101}{}{Ves a un niño. Huele a tierra y pescado.}
{102}{}{¡Gracias, señor! Me hacían falta.}
{1102}{}{¡Gracias, señorita! Me hacían falta.}
{103}{}{Gracias, señor. Pero ya tengo un par de chanclas.}
{1103}{}{Gracias, señorita. Pero ya tengo un par de chanclas.}
{104}{}{Eso fue muy amable de su parte.}

{200}{}{¡Yo los vi! ¡Lo juro! ¡Digo la verdad! Pero, tú... ¿Quién eres?}
{201}{}{¿Qué viste?}
{202}{}{Cuidado con lo que dices, mocoso.}
{203}{}{¡Monstruos! Salen del acueducto cuando es de noche, ¡lo juro, yo los vi! Ahora ya entiendo por qué no nos dejan ir allá abajo. ¡Seguro que hay un montón de ellos!}
{204}{}{Hmm.}
{205}{}{Estás mintiendo.}
{206}{}{¡Lo digo en serio! No tenían nada de pelo y se veían asquerosos, y hacían sonidos raros con sus narices de cerdo. ¿Y si vienen aquí y nos atacan?}
{207}{}{Cálmate, seguramente eran ratas cerdo. No te acerques a ellas y no te harán nada.}
{208}{}{Puede ser. ¿Qué piensas hacer al respecto?}
{209}{}{Yo... No lo sé. Pero a Garth se le ocurrirá algo, siempre tiene un plan. ¡Una vez vi como bajaba al acueducto totalmente sólo! A Garth no le asusta nada. Nos mantiene a salvo, pase lo que pase.}
{210}{}{Espera un momento, ¿qué estabas haciendo tú en el acueducto?}
{211}{}{Pues... Sólo daba una caminata, nada más. Pero se supone que no debemos ir allá, así que me castigaron - hicieron que revisara las redes de pesca. Puaj, estaban todas babosas y apestosas.}  
{212}{}{¿Encontraste algo útil?}
{213}{}{La verdad no... pero... ¿necesitas munición? Encontré un poco al lado del acueducto. Seguramente se le cayó a un cazador. Podría cambiártelas por algo que me sirva.}  
{214}{}{Lo tendré en cuenta.}
{215}{}{No gracias, la pólvora debe estar mojada.}
{216}{}{Andas descalzo, parece que cualquier te sería de ayuda.}
{217}{}{Pues... No lo sé. Es malo que Garth no pueda ayudarnos, él era muy duro. Hubo una vez en la que lo vi entrar al acueducto por sí mismo. No le tenía miedo a nada. ¡Hubiese podido protegernos de quien sea!}
{218}{}{¿Qué aceptarás de vuelta?}

{220}{}{¡Los vi con mis propios ojos! ¡Digo la verdad!}
{221}{}{Te creo. Adiós.}

{230}{}{¿Es por eso que andas descalzo?}
{231}{}{Sí... Cuando vi a los monstruos, salí corriendo. Corrí tanto que se me rompieron las chanclas. Así que debo encontrar unas nuevas...}
{232}{}{¿Y encontraste algo interesante al lado del acueducto?}
