{100}{}{Ves a un forastero.}
{101}{}{Ves a un chico de ropa desgastada.}
{102}{}{Buena suerte, pronto me iré del Acueducto. Intentaré buscar otro lado en donde vivir, más arriba en el Colorado.}
{103}{}{¿Qué tenía... el agua...?}
{104}{}{Ah-h...}

#Dialogue
{200}{}{Em, hola.}
{201}{}{Hola, llegué hace poco, quiero conocer a todos.}
{202}{}{Ah, eso es... genial. Yo también soy nuevo. No he podido hacer amigos.}
{203}{}{¿Pasó algo?}
{204}{}{Llegué junto a mis dos amigos, pero desaparecieron, y los demás no quieren ni hablarme. Solo me queda sentarme junto a la fogata, mientras pesco y pienso sobre el futuro.}
{205}{}{Que triste historia. Es una pena.}
{206}{}{Su comportamiento es entendible, creo yo.}

{210}{}{¿Qué quieres?}
{211}{}{Nada. Por ahora.}
{212}{}{Hola, ¿tienes alguna noticia?}
{213}{}{Lo siento, no tengo nada que decirte.}
{214}{}{Hola.}
{215}{}{Adiós.}

{220}{}{¿Qué hay de los Rangers? ¿No pueden ayudarte con tu grupo?}
{221}{}{Hablé con Garth, es como... el sheriff de este lugar. Pero creo que no hace nada al respecto. ¿Y qué va a hacer? Ya le pregunté a los demás, nadie sabe nada.}
{222}{}{¿De dónde vinieron tú y los demás?}
{223}{}{Somos de una gran ciudad, al este de aquí. Habíamos oído que los rangers estaban dispuestos a proteger a cualquiera. Pero no parece que los lugareños sean amistosos con los forasteros.}
{224}{}{Buscaré a tus amigos, y si me entero de algo, te lo haré saber.}
{225}{}{Gracias. Cuéntame lo que descubras.}
{226}{}{Adiós, nos vemos.}

{230}{}{Encontré a tus amigos... en los túneles del acueducto.}
{231}{}{¿Estaban muertos, verdad? Dios... Ya entiendo por qué Garth le prohíbe a todos bajar ahí. Sé que él y sus matones tuvieron que haber matado a otros. Malditos Rangers...}
{232}{}{¿Qué harás ahora?}
{233}{}{Quiero vengarme de ese hijo de puta para que esto no vuelva a ocurrir. Peso eso me traerá más problemas. De todas formas, no me quedaré aquí.}
{234}{}{¿Qué tal si reportas esto a la base? Dudo que los demás sepan sobre esto.}
{235}{}{No me dejan hablar con el comandante, ya lo intenté. ¿Puedes hacerlo tú? Si no detenemos a Garth, seguirá matando a cualquiera que no le agrade.}
{236}{}{Intentaré decírselo al General. Pero no será fácil.}
{237}{}{Eres una buena persona. Gracias.}
{238}{}{Espérame aquí y te diré lo que pase.}
{239}{}{Piérdete, ya me metiste en problemas.}
{240}{}{Entonces olvídalo, será mejor que me vaya. Garth quedará impune... Sí, claro, eso sí que será mejor.}
{241}{}{No me hagas sentir culpable. Adiós.}
{242}{}{¿Y si matamos a Garth y ya? Será mucho más fácil, y divertido.}
{243}{}{¿Matar a un Ranger? Me buscarán por todo el yermo. Mierda, no quiero escapar de los rangers por el resto de mi vida. Mejor me largo de una vez.}
{244}{}{Te deseo suerte, niño.}

{250}{}{Garth pagará por sus crímenes. Tus amigos fueron vengados.}
{251}{}{Sí... ¿Sabes? Realmente, no éramos amigos. Es solo que, la carretera nos unió, ¿sabes? Pasaron muchas cosas durante el viaje. ¿Quién hubiese dicho que un pueblo así terminaría siendo peor que el yermo? Un ranger demente lo arruinó todo.}
{252}{}{Sí, es una pena que haya acabado así.}
{253}{}{}
{254}{}{Gracias por todo. Ten, acepta estas balas. A decir verdad, se las robé a los Rangers, así que es justo entregártelas. Es hora de que me marche. No podré labrarme una vida aquí.}
{255}{}{Que te vaya bien.}
