{100}{}{Ves a una mujer.}
{101}{}{Ves a una mujer de mediana edad. Parece estar agotada luego de un largo viaje.}
{102}{}{Te deseo buena suerte.}
{103}{}{¡Los maldigo a todos! ¡Ojalá se mueran!}
{104}{}{Se acabó... Déjame ser, que la naturaleza siga su curso.}

#Dialogue on the Rangers map
{200}{}{¡Tú! ¡Tráeme al general, ahora!}
{201}{}{Señora, deje de gritar. La podemos escuchar bien.}
{202}{}{Le estás gritando a la persona equivocada, sólo estoy de paso.}
{203}{}{¡Sí, claro, y ahora me dirás que no eres parte de los malditos Rangers! Hasta los coyotes de por aquí hacen la pelota a los más fuertes.}
{204}{}{¿Tienes algún problema con los rangers?}
{205}{}{¡Eso es decir poco! Y no lo voy a dejar así. Si el general no sale a dar la cara, voy a entrar por mí misma.}
{206}{}{¿Tú otra vez? Si no me vas a ayudar, quítate de mi vista.}
{207}{}{Espera aquí, hablaré con los rangers.}
{208}{}{Dime lo que ocurrió.}
{209}{}{Estos supuestos "guardianes de la paz" ejecutaron a mi esposo, me dejaron a mí y a mi hijo a valernos por nosotros mismos en medio del desierto. Es un milagro que hayamos llegado hasta acá con vida.}
{210}{}{¿Fue culpable de algo?}
{211}{}{¿Culpable? Por acá, todos son culpables de algo, si crees en la ley de los Rangers. ¡Pero eso no quiere decir que deberían ser ejecutados!}
{212}{}{Sé como te sientes.}
{213}{}{¿Qué quieres hablar con el general?}
{214}{}{Lo voy a mirar a los ojos y le diré la verdad acerca de sus hombres. Quizás no sepa que están haciendo, pero pienso en hacerlo responsable por sus acciones y exigirle una compensación.}
{215}{}{Eso es muy valiente de tu parte.}
{216}{}{¿Esas eran todas tus preguntas?}
{217}{}{¿Ese es tu hijo?}
{218}{}{Sí. ¿Por qué preguntas?}
{219}{}{Sólo me daba curiosidad. Olvídalo.}


{220}{}{No puedes quedarte aquí, los rangers no te protegerán y no podrás mudarte a asentamientos cercanos por tu reputación.}
{221}{}{¡Ya lo sé! ¿Pero a dónde iremos? Hay desierto por todos lados, otro viaje así acabará con nosotros. Podríamos intentar llegar a California... Es nuestra única oportunidad. ¡Pero los Rangers bloquearon el único cruce del río!}
{222}{}{Hay un cruce, bajando el río. Pero no es muy seguro.}
{223}{}{Así es, ni siquiera tengo una pistola para defendernos de los coyotes y las ratas. Sin ayuda, no podré llegar a la barcaza con mi bebé.}
{224}{}{Iré con ustedes, prepárate.}
{225}{}{Iré con ustedes, pero luego.}

{226}{}{Los guardias ya no están.}
{227}{}{Eso veo, pero no cambia nada, no podemos acercarnos al General. La presa está repleta de Rangers, ni siquiera podríamos llegar a la ciudadela en el otro lado. Una de dos, o nos matan a disparos, o nos capturarán.}
{228}{}{El General está muerto.}
{229}{}{¿En serio? ¿No es un truco? Bueno, también escuché eso. Parece que estiró la pata, eso es un alivio. Pero no sé que haré ahora.}

{230}{}{Hola, viajero. ¿Intentas escapar de este infierno?}
{1230}{}{Hola, viajera. ¿Intentas escapar de este infierno?}
{231}{}{¿Tienes algo que decirme?}
{232}{}{Quizás.}
{233}{}{Los Rangers arruinaron nuestra familia. No quiero hablar sobre ello... pero si miras la presa, puedes ver que recibieron su merecido.}
{234}{}{¿Y?}
{235}{}{No parece que seas un peligro, deberíamos permanecer juntos. ¿Me ayudarías a cruzar al otro lado? Bajando el río, hay una barcaza, pero no quiero ir sola. Dicen que por ahí hay coyotes, lobos y cosas peores.}
{236}{}{Claro, iré contigo. Vámonos.}
{237}{}{No puedo ayudarte ahora mismo, quizás en otro momento.}
{238}{}{¿Ya cambiaste de opinión? Ven con nosotros. ¿Por qué quedarte en este desierto? En California puedes tener un nuevo comienzo, puedes dejar el pasado atrás.}
{1238}{}{¿Ya cambiaste de opinión? Ven con nosotros. ¿Por qué quedarte en este desierto? En California puedes tener un nuevo comienzo, puedes dejar el pasado atrás.}
{239}{}{Sigue.}
{240}{}{Tengo mis propios problemas con los Rangers.}
{241}{}{¿Se supone que eso me haría sentir mejor? Hm. Bueno, parece que estamos en las mismas, quizás deberíamos ayudarnos.}

#On the ferry map
{300}{}{Hablemos al llegar a la barcaza.}
{301}{}{De acuerdo. Concentrémonos en llegar a salvo.}
{302}{}{Vale.}

{303}{}{No me gusta como estás mirando al niño. No lo asustes, o haré que te arrepientas por el resto de tu vida.}
{304}{}{¡No era mi intención!}
{305}{}{No te conviene amenazarme, señorita.}

{310}{}{¿Cómo se llama, señorita?}
{311}{}{Soy Cecilia, y este es mi hijo.}
{312}{}{No se parece mucho a ti.}
{313}{}{Es... adoptado. Lo encontré entre unas ruinas, no podía dejarlo allí.}
{314}{}{¿Es cierto que tu esposo era un criminal?}
{315}{}{No le preguntaba de donde conseguía los suministros, pero le robaba a los viajeros y los granjeros para mantenernos, eso estaba claro. De alguna forma teníamos que sobrevivir. En Fénix lo tenía peor; allí estaba forzado a trabajos mucho más sucios.}
{316}{}{¿Escapaste de Fénix?}
{317}{}{Sí... La gran ciudad. Demasiada gente y muy pocos recursos. En el yermo, al menos tu destino está en tus manos, pero en la ciudad siempre estás a la merced de otro.}
{318}{}{¿Así que ahora odias a los Rangers?}
{319}{}{Por supuesto, e incluso si hubiesen tenido razón y mi esposo realmente hubiese sido un criminal, ¡eso no me hace la vida más fácil!}
{320}{}{}
{321}{}{Lo entiendo.}
{322}{}{Mi aldea tampoco aceptaría algo así.}
{323}{}{Hmm, en nuestra Villa, cada campesino debe seguir los caprichos de la comunidad. Pero, es distinto.}
{324}{}{Eso es respetable.}
{325}{}{Deberías haberme advertido de eso antes.}

{330}{}{La barcaza está lista para partir. Súbete, te llevaré al otro lado.}
{331}{}{Estoy profundamente agradecida. No cualquiera nos habría ayudado, especialmente en territorio de los Rangers. Pero, ¿y tú? Nos... ¿Nos acompañarás a California?}
{332}{}{No puedo. Tengo un compromiso con mi familia y mi hogar.}
{333}{}{Ah... Está bien. No es común encontrar gente tan leal a su gente como tú. Te deseo suerte, gracias por todo.}
{334}{}{De nada.}
{335}{}{No tengo nada que darte de vuelta, pero si alguna vez te encuentras en Fénix, háblale al cantinero del casino acerca de mí, quizás te de un descuento. Adiós.}
{336}{}{[Envía a la familia al otro lado]}
