{100}{}{Ves a Helford.}
{101}{}{Ves a uno de los comandantes de campo.}
{102}{}{Debido a que rescataste a Jason, tu reputación entre los rangers ha mejorado.}

#First dialogue
{200}{}{(te echa un vistazo rápido y continúa examinando algunos informes) Estás hablando con el comandante de campo, ni nombre es Helford. Si estás aquí para hacerme perder el tiempo, deberías irte de aquí. Tengo trabajo que hacer.}
{201}{}{¿Podrías dar unos minutos de tu tiempo a este humilde campesino?}
{1201}{}{¿Podrías dar unos minutos de tu tiempo a esta humilde campesina?}
{202}{}{No estoy aquí para perder el tiempo charlando, comandante.}

#Repeated dialogue
{210}{}{¿Te puedo ayudar en algo?}
{211}{}{Adiós.}
{212}{}{Ya entendí. No tienes que seguir.}
{213}{}{¿Te puedo hacer una pregunta?}
{214}{}{Adelante.}
{215}{}{Tengo otra pregunta.}

#Questions
{220}{}{¿Cómo te volviste un ranger?}
{221}{}{Empecé joven y me dediqué a perfeccionar mis habilidades en el desierto. Si sirves tanto tiempo como yo, puede que igual te ganes el título de comandante de campo.}
{222}{}{¿Qué es este lugar?}
{223}{}{Esta es la base principal de los rangers, el centro de comando está dentro de la planta eléctrica de la presa; allí se lleva a cabo el entrenamiento de los novatos, además de las reuniones 'diplomáticas'.}
{224}{}{¿Qué clase de reuniones 'diplomáticas'?}
{225}{}{Me refiero a charlas comerciales y a negociaciones. Nos dedicamos a traer de vuelta el orden a la región y eso significa que debemos formar alianzas.}
{226}{}{No sé mucho acerca de los rangers. ¿Qué puedes contarme?}
{227}{}{Somos guerreros de élite y expertos en la supervivencia. Nuestras habilidades nos permiten hacer cumplir la ley y el orden en el Yermo. Nuestra misión principal es traer de vuelta el orden al yermo.}
{228}{}{¿Y lo hacen gratis?}
{229}{}{Imponemos impuestos a nuestros territorios y se les aplican reglas, la 'Ley'. Si te rehúsas a obedecerlas, nos rehusamos a ayudarte.}
{230}{}{¿De qué es esa 'Ley' de la que hablas?}
{231}{}{Las reglas básicas, las regulaciones, etcétera. Si las quiebras, te enfrentas a las consecuencias, las que a veces son letales.}

#Ranger -- Jackals
{233}{}{Gracias por ayudar con la búsqueda, los Chacales hicieron polvo a nuestro hermano; me alegra que hayan pagado por eso.}
{234}{}{No hace falta. Encontramos los restos de nuestra patrulla en la madriguera de los Chacales, allá, al norte. Creo que ya sabes en dónde está.}
{235}{}{No veía eso venir. Qué pena.}
{236}{}{¿Cómo puedo rastrear a la patrulla desaparecida?}
{237}{}{Podrías probar a utilizar la radio y averiguar su última posición, pregunta por los asentamientos vecinos o hasta puedes aventurarte en el desierto y esperar lo mejor.}
{238}{}{Ojalá que no llegue a eso; deambular por el desierto no debe ser nada divertido.}

{239}{}{Quizás no sea el momento adecuado, pero los Chacales están listos para formar una alianza con los rangers.}
{240}{}{¿¡Qué!? ¡Por supuesto que no! Los Chacales son agresivos y astutos; no están dispuestos a negociar. Cualquier oferta que tengan es un truco que los beneficiará a ellos. El general estaría de acuerdo conmigo.}
{241}{}{Los Rangers de la patrulla norteña han muerto, los Chacales los mataron.}
{242}{}{Maldita sea... Tenía un presentimiento de que iba a acabar así. Esos salvajes han derramado la sangre de nuestros hermanos demasiadas veces. Pero, debemos agradecerte que hayas descubierto lo ocurrido. Le enviaré un informe al general.}
{243}{}{De nada.}
{244}{}{Uno de los rangers de la patrulla norteña consiguió regresar, pero vino sólo.}
{245}{}{Ya se me informó sobre esto, bien hecho, ranger. Sigue así..}
{246}{}{Se me hizo saber de eso. Hiciste un buen trabajo, para ser un civil. Nos vendría bien más hombres como tú; tienes lo que se necesita. Sigue así.}
{1246}{}{Se me hizo saber de eso. Hiciste un buen trabajo, para ser un civil. Nos vendría bien más mujeres como tú; tienes lo que se necesita. Sigue así.}
{247}{}{De nada.}
{248}{}{¿Qué opinas de los Chacales?}
{249}{}{Los Chacales es una de las tribus más asquerosas en el Yermo. Son tan salvajes que es imposible diferenciar a sus niños de un perro. Me duele el corazón al ver que una nación ha llegado a la situación en la que está. Hay canibalismo, un culto ridículo, hostilidad a todos los forasteros, incluso a los clanes vecinos - ¿pueden caer más bajo?}

#Family of a criminal
{250}{}{Mataste al esposo de esa mujer, ¿puedes justificar eso?}
{251}{}{Ah, esa señorita te puso las pinzas encima, ¿verdad? Debes entender que su esposo era un criminal, él asaltaba a los granjeros y los vagabundos también sufrían sus ataques. Es por esto que fue ejecutado, acorde a la Ley. Nadie pensó que podría tener una familia.}
{252}{}{[Más]}
{253}{}{Y para ti, eso no es más que una historia. Si te soy honesto, para mí también lo es. Pero no tienes la idea de los problemas que puede causar una escorpión hembra. Hay que hacer algo al respecto de esto.}
{254}{}{[Más]}
{255}{}{Quizás puedas convencerla de que espabile. Sin ofender, pero puede que te ganes su confianza más fácilmente, pero no tienes la apariencia de un ranger, sino de un campesino.}
{256}{}{¿Qué tengo que hacer?}
{257}{}{Es simple, explícale que no es bienvenida en estas tierras. Será mucho mejor para todos si ella y el niño se van de aquí.}
{258}{}{Está bien, lo voy a intentar.}
{259}{}{No quiero meterme en los problemas de los demás.}
{260}{}{Parece que has manejado bien el asunto. Buen trabajo, te daré algo de munición, es mi forma de agradecerte.}
{261}{}{Gracias.}
{262}{}{Un momento. Me he enterado de algo, y es triste. El barquero está muerto y la última vez que se te vio fue sobre la barcaza, junto a la mujer y el niño. Es una coincidencia muy grande, ¿no crees?}
{263}{}{Yo, em, no tuve nada que ver con eso.}
{264}{}{Eso espero. Porque tarde o temprano, nuestros chicos descubrirán la verdad sobre lo que pasó. Y ya sabes cómo imponemos la Ley, más aún si estamos tan cerca de la ciudadela.}
{265}{}{Claro, eh... sé que podrán encontrar al culpable. Tengo que irme...}

#Farm spy
{270}{}{Quiero reportar que hay un espía por aquí, está escondido en la Ruta 95, en el sótano de una choza abandonada.}
{271}{}{Gracias por contarme esto, voy a despachar a un par de los nuestros para tomarlo desprevenido. Es hora de lidiar con ese bastardo.}
{272}{}{Buena suerte.}
{273}{}{¿Escuchaste que el intendente perdió un arma?}
{274}{}{No, y no es problema mío. Tengo asuntos más importantes de los que encargarme.}
{275}{}{Comprendo.}

#Stop-dialogue
{280}{}{Carajo... Eres igual a... Los Segadores que hay más al sur. Sin ofender, pero no deberías bajar la guardia si llegas a estar en alguna ciudad.}
{281}{}{Sí, lo entiendo. No sería la primera vez.}

{282}{}{Tienes agallas para venir aquí después de lo que hiciste.}
{283}{}{Me vendió algo que no funcionaba.}
{284}{}{¿Y te parece bien matar a alguien por algo así? Mierda... Se debería castigar acorde al crimen, ¿no crees?}
{1284}{}{¿Y te parece bien matar a alguien por algo así? Mierda... Se debería castigar acorde al crimen, ¿no crees?}
{285}{}{No, la verdad no.}
{286}{}{Me arrepiento de mis acciones.}
{287}{}{Su guardia me atacó primero.}
{288}{}{¿Te refieres al imbécil de su hijo? Sabíamos que traería problemas, pero raramente causaba alguna pelea. Voy a creer lo que dices, pero, ¿no podías dejarlo pasar y ya?}
{289}{}{¿Te refieres a Flick? ¿De qué estás hablando?}
{290}{}{¿No sabes nada y no estás relacionado a la muerte del mercader? ¿En serio piensas que me creeré eso? Pero, no es fácil probar eso si no hubieron testigos, supongo.}
{1290}{}{¿No sabes nada y no estás relacionada a la muerte del mercader? ¿En serio piensas que me creeré eso? Pero, no es fácil probar eso si no hubieron testigos, supongo.}
{291}{}{Eso fue exactamente lo que ocurrió, comandante.}
{292}{}{(niega con la cabeza) La gente del yermo es tan... Tienes suerte de que nadie lo vio, además, la reputación de Flick no era perfecta. Puedes irte. Pero estamos aquí para mantener la paz, no lo olvides.}
{293}{}{Lo entiendo, comandante.}
{294}{}{Bueno, eso espero. Te creeré, por ahora. Pero no olvides que estamos aquí para mantener la paz. Puedes irte.}
{295}{}{Gracias, comandante.}
{296}{}{Em...}
{297}{}{Bien, quiero saber qué ocurrió contigo y Flick.}

#Defending the Villa
{300}{}{He venido en nombre de la Villa, necesitamos la ayuda de los Rangers.}
{301}{}{Estoy buscando ayuda, quiero liberar a los campesinos de la Villa de la esclavitud.}
{302}{}{Los granjeros de la Villa siguen necesitando ayuda.}
{303}{}{(frunce el ceño y aleja la mirada de sus informes) La Villa - de alguna forma cosechan maíz en medio del desierto, como si fuera un oasis. Puedo simpatizar contigo, en estos días, todos sufren tiempos difíciles. Fénix es una amenaza que se expande sobre toda Arizona, capturan todos los recursos y esclavos que puedan.}
{304}{}{Recuerdo lo que habíamos conversado sobre la Villa.}
{305}{}{Y, ¿me ayudarás?}

{306}{}{Hay demasiados problemas a los que abarcar y no damos abasto, todas nuestras fuerzas están repartidas por el yermo.}
{307}{}{Eso es una pena.}
{308}{}{Entonces, no creo que pueda contar con la ayuda de los Rangers.}
{309}{}{}
{310}{}{Primero, debes completar mis encargos y hasta ese entonces no puedo darte una cita con el General, ni tampoco podría retirar a los demás de sus misiones.}
{311}{}{Ya he completado todas tus misiones.}
{1311}{}{Ya he completado todas tus misiones.}
{312}{}{Eso parece. Te seré sincero, no pensaba que lo conseguirías. Te había dado esos encargos para que no tuviera que lidiar contigo. Me alegra ver eres una persona dedicada.}
{313}{}{Sigue.}
{314}{}{Pero, respecto a la Villa... El General debe encargarse de eso. Ve a hablar con él, los guardias te dejarán entrar. El cómo resulte esto, depende de él.}
{315}{}{Gracias, comandante.}
{316}{}{De acuerdo, pero si resulta que todo esto fue para nada, tú tendrás la culpa.}

{320}{}{El General ayudará a la Villa.}
{321}{}{Maldita sea. ¿Pudiste convencer al viejo? Tenemos problemas mucho más grandes que salvar a un montón de campesinos. Ustedes siempre nos vieron como saqueadores, ¿o me equivoco? Pero, una orden es una orden. De ahora en adelante, la Villa está bajo nuestra protección.}
{322}{}{Para serte honesto, este acuerdo no me emociona para nada. La Villa siempre nos ha visto como saqueadores, pero ahora que tienen problemas, vienen corriendo directo a nosotros. Sin embargo, lo prometimos - la Villa está bajo nuestra protección. Ojalá que podamos sacarle partido a todo esto.}
{323}{}{Lo entiendo. Esperemos que todo salga bien, comandante.}
{324}{}{No me sorprende que los Rangers sean de pocos amigos con una actitud como la tuya. Adiós, 'amigo' mío.}
{1324}{}{No me sorprende que los Rangers sean de pocos amigos con una actitud como la tuya. Adiós, 'amigo' mío.}


#Story quests
{330}{}{¿Puedo ayudarte de alguna forma?}
{331}{}{Lo normal es que la ayuda la demos *nosotros*... Pero, en este caso, agradecemos cualquier asistencia. Incluso si es de parte de un campesino como tú.}
{1331}{}{Lo normal es que la ayuda la demos *nosotros*... Pero, en este caso, agradecemos cualquier asistencia. Incluso si es de parte de una campesina como tú.}
{332}{}{¿Qué necesitas que haga?}

{333}{}{Ve a la estación de radio y habla con la oficial de comunicaciones. Le hacían falta algunas partes, una vez que te hayas encargado de eso, ven a hablar conmigo.}
{334}{}{Eso suena fácil, lo haré.}
{335}{}{Creo que eso me llevaría mucho tiempo, no quiero hacerlo.}

{336}{}{Eso no es todo. Hacia el sur, hay un pueblo llamado Quartz. Hace un tiempo que se habían asentado un grupo de personas, pero nuestros exploradores nos han informado de que desaparecieron. Descubre qué pasó ahí. Ah, y nuestro cartógrafo quiere conseguir información del sitio, habla con él, está en la estación de radio.}
{337}{}{Voy a descubrir lo que ocurrió.}
{338}{}{¿Me estás dejando el trabajo pesado, cierto? Es obvio.}

{340}{}{Una cosa más, perdimos un grupo de exploradores en el norte, en el desierto del Mojave. No hay nadie a quien pueda pedirle que investigue, así que podrías ir tú y descubrir qué ocurrió. Podrías entrar a los asentamientos del norte y preguntar.}
{341}{}{consideralo hecho.}
{342}{}{Si voy hacia allá, lo haré.}

{343}{}{Excelente, espero resultados. Puedes irte.}
{344}{}{[Vete]}

{350}{}{Quiero hablarte respecto a mis misiones...}
{351}{}{Infórmame de lo que has hecho.}
{352}{}{Bueno, la verdad no tengo mucho que decir.}

{353}{}{La estación de radio quedó desactivada, no fue culpa mía.}
{354}{}{(irritado) Ya lo sé. ¡No estás ayudando, para nada! (se calma) Vale... Te creeré, no fue tu culpa. Al fin y al cabo, aliarte con los rangers es tu mejor opción.}
{355}{}{Perdona por los... eh, problemas.}
{356}{}{Cuidado con cómo me hablas, ya te lo dije, no fue mi culpa.}
{357}{}{¿Podrías explicarme cómo puedo arreglar la estación de radio?}
{358}{}{Háblale a la oficial de comunicaciones acerca de eso, yo sólo quiero saber si funciona o no.}
{359}{}{Entiendo, entonces hablaré con ella.}
{360}{}{La radio ha vuelto a funcionar, pude arreglarla.}
{361}{}{Buen trabajo, expandir el rango de la señal ayudará a nuestros rangers, tanto en la paz como en la guerra. Eso de la radio siempre nos ha hecho difíciles las cosas. Pero, me dijeron que hubo un problema.}
{362}{}{Sí, resulta que alguien estaba interceptando las transmisiones.}
{363}{}{¿Así que alguien nos estaba escuchando? No me sorprende, durante nuestra lucha contra el crimen, nos hemos ganado enemigos. Lo extraño es que alguien ha aprendido sobre la transmisión por radio, es poco probable que sea un montón de saqueadores del yermo. Esta información podría sernos útil. Puedes llevarte este rifle de caza, te lo has ganado. Y, si sigues siendo de ayuda, puede que te haga falta.}
{364}{}{A su servicio.}
{1364}{}{A su servicio.}
{365}{}{Espero que podamos seguir cooperando en el futuro.}
// added by cambragol for mid-way feedback
{366}{}{Ya casi arreglo la radio, pero hay algo de interferencia en la señal y estoy trabajando en ello.}
{367}{}{Una vez que hayas terminado, házmelo saber. Quizás debas rastrear la frecuencia, de alguna forma.}
{368}{}{Vale.}



{370}{}{He traído noticias sobre Quartz.}
{371}{}{En ese caso, habla.}
{372}{}{Los lugareños tuvieron la culpa, se irradiaron y se volvieron locos.}
{373}{}{Esta holocinta contiene toda la historia.}
{374}{}{Eh, la verdad, es que no lo sé.}
{375}{}{(suspira) Qué estupidez. Esto es lo que ocurre cuando la gente le mete mano a la tecnología de la preguerra. Activan algo que no entienden, y pierden la cabeza por ello.}
{376}{}{Y estuvieron así de cerca de alcanzar su meta.}
{377}{}{Quizás, pero al menos ya está resuelto.}
{378}{}{Lo hiciste bien, vamos a colocar avisos e informar a las patrullas. Agradezco tu ayuda.}
{1378}{}{Lo hiciste bien, vamos a colocar avisos e informar a las patrullas. Agradezco tu ayuda.}
{379}{}{No fue nada.}
{380}{}{Me alegra haber sido de ayuda.}

{390}{}{Estoy aquí para reportar los crímenes de Garth, el ranger.}
{391}{}{¿Será que te estás pasando de la raya? He oído toda clase de rumores de los Rangers, y Garth tiene un buen historial. La verdad, es que hay cosas peores de las que preocuparse. Déjalo en paz.}
{392}{}{Em...}
{393}{}{Así que Garth era un criminal, me sorprende, tenía tantos logros... La paz le hizo esto. Al estar retirado, la paranoia empieza a apoderarse de ti. Ojalá que no sea contagioso.}
{394}{}{Todos tenemos problemas. Incluso tú, comandante.}
{395}{}{Su historia será una lección, para los rangers, y para ti.}

#Additional quests
{400}{}{Me gustaría seguir ayudando a los Rangers.}
{401}{}{Ese es el espíritu, siempre nos viene bien más manos, piernas, orejas y ojos.}
{402}{}{Encontraré alguna cosa que hacer.}
{403}{}{Tristemente, no voy hacia allá. ¿Quizás haya algo más?}

{410}{}{Podría ayudarte con explorar en áreas más lejanas.}
{411}{}{No sabes lo útil que sería eso. Hemos perdido el contacto con uno de nuestros grupos de exploradores, se encontraban en el desierto del Mojave, hacia el norte. No hay nadie disponible que pueda embarcarse en una operación de rescate, así que quiero que investigues en dónde están.}
{412}{}{Daré mi mejor esfuerzo para encontrarlos.}
{413}{}{Si me encuentro en el área, lo investigaré.}
{414}{}{Estoy esperando tu informe.}
{415}{}{¿Tienes alguna otra misión para mí?}
{416}{}{Debo irme.}

{420}{}{¿Necesitas que haga de intermediario en alguna negociación?}
{421}{}{Tengo justo la tarea indicada para ti. Estábamos esperando a unos refugiados del este, pero se dirigieron a Ciudad Garaje. Dado que posiblemente ya vas en esa dirección, quiero que descubras el por qué cambiaron su curso.}
{422}{}{Vale, me enteraré de qué está pasando.}

{430}{}{Encontré a los refugiados en Ciudad Refugio, pero cuando llegué, ya habían muerto.}  
{431}{}{¿Qué demonios pasó?}  
{432}{}{Los mataron como si fueran animales, los lugareños no son muy cordiales con los forasteros.}  
{433}{}{Mal lugar, mal momento. Eso es todo.}  
{434}{}{No tengo ni la menor idea.}  
{435}{}{En estos tiempos, incluso hasta los chatarreros están dispuestos a cometer un crimen por su odio a los forasteros. Como puedes ver, al mundo le hace falta una mano firme que impida que la gente se pase de la línea.}  
{436}{}{Así es.}
{437}{}{Gracias por aligerarnos un poco el trabajo.}
{438}{}{Me alegra haber sido de ayuda.}
{439}{}{Hago esto para ayudar a la Villa.}
{440}{}{Encontré a los refugiados en Ciudad Garaje, un hombre que fingía ser un ranger los intimidó.}
{441}{}{¿Alguien se está haciendo pasar por nosotros?}
{442}{}{Exacto, aquí está la placa del impostor, ya no será ningún problema.}
{443}{}{Los criminales harán cualquier cosa para llegar a sus metas. Estoy seguro de que debía tener alguna 'justificación' para sus acciones.}
{444}{}{Sí.}
{445}{}{Esta no es la primera vez que alguien intenta ensuciar nuestro nombre. Los norteños nos odian a pesar de nuestras acciones, pero, las cosas están cambiando; los criminales ya no luchan únicamente para sobrevivir, sino que están organizados y patrocinados. Sin embargo, también podremos lidiar con esta amenaza.}

{450}{}{Estoy pensando en quedarme cerca de la base, ¿tienes alguna misión que darme?}
{451}{}{Han habido reportes de una especie de... enfermedad, entre los habitantes del Acueducto, es una comunidad en el litoral del Colorado, un poco al este desde aquí. Quiero que lo investigues y descubras qué podemos hacer para ayudarles.}
{452}{}{Me encargaré de ello, comandante.}

{453}{}{He descubierto qué estaba causando la enfermedad - Flick estaba vendiendo una bebida radioactiva.}
{454}{}{¿Estaba vendiendo material irradiado? Había oído rumores, pero nadie tenía evidencia de que era el culpable.}
{455}{}{Al menos ahora servirá de algo; alimentará a los gusanos.}
{456}{}{Ah, entonces la justicia se nos adelantó. Gracias por informarme de esto, desde ahora, es problema nuestro.}
{457}{}{Claro.}
{458}{}{Adiós.}
{459}{}{No se escapará esta vez.}
{460}{}{Flick ya está yéndose al yermo, debes interceptarlo antes de que llegue demasiado lejos. Encárgate con esos bienes irradiados como sea necesario.}
{461}{}{Entiendo.}
{462}{}{Al desierto, otra vez...}
{463}{}{Flick ya no te causará ningún problema, sufrió las consecuencias de sus acciones.}
{464}{}{¿Lo mataste? No pensé que llegarías a ese punto, pero, gracias por lidiar con el problema.}
{465}{}{Adiós.}
{466}{}{Flick ya no tiene las botellas, es una lección que no olvidará.}
{467}{}{¡Excelente trabajo! Flick es un buscapleitos, pero como mercader, es indispensable. Tiene suerte de que sólo perdió las botellas. Te daré estos suministros, gracias. (Te entrega dos estimulantes y un antídoto) Puedes venderlos, si no te hacen falta.}
{468}{}{No hay de qué.}
{1468}{}{No hay de qué.}
{469}{}{Es una recompensa bastante mala, pero es mejor que nada.}
