{100}{}{Ves al viejo Rufus.}
{101}{}{Ves al supervisor de la presa, es un anciano canoso que lleva puesto un overol desgastado.}

#First Dialogue
{200}{}{(Estás viendo a un hombre calvo y barbudo de unos 50 años, su overol está sucio e indica la naturaleza de su trabajo.) ¿Eh? Perdona, pero mis oídos no son lo que eran antes. Si te pasas los mismos años que yo junto a estas máquinas, igual te costará oír.}
{201}{}{Ya veo.}
{202}{}{¿Y quién eres tú? No te he visto antes y conozco a todos los de esta presa. A los novatos no se les permite estar cerca de la planta y el intendente se encarga de las caravanas. Lo que quiere decir...}
{203}{}{Que vengo a ocuparme de mis propios asuntos.}
{204}{}{Sí, de tus asuntos. Sólo no te metas en donde no te llaman.}
{205}{}{Y, ¿qué haces aquí, viejo?}
{206}{}{Entonces te dejaré en paz.}

#Re-dialogue
{210}{}{¡Habla! No bajes la voz.}
{211}{}{Dije "adiós".}
{212}{}{Retrocedamos un poco.}
{213}{}{Tengo otra pregunta.}

#Questions
{220}{}{¿Quién eres tú?}
{221}{}{Me llaman Rufus, soy el supervisor de esta presa. Yo me aseguro de que este lugar funcione y no tenga problemas.}
{222}{}{¿En qué rango estás, Rufus?}
{223}{}{No tengo. Sólo soy un trabajador, no soy soldado.}
{224}{}{¿Hace cuánto que estás trabajando aquí?}
{225}{}{Hmm, déjame pensar. Unos 30 años, creo. Aquí nadie cuenta los años.}
{226}{}{¿Por qué los rangers se establecieron en esta presa?}
{227}{}{¿No es obvio? Es una forteza impenetrable, y una fuente de energía imparable.}
{228}{}{Soy el supervisor de la presa, me aseguro de que el lugar funcione y no tenga problemas..}
{229}{}{Y, Rufus, ¿cuál es tu trabajo?}
{230}{}{¿El acueducto también es parte de la planta eléctrica?}
{232}{}{No, es distinto. La planta funciona bien sin él, el acueducto no ha estado años sin funcionar.}
{231}{}{¿Qué le pasó?}
{233}{}{Lo que hace el tiempo. Las bombas de agua ya se descompusieron, no se pueden arreglar. Además, el río está bajo. Aunque funcione, ya no hay nadie por esos lados que necesite el agua.}
{234}{}{Esto es una estructura impresionante. ¿Quién la construyó?}
{235}{}{La gente del pasado era astuta. Estos días no hay nadie con vida que sea capaz de construir algo así.}
{236}{}{Supongo que eran demasiado astutos para su propio bien, ¿no crees?}
{237}{}{Sí... Pero eso no cambia el hecho de que crearon un acueducto genial para irrigar el desierto.}

#First quest
{250}{}{Suena a que es todo un desafío.}
{251}{}{Este sitio es una reliquia, ¡pero ni te imaginas los problemas que tiene! Por ejemplo, esa unidad de control no quiere cooperar. Y no podemos reemplazarla - todos los aparatos de por aquí eran únicos en su tipo.}
{252}{}{Entonces, ¿esa unidad está rota? ¿Crees que pueda echarle un vistazo?}
{253}{}{¡Ni lo pienses! Para arreglarla, necesitarás más que tus habilidades. Pero eres de esos que siempre andan viajando por ahí, ¿no? Si te cruzas con partes electrónicas, tráelas. Quizás podamos hacerla funcionar con eso.}
{254}{}{Veré qué encuentro.}
{255}{}{Puede que consiga las partes que necesitas.}
{256}{}{Claro. Mientras intentas hacerte el héroe, yo voy a trabajar. Sin ofender.}
{257}{}{De hecho, necesito más información.}
{258}{}{Entonces nos vemos luego.}
{260}{}{Acerca de la unidad de control...}
{261}{}{¿Eh? ¿Qué le pasa?}
{1261}{}{¿Eh? ¿Qué le pasa?}
{262}{}{Eh, no es nada. Pensaba en voz alta.}
{263}{}{¿Cuál es el problema con conseguir partes electrónicas?}
{264}{}{¿Crees que no las hemos buscado? Lo sabe toda patrulla y comerciante. Pero por estos lados, todo es campo. ¿En dónde encontrarías partes en un lugar así? Traerlas de las ciudades no es ni barato ni rápido. Y ahí tienen que cuidar a su gente.}
{265}{}{¿Por qué es tan importante la unidad de control?}
{266}{}{Mira esa tremenda máquina, la que está en medio de la sala. Dentro, tiene un tornillo que está sumergido en el río Colorado. El río lo hace girar y eso genera electricidad... ¿Sabes qué es la 'electricidad', verdad?}
{267}{}{Sí, obvio...}
{268}{}{Entonces, fluye a través de la unidad de control hacia los transformadores de afuera, y luego a las líneas eléctricas. Pero ahora, está roto - no es más que un montón de cables.}
{269}{}{Hmm. Tengo otras preguntas.}
{270}{}{He conseguido reparar la unidad de control.}
{271}{}{¿Eh? Mira, sólo te digo que a los Rangers no nos gustan las bromas, especialmente si se trata de la presa.}
{272}{}{Pero, está funcionando bien. Mira.}
{273}{}{Bueno, vamos a ver... ¡Santa Catarina! ¿Cómo...? ¡Está funcionando!}
{274}{}{Claro, está como nueva. Pero... em... no soy una caridad, ¿sabes?}
{275}{}{Sí... lo que pensaba. Toma, por ayudarnos. te puedes llevar unas células de microfusión. Si no las ocupas, las puedes intercambiar en alguna ciudad por algo útil.}
{276}{}{Sí, arreglarla no fue tan difícil. Es mi pequeña contribución a la gran causa de los Rangers.}
{277}{}{¡Así es! Los Rangers jamás olvidan a sus amigos.}
{278}{}{[Más]}
{279}{}{Gracias, eso debería mantenerla en marcha durante un tiempo. Es una pena que no seguirás aquí cuando yo me retire.}
{280}{}{Bien, vendré a verla después... De momento, mantén a este pedazo de chatarra funcionando.}
{281}{}{Tranquilo, viejo. Puede que esos cables te chamusquen un poco los dedos.}
{282}{}{}
{283}{}{¿En dónde puedo conseguir partes electrónicas?}
{284}{}{El lugar más cercano es Ciudad Garaje. Hace tiempo coloqué un pedido, pero no ha habido suerte.}

#Second quest
{300}{}{Y, ¿cómo ha estado la presa desde que la arreglé?}
{301}{}{¡De maravilla! No necesitará un arreglo por un buen rato. Pero, es una pena que no me podrás reemplazar el día en el que me retire.}
{302}{}{¿Te encargas de toda la presa tú sólo?}
{303}{}{(suspiro) A veces, escucho el zumbido de estas turbinas. Están oxidadas y el ruido lo demuestra, pero me recuerda a los años pasados.}
{304}{}{Entonces... ¿necesitas un reemplazo?}
{305}{}{Exactamente, joven. Este lugar necesita a un cuidador nuevo - alguien joven que sea habilidoso con la tecnología. Estos días, es difícil encontrar gente así.}
{1305}{}{Exactamente, señorita. Este lugar necesita a un cuidador nuevo - alguien joven que sea habilidoso con la tecnología. Estos días, es difícil encontrar gente así.}
{306}{}{¿A quién tienes en mente?}
{307}{}{Pues, aparte de ti, los caravaneros mencionaron a un chico de Ciudad Garaje, se supone que tiene talento. Me gustaría entrenarlo, pero a esa ciudad no le agradan los Rangers. No es que pueda agarrarlo así como así, debe ser su decisión.}
{308}{}{Quizás pueda convencerlo.}
{309}{}{consideralo hecho. Sacaré al niño de ese vertedero.}
{310}{}{Tendrás que encontrar a alguien más. Adiós, viejo.}
{311}{}{¡Ese es el espíritu! Eso es lo que diferencia a los jóvenes. Trato hecho. Estoy emocionado por conocerlo.}
{312}{}{Adiós.}
{320}{}{Tengo malas noticias - el niño de Ciudad Garaje ha fallecido.}
{321}{}{(niega con la cabeza) Es una pena, podría haberle hecho un gran servicio a los Rangers en el futuro... Bueno, tendré que conformarme con alguno de los lugareños, incluso si ninguno es particularmente aficionado a la tecnología. Ya no tengo más trabajos para ti, gracias por tu esfuerzo.}
{322}{}{Entonces, ¿no me darás una recompensa?}
{323}{}{Tus esfuerzos se quedaron cortos, ¿no? Bueno, a moverse, tengo cosas que volver al trabajo.}
{324}{}{Bueno, así son las cosas...}
{325}{}{Traigo malas noticias. El niño talentoso de Ciudad Garaje está muerto.}

{330}{}{Aquí está el niño que querías.}
{331}{}{Vaya. ¡Hola, hijo! Me da la sensación de que vas a encajar con los Rangers. Pero, primero lo primero - te vendría bien una ducha...}
{332}{}{Ejem...}
{333}{}{...Y, tú le has hecho un gran favor a los Rangers al traerlo con nosotros. Habla con el intendente, le dije que te preparara una buena recompensa.}
{1333}{}{...Y, tú le has hecho un gran favor a los Rangers al traerlo con nosotros. Habla con el intendente, le dije que te preparara una buena recompensa.}
{334}{}{¡Excelente! Iré a por mi recompensa.}