{100}{}{Ves a Flick, el comerciante.}
{101}{}{Estás viendo a Flick, se dedica a comerciar en varios asentamientos.}
{102}{}{No tengo más Nuka-Cola, lo juro.}
{103}{}{El mercader se deshizo de su mercancía dañina. Lo único que falta es informar al Comandante Helford al respecto.}

#Start of Dialogue
{200}{}{¡Hola, viajero! Si vas a viajar y te falta algo, te puedo dar lo que sea... Espera, le vendí todo a los Rangers. Mierda.}
{1200}{}{¡Hola, señorita! Si vas a viajar y te falta algo, te puedo dar lo que sea... Espera, le vendí todo a los Rangers. Mierda.}
{201}{}{¿Eres un comerciante?}
{202}{}{Me llamo Flick. Me dedico a vender en el territorio de los Rangers. ¿Qué necesitas? Quizás sepa en dónde lo puedes encontrar.}
{203}{}{Dudo que tengas lo que busco. Hasta luego, Flick.}
{210}{}{¿Qué necesitas? Quizás sepa en dónde lo puedes encontrar.}
{211}{}{Nos vemos.}
{212}{}{Hablemos de otra cosa.}

#Questions
{220}{}{Para ser exactos, ¿qué es lo que vendes, Flick?}
{221}{}{Lo que me encuentre - comida, ropa, utensilios. Pero ahora lo único que tengo son chapas.}
{222}{}{¿Chapas? ¿Para qué?}
{223}{}{¿No sabes? Hay una ciudad grande al este, y allá empezaron a usar las chapas como dinero. Es una idea rara, pero conveniente. El problema es que los Rangers no aceptan chapas, prefieren los trueques.}
{224}{}{¿Por qué no?}
{225}{}{Piensan que el dinero no es estable, jamás sabes el verdadero valor de una chapa. Así que hacer trueques es mejor, pues no hay 'in-flación'. Aunque, si uno fuera a tener un montón de chapas, quizás cambien de parecer.}
{226}{}{Interesante. Tengo más preguntas, no parece que estés ocupado.}
{227}{}{Me preocupa mi familia, no el dinero. Adiós.}
{230}{}{¿En dónde conseguiste el brahmán?}
{231}{}{Se lo compré a unos pastores de un pueblo de por acá. Fue una gran inversión, pero dio resultados.}
{232}{}{Ya veo. Pero no quiero hablar de brahmanes.}
{233}{}{Comprendo. Adiós.}
{234}{}{He estado en San Brahmán, los pastores ya no están vendiendo sus brahmanes.}
{235}{}{¿Qué quieres decir? ¡Yo no robé ningún animal! Pero no podría decirte en dónde lo consiguió el vendedor.}
{236}{}{Ajá, claro. ¿Qué más tienes que contarme?}
{237}{}{No quiero seguir escuchándote. Adiós.}
{240}{}{Viajar por el desierto es peligroso, ¿no te preocupa?}
{241}{}{Esto es el territorio de los Rangers - es el lugar más seguro que conozco.}
{242}{}{Puede ser, pero no me gusta como me está mirando tu guardia.}
{243}{}{Entonces debes poder responderme unas preguntas más.}
{244}{}{Ah, resulta que debo irme. Adiós, Flick.}
{245}{}{(suspira) Es mi hijo, tiene un poco de... retraso, así que no lo molestes.}
{246}{}{No lo haré, pero sí te voy a molestar a ti, tengo más dudas.}
{247}{}{Me lo deberías haber dicho antes. Tengo que irme...}
{250}{}{¿Alguna vez has ido a Quartz?}
{251}{}{Una vez. La gente era muy pobre y poco amistosa, ni quise pasarme a vender algo.}
{252}{}{¿En serio era tan malo? Lo tendré en cuenta.}
{260}{}{Tengo que hablar con el general de los Rangers.}
{261}{}{Pues, no te puedo ayudar con eso. Pero, ¿sabes qué? Los Rangers no te dejarán entrar a la presa a no ser tengas una muy buena razón. Jeje... puede que hacerse amigo de ellos lo haga más fácil. Pero, ¿para qué quieres al general?}
{262}{}{Nada en particular, solo quiero hablarle.}
{263}{}{Hmm. Lo que tú digas.}
{264}{}{Hmm. (analiza la situación) Carajo, es lejos y está peligroso... Eh... No puedo ayudarte.}
{265}{}{Mi gente fue esclavizada y quiero que los rangers me ayuden a rescatarlos.}
{266}{}{Dudo que vayan a hacer eso, amiguito. Pero, habla con el comandante en el centro de información. ¿En dónde está tu asentamiento?}
{1266}{}{Dudo que vayan a hacer eso, señorita. Pero, habla con el comandante en el centro de información. ¿En dónde está tu asentamiento?}
{267}{}{Está... lejos de aquí.}
{268}{}{Hmm. Lo que tú digas.}
{269}{}{Al note, lo llamamos 'La Villa'.}
{270}{}{Oye, yo te conozco. Tú estabas aquí cuando el Colorado se tragó a la presa.}
{1270}{}{Oye, yo te conozco. Tú estabas aquí cuando el Colorado se tragó a la presa.}
{271}{}{Así es. ¿Y qué estás haciendo aquí?}
{272}{}{Los rangers están en serios problemas, es un caos. Pero, aún puedo vender mi mercancía, aunque todo sea un desastre. Debo... especializarme en otros productos.}
{273}{}{Déjame adivinar, ¿armas, drogas y alcohol?}
{274}{}{¡Baja la voz! Te van a escuchar. Tengo que aprovecharme de la situación hasta que los Rangers vuelvan al control. ¿Lo entiendes?}
{275}{}{Haz lo que debas.}
{276}{}{Acabarán con tu negocio tarde o temprano. Adiós.}

#Dialogue on the road map
{300}{}{¿Qué pasa? ¿Acaso te enviaron los rangers?}
{301}{}{Estás muy preocupado. ¿Ya sabes que te están buscando, no?}
{302}{}{Sí, lo sé. ¡Pero no puedes probar que mi Nuka-Cola enfermó a esos tipos! Mi mercancía está limpia, ¿me escuchas?}
{303}{}{Todos saben que es culpa tuya. ¿Qué tal si usamos el contador Geiger en tus botellas?}
{304}{}{¡Claro que no, quita tus manos de mis cosas! ¡Atrás!}
{305}{}{...}
{310}{}{Déjame en paz, porque no voy a darte nada.}
{311}{}{Está bien.}
{312}{}{¿Puedo llevarme la Nuka-Cola y ya?}
{313}{}{Eso te costará un montón de chapas. Pero creo que podrías darme un tesorito por ese montón de basura. Muéstrame lo que tienes.}
{314}{}{[Seguir]}
{315}{}{Cuídate.}
{316}{}{Entrega toda la Nuka-Cola. No lo pediré dos veces.}
{317}{}{¡Ni en pedo!}
{318}{}{[Atacar]}
{319}{}{Deberías haberme hecho caso.}
