{100}{}{Ves a un fugitivo.}
{101}{}{Ante ti se encuentra un joven con una chaqueta sucia. Está exhausto, parece que ha pasado por mucho.}
{102}{}{¿Qué... me diste...?}
{103}{}{...Eres... escoria...}
{104}{}{Parece que los Rangers atraparon al espía. En medio de la carretera, su cadáver servirá como un recuerdo para los demás mercenarios.}
{105}{}{Le debo la vida, doc.}
{106}{}{Nos veremos en la Catedral del Fuego.}

# First dialogue
{200}{}{(En la penumbra, apenas consigues percibir el movimiento de alguien; un joven con una chaqueta sucia está sentado en un colchón viejo, está exhausto.) ¡Alto! ¿Quién eres? ¿Q-qué estás haciendo aquí?}
{201}{}{Sólo estoy viajando, pensé que este sería un buen lugar para tomar un descanso.}
{202}{}{Como puedes ver, está ocupado.}
{203}{}{Quizás no debería haber venido aquí. Bueno, me voy...}
{204}{}{¡Espera! ¿Tienes agua? ¡Me muero de sed!}
{205}{}{Yo tampoco tengo muchos suministros. ¿En dónde está la fuente de agua más cercana?}
{206}{}{En el otro lado de la calle, los granjeros tienen un pozo. Pero esos bastardos no te darán ni una gota hasta que les pagues todo lo que tienes... Mira, ¡ayúdame a recuperar mis esfuerzas! Tengo conexiones, podré ayudarte en el futuro.}
{207}{}{Es problema tuyo, encárgate tú mismo de él. Así es la ley del Yermo.}
{208}{}{Hmm... Espérame, volveré con agua limpia...}
{209}{}{Claro, aquí tienes.}
{210}{}{(Con manos temblorosas, agarra la cantimplora y traga el agua; luego de satisfacer su sed, se quita la chaqueta y con el agua lava una herida de color negro, mientras llora como un perro por el dolor.)}
{211}{}{¿Te sientes mejor?}
{212}{}{Me salvaste... pero no voy a durar mucho.}
{213}{}{No parece que vayas a sobrevivir con una herida así. Le pediré ayuda a los Rangers...}
{214}{}{¡NO! Esos bastardos no me ayudarán. ¡Ellos tienen la culpa de que esté así! Igual que tú, sólo estaba viajando, buscaba un lugar en el que asentarme. Los Rangers asumieron que era un saqueador y me dispararon sin hacer preguntas, tengo suerte de estar vivo. Saqué la bala con un cuchillo, ¡pero la herida me está matando!}
{215}{}{La tienes difícil...}
{216}{}{¡Has algo! ¡Sin ti, estoy acabado!}
{217}{}{Entonces quítate la chaqueta y prepárate para ser examinado. Soy doctor.}
{1217}{}{Entonces quítate la chaqueta y prepárate para ser examinado. Soy doctora.}
{218}{}{Esa herida es muy seria... no sé de medicina.}
{219}{}{Entonces anda con los Rangers y obtén medicamentos de allá. ¡Necesito un estimulante, o moriré!}
{220}{}{Resiste, ya vengo.}
{221}{}{Hmph. Es problema tuyo.}
{222}{}{Quizás pueda curar tus heridas.}
{223}{}{¿Trajiste agua?}
{1223}{}{¿Trajiste agua?}
{224}{}{Aquí tienes.}
{225}{}{Todavía no, resiste.}
{226}{}{¿Y por qué estás ahí sin hacer nada! ¡Apresúrate!}
{227}{}{No compartiré mis suministros contigo. Estás por tu cuenta.}
{228}{}{¡Mutaracha asquerosa! ¡Voy a llevarme todas tus cosas!}
{229}{}{Oye, oye, guarda esa cosa...}
{250}{}{¿Te gusta verme sufrir?}
{251}{}{Estoy trabajando en ello...}
{252}{}{No te pases, recuerda que sin mi ayuda, estás muerto.}
{253}{}{Para ser sincero, no pensé que alguien fuera a ayudarme. Es... n-noble de tu parte. Quizás deba reflexionar sobre cómo veo a la gente.}
{254}{}{Suena a que también necesitas una dosis de una buena conversación. ¿Quieres hablar?}
{255}{}{Creo que ya hice lo que debía. Cuídate.}
{256}{}{Para tratar al desconocido, utiliza tus habilidades médicas o suministros.}

# Repeat dialogue
{300}{}{¿Qué quieres?}
{301}{}{Ya volveré.}
{310}{}{¿Qué has estado comiendo?}
{311}{}{Lo que me encuentre por el desierto - lagartos, frutas, larvas. No tengo mucha elección, pero ya estoy acostumbrado.}
{312}{}{Los granjeros me contaron que alguien roba sus cultivos.}
{313}{}{(Pausa) Tengo que sobrevivir. No me importa lo que piensen los demás.}
{314}{}{Hmm...}
{315}{}{Comprendo.}
{316}{}{Y, ¿qué te trajo al territorio de los Rangers?}
{317}{}{Los rumores que oí acerca de los Rangers y su justicia. Era mentira y todo estaba exagerado. Si quieres su apoyo, tienes que entregarles todo lo que tengas. Y después de eso, QUIZÁS, vayan a ayudarte.}
{320}{}{¿Has visto al perro de los granjeros?}
{321}{}{He visto uno, pero no sé a dónde se fue. Los granjeros debieron haberlo alimentado mejor.}
{322}{}{Ya veo.}
{323}{}{¿Mataste al perro, verdad?}
{324}{}{¿En serio es tan obvio? Entonces no hay por qué negarlo. Necesitaba comida y esa bestia asquerosa no me dejaba acercarme a la plantación. ¡Además, casi le advirtió a los granjeros de que estaba escondido aquí! Tenía que hacer algo.}
{325}{}{Eso fue una decisión arriesgada...}
{326}{}{¡Oye! Más te vale que mantengas la boca cerrada y no le digas a nadie. ¿Entendido?}
{327}{}{Eh, sí, no diré nada.}
{330}{}{Bien, ¿puedes decirme lo que realmente ocurrió?}
{331}{}{(suspira) Conozco a algunos tipos de Fénix que necesitaban el cifrado de la radio de los Rangers. Me prometieron una buena paga.}
{332}{}{¿Y fuiste herido mientras intentabas conseguir el cifrado?}
{333}{}{Si quieres chapas, necesitas tomar riesgos. Intenté infiltrarme en la estación de radio durante la noche, pero me dispararon. Desde ese entonces he estado aquí escondido, sin poder hacer nada... Oye, ¿quieres ganarte unas chapas conmigo?}
{334}{}{¿Quiénes son los tipos que necesitan el cifrado?}
{335}{}{Si te dijera, me estaría perdiendo un montón de chapas. ¿De acuerdo?}
{336}{}{¿Tienes alguna idea de cómo conseguir el cifrado?}
{337}{}{La estación de radio de los Rangers contiene toda la información, pero convencer a alguno de ellos para que lo comparta sería casi imposible.}
{338}{}{Puede que hayan otras personas intentando conseguir el cifrado.}
{339}{}{Puede ser, pero no conozco a nadie más.}
{340}{}{Voy a pensar sobre tu oferta.}
{341}{}{Tus clientes son los Seguidores del Fuego, ¿no? En ese caso, tengo malas noticias - la Catedral del Fuego fue destruida.}
{342}{}{¿¡Qué!? ¿¡En serio!? ¿Sabes lo que eso significa? ¡Perdí mi paga *y además* el Yermo está a punto de sumirse en el caso! Ya no volveré a Fénix, de ninguna manera... tendré que irme a las montañas y sobrevivir en la naturaleza hasta que las cosas se calmen. Olvídate del cifrado, ya no me sirve.}  
{343}{}{Tienes razón, ya no tienes nada que hacer aquí.}
{344}{}{¿Por qué sigues aquí? Los Rangers deben estar buscándote.}
{345}{}{No tengo otra opción, si no consigo el cifrado, mis clientes me matarán... y si no lo hacen ellos, me matarán los usureros a los que les debo.}
{346}{}{Tengo otra pregunta.}
{347}{}{¿Qué quieres saber?}
{348}{}{Hablemos sobre el cifrado.}
{349}{}{Cuéntame más acerca de esta situación.}
{350}{}{Ya conozco el cifrado.}
{351}{}{¿Y bien? ¿Cuál es?}
{352}{}{No tan rápido. ¿Qué me darás a cambio?}
{353}{}{Un montón de chapas, las escondí en un lugar seguro. Pero primero, debo saber cómo lo conseguiste.}
{354}{}{Aquí tienes el cifrado.}
{355}{}{No te diré nada si no me darás nada.}
{356}{}{Buena jugada, ¿cierto? Ahora, los Seguidores del Fuego me pagarán una fortuna. ¡Estarán *obligados* a aceptarme entre sus filas! ¡Me uniré a la élite de Fénix! ¿¡Me escuchas!?}
{357}{}{Eso es genial. Si alguna vez me encuentro en Fénix, ¿me ayudarás a entrar?}
{358}{}{Ni siquiera necesitarás chapas, ¿sabes? Lo que hace falta es gente con visión. Ahí nos vemos, debo irme.}
{359}{}{¡Adiós!}
{360}{}{Lo único que me interesa son mis chapas.}
{361}{}{Ah, cierto... ¡Aquí las tienes! (se prepara para atacarte)}
{362}{}{¡Oye, esto no era parte del plan!}
{363}{}{¡Eres un asqueroso hijo de perra! ¡Traidor!}
{364}{}{Tengo una mejor idea. Te ayudaré... ¡Porque voy a silenciarte!}
{365}{}{¿¡Qué!? ¿¡Y qué hay de mis chapas!?}
{366}{}{La Iglesia del Fuego Santo necesita sangre nueva. ¡Pero tú no eres digno de ser un iniciado, gusano patético!}
{367}{}{No me quedaré de brazos cruzados mientras este culto de dementes se hace más fuerte. ¡Hora de morir!}  
{368}{}{¿Entonces nos convertiremos en hermanos en la fe?}
{1368}{}{¿Entonces nos convertiremos en hermanos en la fe?}
{369}{}{Algo me dice que realmente no eres de la Iglesia. Pero... esas habilidades médicas... Bueno, ahí nos vemos. Tengo que irme.}
{370}{}{Nos vemos... iniciado.}
