{100}{}{Ves a William Garth.}
{101}{}{Estás viendo a un Ranger veterano.}

{102}{}{Recuerda quién tiene el verdadero poder aquí.}
{103}{}{¿Y de quién es la sangre desparramada aquí, simplón?}
{104}{}{Si esto es alguna clase de truco, lo pagarás caro.}
{200}{}{¿Hmm? No creo haberte visto por aquí antes. Hola, esto es el Acueducto. ¿Qué te trae por aquí?}
{201}{}{Tengo asuntos de los que ocuparme por aquí.}
{202}{}{Lo que tú digas. Pero asegúrate de que tus "asuntos" no se conviertan en mis problemas.}
{203}{}{¿Y quién eres tú?}
{204}{}{Puede que no me reconozcas, también soy un Ranger. Me he unido hace poco.}
{1204}{}{Puede que no me reconozcas, también soy una Ranger. Me he unido hace poco.}
{205}{}{Enhorabuena, siéntete como en casa; por aquí, todos somos parte del mismo equipo.}
{206}{}{¿Y tú eres...?}
{207}{}{Mi asentamiento necesita la ayuda de los Rangers.}
{208}{}{Entonces habla con el comandante en el centro de información, está cerca de la presa. Aquí no hay nadie que pueda ayudarte.}
{209}{}{¿Cuál es tu papel por aquí?}
{210}{}{Soy William Garth, era el comandante de campo anterior, ya estoy retirado. Me retiré de la acción tras muchos años de servicio: los años pasan factura. Algunos me toman por el sheriff local, pero no es así. A veces el Cuartel General me recompensa por supervisar al Acueducto.}
{211}{}{Parece que tienes mucho tiempo libre, ¿te importa si te hago unas preguntas?}
{212}{}{Fue un gusto conocerte, pero tengo que irme.}
{220}{}{Pues, ¿qué pasa?}
{221}{}{Habla, no tengas miedo.}
{222}{}{Adelante.}
{223}{}{Soy todo oídos.}
{224}{}{¿Qué quieres saber?}
{229}{}{Hasta otro día, Ranger.}
{230}{}{He escuchado que por aquí un brote de una enfermedad.}
{231}{}{Algunos han tenido fiebre. Se están recuperando, pero aún no hemos identificado la causa.}
{232}{}{¿Cuáles son los síntomas?}
{233}{}{¿Por qué no hablas con ellos? Están en sus chozas.}
{234}{}{Comprendo, voy a investigar.}
{250}{}{Háblame acerca de este lugar.}
{251}{}{El Acueducto es el hogar de varias familias que solo quieren la paz. El río nos da pescado y agua, la base de los Rangers mantiene a raya a los peligros del yermo.}  
{252}{}{Gracias por la información.}
{253}{}{¿Puedo quedarme aquí una noche?}
{254}{}{No me opongo, mientras te comportes. Los demás tienen cuidado con los forasteros.}
{255}{}{¿Hay alguna oportunidad laboral por aquí?}
{256}{}{Lo dudo, pero podrías preguntarle a los demás.}
{257}{}{¿Qué es esa estructura que está cruzando la carretera? Me da curiosidad.}
{258}{}{Eso es un acueducto, es un río artificial fabricado por la gente del Viejo Mundo. Se extiende por cientos de millas a través de Arizona. Es impresionante, ¿no crees? Pero aléjate de ahí, no es seguro.}
{259}{}{¿Los rangers están de acuerdo con tener civiles tan cerca de la base?}
{260}{}{Tener un asentamiento así de cerca se siente un poco raro, pero el trabajo de los Rangers es proteger estas tierras y a todos dentro de ella.}  

#quest - missing residents
{300}{}{He escuchado rumores acerca de gente desaparecida.}
{301}{}{¿De quién lo escuchaste?}
{302}{}{Del refugiado junto a la fogata.}
{303}{}{Responde la pregunta.}
{304}{}{A veces pasan forasteros por aquí, iguales que tú, pero no se quedan. Eso está bien, luego se van. A veces los rangers encuentran sus cadáveres en el bosque, allí merodean lobos y coyotes en grandes números.}
{305}{}{Eres casi el sheriff de este lugar, ¿no te preocupa encontrar a los desaparecidos?}
{306}{}{Mi responsabilidad es el Acueducto, no lo que yace fuera de sus fronteras. Además, los desaparecidos eran forasteros, no eran lugareños. Si tanto quieres encontrarlos, Hazlo tú.}
{307}{}{De acuerdo, no hay problema. Nos vemos luego, Ranger.}
{308}{}{Eres un pésimo sheriff. Sí, lo voy a hacer yo.}
{310}{}{Hay cadáveres en el acueducto. Estás involucrado, ¿cierto?}
{311}{}{Carajo, le dije a Keel que te detuviera. ¿En dónde está ese idiota?}
{312}{}{Siento decirlo, pero parece que ya no es capaz de seguir tus ordenes.}
{313}{}{Lo intentó y falló. No me vas a intimidar, no podrás callarme.}
{314}{}{¿Quién te crees que eres para venir aquí e irrumpir nuestra paz? ¿Te enviaron los cultistas? ¿Eres de una banda y están planeando un asalto? Quizás solo vengas a robar nuestros pescados. Los forasteros como tú no hacen más que traerle problemas a este lugar. Sólo estoy haciendo mi trabajo - cuido al Acueducto de cualquier cosa que lo amenace.}  
{315}{}{No, sólo estás loco. Y hay que detenerte.}
{316}{}{Está bien, me voy, pero ni pienses en tocarme. O si no, le diré a todos.}
{317}{}{Créeme, estoy de tu lado. Si tu subordinado falló, puedo ayudarte.}
{318}{}{Entonces prueba tu lealtad a los Rangers - encárgate del último refugiado. No me importa lo que hagas - si es una bala o lo engañas de alguna manera. En este momento, es una amenaza para mí y los demás.}
{319}{}{De acuerdo, lo haré.}
{320}{}{No, esto es demasiado. Me encargaré de TI.}
{321}{}{¿Por qué? ¿Acaso no se ha derramado suficiente sangre?}
{322}{}{¿Siquiera sabes algo acerca de esta gente? Está claro que no. Llegaron desde lejos, uno de ellos portaba la marca de los Escudos Azules - una banda de saqueadores en el este. Puede que esté siendo paranoico, pero para MI, eso era suficiente para lidiar con ellos.}
{323}{}{Veamos si de verdad estás dispuesto, entonces.}
{324}{}{Comprendo.}
{325}{}{Eres nuevo en los Rangers, así que déjame explicártelo. El Acueducto es un lugar tranquilo - hay pescadores, recolectores y poco más. Si hay demasiados forasteros, podrían de nuestro hogar. Por aquí pasa gente de todo tipo - cultistas, saqueadores, ladrones. Sólo estoy haciendo mi trabajo, cuido al Acueducto de lo que sea que nos lance el yermo.}  
{1325}{}{Eres nueva en los Rangers, así que déjame explicártelo. El Acueducto es un lugar tranquilo - hay pescadores, recolectores y poco más. Si hay demasiados forasteros, podrían arruinar el balance de nuestro hogar. Por aquí pasa gente de todo tipo - cultistas, saqueadores, ladrones. Sólo estoy haciendo mi trabajo, cuido al Acueducto de lo que sea que nos lance el yermo.}
{330}{}{Me encargué del refugiado.}
{1330}{}{Me encargué del refugiado.}
{331}{}{Buen trabajo, eres mucho más eficaz que ese cobarde de Keel. Pienso que habrá una fructífera colaboración entre nosotros. Toma, llévate algo de munición. Que esto sea nuestro secreto, ¿bien?}
{332}{}{No hay problema, Garth. Te lo juro por mi mamá.}
{333}{}{Hay un... cadáver cerca del acueducto. Eh, puede que quieras ir a verlo.}
{334}{}{No otra vez. Muéstrame en dónde está.}
{335}{}{Es por aquí...}
