{100}{}{Ves a Henry.}
{101}{}{Estás viendo al intendente de los Rangers.}
{102}{}{¿Quién anda ahí? ¡Manos arriba! ¡Estoy armado!}

#First Dialogue
{200}{}{Por última vez, no, NO SÉ EN DÓNDE ESTÁ ESA PUT... Ah, perdona, pensé que estaba pasando el inspector otra vez.}
{201}{}{Eh, no, no soy el inspector.}
{202}{}{Lo dejaré pasar. Por ahora.}
{203}{}{Hmm, una cara nueva, no esperaba eso. Me llamo Henry, soy el intendente de este lugar. Ten en cuenta que tenemos reglas estrictas, así que síguelas si quieres estar aquí.}
{204}{}{¿Y ahora quieres decirme que hacer?}
{205}{}{Por supuesto, no hay problemas.}
{206}{}{Un momento, hace un rato habíamos hablado que hay un idiota que está metiéndose en las tumbas de los Rangers. ¿Tienes alguna idea de quién es?}
{207}{}{¿Yo? Claro que... no, señor.}
{208}{}{Que pena. Los Rangers van a recompensar con un rifle a quien sea que encuentre y duerma a ese bastardo. Ten eso en cuenta.}
{209}{}{Por supuesto, señor.}

#Re-Dialogue
{210}{}{¿Y qué te trae por aquí?}
{211}{}{Por ahora, nada.}
{212}{}{Basta de cháchara, hablemos en serio.}
{213}{}{Sigo sintiendo curiosidad por tu historia.}
{214}{}{Quiero comerciar.}

{220}{}{Me gustaría saber de ti.}
{221}{}{¿En serio te interesa mi vida?}
{222}{}{¿Cuál es tu papel aquí?}
{223}{}{Soy el intendente.}
{224}{}{¿Puedes comerciar con forasteros?}
{225}{}{Lo siento, pero al comandante no le gusta mucho que comerciemos con extraños. Las caravanas ya nos traen los suministros. Pero últimamente, el problema que hay en San Brahmán ha estado afectando el comercio.}
{226}{}{¿Qué está ocurriendo en San Brahmán?}
{227}{}{Allí hay pastores y hacemos trueques con ellos por cuero y carne. Pero se les avecinan problemas, no sé cómo acabaran las cosas.}
{228}{}{Tengo buenas conexiones, no te arrepentirás de hacer negocios conmigo.}
{229}{}{Ya veremos cómo termina eso.}
{230}{}{Gracias.}
{231}{}{Dudo que lo que ofrezcas valga la pena para los Rangers.}
{232}{}{Bueno, lo que tú digas...}
{233}{}{}
{234}{}{¿De dónde eres?}
{235}{}{Mi familia se mudaba mucho, vinimos del oeste.}
{236}{}{Háblame sobre el oeste.}
{237}{}{Si hablamos del sur de California, es un infierno comparado a este sitio. Hay ciudades en ruinas, suelo infértil y caníbales por todos lados. Hay más gente que en Arizona, eso sí.}
{238}{}{¿Cómo acabaste entre los Rangers?}
{239}{}{El Yermo me separó de mi familia, y los Rangers me salvaron el pellejo. Desde ese entonces que los estoy ayudando. Supongo que esta vida me viene como anillo al dedo.}

#Ranger
{250}{}{Parece que debo hablar contigo, ahora estoy entre los reclutas.}
{251}{}{Ya había oído que te iniciaron, Ranger. Es impresionante lo rápido que te ganaste eso.}
{252}{}{[Más]}
{253}{}{Bien, si necesitas algo, dímelo. Te voy a asignar una litera, pero cuidado con tu equipamiento. Aquí tienes tu armadura y una cantimplora para tus viajes. Y bien, ¿qué arma prefieres?}
{254}{}{[Un rifle de caza y munición]}
{255}{}{[Una pistola de bengalas, con... bengalas]}
{256}{}{[Diez cuchillos arrojadizos]}
{257}{}{Firma aquí. Pero ten en cuenta que si se te pierde algo, es cosa tuya.}
{258}{}{Gracias, cuidaré bien de mi equipamiento.}
{259}{}{Ya lo sé. Dame eso.}

{270}{}{Rufus dijo que tendrías una recompensa para mí.}
{271}{}{Sí, ha autorizado que te ofrezca algo. Elije lo que quieras de esta lista.}
{272}{}{En otro momento.}
{273}{}{[3 Estimulantes]}
{274}{}{[35 balas del calibre .44]}
{275}{}{[20 balas del calibre .308]}
{276}{}{[Armadura de cuero]}
{277}{}{}
{278}{}{Aquí tienes.}
{279}{}{Gracias.}

{280}{}{Voy a ir hacia Puerto, llevaré a cabo un reconocimiento del área...}
{281}{}{Buena suerte, los Rangers que están por allá se encuentran preocupados. Es un nuevo enemigo, y no será nada fácil derrotarlos.}
{282}{}{Comprendo.}
{283}{}{Vamos a difundir propaganda entre los asentamientos e incluso pagaremos por cada baja enemiga. Si traes pruebas, te llevas chapas.}
{284}{}{¿Qué clase de prueba necesitas?}
{285}{}{Cada uno de ellos tiene su chapa de identificación. Si las traes, te pagamos. Así de simple.}
{286}{}{Ya veo.}
{287}{}{Tengo una chapa de identificación de la Hermandad.}
{288}{}{Cada baja enemiga representa más libertad para Arizona. Esta es tu recompensa - 10 chapas por cada una.}
{289}{}{Algo es algo. Aquí tienes la chapa de identificación.}
{290}{}{Esto no es sobre el dinero, quédatelas.}
{291}{}{Cada baja enemiga le sube la moral a los Rangers. Gracias, te deseo suerte.}
{292}{}{Nos vemos luego.}
{293}{}{Espera, quiero preguntar otra cosa.}

#Quest for the loss
{300}{}{Sobre ese inspector que decías, ¿acaso se perdió algo?}
{301}{}{Sí... Según el inventario, debería haber una pistola Colt 6520 y una caja con su munición. Pero no están.}
{302}{}{Ah, ya entiendo. Ojalá lo resuelvas.}
{303}{}{Podría ser un error, ¿no?}
{304}{}{Lo dudo, no quiero ni pensar que fue robada por uno de nosotros. Pero no hay otra explicación.}
{305}{}{Puedo ayudarte a encontrarla. ¿Quién fue la última persona que la utilizó?}
{306}{}{Lo más probable es que la hayan perdido. Sólo debes buscarla.}
{307}{}{Por como están las cosas por aquí, es mejor que cuides bien tus bolsillos. Yo debería revisar mi equipamiento.}
{308}{}{Fue usada por cadetes de la Capitana Agatha durante su entrenamiento, después la regresaron. O eso dice el registro.}
{309}{}{Supongo que puedo hablar con ella y su grupo. Gracias.}
{310}{}{Puedo encargarme de eso. Pero recuerda que también eres un sospechoso.}
{311}{}{Acerca del arma que se perdió.}
{312}{}{¿Tienes alguna noticia?}
{313}{}{Todavía no, no tengo pistas.}
{314}{}{¿Podrías repetirme qué se perdió?}
{315}{}{Una pistola Colt 6520 y su munición. La usamos para entrenar, principalmente.}
{316}{}{Bien, seguiré buscando.}
{317}{}{¿Quiénes la usaron por última vez?}
{318}{}{El grupo de la Capitana Agatha. Se supone que la usaron para entrenar y la devolvieron. Se supone.}

{320}{}{He encontrado la pistola, los cadetes de la Capitana Agatha la habían usado para entrenar su puntería.}
{321}{}{¡Por fin! ¿En dónde la encontraste?}
{322}{}{Los cadetes la habían robado para practicar.}
{323}{}{Esos malditos cadetes... No se saldrán con la suya. Estas balas eran para los cadetes, pero te las has ganado. Gracias por ayudarme.}
{324}{}{Me alegra haberte ayudado.}
{1324}{}{Me alegra haberte ayudado.}
{325}{}{Esto no valió la pena.}
{326}{}{Se les había olvidado en el campo de tiro. Parece que hay un error en tu registro.}
{327}{}{Carajo, ahora tendré que hablar con el comandante. Pero, gracias por la ayuda. Se lo contaré a los demás, puede que te ayude a encajar con nosotros.}

#Relic
{350}{}{Encontré algo interesante, mira esta insignia.}
{351}{}{No es nuestra, eso es obvio. Pero parece ser real, es un buen hallazgo.}
{352}{}{Tu rostro cambió por completo. ¿Cuánto te importa esto?}
{353}{}{Las insignias como estas nos recuerdan nuestras raíces, nuestras tradiciones. Me importa mucho.}
{354}{}{¿Te interesa comprarla?}
{355}{}{Por supuesto, este tipo de cosas le suben la moral a los Rangers. Te daré algunas balas a cambio.}
{356}{}{Hmm, te daré la insignia por un cargador de munición de rifle.}
{357}{}{Dame la insignia. Aquí tienes tu munición.}
{358}{}{Fue un buen trato.}
{359}{}{Me vendría bien algo de munición de revólver.}
{360}{}{Bien, entonces dámela. Toma.}
{361}{}{Un buen trato.}
{362}{}{Necesito un calibre pequeño como el .22, me vendría bien.}
{363}{}{Tengo mucho, llévate un cargador entero.}
{364}{}{De acuerdo, aquí está la placa.}
{365}{}{Unas bengalas me servirán.}
{366}{}{Claro, unas bengalas por la insignia.}
{367}{}{Maravilloso.}
{368}{}{Te la regalo, no la necesito.}
{369}{}{¿De verdad? Pues, gracias. No olvidaré esto.}
{370}{}{De nada.}
{371}{}{¿Qué tal si me dejas pasar al campo de tiro por un rato? Me vendría bien practicar con armas pequeñas.}
{372}{}{Por supuesto. Tengo munición y armas justo para eso. Te deseo suerte con tu practica.}
{373}{}{Gracias...}
{374}{}{El intendente ha bajado sus precios por un 10%}
