{100}{}{Ves a un ranger.}
{101}{}{Ves a un ranger. Protege la entrada a la presa.}
#Pass Inside
{110}{}{Si quieres pasar, habla con Jack.}  
{111}{}{Jack decidirá si entras o no.}  
{112}{}{Habla con Jack si buscas entrar.}  
{113}{}{No tengo permiso para dejarte pasar.}  
{114}{}{Lárgate. No creo que estés aquí por las vistas.}  
{115}{}{Entra y deja de molestarme.}  
{116}{}{Tienes permiso de pasar, ¿qué más quieres?}  
{117}{}{No parecemos atracción turística, ¿verdad?}  
{118}{}{¿Quieres ver la presa? Entonces entra a verla.}  
{119}{}{No molestes a un guardia si está trabajando.}  

#Ranger Title
{120}{}{Ni siquiera pienses en distraerme, estoy trabajando.}  
{121}{}{¿Quieres un consejo? Sigue con tus asuntos y aprecia tu tiempo.}  
{122}{}{Los rangers podrían enseñarle a un novato como tú un par de cosas.}  
{123}{}{No nos importa la gente que se queda parada sin hacer nada.}  
{124}{}{Si te enlistas como cadete, el comandante te quitará esa sonrisa del rostro.}  
{125}{}{Enhorabuena, ahora eres un ranger.}  
{126}{}{Ya tienes la placa, pero el respeto te lo tienes que ganar.}  
{127}{}{Te estoy vigilando... aunque seas un ranger.}  
{128}{}{Mantén el orden allá afuera.}  
{129}{}{Ojalá que sientas responsabilidad con esa placa.}  

#Robe
{130}{}{¡Piérdete, maldito cultista!}  
{131}{}{Si llevaras esas túnicas, es mejor que te pintes una diana en la espalda.}  
{132}{}{He visto armaduras feas, pero tú te llevas el premio.}  
{133}{}{¿Quién te dejó robar las señales de tráfico?}  
{134}{}{Ese traje azul te hace resaltar, demasiado.}  
{135}{}{Tienes un sentido de la moda muy... peculiar.}  
{136}{}{¿Quién te dio esa armadura? ¡Habla!}  
{137}{}{Saludos, rang... Un momento, ¿¡quién eres!?}  
{138}{}{¿Por qué llevas puesto un montón de metal? ¡Tira esa cosa ahora! O... dámela...}  
{139}{}{A los cadetes les damos armaduras hechas de cuero de brahmán... A diferencia de... eso que llevas.}  

{1130}{}{¡Piérdete, maldita zorra cultista!}  
{1131}{}{¿Viniste aquí con esas túnicas? Lo estás pidiendo a gritos, nena.}  

#Reputation
{140}{}{Piérdete.}
{141}{}{No voy a hablar contigo.}
{142}{}{¿Tienes algo que decir?}
{143}{}{No deberías quedarte por mucho tiempo.}
{144}{}{Nuestras balas son símbolo de piedad.}
{145}{}{Hola.}
{146}{}{Si te importa tu reputación, no hagas nada estúpido.}
{147}{}{Me alegra verte.}
{148}{}{¿Cómo estás?}
{149}{}{Te deseo suerte.}
