{100}{}{Ves a un cartógrafo.}
{101}{}{Ves a un ranger de atuendo holgado con un voluminoso ocular atado a su cabeza. Parece ser que trabajar con poca luz ha dañado su visión.}

{200}{}{(Estás viendo a un ranger delgado; su uniforme es más grande que su cuerpo y lleva puesto un ocular de varios lentes sobre su ceja. Al darse cuenta de tu presencia, ajusta el lente y entrecierra los ojos, examinando tu rostro.) ¿Eh? ¿Quién te dejó pasar? Si no eres parte de los rangers, no puedes estar aquí.}
{201}{}{No te preocupes, tengo permiso.}
{202}{}{Yo.}

{210}{}{Hola, ¿qué tal?}
{211}{}{Ahí nos vemos.}
{212}{}{Retrocedamos un poco.}
{213}{}{Eh... ¿Hola?}

#Questions
{220}{}{¿Cuál es tu papel aquí?}
{221}{}{Me ocupo de crear mapas nuevos del yermo. Si me lo preguntas, es un trabajo tedioso y minucioso.}
{222}{}{¿Qué tienen de malo los mapas viejos?}
{223}{}{Porque están obsoletos. Es cierto que el relieve no ha cambiado mucho desde la Gran Guerra, pero hay ríos y lagos que se han secado, se han expandido las zonas radioactivas y han aparecido nuevos asentamientos. Hoy en día, los rangers y los caravaneros son los únicos que de verdad comprenden la geografía del área. Sin embargo, a menudo nuestras patrullas necesitan coordenadas precisas. Y nadie hace mapas nuevos... excepto yo.}
{224}{}{¿Qué detallan tus mapas?}
{225}{}{Todo lo que nos podría ser útil en el yermo: asentamientos, granjas, puestos de avanzada, zonas radioactivas, oasis. Casi toda la información cartográfica podría ser vital ante el centro de mando.}
{226}{}{¿Puedo echarle un vistazo a tus mapas?}
{227}{}{Únicamente si tienes la aprobación de un oficial de alto rango.}
{228}{}{Por supuesto. Entre los rangers, no nos guardamos secretos.}
{229}{}{¿Tienes alguna otra responsabilidad además de mapear?}
{230}{}{Me encargan todo lo que involucre leer y escribir.}
{231}{}{¿Por eso estás siempre con el ceño fruncido y los ojos entrecerrados?}
{232}{}{¿Bromeas? Llevo años estudiando mapas y textos con poca luz. Sin mi ocular, apenas puedo ver... Si alguna vez me sacan al yermo, te juro que sería mi último día con vida.}
{233}{}{¿Por qué no te has ido de aquí?}
{234}{}{A pesar de que el centro de mando esté en ruinas, eso no me absuelve de mi deber.}

- added below for mid-quest help in survey quest and map reward for same quest - cambragol
{235}{}{¿En dónde están los marcadores topográficos?}
{236}{}{Como dije, son un trípode de madera y chatarra, insertados en un neumático viejo.}
{237}{}{Entiendo, iré a buscarlos.}

{238}{}{Bien, entonces echemos un vistazo.}
{239}{}{Ojalá te sea de ayuda.}
{240}{}{Gracias, fue muy informativo.}

{241}{}{¿Cuántos marcadores hay?}
{242}{}{Hay cinco, necesitas leer los datos de cada uno.}




#Quartz
{250}{}{El Comandante Helford me ordenó que fuera a echar un vistazo en Quartz.}
{251}{}{¿Lo dices en serio? Al comandante se le están acabando los soldados... Hace tiempo que estoy insistiéndole para que realice mediciones geodésicas por allá.}
{252}{}{Pues, entonces no importa.}
{253}{}{¿Qué puedes contarme acerca de ese lugar?}
{254}{}{Son las ruinas de un viejo pueblo. (apunta en el mapa) Después de la Gran Guerra, se mantuvo gravemente irradiada durante años. Junto con el calor del desierto, ahuyentaba a cualquier colono o viajero que se acercara. Es sólo hace poco que los niveles radioactivos han bajado para que sea considerado seguro estar ahí. Es por eso que no le hemos prestado atención hasta ahora.}
{255}{}{Necesito más detalles al respecto de Quartz.}
{256}{}{Ya veo.}
{257}{}{¿Por qué Quartz era tan radioactivo?}
{258}{}{California fue gravemente atacada durante la Gran Guerra, por lo que las tormentas del oeste llevaron la ceniza radioactiva de las bombas nucleares hacia Quartz.}
{259}{}{¿Qué clase de peligros podría encontrar allá?}
{260}{}{Escorpiones, algo de radiación, edificios en ruinas... Es un lugar muy tranquilo, como puedes ver.}
{261}{}{Cuéntame más acerca de las medidas que debo tomar.}
{262}{}{Los niveles de radiación, las condiciones del medio ambiente, la vegetación... puede que sea mucho para una sola persona.}
{263}{}{Tengo un sensor de mapeo, está integrado en mi Pip-Boy.}
{264}{}{¡Impresionante! Entonces eres la persona adecuada para esto. Establecimos marcadores topográficos en los puntos más ideales. Están marcados con un neumático viejo, dentro tienen insertado un trípode de madera y chatarra. Lo único que debes hacer es acercarte a los marcadores y registrar los datos.}
{265}{}{Ya entendí. Volveré cuando haya terminado.}
{266}{}{Eso de mapear no es lo mío, pero necesito saber más sobre Quartz.}
{267}{}{¡Excelente! Le estarás haciendo un gran servicio a los rangers.}
{268}{}{De acuerdo, pero tengo más preguntas acerca de Quartz.}
{269}{}{Ahí nos vemos.}
{270}{}{Tengo las lecturas de Quartz.}
{271}{}{¡Esto es increíble! ¡Has traído más datos de los que esperaba! Esa dispositivo en tu brazo es una maravilla. Puedes leer mis mapas, es mi muestra de gratitud. Gracias.}
{272}{}{Me alegra haber sido de ayuda para los rangers.}
{1272}{}{Me alegra haber sido de ayuda para los rangers.}
{273}{}{Preferiría un poco de munición, pero supongo que mejorar mi reputación con ustedes basta.}
{274}{}{¿Para qué te molestas en mapear por allá?}
{275}{}{Quizás no sea necesario ahora, pero siempre vale la pena estar preparado. En esas ruinas podrían haber nidos de mutantes, o escondites de saqueadores. Además, Quartz es como la puerta hacia California. Puede que el desierto sea una gran barrera, pero es sólo cuestión de tiempo.}

{276}{}{Yo ir Quartz.}
{277}{}{Ah-ja.}
{278}{}{¿Qué necesitar tú?}
{279}{}{Mí tener Pipa-Boy.}
{280}{}{Oki-doki.}
{281}{}{¡Ayos!}
{282}{}{Mí acabar. [Muestra las lecturas de datos de Quartz]}
{283}{}{Gracias.}