{100}{}{Ves a un ranger.}
{101}{}{Ves a un ranger con equipamiento desértico. Te saluda con la mano.}
{102}{}{Sí, eso me vendría bien.}

# First Dialogue
{200}{}{¡Alto ahí, amigo! Raramente tenemos visitas, ¿te importaría decirme a qué vienes?}
{1200}{}{¡Alto ahí, señorita! Raramente tenemos visitas, ¿te importaría decirme a qué vienes?}
{201}{}{Estoy en una misión, me lo encargó el Capitán Helford.}
{202}{}{Eso tiene sentido, el capitán me ha dicho que está corto de personal. Pues, ten cuidado, este lugar es peligroso.}
{203}{}{El cartógrafo de los rangers me pidió que tomara unas medidas.}
{204}{}{Ya era hora. Pero ahora mismo es demasiado peligroso. Pero es demasiado peligroso como para realizar un mapeo.}
{205}{}{Sólo probando mi suerte, quizás haya algo bueno ahí.}
{206}{}{Así que eres un chatarrero, ¿no? Sí que te aventuraste al venir aquí. Pero créeme, estás en el lugar equivocado. Ya se llevaron todo lo valioso, y es peligroso estar aquí.}
{207}{}{No es asunto tuyo.}
{208}{}{Entiendo. Pero ten en cuenta que estas ruinas son peligrosas. Si te metes en problema, no esperes que corra a rescatarte.}
{209}{}{¿Qué la hace tan peligrosa?}
{210}{}{Hace un tiempo que subieron los niveles radioactivos. La población local se volvió loca y atacan a cualquiera que vean, así que ten cuidado. Estás avisado, ahora todo depende de ti.}
{211}{}{Gracias por decírmelo.}
{212}{}{Seguro que solo intentas asustarme. Hazte a un lado.}
{213}{}{Me las arreglaré. Adiós.}

# Repeat Dialogue
{220}{}{¿Sí?}
{221}{}{Adiós.}
{222}{}{Espera, tengo otra cosa que preguntar.}
{223}{}{Parece que era el último. Que en paz descansen.}

{230}{}{¿Queda algún superviviente?}
{231}{}{Estoy aquí en nombre del Capitán Helford. ¿Dónde está el campamento de los refugiados?}
{232}{}{Aquí se habían asentado unos refugiados de Fénix, pero ya no podemos llamarlos humanos. Se han vuelto locos, no pueden comunicarse y atacan a cualquiera que vean. Si ves a alguno, es mejor que los mates. Los sacará de su sufrimiento.}
{233}{}{¿Quiénes eran?}
{234}{}{Eran unos refugiados del este. Llegaron acá buscando una vida mejor, pero sólo encontraron el sufrimiento. Si los ves, acaba con su miseria.}
{235}{}{¿Cómo enloquecieron?}
{236}{}{No lo sé, pero sospecho que fue la radiación.}
{237}{}{La población local ya no es humana. Se han vuelto locos, no pueden comunicarse y atacan a cualquiera que vean. Casi todos se encuentran entre los remolques.}

{240}{}{¿Por qué hay radioactividad aquí?}
{241}{}{También me gustaría descubrir el por qué. Después de la Gran Guerra, habían altos niveles de radiación debido al viento que llegaba de California. Pero con el pasar del tiempo, los niveles bajaron. Y ahora volvieron a aumentar. Quizás encontraron algo que no debían.}

{250}{}{¿Quién eres?}
{251}{}{Soy un ranger. Mi trabajo es plantar avisos sobre la radiación, y si es posible, eliminar a la población local. Después de eso, volveré al este.}
{252}{}{¿Estás sólo?}
{253}{}{Sí. Han enviado a muchos rangers hacia el este, y sólo dejaron unas pocas patrullas en el área. De todas formas, aquí no vive mucha gente.}
{254}{}{Necesito un acompañante. ¿Podrías venir conmigo?}
{255}{}{Eso es demasiado peligroso. Llamaremos demasiado la atención.}
{256}{}{Sin tu ayuda, no saldré vivo de ahí.}
{257}{}{Yo también soy un ranger. Si vamos juntos, nada nos detendrá.}
{258}{}{No quiero proteger a alguien como tú.}
{259}{}{¿Gente como yo? No sabes nada acerca de mí.}
{260}{}{Si no eres capaz de hacerlo por tu cuenta, es mejor que te vayas.}
{261}{}{No, porque primero necesito respuestas.}
{262}{}{Eso es exactamente lo que haré. Adiós.}
{263}{}{(con escepticismo) De acuerdo... Pero hay radiación, no lo olvides.}
{264}{}{¡En marcha!}
{265}{}{Vamos.}


#Low Intelligence
{270}{}{¡Coo-coo!}
{271}{}{Pobrecito. ¿Ni siquiera sabes a dónde vas, cierto?}
{272}{}{¡Je!}
{273}{}{Aquí es muy peligroso. ¿Lo entiendes? ¡MUY PELIGROSO! Hay niveles fuertes de ra-di-a-ción y la gente está loca. ¿Me entendiste? ¿Sí? Bien, sal de aquí... Quedas advertido.}
{274}{}{Oki-doki.}
{275}{}{Ayos. Ayooos.}