{100}{}{Ves a un mecánico.}
{101}{}{Ves a un habitante del yermo.}
{102}{}{Oye, ¡cuidado! Estuviste a punto de atropellarme.}

#First dialogue
{200}{}{(ves a un joven, lleva un atuendo andrajoso y te observa con cansancio, claramente está molesto) ¿Qué quieres?}
{201}{}{¿No eres uno de los rangers?}
{202}{}{Claro que no. Los rangers me importan un carajo, pero son quiénes nos protegen, supongo. A cambio de eso, me ponen a trabajar.}
{203}{}{Dejaré que sigas.}

#Re-dialogue
{210}{}{¿Tú otra vez?}
{211}{}{Hasta luego.}
{212}{}{¿No puedes negarte a trabajar?}
{213}{}{No realmente. Si los rangers se enojan, nos cortarán los suministros y nos dejarán indefensos ante saqueadores y los mutantes. No tenemos otra opción, debemos hacer lo que nos pidan. Y Créeme, piden mucho.}
{214}{}{Háblame de tu asentamiento.}
{215}{}{Nos situamos en el Acueducto, en la costa del Colorado. Subsistimos gracias al pescado y a los animales que atrapamos. No hay mucho más que contar.}
{216}{}{¿Qué piensas de los rangers?}
{217}{}{Por cómo están las cosas, son nuestra única opción si queremos sobrevivir. Pero entre una crisis y otra, no hacen más que aprovecharse de nosotros, se llevan una parte de nuestro pescado y nos hacen trabajar en su beneficio.}
{218}{}{¿Sabes cómo se entra en su base?}
{219}{}{Ni idea. No es que te vayan a dar un recorrido del interior. Tendrás que hacerle un gran favor a los rangers o tener una razón muy, muy buena para que te dejen pasar.}
