{100}{}{Ves la computadora de los Rangers.}
{101}{}{Ves una terminal con acceso a la red pública.}

#Dialogue
{200}{}{Introducir comando:}
{201}{}{Cerrar sesión}
{202}{}{Regresar}
{203}{}{Conectar al servidor}
{204}{}{Se ha asegurado el acceso al servidor central.}
{205}{}{Excelente.}

{210}{}{Expedientes de los Rangers}
{211}{}{Selecciona una entrada.}

{212}{}{Chacales}
{213}{}{Los Chacales son una tribu de saqueadores caníbales en el yermo del Mojave. Se sabe poco sobre su historia y su vida cotidiana, ya que son extremadamente hostiles a los forasteros.}
{214}{}{[Más]}
{215}{}{Hay más de una docena de clanes, cada uno posee sus propias reglas y territorio. Todos practican el canibalismo.}
{216}{}{Nivel de amenaza actual}
{217}{}{El clan más grande de los Chacales está decayendo, mientras que los demás suponen amenazas menores o latentes.}
{218}{}{Existe una tregua entre los Rangers y los Chacales. Se le ha instruido a cada ranger que debe evitar los conflictos con la tribu a no ser sea absolutamente necesario.}
{219}{}{Los Chacales son una gran amenaza ante los viajeros entre el norte y el sur. Son caníbales habilidosos y astutos que presentan un peligro incluso ante un Ranger experimentado. El Consejo de Ancianos decretó que la tribu debe ser exterminada.}

{230}{}{La Villa}
{231}{}{Se trata de una comunidad agraria, practican la agricultura para subsistir y se encuentran aislados del mundo exterior. Evitan el contacto con los forasteros y se mantienen neutrales en asuntos externos.}
{232}{}{Nivel de amenaza actual}
{233}{}{Los campesinos de la Villa decidieron aliarse con el enemigo, pero difícilmente representan una amenaza por sí mismos. Debemos evitar conflictos con este asentamiento, pero es necesario dañar su relación con la Hermandad del Acero.}
{234}{}{Se ha establecido un pacto de asistencia mutua entre la Villa y los Rangers.}
{235}{}{Los campesinos de la Villa tienen un gran potencial para los Rangers, pero se han negado a un pacto con nosotros. Debemos mejorar nuestras relaciones con este asentamiento.}
{236}{}{Sabotaje en la Villa}
{237}{}{La Villa ha rechazado nuestra cooperación, pero no son una amenaza por sí mismos. Debemos evitar conflictos con este asentamiento y esforzarnos en desestabilizar cualquier alianza que formen con nuestros enemigos.}

{250}{}{La Amenaza Roja}
{251}{}{Los Seguidores del Fuego son un culto que venera la energía nuclear y la tecnología del Viejo Mundo.}
{252}{}{Nivel de amenaza actual}
{253}{}{El culto está en declive y bajo persecución religiosa. Se presume que su base principal fue destruida por una explosión nuclear subterránea. No sabemos de más detalles. Por ahora, sólo algunas facciones del culto representan una amenaza, actuando como parásitos en asentamientos amistosos o participando en el bandidaje.}
{254}{}{La secta está extendiendo rápidamente su influencia a toda la región, incluyendo al sur de Arizona y todo el desierto de Sonora. El Consejo de Ancianos los ha designado como una amenaza de prioridad absoluta.}
{255}{}{Operaciones en contra la Amenaza Roja}
{256}{}{Sabotaje en Flagstaff (suspendido), apoyo a la resistencia de San Brahmán, asistencia a los esclavos fugitivos en Two-Sun.}
{257}{}{Sabotaje en Flagstaff}
{258}{}{La colonia utiliza mano de obra esclava y es respaldada por la Iglesia del Fuego Santo. Se han suspendido temporalmente todas nuestras operaciones en Flagstaff.}
{259}{}{Apoyo a la resistencia en San Brahmán}
{260}{}{Una facción de Seguidores busca incitar una revolución en San Brahmán y así expandir su influencia. Nos vemos forzados a intervenir, se han despachado asesores hacia San Brahmán y así contrarrestar sus ambiciones imperiales.}
{261}{}{Espionaje en Fénix}
{262}{}{Se han despachado a varios Rangers hacia Fénix, operarán encubiertos para recolectar información. Su prioridad actual es establecer contacto con una guerrilla que se opone a la Iglesia del Fuego.}
{263}{}{Apoyo a los esclavos fugitivos en Two-Sun}
{264}{}{Two-Sun es controlada por un grupo que venera la tecnología y significan una amenaza para los asentamientos del área. Los Seguidores del Fuego colaboran con ellos para así obtener bienes y servicios. Debido a la lejanía de la ciudad, es difícil controlar la situación. Los esclavos fugitivos llevan a cabo sabotaje en Two-Sun, por lo que se despacharon espías para ayudarlos. }
{265}{}{El culto se encuentra en declive y bajo persecución. Su base principal fue destruida por fuerzas insurgentes urbanas. De momento, solo los grupos aislados de cultistas presentan una amenaza.}

{290}{}{Amenaza en el Sur}
{291}{}{Nuestros exploradores nos informan de la destrucción del fuerte de la Hermandad del Acero en el sur. ¡Esto pasará a la historia de Arizona como un día de libertad e independencia!}
{292}{}{La Hermandad del Acero es una organización cerrada de estatuto militar con ambiciones imperiales. Practican la esclavitud, obligan a otros asentamientos a cooperar, además de cometer otros crímenes, llevan a cabo invasiones militares. Por el momento, una gran parte del sur de Arizona es controlada por ellos a través de marionetas, esto incluye a Fénix. Como Rangers, es nuestro deber poner un alto a su expansión.}
{293}{}{Nuestros exploradores nos informan sobre una misteriosa organización en el sur. No sabemos lo suficiente para saber si representan una amenaza.}
