{100}{}{Ves al General Dixon.}
{101}{}{Ves al general en persona - es un guerrero increíblemente vanidoso y asertivo.}
{102}{}{No tengo ganas de hablar ahora mismo.}
{103}{}{¿?}
{104}{}{¿¡Qué demonios haces!? Toda servoarmadura es propiedad de la Hermandad del Acero. Entrégasela al intendente de inmediato.}
{105}{}{Gracias por ayudarnos contra los Rangers. Pero tengo mucho que hacer ahora, habla con alguien de abajo.}
{106}{}{Has renunciado a la placa ranger de forma oficial.}
{107}{}{Te has unido oficialmente a la Hermandad del Acero.}
{108}{}{[Probar Cabeza]}
{109}{}{[Sonreír]}
{110}{}{[Normal]}
{111}{}{[Grr]}
{112}{}{[Salir]}

#First dialogue
{200}{}{¿Un civil? ¿Qué estás haciendo aquí?}
{201}{}{Yo... eh...}
{202}{}{Estoy aquí para destruir la nave, idiota.}
{203}{}{¡Tenemos un intruso en la nave! ¡Suenen la alarma!}
{204}{}{Carajo...}
{205}{}{Eso no te ayudará en nada...}

{208}{}{Buena decisión, «compadre.». Pero aún con el consentimiento de tu comunidad, sigo teniendo un problema - los Rangers. Se creen los nobles guardianes del yermo, pero en realidad, son un montón de santurrones que nos impiden progresar al norte. Hemos estado vigilando sus posiciones alrededor de Fénix, y cuando estemos listos, vamos a encargarnos de esos bastardos de una vez por todas.}  
{209}{}{¿Pero qué carajo es esto? ¿Qué clase de idiota dejó pasar a un MUTANTE? Habla de una vez, maldito fenómeno, más te vale que tengas una buena razón para estar aquí.}
{210}{}{¿Pero qué demonios es esto? Eres un civil y te andas paseando por la nave así sin más... tendré que castigar a quien te haya dejado pasar... Pero bueno, ya estás aquí, así que habla. ¿Quién eres, y qué es lo que quieres de mí?}  
{211}{}{Estoy aquí para exterminar a tu ejército. ¡Muerte a los invasores!}
{212}{}{Permiso para partir, General.}
{213}{}{Tengo un informe de Ulysses Grant.}
{214}{}{Ah, por fin. Me han dicho que las noticias de Fénix me harán feliz. Pero te lo dejaré claro - si lo que me trajiste son trabajos a medias y excusas, no saldrás de aquí con vida.}  
{215}{}{Eso es cierto, General.}
{216}{}{Lo intentaré, General.}
{217}{}{Qué interesante. ¿Por qué Ulysses te escogió a ti? No le daría tal trabajo a un vagabundo en su día de suerte. No, él sólo confiaría en alguien con... conexiones importantes. Así que dime - ¿quién eres realmente, y qué tienes que ver con los cultistas en Fénix?}  
{218}{}{Es una larga historia, General. Soy de un pueblo en el norte. Seguro que nunca escuchó de él.}
{219}{}{¿Un pueblo? ¿Así que cosechan? ¿O cazan y recolectan?}
{220}{}{Trabajamos la tierra, mayormente cosechamos maíz. Pero hace poco, fuimos atacados por los esclavistas en Flagstaff...}
{221}{}{Ah, así que de eso se trata. Ya me habían hecho saber la falta de esclavos en la mina de uranio. Bueno, era inevitable. Eso es terriblemente injusto, hijo.}
{1221}{}{Ah, así que de eso se trata. Ya me habían hecho saber la falta de esclavos en la mina de uranio. Bueno, era inevitable. Eso es terriblemente injusto, señorita.}
{222}{}{Así es, General. Terriblemente injusto. Pero, usted estuvo relacionado en eso, ¿cierto?}
{223}{}{Me envía el Maestro Hard de Two-Sun. Aquí tengo su recomendación.}
{224}{}{Hard debe tener una muy buena razón para confiar en ti. He escuchado que Two-Sun está cambiando - tanto que incluso sus habitantes están nerviosos. Pero no responde mi pregunta: ¿quién demonios eres, y qué fue lo que hiciste para ganarte la confianza de los Hojalateros?}  
{1224}{}{Hard debe tener una muy buena razón para confiar en ti. He escuchado que Two-Sun está cambiando - tanto que incluso sus habitantes están nerviosos. Pero no responde mi pregunta: ¿quién demonios eres, y qué fue lo que hiciste para ganarte la confianza de los Hojalateros?}
{225}{}{Estoy aquí en nombre de los Rangers. Quieren que te detenga, pero me llama la atención saber qué planeas.}
{226}{}{Ja. ¿Así que te enviaron a espiarnos, no? Tienes huevos para venir y decírmelo a la cara. Así que habla - ¿qué te prometieron esos santurrones para que hicieras el trabajo por ellos?}  
{227}{}{Pues, me prometieron que mi pueblo natal sería libre y lo protegerían.}
{228}{}{Estoy aquí porque eres el responsable de lo que le pasó a mi hogar. Gracias a tu sed de uranio, Flagstaff asalta y esclaviza a pueblos como el mío.}
{229}{}{Exijo la libertad y la independencia de mi pueblo natal.}
{230}{}{Además, tras todas tus aventuras, ¿no te gustaría cambiar a tu pequeña y primitiva aldea? Seguramente buscas liberarla de sus tradiciones anticuadas, de tener protección ante los bandidos y tener la tecnología para cultivar sus granjas sin que requiera un diluvio de sangre y esfuerzo. ¿Verdad?} 
{231}{}{¿Es eso posible, General?}
{232}{}{Por supuesto, General. Ni hace falta decirlo.}
{233}{}{Sólo la Hermandad del Acero entiende lo que significa la justicia. Somos los únicos que seguimos aferrándonos a la sabiduría del Viejo Mundo - mientras que ustedes deambulan por las ruinas, intentando sobrevivir.}  
{234}{}{Creo que lo entiendo.}
{235}{}{¿Justicia? ¿En serio?}
{236}{}{Si tanto desea tu pueblo la libertad, entonces comprométanse con la Hermandad. Protegeremos a la Villa de sus enemigos y los equiparemos con tecnología. Lo único que pediremos es una parte de la cosecha. Con nosotros a sus espaldas, ni una sola alma en Arizona se atreverá a ponerles la mano encima.}  
{237}{}{Pero no sabemos casi nada acerca de tu Hermandad.}
{238}{}{Eso suena bien, General. ¿Pero qué clase de Hermandad es esta?}  
{239}{}{La Hermandad del Acero es una orden antigua. Heredamos todo lo que importó antes de que las bombas cayeran - el conocimiento, el poder, la tecnología. Mientras que el yermo sigue golpeándose a sí mismo, nosotros estábamos acumulando fuerzas y esperando el momento indicado para expandirnos y traer el cambio al yermo. Y ese momento ha llegado. Los escribas te contarán el resto, si los soportas.}  
{240}{}{}
{241}{}{Sólo pasaba por aquí y me preguntaba si tenía algún trabajo.}
{242}{}{No pierdo el tiempo con mercenarios. Para eso tenemos el puesto de afuera de la nave. Si no tienes nada que tratar conmigo, te recomiendo que te vayas de inmediato.}  
{243}{}{Lo siento, General...}
{244}{}{De acuerdo, me largo.}
{245}{}{¿Qué 'cambio' le traerás al yermo?}
{246}{}{Así que buscan expandirse... ¿para qué?}
{247}{}{El Yermo no necesita ser salvado - sino que lo corrijan. No tiene más opción que evolucionar, es por eso que estamos aquí para darle un empujón. No es porque queramos, sino porque nos necesita para avanzar. Déjame adivinar - en tu pueblo, siguen usando las manos para hacer casi todo el trabajo, ¿no es así?}  
{248}{}{[Asiente con la cabeza]}
{249}{}{Imagina lo siguiente - bombas de agua haciendo su trabajo, generadores dando electricidad a sus hogares, y herramientas que hacen la mitad del trabajo por ustedes. La medicina ayudará a los enfermos y las armas mantendrán a los saqueadores lejos de ustedes. Es el futuro que le podemos ofrecer a tu hogar. Sólo tienes que tomarlo, nada más.}  
{250}{}{No me engañas, no harás más que dominarnos y forzarnos a trabajar para el bien de la Hermandad y no para nosotros. Eso no es libertad.}
{251}{}{Me parece que estoy perdiendo el tiempo contigo. TUVISTE la oportunidad de hacer esto por las buenas. Tu pueblo nos dará comida y recursos - si es por la razón o la fuerza. Te ofrecí el camino fácil, pero prefieres tomar el difícil. Suelta tus armas, y levanta las manos.}  
{252}{}{No, eso deberías hacerlo tú...}
{253}{}{Vete a la mierda. No tienes el derecho de esclavizar a un pueblo libre.}
{254}{}{Suena... maravilloso. Estoy seguro de que podré convencer a mi gente de las ventajas de unirnos a ti.}
{255}{}{Buena decisión, amigo mío. Pero aún con el consentimiento de tu comunidad, sigo teniendo un problema - los Rangers. Se creen los nobles guardianes del yermo, pero en realidad, son un montón de santurrones que nos impiden progresar al norte. Hemos estado vigilando sus posiciones alrededor de Fénix, y cuando estemos listos, vamos a encargarnos de esos bastardos de una vez por todas.}  
{1255}{}{Buena decisión, amigA mío. Pero aún con el consentimiento de tu comunidad, sigo teniendo un problema - los Rangers. Se creen los nobles guardianes del yermo, pero en realidad, son un montón de santurrones que nos impiden progresar al norte. Hemos estado vigilando sus posiciones alrededor de Fénix, y cuando estemos listos, vamos a encargarnos de esos bastardos de una vez por todas.}
{256}{}{Entonces es necesario eliminarlos, porque están muy cerca de la Villa.}
{257}{}{Ah, me gusta como piensas - Sí, los Rangers están escondidos en la presa, creen que es impenetrable. Pero pasaron por alto un detalle: no necesitas nada más que una sola grieta para derribar una presa. Ve y explora el área. Cuando llegue el momento, nos ocuparemos de ellos.}  
{258}{}{¡De inmediato, General!}
{259}{}{}

{260}{}{Por fin estamos cara a cara, maldito salvaje. Sabía que vendrías tarde o temprano. Toda Arizona quiere arrancarte la cabeza.}  
{1260}{}{Por fin estamos cara a cara, perra asquerosa. Sabía que vendrías tarde o temprano. Toda Arizona quiere arrancarte la cabeza.}  
{261}{}{Por fin nos conocemos, maldito salvaje. Sabía que este día llegaría. Toda Arizona te tiene los ojos encima, como una jauría de perros hambrientos.}  
{1261}{}{Por fin nos conocemos, sucia puta. Sabía que este día llegaría. Toda Arizona te tiene los ojos encima, como una jauría de perros hambrientos.}  
{262}{}{¿Cómo sabes quién soy?}
{263}{}{Eres un estúpido. ¿En serio creíste que tus idioteces pasarían desapercibidas? Tenemos oídos en cada rincón del yermo. Si ocurre algo importante, lo sabremos.}  
{1263}{}{Eres una estúpida. ¿En serio creíste que tus idioteces pasarían desapercibidas? Tenemos oídos en cada rincón del yermo. Si ocurre algo importante, lo sabremos.}  
{264}{}{¿Qué piensa de mis 'idioteces', General?}
{265}{}{No me importa lo que pienses o hayas escuchado, estoy aquí para acabar contigo y tu supuesta 'hermandad'.}
{266}{}{Eres un campesino ignorante. ¿Tienes la menor idea de cuánto esfuerzo nos llevó crear la Iglesia del Fuego Santo en Fénix? Fue todo un esfuerzo ingrato, con el objetivo de sacar la ciudad - y la región - de la mugre. Y ahora todo ese plan se fue a la basura, gracias a un campesino sucio y estúpido. Es una maldita tragedia para Arizona y su futuro.}  
{267}{}{Continúa.}
{268}{}{¿Sabes todo el esfuerzo que nos tomó forjar una alianza con los Hojalateros? Tuvimos que hacer milagros para asegurar las rutas comerciales. Y ahora, gracias a tus sucias manos, Two-Sun desaparecerá por completo.}  
{269}{}{Continúa.}
{270}{}{La mina de Flagstaff significaba más de lo que podías imaginar - era la clave para el renacimiento de la civilización. El uranio genera electricidad, y la electricidad es la base para todo el progreso en Arizona. Sin ella, es imposible avanzar. ¿Tienes la menor idea de lo que hiciste?}  
{271}{}{Continúa.}
{272}{}{.....}
{273}{}{Continúa.}
{274}{}{Cuéntame, ¿exactamente qué intentas conseguir, hijo de perra?}  
{1274}{}{Cuéntame, ¿exactamente qué intentas conseguir, pequeña puta?} 
{275}{}{Gracias a tus planes y proyectos, mi familia y parientes tienen un futuro difícil e incierto por delante. Busco conseguir la libertad para mi Villa.}
{276}{}{Quizás - sólo quizás - podría haber tenido un poco de compasión contigo, haber llegado a un acuerdo. ¿Pero y toda nuestra labor de restaurar el orden social, económico y tecnológico en toda la región?  Toda la gran visión que planeamos se fue al caño, y todo por culpa de un sucio y estúpido campesino. Increíble.}  
{277}{}{Así es. No puedes quitarnos nuestra libertad. ¿Acaso no le gusta eso, General?}  
{278}{}{Estás cometiendo crímenes bajo la excusa de que es por el bien mayor. Ni siquiera nos preguntaste si queríamos ser parte de tu gran visión.}
{279}{}{Si la gente como tú hubiera liderado la política durante la preguerra, ¡El mundo no hubiera aguantado ni un sólo día!}
{280}{}{Tonterías. Yo no quiero ver el mundo arder. Pero gracias a tus acciones, Dixon, toda Arizona está ardiendo.}  
{281}{}{Puede que tenga razón al respecto, General.}
{282}{}{A pesar de tu estupidez, debo reconocer tus méritos. Nunca esperé que un paleto sería capaz de algo tan complicado. ¿Pero sabes qué? Estoy dispuesto a perdonarte.}
{1282}{}{A pesar de tu estupidez, debo reconocer tus méritos. Nunca esperé que un paleto sería capaz de algo tan complicado. ¿Pero sabes qué? Estoy dispuesto a perdonarte.}
{283}{}{¿En serio?}
{284}{}{Que 'noble' de tu parte.}
{285}{}{Tu pueblecito de rebeldes podrá ganarse nuestro perdón - y nuestra protección - en nombre de la Hermandad. Pero debes hacer tu parte. Para asegurarte ese futuro, debes librar a Arizona de nuestro adversario, los Rangers. Mis exploradores me informaron de que están escondidos en una central hidroeléctrica. Encuentra una forma de quitarla de la faz de la tierra.}  
{286}{}{Al carajo contigo. Los Rangers nos protegerán, y tú irás directo al infierno.}
{287}{}{Una pena. Entonces, por tus crímenes contra la humanidad, te sentencio a la pena de muerte por tus crímenes en nuestra contra. Prepárate, pedazo de mierda...}
{288}{}{Vete a la mierda.}
{289}{}{Pero no he cometido ningún crimen...}
{1289}{}{Pero no he cometido ningún crimen...}
{290}{}{Si lo dices en serio, lo haré.}
{291}{}{Como Paladín Supremo, te doy mi palabra. Andando.}
{292}{}{De acuerdo. Adiós.}
{293}{}{Es raro que lo consideres injusto si tomamos en cuenta que estás detrás de todo esto.}
{294}{}{¿De qué demonios hablas? Simplemente estamos comprando baterías nucleares - las que fabrican los Hojalateros de Two-Sun. Es cierto que Flagstaff les entrega el uranio, pero ese es su problema, no el nuestro. Por lo que sé, su líder se volvió un avaricioso. ¿Pero qué podemos hacer al respecto? Necesitamos... No. ¡Toda California y toda Arizona NECESITAN esas baterías!}  
{295}{}{Cierto. Pero eres *tú* el que permite que el negocio siga andando. Eso es un hecho.}
{296}{}{Hijo, no somos esclavistas. La Hermandad es una orden noble y antigua, nuestro propósito es mantener el orden en el yermo - porque ahora mismo, California es un maldito desastre. Se está llevando a cabo una guerra contra los supermutantes, si no detenemos eso, ellos llegarán a tu puerta. ¿Es eso lo que quieres?}  
{1296}{}{Señorita, no somos esclavistas. La Hermandad es una orden noble y antigua, nuestro propósito es mantener el orden en el yermo - porque ahora mismo, California es un maldito desastre. Se está llevando a cabo una guerra contra los supermutantes, si no detenemos eso, ellos llegarán a tu puerta. ¿Es eso lo que quieres?}  
{297}{}{Por supuesto que no.}
{298}{}{Suficiente, todo esto son mentiras. ¡Mi verdadero enemigo se encuentra en frente mío!}
{299}{}{}

#Re-dialogue
{300}{}{Habla.}
{301}{}{Permiso para irme, General.}
{302}{}{¿Qué demonios quieres, mutante?}
{303}{}{Tienes huevos para pasearte por acá, mutante asqueroso.}
{304}{}{Eres el único mutante al que voy a tolerar en la nave. ¿Qué quieres?}

{310}{}{Tengo un mensaje de parte de Ulysses Grant.}
{311}{}{Lo he esperado con ansias. Dámelo.}
{312}{}{Aquí tiene.}
{313}{}{El holodisco se estropeó mientras lo traía. Perdón, General.}
{314}{}{}
{315}{}{¿Por qué no te pones uno de esos gorros que dicen "Burro"? No me importa cómo lo hagas, ¡tráeme su mensaje, ahora!}  
{1315}{}{¿Por qué no te pones uno de esos gorros que dicen "Burra"? No me importa cómo lo hagas, ¡tráeme su mensaje, ahora!}  
{316}{}{Sí, General.}
{317}{}{Sólo bromeaba, general. Aquí lo tengo.}
{318}{}{¿Crees que es chistoso? Esto es un ejército, no un circo. Más te vale que ese informe no trate sobre ti. Entrégamelo.}  
{319}{}{Aquí tiene, General.}
{320}{}{No tan rápido, me prometieron que me pagarían el trabajo.}
{321}{}{Tu trabajo es seguir ordenes y cerrar la boca. Dámelo de una vez.}  
{322}{}{Ya veo... Hmm. Interesante. Y son buenas noticias. Ulysses mencionó lo que hiciste por el consejo. No es el tipo de persona que haga cumplidos. Debes ser útil.}  
{323}{}{Bueno, entonces ya acabamos. Tengo que irme.}
{324}{}{El viaje tuvo que haber sido difícil. No te preocupes, serás recompensando. Habla con el intendente.}
{325}{}{Gracias, General.}
{326}{}{Sólo por curiosidad - ¿qué dice el informe?}
{327}{}{No deberías meterte en donde no te llaman. Pero a juzgar por el informe, ya deberías saber casi todo.}
{328}{}{Supongo.}
{329}{}{Sólo hago mi trabajo. ¿Qué hay de mi recompensa?}
{330}{}{Sólo quieres chapas, ¿verdad? Es una pena que no aprecies el honor y la justicia. Pero eso está bien - cumples con tu trabajo, y aquí respetamos eso. Ve a hablar con el intendente y te recompensará.}  
{331}{}{Gracias, General.}

#Questions about BS
{350}{}{Háblame acerca de la Hermandad del Acero.}
{351}{}{Estás hablando con el jodido General. No tengo tiempo para hablar de eso.}
{352}{}{}
{353}{}{Está bien, se lo preguntaré a alguien más.}
{354}{}{¿Podría dejarme clara la misión de la Hermandad, General Dixon?}
{355}{}{Somos una organización cerrada de California de fuero militar y una larga historia.}
{356}{}{No parece que estén muy encerrados.}
{357}{}{Solíamos permanecer escondidos en un búnker bajo tierra, y sólo salíamos cuando era absolutamente necesario. Para que alguien entrara, se necesitaba ser un héroe excepcional. No nos metíamos en la política, sólo comerciábamos y manteníamos el orden donde podíamos.}
{358}{}{Sigue.}
{359}{}{Eso tuvo que haber sido aburridísimo.}
{360}{}{Luego de ciertos sucesos que seguro no conoces, los ancianos decidieron salir del búnker y explorar nuestros alrededores.}
{361}{}{Eso aclara un poco las cosas. Pero, tengo otras preguntas acerca de la Hermandad.}
{362}{}{Estás contento de haber salido de ahí, ¿verdad? La Hermandad necesitaba el aire fresco.}
{363}{}{Gracias por su tiempo. No molestaré más.}
{364}{}{¿Por qué se establecieron aquí?}
{365}{}{Este puerto es el lugar indicado para construir una fortaleza impenetrable. Y si hablamos del reactor de la nave, es la mejor máquina del yermo.}
{366}{}{Ya veo. ¿Puedo preguntar otra cosa acerca de la Hermandad?}

{367}{}{¿Por qué interfieres en los asuntos de la región?}
{368}{}{Necesitamos recursos. Y eso conlleva labor e infraestructura - y ninguna de las dos existe en estos lares. Así que debemos enseñarle a los locales cómo se hace un buen trabajo.}
{369}{}{¿Qué otras razones hay?}
{370}{}{Echa un vistazo a las tribus - se pelean por una trocito de carne y derraman su sangre por un sorbo de agua. Fénix es un ícono del progreso, pero está rodeado de asentamientos que se odian entre sí. Lo que Arizona necesita, es una mano fuerte que la levante y así recrear la civilización.}
{371}{}{[Más]}
{372}{}{¿Existe alguien capaz de hacer eso por aquí? Claro que no, por algo vinimos. Tenemos nuestros propios intereses, que son la tecnología y conocimiento. Pero dime, ¿de qué le servirá eso a un salvaje que no conoce su propósito?}
{373}{}{[Más]}
{374}{}{Arrastramos a estas tribus hacia el progreso aunque les duela. A cambio reciben conocimiento valioso: economía, la moneda, la medicina - y su primera escuela desde hace décadas. Arizona nos debe sus logros, quieran admitirlo o no.}
{375}{}{Dixon, ¿el cuartel general sabe de esto?}
{376}{}{Funciona con cierta independencia de las decisiones del cuartel. Me entregaron un 'amplio poder' para completar nuestra misión.}
{377}{}{Ya veo. ¿Podrías responderme otra pregunta?}

{380}{}{¿Cuáles son sus metas?}
{381}{}{¿Metas? Esa es la pregunta del millón. Nuestros escribas lo han debatido durante décadas. Algunos quieren reconstruir la civilización basándose en el Viejo Mundo. Hay otros que piensan que el mundo ya no merece tal cosa.}
{382}{}{[Más]}
{383}{}{Cuando llegamos a Arizona por primera vez, el cuartel no pensaba en influenciar las cosas por aquí. Se suponía que debíamos reabastecer las reservas nucleares y poner en marcha algunos talleres para ayudar en la guerra contra los mutantes. Pero... las cosas se complicaron.}
{384}{}{¿A qué te refieres?}
{385}{}{No puedes sacar una batería de la basura y esperar que vaya a funcionar. Necesitamos trabajadores, caravanas - incluso rutas postales. Creamos infraestructura y una economía de la nada. No existía nada de eso por aquí hasta que *nosotros* llegamos.}
{386}{}{Ya veo. ¿Me podrías responder otra duda?}
{387}{}{Háblame sobre California.}
{388}{}{California se encuentra devastada gracias a la guerra y el pasar del tiempo. Los Angeles está en ruinas, pero la civilización está renaciendo desde las cenizas.}

{400}{}{Necesito hablar contigo acerca de los Rangers.}
{401}{}{Esos bastardos siempre se meten en nuestro camino. ¿Encontraste alguna debilidad en sus defensas?}
{402}{}{No, señor. Están demasiado bien organizados.}
{403}{}{No puedo esperar mucho de un campesino, pero confío en que lo conseguirás. Cuéntame lo que descubras.}
{1403}{}{No puedo esperar mucho de una campesina, pero confío en que lo conseguirás. Cuéntame lo que descubras.}
{404}{}{Permiso para retirarme, General.}
{405}{}{¿Por qué son tus enemigos? Desean mantener la ley, igual que tú.}
{406}{}{Primero, nos ven como nada más que invasores y ponen a locales en nuestra contra, lo que pone en peligro nuestros planes. Segundo, buscan sabotear el progreso, atacando caravanas y campamentos laborales. Finalmente, controlan un amplio territorio y cobran impuestos a su población. ¿¡Quién demonios se creen!?}
{407}{}{Quizás tengan un punto.}
{408}{}{Esa descripción me resulta muy familiar.}
{409}{}{Ejem.. Nos impiden unir California y Arizona. Además, demostraron que son traidores durante la Batalla de Nogales, cuando intentaron sacarnos de ahí. Eso es más que suficiente.}
{410}{}{Tengo que irme, General.}
{411}{}{He conseguido destruir la presa de los Rangers.}
{412}{}{Me enteré de ello, es una gran hazaña. Gracias a tu ayuda, podremos echar a esos entrometidos de Arizona y podremos imponer el orden - igual que en los viejos días.}
{413}{}{¿Qué hay de nuestro acuerdo?}
{414}{}{Como lo prometí, la Villa se encuentra bajo la protección de la Hermandad. Enviaremos un embajador para formalizar la alianza.}
{415}{}{Son buenas noticias.}
{416}{}{Por tu destacado servicio a la Hermandad, te ofrezco algo que casi ningún civil ha conseguido nunca: ser parte de la Hermandad. Piénsatelo. Te lo has ganado. Puedes irte.}
{417}{}{Gracias, General Dixon.}

{420}{}{Quiero unirme a la Hermandad.}
{421}{}{Arrodíllate y dime tu nombre.}
{422}{}{Soy }
{423}{}{ de la Villa. Juro lealtad a la Hermandad del Acero.}
{424}{}{Elige tu especialización.}
{425}{}{Quiero ser escriba y cargar con la sabiduría del Viejo Mundo.}
{426}{}{Quiero ser paladín y traer la muerte a los enemigos de la Hermandad.}
{427}{}{Quiero ser caballero y difundir la luz de la tecnología.}
{428}{}{Quiero ser explorador, y viajar a donde sea más útil.}
{429}{}{Que así sea, }
{430}{}{. Desde hoy, eres miembro honorario de la Hermandad del Acero. No deshonres nuestro nombre, honra nuestras leyes y sé fiel a la orden, hasta la muerte.}
{431}{}{¡Juro lealtad!}
{432}{}{Sé que te prometí un rango, pero mis hermanos dudan acerca de ti. Debes probar lo que vales, una vez más.}
{433}{}{Carajo. Mi reputación es un problema...}
{434}{}{Convertirse en uno de nosotros requiere méritos excepcionales. Tus logros aún no están a esa altura.}
{435}{}{Lo haré lo mejor que pueda.}
{436}{}{Comprendo. Se enterará de mis hazañas, General.}
{437}{}{Tu servicio ante la Hermandad no tiene precio. Estoy preparado para darte la bienvenida en nuestra orden.}
{438}{}{[Más]}
{439}{}{Lo lamento, pero no podemos tener a un mutante entre nosotros, por mucho mérito que tenga. Permitiré que subas a la nave, pero nada más. Reglas son reglas.}
{1439}{}{Lo lamento, pero no podemos tener a una mutante entre nosotros, por mucho mérito que tenga. Permitiré que subas a la nave, pero nada más. Reglas son reglas.}
{440}{}{Eso está bien, no importa, General. Cuídese.}
{441}{}{Al cabo que ni quería. Adiós.}
{1441}{}{Al cabo que ni quería. Adiós.}