{100}{}{Ves al Paladí­n Dobbs.}
{101}{}{Ves a un hombre fuerte y desafeitado.}
{102}{}{Cuídate la espalda, novato.}
{103}{}{Regresa a la base y habla con el Paladín Latham. Puedes retirarte.}
{104}{}{Luchar junto a ti fue un honor.}
{105}{}{¡Irás directo al tribunal!}

{200}{}{¿Cuánto tiempo tengo que esperarte, soldado? ¡Te pagamos por trabajar, no por flojear!}
{201}{}{¡Perdón, señor! ¡Pero tengo que ir a vaciar el tanque, señor! ¡Ya vuelvo!}
{202}{}{La gente de este estado es tan floja... ¡Tienes cinco minutos!}
{203}{}{¡Señor, sí señor!}
{204}{}{Estoy aquí para servirle, señor. Esperando órdenes.}
{1204}{}{Estoy aquí para servirle, señor. Esperando órdenes.}
{205}{}{¡Escuchen, todos! El campamento enemigo está más adelante. Nuestro objetivo principal es liberar al caravanero secuestrado, lo necesitamos vivo. Neutralicen a los saqueadores sea como sea. ¿Alguna pregunta? ¿No? ¡En marcha!}
{206}{}{Señor, sí señor.}
{207}{}{Ya es hora, cadetes. Tenemos algo serio entre manos - el fuerte enemigo está bien fortificado y lo más seguro es que nos hayan tendido trampas por el perímetro. Mantengan los ojos bien abiertos y cuídense las espaldas una vez que lleguemos a las ruinas. Nuestro objetivo es recolectar información: encontrar dónde se encuentra su base principal. Tras encargarnos de eso, quemaremos el campamento entero. ¿Entendido? ¿Ninguna pregunta? Bien. ¡En marcha!}  
{208}{}{Soldados, este es nuestro día - ¡hoy haremos historia! Estos despreciables se han escondido por demasiado tiempo, pero por fin localizamos su base. ¡Es la hora de librar al yermo de la presencia de estos bastardos! Manténganse alertas, no pierdan la compostura, y destrúyanlos. ¡A la carga, hermanos! ¡Por la gloria de la Hermandad, por el futuro que nos espera!}  
{209}{}{¡Por la Hermandad!}
{210}{}{...Espera. Tú tienes un objetivo aparte. Encuentra el cargamento que robaron de la caravana.}
{211}{}{Llegaste justo a tiempo.}
{212}{}{Te estábamos esperando.}

{220}{}{Habla.}
{221}{}{¿Encontraste algo?}
{222}{}{¿De qué se trata, recluta?}
{223}{}{Ya voy, señor.}
{224}{}{[TRAMPA: He terminado la misión.]}
{225}{}{Entonces regresa a la base y habla con el Paladín Latham. Ten cuidado.}
{226}{}{Me pondré con ello, señor.}

{230}{}{Necesito apoyo, señor. Síganme...}
{231}{}{Iré por mi cuenta para evitar a los guardias. Esperen a mi señal.}
{1231}{}{Iré por mi cuenta para evitar a los guardias. Esperen a mi señal.}
{232}{}{¡Alto ahí, novato! ¿Cómo te atreves a abandonar el área sin permiso? ¿Siquiera terminaste la misión? ¡Explícate!}
{1232}{}{¡Alto ahí, novata! ¿Cómo te atreves a abandonar el área sin permiso? ¿Siquiera terminaste la misión? ¡Explícate!}
{233}{}{Es que, yo... He fallado la misión. Lo siento, señor...}
{1233}{}{Es que, yo... He fallado la misión. Lo siento, señor...}
{234}{}{Un desertor, ¿eh? Jamás vuelvas a poner un pie en la base, a no ser que quieras ir a la corte. ¡Sal de mi vista!}
{1234}{}{Un desertor, ¿eh? Jamás vuelvas a poner un pie en la base, a no ser que quieras ir a la corte. ¡Sal de mi vista!}
{235}{}{Sí, señor...}
{236}{}{No me importa.}

{240}{}{Recuérdame lo que debo hacer..}
{241}{}{¡Debes prestarme más atención, novato! Encuentra al rehén y llévalo a un lugar seguro - al punto de evacuación. Esa es tu misión, nosotros nos ocuparemos del resto.}
{242}{}{Averigua en dónde se ubica su base principal. Encuentra un mapa, o agarra a alguien y sácale la sopa a golpes. ¡Ya muévete, soldado!}
{243}{}{Localiza el cargamento de la caravana, entre lo robado, deberías encontrar una valiosa reliquia de la preguerra. La necesitamos en la base. No es necesario que participes en la batalla, ¿entendido? Buena suerte, soldado.}
{244}{}{De acuerdo.}
{245}{}{El rehén se encuentra a salvo.}
{246}{}{Perfecto. Perder una caravana tan valiosa sería una desgracia.}
{247}{}{Gracias, señor.}
{1247}{}{Gracias, señor.}
{248}{}{El rehén ha muerto. Lo siento, señor.}
{249}{}{¿Murió? Mierda... Suficiente, no tengan piedad con ellos.}
{250}{}{Sí, señor...}
{251}{}{He descubierto la ubicación de la base.}
{252}{}{Bien hecho, recluta. Por eso estábamos aquí en primer lugar.}
{253}{}{He recuperado la reliquia, aquí tiene, señor Dobbs.}
{254}{}{¡Bien hecho, hermano!}
{1254}{}{¡Bien hecho, hermana!}
