{100}{}{Ves a un doctor.}
{101}{}{Ves a un doctor, si no fuera por su bata, no podrías diferenciarlo de los demás soldados.}
{102}{}{Si no me apresuro, no necesitaré la ayuda del doctor.}
{103}{}{¿?}

{200}{}{(se frota las manos, mientras te observa con recelo) ¿Eres un civil? No recuerdo que tengamos nuevos reclutas.}
{201}{}{Así es, no soy parte de la Hermandad.}
{202}{}{Estás en la enfermería, no tengo permitido ayudar a un civil sin la autorización necesaria.}
{203}{}{Perdona las molestias.}
{204}{}{Entonces me voy.}
{205}{}{Eres el nuevo recluta, ¿verdad?}
{206}{}{Sí, soy yo. Creo que deberías poder ayudarme.}
{207}{}{Así es. Si no fuera así, te tendría que tirar por la borda. No puedo tratar a los civiles.}
{208}{}{Sólo necesito atención médica.}
{209}{}{No importa, ya me iba.}

{210}{}{¿Pasó algo?}
{211}{}{Nada. Hasta luego, doctor.}
{212}{}{¿Qué necesitas?}

{213}{}{¿Puedo hacerte unas preguntas?}
{214}{}{No es necesario. Ser un médico me enseñó a mantener la boca cerrada. A no ser que me esté hablando un oficial, por supuesto. Ellos deben enterarse de todo.}
{215}{}{De acuerdo, doctor. Entonces molestaré a alguien más.}

{220}{}{Quiero hablarte al respecto del Iniciado Corwin.}
{221}{}{¿Qué le pasó ahora? ¿Se volvió a meter en problemas?}
{222}{}{Quiere un permiso para bajar a tierra.}
{223}{}{¿De nuevo? Ese tipo es demasiado débil para esto, traerlo con nosotros fue un error. Debería haberse quedado en la base, limpiando las armas. Pero, ¿qué tengo que ver yo?}
{224}{}{No lo sé. Creo que nada, sólo preguntaba. Adiós.}
{225}{}{Pensaba en que podrías darlo de baja por unos días, por cuestiones de salud.}
{226}{}{Podría hacerlo, ¿pero por qué debería?}
{227}{}{No tienes razón para hacerlo, supongo. Perdón, adiós.}
{228}{}{Pues, quizás pueda conseguirte algunos suministros médicos. Sé que debe faltarte alguna cosa.}
{229}{}{Me parece bien. Tráeme cinco estimulantes o una droga militar, y le daré un descanso a tu amiguito.}
{230}{}{Lo pensaré.}
{231}{}{Aquí tengo los cinco estimulantes.}
{232}{}{Tengo un poco de Psico.}
{233}{}{Tengo unos Esteroides.}
{234}{}{Eso me basta. Trato hecho.}
{235}{}{Se lo contaré al Iniciado.}

{240}{}{Oye, Doc. ¿Sabías que me uní al escuadrón de exploradores?}
{241}{}{¿Otro explorador? Genial... Más trabajo. Felicitaciones.}
{242}{}{¿Qué tiene de malo ser un explorador?}
{243}{}{Los exploradores se llevan la peor parte -- radiación, envenenamiento, lo que se te ocurra. Ustedes consumen los medicamentos más rápido que nadie y siempre necesitan más, pero son escasos, especialmente el Rad-X.}
{244}{}{Entonces, ¿me darás algunos medicamentos?}
{245}{}{Sí, un kit de supervivencia: RadAway, Rad-X, un antídoto, y unos estimulantes. Úsalos sabiamente, o mejor aún, ten cuidado y no los uses.}
{246}{}{Comprendo. Gracias, Doc.}

{250}{}{Doctor, necesito su ayuda.}
{251}{}{No puedo tratar a un civil sin la autorización necesaria. Apenas tenemos suficientes estimulantes para nuestros hombres. Prueba a hablar con los Seguidores del Apocalipsis en Casa Nueva. Estarán felices de ayudarte.}
{252}{}{Gracias por el consejo, intentaré no desangrarme en el camino.}
{253}{}{Tenemos que hablar de otra cosa.}
{254}{}{Cúrame, doctor.}
{255}{}{Estás bien, ahora ve por tu rifle y vuelve a la batalla.}
{256}{}{¡Tú sí sabes, doc!}
{257}{}{Ya te lo dije, no te trataré gratis.}
{258}{}{[Salir]}

{260}{}{¿Quién grita tanto? ¿A quién torturas?}
{261}{}{No es eso, es uno de nuestros soldados. Perdió la cabeza, es muy grave.}
{262}{}{¿Qué le pasa?}
{263}{}{Dolores de cabeza, insomnio, escucha voces... No puedo contarte más, eres un civil. Pero es un caso difícil.}
{264}{}{¿Crees que esté fingiendo?}
{265}{}{Dudo que un soldado de la Hermandad haga eso, pero es posible. Todos añoran regresar a California.}
{266}{}{Si no puedes ayudarlo, déjame que lo intente.}
{267}{}{Normalmente no me tomaría bien lo que acabas de decir. Pero esto me supera, no soy psicólogo.}
{268}{}{Déjame hablar con él. Solo necesito cinco minutos.}
{269}{}{¿Estás seguro de que no está fingiendo?}
{270}{}{¿Qué le ocurre, exactamente?}
{271}{}{Creo que tú lo ayudarás mejor que yo. Te deseo suerte, doctor.}
{272}{}{Parece ser que Bell tiene un trauma psicológico muy grave.}
{273}{}{Eso pensé. ¿Pero cuál será la causa?}
{274}{}{Mencionó un yermo hecho de cenizas. ¿Qué significará eso?}
{275}{}{No tengo idea. Pero él empeoró luego de una misión en el desierto. Habla con sus compañeros en las salas de abajo - quizás sepan más.}
{276}{}{Me parece bien, gracias.}
{277}{}{Después de que hablaste con Bell, se calmó y durmió bien. ¿Qué le dijiste?}
{1277}{}{Después de que hablaste con Bell, se calmó y durmió bien. ¿Qué le dijiste?}
{278}{}{Sólo un poco de terapia a la vieja usanza.}
{279}{}{Interesante. Ojalá fuera mejor en eso. Yo soy mejor con los cortes y los moretones - meterme en la mente humana es demasiado terrorífico.}
{280}{}{No pierda la esperanza, Doctor.}
{281}{}{Es lo que mejor sabes hacer, quédate así.}
{282}{}{Gracias. Más aún por haber ayudado a mi paciente. Quiero darte algo; es un kit quirúrgico y un par de estimulantes. Sé que les darás un buen uso.}
{283}{}{Gracias, Doctor. Cuídese.}

{290}{}{[Curar todas las heridas por }
{291}{}{ chapas]}
{292}{}{[Curar todos los miembros rotos por }
{293}{}{[Curar toda la radiación por }
{294}{}{[Curar todo el veneno por }
