{100}{}{Ves al Paladín Latham.}
{101}{}{Ves a un hombre fuerte y barbudo.}
{102}{}{No puedo hablar ahora, lo siento.}
{103}{}{¿?}

{200}{}{Alto, esto es un área restringida, no permitimos civiles.}
{201}{}{¿Civiles? ¿Acaso son un ejército?}
{202}{}{No exactamente. Somos la Hermandad del Acero, una antigua orden militar. Así que debemos mantenernos disciplinados.}
{203}{}{Ya veo. ¿Y tú eres?}
{204}{}{Eso es sorprenderte, ¿y con quién tengo el honor de estar hablando?}
{205}{}{Soy el Paladín Latham, el Jefe de Patrullas. ¿Tienes otra pregunta?}
{206}{}{No, señor.}
{207}{}{Sí, tengo muchas preguntas, pero dudo que las respondas.}
{208}{}{No exactamente. Somos la Hermandad del Acero, una antigua orden militar. Por lo tanto, mantenemos una disciplina militar estricta.}
{209}{}{Puede que sean lo que estoy buscando. Vengo de una aldea al norte de aquí, últimamente hemos tenido problemas y buscamos... Protectores.}  
{210}{}{Puede que sean lo que estoy buscando. La mayoría de mi aldea fue capturada por esclavistas e intento liberarlos...}
{211}{}{Lo lamento, pero no puedo molestar al general con los asuntos de un pueblo. No tenemos tiempo para eso.}
{212}{}{Creo que no me entendiste. Ustedes son los culpables. ¡Y estoy aquí para liberarlos y acabar con ustedes!}
{213}{}{¿Por qué? ¿Acaso hay un problema?}
{214}{}{Entonces no me ayudarás. ¿Puedo irme?}
{215}{}{¿Tú otra vez? Ya te lo dije, no podemos ayudarte. Tenemos problemas más importantes.}
{216}{}{Tenemos un ejército enemigo en el sur, mutantes en el oeste y caos en el este. Perdimos un escuadrón en el norte y ni siquiera podemos enviar una misión de rescate.}
{217}{}{¿Y si rescato al escuadrón? ¿Me dejarás ver al general si cumplo con eso?}
{218}{}{¿Nos quieres ayudar? ¿Un campesino ayudando a la Hermandad? ¡Jajaja! ¿Escucharon eso, muchachos? Muy bien, veamos de qué eres capaz.}
{1218}{}{¿Nos quieres ayudar? ¿Una campesina ayudando a la Hermandad? ¡Jajaja! ¿Escucharon eso, muchachos? Muy bien, veamos de qué eres capaz.}
{219}{}{¿Qué le pasó al escuadrón?}
{220}{}{En el noroeste yacen unas ruinas a las que llamamos el Infierno. Nuestro escuadrón lideraba una caravana y pasaron por la cercanía, pero de repente perdimos el contacto con ellos. No sé qué habrá ocurrido.}
{221}{}{Ya veo. ¿Algo más?}
{222}{}{No. Debes dirigirte hacia allá y descubrir qué ocurrió. Pero ten cuidado, los escribas nos han dicho que la radiación es alta alrededor del Infierno.}
{223}{}{Comprendo. Lo haré.}
{224}{}{Me pongo en marcha, pero volveré, paladín.}
{225}{}{Otro mutante más... ¿cuándo acabará esto?}
{226}{}{Oye, no te haré nada.}
{227}{}{No creo que vivas para ver ese día, normalucho.}

{230}{}{Bien, ¿qué necesitas?}
{231}{}{Nada. Adiós.}
{232}{}{¿Qué necesitas, Explorador? }
{233}{}{¿Qué necesitas, Paladín }
{234}{}{¿Qué necesitas, Caballero }
{235}{}{¿Qué necesitas, Escriba }
{236}{}{?}
{237}{}{¿Qué necesitas, Iniciado }
{1237}{}{¿Qué necesitas, Iniciada }

{240}{}{Necesito saber más acerca del Infierno.}
{241}{}{No hay mucho que decir, los escribas nos han dicho que es una zona muerta, gracias a una explosión nuclear. También mencionaron que es radioactivo.}
{242}{}{¿Qué hay de la caravana?}
{243}{}{Varios miembros de la Hermandad llevaban un importante cargamento de California. Hace mucho que deberían de haber llegado.}
{244}{}{Gracias, escuché suficiente.}
{245}{}{Supongo que eso me bastará.}
{246}{}{Tengo más preguntas que hacerle, Paladín.}
{247}{}{He descubierto lo que ocurrió en el Infierno...}
{248}{}{...Entonces lo que dijeron los escribas es cierto - el lugar está maldito. Debes hablar con nuestro general.}
{249}{}{¿El general?}
{250}{}{Sé que le interesará tu historia. Le diré a los guardias que te dejen pasar.}
{251}{}{Genial.}
{252}{}{Por fin.}
{253}{}{Espera un segundo. ¿En dónde conseguiste esa servoarmadura?}
{254}{}{En una pesadilla. Habían cadáveres en las calles, Segadores que se comían entre sí, escombros por todos lados...}
{255}{}{Suena a que estuviste en el Infierno, nuestra caravana desapareció por allá. ¿Había alguien dentro de la servoarmadura? ¿Estaba muerto?}
{256}{}{Te diré lo que descubrí...}
{257}{}{No tengo que decirte nada. Ahora es mía, y me la quedaré.}
{258}{}{Cuéntame más sobre el escuadrón perdido.}

{260}{}{¿Hay algo más que pueda hacer por la Hermandad?}
{261}{}{Me hablaste sobre un ejército enemigo.}
{262}{}{Sí, hemos visto sus patrullas moverse desde el sur hacia la frontera mexicana. No sabemos mucho de ellos, incluso desconocemos en dónde está su cuartel general.}
{263}{}{Pero en el sur no hay nada más que desierto. ¿En podría estar su base?}
{264}{}{No lo sabemos. Pero el desierto actúa como una barrera natural, los mantiene alejados de Arizona. Por ahora.}
{265}{}{Ojalá que puedan detenerlos. Adiós.}
{266}{}{Yo puedo ir a investigar. Siempre quise explorar por allá.}
{267}{}{Puedo explorar el territorio sureño, si eso ayuda.}
{268}{}{Hemos enviado exploradores hacia el sur, pero nunca regresaron. ¿De verdad quieres hacerlo? Entonces adelante. Si adquieres información de los planes del Ejército Mexicano, te pagaremos.}
{269}{}{Entonces te haré saber si descubro algo.}
{270}{}{El Ejército Mexicano estableció un fuerte en Hermosillo.}
{271}{}{¡Buen trabajo! Esto nos ayudará si deciden atacarnos.}
{272}{}{Hermosillo está muy lejos, dudo que lleguen pronto.}
{273}{}{No sé por qué quieras eso, me interesa la paga.}
{274}{}{Aquí tienes, siempre apreciaremos saber qué piensa el enemigo.}
{275}{}{Gracias.}
{276}{}{Ese tipo al que ayudaste se encontraba en mal estado. ¿Qué le pasó?}
{277}{}{Pancho me dijo que necesitarían información acerca del Ejército Mexicano.}
{278}{}{¿Registraste el lugar? ¿Qué descubriste?}
{1278}{}{¿Registraste el lugar? ¿Qué descubriste?}
{279}{}{Nada útil. Si vuelvo allá, buscaré información que traerte.}

{280}{}{Necesito que me hagas un favor. Llévate al Iniciado Corwin la siguiente vez que vayas a patrullar.}
{281}{}{¿Corwin? ¿Y por qué no viene a decírmelo él?}
{282}{}{Hace un buen tiempo que quiere salir del barco.}
{283}{}{Mira, esto es lo que pasa. Primero, no necesitamos a un inútil en la patrulla. Segundo, no me convencen las palabras de un vagabundo como tú.}
{1283}{}{Mira, esto es lo que pasa. Primero, no necesitamos a unA inútil en la patrulla. Segundo, no me convencen las palabras de una vagabunda como tú.}
{284}{}{¿Vagabundo? Bueno...}
{1284}{}{¿Vagabunda? Bueno...}
{285}{}{Mira, esto es lo que pasa. Primero, no necesitamos a un flojo en la patrulla. Segundo, tu autoridad no vale nada. No te conozco lo suficiente como para hacerte el favor.}
{286}{}{Lo entiendo...}
{287}{}{Mira, sólo le cumplo favores a los que demostraron que valen la pena. Así que dile a Corwin que lo llevaré de ida y vuelta en la patrulla hacia Casa Nueva. No es un permiso para bajar a tierra, pero le dejará disfrutar del aire fresco.}
{288}{}{Gracias, Latham. Has sido muy útil.}
{289}{}{Tengo el holodisco del cuartel general de Hermosillo.}

{300}{}{¿Qué es lo que haces, exactamente?}
{301}{}{Somos patrullas. Mantenemos el orden en los alrededores. ¿Tienes otra pregunta?}
{302}{}{No, señor}
{303}{}{Sí, unas cuantas.}
{304}{}{Eso lo entiendo, pero alrededor sólo hay desierto. ¿Qué orden vas a mantener allá afuera?}
{305}{}{Lo principal es proteger las rutas de las caravanas. También protegemos algunos poblados pesqueros en la costa. Y Casa Nueva nos pide ayuda, a veces. Además, incluso por aquí hay saqueadores. Así que nunca debemos bajar la guardia.}
{306}{}{Ya veo.}
{307}{}{Eso suena interesante. ¿Puedo ir contigo?}
{308}{}{Es arriesgado llevar a un desconocido a patrullar, aunque tengas buenas intenciones.}
{309}{}{De acuerdo. Quizás cambies de opinión si te demuestro que soy de confianza.}
{310}{}{Puede que necesites ayuda, tú mismo has dicho que te falta personal.}
{311}{}{Eso es cierto, pero no pareces alguien que tenga experiencia. Baja tus expectativas.}
{312}{}{Sí, pero... o bueno... Es cierto, no tenemos suficientes soldados para una operación que tenemos planeada.}
{313}{}{Genial. Dime qué debo hacer.}
{314}{}{Llévate a patrullar contigo.}
{315}{}{El General me habló de ti. Quedaría a gusto si nos ayudaras con la operación, pues será difícil.}
{316}{}{Por supuesto. Dime qué debo hacer.}
{317}{}{¿Qué más puedo hacer para ayudar a la Hermandad?}
{318}{}{Luego del viaje a Hermosillo, quiero seguir ayudando a la Hermandad. ¿Puedo patrullar junto a ti?}
{319}{}{Sí, necesitamos a más gente como tú para una operación que planeamos.}
{320}{}{Genial. Te escucho.}
{321}{}{Los saqueadores no han hecho más que irritarnos. Están atacando nuestras rutas comerciales y otros asentamientos locales. Atacaron a una de nuestras caravanas hace poco, y no podemos dejarlo pasar.}
{322}{}{No saben con quién se metieron, Latham.}
{323}{}{Deben ser muy peligrosos, si robaron una caravana a la Hermandad.}
{324}{}{Hemos rastreado a los saqueadores hacia uno de sus campamentos. Es hora de hacerles una visita y poner fin a sus ataques de una vez por todas.}
{325}{}{Genial. ¿Cuándo empezamos?}
{326}{}{Dirígete al punto de reunión que marqué en tu mapa. Al llegar, habla con el Comandante Dobbs y te informará de la situación. Asegúrate de estar bien armado. Buena suerte.}
{327}{}{Comprendo. Iré de inmediato.}
{1327}{}{Entendido. Me marcho.}
{328}{}{Me ocuparé de ello... en algún punto.}
{329}{}{Lléveme a patrullar, Paladín.}

{330}{}{Vengo a informarle sobre el asalto al campamento de los saqueadores...}
{331}{}{...Perfecto. Así que sólo era un campamento provisional. Después de atacar la caravana, los saqueadores se separaron. El otro grupo llevó el botín a su base principal. Capturar la caravana era esencial, pero llevarse el cargamento era mucho más importante.}
{332}{}{Así que hay otra misión, ¿verdad?}
{333}{}{No tenemos la localización de su base principal. Pero durante el asalto, encontramos la ubicación de un campamento más grande en las ruinas de Caborca. Debemos destruirlo, y puede que contenga información sobre la base principal.}
{334}{}{¿Cuáles son mis ordenes, señor?}
{335}{}{Habla con el Comandante Dobbs para tu siguiente misión.}
{336}{}{Sí, Paladín Latham.}
{337}{}{Bueno, es nuestra única opción, es lo único que podemos hacer.}
{338}{}{¿Acaso pedí tu opinión? Aunque... no importa. Estás haciendo un buen trabajo. Hubiera sido difícil sin ti.}
{339}{}{¿Cuáles son mis ordenes, señor?}
{340}{}{...Resulta que el campamento en Caborca sólo estaba allí para atacar nuestras caravanas. Su base se encuentra en las montañas hacia el este. No me sorprende que hayamos tardado tanto en localizarlos.}
{341}{}{¿Así que invadiremos su cuartel general?}
{342}{}{¿Cuartel general? Son sólo un montón de bandidos. Llámalo base o escondite.}
{343}{}{Entendido, señor.}
{344}{}{Informa al comandante sobre mi orden. Esta misión será más difícil que las otras dos. Dile que lleve a sus mejores soldados. Y tú - asegúrate de llevar tus mejores armas y armadura. Buena suerte, soldado.}
{345}{}{Entendido, Paladín Latham.}
{346}{}{...Así que acabamos con su base. Exterminamos a los saqueadores, ejecutamos a sus líderes y lo robado se encuentra con la Hermandad. Bien hecho.}
{347}{}{El yermo recordará este día.}
{348}{}{¡Fue una victoria gloriosa! Hemos purgado estas tierras del mal y demostrado nuestra fuerza una vez más. Con los saqueadores derrotados, los caminos serán más seguros y la gloria de la Hermandad se conocerá por el yermo. Gracias por tu ayuda.}
{349}{}{¡Alabada sea la Hermandad del Acero!}
{350}{}{Quiero presentar una denuncia. ¡El Comandante Dobbs me expulsó de su escuadrón!}
{351}{}{Y con razón. Si no hubiera sido porque nos ayudaste en el pasado, sentirías por completo la justicia militar. Lárgate de nuestra base, es lo mejor que puedes hacer.}
{352}{}{Sí, señor...}
{353}{}{¡Puta madre!}
{354}{}{Tengo malas noticias - el Comandante Dobbs falleció durante el ataque.}
{355}{}{¿Cómo? Esto es una desgracia. Era nuestro mejor comandante, y el único que entendía la situación por completo. Sin él, acabar con los saqueadores será muchísimo más difícil.}
{356}{}{¿Pero qué hay de la operación?}
{357}{}{Tendremos que ponerla en pausa y reagruparnos. No sé cuándo te necesitaremos de nuevo, pero te lo haremos saber. Hasta ese entonces, quedas libre.}
{1357}{}{Tendremos que ponerla en pausa y reagruparnos. No sé cuándo te necesitaremos de nuevo, pero te lo haremos saber. Hasta ese entonces, quedas libre.}
{358}{}{Sí, señor.}

{360}{}{Necesitaré equiparme para el asalto.}
{361}{}{Eso es responsabilidad tuya. Lo único que puedo hacer es otorgarte acceso al intendente. Habla con él, quizás puedas comprar algo mejor.}
{362}{}{Gracias.}

#San Felipe
{370}{}{Viajo mucho, podría ayudarte a explorar el territorio circundante.}
{371}{}{Eso nos sería de ayuda. Cuando llegamos, registramos la costa y no encontramos asentamientos. Sin embargo, últimamente hemos oído rumores, se dice que alguien se ha establecido al otro lado de la costa. Descubre si son rumores sustanciados. Y si hay alguien allá, caen bajo la jurisdicción de la Hermandad.}
{372}{}{¡Sí, señor!}
{373}{}{Estoy aquí para informarte sobre mi exploración de la costa.}
{374}{}{¿Y bien? ¿Qué encontraste? ¿Hay alguien allá afuera?}
{375}{}{No, señor. De momento, no hay nada.}
{376}{}{En caso de que *sí* haya gente por allá, ¿qué harías con ellos?}
{377}{}{Les daremos una opción: que sepan su lugar, o que se vayan. Estas tierras nos pertenecen y no podemos tolerar que unos forasteros se establezcan al lado nuestro. Así de simple.}
{378}{}{Ya veo.}
{379}{}{Tienes razón.}
{380}{}{Resulta que sí había un asentamiento en la costa, lejos de aquí. Allí llegó un pequeño grupo de Mexicanos, escapaban de problemas con su... Gobierno.}
{381}{}{Así que son rebeldes. Déjales claro que las reglas son distintas en este lugar; o se arrodillan ante la Hermandad por voluntad propia, o tomaremos esa decisión por ellos.}
{382}{}{Parecen ser pacíficos, así que intentaré negociar con ellos.}
{383}{}{Apenas están armados, podría acabar con ellos. Te haré saber cuando lo haya hecho.}
{384}{}{Hay algunos Mexicanos que se asentaron en la costa, lejos de aquí. Si les ayudan a sobrevivir, están dispuestos a someterse.}
{385}{}{Hmm. Eso funciona. Podrían abastecernos de pescado y vigilar esa parte de la costa. Es un trato útil. Bien hecho.}
{386}{}{¡Me alegra haber sido de ayuda!}
{1386}{}{¡Me alegra haber sido de ayuda!}
{387}{}{Había un grupo de rebeldes Mexicanos. Se rehusaron a servir a la Hermandad, así que maté a su capitán. Tras eso, el resto se fue en bote. Ni idea hacia dónde.}
{1387}{}{Había un grupo de rebeldes Mexicanos. Se rehusaron a servir a la Hermandad, así que maté a su capitán. Tras eso, el resto se fue en bote. Ni idea hacia dónde.}
{388}{}{Has hecho lo correcto. Lo último que necesitamos cerca de nosotros son unos rebeldes. Nunca sabes qué clase de ideas tienen en la cabeza. Bien hecho.}
{389}{}{Había un grupo de rebeldes mexicanos, pero ya se han ido del área.}
{390}{}{Buena suerte. Lo último que necesitamos cerca de nosotros son unos rebeldes, sin importar su naturaleza. ¿Quién sabe qué andan tramando? Bien hecho.}

