{100}{}{Ves a Christopher.}
{101}{}{Ves a un soldado joven, su expresión es triste y pensativa a la vez.}
{102}{}{Ten cuidado con los supermutantes, soldado.}
{1102}{}{Ten cuidado con los supermutantes, soldada.}

{200}{}{Hola... No sabía que teníamos civiles... Eh, bienvenido a bordo.}
{201}{}{¿Por qué estás tan distraído?}
{202}{}{Deja de balbucear, no es muy militar de tu parte.}

{210}{}{Yo... He... He estado pensando mucho acerca de nuestro hogar. Soy Christopher, Paladín Junior. ¿Te... puedo ayudar en algo?}
{211}{}{No quiero molestarte. Me voy.}
{212}{}{Paladín Junior Christopher... a su servicio. ¿Qué necesitas?}

{220}{}{Me dijiste que recordabas tu hogar. ¿Está muy lejos?}
{221}{}{En el búnker de Lost Hills, está... eh... en California, es bastante lejos. Allí yo nací, crecí... Es un lugar lejano, hacia el noroeste. Una caravana tarda... un mes o así, para llegar. A veces más. Siento que... ha pasado tanto tiempo.}
{222}{}{Cuéntame como era la vida en el búnker.}
{223}{}{¿Un búnker? Los hombres están hechos para vivir bajo el sol, no en un sótano oscuro.}
{224}{}{Yo... extraño sus oscuros pasillos... los sonidos de los cables... teníamos todo lo necesario. Comida, electricidad... incluso entretenimiento. Pero aquí... aquí afuera... somos libres, ¿no? Libres, pero... parecemos animales. No es lo mismo... Nada, nada será lo mismo.}
{225}{}{¿No te gusta Arizona?}
{226}{}{Eres un soldado, deja de chillar porque no te gusta en dónde estás.}
{227}{}{Es un desierto... hay kilómetros y kilómetros de la sofocante arena. He visto arena en California, pero al menos es... familiar para mí, nos pertenecían. Y aquí... todo se siente distinto... desconocido. Casi toda la Hermandad se siente así.}
{228}{}{Es sólo porque no has salido lo suficiente, hay lugares muy bellos.}
{229}{}{Así que por fin saliste de tu agujero, ¿verdad?}
{230}{}{Yo... en ese entonces apenas era un iniciado cuando entré en la tropa de ataque. Me dieron un título y... de la nada, estaba en medio de una batalla. Era el ejército del Maestro... apenas habían empezado a destruir asentamientos. Estaba en el búnker, y en un abrir y cerrar de ojos... en el infierno.}
{231}{}{¿Fue difícil, verdad?}
{232}{}{¿Acaso te faltan agallas para ser un paladín?}
{233}{}{Si no hubiera sido por nuestro... entrenamiento, no hubiera salido vivo de ahí. Pelear no fue lo más difícil, sino cuando perdí a mis hermanos. Todavía conservo esta foto, es nuestro escuadrón, antes de que entráramos a Necrópolis. Éramos siete. Pero sólo dos sobrevivieron... yo y el comandante.}
{234}{}{Sigue, te escucho.}
{235}{}{Me vas a contar todo, verdad...}
{236}{}{Yo... lo saqué de ahí. Lo arrastré cuando estábamos en medio de un tiroteo. Habían supermutantes por todos lados... Apenas llegamos al alcantarillado cuando... le dieron a la escotilla con un cohete. La salida colapsó sobre nosotros.}
{237}{}{Eso tuvo que haber sido difícil.}
{238}{}{Tuviste suerte.}
{239}{}{Sí, tuve suerte... sí... creo. Pero... los demás escuadrones seguían allá afuera, luchando, muriendo. Y yo... yo... Ni siquiera sé por qué te cuento esto. No lo entenderías... No eres uno de nosotros. Debería... debería irme. Buena suerte allá afuera, en el desierto, o, lo que sea.}
{240}{}{Gracias por contármelo. A veces vale la pena desahogarte, aunque sea con un extraño. Buena suerte, paladín.}
{241}{}{No sé cómo es posible que alguien como tú sobreviva. Ojalá que te vuelvan a meter en el búnker.}
