{100}{}{Ves a Maura.}
{101}{}{Ves a la Escriba Suprema de la Hermandad del Acero.}
{102}{}{No me siento con ánimos de hablar.}
{103}{}{}

{110}{}{Ah, como olvido las conferencias de Sophia.}
{111}{}{A veces extraño los consejos de Vree.}
{112}{}{Hace tiempo que no recibo alguna carta de Lost Hills.}
{113}{}{Patrañas. Los experimentos en Casa Nueva sí son seguros.}
{114}{}{Es inhumano, pero la ciencia es más importante que su vida.}
{115}{}{}
{116}{}{}
{117}{}{}
{118}{}{}
{119}{}{}

# First dialogue
{200}{}{Alto. ¿Tienes permiso de estar a bordo?}
{201}{}{No, y no lo necesito. ¿Lo entiendes?}
{202}{}{Eso es interesante. Quédate ahí y no te muevas. Llamaré a los paladines... ¡Te dije que no te movieras! Demonios...}
{203}{}{Oh-oh...}
{204}{}{Sí, todo está bien.}
{205}{}{En ese caso, bienvenido seas. Soy Maura, la Escriba Suprema de la Hermandad del Acero. Es poco frecuente que se permita a un civil a bordo. ¿Qué te trae a nuestra nave?}
{1205}{}{En ese caso, bienvenida seas. Soy Maura, la Escriba Suprema de la Hermandad del Acero. Es poco frecuente que se permita a un civil a bordo. ¿Qué te trae a nuestra nave?}
{206}{}{Me encuentro en una misión importante.}
{207}{}{Entiendo... Pero, sólo para asegurarme, hablaré con los paladines para saber por qué te dejaron pasar.}
{208}{}{Es lo correcto, Maura.}
{209}{}{Ocúpate de tus propios asuntos.}

# Re-dialogue
{210}{}{Saludos, forastero.}
{1210}{}{Saludos, forastera.}
{211}{}{Bienvenido, hermano.}
{1211}{}{Bienvenida, hermana.}
{212}{}{Adiós.}
{213}{}{¿Puedo hacerte unas preguntas?}
{214}{}{Sí, pero no creo que pueda responderlas todas.}
{215}{}{No tengo más preguntas.}
{216}{}{¡No!}
{217}{}{Aja.}
{218}{}{Pueees...}
{219}{}{Smack.}

# Questions
{220}{}{Me encontré con un prisionero allá afuera.}
{221}{}{Sí, empleamos prisioneros para reparar la nave. Pero te aconsejo que no deberías acercarte a ellos.}
{222}{}{Un buen uso de recursos que de otro modo se desperdiciarían.}
{223}{}{El individuo con el que hablaste cometió un crimen y ahora está sirviendo su condena. Le dimos una segunda oportunidad - la usará para pagar su deuda. Espero que reconozca la piedad de tal acto.}
{224}{}{Pero, dijo que sólo se llevó un par de mazorcas de una plantación que era enorme...}
{225}{}{Ah, pero eso es la defensa de siempre, ¿no es así? Y aunque sea verdad, un robo sigue siendo un robo. Los criminales suelen restar importancia a sus fechorías. Sospecho que no sólo fueron las mazorcas, y seguramente no tan poco como quiere hacerte creer.}
{226}{}{Ya entiendo. ¿Te puedo preguntar otra cosa?}
{227}{}{Es eso, o intentas excusar que te gusta tener esclavos.}
{228}{}{¡Por supuesto que no! La historia nos ha demostrado que el labor forzado es una solución de corto plazo, y rara vez sin costo alguno. No es necesario regresar a prácticas tan brutales cuando un criminal puede pasar su condena trabajando por el bien de la sociedad. Se trata de la justicia, no de explotar a alguien.}
{229}{}{Quizás tengas razón.}
{230}{}{Bueno, tengo otra pregunta.}
{231}{}{¿Es humano colocarle un collar y forzarlo a trabajar?}
{232}{}{¿Humano? Ese hombre quebró la ley, y tiene suerte de seguir vivo. Puede que nuestros métodos parezcan duros, pero garantizan que se haga justicia con el menor daño posible, tanto para él como para la sociedad.}
{233}{}{Dijo que sólo robó un par de mazorcas de una plantación grande.}
{234}{}{¿Qué puedes contarme de quienes están en la nave?}
{235}{}{¿Así que ustedes no están detrás de la esclavitud en Arizona?}
{236}{}{No, claro que no. Pero... no negaré que algunos de nuestros aliados han pasado del límite. El yermo es un lugar anárquico, e incluso los más nobles pueden salirse del camino.} 

{240}{}{Háblame de esta nave..}
{241}{}{Te encuentras en el destructor *Wockelgeusing*, DD-1862. Mide 130 yardas de eslora, 13,6 de manga y 4,77 de calado. Si funcionara a pleno rendimiento, sus motores podrían alcanzar una velocidad de 35 nudos.}
{242}{}{Eso suena impresionante. ¿Qué más puedes contarme?}
{243}{}{¿Destructor? ¿Qué significa eso?}
{244}{}{Eso significa que está armada con torpedos nucleares, cada uno es capaz de borrar una ciudad entera del mapa. Supongo que cada soldado sueña con presenciar su poder en persona. Pero somos afortunados, pues nunca hemos tenido que usarlos.}
{245}{}{¿La nave es capaz de... zarpar?}
{246}{}{Por el momento no. Nos falta combustible nuclear para cualquier viaje a larga distancia, y el casco y el equipo de la nave necesitan reparaciones urgentes. Teníamos claro que se trataba de un viaje sólo de ida cuando zarpamos - hasta que estableciéramos una base por aquí.}
{247}{}{¿Por qué hay algunas puertas que están cerradas?}
{248}{}{Es por una buena razón. Algunas áreas de la nave contienen equipos muy sensibles que necesitan mucho cuidado. Incluso entre nuestras filas, los errores pasan, y sólo el Paladín Supremo tiene acceso a esos lugares.}
{249}{}{Ya veo. Gracias por la charla.}

{250}{}{Háblame acerca de la Hermandad del Acero.}
{251}{}{Específicamente, ¿qué deseas saber acerca de nuestra orden? Tenemos una historia rica y llena de propósito.}
{252}{}{Ya hablamos suficiente acerca de la Hermandad.}
{253}{}{¿De dónde vinieron todos ustedes?}
{254}{}{Nuestros orígenes yacen en California. Durante muchos años, nos mantuvimos ocultos y en silencio dentro de nuestro búnker, ocupándonos de nuestros propios asuntos e ignorando el caos del mundo exterior. Pero esos días ya pasaron: ahora, debemos expandirnos. Este es solo uno de nuestros muchos puestos avanzados.}
{255}{}{Háblame de la historia de la Hermandad.}
{256}{}{El General Maxon fundó nuestra orden durante la Gran Guerra, él lideró a nuestros ancestros a una vieja base militar en donde sobrevivimos tiempos muy oscuros. Desde entonces han pasado generaciones, y ahora su descendiente lleva la antorcha, guiándonos hacia adelante.}
{257}{}{¿Cuál es su misión? ¿Cuál es la meta que buscan conseguir?}
{258}{}{Nuestra misión es recuperar y preservar tecnología antigua, con el objetivo final de imponer el orden en lo que una vez fue un gran país. Pero aún así, entre la Hermandad, eso se debate. Durante muchos años nos mantuvimos inertes, pero unos sucesos recientes en California nos forzaron a reconsiderar nuestro rol y salir a la luz una vez más.}
{259}{}{¿País? ¿De qué país estamos hablando?}
{260}{}{Los Estados Unidos de América..}
{261}{}{¿De qué se tratan esos sucesos en California que mencionaste?}
{262}{}{Es una historia de gran consecuencia, que trata sobre el Maestro y su terrible ejército. Si gustas, puedo hablar de los detalles.}
{263}{}{Cuéntame, por favor.}
{264}{}{No me interesa. Hablemos de otra cosa.}
{265}{}{Em, retrocedamos un poco.}
{266}{}{Gracias. Escuché suficiente sobre la Hermandad.}
{267}{}{Dado que ya soy parte de la Hermandad, quiero que seas sincera. ¿Qué es lo que REALMENTE quieren conseguir aquí?}
{268}{}{Esto estrictamente extraoficial, pero nuestra misión principal en Arizona es conseguir material nuclear para el cuartel general en California. También requieren otros recursos importantes. Mientras que la Hermandad puede sustentarse en este momento, algún día esos suministros se agotarán. Es posible que nuestros dirigentes tengan que recurrir a medidas más drásticas para garantizar la supervivencia de la Hermandad.}
{269}{}{Así que la supervivencia de la Hermandad es la máxima prioridad, aunque sea necesario sacrificar a los locales. Ya entiendo.}

{270}{}{El Maestro era un tirano - se engañó a sí mismo pensando que era una especie de dios. Creó una iglesia a su propia imagen, lo que formó un culto peligroso. Atrajo a muchos hacia su influencia, algunos fueron usados como sujetos para sus crueles experimentos. Los más exitosos... se convirtieron en soldados para su ejército.}
{271}{}{Parece que el Maestro planeaba conquistar el mundo o algo así.}
{272}{}{Y ustedes solo quisieron lidiar con él porque los amenazaba, ¿verdad?}
{273}{}{Sí.. nuestros exploradores pusieron sus vidas en riesgo para informarnos sobre la situación. Eventualmente la iglesia fue destruida, y su ejército fue derrotado. Los supervivientes se esparcieron por el yermo, pero nuestras tropas los encontraron rápidamente y los exterminaron a todos.}
{274}{}{Suena a que la Hermandad sabe cómo luchar. Dudo que tengan algún rival digno en Arizona.}
{275}{}{Arizona aún no se ha enfrentado a los retos que tuvimos en California. Deberían considerarse afortunados de que estamos aquí.}
{276}{}{Gracias por contarme la historia.}
{277}{}{Eso fue muy informativo.}
{278}{}{}
{279}{}{Tu historia suena un poco rebuscada. ¿No estarás escondiendo algunos detalles, verdad?}
{280}{}{¿Dudas de mi palabra? Si alguna vez te encuentras en California, pregúntale a sus habitantes. Pero te lo advierto, el yermo está lleno de rumores. Pongamos de ejemplo la historia del Morador del Refugio, como ejemplo; tú eliges si creerás en ella, o si piensas que es una leyenda.}
{281}{}{No es una buena idea creer en los rumores.}
{282}{}{Bueno, en este caso, es mejor que no te crea.}

{288}{}{¿Qué clase de persona es?}
{289}{}{Ten cuidado con Dixon. Con una sola palabra, podría ordenar que arrasen una aldea entera. Es todo lo que deberías saber.}
{1289}{}{Ten cuidado con Dixon. Con una sola palabra, podría ordenar que arrasen una aldea entera. Es todo lo que deberías saber.}
{290}{}{¿Qué puedes decirme sobre el General?}
{291}{}{El General Dixon es uno de los paladines más apreciados de la Hermandad. Su perspicacia militar y su astucia política son incomparables, cualidades que envidiarían la mayoría de los gobernantes modernos.}
{292}{}{Eh, ya veo.}
{293}{}{El General Dixon se encuentra entre los más altos rangos de la Hermandad. Pocos tienen la misma experiencia en campañas largas y luchando lejos de casa. Se ha ganado la confianza del Consejo de la Hermandad.}
{294}{}{¿Y tú?}
{295}{}{Gracias. No necesito saber más.}
{296}{}{Es un soldado, yo soy un escriba. Es natural que pensemos distinto sobre el mismo asunto. Dixon tiene poca paciencia para la burocracia y valora más las acciones. Le resulta más fácil conquistar que negociar.}
{297}{}{¿El cuartel general confía en un guerrero tan empedernido?}
{298}{}{El Consejo no siempre está de acuerdo con los métodos de Dixon. Pero nos encontramos lejos del cuartel general, y los desafíos a los que nos enfrentamos requieren soluciones específicas. A Dixon se le otorgó una autoridad especial para actuar con más libertad de lo normal. Creo que tal autoridad está justificada dada nuestra situación actual.}
{299}{}{Gracias, eso me lo deja más claro.}

{300}{}{Parece que ahora estoy bajo tu mando. Me he unido a los escribas.}
{301}{}{Me hace feliz que hayas escogido el conocimiento sobre el armamento. Es el camino de los sabios, y estaré feliz de ayudarte si lo necesitas.}
{302}{}{Te escucho.}
{303}{}{Por supuesto, señor... ita.}
{304}{}{Aquí tienes un neuroenlace analítico para tu Pip-Boy. Es el modelo estándar que usan nuestros escribas. Utilízalo para estar más atento y ser más perspicaz.}
{305}{}{Gracias, hermana Maura. Lo usaré para el beneficio de la Hermandad.}
{306}{}{De acuerdo. Parece que me será de ayuda.}

# Belief in mistakes
{310}{}{Así que ustedes no son más que unos invasores.}
{311}{}{Ni siquiera sé por que debería escucharte hablar de tal cosa. Sigue así y llamaré a los paladines para que te expulsen de la nave.}
{312}{}{Lo siento, creo que me pasé...}
{1312}{}{Lo siento, creo que me pasé...}
{313}{}{¿Tanto te molesta? Sacarme de la nave no cambiará las cosas.}
{314}{}{¡No puedes callarme! Y si lo intentas, ¡los destrozaré a todos!}
{315}{}{En otras palabras, ustedes llegaron para arrebatar cosas que no les pertenecen y conquistar más territorio.}
{316}{}{Cuidado con lo que dices. La Hermandad no lo ve así. Gracias al liderazgo del General Dixon, Arizona ha conocido el progreso - educación, medicina, e industrias, todo a un nivel que no se ha visto en casi un siglo. Semejante milagro necesita sacrificios, ¿no crees?}
{317}{}{¿Será un milagro, o un espejismo?}
{318}{}{Es difícil discutir eso. Adiós, Maura.}
{319}{}{Tu propaganda no me convencerá, escriba. Adiós.}
{320}{}{¿Sigues con eso? Te lo advierto, llamaré a los paladines si no tienes cuidado con lo que dices.}
{321}{}{Lo siento, no quiero problemas. Adiós.}
{322}{}{¿Así que no tienes ningún argumento, verdad? De acuerdo.}
{323}{}{El General Dixon está mal. El costo de sus políticas es demasiado alto, pues promueven y apoyan a la esclavitud. ¿Acaso no lo entiendes?}
{324}{}{¿De verdad? ¿Acaso no fueron nuestros operadores en Fénix los que le trajeron paz y orden a la ciudad? ¿No fue nuestra intervención la que le otorgó las chapas de botella a Arizona? ¿No fue la producción de Two-Sun y la mina de Flagstaff las que crearon una red de comercio, la cual aún crece?}
{325}{}{Dixon está siendo un despiadado. A través de sus 'operadores', impone la tiranía, captura recursos, roba tecnología y practica la esclavitud.}
{326}{}{No... No sé que más decir. Es mejor que dejemos de hablar.}
{327}{}{Estoy parcialmente de acuerdo. Sin embargo, todo lo que mencionaste son medidas necesarias. Los locales han perdido su conexión con el Viejo Mundo, con lo que eran antes. Ahora son unos salvajes, perdieron una hilo que una vez los unió con nosotros; la cultura. Si no intervenimos, ese hilo jamás nos volverá a atar, y nunca volverán a ser civilizados.}
{328}{}{No sé en qué pensar. Déjame pensarlo.}
{329}{}{He visitado muchos asentamientos del yermo, tu influencia en ellos no es tan bonito como me lo presentas.}
{1329}{}{He visitado muchos asentamientos del yermo, tu influencia en ellos no es tan bonito como me lo presentas.}
{330}{}{La Hermandad del Acero está cometiendo un grave error. ¿Acaso no lo ves?}
{331}{}{Sí. Es muy preocupante. ¿Algo más?}
{332}{}{A un nivel local, eso me suena a exceso. ¿Hay algo más?}
{333}{}{Hmm. Dame ejemplos de los lugares que hayas visitado.}
{334}{}{Pues, eh... Ahora mismo no puedo pensar en nada en particular. Hablemos de esto luego.}
{335}{}{Nadie en Fénix se opone a su 'señor', Aaron. Ahora está construyendo un supuesto 'imperio' y aplasta a los rebeldes. Eso no es libertad.}
{336}{}{Gracias a su maravillosa influencia, estalló una guerra en San Brahmán: La poderosa Fénix contra unas pacíficas tribus del yermo.}
{337}{}{Los Hojalateros de Two-Sun son brutales. Compran esclavos y los envían a sus muertes, para que busquen tecnología y la puedan acaparar.}
{338}{}{Puedes visitar el cementerio de Casa Grande para que veas cómo su influencia condenó a la población a una guerra muy sangrienta, todo por una bomba de agua.}
{339}{}{Pensemos en Casa Nueva: no son más que un rebaño de brahmanes. Sin su ayuda, ellos serían débiles y jamás podrían sobrevivir por su cuenta.}
{340}{}{Tus palabras han... Puesto a nuestro sendero en duda. Puede que estemos cometiendo un grave error, incluso si nuestras intenciones son nobles.}
{341}{}{Entonces, ¿por fin puedes verlo?}
{342}{}{Le hemos hecho poco bien a Arizona. No tenemos derecho a invadirlos, despojar a los habitantes de sus recursos y obligarlos a trabajar. Va en contra de los principios de la Hermandad.}
{343}{}{Por lo que veo, comprendes lo que quería decirte.}
{344}{}{Y aún así, esto no es culpa de los Ancianos, sino que de las ambiciones de Dixon. Reemplazarlo no resolverá todo esto, ya estamos demasiado apegados a esto.}
{345}{}{Me alegra que veas la verdad. Pero tal vez profundizamos demasiado en el tema. Dejémoslo así.}
{346}{}{Tenemos que detener esto. Ayúdame.}
{347}{}{No... No, lo siento. Pero no puedo.}
{348}{}{Adiós, Maura.}
{349}{}{Debemos detenerlo, ayúdame. Sus errores llevaron a que mi hogar y mi familia cayeran en las manos de los esclavistas.}
{350}{}{Te... Te pido perdón por lo ocurrido. Llévate esta llave, puede detonar los torpedos nucleares en la bodega de la nave. Coloca el temporizado y sal de aquí tan rápido como puedas. La Hermandad jamás debió haber venido a Sonora.}
{351}{}{Gracias, Escriba Maura.}
{352}{}{Ve, mi valiente amigo.}
{1352}{}{Adelante. La historia nos juzgará a ambas.}

