{100}{}{Ves al Intendente.}
{101}{}{Estás viendo al Hojalatero que está a cargo del almacén. Su calva está equipada con un avanzado casco de computación.}
{102}{}{Una servoarmadura T-51b... Me intriga como fuiste capaz de procurar un equipo tan tecnológicamente avanzado.}
{103}{}{¿¡QUIEN quebró la puerta del almacén!?}

# First dialogue
{200}{}{(como si no te notara) Cinco mil ciento ochenta y seis... no, ese cálculo es incorrecto...}
{201}{}{Oye, ¿qué estás haciendo?}
{202}{}{(sin subir la mirada) Me encargo del almacén y de las operaciones comerciales. Si no estás aquí para comerciar, dirígete a nuestro líder. Está localizado en el lado opuesto de la estructura.}
{203}{}{Entiendo.}

# Re-dialogue
{210}{}{¿Sí?}
{211}{}{No es nada.}

{216}{}{El Maestro Hard te ha integrado en nuestro sistema de socios. Esto te otorga acceso a un descuento a los precios en este almacén.}
{217}{}{Esas son buenas noticias.}
{218}{}{El Maestro Hard ha determinado que ameritas un descuento superior a un socio estándar. Atesora su criterio.}
{219}{}{¿Así que me venderás las cosas a un precio más bajo aún? Esto es asombroso.}

{220}{}{¿Para qué necesitan todas estas máquinas?}
{221}{}{Facilita nuestras operaciones. Puede que esto sea demasiado complejo para que un salvaje del yermo lo comprenda.}
{222}{}{¿En dónde conseguiste esta computadora?}
{223}{}{Observa - esta instalación está repleta de tecnología avanzada desconocida para los habitantes del yermo. Hemos aprovechado y reutilizado la tecnología antigua. Esta computadora no es más que un ejemplo menor de nuestros avances.}
{224}{}{Entiendo.}

# About the product
{230}{}{¿Qué tipo de cosas tienes a la venta?}
{231}{}{Durante mucho tiempo, Two-Sun ha sido prestigiada por su poderío tecnológico. No todos son vistos como dignos de ella.}
{232}{}{Ya veo.}
{233}{}{¿Aceptas dinero de la preguerra como pago?}

{240}{}{No, únicamente chapas.}
{241}{}{¿Por qué?}
{242}{}{Las chapas son respaldadas por la Iglesia del Fuego Santo en Fénix. En lo personal, las considero engorrosas. Pero en el futuro, podríamos fabricar monedas nuevas utilizando nuestra maquinaria.}
{243}{}{Las chapas eran respaldadas por la Iglesia del Fuego Santo en Fénix. A pesar de la caída de la iglesia, las chapas se mantendrán como una moneda confiable en el futuro cercano.}
{244}{}{Ya veo.}
{245}{}{¿De dónde vinieron todas estas cajas de fideos?}
{246}{}{De almacenes militares recientemente descubiertos y abiertos. Son raciones militares de alta calidad y ocasionalmente, incluso a los Hojalateros nos cansa la monotonía.}
{247}{}{Esos fideos hacen que me duela el estómago. ¿No tienes nada más?}
{248}{}{Bueno... no.}
{249}{}{Que pena.}
{250}{}{De hecho, sí. No preguntes la fuente, pero es comida de la mejor calidad. (te muestra tres contenedores de raciones militares) Te costará.}
{251}{}{¿"Paquete de Ración Individual"? Suena bien, me lo pensaré.}
{252}{}{Le darás un descuento a un miembro de la Hermandad del Acero, ¿no es así?}
{253}{}{Le darás un descuento a un Seguidor del Fuego, ¿no es así?}
{254}{}{Claramente. Nuestros aliados merecen tal cortesía.}
{255}{}{Excelente.}
{256}{}{Fideos... ¿No tienes disponible algo mejor?}

# If ZAX destroyed the village:
{260}{}{¡Santo Ohmio! ¿¡Qué estás haciendo aquí!? Tras el ataque de los robots, no tenía previsto que hubieran supervivientes en Two-Sun. Mis colegas han fallecido y los aldeanos han escapado. Ya no vendrá ningún viajero al área.}
{261}{}{¿Por qué no te vas?}
{262}{}{Carezco de alternativas. Mi experiencia yacía con los Hojalateros. Falto de tecnología, mi supervivencia es improbable. Sin embargo, planeo construir una máquina voladora y emprender un traslado hacia California. Teorizo que encontraré utilidad allí.}
{263}{}{No es mala idea. Bueno, te deseo suerte.}
{264}{}{¿Cómo sobreviviste?}
{265}{}{Esta área me es familiar. Adicionalmente, poseo equipo para eludir a los robots. Pero es únicamente una medida momentánea.}
{266}{}{¿Todavía tienes algo a la venta?}

# Quest for the fusion cell
{269}{}{Hemos detenido toda transacción de energía hasta que la mina de Flagstaff resuma sus operaciones. Busca células de fusión en otra localización.}
{270}{}{Necesito una célula de fusión para un generador.}
{271}{}{Esta tecnología es críticamente importante, no es posible distribuirla indiscriminadamente.}
{272}{}{Dime cuánto vale.}
{273}{}{Luego de lo que ocurrió en la Zona Prohibida, merezco tu confianza.}
{274}{}{Lo ofreceré a este precio. (agrega la célula a los objetos a la venta) Si esto está más allá de tus expectativas, puedes irte.}
{275}{}{Déjame pensarlo.}
{276}{}{Bajo mis condiciones, estos objetos han perdido su importancia. Estoy dispuesto a venderlos.}
{277}{}{Bien pensado.}
{278}{}{Lo especificaré una última vez, este objeto no está a la venta.}
{279}{}{No seas así...}

# Product Reveal
{280}{}{Tengo conexiones en toda Arizona - verás que vale la pena hacer negocios conmigo.}
{281}{}{Es una posibilidad. Pero tus palabras no son suficiente.}
{282}{}{No puedes ver los beneficios que te traería hacer negocios conmigo.}
{283}{}{De acuerdo, eso es suficiente. Puedes presenciar estas valiosas piezas de tecnología y ofrecer algo a cambio.}
{284}{}{Mucho mejor.}
{285}{}{Dado que el Maestro Hard ya no está, no tienes por qué esconder tu mercancía.}
{286}{}{El Maestro Hard fue desmantelado, comerciar con todos es la única opción disponible. Te ofrezco todo mi inventario.}
{287}{}{Bien pensado.}
{288}{}{Yo creo que merezco el acceso a tu inventario completo.}
{289}{}{¿Crees que soy un ser 'digno' para ver tu mercancía?}
{290}{}{No. Pero es posible que el Maestro Hard decida lo contrario.}
{291}{}{Entonces debería hablar con él.}
{292}{}{No lo creo.}
{293}{}{Está bien.}
{294}{}{En este momento, necesitas clientes más que nunca.}
{295}{}{Te vendrá bien hacer negocios conmigo.}

# Upgrades
{300}{}{¿Podrías revisar mi equipamiento?}
{301}{}{¿Específicamente qué? ¿Equipamiento, armas, armadura? Podemos encargarnos de todo tipo de tecnología. Pero este servicio costará una cantidad significativa de chapas.}
{302}{}{Olvídalo.}
{303}{}{Estoy hablando de mi motocicleta.}
{304}{}{Hmm... No he tenido la oportunidad de trabajar con tal maquinaria. En esta ubicación, las partes de motocicleta son escasas; principalmente tratamos con vehículos militares pesados y aeronaves.}
{305}{}{[Más]}
{306}{}{Sin embargo, puedo intentar mejorar la motocicleta utilizando una turbina de avión. Nótese que será necesario instalar neumáticos de alto rendimiento y reforzar el motor para lidiar con la tensión que se aplicará.}
{307}{}{¿Puedes hacerlo tú?}
{308}{}{Como he mencionado, carezco de neumáticos y demás componentes de motocicleta. Examina localizaciones con garajes viejos; es posible que encuentres partes útiles allí.}
{309}{}{Ya veo. Volveré después de mejorar mi motocicleta.}
{310}{}{Ya está listo, el mecánico de Ciudad Garaje ha mejorado tanto las llantas como el motor. Háblame sobre la turbina.}
{311}{}{Las aeronaves disponen de sistemas de propulsión altamente avanzados, pero puedo adaptar algunos componentes a una motocicleta. Para evitar el sobrecalentamiento, hará falta un flujo de aire eficiente y tubos de escape térmicos. Se podrían agregar módulos adicionales para la computadora a bordo y un lubricante aeronáutico de alta calidad, podría ser beneficioso.}
{312}{}{Suena bien.}
{313}{}{Mis cálculos preliminares sugieren un incremento del 40% en velocidad. ¿Te interesa? Prepara }
{314}{}{ chapas, tal modificación es intensiva en cuanto a labor.}
{315}{}{Toma las chapas. ¡Instala esa turbina!}
{316}{}{Por el momento, no puedo permitirme eso. Parece que tendré que ir igual de lento que un brahmán.}
{317}{}{Anticipaba tal respuesta. Es lo que se espera de un salvaje.}
{318}{}{No quería engañarte...}
{319}{}{¡Increíble! Tu motocicleta es irreconocible. ¡Ahora no la conducirás, sino que volarás en la carretera!}
{320}{}{Eso suena demasiado complicado, caro e impráctico. Me las arreglaré sin eso.}

# Rewards
{330}{}{El Maestro Hard mencionó que tendrías una recompensa para mí.}
{331}{}{Correcto. Recompensas: armadura de metal, pistola láser y gafas de visión nocturna. Utiliza estas recompensas sabiamente.}
{332}{}{Le daré un buen uso a todo esto.}
{333}{}{Correcto. Aquí hay una lista de los objetos disponibles. Selecciona y destaca tu elección.}
{334}{}{[Armadura de metal]}
{335}{}{[Pistola de plasma]}
{336}{}{[Medicamentos: 3 estimulantes, 3 antídotos, 1 Rad-X]}
{337}{}{[Sigilante, Sensor de Movimiento y Gafas de Visión Nocturna]}
{338}{}{[2 batería nucleares]}
{339}{}{[350 chapas]}
{340}{}{Utiliza esta recompensa sabiamente.}
{341}{}{Le daré un buen uso a todo esto.}

# Power Armor
{350}{}{Necesito que repares mi servoarmadura..}
{351}{}{Una pieza ejemplar de la tecnología antigua. Al observar esta armadura, detecto errores en los circuitos lógicos de mi red neural. Podremos reparar todo el daño, pero requerirá un número significativo de chapas.}
{352}{}{Adelante.}
{353}{}{No hace falta. Puede que la Hermandad la repare sin pedir chapas.}
{354}{}{Me lo pensaré. De todas formas, tengo que salir de esta cosa.}

# Relic
{400}{}{Tengo un reloj atómico. ¿Y tú?}
{401}{}{¡Santo Ohmio! Este reloj tiene un siglo y aún funciona.}
{402}{}{Parece que te emociona.}
{403}{}{Nuestros ancestros poseían una sabiduría destacable. Nosotros rescatamos los vestigios de su tecnología, y con gran dedicación, nos esforzamos para replicar sus creaciones, aquellas que eran capaces de fabricar en minutos. Este reloj representa una tecnología de precisión más allá de nuestras capacidades actuales.}
{404}{}{Te lo daré gratis, para que lo tengas en cuenta en nuestras futuras transacciones. ¿No te negarás a comerciar conmigo, cierto?}
{405}{}{Eso es razonable. Puedes esperar precios más favorables hacia ti, ser del yermo.}
{406}{}{Muy bien.}
{407}{}{Te venderé este reloj por 350 chapas.}
{408}{}{Eso es razonable, dispensaré las chapas. Espero que esta no sea nuestra última transacción.}
{409}{}{Genial.}
{410}{}{Te daré tecnología a cambio de tecnología. Puedes tener el reloj si me das especificaciones para las armas de energía.}
{411}{}{Eso es justo. Poseo la información que requieres y ciertamente impulsará tus habilidades. Sin embargo, muchos de nosotros están en desacuerdo con la idea de que un primitivo utilice tecnología avanzada.}
{412}{}{Esto me vendrá bien, nos vemos luego, Hojalatero.}
{413}{}{Poseo un formidable puño neumático, utilizado para insertar la justicia a aquellos que nos engañen. No veo el reloj atómico entre tus pertenencias, viajero desértico.}
{414}{}{¿Cómo pasó esto...?}
{415}{}{Dame un momento para pensarlo. No te preocupes, el reloj estará a salvo.}
{416}{}{El Intendente ha reducido el costo de sus bienes en un 10%.}
