{100}{}{Ves a un campesino.}
{101}{}{Ves a un campesino de apariencia común. Resalta mucho entre los Hojalateros.}
{102}{}{Gracias por ayudarme, recordaremos lo que hiciste.}

{200}{}{Oye, no eres de aquí, ¿cierto? Bueno, es obvio. Te daré un consejo - ni te molestes con estos imbéciles. No les importan los forasteros.}
{201}{}{¿Y tú eres...?}
{202}{}{Sólo soy otra víctima de sus pendejadas. Nuestro pueblo necesita células de fusión para nuestro generador, pero los Hojalateros no quieren vendérmelas. ¿Y sabes por qué? ¡Porque según ellos no somos 'dignos' de esa tecnología!}
{203}{}{¿Por qué?}
{204}{}{No lo sé... Tratar con estas... Personas, es muy difícil. Solo somos una pequeña aldea, todos somos granjeros. Ni siquiera le interesamos a los Hojalateros. Ese generador era nuestra única fuente de energía. Y sin él, todo nuestro valle se transformará en un desierto.}
{205}{}{Resulta que tengo una célula de fusión.}

{210}{}{¿Conseguiste la célula de fusión?}
{211}{}{Aún no, lo lamento.}
{212}{}{Tengo que irme.}
{213}{}{Cuéntame más.}

{220}{}{Háblame acerca de tu hogar.}
{221}{}{No es más que un pequeño pueblo rural. Hace poco, nuestro generador se apagó - es la única fuente de energía en nuestro valle. Le pedimos ayuda a los Hojalateros, pero nos consideran dignos - somos insignificantes, supongo.}
{222}{}{¿Por qué te importa tanto el generador?}
{223}{}{¡Porque la comunidad entera depende de él! Nuestra bomba de agua, la electricidad, la comunicación por radio - sin él, nuestro valle volverá a ser un desierto inhabitable.}

{230}{}{¿No hay ningún otro lugar en donde comprar las células?}
{231}{}{Los únicos que las fabrican estos días son los Hojalateros. Y encontrar células de la preguerra es casi imposible. Hace tiempo que estos fanáticos han revisado toda la región.}
{232}{}{¿Has probado a buscar en Fénix?}
{233}{}{¿Lo dices en serio? Somos campesinos, para nosotros un viaje así es un desafío enorme. Además, la gran ciudad también le compra a los Hojalateros y pagan mucho más.}

{240}{}{¿Por qué los Hojalateros se niegan a venderte las células?}
{241}{}{Piensan que no somos dignos de su tecnología. Creen que desperdiciamos sus recursos, pero eso no tiene sentido - las necesitamos para sobrevivir. ¿¡Qué puede ser más importante que eso!?}

{250}{}{¿Qué piensas hacer?}
{251}{}{Necesitamos esas células urgentemente... Mira, eres un campesino igual que nosotros, ¿no? Se nota. No importa lo que lleves puesto, tus ojos y manos te delatan. Tenemos que ayudarnos el uno al otro, amigo.}
{1251}{}{Necesitamos esas células urgentemente... Mira, eres una campesina igual que nosotros, ¿no? Se nota. No importa lo que lleves puesto, tus ojos y manos te delatan. Tenemos que ayudarnos el uno al otro, amiga.}
{252}{}{¿Y cómo me ayudarás tú a mí?}
{253}{}{Tengo muchos contactos entre las caravanas, puedo arreglarte una escolta.}
{254}{}{Me lo pensaré.}
{255}{}{¿Con quién podría hablar acerca de las células?}
{256}{}{Las guardan en ese hangar de allá, el intendente está a cargo de ellas. Pero dudo que cambie de parecer.}
{257}{}{Ya lo veremos.}
{258}{}{¿Acaso sugieres que le robemos a los Hojalateros?}
{259}{}{De la misma forma que le han robado a muchas otras personas. Pero salvarás a todo un asentamiento y te harás amigo de gente honesta. ¿Qué dices, compadre?}
{1259}{}{De la misma forma que le han robado a muchas otras personas. Pero salvarás a todo un asentamiento y te harás amiga de gente honesta. ¿Qué dice, señorita?}


{260}{}{¡Pensé que ya no quedaba nadie por acá!}
{261}{}{¿Qué estás haciendo aquí?}
{262}{}{Necesito células de fusión para nuestro generador. Están en el almacén del hangar de por allá, pero no puedo entrar sin que me vean. Parece que vienes de allá y los robots te dejaron en paz. ¿Me puedes traer una?}
{263}{}{Veré que puedo hacer.}
{264}{}{Eso es problema tuyo, yo tengo que ocuparme de los míos.}
{1264}{}{Eso es problema tuyo, yo tengo que ocuparme de los míos.}
{265}{}{Me largo.}
{266}{}{¿Encontraste alguna?}

{300}{}{Aquí tienes una célula para el generador.}
{301}{}{¡Increíble! ¿Cómo la conseguiste? No importa, no quiero saberlo. Tengo que irme de aquí antes de que sospechen. Gracias compadre, nuestra comunidad hubiera colapsado sin tu ayuda.}
{1301}{}{¡Increíble! ¿Cómo la conseguiste? No importa, no quiero saberlo. Tengo que irme de aquí antes de que sospechen. Gracias señorita, nuestra comunidad hubiera colapsado sin su ayuda.}
{302}{}{Oye, ¿no te olvidas de algo?}
{303}{}{Perdóname, yo... te mentí, no conozco a nadie en las caravanas. Pero... Tengo dinero de la preguerra, aquí tienes, quédatelo. Y... Eh, si quieres, podemos ir a Casa Grande, será más seguro ir juntos. ¿Qué me dices?}
{304}{}{Vamos.}
{305}{}{No, no tengo otras cosas que hacer.}
{306}{}{¿Entonces vendrás conmigo? El camino a Casa Grande es difícil, pero es más seguro que vayamos los dos.}
