{100}{}{Ves a Abel.}
{101}{}{Ves a uno de los representantes de la Iglesia del Fuego Santo.}

# First dialogue
{200}{}{¿Tienes algún asunto que tratar aquí? Si es así, habla con el Maestro Hard. Lo encontrarás en el taller en el hangar de allá.}
{201}{}{Gracias.}
{202}{}{De hecho, me gustaría hablar contigo.}
{203}{}{Sí, claro. Me llamo Abel, soy uno de los Seguidores del Fuego, si eso te suena. Ahora déjame en paz.}
{204}{}{¿Qué haces aquí?}
{205}{}{Eres persistente. Nuestra iglesia necesita los servicios de los Hojalateros, igual que cualquier otra comunidad moderna. Debo supervisar que se cumplan las peticiones de la iglesia.}
{206}{}{¿Tanto confían en los Hojalateros?}
{207}{}{Son los mejores en lo que hacen. Puede que hayas visto su trabajo: armas neumáticas, dispositivos informáticos, incluso miembros protéticos e implantes simples. Por suerte, comprenden que no deben hacer negocios con cualquiera. No comparten su conocimiento ni la tecnología que poseen a la ligera. Nuestra iglesia es afortunada, pues cuenta con su cooperación.}
{208}{}{De acuerdo, iré a ver. Adiós.}
{209}{}{Deben cooperar si eso les consigue el poder en la región. Cuídate.}

# Re-dialogue
{210}{}{¿Tú otra vez?}
{211}{}{Olvídalo.}
{212}{}{¿En qué puedo ayudarte, hermano?}
{1212}{}{¿En qué puedo ayudarte, hermana?}
{213}{}{Gracias, pensaré al respecto.}
{214}{}{Mucha información por hoy.}
{215}{}{Estoy perdiendo el tiempo contigo.}
{216}{}{No importa, ya me voy.}

{220}{}{Háblame acerca de tu religión.}
{221}{}{Es una larga historia. Es mejor que vayas a la Catedral en Fénix y lo veas por tu cuenta.}
{222}{}{De acuerdo.}

{230}{}{De hecho, yo también soy un Seguidor del Fuego.}
{1230}{}{De hecho, yo también soy una Seguidora del Fuego.}
{231}{}{¿Lo dices en serio? Eso lo cambia todo. Bienvenido a Two-Sun, hermano. Juntos, le traeremos gloria al Fuego Santo.}
{1231}{}{¿Lo dices en serio? Eso lo cambia todo. Bienvenido a Two-Sun, hermana. Juntos, le traeremos gloria al Fuego Santo.}
{232}{}{Veo que ya estás más a gusto. ¿Te puedo hacer unas preguntas?}
{233}{}{Entiendo.}
{234}{}{Gracias por haberme respondido, debo ponerme a trabajar.}

{240}{}{¿Qué es lo que realmente hace la iglesia en Two-Sun?}
{241}{}{Como te dije, nuestra iglesia necesita tecnología y conocimiento. Una de nuestras creencias principales es que el Fuego Santo quemó al Viejo Mundo para construir uno nuevo. Los Hojalateros son los constructores de ese Nuevo Mundo, sus habilidades y tecnología son esenciales para sobrevivir y desarrollarse. Lo triste es que gran parte del yermo no entiende el Progreso; le temen al cambio.}
{242}{}{¿En qué peticiones están trabajando los Hojalateros?}
{243}{}{Lo más importante son las baterías. Sin ellas, las máquinas más importantes no son más que chatarra. También fabrican armas y arreglan los viejos equipos electrónicos.}
{244}{}{¿Sabes cómo los Hojalateros aprendieron tanto de la tecnología?}
{245}{}{Sus habilidades se han transmitido de generación en generación, recopilando conocimientos de todo el yermo: nuestra iglesia, intercambios con caravanas y cualquier fragmento de sabiduría que pudieran encontrar.}
{246}{}{Veo que no estás predicando. ¿Por qué?}
{247}{}{La Iglesia busca expandirse, pero en Two-Sun, un embajador es suficiente. No es que los Hojalateros compartan nuestra fe, pero su apoyo es suficiente para que ambos podamos tener éxito.}
{248}{}{Algo me dice que tienes ordenes que prefieres mantener en secreto.}
{249}{}{Ya veo por qué te aceptó la iglesia. Sí, hay tecnologías especiales de la que una persona común no debería saber. Podrían alterar la balanza del poder o crear descontento.}
{250}{}{En la historia, las tecnologías con fines pacíficos suelen transformarse en armas, trayendo mal en vez del bien.}
{251}{}{Si alguien puede traerle el progreso a esta región, mientras que presta atención a las lecciones del pasado, somos nosotros, los que servimos al Fuego Santo. Nos hemos adherido a esa creencia y no cambiaremos de parecer. Confía en mí, la iglesia sabe lo que hace y transformará a Sonora en un paraíso.}
{252}{}{¿Fines pacíficos? No me hagas reír. Los que de verdad pueden traerle el progreso a esta región, somos nosotros, los que servimos al Fuego Santo. Nos hemos adherido a esa creencia y no cambiaremos de parecer. Confía en mí, la iglesia sabe lo que hace y transformará a Sonora en un paraíso.}

{260}{}{Los Hojalateros han esclavizado a muchos de mis amigos. ¿Cómo puedo liberarlos?}
{261}{}{¿Por qué harías eso? No creo que tus amigos sean de ayuda fuera de la esclavitud. Servir al Progreso es un gran honor y beneficia a toda la humanidad. La mayoría de los esclavos ya fueron enviados a la Zona Prohibida, tendrás que entrar ahí dentro y salvar a tus amigos por tu cuenta.}
{262}{}{Pensaré en lo que dijiste, pero quiero hablar de otra cosa.}
{263}{}{Entonces, eso es lo que haré. Adiós.}

# GG enemy cult
{300}{}{¿Tú otra vez? Abandona esta ciudad antes de que llame a los guardias.}
{301}{}{Oye, ¿por qué eres tan hostil?}
{302}{}{¡Ni siquiera me dirijas la palabra, ignorante atómico! Los Seguidores del Fuego tienen una gran red de informantes, ya me han contado de tu expulsión. ¡Vete!}
{303}{}{Cálmate...}

{310}{}{Alto. ¿Quién... quién te envía?}
{311}{}{Nadie. ¿Por qué estás tan nervioso?}
{312}{}{Tengo mis razones. Y para empezar, ni siquiera deberías estar aquí. Es muy sospechoso que un enemigo de los Seguidores esté visitando a los Hojalateros. Es como si estuvieras planeando algo en nuestras narices.}
{313}{}{¿Así que la Iglesia del Fuego Santo perdió el respeto que tenía?}
{314}{}{La Iglesia era como el motor del progreso en Arizona. Y ahora que nuestra Catedral fue destruida, se necesitará mucho esfuerzo para llevarla de vuelta a su grandeza y recobrar la confianza que nos tenían. Pero los Hojalateros nos han servido durante casi diez años, es un sólo error, no traicionarán a sus mecenas por tal cosa.}
{315}{}{¿Y entonces por qué estás tan nervioso? Los Hojalateros ya no son tan sumisos, ¿es eso?}
{316}{}{Los hemos considerado máquinas de trabajo, pero ahora conocen la libertad y la... superioridad, puede que falte una muestra de nuestro poder para que recuerden su lugar. Suficiente, deja de burlarte, átomo insignificante. Fuera de mi vista.}
{317}{}{Si lo piensas, tú eres el que debería salir de Two-Sun, yo no.}
{318}{}{Cuídate la espalda, cultista...}
{319}{}{No tienes que ser tan agresivo...}
{320}{}{¡Déjame en paz, demonio de la fisión atómica!}
{321}{}{Como sea..}
