{100}{}{Ves al guardián de la puerta.}
{101}{}{Estás viendo a un Hojalatero que protege la entrada a su ciudad.}
{102}{}{Acceso concedido, pero estaremos monitoreando tus acciones.}
{103}{}{¡No puedes pasar sin permiso!}
{104}{}{(esconde la comida mientras observa a su alrededor) Acceso concedido, pero no nos causes problemas.}

# Cat-scene at the gate
{110}{}{Parece que la puerta principal está presenciando un problema.}
{111}{}{¡Déjame pasar, ahora! ¡Quiero que Hard me escuche!}
{112}{}{Tu insignificante tribu se estima demasiado a sí misma. Vete.}
{113}{}{¿¡Cómo te atreves!? ¡Ustedes han dependido de nuestros suministros por años, no pueden tirarnos así!}
{114}{}{La Zona Prohibida nos provee de cualquier recurso. Ya no eres necesario. Abandona el área, o me veré obligado a usar la fuerza.}
{115}{}{¡Chinga tu madre!}
{116}{}{}
{117}{}{}
{118}{}{}
{119}{}{ }

# Primary dialogue
{200}{}{Alto. Esto es un área restringida, explica el por qué estás aquí.}
{201}{}{No será necesario, ya me voy.}
{202}{}{Ya veo.}

{210}{}{No nos interesa. Lárgate.}
{211}{}{¡Déjame pasar, maldito fenómeno!}
{212}{}{De acuerdo, me voy. Pero puede que vuelva.}
{213}{}{Piérdete. De lo contrario, la fuerza del Progreso acabará contigo.}
{214}{}{Ya lo veremos luego...}
{215}{}{Acceso concedido. Mientras te encuentres adentro, guarda tu arma y no inicies conflictos. No interactúes con los esclavos. No entres a la Zona Prohibida sin permiso. Dirígete de inmediato al hangar y habla con el Maestro Hard, él es nuestro líder. Eso es todo.}
{216}{}{Son reglas muy estrictas, intentaré no causarles ningún problema.}
{217}{}{No era necesario que lo dijeras, ya es obvio. Apártate.}
{218}{}{Necesito manutención para mi motocicleta.}

{220}{}{Estoy buscando a mis parientes.}
{221}{}{Puede que estén aquí presentes, o puede que no. Nosotros asimilamos a nuevas unidades... es decir, los habitantes del yermo; hay una alta demanda de trabajadores. Si buscas a tus demás unidades biológicas, acércate al taller.}
{222}{}{Comprendo.}

{223}{}{Me gustaría comerciar con ustedes.}
{224}{}{Necesitamos bienes. El Maestro Hard siempre está dispuesto a comerciar, mientras sea rentable.}
{225}{}{Genial, siempre estoy listo para un buen trato.}
{1225}{}{Genial, siempre estoy lista para un buen trato.}

{226}{}{Me encuentro en la búsqueda de conocimiento técnico.}
{227}{}{Durante un siglo, los Hojalateros han estado atados a una única fuente de energía. ¿Quién crees que eres para buscar nuestro conocimiento? Sin embargo, los tiempos han cambiado. Quizás el Maestro Hard quiera hablarte.}
{228}{}{Eso suena genial.}

{229}{}{Necesito que reparen algunas de mis cosas. Para empezar, pagaré 200 chapas.}
{230}{}{Nuestro gusto por trabajar iguala a nuestro amor por la tecnología. Tu problema es nuestro problema, mientras puedas pagarnos.}
{231}{}{Creo que podré reunir las chapas necesarias.}

{232}{}{Soy un acólito del Fuego Santo, soy tu amigo, Hojalatero. Déjame pasar la noche aquí adentro.}
{1232}{}{Soy una acólita del Fuego Santo, soy tu amiga, Hojalatero. Déjame pasar la noche aquí adentro.}
{233}{}{Desde hace años que la Iglesia del Fuego Santo ha demostrado ser un socio confiable. Bienvenido a Two-Sun, acólito.}
{1233}{}{Desde hace años que la Iglesia del Fuego Santo ha demostrado ser un socio confiable. Bienvenido a Two-Sun, acólita.}
{234}{}{Gracias.}

{235}{}{Soy parte de la Hermandad del Acero.}
{236}{}{Nosotros reconocemos lo suprema que es la Hermandad. Su nivel tecnológico no tiene igual.}
{237}{}{Estás en lo correcto.}

{238}{}{¿Puedes ver mi túnica? Estoy con los Seguidores del Fuego Santo, y siempre hemos tenido buenas relaciones con los Hojalateros.}
{1238}{}{¿Puedes ver mi túnica? Estoy con los Seguidores del Fuego Santo, y siempre hemos tenido buenas relaciones con los Hojalateros.}
{239}{}{Tu catedral se desmoronó, tenerlos entre nosotros es calculado como un riesgo. Vete ahora, y no interrumpas nuestro orden.}
{240}{}{Demonios...}

{241}{}{Estoy viajando hacia el Puerto de Acero, vengo desde la Catedral. Me dijeron que podría pasar la noche entre ustedes.}
{242}{}{Reconocemos lo que ha contribuido la Iglesia del Fuego Santo. Acceso concedido.}
{243}{}{Muchas gracias.}
{244}{}{Estoy aquí para comerciar con ustedes. Aquí tengo un reloj atómico, no es lo único que puedo venderles.}

# Re-dialogue
{250}{}{Acceso concedido. Estaremos monitoreando tus acciones, no lo olvides.}
{251}{}{Eh, claro. No hay problema.}
{252}{}{Estoy investigando el ataque a la caravana, el Maestro Hard me lo confió.}
{253}{}{No es normal que Hard confíe en los extranjeros. Pero mi única opción es obedecerlo.}
{254}{}{Antes de irnos, debo prepararme. Dame un segundo.}
{255}{}{¿Quién crees que pudo haber atacado a la caravana?}
{256}{}{Salvo por forajidos y el ocasional saqueador norteño, nadie se atrevía a entrar en nuestro territorio. Desde que Two-Sun interactuó con el resto del mundo, se estableció una gran cantidad de conexiones externas. Esto atrajo a más saqueadores, es inevitable, pero es un precio que pagar por el Progreso.}
{257}{}{¿Qué piensan los líderes de las caravanas?}
{258}{}{Fue un asalto preciso, los saqueadores se ocultaron en el interior de una estructura abandonada localizada junto a la carretera. Su único objetivo era el cargamento; los miembros de la caravana no eran importantes, por lo que los dejaron ir.}
{259}{}{¿Hay algún detalle inusual?}
{260}{}{Algunos de los saqueadores portaban armas de energía. Nuestra hipótesis es que las adquirieron en la Zona Prohibida.}
{261}{}{Muéstrame donde ocurrió el ataque.}
{262}{}{Ocurrió en un café antiguo junto a la interestatal, está localizado a unas millas desde aquí.}
{263}{}{[Ve al área del ataque]}
{264}{}{Enfunda tu arma, o sufrirás las consecuencias.}
{265}{}{Claro.}

{270}{}{¿Por qué colgaste a ese hombre?}
{271}{}{Los Seguidores del Fuego Santo han demostrado que son inadecuados para nuestra tecnología. Los restos de este individuo cumplirán una función, pues disuadirá a los demás.}
{272}{}{Estoy de acuerdo, es hora de que esos cultistas desaparezcan del mundo.}
{273}{}{En mi opinión, es muy cruel. Pero es asunto tuyo.}
