{100}{}{Ves al cantinero.}
{101}{}{Ves al dueño del bar. Se rasca perezosamente la barriga, recargado en un viejo asiento de piloto.}
{102}{}{¡Cierra la puerta! Hay robots por todos lados.}

# First dialogue
{200}{}{(se gira de mala gana en su dirección) No hay espacio, estamos llenos.}
{201}{}{Pero, ahí están la mitad de las llaves...}
{202}{}{Se viene algo grande, las habitaciones están reservadas. Si tienes que pasar la noche, prueba a tocar la puerta en alguna casa.}
{203}{}{No me siento muy a gusto aquí dentro.}
{204}{}{No es problema mío.}
{205}{}{Eh, bueno...}

{210}{}{Te lo dije, estamos llenos.}
{211}{}{Yo creo que sólo quieres evitar a los desconocidos.}
{212}{}{Lo recuerdo.}

{213}{}{Y yo creo que algunas personas meten la nariz en donde no deben.}
{214}{}{Erm...}

{215}{}{(se inclina hacia ti) Los Hojalateros son precavidos contra los espías, no quieren que sus planes salgan a la luz. Así que debo tener cuidado con los desconocidos.}
{216}{}{Me alegro de que nos entendamos.}
{217}{}{Como Seguidor del Fuego, ¡me ofende que me trates así!}
{1217}{}{Como Seguidora del Fuego, ¡me ofende que me trates así!}
{218}{}{Soy parte de la Hermandad, no les gustará que me trates así.}
{219}{}{¿Por qué eres tan antipático?}
{220}{}{No eres de por aquí.}
{221}{}{Bueno, sí, eso es obvio...}

# Re-dialogue
{250}{}{¿Con qué te ayudo?}
{251}{}{Gracias.}
{252}{}{Adiós.}

{260}{}{¿Qué está pasando por aquí?}
{261}{}{Los Hojalateros intentan acceder a un viejo almacén militar. Lo llamaron la "Zona Prohibida", no han tenido éxito, pero es sólo cuestión de tiempo.}
{262}{}{Los Hojalateros accedieron a un viejo almacén militar. Lo llamaron la "Zona Prohibida". Tienen mucho trabajo por delante.}
{263}{}{¿Has escuchado algo sobre esclavos de la Villa?}
{264}{}{No. Ve a preguntar al hangar; allí guardan a los esclavos.}
{265}{}{¿Cómo llegaste aquí?}
{266}{}{Llegué acá hace años cuando los Hojalateros abrieron una ruta comercial con Fénix. Necesitaban un hotel para los caravaneros, así que lo abrí yo. Si no fuera por los Hojalateros, no hubiera durado tanto tiempo vivo. Probablemente me estaría pudriendo en algún lado del yermo, con los huesos expuestos y todo.}
