{100}{}{Ves al empleado de la tienda.}
{101}{}{Ves a un hombre de mediana edad, a juzgar por su actitud, está obsesionado con el orden y la limpieza.}

#Dialogue
{200}{}{Pasa, viajero. Me gusta mantener el lugar limpio, así que no hagas desorden.}
{1200}{}{Pasa, viajera. Me gusta mantener el lugar limpio, así que no hagas desorden.}
{201}{}{Adiós.}
{202}{}{No esperaba que volvieras tan pronto. ¿En qué te puedo ayudar?}
{203}{}{Tengo que enviar un paquete a Fénix.}
{204}{}{Tengo que enviar un paquete a Flagstaff.}
{205}{}{Tengo que enviar un paquete a Puerto Peñasco.}

#Sending a package
{210}{}{Para eso estamos. El costo del envío es de }
{211}{}{ chapas. Ni más ni menos. Coloca lo que quieras enviar a esa caja que está contra la pared. Al pagar las chapas, lo llevaremos al destino que hayas escogido.}
{212}{}{Aquí tienes las chapas, envía el paquete.}
{213}{}{Ahora no.}

{214}{}{No, te falta dinero.}
{215}{}{¿Entonces podemos hablar de otra cosa?}
{216}{}{Volveré cuando tenga más chapas.}
{217}{}{Entonces haré un inventario y lo escribiré en el libro, es parte del protocolo. Gracias por preferirnos, el paquete te estará esperando en Fénix en la oficina del Sonora Express.}
{218}{}{Genial.}

{220}{}{Soy miembro de la Hermandad del Acero, ¿me darás un descuento?}
{221}{}{Por supuesto. Tenemos un trato especial con la Hermandad.}
{222}{}{Eso es genial.}
{223}{}{Ah, eres tú... Tengo que informarte de que el acuerdo con la Hermandad ya no existe. No es decisión mía, es decisión de la empresa.}
{224}{}{Que mala suerte...}

#First dialogue
{230}{}{¿En qué te puedo ayudar?}
{231}{}{¿Qué es este lugar?}
{232}{}{Una oficina local de la compañía de mensajeros, el "Sonora Express". Nuestro trabajo es hacer distintos tipos de envíos.}
{233}{}{¿Qué tan grande es su red de caravanas?}
{234}{}{Llegamos tan cerca como lejos, pero depende del envío. Nuestra oficina central se encuentra en Fénix, y de allí hay rutas a los demás asentamientos.}
{235}{}{Ya veo. Lo tendré en cuenta.}

# added by cambragol
{236}{}{¿El Sonora Express? ¿De nuevo? ¿Qué tan grande es su red de envío?}

{260}{}{¿Puedo dejar mi equipamiento contigo?}
{261}{}{Así es. Contamos con una taquilla de almacenamiento. Tus pertenencias serán protegidas bajo una cerradura de combinación segura y estará bajo supervisión. Cada taquilla tiene un precio de }
{262}{}{ chapas.}
{263}{}{Eso es demasiado caro.}
{264}{}{Está bien, me gustaría rentar una taquilla.}
{265}{}{Muy bien. Podrás accederla en todo momento.}
{266}{}{Gracias.}
{267}{}{Necesito otra taquilla.}
