{101}{}{Ves una mesa de trabajo improvisada.}
{102}{}{Fabricaste 20 bengalas a partir de unos cuetes viejos.}
{110}{}{La mesa contiene los componentes para fabricar unas células de microfusión.}
{111}{}{Ya se han utilizado todos los componentes. La mesa es inútil.}
{112}{}{Fabricaste una célula de microfusión con 10 cargas.}
{113}{}{Fabricaste una célula de microfusión con 20 cargas.}
{114}{}{Fabricaste una célula de microfusión con 30 cargas.}
