{100}{}{Ves a Chris.}
{101}{}{Ves a uno de los campesinos de la Villa. Su rostro demuestra que está confundido.}

{110}{}{La mochila de Chris se encuentra llena de suministros.}
{111}{}{Gracias, será suficiente... o eso espero.}
{112}{}{(}
{113}{}{/}
{114}{}{) de la mochila de Chris se encuentra con suministros, pero no será suficiente para su viaje.}
{115}{}{Gracias, al menos no me voy a morir de hambre.}

{200}{}{, eres tú... No me sorprende, porque la Villa te considerá su ídolo, sé que ellos te enviaron. Te ven como su líder. No querrás perder ese trato, ¿verdad?}
{201}{}{Pero, ¿por qué escapaste de los demás?}
{202}{}{Porque querían darme un castigo. Ya sabes la razón, ¿por qué preguntas algo que ya sabes?}
{203}{}{Necesitaba saber tu lado de la historia.}
{204}{}{Tienes razón, es mejor que te quedes ahí. Seguiré con lo mío.}

{210}{}{Si este es mi último día, preferiría pasarlo junto a ti.}
{211}{}{Si este es mi último día, preferiría estar en el fondo del pozo que al lado tuyo.}
{212}{}{No vayas a ningún lado, ya vuelvo.}
{213}{}{Me parece que no entiendo lo que ocurrió. Dime qué está pasando.}
{1213}{}{Me parece que no entiendo lo que ocurrió. Dime qué está pasando.}
{214}{}{Claro. No hay prisa.}
{215}{}{Sigue.}

{220}{}{¿Por qué están tan furiosos contigo?}
{221}{}{Los saqueadores se 'olvidaron' de mí, igual que tú. Pero a diferencia de ti, no estaba fuera de la Villa, sólo me escondí en el sótanos. Los demás no pueden perdonarme eso y creen que soy un... traidor. Y ya lo sabes, los traidores jamás han durado mucho en la Villa.}
{222}{}{¿Qué clase de castigo tenían planeado?}
{223}{}{No lo tengo claro, pero escuché que pensaban en apedrearme. Antes lo hacían así. Pero después del asalto, seguro que piensan en algo peor.}
{224}{}{Por cierto, ¿qué es de este lugar?}
{225}{}{(encoge los hombros con indiferencias) Son ruinas antiguas. Nuestros ancestros obtuvieron ladrillos de aquí para construir sus hogares. Por cierto, ten cuidado allá arriba, porque pareciera que están a punto de colapsar...}
{226}{}{[Más]}
{227}{}{Es chistoso, ¿no? La Villa existe gracias a estas ruinas. Y ahora, me mantienen vivo a mí. Pero nadie sabe nada sobre quiénes vivían aquí. Quizás, si estuviera en otra ciudad podría encajar, en alguna que no sea como la Villa.}
{228}{}{¿Qué piensas hacer ahora?}
{229}{}{No lo sé. No puedo esconderme para siempre, y no puedo correr a ningún lado. He escuchado sobre los rangers, y de los chatarreros de al lado. Para llegar hasta allá, necesitaré suministros. (risa irónica) De ninguna forma podré conseguirme eso en la Villa.}
{230}{}{Si te traigo suministros, podrías irte y no volver nunca.}
{231}{}{¡Ya lo sé! Puede que sea lo que siempre he querido, pero me daba miedo admitirlo. Casi toda nuestra gente decidió ignorar al mundo exterior. Han vivido así durante décadas, y están listos a lanzarle piedras a cualquier cambio. Quiero ser libre, compadre. ¡Dame una oportunidad!}
{1231}{}{¡Ya lo sé! Puede que sea lo que siempre he querido, pero me daba miedo admitirlo. Casi toda nuestra gente decidió ignorar al mundo exterior. Han vivido así durante décadas, y están listos a lanzarle piedras a cualquier cambio. Quiero ser libre, señorita. ¡Dame una oportunidad!}
{232}{}{Claro, te traeré suministros para el viaje. Espérame aquí.}
{233}{}{No. Este es tu hogar. Mereces un castigo. Prepárate, porque regresaremos a la Villa.}
{234}{}{Primero, cuéntame la historia completa.}
{1234}{}{Primero, cuéntame la historia completa.}
{235}{}{Para darle suministros a Chris, usa el objeto en su personaje.}
{236}{}{Eso debería ser suficiente para que llegues al pueblo más cercano.}
{237}{}{Eso espero. Vamos por aire fresco, quiero echar un vistazo una última vez antes de irme.}
{238}{}{Vámonos.}
{239}{}{[Escolta a Chris a la plaza de la Villa]}

#GG takes Chris away from the location:
{240}{}{Hablemos afuera.}
{241}{}{Vamos.}
{242}{}{No te preocupes por mí, encontraré el camino.}
{243}{}{De acuerdo.}
{244}{}{Escolta a Chris a la salida de las ruinas y luego regresa a la Villa.}
{245}{}{¡Vamos, haz lo que tengas que hacer!}
{1245}{}{¡Vamos, haz lo que tengas que hacer!}
{246}{}{Es mejor que te calles.}
{247}{}{Mira, a mí tampoco me gusta esto.}

#Low INT
{250}{}{Eh, ¿tú también?}
{251}{}{¡Oye! ¿¡Cómo eso!?}
{252}{}{Malo.}
{253}{}{¡Bueno! ¡Mí encontrar comida!}
{254}{}{¡Tú malo! ¡Aplastar!}
{255}{}{¡Comida! ¡Aquí!}
{256}{}{Adelante.}
{257}{}{Bueno.}
{258}{}{Ajá.}