{101}{}{Ves a uno de tus paisanos. Su cuerpo está cubierto de heridas.}
{102}{}{Ves a uno de tus paisanos. Gracias a tu tratamiento, ha empezado a mejorar.}
{103}{}{Esto está más allá de tus habilidades, necesitas encontrar medicina.}
{104}{}{Esto necesita una cirugía.}

{105}{}{Muchísimas gracias, compadre. Me siento mejor.}
{106}{}{Muchísimas gracias, compadre. Me siento mejor.}
{107}{}{Eh, gracias compadre, me siento mejor. Pero, no confío en la medicina del Viejo Mundo.}
{108}{}{La medicina de ese forastero funciona mejor que nuestras cataplasmas. ¡Pero no me quejo!}

{1105}{}{Muchísimas gracias, señorita. Me siento mejor.}
{1106}{}{Muchísimas gracias, señorita. Me siento mejor.}
{1107}{}{Eh, gracias señorita, me siento mejor. Pero, no confío en la medicina del Viejo Mundo.}
{1108}{}{La medicina de ese forastero funciona mejor que nuestras cataplasmas. ¡Pero no me quejo!}

{110}{}{Creo que me... quebraron las costillas...}
{111}{}{Eres fortachón. No vas a quebrarme el resto de mis costillas, ¿no?}

{200}{}{¡Mi salvador!}
{1200}{}{¡Mi salvadora!}
{201}{}{Cuídate.}
{202}{}{Mientras te trataba, dijiste que desconfías en la medicina vieja. ¿Por qué?}
{203}{}{Según los ancestros, tenemos que desconfiar de cualquier cosa del Viejo Mundo. Nos dijeron que todo estaba maldito, que tenían espíritus y era peligroso. Pero, me salvaste la vida con esa cosa... ¿Estaré maldito?}
{204}{}{Al menos estás vivo. Debes descansar.}
{205}{}{Ese forastero sí que sabe lo que hace. ¡Jamás me había sentido así de bien! Pero los ancestros nos lo advirtieron, no debemos confiar en las cosas del Viejo Mundo. Ahora los demás pensarán que estoy maldito o algo así.}
{206}{}{Al menos sigues vivo. Debes descansar.}
{207}{}{¿Te sientes mejor?}
{208}{}{Pensé que ya estaba muerto, pero ahora me siento bien. Haces milagros, en el pasado, si alguien se quebraba un hueso ya lo dábamos por muerto. Tienes un don, no sé cómo no lo vimos antes.}
{209}{}{Lo importante es que sigues vivo. Debes descansar.}

{210}{}{¿Sabes qué hay en el mundo exterior? Ya sabes, afuera de la Villa.}
{211}{}{No sé mucho, jamás me he alejado. Y así me gusta. Habla con José, él sabe más, a veces trata con los forasteros.}
{212}{}{Tengo que emprender un viaje. ¿Tienes algo que me sea de ayuda?}
{213}{}{Ya te diste cuenta, no soy de mucha ayuda. Pero tengo esto... (mete la mano en su bolsillo y te entrega balas de distintos calibres). Se le cayó a uno de los saqueadores durante el asalto y las escondí. Ojalá que te sean de ayuda.}
{214}{}{Gracias.}
{215}{}{¿Conoces a alguien que haya salido de la Villa?}
{216}{}{Pero, ¿¡que sea de la Villa!? ¿A quién se le ocurriría abandonar su hogar e irse a caminar al desierto?}
{217}{}{Eh... sí, me pregunto quién haría eso. Tengo que irme.}

{218}{}{¡Eh!}
{219}{}{Me voy.}
