{100}{}{Ves a José.}
{101}{}{Ves a tu tío. Es normal que intente mantener una fachada alegre, pero esta vez no le está funcionando.}
{102}{}{Has tenido mejores días, José.}
{103}{}{Se ha agregado una nueva misión a tu Pip-Boy.}
{104}{}{¡Santa Catarina! ¿Por qué me asustas así? Esa armadura que tienes no tiene lugar en nuestra Villa.}
{105}{}{Se te metieron los demonios del yermo. Abandona nuestra Villa y déjanos en paz.}
{1105}{}{Se te metieron los demonios del yermo. Abandona nuestra Villa y déjanos en paz.}

{120}{}{*Silba*}
{121}{}{*Suspira*}
{122}{}{Ay, ay, ay...}
{123}{}{Eh...}
{124}{}{Y... ¿Qué hacemos ahora, eh?}

# added by cambragol
{199}{}{«Ay, güey.» ¡Me alegra tanto que sigas con vida! Ay, ay, ay, malditos saqueadores. Tuviste suerte de no estar acá.}
# First Dialogue
{200}{}{Ay compadre, ahí estás. ¡Me alegra tanto que sigas con vida! Ay, ay, ay, malditos saqueadores. Tuviste suerte de no estar acá.}
{1200}{}{Ay señorita, ahí estás. ¡Me alegra tanto que sigas con vida! Ay, ay, ay, malditos saqueadores. Tuviste suerte de no estar acá.}
{201}{}{Cuéntame lo que pasó, tío.}
{202}{}{Esos hijos de su madre nos rodearon cuando menos lo esperábamos. Agarraron a algunos de inmediato, pero otros alcanzaron a esconderse en sus casas. Tu papá junto a los demás hombres intentaron resguardarse en el ayuntamiento. Hubo que sacarlos a la fuerza, y el tiroteo estuvo bien fuerte. Todavía hay unos muertos ahí dentro; ya no queda nadie que pueda enterrarlos.}
{203}{}{Cuéntame más.}
{204}{}{Luego se llevaron a todos a la plaza, como si fueran borregos. Primero apartaron a los fuertes y encerraron a los demás en sus hogares.}
{205}{}{¿Qué pasó después?}

{206}{}{Los bandidos no se fueron a tomar la siesta, porque saquearon la Villa y se pasaron la noche bebiendo. Cuando amaneció, agarraron a nuestra gente y se fueron al yermo, hacia el este. Desde ese entonces que todo está muy silencioso, todavía nos estamos recuperando.}
{207}{}{¿Quiénes eran los asaltantes?}
{208}{}{Dijiste que fueron hacia el este. ¿Podrías especificar?}
{209}{}{¿Por qué secuestraron a los demás?}
{210}{}{Y yo debo encargarme de esto, supongo.}
{211}{}{Eran un grupo con gente de todos lados. Pude reconocer a un par de Ciudad Garaje, pero no conocía al resto.}
{212}{}{El único lugar que conozco por allá es Ciudad Garaje, seguramente pasen la noche ahí.}
{213}{}{Bueno, no le contaron sus planes a tu tío José. Lo más seguro es que los pongan a trabajar. No sé en dónde ni para qué.}
{214}{}{¿Qué hay de mis padres?}
{215}{}{Lo siento, pero igual se los llevaron. Sólo quedaron los viejos y los niños.}
{216}{}{Tenemos que hablar en serio, José. Necesito saber lo que ocurrió.}
{217}{}{¡Bastardos!}
{218}{}{¡Oh!}
{219}{}{[Escucha]}

{220}{}{¡Ese es el espíritu del valiente guerrero que necesitamos! ¿Qué harás ahora? ¿Vas a rastrear a los saqueadores? Se fueron hace rato.}
{1220}{}{¡Ese es el espíritu de la valiente guerrera que necesitamos! ¿Qué harás ahora? ¿Vas a rastrear a los saqueadores? Se fueron hace rato.}
{221}{}{¿Qué crees?}
{222}{}{Para empezar, necesito que me repitas lo que ocurrió en el asalto.}
{223}{}{Bueno, primero querrás ir a Ciudad Garaje. Es un lugar desagradable, pero seguro que los saqueadores pasarán por ahí. Habla con la gente de por allá, si les refrescas la garganta, seguro que algo te dicen.}
{224}{}{¿Refrescarles la garganta?}
{225}{}{Ya sabes, invítales una cerveza. Pero ten cuidado con la gente de allá, si les sale rentable, venderían hasta a su mamá. Llévate unas frutas y algo de harina de maíz, te vendrá bien para el viaje y seguro que hablarán si le ofreces esto a cambio.}
{226}{}{Gracias, José.}
{227}{}{No es nada. Los saqueadores se llevaron todo lo que encontraron. Eso es lo último que tengo y te lo doy a ti, úsalo sabiamente.}
{228}{}{¿Eso es todo? Pues, gracias. Supongo.}
{229}{}{Óyeme, los saqueadores se llevaron todo, eso es lo único que tengo. Úsalo bien.}
{230}{}{No me basta, José. Necesito más.}
{231}{}{¿En serio no le vas a dejar nada para comer a tu tío favorito? Chale, toma un poco más. Pero es todo lo que puedo darte, los saqueadores nos lo quitaron casi todo.}
{232}{}{Los saqueadores se llevaron todo lo que encontraron. Te doy lo último que tengo, úsalo sabiamente.}
{233}{}{Parece que de ahora en adelante, tendré que arreglármelas por mi cuenta. ¡Adiós, Tío José!}
{234}{}{De acuerdo.}

{235}{}{¿Eh?}
{236}{}{Gia-shias.}
{237}{}{Okeei.}


{240}{}{¡Gracias al cielo, has vuelto! ¡Y trajiste a los demás!}
{1240}{}{¡Gracias al cielo, has vuelto! ¡Y trajiste a los demás!}
{241}{}{Sí, no fue nada fácil. Hay un mundo entero allá afuera, ¿sabes? Nadie me habló de él.}
{242}{}{Es mejor que te guardes eso, güey. Los forasteros tienen sus verdades y nosotros las nuestras. Nunca nos vamos a poner de acuerdo con ellos, es por eso que vivimos apartados. Nadie nos puede corromper ni imponernos sus reglas. Ya has visto lo que hizo ese asalto, no podemos dejar que eso ocurra otra vez, ¿cierto?}
{243}{}{Voy a pensar sobre esto, José.}

{244}{}{¡Ba-boom! ¡Gran bum! ¡Muya gente!}
{245}{}{Ajá.}
{246}{}{¡Gracias al cielo, has vuelto! ¡Y trajiste a los demás! Ni siquiera pude hablar contigo antes de que te fueras. ¡Sí que eres de otro mundo!}
{1246}{}{¡Gracias al cielo, has vuelto! ¡Y trajiste a los demás! Ni siquiera pude hablar contigo antes de que te fueras. ¡Sí que eres de otro mundo!}

# Repeated Dialogue
{250}{}{Me alegro de verte, compadre.}
{1250}{}{Me alegra de verla, señorita.}
{251}{}{No te quedes ahí parado, sobrino. Encuentra algo que hacer, ¿ya?}
{1251}{}{No te quedes ahí parada, sobrina. Encuentra algo que hacer, ¿ya?}
{252}{}{Tengo que irme.}

{253}{}{Tengo algunas preguntas... No, tengo muchas preguntas.}
{254}{}{Pregúntame lo que quieras.}
{255}{}{Hay un mundo más allá de la Villa. ¿Qué sabes de él?}
{256}{}{¿Sabías que había un alijo secreto en los sótanos de la Villa?}
{257}{}{¿Quieres venir conmigo?}
{258}{}{Vamos.}
{259}{}{Cambiemos de tema.}

{260}{}{Un yermo salvaje y desértico. Hay caníbales al norte, un ciudad de basura al este, además de unos pueblitos y puestos de los Rangers. He escuchado que hay una gran ciudad, pero nunca he ido más allá de Ciudad Garaje.}
{261}{}{¿No crees que nuestro conocimiento del mundo exterior es... Muy pobre?}
{262}{}{¿Qué, no te basta saber que hay saqueadores? ¿O caníbales? ¿O chatarreros? No, no. Nosotros dejamos a los extraños afuera, y tenemos una buena razón para hacerlo. No se puede confiar en los forasteros. La mayoría no tiene familia, ni hogar. En el yermo, la gente no vive. Sobrevive.}
{263}{}{¿Te vas a quedar ahí parado, o tienes algo que preguntarme?}
{264}{}{}
{265}{}{Cuéntame sobre los salvajes.}
{266}{}{Los llamamos Chacales. Son tan salvajes que ya ni saben hablar. La gente dice que se comen a las personas. Por suerte, somos muy duros para ellos, pero los chatarreros de la ciudad de al lado solían hablar de ellos, y con miedo. Así que mantén la distancia de esos salvajes.}
{267}{}{¿Quiénes son los Rangers?}
{268}{}{Son tipos duros, se creen muy gallos. Según, nos protegen de los malhechores, ¿pero quién sabe qué andan tramando realmente? A veces vienen a presumir, pero nos las arreglamos sin su ayuda... Aunque, la verdad es que ahora mismo nos vendría bien una ayudita.}
{269}{}{¿Hay alguien que se haya ido de nuestro valle?}
{270}{}{Pues... Sí, tu Tío Miguel. Tuvo una discusión con tu viejo y se fue de la Villa. Hace años que no oímos de él.}
{271}{}{¿Por qué se pelearon?}
{272}{}{Tuvieron una discusión acerca de cómo debería la Villa tratar con los forasteros. Uno pensaba que deberíamos echarlos, el otro que deberíamos hacer negocios con ellos. Jamás llegaron a un acuerdo, pero ambos tenían buenos puntos.}

{273}{}{¿Miguel dijo hacia dónde se fue?}
{274}{}{Él dijo que quería visitar esa gran ciudad de la que hablan las leyendas. Pero seguro que lo único que encontró fue la muerte entre las arenas.}
{275}{}{}
{276}{}{}

{277}{}{Háblame sobre la ciudad vecina.}
{278}{}{Ciudad Garaje. Es un lugar podrido, con gente podrida. Se hacen llamar chatarreros. Se dedican a hurgar entre las ruinas, buscando alguna cosa que sea valiosa. Pero ten cuidado con ellos, ninguno es de confianza.}
{279}{}{¿Cómo sabes sobre Ciudad Garaje?}
{280}{}{Güey, acá en la Villa soy el que comerciante principal con los forasteros. ¿Cómo crees que sé? A veces vienen caravanas de allá, hablamos un poco y luego se van.}
{281}{}{No parece que ese lugar te importe mucho.}
{282}{}{Ya conoces a tu tío José - me tratas bien y yo te trato igual, no hay pedo. Pero esos tipos... ellos te engañan, intentan robarte o dicen algo feo. Y encima piensan mal de nosotros. Nos tienen envidia porque vivimos mejor que ellos.}
{283}{}{}
{284}{}{}
{285}{}{}
{286}{}{Jeje.}
{287}{}{(niega con la cabeza con una obvia tristeza) Ay, sobrino, el condenado yermo te ha hecho muy mal, ¿cierto? ¿Aún tienes algo de piel, no? Bueno, eso ya es algo. No te preocupes, aún estamos contigo. Al fin y al cabo, somos de la misma sangre... O bueno, al menos, solíamos serlo.}
{1287}{}{(niega con la cabeza con una obvia tristeza) Ay, sobrina, el condenado yermo te ha hecho muy mal, ¿cierto? ¿Aún tienes algo de piel, no? Bueno, eso ya es algo. No te preocupes, aún estamos contigo. Al fin y al cabo, somos de la misma sangre... O bueno, al menos, solíamos serlo.}
{288}{}{Te lo agradezco, José. Me las arreglaré, de alguna manera.}
{289}{}{¿Tienes algún problema, normalucho? No necesito tus condolencias, así que cállate.}
{290}{}{Ah, so así que la Abuela Adonisia te ha estado contando cuentos de terror, ¿verdad? Jeje. Olvídalo, ahí abajo solo hay ratas y harina podrida.}
{290}{}{¿De qué hablas? Ahí guardamos el grano. Ah, ya sé, la abuela Adonisia te llenó la cabeza con cuentos viejos, ¿cierto? Jaja, olvídalo, ahí no hay nada.}
{291}{}{¿Y cómo me explicas este mono y esta computadora en mi muñeca?}
{292}{}{¿Eh? ¿Las encontraste debajo del ayuntamiento, no? Pues, pregúntale a tu viejo. José no sabe nada.}
{1292}{}{¿Eh? ¿Las encontraste debajo del ayuntamiento, no? Pues, pregúntale a tu viejo. José no sabe nada.}
{293}{}{No te hagas, José. Es obvio que sabes algo.}
{294}{}{¡Córtala, sobrino! Sólo soy un comerciante con la pata chueca, a mí no me cuentan sus secretos. Sí, sabía que tu viejo tenía un alijo secreto en el sótano y que tenía reliquias familiares. Pero no es asunto mío, ¿entendiste?}
{1294}{}{¡Córtala, sobrino! Sólo soy un comerciante con la pata chueca, a mí no me cuentan sus secretos. Sí, sabía que tu viejo tenía un alijo secreto en el sótano y que tenía reliquias familiares. Pero no es asunto mío, ¿entendiste?}
{295}{}{Te seguiría a cualquier lado, pero tengo la pata chueca y con mi edad, no voy a llegar lejos. Ánimo, te irá bien por tu cuenta. Yo creo en ti, somos familia, ¿no?}
{296}{}{José, no parece que estés feliz.}
{297}{}{¿Cómo?}
{298}{}{Pues, es sólo que... ha pasado tanto que... Ah, no importa, olvídalo.}
{299}{}{No eres feliz, José. No puedes estarlo. Ha muerto gente, esclavizaron a los demás, la Villa está en ruinas... Deja de fingir que sonríes.}
{300}{}{(le tiembla el labio) Sobrino... Por qué me dices eso...}
{1300}{}{(le tiembla el labio) Sobrino... Por qué me dices eso...}
{301}{}{Anda... Déjalo salir.}
{302}{}{Está bien, José. Es normal, no es necesario que lo retengas...}
{303}{}{Gracias, Tío José. Significa mucho para mí.}
{304}{}{¡No te preocupes! ¡Las cosas van a salir bien!}
{305}{}{Eso espero. Volvamos a mis preguntas.}
{306}{}{Solo quería darte las gracias por el apoyo. Lo agradezco mucho, Tío José.}
{307}{}{Oye, ¡ya basta de esto! Sólo soy un comerciante con la pata chueca, a mí no me cuentan sus secretos. Los ancianos no me comparten sus secretos.}
{308}{}{Está bien, cambiemos de tema.}

#Quests
{310}{}{¿Puedo ayudar en algo antes de irme?}
{311}{}{¿Quieres ayudar a reconstruir la Villa? De alguna forma nos las vamos a arreglar, lo tuyo es más importante.}
{312}{}{¿Qué más?}
{313}{}{Por la plantación hay unos extraños, probablemente sean merodeadores. Creo que lo mejor sería echarlos.}
{314}{}{¿Algo más?}
{315}{}{Pues, los saqueadores se chingaron la estación meteorológica, hay que arreglarla. Quizás hayan partes en Ciudad Garaje, o puedes intentar repararla así sin más.}
{316}{}{Veré que puedo hacer.}
{317}{}{}
{318}{}{Esos merodeadores de la plantación ya no son un problema.}
{319}{}{¡Órale! Sin tu ayuda, puede que eso haya terminado mal. La Villa es afortunada de tenerte.}
{320}{}{Adiós.}
{321}{}{He reparado la estación meteorológica.}
{322}{}{¡Genial! No lo hubiéramos conseguido sin ti. Gracias.}
{323}{}{Nos vemos.}

#Gambling
{350}{}{Sé que te gustan las apuestas, tío. ¿Quieres jugar?}
{351}{}{¡Ay, no! Antes que nada, tienes que salvar a nuestra gente. Y cuando estén sanos y salvos en la Villa, pues será un gusto tirar los dados contigo.}
{352}{}{De hecho, eso es justo de lo que quería hablar contigo.}
{353}{}{Tienes razón, no debería perder el tiempo.}
{354}{}{Pues, me mataste todas las ganas de jugar.}
{355}{}{Bueno, ya que regresó nuestra gente, podría divertirme un rato. Pero recuerda, que sea tu tío no significa que te vaya a dejar ganar.}
{356}{}{Genial, coloquemos el tablero y los dados...}
{357}{}{Hmm, puede que no sea el momento. Mejor hablemos.}
{358}{}{Este no es el momento, juguemos luego.}
{359}{}{Acabas de derrotar a uno de los mejores apostadores de la Villa, lo que ha mejorado tus habilidades.}
{360}{}{}
{361}{}{Perdiste. No es la primera vez y no será la última.}
