{110}{}{¿Los malos ya no van a volver? ¿En serio?}
{111}{}{. . .}
{112}{}{Tu servoarmadura asusta a los habitantes locales.}

{200}{}{(la niña observa tu armadura metálica en un silencio indeciso, entre el terror y el asombro)}
{201}{}{Saludos, pequeña. De ahora en adelante, el Gigante de Hierro será tu protector. Los malos ya no volverán.}
{1201}{}{Saludos, pequeña. De ahora en adelante, la Gigante de Hierro será tu protector. Los malos ya no volverán.}
{202}{}{(sus ojos se ponen como platos mientras te admira, y sale corriendo a contarles a todos la leyenda del Gigante de Hierro)}
{1202}{}{(sus ojos se ponen como platos mientras te admira, y sale corriendo a contarles a todos la leyenda de la Gigante de Hierro)}
{203}{}{Ya no tienes nada que temer, pequeña. Estás bajo mi protección.}
{204}{}{Muy bien, sal corriendo y cuéntale a todos.}
{205}{}{[Ignórala y sigue con tu vida]}

{210}{}{¿Qué estás mirando! ¡Sigue mirándome mal y te aplastaré!}
{211}{}{¡Ahhh! ¡El Diablo! ¡El Diablo!}
{212}{}{¿Diablo? Ay, esta nueva generación, están mal de la cabeza...}
{213}{}{}
{214}{}{[Ignórala y sigue con tu vida]}
