{100}{}{Ves a Hidalgo, el anciano.}
{101}{}{Ves a uno de los ancianos del pueblo.}
{102}{}{Eres nuestro héroe y salvador. Siempre te querremos y amaremos.}
{1102}{}{Eres nuestra heroína y salvadora. Siempre te querremos y amaremos.}
{103}{}{Le harías un favor a todos si abandonas la Villa. No vuelvas nunca.}
{104}{}{Buena suerte en tu viaje. Eres el hijo de Andrés y María, nunca olvides tus raíces.}
{1104}{}{Buena suerte en tu viaje. Eres la hija de Andrés y María, nunca olvides tus raíces.}
{105}{}{¿Qué clase de broma es esta? ¡Aléjate, demonio de acero!}

# First dialogue
{200}{}{(Estás viendo al anciano Hidalgo; está masticando algo mientras anda medio dormido, como siempre)}
{201}{}{Hm. ¿Querías hablar conmigo, anciano?}
{202}{}{Ah... }
{203}{}{...Hrrm... que... eh... mm... aquí...}
{204}{}{Mira, si dejas de mascar tabaco, quizás entienda lo que quieras decirme.}
{205}{}{(Lo escupe y se limpia la boca con su mano huesuda) Te digo... que los demás te quieren en la reunión. Pensamos que ya es hora de que nos digas lo que piensas.}
{206}{}{¿Qué reunión?}
{207}{}{Hay decisiones que debemos tomar. Salvar a los demás no será nuestro último problema, joven.}
{1207}{}{Hay decisiones que debemos tomar. Salvar a los demás no será nuestro último problema, jovencita.}
{208}{}{¿A qué hora se reunirán todos?}
{209}{}{Esta noche, cuando no haya sol y se haya trabajado. A los mayores como yo nos gusta tomarlo con calma, así que no esperes que termine rápido.}
{210}{}{Entonces vendré a esa hora. Nos vemos.}
{211}{}{Bueno, tengo que ir.}
{212}{}{Mejor espero aquí. ¿Qué tal si jugamos a los dados para pasar el rato?}
{213}{}{Yo estaré esperando. No hay prisa.}

{220}{}{, recuerdas que tenemos reunión, ¿verdad?}
{221}{}{Por supuesto, seré puntual.}
{222}{}{Ya cayó el sol. Es la hora.}
{223}{}{¿Qué tal si jugamos a los dados? Será más entretenido esperar así.}
{224}{}{Voy a esperar.}
{225}{}{Llegaste tarde, ya están todos dormidos.}
{226}{}{Hr-r-r... snrk... khhr-khhr-khhr...}
{227}{}{Está dormido. No valdrá la pena levantarlo...}


vbnet
Copy code
{200}{}{(Estás viendo al anciano Hidalgo; está masticando algo mientras anda medio dormido, como siempre)}
{201}{}{Hm. ¿Querías hablar conmigo, anciano?}
{202}{}{Ah... }
{203}{}{...Hrrm... que... eh... mm... aquí...}
{204}{}{Mira, si dejas de mascar tabaco, quizás entienda lo que quieras decirme.}
{205}{}{(Lo escupe y se limpia la boca con su mano huesuda) Te digo... que los demás te quieren en la reunión. Pensamos que ya es hora de que nos digas lo que piensas.}
{206}{}{¿Qué reunión?}
{207}{}{Hay decisiones que debemos tomar. Salvar a los demás no será nuestro último problema.}
{208}{}{¿A qué hora se reunirán todos?}
{209}{}{Esta noche, cuando no haya sol y se haya trabajado. A los mayores como yo nos gusta tomarlo con calma, así que no esperes que termine rápido.}
{210}{}{Entonces vendré a esa hora. Nos vemos.}
{211}{}{Bueno, tengo que ir.}
{212}{}{Mejor espero aquí. ¿Qué tal si jugamos a los dados para pasar el rato?}
{213}{}{Yo estaré esperando. No hay prisa.}

{220}{}{, recuerdas que tenemos reunión, ¿verdad?}
{221}{}{Por supuesto, seré puntual.}
{222}{}{Ya cayó el sol. Es la hora.}
{223}{}{¿Qué tal si jugamos a los dados? Será más entretenido esperar así.}
{224}{}{Voy a esperar.}
{225}{}{Llegaste tarde, ya están todos dormidos.}
{226}{}{Hr-r-r... snrk... khhr-khhr-khhr...}
{227}{}{Está dormido. No valdrá la pena levantarlo...}

{230}{}{La reunión está a punto de empezar.}
{231}{}{La reunión ha acabado.}
{232}{}{¿Ya estamos todos? Muy bien. Necesitamos la opinión de cada uno de ustedes.}

# First meeting
{250}{}{Como todos han visto, estamos en tiempos difíciles.}
{251}{}{[Seguir]}
{252}{}{Más allá del valle, existe un mundo que jamás habíamos imaginado. Los forasteros han descubierto nuestras cosechas. Tarde o temprano, tanto ladrones como comerciantes vendrán por una parte de lo que es nuestro.}
{253}{}{[Seguir]}
{254}{}{Debemos estar listos para su llegada. ¿Recuerdan lo fácil que los saqueadores invadieron y secuestraron a nuestra Villa? Ni siquiera el Señor Andrés pudo contra ellos dentro del ayuntamiento. (La sala se llena de murmullos de ira.)}
{255}{}{[Seguir]}
{256}{}{Bajen la voz. Sé que estamos a nuestro límite, pero todavía hay esperanza. Nos hemos recuperado de eso, nuestros hogares siguen en pie y pronto las plantaciones nos volverán a dar fruta. Todavía hay un poco de tiempo.}
{257}{}{[Seguir]}
{258}{}{(Una voz de la muchedumbre: "¿Qué haremos, viejo? El primer saqueador que venga nos hará pedazos.") Lo sé, lo sé... ¡Cálmense! No es tan malo como parece. }
{259}{}{, sube. Acércate, siéntate acá...}
{260}{}{[Da un paso adelante]}
{261}{}{Aquí tenemos a nuestro salvador. }
{1261}{}{Aquí tenemos a nuestra salvadora. }
{262}{}{ los liberó a todos de las cadenas de la esclavitud. Ahora, él nos ayudará a proteger a nuestras familias de los extranjeros...}
{1262}{}{ los liberó a todos de las cadenas de la esclavitud. Ahora, ella nos ayudará a proteger a nuestras familias de los extranjeros...}
{263}{}{Hola, chicos. ¿Qué tal?}
{264}{}{Estoy feliz de verlos a todos.}
{1264}{}{Estoy feliz de verlos a todos.}
{265}{}{}
{266}{}{(Se escucha a alguien refunfuñar entre la multitud, y se levanta: "Viejo, deja de mamársela. Podríamos haber salido de esa nosotros mismos. Todos sabemos que él no tiene madera de líder. Esto no cambia nada.") ¡Silencio! Sé que a muchos de ustedes no les agrada }
{1266}{}{(Se escucha a alguien refunfuñar entre la multitud, y se levanta: "Viejo, deja de mamársela. Podríamos haber salido de esa nosotros mismos. Todos sabemos que ellla no tiene madera de líder. Esto no cambia nada.") ¡Silencio! Sé que a muchos de ustedes no les agrada }
{267}{}{, pero les pregunto, ¿qué habrían hecho ustedes sin su ayuda? Además, no estamos aquí para hablar de esto.}
{1267}{}{, pero les pregunto, ¿qué habrían hecho ustedes sin su ayuda? Además, no estamos aquí para hablar de esto}
{268}{}{No los tomes en cuenta. Deben sentirse intimidados.}
{269}{}{No importa, Hidalgo. No cambiemos de tema, ¿bien?}
{270}{}{(Otra persona se levanta: "No sé que piensen los demás, pero yo te lo agradezco, }
{271}{}{. Hay muchos que pensamos que eres un sucesor digno a tu padre.") ¿Escuchaste eso, }
{1271}{}{. Hay muchos que pensamos que eres una sucesora digna a tu padre.") ¿Escuchaste eso, }
{272}{}{? Puedes ver la confianza que te has ganado.}
{273}{}{Lo entiendo, pueden contar conmigo.}
{274}{}{Así me gusta, carajo. Yo les mostraré quién manda.}
{275}{}{(Escuchas a otro de tus paisanos: "Viejo, se lo agradecemos, obvio, pero sabes que no es el momento de colocarle un altar. }
{276}{}{ hizo lo que tenía que hacer. ¿Podemos dejarlo así?") Estás en lo cierto. Pero no olvides quién te sacó de la prisión.}
{1276}{}{ hizo lo que tenía que hacer. ¿Podemos dejarlo así?") Estás en lo cierto. Pero no olvides quién te sacó de la prisión.}
{277}{}{Por favor, compadres, no podemos distraernos.}
{278}{}{Los ayudo y esto es lo que recibo a cambio. Típico.}

{280}{}{Nuestro problema es respecto al Señor Andrés, la esclavitud y su largo viaje por el desierto de verdad lo han desgastado. Ya no puede alejarse mucho de la Villa y apenas puede encargarse de ella. }
{281}{}{, tendrás que hacerte cargo de algunos de sus deberes. Tu padre ya cargó con esa responsabilidad, es tu turno.}
{282}{}{Por supuesto. Me he preparado para este momento durante toda mi vida.}
{1282}{}{Por supuesto. Me he preparado para este momento durante toda mi vida.}
{283}{}{Eh, ¿bromeas, cierto? Oye, papá, ¿qué está pasando?}
{284}{}{También lamento compartir una triste noticia. El señor Andrés, el padre de su salvador, murió durante su encarcelamiento. (la multitud queda boquiabierta) De acuerdo a las reglas de nuestra comunidad, su descendiente tomará su lugar. }
{285}{}{, es tu turno de liderar a la Villa.}
{286}{}{Por supuesto. Me he preparado para este momento durante toda mi vida.}
{1286}{}{Por supuesto. Me he preparado para este momento durante toda mi vida.}
{287}{}{¿En serio? ¿Así sin más?}

{290}{}{Tu madre estaría orgullosa de ti. Es una pena que ya no esté con nosotros. (la multitud se toma un momento se silencio, quitándose sus gorros)}
{291}{}{No se depriman, muchachos. A ella le gustaría que sigan sonriendo.}
{292}{}{Que conste que yo no tuve nada que ver con eso.}
{293}{}{Tu madre ya ha aprobado tu paso al liderazgo. Está ocupada atendiendo a la Villa, lo que quiere decir que tú, }
{294}{}{, tendrás que ocuparte de todo lo demás.}
{295}{}{Me encargaré de todo lo necesario.}
{296}{}{Por fin, ya empiezan a tomarme en serio.}

{300}{}{(El viejo Pablo se hace oír entre la multitud) ¡Es demasiado pronto para dejar que este chico dirija la Villa! ¡No nos hagas reír, Hidalgo! (otro campesino se pone de pie) ¡No es la hora de preocuparse de semejante mamarrachada! ¡Tienes que decirnos cómo lidiar con los esclavistas! (otro aldeano alza la voz) ¿Se enteraron de lo que pasa con los chatarreros de al lado? ¡Nuestra vida es pacífica, y eso podría ser el fin de ella!}
{1300}{}{(El viejo Pablo se hace oír entre la multitud) ¡Es demasiado pronto para dejar que este chico dirija la Villa! ¡No nos hagas reír, Hidalgo! (otro campesino se pone de pie) ¡No es la hora de preocuparse de semejante mamarrachada! ¡Tienes que decirnos cómo lidiar con los esclavistas! (otro aldeano alza la voz) ¿Se enteraron de lo que pasa con los chatarreros de al lado? ¡Nuestra vida es pacífica, y eso podría ser el fin de ella!}
{301}{}{¡Cálmense, todos!}
{302}{}{Esto ya parece un circo...}
{303}{}{(La sala se llena de susurros hasta que Hidalgo levanta la mano) ¡Ya basta! ¡Dejen de hacer tanto ruido! Ya llegaremos a eso, pero uno a la vez, por favor. }
{304}{}{, te toca hablar.}
{305}{}{El viejo Pablo está igual de paranoico que siempre. Tendré que referirme a sus quejas.}
{306}{}{Los esclavistas son nuestro mayor problema en este momento.}
{307}{}{Ciudad Garaje está lleno de víboras, ¿pero cuál es el problema con los chatarreros, exactamente?}

{310}{}{"Oye, Pablo, ¿acaso no te basta con que haya salvado a la aldea? ¿Qué más quieres?" - "Cállate la boca, Hidalgo. Deja que hable por sí mismo. Liderar la Villa no es lo mismo que lidiar contra algunos esclavistas."}
{311}{}{¿Con qué más nos vas a impresionar? Recuerda que somos los ancianos.}
{312}{}{He salvado la Villa, con eso ya deberían confiar en mí. Es hora de que los ancianos se hagan a un lado.}
{313}{}{Pablo, te quejas demasiado y me estás poniendo de los nervios. Ya dije todo lo que tenía que decir.}
{1313}{}{Pablo, te quejas demasiado y me estás poniendo de los nervios. Ya dije todo lo que tenía que decir.}
{314}{}{Es suficiente.}
{315}{}{¡Y esto es justo a lo que me refiero - la imprudencia! Los jóvenes no entienden qué significa ser el líder de una comunidad. No conocen nuestras reglas ni nuestra historia. ¿En serio podemos confiarle nuestro legado a una persona así? (descontento general)}
{316}{}{[Más]}
{317}{}{Pero, al final, esto es decisión de todos. Yo ya dije mi opinión.}
{318}{}{Hmm... Ya entiendo con quién estoy tratando. A ti te importa nuestra aldea y su gente. Podemos confiar en ti, pero sólo si escuchas a los ancianos como nosotros. (se gira a ver a los demás) ¡Estoy de acuerdo con esto! (la multitud empieza a festejar)}
{319}{}{[Más]}
{320}{}{Los saqueadores destruyeron la estación meteorológica, pero mientras ustedes no estaban, conseguí arreglarla.}
{1320}{}{Los saqueadores destruyeron la estación meteorológica, pero mientras ustedes no estaban, conseguí arreglarla.}
{321}{}{¿Qué? Ah, la estación meteorológica... Estábamos en peligro, ¿en serio era prioritario arreglarla? Aunque, es cierto que la estación es importante, en especial ahora que nuestras reservas de comida se están agotando. De todas formas, la gente estaba en problemas.}
{322}{}{No había forma de que José lo hubiera conseguido, ya sabes cómo tiene la pierna.}
{323}{}{Bueno, también tuve que ahuyentar a algunos merodeadores. Estaban intentando conseguir lo poco que quedaba de nuestras cosechas.}
{1323}{}{Bueno, también tuve que ahuyentar a algunos merodeadores. Estaban intentando conseguir lo poco que quedaba de nuestras cosechas.}
{324}{}{Y lo consiguieron, porque agarraste la harina del granero y se la diste. (la multitud demuestra su descontento)}
{1324}{}{Y lo consiguieron, porque agarraste la harina del granero y se la diste. (la multitud demuestra su descontento)}
{325}{}{Pero se fueron sin herirnos, ¡eso es lo que importa!}
{326}{}{Sí. Y esa fue la decisión correcta.}
{327}{}{Eso está bien. En estos momentos, estamos racionando cada grano a nuestra disposición. Al fin y al cabo, los merodeadores no podrían haberse llevado tanto. Y los hubiéramos ahuyentado nosotros, eventualmente.}
{328}{}{Sólo estás especulando, ni siquiera estabas ahí.}
{329}{}{No seas así, los merodeadores hubieran entrado al granero y robado todo mientras estabas armándote de valor. Montón de malagradecidos, denme las gracias.}
{330}{}{Durante el asalto, al menos uno de los nuestros fue herido, pude ayudarlo.}
{1330}{}{Durante el asalto, al menos uno de los nuestros fue herido, pude ayudarlo.}
{331}{}{Y todos sabemos lo que pasó con eso. El Fundador sí tenía una razón para prohibirnos el uso de los remedios antiguos - son peligrosos. La mitad son venenos, e incluso si no lo son, si llegas a tratar a alguien con estos medicamentos sus descendientes podrían estar malditos. Lo que hiciste fue imprudente, pero admito que alguien pudo sobrevivir gracias a ti.}
{332}{}{Lo que hice era necesario, debemos salvar vidas siempre que se pueda.}
{333}{}{¡Al diablo con tus tabús del 'Viejo Mundo'!}
{334}{}{Hay gente que sobrevivió gracias a ti, podrán ayudarnos a reconstruir la aldea. Te lo agradezco, pero primero te deberías haber enfocado en salvar a aquellos que fueron esclavizados.}
{335}{}{Puedes ver que pude lidiar con ambas cosas.}
{336}{}{Dejarte contento es imposible, anciano.}
{337}{}{El Pequeño Edén casi estuvo en problemas, estaba rodeado por unos coyotes y apenas pude sacarlo de allí.}
{338}{}{Nos enteramos de eso. Fuiste valiente, de eso no hay ninguna duda. Pero, no creo que de verdad haya necesitado ayuda. Podría haber sobrevivido con las hojas del elote por un tiempo, eventualmente le habría dado hambre y así hubiera vuelto a la Villa por su cuenta. Ese niño no es tonto.}
{339}{}{Dudo que eso hubiera acabado así.}
{340}{}{Eres un viejo amargado, sólo sabes especular.}

{350}{}{(Se hace oír otra voz entre la multitud) Espera un momento, anciano. Ni siquiera hemos mencionado a Chris. Ese bastardo era un traidor y se merecía unos buenos azotes. ¡Pero se escapó gracias a }
{351}{}{! ¿Quién sabe qué clase de problemas está provocando en el yermo? A lo mejor le cuenta a los demás de nuestros secretos.}
{352}{}{Eh, escuchen...}
{353}{}{Sí, eso fue todo un desastre. ¿Cómo dejaste que eso pasara, }
{354}{}{? Si un hombre le da la espalda a su pueblo, sólo hay una forma de solucionarlo - y esa forma es dura y rápida. Tienes el corazón de pollo y no eres una persona adecuada para liderarnos. ¿Qué tienes que decir en tu defensa, }
{355}{}{?}
{356}{}{Le hice caso a mi consciencia.}
{1356}{}{Le hice caso a mi consciencia.}
{357}{}{¿Lo ven? ¡Has puesto a toda la aldea en riesgo, gracias a tu pinche consciencia! (la multitud empieza a molestarse y su enojo se empieza a hacer aparente)}
{358}{}{No seas así...}
{359}{}{No puedo creer que hayan estado planeando en hacerle eso a uno de los nuestros.}
{360}{}{Los amigos y la familia deberían de cuidarse entre sí, el que merece un azote eres tú por la actitud que tienes contra Chris. Debería darte vergüenza.}
{361}{}{(Se hace silencio en el salón, se ve que están avergonzados) Bueno... Eso es debatible. Mejor no digo nada.}
{362}{}{Exacto.}
{363}{}{(Se oye otra voz entre la multitud) Espera un momento, viejo. No olvides que }
{364}{}{ persiguió a Chris y lo trajo acá. Chris fue un traidor y se ganó lo que le pasó, pero si no hubiera sido por }
{1364}{}{ persiguió a Chris y lo trajo acá. Chris fue un traidor y se ganó lo que le pasó, pero si no hubiera sido por }
{365}{}{, se habría escapado para siempre. Imagínese lo que le hubiera dicho a los forasteros.}
{366}{}{[Continuar]}
{367}{}{Eso mero. Un líder no puede permitirse ser débil, hay que castigar a los traidores.}
{368}{}{[Continuar]}

{370}{}{(Se escucha otra voz) ¡Oigan! ¿Y qué hay de esa cosa de metal en la que }
{371}{}{ siempre anda? Da miedo y asusta a los niños. ¡No nos hace falta una reliquia como esa por acá!}
{372}{}{Se llama servoarmadura y me ha mantenido con vida.}
{373}{}{(El viejo Hidalgo da un estirón al despertarse de la siesta) Tienen un punto válido, }
{374}{}{. Nuestro Fundador nos advirtió que no deberíamos usar la tecnología del Viejo Mundo. Es lo que hizo estallar la Gran Guerra hace cien años. Hemos hecho lo posible para no usar ese tipo de basura y por buena razón. Y ahora la traes y haces como si no ocurriera nada malo.}
{375}{}{A ustedes no hay nada que los haga felices.}
{376}{}{Esta armadura me ha salvado la vida unas cuántas veces, puede que también pueda salvar a la Villa.}
{377}{}{Hmm... quizás tengas razón, pero aún así - no deberías andar asustando a tu propio pueblo. De por sí, ya tenemos muchos problemas con los que lidiar.}
{378}{}{Bueno...}
{379}{}{¿Qué hay de malo con la tecnología antigua si puede protegernos? Eso no tiene sentido.}
{380}{}{¡El Fundador era consciente de la tecnología del Viejo Mundo era capaz de hacer! ¿Te crees más inteligente que nuestros ancestros? (la multitud empieza a abuchearte: "Boo")}
{381}{}{A ustedes no hay nada que los deje contentos, es imposible.}
{382}{}{(Otra voz más se hace escuchar) ¡Esperen! ¿No diremos nada acerca de la bestia metálica que}
{383}{}{ usa para andar por el desierto? Esa cosa no sólo levanta una tormenta de arena, sino que también hace llorar a los niños del miedo. ¡No la necesitamos!}
{384}{}{¿Hablas de mi motocicleta? Me sería muy difícil viajar largas distancias sin ella.}
{385}{}{(Hidalgo se levanta y hace una señal a la multitud) ¿Alguien más quiere decirle algo a nuestro campeón? ¿Ninguna otra queja? Si ese es el caso, que levante la mano el que esté de acuerdo con que }
{1385}{}{(Hidalgo se levanta y hace una señal a la multitud) ¿Alguien más quiere decirle algo a nuestro campeón? ¿Ninguna otra queja? Si ese es el caso, que levante la mano el que esté de acuerdo con que }
{386}{}{ se haga líder de la Villa.}
{387}{}{Aquí vamos...}
{388}{}{No puedo creer que esto esté ocurriendo...}
{389}{}{El voto ha sido un éxito, casi todos votaron por ti. Enhorabuena, }
{390}{}{.}
{391}{}{Ay, no sabía cómo iba a terminar esto...}
{392}{}{Eso era justo lo que esperaba}
{393}{}{Menos de la mitad, pero, de todas formas, }
{394}{}{, tendrás que esforzarte más si quieres ganarte nuestra confianza. Pero por decreto del Fundador, únicamente sus descendientes pueden liderarnos. Un atraso no cambiará eso.}
{395}{}{No tengo problema con eso. No hay prisa.}
{396}{}{Son unos viejos pendejos, todos y cada uno de ustedes.}

{400}{}{Me parece que ya tratamos los problemas más urgentes. Tengo cosas más importantes que hacer.}
{401}{}{Sí, así es. Estaremos esperando a tu regreso. Buena suerte, }
{402}{}{. Que el viento corra contigo, no en tu contra.}
{403}{}{[Sal de la reunión]}

{410}{}{(tu madre se levanta de su asiento) Mientras trabajaba en la guarnición, pude oír a los mercenarios conversar. Dijeron que la demanda de esclavos iba a seguir subiendo, nada nos garantiza que no volverán por nosotros.}
{411}{}{(un campesino se levanta de su asiento) Mientras trabajaba en la guarnición, pude oír a los mercenarios conversar. Dijeron que la demanda de esclavos iba a seguir subiendo, nada nos garantiza que no volverán por nosotros.}
{412}{}{[Siguiente]}
{413}{}{(un campesino se levanta de su asiento) }
{414}{}{(Sancho se levanta de su asiento) }
{415}{}{Tienes razón, lo único que hicimos fue escapar del corral. No estaremos a salvo mientras las minas sigan en pie. Yo digo que deberíamos destruirlas.}
{416}{}{¿Cómo propones que deberíamos destruir las minas?}
{417}{}{Sé que en las minas hay algo llamado "explosivos". Pueden "explotar" y derribar un chingo de rocas. Yo creo que en la mina deben haber guardados suficientes de esas cosas como para colapsar la entrada de la mina.}
{418}{}{Estás demente. ¿Quieres que vuelva ahí para sabotearlos? Es muy peligroso.}
{419}{}{(Hidalgo mastica una hoja de tabaco, pensativo) ¿Se te ocurre una mejor idea? ¿No? Pues piénsatelo y dinos tu solución la siguiente vez que nos veamos. Pero no te tardes.}
{420}{}{Bueno.}
{421}{}{Me gusta esa idea, haré volar a la mina por los aires.}
{422}{}{(hay una celebración entre la multitud, están de acuerdo) ¡Órale! ¡Hazla explotar! ¡Hazlo!}
{423}{}{Está decidido. Lo haré.}
{424}{}{Déjame pensar, quizás pueda encontrar algún acuerdo con el dueño de la mina.}
{425}{}{(Todos en la sala se miran entre sí, algo dudosos) ¿Eso crees? Hmm, pues bueno, por ahora, el Consejo se inclina más para el sabotaje. Debes pensártelo bien.}
{426}{}{De acuerdo.}
{427}{}{(Hugo se levanta para hablar) }

{430}{}{Los mercaderes nos han contado rumores de que los chatarreros de Ciudad Garaje andan arreglando una fábrica antigua, están pensando en producir máquinas. ¡Imagínense lo que eso significa para nuestra Villa!	}
{431}{}{[Siguiente]}
{432}{}{José, ándale, cuéntales. (José se levanta) Sí, claro... }
{433}{}{Nos convertiremos en un punto entre las rutas de caravanas. Van a llegar oleadas de trabajadores y con ellos van a llegar saqueadores, armas y alcohol. No podremos resistirnos ante esos cambios; simple y llanamente, vamos a desaparecer.}
{434}{}{¿Estás sugiriendo que deberíamos detener sus planes de la fábrica?}
{435}{}{Si la fábrica depende de sus máquinas, entonces debemos destruirlas. No sé cómo hacer eso, pero los que regresaron de Flagstaff hablaron de unas cosas llamadas 'explosivos' que pueden destruir montañas de rocas, si hacen eso, seguro que vuelan por los aires a las máquinas. No hace falta destruir la fábrica entera.}
{436}{}{Estoy en buenos términos con los chatarreros, no quiero declararles la guerra.}
{437}{}{No sé si quiero declararle la guerra a los chatarreros. ¡Son nuestros vecinos!}
{438}{}{¡No son amigos nuestros, para nada! Ayudaron a los saqueadores que nos esclavizaron. ¿Cómo vas a querer estar en buenos términos con esos hijos de su madre? En todo caso, no podemos permitir que la fábrica se desarrolle. Si se te ocurre otra opción, pues haz algo. Pero nadie va a acoger a esos rechazados por acá.}
{439}{}{Comprendo.}
{440}{}{Han traicionado a sus vecinos, por lo que los chatarreros merecen caer. Voy a destruir su maldita fábrica.}
{441}{}{(se oye que la mayoría está de acuerdo) ¡Esoooo! ¡Destrúyela y dale a esos cochinos chatarreros lo que se merecen!}
{442}{}{Cuenten conmigo.}
{443}{}{Los chatarreros se esfuerzan para eso y tú quieres quitárselo. Deberíamos encontrar un compromiso.}
{444}{}{¿Un compromiso con los chatarreros? Son mercaderes astutos y tramposos de nacimiento. El Consejo no aprueba ese tipo de tácticas.}
{445}{}{Bueno, voy a pensar en qué hacerle.}

{450}{}{Oye, anciano. Lo hice, la mina de Flagstaff fue destruida.}
{451}{}{¿Hm? Oh... Así que lo conseguiste. Buen trabajo. Bueno, ojalá que todo salga bien.}
{452}{}{Es hora de lidiar con la fábrica de Ciudad Garaje...}
{453}{}{Quiero informarte que la mina de Flagstaff ya no es ningún problema. Ahora usan una máquina y eso reduce el número de esclavos que necesitan.}
{454}{}{¿Una máquina, dices? Así que - ¿es una máquina del Viejo Mundo? Oh, eso es una mala señal. ¿Quién podría decirnos cuánto tiempo funcionará o si Faber tendrá otros planes? Pero el hecho de que ya no necesite esclavos, es bueno.}
{455}{}{Tendré que ir a hacer un trato con la fábrica de Ciudad Garaje...}
{456}{}{Traigo noticias - la máquina de la fábrica en Ciudad Garaje ha sido destruida.}
{457}{}{¿Hm? Ah... Que buenas noticias. No hay por qué despertar a ese viejo demonio... Ya estábamos bien sin esa fábrica.}
{458}{}{Es hora de que me encargue de la prisión en Flagstaff...}
{459}{}{No hace falta que destruyamos las máquinas de Ciudad Garaje, el líder de la fábrica nos ha ofrecido términos favorables para restaurar la Villa.}
{460}{}{Oh... Pero, ¿de qué estás hablando? ¿Nos propones que formemos una alianza con los chatarreros? Hay muchos a los que eso no les gustará para nada. Por otro lado, su labor sería de mucha ayuda y beneficiaría muchísimo a la Villa.}
{461}{}{Iré a lidiar con la mina en Flagstaff.}
{462}{}{Ya hemos resuelto ambos problemas, es hora de llamar a los demás para otro Consejo.}
{463}{}{(piensa por un largo tiempo y asienta con la cabeza) De acuerdo... Pero ahora, tendrás que hablar con los ancianos}
{464}{}{Eh, vale...}
{465}{}{}
{466}{}{, te estamos agradecidos porque nos libraste de nuestros enemigos. El viejo Hidalgo nos dijo que Ciudad Garaje y Flagstaff ya no presentan una amenaza. Al fin y al cabo, eran nuestros adversarios más cercanos y peligrosos.}
{467}{}{Por fin, podemos tomar un respiro.}
{468}{}{Oh, no, me temo que no es así. Tú, tu padre y varios otros ancianos han viajado lejos de casa. Sabemos cómo puede ser el mundo y sin protectores, seremos un blanco fácil para cualquier saqueador.}
{469}{}{Entonces debemos encontrar un aliado, o hacernos tan fuertes que los demás nos tomarán en serio.}
{470}{}{Como ya lo sabes, nuestras tradiciones son de campesinos y no permiten que siquiera toquemos la tecnología antigua. Sabemos cómo cosechar, pero no cómo pelear. Nos hace falta un protector y los únicos que pueden tomar ese puesto son los Rangers. Habla con ellos y habla con el General Mossman, debes negociar con él para que proteja a la Villa a cambio de una parte de nuestra cosecha.}
{471}{}{Que así sea, cumpliré con la voluntad del Consejo.}
{472}{}{No me gusta la idea de tener aliados.}
{473}{}{Tal es la voluntad del Consejo. Dependemos de ti para que se cumpla.}
{474}{}{Pueden contar conmigo.}
{475}{}{Espero que recen para que su voluntad no lleve a que la Villa se arrodille ante otros. Adiós.}
{476}{}{Te oímos, }
{477}{}{. Cuéntanos cómo están las cosas con nuestros enemigos.}

{480}{}{¿Has podido hablar con el general de los Rangers? ¿Cuál fue su respuesta?}
{1480}{}{¿Has podido hablar con el general de los Rangers? ¿Cuál fue su respuesta?}
{481}{}{No he podido verlo, pero todavía tengo la esperanza de poder conseguirlo.}
{482}{}{Hace poco llegó un embajador de la Hermandad del Acero a la Villa. Es arrogante y orgulloso, lo que ya ha cansado a los demás aldeanos. Queremos que nos lo digas directamente, ¿qué significa esto? ¿Qué quieren?}
{483}{}{Estabas buscando un aliado que nos protegiera. Ahí lo tienes, son lo mejor que encontrarás.}
{484}{}{Sabemos de la Hermandad del Acero, pues tu padre aprendió de ellos cuando lo tomaron esclavo. Nos dijo que si no fuera por la Hermandad, no habría una colonia en Flagstaff, ni el Culto del Fuego, ni la esclavitud en Two-Sun. ¿Por qué has traído a esa bestia a nuestro hogar? Nos obligará a trabajar para ella.}
{485}{}{Debemos hacernos amigos de la bestia si no queremos que nos trague, no nos harán daño mientras les demos parte de la cosecha. Además, nos protegerán y ayudarán con la tecnología.}
{486}{}{(silencio tenso) Eres la persona que lidera nuestra comunidad, así que hacia donde vamos, depende de ti. Si ves que el futuro de la Villa yace en este camino, que así sea. No podremos resistirnos a tu voluntad. Ya no es posible.}
{487}{}{No lo veas así. Se quedaron en el pasado y hace tiempo que la Villa necesitaba el cambio. La alianza con la Hermandad es el principio de algo nuevo y lo importante es que no debemos perder esa oportunidad. Debo irme.}
{488}{}{¿Esto es cosa tuya, verdad? Hace poco, llegó un embajador de los Rangers.}
{489}{}{Sí, los Rangers están listos para formar una alianza para proteger la Villa.}
{490}{}{Dame un momento, antes de explicarte las cosas, debo pensarlas bien...}
{491}{}{Los Rangers sólo fingen que les importamos, pero lo cierto es que sólo les preocupa asegurar una fuente de comida. No dejaremos que se pasen de la raya de nuestro contrato.}
{492}{}{Mientras estemos bajo su protección, debemos fortalecer nuestra posición y hacernos más fuertes, así podremos defendernos por cuenta propia.}
{493}{}{(está de acuerdo contigo, a pesar de estar en silencio) Esta es una historia que escribes para ti mismo y nuestras futuras generaciones. La Villa te tiene como líder y hacia dónde se dirige, es elección tuya. A nosotros los ancianos no nos queda mucho tiempo, pero nos alegra que la Villa esté en manos capaces.}
{494}{}{Lo importante es que no podemos permitir que seamos manipulados. Debo irme.}
{495}{}{Los Rangers ya no podrán formar una alianza con nosotros, fueron derrotados.}
{496}{}{No pude conversar las cosas con los Rangers. De hecho, creo que quieren matarme.}
{497}{}{En ese caso, estamos condenados. No podremos defendernos de nuestros enemigos por cuenta propia.}
{498}{}{Pero, Flagstaff, y Ciudad Garaje...}
{499}{}{Sabes muy bien que eran sólo los síntomas de un problema más grande. Aquellos que sostienen el destino de Sonora en sus manos siguen estando bien atrincherados en el sur. Y no soltarán lo que les pertenece.}
{500}{}{¿De quiénes estás hablando?}
{501}{}{Tu padre nos contó que los Hojalateros y los Seguidores del Fuego sólo eran marionetas controladas por la Hermandad del Acero. Encuentra a esta Hermandad y deténlos antes de que sea demasiado tarde. No regreses a la Villa hasta que lo hayas hecho.}
{502}{}{De acuerdo, lo haré.}
{503}{}{Los ancianos de verdad son estúpidos, perdiste la cabeza por completo.}
{504}{}{¿Estás hablando de la Hermandad del Acero?}
{505}{}{Los Hojalateros y los Seguidores del Fuego sólo eran marionetas controladas por la Hermandad del Acero. Encuentra a esta Hermandad y ponles fin antes de que sea demasiado tarde. No regreses a la Villa hasta que hayas hecho esto.}
{506}{}{He destruido la nave de la Hermandad del Acero, no podrá viajar una sola legua más.}
{1506}{}{He destruido la nave de la Hermandad del Acero, no podrá viajar una sola legua más.}
{507}{}{¡Eres un héroe y nadie podría superarte, de eso no cabe duda! Las ciudades ya no cuentan ni con la Hermandad ni con los Rangers, por lo que caerán al caos y no podrán prosperar.}
{1507}{}{¡Eres la protectora de la Villa, de eso no cabe duda! Las ciudades ya no cuentan ni con la Hermandad ni con los Rangers, por lo que caerán al caos y no podrán prosperar}
{508}{}{Esta es nuestra oportunidad para levantarnos, nos haremos tan fuertes que podremos defendernos de nuestros enemigos por cuenta propia.}
{509}{}{Ahora, todos podemos ver que la Villa está en buenas manos. Eres nuestro líder y de eso no cabe duda, el futuro de nuestra gente está seguro entre tus manos.}
{510}{}{La clave es evitar que nos manipulen. Tengo que irme.}
{511}{}{Esto es terrible, si los Rangers son nuestros enemigos, tendremos que hallar otro aliado.}
{512}{}{De acuerdo, intentaré encontrarnos otro aliado.}
{513}{}{Quizás pueda sabotear su presa para que podamos echarlos hacia atrás, al menos durante un tiempo.}
