{100}{}{Ves a un emisario.}
{101}{}{Ves al emisario de los Rangers.}
{102}{}{Puede dar terminada nuestra alianza, emisario.}
{103}{}{Estás bajo nuestra protección.}

# First dialogue
{200}{}{Hola, guerrero. Entonces, ¿eres a quien le debemos la alianza? Sí que eres lo mejor de lo mejor. Ahora puedes relajarte y seguir con tu vida de siempre. Nosotros, los rangers, mantendremos la paz adentro y afuera de la Villa.}
{1200}{}{Hola, guerrera. Entonces, ¿eres a quien le debemos la alianza? Sí que eres lo mejor de lo mejor. Ahora puedes relajarte y seguir con tu vida de siempre. Nosotros, los rangers, mantendremos la paz adentro y afuera de la Villa.}
{201}{}{Pensé que nos enviarían más rangers.}
{1201}{}{Pensé que nos enviarían más rangers.}
{202}{}{No te preocupes, no estoy sólo. Los demás andan patrullando y explorando el área. Si es necesario, los llamaré por la radio.}
{203}{}{Entonces agradezco su servicio, emisario. Debo irme..}
{204}{}{Más vale que ese sea el caso, sino, nuestra alianza habría acabado antes de que empezase siquiera.}

{210}{}{Saludos.}
{211}{}{Adiós.}
