{100}{}{Ves a un Señor Mañoso.}
{101}{}{Ves a un robot del modelo 'Señor Mañoso'.}

# First dialogue
{200}{}{¡Por fin! Hace mucho tiempo que no veo un ser humano. Incluso mis circuitos neurales se ven afectados por tantos años de soledad... ¿Quién eres?}
{201}{}{Soy }
{202}{}{ de la Villa. ¿Pero quién...? Mejor dicho, ¿*Qué* eres?}
{203}{}{Perdón, joven. Verás, técnicamente soy una máquina del Viejo Mundo. Pero lo importante es que poseo la personalidad de tu ancestro, Félix Tejada. Que no te sorprenda, habían muchos robots iguales que yo por todo el continente.}
{1203}{}{Perdón, jovencita. Verás, técnicamente soy una máquina del Viejo Mundo. Pero lo importante es que poseo la personalidad de tu ancestro, Félix Tejada. Que no te sorprenda, habían muchos robots iguales que yo por todo el continente.}
{204}{}{¡Esto es sorprendente!}
{205}{}{Debes tener muchas preguntas. Las responderé, pero a cambio también quiero saber unas cosas.}
{206}{}{Sí, tengo mucho que preguntarte.}
{207}{}{Primero quiero echar un vistazo. Hablamos luego.}

{208}{}{«Perdón, mi niño.» Verás, técnicamente, soy una máquina del Viejo Mundo. Pero lo importante es que poseo la personalidad de tu ancestro, Félix Tejada. Que no te sorprenda, habían muchos robots iguales que yo por todo el continente.}
{1208}{}{«Perdón, mi niña.» Verás, técnicamente, soy una máquina del Viejo Mundo. Pero lo importante es que poseo la personalidad de tu ancestro, Félix Tejada. Que no te sorprenda, habían muchos robots iguales que yo por todo el continente.}


{210}{}{¡Ay! Hace mucho que no sentía la luz del sol, se siente bien.}
{211}{}{Me alegra verte, mi niño. Déjame verte más de cerca.}
{1211}{}{Me alegra verte, mi niña. Déjame verte más de cerca.}
{212}{}{Adiós.}
{213}{}{Tengo algunas preguntas que hacerte.}
{214}{}{¿Qué quieres saber, pequeño?}
{1214}{}{¿Qué quieres saber, pequeña?}
{215}{}{No tengo más dudas.}
{216}{}{Tengo otra pregunta.}
{217}{}{Esperando instrucciones.}
{218}{}{Esto es triste... Yo le dije al Supervisor que no era posible seguir viviendo aquí.}
{219}{}{Cada vez me sorprende más cómo la gente hace lo posible para meterse en problemas. Para eso estamos, ¿no?}

{220}{}{¿Por qué te escondieron aquí adentro?}
{221}{}{Antes de fallecer, mi última orden fue que escondieran toda nuestra tecnología antigua. Cuando traje a la comunidad a nuestra tierra prometida, los artefactos del Viejo Mundo nos ayudaron a sobrevivir. Pero con el tiempo, empezó a fallar.}
{222}{}{¿Y qué pasó?}
{223}{}{No teníamos nada con qué reparar las máquinas, y ningún lugar en donde encontrar repuestos o fuentes de energía. Por lo que habría sido necesario buscar entre las ruinas, pero eran peligrosas debido a la radiación, aventurarse en ellas hubiera afectado la salud de los habitantes. Además, con el tiempo, la gente perdió el conocimiento del Viejo Mundo, y la ignorancia siempre lleva a los errores.}
{224}{}{Sigue, te escucho.}
{225}{}{Decidí que sería mejor proteger a mis descendientes de peligros así, por lo que prohibí toda tecnología antigua y eléctrica. Y tu presencia me confirma que esa decisión salvó a la comunidad.}
{226}{}{Eso es una decisión interesante.}
{227}{}{¿Qué es este lugar?}
{228}{}{¿La cripta? Parece que durante la preguerra funcionaba como un desecho ilegal de residuos tóxicos, o quizás sólo era un búnker. En todo caso, nos escondimos aquí adentro durante las tormentas de polvo hasta que la Villa floreció.}
{229}{}{Ya veo.}
{230}{}{¿Me puedes contar cómo nació la Villa?}
{231}{}{Es una historia triste y larga... Para ser sincero, no conozco todos los detalles. Parece que pasó algo de lo cual Félix no quería hablar. Pero es obvio - tiene algo que ver con el Refugio 27, cerca de Fénix. Quizás valga la pena investigarlo.}
{232}{}{Hmm...}

{233}{}{¿Cómo debería llamarte? Eres... un robot.}
{234}{}{Tú solo llámame Félix. ¿Acaso no suena bien? En todo caso, tu ancestro me llamaba 'Mañoso'.}
{235}{}{Me gusta más 'Robot'.}
{236}{}{Bien, entonces te llamaré Mañoso.}
{237}{}{Como digas, abuelito Félix.}

{240}{}{¿Quieres viajar conmigo?}
{241}{}{¡Por supuesto, mi niño! Es hora de estirar las piernas. ¡Pero no corras tan rápido!}
{1241}{}{¡Por supuesto, mi niña! Es hora de estirar las piernas. ¡Pero no corras tan rápido!}
{242}{}{¡Vámonos, abue!}
{243}{}{Su asistente está listo, maestro.}
{244}{}{Vámonos, robot.}
{245}{}{Espérame aquí, ya vuelvo.}
{246}{}{Claro, aquí te espera el abuelo. No te preocupes, ve a jugar.}
{247}{}{No se te vaya a mojar el pañal, viejo.}
{248}{}{Entendido. Mantendré la posición hasta que indique lo contrario.}
{249}{}{Espérame ahí, robot.}
{250}{}{Apaga el módulo de personalidad.}
{251}{}{Enciende el módulo de personalidad.}
{252}{}{Se ha deshabilitado el módulo de personalidad.}
{253}{}{Mucho mejor.}
{254}{}{¡Ay, canijo! Estoy muy viejo como para que me revuelvan así el cerebro. ¿Qué falta por hacer?}
{1254}{}{¡Caray! Estoy muy viejo como para que me revuelvan así el cerebro. ¿Qué falta por hacer?}
{255}{}{Hola, abuelito.}
{256}{}{Enfunda tu arma.}
