{100}{}{Ves a Arthur Carrington.}
{101}{}{Estás viendo a un arqueólogo que lleva puesta una túnica sucia y rasgada. Se mantiene firme, a pesar de su apariencia desaliñada.}
{102}{}{¿Querías entrar al Refugio? ¡Puedes quedarte ahí, PARA SIEMPRE!}

{110}{}{Quiero vivir aquí, para siempre.}
{111}{}{¿Un laboratorio de la preguerra? ¿Y es funcional? ¡Esto es increíble! No puedo creer que no sabía de este lugar.}
{112}{}{Esto me da curiosidad, ¿será que la central eléctrica sigue operacional?}
{113}{}{¡Por todos los cielos! Estos bandidos se han asentado dentro de la central eléctrica, igual que las larvas en un cadáver.}
{114}{}{Debo estar soñando - ¡el valle está repleto de las tecnologías de la preguerra! ¡Esto es invaluable!}
{115}{}{Este lugar debe ser el centro de la Zona Prohibida, los robots han estado funcionando desde la Gran Guerra.}
{116}{}{No creo que estos tipos sólo lean libros. ¿Quiénes son?}

#Before the escape (in the reactor room)
{200}{}{Ya anticipaba que Fénix enviaría a un rescatista... Pero, ¿quién eres TU?}
{201}{}{Soy un campesino de la Villa. Mis ancestros están conectados a este refugio, de alguna forma. Y quiero averiguar el cómo.}
{1201}{}{Soy una campesina de la Villa. Mis ancestros están conectados a este refugio, de alguna forma. Y quiero averiguar el cómo.}
{202}{}{Me impresiona que hayas llegado tan lejos. ¿Sabes? He oído acerca de esa historia con la Villa, si quieres que te cuente los detalles, tendrás que ayudarme a terminar mi misión en este refugio.}
{203}{}{¿Qué viniste a hacer aquí?}
{204}{}{¿Así que eras *tú* la persona con la que hablaba en el intercomunicador? Bueno, has hecho un trabajo impresionante. Es una pena que no te haya conocido antes.}
{205}{}{Ya llegué demasiado lejos, no voy a arrepentirme de esto.}
{206}{}{Eso era justo lo que pensaba cuando lideré a la expedición a su último viaje. Y fue un error, como puedes ver.}
{207}{}{Cuéntame lo que pasó.}
{208}{}{Este no es el momento adecuado para ponernos a hablar, creo yo. Te contaré lo que ocurrió, pero primero, debo terminar lo que empecé.}
{209}{}{¿De qué estás hablando?}
{210}{}{No es el momento para ponernos a hablar, empaca tus cosas, ya nos vamos.}
{211}{}{Estoy completamente de acuerdo, pero primero, debemos terminar lo que empezamos.}
{212}{}{Debo infiltrarme en la oficina del supervisor. Esa habitación se encuentra un nivel más arriba. Así que sígueme y no perdamos el tiempo. Ah, cierto, me llamo Arthur Carrington. Es un gusto conocerte.}
{213}{}{¿Es necesario hacer esto...?}
{214}{}{Bien, pero no intentes nada raro.}

#Before the escape (at the overseer's post)
{220}{}{¡Maldita sea! Todo esto para un completo fracaso.}
{221}{}{¿Qué pasó? Te ves muy angustiado.}
{222}{}{¿Estás hablando sólo? A mí también me interesa.}
{223}{}{El Protocolo Cero.}
{224}{}{¿Protocolo... qué?}
{225}{}{¿Qué demonios es el Protocolo Cero?}
{226}{}{Estaba entre mis sospechas que esto acabaría así. Tantos años aislamiento llevaron al supervisor a la locura, por lo que empezó una cadena de procedimientos que destruirían el Refugio. El llamado "Protocolo Cero".}
{227}{}{Pero, una parte del equipo del refugio todavía funciona.}
{228}{}{Parece que tus planes fueron un poco más exitosos que los suyos.}
{229}{}{Sí, estás en lo correcto. Asumo que los moradores se resistieron a las acciones del supervisor y fueron capaces de detener algunos de los procedimientos. Salvaron sus vidas, pero se condenaron a muchos años de un terrible sufrimiento, y se volvieron una especie de muertos... vivientes... como zombis.}
{230}{}{Ya debían de estar sufriendo un tiempo antes de que eso ocurriera.}
{231}{}{Si nos quedamos aquí parados, vamos a acabar como ellos.}
{232}{}{Sí... claro... Mira, tengo que llegar a la superficie. Creo que ya no queda nada de valor en este sitio. Si estamos juntos, tendremos mejores posibilidades de salir de aquí con vida. ¿Puedes ayudarme?}
{233}{}{Vayámonos, te llevaré a la superficie.}
{234}{}{Muy bien. Puedes ir a la delantera. No seré de mucha ayuda en una pelea, pero cuidaré la retaguardia.}
{235}{}{Adelante.}

#During the escape
{250}{}{No perdamos el tiempo, salgamos de aquí.}
{251}{}{Vayámonos.}

{260}{}{¿Qué puedes contarme acerca de esta sala?}
{261}{}{Este es el nivel del reactor. En algún punto, el reactor se sobrecalentó y tuvo un momento crítico, lo que destruyó parte del nivel. Y por suerte, la roca nos protege de su intensa radiación.}
{262}{}{Este es el nivel de servicio, el centro de control del refugio y otros servicios de apoyo solían estar aquí. Me encantaría ver todo este esplendor tecnológico en su estado original.}
{263}{}{Este es el centro de educación. La biblioteca está en un estado electrónico, esto demuestra que nuestros ancestros poseían un ingenio asombroso.}
{264}{}{Este es el salón de entretenimiento, pero parece que debido a la sobrepoblación del refugio, lo utilizaron como habitaciones extra, más que para la recreación.}
{265}{}{Esta es la oficina del supervisor, el 'gerente' del refugio, por así decirlo. Desde este lugar, era posible controlar todos los sistemas del refugio. Aquí ya no funciona nada - parece que el supervisor destruyó todo el equipo utilizando una explosión de pulso electromagnético.}
{266}{}{Estamos en uno de los niveles residenciales, no hay mucho que ver aquí, además de las habitaciones.}
{267}{}{Tengo otra pregunta.}

{270}{}{Me has salvado. Sin ti, me habría quedado ahí adentro para siempre, quizás hasta hubiese estado condenado a transformarme en uno de esos... Zombis. Además, aún no se aparece el equipo de rescatistas de Fénix. Ah, ¡tengo en mente a algunas personas a las cuales hacerles una admonición!}
{1270}{}{Me has salvado. Sin ti, me habría quedado ahí adentro para siempre, quizás hasta hubiese estado condenado a transformarme en uno de esos... Zombis. Además, aún no se aparece el equipo de rescatistas de Fénix. Ah, ¡tengo en mente a algunas personas a las cuales hacerles una admonición!}
{271}{}{[Siguiente]}
{272}{}{Entonces, ¡tenemos que apresurarnos!}
{273}{}{En estos momentos, no puedo recompensarte de ninguna forma, pero tengo amigos en la Catedral del Fuego, así que al llegar les contaré de ti una vez que lleguemos a Fénix. Deberías darle una visita al lugar, si no lo has hecho. Pero, em... Necesitaré ayuda para llegar a Fénix. ¿Puedes acompañarme?}
{274}{}{Claro, vamos a Fénix. ¿Por qué no?}
{275}{}{Gracias, has vuelto a salvarme. Si vamos a viajar juntos, puedo llevar parte de tu equipamiento. Tampoco estoy en contra de tomar algunos desvíos, ya sabes... Para apreciar el panorama.}
{276}{}{Genial. Andando, Arthur.}
{277}{}{Hagas lo que hagas, no te vayas sin mí.}
{278}{}{Me encantaría tenerte en mi equipo, pero primero, quiero que cumplas con tu promesa y me des respuestas.}
{279}{}{He oído que hubieron problemas en la Catedral.}
{1279}{}{He oído que hubieron problemas en la Catedral.}
{280}{}{La verdad, es que no pienso ir a Fénix en estos momentos.}
{281}{}{No hay problema, déjame en el asentamiento más cercano y podré llegar a Fénix por mi cuenta. Tampoco estoy en contra de tomar algunos desvíos, ya sabes... Para apreciar el panorama.}
{282}{}{Bienvenido a mi equipo. Vamos, Arthur.}
{283}{}{Entonces, vas a ser mi brahmán de carga. Y no vayas a quejarte. ¡A moverse!}
{284}{}{Bienvenido a mi equipo. Es hora de que hablemos de las respuestas que me prometiste.}

# After the escape
{300}{}{¿Qué pasa?}
{301}{}{Bien, déjame ver estas ecuaciones... Ay, ¿de qué me perdí?}
{302}{}{Las respuestas nunca son suficientes.}
{303}{}{¿Necesitas más de mis sabios consejos?}
{304}{}{¿Ya llegamos a Fénix?}
{305}{}{Oye, la ruta que estás siguiendo es un poco rara.}
{306}{}{¿Qué necesitas?}
{307}{}{Mis planes ya se fueron al traste hace mucho tiempo.}
{308}{}{Podemos conversar si quieres, pero sólo si usamos términos en Latín.}
{309}{}{Es hora de irnos, Arthur.}

{310}{}{Me siento mal, quizás sea el veneno.}
{311}{}{Déjame ver... saca la lengua... Sube el brazo... Listo, ¿te sientes mejor?}
{312}{}{Sí... Gracias, Doc.}

# Questions
{320}{}{Tengo muchas preguntas para ti.}
{321}{}{Ah, eso es obvio. Y tengo muchas respuestas.}
{322}{}{Claro, pregunta lo que gustes.}
{323}{}{No tengo más preguntas.}
{333}{}{Tengo una pregunta más.}
{334}{}{¿En dónde está Fénix?}
{335}{}{Es... raro que no lo sepas. Muéstrame tu Pip-Boy, lo marcaré en el mapa.}
{336}{}{Gracias..}

{350}{}{Háblame de ti.}
{351}{}{¿No me he presentado? Soy Arthur Carrington, el líder de la expedición. Soy un científico independiente, por así decirlo.}
{352}{}{¿En dónde conseguiste tu educación?}
{353}{}{Mis padres me enseñaron habilidades computacionales y cómo leer. Eso no es nada común en estos lares, así que hay gente en Fénix que apreció lo que podía ofrecer. Una vez que la Iglesia del Fuego Santo llegó al poder, tuve oportunidades para hacer ciencia que sólo había visto en mis sueños.}
{354}{}{¿Quiénes fueron tus padres?}
{355}{}{Me parece que eran los descendientes de unos moradores de algún refugio, jamás me lo dijeron directamente.}
{356}{}{¿Por qué te embarcaste en la expedición?}
{357}{}{Los Seguidores del Fuego querían exploradores para obtener hallazgos más prácticos - tecnología antigua, fuentes de energía y armas. Soy un científico, por lo que vi un potencial más amplio. El refugio contenía los secretos del Viejo Mundo, los que podrían ayudar al Nuevo Mundo. No deberíamos tratar las reliquias antiguas a la ligera.}

{360}{}{Cuéntame qué le ocurrió a la expedición.}
{361}{}{Nos separamos en dos grupos - el primero iba a revisar el generador de respaldo y el segundo lo lideré yo, fuimos hacia el reactor. Todo fue cuesta abajo después de eso.}
{362}{}{¿Qué le pasó a tu grupo?}
{363}{}{Llegamos al nivel del reactor y empezamos a explorar. Y en ese entonces, nos atacaron los zombis. Apenas conseguí entrar a la sala del reactor. Tras eso, alguien desactivó el generador de respaldo. Un poco después, todo el grupo quedó... En silencio.}
{364}{}{Me suena a que estabas preocupado de salvarte a ti mientras tus hombres morían.}
{365}{}{Veo que no tomaron precauciones y se apresuraron.}
{366}{}{Cerca del reactor, encontré el cadáver de un mercenario, con una marca que sugería que le dispararon con un arma láser. Explícame eso.}
{1366}{}{Cerca del reactor, encontré el cadáver de un mercenario, con una marca que sugería que le dispararon con un arma láser. Explícame eso.}
{367}{}{¿Por qué sacas los trapos sucios de otra persona? Sí, no fui el único superviviente, pero él estaba herido. Estuvo gimiendo de dolor durante una hora y me volví loco. No sabía como ayudarlo, así que... Acabé con su sufrimiento.}
{368}{}{Cambiemos de tema.}
{369}{}{Ser precavido es lo que me permitió a llegar a esta edad. Y este refugio fue el único lugar en el que mis ambiciones dominaron mi mente. Sí, me apresuré. Al fin y al cabo, la expedición podría haber sido abandonada en cualquier momento. O peor, ¡podrían haber enviado a otra persona a que me reemplazaran!}

{370}{}{¿Qué sabes acerca de los 'zombis'?}
{371}{}{Diría que son los desafortunados resultados de las complicaciones que dejó el "Protocolo Cero": gases tóxicos, virus esparcidos por el aire, radiación, medicamentos, y más. Sus cuerpos quedaron suspendidos durante décadas, hasta que los despertamos. Sus mentes se pudrieron, lo único que quedó fueron sus instintos más primitivos.}
{372}{}{¿Te diste cuenta de que muté a algo similar?}
{1372}{}{¿Te diste cuenta de que muté a algo similar?}
{373}{}{Es similar, pero distinto. A primera vista, casi pensé que eras uno de ellos. Tienes una vida larga y extraña por delante.}

{380}{}{Quiero saber más acerca de cómo el Refugio está conectado a la Villa.}
{381}{}{Perdona, te mentí para que me rescataras. No sé nada acerca de la Villa o cómo las cosas del refugio acabó allí. Es probable que alguien haya dejado el refugio hace años y sus objetos hayan acabado en la Villa. Ocurre todo el tiempo.}
{382}{}{[Más]}
{383}{}{Tendrás que volver a bajar y buscar pistas por tu cuenta. Ten, puedes llevarte esta tarjeta de acceso, abrirá las puertas cerradas.}
{384}{}{No debiste haberme mentido. Es tu primer y último aviso.}
{385}{}{Al menos, agradezco la tarjeta. Iré a investigar.}
{386}{}{¿Tengo que volver a ese maldito infierno? Eso no será nada fácil.}
{387}{}{No hay por qué hacer eso ahora. Encontré algunos diarios y todo estaba explicado en ellos.}

{390}{}{¿Qué harás ahora?}
{391}{}{Voy a escribir un gran informe e intentaré sacarle más recursos al Culto para que así pueda completar la expedición. Me hará falta un equipo de guardias en los que pueda confiar para exterminar a los zombis, y un nuevo grupo de esclavos.}
{392}{}{Entiendo. Has lo que quieras.}
{393}{}{Ha muerto mucha gente debido a tu ambición. ¿En serio quieres seguir?}
{394}{}{Por duro que esto te parezca, la vida de los mercenarios y unos esclavos valen menos que el legado del Viejo Mundo. Estas tecnologías ya fueron olvidadas, ¡imagina las oportunidades que tendremos si Fénix puede conseguirlas!}
{395}{}{¿Y esa tecnología ayudó a los zombis del refugio?}
{396}{}{No, no los ayudó. ¿Y qué? Fue sólo la idiotez del supervisor del refugio.}
{397}{}{Bueno, como tú digas.}
{398}{}{La tecnología no salvó a los moradores de este refugio. Los condenó a vivir en el infierno mismo.}
{399}{}{¿A qué te refieres?}
{400}{}{La tecnología no puede salvar a una sociedad corrupta, sólo hará estallar guerras por el poder que puede dar.}
{401}{}{Hmm... Jamás lo había pensado así. Debido al Culto del Fuego, Fénix ha cambiado. La tecnología antigua nos beneficia, pero igualmente, nos divide... Quizás debería leer sobre la sociología.}
{402}{}{Es bueno que nos entendamos. Ahora, necesito que me respondas otras preguntas.}
{403}{}{Ya hablamos suficiente. Adiós.}
{404}{}{Me alegra que estés entendiendo mejor las cosas. Tengo otras preguntas...}

#THE CONSIGNMENT
{450}{}{Necesito tu ayuda, ven conmigo.}
{451}{}{Perdona, pero no. Te acompaña demasiada gente y eso podría arruinar mis planes.}
{452}{}{Hmm... Entiendo.}
{453}{}{Es hora de decir adiós. Desde hoy, estás por tu cuenta.}
{454}{}{¿Me vas a dejar aquí, después de todo lo que hemos hecho? Bueno. Voy a repasar mis notas hasta que cambies de parecer.}
{455}{}{Quédate aquí.}
{456}{}{Ya puedes quitarte tu armadura.}
{457}{}{Gracias, estaba muy apretada.}
{458}{}{Muy bien.}
{459}{}{Guarda tu arma.}
{460}{}{Lo que tú digas.}
{461}{}{Bien.}
{462}{}{Puede que volvamos a viajar juntos.}
{463}{}{Hemos llegado a Fénix, Q.E.D. Ojalá hubiera tenido más gente como tú acompañándome durante la expedición, de esa forma, no hubiera fallado.}
{464}{}{¿Qué piensas hacer ahora?}
{465}{}{Tengo mucho que hacer. Primero, debo hablar con mi cliente y entregar mi informe acerca de lo descubierto. Eso me llevará un par de días. Estaré ocupado hasta ese entonces.}
{466}{}{Bien, nos reagruparemos aquí en 24 horas.}
{467}{}{Saludos, mi salvador.}
{1467}{}{Saludos, mi salvadora.}
{468}{}{Adiós, Arthur.}
{469}{}{¿¡Qué demonios pasó aquí!? ¿¡La catedral fue destruida!? ¡No puedo creerlo!}

{470}{}{Ahí viene mi salvador. Me alegro de verte.}
{1470}{}{Ahí viene mi salvadora. Me alegro de verte.}
{471}{}{¿Cómo te fue en tu informe? No te ves muy emocionado.}
{472}{}{Ya no hay nadie a quién pueda darle mi informe. La Catedral del Fuego fue destruida. Ya no existe. No sé qué ocurrió, pero los Seguidores del Fuego ahora son un grupo de fugitivos, y nadie necesita a un científico como yo. Ni tampoco los resultados de mis meses de trabajo.}
{473}{}{¿Ahora qué?}
{474}{}{Hay una cosa que podría intentar, he oído que supuestamente hay una ciudad de científicos más al sur. Quiero buscarla, quizás encuentre... un hogar. Me gustaría viajar junto a ti, si planeas ir en esa dirección.}
{475}{}{¿Hacia el sur? Lo pensaré.}
{476}{}{Ah, por cierto. Pude conseguir un poco de Rad-X y estimulantes dentro del laboratorio. Quiero que te los quedes, es mi forma de darte las gracias por haberme rescatado.}
{477}{}{Gracias. Nos vemos.}
{480}{}{Creo que estamos en el lugar del que me hablaste.}
{481}{}{¡Sí, ya llegamos! Esta ciudad es como un oasis, aquí prospera la ciencia y el progreso. Incluso el aire se siente distinto. Es perfecto para mis investigaciones.}
{482}{}{Es hora de decir adiós.}
{483}{}{Así es. Déjame revisar mis cosas, puede que aún tenga algo que te pertenezca, así que mira bien. Quiero entrar a la ciudad y asentarme tan pronto como pueda.}
{484}{}{[Separarse]}
{485}{}{Estoy feliz de haberte conocido. Jamás pensé que alguien que vive en el yermo me enseñaría la lección más importante de mi vida: que debo valorar la vida humana. Solía dedicarme a la ciencia para obtener gloria y fortunas. Pero es el momento de que haga algo verdaderamente significativo.}
{486}{}{Adiós, Arthur.}
{487}{}{El cliente se enfureció al ver mi informe. Se me recriminó porque fui ineficiente y desperdicié recursos, incluso me amenazaron con quemarme en la hoguera. ¿Cómo iba a saber yo que el Refugio tendría esos... 'zombis', o que estaba así de destrozado? Me dijeron que los costos de la expedición no estaban justificados. ¡Malditos avaros! Parece que mi carrera científica se acabó.}
{488}{}{Me parece que están hablando de Casa Nueva. Será difícil llegar hasta allá.}

{489}{}{¿Y qué?}
{490}{}{Adiooos.}
{491}{}{¡Oh!}
{492}{}{Oki.}
{493}{}{Ir.}
{494}{}{Tú no ser necesitado.}
{495}{}{Esconder arma.}
{496}{}{Tú quitarte armadura.}
{497}{}{Eh.}
{498}{}{Ajá.}
{499}{}{Nadie.}
{500}{}{[Apunta a una máquina rota]}
{501}{}{¡Oh, z-zombis! ¡Mí no querer ser zombi!}
{502}{}{¿Aquí?}
{503}{}{}

# added to fix arthur recognizing Casa Nueva
{588}{}{Bueno, creo que me gustaría ir a Casa Nueva, ese sitio tiene algo que encanta. Podría hacer mi vida allí, podría tener un hogar. Si vas a ir hacia allá, me gustaría viajar contigo. }
{589}{}{Ya llegamos. Hogar, dulce hogar.}
