{102}{}{*Estática*}
{103}{}{Es complicado ponerte a hablar por el intercomunicador, estás en medio de una pelea.}

#First dialogue
{199}{}{¡La Villa y este sitio tienen un pasado en común! ¡Tengo que saber qué es!}
{200}{}{(escuchas una voz débil pero esperanzada a través del intercomunicador) ¡Hola! ¿Me escuchas? ¿Quién eres?}
{201}{}{Sólo vengo a... explorar.}
{202}{}{Eh, ¿tu voz viene de esta caja? Yo sólo estaba explorando.}
{203}{}{Demonios. Esperaba que Fénix enviaría a alguien para ayudarme... Bueno, dime, ¿por qué estás aquí? ¿Buscas algo?}
{1203}{}{Demonios. Esperaba que Fénix enviaría a alguien para ayudarme... Bueno, dime, ¿por qué estás aquí? ¿Buscas algo?}
{204}{}{Investigo la historia de mi pueblo, teníamos objetos del Refugio 27 en mi hogar, la Villa. Así que tuvieron que haber venido de aquí.}
{205}{}{La Villa... Sé en dónde está. Y sé cómo ayudarte.}
{206}{}{¡Maravilloso! ¿Cómo me ayudarás?}
{207}{}{No tan rápido. Primero, ayúdame a mí. Estoy atrapado en la planta baja y no puedo salir. Lo único que necesitas es encontrar el generador de emergencia en la planta residencial y encenderlo.}
{208}{}{Primero respondeme, tengo muchas preguntas.}
{209}{}{Em... Está bien, veré que puedo hacer.}

#Second dialogue
{210}{}{Me alegra que estés aquí, pero por favor, apresúrate. ¡Eres mi única esperanza!}
{211}{}{Tengo muchas preguntas.}
{212}{}{[Cuelga la llamada]}
{213}{}{Tengo otra pregunta.}

{214}{}{Genial. Si necesitas algo, usa el intercomunicador para hablarme.}
{215}{}{Está bien.}
{216}{}{El intercomunicador no responde.}
{217}{}{[Hecho]}
{218}{}{¡Gracias!}
{219}{}{De acuerdo.}

#Answers
{220}{}{¿De qué se trata?}
{221}{}{¿Quién eres?}
{222}{}{Soy Arthur Carrington, el líder de la expedición. Estábamos registrando el refugio por recursos. Seguramente ya viste nuestras cosas en la entrada.}
{223}{}{¿Cuánto tiempo puedes estar ahí abajo?}
{224}{}{No sabría decirte. Tengo comida y agua, se arregló un problema con la ventilación, pero no creo que dure mucho.}
{225}{}{¿Cómo funciona el intercomunicador? No hay corriente eléctrica.}
{226}{}{Los ingenieros del pasado eran unos listillos. Conectaron los intercomunicadores para que funcionen como un walkie-talkie con baterías muy duraderas. Justo para situaciones como esta.}
{227}{}{¿Qué debo saber antes de entrar al refugio?}
{228}{}{Está oscuro, no hay corriente. El aire es tóxico, así que una máscara de gas te ayudará. Y trae un arma... por si acaso.}
{229}{}{¿Por qué necesitaría un arma?}
{230}{}{Eh... Mejor prevenir que curar. Esto es un refugio muy viejo, ni siquiera yo conozco todos sus secretos.}
{231}{}{¡No me dijiste nada acerca de los monstruos!}
{232}{}{Básicamente son zombis, son los cadáveres podridos de los viejos moradores del refugio. Despertaron cuando bajamos, es difícil de creer que sigan vivos... si podemos llamarlo a eso 'vida'.}
{233}{}{¡Así que sí lo sabías!}
{234}{}{Lo lamento, tendría que haberte avisado, pero no podía arriesgarme a espantar a mi único rescate. Estoy atrapado aquí, ¿acaso no lo entiendes?}

#The rescue
{240}{}{¿Qué debería hacer?}
{241}{}{Encuentra algún generador de respaldo en la planta residencial y enciéndelo. Si necesita alguna célula de fusión, revisa el almacén, está un piso más abajo.}
{242}{}{Veo que ya encendiste el generador. Ahora busca el sistema de ventilación y ponlo a andar, está en el mismo piso. Eso ayudará con la toxicidad del aire.}
{243}{}{¿El aire está limpio? ¡Genial! Dirígete al piso de más abajo y encuentra el segundo elevador del centro de mando. Yo estaré esperándote en la planta baja. Si pasa algo, llámame por el intercomunicador.}
{244}{}{Tenemos un problema. Hay una turba de unas personas locas o enfermas, me bloquean el paso al elevador.}
{245}{}{Tenemos un problema. Hay un montón de zombis que no me dejan entrar al elevador.}
{246}{}{Ellos ya no son humanos, ni siquiera deben de pensar. Tienes que tener cuidado con ellos, no podemos arriesgarnos, es mejor evitarlos.}
{247}{}{¿Y si los distraemos?}
{248}{}{En eso pensaba... Registra las habitaciones e intenta activar algún equipo viejo para hacer ruido. Y evita a los zombis, por supuesto.}
{249}{}{De acuerdo.}
