{100}{}{Ves a John D. Butler.}
{101}{}{Ves a un necrófago con un traje de negocios desgastado.}
{102}{}{¿Tú ir a base militar? ¡Soldado Gomer querer ir!}

#Introduction
{200}{}{¡Hola! Parece que no nos hemos visto antes. Soy John Butler, fui electo como el alcalde de Dayglow. ¿Y tú eres?}
{201}{}{Es un placer, Butler. Soy }
{202}{}{, sólo soy otra pobre alma que ronda por el yermo.}
{203}{}{No intentes ser amable conmigo, necrófago.}
{204}{}{(suspiro) Jamás pensé que vería un mutante acusar a otro de ser un mutante.}
{205}{}{Sí que el yermo te lanza todo tipo de cosas.}
{206}{}{*¡Aten-ción!* Soy John Butler. Yo mando en este pueblo... o lo que queda de él. Y doy la bienvenida a cualquier piel suave que se comporte. *¡A las armas! ¡Dispárenles!*}
{207}{}{No tengo ninguna intención de causar problemas por aquí.}
{208}{}{Los humanos y los supermutantes nos echaron de nuestros hogares. Estoy seguro de que sabes eso. Pero no hay ninguna razón para odiar a todos, al contrario, quiero demostrar que los necrófagos son tan humanos como ellos... *¡Sigan disparando!*}
{209}{}{¿Intentas engañarme? Pensaba que los necrófagos odiaban a los normaluchos.}
{210}{}{Llegamos a vivir aquí porque los humanos y los supermutantes nos echaron de nuestros hogares. Pero no hay ninguna razón para odiar a todos, al contrario, quiero demostrar que los necrófagos son tan humanos como ellos... *¡Sigan disparando!*}
{211}{}{Parece que mantener la boca cerrada no es lo tuyo, John.}
{212}{}{Tienes razón. Este viejo soldado no tiene sentido del humor. Las viejas costumbres perduran, aún después de cien años. Bueno, ¿cómo te puedo ayudar?}
{213}{}{Por ahora, con nada, gracias.}
{214}{}{Eso es muy noble de tu parte.}
{215}{}{Al diablo con los ancianos como yo. Hemos sobrevivido a muchas guerras y batallas, nuestro destino está únicamente en el pasado. Lo que importa es lo que le ocurra a tu generación... *¡A la carga! ¡Adelante!* Bueno, ¿cómo te puedo ayudar?}
{216}{}{Sólo me pasaba para saludarte. Pero ya debo irme.}
{1216}{}{Sólo me pasaba para saludarte. Pero ya debo irme.}

{220}{}{Vaya, vaya, es nuestro viejo amigo, Gomer. ¿Y trajo un humano? ¡Eso es nuevo! Es como una serpiente haciéndose amigo de un conejo. Estoy felices por los dos.}
{1220}{}{Vaya, vaya, es nuestro viejo amigo, Gomer. ¿Y trajo una humana? ¡Eso es nuevo! Es como una serpiente haciéndose amigo de un conejo. Estoy felices por los dos. Es una pena que no tengamos iglesia para el matrimonio.}
{221}{}{Gomer es mi guardaespaldas.}
{222}{}{Gomer me obedece, hasta necesita mi permiso para ir al baño.}

#Repeat Dialogue
{230}{}{Bien. ¿Cómo te puedo ayudar?}
{231}{}{Hola, normalucho. ¿Tienes algo que decir?}
{1231}{}{Hola, normalucha. ¿Tienes algo que decir?}
{232}{}{Hola, joven mutante. ¿Cómo te puedo ayudar?}
{233}{}{Hola, John. Sólo estoy de visita. Nos vemos.}
{234}{}{Es una pena que no hayamos hablado más. Si necesitas algo, siempre estoy por aquí... *¡Hasta la muerte! ¡Mue-erte!*}
{235}{}{Adiós.}
{236}{}{¿Qué necesitas?}
{237}{}{Basta de bromas. Es hora de hablar en serio.}

{240}{}{Cuéntame, ¿cómo fue que todos ustedes terminaron aquí?}
{241}{}{Vivíamos en el norte, en una ciudad llamada Necrópolis. Entonces llegaron los supermutantes, y después, los normales. Se pelearon entre sí y se olvidaron de nosotros... *¡Apunten! ¡Fuego!* Y cuándo se calmó todo, los normales decidieron que tampoco les gustaban los necrófagos. Así que decidimos buscar un nuevo hogar.}
{242}{}{¿Qué tipo de ciudad intentas construir?}
{243}{}{Una ciudad normal y funcional. Con comercio y una economía, hoteles y casinos, carreteras y rascacielos. Y suficiente espacio para todos, necrófagos, humanos y mutantes. *¡Descansen, soldados!*}
{244}{}{Gracias por la información. Necesito irme.}
{245}{}{¿Puedo ayudar en algo?}
{246}{}{¿En serio quieres ayudar? Si no fuera por mi ojo de vidrio, estaría llorando. Pregúntale a los muertos que te encuentres, seguro que alguien necesita ayuda.}
{247}{}{Eso haré. Nos vemos.}
{248}{}{¿Te puedo ayudar con algo más?}
{249}{}{Cúentame sobre ti.}
{250}{}{Ya te lo he dicho. Soy John Butler. Soy el alcalde de Dayglow... bueno, la futura Dayglow.}
{251}{}{¿San Isidro también cae sobre tu control?}
{252}{}{Es uno de los distritos de la futura Dayglow. Hay varios campamentos necrófagos en las ruinas, pero el Pueblo Viejo y San Isidro son los más grandes. Cada uno tiene su propio administrador. *¡Dios bendiga a América!*}

#Story Quests
{259}{}{¡Urgente! Hay una razón por la que debías reparar la radio. Una caravana de los Comerciantes de Ultramar acaba de contactarnos, los emboscaron en la Ruta 5. Mis necrófagos son demasiado lentos y débiles, eres nuestra última esperanza. Ve, ayuda a tus compañeros en ésta hora oscura. *¡Al ataque!*}
{260}{}{¡Estoy en camino!}
{261}{}{Como siempre, eres característicamente inútil. Me ocuparé de ello.}
{262}{}{La caravana está en el cruce de carreteras, puedes llegar si te diriges hacia el norte por la calle principal, detrás del portón.}
{263}{}{¿Los Comerciantes de Ultramar siguen vivos?}
{264}{}{No he tenido la oportunidad de echarles un ojo. Volveré cuando sepa más.}
{265}{}{El Sr. Rutger me contó de tu heroica hazaña. Necesitamos los bienes del norte, y los Comerciantes de Ultramar son la compañía de caravanas más confiable. Te lo agradezco }
{266}{}{.}
{267}{}{, buen trabajo.}
{268}{}{No fue nada.}
{269}{}{Puedo ver en tus ojos que la misión falló. Bueno, Rutger era el mejor caravanero. Sin él y su compañía, hacer tratos con los humanos será mucho más difícil. Pero Gustavo debe de estar contento, no quiere compartir los artefactos del Viejo Mundo con los normales.}
{270}{}{Ese era el plan.}
{271}{}{Es una pena que haya terminado así. Pero lo hice lo mejor que pude.}
{1271}{}{Es una pena que haya terminado así. Pero lo hice lo mejor que pude.}
{272}{}{Necesito revisar y pensar algunas cosas. Puedes tomar un descanso.}
{273}{}{Está bien.}
{274}{}{}
{275}{}{}
{276}{}{}
{277}{}{}
{278}{}{}
{279}{}{}

#Story Quests
{300}{}{Gustavo me pidió que te diera este holodisco.}
{301}{}{Dámelo. Veamos qué se trae entre manos ese viejo... Hmm. ¡Qué increíbles noticias! Dayglow ahora posee electricidad y radiocomunicación, justo como en los viejos días. ¿Qué podría ser mejor? *¡Todos en línea! ¡A la batalla!*}
{302}{}{[Seguir]}
{303}{}{Ah, claro, Gustavo nos pide que cortemos lazos con los pieles suaves. Otra vez. El viejito simplemente no lo entiende. *¡Apunten! ¡Fuego!* Verás, Gustavo quiere proteger la ciudad de los forasteros. Creo que eso es estúpido, necesitamos bienes y suministros del Eje, y el Eje necesita la tecnología de Dayglow. Dime, no estás de acuerdo con la tontería que él piensa, ¿verdad?}
{304}{}{Claro que no.}
{305}{}{No me importa, porque haré lo que sea mientras me paguen por ello.}
{306}{}{Genial. Entonces te tengo unas tareas pequeñas y fáciles que puedes hacer.}
{307}{}{Te escucho.}
{308}{}{¿Y si estoy de acuerdo con él, qué?}
{309}{}{Sería una pena. Y muy estúpido.}
{310}{}{No me convences. Iré de vuelta a San Isidro.}
{311}{}{Está bien, me convenciste. ¿Qué necesitas que haga?}
{312}{}{Sería una pena. Y muy estúpido. Dime, ¿Te importa quién paga por el trabajo? Yo también necesito tu ayuda.}
{313}{}{¿Qué quieres que haga?}

{320}{}{Ahora mismo, los carroñeros están desmantelando la antigua fábrica de aviones, pieza por pieza. No me importa que los normales lo estén haciendo, pero están trabajando sin el Sello de Set y además tienen a necrófagos haciendo trabajo forzado. Además, necesitamos los componentes electrónicos de la fábrica para la siguiente caravana. ¡Ponte en ello y ve a la fábrica! Dile a los carroñeros que les daré el Sello de Set si consiguen todos los chips. ¡Y ni una palabra de esto a Gustavo!}
{321}{}{¿Qué es el "Sello de Set"?}
{322}{}{Es el derecho a buscar recursos en San Diego y sus alrededores. Y a cambio pedimos una parte de los ingresos, por supuesto. Es una especie de impuesto. *¡Nunca se rindan!* Si los carroñeros se llevaran todos los recursos, nuestra ciudad se quitará sin nada.}
{323}{}{Entendido. Intentaré hablar con ellos.}
{324}{}{Tenemos que hablar sobre la situación con los carroñeros en la fábrica.}
{325}{}{Entonces, ¿terminaste el asunto de los chips?}
{326}{}{No, lo siento.}
{327}{}{Sólo quería volver a preguntártelo, ¿qué es el "Sello de Set"?}
{328}{}{Ah, ya entendí.}
{329}{}{Resulta que todos los carroñeros de la fábrica están muertos.}
{330}{}{¿Todos muertos? ¡Dios santo! ¿Y los chips? ¿Los encontraste?}
{331}{}{Siempre estoy feliz de ayudar.}
{332}{}{¿Y qué recibo yo por mis esfuerzos?}
{333}{}{Todos los chips fueron encontrados, ya tuvieron que haber llegado.}
{334}{}{Excelente trabajo. *¡No dejen a nadie vivo!*}
{335}{}{Aquí está tu recompensa. Pero todavía no vayas al bar, tenemos un problema en nuestras manos.}
{336}{}{Gracias. ¿Qué pasó?}
{337}{}{No. ¿Debería?}
{338}{}{¡El objetivo principal eran los chips! Como los carroñeros fallaron, eres nuestra última esperanza. Trae los malditos chips.}
{339}{}{Ya voy.}
{340}{}{Sí, aquí tienes.}
{341}{}{No los tengo todos.}
{342}{}{¡El objetivo principal eran los chips! Como los carroñeros fallaron, eres nuestra última esperanza. Trae los chips que faltan.}
{343}{}{La fábrica está bajo el control de Gustavo. No recibirás ningún chip.}
{344}{}{¿Gustavo se me adelantó? ¡Qué malas noticias! Pero tenemos un problema más grande. Tendremos que hablar de esto en otro momento.}
{345}{}{¿Qué pasó?}
{346}{}{¿Dónde está la fábrica de aviones?}
{347}{}{Ve hacia la Ruta 805. Allí encontrarás el hospital de Paradise Valley, la fábrica está al este de allí.}
{348}{}{Entendido.}
{349}{}{}

{350}{}{Bien, lo he estado pensando, ¡Y ya me decidí! Verás, el Sr. Rutger tenía un valioso contrato del Eje para un intercambio tecnológico con la base naval Coronado. Sería MUY lucrativo para la ciudad, podemos restaurar las ruinas. ¡Y entonces el sueño de Dayglow será cumplido! *¡Viva América!*}
{351}{}{¿Una base naval? ¿En serio?}
{352}{}{Ahora mismo es inaccesible por las viejas defensas militares. Aquí tienes los códigos de acceso, debes transmitirlos desde la estación de radio que reparaste en San Isidro, no hay otro lugar con una señal tan fuerte. Una vez que hayas hecho eso, ve al puerto, habrá un bote esperando por ti. ¡Y ni una sola palabra de ésto a Gustavo!}
{1352}{}{Ahora mismo es inaccesible por las viejas defensas militares. Aquí tienes los códigos de acceso, debes transmitirlos desde la estación de radio que reparaste en San Isidro, no hay otro lugar con una señal tan fuerte. Una vez que hayas hecho eso, ve al puerto, habrá un bote esperando por ti. ¡Y ni una sola palabra de ésto a Gustavo!}
{353}{}{[Salir]}

# added by cambragol
{354}{}{¿En dónde conseguiste los códigos de seguridad?}
{355}{}{Fueron hallados en El Ardor, es otra base militar, no está muy lejos de aquí. En estos momentos, se está llevando a cabo una excavación.}
