{100}{}{Ves al Señor Gustavo.}
{101}{}{Ves al Señor Gustavo, el administrador de San Isidro.}
{102}{}{¡YO soy la ley por aquí!}
{103}{}{¿Necrófagos necesitar comunicar por radio? Nosotros mejor ayudar, quizás Gomer ganar respeto.}
{104}{}{Nos veremos en el puerto.}

# First Meeting
{200}{}{Gustavo Obanel Vallejo a su servicio. Soy el administrador de San Isidro. Listo, al diablo con la formalidad. Quiero saber por qué interrumpes nuestro descanso eterno.}
{1200}{}{Gustavo Obanel Vallejo a su servicio. Soy el administrador de San Isidro. Listo, al diablo con la formalidad. Quiero saber por qué interrumpes nuestro descanso eterno.}
# Gustavo Obanel Vallejo at your service. I'm the manager of San Ysidro. Now, to hell with pleasantries. I want to know the reason why you're disturbing our posthumous peace. We don't tolerate smooth-skins here. Our family has suffered enough from you. Therefore, explain clearly and without lying - why should we tolerate your presence?
{201}{}{Los necrófagos pueden irse directo al infierno. Estoy aquí por el dinero, escuché que uno puede ganar riquezas en este lugar.}
{202}{}{Una respuesta honesta, eso no me lo esperaba. Puedo tratar con gente como tú, empiezas a agradarme.}
{203}{}{Eso depende de nuestros términos, compañero.}
{204}{}{La verdad, busco un mejor lugar en el que vivir. Las cosas están muy mal en casa.}
{205}{}{Estás escapando de tus problemas, ¿no es así? No me impresionas, suavecito. Pero quizás seas útil.}
{1205}{}{Estás escapando de tus problemas, ¿no es así? No me impresionas, suavecita. Pero quizás seas útil.}
{206}{}{Bueno. ¿Qué tipo de trabajo hay por aquí?}
{207}{}{No tengo ningún problema con ustedes. Amo a los necrófagos y me encantaría vivir entre ellos.}
{1207}{}{No tengo ningún problema con ustedes. Amo a los necrófagos y me encantaría vivir entre ellos.}
{208}{}{Tu piel es tan suave, que podrías ser un postre, normalucho. No voy a tolerar más de tus mentiras. Pero te daré una oportunidad. Demuestra lo que vales y tendrás abrazos de los necrófagos hasta el fin de tus días.}
{209}{}{Oye, ¡sólo intentaba ser amable!}
{1209}{}{Oye, ¡sólo intentaba ser amable!}
{210}{}{Gustavo Obanel Vallejo a su servicio. Soy el administrador de San Isidro. Me alegra verte en nuestro campamento, hermano. Aquí encontrarás la paz eterna.}
{1210}{}{Gustavo Obanel Vallejo a su servicio. Soy el administrador de San Isidro. Me alegra verte en nuestro campamento, hermana. Aquí encontrarás la paz eterna.}
{211}{}{Gracias, hermano. ¿Qué se puede hacer en esta hermosa ciudad?}
{212}{}{Dayglow todavía no brilla. Dirígete a la planta eléctrica y ayuda a nuestros trabajadores a restaurar la electricidad a la ciudad. Te daré una generosa recompensa y dejaré que te quedes en San Isidro por el resto de tus días.}
{213}{}{Dayglow todavía no brilla. Dirígete a la planta eléctrica y ayuda a nuestros trabajadores a restaurar la electricidad a la ciudad. La ciudad te estará eternamente agradecida hasta el fin de los días.}
{214}{}{Trato hecho.}
{215}{}{Es mucho trabajo.}
{216}{}{Hablas demasiado, normalucho. ¡Regresa a tu asqueroso yermo! No te necesitamos por aquí.}
{217}{}{Chale...}
{218}{}{Después del incidente en la frontera, esta conversación será breve. ¿Qué quieres?}
{219}{}{¿Qué incidente? ¡No sé nada!}
{220}{}{Mis leales guardias protegían la entrada. Ahora lo único que deambula por allá es el viento. Y aquí estás. ¿Qué tienes que decir en tu defensa?}
{221}{}{Sólo fue una coincidencia. No había nadie en la entrada, así que entré.}
{1221}{}{Sólo fue una coincidencia. No había nadie en la entrada, así que entré.}
{222}{}{Hmm, si me entero de que estás mintiendo, voy a despellejar tu suave piel y rozar polvo radioactivo sobre tu carne. Sentirás todo el dolor que los necrófagos sentimos a diario.}
{223}{}{Sí, te creo. Pero, ¿quién eres?}
{224}{}{El necrófago me amenazó, sólo me defendía.}
{1224}{}{El necrófago me amenazó, sólo me defendía.}
{225}{}{Era un leal servidor de Dayglow, protegía nuestra ciudad de los normales. ¿Crees que puedes expiar tus crímenes?}
{226}{}{No tienes ningún derecho a poner límites. El yermo es para todos, no sólo ustedes.}
{227}{}{Sólo queremos vivir como personas normales. Sin guerras, sin nobles misiones para salvar la humanidad, quizás no seas capaz de entender eso. Pero ya que estás aquí, no tienes otra elección. Expíate... o muere.}
{228}{}{Elijo la muerte. ¡La tuya!}
{229}{}{¿Podemos negociarlo? Por cierto, no nos hemos presentado.}
{230}{}{No recuerdo que se me haya informado de tu llegada. ¿Cómo pasaste la frontera?}
{231}{}{Bueno, pasé por la puerta y ya.}
{232}{}{¿Y los leales sirvientes de Dayglow no te detuvieron? Alguien merece una buena golpiza.}
{233}{}{Claro, pero yo no. ¿Eres tú el que está a cargo?}
{234}{}{Para vivir con nosotros, debes trabajar. Hasta un mutante como tú debería entender eso, ya tenemos suficientes parásitos.}
{235}{}{Entendido...}
{236}{}{¿Alguna idea de cómo arreglar la estación?}

# Repeat Dialogue
{250}{}{Habla, suavecito.}
{1250}{}{Habla, suavecita.}
{251}{}{Adiós, Señor Gustavo.}
{252}{}{¿Qué tramas, normalucho?}
{1252}{}{¿Qué tramas, normalucha?}
{253}{}{Mira a quien tenemos aquí. Un suavecito que busca una golpiza. No te preocupes, me quedaré tu piel para usarla de repuesto. Pero primero, me contarás todo.}
{254}{}{Siéntate, compadre. Espero que los necrófagos de Dayglow te hayan tratado como uno de los suyos.}
{1254}{}{Siéntese, señorita. Espero que los necrófagos de Dayglow la hayan tratado como uno de los suyos.}
{255}{}{Siéntate, compadre. ¿Cómo te trata Dayglow? ¿Está todo bien? hazme saber si hay algún problema.}
{1255}{}{Siéntese, señorita. ¿Cómo la trata Dayglow? ¿Está todo bien? Hágame saber si hay algún problema.}
{256}{}{Siéntate, compadre. Háblame, quizás te pueda ayudar.}
{1256}{}{Siéntate, señorita. Hábleme, quizás le pueda ayudar.}
{257}{}{Siéntate. Creo que es hora de que hablemos.}

{260}{}{¿Me puedes recordar qué querías que hiciera?}
{261}{}{¿Acaso hablo ruso? (suspiro cansado) }
{262}{}{La planta eléctrica está funcionando de nuevo.}
{263}{}{¡Dayglow está brillando otra vez! La electricidad regresó a San Isidro y al Pueblo Viejo. Haz hecho una gran hazaña, amigo. Déjame darte un abrazo y mi gratitud. Aquí tienes 1.000 chapas.}
{1263}{}{¡Dayglow está brillando otra vez! La electricidad regresó a San Isidro y al Pueblo Viejo. Haz hecho una gran hazaña, amiga. Déjame darte un abrazo y mi gratitud. Aquí tienes 1.000 chapas.}
{264}{}{Gracias.}
{265}{}{Nada mal.}
{266}{}{Te debo una disculpa. Te había encargado eso porque pensé que te mataría un robot o la radiación, y entonces habría un normalucho menos en Dayglow. Pero estaba equivocado, puedes quedarte en nuestra ciudad todo lo que quieras, amigo.}
{1266}{}{Te debo una disculpa. Te había encargado eso porque pensé que te mataría un robot o la radiación, y entonces habría una normalucha menos en Dayglow. Pero estaba equivocado, puedes quedarte en nuestra ciudad todo lo que quieras, amiga.}
{267}{}{Lo entiendo, no te culpo.}
{268}{}{No esperes que te de un apretón de manos luego de eso.}
{1268}{}{No esperes un abrazo luego de eso.}
{269}{}{Ahora que tenemos electricidad, necesitamos reparar la estación de radio. Está en el cuarto de al lado, es una tarea adecuada para ti.}
{270}{}{¿No está muy rota? ¿Estás seguro de que se puede arreglar?}
{271}{}{Arreglarla no, necesita un reemplazo. Sé que hay una idéntica en la oficina fronteriza. Te pagaré si traes las piezas de esa radio de vuelta.}
{272}{}{Bien. Lo intentaré.}
{273}{}{Lo intentaré cuándo me de las gana. Por ahora, no estoy de humor. Nos vemos.}
{274}{}{La estación de radio ya funciona. De hecho, tuve que reemplazarla con una nueva de la oficina fronteriza.}
{275}{}{Siempre es bueno recibir una buena noticia en un mundo como este. Me agradas más y más, suavecito. Eres justo como yo cuando era un jovenzuelo.}
{1275}{}{Siempre es bueno recibir una buena noticia en un mundo como este. Me agradas más y más, suavecita. Eres justo como yo cuando era un jovenzuelo.}
{276}{}{Siempre es bueno recibir una buena noticia en un mundo como este.}
{277}{}{No es una comparación muy bonita, ¿sabes?}
{278}{}{Antes de que lo pienses, no aceptaré un apretón de manos.}
{279}{}{No perdamos el tiempo. Aquí tienes 500 chapas por el trabajo. Ahora necesito que le lleves este holodisco al Alcalde Butler en el Pueblo Viejo, es muy importante.}
{280}{}{¿Nada más? Después de mis otras hazañas, esto es pan comido.}
{281}{}{Ante ti yacen las ruinas de San Diego. Hay muchos peligros en ellas, así que ten más cuidado. Ve al bar y habla con Edward si necesitas suministros para el viaje.}
{282}{}{Bien, nos vemos.}
{283}{}{Dame un arma si quieres que sobreviva el viaje al Pueblo Viejo.}
{1283}{}{Dame un arma si quieres que sobreviva el viaje al Pueblo Viejo.}
{284}{}{Hmm, es razonable. ¿Con qué arma eres mejor?}
{285}{}{[Toma: }
{286}{}{]}
{287}{}{Agradecería que no te mueras en el camino.}
{1287}{}{Agradecería que no te mueras en el camino.}
{288}{}{Lo intentaré...}
{289}{}{Intentaré responder.}
{290}{}{¿Qué tan importante es para ti?}
{291}{}{Necesitamos una estación de radio. Las áreas de Dayglow están separadas por escombros que no podemos evitar, y la radiación bloquea las radios normales. Poder comunicarnos de forma constante cambiará la ciudad por completo. Hazlo lo mejor que puedas, por todos nosotros.}
{292}{}{¿Qué hay en el disco?}
{293}{}{Primero, datos para la transmisión por radio para comunicarnos a larga distancia. Segundo... algunas advertencias para mi hermano y deje de cometer errores.}


{296}{}{¿Cómo puedo llegar a la planta eléctrica?}
{297}{}{Hay dos formas. Puedes ir derecho desde la Ruta 805, y girar al este desde la señal. Pero la autopista es patrullada por robots militares. El camino menos peligroso es a través del pantano tóxico hasta llegar a Chula Vista.}
{298}{}{Intentaré encontrar el camino.}

#Inquiries
{300}{}{¿Te puedo hacer unas preguntas?}
{301}{}{Compadre, siempre estaré feliz de escucharte y responder tus dudas. Pero ahora mismo hay cosas más importantes de las que ocuparse. Ya sabes qué hacer.}
{1301}{}{Señorita, siempre estaré feliz de escucharla y responder sus dudas. Pero ahora mismo hay cosas más importantes de las que ocuparse. Ya sabes qué hacer.}
{302}{}{Es mejor que te pongas a trabajar, si sabes a qué me refiero.}
{303}{}{Nada de charlas. Ni siquiera sé si debería estar hablando contigo.}
{304}{}{Entendido. Hablamos luego.}
{305}{}{Podrías solo decirme que no quieres hablarme. Adiós.}
{306}{}{Compadre, siempre estaré feliz de escucharte y responder tus dudas. }
{1306}{}{Compadre, siempre estaré feliz de escucharla y responder sus dudas. }
{307}{}{Está bien, nos vemos.}

{310}{}{Me gustaría saber más de ti.}
{311}{}{¿Que quién soy? Es una pregunta rara. Antes era un doctor, pero la guerra me quitó la licencia. Ahora, como puedes ver, me encargo de este pequeño pueblo. Puedes aprender a hacer lo que sea, si la vida te obliga a hacerlo.}
{312}{}{Por cierto, acerca de este pueblo. No lo entiendo, ¿entonces dónde está Dayglow? ¿Qué es?}
{313}{}{Está en nuestro corazón. Dayglow es el sueño de los necrófagos, el sueño de una ciudad en la que podemos envejecer en paz. San Isidro es uno de sus distritos. Aquí estamos protegidos por la vieja muralla fronteriza.}
{314}{}{¿Entonces tu meta es construir Dayglow?}
{315}{}{Mi meta es una ciudad para los necrófagos. Sólo queremos vivir como gente normal. Sin opresión, sin guerras, sin ninguna gran odisea para salvar a la humanidad.}
{316}{}{Ya entiendo.}
{317}{}{¿El Pueblo Viejo también quiere este paraíso?}
{318}{}{No parece que el Pueblo Viejo comparta tu sueño.}
{319}{}{El Pueblo Viejo está cometiendo un error. Está demasiado cerca a la ruta de las caravanas y entonces no puede salvarse de la mala influencia que son los normaluchos de las ciudades norteñas.}
{320}{}{¿Cómo puedo llegar al Pueblo Viejo?}
{321}{}{Ve al norte. Puedes ir derecho desde el puerto, pero es un infierno radioactivo. O puedes dar la vuelta a través de las ruinas, eso te asegura experiencias nuevas, pero no siempre placenteras.}
{322}{}{Entendido.}
{323}{}{¿Qué es Dayglow? ¿Dónde está?}
{324}{}{¿Qué clase de ciudad intentas construir?}
{325}{}{Será una ciudad como fue hace cien años. Recolectamos todo lo que queda del Viejo Mundo. Aquí no molestamos a nadie, así que podemos relajarnos y vivir en paz por el resto de nuestros días.}
{326}{}{Háblame sobre ti.}

{350}{}{Le entregué el holodisco a Butler. Tu mensaje no lo convenció.}
{1350}{}{Le entregué el holodisco a Butler. Tu mensaje no lo convenció.}
{351}{}{No me sorprende. John y yo discutimos sobre Dayglow, acerca de cómo debería ser la ciudad de los necrófagos. Le pone demasiada atención a los pieles suaves y ha olvidado por completo que nosotros venimos del Viejo Mundo. ¡Podemos resucitar la ciudad, reconstruirla desde cero! Sí, los necrófagos son débiles, pero tenemos restos de maquinaria vieja y energía. Con esa tecnología, podemos crear todas las condiciones necesarias para nosotros mismos, incluso en medio de estas ruinas.}
{352}{}{Por cierto, luego de leer el holodisco, me pidió que lo ayudara a encontrar chips de la fábrica de aviones.}
{353}{}{¡Qué idiota! Esa fábrica debería servirnos a nosotros, los necrófagos. No le des los chips al Pueblo Viejo, dámelos a mí. Nuestro técnico los puede usar para reparar los robots, y con su ayuda, restaurar la ciudad. Eso nos dará muchas más ventajas futuras que un estúpido intercambio de comida con las caravanas.}
{354}{}{Lo pensaré.}
{355}{}{Bien, lo haré.}
{356}{}{Sabía que dirías eso, así que traje los chips. Aquí los tienes.}
{1356}{}{Sabía que dirías eso, así que traje los chips. Aquí los tienes.}
{357}{}{Gracias. Aquí tienes 1.000 chapas por el trabajo. La fábrica nos ayudará también, no podemos dejar que la destruyan. Pienso que deberías decirle a John que la fábrica está bajo mi control y que no le daré los chips.}
{358}{}{Está bien.}
{359}{}{Aquí tienes los chips que Butler quería vender. Pero ya no podrá hacerlo.}
{360}{}{Entonces te tengo malas noticias, Butler ya consiguió los chips y se está preparando para venderlos.}
{361}{}{Que malas noticias. Creo que deberías vigilar bien a Butler. Déjame saber si te enteras de lo que está planeando.}
{362}{}{Entendido.}
{363}{}{Te tengo malas noticias, Butler ya consiguió los chips y se está preparando para venderlos.}
{364}{}{Sí, y por cierto, manténme informado si te enteras de lo que está planeando.}
{365}{}{Entendido.}

{370}{}{Butler planea abrir la base militar en la isla, usando la radio...}
{371}{}{¡Está cometiendo un error! ¡Venderá la mayoría de lo que encuentre a los normales! Y eso provocará un gran alboroto en los asentamientos de los humanos. La guerra contra los supermutantes acaba de terminar, y las batallas por tecnología vieja empezarán de nuevo. Los pieles suaves no entienden como manejar el legado del Viejo Mundo. Además, lo pueden usar en nuestra contra. ¡La tecnología debería quedarse con los necrófagos! La necesitamos más que ellos y sabemos cómo usarlas mejor.}
{372}{}{¿Qué es lo que vas a hacer?}
{373}{}{Butler no se echará para atrás. Necesitamos llegar primero y tomar todo para nosotros mismos. Enviaré un grupo al puerto para interceptarlos. Usa la estación de radio como Butler te lo pidió, y luego ve al puerto.}
{374}{}{Bien.}
