{100}{}{Ves a Edward.}
{101}{}{Ves al dueño de la cafetería local. Lleva un delantal que era blanco, y una gorra.}
{102}{}{No estoy interesado en eso.}

{200}{}{Hola, bienvenido a... ¡Un humano!}
{201}{}{Así es. ¿Acaso es algo raro de ver?}
{202}{}{Eh, parece que estoy en el sitio equivocado. Adiós...}
{203}{}{No te lo tomes a mal, pero... ¿No sabes que esto es una ciudad para necrófagos? Incluso le subimos los precios a los normales para que no se queden demasiado tiempo.}
{204}{}{Lo sé. No te preocupes, no me molesta su compañía.}
{205}{}{Tráeme una bebida de una vez.}
{206}{}{Como tú digas.}
{207}{}{Bien. ¿Cómo te llamas?}
{208}{}{Edward, señor.}
{1208}{}{Edward, señorita.}
{209}{}{Bueno, Edward, muéstrame lo que tienes para comer.}
{210}{}{Aquí tienes el menú, y esto es lo que tengo para llevar.}
{211}{}{Gracias.}
{212}{}{¿Qué tendrás hoy, amigo mío?}
{1212}{}{¿Qué tendrá hoy, señorita?}
{213}{}{¿Qué quieres, normalucho?}
{214}{}{Creo que nada más.}
{215}{}{Muéstrame el menú.}
{216}{}{Pasa, sin miedo. ¡Aquí somos como familia! No toleramos a los normales e incluso le subimos los precios. Pero los mutantes siempre son bienvenidos.}
{217}{}{Gracias por recibirme. Soy }
{218}{}{. ¿Qué hay de ti?}
{219}{}{Todavía no te acepto en nuestro club. Además, ¿quién eres?}
{1219}{}{Todavía no te acepto en nuestro club. Además, ¿quién eres?}

{220}{}{¿Podemos hablar, Ed?}
{221}{}{¿Sobre qué, en primer lugar?}
{222}{}{Suficiente charla, tengo otras cosas que hacer.}
{223}{}{¿El menú es de la preguerra?}
{224}{}{Así es. Lo que viene de las caravanas norteñas se lo queda el Pueblo Viejo en su mayoría, a nosotros nos dejan las migajas. Así que suelo cocinar los suministros de la preguerra, pero al ser necrófagos es mucho mejor. ¡Ah, la nostalgia! Lo único que falta para un menú completo es el café. ¿Para qué sirve una cafetería, si no hay café?}
{225}{}{Eso es muy malo, Ed. Puedo buscar algo de café para ti en las ruinas.}
{226}{}{Deja de quejarte, estoy aquí para comer, no para escucharte hablar de los viejos días.}
{227}{}{¿Te arriesgarás por una lata de café? ¡Entonces te pagaré el triple de su valor por cada una!}
{228}{}{Trato hecho. Te traeré lo que encuentre.}
{229}{}{Pensándolo mejor, no quiero ponerme a buscar en los escombros. Pero lo anotaré en mi Pip-Boy.}
{230}{}{Tienes suerte, porque tengo una lata de café justo aquí.}
{231}{}{Tengo una lata de café para ti.}
{232}{}{(Abre la lata, huele y prueba) ¡Qué buen sabor! Ganaré mucho dinero con esto en el menú. Aquí está tu paga - }
{233}{}{ chapas. Trae más, compraré todo lo que encuentres.}
{234}{}{Por supuesto.}
{235}{}{Estás en el lugar equivocado, normalucho. No servimos a los de tu especie por aquí.}
{1235}{}{Estás en el lugar equivocado, normalucha. No servimos a los de tu especie por aquí.}
{236}{}{Ordena lo que quieres y sal de aquí.}
{237}{}{Bueno, perdona... ¿Quizás podríamos hacer un trato? Te pagaré el triple por cada botella.}

{240}{}{¡Gracias por arreglar la planta, }
{241}{}{! Fue peligroso, ¿verdad? Ten, debería ayudarte con la radiación. Es mi forma de darte las gracias.}
{242}{}{Gracias, Ed. Me será de mucha ayuda.}
{243}{}{¿Nada más? Bueno, gracias.}
{244}{}{Ah, y también te haré un descuento. A los normales les cargo más, pero sería injusto en tu caso.}
{245}{}{Justo pensaba en comer algo, enséñame el menú.}
{246}{}{Eso es genial, pero necesito pedirte información en vez de comida.}
{247}{}{¡Gracias por arreglar la planta, }
{248}{}{! Fue peligroso, ¿verdad? Ten, unos tragos y un almuerzo, la casa invita. Además, te haré un descuento para la siguiente vez.}
{249}{}{}
{250}{}{El Señor Gustavo me dijo que hablara contigo, por unos suministros.}
{251}{}{Te daré algo de RadAway, Rad-X, antídoto, y un estimulante. Nada es gratis en la vida, pagarás un precio alto al cruzar las ruinas de San Diego. Espero que sobrevivas, buena suerte, compañero.}
{1251}{}{Te daré algo de RadAway, Rad-X, antídoto, y un estimulante. Nada es gratis en la vida, pagarás un precio alto al cruzar las ruinas de San Diego. Espero que sobrevivas, buena suerte, señorita.}
{252}{}{Necesito más. ¿Podrías mostrarme lo que vendes?}
{253}{}{Gracias, Ed. Nos vemos.}

{260}{}{Quiero cambiar mis dólares de la preguerra por chapas.}
{261}{}{Por cada dólar te daré }
{262}{}{ chapas. ¿Qué te parece?}
{263}{}{No es suficiente. Adiós.}
{264}{}{No es necesario. Dame algo de comer.}
{265}{}{[Cambia 1 dólar]}
{266}{}{[Cambia 2 dólares]}
{267}{}{[Cambia 3 dólares]}
{268}{}{[Cambia 4 dólares]}
{269}{}{[Cambia 5 dólares]}
{270}{}{[Cambia 10 dólares]}
{271}{}{[Cambia TODOS tus dólares]}
{272}{}{¿Tienes un agujero en el bolsillo? Suele pasar.}
{273}{}{Sí, está roto...}
{274}{}{Aquí tienes.}
{275}{}{Gracias.}
{276}{}{[Cambia el dinero por chapas]}
{277}{}{[Rehúsate y vete]}

{280}{}{¿Tienes algún trabajo para mí?}
{281}{}{Ningún trabajo serio, pero podrías llevarle el almuerzo a los trabajadores de la presa.}
{282}{}{No gracias, no quiero trabajos así de pequeños.}
{283}{}{Bueno, dame el paquete.}
{284}{}{Bien, aquí tienes cinco almuerzos para cinco personas. Es uno para cada uno. Necesito que lo hagas en un día, definitivamente serás más rápido que los demás necrófagos. Y no te comas nada de camino, o los necrófagos estarán MUY molestos.}
{285}{}{Voy.}
{286}{}{Ya entregué la comida a todos los clientes.}
{287}{}{Muchísimas gracias, aquí está tu dinero.}
{288}{}{Nos vemos.}
{289}{}{Muchísimas gracias, aquí está tu dinero. Ah, cierto, tengo unos suministros que me sobraron. Ten, la casa invita.}
{290}{}{Gracias.}
{291}{}{Nada me hace más feliz que recibir cosas gratis. Adiós, Ed.}

{292}{}{¿Sabes quién tiene la película "Deep Throat"?}
{293}{}{Sí, ese sería Raymond. Pero jamás dejaría su película favorita, aunque creo sólo le gusta la caja y jamás la ha visto. Y no le vayas a quitar el disco, se volverá loco y le hará problemas a todos.}
{294}{}{Gracias por avisarme.}

{295}{}{Ed, encontré un procesador de alimentos en las ruinas, tiene tu nombre.}
{296}{}{¡Por fin lo encontraron! Se supone que un robot debía traerlo, pero algo le tuvo que haber pasado. Ese procesador es invaluable, ¿sabes? Nos estamos muriendo de hambre, no hay comida de verdad, nos sería de mucha ayuda. Bueno, lo tienes, ¿verdad?}
{297}{}{No, eh, lo dejé ahí cuando lo encontré. Lo siento.}
{1297}{}{No, eh, lo dejé ahí cuando lo encontré. Lo siento.}
{298}{}{Eso es una pena. ¡Realmente lo necesitamos! Por favor, traémelo, te daré 200 chapas.}
{299}{}{Bueno, si llego a estar cerca lo haré.}
{300}{}{Claro.}
{301}{}{Sí, aquí está, tómalo.}
{302}{}{¡Nos has salvado! Oigan chicos, miren, este normalucho nos hizo un gran favor. ¡Denle las gracias!}
{1302}{}{¡Nos has salvado! Oigan chicos, miren, este preciosa normalucho nos hizo un gran favor. ¡Denle las gracias!}
{303}{}{Estoy feliz de ayudar. Adiós, Ed.}
{304}{}{Demonios, De Santi me habría pagado más... Me refería a otra cosa, no importa. Eh, adiós.}
{305}{}{Ay, compadre, ¡nos has salvado! Gracias. Dudo que un normalucho hubiera hecho algo así por nosotros. Oigan chicos, ¡Denle las gracias!}
{1305}{}{Oh, nena, ¡nos has salvado! Gracias. Dudo que un normalucho hubiera hecho algo así por nosotros. Oigan chicos, ¡Denle las gracias!}
