{100}{}{Ves a un cantinero.}
{101}{}{Ves a un cantinero sin nada fuera de lo común... dirías eso, si no fuera un necrófago.}
{102}{}{¡Otra vez! ¡Deténlos! ¡Van a destrozarme el bar!}

{210}{}{¿Qué quieres, costal de huesos?}
{211}{}{Ahora mismo nada. Adiós.}
{212}{}{Una bebida y algo para comer. ¿Qué vendes?}

{220}{}{¿Has visto a Steve Morgan?}
{221}{}{Se acaba de ir. ¿Por qué necesitas a un cadáver como él?}
{222}{}{Tengo un "asunto" que tratar con él. Es acerca de un trabajo de mensajero.}
{223}{}{No es tu mejor opción. Lleva ansiando amasar dinero desde la Guerra, pero ni siquiera puede permitirse un coche nuevo. Jeje, sólo bromeo. Dijo que se dirigía de vuelta al Eje, lo mencionó mientras estaba sentado en el mismo taburete en el que estás.}
{224}{}{¿Y cuándo se supone que va a volver? ¿Ahora? Es mejor que intente alcanzarlo en la carretera.}
{225}{}{¡Me lo deberías de haber dicho de inmediato, idiota!}
{226}{}{¿Por qué hay chatarreros por aquí?}
{227}{}{Cualquiera es bienvenido en mi bar, mientras paguen. A Butler tampoco le importa que hayan normales en la ciudad, incluso intenta comerciar con el Eje. Mientras los carroñeros no causen problemas, los toleramos.}
{228}{}{Ya veo.}

{230}{}{¿Tienes algo más fuerte para beber, o sólo hay cerveza del siglo anterior?}
{231}{}{Las botellas de buen licor son una rareza. Lo que encuentran en las ruinas suele venderse a las caravanas del norte, y el bar se queda con las migajas.}
{232}{}{Eso es una pena, quería un buen trago...}
{1232}{}{Eso es una pena, quería un buen trago...}
{233}{}{Podría buscarte algunas botellas en las ruinas.}
{234}{}{Tráeme botellas del whiskey de la preguerra y con gusto te pagaré el triple.}
{235}{}{Trato hecho. Te traeré lo que encuentre allá afuera.}
{236}{}{Estás de suerte. Resulta que tengo una botella de whiskey de la preguerra.}
{237}{}{(Abre la botella, la huele y prueba su contenido.) ¡Es excelente! Esto valdrá el precio. Ten tu parte - }
{238}{}{ chapas. Si llegas a encontrar otra, la compraré.}
{239}{}{Por supuesto.}
{240}{}{Tengo una botella de whiskey de la preguerra para el bar.}

{241}{}{Estamos buscando al escuadrón de Gomer. ¿Has escuchado algo al respecto?}
{242}{}{Escuché que unos supermutantes establecieron un campamento en el Parque Balboa. No son agresivos, parece que es lo contrario. Quizás sean ellos.}
{243}{}{Ya veo. Gracias.}

{260}{}{Quiero cambiar mis dólares por chapas.}
{261}{}{Claro. La tasa de cambio de hoy es de }
{262}{}{ chapas.}
{263}{}{Entonces no. Esperaré a que la tasa cambie.}
{264}{}{Otra vez será Déjame ver lo que hay en el menú.}
{265}{}{[Cambia 1 dólar]}
{266}{}{[Cambia 2 dólares]}
{267}{}{[Cambia 3 dólares]}
{268}{}{[Cambia 4 dólares]}
{269}{}{[Cambia 5 dólares]}
{270}{}{[Cambia 10 dólares]}
{271}{}{[Cambia TODOS tus dólares]}
{272}{}{¿Acaso se te cayó el dinero? A veces pasa.}
{273}{}{Sí, parece que sí...}
{274}{}{Aquí tienes.}
{275}{}{Gracias.}

{280}{}{Quiero una habitación para pasar la noche.}
{281}{}{Para ti, serán }
{282}{}{ chapas.}
{283}{}{¿Por qué tanto?}
{284}{}{Porque eres un normalucho.}
{1284}{}{Porque eres una normalucho.}
{285}{}{¡Eso no es justo!}
{286}{}{Si no te gusta, anda a dormir afuera.}
{287}{}{Está bien, pagaré una noche.}
{288}{}{No, gracias.}
{289}{}{No te puedo ayudar. Todas las habitaciones están... ocupadas.}
{290}{}{¿En serio? ¿No mientes, verdad?}
{291}{}{Que mala suerte.}
{292}{}{Aunque tuviéramos habitaciones vacantes, preferiría dárselas a un supermutante que a ti.}
{293}{}{No olvidaré esto, costal de huesos.}
{294}{}{De todas formas ni quería. Olvídalo.}
{295}{}{No tienes suficientes chapas. Ve a ganarte algunas.}
{296}{}{Bueno.}
