{100}{}{Ves al Sr. De Santi.}
{101}{}{Ves a un necrófago vestido con un traje y un fedora de la preguerra. Una larga cicatriz recorre su rostro.}
{102}{}{Es Albert de Santi.}

{200}{}{Viniste al lugar correcto, jovencito. Soy Albert de Santi, bienvenido a mi establecimiento, La Pensione - el único hotel y spa en Dayglow.}
{1200}{}{Viniste al lugar correcto, pimpollo. Soy Albert de Santi, bienvenido a mi establecimiento, La Pensione - el único hotel y spa en Dayglow.}
{201}{}{[Siguiente]}
{202}{}{Aquí puedes olvidarte de nuestra dura realidad. Tenemos masaje, cine de la época dorada, baños sanos, bronceado radioactivo, exquisitos platillos de rata, incluso pedidos especiales para cualquiera de tus deseos - sólo dime lo que buscas.}
{203}{}{¿En serio? ¿Abriste un spa en medio de las ruinas? ¿Quién crees que va a venir aquí?}
{204}{}{Relájate, pequeñín. Un lugar así es mucho más seguro... Con la excepción de los loquitos que están cruzando la calle. Todavía están medio sanos, pero es solo cuestión de tiempo.}
{1204}{}{Relájate, lindura. Un lugar así es mucho más seguro... Con la excepción de los loquitos que están cruzando la calle. Todavía están medio sanos, pero es solo cuestión de tiempo.}
{205}{}{Está bien, lo tendré en cuenta.}

{210}{}{¿En qué andas, pequeñín?}
{1210}{}{¿La ayudo en algo, señorita?}
{211}{}{Hasta luego.}
{212}{}{Adiós, Sr. de Santi.}
{213}{}{Nos vemos luego, Sr. De Santi.}
{214}{}{Amo el olor a chapas antes de irme a la cama. Aquí tienes, te ganaste la mitad.}
{215}{}{(agita la bolsa con chapas) ¡Ah! Nada es mejor que oler las chapas durante la cena. De verdad te lo ganaste, ten, es la mitad de las chapas.}

# Quests
{220}{}{¿Has probado a lidiar con los locos de al lado?}
{221}{}{Te pagaré 100 chapas por cada uno que mates. Has eso y el dinero es tuyo.}
{222}{}{¿No te sientes mal por ellos? Son necrófagos, igual que tú.}
{223}{}{Muchacho, en este negocio tienes que recordar esto: debes disparar primero, incluso a tu propia gente, si haces eso, sobrevivirás.}
{1223}{}{Cariño, en este negocio tienes que recordar esto: debes disparar primero, incluso a tu propia gente, si haces eso, sobrevivirás. }
{224}{}{Trato hecho, necesito hacer chapas de todas formas.}
{225}{}{No, no lo haré.}
{226}{}{Ya me ocupé de los necrófagos.}
{227}{}{Aquí tienes, jovencito. Dinero fácil, ¿verdad?}
{1227}{}{Aquí tienes, cariño. Dinero fácil, ¿verdad?}
{228}{}{Me gusta su forma de hacer negocios, señor. Podría seguir trabajando para usted, ¿hay algo más que necesite hacerse?}
{229}{}{Hay algo más. ¿Conoces a Derrick? Es el tipo cerca de la entrada, se aprovecha de mi negocio y eso no me gusta. Ocúpate de él.}
{230}{}{Dalo por hecho.}
{231}{}{Derrick ya no será un problema. Está lleno de plomo.}
{232}{}{¡Es una pena! De casualidad, no sabes quién fue, ¿verdad? (guiña y te entrega 100 chapas) Tendré que enviar a alguien para limpiar el desastre.}
{233}{}{[Irse]}
{234}{}{Derrick se pensó mejor su negocio. Ahora trabajará para ti.}
{235}{}{Bien hecho, muchacho. Te mereces un extra. (te guiña y suelta 150 chapas)}
{1235}{}{Bien hecho, cariño. Te mereces un extra. (te guiña y suelta 150 chapas)}
{236}{}{[Irse]}
{237}{}{¿Estás seguro de que matar a los loquitos es una buena idea?}
{238}{}{Bueno, como digas.}
{239}{}{¿Me podrías recordar por qué te molesta Derrick?}
{240}{}{Porque quiere hacer negocios en la puerta, se aprovecha de mi negocio y eso no me gusta. Ocúpate de él.}
{241}{}{Vale.}
{242}{}{¿Tienes más trabajo?}
{243}{}{Un sinvergüenza se escapó al Pueblo Viejo sin pagarme lo que me debía.}
{244}{}{¿Cómo se llama este sinvergüenza?}
{245}{}{Se llama Kurt, me debe 300 chapas. Sácaselas y tendrás la mitad.}
{246}{}{Me pondré en ello.}
{247}{}{Aquí tienes las chapas de Kurt, exactamente 300.}
{248}{}{Ah, amo el amor a chapas por la mañana. Muy bien, niño, te ganaste la mitad.}
{1248}{}{Ah, amo el amor a chapas por la mañana. Muy bien, muñeca, te ganaste la mitad.}
{249}{}{Claro.}

{250}{}{Me parece que este lugar se cae a pedazos. ¿Necesitas ayuda?}
{251}{}{Tienes razón, manejar todo esto yo sólo es duro. Realmente necesito ayuda.}
{252}{}{Puedo hacerlo por un sueldo decente.}
{253}{}{Lo siento, pero no te puedo ayudar con eso.}
{254}{}{Tengo un mejor candidato, ni siquiera necesito pagarle. Está en la otra habitación, es un Señor Mañoso. Lo único que falta para que funcione es arreglarlo y una programación de administrador. Te pagaré 300 chapas, es un trabajo fácil.}
{255}{}{Está bien, lo haré.}
{256}{}{Entonces ponte a trabajar, muchachito. Buscaría la programación en el Pueblo Viejo, y puedes encontrar partes en cualquier lado, debería hacerlo más fácil.}
{1256}{}{Entonces ponte a trabajar, pimpollo. Buscaría la programación en el Pueblo Viejo, y puedes encontrar partes en cualquier lado, debería hacer la reparación más fácil.}
{257}{}{Entiendo.}
{258}{}{El robot ya está funcionando. ¿Pero dónde puedo encontrar su programación?}
{259}{}{Prueba a buscar en el Pueblo Viejo, es un programa de administrador.}
{260}{}{Parece que tienes un empleado nuevo.}
{261}{}{Buen trabajo, muchacho. Aquí tienes las chapas. Tengo más trabajos, si te interesa.}
{1261}{}{Buen trabajo, pimpollo. Aquí tienes las chapas. Tengo más trabajos, si te interesa}
{262}{}{¿De qué se trata?}
{263}{}{Vale.}
{264}{}{No me interesa, no quiero arreglar tecnología vieja.}
{265}{}{Uno de nuestros clientes ordenó una película clásica, "Deep Throat." ¿Qué, nunca escuchaste de ella? ¡Qué pena! Bueno, uno de los necrófagos en San Isidro tiene una copia. Tráemela y tendrás tu paga.}
{1265}{}{Uno de nuestros clientes ordenó una película clásica, "Deep Throat." ¿Qué, nunca escuchaste de ella? ¡Qué pena! Bueno, uno de los necrófagos en San Isidro tiene una copia. Tráemela y tendrás tu paga.}
{266}{}{De acuerdo.}
{267}{}{¿En dónde habías dicho que podía encontrar la película?}
{268}{}{Uno de los necrófagos en San Isidro debería tenerla, pero no sé exactamente quién.}
{269}{}{Entendido.}
{270}{}{Aquí tienes la película que buscabas.}
{271}{}{Me encantan los clásicos. Pero no te recomendaría verla, eres demasiado joven, pequeñín. Ten tu dinero y olvídalo.}
{1271}{}{Me encantan los clásicos. Pero no te recomendaría verla, eres demasiado joven, cariño. Ten tu dinero y olvídalo.}
{272}{}{Está bien.}
{273}{}{Tengo un último trabajo para ti. La paga es buena - 500 chapas. Pero ten una cosa en cuenta, amiguito, no voy a tolerar el fracaso.}
{1273}{}{Tengo un último trabajo para ti. La paga es buena - 500 chapas. Pero ten una cosa en cuenta, cariño, no voy a tolerar el fracaso.}
{274}{}{Dime qué debo hacer.}
{275}{}{Espere un momento, un señor. ¡Ni una palabra más! Esto se está poniendo serio, así que me voy.}
{276}{}{En algún punto del camino a San Isidro, se perdió un robot mensajero que traía una parte. Necesito que me la traigas, es importante. Muévete, niño.}
{1276}{}{En algún punto del camino a San Isidro, se perdió un robot mensajero que traía una parte. Necesito que me la traigas, es importante. Ve a buscarla, cariño.}
{277}{}{[Irte]}
{278}{}{Bien, eres listo, chico. Ve a jugar afuera un rato, ya no te necesito.}
{1278}{}{Bien, eres lista, cariño. Ve a comprarte algo con lo que ganaste, ya no te necesito.}
{279}{}{[Irte]}
{280}{}{¿Podrías ser más específico sobre dónde está el robot mensajero?}
{281}{}{Es en algún punto en el camino desde acá hasta San Isidro. Seguramente sea en la carretera.}
{282}{}{Ya veo.}
{283}{}{Encontré la parte que querías, toma.}
{284}{}{¡Bien hecho! Nunca había tenido a alguien tan astuto en mi banda... o sea, mi equipo. Aquí tienes el dinero, creo que no tengo más trabajos para ti. Ve a descansar, pequeñín.}
{1284}{}{¡Bien hecho! Sé que no me decepcionarías, chiquita. Aquí tienes tu dinero, creo que no tengo más trabajos para ti. Ve a comprarte algo.}
{285}{}{[Irte]}
{1285}{}{Entonces iré a divertirme un rato. Adiós, Sr. De Santi.}
{286}{}{Por cierto, ¿por qué dice que es "Propiedad de Edward"?}
{287}{}{Es mejor que no hagas esas preguntas. Te estoy pagando por esto.}
{1287}{}{Es mejor que no hagas esas preguntas, cariño. Te estoy pagando por esto.}
{288}{}{[Irte]}
{289}{}{Oye, pequeñín, ¿te confundiste? Me dijeron que entregaste la parte a San Isidro. ¿Qué demonios hiciste?}
{1289}{}{Oye, cariño, ¿te confundiste? Me dijeron que entregaste la parte a San Isidro. ¿Qué demonios hiciste?}
{290}{}{Esa parte no era suya, señor.}
{291}{}{Ahora que lo pienso, es verdad. ¿Pero por qué te importa? Trabajas PARA MÍ. Demonios, me decepcionas. Ya no quiero verte, ¡lárgate!}
{1291}{}{Ahora que lo pienso, es verdad. ¿Pero por qué te importa? Trabajas PARA MÍ. Demonios, me decepcionaste, cariño. Ya no quiero verte, ¡fuera de aquí!}
{292}{}{[Irte]}
{293}{}{Ahora, escucha, tengo que hablarte de un problema muy grave. Hay un campamento de chatarreros aquí cerca. Exploran MIS ruinas y no piensan pagar impuestos. Deberían trabajar para mí aunque no lo quieran, y luego pueden sacarse de mis propiedad. Ve a encargarte de ellos.}
{294}{}{Lo haré.}
{295}{}{No haré eso. Tus ambiciones criminales no eran parte de mis planes, así que no seré tu cómplice.}
{296}{}{Me decepcionas. Creía que éramos amigos, es difícil encontrarlos en estos días. Déjame darte un último consejo: cuídate la espalda.}
{297}{}{Me niego a resolver tus problemas con los chatarreros.}
{298}{}{He resuelto el problema con los chatarreros.}
{299}{}{Jamás me decepcionas, bien hecho.}


# Services
{300}{}{Me gustaría relajarme.}
{301}{}{Lo siento, muchacho, pero mis servicios no son adecuados para los normaluchos.}
{1301}{}{Lo siento, lindura, pero mis servicios no son adecuados para los normaluchos.}
{302}{}{Es una pena.}
{303}{}{¿No son adecuados? Pero tengo chapas, sé que las quieres.}
{304}{}{Sólo admite que no te agradan los normaluchos.}
{305}{}{Son negocios, niño. No me interesa cocer vivo a un cliente. Pero dado que eres tan sensible, podría contarle a mis amigos que eres un buen normalucho. Te costará }
{1305}{}{Son negocios, cariño. No me interesa cocer viva a una cliente. Pero dado que eres tan sensible, podría contarle a mis amigos que eres una buena normalucha. Te costará }
{306}{}{No gracias. Me labraré una buena reputación de forma honesta.}
{307}{}{Trato hecho.}
{308}{}{Necesito las chapas, pequeñín. El respeto es caro.}
{1308}{}{Necesito las chapas, cariño. El respeto es caro.}
{309}{}{Vale.}
{310}{}{(cuenta las chapas con rapidez) Me inventaré una grandiosa historia que sea creíble, así los necrófagos estarán impresionados. Tienes mi palabra.}
{311}{}{Cuento contigo.}
{312}{}{Nada de engaños. Eso no me gusta.}
{313}{}{ chapas. ¿Te parece?}

{320}{}{Para empezar, recomiendo los baños curativos con mi encantadora asistente de baño. Y si tienes dinero y tiempo, te puedo ofrecer el paquete completo en el hotel, con películas, música y procedimientos terapéuticos. ¡El servicio es exclusivo a los mutantes y los necrófagos!}
{321}{}{Creo que me quedaré con el baño regular por ahora. ¿Cuánto cuesta?}
{322}{}{ chapas.}
{323}{}{Me parece bien, toma las chapas.}
{324}{}{Lo pensaré, ¿pero cuánto cuesta el paquete completo?}
{325}{}{Quizás otro día.}
{326}{}{Me interesa la segunda opción.}
{327}{}{Por }
{328}{}{ chapas te daremos el paquete completo terapéutico, que incluye desde baños de uranio a masajes, meditación y un sauna de hongos. Un necrófago soltará toda la tierra que haya acumulado en los últimos diez años.}
{329}{}{¡Me gusta cómo suena eso! Toma mis chapas.}
{330}{}{No tengo tanto dinero, pero un baño suena bien.}
{331}{}{¡Con ese dinero mejor lo hago yo! Adiós.}
{1331}{}{¡Con ese dinero mejor lo hago yo! Adiós.}
{332}{}{Los procedimientos terapéuticos te han hecho bien. Tu Resistencia ha mejorado.}
{333}{}{Los procedimientos terapéuticos te hicieron recuperar salud. Esperabas más.}

{350}{}{Te tengo un último trabajo. Hay un supermutante llamado Flores, ahora mismo se anda paseando en la Ruta 805 buscando algún propósito en la vida. Tráemelo y lo cuidaré, si trabaja para mí.}
{351}{}{Me pondré con ello.}
{352}{}{Flores ya llegó.}
{353}{}{¡Ya llegó! Flores protegerá la propiedad de una forma excelente. Ya no tengo más trabajos para ti. Ten tu última paga, felicitaciones, viviste para ver tu retiro.}
{354}{}{[Irse]}
{355}{}{Flores está muerto.}
{356}{}{Que malas noticias, y a mí no me gustan las malas noticias, me decepcionas. Lárgate, niño, ya no tengo más trabajo para ti.}
{1356}{}{Que malas noticias, y a mí no me gustan las malas noticias, me decepcionas. Lárgate, muñeca, ya no tengo más trabajo para ti.}
{357}{}{[Irse]}
{358}{}{Flores no quiso trabajar para ti, se fue con los carroñeros.}

