{100}{}{Ves a Frank.}
{101}{}{Ves a un necrófago con un traje de negocios y un sombrero, justo como en los viejos días.}
{102}{}{Gracias, amigo mío. Sin ti, esta historia habría acabado muy mal.}
{1102}{}{Gracias, señorita. Sin usted, esta historia habría acabado muy mal.}
{103}{}{¡No me toques, normalucho! Estoy tenso ahora mismo.}
{104}{}{Lo siento, pero estoy demasiado emocionado para hablar ahora.}

{110}{}{Jane, si lo encontramos, dejaré la bebida. Lo prometo.}
{111}{}{Prepárate para lo peor, Jane.}
{112}{}{Esto hubiera pasado algún día de todas formas.}
{113}{}{No llores. O empezaré a llorar también.}
