{100}{}{Ves a Peck.}
{101}{}{Ves a un necrófago con la columna retorcida. Su cabeza está cubierta de hongos brillantes.}
{102}{}{No hay problema, señor. Me iré cuando acabe de limpiar.}

{120}{}{Me siento maravilloso.}
{121}{}{Soy Peck. Peckster. ¿Quieres dormir conmigo?}
{122}{}{¿Sabes cuántas chapas tengo? Ninguna. ¡Y soy feliz así!}
{123}{}{Antes yo no tenía dinero. Y ahora nadie lo tiene.}
{124}{}{Me siento como una estrella de la tele.}
{125}{}{Éste es el mejor lugar del mundo. ¡Woohoo!}
{126}{}{Es hora de que Peck se tome la medicina. *Ñom ñom* Rico...}
{127}{}{¡La poli! ¡Es la poli! ¡NOOO...! Ay, sólo fue un sueño.}
{128}{}{Todo está bien, estoy bien... creo.}
{129}{}{Sin extranjeros, Dayglow no es Dayglow.}
{130}{}{No es que no tenga hogar. ¡Estoy libre de un hogar! Es distinto.}
{131}{}{Yo no tomo drogas. Mi cerebro las hace.}
{132}{}{¡Chingada madre!}

{200}{}{¡Alto ahí! No te asustes, pero estás en mi propiedad. Bueno... No me importa que estés aquí. Pero, es para que lo sepas.}
{1200}{}{¡Alto ahí! No te asustes, pero estás en mi propiedad. Bueno... No me importa que estés aquí. Pero, es para que lo sepas.}
{201}{}{¿Vives en la alcantarilla? ¿En serio?}
{202}{}{Sí, no tengo casa. ¿Y qué? ¡Vivo bien! Vivo en el lugar más bonito de Dayglow. ¿Me entiendes?}
{203}{}{¿Has pensado en mudarte a la ciudad con los demás?}
{204}{}{¿Por qué? Estoy bien aquí. Tengo comida, no tengo que seguir ninguna ley, tengo paz y tranquilidad.}
{205}{}{Me da miedo preguntar, ¿qué comes?}
{206}{}{No es sorpresa que estés cubierto en hongos. ¿Te has visto en el espejo?}
{207}{}{En el valle crece de todo, tengo de todo. Mira, ¿quieres unos hongos?}
{208}{}{Claro. ¿Qué quieres a cambio?}
{209}{}{No gracias. No es lo mío.}
{210}{}{El clima local es demasiado húmedo. En Necrópolis no era así, pero al menos no tengo que ir demasiado lejos para tomar mi medicina. ¿Quieres un poco?}
{211}{}{Volverás por otra dosis, lo sé.}
{212}{}{Sí, claro.}

{220}{}{Hola, ¿cómo te va?}
{221}{}{¿Cómo andas, compadre?}
{1221}{}{¿Cómo anda, señorita?}
{222}{}{Hola, jovencito. ¿Estás perdido?}
{1222}{}{Hola, jovencita. ¿Estás perdida?}
{223}{}{Adiós.}
{224}{}{Necesito más hongos.}

{230}{}{¿Cómo salgo de aquí?}
{231}{}{El puente más cercano está roto. ¿Es una pena, verdad? Desde aquí puedes subir al centro comercial, y de allí puedes ir a la carretera otra vez. ¡Y serás libre!}
{232}{}{Bien, me pongo en camino. Cuídate.}
{233}{}{Te daré 300 chapas si me llevas a San Isidro.}
{234}{}{Lo entiendo, lo entiendo. Peck se sabe todos los caminos de por aquí y las partes peligrosas. No podrás salir del valle sin mí.}
{235}{}{Entonces llévame. Aquí tienes }
{236}{}{ chapas.}

#Dialogue numbering fixed by cambragol
{237}{}{Olvídalo, puedo llegar por mi cuenta.}
{238}{}{Necesito llegar a la central eléctrica. ¿Me llevarás si te doy 500 chapas?}
{239}{}{Te pagaré 1.500 chapas si me llevas al Pueblo Viejo de forma segura.}



