{100}{}{Ves a Phil.}
{101}{}{Ves a un necrófago anciano con gafas. Se balancea débilmente en su silla.}

{200}{}{Oye, ¿qué personaje de libro se supone que eres, mi estimado? No recuerdo haber leído de ti.}
{1200}{}{Oye, ¿qué personaje de libro se supone que eres, mi dama? No recuerdo haber leído de ti.}
{201}{}{¿De qué estás hablando, vejestorio?}
{202}{}{¡Perdón, perdón! ¿Acaso un hombre ya no puede fantasear? Por cierto, soy Phil. Digamos que soy una especie de científico.}
{203}{}{Encantado de conocerte, Phil. Los estudiosos son raros de encontrar en estos días.}
{204}{}{Hola, biblióPHILo.}
{205}{}{Soy un ser humano de verdad, no soy un personaje ficticio.}
{206}{}{¿Hmm? (te observa a través de sus gafas) ¿De dónde proviene esa seguridad que tienes? Bueno, no importa. No es que podamos comprobarlo. Por cierto, soy Phil. Digamos que soy una especie de científico.}
{207}{}{Hmm. Quizás esto es una novela heroica o algo así.}
{208}{}{Ah, me gusta cuando las personas pueden ver la ironía en sí mismos. A diferencia de los melancólicos del otro lado de la otra sala. Se pusieron tan serios con construir la ciudad, más serios de lo que estuvieron sus vidas enteras. Por cierto, soy Phil. Digamos que soy una especie de científico.}
{209}{}{}

{210}{}{¿Necesitas ayuda con algo?}
{211}{}{No, nada.}
{212}{}{}
{213}{}{¡Perdón, perdón! ¿Acaso un hombre ya no puede fantasear?}
{214}{}{Parece que estás completamente sumergido en la literatura.}
{215}{}{Ah, me gusta cuando las personas pueden ver la ironía en sí mismos. A diferencia de los melancólicos del otro lado de la otra sala. Se pusieron tan serios con construir la ciudad, más serios de lo que estuvieron sus vidas enteras.}
{216}{}{Eso es natural.}
{217}{}{¿Hmm? (te observa a través de sus gafas) ¿De dónde proviene tanta seguridad? Bueno, no importa. No es que podamos comprobarlo. ¡Qué cosa tan mundana!}
{218}{}{La vida es generalmente aburrida, a no ser te entretengas con algo.}
{219}{}{No lo discutiré.}

{220}{}{¿Quién eres?}
{221}{}{Soy Phil. Digamos que soy una especie de científico. El cerebro de este lugar, por así decirlo.}
{222}{}{¿En serio?}
{223}{}{Bueno, ayudé con todo lo que necesitaba conocimiento de la preguerra, desde viejos manuales a programas para los Sres. Mañosos.}
{224}{}{Entendido.}
{225}{}{Y también soy un campeón mundial del ajedrez. Nadie me pudo vencer, ni siquiera esos astutos comunistas. ¡Y eran partidas de vida o muerte!}
{226}{}{Interesante.}
{227}{}{¿Qué tal si jugamos una partida? Quizás te pueda ganar y quebrar el récord mundial.}
{228}{}{¿Qué tal si jugamos una partida? Seguro que te gano y quiebro el récord mundial.}
{229}{}{¿Tú? ¡No me hagas reír! No tienes ninguna oportunidad contra mí. Soy el único que consiguió ganarle a la inteligencia artificial de ZAX. ¿Y tú?}
{230}{}{Aún así, quiero intentar.}
{231}{}{Una pérdida de tiempo.}
{232}{}{Entonces olvídalo. Buscaré algo más que hacer.}
{233}{}{Ya cometiste un error al decir que no tengo oportunidad, siempre las hay. Te reto a un duelo.}
{234}{}{Uy, eso suena tenso, como en una buena novela. Te daré una oportunidad. Una sola partida. Si me ganas, te daré acceso a mi biblioteca.}
{235}{}{Tengo que prepararme primero. Nos vemos.}
{236}{}{Estoy listo para nuestra batalla en el tablero. ¡Vamos a comenzar!}
{1236}{}{Estoy listo para nuestra batalla en el tablero. ¡Vamos a comenzar!}
{237}{}{Nada mal. Lo hiciste bien, para un novato. Necesitarás mucha más práctica para derrotarme.}
{238}{}{Bueno, no me resultó.}
{239}{}{Hablemos de otra cosa.}
{240}{}{¿Me derrotaste a MI? ¡Eso fue extraordinario!}
{1240}{}{¿Me derrotaste a mí? ¡Qué mujer más extraordinaria!}
{241}{}{¿Quieres jugar una partida de ajedrez?}
{242}{}{¿Ahora ves que no vale la pena subestimar a tus oponentes?}
{243}{}{Definitivamente fue un golpe de suerte. Siento haber batido tu récord mundial.}
{1243}{}{Definitivamente fue un golpe de suerte. Siento haber batido tu récord mundial.}
{244}{}{No entiendo, ¿cómo me pudo haber pasado esto? Estudié TODOS los movimientos posibles en el ajedrez durante 90 años. Pero ese movimiento que hiciste... ¿Por qué no pude predecirlo? Quizás me oxidé sin tener a alguien con quién jugar. ¡Por eso es importante tener un enemigo! Definitivamente deberíamos aprender del otro.}
{245}{}{Claro. ¿Ahora me dejarás leer tu biblioteca?}

{250}{}{¿Qué se puede hacer por aquí?}
{251}{}{Déjame pensar... Butler debe tener algunos quehaceres. Está tratando de devolver la vida a la ciudad, y también lidiando con la llegada de forasteros del norte. Todos los demás también tienen problemas. Cada uno tiene los suyos.}
{252}{}{¿Puedes ser un poco más específico?}
{253}{}{Lo lamento, pero últimamente he estado tan absorto en esta maravillosa novela que he dejado de estar al tanto de lo que ocurre en la ciudad.}
{254}{}{Entendido.}
{255}{}{¿Qué estás leyendo?}
{256}{}{Ahora mismo, un viejo libro acerca de los conquistadores españoles. Es aburrido, la verdad no es lo mío.}
{257}{}{¿Necesitas algún libro en específico?}
{258}{}{Está bien, sigue leyendo.}
{259}{}{¡Sí, hay uno! Justo antes de la guerra, se anunció un nuevo libro de Mortimer acerca de San Diego. Me da curiosidad qué idioteces habrá escrito sobre esta maravillosa ciudad.}
{260}{}{¿Dónde podría encontrarlo?}
{261}{}{En algún lado de las ruinas, supongo. No sé donde exactamente.}
{262}{}{Está bien, iré a buscarlo.}
{263}{}{Entonces anda a buscarlo tú. Tengo cosas más importantes que hacer.}
{264}{}{Tienes suerte, porque lo tengo justo aquí.}
{265}{}{Encontré el libro de Mortimer.}
{1265}{}{Encontré el libro de Mortimer.}
{266}{}{¡Un libro nuevo! Ah, hace tanto que no me sentía tan emocionado ante una edición fresca. Veamos que cosas tan sensacionales habrá reunido Mortimer sobre San Diego... Ah, cierto, debes querer que te pague o algo así. Ten, 100 chapas. Ahora vete, ¡vete, no interrumpas mi lectura!}
{267}{}{Adiós.}

{270}{}{Ahora mismo, un viejo libro acerca de los conquistadores españoles. Es aburrido, la verdad, no es lo mío.}
{271}{}{Ahora mismo, la guía telefónica de la ciudad de Vancouver. Tiene una narrativa muy monótona.}
{272}{}{Ahora mismo, historias sobre las últimas guerras del petróleo. ¿Sabes? En ese entonces habían países que capturaban nuestros barcos petroleros, es bueno que todo eso haya acabado.}
{273}{}{Ahora mismo, una lista de reglas para volar un dirigible. ¿Te da risa? Bueno, algún día, alguien los volverá a pilotar. Créeme.}
{274}{}{Ahora mismo, una historia sobre cómo los comunistas se apoderaron de los Estados Unidos y crearon un estado totalitario. Hasta ahora, está muy bueno.}

{280}{}{Necesito un holodisco con programación para un Sr. Mañoso.}
{281}{}{Eso no es difícil. Pero tengo la cabeza muy metida en este maravilloso libro, ¡No puedo mirar a otro lado!}
{282}{}{¿Y si te trajera más libros?}
{283}{}{¿Más libros? ¡Sí! Tráeme cinco libros de la preguerra, y te ayudaré con el programa. Será fácil.}
{284}{}{Está bien.}
{285}{}{Tengo los libros conmigo, aquí tienes.}
{286}{}{¡Ah, para mi colección! Bueno, tendré que hacerlo, tendré que sacar la cabeza del libro. Programaré eso que querías... Espera, ¿Qué era lo que querías?}
{287}{}{Un holodisco con programación de administrador...}
{288}{}{¿Y si sólo ayudas a una buena persona?}
{289}{}{Por supuesto, ayudaré a una BUENA persona, el momento en que la vea. Aquí no veo a ninguna.}
{290}{}{¡Eres un idiota!}
{291}{}{Ya me dejas claro que no soy una buena influencia en tus ojos. Eso me entristece.}
{292}{}{Olvídalo, tengo los libros. Toma.}
{293}{}{Phil, ¿cómo puedes ser tan egoísta? Estamos todos juntos en esto. ¡Vamos, ayúdame con el maldito programa!}

