{100}{}{Ves a un necrófago.}
{101}{}{Ves a un necrófago de apariencia asquerosa y de un solo ojo. Sus rostro está congelado en un gruñido perpetuo.}
{102}{}{Hola, forastero.}
{1102}{}{Hola, forastera.}
{103}{}{Acércate, no tengas miedo. Solo quiero "tocar" tu suave y lisa piel...}
{1103}{}{Acércate, no tengas miedo. Solo quiero "tocar" tu suave y lisa piel...}
{104}{}{¡Corre, pendejo, corre! Si te atrapo, serás mi cena.}
{105}{}{No hay nada de especial por aquí. Disfruta la vida eterna.}
{1105}{}{No hay nada de especial por aquí. Disfruta la vida eterna.}

{200}{}{Oye, tú, el de la cara fea. Ven. ¿Tienes chapas?}
{201}{}{Sí, unas cuántas.}
{202}{}{Dame 10 chapas, rápido.}
{203}{}{Claro, ten. Lo que sea por ustedes.}
{204}{}{Cuidado con lo que dices, no me ando con juegos. Piérdete.}
{205}{}{Como digas...}
{206}{}{Ten, 10 chapas.}
{207}{}{Muy bien... Veo que eres un ricachón, así que dame otras 10.}
{1207}{}{Muy bien... Veo que eres una niña consentida, así que dame otras 10.}
{208}{}{Aquí tienes las 10. ¿Estás contento?}
{209}{}{Ten todo lo que tengo. ¿Estás contento?}
{210}{}{Algo, amo los idiotas como tú. Aunque no es tan divertido como antes... ¿Por qué te estoy hablando? Lárgate.}
{211}{}{Vete al infierno.}
{212}{}{No eres nadie en esta ciudad, no olvides eso. Es mejor que te vayas.}
{213}{}{Será un placer.}
{214}{}{Ten, es todo lo que tengo, pero es menos que 10.}
{215}{}{Me basta, así que sácate de aquí, estoy de buen humor.}
{216}{}{No.}
{217}{}{No te creo, enséñame tu bolsa.}
{218}{}{Claro, echa un vistazo.}
{219}{}{Justo lo que pensé, los normaluchos solo saben mentir. Como castigo, me voy a llevar TODAS tus chapas. Piérdete.}
{220}{}{Como digas...}
{221}{}{¡Dámelas de vuelta, bastardo!}
{222}{}{Claro, echa un vistazo.}
{223}{}{¡Agh! Eres inútil, ¡fuera de mi calle!}
{224}{}{Será un placer.}
{225}{}{Toca mis cosas y vas a perder los dedos que te quedan.}
{226}{}{[Corre del mendigo tan rápido como puedas]}
{227}{}{[Ignóralo y sigue caminando]}
{228}{}{¡Oye, detente! Te estoy hablando, normalucho.}
{229}{}{[Ignóralo]}
{230}{}{¿Qué quieres?}
{231}{}{Está bien, tengo chapas. ¿Cuánto necesitas?}
{232}{}{Pero no tengo chapas.}
{233}{}{Vete al carajo.}
{234}{}{¿Y por qué debería darte chapas?}
{235}{}{Es lo que me debes si voy a tolerar tu asquerosa cara suave en mi hermosa ciudad. Dame las chapas, ahora.}

{250}{}{¡Mis respetos, señor! ¿Es su primera vez en la ciudad? Puedo enseñarle todo por sólo 10 chapas.}
{1250}{}{¡Mis respetos, señorita! ¿Es su primera vez en la ciudad? Puedo enseñarle todo por sólo 10 chapas.}
{251}{}{Claro, ten 10 chapas.}
{252}{}{Lo siento amigo, estoy quebrado. Tal vez otro día.}
{253}{}{Muchas gracias... Bueno, ahí está el monorriel, y allá está la frontera Mexicana. Al norte hay un pueblo necrófago. Eso, adiós...}
{254}{}{¡No me dijiste nada, maldito estafador!}
{255}{}{Eso fue... útil. Gracias.}
{256}{}{Hola.}
{257}{}{Adiós.}

