{100}{}{Ves a un necrófago.}
{101}{}{Ves a un necrófago sin nada fuera de lo común.}
{102}{}{Z-z-z...}

{110}{}{Agh...}
{111}{}{Ay...}
{112}{}{Duele...}
{113}{}{Todavía me duele...}

{200}{}{¡Oye, ayúdame! El techo colapsó encima mío y me quebré unos huesos. Estas casas ya no valen nada...}
{201}{}{¡Oye, ayúdame! El techo colapsó encima mío y me quebré unos huesos. Estas casas ya no valen nada...}
{202}{}{¡Oh Dios mío! No te muevas, ¡Te ayudaré!}
{203}{}{Sigue soñando. Ni siquiera quiero mancharme las manos con un fenómeno como tú.}
{204}{}{No voy a ayudarte. Sólo me llevaré tus cosas y te daré por muerto. Y por cierto, nadie te va a escuchar.}
{205}{}{¡No! ¡No! ¡Nooo!}
{206}{}{Te veo en la otra vida. Quizás.}
{207}{}{¡Sólo bromeo, viejo! Espérame, te ayudaré apenas pueda.}
{208}{}{Jamás pensé que un normalucho vendría a ayudarme, especialmente en medio de unas ruinas irradiadas. Gracias, amigo mío.}
{1208}{}{Jamás pensé que una normalucha vendría a ayudarme, especialmente en medio de unas ruinas irradiadas. Gracias, señorita.}
{209}{}{De nada. Por cierto, ¿Qué estabas haciendo aquí?}
{210}{}{No olvides de contarle a los demás necrófagos de mi buena acción. ¿Cómo acabaste en este lugar?}
{211}{}{Estaba explorando las ruinas, por supuesto. Pero los pisos de por aquí son muy frágiles, ve con cuidado. Pero, ese no es el peligro de verdad. Por la ventana vi una criatura, era enorme, terrorífica, con garras como sables. No dejes que te agarre desprevenido. Buena suerte, yo me iré al campamento más cercano.}
{212}{}{Gracias por el aviso. Nos vemos.}
{213}{}{No recuerdo haberte visto. ¿No nos habremos cruzado en Necrópolis, verdad? Eso es raro. Pero, te lo agradezco, amigo mío. Sin ti, ni siquiera habría llegado hasta la puerta.}
{1213}{}{No recuerdo haberte visto. ¿No nos habremos cruzado en Necrópolis, verdad? Eso es raro. Pero, te lo agradezco, amiga mía. Sin ti, ni siquiera habría llegado hasta la puerta.}
