{102}{}{Hoy nos encontraste de buen humor. No te metas en nuestro camino de nuevo.}
{103}{}{¡Muerte a los normaluchos!}
{104}{}{¡Sálvame de estos mutantes pendejos!}
{105}{}{La última vez que me hicieron eso fue antes de la guerra. En ese entonces eran matones, ahora son los mutantes, todo sigue igual.}
{106}{}{Ay, pensé que estaba acabado. Ten, un estimulante y mi eterna gratitud. Gracias, amigo.}
{107}{}{}
{108}{}{}
{109}{}{}

{200}{}{¿A quién tenemos aquí? ¡Ven aquí, humanito! Serás mi postre...}
{201}{}{Tendrás que atraparme primero, idiota.}
{202}{}{¡Por favor, no me hagas daño!}
{203}{}{Mis hermanos dijeron lo mismo mientras eran masacrados por los normaluchos. ¡MUERE, PERRA!}
{204}{}{¡Te haré pedazos!}
{205}{}{No, por favor...}
{206}{}{Escucha, intento ayudar a los necrófagos. ¡Ten piedad, no soy tu enemigo!}
{207}{}{¿Tú? ¿Ayudando a los necrófagos! ¡Jajaja, me haces reír! No sabía que existían idiotas como tú.}
{1207}{}{¿Tú? ¿Ayudando a los necrófagos! ¡Jajaja, me haces reír! No sabía que existían idiotas como tú.}
{208}{}{Por favor, deja que este necrófago y yo nos vayamos en paz. Nadie te está amenazando.}
{209}{}{¿Por qué desperdicio el tiempo hablando contigo? ¡Muere, fenómeno!}
{210}{}{Alguien como tú ni siquiera merece manchar mis manos. No te metas en nuestro camino de nuevo.}
{211}{}{Santa Catarina, eso estuvo cerca...}
{212}{}{Mira, otro cuerpo andante. Estamos teniendo suerte con atrapar a los necrófagos.}
{213}{}{Te ves fuerte y amenazante, pero careces de cerebro.}
{214}{}{¡Por favor, no nos hagas daño! ¡Somos de la misma sangre!}
{215}{}{No somos enemigos, ambos somos mutantes. Seamos amigos, ¿bien?}
{216}{}{¿Qué has dicho? ¡Cierra la boca, sabandija! No somos unos sucios mutantes, ¡somos soldados purasangre del Maestro!}
{1216}{}{¿Qué has dicho? ¡Cierra la boca, perra! No somos unos sucios mutantes, ¡somos soldados purasangre del Maestro!}
{217}{}{Parece que solo te enojé más...}
{1217}{}{Parece que solo te enojé más..}
{218}{}{Hmm, eso es cierto. Todos nos odian por esto, pero es lo único que nos une. No somos carroñeros como tú, ¡somos soldados purasangre del Maestro! Recuerda eso, mestizo.}
{219}{}{Sí, señor. Lo recordaré.}
{220}{}{¿Gomer? Jamás pensé que te unirías con... ellos.}
{221}{}{Sí, decidimos unir fuerzas. ¿Tan malo te parece?}
{222}{}{Un normalucho y un nocturno uniendo fuerzas, jamás había visto algo así. Pero si Gomer está contigo, no vamos a interferir.}
{223}{}{Menos mal.}
