{100}{}{Ves a Falik.}
{101}{}{Ves a un necrófago sin nada fuera de lo común.}
{102}{}{Escuchaste la confesión del necrófago.}
{103}{}{¡Estoy orando, no me interrumpas!}
{104}{}{Perdóname por haberte tratado mal.}

{105}{}{¡Oye, deja de escuchar a escondidas!}
{106}{}{Estoy en medio de una confesión. Apresúrate en lo que debas hacer.}
{107}{}{¡Estás interrumpiendo mi confesión, normalucho!}
{108}{}{¿Acaso me estás espiando?}

{110}{}{Padre, usted puede guardar un secreto, ¿verdad?}
{111}{}{¿Le puedo hablar de mi historia?}
{112}{}{Escúcheme, Padre.}
{113}{}{Mi amigo Zerah es un necrófago. Pero ahora la parte de "necro" es más cierto que nunca, murió...}
{114}{}{Bueno, no fui yo, exactamente...}
{115}{}{Pero lo abandoné.}
{116}{}{Demonios, todo pasó en el hospital.}
{117}{}{Zerah y yo estábamos buscando en las ruinas cuando nos encontramos con los chatarreros.}
{118}{}{¡Me sigue dando escalofríos! Y ni siquiera tengo piel.}
{119}{}{Los chatarreros agarraron y asesinaron a Zerah. Y yo corrí y me escondí.}
{120}{}{Dígame, Padre, ¿Dios me lo perdonará?}

{200}{}{(Falik está rezando con mucho fervor.)}
{201}{}{Escuché tu confesión por accidente.}
{1201}{}{Escuché tu confesión por accidente.}
{202}{}{[Déjalo en paz]}
{203}{}{¡Bastardo! ¡No le digas a nadie!}
{204}{}{No te culpo, lo entiendo. Hiciste lo correcto.}
{205}{}{Ay, amigo mío, no le digas a nadie, ¡por favor!}
{1205}{}{Ay, señorita, no le diga a nadie, ¡por favor!}
{206}{}{¿En serio? Bueno, gracias. Pero eso no traerá de vuelta a Zerah.}
{207}{}{¿Estás seguro de que murió?}
{208}{}{No mereces mi atención. Eres patético, un cobarde y un debilucho, ¡abandonaste a tu amigo cuando estaba en problemas!}
{209}{}{¡Es fácil para ti decirlo! ¡No estabas ahí! Ni siquiera conocías a Zerah. ¿Por qué te importa?}
{210}{}{¿Estás seguro de que murió?}
{211}{}{¡Es imposible que siga vivo! Debe seguir tirado en el piso del hospital. Pero no me atrevo a ir y recuperar su cuerpo para enterrarlo con honor.}
{212}{}{Puedo hacer eso por ti. Pero no gratis.}
{213}{}{Está bien, iré a buscar su cuerpo. Tu historia me conmovió.}
{214}{}{¡No necesito tu ayuda! Sólo déjame sólo y no vuelvas a hablarme.}
{215}{}{De todas formas iré a ver. Adiós.}
{216}{}{Lo agradecería de verdad.}
{217}{}{De nada. Adiós.}

{220}{}{(Falik sigue rezando fervientemente)}
{221}{}{[Déjalo.]}
{222}{}{Zerah está muerto. Su cuerpo está en el hospital.}
{223}{}{(pausa) Ah... Lo sabía. No debería haber tenido esperanzas. Pero al menos sé la verdad ahora.}
{224}{}{La vida nunca ha sido buena. Adiós.}
{225}{}{Lo siento mucho.}
{226}{}{Resulta que Zerah estaba vivo. Los chatarreros lo tenían capturado y lo torturaron, pero lo rescaté..}
{227}{}{¿¡ESTÁ VIVO!? ¡Ay Dios mío, mis plegarias funcionaron! Estoy seguro de que Él te envió a ayudarme.}
{228}{}{No, Dios no tuvo nada que ver con ésto.}
{229}{}{Puedes pensar eso, si gustas.}
{230}{}{¿Te puedo pedir un último favor? ¿Podrías ayudar a reconciliarme con él? ¡Encuéntralo y dile que quiero pedirle perdón!}
{231}{}{}

