{100}{}{Ves a Rupert.}
{101}{}{Ves a un necrófago con un traje de la preguerra.}
{102}{}{Ves a un necrófago.}
{103}{}{Si no fuera por De Santi, ya nos habríamos reencontrado hace mucho.}
{104}{}{Hola. Te ves muy bien... para un cadáver.}
{105}{}{¡Agh! Jamás me podré acostumbrar a sus asquerosas caritas de bebé.}
{106}{}{¡Oh-h!}
{107}{}{Sí que eres un aguafiestas.}

# added to make the ghoul trait actually work - cambragol
{198}{}{Vaya, ¿qué tal? Te ves muy joven, para un cadáver. Jeje.}
{199}{}{No soy ningún cadáver.}

{200}{}{Saludos. Te ves muy bien... para un cadáver.}
{201}{}{No soy un cadáver.}
{202}{}{Bueno, sí que tienes suerte. Yo también la tengo. ¡Cada vez gano más y más puntos!}
{203}{}{Bueno, sobre eso...}
{204}{}{¡Ojalá siempre fuera así de suertudo! Pensé que la tercera edad sería aburrida, pero en este hotel, ¡me siento más joven que nunca! ¡Es tan divertido!}
{205}{}{La verdad, yo...}
{206}{}{Me alegra que...}
{207}{}{Y ahora, perdóname, pero a papá ya no le basta la pensión. ¡Bueno, qué demonios! ¡Apuesto al rojo!}
{208}{}{No voy a interferir.}
{209}{}{Cuidado, anciano, podrías perder tu alma.}

{220}{}{No me eches la sal, que tengo una buena mano.}
{221}{}{[Ignóralo]}
{222}{}{Dime, ¿cómo te llamas, viejo?}
{223}{}{¡Mi nombre es El Hijo de Puta Más Afortunado Del Mundo!}
{224}{}{Hablo en serio.}
{225}{}{Escucha, no me arruines el día. No quiero ser amigos contigo, llámame viejo si quieres. No me importa.}
{226}{}{Está bien. Como digas, viejo.}
{227}{}{Eres Rupert, ¿verdad?}
{228}{}{¡Cof cof! No sé de quién hablas, jamás había oído ese nombre.}
{229}{}{Quizá debería hablar con el recepcionista, o echar un ojo al registro de huéspedes.}
{230}{}{¿De verdad? Perdón por molestarte.}
{231}{}{¿Qué quieres? ¿Quién te envía?}
{232}{}{La Abuela Judy. Está buscando a su esposo desaparecido, y parece que está gastándose todo su dinero a escondidas.}
{233}{}{(suspiro) Escucha, amiguito, ¿crees que estaría sentado aquí si quisiera estar con Judy?}
{1233}{}{(suspiro) Nena, ¿crees que estaría sentado aquí si quisiera estar con Judy?}
{234}{}{La verdad no me importa.}
{235}{}{¿Y cuál es la razón detrás de tu comportamiento?}
{236}{}{Eres un hombre, ¡Deberías entender cómo es que te fastidie tu mujer durante 80 años!}
{1236}{}{¡Eres una mujer, no podrías entender cómo es que te fastidie tu mujer durante 80 años!}
{237}{}{[Escucha]}
{238}{}{Me siento bien aquí. Hago lo que quiero - bebo, miro películas, juego a la ruleta. ¿Sabes? Judy jamás me dejó jugar con la maldita ruleta, y yo siempre quise.}
{239}{}{Sabes que seguramente está trucada, ¿verdad?}
{240}{}{Bueno, sí. Pero no importa, ¡lo que importa es que por fin puedo jugar!}
{241}{}{No estará feliz si se entera de que estabas escondido de ella mientras te estaba buscando.}
{242}{}{Lo sé. Mira, ¿Puedes decirle que fallecí? No es asunto tuyo, y podré vivir sin su supervisión total con el tiempo que me queda.}
{243}{}{Bueno. ¿Por qué no?}
{244}{}{¿Lo harás? ¿De verdad? ¡Qué suerte tengo hoy! ¡La mejor del mundo!}
{245}{}{Está bien, adiós.}
{246}{}{No. Tienes que encontrarte con ella. Es la persona más cercana que te queda. No está bien esconderte de ella ahora que estás en tus últimos días.}
{247}{}{¿Por qué tienes que ser un aguafiestas? (suspiro) Está bien. Tienes razón. Se enterará por tu parte de todas formas.}
{248}{}{Sí, ve y habla con ella. Vive en San Isidro.}

{250}{}{Como lo pediste, le dije que habías muerto. ¿Y sabes qué pasó? ¡Su corazón no lo soportó y explotó!}
{1250}{}{Como lo pediste, le dije que habías muerto. ¿Y sabes qué pasó? ¡Su corazón no lo soportó y explotó!}
{251}{}{Cómo... no puede ser... No esperaba que... Oh... Agh...}
{252}{}{No me digas que tú también...}

