{102}{}{Bueno, ¿y ahora qué?}
{103}{}{¡Mataré a cada bastardo de la Hermandad que encuentre!}
{104}{}{¡Odio a la Hermandad! ¡Los odio!}

{110}{}{¡Suelta el arma y sal de ahí! ¡Te mataré a ti y a cada bastardo de la Hermandad!}
{111}{}{No te haré nada. Sólo quiero hablar contigo.}
{112}{}{Dime todo lo que te has estado guardando.}
{113}{}{¿Sabes a cuántos de los nuestros mataron en Lost Hills?}
{114}{}{Nos quitaron nuestro hogar. Nos quitaron a nuestro dios.}
{115}{}{¿Crees que podemos llevarnos bien luego de esto?}
{116}{}{Estoy TAN enojado. Pero seré amable contigo, te mataré rápidamente. No sentirás nada.}
{117}{}{¿Me escuchas?}
{118}{}{¿Por qué sufres? ¿Por qué te resistes? Te liberaré de tu tormento.}
{119}{}{Dios estaba de nuestro lado. Y del suyo solo habían generales. ¡Humanos estúpidos, miren lo que hicieron!}

{200}{}{Oye, pedazo de carne, ten cuidado. Hay un idiota de la Hermandad por aquí. Si lo ves, ten cuidado de que no te dispare.}
{201}{}{Ya veo. Entonces me voy antes de que se ponga muy peligroso.}
{202}{}{¡No te atrevas a meterte con la Hermandad! ¡No dejaré que hagas eso!}
{203}{}{¡Vi que se escapó hacia los muelles! Mientras hablabas solo, aprovechó de escapar.}
{1203}{}{¡Vi que se escapó hacia los muelles! Mientras hablabas solo, aprovechó de escapar.}
{204}{}{¿Qué demonios...? ¡Agh! ¡Lo voy a atrapar! ¡No escapará!}
{205}{}{¡Apresúrate, grandulón!}
{206}{}{¡Jajaja! ¡Eres un idiota! ¡Es más fácil engañarte a ti que a un niñito! ¿Qué te tiene tan molesto?}
{207}{}{¿Gomer? ¿Estás aquí? Vaya, ¿esclavizaste un humano? Bien hecho. Yo intento sacar a un soldadito de la Hermandad, está escondido en el café. ¿Me ayudarás a encargarme de él?}
{208}{}{Gomer, salgamos de aquí. Esto no es asunto nuestro.}
{209}{}{Gomer, dile a éste tonto que la guerra ya terminó. Deja de pelear y deja al humano en paz.}
{210}{}{¿Tú y Gomer son... amigos? No había escuchado de algo así. Quizás sí es hora de hacer las paces. Está bien, Gomer, confiaré en ti.}
{211}{}{Muy bien. Ve en paz.}
{212}{}{¡Ahh! ¡Mueran, humanos estúpidos!}
{213}{}{¡Después de ti, imbécil!}
{214}{}{¡Espera, déjame hablar!}
{215}{}{¡Detente! No tenemos que luchar. No quiero hacerte daño.}
{216}{}{¡Jamás perdonaré lo que nos hicieron los humanos!}
{217}{}{Es una pena que no puedas verlo como yo...}
{218}{}{Estás perdiendo el tiempo...}
{219}{}{Los necrófagos no están felices con lo que haces. Están construyendo una ciudad nueva, los humanos y los mutantes podrán vivir juntos en Dayglow. ¿No quieres la paz?}
{220}{}{¡Los necrófagos son unos ingenuos! Un día pagarán por esto, los humanos los traicionarán.}
{221}{}{Entonces debes protegerlos, no dejes que los humanos los manipulen. Siempre habrán más humanos, un sólo muerto no arreglará nada.}
{222}{}{Eso es verdad, no lo había pensado así. ¿Debería ir hacia la ciudad...? Quizás me ofrezca como guardia a los necrófagos... Sí, ¡sí, es una buena idea! ¡No dejaré que nadie le haga daño a los necrófagos, nunca!}
{223}{}{Muy bien. ¿Ves? Siempre se puede llegar a un acuerdo.}
{224}{}{Estoy de acuerdo contigo. Bueno, ¿seguimos peleando, idiota?}

