{100}{}{Ves a un necrófago.}
{101}{}{Ves a un necrófago con armadura y casco de combate.}

{200}{}{John me habló de ti, dijo que eres un tipo listo. ¿Pero en serio irás a la isla con esa suave carita de bebé?}
{1200}{}{John me habló de ti, dijo que eres una muchacha inteligente. ¿Pero en serio irás a la isla con esa suave carita de bebé?}
{201}{}{Buena pregunta. Tengo que pensarlo.}
{202}{}{No debería importarle a tu cara de necrófago, estás hecho mierda.}
{203}{}{John me habló de ti, dijo que eres un tipo listo. Te esperan problemas en esa isla, lo entiendes, ¿verdad?}
{1203}{}{John me habló de ti, dijo que eres una muchacha inteligente. Te esperan problemas en esa isla, lo entiendes, ¿verdad?}
{204}{}{Buena pregunta. Debería prepararme de antemano.}
{205}{}{No recuerdo haberte preguntado.}
{206}{}{John me habló de ti, pero no esperaba ver a la gente de Gustavo. ¿Qué está pasando?}
{207}{}{Sí, le falta gente. Gustavo va a supervisar la operación.}
{208}{}{Gustavo será nuestro supervisor. ¿Entendido?}

{210}{}{Bueno. Este es el plan, tenemos un transpondedor, los robots no nos atacarán mientras estemos dentro de su alcance. Así que solo tenemos que subirnos al bote e ir hacia la isla. Ahí vemos como le hacemos.}
{211}{}{Necesito prepararme. Espérame un momento.}
{212}{}{Entiendo. ¿Cuál es mi objetivo en la isla?}

{220}{}{Pero la base está destruida, ¿no? ¿Qué se podría rescatar de ahí?}
{221}{}{La isla entera fue bombardeada, la tierra aún está irradiada, pero los niveles subterráneos todavía siguen ahí. Los robots suben, luego bajan y aún los reparan. La base era una de las más grandes en la América de la preguerra, así que incluso después del bombardeo, todavía deberían haber reliquias por ahí.}
{222}{}{Los niveles de radiación deben estar muy altos.}
{223}{}{Por supuesto, es por eso que sólo los necrófagos y los robots podemos trabajar ahí. Eso nos conviene mucho. Pero tendrás que prepararte bien si no quieres que te cocinen los radioisótopos.}
{224}{}{¿Y por qué no han ido allá hasta ahora?}
{225}{}{Por las armas de la isla. Varias sobrevivieron gracias a escudos durante el bombardeo. Están a través de toda la costa, y evitan que nos acerquemos demasiado. Además, hay barricadas, escombros en el agua, minas submarinas y robots patrulleros. Tampoco habíamos conseguido el transpondedor hasta ahora, lo recibimos de la fábrica de aviones. Buen trabajo, por cierto.}
{226}{}{¿Cuál es mi objetivo en la isla?}
{227}{}{Tu trabajo, suavecito, es deshabilitar el sistema de seguridad para que los robots y las armas dejen de dispararnos. Luego de eso, nosotros nos encargaremos y veremos qué extraer y cómo.}
{1227}{}{Tu trabajo, suavecita, es deshabilitar el sistema de seguridad para que los robots y las armas dejen de dispararnos. Luego de eso, nosotros nos encargaremos y veremos qué extraer y cómo.}


{250}{}{¡Ah! ¿Hueles ese aire fresco?}
{251}{}{Sólo siento el polvo radioactivo de la tierra quemada.}
{252}{}{Bueno, para gustos, colores. No lo olvides, tu objetivo es deshabilitar el sistema de seguridad y luego nos encargamos nosotros. Pero ten cuidado con lo que tocas; todavía hay muchos juguetes militares que te pueden hacer polvo.}
{253}{}{Gracias, capitán obvio.}
{1253}{}{Gracias, capitán obvio.}
{254}{}{Entendido.}
{255}{}{Tu objetivo es deshabilitar el sistema de seguridad, nos ocuparemos del resto y podrás regresar al puerto.}
{256}{}{La alerta de combate fue desactivada. El acceso a la base está abierto a todos los interesados.}
{257}{}{¡Bien hecho! Nos ocuparemos del resto. Puedes volver al puerto, pero no podrás volver aquí.}
{258}{}{Vale.}
{259}{}{Por cierto, ¿qué planean hacer con lo que encuentren?}
{260}{}{Tomarlos, por supuesto. Todo lo útil que haya, desde munición a electrónicos, lo usaremos para ayudar a Dayglow o para venderlos.}
{261}{}{¿Entonces los juguetitos peligrosos terminarán en las manos del mejor comprador?}
{262}{}{Por supuesto. ¿Algún problema?}
{263}{}{No, señor. Ninguno.}
{264}{}{¡Idiota! ¡Si llegan a las manos equivocadas será un desastre! No dejaré que te lleves nada.}
{265}{}{Todo lo que sea útil, desde munición a electrónicos, lo usaremos para ayudar a Dayglow.}
{266}{}{Entendido.}

