{100}{}{Ves a Tobias.}
{101}{}{Ves a un necrófago con uniforme de la patrulla fronteriza. Su rostro está desfigurado, y su mirada es tenebrosa.}
{104}{}{Gracias. Siempre sentí que me faltaba algo.}
{105}{}{Tobias coloca la placa en su uniforme. Observas algo parecido a una sonrisa en su desbaratado rostro.}
{106}{}{Tobias ya tiene una placa así..}

{200}{}{[No puedes pasar. Sólo pasan los necrófagos.]}
{201}{}{[Bien, me voy.]}
{202}{}{[Entonces pasaré a la fuerza..]}
{203}{}{[Dame una tarea para que me dejes pasar.]}
{204}{}{[Destruye el robot en Tijuana.]}
{205}{}{[Vale.]}
{206}{}{[Robot neutralizado.]}

{210}{}{Humano, este no es tu lugar. Vete.}
{211}{}{Nada te da el derecho de echarme.}
{212}{}{(te apunta con el rifle) No pasarás hasta que yo lo diga.}
{213}{}{Pasaré de todos formas. ¡Fuera de mi camino, fenómeno!}
{214}{}{Ya, ya, tampoco tengo tantas ganas de pasar...}
{215}{}{¿Por qué no quieres dejarme pasar?}
{216}{}{Un normalucho como tú no tiene sitio en la ciudad de los necrófagos. Ustedes son el por qué vivimos entre estas ruinas.}
{217}{}{Mira, caminé mucho para llegar hasta acá. ¿No podemos llegar a un acuerdo?}
{1217}{}{Mira, caminé mucho para llegar hasta acá. ¿No podemos llegar a un acuerdo?}
{218}{}{Bueno, entonces me voy. Lamento haber molestado.}
{219}{}{Hmm... Quizás te deje pasar si nos haces un favor.}
{220}{}{¿Qué clase de favor?}
{221}{}{En las ruinas de Tijuana, hay un robot militar gigante que deambula desde antes de la Guerra. No nos deja explorar tranquilos el área. Destrúyelo, y te dejaré pasar la frontera.}
{222}{}{Mejor te destruyo a ti. Mucho más fácil.}
{223}{}{Trato hecho. Lo haré.}
{224}{}{Su último avistamiento fue en la Plaza de Toros. Colocamos algunas trampas electromagnéticas, pero no hemos tenido suerte.}
{225}{}{Entendido. Lo tendré en mente.}
{226}{}{Ya me encontré con ese robot. Ya no es un peligro para nadie.}
{227}{}{No soy un suicida. Mejor vuelvo a Sonora...}
{228}{}{No vas a pasar la frontera hasta que te de permiso.}
{229}{}{El robot ha sido destruido.}
{230}{}{Bueno, puedes pasar. Te voy a dar un consejo: antes que nada, ve directo a hablar con el Alcalde Gustavo, está en un edificio grande cerca de la estación de monorriel. Y, te doy la bienvenida a Dayglow.}
{231}{}{Gracias por recibirme.}
{232}{}{Deberías haberme dejado pasar desde el principio. Que pérdida de tiempo...}
{233}{}{Bienvenido, hermano. ¿Primera vez en Dayglow?}
{1233}{}{Bienvenida, hermana. ¿Primera vez en Dayglow?}
{234}{}{Sí. ¿Me dejarás pasar?}
{235}{}{¡Por supuesto! Pero tendrás que pasar por una inspección. Reglas son reglas, lo siento.}
{236}{}{Entendido.}
{237}{}{¿Sabes qué? Ya no quiero pasar. ¡Nos vemos!}
{1237}{}{¿Sabes qué? Ya no quiero pasar. ¡Nos vemos!}
{238}{}{Bien. ¿Cómo te llamas, y de dónde vienes?}
{239}{}{Soy }
{240}{}{ de Arizona.}
{241}{}{Déjame ver lo que llevas encima. ¿No tienes nada ilegal, cierto?}
{242}{}{Depende de qué sea ilegal por aquí...}
{243}{}{¡Bromeo! Puedes pasar.}
{244}{}{¿En serio?}
{245}{}{¡Bienvenido a Dayglow!}
{246}{}{Gracias.}
{247}{}{En el pasado, se castigaban a los que pasaban la frontera ilegalmente. Pero ya que estás aquí, lo dejaré pasar. Sólo no irrumpas en la paz de los necrófagos.}
{248}{}{Por supuesto.}
{249}{}{No esperaba eso. Gracias. Y, bienvenido a Dayglow.}
{250}{}{Puedes pasar.}
{251}{}{Adiós.}
{252}{}{Puedes entrar. Yo no lo permitiría, pero alguien allá en el campamento de allá atrás hizo un escándalo cuando supo que venías. Te voy a dar un consejo: antes que nada, ve directo a hablar con el Alcalde Gustavo, está en un edificio grande cerca de la estación de monorriel.}
{253}{}{Estaré aquí por un rato. ¿Necesitas ayuda en algo?}

