{100}{}{Ves a Ralph.}
{101}{}{Ves a un necrófago con ropa de trabajo de la preguerra. Te resulta familiar.}
{102}{}{Me pregunto como estará yendo todo en la planta eléctrica.}

{200}{}{¡Vaya, vaya! ¡Parece que el Ángel del Pulso Electromagnético nos ha reunido una vez más!}
{201}{}{¿Ralph? ¿Qué haces aquí? ¿No pensabas irte a Texas?}
{202}{}{Por un tiempo, no quería irme de Fénix. Varios coleccionistas del área son unos ricachones. Pero luego un necrófago deprimido llegó a la ciudad y me habló de Dayglow. Pensé que sería mejor estar cerca de los míos que morir sólo en medio del yermo. ¿Qué hay de ti? ¿Qué haces TÚ aquí?}
{203}{}{Buscando nuevas aventuras... supongo.}
{204}{}{¿Eh? Ni siquiera sé que decir. Eres una persona rara. ¿Quizás sientes que no perteneces en tu casa? Pero será difícil que encajes aquí, hay radiación y restos del Viejo Mundo por todos lados. }
{205}{}{Lo sé.}
{206}{}{Agradezco tu ayuda en la central eléctrica, toma un Rad-Away. Quizás te sea útil.}
{207}{}{Gracias, Ralph. Nos vemos.}
{208}{}{¿No querrás decir, como perdón por lo que tú hiciste ahí? De todas formas, me lo llevo. Adiós, Ralph.}
{209}{}{Buena suerte. Le diré a los otros cómo me ayudaste a entrar en razón. Deben saberlo, porque no parece que tengas buena reputación por aquí.}
{210}{}{Gracias Ralph, lo agradezco mucho.}
{1210}{}{Gracias Ralph, lo agradezco mucho.}
{211}{}{No es nada. Mi reputación está bien como está. Adiós.}

{220}{}{Era divertido estar en la central eléctrica. Me pregunto como estará todo por allá.}
{221}{}{No lo sé. Adiós.}
