{100}{}{Ves a un necrófago, parece ser el mecánico de San Isidro.}
{101}{}{Ves a un necrófago con un uniforme de trabajo andrajoso. Uno de sus ojos fue sustituido por una especie de lente.}
{102}{}{Esto es una tienda y un taller. Pero, eh... Sólo atiendo necrófagos y a los amigos de los necrófagos. Primero, ve a hablar con GUstavo}
{103}{}{No voy a atender a un imbécil como tú. Piérdete.}
{104}{}{Eso no va a funcionar conmigo. Pero se ve genial.}

{200}{}{Hola, esto es un taller y una tienda general. El jefe dijo que podemos comerciar contigo, pero seguiré vigilándote.}
{201}{}{Te demostraré que es innecesario.}
{202}{}{No deberías hablarle así a tus clientes.}
{203}{}{Eso es todo lo que tengo. Si necesitas algo más, puedes ir al Pueblo Viejo.}
{204}{}{Adiós.}
{205}{}{Espera, tengo algo que hablar contigo.}
{206}{}{¡Hola! Es bueno verte. Esto es un taller y una tienda general. Ven, entra, elige lo que quieras. Tenemos un descuento para los necrófagos y los mutantes.}
{207}{}{Eso es genial.}
{208}{}{Muéstrame lo que vendes de nuevo.}
{209}{}{}

{210}{}{¿Cómo estás, querido mutante?}
{211}{}{Hola, verdecito. ¿Qué quieres?}
{212}{}{¿Cómo estás, huesudo? Lo siento, pero se nos acabaron las piernas y brazos de repuesto. Jeje, solo bromeo.}
{213}{}{¿Qué tal la vida, fenómeno? ¿Cómo estás hoy?}
{214}{}{¿Qué quieres? Compra lo que necesites y lárgate de aquí.}
{215}{}{¿Qué buscas?}
{216}{}{Dime, ¿qué necesitas? Sólo habla y te ayudaré con ello, es lo menos que puedo hacer por ti.}
{217}{}{Necesito comprar algunas cosas.}
{218}{}{Adiós.}

{220}{}{Un tipo con un pedazo de acero en el cráneo me pidió que arreglara esto.}
{221}{}{¿Nada más? Bueno, dámelo.}
{222}{}{Aquí tienes}
{223}{}{Ahora que lo pienso, intentaré arreglarlo yo en esa estación de ahí.}
{1223}{}{Ahora que lo pienso, intentaré arreglarlo yo en esa estación de ahí.}
{224}{}{No me agrada que esté tratando contigo. Pero ya que estás aquí, tengo que ayudar. Dame la pieza.}
{225}{}{Hecho. Ten cuidado de que no se te quiebre en el camino o algo así.}
{226}{}{Gracias.}
{227}{}{¡Ya lo sé, no tienes que decírmelo!}

{230}{}{Tengo un holodisco con una película vieja. ¿Podrías hacer una copia?}
{231}{}{Vaya, ¿te sientes culpable, no? Le robaste una posesión preciada a una persona autista y luego te andas por ahí como si no importase, para eso hace falta un imbécil de gran calibre. ¿Por qué debería hacerte caso, en vez de dárselo a su dueño?}
{232}{}{Necesito una copia para regresar el original. ¿Me entiendes?}
{233}{}{Ah, eso lo cambia todo. Bueno, te haré una copia por }
{234}{}{ chapas. No acepto cheques.}
{235}{}{Espérame, iré por las chapas.}
{236}{}{Entonces Hazlo, toma, las chapas y el disco.}
{237}{}{Has recibido una copia del holodisco.}

{250}{}{Necesito mejorar mi arma.}
{251}{}{Bueno, déjame verla.}
{252}{}{Ahora mismo, no tengo nada que mostrar.}
{253}{}{[}
{254}{}{ por }
{255}{}{]}
{256}{}{Hecho. ¿Quieres mejorar algo más?}
{257}{}{No, gracias.}
{258}{}{Creo que sí.}
{259}{}{Di la verdad: no tienes el dinero, ¿verdad?}
{260}{}{Ups.}

