{100}{}{Ves al Padre Talius.}
{101}{}{Ves a un mutante con una camiseta y sombrero desgastados. Una cruz cuelga de su cuello.}
{102}{}{Ves a Talius, un miembro de la secta de los Seguidores.}
{103}{}{Deberías darle esto a alguien que realmente merezca portarlo.}
{104}{}{Fernando se quedó en el pueblo.}
{105}{}{Beatrice se quedó en el pueblo.}

#First Meeting
{200}{}{Bienvenido, hermano. Mi nombre es Talius, me alegra verte en Dayglow. ¿Necesitas ayuda en algo?}
{1200}{}{Bienvenida, hermana. Mi nombre es Talius, me alegra verte en Dayglow. ¿Necesitas ayuda en algo?}
{201}{}{No eres mi hermano. ¿Te has visto en el espejo?}
{202}{}{Ya veo, tú tampoco tienes mucho cerebro. Solía ser igual, pero estudiar con los Seguidores me hizo más inteligente.}
{203}{}{¿Sientes apretado el cráneo entonces?}
{204}{}{La verdad sí. Debo recortar un poco de materia gris en el agujero que tengo en... Ah, debes referirte a otra cosa. Lo siento, a veces me distraigo. Bueno, ¿Necesitas ayuda?}
{205}{}{Lo siento, solo quería decir que somos muy distintos.}
{206}{}{Sí, quizás. Entonces, ¿Necesitas de mi ayuda?}
{207}{}{Sólo estoy aquí para ver el sitio.}
{1207}{}{Sólo estoy aquí para ver el sitio.}
{208}{}{Gracias por la bienvenida. Es sorprendente escuchar tales palabras en un lugar como este.}
{209}{}{Se entiende. Los necrófagos sospechan de los normaluchos, han tenido muchos malos ratos. Demuéstrales que vales la pena, y te recibirán con los brazos abiertos.}
{210}{}{Espero que sí. Pero, ¿Por qué eres tan amable?}
{211}{}{¡Era sarcasmo, idiota! Nunca sería amigos con fenómenos como tú.}
{212}{}{Lamento oír eso. Espero que cambies de parecer en el futuro. ¿Necesitas ayuda en algo?}

{220}{}{Saludos, hermano. ¿Puedo ayudarte con algo?}
{1220}{}{Saludos, hermana. ¿Puedo ayudarte con algo?}
{221}{}{No, gracias. Lamento molestarte.}
{222}{}{¿Qué quieres saber?}
{223}{}{Nada más. Gracias por tu tiempo.}
{224}{}{Mucho, pero no creo que sepas algo. Adiós.}
{225}{}{Pronto, Dayglow tendrá grandes cambios. Y luego, vendrán cambios al resto del mundo. Es tan terrorífico como emocionante... ¿Necesitas ayuda en algo?}

#About the Followers
{230}{}{Estás en la capilla de los Seguidores de los Apocalipsis. Aquí ayudo a los necrófagos a entender nuestras enseñanzas.}
{231}{}{Lamento interrumpirte. Pero quiero hablar de algo más.}
{232}{}{Conozco a algunos de los Seguidores. Tienen un puesto en Casa Nueva.}
{233}{}{Entonces sabes lo suficiente. Los Seguidores son buenas personas. Quieren traer la paz al yermo.}
{234}{}{¿Dónde están los demás Seguidores?}
{235}{}{Soy el único aquí. Solo los necrófagos y los mutantes pueden sobrevivir en estas ruinas. Pero gran parte de los Seguidores son gente normal. Su base principal está en otra ciudad.}
{236}{}{¿Cómo te convertiste en Seguidor si eres... ya sabes... un necrófago?}
{237}{}{¿Me creerías si te dijera que tú y yo tenemos una naturaleza distinta? Los Seguidores me salvaron de convertirme en una horrible bestia mientras estaba inconsciente bajo el efecto de un mutágeno. Luego de eso, me compartieron su conocimiento. Son gente amable.}
{238}{}{Ya veo.}
{239}{}{¿De qué se tratan éstas enseñanzas?}
{240}{}{Los Seguidores del Apocalipsis buscan traer paz al yermo. Predican el altruismo y están en contra de la violencia. Utilizan el conocimiento de la preguerra para mejorar la vida de las personas, pero lo más importante es que no permitirán a la humanidad repetir el error del 2077.}
{241}{}{Háblame sobre tu fe.}
{242}{}{Tus palabras acerca de los Seguidores me han conmovido profundamente. Me gustaría hacer una donación.}
{243}{}{Eso es muy noble de tu parte. ¿Cuántos chapas puedes permitirte para ayudar a nuestra causa?}
{244}{}{Ahora mismo, ninguno. Pero lo haré en el futuro.}
{245}{}{100 chapas.}
{246}{}{200 chapas.}
{247}{}{300 chapas.}
{248}{}{400 chapas.}
{249}{}{500 chapas.}
{250}{}{Gracias. ¡Ten un buen día!}
{251}{}{De nada.}
{252}{}{Me siento mejor. Pero me gustaría seguir hablándote, Padre Talius.}

#About Himself
{260}{}{Recuérdame, ¿Cómo te llamas?}
{261}{}{Soy Talius.}
{262}{}{Vale, Talius.}
{263}{}{¿De dónde eres, Talius?}
{264}{}{Mi hogar natal está lejos de aquí, era un viejo refugio, el número 13.}
{265}{}{Conozco varios refugios, pero es la primera vez que escucho del 13.}
{266}{}{Nunca he escuchado de un lugar así.}
{1266}{}{Nunca he escuchado de un lugar así.}
{267}{}{Por supuesto. Habían muchos refugios, y muchos de ellos ya no funcionan hoy en día.}
{268}{}{¿Los demás necrófagos también vinieron del Refugio 13?}
{269}{}{Cambiemos de tema.}
{270}{}{La mayoría de ellos vienen del Refugio 12, que está bajo Necrópolis. Solía visitarlo buscando partes para mi refugio. En ese entonces empezó la mutación.}
{271}{}{Entonces, ¿No eres un necrófago?}
{272}{}{Lamento oír eso. Cambiemos de tema.}
{273}{}{Soy un mutante. Los científicos del Maestro me hicieron así. Intentaron hacerme un supermutante, pero algo salió mal.}
{274}{}{Soy un mutante. Los científicos del Maestro me hicieron así. Intentaron hacerme un supermutante, pero algo salió mal. Y parece que algo similar ocurrió contigo.}
{275}{}{Eso es terrible. Ojalá pudiera ayudarte.}
{1275}{}{Eso es terrible. Ojalá pudiera ayudarte.}
{276}{}{Gracias por tus palabras. Sabes, solía ser ateo. Pero el destino me hizo inmortal, y con ésto empiezas a creer en el plan de Dios. ¿Quizás haya sido una prueba?}
{277}{}{Supongo que es difícil ser así. Pero ya nada puede hacerse.}
{278}{}{Sabes, solía ser ateo. Pero el destino me hizo inmortal, y con ésto empiezas a creer en el plan de Dios. ¿Quizás haya sido una prueba?}
{279}{}{¿Podemos hablar de algo más?}
{280}{}{Buena suerte, Padre Talius.}

{290}{}{Recordé que hablamos de los refugios. ¿Hay alguno en Dayglow?}
{291}{}{Quizás. ¿Por qué lo preguntas?}
{292}{}{Razonamiento lógico. No importa..}
{293}{}{Bueno, encontré esta cosa. Creo que podría estar relacionada a los refugios.}
{294}{}{Una cantimplora del Refugio 24... Es una reliquia del Viejo Mundo. ¿En dónde la encontraste?}
{295}{}{Lo encontré en un esqueleto con un mono del refugio. Fue en las ruinas, parece que ha estado ahí desde hace muchas décadas.}
{296}{}{Puede que haya sido uno de los exploradores que los Seguidores enviaron a explorar. Muchas buenas personas murieron en esos días tan difíciles.}
{297}{}{¿Los Seguidores también vinieron de un refugio?}
{298}{}{Aquellos que fueron los ancestros de los Seguidores sí. Los demás nacieron luego de abandonar el refugio o se unieron después.}
{299}{}{¿Qué ocurrió con su refugio?}
{300}{}{No me conozco toda la historia. El refugio es inútil ahora, los Seguidores se llevaron todo lo valioso. Además, hay unas criaturas terribles merodeando por ahí. No te recomiendo que vayas.}
{301}{}{Me arriesgaré de todas formas. Al menos por la historia. Enséñame el camino.}
{302}{}{El refugio puede esperar. No tengo ganas de aventuras peligrosas ahora mismo.}
{303}{}{Está en el centro de Otay Park. Es difícil de encontrar, así que marcaré el camino en tu Pip-Boy.}
{304}{}{[Dirígete al refugio ahora mismo.]}
{305}{}{Ahora no. Necesito prepararme.}
{306}{}{Me arriesgaré de todas formas. Quizás no se llevaron todo lo valioso. Enséñame el camino.}
{307}{}{¿No es un poco descarado de tu parte meterte ahí sin más? Todo aquí le pertenece a los necrófagos, a muchos ni les gusta que estés aquí. Te puedo mostrar donde está, pero a cambio quiero una generosa donación. Dígamos unas 1.000 chapas.}
{308}{}{No puedo gastar tanto. Hablemos de esto en otra ocasión.}
{309}{}{Vale, aquí tienes las chapas. Enséñame donde está.}
{310}{}{A cambio, te dejaré vivir, imbécil. Eso es lo mejor que te puedo dar.}
{311}{}{Necesito regresar al Refugio 24. Inmediatamente.}
{312}{}{Ayúdame a llegar al Refugio 24.}

{320}{}{¿Hay algo que pueda hacer por ustedes?}
{321}{}{Todavía necesitamos salvar nuestras almas, pero eso lo haremos nosotros. Hace poco, me contaron de otra víctima de la locura: nuestro amigo Gonzo enloqueció y escapó a las ruinas de Chula Vista. En ese estado, es peligroso. Debe ser detenido.}
{322}{}{¿Es posible hacerlo sin matarlo?}
{323}{}{¿Acaso quieres que lo MATE?}
{324}{}{(suspiro) ¿Hay algún necrófago que busque hacerle mal a otro necrófago? No lo creo, no lo creo. Muchos necrófagos condenarían tal acto, pero la locura no tiene solución. Lo único que podemos hacer es evitar matarlo.}
{325}{}{Le cortaré la cabeza y ya, así de simple.}
{326}{}{He visto éste tipo de locura en el Infierno. La única cura es matarlos.}
{327}{}{¡No puedes tomar una vida así sin más! Si realmente no hay otra manera, envía a Gonzo con sus ancestros. Pero recuerda, Gonzo es nuestro hermano, los demás necrófagos vivieron con él por muchos años en Necrópolis. Muéstrale algo de compasión.}
{328}{}{¿Es posible restaurar su sanidad, aunque sea temporalmente?}
{329}{}{En ciertos casos, ayudan las medicinas, en otros - ayudan las memorias pasadas. O quizás nada ayude. Pero cualquier solución es temporal.}
{330}{}{Ya pensaré en algo.}
{331}{}{Dios te acompañe.}
{332}{}{Ya vuelvo.}
{333}{}{Tengo otras preguntas que hacerte.}
{334}{}{Si hasta incluso tú no puedes lidiar con un necrófago, yo tampoco voy a poder. Lo siento.}
{335}{}{Lo entiendo. Entonces, intenta evadir a Gonzo si lo encuentras en las ruinas.}
{336}{}{Recuérdame en donde está Gonzo.}
{337}{}{Fue visto por última vez en el distrito comercial de Chula Vista. Eso está hacia el norte.}
{338}{}{Entendido.}
{339}{}{}
{340}{}{Gonzo está muerto. ¡No tenía otra opción!}
{341}{}{Entonces, su alma puede descansar. (suspiro) Está bien, no te guardo ningún rencor. Sólo estoy enojado conmigo mismo por no saber ayudar a los enloquecidos. Parece ser que todos los necrófagos terminarán así, tarde o temprano. No tiene cura.}
{342}{}{No debes culparte. La vida sigue.}
{343}{}{Era un peligro para la sociedad. Sabías eso.}
{344}{}{Gracias por tus palabras.}
{345}{}{Cambiemos de tema.}
{346}{}{Ahora Gonzo no será un problema, ¿Cierto?}
{347}{}{Gracias. Gonzo está detrás de rejas y no causará problemas. Parece ser que todos los necrófagos terminarán así tarde o temprano, no tiene cura. Solo podemos encerrarlo para que no cause problemas. Si necesitas ayuda con tu cuerpo o alma, te ayudaré.}
{348}{}{Claro, ¡Sólo no me pongas detrás de la reja!}
{349}{}{Gracias, lo tendré en cuenta.}

#Healing
{350}{}{¿Puedes tratar enfermedades?}
{351}{}{Los Seguidores me enseñaron los tratamientos médicos básicos. Pero en nuestra ciudad las medicinas son caras. ¿Qué te aflige?}
{352}{}{Necesito tratamiento.}
{353}{}{No es nada. Solo preguntaba.}
{354}{}{ chapas]}
{355}{}{[Cura tus heridas por }
{356}{}{[Cura tus heridas graves por }
{357}{}{[Cura la radiación por }
{358}{}{[Cura envenenamiento por }
{359}{}{Estás bien.}
{360}{}{Gracias.}
{361}{}{[Cura a Gomer por }
{362}{}{Él se encuentra bien.}


{380}{}{Tengo una situación rara en mis manos, Doc. Es sobre Donovan. Está muerto.}
{381}{}{¿En serio?}
{382}{}{Pero sus amigos no pueden creerlo. ¿Qué debería hacer?}
{383}{}{¿Donovan? ¿Muerto? Vamos, ¡es obvio que está vivo!}
{384}{}{¿Estás chiflado? ¿Acaso todos los necrófagos lo están?}
{385}{}{Mira, no respira. Y le falta la mitad del cuerpo. Está muerto.}
{386}{}{Ven, tráemelo. Me ocuparé de él. Pero...}
{387}{}{¿Pero qué?}
{388}{}{Me temo que no puedo ayudarlo, pues me faltan unas cosas. ¿Sabes dónde está el hospital? Necesito que me traigas tres frascos de biogel de allá.}
{389}{}{De verdad que estás loco. Me largo.}
{390}{}{Bueno, tú debes de saber más que yo. Intentaré traerte el biogel.}
{391}{}{Ya tengo lo que me pediste.}
{392}{}{¡Excelente! No perdamos tiempo, es hora de empezar con la operación.}
{393}{}{Eh, está bien...}
{394}{}{(La operación dura varias horas a puerta cerrada. Tú esperas fuera. Finalmente, Talius sale y declara en voz alta: "¡Donovan vivirá!")}
{395}{}{Vaya, Talius, ¡Sí que haces milagros!}
{396}{}{Sí, claro. No te creo. Adiós, 'doctor'.}
{1396}{}{Sí, claro. No te creo. Adiós, 'doctor'.}
{397}{}{Oye, acerca de Donovan...}

