{100}{}{Este es el punto designado para volver a Sonora.}
{101}{}{Desde aquí, puedes regresar al desierto de Sonora.}
{102}{}{Antes de marcharte, descartaste algunos objetos que ahora resultarían inútiles. (}
{103}{}{).}

{110}{}{Este es el punto de encuentro.}
{111}{}{[Espera al guía y regresa a los yermos de Sonora]}
{112}{}{[Regresa al desierto de Sonora por ti mismo.]}
{113}{}{[Quédate en Dayglow, Sonora puede esperar.]}
{114}{}{¿Realmente quieres hacer esto? No es posible regresar a Dayglow.}
{115}{}{Sí, quiero volver.}
{116}{}{No, me quedaré en Dayglow.}
{117}{}{No puedes llevar más de 100 libras de peso.}
{118}{}{[Ve a Dayglow, por ti mismo]}
{119}{}{[Quédate en Sonora]}
