{110}{}{Este howitzer se encuentra estropeado. Sin embargo, podría ser reparado al reemplazar algunas partes.}
{111}{}{Según tu hipótesis, el cañón podría disparar, al menos una vez.}
{112}{}{El howitzer dispara, pero después de esto se descompone.}
{113}{}{El howitzer está fuera de servicio, permanentemente. Encuentra otro.}
{114}{}{El howitzer está cargado.}
{115}{}{El howitzer ha sido reparado.}
{116}{}{Has removido algunas partes de este howitzer.}