{100}{}{Hay una subestación en frente tuyo.}
{101}{}{Esto es una subestación eléctrica. Los cables se extienden desde ella hasta la línea del monorriel.}
{102}{}{Esto es una subestación eléctrica. No se te ocurre por qué podría ser importante.}
{103}{}{Parece que está subestación que debería dirigir la corriente al monorriel.}
{104}{}{La subestación ya dirige electricidad a la línea del monorriel.}
{105}{}{La corriente de la línea del monorriel ha sido restaurada.}
{106}{}{La subestación está muerta. No le llega la electricidad desde la planta eléctrica.}
