{100}{}{(}
{101}{}{/}
{102}{}{) de los pósteres de propaganda del Viejo Mundo han sido encontrados.}
{103}{}{) de los pósteres de propaganda del Viejo Mundo. Ya has examinado éste.}
{104}{}{Gracias a tu atención al detalle, recibes }
{105}{}{ puntos de experiencia.}
{106}{}{Esto es propaganda. Luego de anexar México, buscaban reconciliar a los Americanos y a los Mexicanos. No fue nada fácil.}
{107}{}{Tú ser inteligente. Gomer no poder leer.}
{1107}{}{Tú ser inteligente. Gomer no poder leer.}
