{100}{}{Ves a un guardia.}
{101}{}{Ves a un guardia de caravana.}

{110}{}{Ojalá que no nos encontremos sorpresas en el camino.}
{111}{}{No puedo esperar a que nos paguen al acabar.}
{112}{}{Ojalá que el bar siga abierto cuando lleguemos.}
{113}{}{Sería genial tener un almuerzo de verdad.}
{114}{}{El viaje ha sido brutal.}
{115}{}{Los brahmanes son muy lentos cuando cargan algo.}

{120}{}{Mierda, ¡mataron al jefe!}
{121}{}{Ya no hay nadie que pague, así que cada uno por su camino...}
{122}{}{Vamos a repartirnos las cosas y nos iremos por distintos caminos.}
