{100}{}{Ves a un inmigrante.}
{101}{}{Ves a una persona sucia y escuálida.}

{110}{}{¡Por favor, no nos ataques!}
{111}{}{¡No queremos problemas!}
{112}{}{Estamos buscando un nuevo hogar.}
{113}{}{¿Ya llegamos?}
{114}{}{Quiero dormir.}
{115}{}{Eres un aventurero, ¿no?}
{116}{}{Ya tuvimos suficiente de tiranos y de guerrilleros.}
{117}{}{Hay bandidos por todas partes.}
{118}{}{¡Déjanos en paz!}
{119}{}{No tenemos nada de valor.}

{210}{}{«¡Por favor, no nos ataques!»}
{211}{}{«¡No queremos problemas!»}
{212}{}{«Estamos buscando un nuevo hogar.»}
{213}{}{«¿Ya llegamos?»}
{214}{}{«Quiero dormir.»}
{215}{}{«Eres un aventurero, ¿no?»}
{216}{}{«Ya tuvimos suficiente de tiranos y de guerrilleros.»}
{217}{}{«Hay bandidos por todas partes.»}
{218}{}{«¡Déjanos en paz!»}
{219}{}{«No tenemos nada de valor.»}

{310}{}{¡Por favor, no nos ataques!}
{311}{}{¡No queremos problemas!}
{312}{}{Estamos buscando un nuevo hogar.}
{313}{}{¿Ya llegamos?}
{314}{}{Quiero dormir.}
{315}{}{Eres un aventurero, ¿no?}
{316}{}{Ya tuvimos suficiente de tiranos y de guerrilleros.}
{317}{}{Hay bandidos por todas partes.}
{318}{}{¡Déjanos en paz!}
{319}{}{No tenemos nada de valor.}
