{110}{}{Esa habilidad no te ayudará aquí.}
{111}{}{¿Quieres ponerte a cavar en medio de una pelea? Claro que no.}
{112}{}{Con músculos como los tuyos, ni puedes levantar la pala.}
{114}{}{Necesitas una herramienta para cavar esto.}
{115}{}{Alguien enterró a un perro aquí. Es evidente que tenían prisa.}
{116}{}{No es tan fácil rellenar un agujero como este.}
{117}{}{Mientras cavas, la tumba colapsa de repente y te arrastra hacia las profundidades.}
{118}{}{Chingada madre...}
{119}{}{Ay...}
{120}{}{El agujero es muy, muy profundo.}

#Companion lines
{130}{}{¿De verdad tenemos que hacer esto?}
{131}{}{Yo... También he robado tumbas, por así decirlo. Ya sabes cómo es.}
{132}{}{Dudo que haya algo de valor ahí abajo.}

{140}{}{¿Por qué haces esto?}
{141}{}{¿En serio crees que esto está bien?}
{142}{}{No creo que los Rangers aprueben algo así.}

{150}{}{¿En serio crees que hay algo de valor ahí adentro?}
{151}{}{A mí me da igual, solo espero que nadie nos vea.}
{152}{}{Los Mexicanos no nos perdonarían por esto.}

{160}{}{¡Dios mío! ¿Es que no te da vergüenza?}
{161}{}{No pongas excusas, no haces esto por 'la ciencia'.}
{162}{}{Eso es asqueroso.}

{170}{}{¡La virgen! ¿En qué momento pensé que acompañarte era una buena idea?}
{171}{}{¿Estás robando una tumba? A la Orden no le gusta eso.}

{180}{}{Voy a fingir que no vi eso.}

{190}{}{Cierto. Ya no lo necesitan, pero puede que nosotros sí.}
{191}{}{¿Y bien? ¿Qué hay ahí?}
{192}{}{No te preocupes, no te voy a juzgar. Yo solía hacer lo mismo.}
