{102}{}{Eso no tiene sentido.}
{103}{}{Podrías encenderle fuego a esto para iluminar el área.}

{110}{}{Encendiste la lámpara. Su tenue luz apenas consigue penetrar la oscuridad del sótano.}
{111}{}{Todavía le queda algo de aceite a la lámpara. Sólo falta encenderla para iluminar el sótano.}
{112}{}{La lámpara ilumina un poco del sótano.}
{113}{}{La lámpara ya no tiene aceite.}
{114}{}{Los coyotes se asustan por el fuego y el humo.}
{115}{}{El fuego mantendrá alejados a los monstruos flotadores.}
