{100}{}{You see Chatto.}
{101}{}{You see a young man with a worried look.}
{102}{}{Wow, is this one of those things they make in City? By the Brahmin!}
{103}{}{The old man is sick in his mind!}
{104}{}{I will change. I promise that I will protect my tribe from strangers of Phoenix until the end.}

{200}{}{Ugh, Mangas has finally left me behind. This must look crazy to you. Do not think that we are all like this. This old man is just sick in his mind.}
{201}{}{Who are you?}
{202}{}{I am Chatto. I am a warrior of tribe.}
{203}{}{Hey Chatto. Why is that old man so mad at you?}
{204}{}{Mangas decides that he, as elder, can tell everyone what is right and what is wrong. Why can I not decide for me? I am also a future leader!}
{205}{}{Future? Who's the real one?}
{206}{}{My father, High Chief Geronimo. You have probably heard of him. He is a legend. It was he who rallied the tribe and founded San Brahmin. But other leaders are sometimes jealous that they did not take his path first.}
{1206}{}{My father, High Chief Geronimo. You have probably heard of him. He is a legend. It was he who rallied the tribe and founded San Brahmin. But other leaders are sometimes jealous that they did not take his path first.}
{207}{}{So what will you do when you become the head of the tribe?}
{208}{}{To Dark Brahmin with old ways and endless war! We must make peace with Phoenix - for our safety and for sake of our future. Such would give us many opportunities. Look at the weapons of strangers, at the new tools of labor, radio communication alone is worth something...}
{209}{}{Keep going...}
{210}{}{What do Rangers give us? They only protect from raiders and dangerous animals. Many young people support me. We are tired of old people and their old words. They lead us to war. Now is time for tribe to change.}
{211}{}{Big ambitions, boy. I hope you understand what you're doing. See you.}

{220}{}{Hello, wanderer. Do my tribesmen treat you well? Tell me if anyone give you hard time.}
{1220}{}{Hello, wanderer. Do my tribesmen treat you well? Tell me if anyone give you hard time.}
{221}{}{Hello, wanderer.}
{1221}{}{Hello, wanderer.}
{222}{}{It's okay. I just want to say hello. See you.}
{223}{}{You're doing the right thing. Bye.}
{224}{}{Too soft in my opinion, but it's your call.}
{225}{}{Rebels have captured the Phoenix Cathedral. Aaron is dead. Now nothing opposes the Rangers.}

{230}{}{Chatto, don't you think it's time to take over the tribe?}
{231}{}{I think about this for long time. Old people do not give me voice in councils. They believe that young people should fight and blindly follow words of their elders.}
{232}{}{But you don't agree with them, do you?}
{233}{}{They do not understand! Life in Phoenix is no longer sick and frail as it used to be. We have lost greatness, while they gain theirs. Now the townspeople have powerful weapons and technology.}
{234}{}{At this rate, Phoenix will wipe out the tribe.}
{235}{}{You speak true! The only way we can survive is to make contact with Phoenix so that we might outwit its people. We too could get weapons and these technologies.}
{236}{}{Exactly. So what are you waiting for?}
{237}{}{Old people do not want to change their ways. They only know idea that technology is evil, and they only know to live by whims of nature.}
{238}{}{Oh, I see. Well then I have nothing to say. Bye.}
{239}{}{You need to talk some sense into them, Chatto.}
{240}{}{What can I do? The old people do not give me my voice in council while my father is alive.}
{241}{}{Well, that leaves you with few options. Good luck.}
{242}{}{When you gain power, it'll be too late. Eliminate your father, Chatto.}
{243}{}{What? Kill my father? Dark Brahmin! I won't do that.}
{244}{}{Sorry. Forget I said that.}
{245}{}{Okay. I'll do it. Someone needs to show you some fortitude.}
{246}{}{Wait... Do you plan to take violence to his rooms in the Sanctuary? No, after such an act I would never be able to stand in his place.}
{247}{}{Any better suggestions? How about poison?}
{248}{}{Scorpion poison will not work... All tribe accustoms itself to this poison from youth. But pre-war drugs often lead to sad fate when someone is treated with them. Therefore, we are weak to the old medicines.}
{249}{}{I think I can find old pre-war drugs in Phoenix. Bye, Chatto.}
{250}{}{You risk missing your chance. You must take your father's place in council. You know what you must do, Chatto.}
{251}{}{What... Kill my father? You speak the unthinkable...}
{252}{}{Sorry. Forget what I said.}
{253}{}{Do it for the future of your tribe. Your father and the rest of the elders are leading the tribe into an abyss.}
{254}{}{(He looks at his hands, nodding for a long time at your words, then silently raises his gaze and leaves towards the sanctuary.)}
{255}{}{Don't worry, Chatto. This conversation never happened.}
{256}{}{Phoenix is spreading slavery throughout Southern Arizona. Villa has already become a victim.}
{257}{}{Phoenix works with the Tinsmiths who use slaves from various tribes. None of them can be trusted.}
{258}{}{There is one more person who is interfering with you and your tribe. What will you do with the ranger?}
{259}{}{I must send him out of the pueblo. But he may leave here in peace.}

{260}{}{What is happening? I saw the shamans run into the sanctuary...}
{261}{}{Your father has... passed away. Now you must lead the tribe. And you know what to do.}
{262}{}{He... is dead? But... wait, I must wrap my thoughts around this.}
{263}{}{Of course. Think carefully about what to do next.}
{264}{}{If you hurry, you will have time to take power into your own hands. Now's your chance to make an alliance with Phoenix just like you wanted.}
{265}{}{You speak truth! This is my chance. And I will never let these foolish old men ruin everything again. (runs off toward to the sanctuary)}
{266}{}{Go, Chatto!}
{267}{}{You may have heard about the explosion in Phoenix. Are these the kind of allies you want?}
{268}{}{Then you'll be interested in what happened in Quartz. Listen to this carefully...}
{269}{}{The Flagstaff colony uses slave labor. Everything it does is directed by Phoenix.}

{270}{}{Now I will lead the tribe in different direction. The old people will not have strength to stop me.}
{271}{}{I think you know what to do. Bye.}
{272}{}{So, are you ready to form an alliance with the Phoenix missionaries?}
{273}{}{That is what I will do. Tell Commander Crook that I am ready to smoke the peace pipe with him... Or sit down at negotiating table. I think that's how it's said in the city?}
{274}{}{Good luck to you and your people, Chief.}
{275}{}{Okay. Bye.}
{276}{}{By the way, it would be good to reopen the caravan route to Garage City. What do you think?}
{277}{}{That is the Phoenix colony to north that sells old items from ruins? Yes, I think it will be useful for tribe to get new things. Tell Ronnie to look into this matter.}

{278}{}{You can read, right? Then read the missionary commander's diaries. I managed to steal them from the camp.}
{279}{}{...What? What does he write? What does it mean? "filthy savages"... "drive into a reserve"... "disarm these savages"... This is the plan he proposes to his leader? Damn it, the Dark Brahmin himself must have clouded my mind.}
{280}{}{Chatto, the chiefs and rangers are not happy with you and your people.}
{281}{}{I know. If not, I would not have to fight this fight. The leaders are wrong, the tribe MUST change. The world has changed. The tribe will not survive unless we too change.}
{282}{}{Okay, I won't argue with you.}
{283}{}{Perhaps they're just not ready for change?}
{284}{}{When will that day come? When will the old people go to the Heavenly Pastures? Before this time, the Phoenix Empire will crush us with weapons and technology.}
{285}{}{What does it take for you to finally open your eyes?}
{286}{}{Prove to me that the Rangers are best choice. Maybe they have already proven themselves somewhere in the wasteland? Or tell us what bad things the alliance with Phoenix would bring us. Have you examples that will change my mind? There may be evil plans in the missionary camp to take over San Brahmin, but until I know the truth of this, I will not change my mind.}
{287}{}{Okay. I'll look into it.}
{288}{}{You're ahead of everyone, Chatto. Like a Brahmin who has strayed from the herd. You don't know where you're going.}
{289}{}{I do not think so...}
{290}{}{Brahmin are herd animals. This is the only way they can protect themselves from enemies. The single Brahmin is doomed.}
{291}{}{(sigh) So what should I do? Please give your wisdom, because you and I are alike, wanderer. Should I stay in the camp and protect its old way of life? Or continue to fight against foolish old men who live in the past?}
{1291}{}{(sigh) So what should I do? Please give your wisdom, because you and I are alike, wandering woman. Should I stay in the camp and protect its old way of life? Or continue to fight against foolish old men who live in the past?}
{292}{}{I don't know, Chatto. I also ask myself this question. Let's put this conversation aside for now, okay?}
{293}{}{Vote for an alliance with the Rangers. You and your companions must return to the tribe.}
{294}{}{Perhaps you are right. I do not know anymore... Okay, I will speak with others and try to calm them down.}
{1294}{}{Perhaps you are right. I do not know anymore... Okay, I will speak with others and try to calm them down.}
{295}{}{Go, Chatto.}
{296}{}{I had a chance to visit Flagstaff. Phoenix created this colony on the lands of a tribe, like your own, which they wiped out.}
{297}{}{Your words are truth? For sake of its colony, Phoenix destroys entire tribe? (shakes head) Hmm... I must have eyes for only what I wanted to see. In war, everyone seeks their own benefit.}
{298}{}{Not so keen for an alliance with Phoenix now, huh?}
{299}{}{To be honest, it's kind of a murky story. Never mind.}
{300}{}{If you're having doubts, let's flip a coin. Let the Spirit of the Wasteland decide.}
{301}{}{I am not leaving it up to chance.}
{302}{}{As you wish.}
{303}{}{Alright, let us flip... What is this? The coin sides with Rangers?}
{304}{}{Alright, let us flip... What is this? The coin sides with Phoenix?}
{305}{}{Honestly, I'm starting to think trusting chance isn't such a good idea. Forget it.}
{306}{}{Let's flip a coin. Let the Spirit of the Wasteland decide for you.}
