{100}{}{You see Geronimo.}
{101}{}{You see an old man in a tribal outfit made of Brahmin leather.}
{102}{}{Protect me, Brahmin of Salvation! Let the joints of this spirit fall apart!}
{103}{}{Oh, Dark Brahmin... Why are you looking at me so intently?}
{104}{}{Is... the time... come...}

#First meeting
{198}{}{I see the Great Spirit of the Wasteland has had its way with your body. Who would think the wasteland could change one so much?}
{199}{}{You know me?}
{200}{}{Peasant from Villa... I know who you are. If the road brought you to us, there are reasons, right?}
{1200}{}{Peasant girl from Villa... I know who you are. If the road brought you to us, there are reasons, right?}
{201}{}{My village has been enslaved. Do you know anything about this?}
{202}{}{Darkness covers Sonora from the eyes of the Divine Brahmin. Slavers are everywhere now. They use our brothers in mines, logging sites, and to build their camps. Where your fellow tribesmen are held, I do not know. But you can learn of it in Phoenix.}
{203}{}{Thanks. I'll look there then.}
{204}{}{We also suffer from slave traders and pale-skinned missionaries from Phoenix. They covet our herds and lands. Hard times come, peasant of Villa.}
{1204}{}{We also suffer from slave traders and pale-skinned missionaries from Phoenix. They covet our herds and lands. Hard times come, peasant of the Villa.}
{205}{}{Or maybe you grabbed them, how should I know?}
{206}{}{Do not speak nonsense! We ourselves suffer from slave traders and pale-skinned missionaries from Phoenix. They covet our herds and lands. Hard times come, peasant of Villa.}
{1206}{}{Do not speak nonsense! We ourselves suffer from slave traders and pale-skinned missionaries from Phoenix. They covet our herds and lands. Hard times come, peasant of the Villa.}
{207}{}{Well, I hope you can handle them.}
{208}{}{I hope Villa can avoid all this.}
{209}{}{Your Villa cannot avoid this fate. We are all cursed by the same Dark Brahmin. Do you think you can remain isolated like you once were?}
{210}{}{What are you going to do?}
{211}{}{I want to make alliance with the Rangers. My mind was not made lightly, but we need an ally to keep our freedom. Our enemies have guns and metal armor. We only have brahmin and spears.}
{212}{}{We should help each other against a common threat. What can I do?}
{213}{}{Villa should take our side and the side of the Rangers. This is common cause. Find Ranger Oscar, he is helping us in the fight against the missionaries. He might need your help.}
{214}{}{I'll talk to him.}
{215}{}{Me and the rest of the Villa, we have no intention of participating in this war.}
{216}{}{Then, you should remember that you are an uninvited guest in our lands. Stay out of our way if you are not going to help.}
{217}{}{Okay. I'll head out soon.}
{218}{}{You can stay at camp for now. Go.}
{219}{}{Goodbye, Chief.}
{220}{}{Bye.}
{221}{}{I'm here to help defeat the threat from Phoenix. The Rangers sent me.}
{222}{}{Rangers have long respected our freedom. I welcome your help.}
{223}{}{Where do I start?}
{224}{}{Speak to your brother ranger, Oscar. He stays in a hut near the sanctuary.}
{225}{}{I'll do that, Chief.}

#Re-dialogue
{230}{}{You test our patience in vain. Watch your tongue or you will become enemy of our tribe.}
{231}{}{What do you want from us?}
{232}{}{You have come back at the right moment.}
{233}{}{Are you going to help us or hinder us this time?}
{234}{}{What else do you need?}
{1234}{}{What else do you need?}
{235}{}{I'll be leaving soon, Chief.}
{236}{}{Don't think I have forgotten your good deeds. How can I help?}
{237}{}{It is a great joy to see you in our camp.}
{238}{}{You should not have returned to our camp. But since you are here, we must bear you.}
#Main quest
{240}{}{I think you should break your alliance with the Rangers and join forces with the Phoenix Missionaries.}
{241}{}{Hmm. You are too bold for a peasant, this is truth. But why should I do this?}
{1241}{}{Hmm. You are too bold for a peasant, this is truth. But why should I do this?}
{242}{}{Hmm. Judging by the rumors coming from the west, I doubt this alliance was a good idea. But will the new union be better?}
{243}{}{The Rangers are just using you in the fight against the Phoenix Empire. They don't care about your tribe.}
{244}{}{You speak of serious things. But these are just the words of a peasant against the words of an entire army of rangers.}
{1244}{}{You speak of serious things. But these are just the words of a peasant woman against the words of an entire army of rangers.}
{245}{}{When the hour is late, you'll remember my words.}
{246}{}{Even if the truth is behind you, I cannot make such a decision alone. Other leaders still share my mind. I will not change it unless they change theirs too.}
{247}{}{Then I should talk to the other leaders. See you later, Geronimo.}
{248}{}{The Phoenix Empire will wipe you off the face of the earth if it doesn't subdue you. Do you want such an inglorious end for your people?}
{249}{}{Finding peace in the battle for your freedom is a glorious end. I would rather die than join the empire.}
{250}{}{So you're a fool. And someday you'll regret your decision.}
{251}{}{I understand. Sorry if my words offended, chief.}
{252}{}{You have united the tribe, high chief. It's up to you to decide what to do next. But by making an alliance with the Rangers, you doom the tribe to endless war.}
{253}{}{Perhaps the truth is behind you. The Phoenix Empire is strong and great. We will not be able to resist and someday we will fail. If we join them now, we might keep some of our independence.}
{254}{}{So you agree?}
{255}{}{Perhaps I should heed your words. The Rangers will not like it though. I hope I will not regret this decision.}
{256}{}{You won't. I'll pass on your words to the missionary commander.}
{257}{}{All my advisors give the same wisdom. An alliance with the Rangers promises only a bloody war. And an alliance with Phoenix gives peace, but takes away freedom.}
{258}{}{You know the importance of the lives of your fellow tribesmen.}
{259}{}{Some of my advisors left this world, and others turned against me. An alliance with the Rangers promises only a bloody war. And an alliance with Phoenix gives peace, but takes away freedom. In the fight between the eagle and the snake, all that remains is to bury your head in the sand.}

{260}{}{The missionaries have left your lands. Ranger Oscar and I made them leave.}
{261}{}{The missionaries have left your lands. I managed to get them to leave.}
{262}{}{Glorious news for the whole tribe! We have kept our independence and maintained our freedom. But, the fight will not end. I am sure, for some time we will be bothered by pale-faced strangers. But we will survive them too.}
{263}{}{[Listen]}
{264}{}{It's as if the Divine Brahmin himself sent you to us in our time of need! Thank you. You may stay in the San Brahmin as long as you want. I will give word of your deeds so that all will share shelter and food with you.}
{265}{}{Thanks.}
{266}{}{I hope your search for your missing kin will meet great success. To this I tell you, our scouts report that a group of slaves were seen being herded toward Flagstaff. Look there.}
{267}{}{Thanks, Chief.}

{270}{}{I think you should reopen the caravan route to Garage City.}
{271}{}{All roads and trade routes with the Phoenix colonies are closed. This is the Council of Elders' decision.}
{272}{}{It seems you won't change your mind until your relationship with Phoenix improves.}
{273}{}{We have already reopened caravan routes with Phoenix. Let all its colonies return to peaceful trade.}
{274}{}{Great. }
{275}{}{Garage City also suffered from Aaron's ambitions. But now the Cathedral of Fire is destroyed, Aaron is dead. Phoenix is no longer a threat to you.}
{276}{}{So be it. Pass my consent to Ronnie, he is in charge of the caravans in this pueblo.}
{277}{}{Thanks.}
{278}{}{I am ready to open the caravan routes for Phoenix. But right in the middle of this path, a snake and an eagle start fight. Until they make peace or devour each other, it will be difficult to negotiate with traders.}
{279}{}{Garage City also suffered from Aaron's ambitions. But the Cathedral of Fire was captured by the rebels, Aaron died. Phoenix is no longer a threat to you.}

#Minor speeches
{300}{}{Who are you?}
{301}{}{You cross a valley, pass an entire pueblo, and do not know who stands in front of you? Then let us correct your lack of wisdom - I am the one called Geronimo. I am the High Chief of my entire tribe.}
{302}{}{Tell me about yourself, chief.}
{303}{}{Is your memory really that short? Then it requires refreshing a little - I'm the one called Geronimo. I am the High Chief of the tribe.}
{304}{}{High Chief? So there are others?}
{305}{}{A tribe is made up of clans, each clan having its own chief or elder. Together we unite during difficult times. The rest of the time we wander Sonora with our herds, in search of food.}
{306}{}{Okay, I get it.}

{310}{}{Tell me about your people.}
{311}{}{You want to know the history of the tribe? We have suffered much, but remain true to our ways.}
{312}{}{Sorry, Chief, but I don't have time to listen to long stories right now.}
{313}{}{Hmph, young people no longer want to know history and honor their ancestors. That worries me.}
{314}{}{Some other time.}
{315}{}{Tell me more.}
{316}{}{We have lived in the lands of Sonora for many generations. Our ancestors lived here even before the world fell from the wrath of the Fiery Brahmin.}
{317}{}{It's hard to believe you were able to survive in the desert for so long.}
{318}{}{It's a miracle you survived the War.}
{319}{}{For a long time, the tribe consisted of many small families scattered throughout the desert. Everyone survived as they could. The weak and sick died out, while the strong and healthy continued their lines. When families grew and good grazing lands grew scarce, clan wars began.}
{320}{}{There's no war between the clans now?}
{321}{}{The threat of the Phoenix Empire has forced us to unite. The city people began to steal our cattle, merchants began to deceive, slave traders appeared in our lands. We could not bear it any longer.}
{322}{}{What did you do?}
{323}{}{The elders gathered around a common fire and decided to unite. I was one of those who brought the tribe together in peace. It happened here, within the walls of this ancient pueblo.}
{324}{}{Thanks for the story. See you later, Geronimo.}
{325}{}{Inspiring story. Let me ask you about other things.}
{326}{}{No, I just want to talk about something else.}

{330}{}{You said you knew me. From where? }
{331}{}{Not you, but your father. I met him once, many years before. Strong man. Persistent. One that all respect.}
{332}{}{Hmm, sounds like him.}
{333}{}{My padre is not worthy of such words. He couldn't resist the slavers and surrendered.}
{334}{}{But he made it clear that he did not want a strangers to set foot in the Villa. We entered into an isolation agreement. Our tribe still does not visit those parts. There is not enough grass for our brahmin.}
{335}{}{It's just desert all around.}
{336}{}{It is very surprising that you grow crops in the middle of barren land. It is as if the Divine Brahmin himself guarded your lands... until recently. Maybe you did something to anger him?}
{337}{}{I'd also like to know how such a miracle came to be. But enough about my village. Let's talk about yours.}
{338}{}{I don't think so. We just let our guard down. And by the way, it's time for me to go and fix this whole problem. See you later, chief.}

{340}{}{I know you have an ancient book, Chieftain. I'd like it.}
{341}{}{Book? What are you talking about? We don't have any books.}
{342}{}{You're lying. The Bookkeeper of the Cathedral could not have been mistaken.}
{343}{}{Please, people outside your tribe need this book.}
{344}{}{Hmm, you must be talking about something down in the underground levels.}
{345}{}{Underground levels? What are you talking about?}
{346}{}{Well, you see, this ancient building has several floors buried beneath the sand. There are still ancient things downstairs, but we have no use for them. Therefore, no one goes down there and no one remembers what is there and what is not. And this is not the only place buried - this entire area has been buried in the sand for several generations.}
{347}{}{So can I go down and get the book?}
{348}{}{You may. But prepare for the worst. A test of spirit awaits you below. I myself heard the voices of long-dead people there. You may never escape those ancient halls, just like the other treasure hunters who went there in search of ancient relics.}
{349}{}{I'll take the risk. See you later, chief.}
