{101}{}{You see a tribal child with long, black hair.}

{110}{}{You are only a stranger.}
{111}{}{Tell me about your tribe?}
{112}{}{Is your tribe big like our tribe?}
{113}{}{Tell me story.}
{114}{}{The shamans say you are good person.}

{120}{}{Get out of the pueblo, you bad person!}
{121}{}{Your tribe is weak.}
{122}{}{Is your whole tribe shit like you?}
{123}{}{Tell that to fools in the City.}
{124}{}{The shamans say you have an evil spirit inside you.}

{130}{}{What tribe are you from?}
{131}{}{Our tribe is better than your tribe.}
{132}{}{What happened to your tribe?}
{133}{}{Tell me story about other lands.}
{134}{}{The shamans say you can not be listened to.}
