{100}{}{You see a woman.}
{101}{}{You see one of the tribe's women. She is busy cooking.}

{210}{}{What do you want?}
{211}{}{You are welcome in my home, hero.}
{212}{}{Were you invited here?}
{213}{}{Bye.}

{220}{}{What's that smell in here?}
{221}{}{I cook brahmin sausages. Hands off! I will not even let you lick plate. Shoo out of here!}
{222}{}{Okay, okay.}
{223}{}{I cook brahmin sausages. My favorite food, but spices hard to get.}
{224}{}{Smells amazing! Can I try it?}
{225}{}{What a smell. Is this even edible?}
{226}{}{Our hero should not feel sorry for anything. Here, take plate.}
{227}{}{Thanks.}
