{100}{}{You see the bartender.}
{101}{}{You see a regular bartender.}
{102}{}{Sorry, but THIS is not allowed here.}

{110}{}{Hey there, traveler! Come wet your throat and wash away the dust of the road.}
{111}{}{Care for a drink? Got some specials today.}
{112}{}{Thought I'd see more folks around, but hey, you're here!}
{113}{}{Don't worry, everyone here is as friendly as a rabid dog in heat.}
{114}{}{Oh, finally, a customer! Been a quiet day, ya know?}

{200}{}{Hey, hi there! Good on ya for stopping by.}
{1200}{}{Aw, lady. My regards. Thanks for stopping by.}
{201}{}{Wasn't this bar abandoned?}
{202}{}{Yeah, it was a ghost town. But the city's picking up, so I thought, why not revive the old watering hole?}
{203}{}{And the mayor didn't mind?}
{204}{}{He used to keep folks out of here, but lately, he's been all fired up. No clue what's crawled up his ass, but I snagged this place before he changed his mind.}
{205}{}{Got it. Can I get a drink?}

{210}{}{Sure thing! Take a seat. The selection's not huge, but it'll wet your whistle.}
{211}{}{Gotta run. Catch ya later.}
