{100}{}{You see John Sullivan.}
{101}{}{You see a man who commands respect. He looks very clean and well-groomed.}
{102}{}{You're not going to wander around here in this, are you?}
{103}{}{You have a deathwish? Get out of town, you god damn highwayman.}

#Before repair
{200}{}{Hey, stranger. I don't like strangers messing around on my property.}
{1200}{}{Aw, lady, what a surprise to see a lady here. Although I don't usually like strangers hanging around on my property.}
{201}{}{Is this your water pump? Do you own it?}
{202}{}{It is and I do. I'm John Sullivan. And I own this entire pump. Do you have business with me? If not, then step outside. I need to fix this filter, not chat with strangers.}
{203}{}{Sorry to bother you. I'll leave right away.}
{204}{}{I'm new here. Can I ask you a couple of questions about the city?}
{205}{}{Am I speaking quietly? I HAVE NO TIME to chat with you.}
{206}{}{Oh, then I'll leave right now.}
{207}{}{Who should I talk to about the city?}
{208}{}{Old Bustos, his mansion is just down the road.}
{209}{}{Thanks. Goodbye.}
{210}{}{Why not have it repaired?}
{211}{}{Is there really no one else to fix this?}
{212}{}{The Tinsmiths charge us three skins for any service. They know that water is a profitable business, but we can't give them everything. And aside from the Tinsmiths, no one can handle such work. Only they have the working machines and the necessary skills.}
{213}{}{Oh, sorry, then I won't interfere.}
{214}{}{And yet you hope to fix it yourself?}
{215}{}{Sometimes it works. This is one of the filters, it's just clogged with dirt... Or something.}
{216}{}{I can fix it.}
{217}{}{Really? If you fix the filter, I'll pay. Less than the Tinsmiths, of course. But in the end, everyone wins.}
{218}{}{Okay... This will take some time.}
{219}{}{Hmm, the tech is too complicated for me. I'm afraid I can't handle it.}
{220}{}{You again? What is it this time?}
{221}{}{Uh, nothing.}
{222}{}{About the pump. Why not have it repaired?}
{223}{}{The filter is fine. Dirt and sand messed up some parts, but I managed to fix them.}
{224}{}{I appreciate efficiency. Here, take these 200 caps as payment for your work.}
{225}{}{Thanks.}
{226}{}{That's not enough.}
{227}{}{That's plenty. If you wanted more, I wouldn't have offered you the job.}
{228}{}{You're really tightfisted.}
{229}{}{Thanks anyway.}
{230}{}{This barely covers the cost of the extra parts.}
{231}{}{Alright, here's another 50 caps. And don't ask for more.}
{232}{}{You're really tightfisted.}
{233}{}{That'll do, thanks.}

{234}{}{I'm looking for a Tinsmith. Has one been here recently?}
{235}{}{Yes, he was here. Checked the pump, discussed some minor repairs, and then headed off to see the mayor. Haven't seen him since.}
{236}{}{Thanks, I'll go talk to the mayor.}
{237}{}{Actually, I'm tracking some slaves taken to Two-Sun.}
{238}{}{Then head to Two-Sun. Why ask me? We just service the caravans and send them on their way. It's just business.}
{239}{}{Convenient excuse, huh?}
{240}{}{Makes sense.}

{241}{}{What kind of disagreement did you have with the mayor?}
{242}{}{Time and children have softened the old tyrant. He lost his edge and the right to dictate to me. Before, I had to play the role of manager because of him. Now, it's my turn to live well.}
{243}{}{I guess so. At least for now.}
{244}{}{Find someone else to chat with. I don't have the time or the interest.}
{245}{}{Alright then, I won't bother you.}

#After repair
{250}{}{Now we can talk a little. What do you need?}
{251}{}{Nothing special. Bye.}

{260}{}{Is this all a water pump? Impressive.}
{261}{}{Yep, over a century old. We just keep the old machinery ticking.}
{262}{}{Why stockpile so much water?}
{263}{}{I've got to go. See you around.}
{264}{}{Hold on, one more question.}
{265}{}{Why not? Everyone needs water. Out here, it's the lifeblood. For me, it's also a good way to earn caps. This pump supplies the whole city.}
{266}{}{Aren't you the one running the show here?}
{267}{}{Water pulls in the caravans, which means more business for the town. Plus, the mayor needs his cut. Gotta keep him happy.}
{268}{}{And I guess you're not too thrilled about that?}
{269}{}{Someone has to handle the paperwork and deal-making. I'd rather be fixing things. I just wish Alfred was tougher on his clients. I'm sick of bouncing between customers.}
{270}{}{Alright, let's rewind a bit.}
{271}{}{Where'd you get all that knowledge of pre-war tech?}
{272}{}{Honestly, the Tinsmiths handle the big repairs. I know a few tricks from experience, but the other guys here just push buttons.}
{273}{}{You don't seem to trust them?}
{274}{}{}
{275}{}{Tinsmiths? What makes them so special?}
{276}{}{We sacrificed a lot to restore this place. No one else could have done it. Plus, the Tinsmiths have a vested interest in the trade routes.}
{277}{}{Did you know those techies fell victim to one of the techs they worshipped so much?}
{278}{}{I've heard. Doesn't bother me. But... what happens when the pump needs another major repair? I don't even want to think about it.}
{279}{}{Let's rewind a bit.}
{280}{}{Who's in charge around here?}
{281}{}{I call the shots here.}
{282}{}{Interesting. So, you're the one I need to talk to.}
{283}{}{The mayor and I run things together. His name's Bustos; he lives down the road in a big mansion.}
{284}{}{Tell me about the mayor. What's he like?}
{285}{}{Known him a long time. We get along, though we clash sometimes -- especially over his daughter. He lets her get away with too much.}
{286}{}{He's got a daughter?}
{287}{}{Yeah, a nice but headstrong girl. I don't get why Bustos lets her off the hook so easily. If she were mine, I'd have set her straight with a belt ages ago.}
{288}{}{I see. Let's backtrack a bit.}
{289}{}{What's your opinion of the mayor?}
{290}{}{What, you want me to bad-mouth my best friend? What's it to you, anyway?}
{291}{}{Nothing, nothing. I'm just passing through.}
{292}{}{Any work around town?}
{293}{}{Try the mayor. There's nothing left for you to do here at the pump.}
{294}{}{Yeah, there's nothing else around here for you.}
{295}{}{Alright. Let's talk about something else.}
{296}{}{Guess I'm wasting my time in this town. Goodbye.}
{297}{}{All I've got is fixing that damn filter. Are you good with tech?}
{298}{}{Nah, not really my thing. Let's talk about something else..}
{299}{}{Let me take a look. Maybe I can help out.}

{300}{}{I know what went down at the merchant's place. Poverty makes folks do crazy things.}
{301}{}{Are you threatening me?}
{302}{}{If you've got any sense, you'll stay quiet. We've got a reputation to protect.}
{303}{}{No worries. I didn't see or hear a thing.}
{1303}{}{No worries. I didn't see or hear anything.}
{304}{}{Smart choice. Maybe you and I can get along.}
{305}{}{Yes... of course.}
{306}{}{Keeping quiet isn't free, you know.}
{307}{}{Keep your trap shut and you'll stay out of trouble. It's that simple.}
{308}{}{Oh, is that how it's gonna be...?}
{309}{}{Silence costs. You don't expect this story to bury itself, do you?}
{310}{}{Business talk, huh? (hands over 10 caps) But mind your tongue. Cause any trouble here, and you'll regret it.}
{311}{}{Oh, I get you loud and clear...}

