{100}{}{You see a super mutant.}
{101}{}{You see a huge super mutant in front of you.}

{110}{}{I hungry.}
{111}{}{Are you hungry too?}
{112}{}{If I don't eat, I kill someone.}
{113}{}{Shall we measure strength?}
{114}{}{Pathetic humans will die out. We will outlive them all.}
{115}{}{The Master hears my prayers.}
{116}{}{Who fart?}
{117}{}{I hate when people stare at me.}
{118}{}{What year is now?}
{119}{}{Slowly. When we leave this desert?}

{120}{}{For the Master!}
