{100}{}{You see a Mexican.}
{101}{}{You see a Mexican who suddenly appeared in the middle of the desert.}
{102}{}{Muchas gracias.}
{103}{}{«Thank you very much.»}


{200}{}{Muchas gracias. (Gives you clean water as a reward) Bebe, amigo.}
{1200}{}{Muchas gracias. (Gives you clean water as a reward) Bebe, amiga.}
{201}{}{You don't speak English?}
{202}{}{Ingles? No.}
{203}{}{I see. Well, have a nice trip then.}
{204}{}{«You're welcome. By the way, where are you from?»}
{205}{}{«I'm from Hermosillo. There are no other cities in this area. Although you can't call it a city.»}
{206}{}{«What are you doing in the middle of the desert?»}
{207}{}{«I'm scouting the land. The army needs to know where there are water sources or anything else around here. True, there is nothing of value here - only desert and giant insects. I thought I was finished. It was great luck to meet you.»}
{208}{}{«I see. Well, have a nice trip then.»}

{300}{}{«Thank you very much. (Gives you clean water as a reward) Drink, friend.»}
{1300}{}{«Thank you very much. (Gives you clean water as a reward) Drink, friend.»}