{100}{}{You see a machine operator.}
{101}{}{You see the processing machine operator.}

# Dialogue
{200}{}{(not looking up from his work) Huh? What do you want?}
{201}{}{Nothing.}
{202}{}{(continuing his work) Make it quick.}
{203}{}{Bye.}
{204}{}{Wait, can you tell me something else?}

{210}{}{Tell me about your work.}
{211}{}{What can I say? I take the ore, load it into the machine, and it grinds and cleans it. The purified ore goes to the beneficiation machine, and the rest is discarded. That's it.}
{212}{}{Why refine the ore?}
{213}{}{Uranium must be free of impurities; otherwise, it won't provide the necessary energy. Honestly, I don't fully understand all the technology.}
{214}{}{Is it safe to work with uranium?}
{215}{}{If you're talking about radiation, it's not a problem until the ore is cleaned. But getting injured by this damned ancient machine is quite possible.}

{220}{}{Where does this equipment come from?}
{221}{}{Leftover from the old days. Although these are small things compared to what was here before.}
{222}{}{So, in pre-war times, uranium was also mined and refined here?}
{223}{}{Yeah. The underground galleries are well preserved, but some of the equipment and buildings have fallen into disrepair.}
{224}{}{There's got to be... something behind this whole setup, don't you think?}
{225}{}{Huh? What are you talking about?}
{226}{}{Just thinking out loud.}
{227}{}{It can't be that people just came and restarted these ancient machines. Who has the knowledge to do something like that?}
{228}{}{Good point. They say that before creating the colony, Faber brought in some guys who repaired and setup the equipment. Only after that did he bring people here and start production. None of the locals could have done this.}
{229}{}{How interesting. I have more questions.}

{230}{}{Are you here of your own free will?}
{231}{}{Formally, yes. But I have nowhere else to go, so I'm essentially a willing slave.}
{232}{}{What do you think about slavery?}
{233}{}{I don't know. It's probably wrong to force others to work for you. But we're all in the same cage here.}

{240}{}{The mine has been blown up. What are you going to do now?}
{241}{}{I don't know. Whatever they order, I'll do. I have nowhere else to go anyway.}
{242}{}{Lash won't bother anyone anymore. Look outside.}

{250}{}{Does the overseer often beat the workers?}
{251}{}{(sigh) That Lash... he's a real psycho. He takes it out on everyone. I get it from him too, but not as often. I wish I could get rid of him, but Faber himself appoints the guards.}
{252}{}{What about the administrator? Can't he do anything?}
{253}{}{I don't know why I'm telling you this, but Lash forces him to rewrite reports, claiming the imprisoned workers were caught in a landslide or injured themselves. He doesn't want to tarnish his reputation. But he also keeps the administrator under his thumb.}
{254}{}{But what's the point of crippling slaves?}
{255}{}{There isn't. Lash is just an evil man. I think Faber deliberately chose such a tough guard to strengthen control over the prisoners because there have been a lot of problems with them lately. Plus, Roy and Lash are on good terms. But Faber probably doesn't know the whole truth.}
{256}{}{I can take care of him for you and the other prisoners.}
{257}{}{What? Are you serious? You'd kill a man for a handful of prisoners? Even the mercenaries in the garrison aren't that bloodthirsty. And a worse tyrant would probably take Lash's place. Any way, don't involve me in this. I have nothing to do with it!}
{258}{}{That's okay. My conscience won't be bothered by killing scum.}
{259}{}{Perhaps you're right. This requires a delicate and 'legal' approach.}
{260}{}{I'll tell Faber what's really going on. He probably won't like it.}
{261}{}{I doubt he'll listen to you. But don't involve me in this. I have nothing to do with it!}
{262}{}{Still worth a try. Bye.}
{263}{}{Then I'll just take care of this Lash. I'll leave his corpse near the entrance.}
{264}{}{How do you like the new overseer?}
{265}{}{Better than before. He doesn't overthink things and keeps himself under control. I'm glad you were able to get rid of Lash.}
{266}{}{It was easy.}
{267}{}{This Lash won't bother you or anyone else anymore.}
{268}{}{You... killed him? Whoa. In any case, this doesn't really solve the problem, because after Lash, they'll probably bring in an even worse tyrant. Haven't you thought about this? Okay, I didn't hear anything, and I had nothing to do with it.}
{1268}{}{You... killed him? Whoa. In any case, this doesn't really solve the problem, because after Lash, they'll probably bring in an even worse tyrant. Haven't you thought about this? Okay, I didn't hear anything, and I had nothing to do with it.}
{269}{}{Is that all the gratitude I get? Yeesh.}
