{100}{}{You see a hunter.}
{101}{}{You see an exhausted looking man.}
{102}{}{Shh! Open the gate. Just don't show yourself to the savages.}
{103}{}{The hunter has been succesfully rescued.}

{200}{}{Hey! Just in time. Keep quiet! These savages have sharp ears. They sent you from Flagstaff?}
{201}{}{Yes. The bartender wants to know what's going on here.}
{202}{}{It's bad. Real bad. The savages killed the other hunters and locked me up for their next meal.}
{203}{}{Actually, no. I'm lost and was hoping to find a place to hole-up for the night.}
{1203}{}{Actually, no. I'm lost and was hoping to find a place to hole-up for the night.}
{204}{}{Well, welcome to Winon. Sorry, I can't offer you a cup of tea. The savages killed the other hunters and locked me up for their next meal.}
{205}{}{That's horrible.}
{206}{}{}
{207}{}{Help me get out of here? Quietly! We can't handle all of them without weapons.}
{208}{}{Now isn't the time. I'll let you know when it's safe.}
{209}{}{Sorry, but you'll have to wait a bit longer.}
{210}{}{Alright. I'll get you out.}
{211}{}{Help me get past the forest, then I'll manage from there.}
{212}{}{Okay.}

{220}{}{Why did the savages attack you?}
{221}{}{Isn't it obvious? They wanted our loot and to show who's boss. This tribe has a grudge against us.}
{222}{}{Enough talk.}
{223}{}{Why do they have a grudge?}
{224}{}{When Faber set up the Flagstaff colony, he drove the local tribe from their homes. Killed some, exiled others, but this group stayed to harass the colony. In a word - savages.}
{225}{}{How did they defeat you with spears?}
{226}{}{They ambushed us at night while we slept. They're better in that kind of a fight than us city folk.}
{227}{}{Tell me about the area.}
{228}{}{Wild lands. Few people, lots of creatures. Forests and mountains stretch for miles. We've set traps around the camp, so watch your step.}
{229}{}{Can you show me where your traps are?}
{230}{}{Traps are set in the forest thicket near the camp entrance. Watch your step.}
{231}{}{Thanks.}
{232}{}{What do you know about these savages?}
{233}{}{They're a clan from a tribe that once lived here. Small in number now. Faber wiped out most and exiled the rest. These few probably returned for the game-rich lands.}
{234}{}{Any ideas on how to drive them away?}
{235}{}{A shotgun or a squad from the garrison would help. They're superstitious. Those totems around the camp are proof.}
{236}{}{What's the nearest city?}
{237}{}{Flagstaff. A mining colony southwest of here.}
{238}{}{Thanks.}

{240}{}{You're safe now.}
{241}{}{Once they realize I've escaped, they'll raise the alarm. But I'll be far away by then. Thanks for your help. I'm gonna tell everyone in Flagstaff what you did.}
{242}{}{Good luck.}
