{100}{}{You see Mr. Kogan's computer.}  
{101}{}{You see an ancient computer that has been skillfully restored by the garage mechanics.}  
{102}{}{The computer is destroyed!}  
{103}{}{[test: damage]}  

#Dialogue
{200}{}{Enter command:}  
{201}{}{End session}  
{202}{}{Back}  

{210}{}{View cartel reports for the entire period}  
{211}{}{(Starting in 2160, scavengers actively extracted resources from the ruins of Kingman. For the first six years, the 'mine' produced huge profits, but after that, the production and trade graph began to steadily decline.)}  
{212}{}{Flagstaff contracts}  
{213}{}{(Mr. Kogan entered into several contracts with the Flagstaff colony to exchange scrap metal and repair services for food, medicine, and nuclear fuel. Apparently, he also anticipates even more significant contracts in the future.)}  
{214}{}{Deployment support contract}  
{215}{}{(Mr. Kogan actively assisted the raiding party before and after the enslavement of Villa. Under the contract, he provided sleeping quarters, clean water, and equipment repair services. Although the profit was small, the potential benefits justified the investment.)}  
{216}{}{[More]}  
{217}{}{(Among the notes, you discover that the raiders were a group of mercenaries from a colony called Flagstaff. Apparently, the enslaved people of Villa was taken there as well.)}  

{220}{}{Copy contracts for Lucas.}  
{221}{}{Data copied successfully.}  
{222}{}{Great.}  
