{100}{}{You see Levi.}
{105}{}{Bastards! You're gonna pay for the death of my friends!}

{110}{}{In the name of the Master...}
{111}{}{In the name of His Holy Spirit...}
{112}{}{Accept the sinful soul of your slave...}
{113}{}{Servant of God, kneel down and repent of your sins before the face of the Master.}
{114}{}{Drink from the sacred cup of Holy Virus.}
{115}{}{May the Holy Spirit be with you.}
{116}{}{Amen.}

{200}{}{Greetings, stranger. I am Levi, guide of my small flock.}
{1200}{}{Greetings, stranger. I am Levi, guide of my small flock.}
{201}{}{And I'm }
{202}{}{. Just a traveler.}
{203}{}{A church and a saint in the middle of charred ruins - this is very strange.}
{204}{}{You have entered our sanctuary, and your presence here is... disturbing. But, let us be clear - you will be safe here as long as you follow the rules and mean us no harm.}
{205}{}{I don't want any trouble. Especially in this situation.}
{206}{}{Whatever you say.}
{207}{}{Very good. It's unexpected to see a normal person here. Tell me what brought you here.}
{208}{}{Be polite at gunpoint with a six-barreled minigun? You're not very nice for a 'priest'.}
{209}{}{If you put yourself in our position, you'd think differently. Now tell me what brought you to these ruins? And don't lie - I will feel any lie.}
{210}{}{Just looking for useful things in the ruins. There must be plenty of pre-war treasures left here.}
{211}{}{Your desire for profit has led you straight to hell. As one would expect.}
{212}{}{What are YOU doing in this hell?}
{213}{}{I'm looking for my people. They were kidnapped by slave traders.}
{214}{}{Obviously they're not here. You are foolish if you're looking for a slave convoy in such a lifeless place.}
{215}{}{Still, I had to check. What are YOU doing here?}
{216}{}{I'm looking for a Brotherhood of Steel convoy. It was lost somewhere in these ruins.}
{217}{}{Ah yes. So the Brotherhood sent a mercenary instead of risking their own people. As I expected, they do not have enough forces in this region for full-fledged rescue operations. So much the better for us.}
{218}{}{Why is that? Are you up to something?}
{219}{}{It's a long story. Some people think I'm the devil, trying to create my own hell. But in reality, I am trying to create a heaven for my people in the middle of hell.}
{220}{}{Sounds like the devil's plan.}
{221}{}{Go on.}
{222}{}{That's very noble of you.}
{223}{}{We can no longer live in a normal world. The pagans burn our brothers in the west, and the east does not accept either our faith or ourselves. The north and south are deserted. All we have left, is to create our own world.}
{224}{}{[More]}
{225}{}{Now you understand why your presence here is highly unwelcome. Especially considering our recent meeting with other "normals".}
{226}{}{Wait, so there are other "normals" like me here?}
{227}{}{A group of pagans were crossing the ruins to the south. They were not destined to leave these lands. Like you, they will remain here forever.}
{228}{}{If I help you with your "heaven", will you let me go free?}
{229}{}{We share a name? Strange twists of fate... But it doesn't matter. }
{230}{}{Whatever. I think I'll be leaving now.}
{231}{}{There's no way out for you here. Garrett, explain this to our guest...}
{232}{}{I'm still leaving here. Don't try to stop me.}
{233}{}{Wait! What if I help you? Will you let me go then?}
{234}{}{You want to make a deal with the devil? Fine.}
{235}{}{[More]}
{236}{}{Go down into the basement and talk to Diana. She'll tell you what kind of research we are conducting and what is needed to complete it. Everyone will receive their reward according to their results.}
{237}{}{Okay. I'm going.}
{238}{}{Actually, no. I don't make deals with devils.}
{239}{}{It's a pity to hear a refusal after such a frank conversation. Garrett, I'll leave this up to you...}
{240}{}{Now what?}
{241}{}{Stay back, big guy!}

{242}{}{Batva? Pra.. What?}
{243}{}{(Heavy sigh) Poor child... It's amazing that you managed to survive and get here. But don't worry. We are your friends. We will help. You wouldn't harm your friends, would you?}
{244}{}{Oh, friends! Friends!}
{245}{}{You're lying. You are bad. I don't have any friends.}
{246}{}{Well, I understand. You're lonely, like all of us. But now we are your friends. I give you my word, you'll be fine with us.}
{247}{}{No! Do not believe! Deception!}
{248}{}{This body will be too much trouble. Garrett, end his suffering...}
{249}{}{Yeah!}

{250}{}{What can you tell me?}
{251}{}{It's time for me to get down to business.}
{252}{}{Calm down, my child. You're in the church, you're safe. Nobody will touch you here. Maybe you can do something for your new friends? Diana lives in the basement. You will find a lot in common with her. Go talk to her. Go...}
{253}{}{Uh, the girl in the basement. OKay, I'm going.}
{254}{}{Still here? Do you really want to stay in this sacred place?}

{255}{}{You have a part for some Power Armor. Will you give it to me?}
{256}{}{Take it. I trust that you will use this armor for good. Besides, we can't use it anyway.}
{257}{}{Thanks. I'll put it to good use.}
{258}{}{Thanks, but there's something else I'd like to know.}
{259}{}{Greetings, brother.}
{1259}{}{Greetings, sister.}

{260}{}{Who are you?}
{261}{}{I am Levi, the shepherd of these unfortunate souls.}
{262}{}{I've heard that before. Let's talk about something else.}
{1262}{}{I've heard that before. Let's talk about something else.}
{263}{}{Shepherd? Are you a priest or something?}
{264}{}{Our church was destroyed by pagans like you. Our god died in the atomic flame, so I lead my flock according to his commandments. But far from those lands where our faith turned to shame.}
{265}{}{What kind of church is it? What's it all about?}
{266}{}{You wouldn't understand the basics concepts in a simple mass. I'll only say that our god, the Master, wanted to save people from their vices and shortcomings by offering a different path.}
{267}{}{The different path being that of mutations and freakishness?}
{268}{}{Your vision is limited. Thanks to the Master, we are devoid of human vices and are able to survive even in such an inhospitable place as these ruins. And you?}
{1269}{}{I don't think I would live here regardless. Why did you come to this place?}
{269}{}{I don't think I would live here regardless. Why did you come to this place?}
{270}{}{Why did you choose this particular place for your flock?}
{271}{}{Simple tactics. Here we are safe from pagans and heretics. We gather our strength for the Second Coming, when the Master will rise again from the ashes.}
{272}{}{Your story is interesting. But there are more important things to discuss.}
{273}{}{So what is this belief you're clinging to?}
{274}{}{It seems this Master was really important to you.}
{275}{}{We are the Children of the Cathedral. We were crucified for our faith, but we'll continue our prayers until the end of the world. This is our burden.}
{276}{}{In my opinion, you're just another cult. I don't believe you.}
{277}{}{You seem to really believe what you say.}
{278}{}{Your devotion to your faith is worthy of respect.}

{280}{}{How did you and the others become like... this?}
{281}{}{Ugly? Freakish? Mutated? Fortunately, we have long stopped taking these words with offense. For us, appearance has long lost its importance. What made us like this? Our sins and impure thoughts when we were human.}
{282}{}{When you talk about god, who do you mean?}
{283}{}{God no longer exists. God fell at the hands of fools. We are the only ones who bring light in this hell after his death.}

{284}{}{Hmm. I've seen a robe like this before. Followers of Fire in Phoenix wear something similar.}
{285}{}{We've encountered imitators who parasitized small settlements under a banner similar to ours. Do not believe these blasphemers; their faith is feigned.}
{286}{}{Who do you mean when you talk about god?}
{287}{}{Not until you've completed your task.}
{288}{}{Okay.}

{290}{}{What do you know about Diana?}
{291}{}{The Followers of the Apocalypse are kind but misguided people. They try to help others to the best of their understanding. They treat people like me with condescension, as if we need their care. But it's the other way around.}
{292}{}{Why do you need Diana?}
{293}{}{She is a physician and scientist. Exactly what I need to complete our mission.}
{294}{}{So what is this mission?}
{295}{}{Heaven in the middle of hell.}
{296}{}{I see.}
{297}{}{What do you know about the Followers of the Apocalypse?}

{300}{}{What do you know about the Brotherhood of Steel?}
{301}{}{Heretics who have lost all faith in God. They only believe in the power of technology. Poor people.}
{302}{}{You're on bad terms with them, aren't you?}
{303}{}{The Brotherhood is guilty of killing our god. Their forgiveness will only come at the epicenter of atomic fission.}
{304}{}{I see.}

{310}{}{Diana developed a mutagen.}
{311}{}{Her work is invaluable. But I can't risk giving the medicine to my people just yet.}
{312}{}{Want to check? But how?}
{313}{}{Let's see how the mutagen affects our crazed brothers living in the ruins. Take these sprayers and place them in the busiest areas where the Reavers perform their demonic rites.}
{314}{}{You do realize that I could die on this mission, right?}
{315}{}{Are you talking about their totems? Okay, we'll have to act secretly so as not to make too much noise.}
{316}{}{You're almost dead anyway. But I believe that you'll succeed if you don't get dragged into a fight. Believe in our mission, believe in yourself.}
{317}{}{Yeah, uh, sure, no problem. Sneak into a crowd of ghouls and setup a sprayer. Nothing could be simpler. Uh, bye.}
{318}{}{You're sending me to my death. But if I survive, you'll answer for everything.}
{319}{}{Thank the Master for your appearance. Now go.}
{320}{}{I'll try not to die.}
{321}{}{If I survive, you're gonna pay dearly.}
{322}{}{It's too dangerous. Maybe there is another option?}

{330}{}{This sounds very promising. But I can't accept it yet.}
{331}{}{We completed the mission. What's wrong? You need some guarantees or something?}
{332}{}{The lives of my people depend on this medicine. Prove that it is indeed safe.}
{333}{}{We did everything you wanted. If you don't keep your word, you can go to hell.}
{334}{}{That's very rude. Garrett, show our guest that he is no longer welcome here...}
{335}{}{Die!}
{336}{}{No, wait! I can take the mutagen to prove its effectiveness. Is that okay with you?}
{337}{}{Wait. What if I install mutagen sprayers in the ruins? Will that satisfy you?}
{338}{}{In that case, I can take the mutagen. I've got so much radiation in me anyway, it's my only shot at surviving.}
{339}{}{Commendable dedication. If you take the mutagen, you will become a different person, one of us. You'll gain friends and a new home, but you will lose your human appearance.}
{340}{}{Idiot, did you think I was serious? I'm not going to turn into a green freak and believe some bullshit.}
{341}{}{Everything will be fine. I'm not afraid of mutation.}
{342}{}{Isn't there another alternative? For example, I can test the mutagen on Reavers.}
{343}{}{Okay. I could install mutagen sprayers in places where Reavers gather.}
{344}{}{Yes, that would clear things up. Let's see how the mutagen affects the inhabitants of these ruins.}
{345}{}{Okay.}
{346}{}{The mutagen will be placed in these sprayers. Your task is to install them in the five busiest places in the ruins. Now go and don't bother me again until you complete the task.}
{347}{}{On my way.}
{348}{}{Get ready for the ceremony. I'll personally conduct the dedication according to the canons of the church.}
{349}{}{[Wait for ceremony]}

{350}{}{I installed the sprayers. They had quite an effect on the Reavers.}
{1350}{}{I installed the sprayers. They had quite an effect on the Reavers.}
{351}{}{Really? What happened to them?}
{352}{}{They have become... smarter and calmer.}
{353}{}{I think the mutagen lowered their aggression and eliminated their chronic pain.}
{354}{}{Good. Just as Diana predicted. You did an excellent job. Honestly, I didn't expect this.}
{355}{}{So can we leave now?}
{356}{}{You have earned your freedom and our gratitude. Prepare for your journey, and when you are ready, you may leave; no one will hinder you. However, entry here will be closed to all "normal" people from now on.}
{357}{}{That's fine with me. Goodbye, Levi.}
{358}{}{I won't step foot into this hell again. Bye.}

{360}{}{You have proven your loyalty to our sacred alliance. You have forsaken the human for the spiritual. We are glad to welcome you, brother.}
{1360}{}{You have proven your loyalty to our sacred alliance. You have forsaken the human for the spiritual. We are glad to welcome you, sister.}
{361}{}{Ugh, I'm experiencing unusual sensations. It's like I've... been reborn.}
{1361}{}{Ugh, I'm experiencing unusual sensations. It's like I've... been reborn.}
{362}{}{That's right, brother. Now you are a new person. Forget the past and live in the present. Consider your last mission complete.}
{1362}{}{That's right, sister. Now you are a new person. Forget the past and live in the present. Consider your last mission complete.}
{363}{}{Now will you let Diana go?}
{364}{}{Of course. She completed her mission and earned forgiveness. But let her remember that Inferno is now under my control. Entrance here will be closed to all "normal" people. I'll collect her things and let her go, but she must not return.}
{365}{}{Allow me to take my leave, Brother Levi.}
{366}{}{So, what did we decide about the mutagen?}
{367}{}{Your job is to place mutagen sprayers in the busiest areas where the most Reavers gather.}
{368}{}{Okay, I'll try.}
{369}{}{You'll have to run fast to avoid the ghouls.}
{370}{}{I can't survive outside without this armor.}
{371}{}{But you've managed before? In any case, I can't trust that such a dangerous item might not be used against my flock.}
{372}{}{Too bad, I could use this armor.}
{373}{}{Levi, I ask you to return the Power Armor parts. With the armor, my chances at success will increase tenfold.}
{374}{}{So be it. Here are the parts. Use the armor only for good.}
{375}{}{Thanks.}
{376}{}{Scientific research requires investment, didn't you know that?}
{377}{}{I can't trust that such a dangerous item might not be used against my flock.}
{378}{}{Diana and I are scientists, not warriors. We need at least some protection.}
