{100}{}{You see a ranger in front of you.}
{101}{}{You see a prisoner. The Jackals beat this poor guy up pretty bad.}
{102}{}{Great. This way I can live a little longer.}
{103}{}{Is that all you've learned, Ranger?}
{104}{}{The ranger has successfully left Jackal Valley.}

#Dialogue BEFORE escaping
{200}{}{Leave me alone, you dirty savage... Shit, you're not one of the savages, are you? Did they catch you too?}
{201}{}{In a way.}
{202}{}{No, you idiot, I *want* to be here.}
{203}{}{Ugh, I thought I'd never see a normal person again...}
{204}{}{Well, you're in luck, buddy.}
{205}{}{Is it that bad?}

{210}{}{Listen, I gotta get out of here. Help me! My fellow Rangers will be in your debt if you do.}
{211}{}{We can't get out now. Wait here.}

{220}{}{Can you walk?}
{221}{}{Barely. The Jackals slashed my legs to prevent me from running away. Can you patch up my wounds? If not, then find my stimpak. One of the savages must have it.}
{222}{}{What is a "stimpak"?}
{223}{}{You really don't know? Damn it, shoot me now! Listen, it's an ancient thing with a needle and red liquid. Find it soon!}
{224}{}{Okay, I'll try to find it.}
{225}{}{Maybe I can find another way to get you back on your feet.}
{226}{}{I think so. At least I can get out.}
{227}{}{Great. Let's get out of here.}
{228}{}{We can't get out now. Wait here.}

{230}{}{Can you fight?}
{231}{}{Only if you give me a weapon. The Jackals took all my stuff, including my rifle. It could be anywhere and with anyone.}
{232}{}{I see. I'll keep that in mind.}
{233}{}{Tell me how you ended up here.}
{234}{}{My group was exploring the area. These cunning sons of bitches lured us into a trap. I'm the only one who survived.}
{235}{}{I see.}
{236}{}{The Jackals don't fight openly?}
{237}{}{That's not their style. Individually they are cowardly, they only attack as a pack... Argh, my legs are burning... Damn these savages!}
{238}{}{What were you looking for in this wilderness?}
{239}{}{We were given a mission. And orders are not discussed. This is the Ranger's charter.}
{240}{}{Okay, I'll take your word for it.}
{241}{}{What interest would Rangers have in such a desolate and wild a place?}
{242}{}{And you have an eye for lies... The commanders believe that the Jackals would be a good incentive to strike a contract with a neighboring city.}
{243}{}{What kind of contract?}
{244}{}{Are you Rangers always so secretive?}
{245}{}{Local settlements are suffering from the Jackals. If we got rid of them, we would improve our reputation around this region. That'll make signing contracts with the settlements a little easier. First step is to gather strategic information about the enemy and the terrain... But how about we stop chit-chatting and get the hell out of here?}
{246}{}{Not until I get more information.}
{247}{}{Good idea.}
{248}{}{What do you know about this place?}
{249}{}{I couldn't see much. Be careful up above - there are plenty of traps around the hut.}
{250}{}{I see.}

#Dialogue during and after the escape
{260}{}{I'll cover your rear. The main thing is not to attract attention.}
{261}{}{Let's go.}
{262}{}{We need to get out of here quickly. Let's talk when we get out.}
{263}{}{Be careful. This building is full of traps. We need to move further away.}
{264}{}{No pursuit in sight. Looks like we lost them!}
{265}{}{Let's go.}
{266}{}{Don't worry about me, I'll find my way.}
{267}{}{Have a safe trip.}

{270}{}{No pursuit in sight. Looks like we lost them!}
{271}{}{Relax, we're safe.}
{272}{}{It won't be long. Besides, I would have to hobble on my sore legs to the nearest outpost and call for help. But I can manage.}
{273}{}{Are you sure you don't need help?}
{274}{}{Yeah. I know a couple of places around here where you can rest and regain strength.}
{275}{}{Well, you know better.}
{276}{}{I advise you to stick to the river and move at a slow jog. This way you'll save energy, but make distance.}
{277}{}{Yah, good idea, although the route will be a little longer.}
{278}{}{[More]}
{279}{}{Then have a safe trip, Ranger.}
{280}{}{Thank you for your help. I'll tell my guys at the base about what you did. If you ever find yourself there, ask for Jason - that's me. Now it's time for me to go.}
{281}{}{See you around, Ranger.}
{282}{}{Thanks for the help. I'll make sure your deeds are known to my fellow rangers back at the base. But for now, I need some rest and a word with the commander.}

{290}{}{Stay here. I'll go scout around.}
{291}{}{Follow me.}
{292}{}{Put your weapon down, you're making too much noise with it.}
{293}{}{Take off this armor. It gives you away in the dark.}
