{100}{}{You see a raider in front of you.}
{101}{}{You see one of the Blue Shields.}

{110}{}{Hey, how's business?}
{111}{}{Good luck on the trail.}
{112}{}{You're tougher than we thought.}
{113}{}{I can't believe we're the route protectors now.}
{114}{}{The roads are now under our control.}
{115}{}{You bring us luck.}
{116}{}{Ben trusts you.}

{120}{}{Keep staring, and I'll give you a hard time.}
{121}{}{What do you want, trash?}
{122}{}{*Spits on the ground*}
{123}{}{Even though Ben let you in, you're not a gang member yet.}
{124}{}{I'm bored. Entertain me.}
{125}{}{You're taking a big risk by being here.}

{130}{}{Who the hell are you?}
{131}{}{It's him, keep quiet.}
{132}{}{I'd like armor like yours.}
{133}{}{Are you one of the Tinsmith's creations?}
