{100}{}{You see a worker.}
{101}{}{You see a man in work clothes. He looks exhausted.}

{110}{}{So you're the reason I'm stuck here, huh?}
{111}{}{If it weren't for you, I wouldn't be suffering like a slave here.}
{112}{}{The administrator's in that building over there.}
{113}{}{Got any idea how to escape this hellish prison?}
{114}{}{Many of us here are forced to work. The rest for measly wages.}
{115}{}{You here to fuck up this mess too?}
{116}{}{They say there was a monster here. Pray it was the only one.}
{117}{}{If that monster shows up again, I'd rather they shoot me on the spot.}
{118}{}{The demand for concrete and bricks is huge.}
{119}{}{Lots of work. We work in three shifts.}
