{100}{}{You see Theodore.}
{101}{}{You see a man with burned skin wearing well-worn work clothes with a pre-war symbol.}
{102}{}{Security! Outsider!}
{103}{}{We'll talk when Ralph's Electromagnetic Retribution hits.}
{104}{}{I have a lot to do. Thanks for visiting, old man. By the way, who are you?}
{105}{}{Oh, I don't feel well...}

{110}{}{ }
{111}{}{Boss! Theodore! Trouble!}
{112}{}{What happened? I'm trying to sleep here...}
{113}{}{Ralph and the others locked themselves in the control room. He's not fooling around this time!}
{114}{}{Ralph? I told you to bring him to me. TO ME. Repeat?}
{115}{}{No, boss, he's locked in and won't let anyone in. We need to do something!}

{200}{}{Well, well. Here comes the first messenger of evil. Or not? I'm losing track of the days. Need to wind my watch.}
{201}{}{Uh, I don't understand what you mean... I'm new in town, looking for my family.}
{202}{}{Hmm, really? Well, I've heard a hundred storys in as many years. Sorry to be skeptical, but it pays to be careful these days.}
{203}{}{Did something happen?}
{204}{}{A pipeline from the reactor cooling system exploded. Burst like a nasty worm. We've cut off the liquid flow, but the reserves won't last long. The reactor will overheat soon, and we'll have to shut it down.}
{205}{}{That doesn't sound good. Can it be fixed?}
{206}{}{Of course, but not by us. This is a nuclear power plant, not a factory. We need parts and equipment, and finding them will be hard work... (looks you up and down) Think you could handle it? We pay well.}
{207}{}{I don't think I could actually.}
{208}{}{Me neither, hehe. Just find us the materials to repair it. Easy peasy. There's a working factory somewhere south of here. Head that way and ask the locals.}
{209}{}{I'll think about it.}
{210}{}{That's too far out of the way. Sorry.}
{211}{}{Sure, I'm always up for earning some caps.}
{212}{}{Great, I'm counting on you. Go, but keep our agreement secret... Hmmm. Disgusting sea worms. They try to bite with their copper teeth.}
{213}{}{Uh... Goodbye.}
{214}{}{And remember, keep quiet about our deal. Especially from those crazy fire worshippers.}

{215}{}{Well, I can understand. But if you head that way, or come across some parts we could use, you know where to come knockin'.}
{216}{}{Sure. Goodbye.}



{220}{}{Yes, yes, I'm listening.}
{221}{}{Goodbye.}
{222}{}{I'm waiting for results. Remember, this work is paid.}

{230}{}{Can I ask a few questions about this power plant?}
{231}{}{Don't waste my time. I've already done you a favor by letting you in.}
{2231}{}{You already know everything, sunshine!}
{232}{}{Okay.}
{233}{}{I managed to fix the cooling system.}
{234}{}{Thank Ampere, you did it! I can't believe it. How did you manage?}
{235}{}{I had to tinker with it all day.}
{236}{}{Smoothtalk, smooth skin. However, I don't think it's a coincidence that your arrival coincided with the sabotage.}
{2236}{}{Smoothtalk, leather face. However, I don't think it's a coincidence that your arrival coincided with the sabotage.}
{237}{}{Uh, sabotage?}
{238}{}{We examined the wreckage. And what did we find? The system was deliberately blown up with dynamite. How do you explain that, my slippery smoothskinned friend?}
{2238}{}{We examined the wreckage. And what did we find? The system was deliberately blown up with dynamite. How do you explain that, my greenish and rotten friend?}
{239}{}{I have nothing to do with this. You let me in yourself and then...}
{240}{}{Enough of this nonsense, darling. I'll tell you what - find the culprits behind the attack. Then I'll decide if you get paid.}
{241}{}{Give me my caps, you rotten freak, or your gonna finally, meet your ancestors.}
{242}{}{How can I do that? The intruders could have snuck in from anywhere!}
{243}{}{You have the right idea. Now go and don't come back without info. Woo-ha-ha, I'll have fun trampling on one foot!}
{244}{}{Okay... uh, I'll go. Goodbye.}
{245}{}{I know the laws! Do you? So don't contradict the officer on duty.}
{246}{}{Uh... What?}
{247}{}{Thats it, you decrepit old freak. I'm gonna knock some sense into you!}

{250}{}{I know who sabotaged the cooling system.}
{251}{}{Well, isn't that interesting. Like a real detective story... And who might that be?}
{252}{}{Actually, I don't know. I'm just desperate. Uh... I better go get a drink.}
{253}{}{The sabotage was done by the Red Cardinals under the fire worshippers' orders. And your loyal assistant - Ralph, helped them.}
{254}{}{Short my circuits! Why would he get involved in this?}
{255}{}{I have no idea, but it's a fact.}
{256}{}{The Church wanted to push you guys into an unfavorable contract. And Ralph... likely, he thinks it's his time to take over as plant chief.}
{257}{}{Hey, security! Bring Ralph to me. And keep a close eye on him, no leniency... He's gone mad. Like an overripe cherry. Do you know how much effort it took to get this power plant running?}
{258}{}{Uhm... I have no idea.}
{259}{}{It must have been incredibly hard?}
{260}{}{Oh yes. Non-stop problems. Ralph thinks the cultists will do a better job if they take over. But from my own experience, I know you can't let ideologues into power. Oh, I love issuing fines for jaywalking. Makes you feel so... powerful.}
{261}{}{Okay...}
{262}{}{Ideologues are definitely dangerous.}

{270}{}{What's that old lecher up to? Deal with Ralph. This whole thing is getting too dangerous.}
{271}{}{I'll take care of it.}
{272}{}{You should talk to him first.}

{280}{}{Here comes our hero. Employee of the month at the power plant. Too bad I've run out of awards. But don't you worry. I know how to cheer you up. Go to the storekeeper and ask for any item in our supply room.}
{1280}{}{Here comes our heroine. Employee of the month at the power plant. Too bad I've run out of awards. But don't you worry. I know how to cheer you up. Go to the storekeeper and ask for any item in our supply room.}
{281}{}{Happy to serve.}
{1281}{}{Happy to serve.}
{282}{}{After everything I've seen, I don't understand how you even function with your madness. And you're running this power plant.}
{283}{}{What's that? Miasmas? Yeah, they're a problem. Tried washing, but the smell only got worse. You just worry about yourself.}
{284}{}{Goodbye, old man.}
{285}{}{I hope we never cross paths again.}
