{100}{}{This is a slum dweller.}
{101}{}{You see a resident of the local slums.}
{102}{}{Some bastard killed her!}
{103}{}{I'm willing to chat, but my stomach's growling. You understand.}
{104}{}{Thanks for the food, sir.}
{1104}{}{Thanks for the food, senora.}

{110}{}{You okay?}
{111}{}{How's life?}
{112}{}{But everything is still the same with us.}
{113}{}{Come again if you want.}

{200}{}{Hello. How can I help you?}
{201}{}{You? You probably can't.}

{210}{}{Who are you?}
{211}{}{I'm Fred. My wife and I recently moved from the desert where we were raising a small herd of brahmin. Or at least trying to. Our ranch collapsed due to drought and bandit raids, so we decided to try our luck in the big city.}
{212}{}{Bye, Fred.}

{220}{}{Why are you living in this old building?}
{221}{}{It's not that bad. Better than living on the street. Vernon made a deal with a gang to protect the area. But to live here, you have to pay tribute or earn your place another way.}
{222}{}{Who's Vernon?}
{223}{}{Community house manager. His office is down the corridor to the right.}
{224}{}{What kind of gang?}
{225}{}{Some shady guys in leather jackets and nasty hairstyles. They've taken over an old building north of here. Best not to mess with them.}
{226}{}{I see. Bye.}
{227}{}{Remind me, what's your name?}
{228}{}{Who are you?}

{230}{}{What can you tell me about this area?}
{231}{}{Many consider this the worst residential area in the city. But for country folk like us, even this place feels like a big step up.}
