{100}{}{You see a Follower of Fire.}
{101}{}{You see one of the Followers. He whispers to himself, muttering either a prayer or some kind of nonsense.}
{102}{}{His Majesty Aaron is waiting for you.}
{103}{}{The Lord of Phoenix awaits you.}

{110}{}{*Inaudible muttering*}
{111}{}{Are you ready to embrace the Church of the Holy Fire?}
{112}{}{Those who ignore the Fire's call will be consumed by it.}
{113}{}{The Holy Fire scorched the ancestors for their transgressions.}
{114}{}{Only through faith in the Fire can both body and soul be saved.}
{115}{}{Blessings of the Fire upon you, brother.}
{116}{}{Has the Holy Fire opened your eyes too?}
{117}{}{Soon, all of Sonora will be bathed in the Holy Fire's light.}
{118}{}{We were all born from the same Holy Fire.}
{119}{}{To be enlightened by the Fire is to spread its light to others.}

{1114}{}{Faith in Fire is the only way to save body and soul.}
{1115}{}{Greetings, sister.}
{1116}{}{Has the Holy Fire illuminated you as well?}
{1117}{}{Soon the Holy Fire will illuminate all of Sonora.}
{1118}{}{We all came from the same protoflame.}
{1119}{}{To be enlightened is to enlighten others.}
