{100}{}{You see Brother Francis.}
{101}{}{You see one of the Followers. He is busy copying ancient drawings.}
{102}{}{How can I copy these drawings in such darkness?}

{200}{}{Greetings, stranger. How can I assist you?}
{1200}{}{Greetings, stranger. How can I assist you?}
{201}{}{First, tell me about this place.}
{202}{}{Assist me? Hmph, I really doubt that.}
{203}{}{Please leave. This is no place for rudeness.}
{204}{}{Sorry, I got off on the wrong foot. Tell me, what is this place?}
{205}{}{I'll leave. For now I guess.}

{210}{}{What do you want, sir?}
{1210}{}{What do you want, miss?}
{211}{}{How can I help you, acolyte?}
{1211}{}{How can I help you, acolyte?}
{212}{}{Goodbye.}
{213}{}{You seem to know a lot. I'd like to ask you about something else.}

{220}{}{Tell me about yourself.}
{221}{}{My name is Francis, I'm a bookkeeper.}
{222}{}{How did you become a follower?}
{223}{}{I've been a follower since I was a teenager. At that time, the church was little known and did not participate in the city's fate.}
{224}{}{And you blindly believe in the dogmas of your church?}
{225}{}{"Nisi videro, non credam. Non credam, nisi videro." There's no point in discussing this.}
{226}{}{And what exactly do you do, Bookkeeper?}
{227}{}{I restore old books, copy ancient writings, and make lists. For example, I'm currently busy with this magnificent drawing.}
{228}{}{Why copy old writings?}
{229}{}{We must preserve the knowledge of our infinitely wise ancestors for posterity. But the paper of the old writings has almost decayed; such texts will not last long, especially in the open air. Therefore, we restore, copy, and then preserve the old scriptures.}
{230}{}{But if you preserve them, they will become unavailable, right?}
{231}{}{Correct. And so we make copies that are kept in our library. True, they are often inferior in quality to the original, but this is a difficult question.}

{240}{}{What is this place?}
{241}{}{This is a library. A place where knowledge is preserved in paper form, mostly pre-war. I know it might seem odd, given that there's hardly a library left in the world. But that only makes our work here even more vital.}
{242}{}{Where do all these books come from?}
{243}{}{From all over the place. We buy all pre-war books and manuscripts. We inherited part of this collection from our predecessors, who buried them in the desert.}
{244}{}{But what are these old books for?}
{245}{}{They keep the knowledge of our ancestors. Unfortunately, we are unable to understand most of them. But someday the time will come, and these books will reveal their secrets.}
{246}{}{Do you think this knowledge is safe? Didn't our ancestors destroy themselves - the world - with it?}
{247}{}{It is true. But people learn from mistakes. From the past. In addition, we carefully share knowledge only with those who are worthy of it.}
{248}{}{Buried in the desert? What do you mean?}
{249}{}{After the Great War, scientists were shunned, blamed for bringing on the Apocalypse. People burned their books in massive pyres - at least, that's what the chronicles say. Our predecessors, the scientists, tried to save what they could, sealing many books in barrels and burying them out in the desert. Plenty of them are still out there, waiting to be found.}

{250}{}{About the drawing you're working on... Tell me, what does "transformer block 6-B" mean?}
{251}{}{That's... well... the title of the document, obviously.}
{252}{}{I understand that. But WHAT does it mean?}
{253}{}{That's the *name* of the drawing you're looking at. What does your name mean?}
{254}{}{I guess that makes sense.}
{255}{}{Of course.}
{256}{}{I see. This seems like a pointless conversation.}
{257}{}{My name has nothing to do with this. What does the drawing symbolize?}
{258}{}{It... symbolizes... (turns over the drawing and reads the inscription) 6-B transformer block.}
{259}{}{Of course, Brother Francis. You've cleared everything up nicely.}

{260}{}{You really have a lot of books. Can I study some of them?}
{261}{}{I'm sorry, but we are very... particular about access to our library. These books are too valuable, and their knowledge can be dangerous, for ordinary people.}
{262}{}{Okay, forget it.}
{263}{}{I think you're just geeks. Bye.}
{264}{}{You wouldn't deny me, your brother in faith, would you?}
{1264}{}{You wouldn't deny me, a sister in faith, would you?}
{265}{}{Oh, I didn't realize you were ordained as a acolyte. Of course, study any of the books. But be careful, they are very fragile.}
{266}{}{Thanks, Brother Francis. I'll be extremely careful.}
{1266}{}{Thanks, Brother Francis. I'll be extremely careful.}
{267}{}{Well, don't blame me if one of them gets damaged.}
{268}{}{I could donate 300 caps to the library.}
{269}{}{Well, that changes things. You can study our books, but be careful, they are very fragile.}
{270}{}{}
{271}{}{Well, that changes things.}
{272}{}{I don't have that many caps right now. I'll back come later.}
{273}{}{Even after all my help, you won't trust me to look at some books?}
{274}{}{Oh, of course you're right. Study the books, but be careful please, they are very fragile.}

{280}{}{Brother Francis, do you keep the acolyte mission schedule?}
{281}{}{Yes. But, understand, I can't just show you these schedules. Only a few of us have access to them. Why do you ask?}
{282}{}{I can't talk about it. But, can you at least tell who's been studying them lately?}
{283}{}{Hmm. These documents are used quite rarely. I think I can match it with the seals of visitors. But tell me the dates you need.}
{284}{}{I'm interested in these days...}
{285}{}{...Well, apparently, during those dates, only Prior Matthias could have examined the schedules.}
{286}{}{Where can I find him?}
{287}{}{His quarters are just up the hall. But be quiet, Brother Matthias gets very upset when he is abruptly interrupted from his meditation.}
{288}{}{Thanks, Brother Francis, you've helped a lot.}
{289}{}{I see. I'll take my leave now.}


#Books
{300}{}{You mentioned buying books. I travel a lot, so...}
{301}{}{Of course. If you come across any old books, please bring them to me. The Church will pay generously for your efforts.}
{302}{}{I'll keep that in mind.}
{303}{}{You need new books, right?}
{304}{}{I have some pre-war books.}
{305}{}{Ah! Excellent. How many books do you have?}
{306}{}{Maybe this isn't quite what you're looking for. Sorry to trouble you.}
{307}{}{What I mean to say is, I'm going to look for books now. Goodbye.}
{308}{}{All the books I have.}
{309}{}{Only one.}
{310}{}{Two books.}
{311}{}{Three books.}
{312}{}{This will be a great addition. You're helping the progress of all humanity. Thank you very much.}
{313}{}{Take it for free. This is my donation to the church.}
{314}{}{Truly, your generosity knows no bounds. Thank you.}
{315}{}{I'd like to ask you something else.}
{316}{}{Thank you very much. Goodbye.}
{317}{}{I want caps for this.}
{318}{}{Of course. It's only fair. Here's what I can offer - }
{319}{}{ caps.}
{320}{}{Is the library in need of any... specific books?}
{321}{}{Oh, yes. There are some we know of that we wish to add to our collection. However, their owners... don't want to share the old knowledge. Maybe you can break through their foolishness?}
{322}{}{Tell me more. Who stands in the way of progress?}
{323}{}{Stubborn people can sometimes be conviced by the old... one - two! One in the kisser and one in the nuts.}
{324}{}{Yes, well, I was recently informed that a very ancient, in fact, holy, book is kept in the town of San Brahmin. And it is apparently much older than the time of the Great War. Can you imagine? Unfortunately, the locals can't read it, and we're not allowed to even see it, due to the recent trade war.}
{325}{}{Are you suggesting I steal it?}
{326}{}{I guess that sounds a little harsh. But don't misunderstand. Local savages do not understand the true meaning of this book and cannot ensure its reliable preservation. In our hands, this relic will serve a higher purpose. So will you get this book? I'll pay handsomely for it.}
{327}{}{I don't think so. I don't want to take part in looting any 'holy' places.}
{328}{}{Well, I understand. Forget everything I said then.}
{329}{}{Of course.}
{330}{}{I think this library is a better place for such an old, holy book. I'll get it for you.}
{331}{}{Very good. I'm looking forward to it, eagerly.}
{332}{}{I have the holy book.}
{333}{}{Oh my... Oh, these pages are beautiful! God, there's even Latin in here! Phew, I'm trembling with emotion just seeing it...}
{334}{}{If it's so important to the church, then take it for free. I just want to do something good.}
{335}{}{You generosity will not be forgotten. I will pray for you, my brother. The world needs people like you.}
{1335}{}{You generosity will not be forgotten. I will pray for you, sister. The world needs people like you.}
{336}{}{Good luck, Brother Francis.}
{337}{}{This book wasn't easy to get. I want 300 caps for it.}
{338}{}{Of course, here are the caps. It's worth it for this precious relic.}
{339}{}{Good luck, Brother Francis.}
{340}{}{Wait, brother. I think you should talk to Aaron himself. I'll let him know about the help you have provided to our church. And if you need my recommendation, you can count on it.}
{1340}{}{Wait, sister. I think you should talk to Aaron himself. I'll let him know about the help you have provided to our church. And if you need my recommendation, you can count on it.}
{341}{}{Okay.}
{342}{}{See you later.}
{343}{}{You know... I think I already have this book.}
