{100}{}{You see a refugee from Flagstaff.}
{101}{}{You see a person in dusty clothes. It looks like they've traveled a long way to get here.}
{102}{}{*Sobs in response*}
{103}{}{Thank you, you've saved me from starving.}
{104}{}{Stay away from me, you pervert.}
{1104}{}{Don't come near me, you pervert.}
{105}{}{What's going on here?!}

{110}{}{Why are you doing this to us?}
{111}{}{We've known each other since we were kids.}
{112}{}{I promise there will be caps, just give me a little time.}
{113}{}{I know how to earn the rent.}
{114}{}{I don't have anything to pay right now, but that won't last long.}
{115}{}{Give me a chance, I'll earn some caps.}
{116}{}{I'm telling you, I WILL find a job.}
{117}{}{Listen, I don't want to fight with you.}
{118}{}{So, some people still hold grudges, huh?}
{119}{}{Let me stay at least one night.}

{200}{}{...How could you?! You were kind to us before. Now we're just street trash to you, huh?}
{201}{}{What's going on here?}
{202}{}{This arrogant jerk is going to evict us, his old friends. We don't have enough rent to pay, but it's just a temporary problem until we find work.}
{203}{}{You came from out of town?}
{204}{}{We're actually locals, but we've been working in Flagstaff for the past few years. After the uranium mine there closed, a lot of people lost their jobs, and riots broke out. We had to come back. The journey was tough, and we just, ran out of caps.}
{205}{}{Everything comes to an end.}
{206}{}{Sad story.}

{210}{}{Hey, can you spare ten caps? I'll pay you back as soon as I can, I promise.}
{211}{}{I'm short on caps too, sorry.}
{212}{}{Yeah, of course, everyone's got their issues. It's okay, I'll figure something out.}
{213}{}{Bye.}
{214}{}{Looks like you really need some caps. Here, just take these.}
{215}{}{Sure, here you go.}
{216}{}{Really? (quickly hides the caps) Oh, thank you, kind sir. What's your name?}
{217}{}{It doesn't matter. This is my way of atoning for past sins. Goodbye.}
{218}{}{My name is }
{219}{}{. Remember it. Tell your children about me.}

{220}{}{I'll give you 35 caps, but on one condition. I need a little 'service' you see.}
{221}{}{(Looks down dejectedly at the sleazy proposition)}
{222}{}{What do you say?}
{223}{}{Okay, forget it. Clearly, this isn't going to work.}
{224}{}{I still have some pride left. You can forget about any 'service' from me, you ugly bastard!}
{225}{}{Hey, take it easy.}
{226}{}{(sighs) Living in a colony, I never thought I'd have to earn money this way.}
{227}{}{There's a first time for everything. Move that ass, we'll find a secluded spot.}
{228}{}{Sorry, this was a bad idea. Forget it, I'm just gonna leave...}
{229}{}{(after an hour of rough sex, you rise from the bed with satisfaction and look at the limp, naked body below; you take out the caps and silently throw them on the dirty sheet; the woman rolls to her side and sobbing quietly)}
{230}{}{[Done]}
