{100}{}{You see Lloyd.}
{101}{}{You see a beggar scrounging the streets for food.}
{102}{}{People like him are just a blight on the world.}
{103}{}{Hey, you talkin' to me, tin can? Must've been somethin' funky in that last bottle...}
{104}{}{Oh, Lloyd...}

{200}{}{Hey, you look like you're new 'round here. Newbies got it tough in this town. Want a free tip? Make friends, it counts around here.}
{201}{}{What's your name, buddy?}
{202}{}{Kinda weird hearing that from a homeless beggar.}
{203}{}{I'm Lloyd. Just a street rat. But don't be fooled, I know this city like the back of my three fingers.}
{204}{}{I could use wisdom of a Phoenix expert. Can you answer a few questions?}
{205}{}{You look like a loser to me. I don't want anything to do with you. Bye.}
{206}{}{Hey, looks like you got some caps. Share a little change and you'll gain grateful, loyal friends in this city.}
{207}{}{Goodbye, Lloyd.}
{208}{}{See you, Lloyd.}
{209}{}{Keep talking, I'm not in a hurry.}

{210}{}{Share a cap, you won't regret it.}
{211}{}{Hey, it's my favorite customer. How can I help this time?}
{212}{}{Maybe some other time.}

{213}{}{Phew, that was some earthquake! And those rumors about the cultists makin' a nuke? Not a lie. They're crazy. Now the whole town hates 'em, and I'm down a gig. Damn...}
{214}{}{They got what they deserved, Lloyd.}
{215}{}{Yeah.}

{220}{}{Here's a cap.}
{221}{}{Here's a cap. A newbie needs advice.}
{222}{}{Here's a cap. What do you got for me this time?}
{223}{}{Here's a cap. Let's hear some interesting rumors.}
{224}{}{[Next]}
{225}{}{Thanks, boss.}
{1225}{}{Thanks, boss lady.}
{226}{}{Thanks, boss. But old Lloyd's outta tips for now.}
{1226}{}{Thanks, boss lady. But old Lloyd's outta tips for now.}
{227}{}{No worries, I get it. I'm just as broke as you. See ya.}
{228}{}{Uh, yeah, bye.}
{229}{}{Nothin' today. Bye.}

{230}{}{Ah, rumors. That's what I live for.}
{231}{}{(looks around) W-well...}
{232}{}{Lloyd sees it all from the streets. That's for sure.}
{233}{}{You know, I hear a lot.}
{234}{}{Fresh news? Heard a bit.}
{235}{}{Yeah. Got a tip for you.}
{236}{}{Hmm... (scratches dirty stubble)}
{237}{}{You know, folks say all kinds of things...}
{238}{}{(humming) Oh, cap, cap-py cap...}
{239}{}{Much obliged.}

{240}{}{So?}
{241}{}{Keep going.}
{242}{}{Talk.}
{243}{}{[Listen]}
{244}{}{[Next]}
{245}{}{What do you have?}

{250}{}{Hey there. How do you like my new threads? Bought 'em with your caps, so thanks. Sometimes I think I can get outta this hole and start fresh. But who am I kidding...}
{251}{}{Not all is lost, Lloyd. Can't fall any lower.}
{252}{}{Guys like you got no future. Deal with it.}
{253}{}{Listen, I'm makin' so much now I can afford this little joy. With this suit, all doors are open. And it's thanks to you.}
{254}{}{Listen, I'm makin' so much now I can afford this little joy. With this suit, I'm ready to move into a deluxe. Shame it's already taken.}
{255}{}{Happy for you, Lloyd.}
{256}{}{Can't believe it. You're just lucky, that's all.}

#Vault 27
{260}{}{You know anything about Vault 27?}
{261}{}{Not much. For 10 caps, I'll tell you what I know.}
{262}{}{Then forget it.}
{263}{}{Here's 10 caps. Spill it.}
{264}{}{Heard different legends about that vault. Some say Phoenix's bigwigs set up a secret lab there. Others say it's haunted by ghosts since the war. Maybe it doesn't even exist.}
{265}{}{Sorry to hear that.}
{266}{}{If you're hunting for that legend, start with old Bob. Lives in the east slums, knows the Phoenix ruins well.}
{267}{}{Thanks, you've been a great help.}
{268}{}{You're no use. Maybe this Bob knows something.}

{270}{}{This city's huge. But I need to find a relative.}
{271}{}{Yeah, finding someone in a big city ain't easy. Plus, not everyone wants to be found. But there's a way. Five caps for the info.}
{272}{}{Here's 5 caps. What's the deal?}
{273}{}{Maybe later.}
{274}{}{There's a hiring agency nearby. For caps, they'll find anyone, even dig El Diablo out of the ground.}
{275}{}{Thanks, friend, you really helped me.}
{276}{}{You charged five caps for that? What a rip-off.}
{277}{}{I know a bunch of Miguels. One's even a woman. But if your relative's from afar, they might've changed their name. Finding 'em won't be easy. Try asking the Merc Guild, they also track people.}

{280}{}{What do you know about the attack on the monks?}
{281}{}{That info ain't cheap. 20 caps.}
{282}{}{That's fair. Here, talk.}
{283}{}{No, I'll find a cheaper source.}
{284}{}{Sorry, boss, but I don't sell such dangerous info. Try someone at the market.}
{1284}{}{Sorry, boss lady, but I don't sell such dangerous info. Try someone at the market.}
{285}{}{Got it.}

#Tips and Rumours
{300}{}{For years now, caps have been the currency here. Like dollars before the Big War, backed by the Fire Cathedral. Still, many don't trust it.}
{301}{}{Speaking of caps. Here's another one. What about pre-war dollars?}
{302}{}{That's tricky. Usually, no one uses 'em, but the casino buys up all the old currency. If you find a bill, take it to the cashier, maybe you'll get a couple caps.}
{303}{}{Ever been to the Atomic Rush Casino? Worth a visit, spend a few caps and test your luck. But don't be fooled. No matter what, the house always wins.}
{304}{}{Who runs the place? Maybe I can work there.}
{305}{}{Doubt the casino hires street folks. It's like a family there. And the head, Don Diego, is picky about staff. Wanna work for him? Gotta earn trust from his crew or have a good city rep.}
{306}{}{Be careful in the east slums. The Orris gang runs it, best to avoid 'em.}
{307}{}{Here's another cap. Tell me about that gang.}
{308}{}{Orris leads the Red Cardinals, runs the slums with them. But he's not as bad as his guys. If he points a gun at you, try talking.}
{309}{}{The power plant hiked prices and gave Aaron an ultimatum. Dunno who'll win, but the city's in for a rough ride.}
{310}{}{I'll give another cap if you tell me about that area.}
{311}{}{Around the power plant's a moat of toxic waste, traps, and barbed wire. I also know there's a sewer tunnel leading straight to the power plant, likely trapped too.}
{312}{}{Somethin's happenin' at the Cathedral of Fire. More caravans head there, and Aaron's gettin' bolder, pressurin' the townsfolk.}
{313}{}{Here's another cap. What do you know about this Aaron?}
{314}{}{Not much. Mixed rumors, but he's clearly a powerful guy obsessed with his ideas. Some say he's hooked on pills he can't live without.}
{315}{}{Lately, more bodies are found in the sewer. Used to be just squatters down there, but now it's deadly.}
{316}{}{Here's another cap. Tell me about these squatters.}
{317}{}{Weird folks living in the sewers. They dislike the surface, only come up to trade rat carcasses. If you talk to 'em, just give 'em something useful, they'll start talking.}
{318}{}{A drifter told legends 'bout a vault full of food and workin' tech. Those who believed him and went lookin' disappeared without a trace.}
{319}{}{Here's another cap if you can tell me how to find this drifter.}
{320}{}{He's just gone. If you're into Phoenix outskirts, talk to old Bob in the east slums. He's got experience digging through the ruins.}
{321}{}{The mail coach runs to Flagstaff regularly. That new colony's growing fast, thanks to the Cathedral of Fire.}
{322}{}{Heard there was a brawl in San Brahmin. Also heard fire worshippers are involved. Nobody knows for sure what's up.}
{323}{}{Rumors from Casa Grande ain't lying - the city's torn by power struggles. One mayor replaces another with every sunrise. If you're there, be ready for trouble.}
{324}{}{Lots of rumors 'bout Tinsmiths in the south. Caravans go there, but few trade with those mysterious people.}
{325}{}{As caravans headed south, raiders gathered along the routes. Highwaymen, they call 'em. They rob and kill travelers.}
{326}{}{Here's another cap. How can I stay safe on the road?}
{327}{}{Two options to avoid highwaymen. First - go around through the scorching desert. Second - join a well-guarded caravan.}
