{100}{}{You see a rebel.}
{101}{}{You see a man in a balaclava, focused on checking his gear.}
{102}{}{You see a man in a balaclava, standing with conviction, ready to defend his beliefs.}
{103}{}{You see a man in a balaclava, looking prepped and ready for battle.}
{104}{}{You see a man in a balaclava. When he notices you, he clenches his fists.}

{110}{}{Hmm...}
{111}{}{Even here at headquarters, we're not safe.}
{112}{}{We're going to win this.}
{113}{}{Damn fanatics.}
{114}{}{Those fanatics are going to get what's coming to them.}
{115}{}{I don't like what they're up to.}
{116}{}{When we take over, Phoenix is going to change.}
{117}{}{It's time for us to step out of the shadows.}
{118}{}{I think I got a fungus from living down here.}
{119}{}{For now, this is the best spot for our headquarters.}

