{100}{}{You see a prisoner in front of you.}
{101}{}{You see one of the Red Cardinals.}
{102}{}{*Ugh*}
{103}{}{...Sons of bitches...}

{110}{}{Listen, help me get outta here. I won't forget it.}
{111}{}{Do you know Orris? Tell him I'm locked up.}
{112}{}{The mercenaries won't let me walk. Tell Orris they're keeping me locked up.}

{115}{}{Did Orris send you? He's not gonna like this mess.}
{116}{}{See you back at the gym. Orris isn't gonna be happy with what I've got to tell him.}
{117}{}{Someone must've set us up.}
