{100}{}{You see Orris.}
{101}{}{You see the leader of the Red Cardinals, a man exuding authority amidst the ruins.}
{102}{}{I need this armor back. Hand it over.}
{103}{}{...Damn, this gear is hotter than a radscorpion nest...}
{104}{}{I don't deal with cultists anymore.}

# Acquaintance
{200}{}{[Murphy] Well, look at this. We've got a rat in our midst. You know where you are, idiot? Hey Orris, let me have some fun with him...}
{1200}{}{[Murphy] Well, look at this. We've got a rat in our midst. You know where you are, fool? Hey Orris, let me have some fun with her...}
{201}{}{[More]}
{202}{}{[Orris] Hold it, Murphy. No need to be so bloodthirsty with our guests. You there, what do you want?}
{203}{}{All I want is for scum like you to vanish from this town.}
{204}{}{If you're looking for trouble, punk, you've found it.}
{205}{}{Fine. Who's up first?}
{206}{}{Word is you're someone to reckon with around here. I want in.}
{207}{}{[Murphy] We have enough people already. Think we need you? Beat it, loser.}
{1207}{}{[Murphy] We have enough people already. Think we need you? Get lost, bitch.}
{208}{}{[More]}
{209}{}{Calm down, Murphy. We need a liaison, remember? You. Come here.}
{210}{}{No way. I don't deal with gangsters.}
{211}{}{And we don't deal with idiots. Guys, take care of him.}
{1211}{}{And we don't deal with dumb bitches. Guys, grab her.}
{212}{}{No, no! Please, don't...}
{213}{}{You were beaten and tossed out onto the street, pockets turned inside out.}
{214}{}{You were raped and thrown out onto the street, pockets emptied.}
{215}{}{Let's see what you can do. Who's first?}
{216}{}{What do you want from me?}
{217}{}{Honestly, I ended up here by accident. Can I just go, please.}
{218}{}{[Murphy] Just another crazy off the street. Let's empty their pockets and be done with it.}
{1218}{}{[Murphy] Just another crazy woman off the street. Let's empty her pockets and be done with it.}
{219}{}{[More]}
{220}{}{No, Murphy. We need a liaison, remember? So, you. Come here.}
{221}{}{What do you want from me?}
{222}{}{No way. I don't deal with gangsters.}
{223}{}{You again? What do you want?}
{224}{}{Hey champ, good to see you. That was a great fight. Too bad you're not in the ring anymore.}
{1224}{}{Hey champ, good to see you. That was a great fight. Too bad you're not in the ring anymore.}
{225}{}{True enough. And don't expect any more winnings.}
{226}{}{Need caps? I need muscle. Damn it, Murphy, shut up! I know who to trust. Listen up, there's a job for you.}
{227}{}{I'm listening.}
{228}{}{No way. I don't want any part in your shady dealings.}
{229}{}{Nothing major. One of my friends was supposed to meet a courier but vanished. Head to the caravan park and down into the local sewer. That's their meeting spot. Find out what happened and come back. If you pull it off, you'll get a reward.}

# First quest
{230}{}{Nothing major. I just need to find a friend. He's hasn't reported back to me. Something's gone wrong.}
{231}{}{I don't wanna get involved in gang business.}
{232}{}{You've got a whole gang. Why me?}
{233}{}{My guys stand out too much. They can't afford to draw attention in the city center.}
{234}{}{Okay, I'll do it.}
{235}{}{See, Murphy? You can negotiate with anyone.}
{236}{}{[More]}
{237}{}{Now listen up. Head to the caravan stop at the city entrance and go down into the local sewer. My guy was supposed to meet with a courier down there. Find out what happened to them and report back to me. Do the job right, and there's a reward in it for you.}
{238}{}{Alright, I'll handle it.}
{239}{}{I'm on it.}
{240}{}{If I do this, will you pay me?}
{241}{}{I promise.}
{242}{}{Remind me where the meeting was supposed to take place?}
{243}{}{Go to the caravan stop at the city entrance and go down into the local sewer. My contact was meeting a courier there. Find out what happened and return to me.}
{244}{}{Got it. I'll check it out.}
{245}{}{My guys need to lay low in the city center. They don't have a "good" reputation like you.}
{246}{}{I've had enough! I'm gonna PERSONALLY kill you.}
{247}{}{Nerves getting to you, huh?}
{248}{}{Easy now...}

{250}{}{Did you find out what happened to my guy?}
{1250}{}{Did you find out what happened to my guy?}
{251}{}{No. Not yet.}
{252}{}{Your friend and the courier were ambushed by Bruce's mercenaries.}
{253}{}{What the... Murphy, did you hear that? This is bad. He knew too much. If they break him, we're screwed. We need to move, and fast.}
{254}{}{What's going on?}
{255}{}{Listen, you're not from around here, are you? Here's how it works - this city's all about survival of the fittest. We stay alive by making sure no one gets the drop on us. If you wanna make it in Phoenix, you stick with the right people.}
{256}{}{And by "right people", you mean you, right?}
{257}{}{Damn straight. Now, here's the deal. I need my guy out of the mercs' jail - or silenced for good. You get me? It's too risky for us to go near the casino, but you? You can handle it. Do the job, and I'll pay you 200 caps.}
{258}{}{I'll see what I can do.}
{259}{}{I don't think I can handle it. I gotta go.}

{260}{}{Any news?}
{261}{}{None yet. Your guy is still in prison.}
{262}{}{Damn it, if he talks, you're in trouble too. Got that?}
{263}{}{Message received...}
{264}{}{Don't threaten me.}
{265}{}{I'm done with this crap. Time to hand your whole gang over to the mercs. Let's go, you bastard.}
{266}{}{Your guy's dead. It wasn't easy, but I got the job done.}
{267}{}{Your guy's free. It wasn't easy, but I got the job done.}
{268}{}{You did good. Lucky to have you on my side. Here's your caps and a stimpak. Take it easy while I clean up this mess.}
{1268}{}{You did good. Lucky to have you on my side. Here's your caps and a stimpak. Take it easy while I clean up this mess.}
{269}{}{Alright, I'll check back later.}

{270}{}{So did you sort that whole mess out with Bruce's mercenaries and that courier? Were you guys set up or what?}
{271}{}{Yeah, some fucker set us up. Only the cultists from the Cathedral of Fire could pull this off. Seems they decided to ditch us after using us for their schemes. But with the Cathedral blown to hell, they've got bigger problems now.}
{272}{}{So you're off the hook?}
{273}{}{It's time to stake our claim on the empty turf before anyone else does. Oh, and by the way, I don't need you anymore. But I remember those who were useful. Talk to the pusher in the slums. We have a special arrangement with him.}
{1273}{}{It's time to stake our claim on the empty turf before anyone else does. Oh, and by the way, I don't need you anymore. But I remember those who were useful. Talk to the pusher in the slums. We have a special arrangement with him.}
{274}{}{Got it. I'll keep that in mind. Later, Orris.}
{275}{}{Yeah, some fucker set us up. Only cultists from the Cathedral of Fire could pull this off. Looks like they decided to dump us after using us for their dirty work. But how they found out about our secret deal, I can't say.}
{276}{}{Could someone have tipped them off?}
{277}{}{One of ours? Hard to swallow. To the cultists, we're just another gang of thugs.}
{278}{}{[More]}
{279}{}{Listen, I need someone inside the Cathedral. Find out who sold us out, and there's good money in it for you. Deal?}
{280}{}{I'll root out the rat in your gang.}
{281}{}{Infiltrate the Cathedral? I'm not cut out for this.}
{282}{}{Did you figure out who set us up?}
{1282}{}{Did you figure out who set us up?}
{283}{}{It was Murphy. He's Aaron's mole.}
{284}{}{Murphy? No way. He's my best guy... But if I think about it... He did know more about my plans than anyone else.}
{285}{}{It's definitely Murphy. I overheard him on the radio talking with a Cathedral operative. Aaron's trying to take over your gang by putting his own guy in charge.}
{286}{}{Aaron's plans are about to go up in flames. I'll deal with Murphy. As for you, you've earned your reward. Don't want to lose a useful asset like you. Here's your caps. Also, have a chat with the pusher in the slums, we've got a special deal with him.}
{287}{}{Later, Orris.}
{288}{}{Murphy's no longer your problem. Later, Orris.}
{289}{}{I think your crew was set up by the cultists. But with the Cathedral in ruins, we may never know the truth.}
{290}{}{What's the deal with the fire worshippers?}
{291}{}{Those cultists see us as just criminals, they don't acknowledge our control over the slums. But when they need something, they're quick to negotiate.}
{292}{}{You mentioned you were running errands for them.}
{293}{}{They paid us to sabotage the nuclear plant. We blew up the cooling system, but then those damn cultists decided they didn't need us anymore. They double-crossed us.}
{294}{}{I see.}
{295}{}{But how do I go about this?}
{296}{}{I don't know. But those monks likely have everything documented in some sort of dossier.}
{297}{}{I keep wondering - how can I find this rat in the Cathedral?}
{298}{}{I guess I'll keep trying.}
{299}{}{Yeah... I don't know if I can pull this off.}

# Dialogue outside the quest
{300}{}{What do you want?}
{301}{}{What's up, drifter?}
{302}{}{Just passing through. Gotta go now.}
{303}{}{Man, you're ugly. What do you want?}
{1303}{}{Lady, you're hideous. What do you want?}
{304}{}{}

{310}{}{Are your guys the ones who snagged the letters from the Sonora Express courier?}
{311}{}{I have no clue what you're talking about. Ask my crew. If someone did, we'll deal with it.}
{312}{}{I'll do that. Bye.}
{313}{}{Don't worry, I'll track down whoever's responsible.}

{320}{}{Word on the street is you took out some of my guys in the slums. Now you've got the guts to walk in here? I'll give you one chance to explain why I shouldn't put you down right now.}
{1320}{}{Word on the street is you took out some of my guys in the slums. Now you've got the guts to walk in here? I'll give you one chance to explain why I shouldn't put you down right now.}
{321}{}{It was their own damn fault.}
{322}{}{My turf, my rules. People need to see that my power is something to fear. Guys, take out this trash...}
{1322}{}{My turf, my rules. People need to see that my power is something to fear. Guys, take out this trash...}
{323}{}{Whoa, not the face...}
{324}{}{You and your whole gang can go to hell.}
{325}{}{It was their own fault. Consider it a personal matter between me and them.}
{326}{}{Their own fault, you say? Well, keep it to yourself. People need to know I'm not someone to mess with.}
{327}{}{Fine. Nothing to do with you.}
{328}{}{You've got the wrong person. It wasn't me.}
{1328}{}{You've got the wrong person. It wasn't me.}
{329}{}{You're lying. Guys, take out this trash...}
{330}{}{Whoa, not the face...}
{331}{}{To hell with you.}
{332}{}{They must've mistaken me for someone else. I mean, look at me. How could I take on your guys?}
{333}{}{Something about this doesn't sit right. I'll let it slide for now, but if you're lying, there'll be hell to pay. People need to know I'm not someone to mess with.}
{334}{}{Of course...}
{335}{}{Your guys proved you're just a bunch of pussies. Someone ought to put you down.}

{340}{}{Were you the ones who attacked the monks?}
{341}{}{No, wasn't us. I give you my word.}
{342}{}{If it wasn't you, then who?}
{343}{}{Word on the street is there's another gang. They're trying to take down Aaron and turn people against the Church of the Holy Fire. But they're too slick to show their faces.}
{344}{}{You're not exactly on good terms with them, huh?}
{345}{}{Can't stand their sneaky tactics. We do things straight up. If you're gonna rob someone, you do it looking 'em in the eye.}
{346}{}{Got it. I'll pass that along to Aaron.}

{350}{}{They say you're the one who took out Gonzales. Why the hell didn't you settle things with him? Did it really have to come to this?}
{1350}{}{They say you're the one who offed Gonzales. I know he had issues, but why the hell did it have to come to that?}
{351}{}{People like him don't belong in a healthy society.}
{352}{}{He got what was coming to him. And you will too.}
{353}{}{No one talks to me like that. NO ONE.}
{354}{}{First time for everything. So, are you all bark and no bite?}
{355}{}{The Gonzales thing just ticked me off. Let's go I guess.}
{356}{}{I thought gangsters like you didn't care about other people's lives.}
{357}{}{Gonzales was useful to us. He supplied drugs and meds. Where are we gonna get them now, huh?}
{358}{}{You know, it's GOOD that scum like you lost your dealer.}
{359}{}{He deserved to die.}
{360}{}{If you weren't a woman, I'd hang you from a lamppost in the slums. Get lost before I change my mind.}
{361}{}{Alright...}
{362}{}{That was my business with him.}
{363}{}{It's my business now. Because of you, we lost a great dealer. You'll have to pay for it. Boys...}
{364}{}{Typical gang behavior...}
{365}{}{That was between me and him. How was I supposed to know Gonzales was dealing with you?}
{366}{}{In that case, you *owe* me. Don't think you're gettin' off easy.}
{367}{}{Got it. You can count on me.}
{368}{}{Come on, gimme a break, it was an accident.}
{369}{}{Not good enough. Blood for blood is the law of the streets. Strip if you want this over quickly. Boys...}
{370}{}{No, don't...}
{371}{}{He got what he deserved. It's too late to change that now. But, maybe I can make it up to you?}
{372}{}{You owe me. Bring me ten stimpaks, and MAYBE I'll let it slide.}
{373}{}{Alright.}
{374}{}{Don't push your luck. It had nothing to do with you.}
{375}{}{Here's 10 stimpaks. Are we square now?}
{376}{}{Yes. We're square.}
{377}{}{Good.}
{378}{}{I'll make it up, just don't kill me!}
{379}{}{}

{380}{}{I'm looking into the sabotage at the nuclear plant. Did you have a hand in it?}
{381}{}{What are you implying? You trying to test my patience?}
{382}{}{No way, man. Just asking.}
{383}{}{Come on, man. The sewers practically lead straight from here to the nuclear plant.}
{384}{}{Tell the nuclear guys my gang had nothing to do with this. Now scram, you piece of crap.}
{385}{}{Alright...}
{386}{}{Level with me, Orris. Man to man. Were you and the Red Cardinals, involved in this?}
{387}{}{Come on... after what we've been through together, you can trust me. Were you involved?}
{388}{}{We're just scraping by. Caps aren't easy to come by.}
{389}{}{What do you mean? Did someone pay you to sabotage it?}
{390}{}{Cultists, motherfucker. They had a ghoul, Ralph, on the inside at the plant who helped with the sabotage. He opened the door, then my guys just slipped into the basement and blew the pipes. Simple as that. But remember, you didn't hear it from me.}
{391}{}{Alright, Orris. No problem.}
{392}{}{You've said enough. Now say goodbye to life, you fool.}
{393}{}{You're running your mouth too much today. You're lucky I'm not your enemy.}
