{110}{}{Equipment is malfunctioning.}
{111}{}{You have managed to disable the radio transmitter. The Fire Worshippers are left without radio contact.}

# Dialogue
{200}{}{Enter command:}
{201}{}{End session}
{202}{}{Back}
{203}{}{The radio transmitter is not responding.}
{204}{}{The radio station is not working because the cathedral is without power.}

{210}{}{Copy frequencies and code. This way I can eavesdrop on the Fire Worshippers' conversations on the radio.}
{211}{}{Radio frequencies copied.}
{212}{}{Examine request history. I wonder if anyone could share information to organize attacks on the monks?}
{213}{}{You find the remains of an encrypted transmission. The terminal access code belonged to Prior Matthias.}
{214}{}{Gotcha, saint?}

{220}{}{Listen to radio communications with a Red Cardinal agent.}
{221}{}{"...I have information for Aaron. The Red Cardinals have begun to act."}
{222}{}{[More]}
{223}{}{"Please clarify the information, sir. Every little detail is important to us."}
{224}{}{[More]}
{225}{}{"Orris sent a man to negotiate a contract for the supply of weapons. He is going to strengthen his position in the slums. I already spoke about this, but you didn't listen to me."}
{226}{}{[More]}
{227}{}{"Where will the deal take place?"}
{228}{}{[More]}
{229}{}{"In the sewer near the main city gate. They'll probably get a fake courier, but that doesn't matter. We have to stop the deal by any means necessary if we don't want civil war in the slums."}
{230}{}{[More]}
{231}{}{"Accepted. We are sending an agent. Be careful, Murphy. Orris must not even suspect that you're working for us. End of communication."}
{232}{}{What? Murphy's an agent of the Cathedral? What a surprise...}
{233}{}{What? Are you kidding me? First Ralph, and now Murphy. Treacherous scum everywhere around here.}

{250}{}{Listen to radio conversations about sabotage at the nuclear power plant.}
{251}{}{"...Report. How is the operation going?"}
{252}{}{[More]}
{253}{}{"Thank Atom, everything went well. The Cardinals fulfilled their part of the agreement flawlessly. They entered the underground level of the power plant and blew up the cooling system where they were told. There's no danger to the city."}
{254}{}{[More]}
{255}{}{"Now it's up to Ralph and your diplomats. Don't miss the opportunity, it sounds like they've found somebody to help fix the cooling system. I don't think he'll succeed, but there's no point in delaying."}
{256}{}{[More]}
{257}{}{"Acknowledged. Keep us posted and may the Fire be with you."}
{258}{}{What? Ralph sold himself to the church? Well well...}
{259}{}{What? Are you kidding me? First Murphy, and now Ralph. Treacherous scum everywhere around here.}
