{100}{}{You see a cadet before you, presently assigned to kitchen duty.}
{101}{}{You see a cadet stationed in the kitchen, hustling to fulfill his tasks.}
{102}{}{Sorry, your name's not on the list for field rations. No can do.}

{200}{}{Hold up... what's a civilian doing here?}
{201}{}{Just keeping an eye on things, you know?}
{202}{}{This area's off-limits to civilians. Move along.}
{203}{}{Make me, tough guy.}
{204}{}{Sure thing, I'm not looking for trouble.}
{205}{}{No worries, I have clearance.}
{206}{}{Not your concern, but I'm cleared to be here. Relax.}

{210}{}{I'm on kitchen duty today. But we don't serve outsiders.}
{211}{}{Fair enough. I'll take off then. Goodbye.}
{212}{}{I'm handling kitchen duties today. But sorry, you're not on the list for rations.}

{220}{}{Who's your commanding officer, cadet?}
{221}{}{Captain Agatha, why do you ask?}
{222}{}{What're your thoughts on her drills?}
{223}{}{Exhausting, truth be told. But the skills she drills into us will be gold out in the wasteland. Only gripe is we're still barred from the heavy weaponry. Been itching to lay hands on them since day one. And even when we earn our stripes, we're still rationed on ammo. A real bummer.}
{224}{}{You'll get your shot eventually. No need to fret.}
{225}{}{Things aren't quite how you imagined they'd be huh?}
{226}{}{Got it, just wanted to chat. Take care.}
{227}{}{Is she a good Captain?}
{228}{}{Absolutely. She looks after her cadets like family. Grateful she's the one shaping our unit.}
{229}{}{You lucked out with her. Later.}

{230}{}{So, the Quartermaster found a weapon missing after your drill, huh?}
{231}{}{But... we returned it.}
{232}{}{Returned it and then swiped it back on the sly, right? Or forged a signature on the log? Come on, which was it?}
{233}{}{Hmm, hard to argue with that. Dismissed, cadet.}
{234}{}{Er... Uh... Look, I warned 'em it was a bad idea.}
{235}{}{Go on, spill the beans.}
{236}{}{So, you're owning up to it, huh?}
{237}{}{We handed the weapon back after the drill, but then borrowed it back with a few rounds. Figured we'd hone our shooting skills a bit. What kind of ranger can't shoot, right?}
{238}{}{You hoped nobody would notice, huh?}
{239}{}{We planned to return it, honest. But our target practice drew radscorpions, had to bolt, and left the gun in the desert. Tried retrieving it, but the Quartermaster began a stock check before we could slip it back in.}
{240}{}{Not my place to judge, even if I don't quite follow. But others might.}
{241}{}{That's a creative excuse. Curious to see what the higher-ups make of it.}
{242}{}{Others won't be thrilled I'm sharing this, but someone's gotta. You're new here. Maybe we can make a deal?}
{243}{}{Alright, let's hear it.}
{244}{}{You get the gun, I'll toss you what's left of the bullets. Then I'll return the gun to the warehouse without a peep to save our hides. It's under a big cactus near the farm. Sound good?}
{245}{}{Not a bad offer. I'll think on it.}
{246}{}{I'm not helping petty thieves. Later, cadet.}
{247}{}{Your secret's safe with me.}
{248}{}{Uh... Look, I warned 'em it was a bad idea. They didn't listen.}
{249}{}{Refresh my memory, where's the gun again?}

{250}{}{You found the gun! Thanks, saved us a world of hurt. We'll tread more carefully from now on. And here's the ammo I promised. }
{251}{}{Take care.}
{252}{}{Did you really have to kiss the quartermaster's ass? Now every cadet knows better than to mess with you.}  
{253}{}{Sorry, I didn't have a choice.}  
{254}{}{You screwed up yourselves. Don't blame anyone else for it.}
{255}{}{Is this the gun we were gabbing about?}
