{100}{}{You see an elderly man.}
{101}{}{You see a gaunt man with calloused hands. His skin is blackened from constant work under the sun.}

#Responses after dialogue
{110}{}{Guess that's enough reminiscing.}
{111}{}{I gotta get back to the farm.}
{112}{}{Thanks for listening to an old man's rambling.}
{113}{}{The dead can wait, but the crops won't.}
{114}{}{Hope you'll forgive me for gettin' all sentimental.}

#Dialogue
{200}{}{(You see an old man, standing thoughtfully in front of a grave)}
{201}{}{[Next]}
{210}{}{Eh? What do you want from me?}
{211}{}{Don't mind me.}
{212}{}{Got it.}
{213}{}{.}
{220}{}{Who are you, old man?}
{221}{}{Old man? Hah, I'm barely forty... But I look like I've been here since the world began, don't I? I'm a farmer. Got a patch of land 'bout two miles from here.}
{222}{}{So you're not with the Rangers?}
{223}{}{Don't be ridiculous. What kind of Ranger would I be at my age and with these dirty hands? My job's to tend the farm, not chase down raiders.}
{224}{}{I passed a farm on my way here.}
{225}{}{There are a few farms and ranches around here. The Rangers watch over us, but they take their cut of the crops... Sometimes they leave us just scraps to live on... But things are getting better. The land's slowly recovering from the Big Fallout.}
{226}{}{The Fallout?}
{227}{}{The General once told me over a cup of tea. When the nukes dropped a hundred years ago, these lands were covered in radioactive clouds, clouds that rained fallout. The clouds came from the west, east, and south, dependin' on the wind. It was bad everywhere back then. They say the land was barren for generations. Only the cacti could keep their life cycle goin' with their deep roots. And only now is the land startin' to come back.}
{230}{}{What are you doing here?}
{231}{}{What does an old man do at a graveyard? Obviously, I'm here to remember the old days. This is my son's grave. The inscription on the cross is nearly gone, but I still have enough sense to remember his name and where he's buried.}
{232}{}{Tell me how he died.}
{233}{}{Young folks are impatient. Workin' the fields tires 'em out. But the land only gives its bounty to those who work hard for years. Same with my Jacob. He left for the Rangers to avoid farm work. The first skirmish with raiders during a patrol took his life.}
{234}{}{Do you blame the Rangers for that?}
{235}{}{I push away those thoughts. The Rangers do a noble thing - they bring order to the wasteland. Yep, people die in the process. You can't please everyone. Help one, and you hurt another. That's the true face of justice.}
{240}{}{Whose graves are these?}
{241}{}{The Rangers bury their own by an old tradition - they bury 'em in the ground. They put a bullet in the grave, usually a revolver round. If there ain't a revolver, any bullet will do. If there ain't even that, they use a casing or a spent round. This is their way of sayin' that even in death, you shouldn't lose your spirit.}
