{100}{}{You see a bandit.}
{101}{}{You see a figure who's almost, but not quite, a Ranger.}

{110}{}{Come closer if you're feeling brave.}
{111}{}{Got no fear in ya?}
{112}{}{You best fear us.}
{113}{}{Just so we're clear - this here's OUR territory.}
{114}{}{Looks like today's my lucky day. Don't gotta go huntin' for prey.}
{115}{}{Let's see what goodies you're carryin'.}
{116}{}{*Cracks his knuckles with a smirk*}
{117}{}{Lookin' to stir up trouble, huh?}
{118}{}{Might wanna pray our boss is feelin' merciful today.}
{119}{}{What brings you trespassin' on our turf?}
