{200}{}{Enter command:}
{201}{}{End session}
{202}{}{Back}

{210}{}{Checking station status.}
{211}{}{Hydraulic unit 1 is active. Hydraulic unit 2 is active. Hydraulic unit 3 is stopped. Locks are lowered: 1,2,3,5. Locks raised: 4.}
{212}{}{Lower sluice 4. It'll be fun when the water floods the dam structure.}
{213}{}{Attention! Full dam shutdown mode is selected. This will change the hydrological regime of the reservoir. Do you confirm the command?}
{214}{}{I confirm the command.}
{215}{}{Airlock 4 is down. Attention! All airlocks are in the lowered position.}
{216}{}{It's time for me to get out of here...}
{217}{}{What? No, no, no need to lower the floodgates! Cancel command.}
