{100}{}{You see a scribe.}
{101}{}{You see an ordinary scribe of the Brotherhood of Steel.}

{210}{}{What are you doing here? Who authorized your presence on board?}
{211}{}{Don't distract me; I'm conducting important research.}
{212}{}{Welcome to the Brotherhood. Now, find something useful to do.}
{213}{}{Interested in talking about science?}
{214}{}{Is your mind ready to delve into the mysteries of quantum physics?}
{215}{}{Do you embrace the teachings of our revered Isaac Newton, who took a blow from an apple, symbolizing our ignorance, our misunderstandings, and our deepest fears?}
