{100}{}{You see a servant.}
{101}{}{You see a gaunt Mexican man, clad in a striped shirt and collar, clutching a mop with calloused hands.}

{110}{}{Of course, sir!}
{111}{}{Right away, sir!}
{112}{}{Am I in your way, sir?}
{113}{}{Apologies, sir.}
{114}{}{As you wish, senor.}

{1110}{}{Of course, senora!}
{1111}{}{Right away, senora!}
{1112}{}{Am I in your way, senora?}
{1113}{}{Apologies, senora.}
{1114}{}{As you wish, senora.}

{200}{}{How can I serve, senor... Oh, you're not with the Brotherhood. Then best we don't speak, the paladins frown upon it.}
{1200}{}{How can I serve, senora... Oh, you're not with the Brotherhood. Then best we don't speak, the paladins frown upon it.}
{201}{}{Why's that?}
{202}{}{They're always sniffing out conspiracies. And if they suspect you, it's inspections and public floggings. It's strict here. They drowned someone just last week for stealing food from the supreme paladin. I don't want to end up like him.}
{203}{}{I see. Well, take care.}

{210}{}{(glances around nervously) Look, we could get in trouble talking like this.}
{211}{}{I see.}
{212}{}{Tell me a little more about this ship and the Brotherhood.}
{213}{}{You're not with the Brotherhood. Answering your questions could get me in trouble. And what's in it for me, huh? Talking only stirs up trouble.}
{214}{}{Alright then.}
{215}{}{Keep your voice down, someone might be listening.}
{216}{}{Best not anger the paladins. Goodbye.}
{217}{}{You don't understand the trouble you could get from me. Now, speak!}
{218}{}{Get outta here or I'll call the paladins!}
{219}{}{Damn it...}

{220}{}{Who are you? You're not a member of the Brotherhood, right?}
{221}{}{No, sir. See the collar? I'm a prisoner. Here's my number.}
{1221}{}{No, senora. See the collar? I'm a prisoner. Here's my number.}
{222}{}{I see. I have more questions.}
{223}{}{Prisoner? Why are they holding you prisoner?}
{224}{}{I just took a few ears of corn from the plantation... Maybe some fruit too... Actually, a whole bag. But I needed to eat! Now I work on the ship until my sentence is up.}
{225}{}{Are there other prisoners like you here serving time?}
{226}{}{Only a few of us are kept on the ship. The rest are scattered -- working on plantations, digging in ruins, laboring in a cement factories, building houses, or hauling cargo across the wasteland. I got lucky, if you can call it that.}
{227}{}{So what do you do around here?}
{228}{}{I scrub this cursed deck four times a day! Or I haul boxes. The Order's always getting and sending things.}
{229}{}{Who else is doing time here besides you?}
{230}{}{Can you leave this place?}
{231}{}{If I go too far from the ship, the collar will explode. It's a scribe invention. They don't go easy on the locals here. Besides, they feed me here. In the wasteland, I'd be scavenging for food again. Tough choice, you know.}
{232}{}{Listen. You either spill everything you know, or you'll "accidentally" go overboard.}
{233}{}{What do you want from me? Don't you know where you are?}
{234}{}{I need information.}

{240}{}{What do you know about the Brotherhood of Steel?}
{241}{}{Not much. They keep quiet about themselves. This is just an outpost; their main base is far to the west. These are the toughest guys in all of Sonora. Even the Tinsmiths don't compare.}
{242}{}{Got it. Seems like the Brotherhood is no joke. Let's talk about something else.}
{243}{}{Who's in charge around here?}
{244}{}{General Dixon. You'll find him in his cabin or the wardroom.}
{245}{}{Alright. Enough about the Brotherhood.}

{250}{}{Do you know every corner of this ship?}
{251}{}{No, there are places even I can't go. Especially the lower holds and storage areas.}
{252}{}{Okay, no problem.}
{253}{}{What's in the lower holds?}
{254}{}{Torpedo room. They say it's full of explosives. There's also a reactor and rats as big as dogs.}
{255}{}{Wow, that's something to check out.}
{256}{}{Who has the keys to all the doors?}
{257}{}{Most people have limited access. Only the Supreme Paladin has keys to everything.}
{258}{}{Hmm. Looks like the general doesn't trust even his own men completely.}
