{100}{}{You see a guard.}
{101}{}{You see a caravan guard. He rests after a grueling journey.}

{110}{}{Great.}
{111}{}{Gimme a break.}
{112}{}{Wanna join our caravan?}
{113}{}{The road between Phoenix and Two-Sun is chaos.}
{114}{}{Dust storms are worse than raiders.}
{115}{}{We have a risky job.}
{116}{}{Talk to the boss; I'm just here to guard the cargo.}
{117}{}{Steer clear of the Tinsmiths if you know what's good for you.}
{118}{}{Here's a tip: avoid the Tinsmith's doc.}
{119}{}{I should head back to Phoenix.}
{120}{}{Tinsmiths don't like strangers and don't chit-chat much.}
{121}{}{Those Tinsmiths creep me out -- they're like machines.}
