{100}{}{You see Gerardo.}
{101}{}{You see one of Villa's enslaved peasants.}

# First dialogue
{200}{}{?! And you're here?! I thought the raiders didn't get you...}
{201}{}{No, Gerardo, they missed me. I'm here to get you out of this mess.}
{202}{}{Eh, amigo, your words are comforting, but believe me - there's no escape. The very ground here reeks of death! We'll perish, amigo, and no one will be left to mourn us.}
{1202}{}{Eh, amiga, your words are comforting, but believe me - there's no escape. The very ground here reeks of death! We'll perish, amiga, and no one will be left to mourn us.}
{203}{}{Where's my padre?}
{204}{}{He should be in the old hangar in the center of the Forbidden Zone by now. All the survivors are gathering there. Head north, you can't miss it.}
{205}{}{Alright. See you around.}
{206}{}{What about you?}
{207}{}{Padre said to stay here and send others to the hangar. Don't worry, these containers are keeping me pretty safe.}
{208}{}{Got it. Stay safe, Gerardo.}

{210}{}{Thank heavens you're back!}
{1210}{}{Thank heavens you're back!}
{211}{}{Stay here.}
{212}{}{The force field's down, and the robots won't bother us. Time to head back to the Villa.}
{213}{}{You actually did it? Truly, you're the leader the Villa needs! Though something's changed in you, amigo... Alright, I'll see you back home! If we make it, that is.}
{1213}{}{You actually did it? Truly, you're the leader the Villa needs! Though something's changed in you, amiga... Alright, I'll see you back home! If we make it, that is.}
{214}{}{Stay safe.}
{215}{}{What's next?}

{220}{}{Come with me, I need backup in the fight.}
{221}{}{What are you saying, amigo! You're leading me to certain death! We're no match for those robots with our gear. It's better to wait for someone to open the force field.}
{1221}{}{What are you saying, amiga! You're leading me to certain death! We're no match for those robots with our gear. It's better to wait for someone to open the force field.}
{222}{}{This isn't like you, Gerardo. You were always the brave one in our village.}
{223}{}{I... I'm only alive because of your padre. The Villa and this place are worlds apart. I'm not cut out for this. Sorry. Even if I make it back, I... I'll never be the same.}
{224}{}{Gerardo, now's not the time for despair. Get up, your family needs you!}
{225}{}{Alright, amigo... But I'm not stepping into that cursed bunker! I'll get you to the entrance, but that's it for me.}
{1225}{}{Alright, amiga... But I'm not stepping into that cursed bunker! I'll get you to the entrance, but that's it for me.}
{226}{}{Better than nothing.}
{227}{}{No... I'm needed here. Andres is counting on me.}
{228}{}{Alright.}
{229}{}{We'll split up. Stay here until I get back.}
{230}{}{As you say, amigo...}
{1230}{}{As you say, amiga...}
{231}{}{It's a deal.}
