{100}{}{You see Second-of-Three.}
{101}{}{You see one of the Tinsmiths, meticulously cleaning his laser pistol.}

# Dialogue with Second-of-Three
{200}{}{(You observe the Tinsmith, who continues cleaning his laser pistol, completely ignoring you.)}
{201}{}{How long have you been at this?}
{202}{}{(He raises his head, his gaze cold and calculated.) Laser technology has been my primary function for as long as my biomatrix has retained data.}
{203}{}{So, the Tinsmiths prefer to focus on a single specialty?}
{204}{}{It is the most efficient protocol to guarantee maximum operational output.}
{205}{}{What happens if a specialist is lost?}
{206}{}{Each of us has redundant units. If I'm deactivated, another steps in.}
{207}{}{Got it.}
{208}{}{Alright, I'll leave you to it.}
{209}{}{Better not disturb him...}

{210}{}{What do you want, wasteland man?}
{211}{}{What do you need?}
{212}{}{Nothing. Goodbye.}

{220}{}{I want to learn the art of laser technology.}
{221}{}{We don't distribute our data to just anyone. You must earn our trust first.}
{222}{}{Give me some time to think.}
{223}{}{How about a trade?}
{224}{}{Possibly. I'm low on electronic components, which are hard to come by in this region. Deliver 5 units, and I might reconsider.}
{225}{}{Even Master Hard trusts me with certain tasks.}
{226}{}{Impressive. Such trust is not given lightly.}
{227}{}{Many here trust me.}
{228}{}{Perhaps. But "many" does not imply consensus. However, a valuable gift might sway my decision. Bring me a couple of electronic components, and I'll consider it.}
{229}{}{Here are 2 electronic parts.}
{230}{}{Here are 5 electronic parts.}
{231}{}{We could trade our skills.}
{232}{}{That's...acceptable.}
{233}{}{Unacceptable. We have nothing to gain from wastelanders.}

{240}{}{Very well. Now we can transact business.}
{241}{}{So, how about a brief introduction?}
{242}{}{Do you grasp the fundamentals of quantum mechanics? If so, let us proceed...}
{243}{}{[Continue]}
{244}{}{The Tinsmith turned out to be a demanding teacher, but you learned a great deal from him.}
