{100}{}{You see Chris's brother.}
{101}{}{The boy you see is Chris's brother.}
{102}{}{How do you control this thing? It's a little scary...}

{200}{}{Hello.}
{201}{}{Bye.}
{202}{}{What are you doing?}
{203}{}{Helping rebuild a house that got damaged in the raid.}
{204}{}{Notice anything unusual?}
{205}{}{Only these strange things that the raiders dropped. (shows spent bullets and a couple of intact 10mm rounds)}
{206}{}{I think I'll take those. You shouldn't be touching outsiders' things.}
{207}{}{No, nothing.}

{210}{}{Hey, uh, I'm just hanging out...}
{211}{}{More like you're bringing food to someone.}
{212}{}{Come on, kid... Alright, I'll believe you this time.}
{213}{}{This is my food!}
{214}{}{[Track the child and find out where he goes]}
{215}{}{Don't worry, I believe you.}
{216}{}{Do you know where your brother Chris is?}
{217}{}{Nope. Don't know.}
{218}{}{Okay. I'll keep looking.}
