{100}{}{You see the library terminal.}
{101}{}{This terminal could grant access to a digital library, but it's currently non-functional.}

{110}{}{This terminal could provide access to a digital library, but it's not operational now.}
{111}{}{You can access the electronic library from this terminal.}
{112}{}{You have successfully restored the library terminal.}
{113}{}{The library terminal is offline. You need to restore the power supply to activate it.}
