{100}{}{You see a rogue scavenger.}
{101}{}{You see a man dressed in specialized gear for exploring ruins.}
{102}{}{You a scavenger too? Then stick to areas we're not planning to hit. Just a friendly warning.}
{103}{}{Fight! If you're not with us, get lost! Fight!}
{104}{}{Alright, alright, we got carried away. Sorry about that.}
{105}{}{Serves them right! We're the real power around here!}

{200}{}{Fight! If you're not with us, get lost! Fight!}
{201}{}{Yeah! And you're gonna get it now!}
{202}{}{Stop fighting! Just settle down! Stop causing trouble with these ghouls.}
{203}{}{Oh yeah? And what are you gonna do about it, PIECE OF SHIT?}
{204}{}{I'll shoot the first one who makes a move.}
{205}{}{Pff-ha-ha-ha! Ghoul's little pet! You got guts! Shoot us! Hoo-ha-ha! Alright, guys, let's get outta here. These clowns aren't worth it.}
{206}{}{Yeah, get out of here.}
{207}{}{I'll wait until you leave.}
{208}{}{What did you say, you bastard? I'm gonna shove those words back down your throat along with your teeth!}
{209}{}{[Throw a handful of bottle caps in the air. Let them scramble for those instead of fighting.]}
