{100}{}{You see Rutger.}
{101}{}{You see the leader of the Far Go Traders.}

{200}{}{We're damn lucky you were nearby. I don't have words to express my gratitude for saving our asses. Here, take this assault rifle as a reward. Now, how can I help you?}
{1200}{}{We're damn lucky you were nearby. I don't have words to express my gratitude for saving our asses. Here, take this asssault rifle as a reward. Now, how can I help you?}
{201}{}{Let's just talk for a start.}
{202}{}{It looks like you were carrying some goods. Can I take a look?}
{203}{}{This cargo was meant for the ghouls, but they weren't interested... }
{204}{}{[Barter]}
{205}{}{Yeah, I was hoping to buy a few things off the ghouls, but they're either not selling, asking too much, or just don't have what I need. I'll pay you if you can scavenge what I need in the ruins.}
{206}{}{Alright. What do you need?}
{207}{}{No, I'm not interested in scavenging for junk.}
{208}{}{What else do you need?}
{209}{}{That's all. Bye, Rutger.}
{210}{}{I want to ask something else.}
{211}{}{I need to take a look at your goods again.}
{212}{}{I'm looking for these things: 1) water chip, 2) circuit board, 3) diagnostic board, 4) fuel controller, 5) vertibird schematics.}
{213}{}{If I run across any of them, I'll bring them straight to you. Bye.}
{214}{}{About those pre-war things you're looking for.}
{215}{}{Did you manage to find any of them? Or anything useful?}
{216}{}{Not yet. If I find them, I'll bring them. Bye.}
{217}{}{Why do you need all these old artifacts?}
{218}{}{My boss Butch in the Hub will be terribly upset if I come back empty-handed. The Hub needs all sorts of things. And not just the Hub. All of California survives on ancient tech. And over time, there's less and less of it.}
{219}{}{Got it.}
{220}{}{Where can I find a water chip?}
{221}{}{That tech was used in Vault-Tec vaults. I know there was at least one of them in San Diego. But I don't have the exact location.}
{222}{}{Where can I find a circuit board?}
{223}{}{Not just any circuit board... one from an old printing press. The Hub folks want to print their own money, and for that, they need to start up a printing press. And that's the one part they lack.}
{224}{}{Where can I find a diagnostic board?}
{225}{}{It's a part from an autodoc. Things like that used to be found in big hospitals.}
{226}{}{Where can I find a fuel controller?}
{227}{}{Funny thing. The trader across the way says he already got that part from another camp. But he can't find it. The old geezer probably lost it among all his junk.}
{228}{}{Where can I find vertibird schematics?}
{229}{}{You know about the naval base on Coronado Island? And the military airfield? They were torn to shreds by nuclear blasts, so I hear. But the ghouls also say there was a factory that serviced military equipment. The schematics might have survived there. And by the way, I have no idea what a "vertibird" is.}
{230}{}{I found the }
{231}{}{ you're looking for.}
{232}{}{Great job! Here's your 400 caps. This'll be going back to the Hub.}
{233}{}{Thanks for the caps.}
{234}{}{You have found everything the Far Go Traders were looking for. Excellent job!}
{235}{}{So, how can I help you?}
{236}{}{Goodbye.}
{237}{}{[Continue the conversation]}
{238}{}{So, how can I help you... You, but not your mutant friend.}
{239}{}{It seems we're no longer welcome in Dayglow. We'll be leaving soon.}

{240}{}{Where's your caravan from?}
{241}{}{We're from the Hub. That's where our main office is.}
{242}{}{Tell me about the Hub.}
{243}{}{It's the largest city in California. The center of bottle cap currency and trade. The main supplier of clean water. Most people and companies are there. But it also has the most problems.}
{244}{}{I see.}
{245}{}{In Phoenix, they also use bottle caps for trading.}
{246}{}{Hubbucks are in Phoenix? Hah! The bottle cap currency has been working in the Hub for many years. Someone must have taken the idea east. But who could have crossed the Toxic Divide between Arizona and California? Interesting!}
{247}{}{Let's go back...}
{248}{}{Which company's office?}
{249}{}{Which caravan company?}
{250}{}{We're the Far Go Traders trading company from the Hub. We transport goods from one settlement to another.}
{251}{}{Tell me about the Hub.}
{252}{}{Tough job, huh?}
{253}{}{Yeah, we went through hell with super mutant raids and all kinds of scum for a while. Lost a lot of folks and brahmin until one person put an end to it. The Vault Dweller - that's what everyone called him.}
{254}{}{Where did these super mutants come from?}
{255}{}{Those sons of bitches raided caravans and kidnapped people to turn them into freaks like themselves. Nobody in the Hub even knew about them. Then one person uncovered their secret. Everyone was horrified.}
{256}{}{Go on.}
{257}{}{I know this story. You don't need to continue.}
{258}{}{Then that mysterious Vault Dweller and the Brotherhood of Steel guys stirred up their nest. Killed most of them. But part of the green army survived and scattered across the Wasteland.}
{259}{}{Thanks for the story, Rutger. I didn't know about any of this.}
{1259}{}{Thanks for the story, Rutger. I didn't know about any of this.}
{260}{}{Thanks for the story, Rutger. I didn't hear about any of this in Inferno.}
{261}{}{Super mutants... What was the deal with them?}
{262}{}{Which office were you talking about?}
{263}{}{Some settlements had the bad luck of being right in their path. That's why folks have been fighting mutants for years. No surprise some of those green bastards ended up out here, far from any human towns.}
{264}{}{What happened to the Vault Dweller?}
{265}{}{I don't know. He seemed to vanish. Nobody has heard anything about him since.}
{266}{}{Butler promises big orders. Looks like he's struck gold.}

