{100}{}{You see Raymond, an autistic ghoul.}
{101}{}{You see one of the ghouls. He's continuously counting and sorting things.}
{102}{}{The ghoul happily takes your box and adds it to his collection.}
{103}{}{That's my box, Bern!}
{104}{}{Boxes! Boxes! Boxes!}
{105}{}{Taking the holodisk upset the ghoul greatly. No one in San Ysidro will forgive you for this.}
{106}{}{GIVE ME BACK MY BOX, BERN!}
{107}{}{You returned the holodisk to its owner. Your reputation has been restored.}
{108}{}{That's MY box, Bern!}

{110}{}{Bern! Bern! Bern!}
{111}{}{These people will be here all day, Bern!}
{112}{}{This is an unscheduled visit, Bern!}
{113}{}{This is not a weekend visit, Bern!}
{114}{}{82! 82 toothpicks!}
{115}{}{One toothpick, two toothpicks, three toothpicks...}
{116}{}{Five. Three. Five. Nine. Two. Six. Two.}
{117}{}{One box, two boxes, three boxes...}
{118}{}{Boxes, boxes, boxes...}
{119}{}{Give me back my boxes!}
