{200}{}{Hey, it Private Gomer! And he with a normie?}
{201}{}{Gomer follows my orders. You should follow them too.}
{202}{}{Grr! Gomer is traitor! Death to normies!}
{203}{}{Wait...}
{204}{}{Gomer and I are friends. Surprised, greenie?}
{205}{}{Gomer friends with normie? Ho-ho-ho, I don't believe it! You his slave. Gomer, you surprise me. Leave the slave aside and help us get people out of that place.}
{206}{}{Did you call me a slave, you green-skinned freak!?}
{207}{}{You run your mouth too much, slave. I will tear it out!}
{208}{}{You can die trying...}
{209}{}{Gomer, explain to them that I'm not a slave and that they should leave those people alone.}
{210}{}{Gomer with normies now? That bad! Gomer disappointed us all again. Gomer is traitor! Death to normies!}
{211}{}{Wait...}
{212}{}{Live, normie. You lucky today.}
{213}{}{The Master watches me from heavens. I will not disgrace His name!}
{214}{}{So you're letting me go, huh? Thanks.}
