{100}{}{You see Peck.}
{101}{}{You see a ghoul with a twisted spine. His head is covered with small glowing mushrooms.}
{102}{}{No problem, sir. I'll leave once I'm done cleaning.}

{120}{}{I feel like a million bucks.}
{121}{}{I'm Peck. Peckster. Wanna sleep with me?}
{122}{}{Do you know how many caps I have? I have no caps. And I'm happy!}
{123}{}{I used to have no money. Now nobody has money.}
{124}{}{I live like a TV star.}
{125}{}{This is the best place in the world. Woohoo!}
{126}{}{Time for Peck to take his meds. *Nom-nom* Yum...}
{127}{}{Cops! It's the cops! Oh no... Just a flashback...}
{128}{}{It's all good, I'm fine... I think.}
{129}{}{Without foreigners, Dayglow isn't Dayglow.}
{130}{}{I'm not homeless. I'm free from a home!}
{131}{}{I don't do drugs. My brain makes them on its own.}
{132}{}{Holy macaroni!}

{200}{}{Whoa-whoa, bro! Don't freak out, but you're on my private property. Well... I don't mind you being here. But just so ya know, it's mine.}
{201}{}{Seriously? You live in these sewers?}
{202}{}{Yeah, I'm homeless. So what? I live well! I live in the most picturesque place in Dayglow. Don't you think?}
{203}{}{Ever thought about moving into the city with the others?}
{204}{}{Why? I'm good here. Plenty of food, no laws to follow, peace and quiet.}
{205}{}{I'm afraid to ask, what do you eat here?}
{206}{}{No wonder you're covered in mushrooms. Have you seen yourself in a mirror?}
{207}{}{All sorts of stuff grows in the valley. I have enough. Here, want some mushrooms?}
{208}{}{Sure. What do you want in return?}
{209}{}{No thanks. That's not my thing.}
{210}{}{The local climate is too humid. It wasn't like this in Necropolis. But at least I don't have to get my fix. Want some too?}
{211}{}{You'll see - you'll be back for another fix.}
{212}{}{Sure.}

{220}{}{Hey, how's it going?}
{221}{}{How's it going, bro?}
{1221}{}{How's it going, sister?}
{222}{}{What's up, kid, lost in the neighborhood?}
{1222}{}{What's up, babe, lost in the neighborhood?}
{223}{}{Goodbye.}
{224}{}{I need more of those glowing mushrooms.}

{230}{}{How do I get out of here?}
{231}{}{The nearest bridge is destroyed, bro. What a bummer, right? Head up to the mall, and from there you can get on the highway again. And you're free!}
{232}{}{Alright, I'll be going. Take care.}
{233}{}{I'll pay you 300 caps if you lead me to San Ysidro.}
{234}{}{I hear ya, I hear ya. Peck knows all the secret paths and the rough spots. Trust me - you're not getting through that valley without me.}
{235}{}{Then lead the way. Here's }
{236}{}{ caps.}

#Dialogue numbering fixed by cambragol
{237}{}{Nevermind, I'll find my own way.}
{238}{}{I need to get to the power station at Bonita Dam. How about 500 caps to lead me there?}
{239}{}{I'll give you 1500 caps if you can guide me through the safe paths to Old Town.}



