{100}{}{You see a ghoul.}
{101}{}{You see a disgusting-looking ghoul with one eye. His teeth are frozen in a perpetual snarl.}
{102}{}{Hello, stranger.}
{1102}{}{Hello, stranger.}
{103}{}{Come closer, don't be afraid. I just want to "touch" your smooth, soft skin...}
{1103}{}{Come closer, don't be afraid. I just want to "touch" your smooth, soft skin...}
{104}{}{Run, normie, run! If I catch you, I'll cook you for dinner.}
{105}{}{There's really nothing special here. Enjoy the afterlife.}
{1105}{}{There's really nothing special here. Enjoy the afterlife.}

{200}{}{Hey, you, with the ugly mug. Come here. Got any caps?}
{201}{}{I do.}
{202}{}{Then hand over 10 caps. And make it quick.}
{203}{}{Alright, here's 10 caps. All for you.}
{204}{}{Watch your mouth. We're not playing games here. Now get lost.}
{205}{}{Alright...}
{206}{}{Here's 10 caps.}
{207}{}{Good boy... I see you're also rich. Hand over another 10 caps.}
{208}{}{Here's another 10 caps. Are you satisfied now?}
{209}{}{Here's all I have. Are you satisfied now?}
{210}{}{Quite. I love suckers like you. Although I don't get the thrill like in the old days. But why am I talking to you? Get lost.}
{211}{}{Go to hell.}
{212}{}{Don't forget, you're nobody in this town. Better disappear.}
{213}{}{With great pleasure.}
{214}{}{Alright, here's all I have, but it's less than 10.}
{215}{}{It'll do. Now get out of here while I'm in a good mood.}
{216}{}{No.}
{217}{}{I don't believe you. Show me what's in your bag.}
{218}{}{Here, take a look.}
{219}{}{Just as I thought. Only lies from smoothskins. As punishment for lying, I'm taking ALL your caps. Now get lost.}
{220}{}{Alright...}
{221}{}{You're not getting any of my caps, freak!}
{222}{}{Here, take a look.}
{223}{}{Ugh! You're useless. Get off my street.}
{224}{}{With great pleasure.}
{225}{}{Touch my stuff, and you'll lose your last fingers.}
{226}{}{[Run away from the beggar as fast as you can]}
{227}{}{[Walk past]}
{228}{}{Stop! I'm talking to you, damn normie.}
{229}{}{[Ignore]}
{230}{}{What do you want?}
{231}{}{Alright, I have caps. How much do you need?}
{232}{}{But I have no caps.}
{233}{}{Go to hell.}
{234}{}{Why should I give you any caps?}
{235}{}{It's the price you pay for me tolerating your disgusting smooth face in my beautiful city. Hand over the caps, now.}

{250}{}{Sir, my respects! First time in the city? I could show you all the sights. Only 10 caps.}
{1250}{}{Ma'am, my respects! First time in the city? I could show you all the sights. Only 10 caps.}
{251}{}{Alright, here's 10 caps.}
{252}{}{Sorry, amigo, I'm broke. Maybe another time.}
{253}{}{Mucho gracias... Oh yes, there's the monorail, and over there is the Mexican border. To the north, there's another ghoul camp. That's it. Bye...}
{254}{}{You didn't show me anything, damn scammer!}
{255}{}{That was... an enlightening tour. Uh... Thanks.}
{256}{}{Hello.}
{257}{}{Goodbye.}

