{100}{}{You see a mercenary.}
{101}{}{You see one of those rogue scavengers who are willing to take any job for money.}

{110}{}{Mr. De Santi's paying good money for your head.}
{111}{}{You shouldn't have crossed Mr. De Santi!}
{112}{}{Folks who cross De Santi don't tend to last long.}
{113}{}{Mr. De Santi is terribly displeased with you!}
{114}{}{Nothing personal. Just someone put a hit on you.}
