{100}{}{You see a paladin.}
{101}{}{You see a Brotherhood of Steel paladin.}
{102}{}{Greetings, brother.}
{1102}{}{Greetings, sister.}

{110}{}{What the hell is going on?}
{111}{}{Damn alarm!}
{112}{}{What's all this noise, damn it?}
{113}{}{Hmm, strange.}
{114}{}{Huh? A false alarm?}
{115}{}{Freaking alarm!}

{120}{}{Damn technology!}
{121}{}{Enough already with the ringing!}
{122}{}{How do I turn it off?}
{123}{}{Too bad there aren't any knights with us...}
{124}{}{How does it even work?}
{125}{}{It's easier to blow it up than to turn it off, I swear!}

{130}{}{Weird. Why did it go off?}
{131}{}{That siren won't be sounding again.}
{132}{}{Surprising that the alarm still works.}
{133}{}{Alright, I think it's definitely off now.}

{200}{}{Stop! This place is under guard. You'll have to leave. Immediately.}
{201}{}{Alright, alright, I'll leave right away.}
{202}{}{I don't have to leave, idiot!}
{203}{}{I'm also from the Brotherhood of Steel. Scribe }
{204}{}{I'm also from the Brotherhood of Steel. Knight }
{205}{}{I'm also from the Brotherhood of Steel. Paladin }
{206}{}{I'm also from the Brotherhood of Steel. Scout }
{207}{}{, Sonoran division.}
{208}{}{Glad to meet you, brother. You can stay here, under our protection.}
{1208}{}{Glad to meet you, sister. You can stay here, under our protection.}
{209}{}{Can I know what you're doing here?}
{210}{}{Just a small mission. We've captured a super mutant captain and are currently interrogating him. Once we're done, we'll kill him. No need to worry, he's under secure guard.}
{211}{}{Oh, that's great. Congratulations.}
{212}{}{Stop! Let me make this clearer - you can't be here. Leave. Right. Now.}
{213}{}{You are seriously testing my patience. This is your last warning. YOU. CAN'T. BE. HERE.}
{214}{}{Enough! Idiots like you are beyond saving. You're in for a serious beating!}
{215}{}{Oh, this is gonna hurt... you.}
{216}{}{You'll be getting the beating, braggart!}
{217}{}{I know who you have locked up. And I can tell you where the rest of his squad is.}
{218}{}{Speak up then! Any information on this will be valuable to us.}
{219}{}{They've set up a camp in Balboa Park.}
{220}{}{We don't waste time with super mutants. They're an evil that must be eradicated. Thank you for the information. We appreciate your help.}
{221}{}{You're welcome.}
{222}{}{What are you gonna do with these super mutants?}
{223}{}{We don't waste time with super mutants. They're an evil that must be eradicated. So where are they located?}
{224}{}{Eradicated? You're all fanatics! I'm not just gonna stand by while you kill whoever you want!}
{225}{}{We'll soon send a team to eliminate that mutie threat. Thank you for the information. We appreciate your help.}

{226}{}{What the...how did you... No one's breaking out on my watch!}

