{102}{}{Well, what else?}
{103}{}{I'll kill every Brotherhood of Steel scum I can find!}
{104}{}{I hate the Brotherhood! Hate them!}

{110}{}{Hey, Brotherhood mutt, drop your gun and come out!}
{111}{}{I won't touch you. Just want to talk.}
{112}{}{Say everything that's been building up.}
{113}{}{You know how many of us they've killed in Lost Hills?}
{114}{}{You took our home. You took our god.}
{115}{}{You think we can get along after this?}
{116}{}{Oh, I'm SO mad. But I be kind to you - I kill you quickly. You won't feel a thing.}
{117}{}{Agreed?}
{118}{}{Why you suffer? Why resist? I free you from this torment.}
{119}{}{God was on our side. And your side - dumb generals. Pitiful humans, how you've fallen!}

{200}{}{Hey, dead guy, be careful. There some Brotherhood of Steel fiend lurking around here. Watch out, don't get caught when they start shooting.}
{201}{}{Ah, I see. I'll scram before it gets too hot around here.}
{202}{}{You mess with the Brotherhood, you mess with me. Time to die!}
{203}{}{Hey, I just saw him run towards the piers! While you were talking to yourself, he took off.}
{204}{}{What the... Ugh, I catch him now! He won't get away!}
{205}{}{Hurry up, big guy!}
{206}{}{Ha-ha, you're such an moron! It was easier to trick you than a child! What's got you all fired up, dummy?}
{207}{}{Gomer? You're here? Hey, did you make this human, slave? Good job. I trying to kill a Brotherhood dog hiding in cafe. Help me finish him?}
{208}{}{Gomer, let's get out of here? This isn't our business.}
{209}{}{Gomer, tell this dimwit that the war is over. Stop fighting. Leave the human alone.}
{210}{}{Gomer and human are partners now? I haven't heard about that. Maybe it really time for peace? Alright, Gomer, I trust you.}
{211}{}{Alright then. Go your way.}
{212}{}{Grrr! Die, you stupid human!}
{213}{}{You first, mutie freak!}
{214}{}{Wait, let's talk this out!}
{215}{}{Hold on! There's no need for us to fight. I don't want to hurt you.}
{216}{}{I never forgive what humans did to us!}
{217}{}{It's a shame you can't just let it go...}
{218}{}{You're wasting your time...}
{219}{}{The ghouls aren't going to be happy about this. They're working hard to build a city for everyone. Humans and mutants can actually live together in the Dayglow. Don't you want to see that long-awaited peace happen too?}
{220}{}{Ghouls are dumb! One day they pay for it. Humans will betray them!}
{221}{}{Then you need to protect them. Don't let humans take advantage of the ghouls. There will always be more humans around. One battle won't solve everything.}
{222}{}{That good point. I never thought about that. Should I go to town? Offer myself as guard for the ghouls? Yeah, that's good idea! I won't let anyone harm the ghouls, no way!}
{223}{}{That's great! See? There's always a chance to work things out.}
{224}{}{I have to agree with you on that. So, shall we continue fighting, dummy?}

