{100}{}{You see Cabot, a ghoul trader.}
{101}{}{You see a local merchant.}
{102}{}{I don't serve traitors. Get out of my store.}
{103}{}{Listen, if you don't like our town, take your ass back to the wastelands, dumbass.}

{200}{}{Hey there, I'm Cabot, and this is my shop. Need anything, just let me know.}
{201}{}{Hi, Cabot. What do you sell?}
{202}{}{I get stuff from all over Dayglow. But most of it gets hauled off by caravans headin' up north.}
{203}{}{Why?}
{204}{}{Here in Old Town, we believe we should help people rebuild civilization with old stuff and knowledge... Well, that's what Butler says. Me, I'm just looking to make a profit. I'm a trader, always have been.}
{205}{}{Let's see what kind of junk you've got...}
{206}{}{I feel like taking a look at all these pre-war relics. Show me your goods...}
{207}{}{Sorry, human, but don't expect any discounts. Prices are the same for you as for the rest of the smoothskins.}
{208}{}{Alright, have it your way...}
{209}{}{For mutants and ghouls, I have special prices. They're more... let's say... reasonable. You see, we have mixed feelings about humans here.}
{210}{}{Okay, thanks, buddy.}
{211}{}{Here's the best stuff found in the ruins of the great Dayglow!}
{212}{}{Goodbye.}
{213}{}{Can I ask you a few questions?}

{220}{}{What are you looking for, friend?}
{1220}{}{What are you looking for, friend?}
{221}{}{What do you need, kiddo?}
{222}{}{What's it this time?}
{223}{}{Goodbye.}
{224}{}{I need to buy something.}

{230}{}{You still haven't found the fuel controller for Rutger?}
{231}{}{It was definitely here! I went through all the boxes, but couldn't find it.}
{232}{}{Who else might have seen it?}
{233}{}{Well, the courier Steve Morgan brought that thing. I think he went to blow his caps in the bar afterward. Haven't seen him since.}
{234}{}{I'll try to find him there. Bye.}

{240}{}{I'm looking for a ghoul named Rupert. Do you know where he is?}
{241}{}{Rupert? He arrived in Dayglow a month ago. Haven't seen him since.}
{242}{}{Alright, forget it.}
{243}{}{Who else was he talking to before he disappeared?}
{244}{}{I don't know.}
{245}{}{Where did he go?}
{246}{}{I don't know.}
{247}{}{Did he mention what he planned to do?}
{248}{}{No. Well... He did say he was tired and wanted to relax.}
{249}{}{And what did you say?}
{250}{}{Well, I told him about the "La Pensione" hotel. Haven't seen him since.}
{251}{}{The one in Little Italy? Got it, thanks.}

{260}{}{Do you know where I can get programs for Mr. Handy?}
{261}{}{Ask Phil in the library. He's got a big brain, might come up with something.}
{262}{}{Thanks.}

{270}{}{Someone told me to pick up an encrypted holodisk here.}
{271}{}{Someone, huh? You don't even know their name?}
{272}{}{Well, they didn't introduce themselves.}
{273}{}{Got it. Well, there *is* a holodisk. Hold out your Pip-Boy. Let's try to load this disk.}
{274}{}{[Continue]}
{275}{}{(You insert the holodisk and start the loading process. It turns out the recording is specifically encrypted for your Pip-Boy.)}
{276}{}{[Listen to the recording]}
{277}{}{"Sorry I couldn't meet you. I've got a lot going on. But you'll figure things out without me."}
{278}{}{[Continue]}
{279}{}{"Gustavo and Butler can't agree about the future of Dayglow. Honestly, I don't know which one of them is more right. What's important is that people don't get hurt because of their disagreement. Dayglow isn't just ruins. It's full of pre-war stuff, some of which is extremely dangerous. We can't let it fall into the wrong hands."}
{280}{}{[Continue]}
{281}{}{"Besides humans and ghouls, there's another force eyeing these resources. The Brotherhood of Steel. They've holed up in an old missile silo. Try to contact them and decide if we should let them take control here. You can find them with a walkie-talkie or a transceiver. Their frequency and the code they use is attached to this recording."}
{282}{}{[Continue]}
{283}{}{"One more thing. I've stashed some stuff in Balboa Park, in an old pipe near the monorail substation. I think you could use it more than me. Until next time."}
{284}{}{[Remove the holodisk]}
{285}{}{[Listen again]}

