{100}{}{You see a stranger.}
{101}{}{You see a man in a blue jumpsuit.}

#Cutscenes
{110}{}{   }
{111}{}{Who are you guys?}
{112}{}{None of your ghoul business. Butler will answer your questions. Now get out of here.}
{113}{}{Mercenaries, huh. As expected, Butler won't back down so easily.}
{114}{}{But it's too late. Coronado belongs to the ghouls of San Ysidro. And you have no place here.}
{115}{}{Whatever. We're just getting a lot of hot air from this scum. Throw 'em off the pier, guys!}

{122}{}{None of your ghoul business. No one's going to that island without our permission.}
{123}{}{Ah, rogue scavengers? As expected, everyone wants a piece of the treasures of Coronado.}
{124}{}{But Coronado belongs to ALL ghouls! San Ysidro has a claim too!}
{125}{}{Hah! We're just getting a bunch of hot air from this scum. Let's drive 'em outta here!}
{126}{}{Coronado belongs to the GHOULS! Get off our land, smoothskins!}

#Final Dialogue
{200}{}{Hey, hey! Are you okay? Wake up!}
{201}{}{Wha... What happened?}
{202}{}{You were knocked out by the explosion. But it looks like you're fine. I was afraid you didn't get my invitation.}
{1202}{}{You were knocked out by the explosion. But it looks like you're fine. I was afraid you didn't get my invitation.}
{203}{}{There was a fight here. Someone threw a grenade, and you were knocked out from it. But it looks like you're fine. I was afraid you didn't get my... invitation.}
{1203}{}{There was a fight here. Someone threw a grenade, and you were knocked out from it. But it looks like you're fine. I was afraid you didn't get my... invitation.}
{204}{}{You? You invited me here? Who are you?}
{205}{}{You might have heard of me... But it doesn't matter. I'm glad you managed to work things out here, for Dayglow. For everyone.}
{1205}{}{You might have heard of me... But it doesn't matter. I'm glad you managed to work things out here, for Dayglow. For everyone.}
{206}{}{You think... you think I did the right thing?}
{1206}{}{You think... you think I did the right thing?}
{207}{}{I'm not here to judge your decisions. You did what *you* thought was right.}
{1207}{}{I'm not here to judge your decisions. You did what *you* thought was right.}
{208}{}{[Listen]}
{209}{}{}

{210}{}{Of course, the ghouls will be terribly upset that the Old World treasures of Coronado, will never be theirs.}
{211}{}{They could have been very useful to this world. But they could also have fallen into the wrong hands.}
{212}{}{Who knows, maybe because of that explosion the world avoided another catastrophe. Or maybe it was exactly those things from that base that were needed to bring civilization back on track. Either way, the base is finally destroyed. And with it, the discord among the ghouls.}

{220}{}{Of course, there will be some... discord among the ghouls over the rights to the Old World treasures of Coronado.}
{221}{}{Gustavo will try to take everything for himself and use it for the development of San Ysidro. He won't share with the human settlements, which also desperately need pre-war items. Butler will try to stop him.}
{222}{}{In the end, Gustavo will be stronger, he'll lure most of the ghouls to his side. And then Dayglow will live its usual, dreary, peaceful life, closed off from the rest of the world. Just as many ghouls always wanted.}
{223}{}{Gustavo will try to take everything for himself and use it for the development of San Ysidro. He won't share with the human settlements, although they also desperately need pre-war items.}
{224}{}{Dayglow will live its usual, dreary, peaceful life, closed off from the rest of the world. Just as many ghouls always wanted.}

{230}{}{Of course, there will be some... discord among the ghouls over the rights to the Old World treasures.}
{231}{}{Butler will start active trade with the human settlements to the north. For some of them, pre-war items will be lifesaving, for others - ruinous. San Ysidro will get mere scraps, turning it into a slum.}
{232}{}{Gradually, the resources will be exhausted. But thanks to trade, Dayglow will survive and live its usual, dreary, peaceful life. As many ghouls wanted.}

{240}{}{Of course, the ghouls will be terribly upset that the Old World treasures of Coronado won't be theirs.}
{241}{}{The Brotherhood of Steel won't let anyone near this goldmine. The Brotherhood will take everything valuable and transport it to the main base.}
{242}{}{The ghouls will get the mere scraps that are left behind. Over time, people will forget about them, and Coronado. And then Dayglow will live its usual dreary life.}

{250}{}{Of course, there will be a great discord among the ghouls over the rights to the Old World treasures of Coronado.}
{251}{}{Without their leaders, it will take them a long time to find a compromise between forces and interests. It will be a period of chaos and confusion. The northern human settlements will also be drawn into this squabbling.}
{252}{}{Some pre-war items will fall into good hands, some - into bad ones. The ghouls will probably end up with the least. But they are used to that. Dayglow will become what Necropolis was before the ghouls left it. A city of the dead. Apparently, that's their fate.}

{260}{}{Well. My business here is done. Yours probably is too. It was good to see you. Adios, amigo.}
{1260}{}{Well. My business here is done. Yours probably is too. It was good to see you. Adios, amiga.}
{261}{}{Goodbye, stranger.}

