{100}{}{This is a publishing computer.}
{101}{}{This computer is connected to a printing press.}
{102}{}{Reading articles from the last century has given you new experience.}

#Dialogue
{200}{}{Access granted. Enter command:}
{201}{}{End session.}
{202}{}{Back}
{203}{}{Next}
{204}{}{Return to main menu}
{205}{}{Cancel}

{210}{}{Read headlines of recent articles.}
{211}{}{Articles for printing}
{212}{}{Business news}
{213}{}{"Mexico receives a new batch of Mr. Handy robots. These robots have proven invaluable following the recent major earthquakes."}
{214}{}{Economic news}
{215}{}{"Mexico's third economic miracle. Following the annexation, Mexico has seen a surge in American manufacturing. While the environment has worsened, the country is rapidly becoming wealthier."}
{216}{}{Industrial news}
{217}{}{"Oil in the Sea of Cortez is running out. Many oil platforms have already been shut down. The remaining platforms will operate for about ten more years, extracting the last remnants of black gold."}
{218}{}{Expert opinions}
{219}{}{"Is nuclear war looming for Mexico? We ask the experts."}
{220}{}{"It's clear that the United States will not threaten Mexico with nuclear weapons. However, Mexico has other neighbors who are eager to seize its resources and maritime territory."}
{221}{}{"Following the annexation, the United States has built numerous factories and strategic facilities in Mexico. It's evident that enemies of the US would seek to eliminate them in case of war. And this would strike not just at us, but at the Mexican people."}
{222}{}{Police chronicles}
{223}{}{"Mexico is purchasing lightweight armored equipment from the US for conducting special operations along its land borders."}
{224}{}{Crime reports}
{225}{}{"A previously banned group sympathetic to China and the Soviet Union has been eliminated in Mexico City. There are casualties among the civilian population."}
{226}{}{Events calendar}
{227}{}{"Don't miss out! This Sunday, enjoy an unforgettable performance by the legendary Mariachi Jose Solis!"}

