{100}{}{You see Stanley.}
{101}{}{You see a terribly bony ghoul in dirty, worn-out overalls. A piece of rebar sticks out of his head.}
{102}{}{Hello, pale one. You no longer look like a real ghost.}

{200}{}{Ahhhh! Don't take me, I wanna live! I wanna live!}
{201}{}{What are you talking about?}
{202}{}{What the hell are you screaming about?!}
{203}{}{Oh, dear, you're a human?! Whew, I thought you were a ghost. Why are you scaring me like that?}
{204}{}{I have the same question for you. Walking around here, all alone in the dark, glowing eyes...}
{205}{}{Sorry, pale one, but I got so scared! You know, it's so lonely at these stations. There used to be rumors about a ghost train that took people's souls to hell. Now it's silly to believe in that, of course. We're already in hell.}
{206}{}{Sorry, it was an accident. I didn't think I'd bump into anyone here.}
{1206}{}{Sorry, it was an accident. I didn't think I'd bump into anyone here.}
{207}{}{Once upon a time, these stations were crowded with people. And now it's utterly deserted. Maybe the ghost train already took everyone to hell. Don't believe me? Well, look around-we're already in hell.}
{208}{}{So, what are you doing here?}
{209}{}{I was asked to prepare the Blue Line for operation. I used to work in the metro, so I know some things. But not everything.}
{210}{}{What's needed to get it operating?}
{211}{}{First off, we're completely out of power. The only real source nearby is the Bonita Dam power station, which has been heavily guarded since the Great War. We'll need to get it up and running and then redirect its power to the monorail substation.}
{212}{}{And second?}
{213}{}{Second, we need to get the monorail line repaired. Once we power up the Mister Handy robots, they'll handle the heavy lifting - dismantling some old lines to repair this one. But we'll need to fix the automated controls at the monorail depot ourselves, and I can't do that alone; I need someone who knows electronics. The control unit's in the main room, and it's a beast to move. Think you can help me out? Maybe we could get a tech from San Ysidro if needed.}
{214}{}{Alright. Then I could use the monorail too.}
{215}{}{I'll do what I can to make your lives easier.}
{216}{}{Great! Help me get it running, and I'll split the fee the mayors promised with you.}
{217}{}{Alright. I'll look into those two issues.}
{218}{}{Before we start, I have a few questions for you.}

{220}{}{What do you say, pale one?}
{221}{}{What are you staring at, pale one?}
{1221}{}{What are you staring at, pale face?}
{222}{}{Hey, it's my pale-skinned brother! How are you?}
{1222}{}{Hey, it's my pale-skinned sister! Are you alright?}
{223}{}{Bye. Gotta go.}

{230}{}{What is a monorail?}
{231}{}{You really don't know? That's a shame! There used to be elevated trains running along these tracks - it was something to see. Help fix the line, and you'll see it for yourself.}
{232}{}{Got it.}
{233}{}{What needs to be done to start the monorail?}
{234}{}{First, power needs to be routed from the Bonita Dam power station to the Blue Line substation. Then repair the electronics in the control room. If you lack the skills, take the equipment to the technician in San Ysidro.}
{235}{}{Alright.}
{236}{}{Doesn't that thing in your head bother you?}
{237}{}{Oh, this thing? You mean the rebar? Yeah, it's been lodged in my head for about a hundred years now. No big deal, I'm used to it. Probably best not to try pulling it out, though.}
{238}{}{Alright.}
{239}{}{It's a miracle! Honestly, I didn't think it would work. It's so incredible, I can hardly believe it. You're restoring my faith in people. Maybe there's still hope for us yet.}
{240}{}{Uh, sure, no problem.}
{241}{}{I'm didn't just do it for you.}
{242}{}{I guess I should share the fee with you - 1000 caps. And thank you... friend.}
{1242}{}{I guess I should share the fee with you - 1000 caps. And thank you... friend.}
{243}{}{You're always welcome... friend.}
{244}{}{I guess I should share the fee with you - 1000 caps. And thank you... partner.}
{245}{}{You're always welcome... partner.}
{246}{}{I guess I should share the fee with you - 500 caps. And thank you... partner.}
{247}{}{Is that all? You're no longer my "partner".}

