{110}{}{This equipment is not working.}
{111}{}{This equipment is operating at full capacity.}
{112}{}{You replaced the broken parts. The radio station is operational again.}
{113}{}{This pathetic junk won't be able to replace the damaged parts.}
{114}{}{This radio station is not working.}
{115}{}{You have no idea how many problems this radio station will save us from. Thank you.}
{116}{}{Gomer is bigger than you and has fewer brains. Gomer could never fix this.}
