{110}{}{This is an operational radio station. It's working thanks to you.}
{111}{}{This equipment is running at full capacity.}
{112}{}{This radio station is used by the ghouls to communicate with other areas of Dayglow.}
{113}{}{This equipment does not require any repairs.}
{114}{}{You send the border service command code to order all San Ysidro border robots to stand down.}
##You transmit data about the new transponder to the naval base. The automation grants landing permission.
{115}{}{You transmit the security code, setting the transponder's ID as friendly for Coronado naval base defenses.}

{116}{}{No power.}
