{100}{}{You see Alejo.}
{101}{}{You see a half-naked man, eyes wild with madness, brandishing a machete menacingly.}

{110}{}{Die, you wasteland vermin!}
{111}{}{Damn rattlers!}
{112}{}{I've been taken! Kidnapped, I tell you!}
{113}{}{Alex! Times! Washington!}
{114}{}{You'll answer to me directly!}
{115}{}{This is my message to those bastards.}
{116}{}{I wandered here, scavenging for food, troubling no one.}
{117}{}{They're watching me, always watching!}
{118}{}{Which Mexican scum stole my cart?}
{119}{}{Revolt and ruin! Revolt and ruin!}
{120}{}{I'll rain grenades upon you!}
{121}{}{Damn! Shit!}
{122}{}{Monkeys, everywhere! There's one right there!}
{123}{}{Damn motherfuckers!}
{124}{}{Ooooh!}
{125}{}{I love animals, truly I do.}
