{100}{}{You see a guard in front of you.}
{101}{}{You see one of the caravan guards.}

{110}{}{I hope we don't run into trouble along the way.}
{111}{}{It'll be great to get those caps once we finish this journey.}
{112}{}{Hope the bar's still open when we get there.}
{113}{}{It'd be nice to finally have some real food.}
{114}{}{This journey's been brutal.}
{115}{}{Brahmin are too slow when they're loaded up.}
