{110}{}{How about a joke, Mr. McClellan?}
{111}{}{Good morning, Mrs. McClellan.}
{112}{}{It was a scumbag like you that killed Mrs. McClellan!}
{113}{}{Get away from the McClellan residence!}
{114}{}{Save yourself, Mr. McClellan! Head to the basement and take the kids!}
{115}{}{I shall not betray my masters!}
{116}{}{Nothing interrupts the master's dog's morning walk.}
{117}{}{I see a thief! Master, stay inside and lock the door!}
{118}{}{You should've never taken my master's dog!}
{119}{}{Oh God, that flash... Mr. McClellan? What's happening to you? Mr. McClellan!}
{120}{}{I cannot harm the McClellan family. But you're not part of the family.}
{121}{}{I was built to obey only the McClellan family's orders.}
{122}{}{I must ensure my safety, as I am the property of the McClellan family.}
{123}{}{Looks like it's gonna be a light drizzle today.}
{124}{}{Your blood will make excellent lubricant, plebeian!}
{125}{}{Activating Deep Cleaning protocol.}
{126}{}{Shall I add this primate's skull to your collection, Mr. McClellan?}
{127}{}{Shall we serve the intruder with garlic or mustard sauce, Mrs. McClellan?}
{128}{}{You're going to have to pay a fine.}
