#For containers
{100}{}{Hey, put that back, now!}
{101}{}{Touch that again and you'll regret it.}
{102}{}{Hands off my stuff!}
{103}{}{Whatever you're looking for, it ain't here. Understand?}
{104}{}{Touch it again and you'll find trouble.}
{105}{}{Keep your mitts off it.}
{106}{}{Don't tell me you're "just looking for your keys."}
{107}{}{Move it, get out of there!}
{108}{}{It's bad manners to take what's not yours.}

{109}{robots}{*Show your pass*}

#For doors
{110}{}{You can't go in there.}
{111}{}{Hey, you! What do you think you're doing?}
{112}{}{Don't tell me you're "just looking for your keys."}
{113}{}{Get out of there, now!}
{114}{}{Just try it and you'll regret it.}
{115}{}{Don't even think about it.}
{116}{}{It's locked for a reason.}
{117}{}{Get away from there!}
{118}{}{Leave it alone or I'll take extreme measures on your ass.}

{119}{robots}{*Show your pass*}

#Replicas during an attack on GG
{120}{people}{You were warned!}
{121}{robots}{Intruder detected!}

{122}{}{The owner doesn't appreciate you touching his things.}
{123}{}{The owner has no intention of letting you in.}
{124}{}{A robot is guarding this warehouse.}
{125}{}{A robot is guarding this place.}

{126}{}{ doesn't allow you to mess with these things.}
{127}{}{ doesn't allow you to touch these things.}
{128}{}{ has no intention of letting you in.}
{129}{}{ has no intention of letting you through.}

{130}{}{No toques la puerta.}
{131}{}{«Don't touch the door.»}







