#Detailed description
{101}{}{You see a regular slot machine.}
{102}{}{You see an unusual machine.}
{103}{}{You see a slot machine.}
{104}{}{You see a sparkling slot machine.}
{105}{}{You see a shiny slot machine.}

#Interaction, use of skills and items
{110}{}{Hacking this machine won't do any good.}
{111}{}{This fancy machine makes noises and spits out chips. Never seen that at the Villa.}
{112}{}{This machine doesn't need repairs.}
{113}{}{Trying this during a fight would be a nightmare.}
{114}{}{This machine requires a special playing chip.}
{115}{}{This machine is out of chips. You'll have to come back later.}
{116}{}{You have no idea how to work this thing.}
{117}{}{Insert a playing chip to play.}
{118}{}{Your bet: }
{119}{}{.}
{120}{}{The machine can't accept any more bets; it's out of chips.}
{121}{}{Maximum bet reached (20 chips).}
{122}{}{These chips won't work in this machine.}
{123}{}{}
{124}{}{}

#Phrases above the GG when you lose and have no chips in your pocket
{125}{}{Hey, this is a rip-off!}
{126}{}{That was my last chip...}
{127}{}{How am I gonna win back my chips?}
{128}{}{Fuck! This machine ate my last chip!}
{129}{}{Damn it! I'm out of chips!}

#Replicas above the machine
{130}{}{*Ding*}
{131}{}{*Ding*}
{132}{}{*Bz-z-z*}
{133}{}{*Trrrrr*}
{134}{}{*Play with me*}
{135}{}{*Hey, hi*}
{136}{}{*You'll love me*}
{137}{}{*Clink*}
{138}{}{*Ding ding*}
{139}{}{*Ding ding ding ding*}
{140}{}{}
{141}{}{}
{142}{}{}
{143}{}{}
{144}{}{}
{145}{}{}
{146}{}{}
{147}{}{}
{148}{}{}
{149}{}{}

#Cues during the game
{150}{}{You lose.}
{151}{}{You've lost. Suck it up.}
{152}{}{Your bet is gone.}
{153}{}{The machine seems to be mocking you. You lose.}
{154}{}{You've lost. Today is not your day.}

{155}{}{You win }
{156}{}{ chips.}
{157}{}{ chips.}
{158}{}{ chips. Nice game!}
{159}{}{JACKPOT!}

#Names of reels
{160}{}{URANIUM}
{161}{}{PLUTONIUM}
{162}{}{RADIUM}
{163}{}{POLONIUM}
{164}{}{RADON}
{165}{}{BERYLLIUM}
{166}{}{MERCURY}
{167}{}{TELLURIUM}
{168}{}{THORIUM}
{169}{}{LEAD}

{170}{}{ - }
{171}{}{ATOM}
{172}{}{BOMB}
{173}{}{CLOUD}
{174}{}{COWBOY}
{175}{}{SEVEN}
{176}{}{CANNON}
{177}{}{SHORE}
{178}{}{}
{179}{}{}
