{110}{}{This skill is not applicable here.}
{111}{}{Digging a hole during combat? Not gonna happen.}
{112}{}{With that strength, you can't even lift a shovel.}
{114}{}{It'll take a tool to dig through this.}
{115}{}{Someone hastily buried a dog here. They were clearly in a rush.}
{116}{}{This hole can't be filled that easily.}
{117}{}{While digging, the grave suddenly collapses, dragging you into the underground voids.}
{118}{}{What the fuck...}
{119}{}{Yikes!}
{120}{}{The hole is pretty deep.}
