{100}{}{One-two, test #1.}
{101}{}{One-two, test #2.}
{102}{}{One-two, test #3.}

{110}{}{This cellar has been completely looted.}
{111}{}{The town hall was ransacked and looted. There are signs of struggle everywhere.}
{112}{}{This is the only remaining building - a silent witness of ancient times. And it seems someone has been here recently.}
{113}{}{The checkpoint building was completely looted by slaves.}
{114}{}{Judging by the numerous tracks, the highwaymen stayed here for several days waiting for a caravan.}
{115}{}{This shack seems long abandoned, but you notice a few drops of blood on the floor.}
{116}{}{This shack seems long abandoned.}
{117}{}{An old, ransacked drinking establishment. Someone set up a camp here.}
{118}{}{An old, half-destroyed house. It's uninhabitable.}
{119}{}{The building is filled with numerous tracks. Apparently, the residents spent a lot of time here.}
{120}{}{The community leader's hut. The owner maintained order even amidst all this ruin.}
{121}{}{Entering the club, you attract a lot of attention. Visitors eye you suspiciously and soon return to their business.}
{122}{}{This stuffy barrack reeks of rust and rubber.}
{123}{}{This library exudes peace and tranquility.}
{124}{}{The Lord of Phoenix's private office stands out with its elegance and luxury.}
{125}{}{This dark, stuffy room is a mess.}
{126}{}{This is your luxury suite. Finally, you can rest after all these exhausting travels.}
{127}{}{This is a luxury suite. It looks impressive against the backdrop of the surrounding despair.}
{128}{}{The road ahead is blocked by rubble from destroyed buildings.}
{129}{}{Phew, this family definitely had something to hide.}
{130}{}{This was a former pumping station. The locals took everything that could be used in everyday life.}
{131}{}{This place stands out with its terrible stench.}
{132}{}{The caravanners set up a barrack in this old building. It's stuffy, noisy, and reeks of sweat.}
{133}{}{This bar has long been abandoned and looted. It looks like there was a shootout here a long time ago.}
{134}{}{This building has long been abandoned. It seems it used to be a bathhouse, but now there's not a drop of water left.}
{135}{}{This large house stands out with its rich decor and relative cleanliness.}
{136}{}{The road ahead is blocked by impenetrable ruins. You'll have to find a detour.}
{137}{}{Ahead, a tall building with lit windows is visible. A whole crowd of raving reavers is wandering in front of it.}
{138}{}{The sign at the entrance reads: "No open carry of weapons in the casino".}
{139}{}{This supermarket was destroyed by a blast wave. Many of its visitors died on the spot.}
{140}{}{This store was badly damaged by the explosion. Its walls are about to collapse.}
{141}{}{Further southeast lie particularly devastated neighborhoods. It seems that was the epicenter of the nuclear blast. Nothing survived.}
{142}{}{This administrative building was recently abandoned. Workers hurriedly left their belongings behind.}
{143}{}{This place reeks of sterile cleanliness. You are not used to such a smell. Or rather - its absence.}
{144}{}{This former hotel has long been abandoned. It looks like someone took everything valuable, including the furniture.}
{145}{}{The restaurant is dim and dirty. Be careful not to trip over anything.}
{146}{}{The basement reeks of urine and old rags.}
{147}{}{It seems this ancient sewer system has been dug up by someone.}
{148}{}{These containers are rusted through, leaking oil into the sea. The fumes could ignite with just a single spark.}
{149}{}{Around the lighthouse, you can see the traces of bare human feet.}
{150}{}{Further north, the road is lost in the sands.}
{151}{}{This is the road you took from Sonora. To return, wait at the gathering point.}
{152}{}{The road is blocked by collapsed buildings.}
{153}{}{The bridge is destroyed. But going down is an option, if you're smart about it.}
