{100}{}{You see a villager.}
{101}{}{You see a fisherman with dark skin.}

{110}{}{Hello.}
{111}{}{Get out of here.}
{112}{}{You're not welcome here.}
{113}{}{You know, you should take a leaky boat and sail far out to sea.}

{120}{}{Hello.}
{121}{}{Nice to see a new face.}
{122}{}{Nice to meet you.}
{123}{}{The catch has been poor lately.}
{124}{}{If you have any brains, don't swim too far out to sea.}
{125}{}{There's a real monster in the sea!}
{126}{}{I think there's going to be a storm.}
{127}{}{You shouldn't walk along the shore at night.}
{128}{}{}
{129}{}{}

{130}{}{My respects.}
{131}{}{You're always welcome here.}
{132}{}{Thank you for everything you did for us.}
{133}{}{Great catch.}
{134}{}{Want to take a boat ride?}
{135}{}{There's a real monster in the sea!}
{136}{}{There might be a storm.}
{137}{}{You shouldn't walk along the shore at night.}
{138}{}{}
{139}{}{}

{140}{}{Are you sure you don't know what happened in Puerto?}
{141}{}{Puerto has been destroyed! Without them it's gonna get harsh around here.}
{142}{}{The Brotherhood of Steel has left us. And with them, safety.}
{143}{}{Damn, if the Brotherhood had explosives like that, imagine how much useful stuff they could have given us.}
{144}{}{We, of course, we'll survive without the Brotherhood. But they supplied us with everything we needed.}

{150}{}{Oh, look at it burn!}
{151}{}{It's amazing that the sea can actually BURN.}
{152}{}{The whole sky is filled with smoke. I guess a lot of that 'oil' spilled into the sea.}
{153}{}{Thanks for the help with the oil. We'll have to tolerate a bit of smoke, though...}

{159}{}{Hey, are you the one who cured all the people who were poisoned? Thank you.}

{160}{}{Someone took Shorty Ruiz down. I won't miss him.}
{161}{}{Shorty Ruiz is adios. He had it coming.}
{162}{}{I guess I won't be hearing Ruiz swearing at the fishermen in the morning anymore.}
{163}{}{I'm dying to know what kind of treasures Ruiz and that gringo found.}
{164}{}{Little Ruiz is stomping around mad, like someone beat him at cards.}
{165}{}{So, the ghost at the lighthouse is real?}
{166}{}{No way I'm going near the lighthouse ruins alone now.}
{167}{}{The Inferno demons are getting too close for comfort.}
{168}{}{Oh God, the Inferno demons are living near us now? This is a nightmare!}
{169}{}{What if the Reavers from Inferno move in here?}
