{100}{}{You see Ruiz.}
{101}{}{You see a local resident. He is wearing a bandana and a light cape.}
{102}{}{Meet me near the treasure.}
{103}{}{You better not test my patience.}
{104}{}{If I come across any more treasure maps, I'll be sure to call you.}
{105}{}{Looking for treasure? It's not here.}
{106}{}{I wouldn't even think of hiding here if I were you. The Reavers will definitely smell you.}

{200}{}{Hey, new guy! My name is Jose Rene Ruiz. What do the winds of fate bring our little town?}
{1200}{}{Hey, new girl! My name is Jose Rene Ruiz. What do the winds of fate bring our little town?}
{201}{}{I'm looking for something.}
{202}{}{Looking for someone.}
{203}{}{I see. You know, I'm looking for something too. If you help me, I'll help you.}
{204}{}{Really? And what is it?}
{205}{}{Well, an old man hid a treasure somewhere on the coast. And then he died. I don't know exactly where the treasure is. There is a map, but he tore it into four fragments and hid them somewhere.}
{206}{}{Cunning.}
{207}{}{I have one fragment. If you find the rest, bring it to me, we'll divide the treasure in half.}
{208}{}{How do I know you won't cheat me?}
{209}{}{Okay. If I find it, I'll come straight to you.}
{210}{}{How do I know that *you* won't cheat me? It's just a verbal agreement. If you don't like it, forget it and move on.}
{211}{}{I'll think about it.}
{212}{}{Whoa, what a freak! How long are you gonna be tolerated around here? Yet, maybe you'll be useful to me... Listen, new guy, my name is Jose Rene Ruiz. First, tell me why you are here?}
{1212}{}{You are one, ugly... How long are you gonna be tolerated around here? Yet, maybe you'll be useful to me... Listen, new girl, my name is Jose Rene Ruiz. First, tell me why you're here?}

{220}{}{What news?}
{221}{}{None yet.}
{222}{}{Did you find anything?}
{223}{}{Not yet.}

{224}{}{Do you have any idea where to look for these map pieces?}
{225}{}{If I did, don't you think I'd have looked already? They could be buired in a pile of shit for all I know.}
{226}{}{Okay, I'll keep looking then.}

{230}{}{Have you been to the platform?}
{231}{}{No. And there is nothing to do there. If there was a bottle cap production machine there, I would be the first to go there.}
{232}{}{Do you know where to get a battery for the boat?}
{233}{}{All the batteries have already been divvied out by the boat owners. I'm not giving mine away. Try your luck with the other owners; they usually gather at the bar.}
{234}{}{I see.}

{240}{}{I have missing map pieces.}
{241}{}{Come here!}
{242}{}{Uh, okay...}
{243}{}{To hell with that! I'll find the treasure without you.}
{244}{}{Sooo... (Takes out his fragment, connects everything together and twirls them around for a long time) Here it is...}
{245}{}{Are you sure?}
{246}{}{Absolutely! All you have to do is go and get it. Now find a shovel and head there. The treasure is buried right next to the old lighthouse on the coast north of the village.}
{247}{}{I'm already on my way!}

{250}{}{Admit it - did you kill Johnny?}
{251}{}{What the hell are you talking about?!}
{252}{}{He was strangled with your rope. How do you explain this?}
{253}{}{Ha! I sold this rope to several fishermen. And why on earth would I kill anyone? What are you, an idiot?}
{254}{}{Who did you sell it to?}
{255}{}{I even have it in my notes, look... Only Tin-Tan has bought rope lately. Hey, he's kind of like Uncle Johnny, isn't he? No wonder he had my rope.}
{256}{}{Okay. I'll talk to this guy.}
{257}{}{This is where I ask questions, idiot. Who was the last person to buy rope from you?}
