{101}{}{You see a tribal child covered in dirt.}

{200}{}{Who is this? Human? This is a man! Help, save us! Help!}
{201}{}{Didn't the elders forbid you to go to the Buried City?}
{202}{}{How did you end up here?}
{203}{}{We explore catacombs when big roar come, and cave fall in. We no find way out.}
{204}{}{Roar?}
{205}{}{Shh! Evil spirit here! He very big, very scary! We can't get out because of him. Help us! Help!}
{206}{}{Okay, let's get out of here.}
{207}{}{We'll get out of here first. And then I'll give your hide a tanning.}

{210}{}{You are bad! You are bad person! Monster should eat you!}
{211}{}{Better shut your trap...}

{220}{}{We not die, right?}
{221}{}{We die? We die?}
{222}{}{Please protect us from evil spirit!}
{223}{}{Follow me. Keep close!}
{224}{}{Stay here and don't go anywhere. I'll see what's ahead.}

{230}{}{Hurray! We are free! We are saved!}
{231}{}{You're safe now.}
{232}{}{You are our savior! Maybe Divine Brahmin himself sent you to us. Who would have thought that a stranger would save us? Your tribe is probably good. Here, take these things, we found them underground. (hands over 10mm rounds, shotgun shells, a grenade and a lighter) Glory to our savior!}
{1232}{}{You are our savior! Maybe Divine Brahmin himself sent you to us. Who would have thought that a stranger would save us? Your tribe is probably good. Here, take these things, we found them underground. (hands over 10mm rounds, shotgun shells, a grenade and a lighter) Glory to our savior!}
{233}{}{Don't wait for me, guys. Go straight to the pueblo.}
