{100}{}{You see Ranger Oscar.}
{101}{}{You see a middle-aged man with gloves and a revolver on his belt.}
{102}{}{I need your tech to drive out those damn missionaries.}
{103}{}{I'm leaving San Brahmin soon. Rangers aren't welcome here anymore. It's a damn shame.}
{104}{}{Thanks for your help. Your dedication will be remembered.}
{105}{}{We'll meet again, amigo.}
{106}{}{You'd better hope our paths don't cross again.}
{107}{}{I need to prep for battle. Meet me near the missionary camp.}

#Before receiving the quest
{200}{}{Hey.}
{201}{}{Bye.}
{202}{}{[Cheat: get out of the pueblo, ranger]}
{203}{}{[Cheat: you won]}
{204}{}{[Cheat: give a quest to eliminate missionaries]}

{210}{}{Yeah. Wait a minute. Who are you? One of the missionaries?}
{211}{}{No, just a traveler. And I'm already leaving.}
{212}{}{No, no, I'm from a village to the northwest.}
{213}{}{Village? There aren't any settlements out that way. I think you're lying...}
{214}{}{I'm telling you... It doesn't matter. Where are you from?}
{215}{}{That ain't your concern. Concern yourself with your own business.}
{216}{}{See you, stranger.}
{217}{}{So what if I am?}
{218}{}{I don't like you. Like everyone else from the east. If I find out you're a missionary spy, you'll get a bullet in the forehead.}
{219}{}{The leaders let me in.}
{220}{}{Lucky you. I wouldn't have.}
{221}{}{I'm not from the east. I'm from the northwest.}
{222}{}{See you, stranger.}
{223}{}{Why did they let you in? Aren't you a stranger too?}
{224}{}{Chief Geronimo sent me to you. How can I help?}
{225}{}{An extra pair of hands would be helpful.}
{226}{}{If I were him, I wouldn't be so quick to trust. But yeah, we could use the help.}
{227}{}{Report the situation, Ranger.}
{228}{}{Are you Ranger Oscar? General Mossman sent me. He wants a report.}
{229}{}{Strange. I don't know why he sent you and not one of the rangers... But the general knows best.}

{230}{}{I was sent to San Brahmin to restore order. The tribe is trying to defend its freedom from the Phoenix empire. The situation is tense and could escalate into full-blown war at any moment.}
{231}{}{Go on.}
{232}{}{Get to the point.}
{233}{}{A detachment of Phoenix men arrived from the east. They've set up camp near the pueblo and are trying to push the tribe out. They claim they want a trade agreement. Total bullshit.}
{234}{}{What's the problem?}
{235}{}{No empire in history has been so nice during expansion. Once the deal is done, the tribe will be disarmed, and the brahmin handed to those who obey the emperor.}
{236}{}{[Listen]}
{237}{}{Phoenix can't be trusted. They're just a bunch of adventurers and tyrants. The townsfolk don't know any better, and the tribe has its own culture and traditions. We can't let greedy city folks ruin their lives.}
{238}{}{I see. You want to push the missionaries back to the city?}
{239}{}{We can't match their numbers for an open fight. And the tribe's split, thanks to Phoenixian influence on the youth. Help me prep a team to drive out the missionaries. We need to heal the wounded and talk sense into Chief Chatto's son.}
{240}{}{Alright. I'll see what I can do.}
{241}{}{I doubt your team can handle it. I'll look for another way.}

{242}{}{Well hello, cultist. Looking for a bullet in the forehead?}
{243}{}{Wait a minute...}
{244}{}{What are you...}
{245}{}{Get the hell out of here! Don't let me catch you here again. No one invited Aaron's lapdogs.}
{246}{}{Okay... take it easy... I'm leaving.}
{247}{}{Ranger? What a surprise. Headquarters didn't warn me about your visit. Here on your own?}
{248}{}{Not exactly. Just passing through. What's going on? Need any help?}
{249}{}{Just passing through. Sorry, but I need to move on. Maybe we'll meet again.}

{250}{}{Weren't you told to get out of San Brahmin? Keep fucking around, and I'll have to use force to drive you outta here.}
{251}{}{It was a mistake. Give me a chance, I'll fix things!}
{252}{}{You have no power here. You're a stranger like me. So sit down and shut up.}
{253}{}{Bet my hat you won't try it. Feeling lucky, punk?}
{254}{}{Let's discuss the plan again. What's the next move?}

{260}{}{Leave San Brahmin immediately. Commander Crook is giving you one last chance to avoid death.}
{261}{}{Your threats don't scare me. I knew the risks. My goal is bigger than one man's life. I'm trying to save the tribe from extermination or enslavement.}
{262}{}{It's over. The elders don't want war with the missionaries.}
{263}{}{I see. The missionaries have somehow clouded the elders' minds. What a sad state of affairs for the people of San Brahmin.}
{264}{}{Most of the tribe is against you. Are you leaving, or what?}
{265}{}{Hmph. I guess I'll head back to base empty-handed. But don't think the Rangers will forget this. Phoenix can't be allowed to crush entire peoples for power and resources.}
{266}{}{Cheer up. You'll still have a chance for revenge. Maybe.}
{267}{}{Just get out of here.}
{268}{}{So are you leaving, or what?}
{269}{}{No. I'll stay and stand with the tribe during the siege. And I won't be alone. Others still stand ready to fight.}
{270}{}{As you wish. But you've been warned.}
{271}{}{Do what you want. My job's to warn.}
{272}{}{The desert teaches patience, right? Go hide in the shadows and wait for the right moment.}
{273}{}{Sometimes it's better to retreat and gather strength. Isn't this one of those times?}
{274}{}{Parker Dam's been flooded and destroyed. The Rangers can't support the fight in San Brahmin anymore.}
{275}{}{It's over. The High Chief has abandoned the Rangers.}

#After receiving the quest
{300}{}{Report. Any intel on the enemy is valuable.}
{301}{}{Nothing to report yet.}
{302}{}{Good to see you, Ranger.}
{303}{}{Good to see you, amigo.}

{310}{}{I want to ask about the Arizona Rangers.}
{311}{}{We bring Law and Order to these lands.}
{312}{}{Do the Rangers have a home base?}
{313}{}{General headquarters in the west and many outposts throughout Southern Arizona. But it'd be stupid to tell you exactly where.}
{314}{}{General headquarters in the west and many outposts throughout Southern Arizona. But you already know where they are.}
{315}{}{Where's your badge, ranger?}
{316}{}{I took it off to make things simple. When the pueblo's safe, it'll be back on my chest.}
{317}{}{Why are the Rangers getting involved in this war?}
{318}{}{We have two goals: make allies of the tribe and stop Phoenix's expansion.}
{319}{}{Don't the Ranger's laws conflict with the tribes laws?}
{320}{}{Simple rules for everyone: don't kill without reason, don't steal. As for local customs, we have to adapt.}
{321}{}{I see.}

{330}{}{The missionaries have retreated back to Phoenix.}
{331}{}{Your diplomacy is impressive. I don't know how you managed, but I'm grateful.}
{332}{}{No big deal. They turned out to be pretty gun shy.}
{333}{}{It wasn't easy. But I did my best.}
{334}{}{General Mossman was right to trust you. He knows good people. And now that this mission is finally over, I can return to base.}
{335}{}{Good luck, Oscar.}
{336}{}{The Rangers need people like you. Visit our base in Parker Dam. I'll recommend you to the general.}
{337}{}{Thanks, Ranger. When I'm in those parts, I'll drop by and pay him a visit.}

{340}{}{Chatto isn't going to support Phoenix anymore.}
{341}{}{Good news. Without Chatto causing problems, our chances increase.}
{342}{}{What else needs to be done?}
{343}{}{All that's left is to rally the warriors and head into battle. But some are wounded. It's worrying the herders. A few of them could join the fight if they're patched up.}
{344}{}{I'll see if I can patch them up.}
{345}{}{Thanks. If you can't treat them, at least get some medicine. You can probably swipe some from the missionaries.}
{346}{}{On my way.}
{347}{}{But I'm not a doctor.}
{348}{}{Then get some medicine. Steal it from the missionaries if you have to.}
{349}{}{On my way.}
{350}{}{All the wounded are back in action. We're ready.}
{351}{}{Great. Let's assemble our squad and plan. Meet me north of the missionary camp. Be ready for a tough fight.}
{352}{}{On my way.}
{353}{}{Chatto's gone. He can't interfere any more.}
{354}{}{That's not good news. Chatto was a leader among the youth and could've swayed the minds of his people. We can only hope none of his pals get in our way.}
{355}{}{No choice now. Crook is expecting your attack. Show him what you can do, Ranger!}
{356}{}{Tell Crook I accept his challenge. If he wants a fight, he'll get it.}
{357}{}{Bye.}
{358}{}{Good job. What about Chatto? Did you convince him?}
{359}{}{I haven't talked to him yet.}

#During a skirmish
{360}{}{Hmm. Looks like the missionaries didn't think we'd really fight. Their arrogance is our advantage. Let's hit 'em.}
{361}{}{Ranger Oscar, can I scout ahead? I'll be back soon.}
{362}{}{Let the battle begin!}
{363}{}{Report: the missionaries fled!}
{364}{}{Victory is ours! (The tribe's warriors rejoice) I need time to look around. Head back to the pueblo. We'll debrief there.}
{365}{}{See you later.}
{366}{}{In that case, you'll die like a dog. Whining and begging for mercy.}
{367}{}{Enough! Time's up, Ranger...}
{368}{}{Drive them back!}
{369}{}{Let's go!}
{370}{}{If Crook and his pack don't surrender right off the bat, we'll force them out.}
{371}{}{I'll tell him your demands.}
{372}{}{The battle is over. We won!}
