{100}{}{You see a ranger in front of you.}
{101}{}{You see a ranger in battle gear, carefully scanning the pueblo.}

{110}{}{So, it's thanks to you we're allied with the tribe? Well done.}
{111}{}{You're doing a damn fine job, partner.}
{112}{}{The general sent us to guard the chief.}
{113}{}{You're on our side, right?}
{114}{}{The high chief is waiting for you. Come on in.}
{115}{}{You may pass.}
{116}{}{*Salutes you*}

{120}{}{You shouldn't have come here.}

