{100}{}{You see a merchant.}
{101}{}{You see a merchant clad in dusty traveling attire.}

{200}{}{Well, look who's sauntered into town! Thanks to you, we've got a new caravan route. Had no clue there was a village 'round these parts.}
{201}{}{What're you guys gonna be trading?}
{202}{}{Ah, we're still dickering, my friend. Casa Nueva needs more hands, and the Followers wanna cultivate some rare plants here. Let's see where this rabbit hole leads.}
{203}{}{Glad to hear. I'm outta here.}

{210}{}{Need something?}
{211}{}{Catch you later.}
{212}{}{I'm outta here.}

{220}{}{Do you have anything to trade?}
{221}{}{I'm only here for negotiations. Y'know, suss out the locals and see what they need. But if you've got something worthwhile, I'm up for it.}
{222}{}{Got it. Later.}
{223}{}{Any idea what went down here?}
{224}{}{Nah, they keep theirs mouths shut. And I ain't one to pry. Everyone's got their secrets, that's just the way of the wasteland. My concern's ensuring we don't get shivved in the back.}
{225}{}{What's the plan after the deal's sealed?}
{226}{}{Straight back to Casa Nueva, of course. Why?}
{227}{}{Alright, no sweat. Catch you later.}
{228}{}{Could you get me to Casa Nueva?}
{229}{}{Grateful for opening up this new route, but I don't work gratis. Escort service runs 300 caps.}
{230}{}{Here's the caps. Ready to roll.}
{231}{}{No need. I'll manage solo.}
{232}{}{Can I tag along to Casa Nueva?}
