{100}{}{You see a raider.}
{101}{}{You see one of the highwaymen. This guy looks like he crawled out of hell itself.}

{110}{}{If we don't get paid, someone's gonna die, and it'll be bloody.}
{111}{}{We didn't come here for a picnic.}
{112}{}{Tell that bastard Bustos to count his caps if he wants his precious daughter back in one piece.}
{113}{}{I don't wanna gut the girl, but if I have to, I will.}
{114}{}{What the hell did Bustos decide? Speak up or I'll start shooting.}
{115}{}{I'm losing my patience, and when I do, people die.}
{116}{}{My fingers are itching to blow someone's brains out.}
{117}{}{}
{118}{}{Follow us, and you'll be picking up pieces of your friends.}
{119}{}{Get lost, or you'll be the first to die.}
