{100}{}{You see old Gallegos.}
{101}{}{You see a thin townsperson with a shaggy beard and shabby clothes. He hobbles along the street, leaning on a stick.}
{102}{}{Don't touch me, I'm a piece of iron, I can still stand up for myself. Shoo, shoo.}
{103}{}{}

{180}{}{«What do you want from me?»}
{181}{}{I just want to talk. Do you understand English?}
{182}{}{«Leave me alone. I don't understand English.»}


{200}{}{Que quieres de mi?}
{201}{}{I just want to talk. Do you understand me?}
{202}{}{Dejame en paz. No lo comprendo.}
{203}{}{Hmph. Forget it. Time to go.}
{204}{}{Don't play dumb with me. There's no way you don't know English.}
{205}{}{No hablo ingles. Dejame en paz!}
{2205}{}{«I don't speak English. Leave me alone!»}
{206}{}{If you don't stop this show, I'll knock your teeth out.}
{207}{}{Stop! Stop! Maldito seas, what do you want?}
{208}{}{«Everything's fine, friend. I just want to talk to you.»}
{209}{}{«Oh, Spanish! You are speaking Spanish? I'm so glad to hear my own language!»}
{210}{}{Um...it's... esta... bien?}
{211}{}{Eh? Que quieres decir? No entiendo nada, habla mas claro.}
{212}{}{This is getting too complicated for me. Goodbye, old man.}
{213}{}{«That's better. Now we can talk, right?»}
{214}{}{«It would be better if you learned English. Mexican.»}
{215}{}{So you really don't understand any English... Damn.}
{216}{}{«Have pity on an old man, senor. Strangers come and go. And I need to look for food. I'm starving, for god's sake.»}
{1216}{}{«Have pity on an old man, senora. Strangers come and go. And I need to look for food. I'm starving, for god's sake.»}
{217}{}{«Okay, hang tight. Maybe I can find some food for you.»}
{218}{}{Looks like we can't have a conversation. Fuck you!}
{219}{}{Looks like we can't have a conversation. Fuck you, «old man!»}

{220}{}{Ten piedad de un hombre viejo, senor. Los extranos van y vienen. Y necesito buscar comida. Estoy hambriento, por el amor de Dios.}
{1220}{}{Ten piedad de un hombre viejo, senora. Los extranos van y vienen. Y necesito buscar comida. Estoy hambriento, por el amor de Dios.}

{240}{}{(raising his hands, begging for mercy) «Ahh, bandit! Don't touch me! I have nothing!»}
{1240}{}{(raising his hands, begging for mercy) «Ahh, bandit! Don't touch me! I have nothing!»}
{241}{}{«Hey, I'm not a bandit.»}
{1241}{}{«Hey, I'm not a bandit.»}
{242}{}{«If you scream, you'll get hurt.»}
{243}{}{(raising his hands, begging for mercy) Ahh, bandido! No me toques! No tengo nada!}

{244}{}{Hey, I'm not a bandit.}
{1244}{}{Hey, I'm not a bandit.}
{245}{}{If you scream, you'll get hurt.}

{250}{}{(Gestures indicating his readiness to talk)}
{251}{}{«Bye, old man.»}
{252}{}{«Oh, food! Thank you, mister.»}
{1252}{}{«Ah, food! Thank you, miss.»}
{253}{}{Oh, comida! Gracias, Senor.}
{1253}{}{Oh, comida! Gracias, Senorita.}
{254}{}{«Feel better? Now can you tell me a little about yourself and the city?»}
{255}{}{«Alright, now that you've had your fill, spill some info about this city.»}

{256}{}{«Ah, how can I help you, mister?»}
{1256}{}{«Ah, how can I help you, miss?»}
{257}{}{Ah, como puedo ayudarte, senor?}
{1257}{}{Ah, como puedo ayudarte, senorita?}

{260}{}{«Who are you, old man?»}
{261}{}{«Me? Well, my name is Gallegos. I live here.»}
{262}{}{Estas hablando conmigo? Mi nombre es Fernando Gallegos. Yo vivo aqui.}
{263}{}{«Nice to meet you, Gallegos. Let's chat?»}
{264}{}{«That's all I wanted to know. Bye, Gallegos.»}
{265}{}{«How old are you, Gallegos?»}
{266}{}{«You look worse than a wrinkled mole rat. How old are you?»}
{267}{}{«I didn't count. I think I've already lived through forty winters.»}
{268}{}{No los he contado. Creo que por lo menos cuarenta primaveras, eso creo.}
{269}{}{«Long time. Many didn't even live half their life. You're not local, are you?»}
{270}{}{«Your accent is unusual. You're not from these parts?»}
{271}{}{«I see why you look like a dead man. It's a wonder you're still hanging on at all. Not local either...»}
{272}{}{«So you know a lot. Let's talk about something else.»}
{273}{}{«That's impressive. I gotta go. See you.»}
{274}{}{«It's true. In the south, where I'm from, they speak only Spanish. I don't know your language well yet.»}
{275}{}{Efectivamente. En el sur hablan espavol, y no hablo bien tu idioma.}
{276}{}{«So you came from the south? It must have been a hard road.»}
{277}{}{«You're mad, old man. There's nothing but barren desert in the south, No one crosses it.»}
{278}{}{«Came from the south huh? It's a miracle you survived.»}
{279}{}{«It was hard to get through the desert. But we managed, because we had no choice. First we got to the city of Two-Sun, but we were driven out. Then we came to Casa Grande and settled in.»}
{280}{}{Fue muy dificil cruzar el desierto. Pero lo hicimos porque no teniamos otra opcion. Primero llegamos a la ciudad de Two-Sun, y de ahÑ™ nos echaron. Luego nos quedamos en Casa Grande.}
{281}{}{«You say "we". Who else was with you?»}
{282}{}{«A few peasants. I'm the only one left among us.»}
{283}{}{Varios campesinos. Pero soy el unico que sigue vivo.»}
{284}{}{«Sad story. I'm really sorry.»}
{285}{}{«How interesting. I'd like to ask more.»}
{286}{}{«Sounds like you're full of shit old man.»}
{287}{}{«Very interesting. But I gotta go. Bye.»}
{288}{}{}
{289}{}{}

{290}{}{«What are you doing?»}
{291}{}{«A little bit of everything. I do what the residents need. Yesterday I was looking for firewood for the bath. It's good that it's working again.»}
{292}{}{«A little bit of everything. I do what the residents need. Yesterday I was looking for firewood for the mayor. He likes to take a bath to relax.»}
{293}{}{«A little bit of everything. I do whatever the residents need.»}
{294}{}{Chambitas.}
{295}{}{«Yeah, that was a pointless question. What else can you tell me?»}
{296}{}{«I'll keep that in mind. For now, let's leave it at that.»}
{297}{}{«Why are you limping?»}
{298}{}{«An old wound. What do you care? Do you like to make fun of others?»}
{299}{}{Es por una vieja herida.}
{300}{}{«Sorry, I shouldn't have brought it up. Let's talk about something else?»}
{301}{}{«If you don't want to talk, that's your business. I'll find others to talk to. Bye.»}
{302}{}{«You waddle around like a pregnant Brahmin before a sacrifice. Ever seen that?»}
{303}{}{«You waddle around like a mole rat that's eaten uranium crumbs. Ever seen that?»}
{304}{}{«Even Uncle Jose worked on the plantations with his bad leg. You're just a whiner and a loser.»}
{305}{}{«Ha ha, yeah. I'll look at you when a stray bullet rips the muscles of your triceps.»}
{306}{}{Callate, sinverguenza. Era una bala perdida.}
{307}{}{«Stray bullet? Please take note of this.»}
{308}{}{«Looks like this place is dangerous. I guess I should get out of here, and quickly.»}
{309}{}{«Come on, tell me how it happened. I'll keep it between us.»}
{310}{}{«Leave me alone.»}
{311}{}{Dejame, canalla.}
{312}{}{«Not until I hear everything you know.»}
{313}{}{«Okay, whatever you say.»}
{314}{}{«It's a shame that this happened. Tell me how it happened? I promise this'll stay between us.»}
{315}{}{«Stray bullet. Do you know the abandoned bar up north? I was there when the shooting happened. A bullet hit me in the leg. Just an accident.»}
{316}{}{Fue un accidente durante un tiroteo en el antiguo bar. Una bala me hirio la pierna.}
{317}{}{«A stray bullet? I'll make a note of that.»}
{318}{}{«Sounds like this place is pretty dangerous. I should probably hit the road, and soon.»}
{319}{}{}

{320}{}{«Tell me about the city.»}
{321}{}{«What's there to tell? We survive only thanks to the water pump. It gives us water and attracts traders from afar.»}
{322}{}{La ciudad sobrevive gracias a la bomba de agua. El agua da vida a este desierto y atrae a comerciantes lejanos.}
{323}{}{«Then why are the streets so empty here?»}
{324}{}{«Water attracts more than just merchants. We are afraid of highwaymen and all kinds of predators.»}
{325}{}{El agua no solo atrae a los comerciantes. Tenemos miedo a los bandidos y a los ladrones.}
{326}{}{«Hmph. The streets are so empty I thought this was a ghost town.»}
{327}{}{«Tell me about your mayor.»}
{328}{}{«Count Bustos. He runs the city from that huge mansion.»}
{329}{}{El conde Bustos gobierna la ciudad desde esa gran mansion.}
{330}{}{«Thanks, this helped me.»}
{331}{}{«In that mansion, right? Perhaps I should check on him right now.»}
{332}{}{«No, I mean what kind of person is he. How do you feel about him?»}
{333}{}{«It's dangerous to discuss those above you. We don't know each other that well.»}
{334}{}{No quiero hablar de el.}
{335}{}{«Indeed, I doubt your fears are far off the mark. Maybe we should talk about something less stressful?»}
{336}{}{«So, you're scared of Bustos, huh? That's saying something. I think I'm good with leaving this discussion alone for now.»}
{337}{}{«I mean, what kind of person is he? Do people admire him or fear him?»}
{338}{}{«Terrible man. Cruel, greedy, keeps everyone subservient. No one will speak against him here.»}
{339}{}{Es una persona terrible, es un tirano. Aqui nadie dira nada malo de el.}
{340}{}{«So he's ruling the city with a tight grip. Thanks for your honesty.»}
{341}{}{«Count Bustos is dead. Do you think the city will be better off without him?»}
{342}{}{«He was a terrible person. Greedy and cruel, he ruled everything with an iron fist. Everyone was afraid to say anything bad about him. But without him, we are an easy target for raiders.»}
{343}{}{Era un tirano. Pero sin el, nos convertimos en un blanco facil para los ladrones.}
{344}{}{«I guess even his tyranny had some use.»}

{350}{}{«I'm going to head south. Wanna come with me?»}
{351}{}{«You're crazy. That's a road of death.»}
{352}{}{Estas completamente loco. Es un camino mortal.}
{353}{}{«Too bad. I could use a guide down there.»}
{354}{}{«If you get to Dominguez's ranch, tell him that I'm alive and that there are settlements in the north too.»}
{355}{}{Cuando encuentres el rancho de Dominguez, cuentale sobre mi. Di que estoy vivo. Di que hay asentamientos en el norte.}
{356}{}{«Rancho Dominguez? Okay, I'll give him your regards. But it won't be anytime soon. I have a few more questions for you.»}
{357}{}{«I'll tell this Dominguez about you if I meet him. Bye.»}
{358}{}{«I'm not going anywhere with you.»}
{359}{}{No voy a ninguna parte contigo.}
{360}{}{«As expected. Maybe you can at least answer some more questions?»}
{361}{}{«Then stay here. Farewell, old man.»}
