{100}{}{You see a townsperson.}
{101}{}{You see a resident of Casa Grande. He's trembling and feverish.}
{102}{}{You see a resident of Casa Grande.}
{103}{}{You've successfully treated the patient.}
{104}{}{This man is suffering from radscorpion poison. Your skills are useless without an antidote.}

{110}{}{*Gah*}
{111}{}{Damn radscorpion venom's got me shaking like a leaf.}
{112}{}{Took a nasty sting from one of them critters on the edge of town.}

{115}{}{Thanks, starting to feel like myself again.}
{116}{}{Got stung by one of them radscorpions just outside town.}
{117}{}{Never thought much of healers...}
{118}{}{Appreciate it, Doc. Radscorpions been thick as thieves lately. Take these buckshot shells, might come in handy out there.}

{120}{}{Oh...}
{121}{}{*Cough cough*}
{122}{}{*Hack*}
{123}{}{Ugh...}
{124}{}{*Moan*}
{125}{}{Hrr...}
