{100}{}{You see an orphan.}
{101}{}{You see a disheveled boy with a wild look.}
{102}{}{Hrrr...}
{1102}{}{Ma... ma... hrrr...}
{103}{}{I have shoes.}
{104}{}{Wow, thanks a lot!}
{105}{}{Changing shoes makes a child happy.}

{200}{}{(On the side of the street, you spot a kid with a wild, unkempt look. His clothes are ragged and stained, and he's tossing a small metal object in his hand, watching your reaction intently. It looks suspiciously like a grenade.)}
{201}{}{Hey boy. Do you know that thing is dangerous?}
{202}{}{(He stops tossing the grenade and tenses as if waiting for a predator to pounce) I'm. Not. A boy.}
{203}{}{Okay, uh, whatever. But that thing is still dangerous. You shouldn't do that.}
{204}{}{No. You are a boy. A child. And you're holding something that is extremely dangerous.}
{205}{}{(the boy puts the grenade in his pocket and pointedly spits) So what?}
{206}{}{Okay, carry on then.}

{210}{}{What do you want?}
{211}{}{Nothing. Forget it.}

{212}{}{Mmm, nice clothes. I want clothes like this. But it's too bright. It needs to be a different color to blend in with the sand. Or enemies will find you and kill you.}
{213}{}{Well, yeah, this jumpsuit is not for combat purposes, you know.}
{214}{}{You want too much.}
{215}{}{Don't come near me, scary face.}
{216}{}{Road warrior! There's a road warrior here!}
{217}{}{Oh no...}
{218}{}{Hey, you...}

{220}{}{When a ranger tells you to put away your weapon, you should listen, kid.}
{221}{}{(looks at you puzzled, then at the grenade, then back at you and shakes his head)}
{222}{}{C'mon, kid. You shouldn't just mindlessly play with grenades. I've seen people hurt that way.}
{223}{}{It's okay, you'll remember my words.}
{224}{}{What happened to them?}
{225}{}{It's a sad sight. The explosion tears off their hands, their eyes burst and flow out of their sockets. If they survive they just writhe in pain for hours...}
{226}{}{Nothing special. Keep fooling around and you'll find out for yourself.}
{227}{}{(The boy throws the grenade like a hot potato and runs to the side.)}
{228}{}{Hey, I haven't told you any of the real gory details yet...}
{1228}{}{Hey, I haven't told you any of the real gory details yet...}

{230}{}{I want that grenade. Wanna trade?}
{231}{}{What do you have?}
{232}{}{Let's see...}
{233}{}{(Waiting for your suggestions.)}
{234}{}{[Done]}

{240}{}{Do you know what happens if you take out the ring?}
{241}{}{I know.}
{242}{}{Well, I'm happy for you. Bye.}
{1242}{}{Well, I'm happy for you. Bye.}
{243}{}{Nope. This thing will play some cool music. Come on, try it.}
{244}{}{(thinks for a moment, then reaches for the ring)}
{245}{}{No, no, I'm actually not sure. Don't be so impulsive.}
{1245}{}{No, no, I'm actually not sure. Don't be so impulsive.}
{246}{}{[Let him pull out the ring]}

{250}{}{Do you know what will happen if you take out this ring?}
{251}{}{I know.}
{252}{}{No, you don't. First, the force of the explosion will tear off both your arms. They will scatter to the sides in a shower of bloody pieces.}
{253}{}{(listens with wide eyes)}
{254}{}{Then the grenade shrapnel will go all the way through your chest and stomach. Your guts will burst out and you'll begin to choke on your own blood.}
{255}{}{(listens with a breathy sound)}
{256}{}{The shrapnel will also rupture your eyes, causing them to burst out of the sockets. You'll go blind and lose consciousness. And when you wake up, you'll face several hours of unimaginable pain in a pool of your own blood, until...}
{257}{}{(the boy throws the grenade like a hot potato and runs to the side)}
{258}{}{Hey, I haven't told you about the final details yet...}

{260}{}{Give me the grenade, now.}
{261}{}{(seeing through your bluff, makes a mocking sound)}
{262}{}{Wow...}
{263}{}{}
{264}{}{Give me the grenade and no one will get hurt. You won't get hurt.}
{265}{}{(Bristles like a wolf cub in danger)}
{266}{}{Are you listening? Give me the grenade. NOW.}
{267}{}{Don't worry, I don't want to hurt you.}
{268}{}{(Numb, he hands over the grenade, but soon comes to his senses and runs away in fear.)}
{269}{}{That's it, you little shit.}
{270}{}{Good boy.}

{271}{}{Let's play a game? If I lose, I'll give you 5 caps, otherwise you'll give me the grenade.}
{272}{}{(Excitement appears in the boy's eyes) Okay.}
{273}{}{Great, let's get started then...}
{274}{}{We'll do this later, I have things to do right now.}
{275}{}{Let's play a game? If you lose, you'll give up the grenade.}
{276}{}{Nah, I'm not that stupid.}
{277}{}{Okay, whatever you say.}
{278}{}{Yeah, I can see that. Later.}
{279}{}{You don't have 5 caps to start the game.}
{280}{}{No!}
{281}{}{Oh yes. And the grenade is now mine. That's fair, baby.}
{282}{}{Better shut up. It's mine now.}
{283}{}{Ha! You can't beat me.}
{284}{}{Well, well, we'll see about that later.}
{285}{}{Continue to make that face, and I'll take both my caps and your grenade.}

{290}{}{Where are your parents, kid?}
{291}{}{I don't have any. What do you care?}
{292}{}{Oh, sorry, I didn't know that.}
{1292}{}{I'm really sorry, I didn't know that.}
{293}{}{Okay. No need to be rude, you little brat.}

{300}{}{[Pinch the handle of the music box and wind the mechanism]}
{301}{}{(The child listens to the melody in fascination; surprise suddenly appears on his wild face, which has not known a child's feelings for a long time.)}
{302}{}{Pretty cool huh? Do you want this?}
{303}{}{(The boy nods happily, expressing in every possible way his desire to possess the unusual object.)}
{304}{}{Here you go.}
{305}{}{[Hold out the music box, but then withdraw your hand]}
{306}{}{(The boy smiles nervously, expressing in every possible way his desire to possess the unusual object.)}
{307}{}{Huh? [repeat process]}
{308}{}{(the boy frowns, and draws back slightly)}
{309}{}{Here you go.}
{310}{}{(The boy grabs the music box, emotions of pure childish delight appear on his face for the first time in his life.)}
{311}{}{Now tell me, where did you find your grenade?}
{312}{}{In the old abandoned school over there. But sometimes there are highwaymen there, it's dangerous.}
{313}{}{I'm not worried about the highwaymen. Take me there.}
{314}{}{This is mine. And I won't just give it away.}
