{100}{}{You see a bodyguard standing firm.}
{101}{}{You see a man in combat gear, watching you like a hawk.}
{102}{}{Hey, tin can, crawl back to the Tinsmiths. We don't need you here.}
{103}{}{Y-you... what do you want? Just get out of here!}

{200}{}{The Count and the others are at the abandoned bar. Something went down there, but I don't know the details.}
{201}{}{The bar, got it. Thanks, see you.}
{202}{}{Why aren't you there?}
{203}{}{I guard the mansion. Can't leave all this wealth unprotected.}
{204}{}{Right. So, the old bar it is...}

{210}{}{The Count is dead. You get it? He's dead! The whole city's finished now!}
{211}{}{One person's death doesn't end a city. Calm down.}
{212}{}{Calm down? I just landed a decent job, and now, because of one accident, I'm back on the street. No job, no caps, no connections. What do I do now?}
{213}{}{The city's free from a tyrant. Isn't that good news?}
{214}{}{Good news? Sure, I just had a solid job under that same 'tyrant'. Now I'm back on the street because of one accident. What am I supposed to do now?}
{215}{}{Any plans?}
{216}{}{Maybe I'll turn to raiding. Plenty of caravans, and I'm just one man. I've got to survive somehow.}
{217}{}{You're a menace to society. I think you need to be dealt with.}
{218}{}{I can't agree with that. Good luck finding real work. Goodbye.}
{219}{}{What do you want?}
{220}{}{Nothing, really.}
{221}{}{Your death.}

{230}{}{Uh, hi. The Count is at home.}
{231}{}{Uh, hi. The Count was looking for you. He wants to discuss something.}
{232}{}{I need to see him.}

{250}{}{Uh, wait a second. Where are you heading?}
{251}{}{I'm just wandering around the city.}
{252}{}{That seems a little suspicious. But, uh, I'll let it slide this time.}
{253}{}{Let it slide? Let what slide exactly?}
{254}{}{Well... Listen, this is Count Bustos' residence. He REALLY doesn't appreciate people loitering around. Got it? So move along. Don't give me any trouble.}
{255}{}{Alright, got it. See you.}
{256}{}{Okay. By the way, can you tell me a little about this Count? Who is he and what does he do?}
{257}{}{I'm curious, who lives in such a luxurious mansion?}
{258}{}{Count Bustos. He's the mayor of the city.}
{259}{}{I should probably pay him a visit then. Is he seeing visitors right now?}
{260}{}{Probably. But he REALLY doesn't like being disturbed without a good reason.}
{261}{}{I still need to talk to him. Bye for now.}
{262}{}{Tell me more about him. You said he's the city's mayor?}
{263}{}{Thanks, that's all I needed to know.}

{300}{}{Tell me about the Count.}
{301}{}{Count Alfred Bustos. He's the mayor of the city and head of the chamber of commerce. Also, he's my boss. Though, I'm still on probation.}
{302}{}{Why is he called the Count?}
{303}{}{Well, he's a count. It's like a title or something. Honestly, I don't know what it means exactly, but it sounds pretty impressive.}
{304}{}{Do you think he's looking for more guards?}
{305}{}{I'm not sure. You should ask him yourself.}
{306}{}{Who are you anyway?}
{307}{}{Tell me more about Count Bustos.}

{310}{}{Who are you?}
{311}{}{I'm just a security guard.}
{312}{}{Are you a local?}
{313}{}{No, I'm from a small community near Phoenix. The community fell apart, so I came to the city. Things didn't work out there either, so I joined a caravan to earn some caps. But they ditched me here. Haven't seen them since. Didn't even pay me in full.}
{314}{}{Have you been working here as a guard since then?}
{315}{}{No, just for a few months. The Count needed people, and there weren't any locals left for security. Otherwise, I wouldn't have gotten this job.}
{316}{}{That's tough. No one needs dead weight dragging them down.}
{317}{}{I'm not dead weight! And why are you grilling me? Just go about your business, I don't owe you anything.}
{1317}{}{I'm not useless! Don't think your pretty charms will work on me. Go on your way, I don't owe you anything.}
{318}{}{Alright, alright.}
{319}{}{I need to go.}
{320}{}{By the way, why are these streets so empty?}
{321}{}{This isn't Phoenix, it's a small town. But I don't get it either. There's a lot of caps here, and caravans pass through often.}
{322}{}{I was starting to think this place was a ghost town. Alright, I'll take a walk.}
{323}{}{Seems like they hired you out of desperation. I'm wasting my time talking to you.}
{324}{}{I'm sure the Count knew who he was hiring. I need to meet him.}
{325}{}{That's pretty unfair. You definitely deserve better.}
{326}{}{Exactly. I hope those caravan folks got eaten by radscorpions. But now I've got a good job with decent pay. Can't complain.}
{327}{}{You're just lucky. Don't get too comfortable.}
{328}{}{Alright then. It's time for me to meet your employer. Goodbye.}
