{100}{}{You see a bodyguard standing guard.}
{101}{}{You see a man in combat gear. He's eyeing you suspiciously.}
{102}{}{Hey, tin can, crawl back to the Tinsmiths. We don't need your kind here.}

{110}{}{The Count has no time for trash like you.}
{111}{}{What are you gawking at?}
{112}{}{Need something?}
{113}{}{Don't get any ideas about stealing anything.}
{114}{}{Looks like someone's about to make trouble.}
{115}{}{You'd have to be desperate to come here.}
{116}{}{Looking for a fight?}

{120}{}{Count Bustos is at home.}
{121}{}{Seeing the mayor, huh? Alright, head on in.}
{122}{}{Alright, go in. But behave yourself.}
{123}{}{Don't you dare disappoint the Count.}
{124}{}{You can go, but I'll be watching you.}

{130}{}{Great, now I have to find a new job.}
{131}{}{A city without a mayor will be a lot more dangerous.}
{132}{}{Damn, the Count paid good caps. And there was water -- plenty of it.}
{133}{}{Bustos may have been a tyrant, but he paid well and on time.}
{134}{}{Well, there goes my job.}

{140}{}{You're in the wrong city, fuckin' raider.}
{141}{}{Hey, aren't you one of the Blue Shields?}
{142}{}{Goddamn raiders have gotten bold, walking around the city like it's theirs.}
{143}{}{The Blue Shields negotiating? These are strange times...}