{100}{}{You see a slave, eyes hollow with despair.}
{101}{}{You see an exhausted slave. His hands are a bloody mess of calluses, and bruises mar his shoulders from the ropes that once bound him.}
{102}{}{This man seems incapable of speaking, his voice likely lost to suffering.}

{110}{}{O-oh...}
{111}{}{Ugh...}
{112}{}{Eh...}
{113}{}{Well...}
{114}{}{What?}
{115}{}{Get away from me.}
{116}{}{Don't talk to me.}
{117}{}{I wish they'd just shoot me.}
{118}{}{}
{119}{}{}