{100}{}{You see Joe, the local bartender.}
{101}{}{You see Joe, the esteemed bartender, a true local celebrity.}
{102}{}{Sorry, folks, bar's closed. Come back in the morning.}
{103}{}{Z-z-z...}
{104}{}{Nice armor, but for the bar, something simpler might be more appropriate.}
{105}{}{Sorry, pal, no weapons allowed in the bar. It's the rule.}

#Floating lines
{109}{}{What's the word on the street?}

{110}{}{Sounds like there's some promising deals in the works with Garage City.}
{111}{}{Silence has fallen over the streets of Garage City. It's like it's been deserted overnight.}
{112}{}{Faber and Garage City have inked a deal. Should be good for everyone involved.}

{113}{}{San Brahmin used to have the best meat, but they've stopped selling it.}
{114}{}{Rumor has it there was quite a stir in San Brahmin, but things seem to have settled down now.}
{115}{}{Those stubborn herders have shut down all their trade routes with Phoenix.}

{116}{}{The cultists from the south seem to be up to something.}
{117}{}{The Cathedral of Fire went up in flames. Quite the irony.}
{118}{}{The cultists from the south seem to be plotting something big.}

{119}{}{More folks are coming up from the south, but the goods seem to be getting scarcer.}
{120}{}{Word is, Phoenix is a bit on edge these days.}
{121}{}{Thinking of making another trip to the Big City, huh?}

{122}{}{Someone's been picking off patrolmen in the old city.}
{123}{}{Didn't know the Rangers were behind those attacks on the patrols.}
{124}{}{Who do those Rangers think they are, huh?}

{125}{}{Faber's got a plan, he'll rebuild the city, mark my words.}
{126}{}{City's gonna feel the pinch without Roy Faber around.}
{127}{}{The mine's humming along at full tilt.}

{128}{}{The jailers seem to be taking over the slave trade. Bit unsettling, if you ask me.}
{129}{}{Prisoners made a break from the jailers. We need to watch our backs.}
{130}{}{First time I've seen the jailers cut loose their prisoners like that.}

{131}{}{Sometimes all you need is a stiff drink and a big-titted babe to make life complete.}
{132}{}{This is a bar, not a market.}
{133}{}{Fancy something with a bit more kick?}
{134}{}{Looks like the new shipment's gonna be delayed.}
{135}{}{This stuff? Best liquor this side of Phoenix.}
{136}{}{Another round, perhaps?}

#First dialogue
{200}{}{Hello there.}
{201}{}{Mind if I ask you a couple of questions?}
{202}{}{See you.}
{203}{}{Come on in, you're always welcome here.}
{204}{}{Come in, but keep the trouble outside.}

#Questions
{210}{}{What would you like to know?}
{211}{}{Tell me something else.}
{212}{}{Let's go back to talking about the bar.}
{213}{}{Can I ask you about something else?}
{214}{}{Let's backtrack a bit.}
{215}{}{Well, options are slim. The mine always needs hands, and the garrison often has odd jobs. I can give you a few pointers. Choose what suits you best.}

{220}{}{Where can someone earn some caps around here?}
{221}{}{Well, choices are limited. The mine always needs laborers, and the garrison sometimes offers odd tasks. I might have a few jobs needing doing.}
{222}{}{I'm new to these parts. Tell me about Flagstaff.}
{223}{}{Flagstaff's a labor colony with a tight grip. Main spots are the garrison out east and the uranium mine up north.}
{224}{}{Can you tell me about the mine?}
{225}{}{The whole city owes its existence to the mine. Built from scratch to churn out uranium. Used to be a cash cow, but lately, it's been running dry due to a labor shortage.}
{226}{}{Can you tell me about the prison?}
{227}{}{Faber's hired guns set up camp among the ruins and tossed the crooks in there. They gathered miscreants from all over. Now, the cons work off their debts, and the colony thrives off their sweat.}
{228}{}{Can you tell me about the postal service?}
{229}{}{It's a Phoenix company branch. Handles small package deliveries between settlements.}
{230}{}{I heard whispers of slavery being rife here. Is this true?}
{231}{}{Quick tip: watch your tongue. The workforce's a mix of cons and peons. Some serving time, others paying off debts. Sure, there are indentured savages, but we call 'em servants, not slaves.}
{232}{}{Why keep ex-cons on lockdown?}
{233}{}{For hard labor. They've done a lot of the heavy lifting around here. Without 'em, setting up Flagstaff would've been a real slog.}
{234}{}{Is that fair, in your opinion?}
{235}{}{Hey, we've rebuilt the city and set up shop thanks to these guys. Seen many other places like it?}
{236}{}{Where do you get all this booze?}
{237}{}{This stuff's brewed in Phoenix, shipped in once a month with the caravans. Not as fancy as pre-war hooch, but it's cheap and plentiful.}
{238}{}{I wanna buy drinks for everyone here.}
{239}{}{Now, that's generous. That'll set you back 50 caps.}
{240}{}{Price isn't an issue - pour one for everyone, it's on me!}
{241}{}{How much? Guess I'll have to hold off on being a big spender today.}
{242}{}{Hang on, I've got a question first.}
{243}{}{Too steep for me. Maybe next time, in the future, some other day.}
{244}{}{Off to a good start. Folks'll appreciate it. Just remember - drinking alone won't earn you a rep around here.}
{245}{}{Before the buzz wears off, let's chat some more.}
{246}{}{Got it. Time for me to focus on more pressing matters now.}
{247}{}{How do you feel about Roy Faber?}
{248}{}{He's the boss, plain and simple. Without him, Flagstaff wouldn't exist. (leaning in and lowering his voice) But listen, not the best guy to talk about casually. If you value your skin, best keep his name out of your idle chatter. You catch my drift?}
{249}{}{He's our leader. Without him, this place wouldn't exist.}

#Teeth of the rat king from the mine
{250}{}{Check it out, got the tooth of that rat king from the mine.}
{251}{}{No kidding? If that mutant wasn't the size of a Brahmin, I'll eat my hat! They spun so many yarns about that beast... Listen, sell it to me. I'll toss you 100 caps.}
{252}{}{What do you want with these teeth?}
{253}{}{Sure thing, here you go.}
{254}{}{Nah, I'm thinking of turning it into an amulet to scare off my enemies.}
{255}{}{I'll mull your offer over.}
{256}{}{This curiosity's bound to draw in some customers.}
{257}{}{Ah, you and your rural superstitions... Throwing caps at them's just a waste. Give it another think.}
{258}{}{(grins ominously) Time to flaunt this thing... Oh yeah - here's your 100 caps.}
{259}{}{Deal's done.}
{260}{}{Later Joe.}
{261}{}{Looks like you're not keen on hashing this out. Let's talk about something else.}
{262}{}{I'm not backing down from anyone. But if that's how it is, let's switch gears.}
{263}{}{Take it for free. But do me a favor and mention my name in your stories, alright?}
{264}{}{Ho-ho-ho, time to flaunt this baby. You sure you don't want a little something as a token of appreciation? How about a cold one?}
{265}{}{Thanks, I'll take one. Best of luck, Joe.}
{266}{}{Please, I'm really hurting for some medicine. We're buddies, aren't we?}
{267}{}{C'mon, you wouldn't want me to suffer, would you?}

#About trading
{270}{}{What's on the trading menu today?}
{271}{}{Alcohol and snacks, my friend. What else do you expect to find in a bar? Although sometimes I gotta play the role of a whole darn store.}
{272}{}{Strictly caps, huh?}
{273}{}{Yep. Down south, it's caps or nothing now. Pre-war cash is as good as worthless these days.}
{274}{}{Where can I get some medicine around here?}
{275}{}{Nowhere local, friend. Caravans are your best bet. I keep what I got for emergencies.}
{276}{}{Fresh out, I'm afraid.}
{277}{}{You might as well offload 'em to me before they go bad.}
{278}{}{Hmm. Can't argue with that logic. Here's what I got. (places a modest stash of meds on the counter)}
{279}{}{Nah, even in a safe haven like Flagstaff, it's wise to keep a couple stimpaks handy.}
{280}{}{A customer with my reputation deserves special prices. Don't you agree?}
{281}{}{I guess you've got a point. Both me and my regulars would be happy to see you around. How about a 20% discount?}
{282}{}{Fantastic. What's on offer today?}
{283}{}{Word on the street is there's trouble stirring thanks to some stranger in town. Let's hope he doesn't stick around too long.}
{284}{}{Prices seem higher than usual. What gives?}
{285}{}{Ah, there was a bit of a trade "hiccup". If you're not a fan of the prices, well, good luck finding another watering hole in this city. Spoiler alert: there ain't one.}
{286}{}{Got it.}

#Showdown at the bar
{287}{}{Been waiting for someone to put that arrogant mercenary in his place. Here, have a beer on the house. But keep your guard up. The garrison won't forget this anytime soon.}
{288}{}{I'll manage somehow. Thanks for the beer.}
{289}{}{Yeah, "special prices"... double the usual.}

#About my relatives in the city
{290}{}{I'm searching for my kin from the village out west.}
{291}{}{They here of their own accord? No? Then they're probably in the pen for prisoners. Head straight east along the main street.}
{292}{}{Why do you think they'd end up there?}
{293}{}{Haven't seen any new faces 'round here lately, but there's been a surge in savage folk being brought into the pen recently.}
{294}{}{Why imprison people like this?}
{295}{}{So they can work in the mine and help rebuild the city. The whole colony owes its existence to hard labor.}
{296}{}{Time for me to pay a visit to the head jailer, then.}
{297}{}{Smart move. Just watch your back and steer clear of trouble. Faber's not one to be trifled with; folks around here fear him.}
{298}{}{Thanks for the help. Gotta get going.}

#Tequila sales have been stopped
{300}{}{What happened to the good stuff?}
{301}{}{Word is, the tequila joint in Phoenix went under or something. Now I'm stuck taking whatever hooch the caravans can scrape together. Hence the price hike.}
{302}{}{I figured as much. Well, take care.}
{303}{}{Yeah, its too bad. Catch you later.}
{304}{}{Show me what you got, then.}
{305}{}{Alright, let's see what I can offer you...}

#Quest - Repay the Debt
{310}{}{Got another task for me?}
{311}{}{Actually, yes. There's this mercenary named Davis who owes me a hundred caps. I've banned him from the bar, but it's bad for business.}
{312}{}{What's the plan?}
{313}{}{If you can get him to pay up, I'll split it with you.}
{314}{}{Consider his debt mine now.}
{315}{}{Sounds risky. I'll pass.}
{316}{}{I'll mull it over.}
{317}{}{Deal. Remember, Davis owes 100 caps. You get half.}
{318}{}{Got it.}
{319}{}{Sure, no problem. But my offer's still on the table.}
{320}{}{Got it.}
{321}{}{Take your time. Davis isn't in any rush to settle up.}
{322}{}{Got it.}
{323}{}{I want to settle Davis' tab.}
{324}{}{Really? Color me surprised. Thanks. Fork over 50 caps, and the rest is yours, as agreed.}
{325}{}{The jingle of caps is growing on me. See you around.}

#Pinball Machine
{330}{}{The pinball machine's busted.}
{331}{}{Yeah, I know. But it was a real draw for customers.}
{332}{}{What's wrong with it?}
{333}{}{Looks like something fried in there. No replacement parts in town. You seem like the traveling type. If you can find something to fix the StarBall, I'll toss you 50 caps.}
{334}{}{Deal.}

{335}{}{Sounds good.}
{336}{}{Before I get to that, I've got a question about the machine.}
{337}{}{Let's talk about something else.}
{338}{}{Got it.}

{339}{}{Not my forte.}
{340}{}{Gotcha. I'll find someone else.}
{341}{}{You know what your bar's missing?}
{342}{}{What's that?}
{343}{}{Haven't got a clue. I'll let you know when it hits me.}
{344}{}{A patriotic flag on the wall. And lucky for you, I've got one right here.}
{345}{}{Well, I'll be damned. Thought those old flags were lone gone. You've got a deal. I'll trade this carbine for the Arizona flag. It's in good condition, but ammo's scarce around here. Deal?}
{346}{}{Sounds like a deal. Let's swap.}
{347}{}{Trading junk for more junk? No thanks.}
{348}{}{I'll hang the flag up after closing. Thanks a bunch.}
{349}{}{You welcome. Nice doing business.}

{350}{}{Got a question about the pinball machine.}
{351}{}{Shoot.}
{352}{}{Nah, never mind.}
{353}{}{Where'd this contraption come from?}
{354}{}{Been in the closet since day one. I dusted it off, Uncle Tom gave it a tune-up for a few caps, and there you have it.}
{355}{}{How do you play?}
{356}{}{Use the side buttons to bounce the ball with the star around the point slots. Longer it stays in play before dropping into the "black hole," more points you rack up. Just watch out, those electromagnetic coils can give you a jolt.}
{357}{}{Any prizes for playing?}
{358}{}{Just for kicks. Although, I promised free drinks to anyone who hits 1000 points.}
{359}{}{Is that even doable?}
{360}{}{Almost happened once. Guy dropped from exhaustion a hair shy of the mark.}
{361}{}{Managed to fix up StarBall.}
{362}{}{Nice. Here's 50 caps and a brew on the house from yours truly.}
{363}{}{Mind if I give this a spin?}
{364}{}{Go ahead. Just don't go busting it.}
{365}{}{Got it.}
{366}{}{Great job. Here's 50 caps.}
{367}{}{Whoa! You really beat the game! Here, this drinks on me. You've earned it after all that tension.}
{368}{}{Appreciate it.}
{369}{}{Hopefully the first of many.}
{370}{}{Guess I'll mosey.}

{380}{}{What's with the pendant?}
{381}{}{Got it in a trade. Looks like solid gold.}
{382}{}{I know the owner. Says it was stolen from her.}
{383}{}{Well... Not my problem. Got it fair and square. You want it back, you gotta make an offer.}
{384}{}{Hand over the pendant... now!}
{385}{}{You're barking up the wrong tree, pal. Pay up or get out.}
{386}{}{Alright, your call.}
{387}{}{No thanks.}
{388}{}{You'll regret this.}

{390}{}{The bartender over in Garage City needs some alcohol supplies.}
{391}{}{Thought that town was deader than a doornail. No caravans from there for awhile... But turns out... Oh, right, the herders. They've been causing a ruckus, blocking caravans from crossing their turf.}
{392}{}{Things are quiet there, but everyone still needs a drink, it seems.}
{393}{}{I can spare some. But that bartender's days are numbered, I reckon. Couriers don't come cheap.}
{394}{}{There's still hope for the Garage yet. I'll pass on your offer to the bartender.}
{395}{}{Good deal. But let's chat more about drinks before I head back to Garage City.}

{400}{}{Did you drop off the lunch for the mine boss?}
{1400}{}{Did you drop off the lunch for the mine boss?}
{401}{}{Not yet, boss.}
{402}{}{Get a move on before the grub's cold.}
{403}{}{Got it.}
{404}{}{Nope, not yet.}
{405}{}{I knnew you couldn't be trusted. Clear out of my bar.}
{406}{}{. . .}
{407}{}{Bad news. The mine boss is dead. Mine's a mess right now.}
{408}{}{Damn... that's rough. He was a good customer for those meals. Hope the new boss keeps up the tradition. Keep the lunch as payment.}
{409}{}{Well, guess I won't starve.}
{410}{}{Lunch instead of caps? Better hope the garrison doesn't catch wind of your stinginess.}
{411}{}{Delivered right on time.}
{412}{}{Good job. Here's your pay. Got someone else lined up for deliveries now, so you're off the hook. But swing by anytime.}
{413}{}{Later, Joe.}

{420}{}{What do you need done?}
{421}{}{I've got a lunch run for the mine boss. Pays good, but my usual guy fell ill at the worst time. Two caps if you can swing it within six hours.}
{422}{}{I'll pass on this job.}
{423}{}{I see. I'm on it.}
{424}{}{Alright, move it. Here's the brahmin sausages he ordered. Just don't scarf them down on the way.}
{425}{}{Okay.}
{426}{}{Who's your usual guy?}
{427}{}{Kid from near the courier service. His dad's keeping him under wraps for some reason.}
{428}{}{What happened to him?}

{430}{}{Got any other jobs in the works?}
{431}{}{Yeah, waiting on some meat from the hunters' camp. But they're MIA, radio's silent. Gotta check it out, see what's up. Could use a hand, in case they need help.}
{432}{}{I could lend a hand.}
{433}{}{Sorry, kind of busy. I think they'll manage without me.}
{434}{}{Camp Winon's 60 miles east, in the mountains. Watch out for wildlife.}
{435}{}{Wish me luck.}
{436}{}{Their probably just drunk or something. I'll tan their hides like pig-rats if they made me go there for nothing.}
{437}{}{About that hunters' camp...}
{438}{}{Any word?}
{439}{}{No. Didn't make it out there yet.}
{440}{}{Remind me where this camp is?}
{441}{}{Camp Winon, 60 miles east.}
{442}{}{Got it. Off I go.}
{443}{}{I checked out up Camp Winon. Looks like savages took out the hunters.}
{1443}{}{I checked out up Camp Winon. Looks like savages killed all the hunters.}
{444}{}{Damn, that's bad news! That camp kept the city fed. Can't let some savages snatch away our hunting grounds.}
{445}{}{What should we do then?}
{446}{}{Maybe Faber can spare a squad? Garrison's twiddling its thumbs anyway. And if not, we'll have to boot the savages out ourselves.}
{447}{}{Gotta drive them out! Wish Faber was here - we need the garrison active now.}
{448}{}{Got it. Later.}
{449}{}{No worries - I took care of the savages.}
{450}{}{Really? How'd you manage that?}
{451}{}{What can a bunch of savages do against modern firepower? Nothing.}
{452}{}{Turned their superstitions against 'em. A little trickery.}
{453}{}{Yikes, glad I'm not on your bad side. Camp's a major meat source for me and the city. Now we owe you big time. Thanks.}
{454}{}{People shouldn't suffer for leaders' failures.}
{455}{}{Thanks doesn't pay the bills.}
{456}{}{I was thinking of paying you 20 caps to bring back the meat. But after how that job turned out, it'd take me a year just to make it up to you. Tell you what, I'll give you a 50% discount on all my goods. Seems fair, right?}
{457}{}{Seems fair. Okay, I'm off to keep righting wrongs.}
{458}{}{I've got it covered.}
