{100}{}{You see a child in front of you.}
{101}{}{You see the child of a colonist family.}
{102}{}{I'll tell everyone you're hustling!}
{103}{}{Z-z-z...}
{104}{}{It's there, in the ruins at the entrance to the city.}

#Response
{110}{}{Hello!}
{111}{}{Will you play with me?}
{112}{}{You're not scary at all.}
{113}{}{I have nothing better to do.}
{114}{}{I'm not allowed to go into the ruins.}

{115}{}{Don't come near me!}
{116}{}{They told me I can't talk to you.}
{117}{}{You're bad!}
{118}{}{Leave me alone or I'll scream.}
{119}{}{Do you really eat children?}

{120}{}{Hello.}
{121}{}{Hello.}
{122}{}{Hello.}
{123}{}{Hello.}
{124}{}{Hello.}

{200}{}{Uh, hi. Are you looking for someone?}
{201}{}{No, no one, calm down.}
{202}{}{Yes. I'm looking for some little thieves.}
{203}{}{We didn't steal anything! It wasn't us!}
{204}{}{Really?}
{205}{}{Yes... really...}
{206}{}{I know you stole Mrs. Brandley's personal belongings. But don't worry - I won't rat you out.}
{207}{}{Well... We just wanted to help Dad. He doesn't have enough money to pay for the house, so we might get kicked out. And that nasty woman always had caps. But there was very little in her wallet.}
{208}{}{Where did you put the rest of her things?}
{209}{}{Stop lying, kid, or things will get worse.}
{210}{}{We threw them in a landfill near the entrance to the city. There were some love notes and bills... But you won't tell anyone, right? We just wanted to help Dad. We won't do it again!}
{211}{}{You can rest easy, kids. I understand.}
{212}{}{How many caps were in her wallet? Hand them over, and I'll forget about your little offense.}
{213}{}{Okay, here you go, sir... Here's the five caps.}
{1213}{}{Whatever you say, ma'am... Here's five caps.}
{214}{}{Alright. Were done.}
