{100}{}{You see your madre.}
{101}{}{You see a woman who is very familiar to you. Your mother.}
{102}{}{Goodbye, madre. From now on, I'll take care of myself.}
{103}{}{You receive }
{104}{}{ experience points for freeing your fellow villagers.}
{105}{}{Your madre has died. You need to find other members of the Villa.}
{106}{}{Your madre has died. There's nothing more to do here.}
{107}{}{We'll talk when we get out of here.}

# First Dialogue
{200}{}{? How did you... For heaven's sake, you shouldn't have taken such a risk! We would have found a way back to Villa... But of course, I'm so happy to see you. How proud your padre would be to know of the determination by his child! You've done well.}
{201}{}{I can't stand you sometimes, madre. I'm no longer a child.}
{1201}{}{I can't stand you sometimes, madre. I'm no longer a child.}
{202}{}{I wouldn't have forgiven myself if something had happened to you if I had done nothing.}
{1202}{}{I wouldn't have forgiven myself if something had happened to you if I had done nothing.}
{203}{}{Oh, yes, of course... I understand. Maybe it's this whole awful ordeal. It's changed something in all of us. I see it in your eyes, I see a slightly different person. And I don't know if that's good or bad.}
{204}{}{Well, that's the strength of our entire Villa - we are all like one big family. Everyone looks out for each other. And I'm glad to see that the journey hasn't changed those ideals in you.}
{205}{}{Right now let's think about how we can get out of this mess.}

{206}{}{I'm afraid it won't be easy. As you can see, there are only three of our people in the pen. Two more have gone missing in the mine. The rest, including your padre, were taken south to the big city of Phoenix.}
{207}{}{What did these mercenaries do to you?}
{208}{}{How can I get to Phoenix?}
{209}{}{What do you know about the missing group?}
{210}{}{How can I free you from this pen?}
{211}{}{I'll find a way to deal with these problems. Wait for my signal.}
{212}{}{So happy to see you.}
{213}{}{I'm still working on your release. Hold on.}
{214}{}{Yes?}
{215}{}{Goodbye.}
{216}{}{I see.}
{217}{}{Nothing special, don't worry. Mostly, I did the same household chores as in the Villa. Only more and harder. These colonists are so... grim. The men were made to work in the mine. They've really had it tough.}
{218}{}{They say it's a big city to the south, but I've never been there. Caravans travel between Flagstaff and Phoenix. Ask the locals, they should know something about it.}
{219}{}{Hugo and Sancho planned to dig a tunnel and escape from the mine. We haven't heard from them since.}
{220}{}{These people won't release us voluntarily. You can talk to their boss, but I don't think he'll listen to us, unless we have something to persuade him with.}
{221}{}{What about escaping?}
{222}{}{We would have escaped long ago if it weren't for these collars. They will kill us instantly if we stray too far from the camp. They say they're controlled by that big antenna opposite the pen, but none of the prisoners know anything about it.}
{223}{}{You don't really want me to go there, do you?}
{224}{}{It's not just the dangers of the journey, it's the city itself. People tell a lot of stories about it, but none of them are good. Besides, your uncle Miguel once left with a caravan to Phoenix and never returned. Try to find him, maybe he can help.}
{225}{}{Faber has released all of you. It's time to return to the Villa.}
{226}{}{We're free! Don't worry about us, we'll make our way back to the Villa on our own. Your padre needs you now. He was sent south. Save him!}
{227}{}{I'll see you back at the Villa, madre.}
{228}{}{The guards are dead, you can leave now.}
{229}{}{The collars are no longer a threat. You can take them off any time.}
{230}{}{That's good, but how do we get past the guards?}
{231}{}{I still need to think about that problem.}
{232}{}{Leave the guards to me. I'll get you out of here.}
{233}{}{Do you really know what you're doing? As soon as we try to leave the pen, the guards will attack us. We can't fight back against them.}
{234}{}{Don't worry about the guards, I know what I'm doing.}
{235}{}{Stay in the pen until I give the signal.}
{236}{}{Alright. Lead on. We'll talk when we get out of the garrison.}
{237}{}{Let's go.}
{238}{}{This is bad. I can't get you out on my own. Is there anyone who could help us?}
{239}{}{The only ones who might be able to help are the Rangers. Their base is south of the Villa, on the Colorado River. But don't rush to beg them for help. The Rangers don't offer their protection for free.}
{240}{}{What about an escape?}
