{100}{}{You see a ranger standing before you.}
{101}{}{You see a ranger in front of you, his gaze conveying unwavering determination.}
{102}{}{Once I gather my belongings, I'm hitting the road.}

#First dialogue
{200}{}{Hold it right there! Take one more step, and I'll put a bullet through your skull.}
{201}{}{Okay, okay, I'm not moving. Just don't shoot.}
{202}{}{Good. I'm a crack shot, so don't try anything funny.}
{203}{}{[More]}
{204}{}{Threatening me? You got some nerve!}
{205}{}{(swiftly aims the gun at you)}
{206}{}{Wait! Don't shoot!}
{207}{}{Son of a bitch!}
{208}{}{Take it easy. What's going on?}
{209}{}{Seems like you're a bit confused. This is a gun. It's loaded. And it'll kill you if you make a move. Got it?}
{210}{}{Got it.}

{211}{}{Hmm. (lowers the gun) You don't seem like a mercenary. Who are you, and what are you doing here?}
{212}{}{Spit it out before I turn your head into a mess.}
{213}{}{Someone's gonna get killed. But it won't be me.}

{214}{}{What? What do you want?}
{215}{}{(lowers the weapon) Hmm. Seems you're lost, huh? I pity folks like you. Maybe I should put you out of your misery with a bullet?}
{216}{}{Shoot? Me? Torment?}
{217}{}{Probably not. You're gonna be bait for mercenaries. Head outside and take a stroll. This spot's mine. Got it? Go on, move!}
{218}{}{Time for a walk. Move it!}

{220}{}{I'm just a wanderer, scavenging for useful junk in these ruins.}
{1220}{}{I'm just a wanderer, scavenging for useful junk in these ruins.}
{221}{}{Not convincing. You're either here against your will or working for the mercenaries from the garrison.}
{222}{}{Can't exactly ask the garrison for food. We have to scavenge in the ruins.}
{223}{}{I'm just after scrap metal, plain and simple.}
{224}{}{This used to be the Northern Arizona Museum, a city landmark.}
{225}{}{I'm telling the truth.}
{226}{}{I lied. But I am here for a reason.}
{227}{}{Exactly. And I aim to deliver your head to them.}

{230}{}{(raises weapon again) Seems you think I'm an idiot.}
{231}{}{You see through it, huh? I'm here for something else entirely.}
{232}{}{Explaining will take too long. I'd rather end this right now.}

{233}{}{Alright, let's entertain that. But how did you manage to bypass my traps?}
{234}{}{Trying to catch children with those? Might work on them, but I'm an experienced trapper.}
{235}{}{Just incredibly attentive, I guess.}
{236}{}{Traps? Seriously? Chinga tu madre! You should've posted a warning at the entrance.}
{237}{}{(shows wounds) Well, that's not entirely true.}
{238}{}{I don't know, luck maybe.}

{240}{}{Should've paid more attention during trap training I guess.}
{241}{}{So, you're not gonna shoot?}
{242}{}{What a stupid answer... (prepares to shoot)}
{243}{}{Hold on, hold on! I really am here for something else.}
{244}{}{[Parry attack]}
{250}{}{Not this time. You're free to go. But watch your back on the way out.}
{251}{}{Alright.}
{252}{}{Wait, I need to ask you a few things.}

{260}{}{Bounty hunter. Word is there's a hefty price on your head.}
{261}{}{That's right. Faber's got a nagging conscience, knowing there's a higher justice out there. Well, your demise will serve as a little reminder for him...}
{262}{}{Let's get this show on the road then.}
{263}{}{Hold on, I'm not looking for a fight.}
{264}{}{Yeah, I bet. Especially since I've got you in my gun sights.}
{265}{}{I've got *my* sights set on Faber's head. What do you say we team up?}
{266}{}{To hell with it, let's fight!}
{267}{}{What's your angle?}
{268}{}{My kin are locked up in the garrison's pen. I need to set them free.}
{1268}{}{My kin are locked up in the garrison's pen. I need to set them free.}
{269}{}{So that's what's driving you into the hunt? (start to lower weapon) Fits right in with Faber's style.}
{270}{}{So you're not pulling the trigger?}
{271}{}{But not mine. Take this!}

{280}{}{I'm on a mission to free my kin from captivity.}
{281}{}{Enslaved too, huh? Faber's thugs are getting bolder by the day. Used to be they only forced criminals into labor, now they're snatching up innocent folk.}
{282}{}{What about your gun? You still planning to use it on me?}

{283}{}{I'm a ranger. Justice is my game.}
{284}{}{Pleasure to meet you. But I didn't ask for backup. It'd jeopardize my cover.}
{285}{}{I'm in this area of my own accord.}
{286}{}{Then we'll find common ground. Just make sure you're not being tailed when you come this way.}
{287}{}{Got it.}

# Re-dialogue
{300}{}{Go ahead.}
{301}{}{Until next time, Ranger.}

# Traps
{310}{}{Show me your traps, or I'm gonna leave here a cripple.}
{311}{}{Only fools or traitors would ask such a thing. My survival depends on these secrets.}
{312}{}{I see. Then my fate rests on your secrets. Goodbye.}

{313}{}{C'mon, I'm a ranger too, you can trust me.}
{314}{}{Heh, new recruits always think they're special. Avoid the doorways and steer clear of the back exit.}
{315}{}{Appreciate it.}

{316}{}{Worried about a spy from town, are you? Obviously not me.}
{317}{}{Yeah, maybe... Avoid the doorways and steer clear of the back exit.}
{318}{}{Thanks.}
{319}{}{Sorry, no can do.}
{320}{}{The ranger revealed all of his traps within the building.}
{321}{}{Are you trying to get me killed?}
{322}{}{No... Fine, I'll show you. Just remember, avoid the doorways and stay away from the back exit.}
{323}{}{Thanks.}

# Questions
{330}{}{Tell me about yourself.}
{331}{}{I'm Ranger Kuyuk, from the Eastern Division of the Arizona Rangers.}
{332}{}{I have a couple more questions.}
{333}{}{I see.}
{334}{}{How did you become a ranger?}
{335}{}{The Rangers took me in when I was just a child. My village fell to slave traders, and I've dedicated my life to preventing such tragedies from happening again.}
{336}{}{Are you here alone?}
{337}{}{In Flagstaff, it's safer to work solo. Makes it easier to avoid mercenaries.}
{338}{}{Seems a tall order for just one ranger against an entire gang.}
{339}{}{Exactly. Our higher-ups prefer to stay clear of local affairs, so I took matters into my own hands. Nobody tried to stop me when I left, either.}
{340}{}{Think the Rangers will take you back after this?}
{341}{}{I'm still a ranger, badge and all. They might scold me for going rogue, but I'll still be one of them.}
{342}{}{You've got an interesting name.}
{343}{}{Not many of my tribe left. Doubt you've heard of us.}
{344}{}{Sounds like an Indian name. Mojave, Hopi...Navajo?}
{345}{}{Hmm. Surprising. Our tribes usually kept hidden from the white folks after the Rain of Fire. I left the Reservation when the slavers came.}
{346}{}{Our stories sound similar. My village suffered the same fate.}
{347}{}{I'm sorry... (hands you several rifle rounds) Take them. Seek your vengeance.}
{348}{}{Uh, thanks.}
{349}{}{Will do.}

{370}{}{Tell me about the rangers.}
{371}{}{What about them?}
{372}{}{Give me more details about the rangers.}
{373}{}{Enough about the rangers.}
{374}{}{Who are you guys, anyway?}
{375}{}{We're the guardians of Law and Order. We hunt criminals, protect settlers, and strive to restore peace to the wasteland.}
{376}{}{Uh huh.}
{377}{}{Hence, your average ranger is a skilled fighter and adept at surviving in the wilderness.}
{378}{}{Why aren't there more stories about you?}
{1378}{}{Why aren't there more stories about you?}
{379}{}{Because we don't boast. And because most folks see us merely as bounty hunters.}
{380}{}{What does it take to become a ranger?}
{381}{}{Five years of grueling training, then prove yourself on a mission. Many cadets don't make it through the training.}
{382}{}{And those who fail?}
{383}{}{Some get dusted on missions, others become guards, mercenaries, or caravan masters out in the wasteland. A lucky few find roles on base as support staff.}
{384}{}{Where's your base?}
{385}{}{Why would I share that with you?}
{386}{}{C'mon, I mean no harm.}
{387}{}{I'm interested in joining the rangers.}
{388}{}{I need the rangers' aid to free my kin.}
{389}{}{}
{390}{}{You could pass that info to my enemies. Can't risk it.}
{391}{}{Understandable concern. Let's move on.}
{392}{}{Agreed. Let's move past this.}
{393}{}{Alright, I'll show you on the map. The base sits along the Colorado River, within the walls of the old dam.}
{394}{}{Appreciate it.}

# Re-dialogue
{400}{}{Can you explain your mission?}
{401}{}{As a ranger, it's my duty to uphold law and justice. The colonists broke those rules by turning to slavery. My bullets will serve as their punishment.}
{402}{}{What was that about your mission?}
{403}{}{I want to ask you about something else.}
{404}{}{Let's return to discussing your mission.}
{405}{}{You're hurting innocent people, not just criminals.}
{406}{}{To eradicate a greater evil, sometimes we must resort to lesser ones. Collateral damage, unfortunate as it is, is sometimes unavoidable.}
{407}{}{Doesn't your conscience bother you?}
{408}{}{No.}
{409}{}{But the colonists also support law and order.}
{410}{}{Sure, but only within the confines of their oppressive colonial society, and at the expense of others. It can't go on like this. They weren't invited here, weren't asked to build a city on the backs of slaves.}
{411}{}{What's your end goal?}
{412}{}{As long as Roy Faber breathes, and there are people in his pen, I won't rest.}
{413}{}{Ambitious. No stopping until Faber's dead or the prisoners are free huh?}
{414}{}{So, you're the one who shot the garrison patrolmen?}
{415}{}{Correct. Their actions got them what they deserved.}
{416}{}{What "actions" are you referring to?}
{417}{}{Their involvement in Roy Faber's criminal activities: tyranny, slavery, banditry.}
{418}{}{Do the Rangers condone murder?}
{419}{}{Only in self-defense or for the greater good.}
{420}{}{Did you know Faber's put a bounty on your head?}
{421}{}{He should triple it.}
{422}{}{What do you know about Faber?}
{423}{}{A tyrant with grand ambitions, dreaming of his own empire. In reality, he's just a criminal who controls through fear and violence.}

{450}{}{I'm asking you to leave Flagstaff.}
{451}{}{I'm staying.}
{452}{}{Fine, stay. I don't really care.}
{453}{}{You'll regret it. You'll see.}
{454}{}{What could change your mind?}
{455}{}{I won't rest as long as slavery persists here.}
{456}{}{Your base is underwater. Don't you think you should be helping your people?}
{457}{}{What are you talking about?}
{458}{}{I don't know. Just rumors. Forget it.}
{459}{}{Well, looks like you're a little behind on the news about the dam breach. You might want to get up to speed.}
{460}{}{Dam breach? That can't be true... I need to get in contact with an outpost. If they confirm this, I'll be heading back to base.}
{461}{}{Go to it then.}
{462}{}{The general's ordered your return to base.}
{463}{}{Damn it, why can't he leave me alone?! My mission's too important to abandon now.}
{464}{}{Don't forget about your fellow rangers. Your help at base may be more critical than you think.}
{465}{}{Hmm. Perhaps you're right. Maybe I've been getting a little too wrapped up in vengeance. Alright, I'll break radio silence and head back to base.}
{466}{}{Good call.}
{467}{}{You're not being entirely honest with yourself. Think about your motives carefully.}
{468}{}{My motives are to stamp out injustice in these lands.}
{469}{}{Well, it seems futile to argue. Stay if you must.}
{470}{}{Seems persuasion's out of the question. I'm leaving.}
{471}{}{No. Your motives are driven by your past.}
{472}{}{What do you know about my past? I've fought so much, I've forgotten about peace... Home, family... All lost because of scum like Faber!}
{473}{}{Like I said. Cease the bloodshed. Return to your people.}
{474}{}{If vengence is all you can think of, I won't be able to sway you. Keep fighting then.}
{475}{}{I'm staying.}
{476}{}{I guess I am a little too bent on vengence. The general did warn me about this... Alright. I'm leaving Flagstaff and heading back to base. Thanks, friend.}
{1476}{}{I guess I am a little too bent on vengence. The general did warn me about this... Alright. I'm leaving Flagstaff and heading back to base. Thanks, ma'am.}
{477}{}{Best of luck.}
{478}{}{Safe travels.}

{480}{}{Faber's dead. Is that enough for you?}
{481}{}{So it's true? (sighs deeply and pauses) You know, I don't feel anything at all. I thought rooting out evil would bring me peace. But now I finally see. Killing Faber won't solve anything. Another tyrant will rise in his place, and the cycle will continue... People never change. The general was right about me being consumed. Thank you for your help. It's time for me to head back to base.}
{482}{}{Well, glad that's settled.}
{483}{}{Okay, good luck then.}
