{100}{}{You see a miner.}
{101}{}{You see a dirty, emaciated man.}
{102}{}{You saved me from suffering.}
{103}{}{Wow, you're one of the brave ones. I won't tell anyone who killed Lash.}

{110}{}{Oh! Oh oh!}
{111}{}{Have mercy, master!}
{112}{}{I'm in a lot of pain!}
{113}{}{Help me! I beg you!}
{114}{}{Ah! Help, I'm dying!}

{120}{}{You're the best.}
{121}{}{I want to be righteous, like you.}
{122}{}{Words can't express my gratitude.}
{123}{}{The new overseer is better than the old one.}
{124}{}{Lash was a damn beast.}
{125}{}{How did you manage to get rid of Lash?}

#Dialogue
{200}{}{Thanks, friend. I thought I was done for. But now I don't know what's better - to keep suffering in this hard labor or to find peace in the next world?}
{1200}{}{Thank you, ma'am. I thought I was done for. But now I don't know what's better - to keep suffering in this hard labor or to find peace in the next world?}
{201}{}{Who beat you like this?}
{202}{}{It was that overseer over there. All the prisoners here hate him; they even gave him a nickname - Lash. He's as evil as the devil himself. Just give him a reason and he grabs the whip.}
{203}{}{So what did you do to piss him off this time?}
{204}{}{I have no strength left because of the work. I collapsed while pushing the cart and scattered all the ore.}
{205}{}{And that made him beat you? You're in a tough spot here...}
{206}{}{That's an understatement. We're behind schedule, and there are rumors about giant rats in the mine. The bosses are angry and take it out on us.}
{207}{}{I see.}
{208}{}{Hey, you don't seem to be one of the guards. Are you a caravan driver or something?}
{209}{}{No. I'm looking for my relatives. Peasants from Villa. Do you know anything about them?}
{210}{}{Everyone here knows them! But I have to disappoint you - Sancho and Hugo went underground and haven't returned yet.}
{211}{}{Thanks for the information. Rest if you can.}
{212}{}{None of your business.}
{213}{}{Okay, okay. My job is to obey, master. But thanks for the help. I'm in your debt.}
{1213}{}{Okay, okay. My job is to obey, mistress. But thanks for the help. I'm in your debt.}
{214}{}{That's it. Get out of my way.}
{215}{}{Glad to help. Goodbye.}
{1215}{}{Glad to help. Goodbye.}
{216}{}{Actually, I'm looking for my family. Peasants from Villa. Do you know anything about them?}

{220}{}{Hey, it's my savior!}
{1220}{}{Hey, it's my savior!}
{221}{}{Take care.}
{222}{}{Quiet, fool.}
