{100}{}{You see a colonist.}
{101}{}{You see a citizen of Flagstaff.}
{102}{}{You'd better not bother me.}
{103}{}{You psycho! Why did you kill my servant?! Who's going to pay me back for that?!}

#Random remarks
{110}{}{You're worthless.}
{111}{}{Mole-rat spawn!}
{112}{}{You're good for nothing.}
{113}{}{Get up and wipe your nose, you worthless bastard.}
{114}{}{I don't even want to dirty my shoes kicking you.}
{115}{}{Is this what I paid my caps for?}
{116}{}{Looks like the jailers overcharged for you, you lump of dirt.}
{117}{}{*Nudges the servant with his foot*}
{118}{}{Are you baring your teeth at me?!}
{119}{}{Are you going to dig your own grave? How about a shoe to the face?}
{120}{}{Remember who your master is.}

#First dialogue
{200}{}{(You see a thin man angrily hitting and kicking a constantly apologizing servant.)}
{201}{}{Hey! Why are you hitting this man?}
{202}{}{This isn't a man, it's my property. I bought him as a servant, and he's a terrible one. I have to beat the filth out of him to make him useful. And what do you care? Move along and mind your own business.}
{203}{}{You're right, it's none of my business.}
{204}{}{Glad we understand each other. Get up! You'll sleep outside tonight. For now, clean the kitchen floor. And make it spotless!}
{205}{}{[More]}
{206}{}{A beaten and exhausted servant just makes you look bad.}
{207}{}{I didn't ask for your opinion!}
{208}{}{Hmm, you might have a point. Fine, I'll be lenient today. But only today.}
{209}{}{[More]}
{210}{}{I'll pay you 5 caps if you leave him alone.}
{211}{}{Oh, did you hear that, little runt? Someone's willing to pay 5 caps for your peace. Who knew you could actually be worth something, huh?}
{212}{}{Here's 5 caps.}
{213}{}{Not bad. Slave! You can have a day off today.}
{214}{}{[More]}
{215}{}{If you hit him again, you'll regret it.}
{216}{}{REALLY? Listen up, hayseed. This city has its own rules. If you break them, someone will call the guards. Then we'll see who regrets it.}
{217}{}{Fine, fine, I'm in a bad mood today... But if you touch me, I'll call the guards. You won't like that.}
{218}{}{[More]}
{219}{}{}
{220}{}{Let me give you some advice. I don't know what you're thinking, but servants in this colony need to be kept on a leash. Otherwise, things could end badly... See you.}
{221}{}{Goodbye.}
