{100}{}{You see Hugo.}
{101}{}{You see a slave. When you look closely, you recognize your fellow villager despite his dirty, emaciated face.}

{102}{}{Oops, I hope no one in the Villa finds out about this...}
{103}{}{Traitor! You've been possessed by Diablo!}
{104}{}{Now Hugo will never return to the Villa.}
{105}{}{Hugo returns to Villa.}
{106}{}{Of course, friend, as you wish.}
{107}{}{See you at the Villa, amigo.}

#First dialogue
{200}{}{? Holy heavens, it's you! We'd almost lost hope.}
{201}{}{I'm here to free you.}
{202}{}{You're just in time! We just need to get to the exit, and then we'll manage on our own.}
{203}{}{Tell me what happened first.}
{204}{}{It's all Sancho's fault! He came up with the dumb idea to use explosives. Neither of us knew how to handle it, but he decided to try anyway. Ask him! Sancho's the 'boss' here.}
{205}{}{Stay here. I'll talk to him first.}
{206}{}{We're at the entrance. Freedom is very close.}

{207}{}{Si?}
{208}{}{That rat was huge and vicious! I'm actually hungry enough to fry it up...}
{209}{}{Okay, let's move.}

{210}{}{Hey Hugo, remember when you ratted me out?}
{211}{}{Wha... wait...}
{212}{}{I took my padre's things without asking, and you told him. I was punished. Remember?}
{1212}{}{I took my padre's things without asking, and you told him. I was punished. Remember?}
{213}{}{(smiling sheepishly) Yeah, hehe, it was... (confused) that...}
{214}{}{I'm here now, saving your skin. How do you feel, Hugo?}
{215}{}{(mutters under his breath) S-sorry... sorry for everything! (wipes away tears)}
{216}{}{Bettr be. Remember this day... 'friend'.}
{217}{}{Come on, I'm not angry. Calm down. Let's get out of here.}
{218}{}{Come on, forget it.}
{219}{}{It's okay, Hugo, don't worry about it.}

{222}{}{Thanks for everything! We'll find our way from here. You need to save the rest of the Villa's residents. We're not much use after what we've been through. Good luck.}
{223}{}{Okay. I'll see you back at the Villa.}
{224}{}{Yeah, listen, Sancho says we need to blow up the mine. Otherwise, the tragedy will repeat itself. If you blow it up, the enterprise will go bankrupt and stop looking for new slaves.}
{225}{}{Blow up the mine? I'm in.}
{226}{}{Sancho is talking nonsense. The explosion will only add more work for the slaves.}
{227}{}{Really, you'll do it? Then find the explosives in the warehouse inside the mine. The administrator has the key. Good luck.}
{228}{}{But the enterprise will continue finding and using slaves. Our escape won't change anything. Don't you get it? Think about it. We need to go. Good luck.}
{229}{}{I'll think about it. Now get out of here.}
