{100}{}{You see Larry.}
{101}{}{You see a bar patron with a shabby appearance and bad manners.}
{102}{}{That's another matter. Your move. No, go to hell.}
{103}{}{Hey, you! Buy us a drink.}

{200}{}{Hey! Scruffy little hicks don't usually stop in Garage City.}
{201}{}{[Ignore]}
{202}{}{Life here seems too fast for hicks like him. You probably thought you could keep up with it, huh?}
{1202}{}{Life here seems too fast for hicks like her. You probably thought you could keep up with it, huh?}
{203}{}{I'm faster than you think.}
{204}{}{(The loudmouth's face drops and after a short pause he returns to the counter) Okay, if you say so. But fast folk forget a lot. Like gettin' the good guys drinks.}
{205}{}{I'm not buying someone a drink for nothing.}
{206}{}{Okay, I'll remember that.}
{207}{}{Listen, leave me alone. I'm just trying to find my family.}

{208}{}{I see you're not too fond of my company? Well, if that's the case, the rest of the city won't suit you either. If I were you, I'd pour everyone a drink to leave a good impression.}
{209}{}{Fuck off, I don't have time for this nonsense.}
{210}{}{(purses his lip with contempt and hatred) That kind of back talk in this city can get you a pipe to the head. I'll forget what I heard if you get me a drink.}
{211}{}{What did you call me, dumbass?}
{212}{}{What's the matter, can't keep up with me? Life here moves too fast for folks from the desert. You probably thought you could keep pace, huh?}
{213}{}{Okay, I'm just gonna leave. Right now, without trouble.}
{214}{}{So you barge into our sweet little town, disturb the peace of this bar, and think you can just leave?}
{215}{}{Uh, yeah.}
{216}{}{Get us a drink. Or you can go to hell.}

{220}{}{What do you want?}
{221}{}{Nothing.}
{222}{}{Nothing? Then why the hell are you bothering me?}
{223}{}{Just forget it.}

{230}{}{Who are you?}
{231}{}{Who am I? I'm the one who knows every damn corner of this city. The one you share with, and the one you speak to with caution. Choose your words wisely.}
{232}{}{Do you even have a name?}
{233}{}{My name is Larry. Do I need to repeat it? Or can you remember it the first time?}
{234}{}{Whatever you say, Larry.}
{235}{}{I'm tired of your attitude. Time to knock that smile off your face!}
{236}{}{My name is Larry. I'm here... doing different things. For example, I protect the city when necessary. Not for free, of course.}
{237}{}{So you're not one of the scavengers?}
{238}{}{No, dumbass. I'm part of an elite group of fighters who don't like shady characters showing up in their city.}
{239}{}{And it looks like I'm on your list.}
{240}{}{So what are you gonna do? Come on, show me what you can do, sucker!}
{241}{}{No, I don't scavenge anymore. As long as Mr. Kogan pays caps, I don't need to.}
{242}{}{No, I don't scavenge anymore. That's dirty work.}
{243}{}{I see.}

{250}{}{Looks like you're stuck in this bar?}
{251}{}{I've got a lot to do. I'm just here to wet my throat. Any more questions?}
{252}{}{No, I guess not.}
{253}{}{The bartender serves crap drinks. But it keeps you warm at night. I've been waiting all year for something invigorating. But he only has crappy beer. All year.}
{254}{}{Sorry to hear that.}
{255}{}{Your ass is going to have to go outside someday.}
{256}{}{Did you see the slave convoy pass through here?}
{257}{}{I saw it. But I won't tell you anything about it. Get lost.}
{258}{}{Okay. If you don't, someone else will.}
{259}{}{You're making a big mistake.}

{300}{}{What's wrong with you? Don't like our company?}
{301}{}{Fuck off, moron.}
{302}{}{Mother fucker... I'll have to teach you some manners!}
{303}{}{[Defend]}
{304}{}{Listen, I really have to go. It's very important.}
{305}{}{Important? Hey everyone, someone has important business here!}
{306}{}{I'm going to save my people...}
{307}{}{Ooh! A noble peasant's going to save his people! Make way everyone!}
{1307}{}{Ooh! A noble peasant woman is coming to save her people! Make way everyone!}
{308}{}{Okay, that's it! I'm gonna rip your filthy tongue out, you son of a bitch!}
{309}{}{I really have to go.}
{310}{}{How about you take 10 caps, and we forget about everything.}
{311}{}{Good decision, amigo. Now get out of the bar.}
{312}{}{I've changed my mind. Give me back my caps, bitch!}
{313}{}{Uh, okay...}
