{100}{}{You see the bartender.}
{101}{}{You see a strong man in an apron. Apparently he owns this place.}
{102}{}{Okay, I won't serve you while you're wearing this armor. Got it?}
{103}{}{Sorry, but no weapons in the bar.}

#First dialogue
{200}{}{(As you approach the bar, you notice the wariness in the eyes of the bartender and the surrounding patrons). What do ya want?}
{201}{}{I'd like black coffee and a cinnamon bun, please.}
{202}{}{(the wariness of others gives way to bewilderment and laughter) I don't have anything like that. Do you really have any idea where you are?}
{203}{}{Well then, I want to know more about this place.}
{204}{}{Just wanted to take a look. Your establishment is interesting.}
{205}{}{(raises one eyebrow, then goes back to his daily routine, cleaning the bar counter of some stains) This is a bar. I hope you know what "bar" means.}
{206}{}{Then I wouldn't mind stopping here awhile.}
{207}{}{I'm following a slave convoy.}
{208}{}{(visitors fall silent and tensely turn in your direction) Slave convoy? No. There were no such people here.}
{209}{}{Well, anyway, I think I'll just stick around a bit.}

#Re-dialogue
{210}{}{Yes?}
{211}{}{I'm outta here.}

#Pocket trash
{220}{}{Nothing could be simpler. But do you have something to pay with?}
{221}{}{Listen, my pockets are full of junk. Let's see, maybe you could make use of this?}
{222}{}{Wait a minute, I'll go through my pockets...}
{223}{}{(you dump your pocket trash on the bar, the bartender sorts through it in bewilderment) If I had such pockets, I would have become rich a long time ago. Look, there's a pre-war bill, a couple of caps, and a bullet. With all this you can buy... a whole fried iguana tail, ha ha!}
{224}{}{Phew, finally got some use out of this trash.}

#Chris from Villa
{230}{}{Didn't a guy from my area pass by here? His names's Chris.}
{231}{}{By the way. A guy passed by here, I think from your area. His name was Chris.}
{232}{}{Yah, I know him. Where did he go?}
{233}{}{He left with a caravan, but I don't know where they went.}
{234}{}{Great. Looks like I won't be hearing from him again.}
{235}{}{Chris? I don't know him.}
{236}{}{Oh, well, sorry then.}

{240}{}{Hmm. You look like an real brawler.}
{1240}{}{Hmm. You look like a real rebel.}
{241}{}{Are you sure?}
{242}{}{I'm sure. I hope you're not going to cause any problems for me?}
{243}{}{No, no problem, sir. I'm a regular visitor.}
{1243}{}{No, no problem, sir. I'm just a regular visitor.}
{244}{}{I think bars are just for brawling.}
{245}{}{Then remember a simple rule. If someone decides to make a commotion here, they will immediately end up on the street and won't be back.}
{246}{}{I understand. No problem, sir.}
{247}{}{Don't threaten me. Otherwise I'll get angry. You won't like me angry.}

#About the bar
{250}{}{What drinks do you sell?}
{251}{}{Take a look. In our area this is the best alcohol you can find.}
{252}{}{Let me think about it.}

{253}{}{So this is all firewater? You should have told me right off the bat!}
{254}{}{Seems like you're from some hick place where no one has ever heard of bars. You might be in some real trouble after a couple of sips. Still want to try?}
{255}{}{Wow, I've never seen so many strong drinks before!}
{1255}{}{Wow, I've never seen so many strong drinks before!}
{256}{}{Then congratulations on joining civilization. So what will you order?}
{257}{}{Where did you get this alcohol?}
{258}{}{Some come from caravans, others from scavengers, but it's not enough. I considered starting my own production, but the business stopped making enough to cover the cost of raw materials.}
{259}{}{I see.}

{260}{}{You can get any strong drink you'd like here.}
{261}{}{Why are you paying with caps here? We usually trade for something *useful*.}
{262}{}{Oh, you're from the wasteland. I don't know the whole story myself, but in big cities they came up with the idea of using caps as currency. It's like money before the Great War... You don't even know anything about money? Well... In general, it's for, uhh... for exchange.}
{263}{}{[More]}
{264}{}{However, caps have caught on in large cities only. They're rarely used in wastelands.}
{265}{}{Interesting idea.}
{266}{}{What idiot came up with this?}

{270}{}{Hey, where did you get this flour?}
{271}{}{A couple of strangers sold it cheap. Want to trade?}
{272}{}{This flour was stolen from the Villa by marauders. You're selling stolen goods!}
{273}{}{Maybe so, but I purchased it honestly.}
{274}{}{[More]}
{275}{}{Now listen up. You're new here and don't deserve any respect yet. If you make a fuss, you'll find yourself outside the door. This is the best case scenario. So calm down, will ya?}
{276}{}{Don't be mad. It wasn't my fault they stole from you guys.}
{277}{}{You're on my blacklist now, huckster.}
{278}{}{Okay. THIS time I forgive you.}

{280}{}{Drinks for everyone here. I'm }
{281}{}{ from Villa. And I'm treating everyone.}
{282}{}{Tryin' to earn a good name among the scavengers, huh? Well, that's how you do it. But it'll cost you 50 caps.}
{283}{}{No problem, here's the caps.}
{284}{}{That much for all these rogues? Forget it, I'm outta here.}
{285}{}{Um... I can't afford it right now. Next time, I guess.}
{286}{}{You're having trouble counting your money, right?}
{287}{}{...}
{288}{}{Hey guys! A newcomer from the wasteland wishes to introduce himself. This is his treat.}
{1288}{}{Hey guys! A stranger from the wasteland wants to introduce herself. This is her treat.}
{289}{}{Enjoy, guys!}

{290}{}{Hello. We're celebrating the extermination of the Jackals. Those savages caused problems for scavengers and travelers alike, but now things will be easier with them gone.}
{291}{}{Yea, they fought like wild dogs.}
{292}{}{Are you saying you had something to do with this?}
{1292}{}{Are you saying that you had something to do with this?}
{293}{}{I joined the attack with your people. The gatekeeper knows about this.}
{294}{}{Damn it, is that true? Well then, I'll buy you a drink on the house. Thanks, buddy.}
{295}{}{You're welcome.}
{296}{}{I told the Rangers, and they exterminated the tribe.}
{1296}{}{I told the Rangers, and they exterminated the tribe.}
{297}{}{Well, well. Anyway, whoever did this did us a big favor.}
{298}{}{Then go ahead and celebrate, guys. I've got other places that need me.}
{299}{}{Maybe...}

{300}{}{Can you tell me a bit about this city?}
{301}{}{What do you want to know?}
{302}{}{Nothing else.}
{303}{}{You either order something or bother someone else.}
{304}{}{Why is everyone looking at me sideways?}
{305}{}{Uh, okay. Hint taken.}
{306}{}{No need to be so rude, bartender.}
{307}{}{Why don't you ask them about it?}
{308}{}{What's going on around here?}
{309}{}{Nothing special. The city is impoverished, and no one knows what to do about it.}
{310}{}{The good news is that the cartel has finally got one of the factories up and running. This will breathe life into a dying city.}
{311}{}{Why do you live in such terrible huts?}
{312}{}{You can find better houses among the local ruins.}
{313}{}{That's all I wanted to know.}

{320}{}{If you're going to get rowdy, go outside. I don't need any drunken fights here.}
{321}{}{He brought it on himself.}
{322}{}{I don't care which one of you started the fight. Just watch yourself and don't make trouble while you're here.}
{323}{}{Don't worry, it won't happen again.}
{324}{}{The only entertainment in this hole is drunken fights.}

#Slave convoy
{330}{}{I'm pursuing a slave convoy. Do you know anything about this?}
{331}{}{I don't know nothing. How about a glass of something strong?}
{332}{}{Okay, forget it, I'll ask someone else.}
{333}{}{You must know something.}
{334}{}{Listen, I don't want any problems with Mr. Kogan. He did business with those slave owners. So talk to him.}
{335}{}{Maybe later. I want to hang out a little longer.}
{336}{}{Okay, I'll go see him.}
{337}{}{Don't worry. I won't cause any problems with Kogan.}
{338}{}{Tell that to someone else. Just don't get me involved.}
{339}{}{Looks like you're all tangled up in this already.}
{340}{}{Really? Well, you know, there are rumors about you... not particularly flattering ones.}
{341}{}{Seriously? I didn't hear anything.}
{1341}{}{Seriously? I didn't hear anything.}
{342}{}{If you don't talk, I'll tear this bar apart just like I did that guy's face.}
{343}{}{Okay, okay. There is no need to get all violent. Agreed?}
{344}{}{Then be smart and tell me everything you know.}

{350}{}{Yes, they stopped by on their way back through town. I haven't had such an influx of clients for a long time.}
{351}{}{That's *great* that your business has taken off. But I need to know where the convoy is headed.}
{352}{}{I don't care about your bar. Tell me where they went.}
{353}{}{Wait a minute, are you saying the city benefited from this slave thing?}
{354}{}{The motel guy and I made good money, and Mr. Kogan signed a couple of new contracts. Even ordinary scavengers found a use for it. These slave traders seemed to breathe life into our dump. At least for a little while.}
{355}{}{Then the convoy headed east to the town of Flagstaff. By the way, Mr. Kogan conducted business with the slavers. Now that he's dead, you could check out his notes in the garage if it's that important to you.}
{356}{}{The convoy headed east to the town of Flagstaff. Walk along Federal Highway 40, you won't miss it. It should take about a week to get there.}
{357}{}{Thanks for the info. I gotta go.}
{358}{}{Now I know that you were involved with the raid. And I won't forget that.}

{360}{}{What's the problem with getting alcohol?}
{361}{}{Tequila and beer used to be brought from the south. But now that route's closed. I'm not against buying booze from Flagstaff, even at a premium, but we don't even have a regular caravan with them. I'll need a courier for negotiations.}
{362}{}{I'm just heading there. Maybe I can talk to someone about getting alcohol?}
{363}{}{Things are really bad for you. I hope you figure it out somehow.}
{364}{}{Go for it. Otherwise, I can't even send a letter there. Find a local bartender there and convince him to send drinks here.}
{365}{}{Agreed. I'll find one and come back with an answer.}
{366}{}{Bye.}
{367}{}{The bartender in Flagstaff said he's willing to supply you with alcohol.}
{368}{}{Holy shit, great job! Even if the price of alcohol goes up, my shelves won't be so empty.}
{369}{}{Ahem. You're not thinking of leaving my work without payment, are you?}
{370}{}{My pleasure, buddy. Now the whole city can get shitfaced.}
{371}{}{Here's 100 caps for your courier service, and I'll throw in my old shotgun. I know it's not much, but I have big expenses coming up!}
{372}{}{I've never been swindled like this before. Goodbye, cheapskate.}
{373}{}{Thanks, that's enough. I'll sell the gun in a neighboring town. Nice doing business.}
{374}{}{Deal. But for the moment, I'll hang around here a bit longer.}

#Trade route quest
{400}{}{Do you have anything edible?}
{401}{}{Something like meat? There's a problem with that.}
{402}{}{Why?}
{403}{}{Trade has died down recently. Fewer caravans with provisions are coming into the city, because we have nothing to trade. You have to survive on your own. Some hunt coyotes, some catch lizards, and some try to grow crops.}
{404}{}{Hunting? I'd like to join in with that.}
{1404}{}{Hunting? I'd like to help with that.}
{405}{}{Is there really nothing that can be done?}
{406}{}{Is that all you can do?}
{407}{}{Well, the gatekeeper said that wild brahmin were spotted in the desert. Some scavengers are going to find them. You can join the hunt too.}
{408}{}{Interesting. I'll talk to the gatekeeper. See you.}
{409}{}{That's not my thing.}

{410}{}{The gatekeeper says you joined in the hunt for the brahmin?}
{1410}{}{The gatekeeper says you joined in the hunt for the brahmin?}
{411}{}{Yes, that's true.}
{412}{}{Maybe I did. Do you have a problem with that?}
{413}{}{Then explain what the hell happened with that and where are our people?!}
{414}{}{Your people, uh, fell to a savage brahmin. It turned out to be stronger than anyone could have imagined.}
{415}{}{Damn. No meat, no people. Eh, looks like we're in for a hungry season again...}
{416}{}{Is it really that bad?}
{417}{}{So you know what really went down there. You're not going go blabbing about it, are you?}
{418}{}{Me? Nah, I won't say a word.}
{419}{}{Cut out my tongue if I spill that we stole the Brahmin.}
{420}{}{Alright. Here's your share of the meat. Thanks, you're saving us from starving.}
{421}{}{So, it's the hunger season for you folks?}
{422}{}{So you just ran off, leaving everyone else to deal with the mess. Do you have any idea what our guys went through out there?}
{1422}{}{So you just ran off, leaving everyone else to deal with the mess. Do you have any idea what our guys went through out there?}
{423}{}{Just drop it.}
{424}{}{I figured as much. Don't think folks around here forget quick, especially not in these hungry times.}
{425}{}{So it's lean season for you?}
{426}{}{Because of you, we lost a whole carcass of clean meat! It could feed one person for a whole year!}
{427}{}{I've got some ideas saved up.}
{428}{}{Oh really? Good. 'Cause otherwise, we might have to roast you instead of that brahmin. We're in a hunger season here, and there isn't enough food for everyone.}
{429}{}{Is it really that bad?}

{430}{}{Exactly. Previously, we traded with southern cities, exchanging parts for products. But not only do we now have almost nothing to trade, but further, San Brahmin isn't selling their meat to anyone anymore.}
{431}{}{And nothing can be done?}
{432}{}{I don't know. We don't have caravans anymore. I can't even contact the traders.}
{433}{}{Looks like you have a problem here.}
{434}{}{One more on the pile. Listen, you seem to be heading for those parts, right? If you're in that area, let the merchant in the square know how things are here. Maybe he'll open up our trade route.}
{435}{}{I doubt I'll ever end up in those places.}
{436}{}{Okay, I'll talk to him if I'm around there.}
{437}{}{I could try to setup something.}
{438}{}{You'll be doing us, and yourself, a big favor if you do this. Find the merchant in the square in San Brahmin and persuade him to reopen the trade route.}

{440}{}{So, have the caravans returned from the south?}
{441}{}{Business is picking up again, thanks to you. We're finally getting meat from San Brahmin, so the city won't face a famine. Plus, the bar's cap turnover has increased. Here, take a hundred caps as your share of the deal. Thank you!}
{442}{}{You're welcome.}
{443}{}{The resumption of trade will boost the turnover of jerky and caps in the bar.}
{444}{}{There won't be any caravans coming. San Brahmin has formed an alliance with the Rangers.}
{445}{}{That's bad news... This town won't last long on just coyote and iguana meat.}
{446}{}{So what's to be done now?}
{447}{}{Buy meat from the rangers.}
{448}{}{I could buy meat from the rangers, but it'll come at a steep price. And I'm not thrilled about the idea of kowtowing to them. Garage City's relationship with them is already on thin ice, you know. But it seems we've got no other option now.}
{449}{}{It's better than nothing. I'll talk to someone at their base.}
{450}{}{It's better than nothing. Good luck.}
{451}{}{Well, none of the rangers will listen to me. Been down that road before.}
{452}{}{I have bad news. No one in the ranger territory wants to trade food with you.}
{453}{}{I understand. Thanks for trying.}
{454}{}{Good luck. Hang in there.}
{455}{}{Some people in the ranger territory have agreed to trade food with you.}
{456}{}{Well, well... business will be picking up, thanks to you. With food coming in again, the city won't be facing famine. But the Rangers' presence has already left its mark on my establishment. Maybe it's for the better, maybe not. Either way, thank you. Here, take a hundred caps as your share of the deal.}
{457}{}{Thanks. And you're welcome.}
{458}{}{Sorry to say, but there won't be any caravans coming. The tribes have become bitter towards outsiders after a series of murders.}

{459}{}{Is it true you made a trade for the brahmin? Damn, have a beer on the house, buddy. Garage City owes you.}
{460}{}{Just doing my part.}
{461}{}{Thanks. I just tried to do the right thing.}