{100}{}{You see a resident.}
{101}{}{You see one of the few residents of Garage City.}

{110}{}{So you're just passing through? That's good.}
{111}{}{You better leave. There's no room for new settlers here.}
{112}{}{First time in a big city?}
{113}{}{Garage City is a great place, you'll love it here.}
{114}{}{Are you planning to stay here?}
{115}{}{We have our own rules here, peasant.}
{116}{}{I don't get why people still come to this forgotten city.}

{120}{}{Hello! How are you?}
{121}{}{Holy shit, look who it is. How long are you here for?}
{122}{}{How's the crop doing, amigo?}
{123}{}{Hello, amigo.}
{124}{}{Sorry we didn't give you a proper welcome.}
{125}{}{We didn't know the villagers of Villa were so friendly.}
{126}{}{Do you need help?}

{130}{}{Stay away from me.}
{131}{}{Stick to your farm, peasant, and don't bother me.}
{132}{}{Tell your elder he's a greedy, arrogant bastard.}
{133}{}{Your Villa has never been known for its good people.}
{134}{}{Are all the inhabitants of your Villa as cunning and greedy as you?}
{135}{}{Now I get why Villa sets such high prices.}
{136}{}{I'll be honest. I was happy to see your kin on their knees.}
{137}{}{When we had a famine, you raised prices.}
{138}{}{Get lost, you dirty peasant.}
{139}{}{Villa got what it deserved.}
