{100}{}{You see Frank.}
{101}{}{You see one of the few residents of Garage City.}
{102}{}{Uh-oh, I need to find a toilet right now...}
{103}{}{Frank is in no condition to talk right now.}
{104}{}{Boo-uh...}
{105}{}{Hrrr...}
{106}{}{After a good drink, Frank passes out in his tattered chair.}
{107}{}{Uh-oh...}
{108}{}{I'm not feeling well...}

#Before the quest
{200}{}{Hey, this is my house. What do you want?}
{201}{}{I'm a thief.}
{202}{}{Great. Just what I needed. Get out of here, you idiot!}
{1202}{}{Wonderful. Just magical... Get out of here, you impudent whore!}
{203}{}{Bye.}
{204}{}{Hey, just kidding. I'm your new neighbor.}
{1204}{}{Hey, just a joke. I'm your new neighbor.}
{205}{}{Who are you kidding? No one comes to this city willingly. There's no work here! But if you really want to live next door, then do me a favor and don't bother me.}
{206}{}{Okay. As you say.}
{207}{}{I'd like to meet my new neighbors.}
{208}{}{Why so much distrust of neighbors?}
{209}{}{}
{210}{}{Do me a favor and don't bother me.}
{211}{}{Why so much distrust of neighbors?}
{212}{}{Okay. As you say.}
{213}{}{You can't trust anyone in this town. Even neighbors will eye your goods. Step outside, and someone will use a master key to get into your lock.}
{214}{}{Did something get stolen from you?}
{215}{}{Yes, things are going missing all the time. It started getting worse when the mine ran dry leaving lots of people with no income.}
{216}{}{What exactly was stolen from you?}
{217}{}{My welding machine. It's valuable. There are only a few working ones left in the whole city. It provided good income. Now what am I supposed to do?}
{218}{}{I see. Maybe I can look for it.}
{219}{}{Really? Or is this a cunning plan - steal it first, then offer to 'find' it? But why am I blaming you? You've just arrived, and it was stolen earlier. Okay, if you find my things, I'll buy them back.}
{220}{}{Alright, I'll do it.}
{221}{}{Don't worry about it. The thief will be punished. As a ranger, I am sworn to uphold the law in these lands.}
{1221}{}{Don't worry about it. The thief will be punished. As a ranger, I am sworn to uphold the law in these lands.}
{222}{}{Huh? So you're a ranger? Why am I finding this out just now? I don't need the 'law' here! I'm a free resident and won't kneel to you!}
{223}{}{It's not your concern anymore. I'll deal with the thief. Wait for the result.}

#After receiving the quest
{230}{}{You again? What do you want?}
{231}{}{People are talking about you lately. What's brings you here?}
{232}{}{Hello, neighbor. What's new?}
{233}{}{Just wanted to say hello before I leave.}

{240}{}{What do you do, Frank?}
{241}{}{I make statues. They sell well throughout the Wasteland.}
{242}{}{Must be a lucrative business?}
{243}{}{Seriously?}
{244}{}{No, not really. The mine is running out of stuff to scavenge, and there's little work. I used to work for a cartel, mining and repairing old things. Now, I can barely make ends meet.}
{245}{}{Sorry to hear that. Can I ask another question?}
{246}{}{Sad story. Bye.}

{250}{}{About that welding machine.}
{251}{}{Any leads?}
{252}{}{No, but I still hope to find it.}
{253}{}{Any idea who could have taken it?}
{254}{}{If I knew, I'd have it back by now. The thief is keeping a low profile. We'll have to be cunning to catch them.}
{255}{}{I see.}
{256}{}{Here's your welding machine.}
{257}{}{You really found it! I thought it was hopeless. Who stole it?}
{258}{}{It was, uh, in the ruins. Not sure who put it there.}
{259}{}{Hmm, either you have an incredible intuition, or you're just covering for the thief. Either way, thanks. Here are your }
{260}{}{ caps.}
{261}{}{You're welcome.}
{262}{}{It was Todd from the trailer.}
{263}{}{Ha! Todd thinks he's the smartest one around here. But sooner or later, justice finds everyone, no matter where they are. Okay, pass it over. Here are your }
{264}{}{ caps. But don't say a word to anyone.}
{265}{}{No problem.}
