{100}{}{You see Eugene.}
{101}{}{You see a teenager. His hands are stained with dirt and rust, clearly he enjoys tinkering with equipment.}
{102}{}{You wanted a better life, boy? This is the best I can offer.}
{103}{}{Sorry, kid, but in this life, only pain and suffering awaited you.}
{104}{}{Eugene has reached his destination.}
{105}{}{Wow!}
{106}{}{As long as Eugene is on your team, you receive a 20-point bonus to repairing broken equipment.}

#Floating remarks when visiting locations:
{120}{}{ }
{121}{}{Wow! I've never seen anything like it!}
{122}{}{Is this a real working radio station? That's wild!}
{123}{}{ }
{124}{}{Let's get out of here, this place scares me.}
{125}{}{You're lucky to have a house like this. I have to live in a hut made of trash.}
{126}{}{I heard about this city, but I never expected to be here!}
{127}{}{I don't know why, but I don't like this place.}
{128}{}{This doesn't look like a ranger base. Are we going the right way?}
{129}{}{What are all these people doing?}
{130}{}{What... what happened here?!}

#Final dialogue
{190}{}{Thanks for everything. These Rangers are tough guys, and their dam is a real fortress. I'm so happy!}
{191}{}{It's good that you like it here. Have fun.}
{192}{}{Pull up your pants, kid. You still have a lot to learn.}
{193}{}{Hello again.}
{194}{}{See ya, kid.}

{195}{}{A lot of bad things are said about you in the wastelands. Are they true?}
{196}{}{Honestly, you're just a means to an end for me. No more.}
{197}{}{That's just the gossip of my enemies. Ignore it.}
{198}{}{I thought so...}
{199}{}{Hmph.}

#First dialogue
{200}{}{Who are you? Hey, you're not from around here!}
{201}{}{Uh, yeah.}
{202}{}{Then where are you from? Are you enslaving peasants too?}
{203}{}{Actually... YES!}
{204}{}{Get away from me!}
{205}{}{Hey, don't be such a wuss... I'll spare this shithole.}
{206}{}{On the contrary, I going to free them. What do you know about the attack on Villa?}
{207}{}{Nothing. Better leave before the others give you a "warm" welcome.}
{208}{}{What do you mean by that?}
{209}{}{Okay, okay, I don't think I'll be staying here long.}
{210}{}{Well, this place is getting pretty bad. There won't be any stuff left in the ruins soon. Then the cartel will fall apart, and all that'll be left for the residents will be a life of banditry. I wish I could just get out of this hellhole!}
{211}{}{Where would you go if you could?}
{212}{}{To the Rangers. Or just head south, where there's at least some kind of civilization.}
{213}{}{You have ambitious plans. Adios, muchacho.}
{214}{}{What do you know about the raid on Villa?}
{215}{}{Hi.}
{216}{}{See ya, kid.}
{217}{}{My dad doesn't like people just walking into our house.}

#In a team
{220}{}{What are we doing here?}
{221}{}{When are we going to get to the Rangers?}
{222}{}{Are we there yet?}
{223}{}{I'm tired...}
{224}{}{Let's take a break, okay?}
{225}{}{I can't wait to see the Ranger Dam.}
{226}{}{Do you know exactly where to go?}
{227}{}{It must be nice to travel with Rangers.}
{228}{}{Is it true that Rangers drink their own urine while traveling?}
{229}{}{I wish I could see the Ranger General himself!}

{230}{}{Wait here, I'll be back soon.}
{231}{}{Let's go.}
{232}{}{Put that down.}
{233}{}{But you'll protect me, right?}
{234}{}{Take it off.}
{235}{}{Whatever you say.}
{236}{}{I just wanna get home as quick as I can... Though... I don't know what I really want anymore.}
{237}{}{I don't like those other guys. Are they coming with us too? Then I'm not going.}
{238}{}{Not a good idea, kid.}
{239}{}{Eugene doesn't trust your crew. He'll only go with you.}

#Joining the team
{300}{}{Hey kid, the Rangers are interested in your skills. I'm here to take you to the base.}
{301}{}{What?! Really?! Amazing! Yes, I dreamed about this ever since I first saw a Ranger. But...}
{302}{}{But?}
{303}{}{Dad won't let me go. He doesn't even want to hear about the Rangers and thinks I should be a scavenger like him. But I'm not interested in digging through scrap metal, I want to repair it!}
{304}{}{Exactly. Your talents will never flourish here. With the Rangers is where you should be.}
{305}{}{I can't just run away. And if I do, the locals will blame the Rangers, and turn against them. They already treat them with contempt. Can you talk to my dad? Maybe he'll listen to you?}
{306}{}{Okay, I'll talk to him.}
{307}{}{The Rangers are still interested in you.}
{308}{}{That's great... But I can't leave until my dad agrees.}
{309}{}{Okay, I'll talk to him.}
{310}{}{Your father has agreed. You're free to go.}
{311}{}{Really?! I didn't even hope. I thought he would never allow it... So when do we leave?}
{312}{}{Right now. Let's go.}
{313}{}{Your father is dead. Now you're free.}
{314}{}{How?! But... I didn't think it would turn out like this. (sobs) Whatever he was, he only wanted the best for me... (calms down) Well, now I definitely have nothing to lose. When do we leave?}
{315}{}{Right now. Let's go.}
{316}{}{How about a sneaky dose of scorpion venom?}
{317}{}{This isn't serious, is it? Then I'll never forgive you!}
{318}{}{Want to just run away?}
{319}{}{Then the Rangers here will be treated even worse than they are now. And I won't get far on my own.}

#If the dam is broken
{320}{}{I've got some bad news: the Ranger base has been destroyed.}
{321}{}{It can't be! I was so hoping that everything would work out... that I wouldn't have to dig through trash anymore for a couple of caps... But I don't want to go back home either. What should I do?}
{322}{}{You won't survive alone in the desert, and what's left of the Rangers have no time for you right now. Go back home.}
{323}{}{Now no one will pay me to guard your ass. You're on your own kid. Disappear.}
{324}{}{Dad warned me not to trust you. I'll find my own way home!}
{325}{}{Off you go then.}
{326}{}{Yah, I guess... I can't believe it was all for nothing!}
{327}{}{Well, maybe life in a junkyard won't be so bad. Let's go.}
{328}{}{Here you are at home. What's the matter?}
{329}{}{You know... This journey with you wasn't in vain. I saw so much, discovered a whole world I knew nothing about. After all this, I won't be able to live as before. Someday, I'm gonna definitely go south.}
{330}{}{Well, that's good to hear, but a little sad. Good luck kid.}
{331}{}{Now you can decide for yourself. My job is done. Take care kid.}
