{100}{}{You see a scavenger.}
{101}{}{You see a scavenger wearing a welding helmet.}

{110}{}{What are you doing here?}
{111}{}{Spying?}
{112}{}{Did Kogan send you?}

{120}{}{Lucas knows what he's doing.}
{121}{}{Lucas and I have been through a lot together.}
{122}{}{Trayvon must be so mad right now. Ha ha...}
{123}{}{This plant is our last hope.}
{124}{}{We were the first to open the plant, so now it's ours.}
{125}{}{Kogan will have to make concessions.}

{130}{}{We're lucky to have you.}
{131}{}{Thanks for your help.}
{132}{}{You're always welcome here.}
{133}{}{We're in charge now. Thank you.}
{134}{}{I don't know how this would have ended if it weren't for you.}
