{100}{}{You see a mechanic.}
{101}{}{You see a hard worker, busy fixing old junk.}
{102}{}{Now the mechanic's items will contain more useful parts and caps.}
{103}{}{Now the mechanic's products will contain even more useful items and caps.}
{104}{}{No creo en mis ojos! Is this really power armor?!}

{105}{}{«I can't believe my eyes!» Is this really power armor?!}
{106}{}{«Hello!»}
{107}{}{«Yes sir?»}
{1107}{}{«Yes, ma'am?»}


{200}{}{Oh! Salute, companeros! New to the city?}
{201}{}{Is this a city?}
{202}{}{Why not, senor? We have everything a city needs - a bar, a hotel, housing, work. Stick around, you'll see for yourself.}
{1202}{}{Why not, senorita? We have everything a city needs - a bar, a hotel, housing, work. Stick around, you'll see for yourself.}
{203}{}{Eh, I'll think about it. And who are you?}
{204}{}{My name is Pedro Fuerte... or just Pete.}
{205}{}{I'll call you Pete.}
{206}{}{Whatever's more convenient, sir.}
{1206}{}{Whatever's more convenient, senora.}
{207}{}{Nice to meet you, Pedro.}
{208}{}{(smiles) Likewise, amigo. The garage doors are always open to good folks. How can I help?}
{209}{}{I guess I'll come by later.}

{210}{}{Salute!}
{211}{}{Adios.}
{212}{}{Can you answer a couple of questions?}
{213}{}{Enough talk. Now I want to look around.}
{214}{}{Tell me more.}
{215}{}{You call this handful of filthy shacks a city?}

#Questions
{220}{}{Si, senor?}
{1220}{}{Si, senora?}
{221}{}{What is this place?}
{222}{}{This is Mr. Kogan's garage - the headquarters of the scavenger cartel. We recycle waste from the ruins. The useful stuff goes with the caravans, and the rest, well, it gets sorted out. Need parts or wires? We can trade.}
{223}{}{Tell me about your work.}
{224}{}{I'm a mechanic, sir. I recycle what the scavengers bring in. Fix it if needed and get it ready for shipping.}
{1224}{}{I'm a mechanic, senora. I recycle what the scavengers bring in. Fix it if needed and get it ready for shipping.}
{225}{}{What does the boss think about you?}
{226}{}{He appreciates my work! I'm his main assistant when dealing with scavengers.}
{227}{}{Seems more like he's just pushing you around.}
{228}{}{Oh, no... Although I do think I should get paid a few more caps.}
{229}{}{He's just using you for next to nothing... Anyway, let's move on.}
{230}{}{No, no, Mr. Kogan - he's the boss. We couldn't surive without him.}
{231}{}{That wasn't the question, but whatever.}
{232}{}{Where does all the stuff go?}
{233}{}{Wherever the caravans comes from, that's where it goes. Everyone needs the stuff we dig up these days.}
{234}{}{Who are the scavengers?}
{235}{}{Well... they're scavengers... They dig up useful stuff from local ruins - remnants of the Old World. Then they bring these things here for processing and get paid in caps. The scavengers are divided into clans, all working under contract with the cartel.}
{236}{}{Can someone trade on the side?}
{237}{}{Oh, Mr. Kogan doesn't like that. And if not him, then the other scavengers won't take kindly to that. Folk like that don't last here long.}
{238}{}{Scavengers don't forgive that kind of thing. Within the clan, everything is handed over to the leader, who then divides the income among everyone. If someone breaks the rules, they don't last here long.}

{240}{}{Your boss is dead. What are you going to do now?}
{241}{}{This is bad, senor. The boss treated me pretty bad... paid me scraps for hard work, but without him... without him, the whole of Garage City will become an empty dump!}
{1241}{}{This is bad, senora. The boss treated me pretty bad... paid me scraps for hard work, but without him... without him, the whole of Garage City will become an empty dump!}
{242}{}{Are you sure?}
{243}{}{Only he knew how to run a business. And now a war for the mine will start among the scavengers. I don't know what to do... Maybe it's time to leave this place. But where will I go?}
{244}{}{Looks like you have a tough choice. Let's talk about something more pleasant.}

#About the product
{250}{}{What are you trading?}
{251}{}{What the scavengers bring in and what I fix up.}
{252}{}{The stuff scavengers bring in and the stuff I fix. But Mr. Kogan keeps the best goods for the top traders. So I can't offer everything.}
{253}{}{Uh, no, the boss knows best.}
{254}{}{You know, you don't always have to be so efficient.}
{255}{}{Great. So what do you say you're trading?}
{256}{}{Just look at this junk. You'll be selling it forever! I can buy it right now.}
{257}{}{You're right, sir. (reveals some of the product)}
{1257}{}{You're right, senora. (reveals some of the product)}
{258}{}{If you deny me good products, you'll miss out on a valuable client.}
{259}{}{You're right, sir. (reveals all his goods)}
{1259}{}{You're right, senora. (reveals all his goods)}
{260}{}{Mr. Kogan is long dead. Can I get full service now?}
{261}{}{Si, senor. (reveals all his goods)}
{1261}{}{Si, senora. (reveals all his goods)}
{262}{}{Mr. Kogan recognized my right to a full service. Let's see everything you have.}
{263}{}{Si, senor. (reveals all his goods)}
{1263}{}{Si, senora. (reveals all his goods)}
{264}{}{What is this gadget?}
{265}{}{The Geiger counter? (takes the device and holds it over your body) Uh, sir, you should buy this thing! It shows radiation levels. Many scavengers would love to have it, but it's too expensive for them.}
{1265}{}{The Geiger counter? (takes the device and holds it over your body) Oh, senora, you should buy this thing! It shows radiation levels. Many scavengers would love to have it, but it's too expensive for them.}
{266}{}{I'll think about it.}
{267}{}{I need parts to fix my radio. An amplifier.}
{268}{}{Radio? Seriously? You must have big plans. Not many people use radios these days. Rangers do though. Did they send you?}
{269}{}{I don't know what you're talking about. Do you have an amplifier or not?}
{270}{}{Hey, take it easy, amigo! Yes, I have a couple of different amplifier modules. They might fit, they might not.}
{271}{}{Then let's take a look at them.}

{276}{}{In Todd's trailer, there was a cap-making machine. It's destroyed now.}  
{277}{}{Good job, amigo. Here are the caps, as I promised. Just keep this quiet, okay? I don't want anyone getting lynched over this.}  
{278}{}{Okay. Bye, Pete.}  
{279}{}{I'll pay with REAL caps.}  

{280}{}{What are these, bottle caps?}  
{281}{}{Well, yes, we've used them as money since the Great War. You didn't know?}  
{282}{}{That's very... strange.}  
{283}{}{Everyone's used to it. And it's convenient. Just be careful; someone's started minting their own caps. It's bad because if there are too many caps, they'll lose value. I'll bet our culprit will be someone who has caps to spare, comprende amigo?.}  
{284}{}{Yeah, I understand.}  
{285}{}{We've been trying to track down this pendejo for a long time. If you find out who's minting fake caps, let me know.}  
{286}{}{Will do.}  
{287}{}{We'll see.}  
{288}{}{About the fake caps...}  
{289}{}{Yes? Any leads?}  
{290}{}{No, not yet.}  
{291}{}{Looks like it's Todd. He paid me with brand new caps.}  
{292}{}{He might have been a victim of this too. Let's not lay the blame yet. But it wouldn't hurt to check him out.}  
{293}{}{What are you suggesting?}  
{294}{}{What do you think, amigo? Trailer... tools... boom! Someone's gotta do it, you know? I'd ask other residents, but I'm afraid Todd will get lynched. I don't anyone getting hurt.}  
{295}{}{Okay, I understand. Get into his trailer, look for tools for making caps. If they're there, destroy them.}  
{296}{}{So, will you do it?}  
{297}{}{Okay. But breaking into someone's home is serious. What's it worth to you if I take this risk?}  
{298}{}{Okay. I'll do it.}  
{299}{}{No, find someone else.}  

#Repair services
{300}{}{What services does this garage provide?}  
{301}{}{We fix everything that can be repaired - weapons, armor, your favorite lawnmower. The only question is how many caps you can pay.}  
{302}{}{Do you repair cars here or something?}  
{303}{}{Oh, if only! Mostly I disassemble old equipment into useful parts. Fixing something truly self-propelled is my dream.}  
{304}{}{Take a look at my bike.}  
{305}{}{In that case, take a look at my bike.}  
{306}{}{I see. Then what do you repair?}  
{307}{}{A real bike in working order?! I swear by all the gears, I'd love to dig into this machine!}  
{308}{}{No, I don't think I'll be letting you near it.}  
{309}{}{This bike needs new tires.}  
{310}{}{Oh, finding good tires these days is near impossible. But I've got a couple of mint ones in the back that should boost your speed. That's why this place is called a garage!}  
{311}{}{I need more or larger storage for my bike.}  
{312}{}{Let me see. Hmm, I can make a new box. There's plenty of iron around, and I've got welding gear.}  
{313}{}{Can you check the engine?}  
{314}{}{Yeah, there's work to be done here! This bike hasn't been cleaned in a hundred years. Plus, I think I can find replacements for some of the worn-out engine parts. This'll likely reduce energy consumption by about 50%.}  
{315}{}{How much will you charge for the job?}  
{316}{}{ caps. And no bartering!}  
{317}{}{Okay, here's the caps.}  
{318}{}{I'll think about it. For now, show me something else.}  
{319}{}{Too expensive. I can't afford it.}  

{320}{}{(shakes head) That's not enough.}
{321}{}{Oh, too bad...}
{322}{}{Changing the tires will boost your bike's speed by 15%.}
{323}{}{Your motorcycle now has a storage rack with a capacity of 100 units.}
{324}{}{Pete did a great job - your motorcycle will now consume 50% less energy.}
{325}{}{Done!}
{326}{}{Great. Let's see what else you can do.}
{327}{}{Thanks. I'll go test it out now.}
{328}{}{Can you modify the rear seat so it can fit two passengers?}
{329}{}{Yeah, I can weld on a frame with an extra seat. Don't expect it to hold more than that, though.}
{330}{}{You can now carry one additional passenger.}

{340}{}{Can you boost the power of this laser emitter?}
{341}{}{Interesting piece. Looks like it's made from scrap parts. Sure, I can work on it. My price is }
{342}{}{ caps.}
{343}{}{We'll do it later. What else can you do?}
{344}{}{Alright. Here are the caps.}
{345}{}{Thanks. I'll go test it on some coyotes.}

{350}{}{Can you modify the flare pistol to take 12-gauge ammo?}
{351}{}{Easy as pie! Shotgun shells are stronger and more common. But it'll be harder to shoot and the range will suck. Think about it: make the flare rounds stronger or modify the flare pistol itself? For the mod, I charge }
{352}{}{ bottle caps.}
{353}{}{You caught me off guard. I'll keep this pistol as is for now.}
{354}{}{Let's modify the flare pistol. Here are the caps.}

{360}{}{I want to upgrade some flare rounds.}
{361}{}{I want to upgrade some flare rounds even more.}
{362}{}{Alright. That'll be }
{363}{}{ caps per round.}
{364}{}{No, I've changed my mind.}
{1364}{}{No, I've changed my mind.}

{365}{}{[Upgrade 1 round]}
{366}{}{[Upgrade 2 rounds]}
{367}{}{[Upgrade 3 rounds]}
{368}{}{[Upgrade 4 rounds]}
{369}{}{[Upgrade 5 rounds]}
{370}{}{[Upgrade 10 rounds]}
{371}{}{[Upgrade ALL rounds]}
