{100}{}{You see a sentry.}
{101}{}{You see a private in standard army armor with an unrecognizable symbol. He makes sure that outsiders do not enter the garrison.}
{102}{}{¡Un intruso!}

{110}{}{*Yawn*}
{111}{}{Estoy aburrido...}
{112}{}{Viene alguien?}
{113}{}{¿Cuándo es el cambio de guardia?}
{114}{}{Hoy hace calor.}
{115}{}{Tengo que informar sobre esto.}
{116}{}{Malditos insectos.}
{117}{}{Necesito zapatos nuevos.}
{118}{}{}
{119}{}{}

{120}{}{*Yawn*}
{121}{}{«Boring...»}
{122}{}{«Is someone coming?»}
{123}{}{«Where is the replacement guard?»}
{124}{}{«It's a hot day today.»}
{125}{}{«This will have to be reported.»}
{126}{}{«Damn insects...»}
{127}{}{«I need new shoes.»}
{128}{}{}
{129}{}{}

{190}{}{«Stop right there! Don't move.»}
{191}{}{«Okay. Now what?»}
{192}{}{«Are you threatening me?»}

{200}{}{Detente ahi! No se mueva.}
{201}{}{What?}
{202}{}{Eres gringo, verdad? Hablas espanol?}
{203}{}{I speak the language of fists. Shall we have a chat?}
{204}{}{Sorry, I don't speak Spanish.}
{205}{}{Americano - road - stop. You understand? Go back. Fast.}
{206}{}{Are you driving me away? But why?}
{207}{}{You can't tell me where to go? Get out of my way!}
{208}{}{Civil - no entry...prohibito. You go - or I shoot. Vamos! Vamos!}
{209}{}{You're so serious. Okay, I'll leave.}
{210}{}{Fuck you!}
{211}{}{«I speak a little Spanish.»}
{212}{}{Are you threatening me?}

{213}{}{«You're a yankee, aren't you? Do you speak Spanish?»}
{214}{}{«I speak the language of fists. Shall we have a chat?»}


{220}{}{«Intruder! Alert!»}
{221}{}{¡Un intruso! Alert!}
{222}{}{Shouldn't have done that...}
{223}{}{Hey, this is just a misunderstanding...}

{224}{}{«Shouldn't have done that...»}
{225}{}{«Hey, this is just a misunderstanding...»}

{230}{}{«I'm glad to hear that. Hm. Where are you from?»}
{231}{}{«I'm from a small village in the far north. I had to travel a long way in search of my relatives.»}
{232}{}{«You crossed the Sonora desert? I find that hard to believe. In any case, turn around and head back.»}
{1232}{}{«You crossed the Sonora desert? I find that hard to believe. In any case, turn around and head back.»}
{233}{}{«But why?»}
{234}{}{«This fort belongs to the United Mexican Army. Civilian entry is forbidden. My orders are to kill anyone who tries to enter without permission.»}
{235}{}{«I understand. Alright, I'm leaving.»}
{236}{}{«Could I join you?»}
{237}{}{«A northern yankee becoming one of us? I think not. Just leave.»}
{238}{}{«Ouch...»}
{239}{}{«To hell with that. I'm not leaving».}

{240}{}{«Didn't you understand the first time? If you try to come into the fort, you'll get a bullet in the forehead. Got it?»}
{241}{}{Okay, okay, I'll leave...}
{242}{}{If you do that again, I won't be responsible for what happens.}
{243}{}{Eres tu otra vez? (raises weapon threateningly) Vete! Voy a dispararte!}
{244}{}{«You know, one of you took the radio transmitter from the Dominguez family.»}
{245}{}{«Seriously? I didn't know that. It's a shame they were treated like that.»}
{246}{}{«Perhaps you could return the radio?»}
{247}{}{«I don't think you really care about the fate of those farmers. You've got some angle...»}
{248}{}{«I understand them well. I've experienced injustice from people with guns too.»}
{249}{}{«I'm just trying to help.»}
{250}{}{«Forget it, it's really not worth it.»}
{251}{}{[At gunpoint] «Radio or life?»}
{252}{}{«Yankees can't be trusted.»}
{253}{}{«Wonderful speech. I almost shed a tear. Okay, I'll talk to the commander...»}
{254}{}{«I'll wait...»}
{255}{}{«We found a radio in the barracks. Give it to the Dominguez family. We don't want to ruin our reputation.»}
{256}{}{«Good move. It would have been easier to do this right from the very start.»}
{257}{}{«Thank you»}
{258}{}{«What if I give you this bottle of booze?»}
{259}{}{«Okay, I'll talk to the commander...»}
{260}{}{«Give it back to them.»}
{261}{}{«You should return it. It's really not fair.»}


{262}{}{«Okay, okay, I'll leave...»}
{263}{}{«If you do that again, I won't be responsible for what happens.»}