{100}{}{You see a savage.}
{101}{}{You see one of the males of the Jackal tribe. His eyes blaze like the gaze of a wolf.}
{102}{}{ }

#Replicas floating
{120}{}{When my stomach is empty, I howl at the moon.}
{121}{}{A beautiful day for a sacrifice.}
{122}{}{This pelt is completely bald.}
{123}{}{Shhh, stop barking! The outsider will hear...}
{124}{}{The parasites on my body keep me from sleeping.}
{125}{}{This b-bitch will be mine!}
{126}{}{*Sniffs*}
{127}{}{*Scratches behind ear vigorously*}
{128}{}{Traps require bait.}
{129}{}{Time to sharpen my fangs.}

#Response
{200}{}{*Bares teeth*}
{201}{}{When you die, I'm gonna rip the meat off your bones first.}
{202}{}{My fangs thirst for your blood.}
{203}{}{Your brain will be mine when you die.}
{204}{}{}
{205}{}{By killing you, I'll gain fame and respect.}
{206}{}{Do you want to die, outsider?}
{207}{}{Mmm, what a juicy outsider.}
{208}{}{}
{209}{}{}
{210}{}{My l-life is yours now, outsider.}
{211}{}{*Piteous whine*}
{212}{}{}
{213}{}{}
{214}{}{}
