{100}{}{You see Ben.}
{101}{}{Covering his scarred face with a mask, this man instills fear in his subordinates.}
{102}{}{Nothing personal. I'll probably get a reward for your head.}
{103}{}{You've been running these roads for too long.}
{104}{}{Nice boots.}
{105}{}{Ben's polished armor reflects the laser beam directly into your eyes.}

{200}{}{Well, well, look at this. We don't usually get scum just wandering in here. (He gestures to his crew) Tear this piece of shit apart and take every damn thing he has!}
{1200}{}{Well, well, look at this. We don't usually get bitches wandering in here. (He gestures to his crew) Strip her and take all her stuff!}
{201}{}{First person who touches me, dies.}
{202}{}{[Don't resist]}
{203}{}{No, please! You can't do this! How am I supposed to survive out in the wasteland?}
{204}{}{You're in my territory now, maggot. Pay up or I'll decorate the sand with your guts.}
{205}{}{Fine, take all my stuff then.}
{206}{}{So you're just another bandit. I don't waste time with your kind...}
{207}{}{I can't stand idiots like you...}
{1207}{}{I can't stand dumb bitches like you...}
{208}{}{Get back from me!}
{209}{}{You shouldn't treat an ambassador from the outside world like this. It's in your best interest to keep me alive.}
{210}{}{(hissing) Ambassador, huh? Did Bustos send you? That spineless coward thinks he can take us down with a few snipers. The last merc he sent is rotting in the sun. But... no one's had the balls to talk to us until now.}
{211}{}{There you go. I'm ready to talk.}
{212}{}{That was the price of passage. Now I'm ready to listen to you.}
{213}{}{Thanks, uh, for keeping me alive.}
{214}{}{How am I supposed to make it in the desert without my gear?}
{215}{}{Give me my things back, you son of a bitch.}
{216}{}{So you saved my man from the bounty hunters?}
{1216}{}{So, babe, you saved my guy from the bounty hunters?}
{217}{}{Exactly. And I want to join your gang.}
{218}{}{Yeah. He said you'd take me in.}
{219}{}{(rasping) Don't get ahead of yourself. I don't trust you yet, no matter how glowing the recommendation. You want in? Prove your worth in blood.}

{220}{}{Enough pleasantries. What are you doing here?}
{221}{}{Actually, I'm here by accident. Looks like I'd better leave.}
{222}{}{I don't know what you're talking about. You're confusing me with someone else.}
{223}{}{You think I'd help scum like your guys? No way. You're wrong, idiot.}

{230}{}{I'm seeking allies to free my people from slavery.}
{231}{}{And why should we give two shits about your problems? The forces behind the slave trade are too powerful to fight.}
{232}{}{How about some mutual aid? You probably need someone with connections outside these walls.}
{233}{}{So, you're not going to help me?}
{234}{}{No. Get lost.}
{235}{}{Fine...}
{236}{}{Don't you dare talk to me like that, you masked freak.}
{237}{}{(hissing through mask) Hmm. There is one thing you could do for me. One of my guys was captured by mercs and is now being tortured in Casa Grande. I need this problem dealt with.}
{238}{}{Are you suggesting a rescue?}
{239}{}{(growling hiss) I can't let my guy talk. I don't care how you do it. If he can't be saved, he'll have to be killed.}
{240}{}{No way. You and your guy can go to hell.}
{241}{}{Got it. I'll take care of it.}
{242}{}{Give me some time to figure out a solution. I don't want to cause a mess in the city.}
{243}{}{Do as you see fit. But make sure the mayor doesn't get any info out of my man.}
{244}{}{Alright. I'll return once the problem's handled.}

{250}{}{I'm here to stop you and your whole gang.}
{251}{}{(rasping growl) I've never met anyone dumber than you. It'll be a real laugh to hear your last squeals.}
{252}{}{Uh, what are you up to? Oh no, not this...}
{253}{}{Screw you.}
{254}{}{}
{255}{}{I'm here on behalf of the mayor of Casa Grande. He accuses you of robbing caravans.}
{256}{}{(snarling through mask) He knows damn well who robs caravans and why. What's the point of this charade, mercenary?}
{1256}{}{(snarling through mask) He knows damn well who robs caravans and why. What's the point of this charade, mercenary?}
{257}{}{So, you admit your guilt. It's time you were all put to death.}
{258}{}{But why are you doing this? Aren't there other options?}
{259}{}{I lived in Casa Grande as a normal, law-abiding citizen. But Bustos came. He declared himself a count and seized power in the city. He labeled those who disagreed as criminals and began to persecute them. He drove us out.}
{260}{}{And now you have nowhere to go?}
{261}{}{We're busy surviving out here because of a tyrant and dictator. By robbing caravans, we simply take what is ours -- what was taken from us. Besides, we aren't bloodthirsty; we let go all the caravaners who don't put up a fight.}
{262}{}{You're just letting them go so they can lead another caravan you can rob again, aren't you? Raider scum...}
{263}{}{I don't give a shit what you think about it.}
{264}{}{}
{265}{}{It doesn't matter how you justify your crimes. You deserve death.}
{266}{}{I can understand you. I had to endure enslavement in Two-Sun. I can help you.}
{267}{}{To be honest, I didn't know this side of the story. Now I definitely don't want to help Bustos.}

{270}{}{I want to join your gang.}
{271}{}{Why? (hisses through mask)}
{272}{}{Because you guys are cool. I want to be like you.}
{273}{}{Do you think I look like an idiot? I'm tired of listening to this nonsense. Finish him off...}
{1273}{}{Do you think I look like an idiot? I'm tired of listening to this nonsense. Finish her off...}
{274}{}{What the...}
{275}{}{Wait. I saved your people in the Casa Grande bar. You can trust me.}
{1275}{}{Wait. I saved your people in the Casa Grande bar. You can trust me.}
{276}{}{I want to be part of a big pack like I used to be.}
{277}{}{To... help you kick things up a notch. I'm good at it.}
{278}{}{To do some good old ultra-violence. I'm not good for anything else anyway.}

{280}{}{I heard the story. But you'll have to prove your loyalty.}
{281}{}{Of course. What do we have to do?}
{282}{}{Sounds convincing. But you'll have to prove your loyalty.}
{283}{}{Of course. What do we have to do?}
{284}{}{I have nowhere to go in this world. Slavers have ravaged my village.}
{285}{}{So you want to survive by joining a strong pack. But we don't know shit about you. You could stab us in the back at any time.}
{286}{}{I can prove my loyalty. Test me.}
{287}{}{You're smarter than you look. I guess I've got just one move... Die, you son of a bitch!}
{288}{}{I saved your people in the Casa Grande bar. You can trust me.}
{1288}{}{I saved your people in the Casa Grande bar. You can trust me.}

{290}{}{I escaped from the Tinsmith's slave pen. Now I have nowhere to go.}
{1290}{}{I escaped from the Tinsmith's slave pen. Now I have nowhere to go.}
{291}{}{(rasping) I get you. Tinsmiths have pissed off a lot of people in these lands. We've felt their sting too.}
{292}{}{Does this mean you'll accept me?}
{293}{}{You'll have to prove your loyalty to the gang.}
{294}{}{Of course. What do I have to do?}
{295}{}{The Phoenix arena taught me only one thing: punch others in the face.}

#Repeat dialogue (after receiving quests)
{300}{}{What news?}
{301}{}{Hey Ben.}

{310}{}{Tell me about the gang.}
{311}{}{(rasping) You're not worth my time. Show yourself in action first.}
{312}{}{Hint taken.}
{313}{}{What do you want to know?}
{314}{}{That's it. It was nice chatting.}
{315}{}{One more question.}
{316}{}{Why are you called Blue Shields?}
{317}{}{Federal highway signs on our jackets. They look like shields. And they're blue. Get it now?}
{318}{}{I think so.}
{319}{}{How can you possibly survive in these lands?}
{320}{}{(laughs through mask) We rob caravans, hunt game, and scavenge ruins. The fuel depot keeps us going. Fuel is life. The water merchants in Casa Grande can't handle us.}
{321}{}{That's it. Interesting.}
{322}{}{But how did you get to this life? Where did all these guys come from?}
{323}{}{Everyone's got a story. But we're all outcasts. Some were driven out of Casa Grande when that bastard Bustos took over. Others were kicked out by Tinsmiths. And some fled problems in Phoenix. This is our only way.}
{324}{}{Everyones got a tough story I guess.}
{325}{}{What did the Tinsmiths do to you?}
{326}{}{Their power is growing, and the Wasteland just bows to it. They seize tech and resources, impose their own laws, and force settlements to work for their cause. Now we hit their caravans the same way.}
{327}{}{[Listen]}
{328}{}{They came with their own twisted ideals and started dictating our lives. Who the hell asked them? Who gave them the right? Before, the strongest ruled, not these tech-obsessed freaks.}
{329}{}{So you're fighting the invaders using their own methods? Ironic.}
{330}{}{Tell me about Rio. He's not particularly open towards me.}
{331}{}{(hissing) We're old friends. He's my right hand. Trust him with my life. He doesn't like anyone trying to win my favor. Deal with it and find a way to get along.}
{332}{}{I see.}
{333}{}{What is this place anyway?}
{334}{}{Petro-Chico Refinery Station. Pre-War, they stored fuel here. Must've been valuable since they built such a strong fence around it. Now it gives us fire.}
{335}{}{I see.}
{336}{}{What's your problem with the mayor of Casa Grande?}
{337}{}{Count Bustos is a tyrant. He seized power by trickery, killed or exiled anyone who opposed him. Now he lives in luxury while we scrape by in this wasteland because of him.}
{338}{}{Sounds like you have a bit of a grudge against him. Let's talk about something else.}

{350}{}{It's done. Your friend is dead.}
{351}{}{Your friend was killed by the locals. They staged a lynching right in the center of the city.}
{352}{}{It's done. Your friend's freed from the prison in Casa Grande.}
{353}{}{(hissing from mask) He's no friend of mine. Just a grunt in my gang. He owes me his life; let him pay with it.}
{354}{}{Well, you can figure it out for yourself.}
{355}{}{Wonderful speech.}
{356}{}{Now I see you've got some teeth. The gang needs links with the outside world; you'll be our connection.}
{357}{}{Where should I go this time?}
{358}{}{Well, it finally dawned on you that I'm here for a reason.}
{359}{}{I sent that guy scouting for a reason. The Tinsmiths are stretching their influence, caravans are multiplying, and Bustos is bringing in more and more mercs. A new order's rising, and we need to carve out our place in this new world.}
{360}{}{What are you up to?}
{361}{}{We're outlaws now. We're marked as criminals. I want a truce with the Tinsmiths. Go to Two-Sun and convince Master Hard to sign a deal-our fuel for our freedom.}
{362}{}{What if he refuses?}
{363}{}{He shouldn't refuse. Do whatever you can to win him over.}
{364}{}{I see. I'm going on a mission.}
{365}{}{What do you know about the Tinsmiths?}
{366}{}{Closed off bunch. They worship their damned tech and see us as inferior. But thanks to their production, these lands came to life again; a water pump started working and trade appeared.}
{367}{}{I see.}
{368}{}{About the contract. Isn't there a limited amount of fuel in the tanks?}
{369}{}{Look at these supplies (gestures towards the fuel depot). It'll take months just to move it. During that time, we'll rack up caps and plan our next move. I'm thinking of ordering some tech from the Tinsmiths, like bullet production gear. We'll become self-reliant, bolster our defenses, and hunt more efficiently.}

{370}{}{Bad news -- the Tinsmiths have been defeated by a supercomputer. There's no one left to negotiate with.}
{371}{}{Bad news -- Master Hard is dead, and the other Tinsmiths are too aggressive towards outsiders.}
{372}{}{Damn it, so it's true? Without the Tinsmiths, the roads will be empty again. Fewer caravans mean trouble for everyone. Looks like hard times are on the horizon.}
{373}{}{What are your plans?}
{374}{}{Loot as much as we can carry. And when the roads are completely deserted, we'll have to head to the mountains in search of game.}
{375}{}{I see.}
{376}{}{There's nothing more you can do for us. You can leave.}
{377}{}{Bye, Ben.}

{380}{}{Good news -- Hard agreed to the trade contract.}
{381}{}{(rasping) Hmm, things are looking up. Didn't think the Tinsmiths would go for it. This is good. Real good. But just getting a deal with them isn't enough.}
{382}{}{Who else is bothering you?}
{383}{}{Count Bustos, the mayor of Casa Grande. If he doesn't recognize us as a legitimate settlement, the caravanners won't do business with us. We need to either convince him to sign the contract or get rid of him.}
{384}{}{Kill Bustos so he doesn't interfere? This seems more realistic than negotiation.}
{385}{}{I'll still try to negotiate with him. It's hard to say what will happen to the city without him.}
{386}{}{Do it for the gang. For our long-awaited freedom.}
{387}{}{You can count on me, Ben.}

{390}{}{Count Bustos didn't want to make an alliance. He had to be "persuaded."}
{391}{}{Count Bustos has agreed to an alliance. It took a long time to persuade him.}
{392}{}{Thanks to you, the Blue Shields have a future. A new era is coming, where the Tinsmiths will open their tech to the world. We'll be among the chosen. No more need to rob travelers.}
{393}{}{[More]}
{394}{}{I didn't realize how crucial your help would be. You've earned your place in the gang. Wear that Blue Shield title with pride. Here's a jacket and a flamethrower as a reward.}
{1394}{}{I didn't realize how crucial your help would be. You've earned your place in the gang. Wear that Blue Shield title with pride. Here's a jacket and a flamethrower as a reward.}
{395}{}{[More]}
{396}{}{Seems like you have a long road ahead of you. I remember you needed allies. You can pick up the bike from Rio. With it you'll quickly get to any point on the highways.}
{397}{}{Thanks, Ben. We've done something good.}
{398}{}{(rasping) Don't thank me. We don't do that here. Just take what's yours. It's your right.}
{399}{}{Then goodbye, Ben.}
