{100}{}{You see a prisoner before you.}
{101}{}{Looks like the raiders are forcing this man to do hard labor.}
{102}{}{Am I free? Is it true?!}

{110}{}{They captured me and are forcing me to work.}
{111}{}{Are you in a gang too?}
{112}{}{I can't take this anymore. I have no strength left.}
{113}{}{When will they leave me alone?}
{114}{}{Save me. You're better than these raiders.}

{120}{}{They captured me and are forcing me to work.}
{121}{}{Are you in a gang too?}
{122}{}{Kill me. I can't stand this anymore.}
{123}{}{When will you leave me alone?}
{124}{}{Better kill me.}

{200}{}{Hello.}
{201}{}{Goodbye.}

{210}{}{Hello.}
{211}{}{Goodbye.}
