{100}{}{You see a agave farmer.}
{101}{}{You see a deeply tanned man wearing a straw hat and a fresh linen shirt.}
{102}{}{Weapons are prohibited in town. Hide it quickly.}
{103}{}{Oh, my respects, sir... I, uh, need to work... if I may...}
{104}{}{«Don't talk to me while there's a curfew in town...»}
{105}{}{You see Juan.}


{107}{}{«I'll introduce myself again. I'm }
{108}{}{, from a distant village in the north.»}

{109}{}{Uh...take it easy, I...me }
{110}{}{. I come (walk fingers through air) from a village to the north. (point to the north)}

{111}{}{Pull yourself together fool.}
{112}{}{No me hables mientras haya toque de queda en la ciudad...}


#First encounter
{200}{}{Hola. I am Juan. Why you come here?}
{1200}{}{Hola. I am Juan. Why you come here?}
{2200}{}{(stares at you wide-eyed, as if seeing a ghost, then steps back) I am Juan. I no speak English. NO! NO SPEAK!}
{201}{}{«Is this the welcome all new people get?»}
{202}{}{«What are you saying, amigo! I only wondered what brought you to our town. My English is not as good as your Spanish, so perhaps my words were rough. We have a close-knit community here. Everyone knows each other. It's hard for new people to settle in.»}
{203}{}{«Alright. Sorry.»}
{204}{}{«I'm not sure if I believe you. But either way, you've completely discouraged me from staying here.»}
{205}{}{Nice to meet you, Juan. I'm }
{206}{}{, from a distant village in the north.}
{207}{}{«Ah, so you're a farmer too! Then welcome. We need people like you.»}
{1207}{}{«Ah, so you're a farmer too! Then welcome. We need people like you.»}
{208}{}{«Thanks. I see good people live here.»}
{209}{}{«I wouldn't have been welcome if I wasn't a farmer? Not exactly friendly, Juan.»}

#Repeated meeting
{210}{}{Hola. Buenas noches.}
{211}{}{Hola. Buenos dias.}
{212}{}{Adios, amigo.}
{213}{}{I need some fire agave juice.}
{2213}{}{«I need some fire agave juice.»}
{214}{}{Hmph! Dirty Mexican!}
{215}{}{«Goodbye, Juan.»}
{216}{}{Hello. Good evening.}
{217}{}{Hello. Good day.}
{218}{}{Hola.}
{219}{}{«You probably have some questions for me?»}

{220}{}{«Tell me about this town. Who's in charge here?»}
{221}{}{«You need to see Mayor Alvaro. He's in that big house with the awning.»}
{222}{}{«Thanks, I'll talk to him later.»}
{223}{}{«Tell me about yourself.»}
{224}{}{«I am Himador Juan. What else do you want to know?»}
{225}{}{«What do you do here, Himador Juan?»}
{226}{}{«I work with the fire agave and other crops. While they're growing, I handle shipments for caravans and other tasks.»}
{227}{}{«Juan, tell me... are you here by choice?»}
{228}{}{«Si, senor. I work as a peon. I could leave anytime, but there's nowhere to go. I have to live by the rules and work off my contract.»}
{1228}{}{«Si, senora. I work as a peon. I could leave anytime, but there's nowhere to go. I have to live by the rules and work off my contract.»}
{229}{}{«I see. Thanks for the answer.»}

{230}{}{«I want to ask you about the plantations.»}
{231}{}{«We mostly grow corn and fire agave. But why are you suddenly interested?»}
{232}{}{«Just curious - what is this "fire agave"?»}
{233}{}{«I've heard of regular agave, but what's fire agave?»}
{234}{}{«The Followers say it's a mutated agave that was grown before the Great War. Since then, it's become bigger, more toxic, and spikier. But it still has useful pulp inside. That's what we mainly harvest.»}
{235}{}{«But what's the use of this plant?»}
{236}{}{«Oh, amigo, everything from the plant is used. The pulp and juice for food. The stalks for fertilizer and straw. The Followers even make medicine from agave extract!»}
{237}{}{«Where are the plantations located?»}
{238}{}{«To the west... But I don't recommend going there. Many people won't like it.»}
{239}{}{«How interesting. Can I buy some of the harvest?»}
{240}{}{«Actually, there's not enough harvest for everyone. So I'm forbidden from selling to just anyone.»}
{241}{}{«I see. Thanks for the answer.»}
{242}{}{«I really need some agave juice. Please sell me some.»}
{243}{}{«Sorry, amigo. I can't. If the Mayor finds out who the buyer is, he's gonna go loco on me.»}
{244}{}{«Alright, forget it.»}
{245}{}{«Who's in charge here?»}
{246}{}{«You must have some extra that no one will miss. And I have some spare caps...»}
{247}{}{«I see you know how to bargain. Alright, if you need agave juice, come to me. Though I don't understand why you need it. Are you planning to make tequila?»}
{248}{}{«Not a bad idea. I'm considering it.»}
{249}{}{«Come on, Juan, it's me. Is that how you treat friends?»}

{250}{}{«Why are weapons forbidden here?»}
{251}{}{«It's not wise to go against the rules, dear viajero. These bans at the front gates are written in blood.»}
{252}{}{«Sorry, that was an unnecessary question. Forget it.»}
{253}{}{«And why do you carry that strange spear?»}
{254}{}{«Ha-ha, that's not a weapon, it's a coa. I cut agave leaves with it during the harvest. And I have permission from the Mayor. Without permission, even carrying a coa openly is forbidden.»}
{255}{}{«I've never seen anything like it.»}
{1255}{}{«I've never seen anything like it.»}
{256}{}{«The Mayor placed an order with the Tinsmiths. They took the payment in harvest. Very expensive, but without tools, our work would be tough. And besides the Tinsmiths, no one else can do it.»}
{257}{}{«Sounds familiar. At the Villa, we also have to do everything by hand.»}
{258}{}{«Really? I've never heard of other plantations. Are you serious?»}
{259}{}{«If you don't believe me, let's change the subject.»}
{260}{}{«I see. Let's talk about something else, then?»}
{261}{}{«I've never seen such a tool.»}
{262}{}{«Me, "just anyone"?»}
{263}{}{«Why?»}
{264}{}{«Would you like it if someone wandered through your home without asking? Plus, sometimes we catch harvest thieves. Their fate is usually grim.»}
{265}{}{«Do you have any more questions?»}

{269}{}{«Uh... I'm sorry, sir.» I no speak English well. }
{1269}{}{«Uh... I'm sorry, ma'ma.» I no speak English well. }

{270}{}{Uh... Lo siento, senor. I no speak English well. }
{1270}{}{Uh... Lo siento, senora. I no speak English well. }
{271}{}{Too bad. I guess were gonna have trouble communicating.}
{272}{}{«I can speak Spanish too, friend.»}
{273}{}{«I'm very relieved to hear that!»}
{274}{}{Can I take a look at what you have in the cart?}
{275}{}{No, no, no, senor! Agave juice is only for the caravans. Not for sale.}
{1275}{}{No, no, no, senora! Agave juice is only for the caravans. Not for sale.}
{276}{}{Lo siento, senor.}
{1276}{}{Lo siento, senora.}
{277}{}{Si, por supuesto, senor.}
{1277}{}{Si, por supuesto, senora.}
{278}{}{[Continue]}
{279}{}{[You switch to speaking Spanish]}
{280}{}{(looks at you and steps back) Wh.. what y-you want?}
{281}{}{(looks at you and goes pale) I n-no...speak English! Go away!}

{282}{}{(looks at you and gulps) «Ah...my friend...Wh... what do you need?»}
{283}{}{(looks at you and breaks out in cold sweat) «Can I help you...er...friend?»}