{100}{}{You see Arthur Carrington.}
{101}{}{You see the same archaeologist from Vault 27.}

#First dialogue
{200}{}{Good to see you again, hero.}
{1200}{}{Nice to see you again, heroine.}
{201}{}{I see you've already settled into your new place. Can you give me a minute?}
{202}{}{Yes?}
{203}{}{Bye.}
{204}{}{Another question.}

{220}{}{What are you doing here?}
{221}{}{They've asked me to teach the children to read and write. It's an unusual experience, but better than toiling on a plantation. I'm not allowed to do more serious research yet. It's frustrating since I've managed several major projects before.}
{222}{}{I think you'll get the hang of it in time. For now, just try to relax.}
{223}{}{What do you think about the Followers?}
{224}{}{At first, I admired their thirst for knowledge. But their kindness is simply baffling. You can't just help everyone and share knowledge indiscriminately. Many people don't deserve it. And even if they do, their stupidity prevents them from properly managing the benefits they receive.}
{225}{}{You have different views on the same thing. That's okay.}
