#Using items
{200}{}{This doesn't apply to the trunk. Try it on a motorcycle.}
{201}{}{By replacing the old mount, you have increased the luggage compartment capacity by 5 units.}
{202}{}{You've already replaced the securing rope. No point in doing it again.}
{203}{}{Hardly possible during combat.}
{204}{}{You've installed a new luggage container. The bike now holds more cargo.}
{205}{}{There's no room for additional containers on the motorcycle.}
{206}{}{This motorcycle doesn't belong to you.}

#Using skills
{300}{}{Nothing to hack here.}
{301}{}{After carefully measuring the trunk, you conclude its volume is }
{302}{}{ units.}
{303}{}{With a skill like that, this luggage box won't get any better.}
{304}{}{There's nothing to repair here.}
{305}{}{You may not repair this bike until you own it.}
{306}{}{After repairs, the luggage compartment capacity has increased by 5 units.}
