{100}{}{}
{101}{}{}
{102}{}{!Cheat: 3D heads enabled.}
{103}{}{!Cheat: 3D heads disabled.}

# Using items on GG
{110}{}{Curious item. It's worth finding some use for it.}
{111}{}{Best used when you get outside.}
{112}{}{Paying yourself is nice, but pointless.}
{113}{}{You received one bottle cap.}
{114}{}{Better to sell this to the upstarts in town.}
{118}{}{Use this item from your hand.}
{119}{}{Use this through your backpack or from your hand.}

{120}{}{Seeing this useless junk, you can't help but think... maybe the world needs another atomic war.}
{121}{}{This update is exclusive to the ZAX logic module.}
{122}{}{You don't look like a nuclear bomb.}
{123}{}{These passwords should be used on computers and other electronic systems.}
{124}{}{You tore up this letter, trying to forget everything that connected you with the fire-worshipping cult.}
{125}{}{This letter should be presented to the Followers of Fire in Phoenix.}
{126}{}{Damn cultists...}
{127}{}{I don't want to think about them anymore.}
{128}{}{Drinking this liquid in its pure form will only cause an upset stomach.}
{129}{}{Hey, watch out! You almost cut your head off.}
{1129}{}{Hey, watch out! You almost cut your head off.}

{130}{}{Setting your hair on fire is not a good idea.}
{131}{}{You changed your boots. Now you can safely walk on burning and caustic substances, but only for a couple of minutes.}
{132}{}{This isn't necessary yet, since the old boots are in excellent condition.}
{133}{}{This isn't necessary yet, since the old glasses are still in working order.}
{134}{}{Wearing these strange glasses feels like stepping into another dimension.}
{135}{}{The battery of the electronic glasses is low. Night vision disabled.}
{136}{}{Hold the sunglasses in your hand to feel cool.}
{1136}{}{Wear your sunglasses to feel like a true fashion god.}
{137}{}{This isn't necessary yet, since wearing a gas mask will provide sufficient protection.}
{138}{}{You changed your gas mask. It will protect you from harmful gas and dust for a while.}
{139}{}{Yeah, put this on your head and scare the village kids. It'll be fun.}

# Reset items
{140}{}{Your family wouldn't be happy to see you throw away family heirlooms.}
{141}{}{Beggars will be very happy to find your caps.}
{142}{}{Imagining yourself to be a philanthropist, you generously throw money to the wind.}
{143}{}{These sandals will help you walk in corrosive substances, but only for a short time.}
{144}{}{Decoy set.}

# Different lines
{150}{}{The radioactive object in your backpack gives off a slight heat.}
{151}{}{Your Pip-Boy shows your exposure level: }
{152}{}{This cannot be done during combat.}
{153}{}{One-two, the radio is working.}
{154}{}{Your legs can't support the enormous weight of your backpack.}
{155}{}{What a pain!}
{156}{}{You shouldn't do this.}
{157}{}{This could be dangerous! Your recklessness almost killed your character. And how upset Granny Adonisia would be...}
{158}{}{You should look for more durable shoes. And this one can be sold at the nearest market.}
{159}{}{You will need a workbench to disassemble this item.}
{160}{}{You need to collect ALL the pieces of the map.}
{161}{}{You have collected all the pieces of the treasure map. It appears to be buried near the ruins of a local lighthouse.}

# Achievements
{200}{}{Your reputation is growing.}
{201}{}{Your infamy is growing.}
{202}{}{A high dose of radiation will permanently reduce your health.}
{203}{}{The high dose of radiation is once again permanently reducing your health.}
{204}{}{I'm getting worse.}
{205}{}{I'm getting MUCH worse.}
{206}{}{Surviving a large number of beatings earns you the Hardened Fighter achievement.}
{207}{}{I think I'm starting to get used to this pain.}
{208}{}{For your vile betrayal, you were stripped of all your ranks in the Brotherhood of Steel.}
{209}{}{For your vile betrayal, you were expelled from the Rangers.}
{210}{}{For your vile betrayal, you were expelled from the magistrates.}
{211}{}{For your vile betrayal, you were expelled from the Fire Cult.}
{212}{}{After such a long journey, you have earned the title of peace-loving wanderer.}
{213}{}{The title of peace-loving wanderer has been lost. But it's not too late to return to the righteous path.}
