{100}{}{You see a power plant ghoul in front of you.}
{101}{}{You see a man with burned, rotten skin wearing well-worn work clothes adorned with a pre-war symbol.}

{200}{}{Holy Ohm! Don't sneak up on me like that. You and your pale skin roam around here like a ghost...}
{201}{}{I'm not the one who looks like the dead around here.}
{202}{}{Sorry, I didn't mean to scare you.}
{203}{}{Ha-ha. Don't mind me. We can only laugh in the face of death... I'm Herbert, the supply room manager.}
{204}{}{A supply room? Then you might have useful stuff.}
{205}{}{Holy Ohm! We have new arrivals! I'm so glad the number of mutants is growing.}
{206}{}{Did you just call me a mutant? Better take that back!}
{207}{}{It's nice to finally meet some fellow sufferers.}

{210}{}{What do you want, drifter?}
{211}{}{Nothing today. Bye, Herbert.}
{212}{}{Got anything for sale? I could use a couple of charged batteries.}
{213}{}{Sorry, we only trade with caravans we have contracts with.}
{214}{}{Alright. Goodbye, Herbert.}
{215}{}{What do you need, my mutated friend?}
{216}{}{Mutants should help each other out. Don't you think?}
{217}{}{Well... Alright. The boss talked about people, but he didn't mention mutants. If you need anything, let me know. I'll try to help. And tell you what, I'll give you the special 'ghoul' price, not the normie rate.}
{218}{}{Sounds great friend.}

{220}{}{Your boss promised to pay me for the job I helped him with.}
{221}{}{Yes, yes, I remember. You can choose your reward.}
{222}{}{Gimme some time to think. I'll be back soon.}
{223}{}{Alright, sign here and here. Just kidding. You probably can't write. By the way, if you need batteries, come to me. The boss said its okay to trade with you.}
{224}{}{Nice. I'll remember that. See you later, Herbert.}
{225}{}{250 caps.}
{226}{}{Laser pistol.}
{227}{}{Rad-X, 3 pcs.}
