{100}{}{You see Steve.}
{101}{}{You see one of the fight fans.}
{102}{}{Holy shit. I knew that Tinsmiths were masters, but I never imagined...}
{103}{}{That letter was very helpful. Thanks for the delivery.}
{104}{}{Do you also take bets?}

#First Dialogue
{200}{}{What? You bettin' on the fights too?}
{201}{}{No. I'm looking for a guy named Steve. He lives in the place across the street.}
{202}{}{Wait a minute, it's you! Wow, those last few fights were amazing. But why don't you fight anymore? I could make a lot of caps bettin' on you.}
{203}{}{It's not up to me.}
{204}{}{Ah, I see. The little guy's greedy for caps, right? Never mind.}
{205}{}{I'm looking for a man named Steve. He lives in the house across the street.}
{206}{}{I don't fight anymore. Period.}
{207}{}{Okay, okay, champ, don't be so tense.}
{208}{}{Whatever. Just tell me if you know this Steve, who lives in the house across the street.}
{209}{}{That's me. What do you want?}
{210}{}{I'm from the Sonora Express. There's a letter for you. Sign for it and it's yours.}
{211}{}{Is this some kind of joke? I can barely read. Who would write to me?}
{212}{}{I guess you're not the Steve I'm lookin' for. Bye.}
{213}{}{Hey, wait a minute. Of course, I'll sign. So, are fingerprints enough? Great, come here...}
{214}{}{[More]}
{215}{}{I don't know who's writing to you. But delivery costs five caps.}
{216}{}{What, I have to pay for this? Well, I don't think so. This is definitely some kind of scam. I'm not fallin' for it.}
{217}{}{Okay, just take the letter then. It's only taking up room in my backpack.}
{218}{}{This is interesting. Okay, here's five caps. I really hope it's worth it.}
{219}{}{Here you go.}
{220}{}{No prob, everything is fine. Just sign and take the letter.}
{221}{}{What? Do you bet on the fights too?}
{222}{}{No, I'm looking for someone to give the letter to. But it looks like I lost it somewhere.}
{223}{}{Yes, problem.}
{224}{}{Uh, I'll go look. Bye.}

{227}{}{Hello. I'm still trying to raise caps in the ring. But it's not working out. Looks like it's time to get out of this stuffy city.}
{228}{}{Speak for yourself. I'm already sick and tired of village life on the plantations. Bye.}
{229}{}{Well, yeah. Life is simpler and calmer away from the noisy city. Bye.}

{230}{}{(takes the letter, unfolds it, and reads it slowly) So... hmm...}
{231}{}{Is the letter really for you?}
{232}{}{It's my uncle from Casa Grande. Looks like he wants to meet me. Thank you, this was a very valuable letter. Truly.}
{233}{}{What does it say?}
{234}{}{Then I can leave with a feeling of deep satisfaction. All the best.}
