{100}{}{You see Vernon.}
{101}{}{You see a man in a very worn suit. The circles under his eyes and nervous tics indicate overwork.}
{102}{}{Of course, our area is dangerous, but to such a degree...}
{103}{}{Please stop them! They'll destroy everything here!}

# First dialogue
{200}{}{(noticing you, the man frowns and nervously twitches his right eye) I don't think I've seen you before. What are you doing here?}
{2200}{}{(noticing you, the man frowns and nervously twitches his right eye) You remind me of the power plant ghouls. But I know all of them by sight. Who are you? What do you want?}
{201}{}{I need a place to stay for the night. Are there any rooms for rent here?}
{202}{}{Sorry, but all the rooms are occupied. We're packed so tight we can hardly breathe.}
{203}{}{What is this place?}
{204}{}{Something like a community house. If you're here by chance, you should probably leave.}
{205}{}{Why?}
{206}{}{The locals are tightknit. All residents know each other by sight and are wary of newcomers.}
{2206}{}{The locals are tough. All the residents know each other by sight and treat newcomers with suspicion. Especially mutants. Honestly, people are afraid of catching your... affliction.}
{207}{}{I understand. In that case, I really better leave.}
{208}{}{Not surprising for such a lousy area. Bye.}
{209}{}{I'm not leaving until my questions are answered.}

{210}{}{Uh... nothing really. What is this place?}
{211}{}{This is a community house. Do you have business here or know anyone? If not, then you'd better leave.}
{212}{}{Why are you kicking me out?}
{213}{}{(dissatisfied, sleepy grumble) Burk... burk... Damn, do you even know what time it is...}
{214}{}{Sorry for disturbing your sleep.}
{215}{}{Wake up. Come on.}

{220}{}{(your appearance causes the man to freeze in amazement, and then nervously twitch his right eye) What a surprise to see such a respected person in our neighborhood. Are you looking for something?}
{221}{}{Actually, I'm looking for a place to stay for the night. Are there any rooms available here?}
{222}{}{I'm afraid all the rooms are occupied. Besides, you probably wouldn't like it here.}
{223}{}{Why?}
{224}{}{How should I put it... You don't quite fit in with these slums. We have poor living conditions and rough tenants. You might even get robbed.}
{225}{}{Not surprising for such a lousy area. Bye.}
{226}{}{I guess I should take my leave then.}
{227}{}{Well, before I go, I want to ask a few questions.}
{228}{}{I was curious, what is this place?}
{229}{}{Something like a community house. If you're here by chance, you shouldn't stick around.}
{230}{}{Why?}

{240}{}{Hey, champ! It was a great fight. What can I do for you?}
{241}{}{I'm not sure. What is this place?}
{242}{}{This is a community house, and I'm the manager. However, I don't think people of your stature will be interested in here. Our neighborhood is inhabited by... less successful townspeople.}
{243}{}{Then could you answer a couple of questions?}
{244}{}{You're right, I'm not interested in a hole like this. I'm outta here.}
{245}{}{Do you mind if I look around? Great, see you.}
{246}{}{Hey, champ! It was a great fight. What can I do for you?}
{247}{}{I want to talk to you.}

# Death of a pusher
{250}{}{(Vernon sits at the table with his head in his hands; he sways a little, letting out a quiet groan)}
{251}{}{What's wrong with you?}
{252}{}{Huh? Oh, it's you... This damn headache... I used to take the drugs that Gonzalez found. But now he's dead and I don't know where to get more... Uhhgg...}
{253}{}{That sucks. Well, there you go.}
{254}{}{Oh, sorry, I thought killing that dealer would be good for everyone.}
{255}{}{WHAT were you thinking? Damn it! Yes, Gonzalez got some of the residents bad drugs, which, uh... messed them up a bit. But for others, he supplied medicine for illnesses, and painkillers. Why the hell did you have to kill him?}
{256}{}{It's done, so just move on.}
{257}{}{Yeah... sure... Then get the hell out of my office.}
{258}{}{Watch your lip or you'll end up like your dealer.}
{259}{}{Whatever.}
{260}{}{His 'medicine' wasn't that good really.}
{261}{}{Is that the only reason? Damn it, you're out of your mind! Get out of our neighborhood, now.}
{262}{}{}
{263}{}{I don't even know. Do you really need a reason at this point?}
{264}{}{You're out of your mind! You'd better leave this area and never come back.}

# Racket after the final game
{270}{}{Oh, thanks, amigo. If it weren't for you, those thugs would have wrecked this place, and probably hurt some of us.}
{271}{}{What did they want from you?}
{272}{}{It's just a racket. After the Cardinals gang broke up, God knows what began in the slums. Now any thugs who were afraid to even go outside before, can rob and beat people at will.}
{273}{}{Weren't the Cardinals themselves just thugs?}
{274}{}{Yes, but they watched the area and didn't let anything get, y'know, out of control. I really hope that this wave of violence will ease down soon. Some new bastard will probably take over the neighborhood. And everything will start all over again.}
{275}{}{Great neighborhood. Bye.}
{276}{}{Not the outcome I expected. Good luck to you.}

# Re-dialogue
{300}{}{So what do you want?}
{301}{}{How can I help you?}
{302}{}{You'd better leave.}
{303}{}{Goodbye.}
{304}{}{What do you want?}
{305}{}{Listen, buddy, you're scaring the residents a bit. You'd better head to the power plant with the other freaks.}

{310}{}{I'm investigating an attack on the Followers. What do you know about it?}
{311}{}{The situation is becoming clearer.}
{312}{}{The situation is becoming clearer. Time to discuss this with Aaron.}
{313}{}{(frowns and twitches nervously) So, another Follower's lackey? I already told the monks everything. Leave us be.}
{314}{}{(twitches nervously with a frown) Didn't think they'd rope you in too. But I already told the monks everything I know.}
{315}{}{Guess you'll have to tell your story again.}
{316}{}{We didn't kill anyone. The monks were asking for alms around here and got nothing. Once outside, they were grabbed by masked men and strung up on lamp posts. We don't know who did it, but they were clearly well-prepared.}
{317}{}{Any locals involved in this?}
{318}{}{The locals fear the church folk. No one here would risk such a crime, especially right in front of their own homes.}
{319}{}{Rumor has it the locals dislike the monks.}
{320}{}{Why should we like them? While we live in poverty, the monks wallow in luxury. They take our weapons and forbid Gonzalez from selling medicine. But look at the locals -- could any of these poor souls have pulled off such an organized attack?}
{321}{}{Who could carry out such a bold attack?}
{322}{}{Only the power plant ghouls and Orris's gang. But the power plant ghouls stay out of city affairs, and Orris wouldn't want trouble with the church.}
{323}{}{No more questions.}
{324}{}{I don't believe you. You're hiding something.}
{325}{}{I know what I know. If you don't believe me, prove I'm lying.}
{326}{}{I'll be nice today and only break your fingers, one by one, until you tell me everything.}
{1326}{}{I'll be nice today and only break your fingers, one by one, until you tell me everything.}
{327}{}{Hmm...}
{328}{}{Stop! Please! Think about it -- would we attack monks near our own homes? It's crazy. But I know something... there's talk of a secret group of 'firephobes'. Remember, Aaron, his Church of the Holy Fire's help, staged a revolution and took over the city. Many have wanted revenge on him since.}
{329}{}{Interesting information. Maybe you've earned a pass for today.}
{330}{}{Enough lies. Time to break some fingers.}
{331}{}{You're pretty eager to fight. But you'll find we can fight too when necessary.}
{332}{}{Bah!}
{333}{}{Tell me again about the attack on the monks.}

# Questions
{350}{}{Who are you and what is this place?}
{351}{}{I told you, this is a community house. I'm Vernon, the manager.}
{352}{}{That's all I needed to know.}
{353}{}{Why did you say this area was dangerous?}
{354}{}{Poor people and gangs are not the best bedfellows for any city.}
{355}{}{What gangs are we talking about?}
{356}{}{I shouldn't have said that. Well, there are several 'gangs' around. The power plant ghouls to the east, Orris's crew to the north, and smaller gangs in every quarter.}
{357}{}{What can you tell me about the power plant ghouls?}
{358}{}{Secretive types, they stay neutral and don't meddle in city affairs. They're not really a gang, but still, only a few are allowed near them.}
{359}{}{Who is Orris and what is his gang known for?}
{360}{}{Orris practically owns this neighborhood. Don't cross his guys, or you won't last long here.}
{361}{}{I'm looking for Steve. They say he lives here.}
{362}{}{I don't know why you want that scoundrel, and I don't care. Lately, he's been hanging around the ring, hoping to make money on bets. Fool.}
{363}{}{Got it, at the ring.}

# Quests
{370}{}{Seems like you're in trouble. I can help.}
{371}{}{Really? The city's taught me not to trust anyone offering help with a smile. What's your angle?}
{372}{}{I genuinely want to help.}
{373}{}{Tell that to someone else. You're not earning any caps here.}
{374}{}{Well, I was just hoping to establish a good rep in the city.}
{375}{}{Ah, I see. But you won't earn any caps here. Still, a good rep can be just as valuable.}
{376}{}{If you don't want help, that's fine. I'm just offering.}
{377}{}{I know. What are your problems?}
{378}{}{There are a couple of troublesome tenants causing a lot of issues. Can you kick them out?}
{379}{}{Sure, who are they?}
{380}{}{I'd rather not get involved in personal disputes.}
{381}{}{One is Larry. He's hooked on drugs and it's wrecking him. Smart guy, but his addiction has taken over. I can't openly evict him because his dealer wouldn't like losing a customer.}
{382}{}{Got it. Who's the other one?}
{383}{}{Badi. He lives opposite. No issues until he got addicted to gambling. Now he's in so much debt that the bouncers are even threatening me.}
{384}{}{No one wants to deal with him anymore. He either pays rent or hits the street. I'm tired of this.}
{385}{}{Remind me about the drug addict.}
{386}{}{Larry. He's probably in his filthy room, wasting his life away.}
{387}{}{Got it. Later.}
{388}{}{Remind me about the tenant behind on rent.}
{389}{}{They're all behind, but Badi owes the most. Plus, his casino problems are a headache I don't need.}
{390}{}{Gambling debts are serious business.}
{391}{}{Larry won't bother the residents anymore. He's dead.}
{392}{}{WHAT? My god, why did it have to come to this?}
{393}{}{You wanted him gone.}
{394}{}{Not like thhis! The slums already have a bad rep, and now people will avoid this place even more.}
{395}{}{You should've clarified the task. It's too late now.}
{396}{}{Yeah, I suppose. Hopefully this blows over soon. At least it'll be quieter without Larry.}
{397}{}{Always a silver lining. Bye, Vernon.}
{398}{}{Larry won't bother anyone anymore. He overcame his addiction.}
{399}{}{Incredible! How did you inspire him? No one believed in Larry anymore. They thought he was a lost cause.}
{400}{}{I have my methods. He just needed motivation.}
{401}{}{I don't know what to say. Thank you.}
{402}{}{You're welcome, Vernon.}
{403}{}{Alright. I'll talk to them first.}

{404}{}{Badi will be able to pay off his rent debt soon.}
{405}{}{Great job! I thought nothing would save him from bloody retribution. How did you straighten him out?}
{406}{}{The key is finding the right approach for each person. Bye, Vernon.}
{407}{}{I made Badi leave. He's out on the street like a stray dog.}
{408}{}{Good. We don't need more trouble. Thanks for the help.}
{409}{}{You're welcome.}
{410}{}{Badi doesn't live here anymore. He's dead.}
{411}{}{He... was killed? My god, those bouncers are real beasts.}
{412}{}{He brought it on himself.}
{413}{}{Don't give me the details. I just hope his debt doesn't affect us. It would've been better if he'd just left.}
{414}{}{Not the cleanest solution, but your problem is solved. Bye.}
{415}{}{Badi paid off his casino debts. He'll pay his rent soon too.}
{416}{}{That's great! How did you manage that?}
{417}{}{The key is finding the right approach for each person.}
{418}{}{Great job. I thought nothing would save him from bloody retribution. Those casino bouncers are real beasts. Thanks for the help.}
{419}{}{You're welcome, Vernon.}

{420}{}{All your little problems are dealt with. How else can I help?}
{421}{}{I can't believe you're helping us poor folks for free. You're not like anyone I've met before. But still, these were small issues compared to our daily struggles.}
{422}{}{What do you mean?}
{423}{}{Our main problem is the Red Cardinal gang. They control this whole area and everyone in it. No one dares stand against them. Even the mercenaries from the guild steer clear. We're constantly under their thumb, and they keep growing stronger.}
{424}{}{Wait, are you suggesting I take them on? You're crazy. Do you even understand what you're asking?}
{425}{}{Please? Um, no, I'm just venting. Taking down the gang sounds crazy, I know. But... you've already done so much for us. Maybe you have some ideas? We'd put our last caps on Orris's head. Without him, the gang would fall apart, giving us some breathing space.}
{426}{}{I'll have to think carefully before I take this on. See you later, Vernon.}
{427}{}{Okay, I'll do it. I hope you scrape together enough to make it worth it.}
{428}{}{You want me to get rid of the gang? Sure. These street thugs have never been in a *real* fight.}
{429}{}{Oh! We'll give you all the caps we have if you take out Orris. Without him, the gang would weaken, giving us some breathing space.}
{430}{}{Don't worry about the caps. I'll enjoy taking care of this scum.}
{431}{}{Get your caps ready. I'll take everything you have for his head.}
{432}{}{Tell me more about the Red Cardinals.}
{433}{}{They control this whole area. Dozens of them, well-armed, and good fighters. Their leader is Orris. Scary guy, tough on everyone. Please save us from his chaos. No one else will help.}
{434}{}{Orris is taken care of. His gang won't be much trouble for awhile.}
{435}{}{You're a true hero! We've been hoping for a miracle, and, and we got one! Now we have hope for a new life. Thank you so much.}
{1435}{}{You're a true heroine! We've been hoping for a miracle, and, and we got one! Now we have hope for a new life. Thank you so much.}
{436}{}{That's good. The main thing is no one threatens you now.}
{437}{}{Spare me the sappy story. Hand over the caps. Do you think I went through all this trouble out of kindness?}
{438}{}{Uh, yeah, take these caps. There's 217 of them. That's all we could gather.}
{439}{}{Idiot! I wouldn't have risked my life if I'd known you'd only collected this measly amount! Damn it. Hand 'em over.}
{1439}{}{Idiot! I wouldn't have risked my life if I'd known you'd only collected this measly amount! Damn it. Hand 'em over.}
{440}{}{Hmph. Better than nothing.}
{441}{}{Sorry it's so little. You can stay here as long as you want.}
{442}{}{Goodbye, Vernon.}
{443}{}{You can return all the caps you collected for the bounty. I was after justice.}
{444}{}{You're amazing. Please know, you're always welcome here.}
{445}{}{Goodbye, Vernon.}
{446}{}{Thanks for your help with Larry and Badi, but you really should... move on. I don't want any more trouble.}
{447}{}{You try to help somebdy...}
{448}{}{It's your loss, pal.}

{449}{}{The more I hear about this scum, the more I want to take him out.}
{450}{}{Dozens? Well-armed? This just gets better and better.}
