{100}{}{You see Bob.}
{101}{}{You see a dark man with a beard, wearing hiking clothes.}
{102}{}{You see old Bob. As usual, he's indulging in drinking.}

#First Dialogue
{200}{}{Hey there, are you lost?}
{1200}{}{Hey there, are you lost?}
{201}{}{Sort of. Do you actually live here?}
{202}{}{(groaning with dissatisfaction) Yeah, this is a community house, and this is my room.}
{203}{}{And you are...?}
{204}{}{I'm Bob, a scavenger and handyman. But, who are you, and what are doing here?}
{205}{}{None of your business.}
{206}{}{Is that right? You're in *my* room and its none of *my* business? I don't know who you are, but you'd better get out.}
{207}{}{Watch yourself before you start giving me orders.}
{208}{}{Sorry, I'm leaving right now.}
{209}{}{My name is }
{210}{}{. I'm passing through Phoenix, looking for a place to stay.}
{211}{}{Talk to Vernon then, he runs the show here.}
{212}{}{Thanks.}
{213}{}{Okay.}
{214}{}{Back again? You're not planning to start trouble here, I hope.}
{215}{}{That's exactly what I'm planning to do.}
{216}{}{No, I'm not. Bye.}
{217}{}{Sorry about last time. I'm }
{218}{}{, and I'm looking for a place to stay.}
{219}{}{Definitely. But first, I wanna talk with you.}

#Re-dialogue
{220}{}{Hello.}
{221}{}{What do you want?}
{222}{}{Looking for something?}
{223}{}{Yeah?}

{225}{}{Stay away from me. I don't want to be seen near you.}
{226}{}{You shouldn't be wandering around this dangerous area alone.}
{227}{}{I don't know what you want, but you better leave.}
{228}{}{}
{229}{}{See you, Bob.}

{230}{}{Hey, great fight, }
{231}{}{. You fight as well as Iron Mike. Pity I didn't place bets, could've gotten rich.}
{232}{}{Should've bet then, huh?}
{233}{}{Thanks for your support, Bob.}
{234}{}{You know, it was just another fight. Nothing special.}
{235}{}{Whatever you say, champ. Whatever you say.}
{236}{}{Hmm.}

#Questions about Scavengers
{250}{}{You mentioned you were a scavenger.}
{251}{}{(looking askance) Yeah... maybe. So?}
{252}{}{Just curious. Anything new going on around here?}
{253}{}{Uh, nothing much.}
{254}{}{Yeah, there was a golden time when scavengers swarmed through the ruins of Phoenix. Now only the truly dangerous, highly radioactive areas remain untouched. So what?}
{255}{}{Tell me about the scavengers.}
{256}{}{You seriously don't know about us? Hmm, guess we do keep a low profile.}
{257}{}{I've been to Garage City, and scavengers live there too.}
{258}{}{Ah, old Kogan must've gone completely crazy by now, right? Many scavengers went there to make money when all the fuss about that new branch of the cartel started. I was afraid to go on such a long journey. But now there's no point in going -- they say the ruins up there have run dry, and the cartel is broken up.}
{259}{}{So what do you do?}
{260}{}{There's no scavengers where I'm from. What do you do?}
{261}{}{}
{262}{}{So, low profile... okay... Let's talk about something else.}
{263}{}{We search for useful stuff in ruins and then sell them at the market or to customers. It's a dangerous and difficult job. That's why scavengers formed a whole cartel for large-scale operations.}
{264}{}{Was it really that big of a job?}
{265}{}{Of course. The city grew and demanded more and more things. Now, however, little remains in the ruins. In the past few years, I've been mostly looking for electronics parts and books for the Fire Cult.}
{266}{}{I see. By the way, anything new going on around the city?}
{267}{}{Parts and books? Hmph. Good luck with that. I guess it's time to go.}

{270}{}{Do you know anything about vaults?}
{271}{}{Vaults? What are you talking about? Like bank vaults?}
{272}{}{No, no, I'm talking about the Great Vaults.}
{273}{}{Ah, a the Vault-Tec project. I came across one of those, uh... number 26.}
{274}{}{Really? Where was it?}
{275}{}{In the western ruins, on the edge of the crater. The Scavenger's Cartel once made an expedition there, but the vault was so destroyed we returned empty-handed.}
{276}{}{Hmph. That's too bad. What about other vaults?}
{277}{}{Real eager to find the good stuff, huh? Many've tried, but found only brain cancer or a raider's bullet. If anyone knows about vaults, it's probably the Fire Cult, but they're uh... reluctant to share information.}
{278}{}{Thanks, maybe they can help me.}
{279}{}{No use talking to you then, old fart.}
{280}{}{I see. Let's talk about something else.}

{290}{}{Can you teach me some tricks?}
{291}{}{I don't wanna teach you nothing. I don't like you. You walk around the city making trouble, stirring shit up. Got stung in the ass by a cazador?}
{292}{}{Uh, let's change the subject.}
{293}{}{Fine. Forget it.}
{294}{}{Believe me, this is a dangerous and thankless task.}
{295}{}{Seems like you just don't want to mess with me.}
{296}{}{You're right. I don't like you.}
{297}{}{I understand. I hope you change your mind someday.}
{298}{}{I don't like you either, Bob.}
{299}{}{Sounds like you've got a lot of useful knowledge. I could use it in my travels.}
{300}{}{Sure, sure. But I'm no longer the type to go on trips. I can only tell you about places around the city if it helps.}
{301}{}{Great. Let's look at my pipboy's map...}
{302}{}{The hardest part is avoiding unwanted trouble.}
{303}{}{Thanks, Bob. This will help a lot.}

{350}{}{Anything new going on around here?}
{351}{}{(squints) I don't remember us getting along well enough to cover local news.}
{352}{}{I thought you said you were a scavenger?}
{353}{}{I see, let's leave it at that then.}
{354}{}{Everything's the same in our ghetto. Gangs, cultists, and poverty.}
{355}{}{I see. Let's not talk about bad things.}
{356}{}{Gangs are threatening you guys?}
{357}{}{Not threatening. They own this neighborhood. The Red Cardinals control the entire area. The other, smaller gangs are afraid to even come here.}
{358}{}{What do the Fire Worshippers want with your area?}
{359}{}{What about the Fire Worshippers?}
{360}{}{They aim to take over the entire city. For them, the slums are just a source of cheap labor. They cover it up with good missions, collecting alms for the needy, crap like that. But we need real, actual help, more than anyone else in the city.}
{361}{}{You don't think they're honest?}
{362}{}{(looks around) Shhh! It's better not to ask about cultists if you don't want trouble with them.}
{363}{}{What did you say about the gangs controlling your area?}
{364}{}{It's that serious, huh? I'll keep that in mind then.}
{365}{}{}
{366}{}{Come on, tell me, no one is listening.}
{367}{}{(shakes his head sadly) They're always listening... I've said enough.}
{368}{}{Alright.}
{369}{}{Pathetic.}
{370}{}{I can take care of myself. And you too. Come on, what's wrong with these guys?}
{371}{}{Fire Worshippers aren't what they seem. They appear as good-natured do-gooders, talking about the benefits of literacy, the 'Rebirth' etc. But behind the Cathedral walls, their masks come off. What happens at their secret meetings, only they know.}
{372}{}{Continue.}
{373}{}{I know they're collecting pre-war knowledge and technology. They say this is for the 'Rebirth' of the world. But it's all off limits to ordinary folk. And considering Aaron came to power through bloody violence, under the banners of the Holy Fire, it's not hard to draw conclusions about their real goals.}
{374}{}{Seize control of this whole region?}
{375}{}{You know the old adage, 'war never changes'. Well, it's true. Nobody cares about ordinary folk. Those who went against the church ended up in hard labor or burned at the stake. And if you join the Followers, only way out is in a coffin.}
{376}{}{Sounds... ominous.}
{377}{}{By the way, some have noticed that more people enter the Cathedral than exit. I don't know why. But there are rumors the building is larger than it looks and is connected to some kind of, underground facility. That's how it is. But keep your mouth shut. People who are too chatty about this stuff, go missing.}
{378}{}{In that case, we won't bring this up again.}
{379}{}{I don't believe your stories, Bob the Scavenger. Bye.}
{380}{}{They lied that the Cathedral was used just for peaceful purposes. Under the building, there was a whole bunker with nuclear weapons. After the explosion, many residents began to talk about how the cultists had been intimidating them. I don't trust that cult. Nobody does now.}
{381}{}{I see. I've got a couple more questions.}
{382}{}{It's a shame you don't know the whole story. Bye, Bob the Scavenger.}
