{100}{}{You see a food vendor.}
{101}{}{You see a dark-skinned guy with wild hair and a filthy apron.}

# Floating Lines
{110}{}{A fly in your soup? Well... just eat it.}
{111}{}{Cut off the mold - and into the soup it goes.}
{112}{}{Mole rat meat needs a long boil.}
{113}{}{Step right up before the best gets taken.}
{114}{}{More? Super.}
{115}{}{Fresh rats!}
{116}{}{Damn, my whole body itches.}
{117}{}{Those brahmin herders in San Brahmin charge insane prices.}
{118}{}{This meat is a bit... uhm... different. But you'll like it.}
{119}{}{Meat from the finest trappers in town.}

# Start of Dialogue
{200}{}{(Upon seeing you, the vendor stops swatting flies and pretends they're not swarming around the stall) Hey, what can I get ya?}
{201}{}{What do you have?}
{202}{}{Only the freshest, straight from the wasteland. Want some rat soup? Mmm, delicious rat! Was running through the sewers just this morning.}
{203}{}{Hmm, let me think...}
{204}{}{By the way, I had to raise prices after all the ruckus at the Cathedral.}
{205}{}{Well, that's your right.}

{210}{}{So, what'll it be?}
{211}{}{Nothing.}
{220}{}{I'm afraid to ask, but where's all this meat from?}
{221}{}{Hey, why do you care which sewer the rat came from? They bring them to me from all over the city. What, am I supposed to check every one?}
{222}{}{I shouldn't have asked...}
{223}{}{Do you have anything less... disgusting?}
{224}{}{Sometimes the scavengers bring in those unforgettable pre-war dinners. Mmm! But I keep them for special customers.}
{225}{}{Sell me one before it spoils.}
{226}{}{You eat that pre-war garbage. I want fresh food.}
{227}{}{Pre-war? Then that's not what I'm looking for.}
{228}{}{...Well, okay. (He pulls out a few old boxes from the fridge)}
{229}{}{[Continue]}
{230}{}{Your list of "special clients" must include the Followers of Fire.}
{231}{}{I think a generous tip might sway you. Here's 10 caps.}
{232}{}{(Grinning with crooked teeth) Thanks, mister.}
{233}{}{So, what about those pre-war dinners?}
{234}{}{Half the town knows me. Don't I deserve some respect?}
{235}{}{Don't I deserve some respect?}
{236}{}{Don't piss me off, or I'll trash your lousy place. And I can do it.}
{237}{}{You know, some solid clients ask me to hold onto any boxes that come my way. It's better for me to save the goods for a regular than sell to the first passerby.}
{238}{}{Hmph. I didn't need it that bad anyway.}
{239}{}{(Spreads his arms) Is this a joke? If you don't have caps, then get out! I don't feed beggars.}
{240}{}{[Leave]}
{241}{}{Where'd you suddenly get so much fresh meat, buddy?}
{242}{}{Oh, it's from that herding tribe out west. They finally got smart and started trading with Phoenix.}
{243}{}{I think I know about that.}
{244}{}{Really? Then you know what I'm talkin' about. Pure freshness! Top-grade beef. Expensive, but worth it. Look, I've gotten fat off just one steak, like a pregnant rat. Ha-ha!}
{245}{}{Well, good for you. I hope you're storing all that fat up nicely.}

{250}{}{What happened to Lloyd?}
{251}{}{Some street thug knifed him like a dog. Shouldn't have been flaunting his new suit.}
{252}{}{He bought it with my caps.}
{253}{}{Well, then you're kind of an accomplice, heh-heh... Oh.}
{1253}{}{Well, then you're kind of an accomplice, heh-heh... Oh.}
{254}{}{Hmm. Interesting thought.}
{255}{}{Watch your mouth, or you'll join Lloyd.}

# Attack on the Followers
{300}{}{Tell me about the attack on the Followers.}
{301}{}{Hey, I've got cooking to do. Want some rat soup? Take a bowl, you won't regret it.}
{302}{}{I don't have caps to buy anything.}
{303}{}{And I don't have time to talk. Sorry.}
{304}{}{I see, goodbye.}
{305}{}{Alright, here's 10 caps. While I eat your soup, tell me what happened. Okay?}
{306}{}{Sorry, but that's not even enough for a spoonful of soup.}
{307}{}{Hmm, looks like I miscounted.}
{1307}{}{Hmm, looks like I miscounted.}
{308}{}{Now that's more like it. Eat up, don't make a mess. So, what did you want to know about?}
{309}{}{The attack. Near the casino.}
{310}{}{You filthy worm, shove that rat up your ass and tell me what you saw.}
{311}{}{Hey, hey! I get it. Sorry, didn't mean to piss you off.}
{312}{}{Start talking.}
{313}{}{It was pretty bad. The monks were walking down the street, then these guys in balaclavas jumped out from the corners, like rats from the sewer. Surrounded them and started shooting. Never heard so many gunshots at once. And then they disappeared, like they were never there. It all happened very quickly.}
{314}{}{Got it. But in the future, don't give me a hard time. Or next time I'll give you a hard time.}
{315}{}{The situation is becoming clearer.}
{316}{}{Things are coming into focus. Time to talk to Aaron about this.}
{317}{}{Thanks, you've been very helpful.}
