{100}{}{You see the casino manager.}
{101}{}{You see a well-dressed man surveying the casino.}
{102}{}{You shouldn't wear that inside the casino.}

#First dialogue
{200}{}{Welcome to our casino. It's the *only* operating casino in all of Arizona.}
{201}{}{Unimpressive. I thought it would be more... lively here.}
{202}{}{It should be. However, the people of Phoenix are going through tough times, and it's affecting our business. What can one do, right?}
{203}{}{Can't argue with that.}
{204}{}{The casino looks great. It's amazing what you've done with it.}
{205}{}{We got here through long, hard work. All thanks to Don Diego.}
{206}{}{I see.}

#Re-dialogue
{210}{}{Can I be of assistance?}
{211}{}{No, I'm okay.}

#Banning casino games
{220}{}{I hope so. Why won't they let me play in the casino?}
{221}{}{}
{222}{}{We are happy to continue providing our entertainment services to you. But only with the chips you have left. We won't issue new ones.}
{223}{}{Why?}
{224}{}{Can you explain?}
{225}{}{It's not hard to guess that if people win too much, it hurts the casino's profits. You've already earned enough for a comfortable old age. It's time to give way to new players. Don't you think?}
{226}{}{So I broke the house, right? You can't fool me.}
{227}{}{I can understand your logic, but it still sucks.}
{228}{}{Please, don't be upset. We always value wealthy clients. Let me give you a small gift from our casino to keep things friendly. This bottle contains *real* pre-war whiskey. Not poisoned or irradiated. An expensive and rare pleasure these days.}
{229}{}{That's it? Not enough to heal the wound in my soul.}
{230}{}{Thanks for the gift.}
{231}{}{We also invite you to stay in one of our luxury suites and enjoy the comforts of our casino. Here's the key.}
{232}{}{That's a little better.}
{233}{}{You're very nice.}
{234}{}{Enjoy your stay... Oh, by the way. Don Diego has... noticed you, and would like to discuss some business. I've already informed the guards to let you through.}
{235}{}{Tell him I'll stop by when I have some free time. Bye.}
{236}{}{Certainly. I'd also like have a chat with him.}
{237}{}{Enjoy your stay.}
{238}{}{Yeah, whatever.}
{239}{}{See you.}

#Questions
{250}{}{Do you run the casino?}
{251}{}{In a way. My name is Bill Gatsby. I'm the manager, but Don Diego owns this place.}
{252}{}{Don Diego - who's he?}
{253}{}{I see.}
{254}{}{What, you've never heard of him? He's a man with a capital M. One of the most respected people in the city. But he usually keeps to his office, managing affairs from there.}
{1254}{}{What, you've never heard of him? He's a man with a capital M. One of the most respected people in the city. But he usually keeps to his office, managing affairs from there.}
{255}{}{Why is he called Don?}
{256}{}{I suppose it's a sign of respect. I don't know how or why they started calling him that.}
{257}{}{Can I meet him?}
{258}{}{I don't think so. He only sees people on particularly important matters.}
{259}{}{In a way. My name is Bill Gatsby, I'm the manager.}

{270}{}{How are you coping here after Don Diego's death?}
{271}{}{The casino was practically running itself previously. Of course, now I have the work of two. But these are temporary problems. In the end, Diego was just sitting in his chair, and I was the one doing the real work.}
{272}{}{I see.}
{273}{}{I think you underestimate his contribution to the business... Anyway, let's change the subject.}

{275}{}{I see the casino is still open after that explosion?}
{276}{}{Yes, a terrible event. We were lucky that the explosion was underground and quite far away. And yet, the building suffered serious damage. We'll have it repaired to its original form within a year... Well, so I hope.}
{277}{}{I see.}
{278}{}{Hard to believe.}

{280}{}{They say some Followers were killed near the casino?}
{281}{}{Yes, a terrible story. Personally, I didn't see anything. And retelling rumors is an unpleasant matter. Talk to those who were on the street that day.}
{282}{}{Of course I will.}
{283}{}{Or maybe you're protecting your casino? Maybe it wasn't an accident that the attack happened nearby?}
{284}{}{(the manager's face contorts in tension) We do not deserve such slander. Do you have any solid evidence against us? I thought not. Then we had best end this conversation. Thank you for understanding.}
{285}{}{You're too smooth for your own good. You'd better hope the casino isn't mixed up in this.}
{286}{}{Of course, I believe you. Forget my question.}

#GG is your own man
{290}{}{Come in, amigo. Welcome to Don Diego's family. Now you're a made man, and the family values its people and doesn't abandon them when in trouble. But you also follow the rules. Don't upset your boss - that's the first one.}
{291}{}{Of course, Bill, I get it.}
{292}{}{Great, now I can tell you straight - you're a lousy manager. How's that taste?}
{293}{}{You know, there is some truth in your words. But Don Diego didn't find anyone better for this position. At least he and I have complete trust when it comes to casino operations.}
{294}{}{Yeah, sure.}
{295}{}{Come in and have a seat. Now you're a made man, and the family values its people and doesn't abandon them when in trouble. But remember, it doesn't tolerate traitors. Don't upset Don Diego - and you'll save not only your skin, but your whole family. Hopefully I won't have to repeat this twice.}
{296}{}{Of course, Bill, I get it.}
{297}{}{I know you don't like me. But we have to work together.}
{298}{}{As the manager, I'm above this. If the boss trusts you, then I can overlook personal prejudices.}
{299}{}{You have the right idea, Bill.}
{300}{}{It's good that we understand each other. (hands you a key with a tag) The boss told me to put you in a suite. Even I have never had such an honor. Appreciate this generosity.}
{301}{}{Wow. Finally, I can live in human conditions.}
{302}{}{By the way, if you decide to relax in the casino, keep in mind that the rules are the same for everyone. If you want to play roulette, buy chips and play like a regular player. If you get into debt, the casino won't write it off your account. Got it? Good.}
{303}{}{Fair rules. Well, time to go.}
{304}{}{I'll treat the place like I own it.}

#Work and access to the boss
{320}{}{Do you have any openings? I'm looking for a job.}
{321}{}{Oh no, we have enough people. Don Diego asked not to be bothered with such questions anymore.}
{322}{}{My offer stands, for a while. Goodbye.}
{323}{}{Give me a chance, I can handle any job.}
{324}{}{Hmm. Prove yourself in action and we'll see if you're worth our time.}
{325}{}{I'm listening.}
{326}{}{Still, tell your boss. What if he's interested in a partnership?}
{327}{}{It's no use. Your candidacy... is not quite at the level to talk about partnership. Do you understand?}
{328}{}{Yeah. I understand. Some people are really full of themselves.}
{329}{}{No problem. I understand.}
{330}{}{Two respected men in town should listen to each other. Don't you think?}
{331}{}{Perhaps. You are quite well known in the city. Don Diego might actually be interested in speaking with you.}
{332}{}{Great. When can I meet him?}
{333}{}{Your boss must have a job for me. I'm the champ!}
{334}{}{Hmm, we can always use someone capable. Especially one as *talented* as you.}
{335}{}{Great. So can I meet your boss?}
{336}{}{Don Diego sent me to work. What's your problem?}
{337}{}{Ah, this is our new employee. How nice it is to relieve oneself of the burden of responsibility, at least in small things.}
{338}{}{Continue.}
{339}{}{After Don Diego died, all hell broke loose. I could really use a smart employee.}

{340}{}{Don Diego will see you. Security knows you are coming. Don Diego's office is on the second floor. Behave respectfully with him, keep your weapon holstered, and things may go well. Is that clear? Go.}
{341}{}{Yeah, but you don't have to explain the obvious.}
{342}{}{Oh, don't worry, I'll be very respectful.}

{350}{}{One of our regular customers has completely forgotten about paying off his debts. We need to... remind him. And make sure the debt is paid.}
{351}{}{Sounds pretty easy. What's the catch?}
{352}{}{I don't think he has a single cap to his name. Word is, he has completely drunk himself into oblivion and is on the brink. If so, we will lose a client, and with him, our caps. By the way, it's }
{353}{}{ caps... I'm gonna write that down.}
{354}{}{His name is Badi. You'll find him in the east slums. Now go, I'm a busy man.}
{355}{}{Okay, consider this handled.}
{356}{}{About Badi and his debt.}
{357}{}{Do you have his caps?}
{358}{}{Unfortunately, no. But I'm working on it.}
{359}{}{Remind me where this loser lives?}
{360}{}{(furrows brows in displeasure) He lives in the eastern slums. His name is Badi.}
{361}{}{Got it. Thanks.}
{362}{}{How much does he owe the casino bank?}
{363}{}{ caps. Caps. Don't let this loser deceive you with barter or some kind of service. You have to be careful with people like him.}
{364}{}{ caps that he owes the casino bank.}
{365}{}{Badi is dead. There's nothing more I can do.}
{366}{}{Dead? (shakes head) I'm afraid this very bad news will upset my boss terribly. Well, you have failed at the task you were given. Get lost. We don't need people who can't get things done right.}
{367}{}{Okay...}
{368}{}{Here is his debt, }
{369}{}{ caps. Don't ask how I managed it.}
{370}{}{(raises eyebrows in mild surprise) Well done. Thank you for your... assistance in this matter. Perhaps you *are* worth our time. And here is your fee - one fifth of the amount owed.}
{371}{}{Thank you. Goodbye.}
{372}{}{So, have I proven myself? Maybe your boss has another job for me?}
