{100}{}{You see the bartender.}
{101}{}{You see the bartender. You're not at all surprised to see him here.}
{102}{}{No, no, if you wear this... this 'suit' you're gonna break all the dishes...}
{103}{}{Please take a seat at the counter.}
{104}{}{I need to get back to the bar.}

#Floating lines
{110}{}{Vegas Lights and Brahmin Steak.}
{111}{}{Sorry, were all out of Nuka-Rum.}
{112}{}{Ashen Los Angeles is ready.}
{113}{}{Here's your "Nuclear Mary."}
{114}{}{Who ordered the Atomic Cocktail?}
{115}{}{You've had enough, buddy.}
{116}{}{Don't swallow it all at once.}
{117}{}{Believe me, this cocktail gives me a hard-on.}
{118}{}{Do your parents mind? Just kidding.}
{119}{}{Coffee? Holy shit, you're a real connoisseur.}

#Dialogue
{200}{}{First time at the casino? Hope you enjoy your stay with us.}
{201}{}{I hope so...}
{202}{}{Oh, why so much skepticism? Relax, this is the only place in town where you can really unwind.}
{203}{}{I don't need your sympathy, bartender.}
{204}{}{Is that so? In that case, I should stick around for a little while.}
{205}{}{Pour me something stronger, buddy. Because I'm gonna break the bank.}
{206}{}{That's the spirit! Good luck to you.}
{207}{}{Your establishment will need it.}
{208}{}{Thanks.}

{210}{}{Would you like something to drink?}
{211}{}{I'll hold off for now.}

{212}{}{Hey, look, it's the new arena champion! This is a surprise. Oh wait, I know this isn't exactly the rule, but on a personal note, I want to put in a bottle of beer. Because it's cool. (to myself) Now I'll tell everyone...}
{213}{}{Thanks, man. That's very kind of you.}
{214}{}{This swill is urine. But I like your attitude.}

{215}{}{Oh, it's you. How is Don Diego? I see you are getting along well.}
{216}{}{Shut up and pour me a drink.}
{217}{}{Yeah, just great. What was that booze he was raving about in the bar?}
{218}{}{I suggest you try our tequila. The best you can find today. (leans in and lowers his voice) By the way, the casino has special prices for its own people.}
{219}{}{Special prices? That's cool.}

{220}{}{What's the story with the shootout that happened out front?}
{221}{}{Shady business. Someone attacked some monks who were just walking peacefully. I didn't see anything myself, but I've heard many versions. Don't trust all these rumors.}
{222}{}{Would things clear up with a few caps?}
{223}{}{Listen, we don't like to talk about this. Let's end this conversation.}
{224}{}{Hmph. If I find out you're hiding something, you're screwed.}
{225}{}{Of course, I understand. Forget I asked, buddy.}

{230}{}{Who's in charge here?}
{231}{}{Things are in a bit of a, umm... transition stage. Since Don Diego was killed, I sometimes wonder who's *really* in charge. (thoughtfully) Well, at least I've still got a job.}
{232}{}{I see.}
{233}{}{Do you need the manager? He's in that room next to the stage.}
{234}{}{No, I'm talking about whoever owns the place.}
{235}{}{Don Diego owns this whole business. He was the one who got this whole thing goind and restored the casino. Why do you ask?}
{236}{}{Just curious. Don't pay me any attention.}
{237}{}{I want to meet him.}
{238}{}{That won't be easy. Talk to the manager. He decides who is allowed to see the boss.}
{239}{}{Okay.}

{240}{}{Have you seen George Crook?}
{241}{}{(gestures upward with displeasure)}
{242}{}{What? He's dead!? Damn, what a shame... Oh, he's just upstairs. Of course.}
{243}{}{Up on the second floor? Got it.}

{250}{}{You know everything that goes on here, right?}
{251}{}{Sorry, but I don't sell rumors or information. The boss doesn't like it.}
{252}{}{Then I have nothing else to do here.}
{253}{}{I see, no problem.}
{254}{}{I thought that bartenders knew everything.}
{255}{}{That's not far from the truth. But I've gotta follow the rules.}
{256}{}{I'll... tip you.}
{257}{}{It won't change anything, sir.}
{1257}{}{It won't change anything, ma'am.}
{258}{}{Hmm. Let's do the opposite - I'll pay if you spread good rumors about me.}
{259}{}{I don't understand, is this some kind of prank? You have an excellent reputation in the city already. You looking to be some kind of heroic legend?}
{260}{}{Maybe you're right... Okay, forget it.}
{261}{}{Well, I'll go spend the caps on something more meaningful.}
{262}{}{Ah, I understand, you need a better reputation for your... career? Yes, I can help you there.}
{263}{}{I'm in no rush. Let's come back to this later.}
{264}{}{I'll have to go get some cash. See you.}
{265}{}{I'll pay 100 caps. Just a few good rumors.}
{266}{}{A little story about your trustworthiness? Not a problem.}
{267}{}{I'll pay 200 caps. Come up with something real good, but not too much.}
{268}{}{An exciting brawl in the streets? Or an impressive story from the wasteland? I'll make something for people to talk about.}
{269}{}{I'll pay 300 caps. But you've gotta do your best.}
{270}{}{A heroic legend? (snaps fingers) Idea! I know what to do, you can count on me.}
{271}{}{Here's the caps. I'll be waiting for the results, partner.}
{272}{}{I'll do my best, sir.}
{1272}{}{I'll do my best, ma'am.}
{273}{}{See you.}
{274}{}{Any problems? It's okay, I'll wait.}
{275}{}{Uh, I need to recount...}

{280}{}{You only serve alcoholic drinks?}
{281}{}{Basically, yes. I can also offer clean water, if you like. But few are willing to afford this luxury.}
{282}{}{Where do you get your alcohol from?}
{283}{}{We have many sources. The beer is produced by a couple of local brewers. Sometimes something special, like pre-war whiskey, can be found in old ruins. But we produce tequila ourselves.}
{284}{}{Yourself? You're kidding?}
{285}{}{This is our pride. We order raw materials from southern plantations. Here we prepare drinks and medical alcohol from it. As far as I know, we're the only ones in this business.}
{286}{}{Actual production? That's impressive.}
{287}{}{Hmm, homemade alcohol? Doesn't really sound safe.}
{288}{}{Water, beer, whiskey, and of course, our own in-house tequila.}
{289}{}{Okay, got it.}
{290}{}{Where's your famous tequila? I wanted to order a couple of bottles, but the shelves look empty.}
{291}{}{Sorry. Minor issues in production. We are working to solve the problem, but it'll take some time.}
{292}{}{Too bad. Hope you find a solution.}
{293}{}{What kind of casino is this if you can't even drink here? This place is a joke.}
{294}{}{We have many sources. The beer is produced by a couple of local brewers. Sometimes something special, like pre-war whiskey, can be found in old ruins. We produced tequila ourselves, but the still fell into disrepair. We're still working on this issue.}
{295}{}{Used to make your own tequila? Well, well, keep filling.}
{296}{}{In-house production? It's a shame your not doing it anymore.}
