{100}{}{You see the radio operator.}
{101}{}{You see one of the Followers.}
{102}{}{What is it? Lost? The exit is over there. Outsiders aren't allowed here.}
{1102}{}{What is it? Lost? The exit is over there. Outsiders aren't allowed here.}
{103}{}{Greetings, brother. May the Holy Fire illuminate you.}
{1103}{}{Greetings, sister. May the Holy Fire illuminate you.}
{104}{}{Great Atom... what's wrong with me?}
{105}{}{...I see... Holy Fire...}
{106}{}{I think I've had enough... Don't tempt me anymore, please...}
