{100}{}{You see a rebel.}
{101}{}{You see a man in a balaclava. He seems to be hiding from someone.}
{102}{}{Looks like it's clear. I'll find my way back. See you at the base.}
{103}{}{Thanks for your help. Together, we'll achieve freedom for Phoenix.}
{104}{}{Before you lie the ruins of a once-great city. Radiation levels are probably high here.}

#First dialogue
{200}{}{Who... who are you?}
{201}{}{Elisa and Marcos sent me. They'd lost contact with you.}
{202}{}{Finally... but keep it quiet! We could be overheard. I have no idea how those monks figured me out. They're sharper than they look. Can you help me get back to base?}
{203}{}{What about your mission?}
{204}{}{Forget it. Right now, we need to get past these cultists. The booster is in the building across from here; it's too risky to approach it now.}
{205}{}{Okay, we need to leave.}
{206}{}{But it's impossible to get past the cultists unnoticed... Hmm, how did you manage it?}
{207}{}{We'll have to fight our way out. Are you ready? Then let's move.}
{208}{}{We need to finish your mission first. Wait here.}

#Re-dialogue
{210}{}{We need to get back to base - and make sure no one's on our tail.}
{211}{}{Got it. Let's get moving.}
{212}{}{Hold up, I'll scout ahead.}
{213}{}{Let's go. They're waiting for us at base.}
{214}{}{Stay here while I check the area.}
{215}{}{What was your mission again?}
{216}{}{I had to set up a signal booster in that old building. It's still there, but I had to ditch my gear to avoid getting caught. I'm not going back-it's too risky. What if they've set up an ambush?}
{217}{}{Looks clear. I'll make my way back. See you at base.}
{218}{}{Alright, see you later.}
{219}{}{Looks clear. If it wasn't for you, I'd be in real trouble. Thanks for the help.}

