{100}{}{You see a squatter.}
{101}{}{You see a dirty squatter in rags. The smell is rancid.}

#Floating lines
{110}{}{Huh? What just happened?}
{111}{}{Are you even listening?}
{112}{}{I smell pureskins... Do we have visitors?}
{113}{}{Looks like some fresh tourists in town.}
{114}{}{Not rat season yet, is it?}
{115}{}{Better check the rat traps.}
{116}{}{Ugh, skin's peeling again.}
{117}{}{I gotta... empty my gut.}
{118}{}{*Scratches lazily*}
{119}{}{*Coughs, hacking loudly*}

#Response

#- GG in Tinsmith glasses
{130}{}{Smart choice. Keep those eyes sharp with those glasses.}
{131}{}{Wish I had a pair like that... Maybe I wouldn't have busted my leg twice last week.}
{132}{}{Live down here in the sewers with us, you won't need 'em.}
{133}{}{Stick around long enough, and you'll get used to the dark too.}
{134}{}{Those glasses let you see through clothes or what?}

#- GG sneaks
{135}{}{Why're you sneaking around?}
{136}{}{Who're you hiding from?}
{137}{}{Yeah, you blend in nice with the wall... but I still see you.}
{138}{}{You always move like that?}
{139}{}{Damn drunk tourists...}

#- Common phrases
{150}{}{Nice.}
{151}{}{What're you looking for down here, handsome?}
{152}{}{New guy? Alright, doesn't bother me.}
{153}{}{Lost? City's up top.}
{154}{}{Not often we get tourists this far down.}

{155}{}{It ain't bad here. True enough.}
{156}{}{We share food to get to know each other.}
{157}{}{Shh... Keep it down.}
{158}{}{You listening? That's the city above, breathing.}
{159}{}{It's usually quiet here... until someone drops down from above.}

{160}{}{Hey there.}
{161}{}{What're you searching for down here, beauty?}
{162}{}{New girl? Alright, doesn't bother me.}
{163}{}{Lost? City's up top.}
{164}{}{We don't get many tourists down here.}

