{102}{}{Clearance granted.}
{103}{}{Only silence answers your call signs.}
{104}{}{You press the buttons, but nothing happens. This intercom seems dead.}
{105}{}{This won't work here.}
{106}{}{No one is answering your calls.}

{200}{}{You press the buttons, but nothing happens.}
{201}{}{Hey, is anyone home?}
{202}{}{Only silence answers your call.}
{203}{}{Leave.}
{204}{}{[CHEAT: open]}
{205}{}{(You hear a click, and the door unlocks.)}
{206}{}{Looks like some silent types are in there...}
{207}{}{I'm from the rangers. Here are my call signs.}
{208}{}{Prior Mathias sent me to help the Liberation Party.}
