{100}{}{You see Cadet Burke.}
{101}{}{You see a skinny and very inexperienced cadet. No wonder he was put in this position.}

{200}{}{(You see a young man with a thin neck; looking at you, he can't make eye contact and constantly makes a short, forced grin) Uh, um, hi there! How can I, um, assist you today?}
{201}{}{What is this place?}
{202}{}{This is, uh, an information center... or, um, a reception area, I guess... (straightens up) Anyway, it's where we, uh, talk business with, um, strangers, sir!}
{1202}{}{This is, uh, an information center... or, um, a reception area, I guess... (straightens up) Anyway, it's where we, uh, talk business with, um, strangers, ma'am!}

{203}{}{Who is "we"?}
{204}{}{(makes a confused face) Uh, the Rangers... I mean... (straightens up) Cadet Burke at your, um, service! If you need a senior ranger, you, um, need to make an appointment.}
{205}{}{Who's behind that door?}
{206}{}{Field Commander Helford... But, um, you haven't made an appointment yet, so I, um, can't...}
{207}{}{Great, maybe he can help me.}
{208}{}{Uh, wait a minute!}
{209}{}{[Done]}

{210}{}{I need your boss.}
{211}{}{The General? Oh, um, no, you can't see the General.}
{212}{}{Who can I see?}
{213}{}{Field Commander Helford is, um, behind this door... But you, uh, have to make an appointment, I can't let...}
{214}{}{Great, maybe he can help me.}
{215}{}{Uh, wait a minute!}
{216}{}{[Done]}

{220}{}{Just don't get me in trouble.}
{221}{}{I won't.}
{222}{}{Um, congrats on your promotion. I still have, um, years to serve until I reach the rank of Ranger.}
{223}{}{Good luck.}
