{100}{}{You see a sickly figure, clearly in need of aid.}
{101}{}{You see a villager who appears feverish and parched, symptoms of a serious ailment.}
{102}{}{Your diagnosis confirms the patient is afflicted with radiation sickness.}
{103}{}{The patient awaits your examination.}

{210}{}{(A sickly villager stands before you, suffering from thirst, profuse sweating, shivering, and difficulty breathing)}
{211}{}{[Leave the sick villager be]}
{212}{}{How're you feeling, pal?}
{213}{}{Cough-cough... slowly on the mend. Yesterday, it was touch and go, I tell ya.}
{214}{}{Any idea what brought this on?}
{215}{}{Can't rightly say. Ate the usual fish, visited the same spots as ever.}
{216}{}{Could someone else have passed it on to you?}
{217}{}{Could be... cough-cough... but then others would be sick too.}
{218}{}{I need to pinpoint the cause. Mind if I give you a once-over?}
{219}{}{Sure thing. Strip down or...?}
{220}{}{Yep...}
{221}{}{Alright.}
{222}{}{Looks like you've been hit hard by radiation exposure.}
{223}{}{What? How? Ain't no radiation sources 'round these parts.}
{224}{}{You likely consumed whatever it was. What've you eaten lately?}
{225}{}{Just the usual fish and communal bread... Oh, and some Nuka-Cola from Flick. Could a couple bottles have done this?}
{226}{}{It's a possibility. I'll look into it...}
