{100}{}{You see Miss Milton.}
{101}{}{You see the matriarch of the Milton family.}

#Dialogue
{110}{}{Please, save us from those cursed pig rats!}  
{111}{}{Stop him before he hurts someone!}  
{112}{}{We owe you our lives. If not for you, he would've killed us.}  
{113}{}{Thank you for your help. Now leave - I need to bury my husband.}  
{114}{}{What good are you damn Rangers?! Get out of here!}  
{115}{}{Stay back! Don't come any closer!}  
{116}{}{Thank you for your help. I just hope Nat-Aani's spirit doesn't come back for revenge.}  
