{100}{}{You see a bandit.}
{101}{}{You see a dangerous criminal wielding a shotgun, ready to use it at a moment's notice.}

{110}{}{Stay down and keep quiet!}
{111}{}{Where's that damn kid hiding?}
{112}{}{If that brat doesn't return soon, someone's getting shot for sure.}
{113}{}{Hey old man, feeling lucky?}
{114}{}{Where's the stash of caps?}
{115}{}{Damn it, these losers don't even have any food!}
{116}{}{Who the hell do you think you're dealing with, assholes?!}
{117}{}{If your kid doesn't come back with food, I'll start cutting fingers off.}
{118}{}{Fingers make for good bait.}
{119}{}{}

#Dialogue
{200}{}{Hold it right there! Hands where I can see 'em!}
{201}{}{You're a dead man walking.}
{202}{}{You're surrounded. Surrender before you regret it.}
{203}{}{(pauses to consider for a moment) Fuck you!}
{204}{}{Let's go...}
{205}{}{(pauses to consider for a moment then flees)}
{206}{}{Yeah, get lost.}
{207}{}{Your hostages escaped. Surrender or meet your end.}
{208}{}{What... Don't forget who's holding the gun here. Now, I'm getting out of this valley, and you're going to stay quiet and stay put. Got it?}
{209}{}{Yeah, get lost.}
