{100}{}{You see a caravan leader.}
{101}{}{You see a man in dusty clothes, looking like he's walked miles through the wasteland.}
{102}{}{After you.}
{103}{}{Thanks for your help, soldier.}

{200}{}{Hey! You're with the Brotherhood, right? About damn time - I thought you lot had left me for dead.}  
{201}{}{Never doubt the honor and valor of the Brotherhood.}
{202}{}{This whole mess is because of your damn *Brotherhood*! So yeah, you owe me - now get me the hell out of here!}  
{203}{}{Okay, let's go. I'll lead you to the extraction point from where we launched the attack.}
{204}{}{You better keep your head down for now. Just cover your ears and wait for it to end.}
{205}{}{The Brotherhood is here to help. I have orders to escort you to safety.}
{206}{}{Alright, soldier, I'm with you. But fair warning - if bullets start flying, I'm hauling ass outta here.}  
{207}{}{Let's go. Paladin Dobbs orders that you be taken to safety.}
{208}{}{Then you better sit tight here until this is all over. Wait for my instructions.}
{209}{}{Hide here and keep your head down. I need to check out the situation.}
{210}{}{Hey, where are your paladins? I'm starting to feel a bit uneasy about all this.}  
{211}{}{We've made it. The paladins will pick you up here after the operation is completed.}
{212}{}{I appreciate your help, soldier. Honestly, I never thought I'd be staring at a brahmin's rear end on this scorching road again.}  
{213}{}{Glad to help.}

{220}{}{Tell me what happened with the attack.}
{221}{}{We were haulin' cargo for the Brotherhood, pickin' it up from the Tinsmiths. Somehow, those damn highwaymen got wind of us before we even made it to Casa Nueva for the night. They didn't rush in, though - just kept tailin' us, roundin' up every raider in the area like they were plannin' somethin' big. Sure enough, halfway to Puerto, they hit us hard - whole damn swarm of 'em. We didn't stand a chance. There was no way out.}  
{222}{}{What was in the cargo you were transporting to Puerto?}
{223}{}{Just some fucking electronics. Way above my pay grade. All I know is the Brotherhood wanted some of it handled real careful-like, said it was important or somethin'.}  
{224}{}{What do you know about the attackers?}
{225}{}{Some local raiders. Judging by the way they talked, I'd say they're either from down south or they've been lurking around here long before the Brotherhood showed up.}  
{226}{}{Got it. Enough talk for now.}
