{100}{}{You see the instructor.}
{101}{}{You see a junior paladin, always shouting commands and blowing his whistle at every opportunity.}

{200}{}{Civilian? Stop talking!}
{201}{}{Whatever you say.}
{202}{}{Wait. What is this place?}
{203}{}{Obviously, this is a training room! What do you have eyes for, idiot?}
{204}{}{For... absorbing light, sir.}
{205}{}{Moron! Get out into the corridor and don't come back!}
{1205}{}{Moron! Get out into the corridor and don't come back!}
{206}{}{As you say, sir...}
{207}{}{Um, I was, uh, just looking for the toilet...}
{208}{}{Wow, can I join one of the training sessions?}
{209}{}{Wait, I want to join in the training too.}
{210}{}{Idiot! This is a military base, civilians aren't even allowed here.}
{1210}{}{Idiot! This is a military base, civilians aren't even allowed here.}
{211}{}{Ah, well, I'll go then. Goodbye.}
{212}{}{Is there any way we can skip all this formal stuff? I've got plenty of caps - how about a thousand to smooth things over?}
{213}{}{Hmm. Fine. Let's see how long you last, dirtbag. What's your goal here anyway?}
{214}{}{That's not important yet. I gotta get the caps first.}
{215}{}{Small guns training.}
{216}{}{Big guns training.}
{217}{}{Energy weapons training.}
{218}{}{Unarmed combat training.}
{219}{}{Melee weapons training.}
{220}{}{Grenade and blade throwing training.}
{221}{}{Maybe I should take one of these training sessions. After all, I'm now a paladin of the Brotherhood.}
{222}{}{Maybe I should take one of these training sessions. After all, I'm now a scout for the Brotherhood.}
{223}{}{For ME, you're still a stinking dirtbag who can't be trusted with a stick to stir his own shit with! Now stand still and name your specialty, soldier!}
{1223}{}{For ME, you're still a stinking rag who can't even be trusted with a mop! Now stand still and name your specialty, soldier!}
{224}{}{I, uh, need to check with my commander. Give me a minute, sir.}
{225}{}{Don't whine, don't piss, don't call your mom! Get to the front of the line. Step march!}
{226}{}{Yes, sir!}
