{100}{}{You see a doctor.}
{101}{}{There is a doctor in front of you. If it weren't for the coat, you wouldn't be able to tell him apart from an ordinary soldier.}
{102}{}{If I don't hurry up, I won't need the doctor's services anymore.}
{103}{}{?}

{200}{}{(rubs his hands, looking you over carefully) Civilian? I don't recall any orders for new recruits.}
{201}{}{Yeah, I'm not with the Brotherhood.}
{202}{}{This is the infirmary. I'm not allowed to treat civilians without proper orders.}
{203}{}{Sorry for the interruption.}
{204}{}{I see. Goodbye.}
{205}{}{So, you're the new recruit?}
{206}{}{Yes, I'm the new recruit. The enrollment order should be in place.}
{207}{}{Alright. Otherwise, I'd have to throw you out. Civilians aren't allowed here.}
{208}{}{I just need some medical attention.}
{209}{}{No worries. I'm leaving anyway.}

{210}{}{What happened?}
{211}{}{Nothing. See you later, Doc.}
{212}{}{Did something happen?}

{213}{}{Can I ask you a couple of questions?}
{214}{}{No need. Being a military doctor has taught me to keep my mouth shut during peacetime. Except, of course, when talking to senior officers. They need to know everything.}
{215}{}{Alright, Doc. I'll find someone else to bother.}

{220}{}{I want to talk about Initiate Corwin.}
{221}{}{What's wrong with him? Did that idiot get into trouble again?}
{222}{}{He needs shore leave.}
{223}{}{What, again? The guy's too weak for this job. It was a mistake to take him along. He should be back at base, cleaning guns. But what does this have to do with me?}
{224}{}{I don't know. Nothing I guess. I was just looking in to it. Goodbye.}
{225}{}{I thought you might grant him a leave for health reasons.}
{226}{}{I could. But why should I?}
{227}{}{No reason, I guess. Sorry for bothering you. Bye.}
{228}{}{Well, maybe I can get you some medical supplies. You must need something.}
{229}{}{Alright. Bring me five stimpaks or one of miltary drugs, and I'll give your friend a break.}
{230}{}{I'll think about it.}
{231}{}{Here's five stimpaks.}
{232}{}{I've got some Psycho.}
{233}{}{I have some Buffout.}
{234}{}{That'll do. Good deal.}
{235}{}{I'll go let the Initiate know.}

{240}{}{Hey, Doc. I was just recruited into the Brotherhood's recon squad.}
{241}{}{Another scout? Oh, great. More work for me then. Congrats on joining up.}
{242}{}{What's the deal with scouts?}
{243}{}{Scouts get the worst of it -- radiation, poisoning, you name it. You lot burn through meds faster than anyone else and always need more for the road. Meds are scarce, especially Rad-X.}
{244}{}{So, am I entitled to some meds?}
{245}{}{You get a survival kit: RadAway, Rad-X, antidote, and stimpaks. Use them wisely, or better yet, steer clear of danger, and don't use them.}
{246}{}{Got it. Thanks, Doc.}

{250}{}{Can you patch me up, Doc?}
{251}{}{I can't treat civilians without special orders. We barely have enough for ourselves. Try the Followers of the Apocalypse in Casa Nueva. They'll patch you up with a smile.}
{252}{}{Thanks for the tip. I'll try not to die on the way there.}
{253}{}{Figures. Ordinary folks mean nothing to you. Later, butcher.}
{254}{}{Heal me, Doc.}
{255}{}{You're fine. Now grab your rifle and get back to the fight.}
{256}{}{Will do, Doc!}
{257}{}{Real funny, Doc.}

{260}{}{What's with all the screaming, Doc? Torturing someone?}
{261}{}{Nah, just one of our soldiers losing it. Severe mental case.}
{262}{}{What's wrong with him?}
{263}{}{Insomnia, headaches, hears voices... Can't talk much more about it with strangers. But it's a tough case.}
{264}{}{Maybe he's faking it?}
{265}{}{A Brotherhood soldier, faking it? Doubt it, but it's possible. Everyone's been homesick for California lately.}
{266}{}{If you can't handle him, let me try.}
{267}{}{Normally, I wouldn't take kindly to talk like that. But this is beyond me. I'm no psychologist.}
{268}{}{Let me talk to him. Give me five minutes, Doc.}
{269}{}{You sure he's not faking it?}
{270}{}{What's his condition, exactly?}
{271}{}{You probably know best how to help him. Good luck, Doc.}
{272}{}{Bell seems to have severe psychological trauma.}
{273}{}{I figured as much. But what's the prognosis?}
{274}{}{He mentioned an ashen wasteland. What could that mean?}
{275}{}{No clue. His condition worsened after a mission in the desert. Talk to his squadmates in the wardroom -- they might know more.}
{276}{}{Alright, thanks, Doc.}
{277}{}{After you talked to Bell, he calmed down and slept well. What did you say to him?}
{1277}{}{After you talked to Bell, he calmed down and slept well. What did you say to him?}
{278}{}{Nothing special. Just some old-fashioned therapy.}
{279}{}{Interesting. Wish I was better at that. I stick to cuts and bruises -- delving into the mind is too scary.}
{280}{}{Don't lose hope, Doc.}
{281}{}{No doubt. Stick to what you know well.}
{282}{}{Thanks. And thanks for your help with my patient. I want to share something with you. Here's a surgical kit and a couple of stims. I'm sure you'll find a good use for them.}
{283}{}{Thanks, Doc. Take care.}
