{100}{}{You see a paladin.}
{101}{}{Short haircut, strong armor, pumped-up muscles -- this is a paladin of the Brotherhood of Steel.}

{200}{}{Reporting in: everything is calm.}
{201}{}{How's work? It's quiet here for now.}
{202}{}{Good to see you. But why aren't you on patrol?}
{203}{}{Want to go on patrol? Contact Paladin Latham.}
{204}{}{No paladin is more experienced than General Dixon. That's why he's here.}
{205}{}{We need soldiers like you.}
{206}{}{Welcome to the Brotherhood.}
{207}{}{*Salutes you*}
{208}{}{}
{209}{}{}

{210}{}{Go back to the wasteland, savage.}
{211}{}{Your curiosity can cost you dearly.}
{212}{}{This isn't a place to hang around like it's your home.}
{213}{}{Do you have a pass? You're lucky you have one...}
{214}{}{Just give me a reason, and you'll be thrown overboard.}
{215}{}{My tactics are simple -- strike first before getting stabbed in the back.}
{216}{}{I'm just curious, who let you in?}
{217}{}{Are civilians allowed to wander around the ship now? This is chaos...}
{218}{}{At ease. I don't bite unless given a reason.}
{219}{}{}

{220}{}{We have a saying in the Brotherhood: "A good ally is a dead ally."}
{221}{}{Wait, do you have a pass? Show me...}
{222}{}{You better not piss me off, you stupid hayseed.}
{223}{}{Showing up here unannounced and demanding answers? There's something wrong with your head.}
{224}{}{Stay here and don't move until I find out who you are and how you got past the guards.}
{225}{}{Well, well, we've got a rat here...}
{226}{}{I don't negotiate with civilians.}
{227}{}{Does the guard know you're on the ship?}
{228}{}{What, a stranger on board? You've got five seconds to explain, or else...}
{229}{}{Do you even realize you're on a warship?}

{230}{}{Did something happen?}
{231}{}{You need to talk to our commander.}
{232}{}{This is a restricted area. You can't be here without permission.}
{233}{}{What brought you to the Brotherhood?}
{234}{}{Do you want to join the Brotherhood?}
{235}{}{We usually don't accept outsiders, but there have been exceptions.}
{236}{}{Where are you from?}
