{100}{}{You see the scribes' terminal.}
{101}{}{You see a computer with access to the public network.}
{102}{}{You've successfully copied the scribes' library.}
{103}{}{The library has already been copied to your holodisk.}

#Dialogue
{200}{}{Enter command:}
{201}{}{End session}
{202}{}{Back}
{203}{}{Next}
{204}{}{Return to main menu}

{210}{}{Search for Vault-Tec Vaults}
{211}{}{Latest intel suggests Vault-Tec vaults 25-28 are located around Phoenix. The Brotherhood of Steel High Command has ordered these vaults to be located, assessed, and their resources and equipment utilized for our self-sufficiency or transported to HQ.}
{212}{}{}
{213}{}{}
{214}{}{Vault 24}
{215}{}{Location: Otay Open Space National Forest, near San Diego, California. Condition: Unknown. Population: Unknown. The vault is likely in an area with high radioactive contamination.}
{216}{}{Vault 25}
{217}{}{Vault located in Phoenix and in excellent condition. Now under Brotherhood control and used as a base for the Church of the Holy Fire. Some equipment has been relocated to the Puerto Penasco outpost.}
{218}{}{Vault 26}
{219}{}{Remains of a vault found west of Phoenix. Severely damaged during the nuclear bombardment, the vault and its equipment are completely unusable.}
{220}{}{Vault 27}
{221}{}{Location identified. Currently being excavated by the Church of the Holy Fire under Paladin Ulysses Grant's command.}
{222}{}{Vault 28}
{223}{}{Location and condition unknown.}

{230}{}{Development of Nanostructured Rounds}
{231}{}{Due to a shortage of armor-piercing rounds, limited production of 10mm rounds made from nanostructured metal has begun.}
{232}{}{Bullet production is handled by the Tinsmiths in Two-Sun under a standard trade contract.}
{233}{}{}
{234}{}{Food Self-Sufficiency}
{235}{}{Our food needs are fully met by the Casa Nueva plantations. Currently, surplus crops are being exported.}
{236}{}{Development of Nuclear Weapons}
{237}{}{Per HQ request, we are moving towards nuclear weapons production. Design documentation is complete and the required nuclear material is being extracted.}
{238}{}{For safety, logistics, and efficiency, the final assembly of these weapons is conducted by the Cathedral of Fire representatives in Phoenix under strict Brotherhood supervision.}
