{100}{}{You see Carlos.}
{101}{}{You see a Villa peasant. Something about him seems different now.}
{102}{}{They say real science is coming back to Casa Nueva, just like before the Great War.}
{103}{}{I'll come home someday... to help make it more civilized.}
{104}{}{I have no choice but to leave on a journey. I hope to see a lot of new things.}
{105}{}{How... how can you...}
{106}{}{You... it's all your fault...}

#First dialogue
{200}{}{? Are you... why are you here?}
{201}{}{Obviously to save your ass, Carlos. Let's get out of here...}
{202}{}{Rescue... Rescue me back to what? To scratching around in the dirt with dying crops? To diseases that peasants will never find a cure for? To enemies we can't even fight with primitive weapons? That's no rescue. In Villa I only see the narrow, limited horizons of a handful of farmers.}
{203}{}{What are you talking about?}
{204}{}{We're primitives, amigo, understand that. Primitives who first saw electric light only after being enslaved. It was like living in a tin can until someone opened it and showed us the vast world outside. Villa was just a tiny part of it, not the center like we thought.}
{205}{}{Hold on a minute...}
{206}{}{Only here have I been able to realize my potential and follow my passion for technology, which was forbidden at home. I hid my interests to avoid causing trouble for myself and others. Now I'm free to follow my heart's call, not the herd's. Go away, amigo. Leave me here.}
{207}{}{I'll leave for now. But don't think you've seen the last of me.}
{208}{}{I won't try to change your mind. Adios, amigo.}

{210}{}{Villa's time is over, understand that.}
{211}{}{Alright, alright, enough already.}

{230}{}{Can you explain what's going on here?}
{231}{}{The Tinsmiths are trying to access the ancient technology buried in the Forbidden Zone. They need this tech and resources to expand and promote the idea of Progress. But the area is well-protected. Periodically, groups of slaves and mercenaries are sent in there to retrieve tech, but they usually don't come back.}
{232}{}{Tell me about the Tinsmiths.}
{233}{}{They're a semi-religious clan with a long history. They want to revive ancient technologies they worship and use them to serve humanity.}
{234}{}{Tell me about the Forbidden Zone.}
{235}{}{It's a storage facility for ancient military equipment. The area is heavily fortified and guarded by robots. The Tinsmiths have figured out how to temporarily disable the force field at the main gate, but only for a few seconds. If you're planning to go in, you'll need weapons and some anti-radiation drugs.}
{236}{}{Who else is here from the Villa besides you?}
{237}{}{Your padre and Gerardo. They've already been sent into the Forbidden Zone. If you want to save them, you'll have to go after them.}
{238}{}{I'm heading into the Forbidden Zone. Carlos, I really need your help.}
{239}{}{I... can't help you... The Tinsmiths keep a close watch on me and track everything in their warehouses.}
{240}{}{Thanks for the info. It's time for me to get to work.}
{241}{}{Come on, the Tinsmiths must be interested in my success!}
{242}{}{(Looks around) I can give you something. These are pulse grenades. They say one of these can take down a robot in one hit. Use them as a last resort.}
{243}{}{Thanks, Carlos. You've been a big help.}
{244}{}{Let's get back to other questions.}
{245}{}{It's too risky. Sorry.}

#Fusion Cell
{250}{}{I need a fusion cell for a generator. Can you get one?}
{251}{}{Don't ask me for anything! The Tinsmiths won't like it if I give away tech without their permission.}
{252}{}{This is really important. I need your help!}
{253}{}{No and no again! I'm not risking my position for peasants.}
{254}{}{That's harsh. See you around.}
{255}{}{Maybe there's a way to not raise suspicion...}
{256}{}{That's the spirit.}
{257}{}{(Looks around) If anyone asks, you didn't get this from me.}
{258}{}{Thank you, amigo.}
{259}{}{We'll see about that later...}

#Care
{300}{}{So, are you going back to the Villa?}
{301}{}{Don't even ask. Until the Tinsmiths kick me out, I'm not leaving.}
{302}{}{I won't do it again. Take care.}
{303}{}{You're just a fool. And you'll stay a fool.}
{304}{}{It's too late. The Tinsmiths are defeated, and this area is under the control of hostile machines. If you stay here, you'll die.}
{305}{}{Since Master Hard's death, the Tinsmiths have become even more intolerant of outsiders. Haven't you noticed?}
{306}{}{Have you heard the rumors about your "thefts" yet?}
{307}{}{Is this your doing? Son of a... Looks like you're serious this time.}
{308}{}{You can't hide anywhere. My padre is committed to bringing you back, dead or alive.}
{309}{}{Sorry, but this was the only way to make you listen.}
{310}{}{This is not your world. My padre says the same.}
{311}{}{This is not your world, amigo. Here, you're just a worker, not a part of a community.}
{312}{}{Maybe for now. But I'm growing beyond myself. Someday, I'll join the Tinsmiths as an equal.}
{313}{}{We'll see about that...}
{314}{}{You're right. The Tinsmiths are distrustful of outsiders. Gaining their trust requires fanaticism for technology. It going to be very difficult to join their ranks as an equal.}
{315}{}{Then go back to Villa and share your knowledge there - that's your path.}
{316}{}{Finally, a voice of reason in all this madness.}
{317}{}{}
{318}{}{Damn... I've already made my decision, and you have no idea how hard it was. But it looks like I have no choice.}
{319}{}{So, what have you decided?}

{320}{}{I can't go back to the Villa after everything that happened. They won't accept me, and my knowledge and skills will go to waste. You know how stubborn our people are.}
{321}{}{Maybe there are places where your talents are needed?}
{322}{}{Hmm. Phoenix? No, that place is run by caps. That leaves Casa Nueva. Caravan drivers talked about this small settlement. They say there's a whole scientific lab there, where the best minds in Arizona gather.}
{323}{}{So, what's stopping you from going there?}
{324}{}{It's a tight-knit community. They might not accept me. While I'm here trying to get by, could you go to the scientists in that lab and ask whether I could join them?}
{325}{}{Of course, amigo. I'll do it for old times' sake.}
{326}{}{Thank you, }
{327}{}{. I'll be waiting for news.}
{328}{}{See you.}
{329}{}{No, I need to get home. Solve your problem yourself.}
{330}{}{Too bad. But if you're pass by there, tell one of the scientists about me, okay?}
{331}{}{I can't promise anything.}
{332}{}{Sure, I'll definitely do that.}

{340}{}{We've already discussed this. I can't go home.}
{341}{}{Your call. Goodbye.}
{342}{}{Fools never learn. Goodbye.}
{343}{}{I have good news. The Followers of the Apocalypse have agreed to take you in. I told them about your knowledge and skills.}
{344}{}{That's encouraging. Don't worry about me, I'll find my way. Thank you for everything.}
{345}{}{The main thing is that you don't work for those damn Tinsmiths. Get out of here.}
{346}{}{Maybe someday I'll leave the village for good, like you. Goodbye.}
{347}{}{I'm sorry, but the Followers of the Apocalypse have real problems right now. You won't be able to join them.}
{348}{}{Is it that bad? I've already heard rumors from the caravan leaders. Well, it looks like I have no choice. I'll have to go on a journey. I don't know where yet. Maybe west to California or east to New Mexico. But I won't be staying here.}
{349}{}{Well, that's not a bad idea.}
{350}{}{Goodbye, }
{351}{}{. Thanks for everything.}
