{100}{}{You see the merchant, Clark.}
{101}{}{You see the caravan manager. His dark skin is evidence of countless miles traveled under the scorching sun.}
{102}{}{Have a safe trip.}
{103}{}{We're here. Up the road is a Brotherhood of Steel fort.}

{200}{}{What do you want?}
{201}{}{You don't look like the Tinsmiths around here. I take it you aren't one of them?}
{202}{}{That's right. I'm a caravan driver with a special contract with the Tinsmiths.}
{203}{}{Can I ask you a few questions?}

{210}{}{What do you want?}
{211}{}{Nothing.}
{212}{}{I'd like to ask some more questions.}

{220}{}{What do you do here?}
{221}{}{I transport cargo across the desert. The Tinsmiths trust me with this task like no one else.}
{222}{}{Hauling cargo across the desert? Who needs that?}
{223}{}{It may sound dull, but there are places in the desert that await our cargo eagerly and pay handsomely for it.}
{224}{}{Do you deal in slaves too?}
{225}{}{Not anymore. They used to bring slaves from Phoenix to clear ruins and build settlements. But now there's no need for that. Slaves are more sought after up north these days.}
{226}{}{Where exactly is this Phoenix?}
{227}{}{You really don't know? You've missed a lot. It's a large city to the north. Follow Federal Highway 10, you can't miss it.}
{1227}{}{You really don't know? You've missed a lot. It's a large city to the north. Follow Federal Highway 10, you can't miss it.}
{228}{}{Thanks.}

{230}{}{So who exactly are these Tinsmiths?}
{231}{}{They're like a cult, worshiping technology and progress. Their biggest dream is to upload their consciousness into robotic bodies. Sounds far-fetched, right? But they're already implanting tech into themselves. Their technical skills are unmatched in all of Sonora.}
{232}{}{What are their immediate plans?}
{233}{}{I don't know; I just transport cargo. But the Tinsmiths are definitely planning something big.}
{234}{}{Why do you think that?}
{235}{}{They're buying a lot of uranium ore and slaves. They must be amassing old equipment. This means serious investments, likely in Phoenix or elsewhere. I can already smell the profit for my caravan in the coming years.}
{236}{}{Aren't you headed to where an entire port recently blew up?}
{237}{}{Well, there's almost nothing left there now. But Casa Nueva's plantations are still on the way. Though how long they'll survive without the Brotherhood of Steel's protection is another matter. Sooner or later, they'll fall under the Tinsmiths' control or be abandoned.}
{238}{}{Sounds like life there is only going to get tougher. Let's change the subject.}

{240}{}{Is it hard to carry cargo through the wasteland?}
{241}{}{We're experts at it. We adapt and wait for the right seasons to travel.}
{242}{}{What kind of dangers do you face out there, in Sonora?}
{243}{}{First off, there's dehydration and lack of food. We stock up on water in Casa Grande, which gets us to the Gulf. Then we desalinate sea water.}
{244}{}{What about hunting for game?}
{245}{}{Nothing but radscorpions survive in these sands. It seems like they've chosen Sonora to breed their offspring. We rarely encounter highwaymen; people are scarce in those parts.}
{246}{}{Your story is pretty interesting. Tell me more.}
{247}{}{Thanks for the info.}

{300}{}{I need to get to Steel Port.}
{301}{}{Steel Port? Never heard of it.}
{302}{}{Come on... You can trust me.}
{303}{}{Don't worry, I'm part of the Brotherhood of Steel.}
{304}{}{Don't worry, I'm one of the Followers of Fire.}
{305}{}{Too bad. But maybe you know about other places.}
{306}{}{Believe me, no caravan goes there anymore. Something went bad for the Brotherhood of Steel, and their ship blew up like a damn atomic bomb. Now there's just a radioactive crater and not a single living soul.}
{307}{}{Wow... that's too bad.}
{308}{}{I don't think so.}

{310}{}{Alright, I see you're one of us. We need to be careful; the Brotherhood has many enemies.}
{311}{}{Can I come with your caravan?}
{312}{}{Be ready at 6 AM, don't be late. Carry no more than 150 pounds of cargo. We'll make a stop in Casa Nueva. It's the only settlement on the way to the Brotherhood.}
{313}{}{I'm good to go.}
{314}{}{I'll be there on time.}
{315}{}{No one will take your things! Remove any extra cargo, or we'll leave without you.}
{316}{}{Extra weights's my problem.}
{317}{}{Whatever you say.}
{318}{}{Right, then get ready for a tough trek through the wasteland.}
{319}{}{[Go on a trip]}
{320}{}{Maybe. Or maybe not. Get it under 150.}
{321}{}{Okay, I'll double-check my backpack.}
{322}{}{I'll pay 1000 caps for an escort.}
{323}{}{Are you sure you've got that many caps?}
{324}{}{Let me count again...}

#Other locations
{400}{}{We'll spend the night in this settlement. You have a bit of time to look around. Don't oversleep, or we'll leave without you.}
{401}{}{What can you tell me about this settlement?}
{402}{}{Casa Nueva is a thriving oasis in the middle of this barren desert. It's the best place to live around here. But... regulations here are a little harsh. Be respectful and careful with the locals.}
{403}{}{See you later.}
{404}{}{[Wait for the caravan to depart]}
{405}{}{Leave without me, I'll be sticking around here.}
{406}{}{Your call. But remember, the trek through the barren Sonoran wasteland is tough, even in a caravan.}
{407}{}{Got it. Bye.}
