{100}{}{You see the gatekeeper.}
{101}{}{You see a Tinsmith guarding the entrance to the town.}
{102}{}{Access granted, but we will be monitoring your actions.}
{103}{}{No entry without permission!}
{104}{}{(hides food and looks around) Access granted, but do not cause any issues.}

# Cat-scene at the gate
{110}{}{Seems like there's something going on at the main gate.}
{111}{}{Let me in now! Hard has to listen to me!}
{112}{}{Your minor tribe thinks too highly of itself. Get out.}
{113}{}{How dare you! You've relied on our supplies for years and now you throw us away!}
{114}{}{The Forbidden Zone provides all resources now. You are no longer necessary. Leave before I use force.}
{115}{}{Damn you!}
{116}{}{}
{117}{}{}
{118}{}{}
{119}{}{ }

# Primary dialogue
{200}{}{Stop. This is a restricted area. State your purpose.}
{201}{}{No need, I'm already leaving.}
{202}{}{I see.}

{210}{}{We are not interested. Leave.}
{211}{}{Let me in now, you damn cyborg!}
{212}{}{Okay, I'll leave peacefully. But I might be back.}
{213}{}{Leave. Otherwise, the power of Progress will terminate you.}
{214}{}{We'll see about that, later...}
{215}{}{Access granted. While within, stow your weapon and do not initiate conflict. Do not interact with the slaves. Do not enter the Forbidden Zone without permission. Go straight to the workshop in the hangar and speak with Master Hard, our leader. That is all.}
{216}{}{Pretty harsh set of rules. I'll try not to cause any problems.}
{217}{}{You didn't have to say all that. It's clear enough. Now move aside.}
{218}{}{My bike needs some fixing up.}

{220}{}{I'm looking for my kin.}
{221}{}{They may be present, or they may not. We assimilate units... people from across the wasteland; workers are in demand. If you seek your kin, proceed to the workshop.}
{222}{}{I see.}

{223}{}{I'm here to trade.}
{224}{}{Goods are required. Master Hard is always interested in profitable trade.}
{225}{}{Great, I'm up for a good deal.}

{226}{}{I'm looking for technological knowledge.}
{227}{}{For a century, the Tinsmiths have been tied to a single power source. Who are you to seek knowledge from us? Still, times have changed. Perhaps Master Hard will talk to you.}
{228}{}{That sounds good.}

{229}{}{I need some fixing up done. Here are two hundred caps to start.}
{230}{}{We love work and technology. Your problem is our problem if you can pay.}
{231}{}{I think I can scrounge up enough caps.}

{232}{}{I am a peaceful preacher of the Holy Fire. Let me in for the night, my Tinsmith friend!}
{1232}{}{I am a peaceful preacher of the Holy Fire. Let me in for the night, my Tinsmith friend!}
{233}{}{The Church of the Holy Fire has been a reliable partner for years. Welcome to Two-Sun, preacher.}
{1233}{}{The Church of the Holy Fire has been a reliable partner for years. Welcome to Two-Sun, preacher.}
{234}{}{Thank you.}

{235}{}{I am from the Brotherhood of Steel.}
{236}{}{We recognize the supremacy of the Brotherhood. Your technology remains unparalleled.}
{237}{}{That's true.}

{238}{}{See this robe? I am a Follower of Fire. We have always had good relations with you Tinsmiths.}
{239}{}{Since your citadel's fall, your presence here is a calculated risk. Depart now, and do not disrupt our order.}
{240}{}{Damn...}

{241}{}{I'm heading from the Cathedral of Fire to Steel Port. I was told I could find lodging here for the night.}
{242}{}{The Church of the Holy Fire's contributions are acknowledged. Access granted.}
{243}{}{Thank you.}
{244}{}{I'm here to trade. This atomic clock isn't the only thing I've got.}

# Re-dialogue
{250}{}{Access granted, but we will be monitoring your actions.}
{251}{}{Sure, uh, no problem.}
{252}{}{Hard has assigned me to investigate the attack on the caravan.}
{253}{}{It is strange that Master Hard trusts outsiders. But I can only obey.}
{254}{}{Give me some time before I head out.}
{255}{}{Who do you think attacked the caravan?}
{256}{}{Previously, none dared to intrude upon our territory, save for highwaymen and the occasional northern raider. Since Two-Sun interfaced with the outside world, we've established numerous external connections, inevitably drawing in more raiders. Consider it the price of Progress.}
{257}{}{What do the caravan leaders say?}
{258}{}{The assault was precise - raiders lay in wait for days, concealed in a derelict structure by the highway. Their objective was solely the cargo; the caravanners were deemed non-essential and released.}
{259}{}{Is there anything unusual about this?}
{260}{}{Some raiders deployed energy weapons. We hypothesize they acquired them from the Forbidden Zone.}
{261}{}{Show me the location of the attack.}
{262}{}{The location is an old cafe along the interstate, a few miles from this point.}
{263}{}{[Go to the attack site]}
{264}{}{Stow your weapons, or you will face consequences.}
{265}{}{Okay.}

{270}{}{Why did you hang this man on a pole?}
{271}{}{The Followers of Fire have demonstrated their inadequacy for our technology. This individual's remains will function as a deterrent to others.}
{272}{}{I approve. It's time for these cultists to disappear from our world.}
{273}{}{Don't you think that's too cruel? However, it's your call.}
