{100}{}{You see a slave.}
{101}{}{You see a bewildered slave. He still doesn't seem to grasp where he is or what's happening.}

{110}{}{The Tinsmiths want us to disable the robots. But how in the wasteland are we supposed to do that?!}
{111}{}{Damn Tinsmiths! They nabbed me and tossed me into this hellhole.}
{112}{}{So many have died here already. We probably won't be the last.}
{113}{}{We're only alive because of Andres. But even that won't last long.}
