{101}{}{You see your fellow villager. His body is a tapestry of wounds.}
{102}{}{You see a fellow villager. After treatment, he's beginning to get better.}
{103}{}{These injuries are beyond your skills. You need to find real medicine.}
{104}{}{This requires surgery.}

{105}{}{Thanks, amigo. I feel much better now.}
{106}{}{Thanks, amigo. I feel much better now.}
{107}{}{Uh, thanks, amigo. I feel better, but I don't trust this Old World stuff.}
{108}{}{The stranger's medicine works better than our poultices. Hard to find fault with that!}

{110}{}{The raiders... I think they broke my ribs...}

{200}{}{Hail to our savior!}
{201}{}{Take care.}
{202}{}{During treatment, you were wary of pre-war medicine. Why?}
{203}{}{Our ancestors always told us not to trust anything from the Old World. Said it was cursed by spirits and full of danger. But one of those things just saved my life. Now I'm wondering... am I cursed?}
{204}{}{At least you survived. Now rest.}
{205}{}{That outsider sure knows what they're doing. I've never felt this good after being sick! But the ancestors always warned us about trusting Old World things. Now people are going to think I'm cursed or something!}
{206}{}{At least you survived. Now rest.}
{207}{}{How are you feeling after the treatment?}
{208}{}{I thought I was a done for. But now I feel fine. You perform miracles. In the past, anyone who got a broken bone rarely survived. How did we not see your gift before?}
{209}{}{The important thing is that you're alive. Now rest.}

{210}{}{What do you know about the world outside the Villa?}
{211}{}{Not much. I've never ventured beyond our desert. And I'm glad of that. Talk to Jose; he knows more since he sometimes deals with outsiders.}
{212}{}{I'm heading out on a journey. Any help you could give me?}
{213}{}{As you can see, I'm not much use. But I can give you this (pulls out a handful of bullets of different calibers). One of the raiders dropped them during the assault, and I hid them. I hope you find them useful.}
{214}{}{Thanks.}
{215}{}{Do you know anyone who has been outside the Villa?}
{216}{}{What... from the Villa?! Who would leave their home and venture out into the scorching desert?}
{217}{}{Well, yes, um, I have to practice my skills on someone. Gotta go.}
