{100}{}{You see Arthur Carrington.}
{101}{}{You see the same archaeologist from Vault 27.}

# First dialogue
{200}{}{Nice to see you again. I must thank you for the honor. Your Villa opens up new dimensions for my research. I am already amazed at the new discoveries! How you cope without high technology is beyond all understanding. Although some technologies should be brought back into use.}
{201}{}{Maybe so.}
{210}{}{Yes, yes?}
{211}{}{Nothing. Bye.}
{212}{}{Enough about that.}

{220}{}{Well, did you get settled in?}
{221}{}{To be honest, your fellow villagers do not welcome strangers. Children laugh at my thin physique, and adults shy away from conversations. You are the only thing that keeps their discontent at bay. But on the other hand, I see interest. Interest in something that used to be taboo for your community.}
{222}{}{What technologies do you think should be brought back?}
{223}{}{Manual labor is tedious and ineffective. According to my calculations, an aqueduct alone will increase productivity by 250% and reduce labor requirements by 40%. Unfortunately, the elders don't want to listen to me.}
{224}{}{The Villa has managed without technology so far.}
{225}{}{Yes, but at what cost? Diseases, periodic crop failure, risk of injury, and difficult working conditions are just the main troubles that the most basic pre-war technologies, such as a pump or electric lighting, would help avoid.}
{226}{}{Do you think Villa needs this ...needs change?}
{227}{}{That's a question only you can answer. But someday the flame of civilization will reignite in the south. Will you be able to withstand such a fight? I doubt it. You couldn't even defend yourself against a handful of mercenaries with primitive rifles.}
{230}{}{One of the villagers is sick and delirious. Can you cure him?}
{231}{}{I know a little about medicine. I think I can help. But keep in mind that your fellow villagers have a negative attitude towards pre-war medicine.}
{232}{}{We don't have time to think about such things. Just help him!}
{233}{}{I'll try to help him with my own remedies.}
{234}{}{Our weather station is damaged. Can you fix it?}
{235}{}{Of course. Shouldn't be a problem. Meteorology is one of my favorite sciences.}
{236}{}{Then please get on with it.}
{237}{}{Okay, but I'll give it a try first.}
