{100}{}{You see a bandit.}
{101}{}{You see yet another bandit. He is likely not the last one you'll encounter.}
{102}{}{The bandit is unwilling to negotiate.}
{103}{}{Agustín Chacon.}

{110}{}{«Damn it! The Brotherhood crushed our forces in Caborca!»}
{111}{}{«The Brotherhood is really damn strong.»}
{112}{}{«But we outnumber them. We'll overwhelm them with sheer numbers!»}
{113}{}{«If not us, then who?»}
{114}{}{«These lands have belonged to us for generations.»}
{115}{}{«Now these strangers come and set their own rules here!»}
{116}{}{«Bastards!»}
{117}{}{«We must drive the Brotherhood off our lands!»}
{118}{}{«This is our land!»}
{119}{}{«They are invaders!»}
{120}{}{«Just let them try to step on our turf.»}
{121}{}{«Only we have the right to these lands!}
{122}{}{«Increase the patrols. The Brotherhood must not find out about this place.»}
{123}{}{«Where did we mess up? Seems like it all started with that one caravan...»}

{130}{}{*Curses in Spanish*}
{131}{}{*Gives a speech in Spanish*}
{132}{}{Maldita sea!}
{133}{}{Esta es nuestra tierra!}
{134}{}{Hemos fracasado!}
{135}{}{Aumenta las patrullas!}
