{100}{}{You see a cannibal.}
{101}{}{You see a strange man. He smiles hungrily, staring at you.}

{110}{}{Your body can feed my entire family.}
{111}{}{Your buttocks would make a great steak.}
{112}{}{You will be my lunch.}
{113}{}{Share your meat with the hungry!}
{114}{}{I can live off your juicy meat for months.}
{115}{}{I'll eat your giblets last. And the eyes and brain will come first.}
{116}{}{Do you have any idea how many people your meat could feed?}
{117}{}{Sorry, but I'm going to have a bite of you. Nothing personal.}
{118}{}{Nothing personal. I just really want to eat.}
{119}{}{Don't worry, I won't bite... until I roast you well over the fire.}
