{110}{}{Using the trap requires skill.}
{111}{}{Yum-yum! These iguanas weren't fast enough, and soon they'll be someone's dinner.}
{112}{}{With your skills, this trap is more useless than garbage.}
{113}{}{The bait is gone, making this trap useless.}
{114}{}{Two traps in one spot? Waste of effort.}
{115}{}{You have successfully set the trap.}
{116}{}{Good idea, but you have no clue how to do it.}
