{110}{}{The emitter is damaged and non-functional. It cannot be repaired on-site.}
{111}{}{This skill won't help here.}
{112}{}{Emitter retuned to a different frequency.}
{113}{}{You struggle to understand the emitter system.}
{114}{}{Force field activated.}
{115}{}{Force field deactivated.}
{116}{}{This is too difficult to handle during combat.}
{117}{}{The decoder is connected. Now it will be easier to hack this system.}
{118}{}{There's no place to connect a second decoder.}
{119}{}{You are unable to reconfigure the power emitter.}
