{110}{}{ is blocking your way. With more force or some explosives, you could clear the obstacle.}
{111}{}{You aren't strong enough to move this mountain of stones.}
{112}{}{Using brute force, you clear the obstacle and open the passage.}
{113}{}{The explosion sends rocks flying in all directions.}
{114}{}{Looks like you'll need heavier weapons here.}
{115}{}{You can't dig during combat.}
{116}{}{You need special equipment for this.}
