#------------------------------------------------
# Perk names
#------------------------------------------------

{101}{}{Awareness}
{102}{}{Bonus HtH Attacks}
{103}{}{Bonus HtH Damage}
{104}{}{Bonus Move}
{105}{}{Bonus Ranged Damage}
{106}{}{Bonus Rate of Fire}
{107}{}{Earlier Sequence}
{108}{}{Faster Healing}
{109}{}{More Criticals}
{110}{}{Night Vision}
{111}{}{Animal Friend} # changed
{112}{}{Rad Resistance}
{113}{}{Toughness}
{114}{}{Strong Back}
{115}{}{Sharpshooter}
{116}{}{Silent Running}
{117}{}{Survivalist}
{118}{}{Master Trader}
{119}{}{Educated}
{120}{}{Healer}
{121}{}{Scavenger's Instinct} # changed
{122}{}{Better Criticals}
{123}{}{Empathy}
{124}{}{Slayer}
{125}{}{Sniper}
{126}{}{Silent Death}
{127}{}{Action Boy}
{128}{}{!Reserve}
{129}{}{Lifegiver}
{130}{}{Dodger}
{131}{}{Snakeater}
{132}{}{Computer Whiz} # changed
{133}{}{Medic}
{134}{}{Master Thief}
{135}{}{Speaker}
{136}{}{Heave Ho!}
{137}{}{Biker} # changed
{138}{}{Pickpocket}
{139}{}{Ghost}
{140}{}{Forgotten Hero}
{141}{}{! Reserve}
{142}{}{Eternal Wanderer} # changed
{143}{}{Rehabilitation}
{144}{}{Pathfinder}
{145}{}{Beginning to Mutate}
{146}{}{Scout}
{147}{}{Mysterious Stranger}
{148}{}{Wanderer's Intuition} # changed
{149}{}{Quick Pockets}
{150}{}{Smooth Talker}
{151}{}{Swift Learner}
{152}{}{Tag!}
{153}{}{Mutate!}
{154}{}{Nuka-Cola Addiction}
{155}{}{Buffout Addiction}
{156}{}{Mentats Addiction}
{157}{}{Psycho Addiction}
{158}{}{RadAway Addiction}
{159}{}{! Weapon Long Range}
{160}{}{! Weapon Accurate}
{161}{}{! Weapon Penetrate}
{162}{}{! Weapon Knockback}
{163}{}{! Powered Armor}
{164}{}{! Combat Armor}
{165}{}{! Weapon Scope Range}
{166}{}{! Weapon Fast Reload}
{167}{}{! Weapon Night Sight}
{168}{}{! Weapon Flameboy}
{169}{}{! Armor Advanced I}
{170}{}{! Armor Advanced II}
{171}{}{Jet Addiction}
{172}{}{! Reserve}
{173}{}{! Armor Charisma}
{174}{}{! Reserve}
{175}{}{Seasoned Fighter}
{176}{}{! Do not use}
{177}{}{! Do not use}
{178}{}{Mutated Looks}
{179}{}{Mutated Phisiology}
{180}{}{Adrenaline Rush}
{181}{}{Wasteland Lessons} # changed
{182}{}{Math Logic} # changed
{183}{}{Demolition Expert}
{184}{}{Gambler}
{185}{}{Gain Strength}
{186}{}{Gain Perception}
{187}{}{Gain Endurance}
{188}{}{Gain Charisma}
{189}{}{Gain Intelligence}
{190}{}{Gain Agility}
{191}{}{Gain Luck}
{192}{}{Harmless}
{193}{}{Here and Now}
{194}{}{Block Strike} # changed
{195}{}{Sonoran Expert}
{196}{}{Hollywood Karma}*** what to do...
{197}{}{Light Step}
{198}{}{Living Anatomy}
{199}{}{Intimidation} # changed
{200}{}{Negotiator}
{201}{}{Pack Rat} # keeping as probably a reverse translation issue, but used sonora description
{202}{}{Pyromaniac}
{203}{}{Quick Recovery}
{204}{}{Salesman}
{205}{}{Stonewall}
{206}{}{Thief}
{207}{}{Weapon Handling}
{208}{}{Pre-war medicine}
{209}{}{Alcohol Boosts Health}
{210}{}{Alcohol Boosts Health II}
{211}{}{Alcohol Reduces Health}
{212}{}{Alcohol Reduces Health II}
{213}{}{Purification} # changed
{214}{}{Purification II} # changed
{215}{}{Radiation Harms Health} # changed
{216}{}{Radiation Harms Health II} # changed
{217}{}{!Reserve}
{218}{}{! Weapon - knockout}
{219}{}{! Do not use}

#------------------------------------------------
# Descriptions of perks
#------------------------------------------------

{1101}{}{With Awareness, you are given detailed information about any critter you examine.  You see their exact hit points and information about any weapon they are equipped with.}
{1102}{}{You have learned the secret arts of the East, or you just punch faster.  In any case, your Hand-to-Hand attacks cost 1 AP less to perform.}
{1103}{}{Experience in unarmed combat has given you the edge when it comes to damage.  You cause +2 points of damage with hand-to-hand and melee attacks for each level of this Perk.}
{1104}{}{For each level of Bonus Move, you get 2 free APs each turn that can only be used for movement.  In other words, you can move 2 free hexes each turn for each level of this Perk.}
{1105}{}{Your training in firearms and other ranged weapons has made you more deadly in ranged combat.  For each level of this Perk, you do +2 points of damage with ranged weapons.}
{1106}{}{This Perk allows you to pull the trigger a little faster and still remain as accurate as before.  Each ranged weapon attack costs 1 AP less to perform.}
{1107}{}{You are more likely to move before your opponents in combat, since your Sequence is +2 for each level of this Perk.}
{1108}{}{With each level of this Perk, you get a +2 bonus to your Healing Rate.  This is in addition to your normal healing rate, thus you heal faster.}
{1109}{}{You are more likely to cause critical hits in combat if you have this Perk.  Each level of More Criticals gets you an additional +5% chance to cause a critical hit.}
{1110}{}{With the Night Vision Perk, you can see in the dark better.  This will reduce the overall darkness level by 20%.}
{1111}{}{You can temporarily calm a wild animal by feeding it. Each rank makes this process quicker.}
{1112}{}{You are better able to avoid radiation and the bad effects radiation causes.  Each level of this Perk improves your Radiation Resistance by 15%.}
{1113}{}{When you are tough, you take less damage.  Each level of this Perk adds +10% to your general damage resistance.}
{1114}{}{AKA Mule.  You can carry an additional 50 pounds of equipment for each level of this Perk.}
{1115}{}{You have a talent for hitting things at longer distances.  For each level of this Perk, you get a +2 bonus to Perception for the purposes of determining range modifiers.  It's easier than ever to kill at long range!}
{1116}{}{With this Perk, you now have the ability to move quickly and still remain quiet.  You can Sneak and run at the same time.  Without this Perk, you would automatically stop Sneaking if you ran.}
{1117}{}{You are a master of the outdoors.  This Perk confers the ability to survive in hostile environments.  You get a +25% bonus to Outdoorsman.}
{1118}{}{You have mastered one aspect of bartering - buying goods far more cheaply than normal. With this Perk, you get a 25% discount when purchasing items from a store or another trader.}
{1119}{}{Each level of Educated adds +2 skill points when you gain a new experience level. This Perk works best when purchased early in your adventure.}
{1120}{}{The healing of bodies comes easier to you with this Perk. Each level of this Perk heals 4-10 additional hit points when using the First Aid or Doctor skills.}
{1121}{}{You've got a knack for unearthing treasure. Now, you'll find more valuable loot in greater quantities, and stashes will be marked on your mini-map. Plus, traders will have 10% more caps for you to barter with.}
{1122}{}{The critical hits you cause in combat are more devastating. You gain a 20% bonus on the critical hit table, almost ensuring that more damage will be done. This does not affect the chance to cause a critical hit.}
{1123}{}{You have studied other human beings, giving you inside knowledge of their emotional reaction to you.  You will see the reaction level of the person you are talking to when involved in an indepth conversation.}
{1124}{}{The Slayer walks the earth!  In hand-to-hand combat all of your hits are upgraded to critical hits, causing destruction and mayhem.}
{1125}{}{You have mastered the firearm as a source of pain.  With this Perk, any successful hit in combat with a ranged weapon will be upgraded to a critical hit if you also make a Luck roll.}
{1126}{}{While Sneaking, if you hit a critter in the back, you will cause double damage using a hand-to-hand attack.  Silent Death is that kind of Perk.}
{1127}{}{Each level of Action Boy gives you an additional AP to spend every combat turn.  You can use these generic APs on any task.}
{1128}{}{( Steadfast Mind in F1)}
{1129}{}{With each level of this Perk, you gain an additional 4 Hit Points every time you advance a level.  This is in addition to the hit points you already gain per level based off of your endurance.}
{1130}{}{You are less likely to be hit in combat if you have this Perk. You gain a +5 to your Armor Class, in addition to the AC bonus from any armor worn.}
{1131}{}{Yum! Tastes like chicken. For each level of this Perk, you gain +25% to your Poison Resistance.}
{1132}{}{You have a deep understanding of pre-war electronics. This ability increases your Repair and Science skills by 10%.}
{1133}{}{The Medic Perk gives you a one-time bonus of +10% to the First Aid and Doctor skills.  Healing skills are a good thing.}
{1134}{}{A Master Thief is proficient at stealing and picking locks. You gain +15 to Stealing and Lockpicking.  Steal from the rich, and give to you.}
{1135}{}{Being a Speaker means you have a one-time bonus of +20% to Speech.  From the mouth of babes and all that.}
{1136}{}{Each level of the Heave Ho! Perk gives you an additional +2 to Strength (up to 10) for purposes of determining range with thrown weapons only. This Perk will not exceed a weapon's maximum range.}
{1137}{}{You've learned enough about motorcycle mechanics and driving techniques to hop on and ride right now. The only thing left is to find a bike that's still in one piece.}
{1138}{}{You are much more adept at stealing than the normal crook. You can steal with the best of them, because with this Perk, you ignore size and facing modifiers when stealing from a person.}
{1139}{}{When the sun goes down or you are in a poorly lit area, you move like a ghost with this Perk.  Your Sneak skill is enhanced +20% in dark conditions.}
{1140}{}{The Wasteland's memory is short; your deeds, whether noble or vile, have faded to dust. Your karma and some titles are now wiped clean.}
{1141}{}{( Flea dealer in F1)}
{1142}{}{Thanks to this ability, you can continue your journey after completing your main mission.}
{1143}{}{You have completed a treatment course for drug addiction. This perk reduces your chances of becoming addicted to chemicals by 50%, and withdrawal will last half as long.}
{1144}{}{The Pathfinder is better able to find the shortest route.  With this Perk, your travel time on the World Map is reduced by 25% for each level.}
{1145}{}{You've been exposed to a mysterious virus and intense radiation. Soon, this will lead to irreversible changes in your body, transforming you into... something else.}
{1146}{}{You have improved your ability to see distant locations, increasing the size of explorations on the World Map by one square in each direction.  You also have a better chance of finding special encounters.}
{1147}{}{With this Perk, you have gained the attention of a Mysterious Stranger, who will appear to help you from time to time.  If your ally is lost in combat, do not expect him (or her) to be replaced.}
{1148}{}{You've traveled enough to develop a special intuition. This ability increases your Outdoorsman skill by 15% and halves the background radiation exposure in locations.}
{1149}{}{You have learned to pack your equipment better.  Accessing your inventory only costs you 2 Action Points in Combat instead of 4.}
{1150}{}{You have learned to increase your dialog options without understanding what you're talking about.  Each level of this Perk will increase your Intelligence by one (up to 10) for purposes of dialog only.}
{1151}{}{You are indeed a Swift Learner with this Perk, as each level gives you an additional +5% bonus whenever you earn experience points.  This is best taken early.}
{1152}{}{Your skills have improved to the point where you can pick an additional Tag Skill.  Tag skills increase twice as fast.}
{1153}{}{The radiation of the wasteland has changed you!  One of your Traits has mutated into something else...}
{1154}{}{You're "hooked" on Nuka-Cola. You need to consume this drink to avoid withdrawal.}
{1155}{}{You're "hooked" on Buffout. You need to consume this drug to avoid withdrawal.}
{1156}{}{You're "hooked" on Mentats. You need to consume this drug to avoid withdrawal.}
{1157}{}{You're "hooked" on Psycho. You need to consume this drug to avoid withdrawal.}
{1158}{}{You're "hooked" on RadAway. You need to consume this drug to avoid withdrawal.}
{1159}{}{Sniper Shot.}
{1160}{}{Precision Aim (+20% hit chance).}
{1161}{}{Increased Armor Penetration (+80% armor penetration ).}
{1162}{}{Knockback of enemy ( more chances than without the ability - 1 hex for 5 points of damage ).}
{1163}{}{Power Armor (+3 Strength, +30 Radiation Resistance ).}
{1164}{}{Combat Armor (+20 Radiation Resistance ).}
{1165}{}{Scope ( changes the hit probability calculation formula ).}
{1166}{}{High-speed Reload ( only 1 AP is spent on reloading).}
{1167}{}{Night Vision Scope ( removes darkness penalty ).}
{1168}{}{Hot Shot ( lowers the threshold for the victim's combustion animation ).}
{1169}{}{Improved Power Armor I (+4 Strength, +60 Radiation Resistance ).}
{1170}{}{Improved Power Armor II (+4 Strength, +75 Radiation Resistance ).}
{1171}{}{Everything is moving so slowly... you need to get some more Jet, right NOW!}
{1172}{}{( Tragic addiction in F2)}
{1173}{}{Impressive armor (+2 Charisma).}
{1174}{}{( Gekko skinning in F2)}
{1175}{}{Your body has toughened up from constant brawls and training. You gain +5 resistance to normal damage and explosions.}
{1176}{}{( Subcutaneous Armor II in F2)}
{1177}{}{( Phoenix Armor I in F2)} #Phoenix Armor
{1178}{}{Your mutation process is complete. Your Charisma has dropped to the minimum.}
{1179}{}{Your mutation process is complete. You gain an additional +10 resistance to energy damage (laser, plasma, fire) and poisons, along with gradual radiation cleansing from your body.}
{1180}{}{With this Perk, you gain +1 to your Strength when you drop below 1/2 of your max hit points.}  # Adrenaline Rush
{1181}{}{You've seen a lot on your journey, but didn't manage to fully absorb this experience. As a result, almost every skill has increased, but only by 2%.}
{1182}{}{You love math and precise data. This ability displays the conditions that contribute to solving a particular issue.}
{1183}{}{You are an expert when it comes to the fine art of handling explosives. They always go off when they're supposed to, as well as causing extra damage.}  # Demolition Expert
{1184}{}{You can roll with the best of them.  You gain +20% to your gambling skill.}  # Gambler
{1185}{}{With this Perk you gain +1 to your Strength.}     # Gain Strength
{1186}{}{With this Perk you gain +1 to your Perception.}   # Gain Perception
{1187}{}{With this Perk you gain +1 to your Endurance.}    # Gain Endurance
{1188}{}{With this Perk you gain +1 to your Charisma.}     # Gain Charisma
{1189}{}{With this Perk you gain +1 to your Intelligence.} # Gain Intelligence
{1190}{}{With this Perk you gain +1 to your Agility.}      # Gain Agility
{1191}{}{With this Perk you gain +1 to your Luck.}         # Gain Luck
{1192}{}{Your innocent demeanor makes stealing from people a little easier. You gain 20% to your Steal skill.}  # Harmless
{1193}{}{With this Perk you immediately gain one experience level.}  # Here and Now
{1194}{}{If your active weapon slot is empty, at the end of your turn, your Armor Class increases by 1/12 of your Unarmed Combat skill and +2 for each unused action point (instead of the usual +1).}
{1195}{}{You have thoroughly studied the geography of the Sonoran Desert. This Perk lifts the "fog of war" on the entire world map, revealing all accessible locations.}
{1196}{}{Your a big star and your Karma shines twice as bright. Whether good or bad, your Karma is doubled for any kind of reaction or modifiers.}  # Karma Beacon
{1197}{}{You are agile, lucky, and always careful. This Perk halves your chances of setting off a trap.}  # Light Step
{1198}{}{You have a better understanding of living creatures and their strengths and weaknesses.  You get a one-time bonus of +10% to Doctor, and you do +5 damage per attack to living creatures.}  # Living Anatomy
{1199}{}{In combat, you can intimidate your opponent to make them abandon their intended attack. The higher your Charisma, the more likely it is to succeed. But this won't work on especially tough enemies.}
{1200}{}{You are a very skilled negotiator.  Not only can you barter with the best of them, but you can talk your way into or out of almost anything.  With this Perk you gain +10% to both Barter and Speech.}  # Negotiator
{1201}{}{Your experience scavenging through ruins has made you better at organizing your backpack. This allows you to carry even more necessary items (+50 to maximum weight).}
{1202}{}{You do extra damage with fire-based weapons, and enemies always seem to die in the most painful fiery fashion.}  # Pyromaniac
{1203}{}{You are quick at recovering from being knocked down.}  # Quick Recovery
{1204}{}{You are an adept salesperson.  With this Perk you gain +20% towards your Barter skill.}  # Salesman
{1205}{}{You are much less likely to be knocked down in combat.}  # Stonewall
{1206}{}{The blood of a thief runs through your veins. With the Thief Perk, you get a one-time bonus of +10% to your Sneak, Lockpick, Steal, and Traps skills.  A well rounded thief is a live thief.}  # Thief
{1207}{}{You can wield weapons much larger than normally allowed. You gain a +3 to your strength for the purposes of Strength checks when trying to wield weaponry.}  # Weapon Handling
{1208}{}{You have mastered various pre-war medical techniques preserved and passed down by the Followers of the Apocalypse. This boosts your Doctor skill by 10%.}
{1209}{}{Your hit points have been enhanced a little by repeated drunkeness.}  # Alcohol Enhanced hit points
{1210}{}{Your hit points have been enhanced a little more by repeated drunkeness.}  # Alcohol Enhanced hit points II
{1211}{}{Your hit points have been lowered slightly by repeated drunkeness.}  # Alcohol Lowered hit points
{1212}{}{Your hit points have been lowered slightly by repeated drunkeness.}  # Alcohol Lowered hit points II
{1213}{}{You've undergone a course of recovery and health improvement using pre-war medical techniques. As a result, your maximum hit point level has increased by 2 points.}
{1214}{}{You've undergone a course of recovery and health improvement using pre-war medical techniques. As a result, your maximum hit point level has increased by 4 points.}
{1215}{}{Your hit point level has decreased by 2 points due to the harmful effects of high radiation exposure. Unfortunately, this is permanent.}
{1216}{}{Your hit point level has decreased by 4 points due to the harmful effects of high radiation exposure. Unfortunately, this is permanent.}
{1217}{}{( Excrement Extraction Expert F2) Ability increases your Speech skill by 5%.}
{1218}{}{Increased KO chance from weapon strikes .}
{1219}{}{( Corrupted in F2)}
