################################################## ########
#
# DESCRIPTIONS OF QUESTS IN PIP-BOY
# (start each new section with 100 and its multiples)
#
################################################## ########

#---------------------------------------------------------------- --------
#Villa
#---------------------------------------------------------------- --------

{100}{}{Investigate the raiders in a nearby town}  
{101}{}{Rescue your people in Flagstaff}  
{102}{}{Liberate your fellow villagers in Two-Sun}  
{103}{}{Address the village Council}  
{104}{}{Recover family heirlooms from the cellars}  
{105}{}{Provide medical aid to a resident in need}  
{106}{}{Eradicate the rat infestation}  
{107}{}{Locate and bring back the runaway child}  
{108}{}{Drive the marauders off the plantations}  
{109}{}{Repair the weather station}  
{110}{}{Eliminate the cult in Phoenix}  
{111}{}{Find Chris-he's probably hiding nearby}  
{112}{}{Blow up the Flagstaff mine on the Council's orders}  
{113}{}{Destroy the machine in Garage City as directed by the Council}  
{114}{}{Secure allies for Villa, as the Council recommends}  

#---------------------------------------------------------------- --------
# Flagstaff
#---------------------------------------------------------------- --------

{200}{}{Locate the Villa's people in the prison pen}  
{201}{}{Free your fellow villagers from captivity by any means necessary}  
{202}{}{Rescue your kinsmen trapped in the mine}  
{203}{}{Repair the drilling machine}  
{204}{}{Eliminate the rat king in the mine}  
{205}{}{Investigate who is attacking patrols in the abandoned area}  
{206}{}{Deliver lunch to the mine administrator}  
{207}{}{Collect the hundred caps Mercenary Davis owes the bar}  
{208}{}{Eliminate the infidel in the name of the Holy Fire}  
{209}{}{Cure the child suffering from radiation sickness}  
{210}{}{Drive the invaders off Randy's farm}  
{211}{}{Retrieve Miss Brandley's personal items}  
{212}{}{Remove Overseer Lash from his position}  
{213}{}{Investigate what's happening at Camp Winon}  

#---------------------------------------------------------------- --------
# GarageCity
#---------------------------------------------------------------- --------

{300}{}{Stop the scavengers in the dorm}  
{301}{}{Get parts for Mr. Kogan from the factory}  
{302}{}{Join the caravan deal}  
{303}{}{Retrieve data from the computer in the garage for Lucas}  
{304}{}{Join the caravan deal}  
{305}{}{Help capture a brahmin}  
{306}{}{Restore the trade route to San Brahmin}  
{307}{}{Set up a trade route to the Ranger lands}  
{308}{}{Arrange an alcohol supply from Flagstaff}  
{309}{}{Shut down the counterfeiting operation}  
{310}{}{Find and return the welding machine}  

#---------------------------------------------------------------- --------
# SanBrahmin
#---------------------------------------------------------------- --------

{400}{}{Help the leader form an alliance}  
{401}{}{Propose an alliance to the tribe on behalf of the missionaries}  
{402}{}{Assist the ranger in driving away the missionaries}  
{403}{}{Stop tequila production in Phoenix}  
{404}{}{Clear the pen of brahmin excrement}  
{405}{}{Discover the secret of the Buried City}  
{406}{}{Clear the oasis of radscorpions}  
{407}{}{Escort the caravan on the way to Phoenix}  
{408}{}{}  
{409}{}{}  

#---------------------------------------------------------------- --------  
# Two-Sun  
#---------------------------------------------------------------- --------  

{500}{}{Disable the force field}  
{501}{}{Locate your padre in the Forbidden Zone}  
{502}{}{Free Villa's people from the Forbidden Zone}  
{503}{}{Convince Carlos, or eliminate him if necessary, at your padre's request}  
{504}{}{Deactivate the security of the Forbidden Zone for the Tinsmiths}  
{505}{}{Identify and stop whoever attacked the caravan}  
{506}{}{Find the missing Tinsmith in Casa Grande}  
{507}{}{Locate Cody's family in Casa Grande}  
{508}{}{Get the fusion cell for the peasant}  
{509}{}{}  

#---------------------------------------------------------------- --------  
# Puerto Penasco  
#---------------------------------------------------------------- --------  

{600}{}{Deliver Ulysses Grant's holodisk to Puerto Penasco}  
{601}{}{Find the missing Brotherhood squad in Inferno}  
{602}{}{Treat Paladin Bell's mental disorder}  
{603}{}{Conduct reconnaissance in the southern region}  
{604}{}{Eliminate the Rangers}  
{605}{}{Join the raids on bandit camps}  
{606}{}{Scout the area in San Felipe}  
{607}{}{}  
{608}{}{}  
{609}{}{}  

#---------------------------------------------------------------- --------  
# Rangers  
#---------------------------------------------------------------- --------  

{700}{}{Repair the water tank on the farm}  
{701}{}{Retrieve the ranger radio code for the spy}  
{702}{}{Fix the equipment at the power plant}  
{703}{}{Escort the young mechanic from Garage City to the power plant}  
{704}{}{Expand the radio station's broadcast range}  
{705}{}{Retrieve a report from the ranger in San Brahmin}
{706}{}{Escort the outcast family to the ferry}  
{707}{}{Locate the missing reconnaissance party in the northern desert}  
{708}{}{Investigate what happened to the people of Quartz}  
{709}{}{Gather map data in Quartz}  
{710}{}{Investigate what happened to the refugees in Garage City}  
{711}{}{Assist Cadet Presley}  
{712}{}{Identify the cause of the sickness in Aqueduct}  
{713}{}{Hunt and kill the legendary radscorpion}  
{714}{}{Retrieve the missing equipment}  
{715}{}{Aid the rebels in Phoenix}  
{716}{}{Find the missing Aqueduct residents}  
{717}{}{Conduct reconnaissance in Puerto Penasco}  
{718}{}{}  
{719}{}{}  

#---------------------------------------------------------------- --------
#Phoenix
#---------------------------------------------------------------- --------

{800}{}{Inquire about Villa slaves in Phoenix}  
{801}{}{Find Uncle Miguel in Phoenix}  
{802}{}{Deliver the heads of the Los Panchos bosses}  
{803}{}{Kill the legendary marksman Gil McCord}  
{804}{}{Investigate recent attacks on monks}  
{805}{}{Infiltrate the rebels}  
{806}{}{Assist George Crook in San Brahmin}  
{807}{}{Eliminate George Crook}  
{808}{}{Locate a Liberation Party agent in the ruins}  
{809}{}{Sabotage the Cathedral at the Liberation Party's request}  
{810}{}{Collect a large debt owed to the casino}  
{811}{}{Recover the stolen letters}  
{812}{}{Assist the Red Cardinal gang in their troubles}  
{813}{}{Address the accident at the nuclear power plant}  
{814}{}{Help Iron Mike seek justice}  
{815}{}{Support the slum dwellers in their struggles}  
{816}{}{}  
{817}{}{}  
{818}{}{}  
{819}{}{}  

#---------------------------------------------------------------- --------  
# Fishing Village (Oil Platform)  
#---------------------------------------------------------------- --------  

{900}{}{Stop the oil rig leak}  
{901}{}{Cure patients suffering from oil poisoning}  
{902}{}{Find Thelma's father's memorabilia}  
{903}{}{Deliver the Geiger counter to the merchant}  
{904}{}{Help Ruiz search for treasure}  
{905}{}{Catch the creature stealing fish catches}  
{906}{}{Investigate a mysterious murder}  

#---------------------------------------------------------------- --------  
# Casa Grande  
#---------------------------------------------------------------- --------  

{1000}{}{Help Steve claim the bathhouse}  
{1001}{}{Collect payment from Sullivan for water pump repairs}  
{1002}{}{Deal with the commotion in an abandoned bar}  
{1003}{}{Confront highwaymen in Casa Grande}  
{1004}{}{Rescue the villager at the train station}  
{1005}{}{Destroy the Blue Shields' fuel depot}  
{1006}{}{Claim the mayor's bounty for the head of the Blue Shields' leader}  
{1007}{}{}  
{1008}{}{}  
{1009}{}{}  

#---------------------------------------------------------------- --------  
# Hermosillo  
#---------------------------------------------------------------- --------  

{1100}{}{Return the radio to the Dominguez ranch}  
{1101}{}{Escort the prisoner to Puerto Penasco}  

#---------------------------------------------------------------- --------  
# San Felipe (Old Lighthouse)  
#---------------------------------------------------------------- --------  

{1200}{}{Check rumors about monsters in the ship graveyard}  
{1201}{}{Eliminate the monsters}  
{1202}{}{Repair the beacon}  
{1203}{}{Find and rescue Gloria}  

#---------------------------------------------------------------- --------  
# Inferno  
#---------------------------------------------------------------- --------  

{1300}{}{Locate Paladin Barkley's entire squad}  
{1301}{}{Help Levi create a mutagen to save his flock}  
{1302}{}{Escort Diana to Casa Nueva}  
{1303}{}{}  
{1304}{}{}  
{1305}{}{}  
{1306}{}{}  
{1307}{}{}  
{1308}{}{}  
{1309}{}{}  

#---------------------------------------------------------------- --------  
# Casa Nueva  
#---------------------------------------------------------------- --------  

{1400}{}{}  
{1401}{}{Find the missing peasant}  
{1402}{}{Help the Followers stop the epidemic}  
{1403}{}{Investigate disappearances at the concrete plant}  
{1404}{}{Cure Chipo's pet despite local opposition}  
{1405}{}{Provide more books for the local school}  
{1406}{}{}  
{1407}{}{}  
{1408}{}{}  
{1409}{}{}  

#---------------------------------------------------------------- --------
# ! Free slot
#---------------------------------------------------------------- --------

{1500}{}{}

#---------------------------------------------------------------- --------
# Old Motel
#---------------------------------------------------------------- --------

{1600}{}{}

#---------------------------------------------------------------- --------
# !DLC Dayglow / San Diego
#---------------------------------------------------------------- --------

{1700}{}{Explore the mysterious city of the dead}  
{1701}{}{Locate Vault 24}  
{1702}{}{Disable the military robot in the ruins of Tijuana}  
{1703}{}{Neutralize Mad Gonzo}  
{1704}{}{Restore the city's power station}  
{1705}{}{Reestablish the city's radio broadcast}  
{1706}{}{Deliver the holodisk to the Old Town}  
{1707}{}{Meet the caravan arriving from the Hub}  
{1708}{}{Search for the treasures of Coronado Island}  
{1709}{}{Restore the monorail service}  
{1710}{}{Organize mariachi performances}  
{1711}{}{Find Donovan}  
{1712}{}{Obtain chips from rogue scavengers at the Factory}  
{1713}{}{Help Granny Judy find her husband Rupert}  
{1714}{}{Work for Mr. De Santi}  
{1715}{}{}  
{1716}{}{Complete Far Go Traders' contract to find relics}  
{1717}{}{Deliver hard liquor}  
{1718}{}{Deliver coffee}  
{1719}{}{Deliver lunches}  
{1720}{}{Find Mortimer's new book}  

#---------------------------------------------------------------- --------
# ! Free slot
#---------------------------------------------------------------- --------

{1800}{}{}

#---------------------------------------------------------------- --------  
# Santa Ana  
#---------------------------------------------------------------- --------  

{1900}{}{Speak with the villagers about the holiday}  
{1901}{}{Recover the missing ceremonial crown}  
{1902}{}{Find and bring Lucia back}  
{1903}{}{Stop Headman Hilario's schemes}  
{1904}{}{Forge a trade alliance with Casa Nueva}  

#---------------------------------------------------------------- --------  
# ! Free slot  
#---------------------------------------------------------------- --------  

{2000}{}{}  

#---------------------------------------------------------------- --------  
# Jackals  
#---------------------------------------------------------------- --------  

{2100}{}{Rescue the captured Ranger}  
{2101}{}{Help Mad Bitch form alliances to solve the hunger crisis}  
{2102}{}{Support Black Fang's plan to leave the valley to find food}  
{2103}{}{Eliminate the Jackals}  
{2104}{}{Raid the Jackal tunnels with the Garage City thugs}  

#---------------------------------------------------------------- --------  
# Car outta Gas Quests  
#---------------------------------------------------------------- --------  

{2200}{}{}  

#---------------------------------------------------------------- --------  
# ! Free slot  
#---------------------------------------------------------------- --------  

{2300}{}{}  

#---------------------------------------------------------------- --------  
# Vault 27  
#---------------------------------------------------------------- --------  

{2400}{}{Locate Vault 27}  
{2401}{}{Uncover the history of Vault 27}  
{2402}{}{Activate the backup generator}  
{2403}{}{Start the backup generator and restore ventilation}  
{2404}{}{Meet with a surviving expedition member}  
{2405}{}{Escort Arthur Carrington to safety}  

#---------------------------------------------------------------- --------  
# Brotherhood of Steel Camp  
#---------------------------------------------------------------- --------  

{2500}{}{}  

#---------------------------------------------------------------- --------  
# Raiders (Highwaymen)  
#---------------------------------------------------------------- --------  

{2600}{}{Eliminate the raider in Casa Grande Prison}  
{2601}{}{Negotiate a truce between the Blue Shields and the Tinsmiths}  
{2602}{}{Forge a truce between the Blue Shields and Casa Grande}  
{2603}{}{Deliver the suspicious package to the pusher in Phoenix}  
{2604}{}{Prepare Chuck for the initiation ceremony}  
{2605}{}{}  
{2606}{}{}  
{2607}{}{}  
{2608}{}{}  
{2609}{}{}  

#---------------------------------------------------------------- --------
# Camp Winon
#---------------------------------------------------------------- --------

{4900}{}{}
