#include "..\headers\define.h"
//---------------------

#define NAME                            SCRIPT_VVCScnc
#define TOWN_REP_VAR                    -1 // привязка к репутации (-1, если не нужно)

#define NUM_TEAM                        TEAM_CULT_ATOMIC      // группа, к которой принадлежит персонаж (-1 если нужно оставить Team, заданный в редакторе)
#define NUM_AI                          AI_PARTY_ARTUR        // AI персонажа (-1 если нужно оставить AI, заданный в редакторе)
#define KILL_SLAVA                      SLAVA_KILL_GOOD       // слава за убийство этого персонажа (SLAVA_KILL_GOOD, SLAVA_KILL_BAD, SLAVA_KILL_NEITRAL, SLAVA_KILL_CHILD)
#define KILL_TOWN_REP                   REP_KILL_NEITRAL      // репутация за убийство этого персонажа (REP_KILL_GOOD, REP_KILL_BAD, REP_KILL_NEITRAL, REP_KILL_CRITICAL для враждебности всего поселения, REP_KILL_CHILD)
#define KILL_FRAC_REP                   FRAC_NON              // принадлежность определенной фракции (-1, если не нужно)

#define FLAG_STEAL                      0  // Нижний порог навыка для кражи (для торговцев 200, для животных 300)
#define FLAG_ALCOHOL                    1  // Примет ли алкоголь от ГГ: 0 - принимает, 1 - не принимает
#define FLAG_FOOD                       1  // Примет ли пищу от ГГ: 0 - принимает, 1 - не принимает

//---------------------

procedure start;
procedure map_enter_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure timed_event_p_proc;
procedure critter_p_proc;
procedure push_p_proc;
procedure use_obj_on_p_proc;
procedure use_skill_on_p_proc;
procedure pickup_p_proc;
procedure combat_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure talk_p_proc;

procedure Node998;
procedure Node999;
procedure NodeStartDialog;

procedure NodeStopDialog000;
procedure NodeStopDialog001;
procedure NodeStopDialog002;
procedure NodeStopDialog003;
procedure NodeStopDialog004;
procedure NodeStopDialog004b;
procedure NodeStopDialog005;
procedure NodeStopDialog006;
procedure NodeStopDialog007;
procedure NodeStopDialog008;
procedure NodeStopDialog009;
procedure NodeStopDialog009b;
procedure NodeStopDialog010;
procedure NodeStopDialog011;

procedure NodeFstDialog100;
procedure NodeFstDialog101;
procedure NodeFstDialog102;
procedure NodeFstDialog103;
procedure NodeFstDialog104;
procedure NodeFstDialog105;
procedure NodeFstDialog106;
procedure NodeFstDialog200;
procedure NodeFstDialog201;
procedure NodeFstDialog202;
procedure NodeFstDialog203;
procedure NodeFstDialog204;
procedure NodeFstDialog205;
procedure NodeFstDialog300;
procedure NodeFstDialog301;
procedure NodeFstDialog302;
procedure NodeFstDialog303;
procedure NodeFstDialog303b;
procedure NodeFstDialog304;
procedure NodeFstDialog305;
procedure NodeFstDialog306;

procedure NodeSndDialog;
procedure NodeSndDialog101;
procedure NodePartyAdd;
procedure NodePartyAdd2;
procedure NodePartyNon;
procedure NodePartyNon2;
procedure NodeParty2;
procedure NodeParty3;
procedure NodeAnswer;
procedure NodeAnswer100;
procedure NodeAnswer101;
procedure NodeAnswer102;
procedure NodeAnswer200;
procedure NodeAnswer201;
procedure NodeAnswer202;
procedure NodeAnswer203;
procedure NodeAnswer300;
procedure NodeAnswer301;
procedure NodeAnswer400;
procedure NodeAnswer401;
procedure NodeAnswer500;
procedure NodeAnswer501;
procedure NodeAnswer502;
procedure NodeAnswer503;

//---------------------

#define LVAR_Timer_Invis                     (7) // время до повторного появления на карте

//---------------------



procedure start begin
end

procedure map_enter_p_proc begin
   if (is_loading_game == false) then begin
       set_start_home
       set_obj_visibility(self_obj, 0);
       add_timer_event(self_obj,3,3);
       add_timer_event(self_obj,3,4);
   end
end

procedure look_at_p_proc begin
   lookProcMsg
end

procedure description_p_proc begin
   dsrptProcMsg
end

procedure timed_event_p_proc begin
   // Таймер за номером 1 зарезервирован под перемещение персонажа по локации
   // Таймер за номером 2 зарезервирован под всплывающие реплики
   if (fixed_param == 1) then begin
       //timer_move_to_home
   end
   if (fixed_param == 2) then begin
       //timer_float_reply(120,123)
   end
   if (fixed_param == 3) then begin
      if (getQuest(GVAR_VAULT27_GO_MERC) == qZero) then begin
      if ((cur_map_index == MAP_PHOENIX_SIGN) or
      (cur_map_index == MAP_PHOENIX_CENTER) or
      (cur_map_index == MAP_PHOENIX_BNDCS) or
      (cur_map_index == MAP_PHOENIX_PLAZA) or
      (cur_map_index == MAP_PHOENIX_CHURCH)) then begin
      setQuest(GVAR_VAULT27_GO_MERC, qStart);
      terminate_combat;
      dialogue_system_enter;
      end
      end
   end
   if (fixed_param == 4) then begin
      if (cur_map_index == MAP_CASA_NUEVA_CITY) then begin
      floater(self_obj, 110, COLOR_MSG_NORMAL);
      end
      else if (cur_map_index == MAP_CASA_NUEVA_GIDROPONIC) then begin
      floater(self_obj, 111, COLOR_MSG_NORMAL);
      end
      else if (cur_map_index == MAP_RANGERS_BASA) then begin
      floater(self_obj, 112, COLOR_MSG_NORMAL);
      end
      else if (cur_map_index == MAP_RANGERS_DAMBA) then begin
      floater(self_obj, 113, COLOR_MSG_NORMAL);
      end
      else if (cur_map_index == MAP_TWO_SUN_GRAVE) then begin
      floater(self_obj, 114, COLOR_MSG_NORMAL);
      end
      else if (cur_map_index == MAP_TWO_SUN_ZAX) then begin
      floater(self_obj, 115, COLOR_MSG_NORMAL);
      end
      else if (cur_map_index == MAP_PUERTO_BASA) then begin
      floater(self_obj, 116, COLOR_MSG_NORMAL);
      end
   end
   if (fixed_param == 5) then begin
      call NodePartyNon2;
   end
end

procedure critter_p_proc begin
   set_critter_options(0,0) //условие нападения (0 личная вражда, 1 вражда клановая, 2 всегда), разворот к ГГ
   if (self_TEAM == TEAM_PLAYER) then begin
      if (cur_map_index == MAP_PHOENIX_BNDCS) then begin
         if (map_var(MVAR_PNX_RING_START) == 1) then begin
            call NodePartyNon2;
         end
      end
   end
   if (getQuest(GVAR_VAULT27_QST_MERC) >= qEnd) then begin
      if (partyPidSelf!=0) then begin
         partyRunToDude // Персонаж следует за ГГ
      end
   end
end

procedure push_p_proc begin
   if (self_TEAM != TEAM_PLAYER) then begin
   script_overrides;
   end
end

procedure use_skill_on_p_proc begin
   skillUseSteal
   skillUseFAid
end

procedure pickup_p_proc begin
   pickupProcCritter
end

procedure use_obj_on_p_proc begin
   UsedItemToCrit_Proc
end

procedure combat_p_proc begin
   effectAttak(0,0,1,1,1) //отравление min, облучение min, травма ног %, травма рук %, травма глаз %
end

procedure damage_p_proc begin
   set_damage_dude
end

procedure destroy_p_proc begin
   setQuest(GVAR_VAULT27_QST_MERC,qStop);
   setQuest(GVAR_VAULT27_STATUS_MERC,qStop);
   if (bitDialog(bit_8) == 0) then begin
   item_add(self_obj,PID_KEY_VAULT27,1)
   end
   kill_critter_opt
   if (cur_map_index == MAP_VAULT_27_INTERIER) then begin
   kill_critter_dude_reply(102,0) // a отрицательная слава, b положительная слава
   end
end

procedure talk_p_proc begin
   setReaction(0) // Отношение к ГГ (1 - персонаж положительный, -1 отрицательный, 0 нейтральный)
   fracReaction(GVAR_TITUL_PHENIX_CULT,20) // Поправка к отношению за принадлежность к фракциям
   fracReaction(GVAR_TITUL_WARRIOR_ROAD,-20) // Поправка к отношению за принадлежность к фракциям
   dialog_proc(0,0,NodeStartDialog,-1,-1)
end

procedure Node998 begin
end

procedure Node999 begin
end

procedure NodeStartDialog begin
   if (cur_map_index != MAP_VAULT_27_INTERIER) then begin
      if (getQuest(GVAR_VAULT27_QST_MERC) < qEnd) then begin
      setQuest(GVAR_VAULT27_QST_MERC, qEnd); // уловка для удобства тестирования в маппере
      end
   end

   if (getQuest(GVAR_VAULT27_GO_MERC) > qEnd) then begin
      call NodeStopDialog011;
   end
   else if (getQuest(GVAR_VAULT27_GO_MERC) == qStart) then begin
      if (local_var(LVAR_Timer_Invis) == 0) then begin
      call NodeStopDialog000;
      end
      else if (local_var(LVAR_Timer_Invis) < game_time) then begin
      call NodeStopDialog004;
      end
      else begin
      call NodeStopDialog001;
      end
   end
   else if (getQuest(GVAR_VAULT27_QST_MERC) < qEnd) then begin
      if (self_elevation == 2) then begin
      call NodeFstDialog100;
      end
      else begin
      call NodeFstDialog200;
      end
   end
   else if (getQuest(GVAR_VAULT27_STATUS_MERC) < qEnd) then begin
      call NodeFstDialog300;
   end
   else begin
      call NodeSndDialog;
   end
end

//----- СТОП-ДИАЛОГ - ожидание в Фениксе

procedure NodeStopDialog000 begin
   if (getQuest(GVAR_PHENIX_CULT_DESTROY) >= qEnd) then begin
      call NodeStopDialog004b;
      Reply(469)
      NAnswer(464,4,NodeStopDialog005)
      NAnswer(489,-3,NodeStopDialog005)
   end
   else if (getQuest(GVAR_PHENIX_PARTY_QST_B) >= qEnd) then begin
      call NodeStopDialog004b;
      Reply(469)
      NAnswer(464,4,NodeStopDialog005)
      NAnswer(489,-3,NodeStopDialog005)
   end
   else begin
      Reply(463)
      NAnswer(464,4,NodeStopDialog002)
      NAnswer(489,-3,NodeStopDialog002)
   end
end

procedure NodeStopDialog001 begin
   zReply(467)
   NAnswer(468,4,Node999)
   NAnswer(490,-3,Node999)
end

procedure NodeStopDialog002 begin
   Reply(465)
   NAnswer(466,4,NodeStopDialog003)
   NAnswer(490,-3,NodeStopDialog003)
end

procedure NodeStopDialog003 begin
   set_local_var(LVAR_Timer_Invis, game_time + ONE_GAME_DAY);
   call NodePartyNon2;
   //set_obj_visibility(self_obj, 1);
   call Node999;
end

procedure NodeStopDialog004 begin
   call NodeStopDialog004b;
   zReply(470)
   NAnswer(471,4,NodeStopDialog005)
   NAnswer(489,-3,NodeStopDialog005)
end

procedure NodeStopDialog004b begin
   set_local_var(LVAR_Timer_Invis, 0);
   setQuest(GVAR_VAULT27_GO_MERC, qEnd);
end

procedure NodeStopDialog005 begin
   if (getQuest(GVAR_PHENIX_CULT_DESTROY) >= qEnd) then begin
   Reply(472)
   end
   else if (getQuest(GVAR_PHENIX_PARTY_QST_B) >= qEnd) then begin
   Reply(472)
   end
   else begin
   Reply(487)
   end
   NAnswer(473,4,NodeStopDialog006)
   NAnswer(491,-3,NodeStopDialog006)
end

procedure NodeStopDialog006 begin
   Reply(474)
   if (town_known(AREA_CASA_NUEVA) == MARK_STATE_VISITED) then begin
   NAnswer(488,4,NodeStopDialog007)
   end
   else begin
   NAnswer(475,4,NodeStopDialog007)
   end
   NAnswer(492,-3,NodeStopDialog007)
end

procedure NodeStopDialog007 begin
   item_add(dude_obj,PID_M_RADAWAY,1)
   item_add(dude_obj,PID_M_STIMPAK,3)
   Reply(476)
   NAnswer(477,4,Node999)
   NAnswer(492,-3,Node999)
end

procedure NodeStopDialog008 begin
   Reply(481)
   NAnswer(482,4,NodeStopDialog009)
   NAnswer(497,-3,NodeStopDialog009)
end

procedure NodeStopDialog009 begin
   Reply(483)
   NAnswer(484,0,NodeStopDialog009b)
end

procedure NodeStopDialog009b begin
   goBarter(0);
   call NodeStopDialog010;
end

procedure NodeStopDialog010 begin
   setQuest(GVAR_VAULT27_GO_MERC, qEnd+1);
   set_SLAVA(25)
   exp_add(1000);
   call NodePartyNon2;
   Reply(485)
   NAnswer(486,4,Node999)
   NAnswer(490,-3,Node999)
end

procedure NodeStopDialog011 begin
   zReply(470)
   NAnswer(486,4,Node999)
   NAnswer(490,-3,Node999)
end

//----- ПЕРВАЯ ВСТРЕЧА - нижний этаж

procedure NodeFstDialog100 begin
   if (getQuest(GVAR_VAULT27_QST_MERC) == qZero) then begin
   Reply(200)
   zNAnswer(201,4,NodeFstDialog101)
   NAnswer(499,-3,NodeFstDialog101)
   end
   else begin
   Reply(204)
   NAnswer(205,4,NodeFstDialog102)
   NAnswer(499,-3,NodeFstDialog101)
   end
end

procedure NodeFstDialog101 begin
   Reply(202)
   NAnswer(203,4,NodeFstDialog105)
   NAnswer(489,-3,NodeFstDialog105)
end

procedure NodeFstDialog102 begin
   Reply(206)
   NAnswer(207,4,NodeFstDialog103)
   NAnswer(210,4,NodeFstDialog104)
end

procedure NodeFstDialog103 begin
   Reply(208)
   NAnswer(209,4,NodeFstDialog105)
end

procedure NodeFstDialog104 begin
   Reply(211)
   NAnswer(209,4,NodeFstDialog105)
end

procedure NodeFstDialog105 begin
   Reply(212)
   NAnswer(213,4,NodeFstDialog106)
   BAnswer(214,4,NodeFstDialog106)
   NAnswer(493,-3,NodeFstDialog106)
end

procedure NodeFstDialog106 begin
   bitDialogExp(bit_1,0)
   set_gvar_bit_on(GVAR_ENCOUNTERS_FLAGS_BIT, bit_4);
   set_map_var(MVAR_Vault_DoorX,1);
   set_local_var(LVAR_Home_Tile,15867);
       move_to(self_obj, HomeTile, 1);
   set_local_var(LVAR_Home_Rotat,5);
       anim(self_obj, ANIMATE_ROTATION, HomeRotat);
   call Node999;
end

//----- ПЕРВАЯ ВСТРЕЧА - на посту смотрителя

procedure NodeFstDialog200 begin
   Reply(220)
   NAnswer(221,4,NodeFstDialog201)
   BAnswer(222,4,NodeFstDialog201)
   NAnswer(489,-3,NodeFstDialog202)
end

procedure NodeFstDialog201 begin
   Reply(223)
   NAnswer(224,4,NodeFstDialog202)
   BAnswer(225,4,NodeFstDialog202)
end

procedure NodeFstDialog202 begin
   Reply(226)
   NAnswer(227,4,NodeFstDialog203)
   BAnswer(228,4,NodeFstDialog203)
   NAnswer(500,-3,NodeFstDialog203)
end

procedure NodeFstDialog203 begin
   Reply(229)
   NAnswer(230,4,NodeFstDialog204)
   BAnswer(231,4,NodeFstDialog204)
   NAnswer(501,-3,NodeFstDialog204)
end

procedure NodeFstDialog204 begin
   Reply(232)
   NAnswer(233,4,NodeFstDialog205)
   NAnswer(492,-3,NodeFstDialog205)
end

procedure NodeFstDialog205 begin
   rm_timer_event(self_obj);
   set_map_var(MVAR_Vault_DoorX,1);
   setQuest(GVAR_VAULT27_QST_MERC,qEnd);
   setQuest(GVAR_VAULT27_STATUS_MERC,qStart);
   call NodePartyAdd2;
   call Node999;
end

//----- ПЕРВАЯ ВСТРЕЧА - побег из убежища

procedure NodeFstDialog300 begin
   if (cur_map_index == MAP_VAULT_27_INTERIER) then begin
   call NodeFstDialog305;
   end
   else if ((cur_map_index == MAP_VAULT_27_EXTERIER) and (self_elevation>0)) then begin
   call NodeFstDialog305;
   end
   else begin
   call NodeFstDialog301;
   end
end

procedure NodeFstDialog301 begin
   exp_add(1000);
   setQuest(GVAR_VAULT27_STATUS_MERC,qEnd);
   //critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,NUM_TEAM);
   set_SLAVA(35)
   setBonusReaction(50)

   Reply(270)
   NAnswer(271,0,NodeFstDialog302)
end

procedure NodeFstDialog302 begin
   Reply(273)
   if ((getQuest(GVAR_PHENIX_CULT_DESTROY) >= qEnd) or (global_var(GVAR_PHENIX_STATUS_CULT_AARON)<0) or (getQuest(GVAR_PHENIX_PARTY_QST_B) >= qEnd)) then begin
   zNAnswer(279,4,NodeFstDialog303b)
   end
   GAnswer(274,4,NodeFstDialog303)
   NAnswer(280,4,NodeFstDialog304)
   NAnswer(492,-3,NodeFstDialog303)
end

procedure NodeFstDialog303 begin
   Reply(275)
   NAnswer(284,4,NodeAnswer)
   NAnswer(282,4,Node999)
   BAnswer(283,4,Node999)
   NAnswer(493,-3,Node999)
end

procedure NodeFstDialog303b begin
   Reply(272)
   NAnswer(284,4,NodeAnswer)
   NAnswer(282,4,Node999)
   BAnswer(283,4,Node999)
   NAnswer(493,-3,Node999)
end

procedure NodeFstDialog304 begin
   Reply(281)
   NAnswer(284,4,NodeAnswer)
   NAnswer(282,4,Node999)
   BAnswer(283,4,Node999)
   NAnswer(493,-3,Node999)
end

procedure NodeFstDialog305 begin
   Reply(250)
   if (cur_map_index == MAP_VAULT_27_INTERIER) then begin
   NAnswer(260,4,NodeFstDialog306)
   end
   NAnswer(251,4,Node999)
   NAnswer(493,-3,Node999)
end

procedure NodeFstDialog306 begin
   if (self_elevation == 2) then begin
      bitDialogExp(bit_2,20)
      Reply(261)
   end
   else if (self_elevation == 1) then begin
      if (tile_distance(dude_tile, 15668) < 12) then begin
      bitDialogExp(bit_3,20)
      Reply(265)
      end
      else if (tile_distance(dude_tile, 16900) < 12) then begin
      bitDialogExp(bit_4,20)
      Reply(264)
      end
      else if (tile_distance(dude_tile, 18539) < 12) then begin
      bitDialogExp(bit_5,20)
      Reply(263)
      end
      else begin
      bitDialogExp(bit_6,20)
      Reply(262)
      end
   end
   else begin
      bitDialogExp(bit_7,20)
      Reply(266)
   end
   NAnswer(267,4,NodeStartDialog)
   NAnswer(251,4,Node999)
end

//----- ДИАЛОГ ПОСЛЕ ПОБЕГА

procedure NodeSndDialog begin
   Reply(random(300,308))

   if (getQuest(GVAR_VAULT27_GO_MERC) == qEnd) then begin
   if (cur_map_index == MAP_CASA_NUEVA_CITY) then begin
   GAnswer(480,4,NodeStopDialog008)
   GAnswer(502,-3,NodeStopDialog008)
   end
   end

   //- Расспросы
   NAnswer(320,4,NodeAnswer)
   if (cur_map_index == MAP_VAULT_27_INTERIER) then begin
   NAnswer(260,4,NodeFstDialog306)
   end
   if (town_known(AREA_PHOENIX) == MARK_STATE_UNKNOWN) then begin
   NAnswer(334,4,NodeSndDialog101)
   end

   //- Управление
   if weapon_invn_self then begin
   NAnswer(459,4,NodeParty2)
   NAnswer(495,-3,NodeParty2)
   end
   if (inven_armor(self_obj) > 0) then begin
   NAnswer(456,4,NodeParty3)
   NAnswer(496,-3,NodeParty3)
   end

   if (cur_map_index == MAP_VAULT_27_INTERIER) then begin
   //на этой карте его нельзя отсоединить
   NAnswer(309,4,Node999)
   end
   else if (self_TEAM == TEAM_PLAYER) then begin
   NAnswer(453,4,NodePartyNon)
   NAnswer(494,-3,NodePartyNon)
   NAnswer(309,4,Node999)
   end
   else begin
   NAnswer(450,4,NodePartyAdd)
   NAnswer(493,-3,NodePartyAdd)
   NAnswer(462,4,Node999)
   end
   NAnswer(490,-3,Node999)
end

procedure NodeSndDialog101 begin
   mark_on_map(AREA_PHOENIX)
   Reply(335)
   NAnswer(336,4,NodeSndDialog)
end

//--- ПАРТИЯ

procedure NodePartyAdd begin
   if (party_member_count(0) > 1) then begin
   Reply(451)
   NAnswer(452,4,Node999)
   NAnswer(497,-3,Node999)
   end
   else begin
   call NodePartyAdd2;
   end
end

procedure NodePartyAdd2 begin
   bitDialogExp(bit_1,0)
   rm_timer_event(self_obj);
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,TEAM_PLAYER);
   party_add(self_obj);
   call Node999;
end

procedure NodePartyNon begin
   call NodePartyNon2;
   Reply(454)
   NAnswer(455,4,Node999)
   NAnswer(498,-3,Node999)
end

procedure NodePartyNon2 begin
   set_local_var(LVAR_Home_Tile, self_tile);
   set_local_var(LVAR_Home_Rotat,self_cur_rot);
   set_local_var(LVAR_Flags,0);
   off_enemy_dude;
   if (cur_map_index == MAP_CASA_NUEVA_CITY) then begin
   set_local_var(LVAR_Home_Tile,16294);
   set_local_var(LVAR_Home_Rotat,3);
   end
   if (cur_map_index == MAP_PHOENIX_SIGN) then begin
   set_local_var(LVAR_Home_Tile,24699);
   set_local_var(LVAR_Home_Rotat,3);
   end
   if ((map_var(MVAR_PNX_RING_START) == 1) and (cur_map_index == MAP_PHOENIX_BNDCS)) then begin
   set_local_var(LVAR_Home_Tile, 18304);
   set_local_var(LVAR_Home_Rotat,2);
   end
   rm_timer_event(self_obj);
   party_remove(self_obj);
   critter_add_trait(self_obj,TRAIT_OBJECT,OBJECT_TEAM_NUM,NUM_TEAM);
end

procedure NodeParty2 begin
   inven_unwield(self_obj);
   Reply(460)
   NAnswer(461,4,NodeSndDialog)
   NAnswer(492,-3,NodeSndDialog)
end

procedure NodeParty3 begin
   item_remove_armor(self_obj)
   Reply(457)
   NAnswer(458,4,NodeSndDialog)
   NAnswer(492,-3,NodeSndDialog)
end

//--- РАССПРОСЫ

procedure NodeAnswer begin
   Reply(random(321,322))
   if (bitDialog(bit_13) == 0) then begin
   NAnswer(350,4,NodeAnswer100)
   end
   NAnswer(360,4,NodeAnswer200)
   NAnswer(370,4,NodeAnswer300)
   if (bitDialog(bit_8) == 0) then begin
   NAnswer(380,4,NodeAnswer400)
   end
   if (getQuest(GVAR_VAULT27_GO_MERC) < qEnd) then begin
   NAnswer(390,4,NodeAnswer500)
   end
   NAnswer(323,4,NodeStartDialog)
end

procedure NodeAnswer100 begin
   bitDialogExp(bit_13,0)
   Reply(351)
   NAnswer(352,4,NodeAnswer101)
end

procedure NodeAnswer101 begin
   Reply(353)
   NAnswer(354,4,NodeAnswer102)
end

procedure NodeAnswer102 begin
   Reply(355)
   NAnswer(333,4,NodeAnswer)
end

procedure NodeAnswer200 begin
   Reply(361)
   NAnswer(362,4,NodeAnswer201)
end

procedure NodeAnswer201 begin
   Reply(363)
   if (global_var(GVAR_VAULT27_KILL_KNOW) > 0) then begin
   if (bitDialog(bit_11) == 0) then begin
   NAnswer(366,4,NodeAnswer203)
   end
   end
   NAnswer(364,4,NodeAnswer202)
   NAnswer(365,4,NodeAnswer202)
end

procedure NodeAnswer202 begin
   Reply(369)
   NAnswer(368,4,NodeAnswer)
end

procedure NodeAnswer203 begin
   bitDialogExp(bit_11,20)
   Reply(367)
   NAnswer(364,4,NodeAnswer202)
   NAnswer(365,4,NodeAnswer202)
end

procedure NodeAnswer300 begin
   Reply(371)
   if (global_var(GVAR_TITUL_REBIRTH) > 0) then begin
   NAnswer(372,4,NodeAnswer301)
   end
   NAnswer(333,4,NodeAnswer)
end

procedure NodeAnswer301 begin
   bitDialogExp(bit_9,20)
   Reply(373)
   NAnswer(333,4,NodeAnswer)
end

procedure NodeAnswer400 begin
   Reply(381)
   NAnswer(382,4,NodeAnswer401)
end

procedure NodeAnswer401 begin
   bitDialogExp(bit_8,0)
   item_add(dude_obj,PID_KEY_VAULT27,1)
   Reply(383)
   if (global_var(GVAR_HOLODISK_02) != 0) then begin
   NAnswer(387,4,NodeAnswer)
   end
   else begin
   NAnswer(386,4,NodeAnswer)
   BAnswer(384,4,NodeAnswer)
   end
end

procedure NodeAnswer500 begin
   Reply(391)
   NAnswer(393,4,NodeAnswer501)
end

procedure NodeAnswer501 begin
   bitDialogExp(bit_10,25)
   Reply(394)
   NAnswerSkill(398,3,NodeAnswer503,SKILL_SCIENCE,60,395,NodeAnswer502)
   NAnswer(392,4,NodeAnswer)
end

procedure NodeAnswer502 begin
   Reply(396)
   NAnswer(397,4,NodeAnswer)
end

procedure NodeAnswer503 begin
   bitDialogExp(bit_12,50)
   setBonusReaction(25)
   Reply(401)
   NAnswer(402,4,NodeAnswer)
   NAnswer(403,4,Node999)
end
