#include "..\headers\define.h"
#include "..\headers\dayglow.h"
#define NAME                    SCRIPT_YSChlRop

procedure start;
procedure map_enter_p_proc;



procedure start begin
end

procedure map_enter_p_proc begin
   if (is_loading_game == false) then begin
      set_obj_visibility(self_obj, 1);
      if (global_var(GVAR_DAYGLOW_CHULA_ROPE)>0) then begin
      set_obj_visibility(self_obj, 0);
      end
   end
end
