#include "..\headers\define.h"
//---------------------

#define NAME                            SCRIPT_PVCMedic
#define TOWN_REP_VAR                    GVAR_TOWN_REP_PHOENIX_CULT // привязка к репутации (-1, если не нужно)

#define NUM_TEAM                        TEAM_CULT_ATOMIC      // группа, к которой принадлежит персонаж (-1 если нужно оставить Team, заданный в редакторе)
#define NUM_AI                          AI_CULT_PHENIX        // AI персонажа (-1 если нужно оставить AI, заданный в редакторе)
#define KILL_SLAVA                      SLAVA_KILL_NEITRAL    // слава за убийство этого персонажа (SLAVA_KILL_GOOD, SLAVA_KILL_BAD, SLAVA_KILL_NEITRAL, SLAVA_KILL_CHILD)
#define KILL_TOWN_REP                   REP_KILL_CRITICAL     // репутация за убийство этого персонажа (REP_KILL_GOOD, REP_KILL_NEITRAL, REP_KILL_BAD, REP_KILL_CHILD, REP_KILL_CRITICAL)
#define KILL_FRAC_REP                   FRAC_PNXCULT          // принадлежность определенной фракции (-1, если не нужно)

#define FLAG_STEAL                      40 // Нижний порог навыка для кражи (для торговцев 200, для животных 300)
#define FLAG_ALCOHOL                    1  // Примет ли алкоголь от ГГ: 0 - принимает, 1 - не принимает
#define FLAG_FOOD                       1  // Примет ли пищу от ГГ: 0 - принимает, 1 - не принимает

//---------------------

procedure start;
procedure map_enter_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure timed_event_p_proc;
procedure critter_p_proc;
procedure use_obj_on_p_proc;
procedure use_skill_on_p_proc;
procedure pickup_p_proc;
procedure combat_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure talk_p_proc;
procedure Node998;
procedure Node999;
procedure NodeStartDialog;
procedure NodeSndDialog;
procedure NodeVilla;
procedure NodeVilla2;
procedure NodeFAIDcost;
procedure NodeFAID;
procedure NodeFAID100;
procedure NodeFAID101;
procedure NodeFAID102;
procedure NodeFAID103;
procedure NodeFAID104;
procedure NodeFAID105;
procedure NodeFAID106;
procedure NodeFAIDnon;
procedure NodeFAIDEnd;

//---------------------

//#define LVAR_Flag_A                     (6) // отвечает за ...

import variable box_stop_use;

variable MedicMany;                     // расчет стоимость медицинских услуг

//---------------------



procedure start begin
end

procedure map_enter_p_proc begin
   if (is_loading_game == false) then begin
       set_start_home
   end
end

procedure look_at_p_proc begin
   lookProcMsg
end

procedure description_p_proc begin
   dsrptProcMsg
end

procedure timed_event_p_proc begin
   // Таймер за номером 1 зарезервирован под перемещение персонажа по локации
   // Таймер за номером 2 зарезервирован под всплывающие реплики
   if (fixed_param == 1) then begin
       timer_move_to_home
   end
   if (fixed_param == 2) then begin
       //timer_float_reply(120,121)
   end
end

procedure critter_p_proc begin
   if (global_var(GVAR_TITUL_PHENIX_CULT) <= 0) then begin
   set_using_stop // привязка хозяина и объекта (удалить, если не нужно)
   end
   pnxCultTeamNoAttak
   set_critter_options(0,0) //условие нападения (0 личная вражда, 1 вражда клановая, 2 всегда), разворот к ГГ
end

procedure use_skill_on_p_proc begin
   skillUseSteal
   skillUseFAid
end

procedure pickup_p_proc begin
   pickupProcCritter
end

procedure use_obj_on_p_proc begin
   UsedItemToCrit_Proc
end

procedure combat_p_proc begin
   effectAttak(0,0,1,1,1) //отравление min, облучение min, травма ног %, травма рук %, травма глаз %
end

procedure damage_p_proc begin
   set_damage_dude
end

procedure destroy_p_proc begin
   kill_critter_opt
end

procedure talk_p_proc begin
   setReaction(1) // Отношение к ГГ(1 - персонаж положительный, -1 отрицательный, 0 нейтральный)
   if (global_var(GVAR_PHENIX_CULT_DESTROY_TIMER) != 0) then begin
   floater(dude_obj,102,COLOR_MSG_RED);
   end
   else begin
   fracReaction(GVAR_TITUL_PHENIX_CULT,40) // Поправка к отношению за принадлежность к фракциям
   dialog_proc(0,0,NodeStartDialog,-1,-1)
   end
end

procedure Node998 begin
   set_enemy_dude;
end

procedure Node999 begin
end

procedure NodeStartDialog begin
   call NodeSndDialog;
end

//--- ПОВТОРНЫЙ ДИАЛОГ

procedure NodeSndDialog begin
   Reply(210)
   if (getQuest(GVAR_MAIN_QUEST_PHENIX) < qEnd) then begin
   NAnswer(240,4,NodeVilla)
   end
   NAnswer(220,4,NodeFAID)
   NAnswer(221,-3,NodeFAID)
   NAnswer(211,4,Node999)
   NAnswer(212,-3,Node999)
end

procedure NodeVilla begin
   Reply(241)
   NAnswer(242,4,NodeVilla2)
end

procedure NodeVilla2 begin
   Reply(243)
   NAnswer(244,4,NodeSndDialog)
end

//--- ЛЕЧЕНИЕ

#define AnswerCost(msg,node)      call NodeFAIDcost; \
                                  if ((item_amnt(dude_obj,PID_BOOTLE_CAPS) >= MedicMany) or (MedicMany == 0)) then begin \
                                  NAnswer(mstr(msg)+MedicMany+mstr(228),0,node) \
                                  end else begin \
                                  NAnswer(mstr(msg)+MedicMany+mstr(228),0,NodeFAIDnon) \
                                  end \

procedure NodeFAIDcost begin
   if town_rep_is_idolized then begin
   MedicMany -= (MedicMany/2);
   end
   if (global_var(GVAR_TITUL_PHENIX_CULT)>0) then begin
   MedicMany := 0;
   end
   if (MedicMany<0) then begin
   MedicMany := 0;
   end
end

procedure NodeFAID begin
   if (global_var(GVAR_TITUL_PHENIX_CULT) > 0) then begin
   call NodeFAID100;
   end
   else begin
   call NodeFAID101;
   end
end

procedure NodeFAID100 begin
   MedicMany := 0;
   Reply(230)
   NAnswer(236,4,NodeFAID106)
   NAnswer(226,4,NodeSndDialog)
   NAnswer(229,-3,NodeFAID106)
end

procedure NodeFAID101 begin
   MedicMany := 0;
   Reply(221)

   if (dude_cur_hits<dude_max_hits) then begin
      MedicMany := (dude_max_hits-dude_cur_hits)*3;
      AnswerCost(222,NodeFAID102)
   end
   if dude_is_crippled then begin
      MedicMany := 25;
      AnswerCost(223,NodeFAID103)
   end
   if (get_critter_stat(dude_obj,STAT_current_rad)>0) then begin
      MedicMany := get_critter_stat(dude_obj,STAT_current_rad)*3;
      AnswerCost(224,NodeFAID104)
   end
   if (get_poison(dude_obj)>0) then begin
      MedicMany := get_poison(dude_obj)*3;
      AnswerCost(225,NodeFAID105)
   end

   NAnswer(226,4,NodeSndDialog)
   NAnswer(229,-3,Node999)
end

procedure NodeFAID102 begin
   critter_heal(dude_obj,dude_max_hits-dude_cur_hits);
   call NodeFAIDEnd;
end

procedure NodeFAID103 begin
   critter_uninjure_full(dude_obj);
   call NodeFAIDEnd;
end

procedure NodeFAID104 begin
   radiation_dec(dude_obj,get_critter_stat(dude_obj,STAT_current_rad));
   call NodeFAIDEnd;
end

procedure NodeFAID105 begin
   poison(dude_obj,-(get_poison(dude_obj)));
   call NodeFAIDEnd;
end

procedure NodeFAID106 begin
   critter_heal(dude_obj,dude_max_hits-dude_cur_hits);
   critter_uninjure_full(dude_obj);
   radiation_dec(dude_obj,get_critter_stat(dude_obj,STAT_current_rad));
   poison(dude_obj,-(get_poison(dude_obj)));
   call NodeFAIDEnd;
end

procedure NodeFAIDnon begin
   Reply(231)
   NAnswer(232,4,Node999)
   NAnswer(229,-3,Node999)
end

procedure NodeFAIDEnd begin
   if (MedicMany>0) then begin
   item_remove(dude_obj, PID_BOOTLE_CAPS, MedicMany)
   end
   PLAY_FADE
   Reply(234)
   NAnswer(235,4,NodeSndDialog)
   NAnswer(237,4,Node999)
   NAnswer(229,-3,Node999)
end
