###------- AMMUNITION
{100}{}{Nuclear Battery}
{101}{}{A small, self-contained unit of energy storage.}
{200}{}{Micro Fusion Cell}
{201}{}{A medium sized energy production unit. Self-contained fusion plant.}
{300}{}{.22 Caliber}
{301}{}{Ammunition. .22 Caliber. Small-caliber unitary rimfire round.}
{400}{}{9mm}
{401}{}{Ammunition. Caliber: 9mm.}
{500}{}{10mm}
{501}{}{Ammunition. Caliber: 10mm.}
{600}{}{10mm NSP}
{601}{}{Ammunition. Caliber: 10mm. Nanostructured Projectile bullets.}
{700}{}{.44 Caliber}
{701}{}{Ammunition. .44 Caliber.}
{800}{}{.50 Caliber}
{801}{}{Ammunition. .50 Caliber. A round for particularly cool pistols and revolvers.}
{900}{}{5mm}
{901}{}{Ammunition. Caliber: 5mm.}
{1000}{}{.308 Caliber}
{1001}{}{Ammunition. .308 Caliber. Rifle round of an old but reliable caliber.}
{1100}{}{12 ga. Shotgun Shells}
{1101}{}{Shotgun ammunition. This particular ammo is marked: "12-gauge shells, not for use by children under the age of 3."}
{1200}{}{12 ga. Shotgun Bullet}
{1201}{}{Shotgun shell loaded with a large bullet.}
{1300}{}{40mm Grenade}
{1301}{}{Ammunition for hand grenade launcher.}
{1400}{}{Flare Round}
{1401}{}{4 gauge flare round for flare pistol.}
{1500}{}{Modified Flare Round}
{1501}{}{Modified 4 gauge flare pistol round.}
{1600}{}{Reinforced Flare Round}
{1601}{}{Reinforced 4 gauge flare pistol round.}
{1700}{}{Universal container}
{1701}{}{Storage container for all occasions.}
###------- THROWN WEAPONS
{1800}{}{Rock}
{1801}{}{It's a rock. The Granite-Inc. model is an upgraded version. Min ST: 1.}
{1900}{}{Throwing Knife}
{1901}{}{A knife, balanced specifically for throwing. Made of titanium, and laser sharpened. Min ST: 2.}
{2000}{}{Grenade (Frag)}
{2001}{}{A generic fragmentation grenade. Contains a small amount of high explosives, the container itself forming most of the damaging fragments. Explodes on contact. Min ST: 3.}
{2100}{}{Grenade (Plasma)}
{2101}{}{A magnetically sealed plasma delivery unit, with detonating explosives. Creates a blast of superheated plasma on contact. Min ST: 4.}
{2200}{}{Grenade (Pulse)}
{2201}{}{An electromagnetic pulse grenade, generating an intense magnetic field on detonation. Doesn't affect biological creatures. Contact fuse. Min ST: 3.}
{2300}{}{Grenade (Nuclear)}
{2301}{}{An improvised hand grenade made from a powerful nuclear projectile. When it explodes, it releases such an amount of energy that it can destroy a house. Min ST: 5.}
###------- ARMOR
{2400}{}{Jumpsuit}
{2401}{}{Cute skintight jumpsuit from a Vault. This item can be sold profitably on the market. Effects: +2 reaction.}
{2500}{}{Leather Jacket}
{2501}{}{A black, heavy, pre-war leather jacket.}
{2600}{}{Combat Leather Jacket}
{2601}{}{This heavily padded leather jacket is unusual in that it has two sleeves. You'll definitely make a fashion statement whenever, and wherever, you rumble.}
{2700}{}{Leather Armor}
{2701}{}{Your basic all leather apparel. Finely crafted from tanned brahmin hide. Only San Brahmin masters know the secrets of its production.}
{2800}{}{Robes}
{2801}{}{Follower of Fire Robes. Made using secret technology and special materials. Provides additional radiation protection.}
{2900}{}{Robes with Body Armor}
{2901}{}{Follower of Fire Robes. Made using secret technology and special materials with additional radiation protection. A lightweight police vest is discreetly hidden under the robe.}
{3000}{}{Metal Armor}
{3001}{}{Polished metal plates, crudely forming a suit of armor. Provides excellent protection from bullets and impacts, but is burdened by its heavy weight and unwieldy shape.}
{3100}{}{Tesla Armor}
{3101}{}{This shining armor provides superior protection against energy attacks. The three Tesla Attraction Coil Rods disperse a large percentage of directed energy attacks.}
{3200}{}{Combat Armor}
{3201}{}{High tech armor, made out of advanced defensive polymers.}
{3300}{}{Brotherhood Armor}
{3301}{}{A superior version of Combat Armor. The Brotherhood of Steel have made many improvements over the standard version.}
{3400}{}{T-51b Power Armor}
{3401}{}{A self-contained suit of advanced technology armor. This copy is partially damaged.}
{3500}{}{T-51b Power Armor}
{3501}{}{A self-contained suit of advanced technology armor. Powered by a micro-fusion reactor, with enough fuel to last a hundred years.}
{3600}{}{Road Armor}
{3601}{}{A pre-war leather jacket, tightly reinforced with road signs. Such jackets are often worn by highwaymen.}
{3700}{}{Ranger Duster}
{3701}{}{A type of armor expertly crafted from brahmin leather for the Rangers. Only San Brahmin masters know the secrets of its production.}
###------- DIFFERENT THINGS
{3800}{}{Fuel Cell Battery}
{3801}{}{A large energy storage unit. Common power source for small vehicles and some equipment.}
{3900}{}{!Do not use}
{3901}{}{Originally - Small Energy Cell.}
{4000}{}{Stimpak}
{4001}{}{A medicinal substance widely used in pre-war times. When injected, it provides rapid healing of small wounds. Effects: +(20-30) hit points.}
{4100}{}{Bottle caps}
{4101}{}{This bag contains your bottle caps. Recently, in large settlements, they have been used for exchanging goods.}
{4200}{}{Pre-war money}
{4201}{}{A means of payment that has long gone out of use. However, some residents of the Wasteland can still use it.}
{4300}{}{Casino Chips}
{4301}{}{These chips are used as local currency in casinos. If you didn't know this, you'd think they were a child's toy from the pre-war era.}
{4400}{}{Soldier's Dog Tag}
{4401}{}{This worn dog tag bears a soldier's name and identification number.}
{4500}{}{Pocket Trash}
{4501}{}{Useless trash from your pocket. If you find this, you're out of luck.}
{4600}{}{Token}
{4601}{}{This token is used as the owner wishes.}
{4700}{}{!Do not use}
{4701}{}{Original: First Aid Kit.}
{4800}{}{RadAway}
{4801}{}{A chemical solution that bonds with radiation particles and passes them through your system. Takes time to work. May be addictive. Effects: -(100-150) rad.}
{4900}{}{Antidote}
{4901}{}{Several ampoules from an army first aid kit containing various potent antitoxins. These drugs neutralize animal poison and its effects. A tourniquet is also included. Effects: -(45-60) poisoning.}
{5000}{}{Doctor's Bag}
{5001}{}{This brown bag contains instruments and drugs used by doctors in the application of their trade.}
{5100}{}{!Do not use}
{5101}{}{Original: Dynamite.}
{5200}{}{Geiger counter}
{5201}{}{A Wattz Electronics C-Radz model Geiger Counter. Detects the presence and strength of radiation fields.}
{5300}{}{Mentats}
{5301}{}{A pillbox of mind-altering drugs. Increases memory related functions, and speeds other mental processes. Highly addictive. Effects: +2 IN, +2 PE, +1 CH.}
{5400}{}{Stealth Boy}
{5401}{}{A RobCo Stealth Boy 3001 personal stealth device. Generates a modulating field that transmits the reflected light from one side of an object to the other. Effects: Sneak +20.}
{5500}{}{Walkie-Talkie}
{5501}{}{A working radio model 2043B from the excellent company Wattz Electronics. Reliable, durable, and camouflaged.}
{5600}{}{Iguana Trap}
{5601}{}{Homemade device for catching desert lizards.}
{5700}{}{Chestplate}
{5701}{}{A pair of metal caps that fit over the shoulders using old belts. In the absence of normal armor, even this can save lives. Or not.}
{5800}{}{Spikes}
{5801}{}{The spiked whip is the weapon of truly carnivorous plants.}
{5900}{}{Motion Sensor}
{5901}{}{A Wattz Electronics C-U model motion sensor. Detects the movement of biological material over a distance of meters using a tuned radar device. Having one in your inventory will also help you avoid outdoor encounters.}
###------- PROVISION
{6000}{}{Iguana-on-a-stick}
{6001}{}{A cooked iguana, roasted in its own skin. Effects: +2 hit points.}
{6100}{}{Mutfruit}
{6101}{}{Unusual fruit. No preservatives or dyes. Effects: +3 hit points.}
{6200}{}{Jerky}
{6201}{}{These dried and smoked pieces of meat remain edible and even somewhat nutritious for many, many, many years... Effects: +4 hit points.}
{6300}{}{Box Of Noodles}
{6301}{}{Box of pasta from a well-known pre-War brand. Oddly enough, still edible. Effects: +7 hit points.}
{6400}{}{Small Dusty Box Of Some Sort}
{6401}{}{A television dinner. You're not sure, but it's definitely not edible. You're not quite sure if it ever was. Effects: +10 hit points, +5 healing rate.}
{6500}{}{Larvae}
{6501}{}{Huge fly-like insect larvae bred inside a corpse. For a Wasteland dweller, this is a real protein feast. Effects: +2 hit points.}
{6600}{}{Brahmin Sausages}
{6601}{}{Prepared according to a special recipe. Besides the obvious brahmin tripe, they could contain... just about anything. Effects: +5 hit points, +5 reaction.}
{6700}{}{Rat Soup}
{6701}{}{A fine dish of sewer rat and unidentifiable additives. A bit of everything. Effects: +6 hit points.}
{6800}{}{IRP}
{6801}{}{Individual diet for a Brotherhood of Steel fighter. Other inhabitants of Sonora can only dream of such rations. Effects: +12 hit points, +10 healing rate.}
{6900}{}{Rotten Dish}
{6901}{}{A plate of long-rotten meat. There's hardly any use for this, but you can try. Effects: +(5-15) poisoning.}
{7000}{}{Fried Cockroach}
{7001}{}{Fire-roasted cockroach with a pinch of sea salt. Mmm, how crunchy! Effects: +2 hit points.}
{7100}{}{Chips}
{7101}{}{A box labeled "Frito Bandito." To your surprise, there were some old corn chips still inside. Effects: +5 hit points.}
{7200}{}{Rogue Scavenger Jacket}
{7201}{}{A thick pre-war leather jacket, reinforced for exploring the ruins of Dayglow. The homemade lining is made of foil and synthetic fabric to protect against radiation.}
###------- TOOLS
{7300}{}{!Reserve book}
{7301}{}{Do not use (Big Book of Science).}
{7400}{}{Lock Picks}
{7401}{}{A set of locksmith tools.  Includes all the necessary picks and tension wrenches to open conventional pin and tumbler locks.}
{7500}{}{Decoder}
{7501}{}{A high-powered hacking calculator designed for electronic systems. It has just enough charge left for one extended operation.}
{7600}{}{!Reserve book}
{7601}{}{Do not use (Electronics).}
{7700}{}{Gas Mask}
{7701}{}{An old, damaged civilian model gas mask. It may still serve you for a while.}
{7800}{}{Tinsmith's Goggles}
{7801}{}{Electronic goggles made by Two-Sun Tinsmiths. Equipped with a night vision device, interchangeable lenses and various sensors. The battery lasts for 10 minutes.}
{7900}{}{Flare}
{7901}{}{A flare.  Creates light for a short period of time.  The paper is a little worn, but otherwise it is in good condition. Turn the top to turn it on.}
{8000}{}{!Reserve book}
{8001}{}{Do not use (First Aid, First Aid Book).}
{8100}{}{Rubber Boots}
{8101}{}{An old pair of sturdy rubber work boots. They look durable enough to keep out sludge, at least for a while.}
{8200}{}{Shovel}
{8201}{}{This is a shovel for digging ditches and stuff.}
{8300}{}{Rope}
{8301}{}{A strong, thick line. About 45 feet in length.}
{8400}{}{Lighter}
{8401}{}{A silver butane lighter, in good condition.}
{8500}{}{Plastic Explosives}
{8501}{}{A chunk of Cordex, a military brand of plastic explosives. Highly stable, very destructive. Includes a timer, which is ticking.}
{8600}{}{!Reserve book}
{8601}{}{Do not use (Scout's Handbook).}
{8700}{}{Buffout}
{8701}{}{Highly advanced steroids. While in effect, they increase strength and reflexes. Very addictive. Effects: +2 ST, +2 AG, +3 EN.}
{8800}{}{Scrap Metal}
{8801}{}{Valuable parts from mechanical equipment. May be useful for repairs or for profitable exchange.}
{8900}{}{Electronics Parts}
{8901}{}{Various parts from electronic equipment: capacitors, vacuum tubes, inductors and much more. All this can be useful for repairs or for a profitable exchange.}
{9000}{}{Flammable Mixture}
{9001}{}{A bottle containing a blend of various flammable substances. A relatively valuable resource in post-nuclear conditions.}
{9100}{}{!Do not use}
{9101}{}{Original: Doctor's case.}
{9200}{}{Scorpion Tail}
{9201}{}{The severed tail of a radscorpion.}
{9300}{}{Trinitite}
{9301}{}{A mineral formed from sand at the epicenter of a nuclear explosion. An unremarkable object at first glance, but deadly due to its radioactivity.}
{9400}{}{Pre-war Book}
{9401}{}{One of the few surviving books from the pre-war era. Most will consider it a means to light a fire, and only a few will see it as a most valuable source of ancient knowledge.}
{9500}{}{Cornmeal}
{9501}{}{A staple of the modern diet. Contains some small foreign debris.}
{9600}{}{Cleaning Agent}
{9601}{}{Dry powder for removing dirt. It's even capable of washing away centuries old muck.}
{9700}{}{Wet Wipes}
{9701}{}{A sealed package of sanitary napkins. Replaces a bath while traveling through the Wasteland.}
{9800}{}{Wasteland Gum}
{9801}{}{Mature leaves of a rare wasteland plant. Valued by travelers for their high micronutrient content, these leaves are also sought after by city dwellers for their soothing, pleasurable effects.}
{9900}{}{Coffee}
{9901}{}{This jar contains some kind of "coffee beans". Apparently this is a barely surviving product of the Old World.}
{10000}{}{Tire Sandals}
{10001}{}{A pair of homemade sandals made from old tires. Better than nothing.}
{10100}{}{Ceramics}
{10101}{}{A simple vessel made of clay. Such things are valued in many settlements.}
{10200}{}{!Reserve book}
{10201}{}{Do not use (Weapons and Ammo).}
{10300}{}{Brahmin Herder's Battle Shield}
{10301}{}{Part of the local tribes' accoutrements. Includes a wooden shield and leather cape.}
{10400}{}{NMR Combat Armor}
{10401}{}{High tech pre-war armor with the insignia of the New Mexican Republic.}
{10500}{}{Hip Flask}
{10501}{}{This flask was a gift from the people of the Vault. It will make it easier for you to travel through the arid, barren desert.}
{10600}{}{Nuka-Cola}
{10601}{}{A bottle of Nuka-Cola, the flavored softdrink of the post-nuclear world. Warm and flat. Effects: +(3-5) hit points.}
{10700}{}{Irradiated Nuka Cola}
{10701}{}{A wonderful pre-war drink in a slightly dirty bottle. It has a wonderful taste and a very dubious glow in the dark. Effects: +(3-5) hit points, +3 rad.}
{10800}{}{Purified Water}
{10801}{}{This vessel contains life-giving drinking water, free from impurities and radiation. It should be used extremely sparingly, especially when traveling. Effects: +(7-10) hit points.}
{10900}{}{Rad-X}
{10901}{}{Anti-radiation drugs to be taken before exposure. No known side effects. Effects: +25 rad resistance.}
{11000}{}{Psycho}
{11001}{}{An unique delivery system filled with strange and unknown chemicals of probably military origin. It is supposed to increase the combat potential of a soldier. Possibly highly addictive. Effects: +3 AG, -3 IN, +25 damage resistance.}
{11100}{}{Rad-Ash}
{11101}{}{Toxic concentrated ash resulting from a nuclear explosion. Having thrown this rubbish in the face of the enemy, you can calmly watch as his eyes run down his cheeks into his mouth. Effects: -2 PE, -5 reaction, -3 AP.}
{11200}{}{Empty Hypodermic}
{11201}{}{This is an empty hypodermic. A rare and valuable item for modern medicine.}
{11300}{}{Knight's Dog Tag}
{11301}{}{This dog tag bears a name and identification number.}
{11400}{}{Squire's Dog Tag}
{11401}{}{This dog tag bears a name and identification number.}
{11500}{}{Mexican Power Armor}
{11501}{}{Autonomous armor upgraded for the needs of the Mexican Navy. Differs from the original model in reduced performance and lighter weight.}
{11600}{}{Acid Spit}
{11601}{}{A dose of strong acid.}
{11700}{}{Ghoul Combat Armor}
{11701}{}{Damaged Combat Armor. Some parts have been replaced with makeshift items.}
{11800}{}{Dixon's Machine Gun}
{11801}{}{A heavy machine gun designed to be fired from the side of a sea vessel. Min ST: 7.}
{11900}{}{Shock Spear}
{11901}{}{A homemade weapon that emits an electric current upon contact with the victim. Min ST: 3.}
###------- ALCOHOL
{12000}{}{Pre-War Beer}
{12001}{}{A can of pre-war beer. Locally produced. Effects: -1 PE.}
{12100}{}{Agave Syrup}
{12101}{}{Syrup obtained from the juice of the "fire agave". Despite the terrible stench and burning taste, it contains large amounts of fructose and sugar.}
{12200}{}{Swill}
{12201}{}{A diluted low-quality alcoholic drink. Its composition and origin can no longer be determined. Effects: -1 PE, -1 IN.}
{12300}{}{Pre-war Whiskey}
{12301}{}{Strong alcoholic drink of the Atomic Whiskey brand. It is highly valued in the modern world compared to other types of alcohol. Effects: -1 PE, +1 CH.}
{12400}{}{Homemade Beer}
{12401}{}{One of the few beers produced post-war. Effects: -1 PE.}
{12500}{}{Wasteland Tequila}
{12501}{}{Tequila alcoholic drink from Phoenix of very dubious quality. It looks like there's a little worm swimming in the bottle. Effects: -1 PE.}
###------- WEAPON
{12600}{}{Brass Knuckles}
{12601}{}{Hardened knuckle grip that is actually made out of steel. They protect your hand, and do more damage, in unarmed combat. Min ST: 1.}
{12700}{}{Spiked Knuckles}
{12701}{}{An improved version of the classic Brass Knuckles. The Spiked Knuckles do more damage, tearing into the flesh of your opponent in unarmed combat. Min ST: 1.}
{12800}{}{Claws}
{12801}{}{Improvised melee weapon. It consists of two old blades connected by bolts to a sleeve frame. Min ST: 1.}
{12900}{}{Pneumatic Fist}
{12901}{}{Homemade mechanical brass knuckles. During the strike, it projects sharp spikes forward with force, piercing the body of the victim. Min ST: 1.}
{13000}{}{Shock Glove}
{13001}{}{Modified police taser. Upon contact with the victim's body, this weapon transmits a powerful charge of electricity to him, and an old rubber glove protects the wearer from electric shock. Min ST: 1.}
{13100}{}{Power Fist}
{13101}{}{A "Big Frigger" Power Fist from BeatCo. Considered by many to be the ultimate weapon to use in unarmed combat. Others are just scared. Powered by micro fusion cells. Min ST: 1.}
{13200}{}{Knife}
{13201}{}{A sharp-bladed cutting and stabbing weapon. Min ST: 1.}
{13300}{}{Combat Knife}
{13301}{}{A high-quality combat knife, the Stallona is from SharpWit, Inc. The edge of this blade is guaranteed sharp for over a decade of use! Min ST: 1.}
{13400}{}{Punch Knife}
{13401}{}{A large knife with a double-edged blade. Still surprisingly spicy. Min ST: 1.}
{13500}{}{Ripper}
{13501}{}{A Ripper(tm) vibroblade. Powered by a micro fusion cell, the chainblade rips and tears into it's target. Min ST: 1.}
{13600}{}{Atomic Cutter}
{13601}{}{A working tool for cutting hard material. Breaks molecular bonds with powerful radiation. Powered by a battery on the belt. Min ST: 1.}
{13700}{}{Spear}
{13701}{}{A razor tipped polearm. The shaft is wooden, and the tip is worked steel. Min ST: 4.}
{13800}{}{Pneumatic Spear}
{13801}{}{A peculiar invention of local engineers. Upon impact, the pneumatic system projects a sharp metal spike at the victim, and then uses a spring to return it to its place. Min ST: 4.}
{13900}{}{Electric Spear}
{13901}{}{An effective police tool for dispersing crowds of troublemakers. Used many times before the Great War. Min ST: 4.}
{14000}{}{Club}
{14001}{}{A military or police baton. Heavy wood. Min ST: 3.}
{14100}{}{Crowbar}
{14101}{}{A very solid and heavy piece of metal, specially designed to exert leverage.  Or pound heads.  Min ST: 3.}
{14200}{}{Cattle Prod}
{14201}{}{An electro prod from Wattz Electronics. Model: "Farmer's Best Friend." Powered by micro fusion cells. Min ST: 3.}
{14300}{}{Reinforced Cattle Prod}
{14301}{}{An electric prod from Wattz Electronics, branded as the "Farmer's Best Friend." Enhanced with modifications, this model packs a much stronger punch. Min ST: 3.}
{14400}{}{Super Stimpak}
{14401}{}{An advanced healing chem. Very powerful. Superstims will cause a small amount of damage after a period of time due to powerful nature of the chemicals used. Effects: +75 hit points, -1 Strength.}
{14500}{}{Sledgehammer}
{14501}{}{A large hammer with big handle. Very popular with the muscular crowd. Min ST: 6.}
{14600}{}{Hammer}
{14601}{}{A balanced, lightweight hammer with increased maneuverability. Although they used to crush bricks, now they have a more practical use. Min ST: 5.}
{14700}{}{Super Sledge}
{14701}{}{A Super Sledgehammer, manufactured by the Brotherhood of Steel, using the finest weapons technology available. Includes a kinetic energy storage device, to increase knockback. Min ST: 5.}
{14800}{}{Old Revolver}
{14801}{}{Ancient civilian weapon. Like any revolver, it's valued for its simplicity and reliability. Min ST: 4.}
{14900}{}{Police Revolver}
{14901}{}{A reliable revolver from S&W, popular in its day among police officers and highway patrolmen. Min ST: 4.}
{15000}{}{Combat Revolver}
{15001}{}{Great revolver. The favorite weapon of collectors and pretentious types. Now it's yours. Min ST: 5.}
{15100}{}{Flare Pistol}
{15101}{}{A pistol for firing a flare. Although it can hardly be called a weapon, at the right moment it can put the enemy to flight (especially if you have skillfully modified rounds). Min ST: 3.}
{15200}{}{.22 Submachine Gun}
{15201}{}{Sporting weapon of a bygone era. Now its main purpose is to shoot iguanas and scare away hooligans. Min ST: 3.}
{15300}{}{10mm pistol}
{15301}{}{A Colt 6520 10mm autoloading pistol. Each pull of the trigger will automatically reload the firearm until the magazine is empty. Single shot only, using the powerful 10mm round. Min ST: 3.}
{15400}{}{10mm SMG}
{15401}{}{H&K MP9 Submachinegun (10mm variant). A medium-sized SMG, capable of single shot and burst mode. Min ST: 4.}
{15500}{}{Mexican SMG}
{15501}{}{HM-23 submachine gun developed by Mendoza CA. It was adopted by the Mexican police and performed well during border unrest before the Great War. Min ST: 4.}
{15600}{}{.50 Pistol}
{15601}{}{SIG-Sauer automatic pistol. Requires special handling skills due to the enormous force of the shot and high noise level. Min ST: 5.}
{15700}{}{Hunting Rifle}
{15701}{}{Colt Rangemaster semi-automatic rifle. Outdated but reliable. Min ST: 5.}
{15800}{}{Combat Rifle}
{15801}{}{American semi-automatic rifle of the AR series, formerly in service with the United States and Mexico. Convenient and reliable. Min ST: 5.}
{15900}{}{Molotov Cocktail}
{15901}{}{A home-made flammable grenade. Min ST: 4.}
{16000}{}{Sniper Rifle}
{16001}{}{DKS-501 rifle, converted to .308 caliber. An excellent long-range firearm. Min ST: 6.}
{16100}{}{Assault Rifle}
{16101}{}{An AK-112 5mm Assault Rifle. An old military model, out of use around the time of the war. Can fire single-shot or burst, using the high velocity 5mm rounds. Min ST: 5.}
{16200}{}{Light Machine Gun}
{16201}{}{Mendoza C-2075 machine gun, 5mm caliber model. After worsening relations with the United States, Mexico has resumed developing its own weapons, and this is one of them. Min ST: 6.}
{16300}{}{Minigun}
{16301}{}{A Rockwell CZ53 Personal Minigun. A multi-barrelled chaingun firing 5mm ammunition at over 60,000 RPM. Min ST: 8.}
{16400}{}{Shotgun}
{16401}{}{A Winchester Widowmaker double-barreled 12-gauge shotgun. Short barrel, with mahogany grip. Min ST: 6.}
{16500}{}{Combat Shotgun}
{16501}{}{A Winchester City-Killer 12-gauge combat shotgun, bullpup variant. In excellent condition, it has the optional DesertWarfare environmental sealant modification for extra reliability. Min ST: 6.}
{16600}{}{Assault Shotgun}
{16601}{}{Melee assault weapon. The bullpup design makes it small and easy to handle. Min ST: 6.}
{16700}{}{40mm Grenade Launcher}
{16701}{}{Hand grenade launcher for 40mm shells. Developed by Rockwell. Min ST: 6.}
{16800}{}{Laser Emitter}
{16801}{}{Homemade weapon crafted from industrial robot parts. Fires a low-power laser beam at close range. Min ST: 3.}
{16900}{}{Laser Pistol}
{16901}{}{A Wattz 1000 Laser Pistol. Civilian model, so the wattage is lower than military or police versions. Powered by a micro fusion cells. Min ST: 3.}
{17000}{}{Laser Rifle}
{17001}{}{A Wattz 2000 Laser Rifle. Uses micro fusion cells for more powerful lasers, and an extended barrel for additional range. Min ST: 4.}
{17100}{}{Plasma Pistol}
{17101}{}{Glock 86 Plasma Pistol. Designed by the Gaston Glock AI. Shoots a small bolt of superheated plasma. Powered by a micro fusion cell. Min ST: 3.}
{17200}{}{Plasma Rifle}
{17201}{}{A Winchester Model P94 Plasma Rifle. An industrial-grade energy weapon, firing superheated bolts of plasma down a superconducting barrel. Powered by micro fusion Cells. Min ST: 4.}
{17300}{}{Radiator Gun}
{17301}{}{A one-of-a-kind weapon utilizing ultra-high-frequency radiation. Certain components are scavenged from industrial machinery. Min ST: 4.}
{17400}{}{Koa}
{17401}{}{A professional tool for cutting and processing fire agave. Recently manufactured. Min ST: 4.}
{17500}{}{Scaremonger}
{17501}{}{Homemade pistol with a single-shot chamber. Surprisingly effective, unless it explodes in your hands. Min ST: 3.}
{17600}{}{Scoped Hunting Rifle}
{17601}{}{Nothing's better than seeing that surprised look on your target's face. The Loophole x10 Scope on this hunting rifle makes it easier than ever before. Accurate from first shot to last, no matter what kind of game you're gunning for. Min ST: 5.}
{17700}{}{.22 Submachine Gun}
{17701}{}{A sporting weapon from a bygone era. Now mainly used for hunting iguanas and deterring hooligans. This version is modified to hold an extended magazine. Min ST: 3.}
{17800}{}{40mm Grenade Launcher}
{17801}{}{Handheld grenade launcher for 40mm rounds. Upgraded with an extended magazine. Developed by Rockwell. Min ST: 6.}
{17900}{}{Winchester}
{17901}{}{Model 2073 Winchester rifle with a lever action and tubular magazine. One of the last models. Min ST: 5.}
{18000}{}{Mop}
{18001}{}{This is a rope mop. It just is. Min ST: 1.}
{18100}{}{.22 pistol}
{18101}{}{A simple, reliable small-caliber pistol. Developed by the Mexican company Armas Trejo. Min ST: 2.}
{18200}{}{Assault Rifle}
{18201}{}{An AK-112 5mm Assault Rifle. An old military model, out of use around the time of the war. Can fire single-shot or burst, using the high velocity 5mm rounds. Min ST: 6.}
{18300}{}{Rail Gun}
{18301}{}{This weapon uses electromagnetic power to launch metal projectiles. Min ST: 7.}
{18400}{}{Flamer}
{18401}{}{A Flambe 450 model flamethrower, varmiter variation. Fires a short spray of extremely hot, flamable liquid. Requires specialized fuel to work properly. Min ST: 6.}
{18500}{}{Flamethrower fuel}
{18501}{}{A cylinder containing an extremely flammable liquid fuel for flamethrowers.}
{18600}{}{Tejada Machine Gun}
{18601}{}{Inspecting this old weapon, you shout "Viva Tejada!" and rush into battle. Min ST: 6.}
{18700}{}{Blaster}
{18701}{}{This weapon looks like it's straight out of a vintage sci-fi flick. Fires a beam of particles accelerated to near-light speed. Min ST: 3.}
{18800}{}{Gatling laser}
{18801}{}{An H&K L30 Gatling Laser. Designed specifically for military use, these were in the prototype stage at the beginning of the War. Multiple barrels allow longer firing before overheating. Powered by micro fusion cells. Min ST: 7.}
{18900}{}{Turret Cannon}
{18901}{}{Twin plasma cannon for turret installation.}
{19000}{}{Battle Hatchet}
{19001}{}{An old camping hatchet. Suitable for combat. Min ST: 3.}
{19100}{}{Turbo Plasma Rifle}
{19101}{}{A modified Winchester P94 plasma rifle. The plasma bolt chamber has been hotwired to accelerate the bolt formation process. Min ST: 4.}
###------- CONTAINERS
{19200}{}{Ammo Box}
{19201}{}{Shockproof metal ammo box.}
{19300}{}{Tradebox}
{19301}{}{Typically used by merchants for storing their goods.}
{19400}{}{Iguana Trap}
{19401}{}{Homemade device for trapping desert lizards.}
{19500}{}{Dog Grave}
{19501}{}{This ground was hastily dug. Bones and bits of fur poke through the dirt.}
{19600}{}{Freshly Dug Earth}
{19601}{}{This ground was recently disturbed. Could be a treasure or a corpse buried here.}
{19700}{}{Trash Pile}
{19701}{}{A small heap of various trash.}
{19800}{}{Receiving Crates}
{19801}{}{Packages from other cities are stored here.}
{19900}{}{Sending Crates}
{19901}{}{Packages destined for other cities are stored here.}
{20000}{}{Packages to Flagstaff}
{20001}{}{A box of items bound for another city.}
{20100}{}{Packages to Phoenix}
{20101}{}{A box of items bound for another city.}
{20200}{}{Packages to Two-Sun}
{20201}{}{A box of items bound for another city.}
{20300}{}{Freshly Dug Earth}
{20301}{}{This ground was recently disturbed. Could be a treasure or a corpse buried here.}
{20400}{}{Boarded-up Box}
{20401}{}{A wooden box. To look inside, you'll need to pry apart the boards.}
{20500}{}{Flare}
{20501}{}{A flare. Creates light for a short period of time. The paper is a little worn, but otherwise it is in good condition.}
{20600}{}{!Do not use}
{20601}{}{Original: Dynamite.}
{20700}{}{Geiger Counter}
{20701}{}{A Wattz Electronics C-Radz model Geiger Counter. Detects the presence and strength of radiation fields.}
{20800}{}{Motion Sensor}
{20801}{}{A Wattz Electronics C-U model motion sensor. Detects the movement of biological material over a distance of meters using a tuned radar device.}
{20900}{}{Plastic Explosives}
{20901}{}{A chunk of Cordex, a military brand of plastic explosives. Highly stable, very destructive. Includes a timer, which is ticking.}
{21000}{}{Stealth Boy}
{21001}{}{A RobCo Stealth Boy 3001 personal stealth device. Generates a modulating field that transmits the reflected light from one side of an object to the other.}
{21100}{}{Grave}
{21101}{}{}
{21200}{}{Grave}
{21201}{}{}
{21300}{}{Grave}
{21301}{}{}
{21400}{}{Grave}
{21401}{}{}
{21500}{}{Grave}
{21501}{}{}
{21600}{}{Grave}
{21601}{}{}
{21700}{}{Grave}
{21701}{}{}
{21800}{}{Bones}
{21801}{}{Several human bones.}
{21900}{}{Wagon}
{21901}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{22000}{}{Wagon}
{22001}{}{A caravan wagon converted from the wrecked remains of an ancient automobile.}
{22100}{}{Jug}
{22101}{}{Large jar for storing crops or water.}
{22200}{}{Pot}
{22201}{}{A finely crafted clay pot.}
{22300}{}{Pot}
{22301}{}{A finely crafted clay pot.}
{22400}{}{Box}
{22401}{}{A wooden box filled with various items.}
{22500}{}{Stuff}
{22501}{}{These are miscellaneous items, also known as "stuff".}
{22600}{}{Stuff}
{22601}{}{These are miscellaneous items, also known as "stuff".}
{22700}{}{Stuff}
{22701}{}{These are miscellaneous items, also known as "stuff".}
{22800}{}{Stuff}
{22801}{}{These are miscellaneous items, also known as "stuff".}
{22900}{}{Safe}
{22901}{}{A small safe bolted to a metal table.}
{23000}{}{Chest}
{23001}{}{A wooden chest.}
{23100}{}{Chest}
{23101}{}{A wooden chest.}
{23200}{}{Shelves}
{23201}{}{A set of wooden shelves.}
{23300}{}{Shelves}
{23301}{}{A set of wooden shelves.}
{23400}{}{Shelves}
{23401}{}{Large wooden shelf with dusty items.}
{23500}{}{Shelves}
{23501}{}{Large wooden shelf with dusty items.}
{23600}{}{Shelves}
{23601}{}{Large wooden shelf with dusty items.}
{23700}{}{Shelves}
{23701}{}{Large wooden shelf with dusty items.}
{23800}{}{Shelves}
{23801}{}{Large wooden shelf with dusty items.}
{23900}{}{Shelves}
{23901}{}{Large wooden shelf with dusty items.}
{24000}{}{Trash Can}
{24001}{}{A trash can. You can barely read the label: Keep your city streets clean!}
{24100}{}{Fridge}
{24101}{}{A refrigerator. Out of coolant.}
{24200}{}{Ice Chest}
{24201}{}{An old-style ice chest. The hinges are in good working condition.}
{24300}{}{Ice Chest}
{24301}{}{An old-style ice chest. The hinges are in good working condition.}
{24400}{}{Table}
{24401}{}{A wooden table with multiple drawers.}
{24500}{}{Table}
{24501}{}{A wooden table with multiple drawers.}
{24600}{}{Table}
{24601}{}{A wooden table with multiple drawers. Working here is risky.}
{24700}{}{Table}
{24701}{}{Coffee table with tempting leftovers.}
{24800}{}{Wall Safe}
{24801}{}{A sturdy wall safe.}
{24900}{}{Safe}
{24901}{}{Very durable stationary safe.}
{25000}{}{Crates}
{25001}{}{Several sturdy shipping crates.}
{25100}{}{Crates}
{25101}{}{Secure and reliable shipping crates.}
{25200}{}{Crate}
{25201}{}{A highly durable shipping case.}
{25300}{}{Crate}
{25301}{}{A highly durable shipping case.}
{25400}{}{Crate of Bottles}
{25401}{}{Wooden box specifically designed for storing bottles.}
{25500}{}{Chest of Drawers}
{25501}{}{An ordinary chest of drawers, with a faint odor of someone else's laundry.}
{25600}{}{Chest of Drawers}
{25601}{}{An ordinary chest of drawers, with a faint odor of someone else's laundry.}
{25700}{}{Chest of Drawers}
{25701}{}{An ordinary chest of drawers, with a faint odor of someone else's laundry.}
{25800}{}{Chest of Drawers}
{25801}{}{An ordinary chest of drawers, with a faint odor of someone else's laundry.}
{25900}{}{!Do not use}
{25901}{}{Originally: Vint.}
{26000}{}{!Do not use}
{26001}{}{Originally: Antidote for the screw.}
{26100}{}{Shelves}
{26101}{}{Wooden shelves in excellent condition.}
{26200}{}{Shelves}
{26201}{}{Wooden shelves in poor condition.}
{26300}{}{Shelves}
{26301}{}{Wooden shelves, or rather, what's left of them.}
{26400}{}{Shelves}
{26401}{}{Wooden shelves in excellent condition.}
{26500}{}{Shelves}
{26501}{}{Wooden shelves in poor condition.}
{26600}{}{Shelves}
{26601}{}{Wooden shelves, or rather, what's left of them.}
{26700}{}{Sink}
{26701}{}{A porcelain sink that long ago ceased to function.}
{26800}{}{Sink}
{26801}{}{A porcelain sink that long ago ceased to function.}
{26900}{}{Workbench}
{26901}{}{Well, this is a standard, old, completely ordinary workbench.}
{27000}{}{Tool Rack}
{27001}{}{This rack is covered with various tools.}
{27100}{}{Fridge}
{27101}{}{A refrigerator with wheels for easy transport.}
{27200}{}{Table}
{27201}{}{A generic table. If you've seen one, you've seen them all.}
{27300}{}{Table}
{27301}{}{A generic table. Holds stuff off the ground.}
{27400}{}{Table}
{27401}{}{A generic table. Holds stuff off the ground.}
{27500}{}{Table}
{27501}{}{A generic table. Holds stuff off the ground.}
{27600}{}{Table}
{27601}{}{A generic table. Holds stuff off the ground.}
{27700}{}{Table}
{27701}{}{A generic table. Holds stuff off the ground.}
{27800}{}{Table}
{27801}{}{A generic table. Holds stuff off the ground.}
{27900}{}{Locker}
{27901}{}{A metal storage box built into the wall.}
{28000}{}{Locker}
{28001}{}{A metal storage box built into the wall.}
{28100}{}{Locker}
{28101}{}{A metal storage box built into the wall.}
{28200}{}{Locker}
{28201}{}{A metal storage box built into the wall.}
{28300}{}{Footlocker}
{28301}{}{Your basic footlocker. Holds stuff, sits at foot of bed, can be locked.}
{28400}{}{Footlocker}
{28401}{}{Your basic footlocker. Holds stuff, sits at foot of bed, can be locked.}
{28500}{}{Footlocker}
{28501}{}{Your basic footlocker. Holds stuff, sits at foot of bed, can be locked.}
{28600}{}{Footlocker}
{28601}{}{Your basic footlocker. Holds stuff, sits at foot of bed, can be locked.}
{28700}{}{Footlocker}
{28701}{}{Your basic footlocker. Holds stuff, sits at foot of bed, can be locked.}
{28800}{}{Footlocker}
{28801}{}{Your basic footlocker. Holds stuff, sits at foot of bed, can be locked.}
{28900}{}{Locker}
{28901}{}{A locker.}
{29000}{}{Locker}
{29001}{}{A locker.}
{29100}{}{Locker}
{29101}{}{A locker.}
{29200}{}{Locker}
{29201}{}{A locker.}
{29300}{}{Locker}
{29301}{}{A locker.}
{29400}{}{Locker}
{29401}{}{A locker.}
{29500}{}{Stuff}
{29501}{}{These are miscellaneous items, also known as "stuff".}
{29600}{}{Stuff}
{29601}{}{These are miscellaneous items, also known as "stuff".}
{29700}{}{Stuff}
{29701}{}{These are miscellaneous items, also known as "stuff".}
{29800}{}{Stuff}
{29801}{}{These are miscellaneous items, also known as "stuff".}
{29900}{}{Box}
{29901}{}{Army box for storing and transporting weapons.}
{30000}{}{Box}
{30001}{}{Army box for storing and transporting weapons.}
{30100}{}{Box}
{30101}{}{Army box for storing and transporting ammunition.}
{30200}{}{Box}
{30201}{}{Army box for storing and transporting ammunition.}
{30300}{}{Crates}
{30301}{}{Several sturdy shipping crates.}
{30400}{}{Crates}
{30401}{}{Several sturdy shipping crates.}
{30500}{}{Crate}
{30501}{}{A highly durable shipping case.}
{30600}{}{Crate}
{30601}{}{A highly durable shipping case.}
{30700}{}{Locker}
{30701}{}{A locker.}
{30800}{}{Locker}
{30801}{}{A locker.}
{30900}{}{Locker}
{30901}{}{A locker.}
{31000}{}{Locker}
{31001}{}{A locker.}
{31100}{}{Container}
{31101}{}{Army transport container with radiation shielding.}
{31200}{}{Container}
{31201}{}{Army transport container with radiation shielding.}
{31300}{}{Still}
{31301}{}{Looks like a wood-burning alcohol still.}
{31400}{}{Backpack}
{31401}{}{Someone left this backpack full of their stuff here.}
{31500}{}{Nuka-Cola Machine}
{31501}{}{The advertising on the side of this machine promotes their popular soda.}
{31600}{}{Prisoner's Corpse}
{31601}{}{The frozen corpse of an escaped prisoner.}
{31700}{}{Pot of Waste}
{31701}{}{I don't really want to dig into this pile of nasty stuff.}
{31800}{}{Destroyed Totem}
{31801}{}{A pile of trash that once served the Jackals as a totem.}
{31900}{}{Mercenary Body}
{31901}{}{The frozen corpse of one of the expedition's guards. He died from loss of blood.}
{32000}{}{Overseer's Post}
{32001}{}{This is the overseer's post. It hasn't been used for a long time.}
{32100}{}{Metal Shelves}
{32101}{}{Antique armored shelves. Very reliable.}
{32200}{}{Tank with Bio-waste}
{32201}{}{The remains of human bodies after operations were disposed of in this tank. Apparently, the surgeon had a lot of work.}
{32300}{}{Sergeant's Remains}
{32301}{}{The bone-shrunken corpse of a sergeant. Apparently, he was killed by security robots.}
{32400}{}{Newspaper machine}
{32401}{}{This newspaper machine is probably empty... or not.}
{32500}{}{Raider's Stuff}
{32501}{}{Luckily for you, the raiders left these items behind.}
{32600}{}{Mycelium}
{32601}{}{These glow-in-the-dark mushrooms grow right in the middle of a toxic puddle.}
{32700}{}{Donation Box}
{32701}{}{This box is used to collect donations.}
{32800}{}{Table}
{32801}{}{An elegant antique table for those with high standards. Luxurious chair included.}
{32900}{}{Fire Locker}
{32901}{}{For some reason, this locker is called a "fire locker". Nobody remembers where this name came from.}
{33000}{}{Fire Locker}
{33001}{}{For some reason, this locker is called a "fire locker". Nobody remembers where this name came from.}
{33100}{}{Book of Bemis}
{33101}{}{One of the best books of the pre-war era. Contains a lot of exclusive information from its time.}
{33200}{}{Pool Table}
{33201}{}{This is an old pool table. No self-respecting billiard connoisseur would play here.}
{33300}{}{Butchering Table}
{33301}{}{This table is used for cutting meat. Human flesh.}
{33400}{}{Ventilation Block}
{33401}{}{An old ventilation system, clogged with years of dust and neglect.}
{33500}{}{Totem}
{33501}{}{A creepy totem collected by the Reavers from various pieces of trash.}
{33600}{}{Cashier}
{33601}{}{This is the cash desk, and there is a cash register on it.}
{33700}{}{Mutant Body}
{33701}{}{The body of a malformed mutant.}
{33800}{}{Totem}
{33801}{}{A creepy totem constructed by the Reavers from various pieces of trash.}
{33900}{}{Totem}
{33901}{}{A creepy totem constructed by the Reavers from various pieces of trash.}
{34000}{}{Totem}
{34001}{}{A creepy totem constructed by the Reavers from various pieces of trash.}
{34100}{}{Totem}
{34101}{}{A creepy totem constructed by the Reavers from various pieces of trash.}
{34200}{}{Scarecrow}
{34201}{}{A comically absurd sentinel against pests, cobbled together from pre-war scraps and tattered rags.}
{34300}{}{Marauder's Body}
{34301}{}{The torn body of a young man. Apparently, he fell into the clutches of the local wildlife.}
{34400}{}{Sarcophagus}
{34401}{}{Here lies the body of your ancestor.}
{34500}{}{Ice Pile}
{34501}{}{Various things are frozen in this pile of ice.}
{34600}{}{Locker}
{34601}{}{A locker.}
{34700}{}{Ed's Bones}
{34701}{}{You see Ed's bones. There are remnants of overalls with the number 13 on them.}
{34800}{}{Mentats Vending Machine}
{34801}{}{According to the advertisement, this machine dispenses Mentats.}
{34900}{}{Robot Remains}
{34901}{}{This robot has been sucked into a toxic quagmire. What a terrible death!}
###------- HOLODICKS
{35000}{}{Founder's Notes}
{35001}{}{A battered and ancient holodisk with notes from the Founder of the Villa. Looks like it can be inserted into your Pip-Boy.}
{35100}{}{Vault Diary}
{35101}{}{A holotape containing the diary of an inhabitant of Vault 27.}
{35200}{}{Expedition Report}
{35201}{}{An earth-stained holotape, inscribed with reports from a Vault 27 expedition.}
{35300}{}{Mission to Quartz}
{35301}{}{An old holodisk, devoid of any inscriptions or notes.}
{35400}{}{McBain's Entry}
{35401}{}{A death audio recording of Sergeant McBain.}
{35500}{}{Mayor's Holodisk}
{35501}{}{A holodisk with instructions for the mayor of Casa Grande. The originator remains prudently unidentified.}
{35600}{}{George Crook' Notes}
{35601}{}{A holotape containing field notes compiled by the missionary commander to San Brahmin.}
{35700}{}{Letter from Vault-Tec}
{35701}{}{A holotape containing an official letter from Vault-Tec.}
{35800}{}{Letter to Shore}
{35801}{}{A holotape of a letter from the Petro-Chico oil platform.}
{35900}{}{Luther's Journal}
{35901}{}{The overseer's journal from Vault 24.}
{36000}{}{Holiday Fireworks}
{36001}{}{A large box of Mexican-made pyrotechnics.}
{36100}{}{Ceremonial Crown}
{36101}{}{A crown made from wires and light bulbs. It would look bizarre on someone's head.}
{36200}{}{Brahmin}
{36201}{}{You are bidding for this brahmin.}
{36300}{}{Magnetic Key}
{36301}{}{A magnetic key that opens doors to the Super Mutant Mobile Fortress.}
{36400}{}{Radio}
{36401}{}{An ancient but still functional radio from Wattz Electronics.}
{36500}{}{Brandley's Personal Effects}
{36501}{}{Anne Brandley's notebook and other belongings.}
{36600}{}{Lost Package}
{36601}{}{A courier was carrying this package, filled with many documents and letters destined for Phoenix. It includes a note: "If lost, please return to the Sonora Express office for a reward."}
{36700}{}{Madre's Pendant}
{36701}{}{A family heirloom pendant passed down through the female side of your family.}
{36800}{}{Green Substance}
{36801}{}{A chemical of unknown purpose from the Followers' lab.}
{36900}{}{Purple Substance}
{36901}{}{Another enigmatic chemical from the Followers' lab.}
{37000}{}{Red Substance}
{37001}{}{Yet another mysterious chemical from the Followers' lab.}
{37100}{}{Library Holodisk}
{37101}{}{This holodisk was given to you by a teacher in Casa Nueva to record Brotherhood of Steel e-books.}
{37200}{}{White Substance}
{37201}{}{An odorless crystalline substance of unknown composition.}
{37300}{}{Lab Notes}
{37301}{}{This holotape contains the latest reports from the Greenway Hydroponics laboratory.}
{37400}{}{Insecticide}
{37401}{}{A jerrycan with a mixture of toxic substances.}
{37500}{}{Raider Map}
{37501}{}{A map detailing locations under raider control, including their main base in the eastern mountains.}
{37600}{}{Valuable Relic}
{37601}{}{An ancient technological device with an unknown purpose, featuring a dial and toggle switches.}
{37700}{}{Mutagen}
{37701}{}{A mutagen sprayer operated by a primitive spring mechanism.}
{37800}{}{Chemistry Set}
{37801}{}{A large collection of chemical tools and substances.}
{37900}{}{Power Armor Helmet}
{37901}{}{You see a T-51b Power Armor helmet.}
{38000}{}{Power Armor Processor}
{38001}{}{This is a processor unit for T-51b Power Armor.}
{38100}{}{Box with Caps}
{38101}{}{A box filled to the brim with prized Nuka-Cola caps-a fortune for the average citizen.}
{38200}{}{Wooden Figurine}
{38201}{}{A figurine of a long-extinct animal, roughly carved from real wood.}
{38300}{}{!Do Not Use}
{38301}{}{Original: Shiloh.}
{38400}{}{Lost Pistol}
{38401}{}{The missing pistol from the Ranger warehouse.}
{38500}{}{Bemis Glasses}
{38501}{}{These are Henry Bemis' reading glasses. They are enormous.}
{38600}{}{Neurochip}
{38601}{}{An implant removed from the body of a deceased Tinsmith.}
{38700}{}{Ranger Badge}
{38701}{}{A badge that ended up in the wrong hands.}
{38800}{}{Suspicious Package}
{38801}{}{A package full of raw chemical materials meant for a pusher in Phoenix.}
{38900}{}{Suspicious Package}
{38901}{}{A bag of chemicals for the Blue Shields.}
{39000}{}{!Do Not Use}
{39001}{}{Original: Sun Scorcher.}
{39100}{}{Faber's Passwords}
{39101}{}{Several passwords are written here. They might be useful in the Flagstaff colony.}
{39200}{}{Eugene's Contract}
{39201}{}{A contract between the Rangers and Eugene Simon for his enlistment.}
{39300}{}{Hiram's Letter}
{39301}{}{A letter of recommendation for you from Preacher Hiram in Flagstaff, directed to Aaron, Lord of Phoenix, and the Church of the Holy Fire.}
{39400}{}{Advisor's Report}
{39401}{}{This holodisk was handed to you by Ulysses Grant. It should be delivered to the military base in Puerto Penasco.}
{39500}{}{Stolen Letters}
{39501}{}{Various letters for recipients in Phoenix.}
{39600}{}{Ben's Head}
{39601}{}{The severed head of the leader of the Blue Shields.}
{39700}{}{Hernando's Head}
{39701}{}{The severed head of a boss of Los Panchos.}
{39800}{}{Chucho's Head}
{39801}{}{Another severed head of a Los Panchos boss.}
{39900}{}{Adie's Head}
{39901}{}{The head of yet another Los Panchos boss.}
{40000}{}{Gil McCord's Head}
{40001}{}{The severed head of a legendary marksman from the Mercenary Guild.}
{40100}{}{Spear Fragment}
{40101}{}{A fragment of a spear taken from the shell of a giant radscorpion.}
{40200}{}{Glowing Mushroom}
{40201}{}{An unusual fungus that forms in toxic puddles, inedible for humans.}
{40300}{}{High-Tech Gadget}
{40301}{}{The Scavenger Cartel would certainly be interested in this piece of ancient technology.}
{40400}{}{Winch Handle}
{40401}{}{A rusty but still usable handle. They don't make 'em like they used to.}
{40500}{}{Signal Booster}
{40501}{}{An electrical vibration power amplifier for a radio transmitter, using the latest generation of advanced electronic vacuum tube technology.}
{40600}{}{Welding Machine}
{40601}{}{A very old but still functional welding machine.}
{40700}{}{ZAX Update}
{40701}{}{An update for one of the ZAX 1.1 routines.}
{40800}{}{!Do Not Use}
{40801}{}{Original: First aid kit for a military paramedic.}
{40900}{}{!Do Not Use}
{40901}{}{Original: Paramedic Bag.}
{41000}{}{Generator Fusion Cell}
{41001}{}{A very large energy storage unit. This nuclear fusion cell is designed to power Wattz Electronics generators.}
{41100}{}{Fuses}
{41101}{}{Nuclear bomb fuses. Without them, it's impossible to activate the detonator.}
{41200}{}{Hold Access Card}
{41201}{}{An access card to some rooms on the Brotherhood of Steel destroyer.}
{41300}{}{Torpedo Key}
{41301}{}{An access card to the torpedo bay control terminal.}
{41400}{}{Luxury Key}
{41401}{}{The Atomic Rush Casino Suite Key.}
{41500}{}{Cathedral Radio Codes}
{41501}{}{The access codes for the radio station in the Cathedral.}
{41600}{}{Access Card}
{41601}{}{An electronic access card for the dam control panel.}
{41700}{}{ZAX Access Card}
{41701}{}{A high-level electronic access card for a ZAX emergency terminal.}
{41800}{}{Access Card}
{41801}{}{An electronic access card from Vault 25, with limited access.}
{41900}{}{Access Card}
{41901}{}{An electronic access card from Vault 25, with the highest clearance.}
{42000}{}{Access Card}
{42001}{}{An electronic access card from Vault 27.}
{42100}{}{Aaron's Key}
{42101}{}{A key that once belonged to Aaron, Lord of Phoenix, seemingly for a special lock.}
{42200}{}{Worn Key}
{42201}{}{A worn-out Old Motel room key.}
{42300}{}{Jackal Storeroom Keys}
{42301}{}{A set of dirty keys that open doors in the Jackal tribe's dens.}
{42400}{}{Irradiated Key}
{42401}{}{A small key found in Quartz, likely for a small lock.}
{42500}{}{Rusty Key}
{42501}{}{A key that opens the inventory warehouse in the Flagstaff Uranium Mine.}
{42600}{}{Teeth of the Rat King}
{42601}{}{The lower incisors of a massive mutant rat from the Flagstaff mine, proof of the monster's death.}
{42700}{}{Barn Key}
{42701}{}{A key that opens the barn door at the Corn Plantations.}
{42800}{}{Family Heirlooms}
{42801}{}{A blue jumpsuit, wrist computer, and hip flask. Passed down through your family for generations, and now yours.}
{42900}{}{Monster Skull}
{42901}{}{A monster's head, terrifying even in death.}
{43000}{}{Motorcycle Key}
{43001}{}{An access key to the motorcycle's onboard computer. Without it, hacking the security system to start the bike is tough.}
{43100}{}{Necklace}
{43101}{}{A neck ornament with several still-effective bullets tied together with old rope. The previous owner didn't grasp their true meaning.}
{43200}{}{Halogen Lamp}
{43201}{}{A surprisingly well-preserved 65-watt lamp, once used in car headlights.}
{43300}{}{Stylish Sunglasses}
{43301}{}{A very stylish pair of mirrored sunglasses. Just having them boosts your confidence. Effects: +1 CH while equipped.}
{43400}{}{Ancient Relic}
{43401}{}{A music box mechanism. Wind the lever to hear a long-forgotten melody.}
{43500}{}{Ancient Relic}
{43501}{}{An antique atomic clock, five minutes slow but still ticking.}
{43600}{}{Ancient Relic}
{43601}{}{A sealed glass ball with white grains of sand inside. It might be what the snow you heard about as a child looks like.}
{43700}{}{Ancient Relic}
{43701}{}{A Medal for Valor at the Battle of Anchorage, 2077-a significant event.}
{43800}{}{Ancient Relic}
{43801}{}{An authentic law enforcement badge, marked with signs of great age.}
{43900}{}{Ancient Relic}
{43901}{}{A sacred book from the Divine Brahmin Shrine, its meaning likely unknown to the tribe.}
{44000}{}{Ancient Relic}
{44001}{}{A photo of a mushroom cloud over smoking ruins. The back reads: Mexicali, 2077.}
{44100}{}{Ancient Relic}
{44101}{}{A hip flask for storing water or some other liquid. It is marked with a large number '24'.}
{44200}{}{Ancient Relic}
{44201}{}{A dusty but well-preserved Arizona flag.}
{44300}{}{Ancient Relic}
{44301}{}{Holodisk with a game for very fast computers.}
{44400}{}{Phoenix Map}
{44401}{}{A marked map of the city and its surroundings. A valuable find for the novice scavenger.}
{44500}{}{Fisherman Tag}
{44501}{}{This tag is engraved with the name of the fisherman Ferrino.}
{44600}{}{Access Card}
{44601}{}{Electronic access card for the doors on the Petro-Chico oil rig.}
{44700}{}{Map Fragment}
{44701}{}{One of the pieces of some kind of handwritten map.}
{44800}{}{Guitar Strings}
{44801}{}{Strings for a five-string guitar.}
{44900}{}{Copper Pipe}
{44901}{}{An ancient musical instrument.}
{45000}{}{Donovan's Body}
{45001}{}{This is Donovan's body. Donovan is dead.}
{45100}{}{Ancient Badge}
{45101}{}{This is a border patrol badge. It's covered in an obscenely thick layer of ash and dirt.}
{45200}{}{Ancient Badge}
{45201}{}{This is a border patrol badge. It proudly shines in the sun, as it once did in the Old World.}
{45300}{}{Wattz 3000 crystal}
{45301}{}{A high-precision artificial crystal for a military-grade laser pistol.}
{45400}{}{Laser Pistol}
{45401}{}{A Wattz 1000 Laser Pistol, upgraded civilian model. The power is increased to the level of military models thanks to the high-precision crystal. Min ST: 3.}
{45500}{}{Trunk}
{45501}{}{An old box strapped to the frame of the motorcycle. Suitable for storing and transporting small items.}
{45600}{}{Bike Bags}
{45601}{}{Strong leather bags. Custom made for your motorcycle.}
{45700}{}{Bonita Access Card}
{45701}{}{Access card for the Bonita power plant. Access level - restricted.}
{45800}{}{Bonita Access Card}
{45801}{}{Access card for the Bonita power plant. Access level - highest.}
{45900}{}{Coffee Table}
{45901}{}{This table is cluttered with various junk.}
{46000}{}{Pulse Generator}
{46001}{}{A working tool designed for emergency disabling electrical equipment.}
{46100}{}{Tablet with Notes}
{46101}{}{A work tablet with notes by old Isaac. Here, he describes the steps to restore the Bonita dam.}
{46200}{}{Gustavo's Holodisk}
{46201}{}{Senor Gustavo asked to secretly deliver this holodisk to the mayor in Old Town.}
{46300}{}{Vacuum Tube}
{46301}{}{A high-power electronic vacuum tube. Most of these tubes have long since burnt out, but this one still works, making it quite rare, and expensive.}
{46400}{}{Dispatcher Module}
{46401}{}{This module is needed for the proper operation of the monorail line. However, it is not working and requires repair.}
{46500}{}{Dispatcher Module}
{46501}{}{This module is needed for the proper operation of the monorail line. It should be returned to its place.}
{46600}{}{Border Service Codes}
{46601}{}{This contains codes and commands for remote control of border robots in the San Ysidro area via radio.}
{46700}{}{!Do not use}
{46701}{}{Originally - Jesse's Container. Used by the engine in the barter system.}
{46800}{}{Holographic Emitter}
{46801}{}{A part for generating holographic images.}
{46900}{}{Water Chip}
{46901}{}{A control chip for the water purification computer system. Used in Vault-Tec vaults.}
{47000}{}{Circuit Board}
{47001}{}{A critical part from a printing press.}
{47100}{}{Diagnostic Board}
{47101}{}{A part from an autodoc, providing quick and accurate medical data analysis.}
{47200}{}{Fuel Controller}
{47201}{}{This chip manages power distribution in a car's electric engine. Such chips fail quickly, making them hard to find.}
{47300}{}{Vertibird Schematics}
{47301}{}{These are schematics for some military equipment. The sheets are marked: "Experimental model."}
{47400}{}{Battery Vending Machine}
{47401}{}{A vending machine for selling nuclear batteries. The selection is limited.}
{47500}{}{Data from Hermosillo}
{47501}{}{Espionage data collected by you at the Mexican army fort. Some people in the wasteland are willing to pay well for it.}
{47600}{}{Book about San Diego}
{47601}{}{A memoir book about San Diego, published just before the Great War. You can be one of its first readers.}
{47700}{}{Medicine Vending Machine}
{47701}{}{A vending machine for selling medicines and medical supplies. The selection is limited.}
{47800}{}{Bar Vending Machine}
{47801}{}{A vending machine for selling various drinks. The selection is limited.}
{47900}{}{Machine Oil Dispenser}
{47901}{}{A vending machine for selling machine oil. There is very little oil left.}
{48000}{}{Biogel}
{48001}{}{A hermetically sealed unbreakable glass jar. The label reads: "Medical Biogel."}
{48100}{}{Microchips}
{48101}{}{Microchips from aviation equipment. For most people, this is useless junk, but for some, it's a valuable find.}
{48200}{}{Coronado Security Codes}
{48201}{}{Security codes for the Coronado naval base. Used via radio communication. Extremely important in the current situation.}
{48300}{}{Reinforced Shock Spear}
{48301}{}{A homemade weapon that emits an electric current upon contact with a victim. Min ST: 3.}
{48400}{}{Taser}
{48401}{}{A police taser. It shocks the target with electricity. Min ST: 4.}
{48500}{}{Hotel Manager Program}
{48501}{}{The disk contains a software module for Mister Handy. With it, the robot will perform hotel manager functions.}
{48600}{}{"Deep Throat"}
{48601}{}{A pornographic film that has become a cult classic. You certainly won't watch it.}
{48700}{}{Food Processor}
{48701}{}{This is a part for a food processor. It comes with a note: "Private property. If lost, please return to Edward in San Ysidro."}
{48800}{}{Howitzer Shell}
{48801}{}{A 75mm howitzer shell. Although the casing is heavily rusted, it still contains gunpowder. Thus, in theory, this shell can be fired.}
{48900}{}{Howitzer Parts}
{48901}{}{These parts can be used to repair one of the damaged howitzers.}
{49000}{}{Coronado Pass}
{49001}{}{Military pass for the Coronado Naval Base. Color: blue.}
{49100}{}{Coronado Pass}
{49101}{}{Military pass for the Coronado Naval Base. Color: red.}
{49200}{}{}
{49201}{}{}
{49300}{}{}
{49301}{}{}
{49400}{}{}
{49401}{}{}
{49500}{}{}
{49501}{}{}
{49600}{}{}
{49601}{}{}
{49700}{}{12 Gauge Flare Gun}
{49701}{}{A pistol originally designed to shoot flares. You've modified its barrel to fire shotgun shells. Shooting has become heavier, but deadlier. Min ST: 5.}
{49800}{}{Laser Emitter (Improved)}
{49801}{}{A makeshift weapon created from parts of an industrial robot. Emits a low-power laser beam over a short distance. Min ST: 3.}
{49900}{}{Viva, Villa!}
{49901}{}{This is an old patriotic comic book. It's amusing that even now its content hasn't lost its relevance.}
{50000}{}{}
{50001}{}{}
{50100}{}{}
{50101}{}{}
{50200}{}{}
{50201}{}{}
{50300}{}{}
{50301}{}{}
{50400}{}{}
{50401}{}{}
{50500}{}{}
{50501}{}{}
{50600}{}{}
{50601}{}{}
{50700}{}{}
{50701}{}{}
{50800}{}{}
{50801}{}{}
{50900}{}{}
{50901}{}{}
{51000}{}{}
{51001}{}{}
{51100}{}{}
{51101}{}{}
{51200}{}{}
{51201}{}{}
{51300}{}{}
{51301}{}{}
{51400}{}{}
{51401}{}{}
{51500}{}{}
{51501}{}{}
{51600}{}{Pip-Boy Booster}
{51601}{}{The booster is designed for quick analysis of the environment. Designed by Brotherhood of Steel scribes, standard model.}
{51700}{}{}
{51701}{}{}
{51800}{}{}
{51801}{}{}
{51900}{}{}
{51901}{}{}
{52000}{}{}
{52001}{}{}
{52100}{}{}
{52101}{}{}
{52200}{}{}
{52201}{}{}
{52300}{}{Survival Guide}
{52301}{}{Nuclear War Survival Guide. Prepared by Vault-Tec for residents of the Vault Network.}
{52400}{}{}
{52401}{}{}
{52500}{}{}
{52501}{}{}
{52600}{}{}
{52601}{}{}
{52700}{}{}
{52701}{}{}
{52800}{}{}
{52801}{}{}
{52900}{}{}
{52901}{}{}
