{110}{}{Right now this boat is only suitable for sailing to the bottom of the sea. Her hull needs repairs and her motor needs power.}
{111}{}{The engine won't start. The power indicator tells you that the fuel cell is depleted.}
{112}{}{}
{113}{}{You have patched up the cracks and holes in the hull.}
{114}{}{You have replaced the fuel cell.}
{115}{}{Fuel cell is already fully charged.}
{116}{}{You have nowhere to go now.}
{117}{}{The boat can't support that much weight. Remove everything unnecessary from your backpack.}
{118}{}{You can take this boat back to shore. Use science to navigate.}
{119}{}{This boat has enough fuel to get back to shore.}

{200}{}{The boat is ready to set out.}
{201}{}{The boat trip is cancelled for now.}
{202}{}{Go to the oil platform.}
{203}{}{Go to the Puerto Peñasco dock.}
{204}{}{Go to the settlement at the San Felipe Lighthouse.}
{205}{}{Go to the El Faro Pier.}
{206}{}{Return to El Faro Pier.}
