{100}{}{You see John Sullivan.}
{101}{}{You see a man who commands respect. It looks very clean and well-groomed.}
{102}{}{You either do something or stay out of the way.}
{103}{}{It was that easy? I can't even believe it.}
{104}{}{What a pleasant surprise. Finally, the Don is dead, and all power now goes to me.}
{105}{}{Let's finish Bustos and end it.}
{106}{}{Everything turned out pretty well. Let's chalk this up to an attack by the highwaymen.}