{100}{}{You see Paul.}
{101}{}{This man looks severely emaciated.}

{198}{}{Hey! A paladin, here? Wait... where did you get that armor? Well, however you got here, the mutants will kill you if they find you.}
{199}{}{Hey! A reaver...? No, you must be a ghoul... how did you get here? You don't belong in this place. The mutants will kill you if they find you.}
{200}{}{Hey! What... How did you get here? The mutants are gonna kill you if they find you.}
{201}{}{They left you alone, didn't they? Who are you?}
{202}{}{I know. So stay quiet and don't make a sound.}

{210}{}{You're taking a big risk.}
{211}{}{If you get caught, I won't be able to help you.}
{212}{}{Why are you still here?}
{213}{}{What's up?}
{214}{}{You still have a chance to get away.}
{215}{}{Do you have a plan, brother?}
{1215}{}{Do you have a plan, sister?}
{216}{}{}
{217}{}{}
{218}{}{'Bye.}
{219}{}{See you.}

{220}{}{My name's Paul. The mutants force me to keep an eye on the platform. They don't understand the technology.}
{221}{}{And you do? Why do you understand it?}
{222}{}{Come on. Nobody alive understands old technology anymore.}
{223}{}{Huh?}

{224}{}{Does the name "Brotherhood of Steel" mean anything to you? I am a knight of this ancient order. And the primary duty of our knights is to understand ancient technology.}
{225}{}{Have you tried escaping?}
{226}{}{Oh really?}

{227}{}{I've missed my chance. It's desert all around, so the mutants would catch me easily. And even if I escaped, we're too far from any base or settlement. By the way... do you know where we are?}
{228}{}{The Sonoran Desert.}
{229}{}{Sonora...}

{230}{}{I know about the Brotherhood of Steel. They've got a base not too far from here.}
{231}{}{What?! Wait-where are we exactly?}
{232}{}{Then I've got hope! I think we had a supply outpost in Puerto Peñasco. They'd take me in there... if I managed to reach it.}
{233}{}{So what are you waiting for?}
{234}{}{And?}
{235}{}{I told you-the mutants are holding me here! We'd need to sabatoge the platform. There's a reactor on the lower level. If we disable it, the platform won't move anywhere.}
{236}{}{Alright. I'll take care of it.}
{237}{}{Got it.}
{238}{}{Wait, Paul. I need to know more about the situation.}
{239}{}{I know about the Brotherhood of Steel. They used to have a base not too far from here.}

{240}{}{The Brotherhood of Steel is evil incarnate. I'll kill you like I killed all your comrades in Puerto Peñasco!}
{1240}{}{The Brotherhood of Steel is evil incarnate. I'll kill you like I killed all your comrades in Puerto Peñasco!}
{241}{}{Bwadahood bad! Die, knight!}
{242}{}{The Brotherhood of Steel is my enemy. You're not leaving this place alive!}
{243}{}{I've recently joined the Brotherhood of Steel myself. Glad to meet you, brother.}
{1243}{}{I've recently joined the Brotherhood of Steel myself. Glad to meet you, brother.}
{244}{}{Alright, I'll take your word for it. Not like I have a choice. But only one outsider has ever been inducted into the Brotherhood, and his deeds were... well, legendary. Anyway... where are we exactly?}

{250}{}{How did you end up here?}
{251}{}{The super mutants grabbed me near Necropolis. First, they wanted to kill me, but then they found out I'm an engineer and kept me around to keep this platform running. Been a prisoner ever since.}
{252}{}{Necropolis? Where is that?}
{253}{}{Kaka-polis?}
{254}{}{It's in California. No wonder you don't know it-we're very far from those places.}
{255}{}{I see.}
{256}{}{Okay.}

{260}{}{Do you know where the super mutants are heading?}
{261}{}{They don't know themselves. The captain promised them he'd seize some rich region and found a super mutant state there.}

{300}{}{The reactor is down. Time to get out of here.}
{301}{}{As an engineer, it hurts me to see ruined machinery. But there was no other choice. The mutants won't be able to restore the platform. And stranded in the desert, they pose no threat to anyone.}
{302}{}{Let's go.}
{303}{}{Boom-boom! Me did it all!}
{304}{}{The reactor is already offline. Time to move.}

{310}{}{The super mutants are dead. You're free.}
{311}{}{Super-muties-gone! Me smash boom heads!}
{312}{}{That's impressive! If only we'd had soldiers like you during the Great War against the super mutants...}
{313}{}{Let's go.}
{314}{}{There's no need. The super mutants are dead and the path is clear.}

{320}{}{The most important thing now is not to draw attention. We need to get away from the platform before we're noticed.}
{321}{}{Let's go.}
{322}{}{We're far enough. You're free now.}
{323}{}{Okay.}
{324}{}{If I make it back, I'll tell everyone about you. Now I need to put everything I learned back at the base to practical use. Maybe we'll meet again in Puerto Peñasco-if your road leads you there.}
{325}{}{Good luck on your journey.}
{326}{}{Later!}