{101}{}{You see an old table equipped for repairing collars.}
{110}{}{Prisoners' collars are repaired on this table.}
{111}{}{All components are used up. There's nothing more to do here.}
{112}{}{Having dismantled the parts, you received a micro fusion cell with 10 charges.}
{113}{}{Having dismantled the parts, you received a micro fusion cell with 20 charges.}
{114}{}{Having dismantled the parts, you received a micro fusion cell with 30 charges.}
