{100}{}{You see a scavenger.}
{101}{}{You see a scavenger ready to hunt a brahmin.}
{102}{}{Damn it! This brahmin isn't wild after all. But we still have to take it. Got it?}

{110}{}{Don't make us regret this.}
{111}{}{The brahmin is ours. Go back to town and give the bartender the good news.}
{112}{}{We didn't expect it to go like this!}

{200}{}{Turns out this brahmin isn't wild after all, huh? Look, we need to get it anyways.}
{201}{}{Are you going to attack?}

{202}{}{The city is starving, trade has almost stopped, we NEED this brahmin! So, do you have a better idea?}
{203}{}{I'm in. Let's begin!}
{204}{}{Don't rush into this, maybe I can negotiate with them.}
{205}{}{There has to be a way to avoid bloodshed!}
{206}{}{You're a soft-hearted fool. If you won't join in the attack, then step aside. Or... can you get the brahmin without the herders noticing?}
{1206}{}{You're a weak little girl. If you won't join in the attack, then step aside. Or... can you get the brahmin without the herders noticing?}
{207}{}{Alright, let's do this. C'mon!}
{208}{}{I won't let you do this.}
{209}{}{Really? So what are you gonna do?}
{210}{}{I know how to fight, unlike those herders. Bring it on!}
{211}{}{Just let me talk to the herders. I can find common ground with them.}
{212}{}{You'll regret this. (spits at your feet) Let's go, guys.}
{213}{}{I've changed my mind. Now you're gonna die!}
{1213}{}{I've changed my mind. Now you're goona die!}
{214}{}{Yeah, get out of here.}
{215}{}{I'll find a way to solve your food problem.}
{216}{}{Your word means nothing to us.}
{217}{}{Then we have no choice but to attack the herders. I'm with you.}
{218}{}{Wait, give me a few minutes. Maybe I can reach an agreement.}
{219}{}{Will you bring the trade caravans back to the city? Hmm, I guess you can be trusted. But don't make us regret this... Let's go, guys.}
{220}{}{Good decision.}
{221}{}{Great idea. I'm gonna try to bring this brahmin to you.}
{222}{}{I'll solve your food problem. I give you my word.}

{250}{}{Hold on, let me negotiate with the herders. Maybe I can persuade them to give up the brahmin peacefully.}
{251}{}{Ha! Herders don't just take care of their flocks, they DEIFY their brahmin. Persuading them to give up a brahmin is like asking them to cut off their own hand.}
{252}{}{I'll try anyway.}
{253}{}{Seems we have no other choice. Guys, surround them from all sides!}
{254}{}{Are you really going to attack peaceful herders?}
{255}{}{Here's the brahmin. Take it before the herders come to their senses.}
{256}{}{The brahmin is ours. The savages won't risk it for its carcass.}
{257}{}{Well, we got what we came for! Imagine the feast we'll have with this meat? Thanks man.}
{258}{}{See you in Garage City.}
{259}{}{We've almost got the brahmin. Wait until I bring it closer...}

// added this to have better responses for buying the brahmin - cambragol
{260}{}{I traded with the herders for the Brahmin. It's ours now.}

