{100}{}{You see Dominguez's child.}
{101}{}{You see a typical village boy. And he smells like one too.}
{102}{}{Hrrr...}
{103}{}{The old shoes haven't worn out yet.}
{104}{}{The child is thrilled with his new shoes.}
{105}{}{Gracias!}

{106}{}{«Thanks!»}

{110}{}{H-Hola. You... really come from norte?}
{111}{}{Weird. You no look like you... eat people.}
{112}{}{They say... only savages live in norte.}
{113}{}{You really... eat people allá... up in norte?}
{114}{}{One day... General Sarabia take Arizona.}
{115}{}{You want push... the waka?}
{116}{}{Better stay away from... our waka. They no like strangers.}
{117}{}{Want ride waks? Pay... dos pesos.}
{118}{}{You really pay con... caps? Pf-ha-ha-ha!}
{119}{}{Estúpido norteño! Estúpido norteño! Be-be-be!}
{120}{}{My shoes... broken. You have... something to fix?}

{210}{}{«Hello. Did you really come from the north?»}
{211}{}{«Weird. You don't look like you eat people.»}
{212}{}{«We were always told that only savages live in the north.»}
{213}{}{«Do you really eat people up there in the north?»}
{214}{}{«One day General Sarabia will take over Arizona.»}
{215}{}{«Do you want to push the waka?»}
{216}{}{«You better stay away from our waka. They don't like strangers.»}
{217}{}{«Want to ride some wakas? Then pay two pesos.»}
{218}{}{«Are you really paying with caps? Pf-ha-ha-ha!»}
{219}{}{«Stupid northerner! Stupid northerner! Be-be-be!»}
{220}{}{«My shoes broke. Do you think you can fix them?»}

{1110}{}{Hola... you really come from the north, sí?}
{1111}{}{Es weird. You no look like... savage caníbal.}
{1112}{}{We always told... only salvajes live en el norte.}
{1113}{}{They eat peoples allá en the north, verdad?}
{1114}{}{One day, General Sarabia... he gonna take all Arizona.}
{1115}{}{¿You want push el waka?}
{1116}{}{Better stay lejos de nuestros waks. They no like strangers.}
{1117}{}{You wanna ride waks? Then... pay doble de pesos, chica.}
{1118}{}{You really payin' con chapas? ¡Pf-ja-ja-ja!}
{1119}{}{¡Stupid girl of the north! ¡Stupid northerner! ¡Be-be-be!}
{1120}{}{My zapatos... they broked. You think... maybe arreglar them?}

{1210}{}{«Hello. Did you really come from the north?»}
{1211}{}{«Weird. You don't look like you eat people.»}
{1212}{}{«We were always told that only savages live in the north.»}
{1213}{}{«Do you really eat people up there in the north?»}
{1214}{}{«One day General Sarabia will take over Arizona.»}
{1215}{}{«Do you want to push the waka?»}
{1216}{}{«You better stay away from our waka. They don't like strangers.»}
{1217}{}{«Want to ride some wakas? Then pay double pesos.»}
{1218}{}{«Are you really paying with caps? Pf-ha-ha-ha!»}
{1219}{}{«Stupid northerner! Stupid northerner! Be-be-be!»}
{1220}{}{«My shoes broke. Do you think you can fix them?»}