{100}{}{You see a lab assistant.}
{101}{}{You see a mutated man. His face looks like melted wax.}

{110}{}{It's surprising they let you in here.}
{111}{}{I don't have time for conversations with pagans.}
{112}{}{I don't have anything for you.}
{113}{}{Leave me alone or I'll call my green-skinned brothers.}
{114}{}{Smooth skin? Ugh, disgusting!}
{115}{}{I'm baffled by how you normals manage to survive in this world.}
{116}{}{Desert dwellers are clueless.}
{117}{}{Listen to Levi.}
{118}{}{I don't trust you or any strangers like you.}
{119}{}{Our people have suffered greatly at the hands of the Norms...}

{120}{}{Oh, come on in, buddy, grab a seat.}
{121}{}{This is no place for pagans. But we'll make an exception for you.}
{122}{}{Want me to whip up some radioactive coffee?}
{123}{}{Apologies for my green brothers; they're a bit out of touch with regular folks.}
{124}{}{What's up with your skin? How'd you manage to keep it?}
{125}{}{You normies are really holding your own in this new world.}
{126}{}{People astound me with their resilience.}
{127}{}{Listen to Levi; he was practically handpicked by the Master himself!}
{128}{}{I trust you. But those Brotherhood of Steel fools? Not so much.}
{129}{}{Our people have been through hell. You couldn't possibly understand.}

{130}{}{How are you feeling?}
{131}{}{Now you will know all the pain we were called to endure. I pity you.}
{132}{}{Care for some irradiated coffee?}
{133}{}{Those dumb green brutes not giving you trouble, are they?}
{134}{}{Your transformation has only just begun.}
{135}{}{Obey Levi. He was close to the Master Himself!}
{136}{}{I trust you.}