{100}{}{You see a computer.}
{101}{}{You see an ancient computer. It's remarkable that it still functions.}

**#Dialogue**
{200}{}{System loaded}
{201}{}{End session}
{202}{}{Back}
{203}{}{Welcome to the electronic files of the Mexicali Police Department.}
{204}{}{Database loading...}

{210}{}{Assault in a supermarket}
{211}{}{"...You have known him for a long time. What do you think caused such an act?"}
{212}{}{[More]}
{213}{}{"What's there to tell? He's a war veteran. You know, all that horror at Anchorage. And although he was awarded for excellent service, the war trauma in his head remained."}
{214}{}{[More]}
{215}{}{"In the head? Was he injured?"}
{216}{}{[More]}
{217}{}{"No, no, he's lost his mind! It was for you that he shot all those people in a supermarket. For him, he's still fighting the war. He thought he was shooting at the Reds..."}
{218}{}{Stop recording}

{220}{}{Complaints about construction work}
{221}{}{"...I'm telling you, my plan is fully compliant! Everything is according to the law! And how can the neighbors prove that I encroached on their property while excavating?"}
{222}{}{[More]}
{223}{}{"I suppose. But what about the vibrations from construction that keeps them awake? And also the dust, broken glass, and endless trucks? They also say that you're using unlicensed labor."}
{224}{}{[More]}
{225}{}{"This is an expensive project... Argh, don't you understand?! When the world war starts, and it definitely will, no one will care about vibrations and trucks! I'm building a bomb shelter to save myself and my family. What will the neighbors do? Oh, they'll run to me for shelter. You'll see, officer..."}
{226}{}{Stop recording}

{230}{}{Complaints of threats}
{231}{}{"...Ma'am, please calm down..."}
{232}{}{[More]}
{233}{}{"Calm down? Yes, these barbarians want me dead! The neighbors have been trying to get me out of the city for a long time. I have been putting up with their antics for many years now. But they have already crossed all boundaries! I pay dearly for the house and will not allow anyone to accuse me of having connections with the Reds just because I have Chinese blood. Do something, you're the police!"}
{234}{}{[More]}
{235}{}{"Of course, ma'am... uh... But understand -- your evidence is not enough to charge your neighbors. A dead cat, writing on the walls, and anonymous notes -- none of this indicates a real threat. We can't..."}
{236}{}{[More]}
{237}{}{"Why am I wasting my time here with you! It's clear -- you're all bastards here! Bastards! Give me my statement, I'm leaving..."}
{238}{}{Next.}
{239}{}{"Ugh... She's such a bitch. This is the third one this month. What do you think, Rodrigo, is she really one of 'those'?"}
{240}{}{[More]}
{241}{}{"Let her go, Nick. It's better that the neighbors push her to the limit than for her to end up with ties to the Reds... Oh, damn, I didn't turn off the recorder..."}
{242}{}{Stop recording}

{250}{}{About the cactus}
{251}{}{"So, guys. Tell me how it *really* happened."}
{252}{}{[More]}
{253}{}{"Well, we were just walking in the desert and sat down near a cactus. And then this thing fell on Paco! We didn't do anything wrong, honestly, senor!"}
{254}{}{[More]}
{255}{}{"Yeah. Then how do you explain the charred laser marks on the stump of a cactus? [silence] Guys, I don't want to put pressure on you. I want to help. Tell me the truth, and you'll get off with just a warning. [silence] So, okay. Let me help you remember."}
{256}{}{[More]}
{257}{}{"Paco took his father's laser pistol without permission, after which you decided to test it on a cactus. Isn't that what happened? [silence] But the cactus turned out to be stronger, and the charge ran out too quickly, and you decided to finish knocking the cactus over by hand? [silence] Guys, you know that shooting at cacti is prohibited in the state, not to mention using weapons without..."}
{258}{}{[More]}
{259}{}{"Senor! Senor! Just don't tell our parents!"}
{260}{}{Stop recording}

{270}{}{About the robot.}
{271}{}{"...So you're saying that the robot had no defects and acted on its own?"}
{272}{}{[More]}
{273}{}{"I'm afraid it doesn't sound quite right this way, senor officer... The Mr. Handy series robot only performs assigned tasks. But look at the requests of the Wilson family! It seems to me that they had... some relationship problems."}
{274}{}{[More]}
{275}{}{"Relationship problems? Yes, we know that there were regular quarrels in their family. But how could this affect a robot that "only performs assigned tasks"?"}
{276}{}{[More]}
{277}{}{"Well... The robot's interpreter is not perfect. And when the Wilsons' mother threatens to "cook" her son, and the son asks the robot to "kill his parents," something might have been misunderstood... "}
{278}{}{[More]}
{279}{}{"So. Do you understand what you're saying? Your service center maintains robots that are programmed to prohibit harming people. And now these robots, you see, have "misunderstood" something. Stop misleading the investigation! Admit the defect and we will reduce the punishment!"}
{280}{}{Stop recording}

{290}{}{Anti-American protest}
{291}{}{"So you admit your guilt in participating in an illegal rally aimed at overthrowing the current government?"}
{292}{}{[More]}
{293}{}{"Guilt? Well, no! These Americans enslaved all of Sonora! They are the criminals! They and our corrupt government! How can you call the rally illegal?..."}
{294}{}{[More]}
{295}{}{"Okay. I'll repeat my question again..."}
{296}{}{[More]}
{297}{}{"Mexico for Mexicans! Mexico for Mexicans!"}
{298}{}{[More]}
{299}{}{"Stop! Silence! Everyone be silent!"}
{300}{}{[More]}
{301}{}{"So what, are you going to jail us?" - "We demand a lawyer!" - "Are you satisfied with your salary?" - "While Madera was in power, the Americans did not interfere with us..." - "Have you already forgotten that massacre on the border?" - "Mexico for Mexicans!"}
{302}{}{Stop recording}
