{110}{}{This is a tribal totem made from skulls and what the savages consider "spiritual." Your opinion on this may differ from theirs.}
{111}{}{Totem destroyed. Maybe there's something useful in this pile of trash.}

{130}{}{}
{131}{}{Aren't you afraid this will anger the savages?}
{132}{}{}
{133}{}{It's part of their 'culture'. Why bother doing this?}
{134}{}{}
{135}{}{}
{136}{}{Ha! I can just imagine the faces the savages will make when they see this.}