{100}{}{You see the manager.}
{101}{}{You see a man in work clothes.}

{200}{}{Ah, our hero. I heard about that creature you took down. The whole town is grateful.}
{1200}{}{Ah, our heroine. I heard about that creature you took down. The whole town is grateful.}
{201}{}{I see you didn't waste any time getting things running again.}
{202}{}{We produced concrete and bricks here until El Gigante appeared. It killed many workers, so we had to shut down. Now that the monster is gone, the work continues.}
{203}{}{I see.}
{204}{}{Come in, I'm always glad to see such helpful people.}
{205}{}{It's time for me to go.}
{206}{}{I see.}

{207}{}{How can I help you?} // added this to make the dialogue smoother - cambragol


{210}{}{How much do you pay your workers?}
{211}{}{Mostly convicts and slaves. They get enough water, food, and work clothes. We also have a few free mercenaries.}
{212}{}{Is this concrete plant really that important to you?}
{213}{}{I don't know of any other operating concrete plant. When someone needs to build a house, they salvage bricks from old ruins. Here in Casa Nueva, we build from scratch.}
{214}{}{Do you sell cement and bricks?}
{215}{}{Initially, the plant served Casa Nueva. Now we transport supplies to construction sites in Puerto and Two-Sun. We're planning to supply Phoenix soon, if we can get local authorities on board. But first, we need to get back to normal operations.}
