{100}{}{You see a lab computer.}
{101}{}{You see a laboratory computer.}
{102}{}{The computer won't start due to lack of power.}
{103}{}{It won't turn on.}

Dialogue

{200}{}{Enter command:}
{201}{}{End session}
{202}{}{Back}
{203}{}{Next}
{204}{}{Return to main menu}

{210}{}{Wang Chong's Research Notes}
{211}{}{"Setting the research goal for the next five years: developing drought-resistant, fruit-bearing crops suitable for mass cultivation. This aims to solve the food scarcity in Arizona and California, addressing the needs of the growing population."}
{212}{}{Material base of the experiment}
{213}{}{"The research is conducted at the well-preserved 'Greenway Hydroponics' lab, where pre-Great War experiments were aimed at creating drought and radiation-resistant plants. This facility also prepared materials included in the Vault-Tec survival kits for post-nuclear war survival."}
{214}{}{[More]}
{215}{}{"The laboratory retains: work equipment, automated hydroponic systems, radiation-free seeds of various plants and fungi, extensive lab documentation and pre-war literature, along with a diverse set of chemicals, biological additives, and viruses."}
{216}{}{Project objectives}
{217}{}{"The first objective is to study the research and material base of Greenway Hydroponics to restore the operation of the complex and laboratory. Among the local developments, there are ready-made solutions that can be used for Casa Nueva."}
{218}{}{[More]}
{219}{}{"The second objective is to breed plants to increase seed reserves. The work should be conducted in isolated greenhouses to create the cleanest and most controlled environment possible."}
{220}{}{[More]}
{221}{}{"The third objective is to develop new plant varieties suitable for survival in the Sonoran Desert and the radioactive wastelands of California."}
{222}{}{Important note}
{223}{}{"An important condition of the experiment is to stimulate the growth of plants, especially their root systems. Various methods are proposed: biological additives, irradiation, fungal spores, and viruses from Greenway Hydroponics' stocks. For safety, access to the laboratory should be strictly limited."}
{224}{}{Copy research data.}
{225}{}{The archives have been successfully copied to the holodisk.}
