{100}{}{You see a surgeon.}
{101}{}{You see a surgeon in a blood-stained coat.}
{102}{}{If I don't hurry, no medicine will help me...}

#First dialogue
{200}{}{What's the problem?}
{201}{}{Are you always this cavalier with your patients?}
{202}{}{(folds his gloves and rubs his hands) I work alone, but there are many, many patients. Are you somehow special?}
{1202}{}{(folds his gloves and rubs his hands) I work alone, but there are many, many patients. Are you somehow special?}
{203}{}{I don't know... uh... What would make me special?}
{1203}{}{I don't know... uh... What would make me special?}
{204}{}{The special title of 'Follower of Fire'... or a large amount of caps. You fulfill either of those?}
{205}{}{I guess.}
{206}{}{No, nevermind. I was just curious.}

#Re-dialogue
{210}{}{Well, what's the problem?}
{211}{}{Nothing.}

#Treatment
{220}{}{I need medical attention.}
{221}{}{Well, let's see. What are we looking to treat?}
{222}{}{[Heal wounds for }
{223}{}{[Heal injuries for }
{224}{}{[Remove all radiation for }
{225}{}{[Remove all poisons for }
{226}{}{You know, it'll probably go away on its own.}
{227}{}{Typical case. We'll take care of it. But since you're not a Follower, you'll have to make a donation.}
{228}{}{ caps]}
{229}{}{Oh.}
{230}{}{Typical case. We'll take care of you.}
{231}{}{Treatment's not free. Come on!}
{232}{}{I'll have to get some caps...}
{233}{}{}
{234}{}{Hail the Holy Fire. Now get out of my office, I have other work to attend to.}
{235}{}{That's not all, Doc.}
{236}{}{Do it, Doc.}
{237}{}{Certainly.}

{240}{}{Have you seen any peasants from Villa recently?}
{241}{}{Hmm, one of the slaves mentioned Villa during their examination.}
{242}{}{What happened to him?}
{243}{}{No idea. My job is to just conduct a physical examination.}
{244}{}{I see.}
