{100}{}{You see the farmer's wife.}
{101}{}{You see the farmer's wife, preoccupied with typical farm chores.}

#Random Remarks
{110}{}{*Humming softly*}  
{111}{}{Wind's starting to pick up.}  
{112}{}{Hope we don't get caught in a sandstorm today.}  
{113}{}{Looks like another bad crop season ahead...}  
{114}{}{Wish those folks up north would share some seeds.}  
{115}{}{I'm so tired...}  
{116}{}{Might need to find ourselves a new dog soon.}  
{117}{}{Damn radscorpions, always stirring up trouble.}  
{118}{}{More drifters seem to be passing through lately.}  
{119}{}{This land's ours, plain and simple.}  
{120}{}{We're safe with the Rangers around.}  
{121}{}{Let's hope no unexpected visitors show up today.}  
{122}{}{Hard to imagine life without the Rangers.}  
{123}{}{At least we can sleep easy with the Rangers watching over us.}  
{124}{}{Gotta trust the Rangers to do what's right.}  
{125}{}{Who's gonna protect us now?}  
{126}{}{Without the Rangers, we'd be easy pickings for raiders.}  
{127}{}{I won't walk away from the land I've spent my life working.}  
{128}{}{Whoever destroyed the dam doomed all of us living nearby.}  
{129}{}{What kind of person could do something like that?}  
{130}{}{Zzz...}  
{131}{}{*Yawns*}  
{132}{}{...Gotta be up early tomorrow...}  
{133}{}{...So worn out...}  
{134}{}{Zzz...}  
{135}{}{*Snoring softly*}  

#Dialogue
{200}{}{Oh, a visitor! Don't believe we've met before. What's your name?}
{201}{}{.}
{202}{}{Just a wastelander passing through.}
{203}{}{Well, pleased to meet you, }
{204}{}{. If you're in need of food or a place to rest, you should speak with the Rangers. Their base's down the road, a few hours walk.}
{205}{}{Nice to meet you... though you have a rather strange name}
{206}{}{Then why are you settled here?}
{207}{}{Seems like you're trying to shoo me off.}
{208}{}{Shoo you? Listen, this is a peaceful farm. And if you're thinking of causing trouble, remember, this is Ranger territory. And the Rangers don't take kindly to troublemakers...}
{209}{}{Alright, alright, got it.}
{1209}{}{Alright, alright, got it.}
{210}{}{Good.}
{211}{}{But why live apart from the Rangers?}
{212}{}{Can't grow crops on rocks. And we prefer our own space.}
{213}{}{Mind if I fetch some water here?}
{214}{}{Got it. Won't bother you any longer.}
{215}{}{My husband wears the pants in this house. You'll need to talk to him.}
{220}{}{Ah, I remember you now.}
{221}{}{Goodbye.}
{222}{}{You'd best move on soon, lest the Rangers find you. They can be quite persistent when they want something.}
{1222}{}{You'd best move on soon, lest the Rangers find you. They can be quite persistent when they want something.}
{223}{}{Pipe down, woman.}
{224}{}{Sorry, won't disturb you further.}
