{100}{}{You see a cartographer.}
{101}{}{You see a Ranger in baggy attire with a bulky eyepiece strapped to his forehead. It looks like constant work in dim light has taken its toll on his vision.}

{200}{}{(You see a thin Ranger; his uniform hangs loosely on his frame, and he wears an eyepiece with interchangeable lenses perched atop his brow. When he notices you, he adjusts the lenses and squints, studying your face intently) Huh? Who let you in?}
{201}{}{No worries, I've got clearance.}
{202}{}{Me.}

{210}{}{Hey there.}
{211}{}{Catch you later.}
{212}{}{Let's backtrack a bit.}
{213}{}{Uh, okay. What now?}

#Questions
{220}{}{What's your role here?}
{221}{}{I'm tasked with crafting new maps of the wasteland. A painstaking and tedious job, if you ask me.}
{222}{}{What's the issue with the old maps?}
{223}{}{They become outdated. Sure, the landscape hasn't changed much since the Great War, but some lakes and rivers have dried up, radioactive zones have expanded, and new settlements have sprung up. Nowadays, only Rangers and caravan drivers have a comprehensive grasp of the surrounding geography. Yet, even our patrols often require precise coordinates. And no one's making new maps... except for me.}
{224}{}{What do your maps detail?}
{225}{}{Anything that could be useful to our people out there: settlements, farms, outposts, radioactive zones, oases. Nearly any kind of cartographic information could prove vital to the command center.}
{226}{}{Can I take a look at your maps?}
{227}{}{This is strategic information. It's not something we just share with outsiders. Become a ranger or earn it.}
{228}{}{Sure thing. We've got no secrets among ourselves.}
{229}{}{Do you have other responsibilities besides mapping?}
{230}{}{They toss me anything that involves reading and writing.}
{231}{}{Is that why you're always scowling and squinting?}
{232}{}{Are you kidding? I've been poring over maps and texts in dim light for years. Without my eyepiece, I can hardly see a thing... If they ever send me out into the Wastes, it'll be my last day alive, mark my words.}
{233}{}{Why haven't you left?}
{234}{}{Despite the command center being in ruins, it doesn't absolve me of my duties.}

- added below for mid-quest help in survey quest and map reward for same quest - cambragol
{235}{}{So where are these survey markers?}
{236}{}{Like I said, they're like a tripod of metal and junk, stuck into an old tire.}
{237}{}{Alright, I'll keep at it.}

{238}{}{Okay, let's take a look then.}
{239}{}{Hope that helps you out.}
{240}{}{Thanks. Very informative.}

{241}{}{How many markers are there?}
{242}{}{You need to take readings from all 5 of them.}




#Quartz
{250}{}{Commander Helford wants me to check out Quartz.}
{251}{}{Really? The commander probably doesn't have enough people... I've been asking him to take measurements there for a long time.}
{252}{}{Well, never mind then.}
{253}{}{What can you tell me about the place?}
{254}{}{It's the remnants of an ancient town. (points to a location on the map) For years after the Great War, it remained heavily irradiated. Coupled with the blistering desert climate, it scared off any settlers or travelers. Only recently have the radiation levels dropped enough to be considered safe. That's why we haven't paid much attention to those ruins until now.}
{255}{}{I need more details about Quartz.}
{256}{}{Fair enough.}
{257}{}{Why was Quartz radioactive?}
{258}{}{The radioactive fallout from the nuclear blasts in California was carried there by western storms. Those lands took a heavy hit during the Great War.}
{259}{}{What dangers might I encounter there?}
{260}{}{Residual radiation, radscorpions, collapsing buildings... Overall, Quartz has been relatively quiet so far.}
{261}{}{What measurements need to be taken?}
{262}{}{It might be too much for one person: radiation levels, environmental conditions, vegetation...}
{263}{}{My Pip-Boy has a built-in mapping sensor.}
{264}{}{Impressive! Seems like you're tailor-made for this task. Survey markers have already been set up in ideal locations. They're marked with a tire supporting a tripod of old wood and metal bars. Your job is simple: go to the survey markers and record the data.}
{265}{}{Got it. I'll report back when I'm done.}
{266}{}{I'm not keen on mapping, but I do need more info about Quartz.}
{267}{}{Excellent! You'll be doing the Rangers a great service. I'll help you out with the maps, too.}
{268}{}{Alright, but I still have some questions about Quartz.}
{269}{}{Catch you later.}
{270}{}{Here are the readings from Quartz.}
{271}{}{Incredible! You've provided more data than I anticipated! That contraption on your arm works wonders. You can use my maps as a token of appreciation. Thanks.}
{272}{}{Glad to be of service to the Rangers.}
{1272}{}{Glad to be of service to the Rangers.}
{273}{}{I could've used some extra ammo...}
{274}{}{Why bother mapping that wasteland?}
{275}{}{We may not need them now, but it pays to be prepared for anything. There could be mutant nests or raider hideouts lurking in those ruins. Besides, Quartz is the gateway to California. It may still be sealed off by the desert, but it's only a matter of time.}

{276}{}{Me go Quartz.}
{277}{}{Ah-huh.}
{278}{}{Doodle-doodle need?}
{279}{}{I got Pipa-Boy here.}
{280}{}{Okey-dokey.}
{281}{}{Bye-bye!}
{282}{}{Me finished. [Show measurements from Quartz]}
{283}{}{Thanks.}