{100}{}{You see the command computer.}
{101}{}{You see the Supreme Paladin's computer.}

#Dialogue
{200}{}{Enter command:}
{201}{}{End session}
{202}{}{Back}
{203}{}{Next}
{204}{}{Return to main menu}

{210}{}{Dossier on Private Corwin}
{211}{}{Name: Alvin Corwin. Rank: Initiate. Unit: Candidate Paladin. Health Status: Normal.}
{212}{}{On behalf of Paladin Dixon, issue a leave order for Initiate E. Corwin.}
{213}{}{Order accepted.}
{214}{}{Perfect. I'll go give Alvin the good news.}

{220}{}{Open Dixon's message.}
{221}{}{"The world needs strength. A strength that can lift it from its knees and set a steady shoulder beneath it so it may take the next step forward. And only the Brotherhood of Steel possesses what is required. For too long, the Order remained apart from the outside world. Yet when the super mutant threat loomed over California, it was we who stood against it. We can no longer cower in our bunkers. The war is not over. Our brothers and sisters in Lost Hills - and all of California - require the technologies and resources of Sonora. Let us temper our steel, and stand together against the enemy!"}
{222}{}{Mission: "Flag of the Nation".}
       #title is a reference to the film "Jailhouse Rock" 1955
{223}{}{"Securing Arizona's wild lands demands decisive action. We need the whole of this fractured territory to be brought under one vision - ours. Installing Brotherhood-friendly governance in critical locations will ensure our influence. Should any ungrateful locals resist, we'll adjust their attitudes as necessary. Reeducation awaits."}
{224}{}{Project: Lame Duck.}
       #title is a political term in the USA
{225}{}{Our mandate in Phoenix is simple: establish unquestionable Brotherhood authority and create a hidden advisory council led by a Brotherhood representative. No one outside the Brotherhood needs to know who truly pulls the strings."}
{226}{}{Operation: Wind of War}
{227}{}{Our Nogales outpost will become a bulwark, controlling the Mexican border and monitoring cross-border threats. Intelligence tells us the settlement faces the Mexican army - excellent. Let them come; the Brotherhood fears no one."}
{228}{}{Our Main Goal}
{229}{}{"The primary objective remains: gather Sonora's technology and nuclear resources for Lost Hills. Arizona's rich resources will power our war against the super mutants and future threats. As High Paladin here, I hold the authority to make any decision necessary to secure these assets."}

{240}{}{Read Dixon's diary.}
{241}{}{"...California's elders didn't send me to Arizona to play the role of a savior. They sent me to claim what's been squandered by those too ignorant to understand the value of what they sit on. Pre-war tech and resources are being squandered, and it falls to us to make sure nothing more is lost."}
{242}{}{"...The locals refuse to surrender technology willingly or share their resources. The seizure of Phoenix was a bloody affair only because it could not have been otherwise. We are FORCED to impose ourselves upon the population in order to achieve our objectives..."}
{243}{}{"...The Elders in the Lost Hills may balk at these measures, but how else can they expect Arizona to supply what they need? Nuclear fuel moves from Flagstaff's mine to Two-Sun's workshops, then onwards through the wastes to the Lost Hills. That requires a great many hands, even if they are unwilling ones. Out here, far from home, we do not have the luxury of moral reflection."}
{244}{}{"...Arizona's traditions are embedded too deeply, and its people cling to their old-ways with the tenacity of weeds. After years of effort, we established our foothold in Phoenix under the guise of the cult of Aaron, yet dissent still simmers. We've brought the Tinsmiths of Two-Sun into line, but it's a tenuous alliance at best. Time is of the essence now; We must take EVERYTHING, here and now. Otherwise, our mission is doomed to fail."}
{245}{}{Close Dixon's journal.}
{246}{}{Read more.}
{247}{}{"...The war against the super mutants continues. Our brothers and sisters die for the future of California-and through them, for the survival of mankind itself. Survival is not won by mercy or hesitation, but by resolve and sacrifice, whatever the cost. That is why our mission in the Sonoran Wastes must succeed. We cannot fail..."}

