{100}{}{You see Jeff.}
{101}{}{You see the leader of a gang of runaway slaves.}
{102}{}{We're heading north soon, spreading the truth about the Tinsmiths as we go.}

{200}{}{This is surprising... Who are you, and why are you here?}

{201}{}{I'm just scavenging for valuables in these ruins...}
{202}{}{Really? And I'm supposed to buy that? You found our hideout, dodged traps, and you're deep in these ruins. Last chance - what's your real reason for being here?}
{203}{}{I'm telling the truth.}
{204}{}{Hmm... You look like a seasoned scavenger, someone who's walked the wasteland miles... Fine, I'll take your word... for now.}
{1204}{}{Hmm... You look like a seasoned scavenger, someone who's walked the wasteland miles... Fine, I'll take your word... for now.}
{205}{}{Glad we understand each other.}
{206}{}{We'll see how you feel hanging over a burning barrel. Grab the spy, boys!}
{1206}{}{We'll see how you feel hanging over a burning barrel. Grab this spy bitch, boys!}
{207}{}{Whoa, take it easy!}

{210}{}{I escaped from a labor camp and I need help.}
{1210}{}{I escaped from a labor camp and I need help.}
{211}{}{We all escaped the Tinsmiths once. Now we aim to bring justice to those who oppressed us. Maybe we can help each other.}
{212}{}{I definitely think we can.}

{220}{}{I'm here on behalf of the Tinsmiths. They're investigating a caravan attack.}
{221}{}{Yes, that was us... or rather, our triumph. We spent a month planning that hit, and we pulled it off. Now the Tinsmiths will know we're a force to be reckoned with.}
{222}{}{I see.}
{223}{}{You know, I can't just let you walk away now. Is there a reason I should?}
{224}{}{I'm just a mercenary. I don't care who you're up against.}
{1224}{}{I'm just a mercenary. I don't care who you're up against.}
{225}{}{You can't. Because now... you're going to die!}
{226}{}{We don't fight for caps, we fight against the evil of the Tinsmith's "Progress." (spits contemptuously) }
{227}{}{[More]}
{228}{}{But skags like you can't be saved. Kill him, boys!}
{1228}{}{But skags like you can't be saved. Kill her, boys!}
{229}{}{Whoa, what the...}
{230}{}{Hmm... you could be useful as our spy behind enemy lines.}
{1230}{}{Hmm... you could be useful as our spy behind enemy lines.}
{231}{}{Indeed I could.}

{240}{}{You can stay in our hideout for now. But cross us, and you'll regret it.}
{241}{}{Alright.}

#Re-dialogue
{250}{}{Our newest recruit. Anything to report?}
{1250}{}{Our lovliest new recruit. Anything to report?}
{251}{}{Nothing yet.}
{252}{}{Alright. No more questions.}

{260}{}{I'm curious, where did you all come from?}
{261}{}{We were all slaves to the Tinsmiths once. Sent to the Forbidden Zone to scavenge old tech, but some managed to escape. Couldn't get far from here, so we made a life in these ruins, surviving as best we could.}
{262}{}{What did you scavenge?}
{263}{}{Ancient tech. Some of it's long dead, and some's too dangerous to handle. The ghosts of old tech didn't like our presence and started taking out anyone who got too close, even if they were just slaves.}
{264}{}{How did you escape the Forbidden Zone?}
{265}{}{Each of us has a different story, but mostly we had help from those who came before us. I'm the last of the old resistance.}
{266}{}{Why don't you leave here?}
{267}{}{We're like this old vault - we're trying to preserve the world we know. And the Tinsmiths are trying to change it.}
{268}{}{So you want to stop the Tinsmiths?}
{269}{}{We're not ready to attack their hangar yet. So we rob the traders who deal with them. This way we replenish our supplies and cut off our enemies'. But our main goal is to kill Master Hard.}

#Attempt to smoke slaves out of Two-Sun
{270}{}{How can I help your resistance?}
{1270}{}{How can I help your resistance?}
{271}{}{We need a spy. Go back to the Tinsmiths' camp and get info on their next caravan. Check the computers in the big hangar. If you succeed, you'll get your reward.}

{280}{}{The Tinsmiths are finished here - ZAX drove them out. Time for you to leave too.}
{281}{}{So it's true? I doubted the reports at first, but now I see it's real. This day will be celebrated across the wasteland. We can finally return home and start over. Thanks for the help.}
{282}{}{You're welcome.}

{283}{}{Hard is dead, and the Tinsmiths are in chaos. Isn't it time for you to go home?}
{284}{}{So it's true? At first, I doubted the reports, but now I see it's real. It's hard to say what this will mean for the Tinsmiths, but they won't recover quickly. We can finally go home and start over. Thanks for the help.}
{285}{}{You're welcome.}

{286}{}{The Tinsmiths are preparing to attack. You better run while you can.}
{287}{}{I won't run over some rumors.}
{288}{}{Then that's your problem.}

{289}{}{(Your words have swayed them. The slaves are preparing to leave Two-Sun.)}
{290}{}{[Done]}
{291}{}{You won't last long hiding in this basement. If you really want to hurt them, there are better ways-tear down their reputation, choke off their trade routes.}
{292}{}{We must keep fighting! The Tinsmiths can't go unpunished.}
{293}{}{If you want to punish them, do it strategically. Disrupt their trade and tarnish their name. You're exhausted and powerless now.}
{294}{}{It's up to you.}
{295}{}{Maybe... maybe you're right. Our situation really is desperate. The supplies from the last convoy won't last much longer. Fine. I'll talk to the others - we'll put it to a vote. Better to live for an idea than die for nothing.}
{296}{}{Good idea.}
{297}{}{The Tinsmiths are gearing up for an attack. You don't stand a chance.}
