{100}{}{You see Jose.}
{101}{}{You see your uncle. He's trying to keep up his usual cheerful front, but it's not working so well this time.}
{102}{}{Not your best day, Jose.}
{103}{}{You've added a new quest to your Pip-Boy.}
{104}{}{Santo cielo! Why do you have to sneak up on me like that? That armor of yours doesn't belong in our peaceful Villa.}
{105}{}{You're haunted by the demons of the wasteland. Leave the village. Leave us in peace.}
{1105}{}{You're haunted by the demons of the wasteland. Leave the village. Leave us in peace.}

{120}{}{*Whistles*}
{121}{}{*Sighs*}
{122}{}{Ay, ay, ay...}
{123}{}{Eh...}
{124}{}{So... what do we do now, eh?}

# added by cambragol
{199}{}{«Ah, my dear friend», I'm so glad fate left you with us! Ay, ay, ay, those cursed raiders. You're lucky you weren't here.}
# First Dialogue
{200}{}{Ah, mi querido amigo, I'm so glad fate left you with us! Ay, ay, ay, those cursed raiders. You're lucky you weren't here.}
{1200}{}{Ah, mi querida amiga, I'm so glad fate left you with us! Ay, ay, ay, those cursed raiders. You're lucky you weren't here.}
{201}{}{Uncle Jose... tell me what happened.}
{202}{}{E-eh, those devils swarmed us when we least expected. Some were grabbed right away, while others managed to hide in their homes. Your padre and the men took cover in the town hall. They had to be dragged out by force. The gunfight was no joke. The bodies are still lying around; no one to bury them.}
{203}{}{Tell me more.}
{204}{}{Then they rounded everyone up in the plaza. They sized each person up like they were bags of corn. The strong ones were taken aside, the rest were driven back into their homes and locked up.}
{205}{}{What happened next?}

{206}{}{The raiders didn't go to sleep - they looted the Villa and drank half the night. In the morning, they took our people and headed east into the wasteland. It's been quiet since then. We're just licking our wounds.}
{207}{}{Who were these raiders?}
{208}{}{You said they went east. Anywhere specific?}
{209}{}{Why did they take our people?}
{210}{}{Well, I guess it's time for me to deal with this.}
{211}{}{They were a mixed bunch from all over. I recognized a few from Garage City, but most were strangers.}
{212}{}{I only know of Garage City in that direction. The raiders will probably stop there for the night.}
{213}{}{Well, they didn't share their plans with old Jose. But you know what, they'll likely put our people to work. Don't know where or why, though.}
{214}{}{And my parents?}
{215}{}{Sorry, but they took them. Only the old folks and kids were left behind.}
{216}{}{Let's get serious, Jose. I need to know what really happened here.}
{217}{}{Bastards!}
{218}{}{Oh!}
{219}{}{[Listen]}

{220}{}{Now that's the spirit of a true valiente guerrero! What will you do now? Start tracking the raiders? They're long gone.}
{1220}{}{Now that's the spirit of a true valiente guerrero! What will you do now? Start tracking the raiders? They're long gone.}
{221}{}{What do you think?}
{222}{}{First, tell me again about the raid.}
{223}{}{Well, first head to Garage City. It's a nasty place, but the raiders will definitely pass through there. Ask the locals, their tongues loosen up when you grease them a little.}
{224}{}{Grease them?}
{225}{}{You know, booze. But be careful with those folks, they'd sell their own mother for profit. Here, take some fruits and cornmeal for the road. For things like these, they'll tell you anything.}
{226}{}{Thanks, Jose.}
{227}{}{Don't mention it. The raiders took everything they could find. I'm giving you my last. Use it wisely.}
{228}{}{That's it? Well, thanks, I guess.}
{229}{}{Hey, the raiders took everything they could find. I'm giving you my last. Use it wisely.}
{230}{}{That's not enough, Jose. I need more.}
{231}{}{Would you leave your dear old uncle without food? Fine, take some more. But that's all I can give you. The raiders took everything they could find.}
{232}{}{The raiders took everything they could find. I'm giving you my last. Use it wisely.}
{233}{}{Looks like I'll have to figure the rest out on my own. Adios, Uncle Jose!}
{234}{}{Alright.}

{235}{}{Huh?}
{236}{}{Tank yu.}
{237}{}{Kay.}


{240}{}{Thank the heavens, you're back and you brought the others with you!}
{1240}{}{Thank the heavens, you're back and you brought the others with you!}
{241}{}{Yeah, it was no easy journey. You know, there's a big world out there beyond the Villa. No one ever told me about it.}
{242}{}{Best to keep that to yourself, amigo. Outsiders have their truth, and we have ours. We'll never see eye to eye, which is why we live apart. No one can corrupt us, no one can force their rules on us. You've seen what that raid did. We can't let something like that happen again, right?}
{243}{}{I'll think about your words, Jose.}

{244}{}{Ba-boom! Big boom! Lotta people!}
{245}{}{Uh-huh.}
{246}{}{Thank heavens you're back and brought the others with you! And I didn't even get a chance to chat with you before you left. You're something!}
{1246}{}{Thank heavens you're back and brought the others with you! And I didn't even get a chance to chat with you before you left. You're something!}

# Repeated Dialogue
{250}{}{Good to see you, amigo.}
{1250}{}{Good to see you, amiga.}
{251}{}{Amigo, don't just stand around. Find something to do, okay?}
{1251}{}{Amiga, don't just stand around. Find something to do, okay?}
{252}{}{I gotta go.}

{253}{}{I have a few questions... No, many questions.}
{254}{}{Ask anything you want.}
{255}{}{What do you know about the world beyond the Villa?}
{256}{}{Did you know there's a secret stash in the Villa's cellars?}
{257}{}{Wanna come with me?}
{258}{}{Let's go.}
{259}{}{Let's change the topic.}

{260}{}{Wild desert wastelands. Cannibal savages to the north, a junk city to the east, and a few small villages and Ranger outposts. There's also talk of a big city, but I've never been further than Garage City.}
{261}{}{It seems our knowledge of the outside world is pretty... sparse. Don't you think?}
{262}{}{Raiders not enough for you? Cannibal savages? Scavengers? No, no - we're right to keep strangers out. You can't trust outsiders. Most of them got no family, no home. Out there in the wasteland, people don't live. They survive.}
{263}{}{You gonna keep standing there, or you got something to ask?}
{264}{}{}
{265}{}{Tell me about the savages.}
{266}{}{Jackals, we call them. So wild they don't even speak human tongue anymore. Folks say they eat people. Luckily, we're too tough for them to handle, but the scavengers from the nearby city often talked about them, with fear. So steer clear of those savages.}
{267}{}{Who are the Rangers?}
{268}{}{Tough, cocky guys. They say they protect us from evildoers, but who knows what they're really up to? They come around sometimes to show off, but we manage without their help... though, you know, right now we could really use some help.}
{269}{}{Has anyone ever left our valley?}
{270}{}{Well... your Uncle Miguel did. He had a falling out with your padre and left the Villa. We haven't heard from him in years.}
{271}{}{What was their falling out?}
{272}{}{They argued about how the Villa should deal with outsiders. One thought they should be driven away, the other suggested doing business with them. They never found common ground. Though, both had valid points.}

{273}{}{Did Miguel say where he was headed?}
{274}{}{Last I remember, he wanted to see that big city folks talk about in legends. But I'm afraid the sands gave him nothing but death.}
{275}{}{}
{276}{}{}

{277}{}{Tell me about the neighboring city.}
{278}{}{Garage City. Rotten place, rotten people. Scavengers - that's what they call themselves. Crawl through ruins looking for junk to sell. Watch yourself with them - every one's a cheat.}
{279}{}{How do you know about Garage City?}
{280}{}{Hey, I'm the main trader with outsiders here in the Villa. Who else would know? Caravans sometimes come from there, we exchange a few words and part peacefully.}
{281}{}{Sounds like you don't care much for that place.}
{282}{}{You know old José - someone comes with good intentions, I answer the same. But those people? Cheat in trade, try to steal, throw sharp words. And believe me, they don't think much better of us. But, they envy us.}
{283}{}{}
{284}{}{}
{285}{}{}
{286}{}{Heh.}
{287}{}{(shakes his head sadly) Ay, amigo... the damned wasteland's been rough on you. Skin still holding? That's something. Don't you worry - we're still with you. Same blood, after all... well. At least we were.}
{1287}{}{(shakes his head sadly) Ay, amiga... the damned wasteland's been rough on you. Skin still holding? That's something. Don't you worry - we're still with you. Same blood, after all... well. At least we were.}
{288}{}{Thanks, José. I'll manage - even looking like this.}
{289}{}{Problems, smoothskin? I don't need your pity, so keep it to yourself.}
{290}{}{Ahh, so Grandma Adonsia's been whisperin' ghost stories in your ear, huh? Heh-heh. Forget it. Nothin' down there but rats and spoiled flour.}
{290}{}{What are you talking about? We store grain there. Ah, grandma Adonisia filled your head with those old tales, didn't she? Ha-ha, forget it, there's nothing there.}
{291}{}{Then how do you explain this jumpsuit and wrist computer?}
{292}{}{Hmm? Found them under the town hall, did you? Well, then talk to your padre. Jose knows nothing.}
{1292}{}{Hmm? Found them under the town hall, did you? Well, then talk to your padre. Jose knows nothing.}
{293}{}{Come on Uncle Jose, you know something.}
{294}{}{Hey, amigo, drop it! I'm just a trader with a bad leg, they don't share secrets with me. Yes, I know that your padre had a secret stash in the cellar. And that it held family heirlooms, but it's none of my business, you understand?}
{1294}{}{Hey, amiga, drop it! I'm just a trader with a bad leg, they don't share secrets with me. Yes, I know that your padre had a secret stash in the cellar. And that it held family heirlooms, but it's none of my business, you understand?}
{295}{}{I'd follow you anywhere, but with this bad leg and my age, I won't make it far. Don't be upset, you'll manage on your own. I believe in you. After all, we're family, right?}
{296}{}{Jose, you don't look too happy.}
{297}{}{Huh?}
{298}{}{Well, it's just... so much has happened... Ah, never mind, forget it.}
{299}{}{You're not happy, Jose. You can't be. People died, others were taken into slavery, the Villa is ruined... Stop pretending you're cheerful.}
{300}{}{(lip trembling) Amigo... Why do you say such things...}
{1300}{}{(lip trembling) Amiga... Why do you say such things...}
{301}{}{Go on... let it out.}
{302}{}{It's alright, Jose. Let yourself feel it. Don't keep it all bottled up...}
{303}{}{Thank you, Uncle Jose. That means a lot to me.}
{304}{}{Don't worry! Things'll work out!}
{305}{}{I hope so. Let's get back to my questions.}
{306}{}{I just wanted to say "thank you" for the support. It really means a lot, Uncle Jose.}
{307}{}{Hey, enough of this! I'm just a trader with a bad leg. The elders don't share their secrets with me.}
{308}{}{Alright. Let's change the subject.}

#Quests
{310}{}{Is there anything I can do before I leave?}
{311}{}{Want to help rebuild the Villa? We'll manage somehow, your task is more important.}
{312}{}{Anything else?}
{313}{}{There are some outsiders, marauders probably, lurking out on the plantations. It'd be good to drive them away.}
{314}{}{Anything else?}
{315}{}{Well, the raiders damaged the weather station. It needs repairs. There might be parts in Garage City.}
{316}{}{I'll see what I can do?}
{317}{}{}
{318}{}{The marauders on the plantations are no longer a problem.}
{319}{}{You did it! Things might have turned out bad, without your help. The Villa's lucky to have you.}
{320}{}{Goodbye.}
{321}{}{The weather station is all fixed up.}
{322}{}{Great news! I couldn't have fixed it without you. Thank you.}
{323}{}{Goodbye.}

#Gambling
{350}{}{Uncle Jose, I know you love gambling. Wanna play?}
{351}{}{Ay, no! Our people need savin' first. When they're back in Villa safe and sound, then I'll gladly rattle the dice with you.}
{352}{}{That's actually what I wanted to talk to you about.}
{353}{}{You're right. I shouldn't waste time.}
{354}{}{Well now, you've gone and killed the mood. Don't even feel like playin' anymore.}
{355}{}{Well, now that our people are back, I could use a bit of fun. Just remember, I won't be going easy on you.}
{356}{}{Excellent, get the board and set up the dice...}
{357}{}{Hmm, it might be better if we didn't play. Let's just chat instead.}
{358}{}{You know, now's not the best time. We'll do it later.}
{359}{}{You just beat one of the Villa's best players, and you've improved your skills.}
{360}{}{}
{361}{}{You lost. Well, it's not the first time, and it won't be the last.}
