{200}{}{Señor }
{1200}{}{Señorita }
{201}{}{! Don't be alarmed, this robot is merely a messenger. It has an important message for you.}
{202}{}{What message?}
{203}{}{"My friend, I've heard about your deeds in the Sonoran Desert. Whatever drives you, your skills are rare and valuable."}
{1203}{}{"My friend, I've heard about your deeds in the Sonoran Desert. Whatever drives you, your skills are rare and valuable."}
{204}{}{[Keep Listening]}
{205}{}{"Right now, history is being written in the ruins of San Diego. You belong there. The local ghouls don't trust humans - they're divided and vulnerable, and this could lead to disaster. They need a hero."}
{206}{}{[Keep Listening]}
{207}{}{"A caravan headed for the ghoul city is gathering on the outskirts of Inferno. The coordinates will be added to your Pip-Boy."}
{208}{}{[Keep Listening]}
{209}{}{"When you reach Old Town, stop by the junk shop and pick up an encrypted holodisk with further instructions. I'm counting on you. Good luck."}
{210}{}{[Listen to the message again]}
{211}{}{[End the message]}
{212}{}{What!?}

