{100}{}{You see Father Talius.}
{101}{}{You see a mutant in a worn-out shirt and hat. A cross hangs around his neck.}
{102}{}{You see Talius, a member of the Followers sect, standing before you.}
{103}{}{Give this to someone who truly deserves to wear it.}
{104}{}{Fernando stayed in town.}
{105}{}{Beatriz stayed in town.}

#First Meeting
{200}{}{Greetings brother. My name is Talius. I'm glad to see you in Dayglow. How might I assist you today?}
{1200}{}{Greetings sister. My name is Talius. I'm glad to see you in Dayglow. How might I assist you today?}
{201}{}{You're no brother of mine. Have you even looked in a mirror?}
{202}{}{I see that you are a little slow. I, too, was once of your intelligence. But, through the teachings of the Followers, I have been able to transcend my shortcomings.}
{203}{}{Doesn't your skull feel tight?}
{204}{}{In fact, on occasion, it does. I sometimes trim away extraneous brain tissue through a cranial aperture - oh, pardon me, I do tend to become engrossed. Would you like some brain help?}
{205}{}{Sorry, I just meant that you and I are quite different.}
{206}{}{Hmm, indeed. Perhaps you have a point. But, let us return to the matter at hand - do you desire any assistance?}
{207}{}{Uh, I'm just here to check this place out.}
{1207}{}{Uh, I'm just here to check this place out.}
{208}{}{Thanks for the warm welcome. It's surprising in a place like this.}
{209}{}{Ah, I understand. The ghouls here tend to harbor a natural wariness towards unmutated folk. They have endured many trials. But if you prove your good intentions, they may yet accept you.}
{210}{}{I hope so. But why are you so friendly?}
{211}{}{I was being sarcastic. I'm not looking to befriend freaks like you guys.}
{212}{}{I am saddened by your sentiment, yet I remain hopeful that in time, your opinion may soften. Do you need some brain help?}

{220}{}{Greetings, brother. How might I assist you today?}
{1220}{}{Greetings, sister. How might I assist you today?}
{221}{}{No, thanks. Sorry for bothering you.}
{222}{}{What knowledge might you seek?}
{223}{}{Nothing more. Thanks for your time.}
{224}{}{A lot, but you wouldn't know about it. Bye.}
{225}{}{Indeed, there are great changes afoot in Dayglow, changes that may well ripple through the world beyond. It is both exhilarating and daunting. Now then, shall I assist you in some way?}

#About the Followers
{230}{}{This humble establishment serves as a sanctuary for the Followers of the Apocalypse. Here, I endeavor to impart our teachings to the ghouls of Dayglow.}
{231}{}{Sorry to interrupt. But I want to change the subject.}
{232}{}{I know some Followers. We met in Casa Nueva.}
{233}{}{Then you are acquainted with our mission. The Followers of the Apocalypse are, at their core, a benevolent group. We seek to foster peace within this scarred land.}
{234}{}{Where are the other Followers?}
{235}{}{Alas, I am the sole representative in these irradiated ruins. Only those altered by radiation can thrive here. Most of our brethren are, shall we say, of more conventional constitution, and reside in other settlements.}
{236}{}{How did you become a Follower if you're... well... a ghoul?}
{237}{}{Would you believe me if I said I am of a rather unique disposition? The Followers preserved me from a monstrous transformation while I lay incapacitated under the effects of a mutagen. They bestowed upon me their wisdom, for which I am eternally grateful.}
{238}{}{I see.}
{239}{}{What are these teachings?}
{240}{}{The Followers of the Apocalypse strive for peace in this desolate land. We advocate selflessness, non-violence, and the application of pre-war knowledge to uplift lives. Above all, we seek to prevent humanity from repeating the tragic errors of 2077.}
{241}{}{Tell me about your... faith.}
{242}{}{Your words about the Followers moved me deeply. I want to make a donation.}
{243}{}{Such generosity is most commendable. Pray, how many hubbucks might you be inclined to offer in service of our cause?}
{244}{}{Right now, none. I mean, I'll do it in the future.}
{245}{}{100 caps.}
{246}{}{200 caps.}
{247}{}{300 caps.}
{248}{}{400 caps.}
{249}{}{500 caps.}
{250}{}{Your generosity is noted, my friend.}
{251}{}{You're welcome.}
{252}{}{I feel good about that. But I'd like to talk to you more, Father Talius.}

#About Himself
{260}{}{Remind me, what's your name?}
{261}{}{Talius is my name.}
{262}{}{Alright, Talius.}
{263}{}{Where are you from, Talius?}
{264}{}{My origin lies far from here, in a place once known as Vault 13.}
{265}{}{I know about several vaults, but this is the first I've heard about Vault 13.}
{266}{}{Never heard of such a place.}
{1266}{}{Never heard of such a place.}
{267}{}{Understandable. There were many vaults constructed, and numerous have ceased to function.}
{268}{}{Did the other ghouls come from Vault 13 too?}
{269}{}{Got it. Let's change the subject.}
{270}{}{Most of the inhabitants here originated from Vault 12, beneath the city of Necropolis. I used to journey there in search of components for my vault. It was during one such expedition that I mutated.}
{271}{}{So, you're not a ghoul?}
{272}{}{Sad story. We should change the subject.}
{273}{}{Indeed, I am... altered. The Master's scientists sought to fashion me into a super mutant, but the process went awry.}
{274}{}{No, I am a mutant. The Master's experiments were intended to reshape me, but something within me resisted. I dare say you may have experienced something akin to this.}
{275}{}{That sounds pretty awful. Sorry I can't help you.}
{1275}{}{That's really awful. I wish I could help you.}
{276}{}{Thank you for your kind words. You know, I used to be an atheist. But after fate made me immortal, it's hard not to believe there's some sort of plan. Maybe this is all just a... test?}
{277}{}{I suppose it was tough, but nothing can be done about it now.}
{276}{}{Your compassion is greatly appreciated. You know, I once denied the existence of any higher power. But with my transformation into something enduring, I find myself pondering the notion of a greater design. Perhaps this life is but a... test?}
{279}{}{Shall we talk about something else?}
{280}{}{Good luck, Father Talius.}

{290}{}{I remember you mentioned vaults. Are there any in Dayglow?}
{291}{}{Perhaps. Why do you ask?}
{292}{}{Just logical reasoning. Don't mind it.}
{293}{}{Well, I came across this flask. I think it's probably from a vault.}
{294}{}{A flask from Vault 24... A relic from an era long past. Where precisely did you obtain it?}
{295}{}{Found it on a skeleton in a blue jumpsuit. I think the skeleton had been lying there for many decades.}
{296}{}{Ah, it might have belonged to one of the scouts the Followers dispatched for reconnaissance. Many noble souls perished in those austere times.}
{297}{}{Did the Followers also come out of a vault?}
{298}{}{Those who were the forefathers of the Followers did. The others were born after leaving the Vault or joined from the outside.}
{299}{}{What happened to this vault?}
{300}{}{I am not privy to the entirety of its tale. The vault now lies abandoned. The Followers retrieved all that held value, and now fearsome creatures haunt its confines. I would strongly advise against venturing there.}
{301}{}{I'll take the risk anyway. At least for the sake of history. Can you show me the way?}
{302}{}{The Vault can wait. I don't need any dangerous adventures right now.}
{303}{}{You'll find it in the heart of Otay Park. It's challenging to locate, so allow me to mark the route on your Pip-Boy.}
{304}{}{[Head there right now.]}
{305}{}{Not now. I need to prepare for the journey.}
{306}{}{I'll take the risk anyway. Maybe not everything has been taken from there yet? Show me the way.}
{307}{}{Isn't it a touch presumptuous to intrude upon another's domain, demanding and seizing as you please? All here belongs to the ghouls, many of whom are disinclined to tolerate your presence. I shall guide you to the vault, but I request a generous donation in return - shall we say, 1000 caps?}
{308}{}{I can't afford that much. Let's put this on hold.}
{309}{}{Alright. Here's 1000 caps. Show me where it is.}
{310}{}{Show me the way, and you'll live, jerk. That's the best I can offer you.}
{311}{}{I need to get back to Vault 24. Right now.}
{312}{}{Help me get into Vault 24.}

{320}{}{Can I help your people with anything?}
{321}{}{Our souls are in need of salvation, though we manage the rest. Alas, we recently received word of another ghoul overtaken by madness: our dear friend Gonzo has lost his sanity and fled to the ruins of Chula Vista. In his state, he poses a threat and must be subdued.}
{322}{}{Can it be done without killing him?}
{323}{}{Are you asking me to KILL him?}
{324}{}{(sigh) Would any ghoul willingly turn on a fellow ghoul? I rather think not. Many would denounce such an action. Yet the progression to total madness is inevitable; it can be delayed but not reversed. In such times, we must mitigate harm wherever possible.}
{325}{}{Just chop off his head - it's that simple.}
{326}{}{I've seen this kind of madness in Inferno before. Only death can stop it.}
{327}{}{You mustn't treat life so frivolously. Should there be no other recourse, we shall indeed send Gonzo to his ancestors. But remember, he is our kin. We ghouls have coexisted with him for many years in Necropolis. Show a modicum of compassion, if you please.}
{328}{}{Is there any way to temporarily restore his sanity?}
{329}{}{In some cases, medication can help; in others, memories of bygone days. Or perhaps nothing will suffice. But any solution is only temporary.}
{330}{}{I'll think of something.}
{331}{}{God be with you.}
{332}{}{Goodbye for now.}
{333}{}{I have a few more questions.}
{334}{}{If you can't even deal with your own kind, I certainly won't be able to. Sorry.}
{335}{}{I understand. In that case, it would be best to avoid Gonzo should you encounter him in the ruins.}
{336}{}{Remind me where to find Gonzo?}
{337}{}{He was last observed in the abandoned shopping district within the ruins of Chula Vista, to the north.}
{338}{}{Got it.}
{339}{}{}
{340}{}{Gonzo is dead. He left me no choice.}
{341}{}{Then his soul shall finally rest. (sigh) Very well. I harbor no ill will toward you. I can only blame myself for failing to aid the lost. It appears that madness is a fate all ghouls must eventually face.}
{342}{}{Don't blame yourself. Life goes on.}
{343}{}{He was a danger to society. You know that yourself.}
{344}{}{Thank you for your kind sentiments.}
{345}{}{Let's change the subject.}
{346}{}{Now Gonzo is no longer a threat, right?}
{347}{}{Indeed. The deranged Gonzo is now securely confined. It seems that all ghouls are fated to succumb to madness eventually. There is no remedy for it; all we can do is ensure no further harm is caused. If ever you find yourself in need of solace for either soul or body, do visit me.}
{348}{}{Just don't lock *me* up!}
{349}{}{I'll keep that in mind.}

#Healing
{350}{}{Do you provide healing?}
{351}{}{The Followers imparted to me the essentials of medical practice. However, medications here are scarce and exorbitantly priced. What ails you?}
{352}{}{I need treatment.}
{353}{}{Nothing. Just curious.}
{354}{}{ caps]}
{355}{}{[Heal wounds for }
{356}{}{[Heal serious injuries for }
{357}{}{[Heal radiation sickness for }
{358}{}{[Heal poisoning for }
{359}{}{You are now in satisfactory health.}
{360}{}{Thank you.}
{361}{}{[Heal Gomer for }
{362}{}{He is fine.}


{380}{}{I have a strange situation here, Doc. It's Donovan. He's dead.}
{381}{}{Really?}
{382}{}{But his friends literally can't believe it. It's bizarre.}
{383}{}{Dead, you say? Donovan? Surely, you must be mistaken - of course he's alive!}
{384}{}{Are you out of your mind too? Is everyone taking crazy pills around here?}
{385}{}{Look. He's not breathing. Half of his body is missing. He is dead.}
{386}{}{Very well, bring him here. I shall see to him. However...}
{387}{}{However what?}
{388}{}{I fear I require certain supplies to assist him. Do you know the location of the hospital? I need three vials of biogel from there. It's likely the only place such items can still be found.}
{389}{}{You really are crazy. I'm outta here.}
{390}{}{Well, you know best I guess. I'll try to get the biogel.}
{391}{}{I have the biogel right here.}
{392}{}{Splendid! We should waste no time - let us commence the procedure at once.}
{393}{}{Uh, okay...}
{394}{}{(The operation extends over several hours behind closed doors. You wait outside. At last, Talius emerges and solemnly proclaims: "Donovan shall live!")}
{395}{}{Wow, Talius, you really work miracles!}
{396}{}{Yeah, right. I don't believe it. Well, goodbye, 'doctor' Talius.}
{1396}{}{Yeah, right. I don't believe it. Well, goodbye, 'doctor' Talius.}
{397}{}{About Donovan.}

