{110}{}{This howitzer is damaged. However, it could be repaired with a few replacement parts.}
{111}{}{This howitzer might hypothetically fire. Maybe - once.}
{112}{}{The howitzer fires a shot, after which it completely falls apart.}
{113}{}{This howitzer is permanently out of order. Find another one.}
{114}{}{The howitzer is loaded.}
{115}{}{The howitzer has been repaired.}
{116}{}{You have removed some parts from this howitzer.}