{110}{}{This skill is not applicable here.}
{111}{}{Digging a hole during combat? Not gonna happen.}
{112}{}{With that strength, you can't even lift a shovel.}
{114}{}{It'll take a tool to dig through this.}
{115}{}{Someone hastily buried a dog here. They were clearly in a rush.}
{116}{}{This hole can't be filled that easily.}
{117}{}{While digging, the grave suddenly collapses, dragging you into the underground voids.}
{118}{}{What the fuck...}
{119}{}{Yikes!}
{120}{}{The hole is pretty deep.}

#Companion lines
{130}{}{Do we really have to do this?}
{131}{}{I've... been a grave robber myself, in a way. You know how it is.}
{132}{}{I doubt there's anything worth finding down there.}

{140}{}{Why are you doing this?}
{141}{}{You really think this is right?}
{142}{}{I don't think the Rangers would approve.}

{150}{}{You think there's something valuable in there?}
{151}{}{I don't really care - just make sure no one sees us.}
{152}{}{The Mexicans wouldn't forgive us for this.}

{160}{}{My God! Have you no shame at all?}
{161}{}{Don't tell me you're doing this "for science."}
{162}{}{That's disgusting.}

{170}{}{Jeezuz! How did I ever get mixed up with you?}
{171}{}{Grave robbing? The Order doesn't look kindly on that.}

{180}{}{I'll pretend I didn't see that.}

{190}{}{Right. They don't need it anymore - we still might.}
{191}{}{Well? What's in there?}
{192}{}{Don't sweat it. I'm not judging you. I used to do the same.}
