{100}{}{You see Tin-Tan.}
{101}{}{You see a raggedly clad, skinny fisherman with a thin mustache and crooked teeth.}
{102}{}{Don't come near me! You, uh, smell bad.}
{103}{}{Damn it, and it's all because of that little sucker...}

{200}{}{Ay-ay-ay, what a small fish! Well, why do I need you? Swim back to the sea, become big and then come back. There you go! See you little fish!}
{201}{}{Uh, I think I'm disturbing you.}
{202}{}{I get sick in the waves and then fall asleep. Sometimes I dream about something cool, like I'm dancing surrounded by beautiful girls!}
{203}{}{Uh, I see.}
{204}{}{Seems like we have you to thank for this oil thing. «Thank you very much! Cheers!»}
{205}{}{«It was nothing.»}
{206}{}{You're welcome.}
{207}{}{Seems like we have you to thank for this oil thing. Muchas gracias! Viva!}


{210}{}{Hello. I'm Tin-Tan. How are you?}
{211}{}{Bye.}

{220}{}{Have you been to the platform?}
{221}{}{In my dreams I go anywhere and in anyone's arms!}
{222}{}{Um, I see.}
{223}{}{Tin-Tan - what a strange name?}
{224}{}{I used to be... drum roll... Topillo! And then I became Tin-Tan. Actually my name is... boom boom boom... German Henaro Cipriano Gomez Valdes-y-Castillo! But it's a little... inconvenient, you know?}
{225}{}{Ah, now it's clear.}
{226}{}{I'd say it's a nickname, idiot.}

{230}{}{I have bad news. Johnny, your relative, has died.}
{231}{}{Ooh, how did this happen?!}
{232}{}{Someone killed him. Strangled him with this rope.}
{233}{}{What is this? Hey, Ruiz sells this rope! Ooh, did Ruiz do this? It can't be!}
{234}{}{Well, I'll have to ask Ruiz about it then.}
{235}{}{But this rope is new, and you were the last one to buy it.}
{236}{}{Why would I do this? I'm his uncle! Oh, please, leave me be and let me cry! Ooh, poor Johnny!}
{237}{}{That's true - why? We need to find more evidence.}
{238}{}{German Henaro Cipriano Gomez Valdes-y-Castillo is dead. Who are you?}
{239}{}{I don't know what you're talking about!}
{240}{}{The real German Valdes died on the stagecoach. You took his documents and impersonated him. Isn't that right?}
{241}{}{(looks around) Listen, you, the jokes are over. Listen to me, motherfucker. Keep your mouth shut. Or you'll end up like that kid. Got it?}
{242}{}{That sounds like a confession. It's time to take your punishment, you bitch!}
{243}{}{I won't say a word to anyone. I promise.}
{244}{}{Really? Well, you probably know better. Sorry to trouble you.}
