{100}{}{You see Sid.}
{101}{}{You see a business-like man in walking clothes.}
{102}{}{It was great luck to meet you. Thanks for your help along the way.}
{103}{}{The path is clear.}
{104}{}{There is no one else to pay for the protection of the caravan.}
{105}{}{Despicable traitor!}
{106}{}{Thanks to intelligence, you were able to pass undetected.}
{107}{}{ died. Now there is no one to pay you to guard the caravan.}

#Before receiving the quest
{200}{}{Hello, wanderer. I'm Sid, the merchant. Looks like we're both stuck in this hole, right?}
{1200}{}{Greetings, lady. I'm Sid, the merchant. Looks like we're both stuck in this hole, right?}
{201}{}{I had business here. But I'll be heading out soon.}
{202}{}{Business, you say? OK. But even if you have good relations with the inhabitants of the pueblo, the tribes in the wasteland are not so friendly. Do you think you can safely pass through their lands?}
{203}{}{Do you have any suggestions?}
{204}{}{You got that right. Can't wait to see a real city for once, like the one everyone's always talking about.}
{205}{}{It only takes a few days to get to Phoenix. But it's a dangerous road. It's better to travel in a group.}
{206}{}{Do you have any group in mind?}
{207}{}{Yep. I'm preparing my caravan to return to Phoenix. I have few people, and the road has become real rough thanks to the showdown with the missionaries. I'm a little worried that some of the savages might ambush us as soon as we leave the pueblo. I need more security. I'll pay 500 caps for the trip to Phoenix. So, will ya' come with us?}
{208}{}{I'll think about it.}
{209}{}{Sign me up. I'm in.}
{210}{}{What is your caravan carrying?}
{211}{}{All kinds of savage utensils, leather goods, dried meat. I was also lucky to trade for several brahmin from Genaro. A living Brahmin is worth a fortune in the city.}
{212}{}{Are we going to have to fight on the road?}
{213}{}{Possibly.}

{220}{}{So, will ya' come with us?}
{221}{}{I still haven't decided. For now - plan without me.}
{1221}{}{I still haven't decided. For now - plan without me.}
{222}{}{Sign me up. I'm in.}

{230}{}{Glad to have ya' on the team. Get your things in order, then meet back here.}
{231}{}{Okay.}
{232}{}{I can move out now.}

#After receiving the quest
{250}{}{Damn, these savages won't leave us alone! We need to get rid of them somehow.}
{251}{}{These radscorpions are gonna kill the brahmin! Can't let that happen!}
{252}{}{Ambush! Everyone tighten up! Protect the wagons!}
{253}{}{I see.}
{254}{}{The coast is clear. Is everyone okay? Then let's get moving.}
{255}{}{Give me another minute, then we can move out.}
{256}{}{Okay, I'm ready to go.}
{257}{}{Damn it! We've lost all the brahmin. We'll have to ditch part of the load and carry the rest ourselves. Looks like I won't be earning anything this trip. Might even take a loss. Shit.}
{258}{}{But WE survived. Let's move on.}
{259}{}{Wait a little, I need to get ready.}

{260}{}{Thanks for your help. It's been good doing business with you. Here's the 500 caps for the work, as promised. But I doubt I'll return to San Brahmin for another couple of years. Gotta wait until the dust settles there. Well, you understand.}
{261}{}{Good luck, Sid.}
{262}{}{Thanks for your help. But because of the loss of the brahmin and most of the cargo, I won't be able to pay ya' the full price. Here's }
{263}{}{ caps for your work. And I most likely won't return to San Brahmin for another couple of years, until the dust settles there. Well, you understand.}
{264}{}{Listen, maybe we should scout a route through those ruins?}
{265}{}{No, we're not making good time. And we don't have enough supplies or patience. Time to push straight on.}
{266}{}{Hey, let's go through the ruins up ahead. It'll take more time, but we'll be out of the open.}
{267}{}{I was hoping to get to the city by sunset, but you've got a point. Scout ahead and we'll catch up.}
{268}{}{Alright, I'm on it.}
{269}{}{Not yet, I need another minute.}
{270}{}{It could be dangerous up ahead too. I could do some scouting.}
{271}{}{You wanna go die alone? Don't be stupid. Together it'll be easier for us to make it through.}
{272}{}{There could be more trouble up ahead too. I'll do some scouting and assess the situation.}
{273}{}{Be careful. I already have too few people. Losing you would be rough.}
{274}{}{I don't plan on dying. Wait here for my all clear...}
{275}{}{Yeah, I guess I'd be an easy target alone. Let's stick together.}
{276}{}{I need to get ready. Wait a minute.}
