{101}{}{You see a brahmin herder.}
{102}{}{This is one of the local herders. His face seems familiar to you.}

{200}{}{Well, look who wind drag in! I know this face. You are scoundrel who try to take our brahmin near Garage City.}
{201}{}{Yeah, but it all ended okay, right? You're still breathing, aren't you?}
{202}{}{Hmm... You talk down those raiders? That does not change truth. I do not trust you more than I can spit. I hope elders send you out of pueblo soon.}
{203}{}{Oh, come on...}
{204}{}{Don't hold your breath.}
{205}{}{I don't know what you're talking about.}
{206}{}{Is that so? Well... those raiders' faces fade from my mind. Fine. I give you chance, stranger.}
{207}{}{Thanks. Believe me, we've got no reason to be enemies.}
{208}{}{Your puny threats don't scare me.}
{209}{}{What are you talking about? It wasn't me...}
{210}{}{Speak not your lies. I know that face, you thieving snake!}
{211}{}{Alright, that was a mistake. We thought the brahmin were wild...}
{212}{}{Wild, huh? That is your truth? It is outsiders like you that Mangas and others speak against. I hope they drive you out soon, you thief. If not, I might lose my temper!}
{213}{}{So, what now?}
{214}{}{I tell all what you really are. Do not think you walk free easy, thief. I hope they drive you out soon. If not, I cannot promise to hold back!}
{215}{}{See ya, buddy.}

{220}{}{Get lost, you weed.}
{221}{}{Hey. You have done much good for tribe. Sorry, I judged you wrong.}
{222}{}{Goodbye.}
