{100}{}{You see a herder.}
{101}{}{You see a man with long black hair.}
{102}{}{These damn mushrooms are stronger than I thought...}

{200}{}{What do you want, stranger?}
{1200}{}{What do you want, stranger?}
{201}{}{Leave me, pale-face.}
{1201}{}{Leave me, pale-face.}
{202}{}{Whoa, why so hostile?}
{203}{}{Pretend you do not understand. I need nothing from you. Time flows like sand through fingers. I leave soon.}
{204}{}{Where are you headed?}
{205}{}{My kin prepares to cross desert. Must be ready before dust storms come. But damn cart is broken.}
{206}{}{Is that really a problem?}
{207}{}{Once, we could trade or ask pale-face for help. Now you wage war on us. No one to fix this cart but me, and I can nott.}
{208}{}{I can help.}
{209}{}{I do not want help from strangers.}
{210}{}{Let me show you, not all strangers are the same.}
{211}{}{You will help? Hmm, fine. But I have nothing to give in return.}
{212}{}{No problem. I'll do it.}
{213}{}{Nothing at all? Then I maybe I'll do nothing.}
{214}{}{I'll fix the cart, but it's gonna cost you. Parts aren't free.}
{215}{}{Always about trade, you pale-faces. I have no coins. But if you fix it, I give you dried meat.}
{216}{}{I'll think about it.}
{217}{}{You'll just give me bad meat. Fix it yourself.}

{220}{}{What do you want, stranger?}
{1220}{}{What do you want, stranger?}
{221}{}{Leave me, pale-face.}
{1221}{}{Leave me, pale-face.}
{222}{}{Peace to your home.}
{223}{}{Goodbye.}

{230}{}{Your cart's fixed.}
{231}{}{You did it! Pale-faces caused so much harm, never thought one would help. Peace seems so far away.}
{1231}{}{You did it! Pale-faces caused so much harm, never thought one would help. Peace seems so far away.}
{232}{}{Nothing for my work?}
{233}{}{(sigh) Knew I could not trust you. Just like the rest, you think only of self. That is difference between us.}
{234}{}{Give it a rest.}
{235}{}{Isn't it fair to get something for my work?}
{236}{}{Fine, here is some jerky. But do not ask for more. I need to prepare for journey.}
{237}{}{Fair enough.}
{238}{}{I want nothing in return. I help for peace.}
{239}{}{First time I have seen selfless pale-face. Thank you. May the Brahmin guide you in your time of need.}

{250}{}{What's so hard about fixing the cart?}
{251}{}{Our tribe works leather, not carts. We used to ask pale-faces for this in trade. Now, there is no one to ask.}
{252}{}{I see.}
{253}{}{Why take your whole family into the wasteland?}
{254}{}{We roam the Sonoran Desert. In hard seasons, the tribe gathers here. Stay put, we starve. Brahmin need grass, grass needs time. Not enough water here for all.}
{255}{}{I understand.}

{260}{}{How do you feel about allying with outsiders?}
{261}{}{Chase two mole rats, you rip your pants. Can't look west and east at once.}
{262}{}{I think I get it...}
{263}{}{We must stay true to our ways. If we cannot, someone stronger will decide our fate. They will become our herder and we their herd.}
{264}{}{Okay, now I get it..}
