{100}{}{You see Hilario.}
{101}{}{You see a strong old man in magnificent religious attire, at least by local standards.}
{102}{}{You have no idea what you've done.}
{1102}{}{You have no idea what you've done.}
{103}{}{(}
{104}{}{/3) of the villagers have been talked to about the holiday.}

{110}{}{}

# Phrases from the opening cutscene
{120}{}{Brothers and sisters! Today is an important day for us. This is the Day of Life. Today we honor Lucia.}
{121}{}{She will be our 'queen' for the day, a day when we proudly proclaim: yes, we are still alive. We made it through another day.}
{122}{}{Many were not so fortunate, but we have been. Give thanks for this blessing to our saint, who protect us from wild beasts and raiders...}
{123}{}{And just... Just... Oh, uh...}
{124}{}{Lucia, today is your big day.}
{125}{}{Go to the church and complete the ceremony. You know what to do. And we will pray.}

# First dialogue
{200}{}{(At the sight of you, the crowd falls silent and moves aside; a tense pause follows) Uh... uh... It seems we have guests... What a surprise!}
{201}{}{I was just passing by and heard the sounds of your... festival? What's going on here?}
{1201}{}{I was just passing by and heard the sounds of your... festival? What's going on here?}
{202}{}{What's going on? Well, gringo, we celebrate our saint's day. You are at the Day of Life celebration! Please, enjoy the celebration and make yourself at home. We welcome everyone... who comes with good intentions.}
{203}{}{This is the first time in my journey that I've seen such a joyful place. I'll be glad to join your festivities.}
{1203}{}{This is the first time in my journey that I've seen such a joyful place. I'll be glad to join your festivities.}
{204}{}{Most friendly people I've come across tried to trick me. I hope you're an exception.}
{205}{}{Well then. Bienvenido, gringo. If you have any questions, please contact me immediately. My name is Hilario Lopez Andrade. I am the headman of the village and also the chief priest. So! Why is everyone quiet? Let's continue, brothers and sisters!}
{206}{}{Thanks for your hospitality.}
{207}{}{Okay, I'll stick around a while.}
{208}{}{}
{209}{}{}
{210}{}{So, amigo, you probably have a lot of questions. I would also like to find out more about you, but unfortunately I have my hands full at the moment. Someone stole the crown for our ceremony. And we can't find it. You can't have a coronation without a crown, that would go against our traditions.}
{1210}{}{So, amiga, you probably have a lot of questions. I would also like to find out more about you, but unfortunately I have my hands full at the moment. Someone stole the crown for our ceremony. And we can't find it. You can't have a coronation without a crown, that would go against our traditions.}
{211}{}{I see you have no time to talk right now. I'll come back later.}
{212}{}{Then I'll try to find this crown.}
{213}{}{Is this the crown you're looking for?}
{214}{}{Yes, it is! Where did you find it?}
{215}{}{Well, it was just lying on the ground nearby.}
{216}{}{Are you saying it was just dropped by accident? Phew, I was worried that one of my flock had turned from the faith. That's reassuring. You know, we are the most peaceful settlement in all of God's world. No one has committed a crime here for years.}
{217}{}{That's great.}
{218}{}{Really?}
{219}{}{It was taken by a teenager. I don't know why he did it.}
{220}{}{Oh, I guess... Simple passion, hot blood in a young body. No need to pay it any heed.}
{221}{}{Okay, if you say so.}
{222}{}{Really?}
{223}{}{Now we can conclude the ceremony. You should know that we've been following this tradition for a long time and it's of great importance for this community. Every few months, we give the crown to one of our own as a reminder that we are all equal and that everyone can contribute. This time the honor fell to Lucia. Now, Lucia, come closer...}
{224}{}{[Watch the ceremony]}
{225}{}{Conducting the ceremony is so tiring. I'm not quite so young anymore. I need to lie down and rest.}
{226}{}{[Leave the headman alone]}
{227}{}{Why is the church locked?}
{228}{}{You shouldn't go in there. Even the residents aren't allowed to enter during the ceremony. For us, this is sacred ground, so please, don't go in there. We can't allow this place to be desecrated.}
{229}{}{Okay.}


{230}{}{What are you doing here, you damn gringo?! How dare you desecrate our sanctuary?!}
{231}{}{Don't worry, old man. The monster in the basement is dead. You have nothing to fear anymore.}
{232}{}{D-dead?! (confused) You... WHAT HAVE YOU DONE!!!}
{1232}{}{D-dead?! (confused) You... WHAT HAVE YOU DONE!!!}
{233}{}{Well, I killed the monster. He's dead. Dead. Sent back to hell. Understand?}
{1233}{}{Well, I killed the monster. He's dead. Dead. Sent back to hell. Understand?}
{234}{}{Why have you done this to us?! Do you even realize that El Diablo was our patron, our saint?}
{235}{}{You worshipped a monster? Seriously?}
{236}{}{He protected us from strangers and wild animals, he cleansed the community of lepers and the infirm, people banded together thanks to El Diablo. There hasn't even been theft among our people for many years. Without El Diablo, our entire way of life will fall. What fate await us now?}
{237}{}{Well, you'll probably come up with something. Eventually, your "saint" would've died anyway.}
{238}{}{Ah, maybe you're worried about your power, head boy? Now it'll be more difficult for you to unite the people with fear, and rule them. That's for sure.}
{239}{}{I see right through you, gringo. If... when you die, the world will be better off. And I won't permit you to leave this church.}
{240}{}{Try to stop me, old man.}
{241}{}{You're making a big mistake...}
{242}{}{That's enough, gringo. Leave and never come back.}
{243}{}{You'd be wise not to threaten me, old man. Believe me, it's not in your best interest.}
{244}{}{My business here is truly finished. Goodbye, headman.}
{245}{}{After everything you've heard and seen, it's not enough to execute you.}
{246}{}{Don't you dare come back! Do you hear? Leave!}
{247}{}{Yeah, yeah, whatever you say, stupid old man.}
{248}{}{Why are you still here?}
{249}{}{I'm already on my way. Just, uh, forgot my things. Goodbye.}
{1249}{}{I'm already on my way. I just, uh, forgot my things. Goodbye.}
{250}{}{The people of Santa Ana want you gone. Don't you get it? Your actions have turned them against you.}
{251}{}{For fifteen years, I protected these people. And this is my reward! Now that El Diablo is gone, they blame me for everything. Do you know the price I paid? The torment I endured in those early years? But I did what I was chosen to do -- I saved them. And now you say it was all wrong? To hell with your opinion, gringo!}
{252}{}{Seems like you can't be convinced. It'll be better if you just die!}
{253}{}{As you wish. This whole business is your affair now. Bye, Headman.}
{254}{}{You don't belong in Santa Ana anymore. The entire population is against you now. Time for you to leave.}
{255}{}{I've been looking after these people for 15 years and this is what I get?! Now that El Diablo is gone, they turn their back on me. Do you have any idea what sacrifices I had to make? All that suffering in those first years? I did what I was chosen to do. I saved them! At least it wasn't all for nothing, so I'll go with a clear conscience. If exile is the price for the peace of my people, so be it. I'll leave.}
{256}{}{I didn't expect you to agree. Goodbye, old man.}
{257}{}{I'll help you find a new place to live... in hell!}

{258}{}{Any other questions my friend?}

