{100}{}{You see Count Bustos.}
{101}{}{You see a man in a respectable but shabby suit. His gray temples seem to hint at a difficult past.}
{102}{}{Thanks for your help. See you at my mansion.}
{103}{}{Go back to my mansion. We'll talk there.}

#First dialogue
{200}{}{(As you approach the bar building, you find a crowd of armed people; the mayor is actively discussing something with them.)}
{201}{}{Ahem.}
{202}{}{Oh, it's you... Come closer. We need all the help we can get right now.}
{203}{}{What's going on here?}
{204}{}{There are goddamn highwaymen in the bar. They grabbed my daughter and are demanding ransom. Negotiating with them ain't an option. I'll pay any amount of caps to the one who saves Christina.}
{205}{}{Ransom huh? That's not good at all.}
{206}{}{What does that have to do with me?}

#Re-dialogue
{210}{}{Do you have any suggestions?}
{211}{}{Hey, I value my life, don't count on me.}
{212}{}{Then stand aside and don't interfere. Maybe the sight of a large crowd will scare these scum shitless.}
{213}{}{That makes sense. I'll watch from the outside.}
{214}{}{Let me talk to them. Maybe I can convince them to leave.}
{215}{}{Talk to those highway bastards? This is a goddamn suicide mission. And I won't save your ass if you get taken hostage too.}
{216}{}{Then I'll just watch from the sidelines how it all ends. Good luck.}
{217}{}{Don't worry about me. I can negotiate.}
{218}{}{I propose a frontal attack. No point in talking to those assholes.}
{219}{}{Looks like I have no choice... Who's ready to do this? I'm gonna pay anyone who helps save my daughter.}
{220}{}{Wait, let's not rush. Let me assess the situation.}
{221}{}{I'm in. Let's give those bastards hell!}
{222}{}{Then lets go!}
{223}{}{Yeah!}
{224}{}{Why not pay them a ransom?}
{225}{}{They want too much. The city will be ruined. And further...}
{226}{}{More?}
{227}{}{They want to trade Christina for me to clear their path to the wasteland. I can't trust them.}
{228}{}{Maybe you could sneak in with the road armor your wearing... Not a bad idea, but...No. they'll spot you quickly. Any ideas?}
{229}{}{I see...}

{250}{}{As you can see, your daughter is safe.}
{251}{}{My God, Christina... Are you alright? I'll make those bastards pay for what they did!}
{252}{}{Are you going to attack the bar?}
{253}{}{Of course. If other highwaymen find out about this, my daughter will be kidnapped every goddamn day. We need to end them now.}
{254}{}{Can't argue with that. Criminals should be punished. When do we start the attack?}
{255}{}{Don't count me in. I'm not gonna take part in this.}
{256}{}{Your daughter is dead. I saw it with my own eyes.}
{1256}{}{Your daughter is dead. I saw it with my own eyes.}
{257}{}{No! Noooo!}
{258}{}{I'm so sorry.}
{259}{}{(furious) Those... bastards will pay dearly. Listen EVERYONE! I'll pay for the head of every son of a bitch in the bar!}
{260}{}{Great, I'm in.}
{261}{}{Without me. I don't want to get mixed up in this fight.}
{262}{}{Bring my daughter. Immediately.}
{263}{}{No time to talk now. Those highwaymen won't give up so easily.}
{264}{}{They deserve to be punished. But it's too dangerous to attack while they're at the bar. Let them go, at least you'll spare some of your people.}
{265}{}{I don't want another massacre in my city either. We already have a bloody enough reputation. Let them go. We're heading back to the mansion.}
{266}{}{Good decision, Mr. Mayor...}
{267}{}{That doesn't make much sense. They're already leaving the city.}
{268}{}{You have incredible powers of persuasion. Even a little suspicious. Well, let them leave. And we return to my mansion.}
{269}{}{Good decision, Mr. Mayor...}
{270}{}{The goal is clear...}
{271}{}{Don't count on me. I'm not gonna shed anyone's blood.}
{272}{}{The highwaymen won't go anywhere until you fulfill their demands.}
{273}{}{So there's no choice. They'll all have to be taken out. Can you get my daughter out of the bar without anyone noticing?}
{274}{}{Give me time, I'll try to get her out without anyone noticing.}
{275}{}{That's impossible. I propose a frontal attack right now!}
{276}{}{Relax, Count. All the highwaymen in the bar are already dead.}
{277}{}{Amazing! You are quite the problem solver.}
{278}{}{Then you're in luck.}

{280}{}{}
{281}{}{[Eavesdrop on negotiations]}
{282}{}{Bustos: What's the word, John?}
{283}{}{[Listen]}
{284}{}{Sullivan: They say there are four of them. Your daughter's a hostage. No demands yet. We need to send someone to talk.}
{285}{}{[Listen]}
{286}{}{Bustos: Gr-rm... They knew exactly how to get to her and who to target... Damn it, if word spreads, this'll keep happening.}
{287}{}{[Listen]}
{288}{}{Sullivan: Should've watched her. Mayor of a city, can't keep tabs on his own kid.}
{289}{}{[Listen]}
{290}{}{Bustos: Shut your trap, John! You better figure out how to get my girl back.}
{291}{}{[Listen]}
{292}{}{Sullivan: Don't you lecture me, Bustos. This isn't the time for tequila-soaked memories. You better have a pile of caps ready for ransom. And move it... (noticing you) Eh? What do you want?}
{293}{}{What's going on here?}

