{100}{}{You see a guard.}
{101}{}{You see a caravan guard, taking a moment to rest after a grueling journey.}

{110}{}{Hey there. How's the road treating you?}
{111}{}{Sorry, friend, but I need a breather.}
{112}{}{Got water here, at least. Rest of this place? Total dump.}
{113}{}{Casa Grande? Brutal as they come.}
{114}{}{Mayor's a tough nut, ain't he?}
{115}{}{You wanna chat with the boss.}
{116}{}{Phoenix to Two-Sun road's a damn rollercoaster.}
{117}{}{Highway's a minefield, thanks to those raiders.}
{118}{}{Best steer clear of 'em highwaymen.}
{119}{}{Just cash cows for the locals, that's all we are.}
