{100}{}{You see Christina.}
{101}{}{You see a girl with a sharp, eager look in her eyes. It seems like the easy life hasn't taught her much yet.}
{102}{}{You see a girl with a sorrowful look in her eyes. It seems that recent events have caused her to reflect deeply.}
{103}{}{Wow, how do you go to the toilet in that thing?}
{104}{}{Daddy... daddy... he's gone...}
{105}{}{Where did you get THIS? Hide it right away before anyone sees it. Dad's bodyguards shoot at any highwaymen on sight.}
{106}{}{What's going on? Where's my dad?}

{110}{}{Z-z-z...}
{111}{}{Hrr...}
{112}{}{...Daddy, it's too early...}
{113}{}{...I'm not dreaming...}
{114}{}{I'm... sleeping...}
{115}{}{...It's... a dream...}
{116}{}{Do you know what time it is?}
{117}{}{I'm sleepy.}
{118}{}{Don't disturb my sleep.}
{119}{}{Let me sleep.}

{120}{}{*Humming*}
{121}{}{Great day for pranks.}
{122}{}{Should I offer that new guy a game of poker?}
{123}{}{I need to ask daddy for more caps.}
{124}{}{It's okay, daddy will forgive me.}
{125}{}{Oh, how boring...}
{126}{}{What should I do?}
{127}{}{Water, caps. Caps, water. Can't they think of anything else?}
{128}{}{I wish I could see the neon lights of Phoenix again.}
{129}{}{It's getting really boring without the bar.}

{130}{}{Ah...}
{131}{}{*Sigh*}
{132}{}{Can't even play cards.}
{133}{}{Why did things turn out this way?}
{134}{}{I'm in a terrible story.}
{135}{}{I guess I won't be able to live like I used to.}
{136}{}{I don't understand how it could have turned out this way?}
{137}{}{Why have people become so angry?}
{138}{}{}
{139}{}{}

#Acquaintance
{200}{}{Oh, hi. New faces are always so interesting. My name is Christina. How long are you here for?}
{201}{}{Well, I...}
{202}{}{Come on, stay, it's good here. Although the city is, of course, boring. I'm just dying without gambling.}
{203}{}{Maybe I will, but I need to talk to the mayor now.}
{204}{}{As usual. OK go. He's probably in his office. Don't forget to knock before entering.}
{205}{}{Okay.}
{206}{}{I'm not in the mood for chit chat right now. I need to look around.}
{207}{}{Oh, sooo boring. OK Go. I hope you change your mind. Just don't hang around our house doing nothing. My daddy doesn't like it.}
{208}{}{Okay.}
{209}{}{I don't care what your daddy doesn't like.}

{210}{}{Oh, hi.}
{211}{}{Bye.}
{212}{}{I want to ask you about the city.}
{213}{}{Uh, look, I don't want to talk to you about boring stuff, okay? If you bother me, I'll call my bodyguards.}
{214}{}{Well, sit alone then, bitch. Now it's clear why no one's interested in you.}
{215}{}{Why is this whole town so unfriendly? Nevermind.}

#A game
{220}{}{Oh, hi. Do you want to play cards?}
{221}{}{Let's play. I bet 10 caps.}
{222}{}{Oh, hi. Do you want to play cards? I haven't played with anyone for so long, I'm dying of boredom.}
{223}{}{Sorry, but I don't gamble.}
{224}{}{I think you're just being stingy.}
{225}{}{Eh, I don't think so. Bye.}
{226}{}{A game for fun?}
{227}{}{What else! Without bets, the game becomes boring. When you know that you can lose your valuables, that's when real fun appears.}
{228}{}{Um, are you sure you have caps for the game?}
{229}{}{Of course! My daddy is the head of the city. Even if I lose, he'll give me more caps, he has a whole safe full of them.}
{230}{}{Sorry, but I can't waste time playing games right now. Maybe next time.}
{231}{}{What a shame. Okay, go and sort out your *important matters*.}
{232}{}{You know, it's time for me to relax a little. I'll bet 10 caps.}
{233}{}{Uh, bye.}
{234}{}{Okay, let's play. I bet 10 caps.}
{235}{}{Great. This is getting interesting...}
{236}{}{And he will do the right thing. Stop wasting his cash.}
{237}{}{See you later. Don't be bored.}
{238}{}{Oops. Seems I'm short on caps...}
{239}{}{[Start Game]}
{240}{}{Hurray! The card is gone!}
{241}{}{What? No, give me a change to get even.}
{242}{}{I gotta go.}
{243}{}{What? Why so early? We've only just begun. Well, okay. It's a little boring hanging out with you.}
{244}{}{Bye.}
{245}{}{What? I lost? Oh no, daddy's going to kill me... But... it's only 10 caps. I had fun killing time.}
{246}{}{Do you want to play some more?}
{247}{}{I gotta go.}
{248}{}{No, I'm afraid daddy won't give me any more money for gambling.}
{249}{}{Pfft. Sooo boring!}

#Questions
{300}{}{Who are you?}
{301}{}{Christina. Have you lost your memory?}
{302}{}{Are you the mayor's daughter?}
{303}{}{Well, yes. Aren't we alike? Look - we have the same nose and eyes.}
{304}{}{Exactly. And I have a feeling that I really need to meet with your father. Right now.}
{305}{}{That's great. You must know a lot about this city?}
{306}{}{What can you tell me about the city?}
{307}{}{Only that it's dead boring here. Although there are seasons when caravans flock to the city. Then a lot of interesting things happen.}
{308}{}{How interesting. But who are you?}
{309}{}{You're no help. I'll go look for someone who knows something.}
{310}{}{Why do you have such a big cemetery in the east?}
{311}{}{Why not? People die, they need to be buried somewhere. Isn't this the same as other places?}
{312}{}{I've never seen a larger graveyard.}
{313}{}{I don't know. I've been here my whole life and have only been to Phoenix once.}
{314}{}{I gotta go.}

{320}{}{Hello. How are you?}
{321}{}{I wanted to check on you. Keep up the good work. Bye.}
{322}{}{Want to play some cards?}
{323}{}{No, I don't play cards anymore. And no games at all.}
{324}{}{I understand. See you.}
{325}{}{So what did those highwaymen want from you?}
{326}{}{Revenge on my father for past atrocities. I didn't know all the terrible things he did in this city before.}
{327}{}{I see. Don't dwell on it too much.}

{330}{}{Oh, it's you... They killed my dad, you know?}
{331}{}{Yes, I saw it with my own eyes. How are you?}
{1331}{}{Yes, I saw it with my own eyes. How are you?}
{332}{}{I'm fine. Honestly. But, while I was hostage, the highwaymen were discussing my father. They said that he took power from the previous mayor, that he mercilessly killed half of the residents who opposed his power. I was too young to remember those days. Is it all really true?}
{333}{}{Stop being a naive fool, open your eyes - any power is violence. Your daddy is just an example this.}
{334}{}{I understand... Perhaps he was a tyrant and committed terrible crimes. But for me he was my... dad. He always tolerated my whims and gave me the best. How could things turn out this way?}
{335}{}{Welcome to the world of reality, baby. A world built on blood.}
{336}{}{Yes. I get it now. And I'm gonna do everything to prevent this from happening again.}
{337}{}{It's up to you. For me, my business in this city is finished. It's time to hit the road.}
{338}{}{Seems like it. I'm really sorry.}
{339}{}{At least he loved you. This means that deep down he wasn't a tyrant. It's just the way things turned out.}
{340}{}{Wait. You probably need some caps for the trip. Here, take it. These are what's left of my pocket caps. You need them more now.}
{341}{}{Thanks. And goodbye.}
{342}{}{Wait. You probably need some caps for the trip. Here, take these. These are my pocket caps. And all those that you lost to me at cards. You need them more now.}
{1342}{}{Wait. You probably need some caps for the trip. Here, take these. These are my pocket caps. And all those that you lost to me at cards. You need them more now.}
{343}{}{Good luck to you. And it's time for me to head out on a long journey.}
{344}{}{Goodbye, stranger.}
{345}{}{Goodbye.}
{346}{}{Oh, it's you... I'm forever grateful to you for saving me.}
{347}{}{Then why do you have such a sad face?}
{348}{}{Hey, where's that naive girl's passionate, eager look?}
{349}{}{At least he loves you. This means that deep down he's not a tyrant. It's just the way things turned out.}
