{100}{}{You see a ranger in front of you.}
{101}{}{You see a man in leather armor.}
{102}{}{We have nothing more to talk about.}

{200}{}{Well, well. Looks like we have a troublemaker here. }
{201}{}{Oops...}
{202}{}{What are you doing, fool?}
{1202}{}{What's a lady like you doing in a cemetery?}
{203}{}{It's none of your business. So don't bother asking.}
{204}{}{But I will. It's a pity that scum like you interfere with the lives of normal people.}
{205}{}{[More]}
{206}{}{(draws weapon) By the authority vested in me by the Arizona Ranger Department and the Constitution, I sentence you... to death. The sentence will be carried out immediately.}
{207}{}{Wha...}
{208}{}{Go to hell.}
{209}{}{Stop! Tinsmiths asked me to do this. They are looking for their compatriot, I think he's in this grave.}

{210}{}{Looking for valuables.}
{211}{}{Valuables in the grave? Didn't it ever occur to you that someone would be VERY upset by this?}
{212}{}{I don't care. So, what's next? Will you try to stop me?}
{213}{}{Dead people have no use for this.}
{214}{}{Maybe so. But that's not for you to decide. And it is in my power to punish you for such an offense.}
{215}{}{Who are you?}
{216}{}{Yes, sir. I admit my guilt, sir.}
{217}{}{These tricks won't work on me, buddy. I have a keen eye for scammers like you.}
{1217}{}{These tricks won't work on me, lady. I have a keen eye for women like you.}
{218}{}{Who are you?}
{219}{}{Oh no, this man's relatives won't mind. And do you know why?}

{220}{}{I'm a ranger. But who are you? Why do you come to this city and act like you can do anything?}
{221}{}{The Tinsmiths are looking for their compatriot. He was killed. And it looks like you know something about it.}
{222}{}{Who are you anyway?}
{223}{}{None of your business.}

{230}{}{Oh no, no, this is a misunderstanding, I'll explain everything now.}
{231}{}{Work hard, I'm listening carefully.}
{232}{}{You see, I'm looking for... [Take out your weapon and attack]}
{233}{}{It's none of your business. I won't tell you anything.}
{234}{}{The Tinsmiths asked me. They are looking for their brother. He is here.}

{240}{}{I know why. I killed him.}
{241}{}{But why? Why did you kill the Tinsmith?}
{242}{}{Scum like Tinsmiths should be in the ground. They consider themselves gods, as if everything is allowed for them. They oppress the inhabitants, take away any tech from them and force them to work. Their power casts doubt on any hope for justice in the lands of Southern Arizona. And their very existence, combined (contemptuously) with *technology*, is inhumane. For me, this is quite enough.}
{243}{}{[More]}
{244}{}{What attracted you to the Tinsmiths? Bribed by the sound of rusty caps?}
{245}{}{Maybe so. I'm a simple mercenary, I don't care about your Arizona and justice.}
{1245}{}{Maybe so. I'm a simple mercenary, I don't care about your Arizona and justice.}
{246}{}{Well then. Working for the enemies of the wasteland means you're an enemy yourself.}
{1246}{}{Well then. Working for the enemies of the wasteland means you're an enemy yourself.}
{247}{}{[More]}
{248}{}{No need. Please.}
{249}{}{Oh crap...}
{250}{}{So, you confessed. Give me a reason why you should be left alive.}
{251}{}{(pulls out a weapon) I have six reasons, fool. Listen carefully...}
{1251}{}{(pulls out a weapon) I have six reasons, stupid. Listen carefully...}
{252}{}{Oh crap...}
{253}{}{Oh, don't...}
{254}{}{I'm a ranger too. And I'm on a mission. I've been ordered to infiltrate the Tinsmiths to find their weaknesses.}
{255}{}{Hmm. Unexpected meeting, partner. I'm glad to see you. Well, in that case, I have no more questions. We will assume that this meeting did not take place.}
{256}{}{Of course. Nobody saw anything.}
{257}{}{Let me take the remains. Tinsmiths deserve respect.}
{258}{}{Nope. I can't let you keep working for these bastards.}
{259}{}{[More]}
{260}{}{You may hate them. But as a ranger you must respect a strong enemy. Let me take the remains to them.}
{261}{}{Hmm. Your words really make me think. Okay, do your dirty work, mercenary. And tell the Tinsmiths that the wastelanders will not always kneel before them.}
{1261}{}{Hmm. Your words really make me think. Okay, do your dirty work, mercenary. And tell the Tinsmiths that the wastelanders will not always kneel before them.}
{262}{}{Uh, yes, sir. As you say then.}
{263}{}{Just leave me then.}
{264}{}{Sir, I have no complaints against you. I'm just fulfilling a peace contract.}
{265}{}{(taunting) Okay, do your dirty work, mercenary. And tell the Tinsmiths that the wastelanders will not always kneel before them, like you do.}
{1265}{}{(taunting) Okay, do your dirty work, mercenary. And tell the Tinsmiths that the wastelanders will not always kneel before them, like you do.}
{266}{}{I'm just fulfilling a contract. What's the problem?}
