{100}{}{You see Henry Bemis amidst the rubble.}
{101}{}{You see Henry Bemis, a mere remnant of the shattered world. A fragment of what humanity has wrought upon itself.}
{102}{}{Well, perhaps I'll be forgiven.}
{103}{}{*Sigh* I've had an eternity to read. But I've lost my glasses. It's unjust. Unjust indeed.}
{104}{}{Oh, books! Enough to last a lifetime.}
{105}{}{Ah! I can see! You've rescued me from eternal desolation... Here, take it and read alongside me, this is a most intriguing book.}
{106}{}{I require reading glasses, do you understand?}

{110}{}{Nothing, um, everything's fine.}
{111}{}{I've never had the luxury of solitude.}
{112}{}{What am I to do now?}
{113}{}{*Whine*}
{114}{}{*Crying*}
{115}{}{Yes, um, fortunate... Incredibly fortunate... Help! Anyone!}
{116}{}{Am I truly alone in this?}
{117}{}{If only this solitude could be dispelled...}
{118}{}{If only we could TAKE action...}
{119}{}{Something... anything must be done...}
{120}{}{It's unjust. This is wholly unjust.}

{150}{}{Oh, such a multitude of books here!}
{151}{}{The Complete Works of Dickens!}
{152}{}{The Complete Works of George Bernard Shaw!}
{153}{}{Poetry by Browning, Shelley, and Keats!}
{154}{}{"David Copperfield," "The Great Gatsby," "Uncle Tom's Cabin"...}
{155}{}{Books... Precious treasures of the world...}
{156}{}{Books, books, books... Ah!}
{157}{}{January... February... March... this year... next year...}
{158}{}{What matters is that now I have all the time in the world.}
{159}{}{*Contented cooing*}
{160}{}{Truly fortunate... indeed...}
{161}{}{Everything I've longed for is here.}
{162}{}{Now I shall have something to occupy my mind.}
