{100}{}{You see Harvey.}

{110}{}{Harvey hates people!}
{111}{}{Fight, you little bug!}
{112}{}{People hate people like me.}
{113}{}{Why won't you leave us alone?!}
{114}{}{People are following us everywhere!}
{115}{}{People always shoot at us first!}
{116}{}{Master, give me the strength to protect this place from the normies!}
{117}{}{Levi didn't want people in our city.}
{118}{}{Harvey is just protecting the city from the normies!}
{119}{}{Harvey is good. Harvey tries for Levi.}

{120}{}{Levi ordered me guard the city from people.}
{121}{}{Sorry, but you can't stay here.}
{122}{}{Harvey remembers who helped Levi. Harvey is grateful.}
{123}{}{Harvey is good. Harvey protects the city from people.}
{124}{}{Do you revere Levi as much as I do?}
{125}{}{Do you honor the Master?}
{126}{}{I miss the Master...}
{127}{}{Harvey!}
{128}{}{}
{129}{}{}
