{100}{}{You see the administrator.}
{101}{}{You see a man who seems perpetually irritable, muttering under his breath as he navigates through his duties.}
{102}{}{The mine is closed for now. Without Faber, the city's lost its mind!}
{103}{}{This is what happens when people raise their voices at me.}
{104}{}{Ah, finally, my favorite brahmin sausages! The only solace in this wretched world.}
{105}{}{I haven't ordered anything recently, you dimwit!}
{106}{}{You've delivered your order.}

#Random remarks
{110}{}{Morons! Idiots! They've missed all the deadlines again!}
{111}{}{How many times do I have to repeat myself to these imbeciles?!}
{112}{}{The mine will grind to a halt without my guidance.}
{113}{}{I've got the toughest job around here.}
{114}{}{The boss doesn't appreciate how hard I'm working.}
{115}{}{I'd work even better if the pay wasn't so dismal.}
{116}{}{Ore, ore... What am I even living for?}
{117}{}{I'll just tweak a couple of figures in the reports. No one will ever know.}
{118}{}{This report needs to be rewritten. Again.}
{119}{}{No one could handle this position as skillfully as I do.}

{120}{}{Damn, damn, damn! The mine's blown up, we're short on workers... what now?}
{121}{}{What kind of lunatic wants to blow up a mine?!}
{122}{}{This mine will never operate again without my expertise.}
{123}{}{It's all gone...}
{124}{}{Okay... I'm definitely in for a tongue-lashing now.}
{125}{}{Should we pack up and flee?}
{126}{}{Ore, ore... Can't take much more of this.}
{127}{}{My precious caps... The city's about to be in dire straits.}
{128}{}{The mine's collapsed, but the paperwork's still piling up.}
{129}{}{Just a bit more and I'll completely lose my mind.}

#Dialogue
{200}{}{This is administration, not a brothel! What do you want?!}
{201}{}{Raise your voice at me one more time and I'll knock all your teeth out.}
{202}{}{Calm down. I'm just here to ask a couple of questions.}
{203}{}{Do you even know who I am?! I am the administrator of this mine! One might say, the right hand of Roy Faber himself. You dare talk to me with that tone? Get the hell out before I lose my temper!}
{204}{}{Okay, that's it. You're about to feel a world of hurt, Mr. Big Boss.}
{205}{}{(changes tone) Okay, okay, let's not get carried away! The caravan men won't respect me much if I show up all battered... (to himself) Where do they find these people...}
{206}{}{So, are we ready to have a civilized conversation now?}
{207}{}{A couple of questions?! I don't get paid for small talk. I'm working here. Understand? WORKING! So let's make it quick.}
{208}{}{So, are you ready to talk now?}

{209}{}{I see. I'll be going now.}
{210}{}{What do you want?}
{211}{}{Nothing. All's well.}

#About myself
{212}{}{Who are you and what are you doing here?}
{213}{}{I'm the administrator! Let me spell it out for you: A-D-M-I-N-I-S-T-R-A-T-O-R! It means the entire operation of this mine rests on my shoulders. In simpler terms, I'm the face of this company... well, after Roy Faber, of course.}
{214}{}{Sounds like a demanding job.}
{215}{}{Demanding doesn't even begin to describe it. Do you think managing ore production is anything like tending fields of crops?}
{216}{}{You must be under a lot of stress. It seems like no one gets it but you.}
{217}{}{(pause) You have no idea how accurate that is. I pour my soul into this work, and what do I get in return? Miserable caps, barely enough to buy anything worthwhile. And living conditions? Don't get me started.}
{218}{}{[Listen]}
{219}{}{Roy just doesn't get it. He doesn't grasp my significance or the magnitude of my contributions. To him, I'm just another worker. (to himself) Damn it, I should never have left Phoenix for this dump...}
{220}{}{That sounds tough. Let's talk about something else.}
{221}{}{That's none of your business. Let's move on.}
{222}{}{Alright, let's talk about something else.}
{223}{}{What's Roy Faber's role in all this?}
{224}{}{Seriously? He *owns* this mine, along with the entire colony.}

{230}{}{Is this where the caravans depart for Phoenix?}
{231}{}{Only special cargo caravans leave from here. Is that what you're after? Look for the leader in the building across the street.}
{232}{}{Got it.}
{233}{}{I heard there's been disappearances among the workers. What's the story here?}
{234}{}{Workers go missing here now and then. Some get buried in cave-ins, others become giant rat chow. We don't have the resources to investigate every case. If you're seeking answers, delve into the depths of the mine, but don't pester me about it.}
{235}{}{That's unfortunate.}
{236}{}{Why is the mine closed?}
{237}{}{It's a disaster! The mine's sealed shut because some moron blew up the entrance. We'll be digging out the rubble for at least a month. But we lack the resources - the mine's bankrupt.}
{238}{}{Looks like that "moron" gave you a real headache. Good luck.}
{239}{}{What about my task?}
{240}{}{Forget it. The mine's a wreck; there's no way inside now.}
{241}{}{I'll have to look elsewhere for work I guess. Goodbye.}
{242}{}{The bartender asked me to give this to you.}
{243}{}{Ah, my favorite brahmin sausages! The only joy in this godforsaken place. You didn't mess with anything here, did you? Because if you did, you'll have me to deal with. Now, quit staring and go do something useful.}
{1243}{}{Ah, my favorite brahmin sausages! The only joy in this godforsaken place. You didn't mess with anything here, did you? Because if you did, you'll have me to deal with. Now, quit staring and go do something useful.}
{244}{}{Alright.}
{245}{}{Did you know the overseer mistreats prisoners?}
{246}{}{I'm not discussing that with you.}
{247}{}{Take it easy, don't stress yourself out...}

{250}{}{Faber wants us to tackle the mine's issues. So what are they?}
{251}{}{Deadlines are slipping, and those numskulls at the garrison can't drum up new workers. I'm busting my hump, but it's not cutting it!}
{252}{}{Sounds rough. What's the solution?}
{253}{}{The drilling machine's on the fritz. Fixing it would cut down the need for workers big time. Someone's gotta scrounge up the parts and patch that hunk of metal up.}
{254}{}{Anything else?}
{255}{}{The mine is infested with giant rats. They're munching on workers and gnawing our gear. First, off the rat king's gotta go - it's the biggest threat.}
{256}{}{Got it. I'll keep you posted on how it goes.}
{257}{}{Not yet.}
{258}{}{Figured as much.}

{260}{}{About the drilling machine...}
{261}{}{Is it up and running? If not, I don't wanna hear it.}
{262}{}{Where do I find parts for that weird contraption?}
{263}{}{Wherever they are! Get it? Don't ask me! Checked those endless scrapyards you passed by?}
{264}{}{The drilling machine's good as new.}
{265}{}{Didn't peg a backwoods like you for fixing tech. Here's your pay - 200 caps. Good work.}
{266}{}{Nice.}
{267}{}{Faber needs to hear about your deeds. Go chat him up.}
{268}{}{I'll go let him know.}
{269}{}{When I've got a sec.}

{270}{}{About the rat king...}
{271}{}{Is that thing really dead?}
{272}{}{Dead as a doornail.}
{273}{}{You sure? You gotta reason I should believe you?}
{274}{}{Here's the beast's teeth as proof.}
{275}{}{If you want that critter gone, hand over some explosives.}
{276}{}{Damn, you know how tough it is to snag these military supplies? But the rat's gotta go. Here's the warehouse key in the mine. Use the stash sparingly.}
{277}{}{Got it.}
{278}{}{No way, not happening.}
{279}{}{Might've coughed up the explosives, but my key's vanished. (hushed) I think it got swiped.}
{280}{}{Figures.}
{281}{}{Nicely done! I like efficient types. Here's your 200 caps. Spend 'em all at Joe's joint.}
{282}{}{For sure.}
{283}{}{A thief? Here? Damn.}

{290}{}{How's the mine holding up?}
{291}{}{Another question?}
{292}{}{Got it.}
{293}{}{Since the mine was sabotaged, we've been busting our butts to clear the rubble manually. It's gonna take a ton of time and sweat. Don't know if we've got the will or patience.}
{294}{}{Since the boss was taken out, the city's gone haywire. And the mine's fate? Murkier than ever. Fingers crossed.}
{295}{}{Since the prisoner breakout, we're short on hands to mine ore. Missed deadlines were bad enough, now this...}
{296}{}{Thanks to your hustle, mine's humming! Not even sure if we'll move all the uranium this season. Keep it up! Now I can channel my brilliance where it counts.}
{297}{}{Times are tough. Missed deadlines, worker shortage, boss man's boiling over. Mine's in a rough spot, no two ways about it.}
{298}{}{Anything I can pitch in with?}
{299}{}{Collapsed mine's put the brakes on everything. If you wanna help, fine, just don't ask dumb questions.}
{300}{}{Mine's on lockdown. Without Faber, town's losing its marbles!}
{301}{}{Looks like you're knee-deep in it. Guess I'll be on my way. Bye.}
{302}{}{What's going on with the drilling machine and the rat king problems?}
{303}{}{Never mind. I'm outta here.}
{304}{}{Gotcha.}
