{100}{}{You see a colonist.}
{101}{}{You see a citizen of Flagstaff.}
{102}{}{What are you doing out after curfew?}
{103}{}{I have better things to do than chat with strangers.}
{104}{}{Don't push me. I'm not myself since my son died.}
{105}{}{You... bastard...}
{106}{}{...Can't... breathe...}

#Dialogue
{200}{}{Stop! Don't come any closer. What are you doing out after curfew?}
{201}{}{I'm looking for a troublemaker who's been harassing the local preacher. Hello.}
{202}{}{So you're in with that cultist? I don't want to talk to you! I'm going home, and don't you dare follow me.}
{203}{}{I wasn't going to anyway.}
{204}{}{Hold on, let's back up a bit.}

{210}{}{What do you want from me?}
{211}{}{Just ignore me.}
{212}{}{What's your take on the Cult of the Holy Fire?}
{213}{}{I never liked that cult. Worshipping old relics and some mythical Fire? Any sane person has more important things to do.}
{214}{}{Isn't a preacher supposed to heal and teach?}
{215}{}{Yeah... if you bribe him with a bunch of caps and then listen to his idiotic ramblings. I can spout that nonsense about radiation, X-rays, and atoms for free. The whole Church of the Holy Fire is full of charlatans who only help for hefty donations.}
{216}{}{I can't stand this stupid cult either. What can we do about it?}
{217}{}{I'll leave you to your skepticism.}
{218}{}{Hmm. I'm not sure if I believe you. But if you really want to cleanse the city of this filth, it's either we kill the cultist, or we get the people to drive him out.}
{219}{}{How do we do that?}
{220}{}{I don't even know, buddy. If we attack him openly, the city might rally around him. Too many people here buy into his nonsense. We need to take him out quietly.}
{221}{}{If you offer me some incentive, I'll rid the city of the preacher.}
{222}{}{I'll have to think on this. I'll be back later.}
{223}{}{I hear it was your relatives who were enslaved. You should know that the cultist blessed the mercenaries for this "godly" mission. Some of your relatives were taken by other fire worshippers and marched out of the city. If that doesn't bother you, think about the medicines the cultist gets from the south. That's the real "uranium vein," huh?}
{224}{}{I'm so glad to see you!}
{225}{}{Good to see you.}
{226}{}{Hiram shares my son's story during Sunday sermons. Now nothing depends on me.}

{230}{}{I want you to come to the temple and publicly confess what you did.}
{231}{}{Are you out of your mind? That'll turn the whole city against me!}
{232}{}{Not if you pretend you sympathize with the cult now.}
{233}{}{Yeah, that's a stupid idea. Forget it.}
{234}{}{Nonsense! Why would I do that?}
{235}{}{Your son will be saved. Besides, Hiram knows who's behind the nighttime sabotage and won't let it slide.}
{236}{}{Damn... Well, you're right, there's nothing left for me to do.}
{237}{}{The cultist must have fried your brain. Leave me alone.}
{238}{}{Okay. But it's on you.}
{239}{}{Damn, even away from Phoenix you can't escape those crazy fire worshippers... Fine, I'll talk to Hiram. I'll try to find some common ground, but only to avoid conflict.}
{240}{}{Great, this will make things better.}
{241}{}{It's done - Hiram is no more.}
{242}{}{Ahh, wonderful news. With that fanatic gone, the city will be better off. Here's a hundred caps, you earned it.}
{243}{}{What about your son's treatment?}
{244}{}{Hiram saved your son.}
{245}{}{Not bad. Bye.}

{246}{}{There's always bad with the good. No idea what to do for him now.}
{247}{}{Might have been better to deal with that first. Well, bye.}

{250}{}{Why are you trying to drive away the priest?}
{251}{}{An idiotic cult brainwashing people and draining their caps is *already* a good enough reason. But there's another one - my son, suffering from radiation sickness.}
{252}{}{Sad story. Let's change the subject.}
{253}{}{Hiram refused to help you?}
{254}{}{He demanded conversion. Not from me, of course, but from my son. He has to become a temple servant, attend classes, and morning prayers. Damn it. We moved away from those fanatics, but they still meddle in our lives.}
{255}{}{Even caps don't help?}
{256}{}{The local temple is just a branch of the main one in Phoenix. Their prices are sky-high. So, Hiram has enough money to live on. It's more important for him to spread his stupid faith among the colonists. And he'll stop at nothing.}
{257}{}{I can help with the healing if you let me.}
{258}{}{Really? I'd be grateful for any help and will pay with caps, just to avoid dealing with that damn cult.}
{259}{}{I managed to cure your son. Without the church's help.}
{260}{}{Hiram healed your son as a sign of reconciliation.}
{261}{}{Really?! Thank you! Here, take 100 caps for your help.}
{262}{}{I don't heal for the caps. Keep them and be happy.}
{263}{}{You're an incredible person. I'll tell everyone about your good deeds. Thanks again.}
{264}{}{You're welcome.}
{265}{}{Great, that'll cover the cost of the medicine.}
{266}{}{Thanks again.}
{267}{}{You're welcome.}
{268}{}{I'll see what I can do.}
{269}{}{Damn that cultist! Don't think I owe you anything now. But... I'll try not to bother the preacher anymore I guess.}
{270}{}{So we're agreed.}
{271}{}{What's the problem with finding a cure for radiation sickness?}
{272}{}{Hiram is getting medical supplies from the main temple. There's nowhere else to get medicine here. Caravans rarely bring in medicine, and if they do, it's way overpriced.}
