{100}{}{You see a patrolman in front of you.}
{101}{}{You see one of the local mercenaries, leisurely patrolling the streets.}
{102}{}{Damn, I was about to take you out. There's no point in hanging around outside after curfew.}

{110}{}{Greetings.}
{111}{}{Welcome to Flagstaff.}
{112}{}{Move along.}
{113}{}{Any problems?}
{114}{}{What do you need?}
{115}{}{Got a weapon? Keep it holstered.}
{116}{}{Have a nice time.}
{117}{}{Galaxy Lunch has good brahmin sausages.}
{118}{}{See anything suspicious, let me know.}
