{100}{}{You see a bandit, armed and dangerous.}
{101}{}{You see an escaped prisoner, armed and extremely dangerous.}
{102}{}{Step any closer, and you're a corpse!}
{103}{}{Seems like the city's taken a turn for the worse.}
{104}{}{Put your weapon down or everyone here dies!}

#Floating lines
{110}{}{Caps on the table, and make it quick!}
{111}{}{We can do this easy or we can do it hard, your choice.}
{112}{}{Hand over the caps, now!}
{113}{}{I'm losing my patience, fast.}
{114}{}{Hand over the caps or you're dead!}
{115}{}{Face down, now!}

#Dialogue
{200}{}{Hey, you. Hand over all your caps. No funny business!}
{201}{}{Alright, alright, here's 50 caps, just don't hurt anyone...}
{202}{}{Is that all? Damn, that won't get me far... Now, against the wall, and count to a thousand. Got it?}
{203}{}{Uh, sure, whatever you say...}
{204}{}{That's it, I'm done playing nice. Time to teach you a lesson!}
{205}{}{Calm down, there's no need for bloodshed. You still have a chance to walk away.}
{206}{}{I said, hand over all your caps. Now!}
{207}{}{Okay, okay, here's all my caps, just don't hurt anyone...}
{208}{}{What are you talking about?! If I'm caught again, I'm finished.}
{209}{}{But doing this won't solve your problems.}
{210}{}{Damn, you're right... Fine, turn around and count to a thousand. Got it?}
{211}{}{You won't get anything from me.}
{212}{}{We'll see about that right now!}
{213}{}{Watch where you're pointing that thing!}
{214}{}{Alright, let's get this over with!}
{215}{}{I don't have any caps, I swear!}
{216}{}{LIAR!}
