{100}{}{You see a Smart Guy.}
{101}{}{You see a skinny man with glasses, busy doing calculations.}
{102}{}{Finally... peace...}

#Floating lines
{110}{}{So, uh, what's eight times six?}
{111}{}{I really don't know what these numbers mean.}
{112}{}{If I finish early, will they give me another fried rat?}
{113}{}{Power failure again.}
{114}{}{This iron won't last more than a year.}
{115}{}{Seems like it's not just white noise.}
{116}{}{Sometimes strange sounds can be heard at low frequencies.}
{117}{}{Need to update call signs for patrols.}
{118}{}{The last patrol never made contact.}
{119}{}{We might be bugged.}

#Dialogue
{200}{}{(adjusts his glasses, looking at your face) Oh, no, what are you doing here?}
{201}{}{I'm looking for my relatives. Have you heard anything about the peasants from Villa?}
{202}{}{Yes... okay, okay, I know about them. The mercenaries dragged a whole crowd of peasants here and locked them in with the other prisoners. Don't even think about trying to rescue them - it will end badly.}
{203}{}{Is there a way to get into the pen?}
{204}{}{Well, if you have a lot of caps, Faber might let you in. I just don't know if he'll let you out... I'll tell you this - the prison guards have a cushy job, so try to suck up to one of them.}
{205}{}{Hold up, I had another question.}
{206}{}{I'll handle the rest myself.}
{1206}{}{I'll handle the rest myself.}
{207}{}{What do you want?}

{208}{}{What is this place?}
{209}{}{It's a radio station. It's used to communicate with patrolmen over long distances. And you should leave right away. Strangers aren't supposed to be here.}
{210}{}{Where does all this equipment come from?}
{211}{}{I don't know. It was already here when they brought me.}
{212}{}{Interesting. What frequency do the mercenaries communicate on?}
{213}{}{That's something I definitely shouldn't say. If you want to know, go ask the boss.}
{214}{}{You're being difficult, bespectacled guy. Tell me the frequency, now!}
{215}{}{Be quiet! They'll hear us... Okay, look, this is the frequency for patrol officers, and this is for jailers. Just don't tell anyone!}
{216}{}{Got it.}
{217}{}{I'm going to scream! I'll scream and you'll get caught!}
{218}{}{There's no need for that. Calm down.}

{219}{}{So much equipment just for communication?}
{220}{}{Well, yes... and for controlling the collars.}
{221}{}{Do you know how to disable the prisoners' collars?}
{222}{}{You need a terminal access code. Only Faber and I have it, and I won't tell you.}
{223}{}{Come on, do something useful for oppressed people like you. This is your chance at salvation.}
{224}{}{You're insane! If a the warden catches us, we'll face something worse than the noose. You better leave before they see us together. I don't want any trouble.}
{225}{}{Well... maybe. I don't know if I can trust you... we could both pay with our lives for this. Here's the password, but be careful!}
{226}{}{Good decision.}
{227}{}{This equipment seems out of place here.}
{228}{}{How should I know? I'm just pushing buttons.}
{229}{}{Maybe so. The building is all run down, but the equipment seems newer. And the antenna definitely doesn't belong here.}
{230}{}{We'll deal with this later.}
{231}{}{Goodbye.}

{250}{}{Who are you?}
{251}{}{They call me Smart Guy. I wasn't suitable for working in the mine, so they assigned me to monitor radio communications.}
{252}{}{Do you want to be free?}
{253}{}{Me? Free? But... what would I do out there? The boss might be evil, but he feeds us and protects us from raiders. Where could I go without him? I don't know...}
{254}{}{You told Faber I was asking you questions!}
{255}{}{W-Wait! Have pity! Don't hit me! I'm just a prisoner! What was I supposed to do? You have zero chance against the mercenaries, and I have to live here until the end of my days. I'd be dead if I hadn't fessed up to him!}
{256}{}{Better shut up, you little bastard, before I shove your glasses down your throat.}
{1256}{}{Better shut up, you little prick, before I shove your glasses down your throat.}
{257}{}{Fine, live for now. I shouldn't have trusted the first person I met.}
{258}{}{When the equipment was operational, it was a radio station. Now it's just a warehouse for junk. But still, you shouldn't be here.}

{260}{}{Faber is dead. You're free.}
{261}{}{God, why?! Without Faber, all of Flagstaff will collapse! The mercenaries will fight for his position, and there'll be riots and banditry! Do you know how much work went into setting this place up? Thanks for the freedom, but I never needed it.}
{262}{}{Hmm...}
{263}{}{Why didn't you escape with the other prisoners?}
{264}{}{Where would I go? Into the wasteland? I'd be dead in no time. And in the city, no one needs me. This Prison was the only place where my talents were valued, and I got food and protection. Think what you want, but I was content here.}
{265}{}{Ironic I guess. Fine, stay here, loser.}
