{110}{}{Equipment is malfunctioning.}
{111}{}{You have managed to disable the radio transmitter. The entire colony is now without radio communications.}
{112}{}{You have no idea how this works.}
{113}{}{Cannot be repaired.}

#Dialogue
{200}{}{Enter command:}
{201}{}{End session}
{202}{}{Back}
{203}{}{The radio transmitter is not responding.}

{210}{}{Disable collar control}
{211}{}{Warning! Disabling collars will reduce control over prisoners. Are you sure you want to proceed?}
{212}{}{Yes, disable the collars.}
{213}{}{Collar control disabled.}

{214}{}{Copy mercenary frequencies to eavesdrop on their radio communications.}
{215}{}{Radio frequencies copied.}

{216}{}{Engineer's comment}
{217}{}{This sacred equipment was brought from the Navajo camp, 11 miles from Flagstaff, and installed in the colony in honor of the Holy Fire in the year 2*** by His humble servant *** under the order of Aaron, Lord of Phoenix. May the sky fall upon anyone who desecrates this gift.}
