{200}{}{"Welcome to Flagstaff - the best city north of Phoenix! Founded in 2163."}
{201}{}{I've had enough of this sign.}
{202}{}{Best city, huh? Perhaps it's worth taking a look around here.}

{210}{}{What does it say about a curfew?}
{211}{}{"Curfew from 00:00 to 06:00. Open carry of weapons is prohibited in the city."}

{220}{}{What does this map of the colony show?}
{221}{}{On the crookedly drawn diagram there are 4 areas labeled: Block A (this residential area), in the east Block B (garrison and prison), in the north Block C (uranium mine), as well as the uninhabited ruins of the old city in the east.}
{222}{}{What does it say about the old city?}
{223}{}{"Warning! There is a suspected group of raiders operating in the eastern ruins. Be careful!"}
{224}{}{The text is crossed out. Apparently this announcement has lost its relevance.}

{230}{}{This doesn't seem to be written very well...}
{231}{}{(You find a lot of grammatical errors in the bulletins.)}
{232}{}{Yeesh, there are so many mistakes here! This needs to be corrected...}
{233}{}{(The grammar is ok now.)}
{234}{}{Yes. That's better.}
{235}{}{(You find no errors.)}
{236}{}{The text is fine. Well, at least I think it is...}
