{100}{}{You see Mr. Kogan.}
{101}{}{You see a scruffy fat man in a dirty business suit. Looks like he's in charge here.}
{102}{}{Choke on lead, you fat pig rat!}
{103}{}{How does a scavenger feel when his fate depends on trash?}
{104}{}{Hey! I have nothing to do with this. He's having a heart attack!}
{105}{}{I'm not against peace talks, but first, get out of that tin suit.}
{106}{}{Get out of my town.}
{107}{}{Get out of my garage.}

#Floating replicas (do not delete empty lines!)
{110}{}{*Cough cough*}
{111}{}{*Ugh*}
{112}{}{*Urp*}
{113}{}{*Burp*}
{114}{}{Damn heartburn...}
{115}{}{ }
{116}{}{ }
{117}{}{ }
{118}{}{ }
{119}{}{ }

#Cut-scene
{120}{}{ }
{121}{}{Mr. Kogan! Mr. Kogan!}
{122}{}{Fuck Larry! Why the hell are you barging into my office?}
{123}{}{What the hell! You know better than to barge into my office...}
{124}{}{Mr. Kogan! In the dorm, there's a serious problem!}
{125}{}{God damn this hole! Well, what is it now? Probably another drunken brawl.}
{126}{}{No, it doesn't look like it. More serious. I didn't understand the reason for the fight, I just ran straight here...}
{127}{}{So go and figure it out, idiot!}

#Dialogue
{170}{}{I've seen this type of clothing before. What connection do you have with the Followers of Fire?}
{171}{}{The most direct. I am part of the church.}
{172}{}{Hmm... very interesting. I usually try to avoid religion. But the Followers contribute to the progress of Arizona and, as a result, the development of my cartel. You can feel protected here.}
{173}{}{Well, that's good to hear.}
{174}{}{Can I count on full garage service?}
{175}{}{Of course. I'll let Pete know.}
{176}{}{Thanks.}
{177}{}{This is the first time I've heard about these "Followers of Fire." I took this robe from a corpse in the desert.}
{1177}{}{This is the first time I've heard about these "Followers of Fire." I took this robe off a corpse in the desert.}
{178}{}{Is this true? Then forget I asked.}
{179}{}{I'll do that.}

{180}{}{I heard you had some kind of... incident with Larry?}
{181}{}{Nothing special. He was just getting into trouble at the bar.}
{182}{}{You must have nerves of steel if you think you can kill my people. On the other hand, I've wanted to get rid of that drunken devil for a long time. He made too much trouble.}
{183}{}{So you won't come after me?}
{184}{}{You'll have to work hard to earn my respect. It's up to you.}
{185}{}{Okay...}
{186}{}{He came at me first! I was just defending myself.}
{1186}{}{He started it first! I was just defending myself.}
{187}{}{That was between him and me. It doesn't concern you.}

{190}{}{You again... (sigh) Do you know about the Rangers? I hate those guys. They always stick their noses into business that isn't theirs, as if the whole wasteland belongs to them. You're not planning on doing the same thing in *my* city, are you?}
{191}{}{No, Mr. Kogan. I'm here purely on business.}
{192}{}{Okay. I think we understand each other. Don't forget who owns this place.}
{193}{}{All right.}
{194}{}{You better talk about the Rangers in a respectful manner. Someday we'll have all of Arizona under our control.}
{195}{}{I highly doubt that. The Rangers have a lot of enemies, and their numbers are too small to control the population on their own. And they'll certainly never gain control of this city as long as I live.}
{196}{}{What's your problem with the Rangers?}
{197}{}{I *don't* have a problem with them. But I'm not going to share power with anyone. I put too much work into this place and created this entire city practically from scratch.}
{198}{}{Well, that's something to think about.}
{199}{}{Rangers are occupied with their own narrow interests. They are not able to create anything new. And this is exactly what people need now.}

{200}{}{(You see a very well-fed man in a worn business suit, looking out of place against the background of the surrounding ruins. When he sees you, he turns away from some device and removes the headphones connected to it.)}
{201}{}{Ahem. Are you in charge here?}
{202}{}{(puts down the headphones and presses some buttons on the device, then points to it) This is an old tape player. Before the Great War, these were produced by the famous Wattz Electronics company. The model wasn't the most high-end, but was well made. Evidenced by its survival to this day.}
{203}{}{[Listen]}
{204}{}{This is why I love old things. Our ancestors made many mistakes, but they knew how to make tape players. Back then, many factories, producing many different devices, tools, and machines, operated throughout Arizona. Now they're all gone.}
{205}{}{Who needs old stuff like that?}
{206}{}{I knew you couldn't grasp it. Now, what do you want, boy?}
{1206}{}{I knew you couldn't grasp it. Now, what do you want, lady?}
{207}{}{Yeah... The world has definitely lost a lot.}
{208}{}{Hmm. I thought you would have disagreed. Though neither you nor I have much power to bring the past back, anyway. So. Whats on your mind, boy?}
{1208}{}{Hmm. I thought you would have disagreed. Though neither you nor I have much power to bring the past back, anyway. So. Whats on your mind, lady?}
{209}{}{Stop blathering about tape players! I didn't trek through the desert for a lecture on ancient gadgets!}
{1209}{}{Stop blathering about tape players! I didn't trek through the desert for a lecture on ancient gadgets!}
{210}{}{You're not much of an intellectual, are you? So what's on your mind, boy?}
{1210}{}{You're not much of an intellectual, are you? So what's on your mind, lady?}

{211}{}{I'm here because someone enslaved the villagers of Villa and took them in this direction.}
{212}{}{Nobody likes their routine messed up. I hate when ruins are scavenged dry - then we gotta hunt for new spots, which makes my crew real jittery. I've got a few dozen scavengers under my command, and deals with other groups across Arizona and beyond.}
{213}{}{[More]}
{214}{}{Villa's got it easy compared to us. People keep popping out kids, but scrap? That stuff doesn't grow back. You folks don't get it. Your world's just your little village. We scavengers, we keep Southern Arizona running with what we dig up. No one but you village folk care about what happens to Villa.}
{215}{}{So did you order the capture of my people, you son of a bitch?}
{216}{}{So you don't deny your involvement?}
{217}{}{Me? Certainly not. This was the undertaking of another, more powerful organization. We were merely a waypoint on their journey. If I were you, I'd forget all this, return to my empty house, and start afresh.}
{218}{}{You think it's that simple?}
{219}{}{There is no other way for you. However, you can stay here and work as a scavenger if you like. What do you say?}
{220}{}{I...}
{221}{}{You seem to be enjoying my Villa's tragedy.}
{222}{}{Enjoying? No. But when WE needed help in times of famine, YOU profited from this by demanding higher prices from us. Well, how does it feel to be on the receiving end?}
{223}{}{That's not what I asked.}

{230}{}{Those scavengers get real nasty when they're drunk. Listen, if you're planning to stick around, you'll need my protection. Here's your chance to prove your worth.}
{231}{}{Are you suggesting I deal with the workers?}
{232}{}{Go to the dorm and find out what happened there. I don't need any more problems around here.}
{233}{}{I'll see what I can do.}
{234}{}{I don't think I'd want to work for you.}
{235}{}{Wonderful. Oh yeah, I didn't introduce myself. Karl Kogan. I run things around here. Now get to work.}
{236}{}{. . .}
{237}{}{Then you don't belong in Garage City. Get out.}
{238}{}{. . .}
{239}{}{Why should I get involved in local squabbles?}
{240}{}{My good will isn't enough? Don't forget that I know everything about your enemies - more than anyone in Garage City.}
{241}{}{What did you find out about the fight in the dorm?}
{1241}{}{What did you find out about the fight in the dorm?}
{242}{}{Nothing. I'll get digging right now.}
{243}{}{Can I ask you a couple of questions?}
{244}{}{First prove that you're worthy of my attention. Or are you already planning to skip out of town?}
{1244}{}{First prove that you're worthy of my attention. Or are you already planning to skip out of town?}
{245}{}{Okay, I'll do what you ask.}
{246}{}{That's exactly what I'm going to do.}
{247}{}{Lucas's men robbed Trayvon's men and left town. They were talking about some kind of decoder.}
{248}{}{I know, idiot! How long has it been since I gave you this task? Your chances of proving your usefulness are rapidly dwindling.}
{1248}{}{I damn well know! How long has it been since I gave you the task? Your chances of proving your usefulness are rapidly dwindling.}
{249}{}{What's this all about anyway?}
{250}{}{I didn't expect this from Lucas. His clan had a reputation for being a small but tough team. If he decides to go against me, he'll have to pay dearly for it.}
{251}{}{I have questions about this Lucas thing.}
{252}{}{Is there anything else I can do to help you, Mr. Kogan?}
{1252}{}{Is there anything else I can do to help you, Mr. Kogan?}

{253}{}{I have the answers.}
{254}{}{Why are the clans so bitter against each other?}
{255}{}{The ruins have been almost picked clean, making it difficult for the scavengers to survive. Previously, the clans got along well - there was enough for everyone. Now they've become fierce competitors.}
{256}{}{What's the story with the decoder?}
{257}{}{A rare device for hacking electronic systems. I ordered a decoder for a large sum of caps through the southern caravans and gave it to the Trayvon clan to open the old plant. This is the only place we couldn't get to because of the damn security system. Looks like Lucas has decided to beat us all to the prize.}
{258}{}{Why was it necessary to divide the scavengers into clans?}
{259}{}{They wanted it themselves. People need authority, that's how their thinking works. I don't care who gets the orders. The main thing is that they obey and don't create problems.}
{260}{}{Enough about scavengers.}
{261}{}{Enough cartel talk.}
{262}{}{I've had enough of this local drama. Goodbye.}

{270}{}{Are you the local elder?}
{271}{}{Elder... Is that what the peasants call the mayor? No, the city doesn't need a mayor. At least for now. I'm the boss of the scavenger cartel. But since the whole city is tied to this business, not a single important decision can be made without me. In this sense, you can consider me an "elder".}
{272}{}{So you're the mayor of this city?}
{273}{}{No. And the city doesn't need a mayor. At least for now. I'm the boss of the scavenger cartel. But since the whole city is tied to this business, not a single important decision can be made without me. In this sense, you can consider me the mayor.}
{274}{}{How did you become the head of the cartel? You must have eliminated your rivals?}
{275}{}{Nothing like that. I started out as an ordinary scavenger in the Big City. The cartel already existed; I just took a vacant position in the administration. And then we opened a branch in these ruins, and I decided to move here to supervise the work.}
{276}{}{It doesn't seem like you want to go back.}
{277}{}{I'm afraid the main office and I are having some... disagreements.}
{278}{}{What does your cartel do?}
{279}{}{Mainly we scavenge old ruins. In the hundred years since the Great War, many things have deteriorated, but some have survived and can be useful to society. We also try to fix up some of the stuff we find, but this is much more difficult.}

{280}{}{My village doesn't like that your rebuilding the old factory.}
{281}{}{Why? Oh yes, I've heard a lot about your superstitions and fear of old technology. Well, you have no say in the matter.}
{282}{}{Really?}
{283}{}{From now on, no one will allow your peaceful village to flourish with manual labor alone and live according to the laws of a village. Cities are being reborn. If not now, then soon, someone will come here to restore production. It's unavoidable.}
{284}{}{It seems impossible to fight this. Goodbye.}
{285}{}{The Elders want isolation. They don't like the idea of strangers coming into the valley again.}
{286}{}{Like I said, you have no say in the inevitable. All you can do is prepare. You could buy weapons, build fences, reclaim lost property, and even create a more efficient irrigation system. And for much of this, oddly enough, you'd need the services of my enterprise.}
{287}{}{Are you offering a deal?}
{288}{}{Considering that the whole city is to blame for your troubles and that you opened the plant with your own hands, I offer to provide services to your Villa at a very low price. This will bring jobs to the city and allow your people to prepare for the inevitable. Everyone will benefit.}
{289}{}{Sounds interesting. But convincing the elders won't be easy. I'll think about it.}

{300}{}{What's on your mind?}
{301}{}{Nothing actually. I've got stuff to do.}

#Quest 2
{310}{}{Old Lucas made an unforgivable mistake. It damaged my reputation. And more importantly, ruined my plans.}
{311}{}{[Listen]}
{312}{}{But that's not the point right now, I'll deal with it later. Right now I need some special radio parts from the factory. I need them as soon as possible. Can you get them?}
{313}{}{What if I kill Lucas?}
{314}{}{I doubt you have the guts or skill. And if they finish you off, then our whole conversation will be meaningless. Just get me what I asked for.}
{315}{}{I see. I'll take care of it.}
{316}{}{No way. Try finding some other sucker.}
{317}{}{Of course. I'll do it.}
{318}{}{What's in it for me?}
{319}{}{Of course, I'll pay you for this job. But my respect is worth much more.}
{320}{}{Is there anything else I can do to help you, Mr. Kogan?}
{1320}{}{Is there anything else I can do to help you, Mr. Kogan?}

{330}{}{These are the parts you wanted from the factory.}
{331}{}{Great. I'm starting to like you. Now all that's left to do is deliver this to the client.}
{332}{}{What about my reward?}
{333}{}{You'll receive it after the deal is done.}
{334}{}{What kind of deal?}
{335}{}{I'm waiting for a very important caravan that will begin a new milestone in the history of this city. The caravan is coming for this part. And I need reliable people to protect me during the transaction. Are you with us?}
{336}{}{What if I refuse?}
{337}{}{Then you'll really upset me. It's better not to upset me.}
{338}{}{Then I have to really upset you, fatso.}
{1338}{}{Then I have to really upset you, fatso.}
{339}{}{Well, that was pretty stupid of you. Get out of my city. And you get nothing.}
{340}{}{...}
{341}{}{Okay. I'm with you.}
{342}{}{Very good. Get ready for the meeting, get everything you need. And then come back here.}
{343}{}{Okay.}
{344}{}{Okay, what should we do?}

#Quest 3
{350}{}{}
{351}{}{Are you ready?}
{1351}{}{Are you ready?}
{352}{}{Yes, I'm ready.}
{1352}{}{Yes, I'm ready.}
{353}{}{No, I still need to get something. It won't take long.}
{354}{}{Be careful. Nobody knows about this deal, but anything can happen. I'm gonna talk to the caravan, your task is to make sure that everything goes as it should. The client should leave satisfied.}
{355}{}{Got it.}
{356}{}{Uh... I just gotta take a leak. You know how it is, before a big job... I'll be right back.}

{360}{}{The deal was a success, wasn't it?}
{361}{}{That was a great deal. You can't even imagine how great. We didn't just earn caps. We gave the city a chance to survive.}
{362}{}{What do you mean?}
{363}{}{This city is dying. Before, we survived by scavenging from the ruins, but their resources have become scarce. To survive, this city can't rely on old ways. It needs a whole new direction.}
{364}{}{So you're going to restore that factory?}
{365}{}{Correct. However, this will be a pointless exercise without a powerful source of energy. This can only be obtained in Flagstaff - the city where that caravan came from.}
{366}{}{Great idea. This is exactly what this ruined world needs.}
{367}{}{Glad we can agree on that. Someday you'll see Garage City like the good old days - clad in shining vacuum tubes with perky bebop and bikers on motorcycles.}
{368}{}{So what about our agreement?}
{369}{}{You'll never be able to restore that factory. Crazy.}
{370}{}{That's what most people think. But I'm confident in my abilities. And someday you'll see Garage City as in the good old days - clad in shining vacuum tubes with perky bebop and bikers on motorcycles.}
{371}{}{So what about our agreement?}
{372}{}{Yeah, cool. So what about the payment?}
{373}{}{I don't care. I'm only interested in our agreement.}

{380}{}{I value my business partners. Here is your fee for your work - thats 200 caps. I'll also tell Pete to serve you to the fullest. Make yourself at home.}
{381}{}{I'll go spend some caps.}
{382}{}{What about Villa and the raiders?}
{383}{}{You're still fixated on that huh? The slave convoy with your kin went to the city of Flagstaff. It's located in the east, a week's journey from here. Walk along Interstate 40, you won't miss it.}
{384}{}{Great, now I'll deal with these damn raiders.}
{385}{}{Hopefully there will be something there to spend my caps on.}
{386}{}{How could you accept slave traders? Doesn't your conscience bother you?}
{387}{}{You know, fat guy. If I had a nuclear bomb, I would blow up this entire town. But I don't have one. Unfortunately.}
{1387}{}{You know, fat guy. If I had a nuclear bomb, I would blow up this entire town. But I don't have one. Unfortunately.}
{388}{}{Ah. OK. Bye.}

{390}{}{You might be glad to hear that Lucas is dead.}
{391}{}{Well, well. Good job. Here's your reward, 100 caps. You can spend it at the local bar, though I don't think you'll be welcomed there after that.}
{392}{}{Thanks for the caps, Mr. Kogan.}
{393}{}{I was hoping for a different amount for such a dirty job. But this will do I guess.}
{1393}{}{I was hoping for a different amount for such a dirty job. But this will do I guess.}
{394}{}{Can I ask you a question? How does it feel to get rid of a competitor?}
{395}{}{What does a person feel after getting rid of trash? Relief, I suppose. Although, I admit, I am also haunted by a faint sense of loss.}
{396}{}{Continue.}
{397}{}{Really?}
{398}{}{Lucas was one of the best scavengers. At one time he and I were friends. But even such an experienced and valuable person ultimately turned out to be a traitor and set a bad example for others. And I'm definitely not going to worry about it for long.}
{399}{}{I see your point.}
