{100}{}{You see a brahmin.}
{101}{}{You see a brahmin looking for sparse vegetation on the dry ground.}
{102}{}{Moo!}
{103}{}{Moo?}
{104}{}{You're too far away. The brahmin has lost sight of you.}
{105}{}{?}

{200}{}{Moo?}
{201}{}{Don't worry so much. I'm just passing by.}
{202}{}{Follow me, animal, I'll give you something tasty.}
{203}{}{Moo!}
{204}{}{No, don't follow me. Shoo, shoo! You brainless brahmin...}
{205}{}{C'mon, c'mon, you dumb brahmin...}
