{100}{}{You see a refugee.}
{101}{}{You see one of the new arrivals.}
{102}{}{To feed a refugee, use food items on them.}

#First dialogue
{200}{}{(a piercing, wild set of eyes stares at you from under dirty curls) What do you want? What do you want? Eh?}
{201}{}{Don't worry, I won't hurt you.}
{202}{}{You're not too trusting of strangers, are you?}
{203}{}{What do you want? I haven't eaten for two days, and they're kicking me out of this city. Give me something to eat or leave me alone.}
{204}{}{Okay, I'll see if I have anything to eat in my backpack.}
{205}{}{Feed you? Go to hell, beggar!}
{206}{}{I'll give you a couple of knuckle sandwiches.}
{207}{}{Give me any more lip, and you'll eat your own hand.}
{208}{}{Stop! Don't touch me!}
{209}{}{Okay, calm down. I just want to ask a question.}
{210}{}{If you answer my questions, you won't get hurt.}
{211}{}{Leave me alone.}
{212}{}{Oh well, whatever.}
{213}{}{So it was your group that went to the rangers and turned off the path?}

#Re-dialogue
{220}{}{What do you want?}
{221}{}{Goodbye.}
{222}{}{Thanks for the food. How can I thank you?}
{223}{}{Nothing today. Goodbye.}
{224}{}{I see.}

{230}{}{What are you doing in this town?}
{231}{}{We're running from trouble. Terrible things are happening in the southeast: power is changing in the cities, people are being enslaved, farmers are being driven from their rightful lands. We hoped to find safety in the Rangers territory, but they turned out to be no better.}
{232}{}{How did you manage to cross the desert?}
{233}{}{It was a real brutal ordeal. It was cold at night and so hot during the day that we fried lizards right on the rocks. We made most of the distance in the evenings and early mornings. At times it seemed like we wouldn't survive. We definitely won't survive a second trip like that.}
{234}{}{Yah, it's an unforgiving land.}
{235}{}{Tell me again how you ended up here?}

{240}{}{What happened with the Rangers?}
{241}{}{Rangers? Ha! We were told that they protect law and order. But in reality, they're just ordinary raiders.}
{242}{}{What made you think like that?}
{243}{}{You better watch how you talk about the Rangers.}
{244}{}{First, they took everything of value from us, and then they told us to get off their land.}
{245}{}{But why would they drive you away?}
{246}{}{Look at these rags - there's nothing to take from us, we're poor refugees. And we have neither the strength nor the desire to work for them as free slaves. They don't need us. So they drove us away like useless trash.}
{247}{}{How do you know it was the Rangers?}
{248}{}{One of them showed a badge. Besides, the raiders wouldn't have driven us away; they would've just robbed or killed us.}
{249}{}{Strange story... I need to find out more about this. Don't leave town just yet.}

{250}{}{I need to find these Rangers.}
{251}{}{Find them? For what? Don't tempt fate. They'll rob or kill you too.}
{252}{}{I'll deal with them. Just show me the way.}
{253}{}{Yeah, it's probably just asking for trouble. Forget it.}
{254}{}{No no, I'm too weak to travel. I need to recover for a while before any journey.}
{255}{}{I'll come back when you're stronger. Goodbye.}
{256}{}{You'll be chewing your own teeth if you don't show me the way.}
{257}{}{Fair enough. Here's 20 caps; use them to buy food at the bar.}
{258}{}{(watches hungrily as you rummage through your pockets)}
{259}{}{Uh, I think I left my caps at the... um... motel.}
{1259}{}{Uh, I think I left my caps at the... um... motel.}
