{100}{}{You see Lucas.}
{101}{}{You see an experienced-looking scavenger wearing a blue headband.}
{102}{}{Get out of my factory!}

#First quest
{150}{}{(You see an experienced scavenger; he frowns at you, sitting in a relaxed position) I didn't expect Kogan to send a stranger. Who are you?}
{1150}{}{(You see an experienced scavenger; he frowns at you, sitting in a relaxed position) I didn't expect Kogan to send a foreigner. Who are you?}
{151}{}{I have no idea who Kogan is. I'm tracking down a slave convoy.}
{152}{}{Hmm. So you're from the village that the colonists raided? I heard all about that. Kogan tried to get along with the colonists in hopes of future contracts with them. He was the one who told them about Villa. Those guys were looking for savages; they hadn't even heard of you.}
{153}{}{Kogan demands an explanation.}
{154}{}{He'll get them. But I want to know why YOU work for this greedy bastard? What did he promise you for your work?}
{155}{}{Actually, I'm pursuing the people who took my relatives away against their will. Kogan knows something about this.}
{156}{}{Do you know where the convoy went?}
{157}{}{Yes, I know. I'll tell you everything if you do me a favor. Afterall, you're not going to work for Kogan after what I just told you, right?}
{158}{}{Just tell me. And you won't get hurt.}
{159}{}{You have any brains in that head? Yeah? Then use them. Because around here you could get them bashed in.}
{160}{}{What do you want me to do?}
{161}{}{Okay, what's this "favor" then?}
{162}{}{I need all of Kogan's latest contracts. They must be recorded on the computer in his garage. Just copy them and bring them to me. Then we'll talk.}
{163}{}{Okay, I'll get these contracts. Be right back.}
{164}{}{That sounds more than a little risky. You're asking too much.}
{165}{}{You want to know about the colonist convoy? Then go and don't come back without the contracts.}
{166}{}{Alright, alright. I'll do it.}
{167}{}{I'll think about it.}
{168}{}{I have some questions.}
{169}{}{Hey, I see you! Come out into the light, you little rat. Are you spying for Kogan?}
{170}{}{So, did you manage to get the contracts?}
{171}{}{Not yet.}
{172}{}{Who said I was even going to get them?}
{173}{}{You probably don't know, but Kogan is dead.}
{174}{}{So it'll be easier for you to get the contracts. I still need that info.}
{175}{}{I'll go and get on with it then.}
{176}{}{You know, I'm not so good with computers. So... it'll be pretty tough to finish your 'favor'.}
{177}{}{What, you can't access the computer huh? Kogan probably keeps it protected by a password. Hmm...I'm a little reluctant, but I'll have to give you the decoder. It'll hack the system itself; you just have to give it some time.}
{178}{}{This changes things. I'll give it a try.}
{179}{}{}
{180}{}{Here's the contract data you asked for.}
{181}{}{Okay, let's see... yeah... I understand...}
{182}{}{What do you understand?}
{183}{}{You talk to yourself a lot, huh?}
{184}{}{Kogan agreed with a neighboring city to supply parts from this factory. The caravan is already on its way. All we need is to get ahead of it and meet the caravan earlier.}
{185}{}{Why do you need this?}
{186}{}{This factory is a practical goldmine! You just need to get it working and find customers. There aren't many, but they exist.}
{187}{}{Okay, but what about our agreement?}
{188}{}{You better stick with us. We'll talk when this is all done.}
{189}{}{But I don't want any part of this!}
{190}{}{If everything goes smoothly, you won't be part of it. We'll just meet up with the caravan, exchange things, and go our separate ways.}
{191}{}{Do what you want. I'm not involved.}
{192}{}{Sounds good. When are we heading out?}
{193}{}{We need to gather the parts first. Walk around the factory and find the things listed in the contract. Everything listed should be here.}
{194}{}{Fine.}
{195}{}{I need to ask you something.}
{196}{}{No questions until I get the contracts.}
{197}{}{Okay, I'll get the contracts...}
{198}{}{Oh, so that's how it is!}

{210}{}{What is it?}
{211}{}{I think I'll go.}

{220}{}{What is this place?}
{221}{}{You really don't know what a factory is? Dark skin like that... You probably live in the desert... Okay, factories used to produce equipment and gadgets. Now, of course, they don't.}
{222}{}{I've heard enough about the factory. Can we talk about something else?}
{223}{}{Why?}
{224}{}{You said the factories are now idle. Why?}
{225}{}{There's nowhere to get that much energy these days. And even if there is a source, only a few have the necessary skills and knowledge to use it. Since the Great War, people have squandered their achievements...}
{226}{}{What did they produce here?}
{227}{}{This was the Wattz Electronics factory. Parts for electronic equipment and various types of nuclear batteries were made here.}
{228}{}{Why is there so much light here?}
{229}{}{Old lamps. They run on electricity, which is produced by backup generators because the local reactor has been idle since the "big boom." It could still be powered up, potentially. But that would require nuclear fuel. And there's nowhere to get it, yet.}
{230}{}{How do you know so much about pre-war stuff?}
{231}{}{I'm a scavenger, I've been working with old items for years.}
{232}{}{You know, these iron contraptions look kind of dangerous.}
{233}{}{What, the robots? They still won't let us into the rest of the factory. Only thanks to the decoder was it possible to hack the system and turn off the alarm. The robots here are harmless now. And eventually, they can be used instead of workers.}

{240}{}{Did you know Kogan is dead?}
{241}{}{Yes, rumors travel fast in the Garage. To be honest, I'm even a little sorry.}
{242}{}{[More]}
{243}{}{Kogan was a greedy bastard, but he was a worthy entrepreneur. And I think it would have been possible to come to an agreement with him. Now, without him, the scavengers will destroy everything here.}
{244}{}{Looks like things are messed up here. Let's talk about something else.}
{245}{}{Seems like you really upset your boss.}
{246}{}{I don't care. The boss needs new investment in the business, and among all the scavengers in the city, I'm the only who can provide it. He'll have to deal with me.}
{247}{}{I get it.}
{248}{}{What about the rest of the scavengers? Have you thought about them?}
{249}{}{Open your eyes - Garage City is almost finished. There's no room for so many workers here anymore. They'll have to go to other places.}

{250}{}{Here's the part that was mentioned in the contract.}
{251}{}{(carefully studies the high-tech gadget) Yah, this is it. Get ready to meet the caravan. We meet near the old water pump. I don't know what might happen there, so take a good weapon and wear armor.}
{252}{}{I can move out now.}
{253}{}{I need time to get ready.}
{254}{}{Relax for now, this will take some time...}
{255}{}{[Go with the scavengers]}
{256}{}{No, wait, I need some time.}
{257}{}{Okay. See you at the water pump.}

{260}{}{We made the deal! Without your help, it would've been much more difficult. We owe you. Here, take 200 caps. This is your share of the take.}
{261}{}{What are you going to do now?}
{262}{}{I'll start restoring the factory. They promised to bring us fuel for the reactor, then we could start the machines and start producing new parts.}
{263}{}{Good luck then. And my business here is finished.}
{264}{}{Well, well, I'll take a look at your efforts in the future. Goodbye, dreamer.}
{265}{}{We made the deal. However, your help didn't amount to much. We talked and decided that you don't deserve a share.}
{266}{}{Caps are good. What are you going to do now?}
{267}{}{Is that a laser weapon you got there? It would be more useful to me than caps.}
{268}{}{No problem, take it. This is a laser emitter. I cobbled it together from local parts. I'll probably make more in the future.}

{270}{}{You promised to tell me about the colonist slave convoy.}
{271}{}{Yes, it's a complicated story. You see, actually, they were mercenaries from a number of nearby settlements. But they were led by some dudes from Flagstaff. That's the colony. It's in the east, a week's journey from here.}
{272}{}{Why do they need slaves?}
{273}{}{At first, they were looking for the Jackals' lair, aiming to enslave the lot of them. They need labor for some kind of actual mine. But then Kogan sensed profit and proposed an attack on Villa. An easier target. He wanted to get in good with them. Because Flagstaff promises to be a good client for the cartel.}
{274}{}{So you're all connected, right?}
{275}{}{You have to understand, such a deal was good for Garage City. And our meeting with the caravan was part of this whole thing. You may not like it, but we scavengers need to take care of ourselves.}
{276}{}{I get it. Now I need to go to this... Flagstaff.}
{277}{}{Well, I won't forget this whole dirty business. The villagers of Villa have long memories.}

{280}{}{Hi, Lucas. About your factory, and your plans for production. My community fears it'll have a bad effect on Villa.}
{281}{}{Nonsense. New workers will come here, and the city's trade will increase. It's better for you, because you'll be able to trade more crops and ceramics with us, and with other cities.}
{282}{}{Perhaps. However, our elders want isolation.}
{283}{}{Old people don't want change? Too bad! The world is changing, and they'll have to too.}
{284}{}{Maybe so, but they don't like it.}
{285}{}{Well, after all my wanderings, I guess I have to agree with you. But how can I persuade the elders? They'll need guarantees of some kind.}
{286}{}{Huh, what kind of fantasy world do your people live in? There are no guarantees, there are only agreements. And you know what - we *can* agree.}
{287}{}{Really?}
{288}{}{There are a lot of unemployed people left in the city. My factory will provide work for all of them in the near future. We could also provide your Villa with various services at a very low cost. You'll restore the village, strengthen your lands, and we'll earn a little money, or, corn I guess. And more importantly, we'll avoid neighborly 'conflicts'.}
{289}{}{I'll pass on your proposal to the community. Perhaps they'll agree.}
{290}{}{I'm afraid the elders won't like this. Bye.}
