{100}{}{You see the Withered One.}
{101}{}{You see a withered creature who stares at you with crazed eyes.}
{102}{}{I'll eat you and become stronger... but I hate myself for it.}
{103}{}{The Withered One attacked you when your back was turned!}
{104}{}{My horns are starting to hurt. Better go!}

{110}{}{Pain... It hurts...}
{111}{}{The pain is gone... Now I feel weak...}

#Encounter with the Ragged Creature
{200}{}{(Before you is a creature in rags, vaguely reminiscent of a man. His crazed eyes are filled with fear and hunger as they look at you.)}
{201}{}{Ahhh! A demon! Die! Die!}
{202}{}{I mean no harm. Who are you?}
{203}{}{Back up, freak. Tell me who you are.}
{204}{}{(grabs his head; you notice several horn-like growths protruding from his scalp)}
{205}{}{Are you from around here?}
{206}{}{Speak when people talk to you.}
{207}{}{(rises and looks around) Yes... yes. But you? Where are you from? Haven't seen a normal person in ages. And those clothes... I remember now. Yeah. Vault Dwellers wore that. (circles around, examining you) I never got into a Vault. That's why I'm here.}
{208}{}{Hold on, friend. I've got a ton of questions for you.}
{209}{}{Stay still, freak. Try anything funny, and I'll end you.}

{220}{}{(covers face with hands) What do you want? The city's ruined. No one's here. Leave.}
{221}{}{Alright, I'm leaving. Don't get any ideas about following me.}
{222}{}{(rises and looks around) Yes... yes. But you? Where are you from? Haven't seen a normal person since... (circles around, examining you) since the people took shelter in the Vaults. I didn't make it in, so here I am.}

#About Me
{230}{}{Who are you? What are you? You look like a ghoul, but those horns... Are you a demon?}
{231}{}{Demon? (looks away) That's what we call each other... I was once a man... a farmer. I poured milk onto the ground so prices wouldn't fall. I buried potatoes and vegetables... How stupid.}
{232}{}{Is there anyone else here besides you?}
{233}{}{Was this where your farm was, among these ruins?}
{234}{}{How did you manage to survive?}
{235}{}{Survive? No. This isn't even surviving. This is hell. We're all living in hell. We can't die. Radiation made us like this. This is our punishment. Some were lucky to be at the epicenter of the nukes. But not me.}
{236}{}{What happened to the other survivors?}
{237}{}{There was a big city here, wasn't there?}
{238}{}{What are you doing now? There doesn't seem to be much to scavenge.}
{239}{}{There's no food here! We used to eat what we found in the ruins. Now we eat each other. But rarely. We've grown used to hunger.}
{240}{}{So there are others here... like you?}
{241}{}{No wonder -- there are ruins everywhere.}
{242}{}{Farmer, you say? Wait a minute, when was this?}
{243}{}{It was a long time ago, when the bombs fell. You weren't born yet.}
{244}{}{Did you really see the Great War with your own eyes?}
{245}{}{Did anyone else survive that inferno besides you?}
{246}{}{By the way, what kind of city was here before?}
{247}{}{That's not what I wanted to hear. Let's talk about something else.}

### About Packs

{250}{}{There aren't many of us left. But even now, we have a division between the rich demons, and poor ones like me. The rich demons glow in the dark. They keep everyone else in line and take the best for themselves.}  
{251}{}{[Listen]}  
{252}{}{They used to be important and influential. Now, as demons, they still crush others underfoot. (laughs) Fine, let them shine and live forever in torment.}  
{253}{}{[More]}  
{254}{}{This is a hell worse than death. They can't die, even if they want to. This is their punishment -- immortality. Tormented by their sins, they must suffer forever.}  
{255}{}{I guess your a 'demon' too? Like those glowing ones?}  
{256}{}{What kind of place turns people into this?}  
{257}{}{So you were kicked out of the pack? Is that why you're so skinny?}  
{258}{}{The pack shares food. You can't survive here alone. And the glowing ones take all the best for themselves. When there's no food, they eat the weakest... like me. They'll eat me next, and I'll be freed from torment. But I don't want to be eaten. That's why I'm hiding.}  
{259}{}{I think I'm starting to understand. But let's change the subject.}  
{260}{}{So there aren't any normal people here, are there?}  
{261}{}{Oh, there are! Someone lives in the Church. In the evening, there's a light on. But I haven't seen who it is. Many want to get there, but they can't.}  
{262}{}{Do you know a safe way to this church?}  
{263}{}{I could show you. But they'll eat me there. And they'll eat you too. But if you're determined... go through the sewers. It's the safest way.}  
{264}{}{Interesting. But you must know something else.}  
{265}{}{Who else lives in these ruins besides you?}  
{266}{}{What is this city?}  

### About the City

{270}{}{(looks around for a long time) Long ago, there was a big city here. It was called Mexicali. A beautiful city. Then the atomic bombs fell...}  
{271}{}{[Listen]}  
{272}{}{They turned it into fields of burnt trash and scrap metal. The Reds did it. They aimed at aircraft factories but destroyed everything else. Now, 'cause of the radioactive fallout, there's no life left here. Even the grass doesn't grow.}  
{273}{}{[More]}  
{274}{}{Everything here is contaminated with radiation. That's why I have mutations like these. (touches horns)}  
{275}{}{But how did you manage to survive in this hell?}  
{276}{}{So you're not alone here? Are there other survivors in the ruins?}  
{277}{}{Why is this city destroyed? Was it from the Great War?}  

### About the War

{280}{}{Stupid people did this. They turned the planet into a wasteland, used up all the oil, and started taking the last crumbs from each other. The cities and nature we loved have disappeared from the face of the Earth.}  
{281}{}{[Listen]}  
{282}{}{Look at this giant ant. There were never any like this before. It's not right. Ants should be... small. Smaller than the nail on your little finger. But they're not like that anymore.}  
{283}{}{[More]}  
{284}{}{It's because of the radioactive fallout... Shh! Can you hear that? Those are demons howling in pain. When night comes, all demons feel pain.}  
{285}{}{Are these demons the rest of the survivors?}  
{286}{}{Tell me what this city was like before the bombing.}  
{287}{}{Okay, let's stop here. I need to let this information sink in.}  
{288}{}{And you? I guess your a demon too?}  
{289}{}{Are you the only one alive? Is anyone else here?}  

### About the Brotherhood of Steel

{300}{}{Have you seen a Brotherhood of Steel convoy? A squad... of soldiers. They were supposed to pass this way.}  
{301}{}{Oh, my head hurts! So painful...}  
{302}{}{Don't try to fool me. Tell me what happened to the soldiers!}  
{1302}{}{Your tricks don't work on me. Tell me what happened to the soldiers!}  
{303}{}{Sorry, but this is very important. Try to remember.}  
{304}{}{Ah, those pale-skinned ones couldn't get out of our underworld. Hehe, like the others, they'll have to burn here forever.}  
{305}{}{So they're alive?}  
{306}{}{They're being kept in the old church. But you can't get there. No, no, don't try! There are crowds of demons around and no one knows what's happening inside. It's a cursed place, the lair of Lucifer himself. No one ever returned from there.}  
{307}{}{Looks like this won't be easy...}  
