{100}{}{You see Garrett.}
{105}{}{Bastards! Gonna smash you for what you did to my friends!}

{200}{}{Huh? Another normie? And you come right to me? Ha! You stupid or what?}
{201}{}{What is this place? And who are you?}
{202}{}{Are you wearing a fat, green, troll costume?}
{203}{}{Lower your weapons and follow me. Levi will speak to you.}
{204}{}{Okay. Take me to Levi. I want to ask him a few questions.}
{205}{}{No, big guy, I'll only talk to you.}
{206}{}{I said, go to Levi! You don't listen, I break your legs, drag you there myself, and toss you like trash.}
{207}{}{Okay, I'm going, just don't hit me.}
{208}{}{Just try it, you big freak.}
{209}{}{Please listen to me first. I come in peace.}
{1209}{}{Please listen to me first. I come in peace.}

{210}{}{What you want, normie?}
{211}{}{Nothing, bye.}
{212}{}{Yes, sir.}

{220}{}{Let's talk. What's your name?}
{221}{}{Garrett. I don't talk to normies.}
{222}{}{Garrett. I don't trust your kind.}
{223}{}{}
{224}{}{Okay. It's good that we were able to meet. Bye.}
{225}{}{Why? Did something happen in the past?}
{226}{}{Shut up before I smash you.}
{227}{}{Your subordinates aren't talkative either. Why so much anger towards people?}
{228}{}{Mad? No. Master taught us respect for life. But normies like you chased us from the West. Now, if you don't shut up, I'll shut you up.}
{229}{}{Okay, okay...}
{230}{}{You always been this... different?}
{231}{}{I was like you once. Had feelings - fear, hate, envy. Master gave me new life. I got rid of human crap. Then you normies killed the Master.}
{232}{}{Sorry, didn't mean to piss you off. I'll go.}
{233}{}{By "new life," you mean with mutagen?}
{234}{}{Mutagen's just part of it. Whole thing takes a year. I trained, fasted, meditated in ruins. You don't get mutagen if you're not ready.}
{235}{}{Looks like you've been through a lot. It's time for me to take care of my problems too. Bye.}
{236}{}{Master -- who is this?}
{237}{}{Who is this Master of yours?}
{238}{}{He's my god.}
{239}{}{That... explains a little.}
{240}{}{Ha! Stupid normie. You'll never see God. You killed him!}
{241}{}{Killed a god? How?}
{242}{}{No god now. We're alone. That's it.}
{243}{}{Okay. Let's leave it at that for now.}
{244}{}{So Levi is in charge here?}
{245}{}{He's the hand of my god. I'd die for him.}
{246}{}{Thought you were the toughest one here.}
{247}{}{Your loyalty's impressive.}
{248}{}{Levi saves us. Without him, no future. I serve him like I served the Master. But you, normie, you can't get our pain.}
{249}{}{Okay, let's assume that's true.}

{250}{}{Hey, Garrett. How's guard duty?}
{251}{}{All quiet. My guys will protect you if needed.}
{252}{}{Seems like it's the other way around for now.}
{253}{}{Ha! You got a point, normie. But you could use help. Here, take this radiator gun.}
{254}{}{Radiator? I guess this is one of Levi's. Can you teach me how to use it?}
{255}{}{You normies need to be taught everything. Okay, I'll show you... if you bring me some decent food.}
{256}{}{Okay, I'll look for something.}
{257}{}{Food? Around here? You're asking for a lot, greenie.}

{260}{}{You promised to teach me how to shoot the radiator gun.}
{261}{}{I'm hungry!}
{262}{}{Okay. I'll show you. It's not difficult.}
{263}{}{Then let's not waste time. I don't want to end up in a situation where you get hungry again in the middle of training...}
{264}{}{Great, but let's get to that a little later.}
{265}{}{Actually, I'm not very interested in energy weapons. But this gun looks impressive. Show me how to handle heavy weapons!}
