{100}{}{You see a lab assistant.}
{101}{}{You see a mutated man. His face looks like melted wax.}

{110}{}{It's surprising they let you in here.}
{111}{}{I don't have time for conversations with pagans.}
{112}{}{I don't have anything for you.}
{113}{}{Leave me alone or I'll call my green brothers.}
{114}{}{What's wrong with your skin? Well, you're not winning any beauty contests.}
{115}{}{I'm baffled by how you normals manage to survive in this world.}
{116}{}{Desert dwellers are clueless.}
{117}{}{Listen to Levi.}
{118}{}{I don't trust you or any strangers like you.}
{119}{}{Our people have suffered greatly at the hands of the Norms...}

{120}{}{Oh, come on in, buddy, grab a seat.}
{121}{}{Even though you're a pagan, at least you're harmless.}
{122}{}{Want me to whip up some radioactive coffee?}
{123}{}{Apologies for my green brothers; they're a bit out of touch with regular folks.}
{124}{}{What's up with your skin? How'd you manage to keep it?}
{125}{}{You normies are really holding your own in this new world.}
{126}{}{People astound me with their resilience.}
{127}{}{Listen to Levi; he was practically handpicked by God himself!}
{128}{}{I trust you. But those Brotherhood of Steel fools? Not so much.}
{129}{}{Our people have been through hell. You couldn't possibly understand.}
