{100}{}{You see Paladin Barkley.}
{101}{}{This thick-skinned warrior has an unwavering face, ready for battle.}
{102}{}{Change formation.}
{103}{}{Thanks, Doc.}
{104}{}{Traitor! You'll die like a lousy dog!}
{105}{}{Bastards! You'll pay for my friends' deaths!}
{106}{}{M-mutants, damn it! Just a bit more and I'll start shooting. Are you with them?}

{110}{}{I can't believe my eyes! How did this happen?}
{111}{}{Welcome to the Brotherhood.}
{112}{}{This isn't why I serve as a paladin.}
{113}{}{Hmm, looks like our recon was off by a few zeros on the enemy count.}
{114}{}{Ah, reminds me of old times...}

#Counter dialogue
{200}{}{Grr, damn it... I almost blasted you. Thought you were another mutant. You part of the support team?}
{201}{}{What team? What are you talking about?}
{202}{}{Damn. So the Brotherhood didn't send you? Bad news. What are you doing in this damned place?}
{203}{}{I'm just scavenging for useful things. Deserted ruins usually have plenty.}
{204}{}{Ugh. So you're a scavenger? (sigh) Looks like my luck ran out last year.}
{205}{}{What's going on?}
{206}{}{I'm looking for someone. But that's personal.}
{207}{}{Okay... Let's say that's true. Would you help find someone else for me?}
{208}{}{Are you missing someone?}
{209}{}{I responded to the radio request for help.}
{1209}{}{I responded to the radio request for help.}
{210}{}{At least some good news today.}
{211}{}{Tell me what happened.}
{212}{}{You should have shot, idiot. Now it's my turn...}
{213}{}{So you're from the Brotherhood of Steel? I hate all of you. Die, scum!}

{220}{}{Yes, the Brotherhood sent me on a rescue mission.}
{221}{}{Hmm. I don't remember you. Show your tag.}
{222}{}{Tag? I'm not Brotherhood. I'm just hired help.}
{223}{}{I see. I heard the Brotherhood in Arizona isn't doing too well. Sad. Where's the rest of your team?}
{224}{}{Who are you talking about? I'm alone.}
{1224}{}{Who are you talking about? I'm alone.}
{225}{}{Damn it! What are they thinking? How can one mercenary handle this? Though a small group does have a tactical edge in ruins... Fine, just don't get in my way.}
{226}{}{So what happened?}
{227}{}{Um... Here, I have a Brotherhood tag. Believe me now?}
{228}{}{I recognize that name. You have one chance to explain your lies.}
{229}{}{Um... Screw it. Die!}
{230}{}{Yes, I'm not from the Brotherhood. I just thought you'd shoot me...}
{231}{}{Ugh, you snotty shit, how can I trust you now?}
{232}{}{Can you tell me what happened so we can help each other?}
{233}{}{Listen, I know you're in trouble. Now it doesn't matter who serves where. We need to help each other.}
{234}{}{Okay. Don't try to fool me again. I don't tolerate lies.}
{235}{}{Eh, okay. Maybe then you can tell me the truth about what you're doing here?}

{240}{}{My squad was ambushed by local ghouls... 'reavers'. In the chaos, I lost the rest of my team and can't contact them. Plus, I injured my leg during the fight.}
{241}{}{You're military, right? And you're fully geared too.}
{242}{}{Got it. Mission failed before it even started.}
{243}{}{No one expected resistance in these ruins. We thought it was deserted, so we walked through the city to avoid mutants in the desert.}
{244}{}{Okay. So what's your plan?}
{245}{}{I need to gather my squad, if there's anyone left. And patch myself up to move on to the objective... Hey, do your civic duty - can you help me do this?}
{246}{}{Of course. I can't leave someone in trouble.}
{247}{}{I knew I could count on you. If I complete my mission, I won't forget it.}
{248}{}{I hope not.}
{249}{}{Look's like your luck really ran out, soldier. Time to scavenge your corpse...}
{250}{}{You're talking about a dangerous job. Why should I take the risk?}
{251}{}{Don't worry about payment. When we reach the base, you'll be generously rewarded.}
{252}{}{I really hope so.}
{253}{}{Oh, by the way, my name is Paladin Barkley. Now go check around for my squad. But be careful on the way out; I set a couple of traps.}
{254}{}{I'm on it.}
{255}{}{I'm not interested in rewards. My village needs protection, and allies.}
{256}{}{If we get to the base, I'll talk to the elders about your problem. Meanwhile, help me out.}
{257}{}{Okay.}

{260}{}{Show me how to get out of here safely.}
{261}{}{There are several traps in the corridor. Watch your step carefully.}
{262}{}{Thanks.}
{263}{}{Listen, I have a lot of questions.}

#Re-dialogue
{300}{}{Report the situation.}
{301}{}{Everything is calm.}
{302}{}{Yes?}
{303}{}{We need to talk.}
{304}{}{What do you want to know?}
{305}{}{Enough talk.}
{306}{}{Stop talking. We have no time for this now.}
{307}{}{Yeah, you're right.}
{308}{}{A bit more and I'll shoot all these mutants!}
{309}{}{That's all for now.}

{310}{}{So, what should I do?}
{311}{}{Treat my injury and find the rest of the team. After that, we'll discuss the plan from there.}
{312}{}{Got it.}
{313}{}{Serious wound. I may not be able to handle it.}
{314}{}{Just find some medicine. They was some among our convoy's things. Hurry before the ghouls get everything.}
{315}{}{How did you get into this?}
{316}{}{Caught in a trap. These ghouls set traps in our path and created a smoke screen. Sons of bitches, caught like a rookie...}
{317}{}{I see. Let's go over the plan again.}
{318}{}{Starting the task.}
{319}{}{I'm going on a search.}

{320}{}{Who else was in the party?}
{321}{}{Several people. Half are definitely dead; I don't know about the rest.}
{322}{}{Continue.}
{323}{}{I'm gonna go search around.}
{324}{}{I last heard from the squire near the supermarket, but then I lost contact.}
{325}{}{The knight held the line at the ambush point, near the monument.}
{326}{}{Diana from the Followers of the Apocalypse was with us. I heard her screams; the ghouls were dragging her somewhere.}
{327}{}{Who else was on the team?}
{328}{}{What if they're all dead?}
{329}{}{Then it's my duty to collect their dog tags to inform command and honor their memory.}
{330}{}{Where did the convoy attack happen?}
{331}{}{Northwest, on Highway 5, next to a monument.}
{332}{}{I see.}
{333}{}{How did the ghouls defeat an armed convoy?}
{334}{}{These ghouls might be wild, but they're smart enough to fight. Their long life in the ruins taught them a lot.}
{335}{}{What did they do?}
{336}{}{We were ambushed. The ghouls, they call them reavers around here I guess, set traps and lured us to a spot that was hard to defend. They surrounded us and threw bags of dust. A smoke screen rose, and everyone got dragged away one by one.}
{337}{}{Continue.}
{338}{}{We killed a few, but there were too many. When the frontal attack began, only I managed to hold my own. I had to retreat... Damn, if only I'd had time to get on the Power Armor!}
{339}{}{I'm so sorry.}
{340}{}{We all fail, paladin. You're no exception.}
{341}{}{Anyone else?}
{342}{}{Okay. Let's see what's left there.}
{343}{}{Your wound is serious. What can I do?}
{344}{}{I'm almost back to normal. We just need to find the missing squad members. After that, we'll discuss what to do next.}
{345}{}{We need to find Diana. She might still be alive and needs help.}
{346}{}{We need to find Diana. She might still be alive and needs help. And I could use some patching up too.}
{347}{}{I found the knight's body. I'll keep searching.}
{348}{}{I found the squire's body. I'll keep searching.}

{350}{}{Your brothers are dead. Here's their tags. I'm really sorry.}
{351}{}{They died fighting like true warriors. May their memory be honored... What about the girl? A civilian from the Followers of the Apocalypse was with us.}
{352}{}{I don't know anything about her.}
{353}{}{I need to know for sure. Command instructed me to escort her. I can't disobey orders by leaving her.}
{354}{}{I'll try to find out what happened to her.}
{355}{}{Diana is being held in the old church.}
{356}{}{Held? By who? These reavers can barely speak.}
{357}{}{No, not them, others. There's some kind of... cult.}
{358}{}{I don't understand. Cult? Maybe this cult controls the reavers? We need more information. But saving Diana is top priority.}
{359}{}{I'll think about how to do that.}
{360}{}{Diana is dead. That's for sure.}
{361}{}{Bad news. I'll be getting a serious reprimand, maybe even a tribunal over this girl. Damn, I don't want to go back to that stuffy bunker in California. Thanks for the help, pal.}
{362}{}{Is that all you've been looking for?}
{363}{}{Diana is waiting for us at the exit. You can talk to her there.}
{364}{}{Great job, pal. I'm in your debt.}
{365}{}{Is that all you've been looking for?}
{366}{}{Diana left town. She didn't want to stay in this hell.}
{367}{}{She left without me? Damn it. I risked my life for her... Fine, let her go. She's not my concern anymore.}
{368}{}{Is that it for here then?}
{369}{}{I found Diana.}
{370}{}{What's her condition? Is she alive?}
{371}{}{I'll go find the others.}
{372}{}{They died fighting like true warriors. May their memory be blessed...}
{373}{}{That's right. But I can't return to base without completing the main task.}
{374}{}{What's the main task?}
{375}{}{Delivering Power Armor. It was the main cargo we carried to the base in Puerto. Now these reavers have it. A huge loss.}
{376}{}{There's no Power Armor where you were attacked. The mutants dragged it to the old church.}
{377}{}{So we need to get it back. You already know how to get in and out safely. I'm relying on your resourcefulness, friend.}
{378}{}{It won't be easy, but who else if not me? I'm on it.}
{379}{}{I have the armor. If not for it, I wouldn't have gotten out alive.}
{1379}{}{I have the armor. If not for it, I wouldn't have gotten out alive.}
{380}{}{Delivering Power Armor. We were taking it to the base in Puerto. You'll need to return it to our base.}
{381}{}{Great job. But you'll need to return it to our base.}
{382}{}{What, give away such cool armor? Isn't that asking a little much?}
{383}{}{This is Brotherhood of Steel property. Any problem with that, civilian?}
{384}{}{Yes. Problem. With you. The armor is mine now!}
{385}{}{No, no problem. I'll gladly get rid of the extra burden.}
{386}{}{Of course, I'll gladly get rid of the extra burden.}
{387}{}{Thanks for your help. You'll make a great fighter. When I get to the base, I'll tell command everything. For now, take the armor to the quartermaster. I need to regain my strength before heading out.}
{388}{}{See you at the base, Paladin Barkley.}
{389}{}{Sorry, but I already took the armor to the quartermaster in Puerto.}
{1389}{}{Sorry, but I already took the armor to the quartermaster in Puerto.}
{390}{}{Thanks for your help. You'll make a great fighter. When I get to the base, I'll tell command everything. For now, I need to regain my strength before heading out.}
{391}{}{See you at the base, Paladin Barkley.}
{392}{}{Thanks for your help. You remind me of one of the Vault Dwellers who helped us against super mutants in California. No civilian has ever been this useful to the Brotherhood. Keep it up, fighter.}
{393}{}{It's worth trying for the Brotherhood. Shall we continue our journey?}
{394}{}{That's right. Now I can return to base with a clear conscience. Though I can't imagine the shame awaiting me there. Damn. The entire squad was killed and the cargo lost. This will be remembered for a long time, even if the tribunal clears me of any wrongdoing.}
{395}{}{Your brothers will understand, I'm sure.}
{396}{}{You're definitely in trouble. No doubt about it.}
{397}{}{Thanks for your help. You'll make a great fighter. When I get to the base, I'll tell command everything. For now, I need to regain my strength before heading out.}
{398}{}{Perhaps we'll see each other again. Good luck.}
{399}{}{Then come with me? I need combat support.}

#Team
{400}{}{Won't you come with me? I could use the protection of an experienced warrior.}
{401}{}{I have no doubt. But as you can see, I'm not in the best shape right now. Wounded like this, I can hardly defend myself.}
{402}{}{I see. But you can at least talk?}
{403}{}{Okay, I'll do it on my own.}
{404}{}{I have no doubt. But moving around together is going to attract more attention from the ghouls. That isn't the best tactic right now.}
{405}{}{If you were soldiers, I'd just take command. But with this group, we lose all tactical advantage. Get rid of the 'extra weight' if you want my help.}
{406}{}{Then just forget it.}
{407}{}{Okay, I'll talk to the others.}
{408}{}{I owe you one. If you're heading to our base in Puerto, I'll go with you.}
{409}{}{Alright. That's where I'm heading. Let's go together then.}
{410}{}{No. I'm heading a different way. Maybe next time our paths cross.}
{411}{}{We need to put away our weapons now.}
{412}{}{Are you out of your mind? Trying to get me killed?}
{413}{}{Just a stupid idea. Forget it.}
{414}{}{No, we need to show our friendliness to avoid a confrontation.}
{415}{}{Hmm. Okay. But keep in mind -- I can draw my gun in half a second.}
{416}{}{That's great.}
{417}{}{Let's get your old armor back. Give this one to me.}
{418}{}{With pleasure. My old one was more my size.}
{419}{}{Great.}
{420}{}{Defend this position. I need to go far.}
{421}{}{Good idea. Scout around while I clean my gear.}
{422}{}{Uh, okay.}
{423}{}{Get ready. We can move on.}
{424}{}{Lead the way. I hope you know a safe route.}
{425}{}{Uh, sure. Let's go.}
{426}{}{It's time to say goodbye. Our paths split here.}
{427}{}{Are you sure? Okay. But don't forget about Barkley, old man.}
{1427}{}{Are you sure? Okay. But don't forget about Barkley, sister.}
{428}{}{I won't forget. See you later, Paladin Barkley.}
{429}{}{What am I doing, really? I need you so I don't become the glow ants' breakfast.}
{430}{}{Come with me. I need the protection of an experienced warrior.}
{431}{}{But without your help, I could die.}
{432}{}{Believe me, you have a better chance staying in the shadows, alone. I'll attract too much attention from the ghouls.}
{433}{}{I see.}
{434}{}{I definitely can't do this without you. If you're not gonna help, then I'm heading out.}
{435}{}{I knew I couldn't rely on you... Okay, my leg doesn't hurt so much anymore, I can move.}
{436}{}{That's more like it.}
{437}{}{You know, limping like that is really going to draw attention. I'd better go alone. Bye.}
{438}{}{I owe you one. If you need protection or an escort, I'm at your disposal.}
{439}{}{Come on then, we have a long and dangerous road ahead of us.}

#Place
{450}{}{What do you think of this place?}
{451}{}{Nothing special. No point in lingering here.}
{452}{}{I see.}
{453}{}{This is a Brotherhood outpost. Welcome. But keep in mind, it's a high-security facility. Command won't like you hanging around without permission.}
{454}{}{I still can't believe our fort was destroyed. The best of the best served there.}
{455}{}{Another ruin of the Old World. Most of California's cities lie in ruins like this.}
{456}{}{After Inferno, this place seems like paradise. Looks like the Brotherhood of Steel was involved here.}
{457}{}{Looks like the Tinsmiths live here. The Brotherhood had a contract with them to maintain the outpost.}
{458}{}{Quite a growing city. In California, only the Hub can compare. It's good to see civilization getting back on its feet.}
{459}{}{I read about this church in the scribes' reports. The local leader seems to be on good terms with the Brotherhood.}
{460}{}{Sorry, this is classified information. I can't discuss it with you.}
{461}{}{Not a bad colony. Though they still have a long way to go before matching the order of our Brotherhood.}
{462}{}{This is not a vault. It's a crypt.}
{463}{}{It's an outpost. Of course, it can't compare with the main base. But it's better than nothing.}
{464}{}{I would tell you a lot, but you already know everything perfectly, brother.}
{1464}{}{I would tell you a lot, but you already know everything very well, sister.}
{465}{}{I'm kind of at a loss. Without the Brotherhood, I guess I'll have to just help people like you.}
{466}{}{This is the fort you were heading to. Aren't you happy?}
{467}{}{Total disappointment. Headquarters in California will be furious once they find out how things are here. You know, I wouldn't mind going with you to the some of nearby settlements. I'd like to clear my head a bit before returning to duty.}
{468}{}{Inferno still bothers you huh? I Understand.}

#Brotherhood
{470}{}{Tell me about your Brotherhood.}
{471}{}{I can't share much. Some information might have strategic value.}
{472}{}{Then let's go.}
{473}{}{Where is the Brotherhood's main base?}
{474}{}{I see. That's all I wanted to know about the Brotherhood.}
{475}{}{Where is your local base?}
{476}{}{On the coast of the gulf, at Rocky Point. Locals call it Puerto.}
{477}{}{You'd have to ask headquarters about that. I'm just a soldier, following orders.}
{478}{}{What are you doing in the Sonoran Desert?}
{479}{}{Headquarters is far away in California. Here in the Sonoran Desert, we have a small fort.}
{480}{}{I don't want to talk about it now. Such a ridiculous defeat in Puerto only fills me with rage.}
{481}{}{I can't believe it...}
{482}{}{Are you okay?}
{483}{}{My brothers and sisters... Such a ridiculous death... What could have happened?}
{484}{}{Probably the quartermaster's negligence or some kind of leak.}
{485}{}{Nonsense! We have always treated weapons and equipment with care! I refuse to believe this was a staff mistake. It could only be sabotage.}
{486}{}{Well, you have a lot of enemies...}
{487}{}{Okay, sorry for yelling. After the events in Inferno, receiving such a blow to the Brotherhood is too much.}
{488}{}{I understand. But now you are free from regulations and orders, aren't you?}
{489}{}{I don't think I can live a rural life in these wild lands. We should move on. Look, I'm still with you, pal.}
{490}{}{Let's go.}
{491}{}{Apparently, someone really didn't like your Brotherhood.}
{492}{}{Exactly! It could only be sabotage.}
{493}{}{I blew up a couple of torpedoes in the hold. Are you not happy with this?}
{1493}{}{I blew up a couple of torpedoes in the hold. Are you not happy with this?}
{494}{}{Why?! What did the Brotherhood do to you?!}
{495}{}{You have caused too much trouble in Sonora. You don't belong here.}
{496}{}{I don't even know. I just wanted to see the big explosion.}
{497}{}{I think I pressed the wrong button. I don't know how this happened.}
{1497}{}{I think I pressed the wrong button. I don't know how this happened.}
{498}{}{You crazy redneck! You should have died in the womb!}
{499}{}{Well, well.}
