{100}{}{You see a wild kid.}
{101}{}{You see a young savage from the Jackal tribe.}
{102}{}{*Hissing*}

#Response
{200}{}{*Bares teeth*}
{201}{}{*Hissing*}
{202}{}{Woof!}
{203}{}{Stay back or I'll bite you.}
{204}{}{*Whines and shrinks away from you*}
{205}{}{Rrrr!}

{210}{}{*Snorts*}
{211}{}{*Sniffs you*}
{212}{}{Woof!}
{213}{}{Woof-woof!}
{214}{}{My teeth are sharper than yours.}

{220}{}{*Cheers of joy*}
{221}{}{*Jumps to show off*}
{222}{}{Play with me.}
{223}{}{Let's do somersaults?}
