{100}{}{You see Black Fang.}
{101}{}{You see a formidable warrior from the Jackal tribe.}
{102}{}{}
{103}{}{You shouldn't have made me angry, you freak.}
{104}{}{I-is this s-some kind of j-joke?!}
{105}{}{I'll kill you!}

#Floating lines
{120}{}{Everyone should fear me!}
{121}{}{I won't forgive, I won't forgive, I won't forgive!}
{122}{}{Mad Bitch will crawl at my feet.}
{123}{}{Someday I will lead the tribe.}
{124}{}{No one dares take my place!}
{125}{}{Someday I'll bring the Mad Bitch to her knees.}
{126}{}{}
{127}{}{}
{128}{}{}
{129}{}{}

#Dialogue at the first meeting
{200}{}{You're trapped! Don't even try to resist. Now you are my prey. Sha-a-ah!}
{201}{}{I'm not here to hurt anyone.}
{202}{}{Give your head a shake, moron. You haven't trapped anyone.}
{203}{}{You will die in agony for your words!}
{204}{}{Okay, fool, time for a lesson...}
{205}{}{Yes... It'll be better that way. Now let's go. I want to show you to Mad Bitch. You are my prey. Everyone should know this!}
{206}{}{Okay, lead the way.}
{207}{}{The Mad Bitch has gone crazy, letting an outsider into our dens. Just give me a reason and I'll rip your heart out with my claws!}
{208}{}{It won't come to that.}
{209}{}{You! You won't escape again, you piece of meat!}
{210}{}{We'll see about that later...}
{211}{}{What do you want?}
{212}{}{Nothing. Bye.}
{213}{}{Stop, I really don't want to hurt you!}
{214}{}{You're trapped, outsider... Arrr! A man with iron skin! Who are you? What do you want?}
{215}{}{I need you dead. Take off your capes and hand over the spear.}
{216}{}{Everyone here! An evil iron spirit is in the dens!}
{217}{}{You know, you shouldn't have done that...}
{218}{}{Who's your boss?}
{219}{}{Do you want to talk to our leader? That's the Mad Bitch. Let her deal with you, then I'll see you off.}

#Necklace
{220}{}{That necklace of bullets doesn't suit you.}
{221}{}{W-what are you talking about? Spare me your vile speech. I took this trophy from the bodies of Rangers. It speaks of my deeds to the pack.}
{222}{}{It also says you're a fool for flaunting enemy gear.}
{223}{}{Gr-rm! (Angrily rips off the necklace and throws it at your feet) I don't need the things of my enemies!}
{224}{}{That's it.}
{225}{}{Should we play for this thing?}
{226}{}{Then forget it.}
{227}{}{Bite your tongue, puppy, or I'll rip it out of your mouth!}
{228}{}{Let's play by my rules. If you lose, I'll take a glass of your blood. If you win, the trophy will be yours.}
{229}{}{Let's play.}
{230}{}{What kind of wager is this? I pass.}
{231}{}{Gr-rm! (Angrily rips off the necklace and throws it at your feet) You win, outsider!}
{1231}{}{Gr-rm! (Angrily rips off the necklace and throws it at your feet) You win, bitch!}
{232}{}{I guess I'll leave you until you calm down...}
{233}{}{Hah! Black Fang is the winner again! I am the winner!}
{234}{}{Hey, wait, you're not actually going...}
{235}{}{Games are not for warriors. Only for pups like you.}
{236}{}{Whatever.}
{237}{}{No need. I'll just kill you all, one by one. And I'll start with you, moron.}

#Grooming services
{240}{}{You look like you're in rough shape. Is guarding the entrance that tough?}
{241}{}{I protect the pack from outsiders and get food! Others look up to me. This duty is exhausting, but I must do it. After all, I will lead the pack when the Mad Bitch leaves her post.}
{242}{}{You're too tense. Just relax a little.}
{243}{}{Ah, I see.}
{244}{}{Relax with an outsider? Okay, it will make me rise even higher in the eyes of the pack.}
{1244}{}{Relax with an outsider bitch? Okay, it will make me rise even higher in the eyes of the pack.}
{245}{}{Of course, you're a leader. Sit down, I'll rub your back...}
{246}{}{Something's gone wrong.}
{247}{}{I don't trust outsiders. And you are an outsider.}
{248}{}{Yeah, I don't trust you either.}
{249}{}{Your "grooming" services have raised your reputation in the eyes of the Jackals.}

#Questions
{250}{}{Who are you?}
{251}{}{I am a warrior. The pack calls me Black Fang.}
{252}{}{How do you feel about Mad Bitch?}
{253}{}{Insolent bitch. Sometimes I'm ready to pounce on her and strangle her with my claws. But she is devoted to the pack. Even if she leads it astray.}
{254}{}{}
{255}{}{}
{256}{}{I see.}
