{100}{}{You see the mutant Sherman.}
{101}{}{You see a horribly disfigured man.}
{102}{}{A mutant suddenly appears from the shadows.}
{103}{}{Who opened the gate?}
{104}{}{W-what's that sh-noise?}
{105}{}{Hmmmm...}

{110}{}{Woah, we have a stranger!}
{111}{}{Look at this knife. Lean a little closer...}
{112}{}{Come closer, don't be afraid}
{113}{}{We'll have to sort through the bones again...}
