{102}{}{This poor guy is tied to a post for everyone to see. He's gone delerious from the heat, muttering to himself.}
{103}{}{A man can't be repaired. Unfortunately.}

{200}{}{W-water! I beg you, give me some water!}
{201}{}{[Pass by]}
{202}{}{[spit on the ground] There's your water.}
{203}{}{Mercy, senor! I'm dying of thirst!}
{1203}{}{Mercy, senora! I'm dying of thirst!}
{204}{}{You should've thought of that before you did whatever you did. Goodbye.}
{205}{}{Okay, I'll get you some water.}
{206}{}{Whoa, of course, I'll get you some water right away.}

{210}{}{Gulp, gulp, ah, water! I've never been so happy to taste plain water. Thank you, sir, you're saving my life.}
{1210}{}{Gulp, gulp, ah, water! I've never been so happy to taste plain water. Thank you, senora, you're saving my life.}
{211}{}{Tell me, why are you tied to this post?}
{212}{}{Who left you here to suffer in the sun?}
{213}{}{It was Frank. This is how he punishes anyone who steps out of line.}
{214}{}{What did you do wrong?}
{215}{}{Isn't this punishment a bit harsh?}
{216}{}{I just had too much tequila... and got rowdy. My fault, I admit. But I would've gotten away with it if I hadn't yelled at Frank himself. That was a mistake.}
{217}{}{Well, I guess Frank had a reason. At least you admit what you did.}
{218}{}{Frank can't do this. You didn't do anything wrong.}
{219}{}{I realize I was wrong. It won't happen again. If only they'd forgive me... Ahh, my head is pounding...}
{220}{}{Do you want me to untie you?}
{221}{}{Okay.}
{222}{}{No, senor. Thank you, but Frank won't like it. He'd tie me up again for a day, maybe two. There's no need to provoke him, sir. That's how it works here -- either you follow the rules, or you're forced to. I've learned this the hard way and won't make that mistake again.}
{1222}{}{No, senora. Thank you, but Frank won't like it. He'd tie me up again for a day, maybe two. There's no need to provoke him, senora. That's how it works here -- either you follow the rules, or you're forced to. I've learned this the hard way and won't make that mistake again.}
{223}{}{Who is Frank?}
{224}{}{He's our sheriff. Probably the most important person in town. He's in the jail near the front gate.}

{230}{}{Thank you, sir, you're saving my life.}
{1230}{}{Thank you, senora, you're saving my life.}
{231}{}{Hang in there.}
{232}{}{I can untie you.}
