{100}{}{You see Chipo.}
{101}{}{You see a local child.}
{102}{}{Wow, is that a real weapon? Do you have permission?}
{103}{}{Wow, is that Power Armor? I thought it was Frank's idea.}
{104}{}{What are you up to?}
{105}{}{I miss Pinky.}
{106}{}{Meanie! Why did you do that?}
{1106}{}{Meanie! Why did you do that?}

# Floating phrases
{110}{}{Hey Pinky!}
{111}{}{Sit, Pinky!}
{112}{}{What a dumb animal.}
{113}{}{No, Pinky!}
{114}{}{Don't scratch the floor!}
{115}{}{Pinky, stop chewing the furniture.}
{116}{}{Oh, my dad will scold me for this.}
{117}{}{Wait, I'll get you some water.}
{118}{}{Are you hungry?}
{119}{}{Do you want something tasty?}
{120}{}{Look, I have a mantis leg.}
{121}{}{Well done, Pinky. Nice Pinky.}
{122}{}{Here's a treat.}
{123}{}{Do you want some more?}
{124}{}{Give me your paw!}

{130}{}{Hey Pinky!}
{131}{}{Come on, stop whining, Pinky.}
{132}{}{You've caused trouble everywhere in the house.}
{133}{}{Do you want the neighbors to hear?}
{134}{}{Stop scratching me!}
{135}{}{I'm worried about you.}
{136}{}{Oh, what's wrong with you?}
{137}{}{Should I get you some water?}
{138}{}{Look what you did!}
{139}{}{What's hurting you?}

{200}{}{Hello. Are you visiting my dad? He should be in his office.}
{201}{}{Yes. Are you his son?}
{202}{}{Yeah. I'm Chipo.}
{203}{}{I see.}
{204}{}{Who's this?}
{205}{}{This... This is Pinky. I'm taking care of him...}
{206}{}{Hmm. Curious.}

# Dialogue
{210}{}{What are you up to?}
{211}{}{Wow. I thought you were run out of town.}
{212}{}{Hey, you're the one that's being talked about so much, aren't you? Cool.}
{213}{}{Pinky's been pretty lively lately. Seems he's all better.}
{214}{}{Hey, keep an eye on Pinky okay?}

{219}{}{Bye, Chipo.}

{220}{}{Do you know where your dad is?}
{221}{}{In the office, probably. As usual. He constantly sits there over his papers, and he kicks me out so I don't bother him.}
{222}{}{Trust me, you really shouldn't "bother" him.}

{230}{}{You have an unusual pet.}
{231}{}{This is Pinky. He's cool, but people don't want him in town.}
{232}{}{Why?}
{233}{}{They come up with all sorts of things. Saying he's dangerous, spreads infection, or harms plantations. Nonsense. Frank's the most unhappy about it. He keeps threatening to kill Pinky whenever he can.}
{234}{}{Pig rats can indeed be dangerous.}
{235}{}{But Pinky's not like that! He hasn't done anything wrong. He just scratches at night. Lately, he's been sick too. While everyone wants him dead, he really needs help now.}
{236}{}{Maybe it's for the best. Bye.}
{237}{}{That's unfortunate. Hang in there, buddy.}
{238}{}{Let me take a look at this creature. Maybe I can help him heal.}
{239}{}{I had to perform a whole operation on Pinky. But it's all over now.}
{240}{}{You mean you fixed him! Amazing! Oh, thank you so much. You know, he seems to like you. You can play with him if you want. But don't go too far from the plantations, or he might wander into the desert.}
{241}{}{Glad to help. Have fun with your little friend, Chipo.}
{1241}{}{Glad to help. Have fun with your little friend, Chipo.}
{242}{}{That's not fair.}
{243}{}{I'd like to take Pinky for a walk.}
{244}{}{If he wants to go with you, then I don't mind. Just don't take him too far from home.}
{245}{}{Thanks. I'll take a walk around the town with him.}
