{100}{}{You see a resident of Casa Nueva.}
{101}{}{You see a local resident. Compared to people from other settlements, they looks quite well-fed and healthy.}

{110}{}{Hello. Where are you from?}
{111}{}{Don't mess around on the plantation, or you'll be mistaken for a thief.}
{112}{}{Sorry, I have too much work to talk right now.}
{113}{}{I'd love to chat, but I don't have time at the moment.}
{114}{}{Follow the rules if you don't want any trouble.}

{120}{}{I'll call for help if you don't leave me alone.}
{121}{}{Are you crazy? It's night outside!}
{122}{}{Don't push me.}
{123}{}{Go away. Don't make me scream.}
{124}{}{How rude. Strangers are such nerve...}
{125}{}{Now's not the time to talk. Leave.}
{126}{}{Listen, it's past curfew. We'll get in trouble.}

{130}{}{Hola! How are you?}
{131}{}{Our cities should unite.}
{132}{}{You're welcome.}
{133}{}{My home is your home.}
{134}{}{Peasants must stick together.}

{140}{}{How are we going to survive now?}
{141}{}{Without the Brotherhood, we're easy targets for raiders.}
{142}{}{Alvaro has to tell us what to do!}
{143}{}{Down with the gun ban!}
{144}{}{To hell with the bans now.}
{145}{}{We've endured this oppression for too long. Enough!}
{146}{}{Now WE will rule the town!}
{147}{}{A rifle for every family!}
