{100}{}{You see a gas mixer.}
{101}{}{You see a system of gas cylinders and pipes leading to the ventilation system. It appears to be part of the local climate control.}
{102}{}{This is part of the climate control system. A nearby sign warns, "Caution! Explosive."}
{103}{}{The system is overheating and is on the verge of igniting everything around it.}
{104}{}{This won't help. The system has malfunctioned and is about to ignite everything nearby.}
{105}{}{Burn! Burn!}
{106}{}{The system is on the brink of overload. It's about to blow any second now...}