{100}{}{You're looking at a lab.}
{101}{}{You're looking at a chemistry lab.}
{102}{}{This is a chemistry lab. It requires scientific knowledge to operate it.}
{103}{}{The component is prepared for the chemical process and loaded into a special vessel.}
{104}{}{Components are needed to complete the chemical process.}
{105}{}{The poison has been manufactured. It's exactly what the Followers need.}
{106}{}{I need lab data to properly manufacture the poison.}
{107}{}{There's nothing more to do here}
{108}{}{You need ingredients and instructions.}
{109}{}{I need a manual}
{110}{}{Done}
