{100}{}{You see a bandit in front of you.}
{101}{}{You see a young man with a defiant demeanor.}
{102}{}{Is this your motorcycle? Oh, my mistake. I thought it was abandoned. Of course, uh, take it, we don't mind.}
{103}{}{Get lost.}
{104}{}{Hey, is that your bike?}

{200}{}{Hey, is that your bike?}
{201}{}{That's right.}
{202}{}{Maybe it is. What's it to you?} 
{203}{}{You're wrong. It's my bike. Got a problem with that? Or maybe you want to BUY it? Smart move. Price is 500 caps. And hurry up before I change my mind.}
{204}{}{Why do you need it? I doubt you can't even ride it.}
{205}{}{Do I look like an idiot? This bike is a hot commodity. If you don't pay, someone else will.}
{206}{}{Hand over the motorcycle. I'm asking nicely, but there won't be a second time.}
{207}{}{Give me time to get the caps.}

{210}{}{Did you bring 500 caps?}
{1210}{}{Did you bring 500 caps?}
{211}{}{Did you bring 700 caps?}
{1211}{}{Did you bring 700 caps?}
{212}{}{Give me time to get the caps.}

{220}{}{This is *my* motorcycle. Hand over the keys. Now.}
{221}{}{Or what? Are you gonna challenge me? My gang *owns* this area. Mess with me, you mess with the whole gang. Got it?}
{222}{}{I don't care about you or your gang. Give me the keys or you'll die.}
{223}{}{Okay, okay. I don't want any trouble with you or your crew.}
{224}{}{By the way, I changed my mind too. The price is now 700 caps.}
{225}{}{Hmph.}
{226}{}{This is stupid. I'll just kill you.}

{230}{}{Here's the caps. Now give me the keys.}
{231}{}{(carelessly throws the keys on the ground) Take 'em'. I didn't know how to use it anyway. (with a grin, he heads deeper into the area, weighing the caps in his hand with a satisfied look)}
{232}{}{Thanks, nice doing business with you.}
{233}{}{One day, I'll catch you in your sleep and slit your throat. And I'll laugh. Oh, I'll laugh.} 
{234}{}{Not so fast, buddy. I think I'll take all those caps back.}

{240}{}{You're an idiot if you think you can mess with the champ. Wanna test that theory?}
{241}{}{You're a fool if you think you can go against a Follower. My brothers won't let this slide.}
{242}{}{Ever heard of the Highwaymen? I'm one of 'em. Don't cross us.}
{243}{}{(grins like a cornered dog) Damn, I didn't know... Sorry, here's the key... Is everything okay now? I'll, uh, go.}
{244}{}{Get out of here.}
{245}{}{No problem. Let's forget about this misunderstanding.}
