{100}{}{You see Badi.}
{101}{}{You see an ordinary beggar, barely scraping by. It's a wonder he's still alive.}
{102}{}{Hello, partner. How are you?}
{103}{}{One day, I'll get my revenge.}

{110}{}{I'm hopeless.}
{111}{}{I'm finished.}
{112}{}{Only one cap left.}
{113}{}{I blew my last cap at the casino.}
{114}{}{I don't know how I'll get out of debt.}
{115}{}{I lost everything in just a few days.}
{116}{}{This might be my last day alive.}
{117}{}{Can you lend me a thousand caps? I promise I'll pay you back.}
{118}{}{Looks like I'm about to be enslaved.}
{119}{}{I'll be on the streets soon.}

{200}{}{Phew, don't scare me like that. I've been avoiding strangers lately.}
{201}{}{Who are you?}
{202}{}{My name's Badi, I live here. But I don't recognize you.}
{203}{}{Why would a filthy beggar like you know me?}
{204}{}{Well, hi, Badi. I'm }
{205}{}{.}

{210}{}{What do you want from me?}
{211}{}{From you? Nothing. Bye.}

{220}{}{Vernon's tired of your endless debts. Time to pay up or get out.}
{221}{}{No, please don't kick me out! I'll pay Vernon, I just need a little more time to settle my debt with the casino.}
{222}{}{You owe the casino?}
{223}{}{Yeah. I know it was stupid. I got caught up in a lucky streak and couldn't stop.}
{224}{}{I don't care about your excuses. Time to get out.}
{225}{}{I've lived here for years! Is this how Vernon treats his guests? Damn it... you haven't see the last of me.}
{226}{}{Get out of here.}
{227}{}{I see. How much do you owe Vernon?}
{228}{}{37 caps from last quarter.}
{229}{}{I know what it's like to lose everything. Don't worry, I'll pay your rent.}
{230}{}{Really? God bless you! Thank you! Thank you!}
{231}{}{It's a small thing for me. I'm }
{232}{}{. Remember my name.}
{233}{}{See you.}
{234}{}{Alright, I'll give you a little more time.}
{235}{}{Really? Thank you! I'll get the caps soon, I promise.}
{236}{}{You better make sure.}

{250}{}{You owe the casino a lot of money. It's time to pay the bills.}
{251}{}{I've given everything I had! There's nothing left! Please, I need a little more time. I'll repay everything!}
{252}{}{You've had enough time. Why can't you come up with the caps?}
{253}{}{There's no work in the city, and my reputation is ruined because of this debt. I'm just surviving by scavenging the ruins right now.}
{254}{}{Looks like there's really nothing to take from you. Keep wallowing in your filthy poverty then.}
{255}{}{If you want to avoid my fist, say something reassuring.}
{256}{}{Wait, don't go that far. If Don Diego wants his caps, he needs me alive and unharmed, right? Otherwise, I'd already be dead, or enslaved. Right?}
{257}{}{Damn, I'm wasting my time with you.}
{258}{}{How are you going to pay back your debts?}
{259}{}{I have a plan. I just need a little time to prepare.}
{260}{}{What, more of your excuses?}
{261}{}{What are you up to? Come on, tell me.}
{262}{}{Enough of this crap. Get the caps or I'll break your bones.}
{263}{}{Listen, you can make some money too. Don Diego's not gonna pay you much, or hire you. But I know a way to earn some *real* caps!}
{264}{}{This is intriguing. Tell me more.}
{265}{}{Your excuses seem to know no bounds. But I'll listen to what you have to say this time.}
{266}{}{There's a place with heaps and heaps of caps. I'm not lying, it's true. Only I know about it. We go there, break in, and take everything. We'll split the caps fifty-fifty. Deal?}
{267}{}{Something's off here. Why haven't you done this before?}
{268}{}{Sounds too good to be true. What's the catch?}
{269}{}{There is one hitch. The place, it's a warehouse, is guarded by a couple of old robots. Some people tried to get past them and got... uh... fried. But you can handle them!}
{270}{}{Hmm, that sounds promising. Where is it?}
{271}{}{You're scamming me. Show me this place first.}
{272}{}{Uh, no. What if you scam me? This is my only chance to get out of debt. I need a reliable partner. Do we have a deal? Fifty-fifty?}
{273}{}{Alright. But I need time to prepare.}
{274}{}{Of course. You'll need decent weapons for the robots, but don't weight yourself down with stuff you don't need. Oh, and it's in the nuclear zone. There are still radioactive spots, but I know how to avoid them.}
{275}{}{I see. I'll be back.}
{276}{}{I can see right through you. I've heard enough of your crap today, but next time I might come back with a baseball bat.}
{277}{}{Hey, I'm just offering a deal. It's a simple, temporary partnership, okay? Think about it.}
{278}{}{We'll see.}

{280}{}{About our 'deal'. I'm ready to head to the warehouse.}
{281}{}{Yes, great! You won't regret it. Let's go. The sooner I'm out of debt, the better.}
{282}{}{Lead the way.}
