{100}{}{You see an adept.}
{101}{}{You see one of the Followers of Fire. He's shouting something manically to draw attention.}

#Floating Lines
{110}{}{Tremble before the Holy Fire!}
{111}{}{Beware the wrath of the Fiery Heavens!}
{112}{}{The Lord's power is in nuclear fission!}
{113}{}{Repent, all of you, repent while you still can!}
{114}{}{Who dares defy the voice of our Lord?}
{115}{}{Doubters! They will be the first to fall!}
{116}{}{These souls have surrendered to the Nuclear Devil!}
{117}{}{Hear me, victims of Radiation and Desolation!}
{118}{}{They have fallen prey to their own wickedness!}
{119}{}{Honor Father Aaron, Lord of Phoenix, for He breathes life into this wasteland!}
{120}{}{A new age is upon us!}
{121}{}{Only a fool would stand against progress!}

#First Dialogue
{200}{}{Come closer, child of Radiation and Desolation. All must see that justice prevails. None shall escape the wrath of the heavens!}
{201}{}{Umm, what are you going on about?}
{202}{}{For years, we, the servants of the Holy Fire, kept ourselves hidden from the common folk. Their hearts and minds couldn't comprehend the simplest truths. We were shunned, beaten, even killed! But we waited... waited for the right time.}
{203}{}{[Continue]}
{204}{}{Hey, crazy guy in the rags, why all the shouting?}
{205}{}{There it is! Intolerance! Blasphemy! We, the servants of the Holy Fire, stayed hidden from ordinary people for years, because they couldn't grasp the simple truths. We were driven away, beaten, and killed! But we waited patiently... for the right time.}
{206}{}{The time when the Lord would tire of human foolishness and grant us peace. These people, whose bodies have become vessels for the Nuclear Devil, are proof. For many years, they plotted their wicked deeds against the church. They robbed and killed our monks who spread the bright truths to the world. Ungrateful! They will burn in the Nuclear Fire of Hell!}
{207}{}{Terrible. Those people definitely had it coming.}
{208}{}{May the Holy Fire be with you! Go in peace, and spread the word to the common folk about the persecution of our peaceful church.}
{209}{}{Of course. After hearing all this, I can't stand by and let such injustice continue.}
{210}{}{Don't drag me into this. I'm just going to mind my own business.}
{211}{}{I've only heard your side of the story. The other side... well, they won't be telling it, will they?}
{212}{}{Skeptic! Have we not done enough for this city? Look at how Phoenix has thrived under the wisdom of Lord Aaron. Go and reflect on that... and fear the Holy Fire! Fear the Fire!}
{213}{}{Sorry, I'm new around here. I'll make sure to check out your church, though.}
{214}{}{After what I've seen, I'm not sure I can take your words at face value. I'll figure out my own opinion of your church.}

{220}{}{Greetings, brother. I'm glad to see you've come around since our last meeting. You were a skeptic back then, looking at me with disdain. Now, I extend my hand and say crede firmiter et pecca fortiter.}
{1220}{}{Greetings, sister. I'm glad to see you've come around since our last meeting. You were a skeptic back then, looking at me with disdain. Now, I extend my hand and say crede firmiter et pecca fortiter.}
{221}{}{Greetings, brother. I'm glad to see you've joined the cause. It's a great honor and responsibility. Crede firmiter et pecca fortiter.}
{1221}{}{Greetings, sister. I'm glad to see you've joined the cause. It's a great honor and responsibility. Crede firmiter et pecca fortiter.}
{222}{}{Now, if you don't mind, I'd like to talk with you.}
{223}{}{Crede firmi... What? I'm not up to speed on the sacred texts yet. See you around.}

#Repeat Dialogue
{250}{}{I see the words of the Holy Fire still trouble you? What do you want to know this time?}
{251}{}{Again you come, servant of the Nuclear Devil, to test me.}
{252}{}{Greetings, brother. Everything alright? Are the common folk giving you any trouble?}
{1252}{}{Greetings, sister. Everything alright? Are the common folk giving you any trouble?}
{253}{}{I think I'll be going now.}

{260}{}{Who are you?}
{261}{}{Tell me more about yourself, brother.}
{262}{}{I am a priest and humble servant of Aaron, Lord of Phoenix. My name is Gabriel.}
{263}{}{That isn't your real name, is it?}
{264}{}{Well, that was enlightening. See you around.}
{265}{}{What is this 'church' you represent, Gabriel?}
{266}{}{That's right. After joining the service, we change our names, putting a cross over our past lives.}
{267}{}{}
{268}{}{By the way, could you help me understand our faith better?}
{269}{}{After what I've heard, I'd like to know more about your faith.}
{270}{}{Tell me about the religion you represent.}
{271}{}{Can we talk about our church?}
{272}{}{It's better to learn about the faith during sermons than from me. The Church of the Holy Fire is north of the city. Follow the main street, the road will lead you to the cathedral.}
{273}{}{So, who exactly are you?}
{274}{}{A cheap trick to lure people in, cultist. You're not fooling me.}
{275}{}{Alright, I'll head straight there.}
{276}{}{Your church weilds enough power to carry out public executions?}
{277}{}{No, no, the execution was carried out by others, but under our supervision. And yet, the whole city owes the church. Owes for water, for electricity, for peace and order. Soon you will see all this with your own eyes, child of Radiation and Desolation.}
{278}{}{You sure talk a good game, old man. I'll check it out myself to see if you're lying or not.}
{279}{}{Well then, I should explore the city a bit and see. Goodbye.}
{280}{}{Sorry to be blunt, but such questions shouldn't be discussed on the street. And don't clutter your mind with skepticism; that's how the Nuclear Devil infiltrates the souls of young monks. Fear the Holy Fire, acolyte, fear the Fire!}
{281}{}{Looks like I'll need to speak with the clergy at the cathedral. See you.}
{282}{}{And what do you do exactly?}
{283}{}{Why were those guys punished?}
{284}{}{Those guys behind you didn't fear it. Why were they executed?}
{285}{}{What did these people do to deserve punishment?}
{286}{}{Fools. They succumbed to the temptations of the Nuclear Devil. Some of them spread false rumors about our church and its leader Aaron, may he be praised forever. Others were punished for robbing our monks or the church itself. From now on, their souls will find no peace in the Nuclear Hell.}
{287}{}{Don't you think that's a bit... harsh?}
{288}{}{I guess they got what they deserved. I'll watch myself around here. Goodbye.}
{289}{}{Religious based executions? You're not really selling Phoenix to me.}
{290}{}{Who are you to be overseeing this execution?}
{291}{}{What do you know about the rebels fighting the church?}
{292}{}{Heretics and cowards! If ONLY we knew the location of their headquarters, they'd all burn at the stake.}
{293}{}{Got it. You don't know anything. I'll ask around elsewhere.}

#Quest
{300}{}{I'm investigating the attacks on the monks at Aaron's request. What can you tell me about them?}
{301}{}{Tell me again about the attacks on the Followers.}
{302}{}{We Followers were often the targets of robberies and ridicule. When Aaron rose to power - may his name be praised - the gangs steered clear of us. But lately, the attacks have started up again.}
{303}{}{[Continue]}
{304}{}{The shooting during the execution, the murder in the slums, and the attack in front of the casino are the most daring crimes against our brothers recently.}
{305}{}{Thanks, that's enough.}

{310}{}{Tell me about the shooting during the execution.}
{311}{}{They shot from the top of those ruins while we were carrying out the execution. There were several shooters, they fired crosswise and clearly aimed at me. Perhaps the supporters of the criminals tried to save their accomplices, but by the will of the Eye of the Phoenix, they failed.}
{312}{}{What about the attack in front of the casino?}
{313}{}{Savage criminals cut down our brothers near the casino, like mole rats on a ranch. It's hard to say what really happened, as people are saying different things.}
{314}{}{What do you know about the incident in the slums?}
{315}{}{A grim and tragic affair. Our acolytes ventured into the slums to spread Aaron's word and seek donations for the temple. Not long after, their bodies were found hanging from lampposts. The locals, as expected, claim ignorance - no one saw a thing. Let us pray for the souls of our fallen brothers.}
{316}{}{Do you have any leads on these attacks?}
{317}{}{You think Aaron would've trusted you with this if it wasn't serious? Ask around the casino and the slums. They might be more open with you. Most folks recognize the Followers on sight, but you're still unknown. Use that to your advantage.}