{100}{}{You see a ghost!}
{101}{}{You see... the soul of a man burned in a nuclear flame.}

{102}{}{What the hell is this?}
{103}{}{It wasn't real, was it?}
{104}{}{I think I'm going crazy... Or am I?}
{105}{}{These... ghosts are everywhere!}

{110}{}{Look at what you've done!}
{111}{}{This is all your fault!}
{112}{}{Why did you do this to us?}
{113}{}{Why did you kill us?}
{114}{}{We'll haunt you forever.}
{115}{}{Murderer!}

{1110}{}{Look what you've done!}
{1111}{}{This is your fault!}
{1112}{}{Why did you do this to us?}
{1113}{}{Why did you kill us?}
{1114}{}{We will haunt you for the rest of our lives.}
{1115}{}{Killer!}
