{100}{}{You see an announcement.}
{101}{}{You see a board with several announcements.}
{102}{}{You see a notice board. It's worth studying closely.}

{200}{}{(You see a notice board filled with writing)}
{201}{}{Leave.}
{202}{}{I see.}
{203}{}{Back.}

{210}{}{Dangerous areas.}
{211}{}{(You examine a map of Phoenix, noting the most hazardous areas. The largest ones are labeled: "Power Plant Ghouls", "Red Cardinals", "Irradiated Ruins.")}

{220}{}{Beware the highwaymen!}
{221}{}{Beware the raiders on routes 10 and 17. They attack travelers and caravans without mercy or remorse. Don't even try to negotiate with them.}

{230}{}{Los Panchos Gang.}
{231}{}{Attention! Particularly dangerous criminals wanted - leaders of the Los Panchos gang. (Their portraits are attached) Payment of 500 caps for each head.}
{232}{}{Hernando Aviles.}
{233}{}{[Crossed out] Hernando Aviles.}
{234}{}{Former security guard. Killed his employer and the entire family during a robbery. Afterward, he wandered the desert, joining the Los Panchos gang. Calm and cool-headed, he likes to talk to his victims before killing them.}
{235}{}{Chucho Navarro.}
{236}{}{[Crossed out] Chucho Navarro.}
{237}{}{Former laborer. Escaped slavery after being sent there for debt. Known for his penchant for torture. Mentally unstable.}
{238}{}{Aidy Gorme.}
{239}{}{[Crossed out] Aidy Gorme.}
{240}{}{Former singer. She robbed the casino where she worked, then disappeared with her accomplices into the desert, joining the Los Panchos gang. She rose to the rank of boss through cruelty, emotional volatility, and a penchant for cannibalism.}

{250}{}{Wanted: Gil McCord.}
{251}{}{Former marksman Gil McCord is wanted for attacks on members of the mercenary guild. Reward 750 caps, dead or alive.}
{252}{}{[Crossed out] Gil McCord Wanted.}

{260}{}{Wanted }
{261}{}{ from Villa... What?}
{262}{}{Wanted for numerous crimes against the people of Phoenix. Any contact with this person could cost you your life.}
{263}{}{Wanted for numerous crimes against the Church of the Holy Fire. Any contact with this heretic may cost you your reputation and well-being.}
