{100}{}{You see Professor Zimmer.}
{101}{}{You see the leader of the research team. He looks eccentric.}
{102}{}{Now is not the time for scientific debate...}

#First dialogue
{200}{}{(A scientist in a lab coat with a wild look and tousled hair speaks without looking up from his tablet) I'm busy, get out.}
{201}{}{I'm new here, can I just ask you a few questions?}
{202}{}{Look me in the eyes when you speak.}
{203}{}{Sorry to bother you then.}

{207}{}{That's what I'm trying to explain - I'm new here and...}
{208}{}{Security! We have an intruder!}
{209}{}{Shouldn't have done that...}

{210}{}{(Irritated) I told you, I don't have time... wait. Who are you?}
{1210}{}{(Irritated) I told you, I don't have time... wait. Who are YOU?}

{211}{}{I'm a Follower of Fire.}
{212}{}{That's it. (Gradually raises his voice) And so, you think you can barge into the lab and distract ME from MY work?! (Raises his voice again) Understand this, you piece of social decay, the work in this lab is far more important than your petty Cathedral antics! And no matter what lofty title you hold in your "cult," it doesn't matter here! Do you understand? Now disappear.}
{1212}{}{That's it. (Gradually raises his voice) And now you think you can barge into the lab and distract ME from MY work?! (Raises his voice again) Understand this, you piece of social decay, the work in this lab is far more important than your petty Cathedral antics! And no matter what lofty title you hold in your "cult," it doesn't matter here! Do you understand? Now disappear.}
{213}{}{I see.}
{214}{}{I'll think about it.}

{215}{}{I was given permission to look around.}
{216}{}{Permission or not, you won't be getting a tour. Get out before I call security!}
{217}{}{No problem.}

{219}{}{I was sent to fix something.}
{220}{}{Then go and fix it, idiot!}
{1220}{}{Then go and fix it, idiot!}
{221}{}{Yeah, uh, sure.}

{223}{}{I'm also a scientist, so I was sent to you.}
{224}{}{Really? (Puts down the tablet) Very curious... very... But no one informed me about a new lab assistant. Bring the order, then we'll talk.}
{225}{}{Okay.}

{227}{}{I was given permission to look around.}

#Re-dialogue
{300}{}{Okay. Now what do you need?}
{301}{}{Nothing else.}
{302}{}{Goodbye.}
{303}{}{Should we change the subject?}
{304}{}{Let me ask you another question.}
{305}{}{With all due respect, colleague, *I* am in charge here. I have the authority to kick anyone out of the lab, even Aaron himself. Get out!}
{306}{}{Okay, okay...}

#Questions about yourself
{310}{}{Sorry, but who are you?}
{311}{}{(Waves his hand in disappointment) This is what it means to work in the shadows... My name is Zack Zimmer. Professor Zack Zimmer. I head this scientific department. Practically, I am the third most important person in the entire church, after Aaron and the Advisor. No need to bow.}

{312}{}{A scientist is rare these days.}
{313}{}{That's why I'm holed up in a vault under the protection of a major organization. Scientists without patrons can't survive in our times.}
{314}{}{Is your name Professor?}
{315}{}{(Sighs) I've never heard a dumber question.}
{316}{}{Professor is a title. It's awarded from a... school.}
{317}{}{What knowledge! I'll tell you a secret - at one time, I took courses in a little-known educational organization. It was there I earned this title.}
{318}{}{How did you end up here, Professor?}
{319}{}{You must have quite an interesting story.}
{320}{}{It's a long story, and it's not for your ears. Let's just say the West didn't have enough room for my ambitions.}
{321}{}{The West? You mean California? Are you saying you crossed the desert between here and there?}
{322}{}{Ahem. You're asking too many questions.}
{323}{}{I'm a member of the Brotherhood of Steel. The base has a detailed dossier on you, of course.}
{324}{}{That changes things I guess. Yes, well, I came here with the Brotherhood of Steel. And I received the title from the Followers of the Apocalypse in the Boneyard. But we had differences, and so I came here.}
{325}{}{What were the differences?}
{326}{}{Let's just say... the Followers of the Apocalypse are too soft. They oppose experiments on living people. And this slowed down many medical projects.}
{327}{}{What kind of boneyard?}
{328}{}{The Angel's Boneyard. The ruins of a vast city, to the west, beyond the Sonoran Desert. It's very far away, too far for you to ever reach.}

{330}{}{So you're also a Follower of Fire?}
{331}{}{What? No. I'm a scientist, not a preacher! Besides, many of their teachings seem ridiculous to me.}
{332}{}{Can you tell me about Aaron?}
{333}{}{Discussing leaders has always been dangerous. Regardless of your rank.}
{334}{}{I'm not a cult member.}
{335}{}{Then we have nothing left to talk about.}
{336}{}{I am a member of the Brotherhood of Steel.}
{337}{}{Ah... That changes a lot... Well, then you'd better talk to the Advisor instead of me.}
{338}{}{This will remain between us.}
{339}{}{Aaron would be nothing if he hadn't been put in charge of the city and the church. He still feels like a puppet, and sometimes it drives him crazy... However, I'm talking too much today.}
{340}{}{I've no reason to trust you or anyone here.}
{341}{}{For example?}
{342}{}{I'm already tired of explaining simple things to these monks, let alone you. Go read some scientific literature.}
{343}{}{Such as, making gods of elementary particles?}
{344}{}{Exactly! What kind of ridiculous fantasy is this, that some deity punished people with a Fiery Flood for their sins? It was a nuclear war! That is, an ordinary war with very powerful bombs.}
{345}{}{Don't they know that?}
{346}{}{I'm afraid it's been too long. The events of a bygone era are overgrown with myths and legends. On the other hand, the faith of the Followers is useful for society... as long as it does not hinder progress.}

{350}{}{Why do you snap at your subordinates?}
{351}{}{Because I'm tired of idiots and ignorant monkeys.}
{352}{}{Is that all?}
{353}{}{I'm not going to discuss this.}
{354}{}{I think your frustrated by unfulfilled hopes. Aren't you given proper freedom?}

{355}{}{(Adjusts glasses in sarcastic bewilderment) Wow! Look, the first psychologist of post-nuclear civilization! Save those sweet consoling words for those above. If they paid more RESPECT to my work, I wouldn't have to raise my voice at everyone I meet.}
{356}{}{Sure, whatever you say.}
{357}{}{What is a "monkey"?}
{358}{}{(Sighs) It's you.}
{359}{}{[Science 20] They say that work made people out of monkeys.}
{360}{}{Nonsense! I found old texts clearly stating that these are two different branches of evolution with common ancestors. However... it is much more important that I hear this from the lips of a commoner.}

#Questions about the bomb
{378}{}{And you designed all this yourself?}
{379}{}{Of course. Many years of painstaking work by a handful of scientists.}
{380}{}{Is this a nuclear bomb? Impressive.}
{381}{}{This might be the toughest thing we've ever tackled. Nobody, from California to Texas, could pull this off. And here we are, right on the brink of completion! Just waiting on a few parts from Two-Sun now.}  
{382}{}{California and... Texas?}
{383}{}{(shakes head, disappointed) Texas! Those places are from a country that's long gone, you fool. Maybe they go by different names now, but before the Great War, that's what they were called.}  
{384}{}{But you couldn't have built it without instructions.}
{385}{}{Hmm, you catch on quickly! Without instructions, we would have gotten nothing but cancer and leukemia. The blueprints were brought by order from an old military base, very far from here.}
{386}{}{Where do you get nuclear material?}
{387}{}{From Flagstaff. There's an active uranium mine and enrichment plant there. The quality is low, and production is slow, but we have no other sources.}
{388}{}{Why do you need such a powerful weapon?}
{389}{}{Good question. Let's just say there are many reasons. And all of them are known only to one person in all of Phoenix - the Advisor himself.}

#Questions about research
{400}{}{What kind of research does your lab do?}
{401}{}{Various kinds. (Loses himself in thought) Our mission is... first to provide the Followers of Fire with everything they need... Yes. And then to take on the reconstruction of the city and its industrial facilities. After all, we need work for workers... And this is only the first part of the plan. The most important thing now is to eliminate shortages of food and clean water in Phoenix.}
{402}{}{How's it going?}
{403}{}{There is progress, but it's too slow. The city is badly destroyed, old equipment is ruined or worn out, and the production base of this vault is only enough to supply the Cathedral. Add to this the squabbles between individual clans in the city, illiteracy, and a whole list of other problems. Now, if you don't have any more stupid questions, I'll get back to finding solutions.}
{404}{}{I thought the Followers weren't generous enough to give out food.}
{405}{}{What are you talking about? No one is going to 'give out' food to the rabble on the streets! Food and water give unconditional power over the entire city. In exchange for food, locals are ready to do *work*, and we *need* cheap labor.}
{406}{}{Unconditional power? Sounds like tyranny.}
{407}{}{How narrow-minded! Power is just a mechanism. When we created the Fire Cult, there was no power in this city. And there were pathetic primates, fighting among themselves over a dead rat. And look at the city now. With our help, electricity and currency returned here, industry and education were born, even gambling appeared! And it's all thanks to the heavy hand of the cult that set the local apes straight.}
{408}{}{[Science 100] How confident are you that society is ready for such innovations?}
{409}{}{I've been thinking about this a lot...}
