{100}{}{You see a settler.}
{101}{}{You see an ordinary citizen of Aqueduct.}

{200}{}{Is it too late for a visit?}
{201}{}{I'm just...}
{202}{}{Out! Scram!}
{203}{}{Alright, catch you later.}

{210}{}{Sorry, no time for chit-chat. Try Garth or someone with less on their plate.}
{211}{}{Sorry, busy. Find someone with more free time.}
{212}{}{Just found out Garth's been behind those disappearances. Now I get why he's been so adamant about keeping folks out of the aqueduct catacombs. But now who's gonna keep the riffraff out?}
{213}{}{Hey, Ranger. How's it going?}
{214}{}{Later.}

{220}{}{What are you doing?}
{221}{}{Getting prepped for a big fishing trip up at the reservoir. Takes some effort, you know.}
{222}{}{Who built this aqueduct?}
{223}{}{Honestly, not sure. Could've been the Rangers themselves. Been here as long as anyone can remember.}
{224}{}{What's your opinion on Garth?}
{225}{}{Solid guy, unshakeable. Always had our backs, keeping us safe from highwaymen, raiders, and critters. Lives across the way.}
{226}{}{How's life under ranger protection?}
{227}{}{Great. Rangers keep us safe from raiders and beasts, and we pay 'em with some of our food. No complaints here.}
{228}{}{Do you know anything about the missing people?}
{229}{}{Seems like critters got 'em. Wolves and nasty pig rats lurk in the valley. Outsiders often don't know the danger.}
{230}{}{I heard there's an epidemic around here?}
{231}{}{Yep, some kinda' fever hit a few folks. Some got better, others still burning up. Guy in the shack across the way's been hit hard.}

{240}{}{I'm speaking for the people in Garage City. There's a serious food shortage there.}
{241}{}{Hmm. Heard that city's brimming with scavengers. We just need parts, at the least, to fix up some boats. But word has it, folks there ain't too keen on Rangers. Must be a real dire situation if you're willing to come cap in hand.}
{242}{}{How about trading with Garage City then? Parts for fish?}
{243}{}{I've still gotta convince the Rangers to agree to trade. But if there's profit to be had, they ain't likely to say no. Yeah, we'll send a caravan with dried fish to that nasty, stinking town.}
{244}{}{People are starving in Garage, and you're talking profit. I guess that's how things work.}
{245}{}{That's great. I'll let Garage City know you're on board.}
