{100}{}{You see a fugitive.}
{101}{}{In front of you is a young man in a dirty jacket, exhausted. He looks like he's been through a lot.}
{102}{}{What... what did you slip me...}
{103}{}{...You... scum...}
{104}{}{Looks like the Rangers finally caught the spy. His lifeless body on the road will serve as a reminder to the other mercenaries.}
{105}{}{I owe you my life, doc.}
{106}{}{See you at the Cathedral of Fire.}

# First dialogue
{200}{}{(In the dim light, you barely catch someone's movement; a young man in a dirty jacket sits exhausted on an old mattress) Stop! Who are you? W-what do you want here?}
{201}{}{I'm just traveling. This place seemed like a good spot to rest.}
{202}{}{As you can see, it's already taken.}
{203}{}{Maybe I shouldn't have come here. Alright, I'll leave...}
{204}{}{Wait! Do you have any water? I'm dying of thirst!}
{205}{}{My supplies are low too. Where's the nearest water source?}
{206}{}{The farmers across the way have a well. But those bastards won't share a drop unless you pay them everything you've got... Listen, help me get back my strength! I have a lot of connections, I'll help you in the future.}
{207}{}{Handle your own problems. That's the law of the Wasteland.}
{208}{}{Hmm... Wait here, I'll be back with clean water...}
{209}{}{Of course, here you go.}
{210}{}{(With trembling hands, he grabs the flask and gulps down the water; after satisfying his thirst, he takes off his jacket and washes a blackened wound with the water, whimpering like a dog from the pain.)}
{211}{}{Feeling better?}
{212}{}{You're saving me... but I won't last long.}
{213}{}{Looks like you won't make it with that wound. I'll call the Rangers for help...}
{214}{}{NO! Those bastards won't help me. They're the reason I'm in this mess! Like you, I was just traveling, looking for a new place to settle. The Rangers mistook me for a raider and shot me without asking questions. I was lucky to survive, and I dug the bullet out with a knife, but this wound is killing me!}
{215}{}{Tough situation...}
{216}{}{Do something! Without you, I'm done for!}
{217}{}{Then unbutton your jacket and get ready for an examination. The good doctor will heal you now.}
{218}{}{This wound looks too serious... I'm no doctor.}
{219}{}{Then go to the Rangers and get some meds from them. I'll die without a stimpak!}
{220}{}{Hang in there, I'll be quick.}
{221}{}{Hmph. Deal with your own problems.}
{222}{}{Maybe I could patch up your wounds.}
{223}{}{Did you bring water?}
{1223}{}{Did you bring water?}
{224}{}{Here's clean water.}
{225}{}{Not yet, hang in there.}
{226}{}{Then why are you still here? Hurry!}
{227}{}{I'm not sharing my supplies with you. Survive on your own.}
{228}{}{Radroach scum! I'm taking all your stuff!}
{229}{}{Whoa, whoa, put that away...}
{250}{}{Do you enjoy watching me suffer?}
{251}{}{I'm working on your problem...}
{252}{}{Don't push it. Remember, your dead without me.}
{253}{}{Honestly, I didn't expect any help. It's... n-nice of you. Maybe I need to rethink my views on people.}
{254}{}{Looks like you also need a dose of good conversation. Shall we talk?}
{255}{}{I think my mission here is done. Stay safe.}
{256}{}{To treat the stranger, use medical skills or supplies.}

# Repeat dialogue
{300}{}{What do you want?}
{301}{}{I'll be back soon.}
{310}{}{What have you been eating out here?}
{311}{}{Whatever I find in the desert - lizards, plant fruits, larvae. Not much choice, but I'm used to it.}
{312}{}{Farmers say someone's been stealing their crops.}
{313}{}{(Pause) I need to survive. I don't care what others think.}
{314}{}{Hmm...}
{315}{}{Got it.}
{316}{}{So what brought you to Ranger territory?}
{317}{}{Talk, about the Rangers and their justice. The talks all lies and exaggerations. If you want their support, you have to give them everything you've got. And then, MAYBE, they'll help you.}
{320}{}{Have you seen the farmers' dog?}
{321}{}{I saw one, but where it went, I don't know. The farmers should've fed it better.}
{322}{}{I see.}
{323}{}{Did you kill the farmers' dog?}
{324}{}{Is it that obvious? Then no point denying it. I needed food, and that damn beast wouldn't let me near the plantation. Plus, it almost let the farmers know I was hiding here! I had to do something.}
{325}{}{Quite a risky decision...}
{326}{}{Hey! You better not blab about this to anyone, right? Got it?}
{327}{}{Uh, yeah, no problem.}
{330}{}{Now, will you tell me what really happened here?}
{331}{}{(sighs) I know a couple of guys from Phoenix who need the Rangers' radio cipher. They promised good pay.}
{332}{}{And you got wounded while trying to get the cipher?}
{333}{}{You have to take risks for caps. I tried to infiltrate the radio station at night but got shot instead. Since then, I've been hiding in this basement, unable to do anything... Hey, do you want to earn some caps with me?}
{334}{}{Who are these guys who need the cipher?}
{335}{}{I'd tell you, but then I'd lose a great payday. Got it?}
{336}{}{Any ideas on how to get the cipher?}
{337}{}{The Rangers' radio station has all the info. Convincing someone to share it is nearly impossible.}
{338}{}{There must be others trying to get the cypher.}
{339}{}{Maybe. But I don't know any.}
{340}{}{I'll think about your offer.}
{341}{}{Your clients were fire worshippers, right? In that case, I have bad news - the Cathedral of Fire is destroyed.}
{342}{}{What?! Are you serious?! Do you know what this means? I just lost my payday *and* the whole Wasteland's about to spiral into chaos! There's no way I'm going back to Phoenix now... I'll have to head for the mountains and live off the land till things calm down. Forget the cipher - it's useless to me now.}  
{343}{}{Right, there's nothing more for you here.}
{344}{}{Why haven't you left? The Rangers are almost certainly looking for you.}
{345}{}{I have no choice. If I don't get the cipher, the clients will kill me... and if not them, then the loan sharks I owe.}
{346}{}{I had another question.}
{347}{}{What do you want to know?}
{348}{}{Let's talk about the cipher.}
{349}{}{Tell me more about this situation.}
{350}{}{I know the cipher.}
{351}{}{Well? What's the cipher?}
{352}{}{Not so fast. What's in it for me?}
{353}{}{A pile of caps. I stashed them in a safe place. But first, I need to know you actually got it.}
{354}{}{Here's the cipher.}
{355}{}{I'm not telling you anything for nothing.}
{356}{}{That was a smart move, don't you think? Now the fire worshippers will pay me a fortune. They'll be *forced* to accept me into their ranks! I'll join the Phoenix elite, got it?!}
{357}{}{Sounds great. If I end up in Phoenix, will you help me get in too?}
{358}{}{You won't even need caps, got it? We need people with vision. See you around. I gotta go.}
{359}{}{See you!}
{360}{}{I'm only interested in my caps.}
{361}{}{Oh yeah... You'll get them right now! (prepares to attack)}
{362}{}{Hey, this wasn't part of the deal!}
{363}{}{You back-stabbing son of a bitch!}
{364}{}{I have a better idea. I'll help you right now... to stay silent!}
{365}{}{Hey, what about my caps?!}
{366}{}{The Church of the Holy Fire needs new blood. But you, pathetic worm, are not worthy of initiation!}
{367}{}{I won't stand by and let this crazy cult spread. Time to die!}  
{368}{}{So we'll become brothers in faith?}
{1368}{}{So we'll become siblings in faith?}
{369}{}{Something tells me you're not really from the Church. But... your medical skills... Anyway, see you around. I gotta go.}
{370}{}{See you... initiate.}
