{100}{}{You see a ferryman by the water.}
{101}{}{You see a balding redneck, his face twisted in a grin.}
{102}{}{Oh yeah, you sure know how to please an old redneck.}

#First Dialogue
{200}{}{What brings you out here to these parts?}
{201}{}{Maybe I'm looking for you.}
{202}{}{Well, I'm Jo. Been living here, guarding this ferry. Wanna head to the other side? Easy peasy... but not for free, I'm sure you get that.}
{1202}{}{Well, I'm Jo. Been living here, guarding this ferry. Wanna head to the other side? Easy peasy... but not for free, I'm sure you get that.}
{203}{}{I'll mull it over.}

#Re-Dialogue
{210}{}{Hey there.}
{211}{}{Catch you later.}
{220}{}{What's it like living out here in the wilds?}
{221}{}{No gripes. Place ain't exactly quiet. Folks come through here daily - Rangers, fishermen, or just drifters. Everybody pays their due to cross over. And it's enough to keep me ticking.}
{222}{}{[Continue]}
{223}{}{Sure, wolves and pig rats never let up, but after years here, I've learned to handle 'em. Got snares set up in the woods, so stick to the road to save me from fishing you out of my own traps.}
{224}{}{Tell me about the ferry.}
{225}{}{Rangers pitched the idea, I built it. Been holding down the fort here ever since. Anyone needs to cross over, I'm their guy.}
{226}{}{Why would folks need to cross over?}
{227}{}{Mostly it's Rangers on patrol. But plenty without 'em too. Folks journeying to new lands, hoping for a better shake. But lemme tell ya, wherever you go, it's just as rough as anywhere else.}
{228}{}{The Rangers are okay with you charging?}
{229}{}{They're fine, 'cause I pay 'em taxes from it. Once a month, I hand over the goods - hides, meat, trinkets found by drifters. Sometimes don't even know what half the stuff is, but Rangers'll sort it out.}
{230}{}{How'd the dam blowout affect business?}
{231}{}{That disaster wrecked everything here. Shack's still a mess. Can't fathom who'd pull such a stunt. But for me, it's been a boon - ferry's raking in more than ever.}
{232}{}{Interesting. I had another question.}
{233}{}{I had some other questions I wanted to ask you.}
{250}{}{These folks need to get to the other side.}
{251}{}{Then they gotta pay. Dirt cheap. And if they ain't payin', they ain't crankin' the winch. Handle stays with me.}
{252}{}{How much will it cost?}
{253}{}{I'm asking on behalf of the Rangers.}
{254}{}{Dammit, another day down the drain... Here, take the handle. But they turn it themselves.}
{1254}{}{Dammit, another day down the drain... Here, take the handle. But they turn it themselves.}
{255}{}{Thanks.}
{256}{}{You're a real saint.}
{257}{}{Hold on, I'll see if they have the caps.}
{258}{}{Just give me the handle, and avoid a lot of regret.}
{259}{}{Alright, show your hand, tough guy! I've strangled wolves bare-handed, what're your empty threats to me?}
{260}{}{Alright, cut it out!}
{261}{}{I ain't one for hagglin', y'know.}
{262}{}{[More]}
