{100}{}{You see the communications officer.}
{101}{}{You see a stern-looking woman.}

{200}{}{Hey there.}
{201}{}{Later.}
{210}{}{What's the matter?}
{211}{}{Later.}
{220}{}{Tell me a bit about yourself.}
{221}{}{I'm comms officer Jain.}
{222}{}{How'd you end up as a Ranger?}
{223}{}{I just did.}
{224}{}{Well, that clears things up.}
{225}{}{Got any more brilliant questions?}
{226}{}{Sure.}
{227}{}{Nah.}
{228}{}{}
{229}{}{I had another question.}
{230}{}{What's this place all about?}
{231}{}{It's a radio station. Not a radiation station, mind you. Might take a bit to explain. Basically, we use this gear to keep in touch with our patrols from a distance.}
{232}{}{Impressive that all this tech still functions.}
{233}{}{Yeah, it's a miracle, huh? Kept running thanks to trade caravans for parts and power from the local dam.}
{234}{}{Not many folks in the wastes have Old World tech.}
{235}{}{That's right. Tech's a lifeline out here. Some folks fear places like this, but for us, it's a legacy passed down through generations, documented on holotapes. It's a kind of relic for us.}
{236}{}{Where is everybody? The place seems deserted.}
{237}{}{Got enough noise on the radio. And outsiders ain't welcome here, especially not ones with loose lips.}
{238}{}{Thought you might want to unwind somewhere.}
{239}{}{Where? I'm up for taking down some coyotes, but your company's not really my scene.}
{240}{}{A little frustrated with people?}
{241}{}{Maybe a bit. Dealing with cadets causing trouble or sergeants ignoring orders tends to sour your view of folks.}
{242}{}{What's with the field of crosses by the station?}
{243}{}{That's our cemetery. Rangers and their kin rest there. Hope you're not thinking of desecrating those graves. 'Cause that'd be the last mistake you'd make.}
{244}{}{I've got another question about the... rad-station...}

{250}{}{I need the radio codes.}
{251}{}{That's classified info, not for the ears of common folk.}
{252}{}{I'm a new recruit.}
{253}{}{Alright, forget I asked.}
{254}{}{Then shove 'em where the sun don't shine.}
{255}{}{Sorry 'bout that. Here are the codes and the cipher for the main communication frequencies. But remember, recruit, these stay between us Rangers.}
{256}{}{Much appreciated, officer.}
{257}{}{Got it, thanks.}
{260}{}{The dam's blown, so why stick around?}
{261}{}{In times like these, my role's even more crucial. Command's scouting for a new HQ, and without remote comms, they're flying blind.}
{262}{}{Go on.}
{263}{}{Won't last forever, though. Standby generators' juice is limited. Once it's out or this station's wrecked, we're toast. At least we've got a decent view of the valley from up here.}
{264}{}{Got it.}
{270}{}{Heard you nabbed that spy lurking around the farmers. Good work.}
{271}{}{I was happy to lend a hand.}
{1271}{}{I was happy to lend a hand.}
{272}{}{Just doing my part.}
{273}{}{So, you're the reason Jason made it out of the Jackals' claws? Impressive. Thought we'd lost the lot of 'em.}
{274}{}{Just happy to help.}
{1274}{}{Just happy to help.}
{275}{}{You're welcome.}

#Story quest
{278}{}{Really?}
{279}{}{Problem is, half the repeaters have been offline for ages. Need fixing or replacing. Once they're up and running, we'll have good enough coverage to control territory up to San Brahmin... maybe even Phoenix.}
{280}{}{I was sent here by Commander Helford.}
{281}{}{Fantastic, just fantastic. Station's falling apart and Helford sends in the peasants to fix it! You got any clue how a radio station works?}
{282}{}{I'll figure it out. What's the plan?}
{283}{}{Right now, our boys are stretched thin on the eastern and south-eastern fronts. But some outposts are out of touch, even though they shouldn't be.}
{284}{}{So where's the busted equipment?}
{285}{}{Down in the basement under the antenna. You'll need more than tin cans and forks for this job. Might find what you need in Garage City from the Scavengers, but they ain't too fond of Rangers. Can you handle that?}
{286}{}{I'll check it out...}
{287}{}{Hold up. You're heading to Garage for components, right? Got another favor then. Lost a patrol in that area. See if you can dig up what happened to 'em. Our radios can't reach that far, but they can pick up signals nearby. Rangers'd be mighty thankful if you can pull this off.}
{288}{}{I'll find out what happened, don't worry.}
{289}{}{I can't make any promises.}
{290}{}{The radio's back online.}
{291}{}{The echo problem is taken care of. The spy's repeater has been put out of commission.}
{292}{}{What was I supposed to do again?}
{293}{}{So it's too much for your brain to handle, huh? Hunt down the source of the echo in our broadcasts. Head out into the desert, south or east, and use the walkie-talkie to track the signal. Pinpoint where it's coming from.}
{294}{}{Alright, let's get this done...}
{295}{}{[Continue]}
{296}{}{Good job! But hold on... You hear that?}
{297}{}{An echo? Something's repeating our signal?}
{298}{}{Sounds like it... Signal's faint, coming from the south... maybe east... We didn't catch this before. Could be a glitch in the new gear, but... Listen, we gotta know for sure what it is. Can't ignore this noise.}
{299}{}{[Continue]}
{300}{}{Head south or east toward the signal's source and find out what's causing the echo. You'll have to head way out into the desert. Take this walkie-talkie to track it down.}
{301}{}{I guess this job isn't over yet...}

{302}{}{Well, this is unexpected! Thought we were the only ones with tech for broadcasts this powerful. Report to Commander Helford ASAP.}
{303}{}{[Continue]}
{304}{}{You got somethin' there... Tell Commander Helford how the operation went down.}
{305}{}{Aye-aye!}
