{110}{}{This lifting mechanism holds the dam gate in place with steel cables.}
{111}{}{The lifting mechanism has failed. It likely can't be repaired.}
{112}{}{Not a scratch left on the mechanism.}
{113}{}{The lifting mechanism breaks into pieces, and the support cables whiz into the darkness. A few moments later, at the bottom of the shaft, you hear the thundering crash of the fallen shutter.}
{114}{}{Well... the floodgates have opened. Literally.}
