{100}{}{You see a runaway slave.}
{101}{}{You see one of the runaway slaves making a home in these ruins.}

{110}{}{The Tinsmiths are gonna pay for what they've done.}
{111}{}{The Tinsmiths took your family too? I know the feeling...}
{112}{}{If you despise the Tinsmiths, you're among friends here.}
{113}{}{Looking to join us?}
{114}{}{Join us. We need more gutsy fighters.}
{115}{}{Got any weapons? Food or water?}
{116}{}{What are you staring at?}
{117}{}{Never heard of the Arizona National Bank.}
{118}{}{Money? We use it for kindling. Why, you need some?}
{119}{}{The fight for freedom is all we've got left.}
