{100}{}{You see a doctor.}
{101}{}{You see Doc Jones. He looks more like a mechanic than a doctor.}
{102}{}{The operation was successful.}

# Floating replicas (do not remove empty lines)
{110}{}{Fixing people is harder than fixing machines.}
{111}{}{Never thought about what goes into stimpaks.}
{112}{}{Injuries have been more frequent lately.}
{113}{}{Lose a few more patients and I'll be up for a technical inspection.}
{114}{}{ }
{115}{}{ }
{116}{}{ }
{117}{}{ }
{118}{}{ }
{119}{}{ }

# First dialogue
{200}{}{Ahh, fresh biological material. Lie down there. (points unceremoniously at the dirty operating table) What are we fixing today?}
{201}{}{I'm not a machine you can just *fix*.}
{202}{}{Understood. If the material is exceptionally fragile, then surgical amputation is the optimal solution. It ensures maximum efficiency.}
{203}{}{Hey, were not cutting anything off either!}
{204}{}{Really? (adjusts strange glasses with glowing lenses and examines you) Where does it hurt?}
{205}{}{Uh, doc... maybe we should talk first?}
{206}{}{Wait, Doc, I'll be back soon...}
{207}{}{Tourniquets are gone, so you'll have to tough it out.}

{210}{}{Well, what is it?}
{211}{}{Wrong door, Doc.}
{212}{}{Enough talk.}
{213}{}{Another question.}

# Treatment
{220}{}{I need healing.}
{221}{}{My medical services are exclusively for fellow Tinsmiths and individuals designated by our leader.}
{222}{}{That's not good.}
{223}{}{You have caps? Then point out where the issue is.}
{224}{}{Nothing.}
{225}{}{Just heal my wounds, Doc.}
{226}{}{}
{227}{}{The cost of treatment will be }
{228}{}{ caps.}
{229}{}{Okay Doc, here are the caps.}
{230}{}{You know, Doc, I'll tough it out.}
{231}{}{It can wait. I have questions.}
{232}{}{You're okay.}
{233}{}{Thanks, Doc.}
{234}{}{Next time I'll find another clinic. Bye.}
{235}{}{ caps.}

{250}{}{Can you give me one of those implants of yours?}
{251}{}{(frowning) Master Hard has authorized your medical treatment. However, expending our most advanced implants on a wasteland primitive is inefficient and illogical.}
{252}{}{Are they really that important to you?}
{253}{}{Not every Tinsmith is authorized to install new implants. It demands a valid justification and the body's compatibility. Some must wait for years to qualify.}
{254}{}{Master Hard considers me worthy. I think he won't mind one operation.}
{255}{}{Maybe so. Select the type of implant. Its cost is }
{256}{}{Not now. I need to prepare for such an operation.}
{257}{}{Unfortunately, this implant is contraindicated for your biological system.}
{258}{}{Too bad. Maybe we can try another one?}
{259}{}{Then let's postpone the operation for a while.}
{260}{}{[Strength +1]}
{261}{}{[Perception +1]}
{262}{}{[Endurance +1]}
{263}{}{[Charisma +1]}
{264}{}{[Intelligence +1]}
{265}{}{[Agility +1]}
{266}{}{[Luck +1]}
{267}{}{Great. }
{268}{}{ caps, and we can begin. After the operation, you will require two days to adapt.}
{269}{}{Here are the caps. Get started, doc.}

# Questions
{300}{}{Why is it so dirty in here?}
{301}{}{(looks around in bewilderment) Dirty?}
{302}{}{Doc, I'm afraid to ask, but... how many of your patients survived their surgeries?}
{303}{}{Wait, I'll access on the statistics analyzer... Yes. 58 percent.}
{304}{}{That's... a little more than half.}
{305}{}{This facility handles severe trauma, not minor injuries. Typical cases include electrical burns, radiation exposure, respiratory failures, vision impairment, and gastrointestinal disturbances.}
{306}{}{Uh, I see, Doc. You don't have to continue...}

{310}{}{Tell me about the clinic.}
{311}{}{This is a hospital, not a bar.}
{312}{}{How did you become a doctor?}
{313}{}{My predecessor attempted to enhance his medical capabilities with a neural implant. Unfortunately, a malfunction resulted in a fatal cerebral hemorrhage. Consequently, my fellow Tinsmiths required a replacement, and I was dispatched to train with the Followers of the Apocalypse. I have been serving in this capacity ever since.}
{314}{}{Where do you get your medicine?}
{315}{}{Pre-war pharmaceuticals are predominantly transported by caravans from Phoenix. Contemporary compounds are sourced from a small facility in Casa Nueva, where they maintain their own production capabilities.}
{316}{}{Who are these Followers of the Apocalypse?}
{317}{}{I would classify them as fanatics, obsessed with the knowledge of the Old World. Knowledge devoid of technological application is essentially useless.}

{320}{}{Why do Tinsmiths implant electronics into themselves?}
{321}{}{The biological human form is inherently fragile and vulnerable. By integrating electronic components, we enhance strength, intelligence, and durability. The ultimate aspiration of every Tinsmith is full cybernetic integration and digitalization of consciousness. Regrettably, this remains an unattainable ideal.}

{330}{}{What happened to that patient over there?}
{331}{}{The subject is critically injured. In an attempt to save him, I implemented several implants and prosthetics. However, the delicate human physiology rejects technological integration. He cannot endure without these enhancements, yet even with them, his survival is compromised. A cruel irony.}
{332}{}{Can he be cured?}
{333}{}{Fixed? I'm afraid not. He will have to be "dismantled".}
{334}{}{Can I try?}
{335}{}{If our advanced medical technology cannot restore him, your primitive rituals will be equally ineffective. However, I am open to any intervention in such a dire situation.}
{336}{}{Let's see what my "rituals" can do, Doc.}
{337}{}{Can we talk about something less grim...}
