{100}{}{You see a floating eye.}
{101}{}{You see a robot translator.}
{102}{}{*Psh-sh-sh*}
{103}{}{All you get in response is a static hiss from the loudspeaker.}

{110}{}{I think we understand each other.}

{200}{}{(A floating eye bot greets you with a message from ZAX) Thank you for your help. As you can see, I've already dismantled this hostile settlement. I will release you and your fellow villagers on one condition - never return to these lands again.}
{201}{}{Sounds reasonable.}
{202}{}{I count on your loyalty. Let me make a recommendation. According to my data, the Tinsmiths were accountable to a powerful organization called the Brotherhood of Steel. This organization is behind the rise of slavery in Sonora. You must find a way to eliminate the Brotherhood's main base to reduce future risks to the Villa.}
{203}{}{So they're just going to keep on with their plans, even after their setback here? ...Where can I find this base?}
{204}{}{Head west to the old port of Puerto Penasco on the Sea of Cortez. The safest route passes through the town of Casa Nueva. Like you, I want to eliminate this threat, but don't expect any further assistance. My capabilities are too localized.}
{205}{}{Okay, ZAX, thanks for the help.}
{206}{}{I'm not one of your robots. I'll figure it out without your instructions.}
