{100}{}{You see Granny Adonisia.}
{101}{}{You see a familiar figure - your grandmother. She's puffing on her old, battered pipe, squinting at you through a cloud of smoke with a gaze sharp enough to cut glass.}
{102}{}{Goodbye, Granny. I hope no one ever finds out the real reason for your demise.}
{103}{}{What demon led you against us? Drive it away! Come to your senses!}

# First Dialogue
{210}{}{(takes a long drag, then exhales a plume of dark smoke, scrutinizing you with a critical eye) So, you're here. Luck sure smiled on you, being away from home during the toughest times. Or maybe it'll end up a curse.}
{211}{}{Toughest times? Curse? Please, Granny Adonisia, tell me what's going on?}
{212}{}{Enough grumbling, granny. What happened?}
{213}{}{What happened? What's going on?}
{214}{}{Hmm? Finally listening to your elders, like someone with a bit of sense. There might be hope for you yet.}
{215}{}{Still can't keep that fiery tongue in check, eh? That spitfire might just be what saves you in the end.}
{216}{}{Worried, are you? Not the best trait for decision-making. But when push comes to shove, you'll have to step up. Just remember, worry is like a rocking chair: it gives you something to do but gets you nowhere.}
{217}{}{So, what happened?}

{218}{}{While you were off gallivanting, strangers came. Nasty folks, like a bad wind. About ten of 'em, all armed to the teeth. Our men couldn't hold them off.}
{219}{}{Go on.}
{220}{}{Those devils took everyone fit for work. Left only the old bones and the young sprouts. Now Villa's fate rests in your hands. You've got to do something, and fast.}
{221}{}{What can I possibly do alone?}
{222}{}{What do you think? Get our folks back. At least your parents. They're caught in the clutches of those devils.}
{223}{}{It won't be easy...}
{224}{}{(nods) You bet your boots it won't. And here's a piece of wisdom for you, even if it'll ruffle your padre's feathers. Down in the cellars under the town hall, there's a hidden room with family heirlooms. Only a few of us old bones know about it. Get down there, find it, and take anything useful for your journey. And do it now, time's ticking away.}
{225}{}{Thanks, Granny. Every little bit helps right now.}
{226}{}{Family heirlooms? That's it? Damn, granny, you're no help at all. Fine, I'll check out Dad's cellar.}
{227}{}{Alright, I'll try to find them before I head out.}
{228}{}{Be careful. The cellars are crawling with rats and darker than a brahmin's backside. Take this lighter, though it's like giving away my right arm. And when you find the family heirlooms, head straight to the plaza and find Jose. He's knows a bit that ought to help you along your way.}
{229}{}{Before I go down, I need to ask you something.}
{1229}{}{Before I go down, I need to ask you something.}
{230}{}{I'm going right now.}

{231}{}{Why are you still flapping your gums here?}
{232}{}{Before I leave, I need to ask some questions.}
{1232}{}{Before I leave, I need to ask some questions.}
{233}{}{Indeed, it's time for me to go.}
{234}{}{You did a good job bringing our people back. Well done.}
{1234}{}{You did a good job bringing our people back. Well done.}
{235}{}{I have questions.}
{236}{}{I need to go.}
{237}{}{Well, it's on me then. I'll do everything I can.}
{238}{}{Get our folks back. Your parents are among the captives too. Whether you like it or not, you'll have to save them. Blood for blood, shoulder to shoulder - that's what our ancestors always said. Do nothin', and you'll doom the community faster than a brahmin on the grill.}
{239}{}{You must be out of your mind! What can I do against a whole gang of raiders?}

# Inquiries
{240}{}{Find Jose by the plaza, he knows more than this old bird does.}
{241}{}{What happened in the attack?}
{242}{}{Did anyone die?}
{243}{}{What about my parents?}
{244}{}{This hidden room in the cellars raises some questions.}
{245}{}{What should I do after I find the family heirlooms?}
{246}{}{Alright, I'm leaving.}
{247}{}{I have another question.}
{248}{}{Your parents were taken by 'em too. Whether you like it or not, you'll have to save them. Blood for blood, shoulder to shoulder - that's what our ancestors always said. Do nothin', and you'll doom the community.}

{250}{}{The strangers stormed in like a pack of hungry coyotes, without any warning. Tied up everyone who could work and took them east at first light. Jose knows more, get the story from him.}
{251}{}{There was a real bloodbath in the town hall. Some were killed, others got hurt bad. If you've got a weak stomach, best stay clear of there.}
{252}{}{Your padre and madre were also taken, so you'd best hurry up before something worse happens to them.}
{253}{}{Of course, only us old bones knew about the Founder's hidden room. It holds some truly ancient things and knowledge that not everyone in the Villa is supposed to know. Your padre would've taken you there when he thought you were ready.}
{254}{}{It's obvious, aint it? First find Jose and ask him about the raid. Then go after the raiders. You'll have to make decisions on your own after that.}
{1254}{}{It's obvious, aint it? First find Jose and ask him about the raid. Then go after the raiders. You'll have to make decisions on your own after that.}
{255}{}{But you old folks always taught us not to use things from the Old World. Now it turns out even the Founder broke that taboo?}
{256}{}{Don't jump to conclusions. The taboo was there to protect you from the dangers of the Old World. But not all are dangerous. Some are worth their weight in gold.}
{257}{}{Maybe if we knew more about things from the Old World, we'd have been ready for the raider attack.}
{258}{}{(thoughtfully takes a drag and releases a thick cloud of smoke that lingers like a bad memory) The Founder didn't think so. He said our job was to grow crops. That's how we survived the rough times. We did just fine without technology from the Old World. Would we have lived better with it? I don't know. Nobody knows.}
{259}{}{Granny Adonisia, did you know the Founder?}
{260}{}{Oh, that was so long ago, I don't even remember his face. I remember his mustache, though, like a bristly broom. But that's old history, don't clutter your head with it. You've got more pressing issues.}

{261}{}{Granny, did you know the Founder was a traitor to his Vault?}
{262}{}{Oh really. Did your padre show you his records? Well, Felix carried a heavy load and his conscience visited him in nightmares every night. It's not for you to judge him. He gave life to this place, even if it cost many lives. So, appreciate it.}
{263}{}{Don't clutter your head with idle thoughts. That's not what you should be focusing on now.}

# After Story Completion
{300}{}{You shouldn't have come back to the Villa after all you've done. You're like a bad penny, you know that? Always turning up where you're not wanted.}
{1300}{}{You shouldn't have come back to the Villa after all you've done. You're like a bad penny, you know that? Always turning up where you're not wanted.}
{301}{}{Oh, come on. Like you're all saints here.}
{302}{}{The Wasteland opened my eyes to the world. You've all got it wrong here.}
{303}{}{It's not for you to decide how we should live! The Villa has survived thanks to the traditions and values we chose. The wasteland can dictate another path to us. But you...}
{304}{}{What?}
{305}{}{You're just a hypocrite hiding your foolishness behind the outside world! Get out and don't come back. I curse you, }
{306}{}{!}
{307}{}{Take it easy, Granny.}
{308}{}{You're the hypocrites. I'm not taking another step into this snake pit.}
{309}{}{The Founder of the Villa urged unity. But now, it's too late. This corruption can't be undone as long as your influence lingers.}
{310}{}{By the way, what happened to the Founder?}

{320}{}{I'm proud of you, }
{321}{}{.}
{322}{}{Really?}
{323}{}{That's nice to hear from you.}
{324}{}{You've traveled far and wide, but you've stayed true to your roots and your family. Now, I can shuffle off this mortal coil knowing that the Villa is in good hands.}
{1324}{}{You've come a long way, yet you've remained loyal to your home and family. Now I can finally rest easy, knowing that the Villa is in safe hands.}
{325}{}{How could you ever have doubted me?}
{326}{}{Thanks for the kind words, Granny.}
{327}{}{Us old-timers know a thing or two more than the young'uns. We've seen the cities beyond and the gadgets of the Old World. We've learned that only shared hardships can knit folks together. When life's all roses, there's no stopping folks from showing their selfish streak.}
{328}{}{I can't argue with that.}
{329}{}{Experience has given me a new appreciation for your wisdom.}
{330}{}{That's when you get bickering and families breaking apart. Maybe that raid was a wake-up call - a reminder that we must stick together. The Founder of the Villa understood this well and wrote it down for all of us to remember.}
{331}{}{Speaking of the Founder, what happened to him?}

{340}{}{So, }
{341}{}{, you're back. Right back where you started. But something in you has changed, hasn't it?}
{342}{}{Yeah, I woke up. I know now you elders really kept us 'young'uns' in the dark.}
{343}{}{The Wastes have changed us all. Change is the only constant.}
{344}{}{The Villa has survived on the traditions and values we held dear. The wasteland can't dictate our path. You ought to lend an ear to your family's wisdom.}
{345}{}{I'm not here to argue. I've got my own ideas now.}
{346}{}{Maybe you're right. And what of it?}
{347}{}{The Villa's Founder warned us to stick together. But now it's too late - the raid could have united the community. Your meddling might just sow discord.}
{348}{}{Speaking of the Founder, what happened to him? I don't really know the full story.}

{350}{}{He worked himself to an early grave, toiling in the fields and working on the buildings. We didn't bury him in the ground like tradition dictates. We carried him to a cave and built a brick sarcophagus around him. That crypt still stands strong today.}
{351}{}{Crypt? I never knew that. Can you show me this crypt?}
{1351}{}{Crypt? I never knew that. Can you show me this crypt?}
{352}{}{Hmph. Well, time for me to go. Goodbye, Granny.}
{353}{}{Alright. Maybe a visit to his crypt will soften that hard heart of yours.}
{354}{}{Alright. I think you've earned a trip to that sacred spot.}
{355}{}{Alright. Perhaps a visit to the crypt will bring you some inner peace.}
{356}{}{Let's go. I'm ready to head there right now.}
{357}{}{Great, but, uh, now's not the time. Let's head there when I can find a free moment.}

{360}{}{Close the door behind when you leave.}
{361}{}{I'm on my way out now. Goodbye, Granny.}
{362}{}{I want to see the Founder's crypt now. Can you take me there?}
