{100}{}{You see a peasant.}
{101}{}{You see one of your fellow villagers, freshly back from Flagstaff.}
{102}{}{Hey, did you let things go to your head a bit, after all your exploits? Careful.}
{103}{}{Stay back, tough guy! I can handle myself!}

{110}{}{What a mess!}
{111}{}{It's going to be tough to fix this without parts.}
{112}{}{I wish these so-called heroes would stop showing up at my door.}
{113}{}{Looks like someone's been poking around my cellar.}
{114}{}{That's it, I'm locking the cellar from now on.}
{115}{}{We're going to need a new door.}
{116}{}{Damn raiders, they'll pay for this!}
{117}{}{If I were in charge of the Villa, this would never have happened!}
{118}{}{Where was the village Council during all this?}
{119}{}{We're never trusting outsiders again.}

{200}{}{Hey there. Thanks for saving my hide. Now, if you'll excuse me, I've got a house to fix up.}
{201}{}{Goodbye.}
{202}{}{Sorry, I rummaged through your cellar and took some supplies.}
{1202}{}{Sorry, I rummaged through your cellar and took some supplies.}
{203}{}{So it was you. Not exactly polite to go rifling through other folks' things, don't you think?}
{204}{}{I needed supplies and stuff to rescue you and the others.}
{205}{}{Cut the crap! No matter how big of a hero you think you are or what deeds you've done, you still gotta ask before poking around in other people's stuff. Got it?}
{1205}{}{Cut the crap! No matter what kind of heroine you are or what feats you've achieved, you must ask permission before messing with other folks' things. Understand?}
{206}{}{Ungrateful... go to hell.}
{207}{}{I see.}
{208}{}{I've got time on my hands. Need help with anything?}
{209}{}{I've still got some things in the cellar. Go down and see if there's anything you can use. The entrance is buried under boxes in the pantry.}
{210}{}{Thanks.}
