{100}{}{You see Eden.}
{101}{}{You see a boy named Eden. He looks wild and scared.}
{102}{}{*Silently nods head*}
{103}{}{Eden has returned to Villa.}

{200}{}{(looks at you in fear, without saying a word)}
{201}{}{Hey, don't you know it's dangerous to walk around here alone?}
{202}{}{(continues to stare at you in fear)}
{203}{}{Look, it's tough for everyone right now. But together we can survive. Come on, let's head back to the village.}
{204}{}{Don't worry, I'll take care of you.}
{205}{}{Then stay here and starve, you little brat. I'm leaving.}
{206}{}{It's too dangerous here. Let's go back to the Villa.}
{207}{}{Hey, look, I have a juicy mutfruit. You're probably hungry, right?}
{208}{}{Stay here, I'll be back soon.}
{209}{}{Oops, I think it fell out of my pocket. Stay here, I'll be back soon.}

{210}{}{(silently shakes his head and backs away from you)}
{211}{}{Ahh! (It looks like Eden is now ready to follow you)}
{212}{}{Great, follow me.}
