{110}{}{Bad people won't come back? Is it true?}
{111}{}{. . .}
{112}{}{Your arrival in Power Armor alarmed the local population.}

{200}{}{(the girl stares at your iron armor in stunned silence, torn between awe and terror)}
{201}{}{Greetings, child. From now on, the Big Iron Man will be your protector. The bad people won't dare come back.}
{202}{}{(her eyes widen in admiration, then she runs off to spread the tale of the Big Iron Defender)}
{203}{}{You don't have to be afraid anymore, child. You're under my protection.}
{204}{}{Yes, run and tell everyone, spread the tale.}
{205}{}{[Ignore and move on]}

{210}{}{What're you staring at? Keep it up, and I'll crush you just for looking at me wrong!}
{211}{}{Ahhh! El Diablo! El Diablo!}
{212}{}{Diablo? This new generation is doomed...}
{213}{}{}
{214}{}{[Ignore and move on]}
