{100}{}{You see a farmer.}
{101}{}{You see a man with worn-out hands, carrying a bag of supplies.}
{102}{}{First, let's put away the weapons. Alright?}

{200}{}{Well, howdy, traveler. Looks like you're here to chat, not scrap. What can I do for ya?}  
{1200}{}{Well, howdy, traveler. Looks like you're here to chat, not scrap. What can I do for ya?}  
{201}{}{Probably nothing. Bye.}
{202}{}{Where are you headed?}
{203}{}{Off to the nearest town to do some tradin'. Folks can't get enough of my produce.}  
{204}{}{What are you selling?}
{205}{}{Got more crops than I can eat. Lookin' to swap for things I can't grow myself.}  
{206}{}{Should we trade here?}
{207}{}{Sure thing. Saves me a trip.}  
{208}{}{Maybe another time.}
{209}{}{Let's see what you've got.}

{210}{}{Alright then, I best be goin'.}  
{211}{}{Bye.}
{212}{}{Hmm... you look mighty familiar... Hey! The Rangers got their sights on you, don't they? I don't care why. Just keep movin'.}  
{213}{}{Bye.}
{214}{}{Better keep quiet about me...}
{215}{}{Hmm... you look mighty familiar... Hey! The Rangers are after you, huh? Don't worry, I ain't sayin' nothin'. They're after me too, heh.}  
{216}{}{That's good. Where are you headed?}
