{100}{}{You see a ghoul.}

{110}{}{How old are you?}
{111}{}{We've trekked from Necropolis to the Hub, and then from the Hub to San Diego... Now here we are.}
{112}{}{San Diego's just super mutants and ghouls these days.}
{113}{}{There's a wall of radiation in the northwest.}
{114}{}{California's off-limits, thanks to the mountains, mutants, and radiation.}
{115}{}{Got wanderlust too, huh?}
{116}{}{Damn smoothskins ran us out of our homes.}
{117}{}{I miss the charred ruins of old Necropolis.}
{118}{}{You use caps too? Small world.}
{119}{}{The Master had a thing for breeding flying worms and mixing people with dogs.}
{120}{}{The Master's dead, his army in ruins.}
{121}{}{I don't know who this 'Exit' was, but he sure got lucky.}
{122}{}{The Vault Dweller only cared about themselves.}
{123}{}{If one smoothskin hadn't blown up the Cathedral, we'd still be stuck there.}
{124}{}{Ever heard of the Vault Dweller?}
{125}{}{We're just aimlessly wandering.}
{126}{}{San Diego's packed.}
{127}{}{Dayglow's in the northwest, but you can't get there.}
{128}{}{Seen those ugly giant worms?}
{129}{}{}

{130}{}{Sorry, smoothskin, but you can't tag along.}
{131}{}{Didn't expect to see a normal guy out here.}
{132}{}{Hey smoothskin, we don't take kindly to your type here. But yeah, that's true.}
{133}{}{You normies are always so miserable. Take it easy and enjoy the ride.}
{134}{}{No room for smoothskins in our group. We've got a special vibe, you know.}

{150}{}{Sorry, my decaying friend, but you can't come with us.}
{151}{}{Never thought I'd see a freak like me around here.}
{152}{}{Normies, they're total assholes. Ain't that the truth?}
{153}{}{Getting shunned by the normies too? We know that feeling all too well.}
{154}{}{We'd take you, but we're wandering aimlessly ourselves.}
