{100}{}{You see a hunter.}
{101}{}{You see a man with a thick beard. He seems pretty exhausted from the hunt.}
{102}{}{How about we both lower our weapons, friend?}

{200}{}{Greetings, wanderer. It's rare to see a soul around these parts. For a moment, I thought you were game.}
{1200}{}{Greetings, wanderer. It's rare to see a soul around these parts. For a moment, I thought you were game.}
{201}{}{You're a hunter, I take it?}
{202}{}{That's right. Not much to hunt out here, but enough to keep me fed and bring in some trade at the city.}
{203}{}{What city are you talking about?}
{204}{}{Flagstaff? It's a sizeable colony near an old mine. Founded a few years back, and the ruins have transformed since then. Take the high road, you can't miss it.}
{205}{}{Thanks. What's the game like around here?}
{206}{}{Can I buy some provisions for the journey?}
{207}{}{I've just dried some fresh meat. I can trade it for something useful.}
{208}{}{Maybe next time.}
{209}{}{I could use a restock.}
{210}{}{Alright, I should move on before this meat spoils.}
{211}{}{Stay safe out there.}
{212}{}{Hey, you know the garrison boys were looking for you? They seemed pretty steamed. Be wary of them; I'm not one to meddle, but if they see me with you, it'll make selling my game a real pain.}
{213}{}{Hold on. I'd like to trade for some of that jerky.}
