{110}{}{This crate is nailed shut. Only brute force will get it open.}
{111}{}{You lack the strength to wield the tool effectively.}
{112}{}{You managed to pry the lid off the crate.}

{120}{}{You've pried open one side a bit. Push harder!}
{121}{}{Just a little more effort and you'll get it!}
{122}{}{Keep at it! This crate's almost busted open.}
{123}{}{Almost... Come on, wastelander, give it all you've got!}
{124}{}{Not quite there. You need to push a bit more.}
{125}{}{Almost there! Just a bit more effort!}
