{110}{}{You haven't learned anything new yet. Maybe try exploring more methodically.}
{111}{}{?}
{112}{}{Systems analysis isn't your strong suit.}
{113}{}{This can't be fixed.}
{114}{}{You will need to use a scientific approach to study this object.}
{115}{}{What's THIS doing here?}
{116}{}{Your companion failed to gather any valuable information.}

# 20 lines are allocated for one location.
# For each object, 2 adjacent lines are created:
# - first under the message in the log
# - second under the line above the GG (if not needed, put spaces in it, otherwise the GG will say Error)

#Villa
{200}{}{This is an old midwife's chair. You were born in it.}
{201}{}{Not the most pleasant memories.}
{202}{}{This ancient machine isn't functioning -- completely rusted from moisture.}
{203}{}{It's not working. And it never will.}
{204}{}{This computer is so old that its parts are rusted solid. It hasn't been used for at least forty years. Not surprising for Villa.}
{205}{}{Padre didn't tell me...}
{206}{}{You conclude that the symbol depicts a winged creature rising from a fire. But you're not sure.}
{207}{}{This symbol was left by the raiders.}
{208}{}{One of the local engineering feats. Since childhood, you weren't allowed near it as all the seats were always taken.}
{209}{}{Seems like some of our ceramics were traded with neighboring settlements.}

#Jackals
{210}{}{}
{211}{}{}
{212}{}{}
{213}{}{}
{214}{}{Probably a nuclear ramjet. This technology is too complex for the modern world.}
{215}{}{It's going to take a LOT of work to get this moving on its own.}
{216}{}{This equipment controlled the flow of a complex gas mixture into the sarcophagi. It was recently disabled by an internal timer.}
{217}{}{Wow, they must have been asleep for decades.}
{218}{}{This structure of planks and skulls must represent something from the pre-war era. The number 15 is painted on a piece of skin.}
{219}{}{An echo of ancient times, its meaning lost.}

#Flagstaff
{220}{}{It appears that surgeries are performed here, and the basement hides the cries of the sick.}
{221}{}{And no hygiene...}
{222}{}{The information on the stand doesn't match reality. This mine appears to be from pre-war times.}
{223}{}{This stand is older than the colony.}
{224}{}{This ancient poster encourages women to work hard during the war.}
{225}{}{In the Villa, they work without any need for 'persuasion'.}
{226}{}{The sign reads: "Museum of Northern Arizona." Below is the caption: "Museum, shop, and library."}
{227}{}{I don't know what a "museum" is.}
{228}{}{As you look at the ancient exhibit with interest, you suddenly discover a forgotten grenade at its base.}
{229}{}{Where did this come from?}

#SanBrahmin
{230}{}{This exhibit inspires admiration and fear at the same time.}
{231}{}{It's good there are no such monsters in the world anymore... I think.}
{232}{}{Movie titles are written here. You've never seen them. You haven't seen any films at all.}
{233}{}{ }

#Phoenix
{240}{}{Hidden security cameras allow Aaron to monitor the cathedral's premises.}
{241}{}{Seems like the Lord of Phoenix is obsessed with security and control.}
{242}{}{After studying the winning statistics, you've made some conclusions. Playing roulette will be 15% more successful now.}
{243}{}{Heh, sometimes wear and tear works in your favor.}
{244}{}{You've learned the recipe for making Wasteland Tequila.}
{245}{}{Now I see why only casinos bother with this.}
{246}{}{You already know the recipe for making Wasteland Tequila.}
{247}{}{I've had enough of these numbers.}
{248}{}{This statue has no inscriptions left. It's anyone's guess why it was placed here.}
{249}{}{Looks quite... fitting. For these ruins.}

#Two-Sun, Vault 27
{250}{}{This computer was cobbled together by Tinsmiths from various components. Surprisingly, it works great.}
{251}{}{Looks like the Tinsmiths have made some good progress.}
{252}{}{Blackened gold bars. They say they used to fetch a high price, but now no one will pay even one cap for them.}
{253}{}{This gold lost its value a long time ago.}
{254}{}{Among the payment orders, you find information about slaves. They are mainly transported to Two-Sun.}
{255}{}{Maybe it's worth visiting Two-Sun and checking out the slave situation.}
{256}{}{You found some kind of code on the back of the painting.}
{257}{}{Hmm, what do these numbers mean?}
{258}{}{These mercenaries were killed by a massive explosion. But one of them died from a shot to the head with a 10mm bullet.}
{259}{}{Not worth looking at for too long.}

#Rangers, Quartzsite
{260}{}{This ancient sign shows the distance to the dam. A painted inscription on top reads: "Rangers Territory".}
{261}{}{Up the road is Parker Dam - the Rangers' citadel}
{262}{}{You carefully studied the Rangers' maps. Traveling around the area will now be much easier.}
{263}{}{Wow, the cartographer really knows his stuff.}
{264}{}{The cartographer won't let you look through his maps.}
{265}{}{   }
{266}{}{Rangers rely more on themselves than on technology, even with such tech right under their noses.}
{267}{}{This computer hasn't been used in a long time}
{268}{}{"Warning! Restricted area. All persons in this area are subject to Federal law protecting this site."}
{269}{}{Looks like this sign has been here since pre-war times}
{270}{}{A homemade "reactor" that locals unsuccessfully tried to build. The failure resulted in an accident and radiation contamination of the area.}
{271}{}{So this is what happened here}
{272}{}{Visitor information: "Quartzsite, founded in 1879, elevation 879".}
{273}{}{Probably a lot of people used to pass through this town}
{274}{}{"Parker Dam, founded in 1934-1938, reconstructed in 2055".}
{275}{}{That's a *very* old structure}
{276}{}{An old road sign. A Ranger mark is painted on it.}
{277}{}{This mark means the settlement is under Rangers' protection}
{278}{}{}
{279}{}{}

#Other locations
{280}{}{"Monument to the Victims of the Annexation and Border Riots of 2051."}
{281}{}{So the US annexed Mexico after all.}
{282}{}{Security system disabled.}
{283}{}{How's that for you, rusty tin?}
{284}{}{"Attention, traveler! Alcohol, drugs, and open carrying of weapons are prohibited here. Theft of crops is punishable by death. There is a curfew at night."}
{285}{}{Strict rules here.}
{286}{}{The guest log ends in 2077.}
{287}{}{Nothing interesting.}
{288}{}{This painting is over a hundred years old. It's amazing that it survived at all.}
{289}{}{Was this really painted by hand?}

#Puerto
{290}{}{Brotherhood of Steel radio frequencies copied.}
{291}{}{Great, now I can eavesdrop on Brotherhood patrols.}
{292}{}{This ramp goes down. What a surprise.}
{293}{}{?}
{294}{}{You carefully studied the maps of the Brotherhood of Steel. Now traveling around the area will be much easier.}
{295}{}{Brotherhood scouts don't get their IRP for nothing.}
{296}{}{You are trying to find Villa without success. But you are amazed by the scale of the continent.}
{297}{}{Is the world really this big?}
{298}{}{This welcome sign is bilingual in Spanish and English.}
{299}{}{I guess these ruins were once a nice place...}

{300}{}{This equipment is used to communicate with Puerto Penasco.}
{301}{}{Standard radio transmitter.}
{302}{}{This equipment used to be used to communicate with Puerto Penasco.}
{303}{}{Standard radio transmitter.}

