{110}{}{This mini-lab is filled with various components. It takes knowledge to make something useful out of it.}
{111}{}{This mini-lab is empty. It's useless now.}
{112}{}{You should have spent more time on your chemistry textbooks.}
{113}{}{After a lot of work, you have produced one stimpak.}
{114}{}{After a lot of work, you have created two stimpaks.}
{115}{}{After a lot of work, you have produced three stimpaks.}
{116}{}{You've made some fuel.}
