{100}{}{You were caught in a rockfall. You got off easy this time.}
{101}{}{The mountains tried to stop you, but you dodged the falling rocks with ease.}
{110}{}{You've crossed irradiated lands and taken on a high dose of radiation.}
{120}{}{You're caught in a relentless dust storm!}
{130}{}{You're desperately trying to find water, but to no avail.}
{131}{}{After an exhausting search, you finally find some water.}
{132}{}{You managed to stay hydrated, thanks to your own water supply.}
{133}{}{You stayed hydrated, thanks to the supplies in your trusty flask.}
{134}{}{Looks like there was an accident here recently. That's the price of speeding!}
