#include "..\headers\define.h"
//---------------------

#define NAME                            SCRIPT_ZCFloatr
#define TOWN_REP_VAR                    -1   // привязка к репутации (-1, если не нужно)

#define NUM_TEAM                        TEAM_DEATHCLAW        // группа, к которой принадлежит персонаж (-1 если нужно оставить Team, заданный в редакторе)
#define NUM_AI                          AI_FLOATER            // AI персонажа (-1 если нужно оставить AI, заданный в редакторе)
#define KILL_SLAVA                      SLAVA_KILL_BAD        // слава за убийство этого персонажа (SLAVA_KILL_GOOD, SLAVA_KILL_BAD, SLAVA_KILL_NEITRAL, SLAVA_KILL_CHILD)
#define KILL_TOWN_REP                   REP_KILL_NEITRAL      // репутация за убийство этого персонажа (REP_KILL_GOOD, REP_KILL_BAD, REP_KILL_NEITRAL, REP_KILL_CRITICAL для враждебности всего поселения, REP_KILL_CHILD)
#define KILL_FRAC_REP                   FRAC_NON              // принадлежность определенной фракции (-1, если не нужно)

#define FLAG_STEAL                      300 // Нижний порог навыка для кражи (для торговцев 200, для животных 300)
#define FLAG_ALCOHOL                    1  // Примет ли алкоголь от ГГ: 0 - принимает, 1 - не принимает
#define FLAG_FOOD                       0  // Примет ли пищу от ГГ: 0 - принимает, 1 - не принимает

//---------------------

procedure start;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure critter_p_proc;
procedure use_obj_on_p_proc;
procedure use_skill_on_p_proc;
procedure pickup_p_proc;
procedure combat_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure sanfelipe_finish_msg;

//---------------------

variable tileNumRun;



procedure start begin
end

procedure map_enter_p_proc begin
   if (is_loading_game == false) then begin
       set_start_home
       if (map_first_run == true) then begin
          if (cur_map_index == MAP_SAN_FELIPE_COAST) then begin
          inc_map_var(MVAR_FELIPE_MONSTR_COAST_AMNT);
          end
          if (cur_map_index == MAP_SAN_FELIPE_CAVE) then begin
          inc_map_var(MVAR_FELIPE_MONSTR_CAVE_AMNT);
          end
       end

       if (cur_map_index == MAP_SAN_FELIPE_CITY) then begin
          set_obj_visibility(self_obj, 1);
          if (getQuest(GVAR_SANFELIPE_QST_RUN) >= qEnd) then begin
          set_obj_visibility(self_obj, 0);
          end
       end
   end
end

procedure timed_event_p_proc begin
   // Таймер за номером 1 рарезервирован под перемещение персонажа по локации
   // Таймер за номером 2 рарезервирован под всплывающие реплики
   if (fixed_param == 1) then begin
       timer_move_random
   end
   if (fixed_param == 2) then begin
       //timer_float_reply(120,121)
   end
end

procedure critter_p_proc begin
   set_critter_options(2,0) //условие нападения (0 личная вражда, 1 вражда клановая, 2 всегда), разворот к ГГ

   //--- покидают карту после розжига костров
   if (cur_map_index == MAP_SAN_FELIPE_COAST) then begin
      if (map_var(MVAR_FELIPE_MONSTR_COAST_FIRE) >= 3) then begin
      if (combat_is_initialized == false) then begin

          if (tile_distance(self_tile,14932) < tile_distance(self_tile,20891)) then begin
          tileNumRun := 14932; // запад
          end else begin
          tileNumRun := 20891; // восток
          end

          if (tile_distance(self_tile,tileNumRun) < 2) then begin
          set_obj_visibility(self_obj, 1);
          inc_global_var(GVAR_SANFELIPE_STATUS_MONSTRCOAST);
          display_mstr(111);
          destroy_object(self_obj);
          end
          else begin
          move_to_tile(1,tileNumRun,0)
          end
      end
      end
   end
end

procedure use_skill_on_p_proc begin
   skillUseSteal
   skillUseFAid
end

procedure pickup_p_proc begin
   pickupProcCritter
end

procedure use_obj_on_p_proc begin
   UsedItemToCrit_Proc
end

procedure combat_p_proc begin
   effectAttak(3,0,0,0,1) //отравление min, облучение min, травма ног %, травма рук %, травма глаз %
   effectIntimidationPerk
end

procedure damage_p_proc begin
   set_damage_dude
end

procedure destroy_p_proc begin
   if (cur_map_index == MAP_SAN_FELIPE_COAST) then begin
      inc_global_var(GVAR_SANFELIPE_STATUS_MONSTRCOAST);
      if (global_var(GVAR_SANFELIPE_STATUS_MONSTRCOAST)>=map_var(MVAR_FELIPE_MONSTR_COAST_AMNT)) then begin
      call sanfelipe_finish_msg;
      end
   end
   if (cur_map_index == MAP_SAN_FELIPE_CAVE) then begin
      inc_global_var(GVAR_SANFELIPE_STATUS_MONSTRCAVE);
      if (global_var(GVAR_SANFELIPE_STATUS_MONSTRCAVE)>=map_var(MVAR_FELIPE_MONSTR_CAVE_AMNT)) then begin
      call sanfelipe_finish_msg;
      end
   end
   kill_critter_opt
end

procedure sanfelipe_finish_msg begin
   play_sfx("ICSXXXX1");
   if (dude_iq>=4) then begin
   floater(dude_obj, 110, COLOR_MSG_GREEN);
   end
   else begin
   display_mstr(110);
   end
end
