#include "..\headers\define.h"
#include "..\headers\updatmap.h"
#define NAME                    SCRIPT_ZIPostA

procedure start;
procedure map_enter_p_proc;
procedure use_p_proc;
procedure use_skill_on_p_proc;

/*
   Это ящик для получения посылок из других городов.
   См подробности в скрипте ГГ, процедура express_box_proc.
*/



procedure start begin
end

procedure map_enter_p_proc begin
   if (is_loading_game == false) then begin
      if (map_first_run == true) then begin
      //obj_lock(self_obj);
      item_add(self_obj,PID_TEST,1)
      end
   end
end

procedure use_p_proc begin
   if (item_amnt(self_obj,PID_TEST) > 0) then begin
       if (cur_map_index == MAP_FLAGSTAFF_CITY) then begin
          if (gvar_bit(GVAR_EXPRESS_FLAGS_BIT,bit_7) != 0) then begin
          obj_unlock(self_obj);
          item_remove(self_obj,PID_TEST,999)
          end
       end
       if (cur_map_index == MAP_PHOENIX_CENTER) then begin
          if (gvar_bit(GVAR_EXPRESS_FLAGS_BIT,bit_8) != 0) then begin
          obj_unlock(self_obj);
          item_remove(self_obj,PID_TEST,999)
          end
       end
       if (cur_map_index == MAP_TWO_SUN_CITY) then begin
          if (gvar_bit(GVAR_EXPRESS_FLAGS_BIT,bit_9) != 0) then begin
          obj_unlock(self_obj);
          item_remove(self_obj,PID_TEST,999)
          end
       end
   end

   if (item_amnt(self_obj,PID_TEST) > 0) then begin
       script_overrides;

       reg_anim_begin();
       reg_anim_clear(self_obj);
       reg_anim_clear(source_obj);
       reg_anim_end();

       display_mstr(110);
   end
end

procedure use_skill_on_p_proc begin
   if (action_being_used == SKILL_LOCKPICK) then begin
      script_overrides;
      display_mstr(110);
   end
   if (action_being_used == SKILL_STEAL) then begin
      if (item_amnt(self_obj,PID_TEST) > 0) then begin
      script_overrides;
      display_mstr(110);
      end
   end
end

/*
procedure map_update_p_proc begin
   call box_inven_to;
end

procedure box_inven_to begin
   variable boxPID;
   boxPID := 0;

   //- Идентификация ящика
   if (cur_map_index == MAP_FLAGSTAFF_CITY) then begin
      boxPID := PID_CNTR_EXPRESSBOX_F;
   end
   if (cur_map_index == MAP_PHOENIX_CENTER) then begin
      boxPID := PID_CNTR_EXPRESSBOX_P;
   end
   if (cur_map_index == MAP_TWO_SUN_CITY) then begin
      boxPID := PID_CNTR_EXPRESSBOX_T;
   end

   //- Перенос лута
   if (boxPID > 0) then begin
      if (express_box_obj(boxPID) > 0) then begin
      move_obj_inven_to_obj(express_box_obj(boxPID), self_obj);
      end
   end
end
*/
