#include "..\headers\define.h"
#include "..\headers\REPAIR.h"
#define NAME                    SCRIPT_ZSTblUzi
#define SKILL_LIMIT                     75

procedure start;
procedure map_enter_p_proc;
procedure use_p_proc;
procedure use_skill_on_p_proc;
procedure use_obj_on_p_proc;
procedure repair_proc;



procedure start begin
end

procedure map_enter_p_proc begin
end

procedure use_p_proc begin
   script_overrides;
   if (local_var(LVAR_Status) > 0) then begin
      set_obj_visibility(self_obj, 1);
      if (cur_map_index == MAP_HERMO_CASA) then begin
      create_object_sid(33555382, self_tile, self_elevation, -1);
      item_add(dude_obj,PID_W_SMG_UZI,1)
      display_msg(proto_data(PID_W_SMG_UZI, it_name)+mstr(113));
      end
      else if (cur_map_index == MAP_SAN_FELIPE_CITY) then begin
      item_add(dude_obj,PID_W_FLAMER,1)
      display_msg(proto_data(PID_W_FLAMER, it_name)+mstr(113));
      end
      else begin
      item_add(dude_obj,PID_W_SMG_10,1)
      display_msg(proto_data(PID_W_SMG_10, it_name)+mstr(113));
      end
      destroy_object(self_obj);
   end
   else begin
      RepairProcUsing(110,111)
   end
end

procedure use_skill_on_p_proc begin
   RepairVarCheck
   RepairSkillRepair
end

procedure use_obj_on_p_proc begin
   stopUseCarGaz
   RepairUsedJunk(PID_TOOL_PARTS_MECHANICAL,20)
end

procedure repair_proc begin
   RepairProcRepair(112,0,"WRD1XXX1")
end
