#include "..\headers\define.h"
#define NAME                    SCRIPT_VICtzHom
#define AMMOPID                 PID_AMMO_SHOTGUN_SHELLS
#define WPNPID                  PID_W_SHOTGUN_DUBLET

procedure start;
procedure map_enter_p_proc;
procedure use_p_proc;
procedure timed_event_p_proc;
procedure use_skill_on_p_proc;

#define LVAR_ItemAmnt                     (0) // число патронов в сундуке



procedure start begin
end

procedure map_enter_p_proc begin
   if (is_loading_game == false) then begin
       if (map_first_run) then begin
       item_add(self_obj,AMMOPID,2)
       item_add(self_obj,WPNPID,1)
       end
       set_local_var(LVAR_ItemAmnt,item_amnt(self_obj, AMMOPID));
   end
end

procedure use_p_proc begin
   add_timer_event(self_obj, 2, 1);
end

procedure timed_event_p_proc begin
   if (fixed_param == 1) then begin
       if (item_amnt(self_obj, AMMOPID) < local_var(LVAR_ItemAmnt)) then begin
       set_gvar_bit_on(GVAR_DIALOGS_FLAGS_BIT, bit_2);
       end
       if (item_amnt(self_obj, WPNPID) < 1) then begin
       set_gvar_bit_on(GVAR_DIALOGS_FLAGS_BIT, bit_2);
       end
   end
end

procedure use_skill_on_p_proc begin
   if (action_being_used == SKILL_STEAL) then begin
       script_overrides;
   end
end
