#include "..\headers\define.h"
#define NAME                    SCRIPT_VSDstr

procedure start;
procedure map_enter_p_proc;
procedure use_obj_on_p_proc;



procedure start begin
end

procedure map_enter_p_proc begin
   if (is_loading_game == false) then begin
      if (getQuest(GVAR_MAIN_QUEST_FLAGSTAFF) >= qEnd) then begin
         set_obj_visibility(self_obj, 1);
         if (self_PID == 33555690) then begin
         create_object_sid(221, self_tile, self_elevation, -1);
         create_object_sid(PID_HEX_BLOCKING, self_tile, self_elevation, -1);
         destroy_object(self_obj);
         end
      end
   end
end

procedure use_obj_on_p_proc begin
   stopUseCarGaz
end
